### PR TITLE
BUG: fix syntax to work with older gcc

### LINKED ISSUE #14182: Unable to build numpy with GCC 4.8.5
I'm trying to install numpy from source but I'm seeing a lot of C99 errors.

### Reproducing code example:

```console
$ python -s setup.py --no-user-cfg build
$ python -s setup.py --no-user-cfg install --prefix=/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-numpy-1.17.0-37xrxjmnbitsruc7alrutzpvdil2xhhy --single-version-externally-managed --root=/
```

### Error message:

I see hundreds of errors like:
```
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_bool':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (npy_intp i = 1; i < num; i++) {
     ^
numpy/core/src/npysort/radixsort.c.src:112:5: note: use option -std=c99 or -std=gnu99 to compile your code
```

### Numpy/Python version information:

- Linux CentOS 7
- GCC 4.8.5
- Python 3.7.4
- Numpy 1.17.0

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Fixes #14182 

Just discovered the same in our CI and fixed it.

### CODE REVIEW

**Comment by charris** [comment]
We do require C99 support, which for older compilers requires a flag. How old a gcc are you talking about? The current source compiles with manylinux1, which is gcc 4.9 or some such.

**Comment by charris** [comment]
PS: I don't think that is the only place with local declarations in loops. IIRC that was the bit that needed the flag.

**Comment by oleksandr-pavlyk** [comment]
It was failing with gcc 4.8.5, the same as in the referenced issue, but we used older CentOS 6.

**Comment by oleksandr-pavlyk** [comment]
Ok, so what flag do I need, `--std=c99`?

**Comment by oleksandr-pavlyk** [comment]
Thanks for the information @charris, I will trying our CI with `--std=c99` and report back.

**Comment by charris** [comment]
Yes. See https://github.com/numpy/numpy/pull/12610#issuecomment-451709130 for the loop variable mention.

**Comment by charris** [comment]
@oleksandr-pavlyk Any luck with the flag?

**Comment by oleksandr-pavlyk** [comment]
Thanks for the ping @charris. Yes, the flag worked fine. Closing.

**Pull request closed without merging**
