### PR TITLE
MAINT: follow-up cleanup for blas64 PR

### PR DESCRIPTION
**Pull request by pv**
Follow-up cleanup for gh-15021 and gh-15012. Add missing release note, pick up (most) recommendations from missed review, and fix a stray debug print.

### CODE REVIEW

**Comment by charris** [comment]
The original is in 1.18.x as I wanted folks to have something to play with. Does this PR need a backport? I'll take the release note in any case.

**Comment by pv** [comment]
I think none of these are crucial to backport.

**Review by eric-wieser — APPROVED** [review]
Looks good, thanks.

**Comment by seberg** [comment]
Thanks, lets put it in.

**Pull request merged**
