### PR TITLE
DOC: fix docstring for floor_divide

### LINKED ISSUE #13215: Documentation mistake numpy.floor_divide
The [floor_divide docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.floor_divide.html) claim that 

> Return the largest integer smaller or equal to the division of the inputs. It is equivalent to the Python // operator and pairs with the Python % (remainder), function so that b = a % b + b * (a // b) up to roundoff.

However, the mathematical expression is equal to a, not equal to b.

### Reproducing code example:

```
a=9; b=2; a % b + b * (a // b)  == a
True
```

### Numpy/Python version information:

Numpy docs V1.16.1

### PR DESCRIPTION
**Pull request by ay11111111111**
Corrected the mistake in the docstring for floor_divide: change 'b' to 'a'.
However, my IDE has also deleted the unnecessary spaces. Is it ok, or should I delete it?

### CODE REVIEW

**Comment by mattip** [comment]
Removing a few trailing spaces is fine.

Fixes #13215

**Comment by mattip** [comment]
Thanks @yesass

**Comment by yesass** [comment]
@mattip what should I write in "Outreachy internship project timeline:" field?
I am sorry for offtopic and late application

**Comment by mattip** [comment]
Please reach out privately via the outreachy mentor mail you should have recieved

**Pull request merged**
