### PR TITLE
BUG: Fix sorting of int8/int16

### LINKED ISSUE #20567: BUG: `np.sort(..., kind="stable")` for some `int8`/`int16` arrays is incorrect
### Describe the issue:

Some arrays of 8 and 16 width ints don't sort correct when stable sort specified. Can't quite identify the pattern, but it seems like unordered inputs containing a mix of positive and negative elements can trigger it.

This also affects `array_api.sort`, which uses stable sort by default so this gets annoying fast heh. cc @asmeurer 

### Reproduce the code example:

```python
>>> np.sort(np.asarray([0, -1], dtype=np.int8), kind="stable")
array([ 0, -1], dtype=int8)      # should be [-1, 0]
...
# different dtypes
>>> np.sort(np.asarray([0, -1], dtype=np.int16), kind="stable")
array([ 0, -1], dtype=int8)      # int16 also incorrect
>>> np.sort(np.asarray([0, -1], dtype=np.int32), kind="stable")
array([-1,  0], dtype=int32)     # int32 and int64 seem to work fine
...
# related examples
>>> np.sort(np.asarray([-1, 0], dtype=np.int8), kind="stable")
array([-1,  0], dtype=int8)
>>> np.sort(np.asarray([-1, -2], dtype=np.int8), kind="stable")
array([-2, -1], dtype=int8)
>>> np.sort(np.asarray([10, -10], dtype=np.int8), kind="stable")
array([ 10, -10], dtype=int8)    # incorrect
>>> np.sort(np.asarray([1, 0], dtype=np.int8), kind="stable")
array([0, 1], dtype=int8)
>>> np.sort(np.asarray([0, -1, -2], dtype=np.int8), kind="stable")
array([-2, -1,  0], dtype=int8)
>>> np.sort(np.asarray([0, -2, -1], dtype=np.int8), kind="stable")
array([ 0, -2, -1], dtype=int8)  # incorrect
```

### Error message:

_No response_

### NumPy/Python version information:

1.23.0.dev0+144.g4d6e41879 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]

### PR DESCRIPTION
**Pull request by serge-sans-paille**
radix sort operates on unsigned types, but the key extractor needs to know the
original type.

Fix #20567

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Currently just adding the failing test case

**Comment by serge-sans-paille** [comment]
+fix

**Comment by charris** [comment]
Looks right, the key was to convert two's complement to offset binary for the keys and sort as unsigned, which was a subtle bit of the original template. I wonder if `KEY_OF` could be specialized into float and integer types as we don't use radix sort for floats. Does the compiler takes care of that and inline the result?

**Comment by charris** [comment]
Thanks @serge-sans-paille .

**Pull request merged**
