### PR TITLE
BUG: cast missing in PyPy-specific f2py code, pin spin in CI

### PR DESCRIPTION
**Pull request by mattip**
Discovered when building SciPy with GCC14, which is more strict about casting. See pypy/pypy#4969.

### CODE REVIEW

**Comment by mattip** [comment]
@mgorny could you confirm this fixes the problem from your tests?

**Comment by mattip** [comment]
I added another commit to fix CI on windows by using the `build_requirements.txt` requirements file instead of installing a random version of spin.

**Comment by mgorny** [comment]
> @mgorny could you confirm this fixes the problem from your tests?

Yeah, with this applied, SciPy seems to build fine afterwards. Thanks!

**Comment by seberg** [comment]
LGTM, and fixes the windows spin issue, thanks.

**Pull request merged**
