### PR TITLE
ENH: Use AVX-512 for np.frexp and np.ldexp

### PR DESCRIPTION
**Pull request by r-devulap**
AVX-512 native instructions `vgetmant, vgetexp and vscalef` directly map to `np.frexp` and `np.ldexp ` and speed it up by nearly **6x** and **16x** respectively for floats and doubles. This PR includes commits from the other PR #16334, I will rebase if and when that's merged. 

- Code is enabled through runtime detection.
- Code bloat: 24701096 Bytes to 24900224 Bytes --> 194Kb (This includes all the ufunc's from PR https://github.com/numpy/numpy/pull/16334 as well). 
- Benchmarks: 

```
   before           after         ratio                                         
[9b06bd25]       [84bac12f]                                                     
<test-ufunc-avx>       <ldexp-frexp-avx>                                        
29.5±0.02ms       8.50±0.3ms     0.29  bench_avx.AVX_UFunc.time_ufunc('frexp', 4, 'd')
29.5±0.02ms      6.91±0.03ms     0.23  bench_avx.AVX_UFunc.time_ufunc('frexp', 2, 'd')
29.4±0.02ms       6.10±0.2ms     0.21  bench_avx.AVX_UFunc.time_ufunc('frexp', 1, 'd')
26.4±0.02ms       5.46±0.5ms     0.21  bench_avx.AVX_UFunc.time_ufunc('frexp', 4, 'f')
26.4±0.05ms      4.96±0.04ms     0.19  bench_avx.AVX_UFunc.time_ufunc('frexp', 2, 'f')
26.3±0.03ms       4.34±0.6ms     0.17  bench_avx.AVX_UFunc.time_ufunc('frexp', 1, 'f')
51.9±0.1ms       8.94±0.2ms      0.17  bench_avx.AVX_ldexp.time_ufunc('d', 4)   
50.7±0.01ms      8.09±0.08ms     0.16  bench_avx.AVX_ldexp.time_ufunc('f', 4)   
51.8±0.03ms      7.88±0.07ms     0.15  bench_avx.AVX_ldexp.time_ufunc('d', 2)   
50.7±0.01ms      7.40±0.07ms     0.15  bench_avx.AVX_ldexp.time_ufunc('f', 2)   
51.3±0.02ms       3.72±0.1ms     0.07  bench_avx.AVX_ldexp.time_ufunc('d', 1)   
50.2±0.02ms      2.78±0.03ms     0.06  bench_avx.AVX_ldexp.time_ufunc('f', 1) 
```

### CODE REVIEW

**Comment by r-devulap** [comment]
Seems like the output of `np.frexp` differ on windows and linux. Is this expected? The test I have added expects the result to match the linux output and hence fails on windows. 

Output of:
 ```
arr = np.array([np.nan, -np.nan, np.inf, -np.inf, 0.0, -0.0])
print(np.frexp(arr))
```
On windows: `array([ nan,  nan,  inf, -inf,   0.,  -0.]), array([-1, -1, -1, -1,  0,  0], dtype=int32)`

On Linux: `array([ nan,  nan,  inf, -inf,   0.,  -0.]), array([0, 0, 0, 0, 0, 0], dtype=int32)`

**Comment by seiko2plus** [comment]
@r-devulap, MSVC compiler doesn't support `__attribute__((target))`, also msvc tends to use a soft version of libmath instead of using `SSE*` if the loop not clarified as contiguous, see 
https://github.com/numpy/numpy/pull/16247/commits/f1759d6dbb696cd7bd96c390cff1a3912f8e110c#diff-9e63df11befcb00a2a969465358b2dd8R50-R64

**Comment by r-devulap** [comment]
@seiko2plus I should have been clear: `np.frexp` seems to give different answers on windows and linux even prior to this patch.

**Comment by seiko2plus** [comment]
@r-devulap, I'm sorry I don't understand, if the issue about the sign of NaN  then np.frexp looks fine to me,
```Python
>>> np.copysign(1, np.frexp(-np.nan)[0])
-1.0
>>> np.copysign(1, np.frexp(np.nan)[0])
1.0
````
I use `np.copysign` since python doesn't respect the sign of NaN during string convertion, I guess  you already know that.
In light of the above, my previous answer was about exp value since it should be unspecified, the soft version frexp of msvc returns -1 rather than zero.

**Comment by r-devulap** [comment]
> I guess the soft version of frexp in msvc returns -1 rather than zero.

Yes. I am merely pointing out this fact.

**Comment by mattip** [comment]
Is it worth thinking about an avx2 variant or would that be too complicated for too little gain?

**Comment by r-devulap** [comment]
@mattip I am sure these can be implemented in AVX2 as well, but it lacks kmasks and these dedicated instructions which makes programming really simple. Writing this in AVX2 would be a lot more work and would also need thorough validation.

**Comment by mattip** [comment]
gh-16334 is merged. Please rebase at your convenience.

**Comment by r-devulap** [comment]
@mattip: rebased.

**Comment by mattip** [comment]
CI failure unrelated. Thanks @r-devulap

**Pull request merged**
