### PR TITLE
CI: only run cirrus on commit to PR [skip actions]

### PR DESCRIPTION
**Pull request by andyfaff**
This PR reduces cirrus ci usage by only allowing commit to PRs to start general CI. Merge commits won't trigger a run.

### CODE REVIEW

**Comment by mattip** [comment]
Looks good.

I also like the idea of adding a "smoke test" x86_64 linux test run before running the more expensive macos_arm64 test. Do you think that would be a lot of work? Could it be done here or should it be a separate PR?

**Comment by andyfaff** [comment]
I would run a smoke linux_aarch64 test rather than a linux_x86_64. It shouldn't be too hard. I'd rather do it in a different PR.

**Comment by mattip** [comment]
Let's give this a shot then

**Comment by mattip** [comment]
Thanks @andyfaff

**Pull request merged**
