### PR TITLE
BENCH: Add basic benchmarks for numpy.pad

### PR DESCRIPTION
**Pull request by lagru**
Provides basic benchmarks for a few representative (?) modes in `numpy.pad`. Please, don't hesitate to suggest any modifications to the benchmarks scenarios (content of `Pad.params`).

Related #11126

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Looks fine to me

**Comment by eric-wieser** [comment]
Build failures are pretty alarming, but clearly unrelated (https://ci.appveyor.com/project/charris/numpy/build/1.0.10313)

**Comment by eric-wieser** [comment]
Thanks @lagru - these should turn up on https://pv.github.io/numpy-bench/ in the next day or so

**Comment by lagru** [comment]
Thanks, I'll keep an eye on it.

**Comment by eric-wieser** [comment]
Nope, works fine for me at https://pv.github.io/numpy-bench/#bench_lib.Pad.time_pad?

Perhaps a rogue ad-blocker / firewall, or maybe just javascript is disabled?

**Comment by lagru** [comment]
It was indeed an adblocker that was still interfering even when it was disabled. It's working now, thanks!

**Pull request merged**
