### PR TITLE
BUG: Complex printing tests fail on Windows ARM64

### PR DESCRIPTION
**Pull request by SlobodanMiletic**
Fixes issue #25626

### CODE REVIEW

**Review by mattip — APPROVED** [review]
Makes sense to me. @lysnikolaou, as our resident complex number code expert, does this ring a bell?

**Comment by seberg** [comment]
Let's put it in, looks good and we already have tests (although not running in CI).  Thanks.

**Comment by ilayn** [comment]
The the strict aliasing flags don't seem to like the fix here

```bash
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\include/numpy/npy_math.h: In function 'npy_longdouble npy_creall(npy_clongdouble)':
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\include/numpy/npy_math.h:422:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  422 |     return ((longdouble_t *) &z)[0];
      |            ~^~~~~~~~~~~~~~~~~~~~
[838/1470] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cp312-win_amd64.pyd.p/other.cxx.obj
In file included from ../scipy/sparse/sparsetools/complex_ops.h:9,
                 from ../scipy/sparse/sparsetools/sparsetools.h:10,
                 from ../scipy/sparse/sparsetools/other.cxx:4:
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\include/numpy/npy_math.h: In function 'npy_longdouble npy_creall(npy_clongdouble)':
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\include/numpy/npy_math.h:422:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  422 |     return ((longdouble_t *) &z)[0];
      |            ~^~~~~~~~~~~~~~~~~~~~
[839/1470] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cp312-win_amd64.pyd.p/sparsetools.cxx.obj
In file included from ../scipy/sparse/sparsetools/complex_ops.h:9,
                 from ../scipy/sparse/sparsetools/sparsetools.h:10,
                 from ../scipy/sparse/sparsetools/sparsetools.cxx:36:
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\include/numpy/npy_math.h: In function 'npy_longdouble npy_creall(npy_clongdouble)':
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\include/numpy/npy_math.h:422:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  422 |     return ((longdouble_t *) &z)[0];
      |            ~^~~~~~~~~~~~~~~~~~~~
[843/1470] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cp312-win_amd64.pyd.p/csc.cxx.obj
In file included from ../scipy/sparse/sparsetools/complex_ops.h:9,
                 from ../scipy/sparse/sparsetools/sparsetools.h:10,
                 from ../scipy/sparse/sparsetools/csc.cxx:4:
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\include/numpy/npy_math.h: In function 'npy_longdouble npy_creall(npy_clongdouble)':
..\..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\include/numpy/npy_math.h:422:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  422 |     return ((longdouble_t *) &z)[0];
```

on SciPy builds. Can we consider a different way to get the complex element without resorting to a array pointer conversion?

**Comment by ilayn** [comment]
Well I'm mistaken to blame this PR, it is the untouched branch that is causing it. Apologies for the noise.

**Pull request merged**
