### PR TITLE
DOC: include NEP number on each NEP page

### PR DESCRIPTION
**Pull request by shoyer**
Currently, if you include a NEP number in the title of a NEP, it gets rendered twice in the index.

This is just a minor annoyance I noticed while writing a few NEPs recently.

### CODE REVIEW

**Comment by charris** [comment]
So the solution here is to always put the NEP number in the title and avoid the other reference?

**Comment by shoyer** [comment]
The other way to do this would be to generate the rst page for the NEPs
dynamically, but this seemed simpler.

**Comment by shoyer** [comment]
@stefanv any thoughts here? If I recall correctly you wrote this script originally?

**Comment by stefanv** [comment]
When I wrote the script, none of the NEPs had a number in the title, and it was only encoded in the filename.  It would probably make sense to have these in the actual document as well.

This requires no change other than to modify `doc/neps/index.rst.tmpl` (and also modifying each NEP document to have `NEP xyz — <title>` as its title.

**Comment by stefanv** [comment]
EDIT: Which I see is exactly what this PR does.

**Review by stefanv — APPROVED** [review]

**Comment by charris** [comment]
Thanks Stephan.

**Pull request merged**
