### PR TITLE
DEP: Deprecate arrayprint formatting functions

### PR DESCRIPTION
**Pull request by kritisingh1**
Related to #11521

### CODE REVIEW

**Comment by mattip** [comment]
@kritisingh1 this needs a release note in `doc/release/upcoming_changes`

**Comment by kritisingh1** [comment]
@mattip In `doc/release/..` or in `changelog/14259.deprecation.rst` ?

**Comment by seberg** [comment]
@kritisingh1 I moved it to `/doc/release/upcoming_changes/`, so that is the correct spot now. You may need to rebase on master to see that the folder exists (although I guess just creating that folder will merge work).

**Comment by mattip** [comment]
Thanks @kritisingh1

**Pull request merged**
