### PR TITLE
ENH: Compiler fixes for Cartesi Machine

### PR DESCRIPTION
**Pull request by juztamau5**
## Description

This PR contains an assortment of C++ fixes I applied in order to cross-compile numpy for the Cartesi Machine (https://github.com/Cartesi). The Cartesi Machine is a RISC-V rv64ima environment with a GCC 10 toolchain.

The PR is organized as a list of commits that address individual compiler errors. Error messages from the compiler are included in the commit descriptions. Fixes are independent, so if any fixes aren't desired they can be dropped from the PR.

The toolchain brings stronger C++ enforcement, so the following are no longer allowed:

* Use of reserved words for variable names
* Designator order not matching declaration order
* Jumping to a label across an initialization (this one can probably be solved more gracefully)
* Some operations for enum types
* Calling libdivide functions outside their namespace
* Mismatching argument types for `isless()`
* Use of some functions outside of the `std` namespace when both C and C++ headers are included
* Defining a struct inside `offsetof()`
* Redefining static variables
* Taking an address of a temporary array

In addition, taking an address of a temporary array is a potential bug in the code.

## How has this been tested?

The commands I used to cross-compile numpy were:

```bash
python3 -m crossenv /mnt/python-dapp/bin/python3 .env
. .env/bin/activate

export CC=riscv64-cartesi-linux-gnu-g++
export CPPFLAGS=" \
  -I/opt/riscv/rootfs/buildroot/work/staging/usr/include \
  -fpermissive \
  -Wno-literal-suffix \
  -Wno-write-strings \
  -Wno-sign-compare \
  -Wno-narrowing \
"
export LDFLAGS="-L/opt/riscv/rootfs/buildroot/work/staging/usr/lib"
pip install git+https://github.com/juztamau5/numpy.git@fixes#egg=numpy
```

With these changes, cross-compiling numpy for the Cartesi Machine succeeds and numpy is built into the filesystem image. I'm currently working on runtime testing. Let me know if there are specific code paths I should test.

### CODE REVIEW

**Comment by seberg** [comment]
A lot of these changes seem like using a C++ compiler to compile C code and CI fails because of that?  (Many of them do look like good cleanups.)

Maybe you should be using `export CC=riscv64-cartesi-linux-gnu-gcc` or so, rather than `g++` (yes, NumPy also has C++ code, but most of it is not C++)?

**Comment by charris** [comment]
I am not opposed to making NumPy code more C++ compatible, but would break it up into small steps and several PRs, i.e., rename variables with reserved names ("new" is a common example), and other such harmless things. After all, NumPy is written for C99.

**Comment by juztamau5** [comment]
@seberg Thanks for pointing out that I should be using gcc instead of g++ to compile numpy. I'm still getting the hang of the Cartesi build system. Using gcc I can build and run numpy without any of the fixes in this PR. However, there is still some value in some of the fixes, so I'll break the ones we could keep into separate PRs.

**Comment by charris** [comment]
I'm going to close this PR. @juztamau5 We appreciate the effort and look forward to some cleanups.

**Pull request closed without merging**
