### PR TITLE
BUG: Ensure non-array logspace base does not influence dtype of output.

### LINKED ISSUE #24957: BUG: incorrect promotion of scalars in logspace
gh-23275 added broadcasting before the promotion happened, which is incorrect for 0-D objects as they may have special promotion rules (value-based or Python int/float/complex being special).

First reported at https://github.com/cupy/cupy/issues/7946

Ping @byrdie since it was your PR.

### PR DESCRIPTION
**Pull request by mhvk**
Fixes gh-24957

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @mhvk!

The CircleCI failure is related:
```
numpy.logspace
--------------

File "venv/lib/python3.11/site-packages/numpy/__init__.py", line ?, in logspace
Failed example:
    np.logspace(2.0, 3.0, num=4, base=[2.0, 3.0], axis=-1)
Exception raised:
    Traceback (most recent call last):
      File "/home/circleci/.pyenv/versions/3.11.4/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest logspace[5]>", line 1, in <module>
        np.logspace(2.0, 3.0, num=4, base=[2.0, 3.0], axis=-1)
      File "/home/circleci/repo/venv/lib/python3.11/site-packages/numpy/_core/function_base.py", line 312, in logspace
        return _nx.power(base, y)
               ^^^^^^^^^^^^^^^^^^
    ValueError: operands could not be broadcast together with shapes (2,) (4,)
```

**Comment by mhvk** [comment]
OK, hopefully fixed now...

**Comment by mhvk** [comment]
The freebsd failure is unrelated, so this should be all OK now.

**Review by rgommers — APPROVED** [review]
LGTM, thanks for the fix @mhvk!

**Comment by seberg** [comment]
Thanks, it's not actually quite right, because we are not dealing with the other arguments being scalars.  But at least it fixes the bigger problem.

**Comment by seberg** [comment]
Yeah, array-converter should help a bit, but it simply is tedious.  The reason is that `base` can be the only array in which case you need to broadcast the linspace result manually.

**Pull request merged**
