### PR TITLE
ENH: Add copy and device keyword to np.asanyarray to match np.asarray

### PR DESCRIPTION
**Pull request by JuliaPoo**
See #26196

### CODE REVIEW

**Comment by ngoldbaum** [comment]
This needs a release note. It should be versionadded for 2.1 since I don't think it's an emergency to backport this for 2.0. Also needs new tests.

**Comment by JuliaPoo** [comment]
I've added a release note as per suggested. Is there a way to flag this change for 2.1 in the release note? As for the tests, the underlying implementation for  `np.asanyarray` (`_array_fromobject_generic`) is already tested by tests surrounding `np.array`, is there still a need to write tests? If so should I also add tests for `np.asarray`?

**Comment by rgommers** [comment]
> Is there a way to flag this change for 2.1 in the release note?

That is automatic in the release notes; the tooling knows how to assemble the release notes for the next version from these snippets.

And you already used `.. versionadded::` correctly in the docs (except there adding the correct version number manually is needed, and it should be 2.1.0 rather than 2.0.0).

> As for the tests, the underlying implementation for `np.asanyarray` (`_array_fromobject_generic`) is already covered by tests surrounding `np.array`, is there still a need to write tests? If so should I also add tests for `np.asarray`?

Yes, this will be useful. Any public API construct should have at least a single direct test even when the underlying machinery is tested extensively in some other way. Probably `TestDevice` in `_core/tests/test_multiarray.py` is the place to put this. And yes, doing that for `np.asarray` too would be nice, good catch.

**Comment by JuliaPoo** [comment]
> And you already used .. versionadded:: correctly in the docs (except there adding the correct version number manually is needed, and it should be 2.1.0 rather than 2.0.0).

Oh my bad, I completely forgot I did that, I've made the changes.

If the only new tests to add are related to the `device` keyword, then I'm not sure what tests to add since all methods discard the `device` keyword, and `arr.device` calls the following stub:

```c
static PyObject *
array_device(PyArrayObject *self, void *NPY_UNUSED(ignored))
{
    return PyUnicode_FromString("cpu");
}
```

**Comment by rgommers** [comment]
I think you only test that `np.asanyarray(...)`, `np.asanyarray(..., device=None)` and `np.asanyarray(..., device='cpu')` all work and yield the same result - that ensures that usage of the keyword functions as expected. And that `np.asanyarray(..., device='nonsense')` raises an understandable exception.

**Comment by JuliaPoo** [comment]
Okay, I've added new tests

**Review by mattip — COMMENTED** [review]
LGTM. One typo and an optional vertical spacing suggestion

**Comment by JuliaPoo** [comment]
Yea I think adding one more newline looks nicer too, Ive commited the suggestions

**Comment by mattip** [comment]
Thanks @JuliaPoo

**Pull request merged**
