### PR TITLE
TST: add test for 'python -mnumpy.f2py'

### PR DESCRIPTION
**Pull request by mattip**
Add a test that fails before, passes after #12577 on Linux

Edit: qualify "passes" with Linux

### CODE REVIEW

**Comment by charris** [comment]
Should also work on Windows, why the Linux qualification?

**Comment by charris** [comment]
Thanks Matti.

**Comment by eric-wieser** [comment]
Doesn't work for me on windows, but I'm pretty used to the f2py tests failing at this point

**Comment by mattip** [comment]
What is the error message? It passes on CI

**Comment by eric-wieser** [comment]
```python
_________________________________ test_pep338 _________________________________

    def test_pep338():
        f2py_cmd = [sys.executable, '-mnumpy.f2py', '-v']
>       code, stdout, stderr = run_command(f2py_cmd)

f2py_cmd   = ['C:\\Program Files\\Python 3.5\\python.exe', '-mnumpy.f2py', '-v']

numpy\tests\test_scripts.py:103:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
numpy\tests\test_scripts.py:50: in run_command
    proc = Popen(cmd, stdout=PIPE, stderr=PIPE)
C:\Program Files\Python 3.5\lib\subprocess.py:676: in __init__
    restore_signals, start_new_session)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <subprocess.Popen object at 0x0000020A06AE35F8>
args = '"\\"C:\\Program Files\\Python 3.5\\python.exe\\"" -mnumpy.f2py -v'
executable = None, preexec_fn = None, close_fds = False, pass_fds = ()
cwd = None, env = None
startupinfo = <subprocess.STARTUPINFO object at 0x0000020A06AE3438>
creationflags = 0, shell = False, p2cread = Handle(896), p2cwrite = -1
c2pread = 8, c2pwrite = Handle(908), errread = 10, errwrite = Handle(916)
unused_restore_signals = True, unused_start_new_session = False

    def _execute_child(self, args, executable, preexec_fn, close_fds,
                       pass_fds, cwd, env,
                       startupinfo, creationflags, shell,
                       p2cread, p2cwrite,
                       c2pread, c2pwrite,
                       errread, errwrite,
                       unused_restore_signals, unused_start_new_session):
        """Execute program (MS Windows version)"""

        assert not pass_fds, "pass_fds not supported on Windows."

        if not isinstance(args, str):
            args = list2cmdline(args)

        # Process startup details
        if startupinfo is None:
            startupinfo = STARTUPINFO()
        if -1 not in (p2cread, c2pwrite, errwrite):
            startupinfo.dwFlags |= _winapi.STARTF_USESTDHANDLES
            startupinfo.hStdInput = p2cread
            startupinfo.hStdOutput = c2pwrite
            startupinfo.hStdError = errwrite

        if shell:
            startupinfo.dwFlags |= _winapi.STARTF_USESHOWWINDOW
            startupinfo.wShowWindow = _winapi.SW_HIDE
            comspec = os.environ.get("COMSPEC", "cmd.exe")
            args = '{} /c "{}"'.format (comspec, args)

        # Start the process
        try:
            hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                                     # no special security
                                     None, None,
                                     int(not close_fds),
                                     creationflags,
                                     env,
                                     cwd,
>                                    startupinfo)
E                                    PermissionError: [WinError 5] Access is denied

args       = '"\\"C:\\Program Files\\Python 3.5\\python.exe\\"" -mnumpy.f2py -v'
c2pread    = 8
c2pwrite   = Handle(908)
close_fds  = False
creationflags = 0
cwd        = None
env        = None
errread    = 10
errwrite   = Handle(916)
executable = None
p2cread    = Handle(896)
p2cwrite   = -1
pass_fds   = ()
preexec_fn = None
self       = <subprocess.Popen object at 0x0000020A06AE35F8>
shell      = False
startupinfo = <subprocess.STARTUPINFO object at 0x0000020A06AE3438>
unused_restore_signals = True
unused_start_new_session = False

C:\Program Files\Python 3.5\lib\subprocess.py:957: PermissionError
```

**Pull request merged**
