### PR TITLE
DOC: Improve `rec.array` function documentation (#15853)

### PR DESCRIPTION
**Pull request by tohabyuraev**
Adding full function documention with parameters and examples to `numpy/core/records.py`.

### CODE REVIEW

**Review by rossbar — CHANGES_REQUESTED** [review]
Thanks for taking a look at this! This function is a bit tricky as it's a combination of the other `records.from*` functions. Because of this, extra attention should be paid to the parameters, perhaps calling out which parameters are valid for which kinds of input. Also, since `records.array` accepts many different kinds of input, I would vote for an expanded example section that has at least one of each of the different types of input `obj`. The good news is, you should be able to draw directly from the examples in the other docstrings.

**Comment by tohabyuraev** [comment]
@rossbar Thanks for the code review! I will add some changes. Can i 'commit suggestion' yet?

**Comment by rossbar** [comment]
> Can i 'commit suggestion' yet? Or i need to add these suggestions in one big commit?

Good question :) - You don't have to worry about combining everything in one commit yourself, the maintainers can handle it at merge time. The 'commit suggestion' button is fine for any suggestions you want to accept verbatim.

**Comment by charris** [comment]
Close/reopen.

**Comment by rossbar** [comment]
Hey @tohabyuraev , just a quick ping to see if you're still working on this PR - it looks like almost everything has been addressed from the first round of reviews. If you end up completing the changes, feel free to ping back when you think it's ready for another.

**Comment by tohabyuraev** [comment]
Hello @rossbar . I almost fixed everything. But there is a question on the first point. I don't know how to correctly anf briefly write about the input object. Can you advise?

**Comment by rossbar** [comment]
That's understandable - AFAIK there is no required format for listing multiple types in the parameter description, so I think chaining together the valid types is reasonable, e.g.

```
obj: array_like or buffer_like or file_like
```

Though not generally used in the NumPy docstrings, in this case there are so many possible types for the `obj` parameter that it might make sense to use type-hinting syntax, e.g. `Union[array_like, file_like, ...]`. You can always try and see what feedback you get!

You should double check within the function itself to see what types of objects are accepted so that the list is complete.

**Comment by rossbar** [comment]
@tohabyuraev I took the liberty of updating the docstring with a suggestion for how to get around the thorny issue of the `obj` type parameter listing. My approach was to port the wording from the [Guide to NumPy (pg. 146)](https://web.mit.edu/dvp/Public/numpybook.pdf) to a `Notes` section that explains how the various input types are treated, rather than worrying about trying to include them all in the `Parameters` listing.

LMK what you think. Also ping @teresafds to see if there are any components from #16449 that you'd like to include here.

**Comment by tohabyuraev** [comment]
@rossbar Yes, really everything is clear. And notes will be really helpful.

This book is something new. I did not know what it is before. There are so many pages!

**Comment by rossbar** [comment]
> This book is something new. I did not know what it is before. There are so many pages!

The book is actually quite old - I believe this edition is from 2006! Some of the information is dated, but it does present a really nice, wholistic picture of the concepts behind the various components of the library.

**Comment by rossbar** [comment]
@tohabyuraev it looks like you undid the changes in 16e80cc with the latest merge/force-push

**Comment by tohabyuraev** [comment]
@rossbar Sorry. I thought this commit was added. How to add it over the previous commit now? Do revert?

**Comment by rossbar** [comment]
Okay - I *think* I've fixed it in a way that preserves the commit history. Please fetch from `array-func-doc-1` from your fork and verify that everything looks as you expect.

**Review by rossbar — APPROVED** [review]

**Comment by rossbar** [comment]
How does this look to you @tohabyuraev ? Thanks for the additional examples - I think there's enough there for now. Unless you were planning on adding more, I think this is just about ready.

**Comment by tohabyuraev** [comment]
Thanks for the help and tips @rossbar . The examples I added were from #16449 . Everything seems to be there.
So, I realized that I need to better deal with the GitHub interface and git in particular)

**Comment by rossbar** [comment]
No worries, thanks for the persistence! We'll see if any other reviewers have comments but if not I think we can put it in soon.

**Comment by rossbar** [comment]
I'm going to go ahead and put this in. Thanks @tohabyuraev !

**Comment by tohabyuraev** [comment]
Thank you, @rossbar !

**Pull request merged**
