### PR TITLE
DEP: Raise warnings for deprecated functions PyArray_As1D, PyArray_As2D

### PR DESCRIPTION
**Pull request by kritisingh1**
Related to #11521

### CODE REVIEW

**Comment by mattip** [comment]
Unfortunately we really cannot remove these from `numpy/core/code_generators/numpy_api.py` until we release a Numpy2 (which may never happen) as it breaks backward compatibility. We can only raise an exception in the C code if the functions are called.

**Comment by kritisingh1** [comment]
My bad, @mattip how do we deal with raising exceptions in C side of functions, any previous PR or example?

**Comment by mattip** [comment]
The return value will be different from each function, and in the general case there may be cleanup to be done (not in this simple case). Since there is no `DeprecationError` I propose raising a `NotImplementedError` like this:

```
PyErr_SetString(PyExc_NotImplementedError, msg);
return <errorval>;
```

**Comment by kritisingh1** [comment]
I'm not sure how to go ahead with this since the travis builds are failing due to reasons jargon to me. Based on a discussion with @seberg recently, builds are failing due to presence of unused lines of code in the functions being deprecated. A possible solution is to just set the error message and return -1, and omit all other lines in the body of function. Should I try this?

**Comment by seberg** [comment]
OK, lets put this in now that the tests pass. thanks Kriti.

**Pull request merged**
