### PR TITLE
 Import directory debugged and readdressed

### PR DESCRIPTION
**Pull request by debarun1234**
Screenshot 2021-08-19 092333
Picking from #15986  have fixed the import error came to line 40 to 44 of the file

### CODE REVIEW

**Comment by mattip** [comment]
What import error? That issue is about chaining exceptions, which is something different.

**Comment by rkern** [comment]
I'm sorry, I'm not seeing the bug described in the referenced issue, which is about exception-chaining, not imports. The existing code is generally the style that we use for within-subpackage imports like these. Is there a specific bug fixed by the fully-qualified imports? If not, then we would prefer the existing code.

**Comment by debarun1234** [comment]
> I'm sorry, I'm not seeing the bug described in the referenced issue, which is about exception-chaining, not imports. The existing code is generally the style that we use for within-subpackage imports like these. Is there a specific bug fixed by the fully-qualified imports? If not, then we would prefer the existing code.

when i ran the records.py as it in in my git there was not able to fetch from parent instance error line 40 in the code after fixing the line 40, 43,44. It ran perfectly

**Comment by mattip** [comment]
You are not meant to run `python numpy/core/records.py`, it is a module within a package, and is imported as part of `python -c "import numpy"`.

**Pull request closed without merging**
