### PR TITLE
added extra line in the tile help doc to outline a general repeat, co…

### PR DESCRIPTION
**Pull request by jrmlhermitte**
…mmonly used

This is just an addition to the documentation. I think it is very common to want to simply repeat an index across a dimension, hence the "c" example. Happy to discuss and I won't be offended if it's refused but I felt this would be the most efficient way to propose this. :)

### CODE REVIEW

**Comment by shoyer** [comment]
A better way to achieve this specific result would be to use the new `np.broadcast_to` function, e.g., `np.broadcast_to(c, (4, 4))`. `broadcast_to` doesn't need to copy the array data, until `tile`.

**Comment by ordirules** [comment]
thanks, I like broadcast_to over using np.newaxis. It's much more explicit. However, I'll stick to the latter because many collaborators still use v 1.9.

should the tile function refer to broadcasting and recommend its usage?

**Comment by mhvk** [comment]
Just looked at the example and agree that for most purposes this be better done using implicit broadcasting. I think it may still make sense to add the example, but then with a comment that this can be done without copying using broadcasting even without changing the dimensions, and with `broadcast_to` if one really wants to have the data (appear) repeated.

**Comment by ordirules** [comment]
Thanks, I added more text referring to broadcasting. I think it could help the inexperienced user.

As a side note, I ended up using tile because it looks nicer and I can't use broadcast_to just yet because of collaborators. It looks much clearer than doing things like A=A[np.newaxis,:]; Anew = A + A.T*0 etc. (which broadcast_to will solve)

thanks!

**Comment by charris** [comment]
Thanks @ordirules .

**Pull request merged**
