### PR TITLE
Clarified documentation on 'argsort' regarding sorting arrays (Issue #4724).

### PR DESCRIPTION
**Pull request by lzkelley**
See Issue #4724

### CODE REVIEW

**Comment by charris** [comment]
See `doc/source/dev/gitwash/development_workflow.rst` for formatting commit message. Also, please squash the commit using `git rebase -i`. If you first rebase on master you can probably also get rid of the merge commit, which looks unnecessary here.

**Comment by lzkelley** [comment]
@charris sorry about that (first PR).  I just opened a new PR #6548, fixing these problems.

**Comment by njsmith** [comment]
For future reference, a useful trick is that after squashing or rebasing
you can do a "force push" (git push -f) to update your original pull
request, and skip having to make a new one.

**Comment by lzkelley** [comment]
Thanks!  Should have looked into that, I was imaging a PR as a static object.

**Comment by njsmith** [comment]
Yeah, it's not at all obvious how it works... but when you create a PR you
specify a particular branch name in your fork, and if you change what's in
that branch, then the PR automagically changes too.

**Pull request closed without merging**
