### PR TITLE
Add monthly downloads badge to README

### PR DESCRIPTION
**Pull request by ayushjain01**
Added a monthly downloads badge by pip Trends to the README.
View more at - https://piptrends.com/widgets/numpy

### CODE REVIEW

**Comment by charris** [comment]
I don't think this adds much and is mostly covered by the PyPI downloads.

**Comment by ngoldbaum** [comment]
This looks like a way to drive traffic to piptrends.com, which appears to be a commercial enterprise. I don't think we should do that.

**Comment by ayushjain01** [comment]
@seberg I couldn't edit or reopen this PR, so I opened a new one.

**Comment by mattip** [comment]
If I were you I would start with an issue to state your case: 
- why we should add yet another badge to the already overloaded README, 
- why the link to pip trends is a good idea for such a badge.

If that discussion is positive (and I have my doubts), only then should you submit a PR. Note that creating a PR burns up not only reviewer time, but CI resources as well.

I see you have opened other such PRs: https://github.com/aio-libs/aiobotocore/pull/1118, https://github.com/pypa/virtualenv/pull/2729, https://github.com/pyca/cryptography/pull/11009 and more. Perhaps you could start a discussion somewhere like https://scientific-python.org/specs/ to add this proposal for a badge to recommended (or not recommened) practices for scientific python packages.

**Comment by thehesiod** [comment]
@seberg now they just need a badge :)

**Comment by thehesiod** [comment]
@seberg awesome, going to swap to that too, ty!

**Comment by ayushjain01** [comment]
@mattip to address your issues - 
1. Why should you add another badge - there is already a badge that indicates the download counts but has a significantly lower number of downloads, so it's not about adding a new badge but replacing it with a more accurate badge. Didn't remove it in PR to show the difference and why this badge needed to be removed. 
2. Why the link is needed - the link is just to a information page about the package, very much like how the pypi downloads badge links to the pypi page. Since there were concerns of the link, I had removed the link and reopened another PR. 

Talking about raising a PR directly - I believe this is what GitHub is built for - to raise PRs and make contributions. also numpy's Call to Contributors mentions [Small improvements or fixes are always appreciated.](https://github.com/numpy/numpy#:~:text=Small%20improvements%20or%20fixes%20are%20always%20appreciated.), which is what I believe my PR did. There were no strict guidelines suggesting to open an issue first, but I apologise for burning out the reviewer's time and CI resources. Will keep that in mind next time. 

Also, going around and commenting on accepted PR's to remove the badge isn't really an appreciate move. We built something and wanted to share it with the community and that's what we did. Those who felt we added some value - accepted it, those who didn't - closed it. 

> If I were you I would start with an issue to state your case:
> 
> * why we should add yet another badge to the already overloaded README,
> * why the link to pip trends is a good idea for such a badge.
> 
> If that discussion is positive (and I have my doubts), only then should you submit a PR. Note that creating a PR burns up not only reviewer time, but CI resources as well.
> 
> I see you have opened other such PRs: [aio-libs/aiobotocore#1118](https://github.com/aio-libs/aiobotocore/pull/1118), [pypa/virtualenv#2729](https://github.com/pypa/virtualenv/pull/2729), [pyca/cryptography#11009](https://github.com/pyca/cryptography/pull/11009) and more. Perhaps you could start a discussion somewhere like https://scientific-python.org/specs/ to add this proposal for a badge to recommended (or not recommened) practices for scientific python packages.

**Comment by ayushjain01** [comment]
> TBH, 4 core dev's have a preference for nothing and I have not seen new arguments. https://pypistats.org looks better and clearly a community project without any advertisement for a company or jobs.
> 
> (Basically, posting just to point out https://pypistats.org again.)

@seberg The career page links to Bavanti Software Solutions - under with pip trends is a community project. We don't plan on adding ads to pip Trends. pip Trends is only for learners and the community. You can check out piptrends.com and see what we're trying to do.

**Comment by ixmatus** [comment]
A colleague of this person tried to open this exact PR against a project I'm the maintainer for as well (https://github.com/ixmatus/inflector/pull/16). This is a promotional campaign and they (or colleagues) appear to be doing it on reddit too, I think this is suspicious activity. They are creating an external dependency on a web property that (as far as I can tell) is not officially blessed by pypi.

Users can get package statistics from `libraries.io` which is linked to directly by pypi itself.

**Comment by ixmatus** [comment]
@ayushjain01 if you do mean well you should know that shotgunning a badge (with your other colleague) across Python package projects that links to an unknown, untrusted, and not blessed by pypi source is _exactly_ the sort of behavior that OSS maintainers must be suspicious of (not just suspicious of commercial intent but of attack vector intent).

I think this is a promotional attempt at generating link juice to the piptrends site for SEO purposes. But honestly, I also have to consider a more nefarious interpretation since it's difficult to establish or verify how I should trust you: you're building first-time contributor trust so you can later inject something malicious into these projects.

**Comment by ayushjain01** [comment]
Thank you for your feedback and concerns. I'd like to clarify that this is not a promotional campaign. As stated in the PR description, our intention is simply to share a tool we have developed, which we believe could be beneficial to the community.

Our badge system offers highly accurate statistics, which is why we wanted to make it available. If the link to the pip trends page is a concern, we are more than willing to remove it.

We respect your decision if you prefer not to add more badges to your README. Our primary goal is to address any misunderstandings and assure you that this is a genuine effort to contribute to the open-source community by sharing our work on GitHub.

Thank you for considering our contribution.

**Pull request closed without merging**
