### PR TITLE
DOC: Move Sphinx numpy target in reference index.

### PR DESCRIPTION
**Pull request by adrn**
This is a possible improvement / step in the direction of a fix for #18844. However, this won't be a complete fix for that issue because the nav bar will still overlap the target location that is scrolled to in the body text.

### CODE REVIEW

**Comment by melissawm** [comment]
This LGTM - I´m pretty sure the overlap you´re describing is related to #18620, can you confirm?

**Comment by adrn** [comment]
Ah, yes, sorry - the overlap comment is a duplicate of #18620!

**Comment by adrn** [comment]
And for completeness: I do think it's still worth moving the target location. Following the suggestion in #18620 to try with /devdocs/ instead of /stable/, the navbar issue is fixed but the target location still goes to an odd place in the page:

https://numpy.org/devdocs/reference/index.html#module-numpy goes to:
image

With this PR, it should go to:
image

**Comment by melissawm** [comment]
Agreed - thanks @adrn !

**Pull request merged**
