### PR TITLE
ENH: Add str_len & count ufuncs for unicode and bytes dtypes

### PR DESCRIPTION
**Pull request by lysnikolaou**

### CODE REVIEW

**Comment by lysnikolaou** [comment]
@seberg @ngoldbaum Let's please merge this next, since it's required for `np.char.replace`.

**Review by seberg — APPROVED** [review]
Looks good to me, but will let Nathan have another look and merge.

**Review by ngoldbaum — COMMENTED** [review]
Two super minor things, otherwise looks great. I'm glad the `Buffer` class has proven to be a nice abstraction for this.

**Comment by ngoldbaum** [comment]
Thanks @lysnikolaou!

**Pull request merged**
