### PR TITLE
MAINT: Update funding link in FUNDING.yml

### PR DESCRIPTION
**Pull request by fayasnoushad**
`https://numpy.org/about/` to `https://numfocus.org/donate-to-numpy`

### CODE REVIEW

**Comment by charris** [comment]
Seems reasonable. @rgommers Thoughts?

**Comment by FayasNoushad** [comment]
> Seems reasonable. @rgommers Thoughts?

`https://numpy.org/about/` is about page of numpy. `https://numfocus.org/donate-to-numpy` is the donate page.

**Review by rgommers — CHANGES_REQUESTED** [review]
This does not seem desirable. We want to point people to the `Donate` section on our website, not to a form with no context.

If you want to improve where this points, then adding an anchor on the about page so we can make the link https://numpy.org/about#donate would be better.

**Comment by FayasNoushad** [comment]
> This does not seem desirable. We want to point people to the `Donate` section on our website, not to a form with no context.
> 
> If you want to improve where this points, then adding an anchor on the about page so we can make the link https://numpy.org/about#donate would be better.

Done

**Comment by charris** [comment]
@rgommers Looks like headings in markdown are already anchor points.

**Review by rgommers — APPROVED** [review]
LGTM now, thanks @FayasNoushad

**Pull request merged**
