### PR TITLE
DOC: Created fundamentals doc for explanations in `ufunc` reference doc

### LINKED ISSUE #16924: DOC: Create a documentation subpage for ufunc
The ufunc page in the reference guide ([source](https://github.com/numpy/numpy/blob/master/doc/source/reference/ufuncs.rst), [rendered](https://numpy.org/devdocs/reference/ufuncs.html)) contains both high-level discussion on things like broadcasting and casting rules, as well as details about the `ufunc` class itself (methods, attributes, `__call__` parameters).

Details pertaining to the ufunc class could be made more visible by splitting the methods, attributes, kwargs etc. out into their own subpage (see #16919).

### PR DESCRIPTION
**Pull request by Mukulikaa**
Closes #16924

Changes:
1. Moved all explanations from `ufuncs.rst` to a new doc in the Fundamentals section named `basics.ufunc.rst`.
2. I have named the new doc as `Universal functions (ufunc) basics` but other suggestions are welcome.
3. I have also rearranged the order of the sections a bit from the [original doc](https://numpy.org/devdocs/reference/ufuncs.html). Let me know if it makes sense or should I change it back :)
4. `ufuncs.py` in `numpy/doc` has a few examples in it but apart from that the explanations are more or else the same. I thought we could incorporate some examples into the new `basics.ufunc.rst` doc and remove the `ufuncs.py` file. 

Let me know what y'all think! 

cc: @melissawm @rossbar 🙂

### CODE REVIEW

**Review by melissawm — CHANGES_REQUESTED** [review]
Hi Mukulika! I like the organization and new examples, thanks for that!

I left a couple of comments about formatting (mostly links). I think I understand your goal with reorganizing the order of the sections but can you explain? 

Finally, I haven't checked all the details to see if any of that text is outdated, but I'm trusting it's not. If it is maybe it can be updated in a follow-up.

**Comment by Mukulikaa** [comment]
Thanks for helping me with the links @melissawm! As for the broadcasting section- I was wondering if we could remove most of it from here since the information already exists in the Broadcasting doc. We could add a line about `Broadcastable arrays` in the Broadcasting doc itself and shift the section link there. I am not sure if I should do it in this PR itself or make a separate one.

**Comment by melissawm** [comment]
Yes about broadcasting - I'd keep the first part:

```
Each universal function takes array inputs and produces array outputs
by performing the core function element-wise on the inputs (where an
element is generally a scalar, but can be a vector or higher-order
sub-array for generalized ufuncs). Standard
broadcasting rules are applied so that inputs not sharing exactly the
same shapes can still be usefully operated on.
```

but maybe link to the main broadcasting doc for the rest (making sure no information is lost in the process)

As for the organization that makes total sense, thanks!

**Comment by Mukulikaa** [comment]
I moved the Broadcastable arrays section to the Broadcasting doc. The "rules" that were written in that section are already explained in the doc so I decided to remove them. Also, let me know if this branch needs a rebase because I had to merge my broadcasting branch into this one and it adds an extra merge commit 🙂

**Comment by melissawm** [comment]
You probably do need a rebase - but otherwise this looks good! Thanks for the great work here, @Mukulikaa !

**Review by melissawm — APPROVED** [review]

**Review by rossbar — APPROVED** [review]
Very nice work @Mukulikaa ! This is a big re-organization and you've done a nice job of moving & consolidating the relevant info on ufuncs and broadcasting without (AFAICT) losing anything - no small feat!

The page on ufuncs in the reference guide now reads much more like reference material, and the material that was in the `theory.broadcasting` doc is now much more discoverable. Thanks!

**Pull request merged**
