### PR TITLE
ENH: Add annotations for `np.core.shape_base`

### PR DESCRIPTION
**Pull request by BvB93**
This PR adds annotations for the following functions in `np.core.shape_base`:
* `atleast_1d`
* `atleast_2d`
* `atleast_3d`
* `vstack`
* `hstack`
* `stack`
* `block`

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks @BvB93, LGTM.

**Comment by rgommers** [comment]
One thing that has become clear to me is that these kinds of type annotations are _not_ useful as documentation. The type annotations attempt to be very correct for all sorts of corner cases, like `axis: SupportsIndex`, which makes them very confusing to the average user (who should just see `int`). If IDE's are going to use type annotations instead of docstrings for this, that's going to be problematic. I'm not sure we have discussed this issue elsewhere already?

**Comment by BvB93** [comment]
> If IDE's are going to use type annotations instead of docstrings for this, that's going to be problematic. 

I feel that a fundamental problem here is that many (seemingly simple?) runtime behaviors cannot be conveniently expressed with static typing, thus forcing us to resort to the likes of `axis: SupportsIndex` (or worse: _overloads_).

**Comment by rgommers** [comment]
> I feel that a fundamental problem here is that many (seemingly simple?) runtime behaviors cannot be conveniently expressed with static typing

Yeah, this is partly historical. I'd much prefer to have axis only accept an `int`, and if static typing had existed when NumPy was first written, that's probably what the design would have been. Same with the `array_like` mess. Retrofitting static typing onto a too-forgiving code base is not ideal.

Maybe at this point it just is what it is, and it's on IDE's to do the right thing here (prioritize docs over annotations).

**Pull request merged**
