### PR TITLE
MAINT: remove NPY_NO_DEPRECATED_API define from f2py.

### PR DESCRIPTION
**Pull request by rgommers**
See gh-5281 for discussion.  With the defines in, compiling scipy 0.14.0 and
below isn't possible.

### CODE REVIEW

**Comment by charris** [comment]
Hmm, what is the advantage of ignoring unknown options if the problem is older versions of f2py? That said, don't see any reason not to drop the `sys.exit()` except visibility.

**Comment by rgommers** [comment]
@charris good point, either option only helps a few years after introducing it.

**Comment by pearu** [comment]
Hi guys,

Even when it is too late, let me ask what is the main point of introducing the --no-deprecated-api? Is it just to enable/disable the following line:
```
#define NPY_NO_DEPRECATED_API NPY_API_VERSION
```
?
If so, this could have been achieved by introducing CPP macro, say DISABLE_NO_DEPRECATED_API, that wraps the above line and defining the macro at f2py command line when needed. For example,
```
#ifdef DISABLE_NO_DEPRECATED_API
#else
#define NPY_NO_DEPRECATED_API NPY_API_VERSION
#endif
```
and then use `f2py -c -DDISABLE_NO_DEPRECATED_API ...`.

Note that the `-DDISABLE_NO_DEPRECATED_API` could be introduced in f2py main script when `--no-deprecated-api` flag is used (of course, the script must remove the flag from sys.argv before calling main()).

The above should be equivalent to rgommers commit and usage `f2py -c --no-deprecated-api ...`, if I understand the whole issue correctly.

**Comment by njsmith** [comment]
The problem with the proposed DISABLE_NO_DEPRECATED_API is that it would
break all the non-f2py users of the numpy c API.

**Comment by rgommers** [comment]
@pearu it's never too late. You're right about the goal of introducing the option. I implemented it this way mainly because it's a relatively clean way and that seemed to be supported by numpy.distutils with ``f2py_options`` already and would work also for older versions (said https://github.com/numpy/numpy/pull/5309#issuecomment-64705118). The last bit turned out to not be true. 

What you propose is the wrong way around as @njsmith points out, but in principle an interface like that could work I think. I need to think a bit about how one would then enable it from a ``setup.py`` in a scipy submodule for example.

**Comment by rgommers** [comment]
I think Pearu has a point: it is already possible to switch these deprecations on/off by compiling with

    -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION

or in a ``setup.py`` using this kwarg to ``add_extension``:

    define_macros=[("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")]

This is actuall better than ``--no-deprecated-api`` because it allows setting a specific API version.

I'm going to try to use ``define_macros`` for every Scipy extension module; if that works without any unpleasant surprises then I propose to just keep the first commit from this PR.

**Comment by rgommers** [comment]
Scipy PR: https://github.com/scipy/scipy/pull/4351

**Comment by rgommers** [comment]
OK that didn't work, because for all released numpy versions f2py itself still uses deprecated C API.

**Comment by charris** [comment]
Looks like we are stuck. Living with the warnings is an option...

**Comment by rgommers** [comment]
@charris it's an option, but tons of warnings that you can't possibly fix is a bit ridiculous....

I will try a few more things.

**Comment by charris** [comment]
@rgommers I see that you have had success on the scipy side. Where are you with this PR?

**Comment by rgommers** [comment]
I'm waiting for an OK on the Scipy PR. If that goes in, then I'll remove the commits related to the ``f2py`` command line option from this PR.

**Comment by rgommers** [comment]
Scipy PR is merged, that looks like the way to go. Removed the command line option for ``f2py`` from this PR again. Ready to merge I'd say.

**Comment by charris** [comment]
OK, thanks Ralf.

We should probably document how to fix the warnings. Maybe in the f2py documentation?

**Comment by rgommers** [comment]
It's not f2py-specific. How about on http://docs.scipy.org/doc/numpy/reference/c-api.deprecations.html?

**Comment by charris** [comment]
OK.

**Pull request merged**
