### PR TITLE
DOC: Clarify randint and integers doc

### LINKED ISSUE #9573: Confusing argument order for random.randint
Not sure if this is covered anywhere already, feel free to close if this is the case.

Without having the numpy documentation open, and just looking at the argument names for `random.randint`, the results I got were.. confusing, to say the least.

Without looking at the docs, what would the following code do: `random.randint(low=2, size=5)`?
My guess would be that it would give back five integers larger than or equal to 2. However, the result was quite different: `array([1, 0, 0, 1, 1])`.

Wait, so I specified `low=2`, but got back numbers which are all __lower__ than `low`? What the...

The docs didn't help much at first, either: "unless high=None, in which case this parameter is one above the highest such integer" - what? Until I stumbled upon this: "If high is None (the default), then results are from [0, low)."

So `high` and `low` are switched based on the value of one of the parameters, which makes things very confusing. Much cleaner would be the following function definition:

    randint(high, low=0, size=None, dtype='l')

Of course, this would not permit something like `randint(1, 2)`, but `randint(low=1, high=2)` is arguably more readable anyway. For backwards compatibility, a check could be built in which checks if `low` is greater than `high`, in which case the order can be reversed (while raising a warning).

### PR DESCRIPTION
**Pull request by bashtage**
Improve doc strings to include multiple signatures Clean up docstring generally

closes #9573

### CODE REVIEW

**Comment by bashtage** [comment]
Need to see how this renders in the docbuild.

**Comment by charris** [comment]
Doesn't render correctly. The first docstring line gets appended to the signature. This might be a numpydoc problem, not sure how multiple signatures should be marked up.

**Comment by seberg** [comment]
Maybe @rossbar has a suggestion (or maybe it should also use `[]` style in the signature).

**Comment by melissawm** [comment]
I'm pretty sure there's no way to do this currently. We also tried with arange and never got it to work 😞

**Comment by charris** [comment]
> I'm pretty sure there's no way to do this currently

It seems that way. I'm going to close this as it seems stalled.

**Pull request closed without merging**
