### PR TITLE
Replaced Travis link, descriptive Travis label

### PR DESCRIPTION
**Pull request by philipgura**
Travis link was not always loading

### CODE REVIEW

**Comment by charris** [comment]
Much nicer. Is there a way to also label icon? Not everyone would recognize it, maybe something like `Travis CI status`.

**Comment by philipgura** [comment]
Great idea, thank you

**Comment by charris** [comment]
For some reason the text doesn't show up. Hit the view button in `files changed` to see the result.

**Comment by charris** [comment]
I assume this can be closed now. BTW, you can keep pushing to the same branch, no need to make a new PR. When ready, the commits can be squashed.

**Pull request closed without merging**
