### PR TITLE
MAINT: fix name of first parameter to dtype constructor in type stubs

### PR DESCRIPTION
**Pull request by person142**
The first parameter to the constructor is currently called "obj",
which is incorrect. It should instead be "dtype".

### CODE REVIEW

**Comment by BvB93** [comment]
Despite what the NumPy documentation claims (calling the first argument `obj`; [ref](https://numpy.org/doc/1.18/reference/generated/numpy.dtype.html)) it seems that `dtype` is indeed the correct name.
``` python
>>> import numpy as np

>>> np.type(dtype=int)
dtype('int64')

>>> np.dtype(obj=int)
Traceback (most recent call last):
  ...
TypeError: dtype() missing required argument 'dtype' (pos 1)
```

**Comment by seberg** [comment]
There is actually one more kwarg which is also not documented, and that is `metadata=None`, which must be a dictionary.  Not sure it matters for this though.

**Comment by person142** [comment]
> There is actually one more kwarg which is also not documented, and that is metadata=None, which must be a dictionary

Huh, TIL. Let's keep pretending it doesn't exist for the types...

**Comment by person142** [comment]
Corrected the docs and added a test for a keyword first argument in the constructor in https://github.com/numpy/numpy/pull/16574/commits/8190116aa2fa58aba628b0a5cea768017acf82bf.

**Review by eric-wieser — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @person142

**Comment by seberg** [comment]
Oh, thanks for the followup on the docs!

**Pull request merged**
