### PR TITLE
MAINT: Use textwrap.dedent in f2py tests

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by charris** [comment]
Hmm, not sure if this is a good idea or not. In Fortran 77 indentation is important, in particular, code begins in column 7 with numeric labels in columns 2-5, and that is easier to see without the indent added here. Reference at https://www.lrsm.upenn.edu/~vitek/courses/f77intro/node9.html.

**Review by jeffyancey — COMMENTED** [review]
Well, looks good to me, assuming we decide the indentation is preferable.

**Comment by eric-wieser** [comment]
In the interest of closing this out, will rollback the changes to the fortran, and just leave it on the python

**Comment by charris** [comment]
LGTM. Thanks Eric.

**Pull request merged**
