### PR TITLE
DOC: promote_types is not associative by design,

### PR DESCRIPTION
**Pull request by eric-wieser**
Despite the fact it would be nice if it was

Also give an example of the non-associative case.

### CODE REVIEW

**Comment by ahaldane** [comment]
Is is only non-associative for flexible types?

**Comment by eric-wieser** [comment]
I think specifically character types break the associativity, but I don't want to make any guarantees I can't prove.

`result_type` is much less associative than `promote_types` due to an additional layer of scalar-checking logic.

**Comment by ahaldane** [comment]
Hmm, actually many combinations even including numeric types break associativity. See the output of:
```python
>>> p = np.promote_types
>>> t = ['b', 'h', 'i', 'l', 'q', 'p', 'i1', 'i2', 'i4', 'i8', 'B', 'H', 'I', 
... 'L', 'Q', 'P', 'u1', 'u2', 'u4', 'u8', 'e', 'f', 'd', 'g', 'f2', 'f4', 'f8
... ', 'f16', 'F', 'D', 'G', 'c8', 'c16', 'c32', 'O']
>>> for a,b,c in itertools.permutations(t, 3):
...     if p(p(a,b), c) != p(a,p(b,c)):
...         print a,b,c, p(p(a,b), c), p(a,p(b,c))
```
(output a bit too long to paste)

The output is long enough that I would hesitate to even say that the function is "usually" associative. I would either say nothing, or say "not associative". 

Just one example:
```python
>>> p(p('u2', 'i1'), 'f4'), p('u2', p('i1', 'f4'))
(dtype('float64'), dtype('float32'))
```

**Comment by ahaldane** [comment]
Incidentally, the "C" promotion/conversion rules *are* associative. Maybe that's one more reason "I wish we had gone with C conversion rules back in the day". Although I'm not sure associativity really matters since all arithmetic operations are binops.

<details>
<summary> C-like conversion rules code</summary>

(ignores integer promotion of byte/short, only covers numeric types)
```python

def promote_types_C(a, b):
    a, b = np.dtype(a), np.dtype(b)          
    
    # complex
    ia = issubclass(a.type, np.complexfloating)
    ib = issubclass(b.type, np.complexfloating)
    if ia and ib:
        return a.type if a.itemsize > b.itemsize else b.type
    elif ia:
        return a.type
    elif ib:
        return b.type
    
    # float
    ia, ib = issubclass(a.type, np.floating), issubclass(b.type, np.floating)
    if ia and ib:
        return a.type if a.itemsize > b.itemsize else b.type
    elif ia:
        return a.type
    elif ib:
        return b.type
    
    # only integers left at this point
    ia = issubclass(a.type, np.unsignedinteger)
    ib = issubclass(b.type, np.unsignedinteger)
    if ia == ib:
        return a.type if a.itemsize >= b.itemsize else b.type
    elif a.itemsize == b.itemsize:
        return a.type if ia else b.type
    return a.type if a.itemsize > b.itemsize else b.type
```

</details>

**Comment by ahaldane** [comment]
A related trick:
```python
>>> np.result_type('u2', 'i2', 'f4')
dtype('float64')
>>> np.result_type('i2', 'f4', 'u2')
dtype('float32')
```

By the way, I would merge this PR if you update the comment.

**Comment by eric-wieser** [comment]
Look good now? Or should I remove the word "rarely"? If you use only signedinteger + float types, the result is associative

**Comment by ahaldane** [comment]
Great as is! Thanks Eric, merging.

**Pull request merged**
