### PR TITLE
BUG, SIMD: Restore behavior converting non bool input to 0x00/0xff

### LINKED ISSUE #22845: BUG: (main branch only; 1.24.0 fine) bizzare boolean product issue
I did see a number of `bool_` comparison related issues open, but they seem to be fine here for NumPy `1.24.0`, while in my case it is the `main` branch that is a problem and the stable release is working just fine.

I've been looking at some of the failures in SciPy + NumPy `main` branch after the recent release (which confusingly seems to be named/versioned `1.24.0.dev0+1413.gca2575655` in my tests, but clearly causes a number of issues in https://github.com/scipy/scipy/issues/17630#issuecomment-1358008148). Before deciding to release the next RC for SciPy `1.10.0` I wanted to drill down on one of the test failures to make sure I couldn't just easily shim around these, but it looks like this stuff is going to be too tricky because there are tons of them. Maybe not so serious since it just on the unreleased `main` branch so perhaps I'll move forward for now.

Here is a specific reproducer with `*.npy` files available from `np.save` in this tarball:  [arrays.tar.gz](https://github.com/numpy/numpy/files/10273085/arrays.tar.gz)

```python
import numpy as np

print("np.__version__:", np.__version__)

with open("q.npy", "rb") as q_file:
    q = np.load(q_file)

with open("r.npy", "rb") as r_file:
    r = np.load(r_file)

print("q, q.shape, q.dtype:", q, q.shape, q.dtype)
print("r, r.shape, r.dtype:", r, r.shape, r.dtype)

print("q * r:", q * r)
```

The results from `main` and `1.24.0`, respectively, follow:

```
np.__version__: 1.24.0.dev0+1413.gca2575655
q, q.shape, q.dtype: [ True False False ... False False False] (10000,) bool
r, r.shape, r.dtype: [ True  True  True ...  True  True  True] (10000,) bool
q * r: [False False False ... False False False]
```

```
np.__version__: 1.24.0
q, q.shape, q.dtype: [ True False False ... False False False] (10000,) bool
r, r.shape, r.dtype: [ True  True  True ...  True  True  True] (10000,) bool
q * r: [ True False False ... False False False]
```

If you focus on the first element in the result array, the stable release looks much more sensible. 

This manifested as a single (first) element difference in the expected value of the test result for `scipy/stats/tests/test_sampling.py::TestDiscreteGuideTable::test_ppf[u0]`. In fact, the actual value is just fine, but that means `stats.binom.ppf(u, n, p)` may be broken with NumPy `main` at the moment (cc: @mdhaber @tupui ), and naturally these kinds of issues seem to cascade around in a way that I probably can't patch manually, so I'll probably wait for some fixes in NumPy if you agree this is a problem.

### PR DESCRIPTION
**Pull request by Developer-Ecosystem-Engineering**
This resolves https://github.com/numpy/numpy/issues/22845 by restoring prior behavior to convert non bool input

### CODE REVIEW

**Comment by charris** [comment]
Is there a test for this behavior?

**Review by tylerjereddy — COMMENTED** [review]
Here's a test that fails on latest `main` and passes on this branch, though it melts my brain a bit:

```python
import numpy as np
from numpy.testing import assert_array_equal

def test_bool_comp():
    a = np.frombuffer(b'\x01' + b'\x00' * 99, dtype=np.bool_)
    b = np.frombuffer(b'\xfe' * 100, dtype=np.bool_)
    expected = np.zeros(100, dtype=np.bool_)
    expected[0] = 1
    assert_array_equal(a * b, expected)
```

**Review by seiko2plus — APPROVED** [review]
LGTM, Thank you.

**Comment by mattip** [comment]
Thanks @Developer-Ecosystem-Engineering

**Comment by charris** [comment]
@mattip The `numpy/core/src/umath/loops_logical.dispatch.c.src`  file does not exist in 1.24.x, I suggest leaving this to 1.25.x.

**Comment by mattip** [comment]
@charris the test seems to pass for me on maintenance/1.24.x, I do not have AVX512.

**Comment by seberg** [comment]
Yah, this wasn't a problem in main, but it was confusing because it was only apparent because it overlapped with a problem that did exist on main.

**Pull request merged**
