### PR TITLE
DOC: Add examples using DASK arrays.

### LINKED ISSUE #9476: DOC: Clearly document functions with duck-type compatibility
We don't do a very good job of describing how functions like `numpy.mean()` or `numpy.moveaxis()` handle duck-arrays like those from dask. It would be nice to clearly document this somehow (either in docstrings or a separate table somewhere), so developers know they can rely on this.

xref https://github.com/dask/dask/issues/2559

### PR DESCRIPTION
**Pull request by shivam2012**
Added example of dask array compatibility with np.mean() and np.moveaxis()

#9476

### CODE REVIEW

**Comment by charris** [comment]
I'm not sure we want to add this, especially as it adds a dependency on DASK arrays if/when we run checks on the examples.

**Comment by eric-wieser** [comment]
The summary in #9476 gives an _example_ of the type of thing that needs documenting. Simply documenting that one example isn't useful or scalable - we don't want to document, for every function, every dependency that does and does not work with that function.

I'm with @charris on this one

**Comment by shivam2012** [comment]
Any suggestions where can this example be added

**Comment by rgommers** [comment]
Agree, we can't add this. For discussion on how to handle this, let's do that on gh-9476 (just added a comment there).

Thanks for the attempt at improving the status quo @shivam2012

**Comment by jakirkham** [comment]
Kind of tempted to add this info in Dask with tests ATM to at least avoid confusion for our users. ( https://github.com/dask/dask/issues/3258 ) Though I agree that it would be good for NumPy to include this somewhere as well.

**Comment by njsmith** [comment]
Maybe once we have something like NEP 16's `AbstractArray`, we can start referring to that in documentation, like "this function works on arbitrary abstract arrays"?

**Pull request closed without merging**
