### PR TITLE
DOC: Update 1.12.0 release notes.

### PR DESCRIPTION
**Pull request by charris**
[ci skip]

### CODE REVIEW

**Comment by charris** [comment]
I've included lists of the contributors and PRs in the release notes. That bulks them up considerably and may be somewhat controversial. Note that SciPy now does the same.

For future reference, it shoud be possible to separate the PRs by lable into bugs, enhancements, etc. We may want to do that in the future if we continue down this route.

**Comment by rgommers** [comment]
> That bulks them up considerably and may be somewhat controversial. 

+1 from me, it's useful info. The one thing to make sure is that everyone who's merging PRs is consistent in actually setting the Milestone.

**Comment by charris** [comment]
I don't use milestones, the script searches out all merges in the specified range and extracts the relevant PR. This now works for the github squash-merge button as well as the homu delayed merges (I don't recommend the latter).

**Comment by rgommers** [comment]
Right. That's even better.

**Pull request merged**
