### PR TITLE
WIP: CI: add link to doc build artifact on CircleCI in GitHub UI

### PR DESCRIPTION
**Pull request by rgommers**
Idea taken over from https://github.com/scipy/scipy/pull/10707

Closes gh-15005

### CODE REVIEW

**Comment by rgommers** [comment]
@larsoner would you recommend installing https://github.com/larsoner/circleci-artifacts-redirector or https://github.com/larsoner/circleci-artifacts-redirector-action at this point?

**Comment by larsoner** [comment]
The action (second one) is probably better

**Comment by eric-wieser** [comment]
I assume this still needs work since I see no link in the CI checks.

**Comment by rgommers** [comment]
indeed, I need to mess with the GitHub Action

**Comment by rgommers** [comment]
Superceded by gh-16337, closing. Thanks all

**Pull request closed without merging**
