### PR TITLE
DEP: Deprecate ufunc.outer with matrix inputs

### PR DESCRIPTION
**Pull request by seberg**
Previously we converted matrices to arrays for the user, since
`np.outer` does not make sense for matrix. This deprecates that
usage (which in almost all cases will result in an error).

The main reason for this deprecation is to remove all direct
references of matrix from the NumPy codebase, so that it is
easier to move it out of NumPy eventually.

---

I can spin off the first maintenance commit if anyone feels the deprecation is trivial...

EDIT: xref gh-15105 which this closes, but I will remove the 1.19 milestone, since this doesn't really need to be in 1.19. It might just make the next steps to get rid of matrix a tiny bit simpler.

**EDIT: For reviewers, the commits are probably best reviewed separately, just to disentangle things a bit. Both should be very straight forward.**

### CODE REVIEW

**Comment by mattip** [comment]
LGTM, and I would even vote for putting it into 1.19.

@charris - thoughts?

**Comment by seberg** [comment]
To be fair: `np.diagonal`, `np.trace`, `np.ravel`, `np.apply_along_axis`, and `np.expand_dims` still have python side `isinstance` checks (I may have missed some place). (May be a bit easier to cover with `__array_function__` though, since its all single argument functions.)

**Comment by seberg** [comment]
Well, since its all branched, I updated the comments to say 1.20 (it was actually inconsistent before...)

**Comment by seberg** [comment]
Should we just put this in now?

**Comment by mattip** [comment]
Thanks @seberg.

**Pull request merged**
