### PR TITLE
MAINT: Deal with first TODO in prepare_index in mapping.c

### PR DESCRIPTION
**Pull request by k-kapp**
Just a suggestion to refactor that block of code into a function,
as requested by the TODO.
Two variables from the caller get modified (index and make_tuple).
Index I modified by having a pointer to the pointer being passed in,
and make_tuple I returned from the function, since it acts like
an indicator on whether the index was converted to a tuple, or whether
conversion was successful. There might be better/more preferable ways
to modify these variables, though.
The only reason this would be refactored into a function would be
to make the prepare_index function slightly smaller, even if only
slightly, since I did not, after a quick survey, see any other uses
for this function in the codebase at the present moment.

### CODE REVIEW

**Comment by k-kapp** [comment]
Sorry, PR title might be slightly unclear - thought it would be obvious when looking at the specific changes, but it's a bit of a jumble there too. Will change it when I can think of something better.

**Comment by eric-wieser** [comment]
I already did this is #8278

**Comment by k-kapp** [comment]
Ah ok, will close then.

**Comment by eric-wieser** [comment]
Of course, it might be that this refactor is preferable - the first solution is not necessarily the best one

**Comment by k-kapp** [comment]
Although I think that is unlikely, since you are much better acquainted with the codebase than I am, and the discussion on your PR is much further and older than this one, should I reopen? This is also a pretty trivial PR, since I pretty much just moved that block of code into a function.

**Pull request closed without merging**
