### PR TITLE
MAINT: Refresh Doxyfile and modernize numpyfilter.py

### PR DESCRIPTION
**Pull request by mwtoews**
It doesn't look like the `doc/cdoc` space has seen much attention in the past decade, as it currently does not work. This PR does a few modernizations:

#### Doxyfile refreshed
Done automatically:
```
$ doxygen --version
1.8.13
$ doxygen -u
warning: Tag `SYMBOL_CACHE_SIZE' at line 300 of file `Doxyfile' has become obsolete.
         This tag has been removed.
warning: Tag `SHOW_DIRECTORIES' at line 500 of file `Doxyfile' has become obsolete.
         This tag has been removed.
warning: Tag `HTML_ALIGN_MEMBERS' at line 828 of file `Doxyfile' has become obsolete.
         This tag has been removed.
warning: Tag `USE_INLINE_TREES' at line 999 of file `Doxyfile' has become obsolete.
         This tag has been removed.
warning: Tag `XML_SCHEMA' at line 1211 of file `Doxyfile' has become obsolete.
         This tag has been removed.
warning: Tag `XML_DTD' at line 1217 of file `Doxyfile' has become obsolete.
         This tag has been removed.
```
No manual changes were made to the file.

#### Update numpyfilter.py
This utility is called from Doxygen, but it is out-of-date with Python3 and the rest of numpy, thus a few fixes were done to make it work again. Also, the deprecated optparse is replaced with argparse.

#### Misc
* Added `clean` target to Makefile to clear build and cache

### CODE REVIEW

**Comment by rgommers** [comment]
Is this used at all? Maybe `doc/cdoc/` just needs deleting?

**Comment by mattip** [comment]
I see two choices:
- Decide that documentation belongs in the source code, not in separate files. Revive the use of doxygen and somehow merge its output with the sphinx document build system.
- Stay on our current path of minimal C code documentation where needed for NumPy developers together with `doc/source/reference/*.rst` documentation for C-API consumers.

I think the first alternative would generate a lot of work without much user experience improvement, so I agree with @rgommers that we should delete `doc/cdoc`

**Comment by eric-wieser** [comment]
> and somehow merge its output with the sphinx document build system.

This can be done with `breathe`, and isn't all that complex from what I remember.

**Comment by seberg** [comment]
I think moving the docs into the code and auto-generating the C-docs would be a commendable effort! But is it useful to keep this around unless it is replaced with a complete new system based on `breathe` and the two (now diverged) documentations manually unified?

**Comment by mwtoews** [comment]
If we're deciding going to hang on to this C API documentation (for now?), I think the `Doxyfile` should be boiled down considerably to <20 lines by removing the comments and default parameters. A comment to [Doxygen's config manual](http://www.doxygen.nl/manual/config.html) should suffice.

As for [Breathe](https://breathe.readthedocs.io/), this is a useful documentation tool that I've used in a few other projects. But this would be a separate effort.

**Comment by charris** [comment]
IIRC, the idea here was to write C documentation using the numpy docstring standard. A couple (or fewer :) functions were so documented. If we decide to document the C functions in the code and choose another tool, this could be removed. But we should decide what to do about the C documentation and make a NEP, or at least a style guide.

**Comment by mwtoews** [comment]
I've updated this PR to strip out ~1.5k lines of Doxygen comments and defaults.

**Comment by charris** [comment]
Thanks @mwtoews . No reason to keep this hanging, we can decide on its long term fate later. My understanding is that it has been tested, is that correct?

**Comment by mwtoews** [comment]
@charris yes this was tested on an Ubuntu laptop

**Pull request merged**
