### PR TITLE
ENH: Rearrange testing module to isolate nose dependency.

### PR DESCRIPTION
**Pull request by charris**
The aim here is to separate out the nose dependent files prior to adding
pytest support. This could be done by adding new files to the general
numpy/testing directory, but I felt that it was to have the relevant
files separated out as it makes it easier to completely remove nose
dependencies when needed.

Many places were accessing submodules in numpy/testing directly, and in
some cases incorrectly. That presented a backwards compatibility
problem. The solution adapted here is to have "dummy" files whose
contents will depend on whether of not pytest is active. That way the
module looks the same as before from the outside.

In the case of numpy itself, direct accesses have been fixed. Having
proper `__all__` lists in the submodules helped in that.

A simplified nose compatible `parametrize` decorator has also been added. 
to help  in achieving pytest compatibility by providing a way to replace
yield based nose tests. The version here does not have all the functionality of
the pytest version, but should be adequate for our immediate needs.

Tests for the `parametrize` decorator are still needed, but I thought I'd put this
up for initial comment.

### CODE REVIEW

**Comment by charris** [comment]
@rgommers Should we just remove the `test` and `bench` functions from the numpy submodules?

**Comment by charris** [comment]
This PR has been tested with numpy ... and fixed accordingly ;)

**Comment by rgommers** [comment]
> @rgommers Should we just remove the `test` and `bench` functions from the numpy submodules?

``bench`` yes, because it doesn't work. ``submodule.test`` is useful (I use it all the time).

**Comment by rgommers** [comment]
Thanks for having a go at this!

**Comment by rgommers** [comment]
I'm afraid https://github.com/scipy/scipy/pull/7562 shows that this needs the functions that are removed from some ``testing.xxx`` namespace to be put back with a ``DeprecationWarning`` (or ``VisibleDeprecationWarning``?).

**Comment by charris** [comment]
@rgommers All the old functions are in the "dummy" functions for that reason. Unfortunately, not all those functions were previously available directly from `numpy.testing`, so there is a potential backwards compatibility problem for downstream projects supporting older versions of numpy and also using the numpy test functions.  It would actually be pretty easy to deprecate all imports of the submodules, the `__init__` just needs to import directly from `nose_tools` and the dummy functions can raise warnings on import.

If this all looks good, I'd like to get it in soonish and add pytest versions so as to support the scipy sprint -- if anyone works on this.

**Comment by charris** [comment]
Done. I have more, but it can go into a later PR.

**Comment by pv** [comment]
I understand the parametrize decorator is for emulating the 
corresponding pytest decorator in nose, but it's unclear to me why this 
is needed? Does it need to be public?

**Comment by charris** [comment]
@pv The idea is to attain pytest compatibility incrementally. To do so, the yield tests need to be rewritten to run under both nose and pytests. At least if we want to have compatibility with the next version of pytests. What is your idea where we don't need the parametrize decorator to be public? It probably isn't useful outside of numpy due to the lack of support in earlier numpy versions, although I suppose it could be backported. Hmm... It does need a version added mark.

**Comment by pv** [comment]
pytest 3.x still supports yield tests, so I was thinking of first 
switching to pytest, and then starting to clean up.

**Comment by pv** [comment]
Namely, this way, there is no need to have the test suite runnable under 
both nose and pytest at the same time. There is a need to do a "big" PR 
first that fixes the problems that prevent pytest from working at all 
--- however, the yield tests do not seem to be in this problem class, 
and can be fixed up later.

**Comment by charris** [comment]
> There is a need to do a "big" PR first that fixes the problems that prevent pytest from working at all

Don't see the point when it is just as easy to do it incrementally. In anycase, we still need to support nose for downstream projects. Whether or not parametrize is public is a small detail.

**Comment by charris** [comment]
Note that I already have the pytest compatible testing support decorators and utils written, they just need to be plugged in. And we want pytest to work even if nose isn't present, which is not quite the case now as all the decorators currently out there use nose.

What I do want to settle with this PR is whether the chosen approach is acceptable.

**Comment by charris** [comment]
If there are no complaints, I will put this in soon as part of the preparation for the Scipy 2017 sprint.

**Comment by rgommers** [comment]
Thanks Chuck. All LGTM after testing a few projects against current master.

**Pull request merged**
