### PR TITLE
Code Formatted and Re-structured

### PR DESCRIPTION
**Pull request by dhhruv**
Code Formatted and Re-structured for better visibility and to easily understand the code.
Some of the code lines were messy so I formatted them as many of my colleagues find it difficult to understand as well.

### CODE REVIEW

**Comment by charris** [comment]
Why are so many files without changes included?

**Comment by charris** [comment]
How were these changes generated?

**Comment by rkern** [comment]
This is from the SciPy contributor docs, but the same generally applies for the NumPy project as well (we should look into rationalizing the two):

http://scipy.github.io/devdocs/dev/hacking.html#maintaining-existing-code

**Comment by charris** [comment]
Big cleanup PRs like this are generally frowned on and should probably use `.git-blame-ignore-revs` to avoid messing up git blame.

**Comment by rkern** [comment]
Looking at the changes that were made, I'm guessing this was done with `black`. [This is the related (closed) SciPy issue on the same subject](https://github.com/scipy/scipy/pull/14330).

**Comment by dhhruv** [comment]
> Looking at the changes that were made, I'm guessing this was done with `black`. [This is the related (closed) SciPy issue on the same subject](https://github.com/scipy/scipy/pull/14330).

Got it,

**Comment by dhhruv** [comment]
> How were these changes generated?

Using black.

**Pull request closed without merging**
