### PR TITLE
BUG: Fix unaligned memory access in `npy_memchr`.

### LINKED ISSUE #21116: BUG: `npy_memchr` has misaligned memory access
### Describe the issue:

The function `npy_memchr` (in `multiarray/common.h`) has an optimisation for the case `!NPY_ALIGNMENT_REQUIRED && needle == 0 && stride == 1` where it start by find the first nonzero 4-byte block before iterating within the block. However, the coarse-grained loop begins at `haystack` itself, and since the stride is 1 there's no expectation that this pointer would have any particular alignment.

While this is benign on x86_64, the misaligned access is nevertheless picked up by UBsan as it is undefined behaviour according to the C standard. `npy_memchr` should first scan each byte until it reaches the first 4-byte aligned block before entering the coarse-grained loop.

### How to reproduce:

Build NumPy with UBsan and run a test suite containing a sufficiently large number of `np.testing.assert_` calls. Since `func_assert_same_pos` constructs a boolean mask that is used to index into the arrays under test, with enough calls there's a decent chance that it will end up creating an unaligned boolean array at least once.

### Error message:

```shell
third_party/py/numpy/core/src/multiarray/common.h:277:35: runtime error: load of misaligned address 0x... for type 'unsigned int', which requires 4 byte alignment
0x615000673205: note: pointer points here
 01 01 01 01 01 01 01  01 01 01 01 01 01 01 01  
             ^ 
    #0 0x... in npy_memchr third_party/py/numpy/core/src/multiarray/common.h:277:35
    #1 0x... in array_boolean_subscript third_party/py/numpy/core/src/multiarray/mapping.c:1113:30
    #2 0x... in array_subscript third_party/py/numpy/core/src/multiarray/mapping.c:1572:30
    #3 0x... in PyObject_GetItem third_party/python_runtime/v3_7/Objects/abstract.c:182:26
...
SUMMARY: UndefinedBehaviorSanitizer: misaligned-pointer-use third_party/py/numpy/core/src/multiarray/common.h:277:35
```

### NumPy/Python version information:

Bug exists at HEAD.

### PR DESCRIPTION
**Pull request by saran-t**
Fixes #21116

### CODE REVIEW

**Comment by seberg** [comment]
Thanks!  We could remove the alignment required flag if we do this change, I think?  I have to admit, I am a bit curious if this is worthwhile and whether it might slow down things a bit.  Or is this actually incorrect and not just the sanitizer being very strict?

If you are up for it, I would be interested whether the `bench_io` benchmarks, pick this up: `python3 runtests.py --bench-compare main --bench bench_io` should work.  (I think they use this code for some of the `copyto` benchmarks.)

**Comment by saran-t** [comment]
I'm pretty busy right now but can probably pick this up sometime in the next couple of weeks. I wouldn't be surprised if this actually makes things a bit faster on largeish arrays. As thing stands if the array isn't uint-aligned then you would be _repeatedly_ performing unaligned reads in the coarse-grained loop, and these may or may not come with a performance penalty (see e.g. https://stackoverflow.com/questions/70964604).

We can also replace the modulo calculation with `switch sizeof(unsigned int)` and bit shifts, assuming that `sizeof(unsigned int)` is a power of two (which is a safe assumption on any platform). Since the `switch` condition is a compile-time constant there shouldn't be any runtime branching. If we do that then I would not expect the change to have any noticeable negative performance impact (famous last words 🙂 ).

**Comment by saran-t** [comment]
I'm pretty busy right now but can probably pick this up sometime in the next couple of weeks. I wouldn't be surprised if this actually makes things a bit faster on largeish arrays. As thing stands if the array isn't uint-aligned then you would be _repeatedly_ performing unaligned reads in the coarse-grained loop, and these may or may not come with a performance penalty (see e.g. https://stackoverflow.com/questions/70964604).

We can also replace the modulo calculation with `switch sizeof(unsigned int)` and bit shifts, assuming that `sizeof(unsigned int)` is a power of two (which is a safe assumption on any platform). Since the `switch` condition is a compile-time constant there shouldn't be any runtime branching. If we do that then I would not expect the change to have any noticeable negative performance impact (famous last words 🙂 ).

**Comment by seberg** [comment]
> repeatedly performing unaligned reads

Well, we are also interested in random arrays (i.e. we should aim to do well for short loops) – OTOH short loops have a lot of other overheads, so it may not matter there.  The % will be optimized away, no problem.
I ran a quick test locally, and annoyingly it is the test that should _not_ notice this change at all that slows down (i.e. where this loop just keeps going) – and the case that should bail out right away _once_ (use the other branch mostly) is much faster...  

Possibly just random, or the additional code makes gcc do some different optimization choices.  The more "mixed" cases, seem to barely notice though.
May, need to time it more manual if I want results that can be trusted...

**Comment by saran-t** [comment]
Thanks! In the meantime, I found a reference for a real situation where this UB can result in a real crash: https://blog.quarkslab.com/unaligned-accesses-in-cc-what-why-and-solutions-to-do-it-properly.html

**Comment by seberg** [comment]
@saran-t we test on platforms that do not support unaligned access.  This code path is only taken when that define evaluates to 0, which is only the case on selected CPUs/platforms.  So we _know_ that this is OK.  Unless, the compiler goes one step further and optimizes this for SIMDs that have higher alignment requirements somehow.

**Comment by saran-t** [comment]
Ah, fair enough.

**Comment by seberg** [comment]
Considering that my timings were a bit mixed, I am somewhat tempted to close this.  At least unless we see it as a speed-enhancement on CPUs that do not support this unaligned access.

Or is that sanitizer warning problematic? (since I don't think the sanitizer is right to worry here.)

**Comment by saran-t** [comment]
The issue with the sanitizer firing is that it means that we cannot use UBsan to detect bugs in our own code that depends on NumPy. An alternative "fix" would be to add ` __attribute__((no_sanitize("alignment")))` to the function, guarded behind `#ifdef __clang__`.

**Comment by charris** [comment]
What is the status of this?

**Comment by seberg** [comment]
Let me make a PR adding the attribute on clang for now, so we can backport that.

I do think there may be value in this (or similar changes) in terms of optimizing this code.  But, right now, as far as I understand, the code is correct; and clang is only half correct (in the sense that it affects some platforms, but is OK on the one where it is run).

And since I am not sure that this might not slow down certain common code paths, I think optimization would be nice with benchmarks and a bit more care.

**Pull request closed without merging**
