### PR TITLE
[Don't merge] GSoD - Testing current version of new sphinx theme

### PR DESCRIPTION
**Pull request by Shekharrajak**
Build using https://github.com/Shekharrajak/scipy-sphinx-theme-v2/pull/28

Latest build: http://generated-numpy-docs-28.surge.sh/

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Inside numpy/doc/scipy-sphinx-theme-v2 folder run `grunt --project=docs` command to generate the docs for the `numpy/doc/source` folder. Build will be generated in `numpy/doc/source/build` folder.

**Comment by Shekharrajak** [comment]
Build for the https://github.com/Shekharrajak/scipy-sphinx-theme-v2/pull/28 is deployed at: 

https://generated-numpy-docs-28.surge.sh

**Comment by Shekharrajak** [comment]
Previous build : 

Build using Shekharrajak/scipy-sphinx-theme-v2#20

Latest build: http://generated-numpy-docs-23.surge.sh/

**Comment by Shekharrajak** [comment]
I was getting latex error `* file not found`. To resolve the issue we need to install http://www.tug.org/mactex/mactex-download.html

**Comment by Shekharrajak** [comment]
Working Search box version is at https://github.com/numpy/numpy/pull/14648

**Comment by charris** [comment]
@Shekharrajak Do you still want this open?

**Comment by Shekharrajak** [comment]
Closing it for now. We can refer to the changes I did for the new theme later.

**Pull request closed without merging**
