### PR TITLE
A new PEP for infix matrix multiplication

### PR DESCRIPTION
**Pull request by njsmith**
This is now PEP 465, and a properly rendered version can be found here [here](http://legacy.python.org/dev/peps/pep-0465).

A poorly rendered version of the latest draft can be found [here](https://github.com/njsmith/numpy/blob/matmul-pep/doc/neps/return-of-revenge-of-matmul-pep.rst).

Let's use this PR as a central place to discuss this draft PEP for adding an infix matrix multiplication operator to numpy. The PR format is nice in that it allows line by line comments, updating, etc.

Hopefully this goes without saying, but just in case: **We especially welcome comments about how the proposal will work for non-numpy projects (or could work, with fixes)**; this proposal started in the numpy community but the idea here is to build a consensus about how to make Python better for _all_ projects that care about linear algebra.

Some possible points of discussion:
- Does this in fact seem like a good idea?
- Do people agree with the points where I claim "there is consensus that..."? (You can search on "consensus")
- Any suggestions on making the argument stronger and clearer?

### CODE REVIEW

**Comment by jiahao** [comment]
Super late to the party, but I'd like to cross-reference JuliaLanguage/julia#4774 here, where it looks like very similar discussions have taken place in the context of how to define vector transposition.

**Comment by owendavey** [comment]
Re the use of a potential @@ operator.  In a lot of mathematical contexts, we actually consider exp(A) for some matrix A.  exp(A)=I + A A@@2/2! + A@@3/3! + A@@4/4! + .... continuing like the Taylor Series.  Other useful contexts for the @@ operator exist, but it is definitely specifically for math people and may be noise to most non-scientific programmers.

**Comment by dimpase** [comment]
On 30 January 2016 at 17:12, owendavey <notifications@github.com> wrote:

> Re the use of a potential @@ operator. In a lot of mathematical contexts,
> we actually consider exp(A) for some matrix A. exp(A)=I + A A@@2/2! + A@@3/3!
> + A@@4/4! + .... continuing like the Taylor Series. Other useful contexts
> for the @@ operator exist, but it is definitely specifically for math
> people and may be noise to most non-scientific programmers.
>

In computer graphics, one multiplies matrices a lot. Considering that this
is certainly going beyond "science",
I don't quite understand what you meant to say.

**Comment by owendavey** [comment]
@dimpase - I was not referring to matrix multiplication.  I was referring to matrix exponentiation - hence the double @ operator which above seems to have been considered not important enough to be added in addition to the single @ operator of matrix multiplication for this PEP.

**Comment by rkern** [comment]
The discussion here has ended. The PEP has been accepted and implemented. If you would like to propose or discuss the merits of further changes, please find an appropriate mailing list. Thanks.

**Pull request merged**
