### PR TITLE
DOC: dark theme css rules

### PR DESCRIPTION
**Pull request by tupui**
* Add some CSS rules to make the theme nicer in dark mode
* Add dark version of the logo (hand modified version of the current svg)

I also remove the need to prefix the switcher identifier with `doc/` (see https://github.com/numpy/doc/pull/11)

cc @seberg and not sure who's in charge of your graphical guidelines.

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
Generally +1 on this, especially since it syncs the styling back up with what's used in scipy. I know I've mentioned this before, but is this something that could/would be upstreamed into the theme itself? The fewer project-specific style changes we have to maintain, the better!

**Comment by tupui** [comment]
> I know I've mentioned this before, but is this something that could/would be upstreamed into the theme itself? The fewer project-specific style changes we have to maintain, the better!

Agreed. The colour part is specific to each projects, but the card part is common. I remember talks about moving away from this though. Or maybe I am confusing this with something else (panel thing).

**Review by seberg — APPROVED** [review]
LGTM, so will probably just merge later today.  If you have an opinion @MarsBarLee please comment, but we can always follow up with tweaks as well.

The one thing I am curious about is the logo coloring.  @isabela-pf may have an opinion on it.  I think it is OK, but the perfectionist thing may be to bless a specific color and add it to `numpy/branding` (and if just using white rather than the inversion created off-white).

Right now the logo on the website does not exist (the NumPy text has the same color as the "N" normally) and our "light" versions are just plain wite.

**Comment by tupui** [comment]
Ah I was looking for that thanks https://github.com/numpy/numpy/blob/main/branding/logo/primary/numpylogolight.png

Seems like this one should be used instead?

**Comment by seberg** [comment]
Well, that is a monochrome version and feels more like for scaled down places (or just less prominent ones);  not for the large "main" logo?

**Comment by tupui** [comment]
Agreed that it does not look like a "proper" dark mode version.

**Pull request merged**
