### PR TITLE
BUG: Quantile now casts properly (#22766)

### PR DESCRIPTION
**Pull request by MatteoRaso**

### CODE REVIEW

**Comment by seberg** [comment]
As mentioned on the issue, I am tempted to close this and rather consider fixing `.take` the correct thing (and maybe the docs), since it doesn't mention "same-kind" casting.  (I doubt it matters much for end-users much, but is imprecise.)

Happy about disagreement, but without it, may just close in a bit.  Sorry about that @MatteoRaso and thanks for opening a PR.  With these things there is always some decision about _what_ should be changed and in this particular case I tend to see this as the wrong direction.

**Comment by MatteoRaso** [comment]
I'm a bit confused. Isn't the problem with `take` that it also uses a bad casting parameter? If that's the case, then shouldn't we change the casting parameter for that as well? I'm not entirely sure what `take` has to do with my PR, anyways.

**Comment by seberg** [comment]
Quantile sometimes uses same-kind casting and sometimes nonsense casting (which should be same-kind), because it uses `np.take`.
I am arguing the current same-kind casting is correct (what we use the most in numpy), so the _other_ path should be fixed.  And that other path is inherited from take.

**Comment by MatteoRaso** [comment]
> Quantile sometimes uses same-kind casting and sometimes nonsense casting (which should be same-kind), because it uses `np.take`. I am arguing the current same-kind casting is correct (what we use the most in numpy), so the _other_ path should be fixed. And that other path is inherited from take.

That makes sense. Closing PR.

**Pull request closed without merging**
