### PR TITLE
API: Remove The MapIter API from public

### PR DESCRIPTION
**Pull request by seberg**
This API is very slow to use compared to normal advanced indexing
(which reaches deep into the much richer internals).
Making this fast is difficult and the only known users is Theano:
* While probably still in use Theano is end-of-life for a long time.
* The use-case in Theano would be better served with `ufunc.at` or
  direct advanced indexing use probably (even if that requires
  wrapping into NumPy arrays).  Because it will be vastly faster
  normally.

So remove it (make it private) to allow making the ABI of it not be
a strange mix for backwards compatibility.

---

It could also make sense to only make the struct almost fully opaque (with some macros to fetch the pointers needed in a version agnostic way).  But considering that the only user is Theano, and that this is rather complicated...

Looking it partially, because I think we we need to improve `ufunc.at`.  At that point we won't use the "truly" public portion of the API anymore, ourselves.

### CODE REVIEW

**Comment by rkern** [comment]
While Theano per se is EOL, the codebase continues on as [Aesara](https://github.com/aesara-devs/aesara), which is the foundation for PyMC. Worth checking there.

**Comment by seberg** [comment]
Ouch!  Pinged them there.  While I think that using `np.add.at` is good, it does require a newer NumPy version to get good performance (and some paths will still have terrible performance).

Will close it for, I still want to stop using the slow API internally, but probably little point in breaking them just yet.

**Comment by seberg** [comment]
Seems like Aesara is deprecating that code, so I might revive it after all: https://github.com/aesara-devs/aesara/issues/1506

**Comment by seberg** [comment]
A major reason would be part of lifting the 32 maxargs/maxdims limit in the iterator, given the above, I think we should not let this hold the maxdims/maxarg lifting back.

**Pull request closed without merging**
