### PR TITLE
WIP, DOC: add skeleton release note for 1.17

### PR DESCRIPTION
**Pull request by mattip**
Add a release note for 1.17 so new PRs can modify it

### CODE REVIEW

**Comment by charris** [comment]
Normally this is added as part of the master branch update after the maintenance branch is made, otherwise it will be included in that branch for no particular reason. The other things that come along with it are an `doc/source/release.rst` entry, fixups to the version number in `setup.py`.  and updated release note entry in `pavement.py`. I've put a `wip` on this to keep it from being merged prematurely.

**Comment by tylerjereddy** [comment]
Could use a wiki page to collect release notes? I know SciPy does this closer to a release to avoid conflicts. Not sure if NumPy has a reason not to do that.

Slightly annoying to have a different format on wiki vs. the text file (release manager has to reformat at copy/paste near release time), but not nearly as annoying as the fishing expedition for missing release notes.

**Comment by charris** [comment]
Looks like the removal in #12402 is meeting strong resistance. I think we should close both this and that PR and simply put a compiler warning in `noprefix.h`.

**Comment by mattip** [comment]
Lets give it some more time. SciPy is already compliant, matlab is next. The newer a codebase is the easier it is to update, there are only a handful old enough to have the problem.

People using this already get a compiler warning since they do not define `NPY_NO_DEPRECATED_API`, so another warning is not likely to have much effect

**Comment by charris** [comment]
I'm thinking we should just leave it in. It costs us nothing, and if it eventually causes problems downstream I don't thing that is our problem.

**Comment by charris** [comment]
Conflicts with #12506.

**Pull request closed without merging**
