### PR TITLE
DOC: Clarify ``where`` docs

### PR DESCRIPTION
**Pull request by evensong**
DOC: x=None, y=None instead of [x,y]/ in numpy.where()

x and y are optional variables. [x,y]/ is Backus-Naur Form to show optional arguments, but the [] operator is used so frequently in lists and as an accessor that to a programmer unfamiliar with this form becomes ambiguous. Writing that x and y default to None is more explicit and is easily readable without assuming knowledge of 1970's documentation standards.

### CODE REVIEW

**Comment by mattip** [comment]
> Writing that x and y default to None is more explicit

The function definition is masked by the decorator, and the actual function being called ([`array_where`](https://github.com/numpy/numpy/blob/742545f1336e7cd12cdf656792c44b90b9f0f4b9/numpy/core/src/multiarray/multiarraymodule.c#L3434) has `x` and `y` as optional positional arguments. Either both must be missing (in which case the call is equivalent to `np.nonzero`) or both must be arrays. The defaults in `def where(condition, x=None, y=None)` are never used.

**Comment by mattip** [comment]
xref issue #22627

**Review by eric-wieser — CHANGES_REQUESTED** [review]
Reiterating my comment on the issue, these arguments do _not_ have defaults of `None`. You can test that by passing `None` instead of omitting the argument:
```python
In [1]: import numpy as np

In [2]: np.where(True, None, None)
Out[2]: array(None, dtype=object)

In [3]: np.where(True)
Out[3]: (array([0]),)
```

**Comment by evensong** [comment]
Agreed, the issue was lack of knowledge on my part. Sorry to waste time, I hope my future contributions will be more helpful!

**Pull request closed without merging**
