### PR TITLE
WIP, ENH: Add the function `expanded_view`

### PR DESCRIPTION
**Pull request by jakirkham**
Takes an array and provides view of it with dummy dimensions of arbitrary length tacked on to either side.

I know this is going to need a lot more clean up and moving around before it is mergeable, but I would like to get the process started soon as I am interested in getting this function into the hands of other users.

### CODE REVIEW

**Comment by shoyer** [comment]
New API needs to be discussed on the mailing list, so I would recommend posting a proposal there.

It seems like this function has a lot of overlap with `np.broadcast_to`, which we added in v1.10.

**Comment by jakirkham** [comment]
Ah, ok. Sorry, I was unclear. Will do.

I saw your proposal for `broadcast_to` and I think it is a nice one and was happy to see it enter the library. A function of this sort was desperately needed in the library.

That being said, I think there are some significant differences from what I am proposing here. This tacks on additional dimensions on *either* side of the array as specified by the user. It does this in a bit clearer way by *not including* the shape of the original array. Finally, it allows for read and *write* access of the original array.

If at the end of this my proposal is rejected and a bit more control is provided through `broadcast_to`, I would be ok with that.

**Comment by seberg** [comment]
Could you maybe give a use case example? Tagging dimensions to the front or end, if it is just one or two, I personally use indexing `arr[np.newaxis, ..., np.newaxis]` (though at the font is usually unnecessary).
Also in many cases repeating those axes is unnecessary, since broadcasting already does this implicitly. Note that `writing` is possible in broadcast_to I think with passing in the keyword argument? Or at least, we said we would add it if someone asked for it. Though write access to a stride tricks array is *dangerous* and often *unpredictable* (or relies on implementation details that should not be relied on).

**Comment by jakirkham** [comment]
Add this to the mailing list here ( http://www.mail-archive.com/numpy-discussion@scipy.org/msg49147.html ).

**Comment by jakirkham** [comment]
I used this in a variety of different cases in image processing.

Often this came in handing because broadcasting failed for whatever reason. It also was handy when I wasn't sure how many dimensions I would need in advance (e.g. handling various numbers of dimensions) so writing some number of `np.newaxis`s or `None`s wouldn't cut it. Doing nasty multiplications of tuples with such objects could be done, but just made the code more unreadable. In short, I feel all of these types of solutions end up forcing the developers to think about how the shape is working and not more important issues like whether the algorithm is working.

Whereas writing something like this `expand_view(b, reps_before=a.shape[:-1])`, it is immediately clear that I want a view of `b`, whose shape will be the same as `a`'s except for the last axis.

**Comment by jakirkham** [comment]
I tried to respond to some peoples comments and questions on the mailing list and it appears to have gone out. Though I have seen the mailing list has had issues in the past so I figured I should mention it here so people are aware. Here's the link to what I wrote. ( http://www.mail-archive.com/numpy-discussion@scipy.org/msg49462.html )

**Comment by jakirkham** [comment]
I have decided to put this in it's own library for now with a couple general cases that I use it for. It is called [`xnumpy`]( https://github.com/jakirkham/xnumpy ) (for lack of a better name 😉). Feel free to take a look if you are interested.

Given that I have done this and there doesn't seem to be interest in this at NumPy, I'm not going to pursue integrating it with NumPy at this time. However, if there is growing interest in integrating this with NumPy in the future, I'm not against revisiting integration.

Thanks everyone for your comments.

**Pull request closed without merging**
