### PR TITLE
added NumPy logo and separator

### PR DESCRIPTION
**Pull request by philipgura**

### CODE REVIEW

**Comment by charris** [comment]
Thanks @philipgura . The travis link could also use a label as to what it is.

**Comment by njsmith** [comment]
Do we want to add an appveyor image too while we're at it?

**Comment by pv** [comment]
The travis badge btw does not load the image currently --- maybe replace with (copied from the travis page)
```
[![Travis-CI status](https://travis-ci.org/numpy/numpy.svg?branch=master)](https://travis-ci.org/numpy/numpy)
```
[Travis-CI status](https://travis-ci.org/numpy/numpy)

**Comment by philipgura** [comment]
Travis link replaced and more descriptive label added.

**Pull request merged**
