### PR TITLE
DOC: add Quansight Labs as an Institutional Partner

### PR DESCRIPTION
**Pull request by rgommers**
`[ci skip]` `[skip ci]`

tl;dr @hameerabbasi and myself have funded time to work on NumPy, which qualifies Quansight Labs as an institutional partner

I'll post a message to the mailing list related to this.

### CODE REVIEW

**Comment by seberg** [comment]
I don't think Hameer is currently on the other list :), could be something to discuss though.

**Comment by rgommers** [comment]
> I don't think Hameer is currently on the other list 

He doesn't need to be, https://docs.scipy.org/doc/numpy/dev/governance/governance.html#institutional-partners-and-funding says: 

"... by participating in the Project as Contributors and Council Members. However, because institutions can be an important funding mechanism for the project, it is important to formally acknowledge institutional participation in the project. These are Institutional Partners.


An Institutional Contributor is any individual Project Contributor who contributes to the project as part of their official duties at an Institutional Partner."

We also don't list core developers that are not on the Steering Council.

> could be something to discuss though.

Indeed, Hameer has already done quite a bit (e.g. co-author NEP 18, a number of PRs).

**Comment by seberg** [comment]
Ohh, good point, I am happy with listing him, seemed a bit odd on first sight. I suppose it is also something that Quansight can think about.

**Comment by rgommers** [comment]
The one minor thing I saw in the governance doc is that it doesn't state a minimum contribution level (e.g. in number of hours). Having someone with an "official duty" in their job description to contribute 15 minutes per week doesn't quite meet the bar I think:)

Not sure what the right level should be though. Half a day per week at least? That's equivalent to a $25k/year contribution for an employer, which feels like a good level.

**Comment by mattip** [comment]
> it doesn't state a minimum contribution level 

I would prefer to not quantify it.

as **a substantial** part of their official duties at an Institutional Partner

alternatives: significant, meaningful

**Comment by rgommers** [comment]
> as a substantial part of their official duties at an Institutional Partner

> alternatives: significant, meaningful

yes, that's a good idea

**Comment by hameerabbasi** [comment]
I kinda feel humbled there would even be a discussion about adding my name to that list -- I certainly don't feel I've done enough. However, it's certainly very welcome, and I do average around half a day or more to NumPy, depending on whether I'm actively working on PRs. I could dedicate more time to review when it's needed.

**Comment by rgommers** [comment]
I only have a vague memory as well about why we added @stefanv but not @mattip or @tylerjereddy. Maybe I'm imagining that, and we just forgot to update this list. Matti and Tyler should be listed too I think. They're paid from a grant rather than by BIDS itself, but I don't think that as a project we should care about that. Their job description includes "work on numpy" and we're happy about that, so they should be listed. @stefanv does that make sense?

**Comment by charris** [comment]
I'd feel fine about adding everyone working on numpy and paid to do so by another organization. What about NumFocus?

**Comment by rgommers** [comment]
> What about NumFocus?

Hmm, that's a good one. We should list them here probably. Not sure as an Institutional Partner or separately as our Fiscal Sponsor - their role and our relationship is a bit different than how we describe Institutional Partners.

**Comment by stefanv** [comment]
@rgommers Maybe it used to be Nathaniel's name, before there were people at BIDS.  It makes sense to add the whole team.  Sebastian's name too?

**Comment by rgommers** [comment]
> Sebastian's name too?

Of course that is fine with me. You realize that this is the public announcement of Sebastian joining right? (feel free to edit both my comment and your own if you want)

**Comment by rgommers** [comment]
After reviewing https://docs.scipy.org/doc/numpy/dev/governance/governance.html, it talks fairly extensively about NumFOCUS' relationship with NumPy. This is clearly different from how we describe Institutional Partners, so listing NumFOCUS as an institutional partner as well would be odd. Also, the time spent by each person at NumFOCUS is probably not "substantial" given that they act on behalf of and work for ~50 projects. So I'd like to leave NumFOCUS out of this PR.

**Comment by rgommers** [comment]
Anyone know what the deal is with Azure not listening to `[skip ci]`? It's documented to work: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits

**Comment by charris** [comment]
@rgommers I don't recall it working before, but there was a different string that did work (`**no ci**`?). Maybe our azure app is outdated? Azure is fast enough that is isn't a big deal, but it would be nice if it worked.

**Comment by charris** [comment]
Maybe we can enable for the pipeline triggers?

**Comment by charris** [comment]
LGTM, thanks Ralf.

**Pull request merged**
