### PR TITLE
TST: Refactor to consistently use CompilerChecker

### LINKED ISSUE #27045: BUG: tests depend on availability of fortran compiler
In numpy 2.0.1, there's a failing test in [conda-forge](https://github.com/conda-forge/numpy-feedstock/pull/321) (`f2py/tests/test_regression.py::test_gh25784`)

<details>
<summary>Logs</summary>

```
=========================== short test summary info ============================
FAILED f2py/tests/test_regression.py::test_gh25784 - RuntimeError: Running f2py failed: ['-m', 'Blah', "--f77flags='-ffixed-form -O2'", '--f90flags="-ffixed-form -Og"', '/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpcxdbx4rs/f77fixedform.f95', '--backend', 'meson']
Using meson backend
Will pass --lower to f2py
See https://numpy.org/doc/stable/f2py/buildtools/meson.html
Reading fortran codes...
	Reading file '/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpcxdbx4rs/f77fixedform.f95' (format:free)
Line #2 in /var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpcxdbx4rs/f77fixedform.f95:"      subroutine mwe( "
	analyzeline: No name/args pattern found for line.
Post-processing...
	Block: Blah
			Block: unknown_subroutine
Applying post-processing hooks...
  character_backward_compatibility_hook
Post-processing (stage 2)...
Building modules...
    Building module "Blah"...
    Generating possibly empty wrappers"
    Maybe empty "Blah-f2pywrappers.f"
        Constructing wrapper function "unknown_subroutine"...
          unknown_subroutine()
    Wrote C/API module "Blah" to file "./Blahmodule.c"
The Meson build system
Version: 1.5.0
Source dir: /private/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpp3kn95v4
Build dir: /private/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpp3kn95v4/bbdir
Build type: native build
Project name: Blah
Project version: 0.1

meson.build:1:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
The following exception(s) were encountered:
Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"

A full log can be found at /private/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpp3kn95v4/bbdir/meson-logs/meson-log.txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 769, in main
    run_compile()
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 741, in run_compile
    builder.compile()
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/_backends/_meson.py", line 193, in compile
    self.run_meson(self.build_dir)
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/_backends/_meson.py", line 186, in run_meson
    self._run_subprocess_command(setup_command, build_dir)
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/_backends/_meson.py", line 182, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
  File "$PREFIX/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['meson', 'setup', 'bbdir']' returned non-zero exit status 1.
1 failed, 48842 passed, 2696 skipped, 70 xfailed, 9 xpassed, 12 warnings in 194.61s (0:03:14)
```

</details>

Although it wouldn't be a big issue to add the fortran-compilers as a test-dependency, the decision the last time this happened (#21621; https://github.com/conda-forge/numpy-feedstock/pull/272) was that tests should not fail in this case.

CC @HaoZeke

### PR DESCRIPTION
**Pull request by HaoZeke**
Closes #27045, by using the `CompilerChecker` object to make sure tests which would need a compiler are skipped correctly. 

**TODO**

- [x] Documentation addition detailing the no-compiler and `CompilerChecker` bits in `f2py-testing.rst`.

**Implementation note**
- `CompilerChecker` basically runs `meson`, so if there are environments where the tests may be run without `meson` being installed at all then this needs to be reworked.
  - ~~Like all the failing Windows builds~~ In these scenarios the compiled tests can be skipped anyway.
- Soft reverts [17f529a](https://github.com/numpy/numpy/commit/17f529a2682660b563fb87acebbf5413c382fc0b)

### CODE REVIEW

**Comment by HaoZeke** [comment]
The remaining test failures on Windows are real errors, not related to the compiler presence, which were previously being suppressed. (though I might still end up skipping them for now since they seem to be linking errors, i.e. system configuration related issues).

**Comment by mattip** [comment]
Is skipping windows f2py CI critical enough that this should wait for #25134?

**Comment by HaoZeke** [comment]
> Is skipping windows f2py CI critical enough that this should wait for #25134?

I think skipping here is OK since this PR is mostly to unblock `conda-forge`, reported in #27045.

However, I'll try to get #25134 ready ASAP, just need to find some time to test on a clean Windows machine.

**Comment by HaoZeke** [comment]
Should be good to go for now.

**Comment by rgommers** [comment]
Thanks @HaoZeke! Changes LGTM; I'm testing this the lazy way to be sure: pushed a commit to trigger wheel builds.

**Comment by rgommers** [comment]
> `CompilerChecker` basically runs `meson`, so if there are environments where the tests may be run without `meson` being installed at all then this needs to be reworked.

It's a required test dependency also outside of `f2py`, so should be fine. Only `ninja` may be missing in a Pyodide environment, but CI wasn't complaining.

**Review by rgommers — APPROVED** [review]
All happy, so let's give it a go - thanks Rohit!

**Pull request merged**
