### PR TITLE
MAINT: Update README.md with badges

### PR DESCRIPTION
**Pull request by charris**
Adds badges for
    
    - NumFocus
    - downloads from Pypi and Conda
    - link to stackoverflow
    - link to Nature paper

There are also commented out badges for test results that can be activated if desired. They aren't deleted because they can be a bit tricky to get right.

### CODE REVIEW

**Comment by mattip** [comment]
The [README on your branch](https://github.com/charris/numpy/tree/update-readme) is what it will look like?

**Comment by charris** [comment]
Comments on layout welcome. There is an existing Numfocus badge at the bottom, should it be moved?

**Comment by charris** [comment]
@mattip You can view the file to see what it looks like, use the drop down menu that also has the `edit` option.

**Comment by seberg** [comment]
I personally don't have much love for the testing badges (I just don't see much point and sometimes they indicate nonsense errors).  But I do like the new second line!  (And I don't dislike the testing ones to care and for all I know there may be an expectation that I don't understand)

Moving the the numfocus badge to the top seems like a good idea to me if we have this new line, it feels not too out of place with the DOI there as well?

**Comment by charris** [comment]
@seberg Pretty much agree about the first line. The second line is good advertising.

**Comment by tupui** [comment]
I also think the CI information is not very helpful. It can just scare away someone which is just passing by and would not know the project. It just does not give confidence even if in the end we know that nothing is published without a passing CI.

I added it in SciPy because it used to be there, but I will propose to remove it too. Also good thing about the numfocus badge. Although we could argue that Tidelift should then be there??

**Pull request merged**
