### PR TITLE
CI: Update cirrus nightly wheel upload token

### PR DESCRIPTION
**Pull request by seberg**
This updates the encryption key, I am not sure about the ! marks. Ping @andyfaff and @tupui. 

But I will just merge this myself it cannot break anything (and it should be broken currently).

### CODE REVIEW

**Comment by andyfaff** [comment]
The stuff in the square brackets should be whatever is returned by the encryption process. If there's no starting exclamation mark returned by that then I would assume that one isn't needed.

It's kind of hard maintaining  CI without access to keygen.

**Comment by tupui** [comment]
I suppose we should also do this for SciPy @rgommers?

**Comment by charris** [comment]
I'm thinking we should also reschedule the uploads to be a closer match with github actions.

**Comment by seberg** [comment]
Yeah, it was... Just a bit surprised it was there before and now is not... Maybe cirrus uses it to indicate how to decrypt things.

**Pull request merged**
