### PR TITLE
MAINT: Better error message for norm

### PR DESCRIPTION
**Pull request by larsoner**
While testing https://github.com/cupy/cupy/pull/2355 I found I was getting this error:
```
E     File "/home/larsoner/python/cupy/tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py", line 76, in test_ifft_overwrite
E       **overwrite_kw)
E     File "<__array_function__ internals>", line 6, in ifft
E     File "/home/larsoner/python/numpy/numpy/fft/pocketfft.py", line 274, in ifft
E       fct = 1/n
E   ZeroDivisionError: division by zero
```
This fixes it by ensuring the correct, more informative error message is emitted.

### CODE REVIEW

**Comment by charris** [comment]
Thanks @larsoner .

**Comment by charris** [comment]
Is it assured that an error message is still raised when `n == 0`? Is it checked elsewhere?

**Comment by charris** [comment]
Why not raise an error when `n == 0` instead of setting it to 1?

**Comment by charris** [comment]
I may have merged too soon...

**Comment by larsoner** [comment]
> Why not raise an error when n == 0 instead of setting it to 1?

Because just a little bit downstream an informative error is already going to be raised. This just delays it (presumably) a few microseconds.

> Is it assured that an error message is still raised when n == 0? Is it checked elsewhere?=

Yes indeed, the test checks this explicitly with `pytest.raises(...)`.

**Pull request merged**
