### PR TITLE
MAINT: random: Remove unused empty file binomial.h.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
The file numpy/random/src/distributions/binomial.h was empty and unused.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can we remove `zigurrat.h` from the same folder too? It seems to have been replaced by `zigurrat_constants.h`

**Comment by WarrenWeckesser** [comment]
Eric, it looks like there are still a few scalar constants defined in `ziggurat.h` that are used in `distributions.c`.  They can probably be moved to `ziggurat_constants.h`, and then `ziggurat.h` could be removed.  I can make that change in another pull request.

**Review by eric-wieser — APPROVED** [review]
Obviously safe. Perhaps @rkern knows if this was supposed to contain something, but either way deleting it is an improvement

**Comment by rkern** [comment]
Not mine. It's from [`bashtage/randomgen`](https://github.com/bashtage/randomgen/blob/master/randomgen/src/distributions/binomial.h), probably vestigial in the refactor from [`bashtage/ng-numpy-randomstate`](https://github.com/bashtage/ng-numpy-randomstate/blob/master/randomstate/src/common/binomial.h).

**Pull request merged**
