### PR TITLE
ENH,TST: Bump stacklevel and add tests for warnings

### PR DESCRIPTION
**Pull request by seberg**
This is related (and relies upon the suppressed warnings pull request). The tests will not be successfully (one of them actually checks things only fixed in the other one, and I would be surprised if the stacklevel bump does not create test failures on its own.

### CODE REVIEW

**Comment by seberg** [comment]
Seems the stacklevel bump does not create new warnings on its own, so if wanted, I could split of the tests.

**Comment by seberg** [comment]
Sorry, no, creates an extra warning on Python 2. (whatever the reason it survives in Python 3, did not check). Are the slow tests not run on travis (or not on python 3)? Since the new test should fail.

**Comment by rgommers** [comment]
Note that this is a superset of gh-6424.

**Comment by charris** [comment]
Interesting failures ;)

**Comment by charris** [comment]
@seberg Needs rebase.

**Comment by seberg** [comment]
The test part of this, needs the suppressed warnings thing merged anyway. Can split it off (and do the rebase) though if you like.

**Comment by charris** [comment]
@seberg  `suppress_warnings` has been merged, what do you want to do with this?

**Comment by seberg** [comment]
If everyone still likes changing stack level, I guess clean it up and put it in. The test added also checks the other PR though, so will do that first unless you prefer to split the stacklevel stuff off.

**Comment by seberg** [comment]
OK, rebased against master and (new) tests passing.

**Comment by charris** [comment]
Ah, another 39 files with modifications. Homu will come calling. Thanks Sebastian ;)

**Comment by seberg** [comment]
Hehe :).

**Pull request merged**
