### PR TITLE
BUG: Fix order='K' behavior for tobytes

### LINKED ISSUE #16569: BUG: `order='K'` behavior for `tobytes`
The `tobytes` method of ndarray accepts `'K'` for the order keyword argument, but appears not to keep the order as expected:

### Reproducing code example:

```python
>>> a = np.array([[1, 2], [3, 4]], dtype=np.uint8, order='F')
>>> a.ravel('K')   # Keep array order
array([1, 3, 2, 4])
>>> a.tobytes('K')  # Expect consistency with ravel
b'\x01\x02\x03\x04'
```
See https://github.com/numpy/numpy/pull/16291#discussion_r426861913 and #16328 for related discussion. 

 - [ ] Fix bug (see #16328)
 - [ ] Update `tobytes()` docstring to add `K` option to `order=` (see: https://github.com/numpy/numpy/blob/68ebc2bad1ad6a99e9939eff205a1a6d936cf4fd/numpy/core/_add_newdocs.py#L3933-L3950)

### Numpy/Python version information:

1.20.0.dev0+1d799fd 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]

### PR DESCRIPTION
**Pull request by shubham11941140**
The tobytes method of ndarray accepts 'K' for the order keyword argument, but appears not to keep the order as expected.

# Reproducing Code Example:
```
>>> a = np.array([[1, 2], [3, 4]], dtype=np.uint8, order='F')
>>> a.ravel('K')   # Keep array order
array([1, 3, 2, 4])
>>> a.tobytes('K')  # Expect consistency with ravel
b'\x01\x02\x03\x04'
```
The above stated test case 

This edit in the "convert.c" file actually solves the tobyte conversion issue. It parses the array and converts each value to the necessary byte value as expected.
Reviving #16328
"Fixes #16569"

### CODE REVIEW

**Comment by mattip** [comment]
At the very least this PR should have some text description
- what problem does it solve
- what issue is it related to

There should also be tests that fail before the PR and pass after

**Comment by shubham11941140** [comment]
Sure, I will write a description.

**Comment by shubham11941140** [comment]
There are no conflicts and all checks have passed, please merge it with the main, so I can close the Pull Request.

**Comment by mattip** [comment]
> There are no conflicts and all checks have passed, please merge it with the main, so I can close the Pull Request.

That is not the way this works. Your PR will be reviewed. If there are no corrections or modifications needed (which is rare), and if it does not require further consideration, it may be merged. If it is not commented on for week, then you can ping with a reminder, but certainly not after 2 hours.

**Comment by mattip** [comment]
If the PR is meant to solve an issue, please use the magic incantation "Fixes #16569" so github will connect the two and close the issue if the PR is merged. Note how after I made this comment the "Linked issues" section on the right hand side now relates to that issue.

**Comment by shubham11941140** [comment]
I think this should do, it is ready to be merged.

**Comment by mattip** [comment]
It is not ready to be reviewed. You need to add a test. I would suggest `numpy/core/tests/test_multiarray.py`, where `tobytes` is tested.

**Comment by shubham11941140** [comment]
I added a test in ``` numpy/core/tests/test_multiarray.py ```, but build error is coming.

**Comment by shubham11941140** [comment]
Please merge it with main.

**Comment by mattip** [comment]
Rather than requesting a merge, please request a review. It may be only a small semantic difference, but it shows you understand that reviewing code can be as hard as fixing code, and that it may take a few days or weeks for review to happen. Changes like these often have unwanted side effects that must be carefully considered before approval.

**Comment by mattip** [comment]
Where is the test?

**Comment by seberg** [comment]
This looks a lot like it is currently (mostly?) equivalent to gh-16328.   Now that PR was possibly almost practically ready...

I had some pending comments there: 1. `f (needs_api && PyErr_Occurred()) {` is unnecessary, 2. to expand the tests with 3-D examples like `x3d.tobytes("K")` and `x3d.transpose(1, 2, 0).tobytes("K")`.  But have to check whether there was another reason for the stalling, maybe I just thought fast-paths might be good.

**Comment by mattip** [comment]
Ahh, so I think we should close this and continue the work in #16328.

**Comment by shubham11941140** [comment]
The code part that implements the tobytes is almost the same. This passes all the checks.
The previous PR solves the issue but the test fails.
The build is complete on my system and it works.

**Comment by shubham11941140** [comment]
I committed it, so the branch has no conflicts with the base branch and it is ready to merge.

**Comment by eric-wieser** [comment]
This patch seems to match gh-16328 exactly. @shubham11941140, it is fine to copy code from stale PRs, but only if you make it clear what the original PR was and who the original author was (preferably with a `Co-authored-by` line or even by changing the author in the git commit). 

In the likely event that you contribution is to fulfill part of a degree requirement, you are at risk of breaching plagiarism rules, which in many institutions can be a serious offence that if repeated can lead to disqualification from your course.

**Comment by shubham11941140** [comment]
I can do that, but I am unaware of the process. Could you please do that?

**Comment by shubham11941140** [comment]
Ok can you open it again, I will commit again with a different code. Please could you delete the plag comments.

**Comment by shubham11941140** [comment]
Please reopen the PR as I cant open it

**Comment by shubham11941140** [comment]
Please reopen it.

**Comment by shubham11941140** [comment]
@eric-wieser please reopen the PR.

**Comment by shubham11941140** [comment]
I have mentioned revival of PR.

**Comment by shubham11941140** [comment]
Please remove the comments that involve the copy keyword.

**Pull request closed without merging**
