### PR TITLE
MAINT: Update sphinxext submodule hash.

### PR DESCRIPTION
**Pull request by charris**
Update to numpydoc v0.7.0, needed for sphinx 1.7.0 released 2/12/2018.

This PR also disables the `doc_note` function in `numpy/ma/core.py`. Currently, that function is called to add a "Notes" section to the existing docstrings of the unmasked versions of some functions, which may 
result in duplicate "Notes" sections, or incorrect placement. Those raise errors in current numpydoc.

### CODE REVIEW

**Comment by charris** [comment]
Closes #10595 .

**Comment by pv** [comment]
Different error. Maybe bump it to current numpydoc master...

**Comment by pv** [comment]
... or fix the numpy.ma.inner docstring.

**Comment by charris** [comment]
@pv I disabled the `doc_note` function until we can decide on a fix. I'm tempted to just rewrite the summary part of the docstring, as that looks like the only part that really needs changing for the affected functions. Parsing out the where/if the put the Notes section looks like more work than it is worth for the minor amount of extra content and the summary section always comes first.

**Pull request merged**
