### PR TITLE
DOC: order of indices returned in tril_indices and triu_indices

### LINKED ISSUE #26350: DOC: tril_indices triu_indices order
### Issue with current documentation:

The order of indices in not specified which makes it hard to rely on.

### Idea or request for content:

Document the current behavior and make it part of the function contract:

"The indices returned are sorted first with respect to the row and then the column"

### PR DESCRIPTION
**Pull request by ajayjanapareddi**
Closes #26350

Updated documentation as requested. Kindly review.

### CODE REVIEW

**Comment by mattip** [comment]
I think `ordered` should be `sorted`. Is it rows and columns, or according to the indexes passed in?

**Comment by mattip** [comment]
Actually, this would be better if demonstrated and commented on in the examples, which would make the idea easier to explain.

**Comment by mattip** [comment]
@ajayjanapareddi there are some requests for changes, but the PR seems to have stalled. Will you be continuing to work on it?

**Comment by mdhaber** [comment]
@mattip @melissawm I can finish this up. Hopefully this wording will be difficult to misunderstand, especially next to the example in the documentation.

**Comment by mattip** [comment]
Thanks @ajayjanapareddi

**Pull request merged**
