### PR TITLE
MAINT: Forward port accumulated changes from the 1.12.0 release.

### PR DESCRIPTION
**Pull request by charris**
The following files were updated during the NumPy 1.12.0 release

- .mailmap
- doc/release/1.12.0-notes.rst
- tools/announce.py
- pavement.py

and are forward ported to master by this PR.

[ci skip]

### CODE REVIEW

**Comment by rgommers** [comment]
We've never before forward-ported author names and lists of issues/PRs. It will be very long in the built pdfs. Do you think it adds much?

**Comment by charris** [comment]
The lists are already in there, this just updates them a bit. When I asked about including that info a while back you said it was useful information ;) That said, I have no strong feeling one way or the other and could happily live with only including the lists in the release notifications.

**Comment by rgommers** [comment]
> When I asked about including that info a while back you said it was useful information ;)

New year, new opinion:) No, I don't really mind. PDFs aren't used much anymore anyway, 1500 vs. 1550 pages are not going to be the deciding factor.

I'll hit the green button.

**Comment by charris** [comment]
Fifty pages is a bit much, in a couple of years it will be hundreds. I think I will skip that for the 1.13 release and modify the pavement file to add the authors and PRs to the posting versions.

**Pull request merged**
