### PR TITLE
DOC: Update the f2py section of the "Using Python as Glue" page.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
* Update the output shown for the docstrings generated by f2py.

### CODE REVIEW

**Review by anirudh2290 — APPROVED** [review]

**Comment by WarrenWeckesser** [comment]
Updated to account for changes commited in https://github.com/numpy/numpy/pull/16258

**Review by rossbar — APPROVED** [review]
LGTM - there are a couple of style things that `pycodestyle` would complain about in some of the code examples, e.g. the lack of spaces after commas in the lists on L197:

```python
>>> add.zadd([1,2,3], [1,2], [3,4], 1000)
```

Certainly not a blocker, but might be worth cleaning up if the examples are being updated (L269 has a similar problem)

**Comment by WarrenWeckesser** [comment]
@rossbar, good idea.  I fixed the spacing in the two Python shell inputs, and also fixed the capitalization of Python and Fortran.

**Comment by seberg** [comment]
Thanks Warren and everyone!

**Pull request merged**
