### PR TITLE
MAINT: Refactor sorting header file

### PR DESCRIPTION
**Pull request by liwt31**
This is part of adding timsort to numpy sorting algorithms #12186. 
While trying to modify the header files related to sorting algorithms I find `numpy/core/src/common/npy_sort.h` is verbose and hard-coded. It might be a better idea to use a template `numpy/core/src/common/npy_sort.h.src` (the main part of this PR) to generate the file when building  numpy.
BTW some lines in `.gitignore` labeled as `# Things specific to this project #
` seem outdated. Maybe this should be filed in another issue?

### CODE REVIEW

**Comment by liwt31** [comment]
I assume the codecov report isn't making lots of sense here?

**Review by eric-wieser — APPROVED** [review]
Looks great, thanks. I wonder why this was not done like this to begin with...

codecov failure is garbage, and due to `setup.py` not having any coverage data, even though those lines are obviously executing in order to produce the build

**Comment by charris** [comment]
Thanks @liwt31 .

**Comment by charris** [comment]
> Looks great, thanks. I wonder why this was not done like this to begin with...

The include file was made a couple of years before we started generating include files.  The idea of generating it didn't even occur to me...

**Pull request merged**
