### PR TITLE
DOC: use float64 instead of float128 in docstring

### PR DESCRIPTION
**Pull request by DhavalParmar61**

### CODE REVIEW

**Comment by DhavalParmar61** [comment]
Update function_base.py #23820

**Comment by mattip** [comment]
Closes #23820

**Comment by mattip** [comment]
Thanks @DhavalParmar61

**Comment by DhavalParmar61** [comment]
@mattip I can see changes are reflected on dev document but not on v1.24 or any other version. Should we make changes there as well?

**Comment by rossbar** [comment]
> I can see changes are reflected on dev document but not on v1.24 or any other version. Should we make changes there as well?

No need to do so @DhavalParmar61 - small doc changes like this are often not backported, and if they are they will be included whenever the next patch release for the docs is built.

**Pull request merged**
