### PR TITLE
TST: f2py: Add a doctest for `getlincoef`

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by mattip** [comment]
crackfortran.py is not included in our doc build nor are the doctests run in CI. Trying the doctest locally passes, so putting this in.

**Comment by mattip** [comment]
Thanks @eric-wieser

**Comment by eric-wieser** [comment]
Huh, I thought we found in one of @melissawm's PRs that refguide was still going through this file.

**Comment by mattip** [comment]
Currently it does not, at least not via `python runtests.py --refguidecheck`. 

It will if we add `f2py.crackfortran` to refguidecheck [here](https://github.com/numpy/numpy/blob/v1.19.3/tools/refguide_check.py#L75), but then we will have to fix the non-compliant module docstring and add `>>> from numpy.f2py.crackfortran import getlincoef` to the new doctest.

xref gh-15845 to replace refguidecheck with a better supported solution.

**Pull request merged**
