### PR TITLE
DOC: Recommend the use of `np.ndim` over `np.isscalar`, and explain the differences

### PR DESCRIPTION
**Pull request by eric-wieser**
Brought on by #4701

### CODE REVIEW

**Comment by eric-wieser** [comment]
Current places where we still use `isscalar` internally:

* `assert_equal` - probably harmless
* `linspace` - used as an optimization check without breaking duck-types
* `np.poly1d` - Only used in an optimization path. Since this is pseudo-deprecated anyway, it's not worth touching this..
* `np.matrix` - Cause of a bug -  `m[:, np.array(0)]` is the transpose of `a[:, 0]`. Not worth fixing since `matrix` is in many ways broken by design
* `np.ma.apply_along_axis` - Cause of a bug, fixed in #8511
* `np.piecewise` - used for an undocumented special case that probably shouldn't exist in the first place.

Places where we no longer do because it caused issues

* `np.gradient`
* `np.histogram`
* `np.apply_along_axis` (#8441)

**Review by jeffyancey — APPROVED** [review]
TIL! Looks good to me, the table is very informative.

**Comment by dopplershift** [comment]
Very informative--I learned a lot just reading this PR.

**Comment by eric-wieser** [comment]
@charris, can you restart the appveyor build?

Although probably safe to ignore, since this is a doc-only change

**Comment by mattip** [comment]
Apparently it is not possible to [restart single jobs on AppVeyor](https://github.com/appveyor/ci/issues/58)

**Comment by eric-wieser** [comment]
Right now it's not even possible to restart the whole run, since the appveyor account is not the org one (as discussed elsewhere)

**Comment by rgommers** [comment]
> Seems wasteful to rerun all the tests on a doc-only just because appveyor failed

agreed

**Comment by charris** [comment]
Thanks Eric.

**Pull request merged**
