### PR TITLE
MRG: preparing for 1.9.4 release

### PR DESCRIPTION
**Pull request by matthew-brett**
Add fixes for f2py installation from wheels, including tests.

### CODE REVIEW

**Comment by matthew-brett** [comment]
@carlkl  - any interest in getting the Windows build fixes in for this one?

**Comment by matthew-brett** [comment]
@juliantaylor - do you want to add anything here?

**Comment by carlkl** [comment]
@matthew-brett, I will make a PR my to maintainance/1.9.x today or tomorrow, and after that  (if sucessfull tested) another PR to master.

**Comment by njsmith** [comment]
Usually the rule is that all PRs go to master first, and then get
backported to maintenance branches (or not). Is there some reason this
needs to not follow that rule?

**Comment by carlkl** [comment]
numpy master contains some mingw-w64 patches, maintainance-1.9,x none of them. I could be difficult to merge. I could send a complete numpy-1.9.3 patch as an alternative after a master PR.

**Comment by charris** [comment]
@carlkl Don't worry about it. It would be good if you could get the PR to master done before the 1.10.0 release.

**Comment by carlkl** [comment]
Hi folks,

mingwpy PR is now in https://github.com/numpy/numpy/pull/6354. Uses https://anaconda.org/carlkl/mingwpy (mingw-w64 wheel installable) and https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/OpenBLAS_mingwpy_amd64.7z / https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/OpenBLAS_mingwpy-win32.7z. 
I encountered some new errors in numpy.test() with numpy.master I have to dig in.

**Comment by charris** [comment]
@matthew Still want to pursue this?

**Comment by matthew-brett** [comment]
What do you think?  Are people still installing 1.9.x do you think?

By the way github user "matthew" is sadly not me but someone quicker to github awesomeness than me.

**Comment by charris** [comment]
People are definitely still using 1.9 as it is in many distros. OTOH, 1.10.2 should be out in time for the spring distro releases and I think it should be a decent release. I was asking because there wasn't much activity here and I'm trying to cleanup the PR pile. No problem if you want to keep working on this, just say so.

**Comment by matthew-brett** [comment]
What about merging this one to maintenance for now, and seeing how it goes after 1.10.2 ?

**Comment by charris** [comment]
Fine with me, your choice.

**Comment by matthew-brett** [comment]
Thanks - I endorse my own work :)

**Pull request merged**
