### PR TITLE
BUG: fix an interaction between vectorize and size-zero arrays

### LINKED ISSUE #5868: vectorize fails for zero-dimensioned arrays
The following used to work and return an empty 5 by 0 array.

```python
np.vectorize(lambda x: x+1)(np.zeros([5,0]))
```

Now it stack traces:

```
/usr/lib/python2.7/dist-packages/numpy/lib/function_base.pyc in __call__(self, *args, **kwargs)
   1571             vargs.extend([kwargs[_n] for _n in names])
   1572 
-> 1573         return self._vectorize_call(func=func, args=vargs)
   1574 
   1575     def _get_ufunc_and_otypes(self, func, args):

/usr/lib/python2.7/dist-packages/numpy/lib/function_base.pyc in _vectorize_call(self, func, args)
   1631             _res = func()
   1632         else:
-> 1633             ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
   1634 
   1635             # Convert args to object arrays first

/usr/lib/python2.7/dist-packages/numpy/lib/function_base.pyc in _get_ufunc_and_otypes(self, func, args)
   1594             # Assumes that ufunc first evaluates the 0th elements in the input
   1595             # arrays (the input values are not checked to ensure this)
-> 1596             inputs = [asarray(_a).flat[0] for _a in args]
   1597             outputs = func(*inputs)
   1598 

IndexError: index 0 is out of bounds for axis 0 with size 0
> /usr/lib/python2.7/dist-packages/numpy/lib/function_base.py(1596)_get_ufunc_and_otypes()
   1595             # arrays (the input values are not checked to ensure this)
-> 1596             inputs = [asarray(_a).flat[0] for _a in args]
   1597             outputs = func(*inputs)
```

Seems to me that there should first be a check for empty arrays before attempting to see the return types of the function?

### PR DESCRIPTION
**Pull request by argriffing**
From @jordigh in https://github.com/numpy/numpy/issues/5868#issuecomment-102046946.
Closes https://github.com/numpy/numpy/issues/5868.

### CODE REVIEW

**Comment by njsmith** [comment]
I have serious doubts here -- what if the function has side effects, e.g.
prints stuff or saves it? Or errors out on certain input, like zeroes?

**Comment by jordigh** [comment]
It's already a pretty dangerous thing to get the types from evaluating the function to begin with. What if it returns different types for different inputs?

The only safe thing to do is change the dtype argument from keyword to positional. But this breaks the condition to not break code that relied on the pre-1.7 behaviour.

**Comment by njsmith** [comment]
We could give a better error on empty inputs where the output type was not
specified, saying that you need to specify the output type if you want to
support empty inputs.

**Comment by jordigh** [comment]
I want to argue most vehemently against treating zero-size arrays especially. That should never be necessary. Whenever I have to ask myself, "could this array be empty?" I have to do all sorts of uncomfortable contortions in the calling code. This applies to all function calls and indexing and arithmetic operations. Empty in, empty out. Consistently, and without thinking about it.

Supporting empty arrays is numpy's job, not the user's job.

**Comment by argriffing** [comment]
This PR still does unexpected things like
```python
>>> np.vectorize(lambda x : np.log(x) + 1/x)(np.ones((5, 0)))
__main__:1: RuntimeWarning: divide by zero encountered in log
__main__:1: RuntimeWarning: divide by zero encountered in double_scalars
__main__:1: RuntimeWarning: invalid value encountered in double_scalars
array([], shape=(5, 0), dtype=float64)
```
or like @njsmith mentioned
```
>>> np.vectorize(lambda x : 42 if x else print('fire ze missiles!'))(np.ones((5, 0)))
fire ze missiles!
array([], shape=(5, 0), dtype=object)
```

**Comment by njsmith** [comment]
Then the user who uses np.vectorize has to specify their types, I guess?
Numpy cannot read your mind, and adding one argument to one call doesn't
really involve any uncomfortable contortions.

Note that vectorize is kinda a weird, slow, lower-level-than-it-looks
corner of numpy. Almost always the right thing to do is to write a regular
function that calls already-vectorized operations, and these already know
what to with empty arrays (or if they don't it's a bug). vectorize kiss
tricky because it tries to couple between this lower-level array typing
system and Python's more laissez-faire approach.

**Comment by argriffing** [comment]
The CI failure looks unrelated.
`Failed to fetch bzip2:/var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_trusty-security_universe_i18n_Translation-en  Hash Sum mismatch`

**Comment by jordigh** [comment]
I consider both of those problems "expected" myself. They are both potential problems that could also happen with non-empty arrays. They could also happen with a dtype argument. Short of going all Haskell, a compromise has to be struck somewhere. We can't keep backwards compatiblity, safe types, and transparent handling of empty arrays all at once. It looks to me like we can only get two of these.

**Comment by jordigh** [comment]
> Note that vectorize is kinda a weird

I suppose completely nuking it is another way to break backwards compatibility while simultaneously (and vacuously!) keeping it type safe and aware of empty arrays.

**Comment by argriffing** [comment]
Added a `RuntimeWarning` for this edge case (numpy.vectorize wrapping a function with implicit output types and called with a size-zero array argument).

**Comment by argriffing** [comment]
I like this noisy compromise. @njsmith?

**Comment by njsmith** [comment]
I'm afraid it feels terrible unpythonic to me. "When in doubt, resist
the temptation to guess", and calling a piece of arbitrary code with
some made up values is a pretty extreme form of guessing. Plus
warnings are almost always a code smell -- they indicate that
something is "sorta broken", and "sorta" is never a good thing to have
in an API, computers do not do well with "sorta". Plus they only help
if someone happens to be looking at the right moment etc., and even
then the code might have already done something unpardonable. So...
sorry.
.
I can see an argument for issuing a warning if someone calls
vectorize() without specifying the output types, and ideally making it
required eventually. But it's not high enough a priority for me to
bother trying to push through when we have much bigger backcompat
issues to try and navigate -- if someone wants to go this way then the
next step would be to propose a transition plan on the list. (If we
were doing it today we'd obviously require vectorize to specify types
-- in general all ufuncs have to be able to compute output types given
input types without looking at the actual values.) Or, obviously it
would be fine to just improve the error message on an empty array
without changing anything else.

**Comment by charris** [comment]
@argriffing @njsmith What is the status of this? I don't use/recommend vectorize myself and don't have an opinion, but I think this should either be merged or closed rather than just leaving it hanging about.

**Comment by njsmith** [comment]
I really dislike the warn-and-then-do-something-weird approach, and it doesn't sound like any more counter arguments are forthcoming, so yeah, I'll close this for now. I'd be in favor of a change to error out on empty arrays when otypes aren't specified (likely with a deprecation period) -- if anyone wants to push that forward then the next step would be to send a note to the list describing the proposed change. Or if someone wants to make an argument for another way forward, that'd be great too, please reopen/open a new issue/send an email to the list.

**Pull request closed without merging**
