### PR TITLE
DOC: Small elaboration in ravel examples.

### PR DESCRIPTION
**Pull request by petetanru**

### CODE REVIEW

**Comment by seberg** [comment]
Should we remove that shape assignment example? I frankly think that container manipulation is not a good design choice.

**Comment by petetanru** [comment]
I think it depends on how popular the method is. What do people actually use it for? I've never used it myself.

**Comment by seberg** [comment]
There is no good reason to use it really. You should prefer `np.reshape` instead and use the new array. Within numpy, some places use it, though most of it probably is a bit unclean usage. I have seen people use it to get warnings because unlike reshape it will give an error if the reshape result needs to be a copy (though it does the copy anyway first).

**Comment by petetanru** [comment]
yah, the use of it for warning purposes doesn't sound is probably not something for quickstart tutorial. certainly change it to reshape

**Comment by seberg** [comment]
Do you want to fix up the PR (or make a new one) with a single commit with a message such as "DOC: ..." (we try to keep those clean). Also as a side note, it is usually a good idea to not modify your master branch, because if you do it is difficult to keep your master in sync with our (upstream) master.

**Comment by petetanru** [comment]
Okay! Let me give it a shot. 
Noted on modifying master branch.

**Comment by petetanru** [comment]
I created a new PR instead since I had issues squashing the commits together.. (I couldn't even find my earlier ones)

**Pull request closed without merging**
