### PR TITLE
BUG,MAINT: Fix utf-8 character stripping memory access

### PR DESCRIPTION
**Pull request by seberg**
This fixes the memory access bug, the old if was there for a reason (obviously...), but unfortunately only the sanitizer checks noticed that.

But to make it clear, I had to just also rename/change things a bit making it unsigned and using a stop range rather than the actual range is just much clearer here where the range can go to length 0 IMO.

I.e. the old code had to check for `j >= 0` not `j > 0` (j being the last character index), because `j` could go negative.

Fixes the sanitizer tests.

### CODE REVIEW

**Comment by mattip** [comment]
Is there an easy way to write a test for this?

**Comment by seberg** [comment]
One of the test ran into it with asan, so there is some test.  Can't think of a way to make that much more sensitive, presumably valgrind would also catch it.

Since all that is happening is reading 1-3 bytes in front of an allocation and that probably just doesn't fail that reliably.

**Comment by ngoldbaum** [comment]
I agree this is clearer and after going through it carefully I think the code behaves identically before and after the renaming (except the re-added if block).

Right now the whitespace variants aren't being tested. The following patch fixes that and adds a test case too.

```
diff --git a/numpy/_core/tests/test_strings.py b/numpy/_core/tests/test_strings.py
index ec8f8f723e..1e86be1930 100644
--- a/numpy/_core/tests/test_strings.py
+++ b/numpy/_core/tests/test_strings.py
@@ -486,6 +486,7 @@ def test_lstrip(self, a, chars, out, dt):
         ("xyzzyhelloxyzzy", "xyz", "xyzzyhello"),
         ("hello", "xyz", "hello"),
         ("xyxz", "xyxz", ""),
+        ("    ", None, ""),
         ("xyxzx", "x", "xyxz"),
         (["xyzzyhelloxyzzy", "hello"], ["xyz", "xyz"],
          ["xyzzyhello", "hello"]),
@@ -493,10 +494,12 @@ def test_lstrip(self, a, chars, out, dt):
     ])
     def test_rstrip(self, a, chars, out, dt):
         a = np.array(a, dtype=dt)
+        out = np.array(out, dtype=dt)
         if chars is not None:
             chars = np.array(chars, dtype=dt)
-        out = np.array(out, dtype=dt)
-        assert_array_equal(np.strings.rstrip(a, chars), out)
+            assert_array_equal(np.strings.rstrip(a, chars), out)
+        else:
+            assert_array_equal(np.strings.rstrip(a), out)

     @pytest.mark.parametrize("a,chars,out", [
         ("", None, ""),
```

```
diff --git a/numpy/_core/tests/test_strings.py b/numpy/_core/tests/test_strings.py
index ec8f8f723e..eb655c129a 100644
--- a/numpy/_core/tests/test_strings.py
+++ b/numpy/_core/tests/test_strings.py
@@ -467,10 +467,12 @@ def test_endswith(self, a, suffix, start, end, out, dt):
     ])
     def test_lstrip(self, a, chars, out, dt):
         a = np.array(a, dtype=dt)
+        out = np.array(out, dtype=dt)
         if chars is not None:
             chars = np.array(chars, dtype=dt)
-        out = np.array(out, dtype=dt)
-        assert_array_equal(np.strings.lstrip(a, chars), out)
+            assert_array_equal(np.strings.lstrip(a, chars), out)
+        else:
+            assert_array_eqyal(np.strings.lstrip(a), out)

     @pytest.mark.parametrize("a,chars,out", [
         ("", None, ""),
@@ -486,6 +488,7 @@ def test_lstrip(self, a, chars, out, dt):
         ("xyzzyhelloxyzzy", "xyz", "xyzzyhello"),
         ("hello", "xyz", "hello"),
         ("xyxz", "xyxz", ""),
+        ("    ", None, ""),
         ("xyxzx", "x", "xyxz"),
         (["xyzzyhelloxyzzy", "hello"], ["xyz", "xyz"],
          ["xyzzyhello", "hello"]),
@@ -493,10 +496,12 @@ def test_lstrip(self, a, chars, out, dt):
     ])
     def test_rstrip(self, a, chars, out, dt):
         a = np.array(a, dtype=dt)
+        out = np.array(out, dtype=dt)
         if chars is not None:
             chars = np.array(chars, dtype=dt)
-        out = np.array(out, dtype=dt)
-        assert_array_equal(np.strings.rstrip(a, chars), out)
+            assert_array_equal(np.strings.rstrip(a, chars), out)
+        else:
+            assert_array_equal(np.strings.rstrip(a), out)

     @pytest.mark.parametrize("a,chars,out", [
         ("", None, ""),
```

**Comment by ngoldbaum** [comment]
Thanks Sebastian! Let's pull this in to unbreak the ASAN tests. I'll try to fix the issue @WarrenWeckesser reported about stripping unicode in a followup.

**Comment by lysnikolaou** [comment]
Thanks both for looking into this and sorry for not being careful enough in my PR.

**Pull request merged**
