### PR TITLE
TST, MAINT: Fix detecting and testing armhf features

### LINKED ISSUE #16302: ARM-only test failure on 1.19.0 rc1
Build succeeds on Fedora Rawhide but fails on ARM due to test issue.

### Reproducing code example:

N/A

### Error message:

See attached log

### Numpy/Python version information:

Numpy 1.19.0 rc1, python 3.8.3

### PR DESCRIPTION
**Pull request by seiko2plus**
- fix detect and test Arm Advanced SIMD on aarch32
- fix testing armhf's rootfs on aarch64 kernel

Closes #16302.

### CODE REVIEW

**Comment by charris** [comment]
Azure is acting up these days.

**Comment by charris** [comment]
close/reopen

**Comment by vrakesh** [comment]
These tests, go in-hand with Detection of features in #16321 , should we merge this one after #16321 ??

**Comment by seiko2plus** [comment]
@vrakesh, not gonna make a difference.

**Comment by seiko2plus** [comment]
@Qiyu8, I detected the issue of running armhf rootfs through `chroot` on aarch64 kernel and I combined a fix for it.

**Comment by charris** [comment]
@seiko2plus What is the current relationship of this with #16321.

**Comment by Qiyu8** [comment]
@charris I think there has no relationship between this PR and[ #16321](https://github.com/numpy/numpy/pull/16321). This PR is focused on fix getauxval/auxv cpu feature detection bug, [ #16321](https://github.com/numpy/numpy/pull/16321) is another way to detect cpu feature.

**Comment by charris** [comment]
@seiko2plus  @Qiyu8 So are the two methods complimentary? Do they solve different problems? I mostly want to fix the aarch64 problems for 1.19 and would like to have some sense of how things fit together.

**Comment by seiko2plus** [comment]
@charris,
this patch now resolves two bugs for detect/test CPU features on armhf architecture(arm7-a):
1-  (#16302) when fully load armhf linux kernel on aarch64 through qemu with options (aarch64=off and -enable-kvm) enabled
2- when you load rootfs of armhf on aarch64 kernel through chroot and mounting virtual filesystem(proc)

What #16321 resolves is the issue of badly patched kernels, usually the old arm7-a kernels on Andriod devices don't provide support for auxiliary vector or sometimes `selinux` prevent reading auxiliary vector (`/proc/self/auxv`) on non-root users.

**Comment by charris** [comment]
@seiko2plus Thanks for the nice explanation. I'm going to put this in now for the rc2 release.

**Comment by charris** [comment]
Thanks @seiko2plus .

**Comment by seiko2plus** [comment]
@charris, Thank you

**Pull request merged**
