### PR TITLE
TYP: Explicit ``numpy.__all__`` in the stubs

### PR DESCRIPTION
**Pull request by jorenham**
According to the [typing spec](https://typing.readthedocs.io/en/latest/reference/stubs.html#all):

> A type stub should contain an `__all__` variable if and only if it also present at runtime. In that case, the contents of `__all__` should be identical in the stub and at runtime. If the runtime dynamically adds or removes elements (for example if certain functions are only available on some platforms), include all possible elements in the stubs.

Furthermore, type-checkers such as Pyright / Pylance only consider the own members within ``.pyi`` stubs as public, even if ``import spam as ham`` is used.

For example, the following code is not understood by (at least) Pyright:

```python
import numpy as np

np.linalg.pinv(1)  # ok
np.emath.sqrt(1)  # error: "emath" is not a known attribute of module "numpy"
```

This particular example could also be solved with e.g. ``emath = numpy.lib.scimath``.
But for ``numpy._get_promotion_state``, that isn't the case.
One could argue that, even though it is explicitly exported at runtime in ``numpy.__all__``, it should still be considered private, and therefore not be part of the typing stubs.

And that brings me to the most important advantage: It is *explicit*. 
A ``import this`` will tell us that 

> Explicit is better than implicit.

And this case is in particular a great example of that: Once I added the ``__all__``, my IDE (vscode) noticed that one of functions, ``trapezoid``, was missing (and I plan to open a separate PR for it soon).

Without the ``__all__``, checking for missing annotations like these, would take way more effort. 
The usual approach to this is by using stub-checker tools such as ``pyright --verifytypes``. 
But at the moment, running ``pyright --ignoreexternal --verifytypes numpy`` produces >23000 lines of output and reports >8000 errors, of which >4500 originate in `.pyi` files.

### CODE REVIEW

**Comment by seberg** [comment]
This looks fine if pyright needs it.  Is there a test, or would it be possible to add a test that the two `__all__` (maybe also at least for `np.random` and `np.linalg` match)?

Otherwise, this is bound to get out of sync quickly.  With such a test, it might actually end up replace the test for our public API not accidentally growing than the current test we have.

**Comment by jorenham** [comment]
> This looks fine if pyright needs it. Is there a test, or would it be possible to add a test that the two `__all__` (maybe also at least for `np.random` and `np.linalg` match)?

The only test I can think of is something like `pyright --verifytypes numpy`, but like I mentioned before, that's a rather brute force approach, but we might be able to `sed` the output for it.
The mypy equivalent of this is [`mypy stubtest`](https://mypy.readthedocs.io/en/stable/stubtest.html), but from the looks of it, it also doesn't have flags to only check the `__all__`.

But it should be difficult to write a simple script for this ourselves in e.g. `numpy/typing/tests/`:
A simple `import numpy; numpy.__all__` will get us the runtime part.
If we assume that the stubs always uses a static `__all__` (no `.append() or `+=` or something), then we could probably get away with a regex.
Then compare the two (sorted) `__all__`'s and output `difflib.context_diff` or something to stderr in case they don't match.

**Comment by jorenham** [comment]
> Otherwise, this is bound to get out of sync quickly. With such a test, it might actually end up replace the test for our public API not accidentally growing than the current test we have.

Currently, without an explicit `__all__`, it's even easier to get out of sync. 
If functions are missing form the stubs, but are present it the `__all__` (in the stubs), then your IDE will highlight the missing export (assuming that it's not only Pylance that does this). This is precisely how I found out that `numpy.trapezoid` was missing, which as far as I'm concerned, wasn't known before that.

And syncing `__all__` is in this case as simple as copy-pasting the `import numpy; print(numpy.__all__)` output into `numpy/__init__.pyi`

Either way, I do agree that an automatic check for this, is an excellent idea.
But without having `__all__` in the stubs, writing such a test would be a lot more difficult, than with it. 
So I suppose that having `__all__` in the stubs is a win/win scenario.

**Comment by charris** [comment]
Thanks @jorenham .

**Pull request merged**
