### PR TITLE
MAINT: changing the method of checking for nan / inf values linalg.eig

### LINKED ISSUE #1339: Unifying numpy.linalg and scipy.linalg exceptions for NaN inputs (Trac #812)
_Original ticket http://projects.scipy.org/scipy/ticket/812 on 2008-12-13 by @pv, assigned to unknown._

From gh-1327 by tzito

---

[...] numpy.linalg.eig raises LinAlgError? if the array contains NaNs? (lines 590 and 118 in numpy/linalg/linalg.py), whereas scipy.linalg.eig raises ValueError? (line 151 in scipy/linalg/decomp.py).

I find the scipy behaviour more consistent: scipy.linalg.eig uses the numpy function asarray_chkfinite to check that the array does not contain NaNs?. numpy.linalg.eig uses an _assertFinite function instead, which is defined inside numpy/linalg/linalg.py and which is actually not needed.

There are three possible fixes:
1. change numpy.linalg.eig so that it uses asarray_chkfinite instead of _assertFinite
2. change scipy.linalg.eig so that it uses a to be defined _assertFinite function instead of asarray_chkfinite.

### PR DESCRIPTION
**Pull request by WillTirone**
Hi all, first commit to numpy so please double check everything :) 

This is intended to close [scipy issue #1339](https://github.com/scipy/scipy/issues/1339#issuecomment-1162504893). Tests passed locally.

### CODE REVIEW

**Comment by WillTirone** [comment]
Ah - looks like there was an issue with Test_Regression, I'll take a look at that and try to resubmit the PR.

**Comment by charris** [comment]
> try to resubmit the PR.

You can keep pushing new changesets to your PR branch, no need to resubmit.

**Comment by mattip** [comment]
Changing the types of errors raised can be problematic, especially since `LinAlgError` is not a `ValueError` subclass. On the other hand, having a polynomial method raise `LinAlgError` seems out of place. I don't know the history of `LinAlgError`, but it seems heavily used in SciPy. I think changing `LinAlgError` to be a subclass of `ValueError` would be a better fix.

**Comment by WillTirone** [comment]
@mattip thank you for the feedback! I'll look into that and attempt making that change that you suggested.

**Comment by WillTirone** [comment]
@mattip apologies as I forgot to continue on this one, but let me know if the recent fix was what you had in mind. I took your instructions pretty literally so just wanted to confirm (whenever you have a chance).

Thank you!

**Comment by mattip** [comment]
Yes, that seems better. Would this solve the SciPy problem?

**Comment by WillTirone** [comment]
Yes, or at least that issue was marked closed yesterday as "not planned" so I think it is more of a numpy fix at this stage.

**Comment by mattip** [comment]
Thanks @WillTirone

**Comment by WillTirone** [comment]
Thank you @mattip !

**Pull request merged**
