### PR TITLE
MAINT: Proposal to expire three deprecated functions in numpy.lib.npyio

### PR DESCRIPTION
**Pull request by rossbar**
There are three functions in the `npyio` module which are all in the main namespace that are suitable for removal according to the [criteria laid out in NEP23](https://numpy.org/neps/nep-0023-backwards-compatibility.html#implementing-deprecations-and-removals):
 - `np.loads`, deprecated in v1.15
 - `np.ndfromtxt` and `np.mafromtxt`, both deprecated in v1.17.

This PR proposes to remove them outright, but happy to hear thoughts on the appropriate course of action.

### CODE REVIEW

**Review by seberg — APPROVED** [review]
Weird that the tests actually only use `genfromtext` (I guess to avoid the warning...).  In any case we seem to have more tests with `usemask=True` so looks good to me, unless anyone wants to nitpick the release notes :).

**Comment by rossbar** [comment]
> unless anyone wants to nitpick the release notes

Suggestions welcome - I'm happy to expand/reorganize them!

**Comment by charris** [comment]
> so looks good to me, unless anyone wants to nitpick the release notes

I'll edit them all into a list when the release notes are generated.

**Comment by charris** [comment]
Thanks Ross.

**Pull request merged**
