### PR TITLE
MNT: try updating pythoncapi-compat

### PR DESCRIPTION
**Pull request by tacaswell**
~xref to https://github.com/python/pythoncapi-compat/issues/89~

~It looks like https://github.com/python/cpython/pull/116883 and https://github.com/python/pythoncapi-compat/pull/87 are collaborating to break the numpy build.~

This was fixed upstream so update instead of revert.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
The build failure is only for python 3.13, right?

**Comment by tacaswell** [comment]
I'm not sure this failure is even in a tagged pre-release.

**Comment by vstinner** [comment]
I fixed the issue with the current Python main branch in pythoncapi-compat: https://github.com/python/pythoncapi-compat/issues/89#issuecomment-2038266179

**Comment by vstinner** [comment]
Does a CI fail with pythoncapi-compat.h and Python 3.13? Which CI?

**Comment by ngoldbaum** [comment]
It looks like [a linux CI that has `-Werror` set](https://github.com/numpy/numpy/actions/runs/8562015234/job/23464447862?pr=26213) is now failing with:

```
n file included from ../numpy/_core/src/common/npy_pycompat.h:5,
                 from ../numpy/_core/src/multiarray/arraytypes.c.src:15:
../numpy/_core/src/common/pythoncapi-compat/pythoncapi_compat.h:1304:1: error: ‘PyDict_SetDefaultRef’ defined but not used [-Werror=unused-function]
 1304 | PyDict_SetDefaultRef(PyObject *d, PyObject *key, PyObject *default_value,
      | ^~~~~~~~~~~~~~~~~~~~
```

not sure offhand why the compiler considers this one unused but not all the others

**Comment by vstinner** [comment]
> not sure offhand why the compiler considers this one unused but not all the others

It's a stupid mistake: I forgot "inline" in "static inline". Fixed in pythoncapi-compat by https://github.com/python/pythoncapi-compat/commit/01341acbbef0ca85cf2fa31b63307ddf4d9a87fb

**Comment by tacaswell** [comment]
I can confirm that with this PR to numpy + cpython main numpy builds.

**Comment by ngoldbaum** [comment]
@tacaswell can you update the submodule once more to fix the compiler warning failing CI?

**Comment by tacaswell** [comment]
Ah, sorry did not get to this.

**Comment by ngoldbaum** [comment]
No worries, figured I'd just push on top of this to finish it up.

**Comment by tacaswell** [comment]
I can also confirm that this PR builds with cpython main still.

**Comment by ngoldbaum** [comment]
Pulling this in, thanks for getting the ball rolling on this @tacaswell!

**Comment by vstinner** [comment]
Thanks for the bug reports, it helped me to discover bugs and enhance pythoncapi-compat :-)

**Pull request merged**
