### PR TITLE
DOC: updated docstrings in numpy/ma/core.py

### PR DESCRIPTION
**Pull request by ay11111111111**
This PR updates docstrings in numpy/ma/core.py for 'filled' and 'MaskedArray' functions. More specifically, it specifies that fill_value attribute can be of any shape.

### CODE REVIEW

**Comment by mattip** [comment]
The shape cannot be "any", it must be able to be broadcast to `x`. Also needs expanded examples showing how it can be used.

**Comment by mattip** [comment]
Sorry, issue #4363 requested deprecation instead.

**Comment by yesass** [comment]
@mattip I am so sorry, I have commited the solution for another issue to this branch. How can I discard this commit?

**Comment by mattip** [comment]
You can do something like `git rebase -i HEAD~2` which should open an editor with your three commits, with `pick` in the first column. Change that to `drop` on the commits you wish to revert, then write the file and exit.

**Comment by yesass** [comment]
@mattip I have updated docstrings, added several examples and deprecation warnings.
Now, trying to figure out how to write warning tests. Can you check if I added deprecation warning right?
And is it ok if I am doing often commits to the branch? I am a newbie in git, that's why there is a little mess :)

**Comment by mattip** [comment]
> is it ok if I am doing often commits to the branch

You might want to investigate `git rebase -i ...`, it allows you to `squash` and `drop` changesets. Then you will need to use `-f` when you push since you have modified history

**Comment by mattip** [comment]
> added deprecation warning

In the issue @eric-wieser commented "I think we should compromise on allowing filled(...) to take a broadcasting value, and writing tests for it (it's easy to get right), but deprecating using a non-scalar fill value for fill_value (because getting that right is hard)." Please be sure your code and tests answer to that spec or if you disagree discuss it here.

Also, you should add a comment before the warning with the date and version (currently 1.17.0), and the relevant github issue. See the other DeprecationWarnings in the file.

Since this changes user-facing behaviour, you also need to add a comment in `doc/release/1.17.0-notes.rst`.

**Comment by yesass** [comment]
@mattip thanks for navigating me. I'll do my best :+1:

**Comment by charris** [comment]
close/reopen.

**Comment by yesass** [comment]
Hi @mattip ! To be honest, I am confused a little bit because the deprecation warnings in core.py are different in structure, and not all of them has a deprecation test. Can I ask 2 more questions?
1) Did I understand right that fill_value must be only scalar broadcastable over 'a' (however, the type of fill_value broadcasts over 'a' automatically), and non-scalar values are deprecated. 
2) Am I writing test right?
```
class TestMaFilled(object):
    """gh-4363"""
    x = np.ma.array(np.arange(4).reshape(2, 2), mask=[[1, 0],[0, 1]])
    def test_base(self):
        assert_warns(DeprecationWarning, x.filled,fill_value=0)
```

Also, can I suggest reorder functions in alphabetical order in order to ease analysis for new-comer contributors?

**Comment by mattip** [comment]
Duplicate of #13698 which was merged. Closing.

**Comment by eric-wieser** [comment]
Wrong PR?

**Pull request closed without merging**
