### PR TITLE
BUG: Backport fix build on ppc64 when the baseline set to Power9 or higher

### PR DESCRIPTION
**Pull request by seiko2plus**
Backport #24806

closes https://github.com/numpy/numpy/issues/24789

### CODE REVIEW

**Comment by mattip** [comment]
Copying [the comment](https://github.com/numpy/numpy/issues/24789#issuecomment-1797180278) from #24789:

> Works for me here on POWER9, both LE and BE. Thanks!

**Comment by charris** [comment]
Thanks Sayed.

**Comment by yselkowitz** [comment]
Is there a timeline for the next 1.26.x release with this fix?

**Comment by charris** [comment]
> Is there a timeline for the next 1.26.x release with this fix?

Somewhere between a week and two weeks from now.

**Pull request merged**
