### PR TITLE
ENH: Support exotic installation of nvfortran

### PR DESCRIPTION
**Pull request by danbeibei**
The current `fcompiler` implementation for NVHPC Fortran compiler fails with exotic NVHPC installations.
This change allows support for custom installations where the Fortran compiler command is not called `nvfortran`, e.g. when using a wrapper.
The `aka nvfortran` part in the pattern is actually enough to garantee that it is the NVHPC Fortran compiler.

### CODE REVIEW

**Comment by charris** [comment]
I guess the `pg` compiler is there because that is what the nvidia compiler was based on. is it safe to remove? I'm not clear on why it breaks the detection.

**Comment by danbeibei** [comment]
That's right, `pgf77`, `pgf90` and `pgfortran` were the command names before being repackaged under the `nvfortran` command. They will still match the new pattern as it is broader.

The old pattern fails when the command has a custom name (e.g. a symlink to `nvfortran`) because the command name is printed in the `--version` output:
```
$ ln -s $(which nvfortran) foobar
$ ./foobar --version
foobar (aka nvfortran) 23.7-0 [...]
```
It is the `aka nvfortran` part that should be matched, what is before can be allowed to be anything.

Note that if one does this kind of quirk with `gfortran`, there's no problem, because it doesn't print the command name in the output:
```
$ ln -s $(which gfortran) foobar
$ ./foobar --version
GNU Fortran (GCC) 13.0.0 [...]
```

**Comment by charris** [comment]
I note that this only affects projects still using distutils. Does meson detection work.

**Comment by danbeibei** [comment]
I don't really know how to try with meson. I'm using f2py, is there a way to use meson?

**Comment by charris** [comment]
I think you will need to wait until NumPy 2.0 for meson. @HaoZeke Comment?

**Comment by HaoZeke** [comment]
With meson one can just set the FC variable.. Some bugfixes are waiting for 2.0 but basic support was shipped in 1.24 I think

**Pull request merged**
