### PR TITLE
DOC: show_config documentation

### PR DESCRIPTION
**Pull request by ghost**
Continuing from #9275, fixing #9258

@rgommers @charris 
I ended up going with your original suggestion and put the documentation in the _packaging (distutils)_ section.

Final question:
Notice that because I have Numpy built on my machine, `linkcode_resolve` finds the source for `show_config` in `__config__.py` and produces a URL, which it then tries to follow on the master branch and obviously fails to locate it. Will this be an issue when you rebuild the html or is this fine?

### CODE REVIEW

**Comment by rgommers** [comment]
> I ended up going with your original suggestion and put the documentation in the packaging (distutils) section.

I think that choice is fine. However you now have duplicated the docstring content because of the difficulty of including it with ``autodoc``. 

The linkcode not resolving is an issue that's probably solvable, but I'm not too bothered right now - quite a bit of work for a very minor thing.

**Comment by siryog90** [comment]
@rgommers 

I removed the duplication by putting the documentation in an `.rst` file and reading it when generating `__config__.py`

I did some tests and the write process works. However, the issue I have now is that if you try to search for `show_config` in the numpy index, you find that Sphinx has automatically created an extra stub page for it, which we don't want. Am I correct in guessing that the reason this happens is that I have put `show_config.rst` in the `reference` folder, and whatever `.rst` files are there automatically get generated stubs?

**Comment by rgommers** [comment]
This works and docs look good to me. I have the feeling that this is going to break something though - that file reading doesn't look very robust. It's hard to predict how; for example packaging scripts could be stripping off ``doc/``, which would break the build.

I've seen enough versions now that I've gotten a bit confused - could you remind me why the obvious solution (have the docstring inside ``generate_config_py``, write it from there to ``__config__.py`` and adding  `` `show_config` `` to ``reference/distutils.rst``) didn't work?

**Comment by siryog90** [comment]
The issue was that `__config__.py` and by extension `show` are generated during the build process, so Sphinx doesn't know about them prior to building the project.

**Comment by eric-wieser** [comment]
Isn't this also true of any C function though?

**Comment by siryog90** [comment]
I did stumble upon the `add_doc` helper,  as well as the convention of writing the function signature as the first line of the docstring.

I'll give these a go today.

**Comment by eric-wieser** [comment]
I don't think _"Sphinx doesn't know about them prior to building the project"_ is a good argument, as I think this is already true in many other places.

**Comment by siryog90** [comment]
@eric-wieser as I am new to the project's source code, I would appreciate it if you could tell me where to look for something similar in the source, if you can think of such a place.

**Comment by eric-wieser** [comment]
I'm saying that the suggestion to "have the docstring inside  generate_config_py" seems correct to me, as suggested by @rgommers

**Review by charris — CHANGES_REQUESTED** [review]
There seems to be a consensus that the way to do this is in `generate_config_py`.

**Comment by WarrenWeckesser** [comment]
This pull request is superseded by https://github.com/numpy/numpy/pull/15429, so closing.

**Pull request closed without merging**
