### PR TITLE
PERF: Fast path for dtype lookup of float and long

### PR DESCRIPTION
**Pull request by eendebakpt**
* Add fast path for lookup of the dtype of a Python float and long
* Remove check on `Py_None`

### CODE REVIEW

**Comment by seberg** [comment]
At some point I was wondering if tiny LRU of recently seen types can work (even within the same call for recursive cases), but with the plausibility of subinterpreters, I am not sure it is fun to spend much time on figuring it out.

Anyway, I am happy with adding a fast path for ints and floats here (still some code nitpicks).  I am curious how much it makes the benchmarks faster (I think thre should be one be some benchmarks hitting this for `bench_array_coercion`).

**Comment by eendebakpt** [comment]
> At some point I was wondering if tiny LRU of recently seen types can work (even within the same call for recursive cases), but with the plausibility of subinterpreters, I am not sure it is fun to spend much time on figuring it out.
> 
> Anyway, I am happy with adding a fast path for ints and floats here (still some code nitpicks). I am curious how much it makes the benchmarks faster (I think thre should be one be some benchmarks hitting this for `bench_array_coercion`).

Improvement on the benchmarks is not a lot. From profiling results, the improvement on `np.sqrt(1.1)` is at best 1% to 2% (and similar for most ufuncs on a float). The expensive part is the call to `PyDict_GetItem` on `_global_pytype_to_type_dict`. Instead of a fast path we could use a structure that that is more efficient than the python dictionary (that one has to calculate hashes for the objects), something like a `std::map<PyObject *, PyObject *>`. We then skip any hash calculations, and if works for all types. (I am thinking of `np.float64`). The new structure would either have to replace the `_global_pytype_to_type_dict`, or act as a fast path with the `_global_pytype_to_type_dict` as a fallback.

Even though it is not a lot of work, 1% gain is not a lot so I am considering closing this PR.

**Comment by seberg** [comment]
Ah OK, maybe that is why I didn't add it.  The case that I thought might gain quite a bit would be:
```
arr = np.array([1000.] * 10000)
```
but, I guess they should also gain quite well to be worthwhile.

**Comment by eendebakpt** [comment]
> Ah OK, maybe that is why I didn't add it. The case that I thought might gain quite a bit would be:
> 
> ```
> arr = np.array([1000.] * 10000)
> ```
> 
> but, I guess they should also gain quite well to be worthwhile.

For the example you gave performance improvement is about 20-25%. But for a smaller list the gain will be less. 
For this particular example a LRU with just 1 element would probably work, or the current fast path for `long` and `float`. 
If a more general approach covering all types is just as fast I would still prefer that.

**Comment by seberg** [comment]
The problem with an LRU is that I am not sure it is wise to make it persistent over multiple calls,  `type` objects are not necessarily immortal (although the ones that have DTypes effectively are right now).
OTOH, it could still be very effective if it is persistent only in a single (recrusive) call for those large lists, that is.

So, I am happy for you to look into it if it interests you, but I am not sure it is particularly high priority. (priority is very subjective though :))

**Comment by eendebakpt** [comment]
> The problem with an LRU is that I am not sure it is wise to make it persistent over multiple calls, `type` objects are not necessarily immortal (although the ones that have DTypes effectively are right now). OTOH, it could still be very effective if it is persistent only in a single (recrusive) call for those large lists, that is.
> 
> So, I am happy for you to look into it if it interests you, but I am not sure it is particularly high priority. (priority is very subjective though :))

I agree priority is not so high, but since I am working on it I might complete it anyway.

Besides this PR, I tested two more variations:

1) This https://github.com/numpy/numpy/compare/main...eendebakpt:dtype_lookup_v2a is an implementation of the lookup table approach I had in mind. The advantage is that it works for all types, not just a few selected ones.
2) https://github.com/numpy/numpy/compare/main...eendebakpt:dtype_lookup_v3 is a single-element LRU. Advantage it is adaptive (so large lists are covered, whether they are `int` or `float` or something else) a small addition. Downside is that mixed cases are not handled as good as by 1)

Performance numbers on `np.array([0] * 100)`:
```
main: 1.21 seconds
this PR: 1.0 seconds
LUT approach: between 1.08 and 1.12 seconds
LRU: 0.97 seconds
```
The results of the LUT approach depends a bit on what is in the lookup table. In my tests adding more types (e.g. `np.int16`) could improve performance when the type searched for (e.g. `int`) is easier to find with the binary search.

@seberg Based on the above I have a small preference for either the LRU approach or the approach in this PR. 

<details>
<summary>dtype_lookup_v3: python runtests.py --bench-compare main bench_array_coercion</summary>

```
       before           after         ratio
     [57961d23]       [6be51bac]
     <main>           <dtype_lookup_v3>
-        546±20ns        519±0.5ns     0.95  bench_array_coercion.ArrayCoercionSmall.time_array_dtype_not_kwargs(array([5]))
-        470±10ns          447±1ns     0.95  bench_array_coercion.ArrayCoercionSmall.time_ascontiguousarray(1)
-         460±6ns          437±4ns     0.95  bench_array_coercion.ArrayCoercionSmall.time_array_no_copy(1)
-         387±8ns          368±5ns     0.95  bench_array_coercion.ArrayCoercionSmall.time_array(5)
-       399±0.9ns          379±2ns     0.95  bench_array_coercion.ArrayCoercionSmall.time_asanyarray(1)
-         454±5ns          429±1ns     0.94  bench_array_coercion.ArrayCoercionSmall.time_ascontiguousarray(5)
-         390±6ns          366±2ns     0.94  bench_array_coercion.ArrayCoercionSmall.time_asanyarray(5)
-        420±10ns          382±2ns     0.91  bench_array_coercion.ArrayCoercionSmall.time_array(1)

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```
</details>

<details>
<summary>dtype_lookup_v3: python runtests.py --bench-compare main bench_core</summary>

```
      before           after         ratio
     [57961d23]       [6be51bac]
     <main>           <dtype_lookup_v3>
+      67.1±0.3μs       82.8±0.3μs     1.23  bench_core.PackBits.time_packbits_little(<class 'numpy.uint64'>)
+        995±10μs      1.09±0.01ms     1.09  bench_core.PackBits.time_packbits_axis1(<class 'numpy.uint64'>)
+         169±4μs          182±7μs     1.08  bench_core.CountNonzero.time_count_nonzero(1, 1000000, <class 'numpy.int32'>)
+      51.0±0.5μs       54.9±0.3μs     1.08  bench_core.PackBits.time_packbits(<class 'numpy.uint64'>)
+     1.07±0.01ms      1.15±0.03ms     1.07  bench_core.PackBits.time_packbits_axis0(<class 'numpy.uint64'>)
+         147±1μs          157±1μs     1.07  bench_core.CountNonzero.time_count_nonzero(3, 1000000, <class 'numpy.int8'>)
-         345±4ns          327±2ns     0.95  bench_core.Core.time_array_empty
-         100±1μs       95.1±0.7μs     0.95  bench_core.UnpackBits.time_unpackbits_axis1
-      39.3±0.6μs       36.9±0.3μs     0.94  bench_core.CorrConv.time_convolve(50, 1000, 'valid')
-      10.3±0.3μs       9.51±0.2μs     0.93  bench_core.CountNonzero.time_count_nonzero_axis(3, 100, <class 'str'>)
-     1.99±0.06μs      1.84±0.01μs     0.93  bench_core.Core.time_array_l_view
-         455±2μs          417±2μs     0.92  bench_core.CountNonzero.time_count_nonzero_multi_axis(2, 10000, <class 'object'>)
-     6.14±0.04μs      5.62±0.05μs     0.92  bench_core.UnpackBits.time_unpackbits
-     44.6±0.06ms       40.8±0.1ms     0.91  bench_core.CountNonzero.time_count_nonzero_multi_axis(2, 1000000, <class 'object'>)
-         291±4μs          265±2μs     0.91  bench_core.PackBits.time_packbits_axis0(<class 'bool'>)
-         684±4μs          622±2μs     0.91  bench_core.CountNonzero.time_count_nonzero_multi_axis(3, 10000, <class 'object'>)
-      67.3±0.4ms       61.1±0.1ms     0.91  bench_core.CountNonzero.time_count_nonzero_axis(3, 1000000, <class 'object'>)
-         682±3μs          618±2μs     0.91  bench_core.CountNonzero.time_count_nonzero_axis(3, 10000, <class 'object'>)
-      17.8±0.8μs      16.1±0.09μs     0.91  bench_core.Core.time_diagflat_l50_l50
-      44.9±0.4ms       40.7±0.1ms     0.91  bench_core.CountNonzero.time_count_nonzero_axis(2, 1000000, <class 'object'>)
-         234±3μs        211±0.6μs     0.90  bench_core.CountNonzero.time_count_nonzero_axis(1, 10000, <class 'object'>)
-     22.7±0.05ms      20.5±0.05ms     0.90  bench_core.CountNonzero.time_count_nonzero_axis(1, 1000000, <class 'object'>)
-         464±3μs          418±2μs     0.90  bench_core.CountNonzero.time_count_nonzero_axis(2, 10000, <class 'object'>)
-      67.9±0.6ms      61.0±0.06ms     0.90  bench_core.CountNonzero.time_count_nonzero_multi_axis(3, 1000000, <class 'object'>)
-        16.7±1μs       14.9±0.1μs     0.89  bench_core.Core.time_diagflat_l100
-        327±20ns          290±5ns     0.88  bench_core.Core.time_array_1
-      6.99±0.2μs      5.76±0.02μs     0.82  bench_core.Core.time_array_l100
-      13.4±0.1μs      10.9±0.05μs     0.82  bench_core.Core.time_diag_l100
-      49.9±0.4μs       40.5±0.2μs     0.81  bench_core.Core.time_array_float_l1000
-      51.8±0.1μs       41.7±0.2μs     0.81  bench_core.Core.time_array_int_l1000
-        39.5±2μs       28.4±0.2μs     0.72  bench_core.Core.time_array_float64_l1000

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.
```

(benchmark claims performance decreased, but I think this is just fluctuations on my system. overall there seems to be an increase)
</details>

**Comment by seberg** [comment]
I have to think about it.  I am still a bit worried that caching `pytype` may be a bit tricky if done persistently over multiple function calls.  So I was wondering if the "single type LRU" should basically live on the recursive call (or even only in the sequence branch, which is likely the only branch it matters).

**Comment by eendebakpt** [comment]
@seberg Marking this one as ready for review. The alternative options are not much faster, and we have some worries about the caching.

Conversion of python lists with long and float are faster. Benchmark:
```
np.array(longs20): Mean +- std dev: [main] 1.48 us +- 0.05 us -> [pr] 1.28 us +- 0.03 us: 1.16x faster
np.array(longs): Mean +- std dev: [main] 5.31 ms +- 0.06 ms -> [pr] 4.34 ms +- 0.05 ms: 1.22x faster
np.array(floats): Mean +- std dev: [main] 480 us +- 4 us -> [pr] 392 us +- 5 us: 1.22x faster

Geometric mean: 1.20x faster
```
<details>

```
import numpy as np
import time
import pyperf

setup="import numpy as np; l=[1]*10_0000; lf=[1.]*10_000; s=[-1]*20"   

runner = pyperf.Runner()
runner.timeit('np.array(longs20)', stmt='np.array(s)', setup=setup)
runner.timeit('np.array(longs)', stmt='np.array(l)', setup=setup)
runner.timeit('np.array(floats)', stmt='np.array(lf)', setup=setup)
```
</details>

The numpy benchmarks `bench_core` are a bit strange on my system. The values for `CountNonzero` seem to vary a lot, but I cannot see why.

<details>
<summary>bench_core results (twice)</summary>
```
      before           after         ratio
     [c8de16e4]       [50a0789b]
     <main>           <dtype_lookup>
+      98.4±0.9μs          111±3μs     1.13  bench_core.CountNonzero.time_count_nonzero(2, 1000000, <class 'numpy.int8'>)
+      50.1±0.4μs         56.0±2μs     1.12  bench_core.CountNonzero.time_count_nonzero(1, 1000000, <class 'numpy.int8'>)
+      49.9±0.8μs       55.3±0.8μs     1.11  bench_core.CountNonzero.time_count_nonzero(1, 1000000, <class 'bool'>)
+         147±1μs          163±2μs     1.11  bench_core.CountNonzero.time_count_nonzero(3, 1000000, <class 'bool'>)
+         148±2μs          161±2μs     1.08  bench_core.CountNonzero.time_count_nonzero(3, 1000000, <class 'numpy.int8'>)
+        98.4±1μs        105±0.8μs     1.07  bench_core.CountNonzero.time_count_nonzero(2, 1000000, <class 'bool'>)
+     2.54±0.02μs      2.68±0.03μs     1.06  bench_core.CountNonzero.time_count_nonzero(3, 10000, <class 'bool'>)
-      5.22±0.1μs      4.94±0.05μs     0.95  bench_core.CountNonzero.time_count_nonzero_multi_axis(2, 100, <class 'bool'>)
-      7.61±0.2μs      7.20±0.06μs     0.95  bench_core.CountNonzero.time_count_nonzero_axis(1, 100, <class 'object'>)
-      40.8±0.6μs       38.5±0.8μs     0.94  bench_core.CorrConv.time_convolve(50, 1000, 'valid')
-         303±2ns          286±4ns     0.94  bench_core.Core.time_array_1
-      10.4±0.3μs      9.73±0.06μs     0.94  bench_core.CountNonzero.time_count_nonzero_multi_axis(2, 100, <class 'object'>)
-     5.89±0.08μs      5.53±0.06μs     0.94  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 100, <class 'numpy.int32'>)
-      5.90±0.3μs      5.49±0.05μs     0.93  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 100, <class 'numpy.int16'>)
-      17.7±0.7μs      16.4±0.08μs     0.93  bench_core.Core.time_diagflat_l50_l50
-     12.7±0.08μs       11.8±0.1μs     0.93  bench_core.CountNonzero.time_count_nonzero_axis(3, 100, <class 'object'>)
-      16.8±0.6μs       15.6±0.1μs     0.93  bench_core.Core.time_diagflat_l100
-     5.31±0.03μs      4.92±0.02μs     0.93  bench_core.CountNonzero.time_count_nonzero_axis(3, 100, <class 'bool'>)
-      12.5±0.3μs      11.4±0.08μs     0.92  bench_core.Core.time_diag_l100
-         465±4μs          420±2μs     0.90  bench_core.CountNonzero.time_count_nonzero_axis(2, 10000, <class 'object'>)
-      6.21±0.3μs      5.59±0.06μs     0.90  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 100, <class 'numpy.int64'>)
-      13.1±0.5μs      11.8±0.04μs     0.90  bench_core.CountNonzero.time_count_nonzero_multi_axis(3, 100, <class 'object'>)
-         466±5μs          417±5μs     0.89  bench_core.CountNonzero.time_count_nonzero_multi_axis(2, 10000, <class 'object'>)
-         237±2μs          212±2μs     0.89  bench_core.CountNonzero.time_count_nonzero_axis(1, 10000, <class 'object'>)
-        697±10μs          619±4μs     0.89  bench_core.CountNonzero.time_count_nonzero_multi_axis(3, 10000, <class 'object'>)
-      68.7±0.3ms       60.7±0.2ms     0.88  bench_core.CountNonzero.time_count_nonzero_multi_axis(3, 1000000, <class 'object'>)
-      45.9±0.5ms      40.6±0.08ms     0.88  bench_core.CountNonzero.time_count_nonzero_multi_axis(2, 1000000, <class 'object'>)
-         702±8μs          617±5μs     0.88  bench_core.CountNonzero.time_count_nonzero_axis(3, 10000, <class 'object'>)
-         245±8μs          213±2μs     0.87  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 10000, <class 'object'>)
-      23.6±0.7ms      20.3±0.06ms     0.86  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 1000000, <class 'object'>)
-        490±60ns          421±6ns     0.86  bench_core.Core.time_array_l1
-        207±10μs          177±3μs     0.86  bench_core.CountNonzero.time_count_nonzero(1, 1000000, <class 'numpy.int32'>)
-      7.07±0.1μs      5.98±0.07μs     0.85  bench_core.Core.time_array_l100
-      54.4±0.5μs       43.8±0.2μs     0.81  bench_core.Core.time_array_int_l1000
-        50.4±1μs       40.0±0.2μs     0.79  bench_core.Core.time_array_float_l1000
-        13.3±6μs      7.47±0.06μs     0.56  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 100, <class 'object'>)

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.

    

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.

+      49.6±0.4μs       54.5±0.8μs     1.10  bench_core.CountNonzero.time_count_nonzero(1, 1000000, <class 'bool'>)
+      96.7±0.5μs        106±0.9μs     1.10  bench_core.CountNonzero.time_count_nonzero(2, 1000000, <class 'numpy.int8'>)
+      97.2±0.4μs        107±0.8μs     1.10  bench_core.CountNonzero.time_count_nonzero(2, 1000000, <class 'bool'>)
+      49.7±0.3μs         54.3±1μs     1.09  bench_core.CountNonzero.time_count_nonzero(1, 1000000, <class 'numpy.int8'>)
+         148±1μs          161±1μs     1.09  bench_core.CountNonzero.time_count_nonzero(3, 1000000, <class 'bool'>)
+     2.52±0.01μs      2.69±0.02μs     1.07  bench_core.CountNonzero.time_count_nonzero(3, 10000, <class 'numpy.int8'>)
+         152±5μs          161±1μs     1.06  bench_core.CountNonzero.time_count_nonzero(3, 1000000, <class 'numpy.int8'>)
+     2.51±0.01μs      2.66±0.02μs     1.06  bench_core.CountNonzero.time_count_nonzero(3, 10000, <class 'bool'>)
+     1.50±0.01μs      1.59±0.02μs     1.06  bench_core.CountNonzero.time_count_nonzero(1, 10000, <class 'bool'>)
+     2.02±0.01μs      2.13±0.01μs     1.05  bench_core.CountNonzero.time_count_nonzero(2, 10000, <class 'bool'>)
-     1.80±0.07μs      1.70±0.02μs     0.95  bench_core.CorrConv.time_correlate(50, 10, 'same')
-     7.95±0.09μs      7.52±0.05μs     0.95  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 100, <class 'object'>)
-     1.85±0.05μs      1.75±0.02μs     0.94  bench_core.CorrConv.time_correlate(50, 10, 'full')
-     1.70±0.04μs      1.59±0.03μs     0.93  bench_core.Core.time_ones_100
-     1.70±0.09μs      1.58±0.01μs     0.93  bench_core.CorrConv.time_correlate(50, 10, 'valid')
-         309±6ns          287±2ns     0.93  bench_core.Core.time_array_1
-      16.9±0.2μs       15.5±0.1μs     0.92  bench_core.Core.time_diagflat_l100
-      12.4±0.1μs       11.3±0.3μs     0.91  bench_core.Core.time_diag_l100
-        18.1±2μs       16.2±0.2μs     0.90  bench_core.Core.time_diagflat_l50_l50
-         236±2μs          210±1μs     0.89  bench_core.CountNonzero.time_count_nonzero_axis(1, 10000, <class 'object'>)
-         467±3μs          416±1μs     0.89  bench_core.CountNonzero.time_count_nonzero_multi_axis(2, 10000, <class 'object'>)
-      68.4±0.2ms       60.8±0.4ms     0.89  bench_core.CountNonzero.time_count_nonzero_axis(3, 1000000, <class 'object'>)
-      22.9±0.1ms       20.3±0.1ms     0.89  bench_core.CountNonzero.time_count_nonzero_axis(1, 1000000, <class 'object'>)
-         464±2μs          412±2μs     0.89  bench_core.CountNonzero.time_count_nonzero_axis(2, 10000, <class 'object'>)
-         238±2μs        211±0.6μs     0.89  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 10000, <class 'object'>)
-         696±4μs          616±4μs     0.89  bench_core.CountNonzero.time_count_nonzero_multi_axis(3, 10000, <class 'object'>)
-      68.4±0.2ms       60.5±0.1ms     0.89  bench_core.CountNonzero.time_count_nonzero_multi_axis(3, 1000000, <class 'object'>)
-         700±6μs          619±5μs     0.88  bench_core.CountNonzero.time_count_nonzero_axis(3, 10000, <class 'object'>)
-      45.7±0.3ms       40.3±0.1ms     0.88  bench_core.CountNonzero.time_count_nonzero_axis(2, 1000000, <class 'object'>)
-      23.0±0.2ms      20.3±0.07ms     0.88  bench_core.CountNonzero.time_count_nonzero_multi_axis(1, 1000000, <class 'object'>)
-      7.15±0.2μs      5.95±0.06μs     0.83  bench_core.Core.time_array_l100
-      53.8±0.5μs       44.1±0.5μs     0.82  bench_core.Core.time_array_int_l1000
-      48.6±0.4μs       39.7±0.4μs     0.82  bench_core.Core.time_array_float_l1000
```
</details>

**Comment by seberg** [comment]
Thanks.  Yeah, some of the tests always fluctuates like crazy unfortunately.  Presumably either something to do with `malloc`s arena dynamic resizing or the compiler making very different optimization decisions.
(I now suspect the former after learning about it, which may mean that we could avoid it using some env variables or tricks to ensure we are in the `malloc` range.)

For now, I will let someone else comment on whether this is worthwhile ;).  It is a small enough change, and I guess lists of floats/ints are fairly common.  IIRC, I added the array check there because otherwise I wasn't able to match `np.array(arr)` in speed with the old implementation.

**Comment by seberg** [comment]
Thanks @eendebakpt.  Considering that it seems almost 20% improvement on a probably fairly common case of a longish (not absurdly long even) list of ints or floats, I am going to put this in.  The added complexity is very localized and easy to remove after all.

**Pull request merged**
