### PR TITLE
BUG: Fix segfault in frompyfunc with nout=0

### LINKED ISSUE #2014: functions returned by frompyfunc() cause segmentation faults (Trac #1416)
_Original ticket http://projects.scipy.org/numpy/ticket/1416 on 2010-02-28 by trac user ernest_ac, assigned to unknown._

When called with a last argument equal to zero, frompyfunc produces a function that segfaults on execution. Example:

    In [3]: f = np.frompyfunc(lambda x: x, 1, 0)
    In [4]: f([1,2,3])
    <segmentation fault>

Observed in Numpy 1.3.0 and in more recent versions.

### PR DESCRIPTION
**Pull request by jaimefrio**
Fixes #2014

### CODE REVIEW

**Comment by charris** [comment]
LGTM. Looks like there would be a problem with nout=1 and returning a tuple as the single result, but that is another issue...

Thanks Jaime.

**Comment by charris** [comment]
Thinking about this, I'd do the checks something like
```
if (nout == 0) {
    discard;
}
else if (nout == 1) {
    assign result;
}
else if ( nout > 1 && PyTuple_Check(result)) {
    check for nout match and process
}
else {
    discard result and return;
}
```

**Comment by jaimefrio** [comment]
That makes a lot of sense, will send a follow-up PR.

For the case of `nout == 0`, shouldn't we check that `result == PyNone`? After all, that's what Python functions that don't return anything return.

**Comment by charris** [comment]
Checking `PyNone` would work for functions, but the original example with a lambda function would fail. Arguably, lamba functions should always have `nout` >= 1 (they can return tuples). The `frompyfunc` docstring should have some explanation.

**Pull request merged**
