### PR TITLE
MAINT: Simplify parts of `_type_aliases`

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by eric-wieser** [comment]
Coverage failure is partly because this touches py2-only code-paths, and partly becauase `np.sctype2char` has no tests

**Comment by mattip** [comment]
Could you add the doctests from `sctype2char` to `numpy/core/tests/test_numeric.py`?

**Comment by eric-wieser** [comment]
Sure you want that and not `test_numerictypes.py`?

**Comment by eric-wieser** [comment]
@mattip: Done in #12020

**Comment by mattip** [comment]
It seems coverage is only running on [python3.6](https://github.com/numpy/numpy/blob/master/.travis.yml#L63). Would it make sense to add the flag to the python2.7 build as well? In any case, this looks good to me. Squashing and merging.

**Comment by mattip** [comment]
Thanks Eric

**Pull request merged**
