### PR TITLE
DOC: Proposal - make the doc landing page cards more similar to scipy

### LINKED ISSUE #21264: DOC: Sidebars are not pinned on the numpy docs site
### Issue with current documentation:

At https://numpy.org/doc/stable/reference/arrays.indexing.html, for instance, if you scroll down on the page, the sidebars scroll with the content, and stop being visible. This particularly defeats the purpose of the right sidebar, which is supposed to show you which section you are viewing. 

Compare this to the NEPs documentation, e.g., https://numpy.org/neps/nep-0021-advanced-indexing.html, where the sidebars are pinned to the page. 

It's not clear to me why this happens. I think both documents are using the pydata Sphinx theme

### Idea or request for content:

_No response_

### PR DESCRIPTION
**Pull request by rossbar**
This was discussed in the docs meeting and builds on #21456 . The proposal is to make the docs landing page look more like the [pandas](https://pandas.pydata.org/pandas-docs/stable/) and [scipy](https://scipy.github.io/devdocs/index.html#) landing pages. The landing pages for these three projects already borrow heavily from one another - this PR just makes a few tweaks to bring numpy more in line stylistically with the other two. Main changes:
 - Match the card styling by dropping the card title background color and adding a button in the same style as scipy/pandas
 - Adds a link to the release notes to the top-level nav bar

There's also one minor maintenance issue: we're currently loading the custom css by extending the main layout template. AFAICT that is the *only* purpose that extending the layout template currently serves (the other additions have been commented out - see #17220). I think it's more straightforward to use the sphinx `html_css_files` config value to accomplish this rather than loading the css in the base template. I've made that change in 08ae8d3 but if there are objections I'm happy to break that out into a separate PR.

Also fixes #21264

### CODE REVIEW

**Review by seberg — APPROVED** [review]
I think the changes are a pretty nice improvement.  Especially, the fact that we uninentionally had a smaller width on all of the docs because of htat one small setting ;).
@melissawm, I guess this was good to just be merged?

**Comment by charris** [comment]
Thanks Ross. Should (can) this be backported? I'm going to rebuild the 1.22 docs for 1.22.4.

**Comment by rossbar** [comment]
> Thanks Ross. Should (can) this be backported? I'm going to rebuild the 1.22 docs for 1.22.4.

Yes I think this should be backported - it'd be nice to have consistent theming for the 1.22 and 1.23 docs. There *shouldn't* be any problems backporting, but I'll keep an eye on the CI of the backport PR!

**Comment by chrisjsewell** [comment]
Hey @rossbar 👋
just to mention, I deprecated sphinx-panels for sphinx-design a little while ago.
Here are some pointers on migrating: https://sphinx-design.readthedocs.io/en/furo-theme/get_started.html#migrating-from-sphinx-panels, and also in https://github.com/executablebooks/sphinx-design/issues/51

You can also see it in action now on the front page of https://myst-parser.readthedocs.io, https://myst-nb.readthedocs.io, and https://aiida.readthedocs.io

Obviously, feedback is also welcome 😄

**Comment by rossbar** [comment]
Thanks for the heads up @chrisjsewell !

The goal here is to stay coordinated with the card-layout on the front page of scipy & pandas - it'd be nice to coordinate the transition or synchronize once one of the projects migrates. Pinging @tupui and @jorisvandenbossche just so it's on some radars.

**Pull request merged**
