### PR TITLE
DOC: make NEP 18 status Final

### PR DESCRIPTION
**Pull request by rgommers**
The feature has been stable for 3 releases, shouldn't still be marked Provisional.

### CODE REVIEW

**Comment by charris** [comment]
Thanks Ralf.

**Comment by seberg** [comment]
A ping to @shoyer just in case.

I am wondering what changes/additions we will need to come up with in the light of extensions such as `like=` (e.g. not passing in an instance or can we always assume that there is an instance available?). I suppose those are probably minor extensions which are OK in any case.

**Comment by rgommers** [comment]
`like=`, `__duckarray__` and `__array_module__` are all separate NEPs, so I'd say that shouldn't affect NEP 18

**Comment by seberg** [comment]
Right, what I am not sure about is whether the choice of it being a method instead of classmethod may be affected. Or e.g. the signature possibilities of `__array_function__` may need an extension. I think all of that can be done in a backward compatible way though.

**Pull request merged**
