### PR TITLE
BLD: remove __NUMPY_SETUP__ from builtins at end of setup.py

### PR DESCRIPTION
**Pull request by rgommers**
May help reduce the occurrence of gh-2434.

### CODE REVIEW

**Comment by JensTimmerman** [comment]
I just tested this and this seems to fix my problem.

the current numpy fails on this (the build of h5py fails, because it believes numpy isn't completely installed yet, since __NUMPY_SETUP__ is still defined)
```
 from setuptools import setup                                                                                             
 PACKAGE = {                                                                                                              
     'name': 'numpytest',                                                                                                 
     'version': '0.7.1',                                                                                                  
     'install_requires': [                                                                                                
         'numpy >= 1.10.0',                                                                                               
         'matplotlib >= 1.3.1',                                                                                           
         'h5py',                       
     ],        
   # Workaround from                                                                                                    
   # https://github.com/numpy/numpy/issues/2434#issuecomment-65252402                                                   
   # and                                                                                                                
   # https://github.com/h5py/h5py/issues/535#issuecomment-79158166                                                
  # this makes the installation work on the 2nd try
   'setup_requires': [                                                                                                  
        'numpy >= 1.10.0',                                                                                                
     ],                                                                                                                   
     'author': 'jenstimmerman',                                                                                           
     'author': 'jenstimmerman@gmail.com',                                                                                 
                                                                                                                
 }                                                                                                                        
setup(**PACKAGE)  
```

your branch builds fine:
```
from setuptools import setup                                                                                             
PACKAGE = {                                                                                                              
   'name': 'numpytest',                                                                                                 
   'version': '0.7.1',                                                                                                  
   'install_requires': [                                                                                                
       'numpy >= 1.12.0.dev0+940247',                                                                                  
       'matplotlib >= 1.3.1',                                                                                           
       'h5py',                          
   ],                                                                                                                   
   # this workaround is still needed in this test, because h5py would pull in numpy 1.11.1, and not this branch yet. Can be removed once h5py depends on numpy >=1.12.1?      
  # but now the install works the first time around!             
   'setup_requires': [                                                                                                  
       'numpy >= 1.12.0.dev0+940247',                                                                                  
   ],                                                                                                                   
   'author': 'jenstimmerman',                                                                                           
   'author': 'jenstimmerman@gmail.com',                                                                                 
   'dependency_links': [                                                                                               
         "git+https://github.com/rgommers/numpy.git@numpysetup#egg=numpy-1.12.0",    # this is how we tell setuptools where to find this branch for testing
   ]                                                                                                                   
}                                                                                                                        
setup(**PACKAGE)       
```
I test this with `python setup.py test` and remove your `.eggs` folder afterwards, because the first setup.py script will work on the second run, because the second time around `__NUMPY_SETUP__` is not set again.

also make sure to have run `easy_install --user cython`, or the above setup.py scripts will fail, but this is a different issue, see https://github.com/numpy/numpy/issues/7959


I can also confirm that
`easy_install --user https://github.com/rgommers/numpy/archive/numpysetup.zip` 
and 
`setup.py install --user` 
from this branch still work as expected.

I had some issues testing bdist_rpm (also on master, so this means nothing)

**Comment by rgommers** [comment]
Thanks @JensTimmerman. I'll try to reproduce your issue first, but looks like this is a correct change then.

**Comment by charris** [comment]
It will be interesting to see if this affects `matplotlib`. They explicitly delete `__NUMPY_SETUP__` and this is likely to raise a NameError. Of course, they should not be deleting private variables...

**Comment by charris** [comment]
NVM, MPL checks for the attribute before deleting it.

**Comment by JensTimmerman** [comment]
@charris matplotlib is included in my testcases and works.

`pip install --user https://github.com/rgommers/numpy/archive/numpysetup.zip` also works fine

**Comment by charris** [comment]
@rgommers I'm going to try to put this in 1.11.2rc1 if you are OK with that and accept it in time. That way it will get more testing and it doesn't look to break anything common at the moment.

**Comment by embray** [comment]
I don't know that this fixes the specific issue I described, but it might help with other similar issues.  It's not a bad idea anyhow.

**Comment by charris** [comment]
@rgommers A comment to clarify the reason for the deletion would be helpful. If none is forth coming, I'm going to put this in this weekend in any case, so complain now or never.

**Comment by rgommers** [comment]
> I'm going to try to put this in 1.11.2rc1 if you are OK with that and accept it in time

sounds good to me.

> A comment to clarify the reason for the deletion would be helpful.

good point, will add

**Comment by rgommers** [comment]
> I don't know that this fixes the specific issue I described, but it might help with other similar issues. It's not a bad idea anyhow.

I agree, it's only a partial fix. There are a number of ways for the install to fail with the same symptoms. This one is the most straightforward to fix.

**Comment by rgommers** [comment]
OK did some more testing/checking, this should be OK to merge once TravisCI is happy.

**Comment by charris** [comment]
Thanks Ralf.

**Comment by rgommers** [comment]
Thanks @JensTimmerman for pointing out this issue and testing.

**Comment by mhvk** [comment]
@MSeifert04 - our problem was actually fixed already, by #7941

**Pull request merged**
