### PR TITLE
ENH: Allow keyword arguments in auto-converted ma functions.

### LINKED ISSUE #4582: numpy.ma.zeros/ones/empty don't work correctly with keyword arguments
The zeros/ones/empty constructors for 'numpy.ma' don't like to be called with keyword arguments `shape`, `dtype`:

```
In [1]: numpy.ma.zeros(2, "f8")
Out[1]: 
masked_array(data = [ 0.  0.],
             mask = False,
       fill_value = 1e+20)

In [2]: numpy.ma.zeros(shape=2, dtype="f8")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-1a1b42c40a81> in <module>()
----> 1 numpy.ma.zeros(shape=2, dtype="f8")

TypeError: __call__() missing 1 required positional argument: 'a'
```

### PR DESCRIPTION
**Pull request by abalkin**
Fixes #4582.

### CODE REVIEW

**Comment by charris** [comment]
@abalkin `inspect.getcallargs` is not available in Python 2.6. Could you fix that up?

**Comment by charris** [comment]
@abalkin See also #5706.

**Comment by charris** [comment]
@abalkin I'm going to put this and #5706 off to numpy 1.11.

**Comment by charris** [comment]
@abalkin Needs a rebase.

**Comment by ahaldane** [comment]
Looks like this can be closed: #4582 was fixed by #6355, with a very similar fix as proposed here.

I'm going to close, please complain if there's something more I missed.

**Pull request closed without merging**
