### PR TITLE
BUG: Support env argument in CCompiler.spawn

### LINKED ISSUE #17216: distutils MSVC: CCompiler_spawn() got an unexpected keyword argument 'env'
In the words of @jaraco, it looks like numpy is incompatible with pypa/distutils#6, which breaks the building of Cython-based extensions using MSVC. Triggered by switching from setuptools 49.6 to 50.0 (see also pypa/setuptools#2368)

### Error message:

```
self.run_command('build_ext')
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\numpy\distutils\command\build_ext.py", line 274, in run
    self.build_extensions()
  File "D:\a\1\s\setup.py", line 168, in build_extensions
    if self.can_compile_link(compile_flags, link_flags):
  File "D:\a\1\s\setup.py", line 142, in can_compile_link
    extra_postargs=compile_flags)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 403, in compile
    self.spawn(args)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 507, in spawn
    return super().spawn(cmd, env=env)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\numpy\distutils\ccompiler.py", line 92, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
```

### Numpy/Python version information:
numpy-1.18.5-cp35-cp35m-win_amd64.whl
setuptools 50.0

Thanks,
Michael

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/numpy/numpy/issues/17216

### CODE REVIEW

**Comment by lesteve** [comment]
I am a bit confused, I thought this was fixed in distutils in https://github.com/pypa/distutils/commit/6e92cdabaff71ab2bab3300763101fb8f84c367f that adds a fall-back if env is not supported as an argument. See https://github.com/pypa/distutils/issues/15 for some context.

**Comment by rgommers** [comment]
> I am a bit confused, I thought this was fixed in distutils in [pypa/distutils@6e92cda](https://github.com/pypa/distutils/commit/6e92cdabaff71ab2bab3300763101fb8f84c367f) that adds a fall-back if env is not supported as an argument. See [pypa/distutils#15](https://github.com/pypa/distutils/issues/15) for some context.

That fix was either incomplete or didn't make it into a `setuptools` <=60.0.3 release. The traceback in the log linked from https://github.com/conda-forge/setuptools-feedstock/pull/222#issuecomment-999425485 is pretty clear:

<details>

```

2021-12-21T18:14:12.5209725Z + python setup.py bdist_wheel
2021-12-21T18:14:36.2685350Z Partial import of sklearn during the build process.
2021-12-21T18:14:36.2687500Z C:\Miniconda\envs\testvenv\lib\site-packages\setuptools\_distutils\_msvccompiler.py:536: UserWarning: Fallback spawn triggered. Please update distutils monkeypatch.
2021-12-21T18:14:36.2688861Z   "Fallback spawn triggered. Please update distutils monkeypatch.")
2021-12-21T18:14:36.2742186Z Traceback (most recent call last):
2021-12-21T18:14:36.2744237Z   File "C:\Miniconda\envs\testvenv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 529, in _fallback_spawn
2021-12-21T18:14:36.2746095Z     yield bag
2021-12-21T18:14:36.2747644Z   File "C:\Miniconda\envs\testvenv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
2021-12-21T18:14:36.2748777Z     return super().spawn(cmd, env=env)
2021-12-21T18:14:36.2749879Z   File "C:\Miniconda\envs\testvenv\lib\site-packages\numpy\distutils\ccompiler.py", line 89, in <lambda>
2021-12-21T18:14:36.2751155Z     m = lambda self, *args, **kw: func(self, *args, **kw)
2021-12-21T18:14:36.2752198Z TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
```

</details>

This PR won't fix that any time soon, because projects build against the lowest supported NumPy version. We may get rid of `numpy.disutils` complete by the time that this PR becomes effective. That said, the fix looks correct and fixes the problem on our side, so let's just merge it.

By the way, y'all really should pin `setuptools` in your release branches (Cc @thomasjpfan). This is not done currently (https://github.com/scikit-learn/scikit-learn/blob/1.0.X/pyproject.toml#L4), and hence the breakage you're seeing in your CI will also occur when installing from an sdist with `pip install scikit-learn`. See here for docs on how SciPy does this as part of the release process: http://scipy.github.io/devdocs/dev/core-dev/index.html#updating-upper-bounds-of-dependencies

**Review by rgommers — APPROVED** [review]
LGTM, thanks @isuruf!

**Comment by rgommers** [comment]
The one CI failure on Cygwin was unrelated.

**Comment by isuruf** [comment]
> . The traceback in the log linked from conda-forge/setuptools-feedstock#222 (comment) is pretty clear:

Sure, but this exception is caught and the exception handling code path throws the next exception.

**Comment by isuruf** [comment]
> That fix was either incomplete

Yep. See https://github.com/pypa/distutils/pull/89

**Pull request merged**
