### PR TITLE
ENH: Add new ``numpy.ma.*`` aliases

### PR DESCRIPTION
**Pull request by bsipocz**
This is the stashed and rebased version of https://github.com/numpy/numpy/pull/17480 which contained some conflicting changes as https://github.com/numpy/numpy/pull/19899 has already added some of the aliases.

The first commit is purely the cleaned up previous PR, that is now closed, I'll follow-up with potentially necessary changes once CI has run.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
I guess the main high-level question for me is: do we really want to expand the suite of `ma` creation functions? AFAIK the original motivation for this was actually fixing broken links in the docs, *not* users asking for masked versions of `ones`, `zeros`, etc. Broken doc links seems like a weak motivation for expanding the API footprint, especially in the `ma` package, which is notorious for subtle divergences from its `ndarray` counterparts. OTOH if these creation functions address actual use-cases or fulfill user needs, then :+1: .

**Comment by bsipocz** [comment]
@rossbar - I don't have a specific need for these, was doing issue and PR triage. If the decision is to not extend then we should go back and tell it to multiple PR authors, and close off issues, too so people know that there is a decision. 

OTOH, a solution for broken links should be figured out, too, it's not OK to keep them around broken because the actual underlying code is not supposed to contain functionality that is linked to, but that is a separate, and maybe already fixed issue.

**Comment by bsipocz** [comment]
My sole motivation was to wrap up almost ready PRs, e.g. https://github.com/numpy/numpy/pull/17480 which needed a rebase to pick up new CI and resolve conflicts, but otherwise was ready to go, based on the comments. Another similar one is https://github.com/numpy/numpy/pull/17500 which was separated out from https://github.com/numpy/numpy/pull/17480.

Note that I've already closed #17480 as it was conflicting, some of the aliases have been already been added, but basically, this one and #17500 have to go hand in hand, either close both as unwanted puppies/extensions of np.ma (absolutely valid decision) or merge them sometimes in the near future.

**Comment by mattip** [comment]
I am inclined to close this and not merge it until there is a clear use case for these functions. Is there anyone who is championing the additions and can point to their use-case for them?

**Comment by InessaPawson** [comment]
> I am inclined to close this and not merge it until there is a clear use case for these functions. Is there anyone who is championing the additions and can point to their use-case for them?

@mattip Shall we ask on the mailing list?

**Comment by mattip** [comment]
I started a [mailing list discussion](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/P6RLDSCGXXTAUVDHUQAJZFKUOOOQZDE6/)

**Comment by mattip** [comment]
Thanks @bsipocz. The mailing list did not bring up any use cases, so let's close this and try to fix the documentation in a different way.

**Comment by bsipocz** [comment]
Thanks @mattip. I suppose then the same logic applies to #17500 and we should close that one, too.

**Pull request closed without merging**
