### PR TITLE
Allowing unicode fmt in savetxt.

### PR DESCRIPTION
**Pull request by Dapid**
If the fmt is unicode, it will be re-encoded in ASCII before use.

Raises an error if the conversion is not possible.

I have to add a test, but I don't know where are they sitting.

### CODE REVIEW

**Comment by cdeil** [comment]
I just ran into this same issue, see here:
https://travis-ci.org/astropy/regions/jobs/179816687#L1057

To give a minimal example, what we're doing it passing unicode for `fmt`, which fails on Python 2:
```python
>>> import numpy as np
>>> from __future__ import unicode_literals
>>> np.savetxt('/tmp/test.txt', np.arange(10), fmt='%12.8e')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1143, in savetxt
    raise ValueError('invalid fmt: %r' % (fmt,))
ValueError: invalid fmt: u'%12.8e'
```

Passing a unicode `fmt` does already now work on Python 3:
```python
np.savetxt('/tmp/test.txt', np.arange(10), fmt='%12.8e')
```

Passing bytes works on Python 2 and 3 (I only tested 2.7 and 3.5, and don't care about older versions for the project where the issue occured)
```python
np.savetxt('/tmp/test.txt', np.arange(10), fmt=b'%12.8e')
```
I guess using bytes literals is the recommended workaround for now?

The docstring says:
> fmt : str or sequence of strs, optional
https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html

---

This pull request seems to have stalled in 2013. I'm still seeing the issue with numpy `1.11.2`.

@Dapid or any of the other numpy devs -- do you have time to revive this PR or make a new one?

---

I think I've run into such an issue before with some other numpy function. It seems that this is something that could be automated to a large degree: use type annotations others have built (like the PyCharm folk) for numpy to make a list of all such arguments that should work with bytes and unicode input on Python 2 and 3, and try to auto-generate tests that call them with all four cases to get a list of functions / parameters that have this issue?
Is it worth making a separate issue to propose / pursue this idea?

**Comment by mattip** [comment]
The test in the [comment above](https://github.com/numpy/numpy/pull/4053#issuecomment-263808221) fails on 1.14.2, the small pure python PR looks like it could still be applied to master. @Dapid would you like to rebase this and try again?

**Comment by eric-wieser** [comment]
If the format string is unicode, then I'd argue that either:

* The `encoding` argument should be specified
* A pre-opened unicode file should be passed

Does it succeed for both of these cases?

**Comment by pierre-haessig** [comment]
I had forgotten about this problem a long time ago, but anyway it's nice to know it's been fixed!

Thanks @seberg !

**Pull request closed without merging**
