### PR TITLE
Update versionner

### PR DESCRIPTION
**Pull request by Kshitish555**

### CODE REVIEW

**Comment by bashtage** [comment]
Any hint as to why this is needed?

**Comment by Kshitish555** [comment]
Because the list index out of range.

**Comment by bashtage** [comment]
How is this code hit?  CI passes without this change. It is only intended to be used with commands that have 2 args?  Is this code even needed?

**Comment by Kshitish555** [comment]
`Yes, you are right CI is easily pass without change. But If any user put 2 args. May be it will throw the error and I think that will not good for numpy. We don't know what types of input we will get from users. I think we should put error handling code her to avoid this error.

**Comment by bashtage** [comment]
What specific correct inputs cause this to error?  It seems the correct fix would be to check that there are at least 2 inputs and if not to provide a more meaningful error. 

I'm not convinced that this code is ever run though, which makes modifying it a bit of an exercise in futility.

**Comment by bashtage** [comment]
To be 100% clear, I think `verioneer.py` is not intended to be run by end users. Th eonly plae this file is ever used in NumPy is through an import in `setup.py`.

**Comment by Kshitish555** [comment]
`verioneer.py` is run through `setup.py`. But still `setup.py` can't avoid this issue on `verioneer.py`. Our main agenda should be avoid every error in the code. No doubt this `verioneer.py` file through error.

**Comment by Kshitish555** [comment]
Screenshot

You handle this handle with try and  except. This `verioneer.py` through error. But with this we can avoid this error

**Comment by bashtage** [comment]
This code is only executed when `versioneer.py` is directly called from Python, not when it is used as a stand alone module.   This is what the `__name__ = "__main__"` check does.  

IMO no change is needed here. `versoneer.py` is _only_ [used once](https://github.com/python-versioneer/python-versioneer) directly. 

If one is needed, the fix should be checking the length and telling the users that at least two arguments are needed. But like I said above, this is the format of all copies of `versioneer.py` all over the internet.

pandas
https://github.com/pandas-dev/pandas/blob/e7c1ef71d80797cab0bffda8c47948261cffc139/versioneer.py#L1907
statsmodels
https://github.com/statsmodels/statsmodels/blob/c5abe558dcdb54c47894ffec6fab0e94f63ebe8c/versioneer.py#L1816
versioneer's source
https://github.com/python-versioneer/python-versioneer/blob/7353832af2971eb6128cc513499cdef5fd12c099/src/setupfunc.py#L183

**Comment by charris** [comment]
I agree that this is not needed. Versioneer is only run directly during installation/upgrading.

**Pull request closed without merging**
