### PR TITLE
WIP: use openmp vector function ABI for sin, cos, exp and log

### PR DESCRIPTION
**Pull request by juliantaylor**
glibc provides sin, cos, exp, log, pow and sincos with this ABI since 2.22 for sse4 and AVX2.
https://sourceware.org/glibc/wiki/libmvec
In this branch I have added support for the first four which provides significant speedup over the scalar functions.

It is implemented directly via the ABI instead of relying on compiler support to do so automatically. Using the compiler would be nicer (especially since gcc can do auto cloning) but this might be more portable.

There are still a couple issues but it should be testable.
- the vectorized functions are also less accurate so there are some failures in scipy due to slightly different results
- no AVX autodetection so you have to build with `OPT=-mavx2`
- the glibc implementation uses SSE4 but falls back to the scalar ones if that is not available, this might not be the case for other implementation (e.g. svml) so could be a problem, the branch only checks for sse2 which is all that is needed on the numpy side.
- ~~npymath now requires a link to libmvec which could be a problem for third parties~~ (but still a hack in linalg_umath which likely will cause a failure in travis)

### CODE REVIEW

**Comment by juliantaylor** [comment]
added power support and solved the npymath problem, forgot about the mlib.ini

**Comment by charris** [comment]
Failed build and needs rebase.

**Comment by mattip** [comment]
@juliantaylor it seems we are going in the direction of adding direct support for intrinsics in gh-13368, gh-13885, gh-13516. Should we discuss using external glibc or other packages to do this for us instead?

**Comment by mattip** [comment]
Closing, since it seems we will not be able to merge this with our current approach. Please reopen if I am mistaken.

**Pull request closed without merging**
