### PR TITLE
REF: Clean up wheels workflow [wheel build]

### PR DESCRIPTION
**Pull request by lithomas1**

### CODE REVIEW

**Comment by lithomas1** [comment]
This seems working now. GHA matrices are still a little crude, so the solution is a bit kludgy, but it should still be a net improvement over the previous version.
@mattip for review.

**Comment by mattip** [comment]
Thanks. The artifact available from the bottom of the build summary weighs in at 201MB and has 14 wheels: 6 python3.8 (macos-x86_64, macos-arm64, manylinux2014, win_amd64, pypy-manylinux, pypy-win_amd64), 4 each python3.9 and python3.10 (macos-x86_64, macos-arm64, manylinux2014, win_amd64)

**Comment by mattip** [comment]
Thanks @lithomas1

**Comment by mattip** [comment]
From issue #20262, we are still missing 32-bit windows for CPython. Is there a way to do that with cibuildwheel?

**Pull request merged**
