### PR TITLE
testing

### PR DESCRIPTION
**Pull request by charris**
Big nothing, do not merge.

### CODE REVIEW

**Comment by jakirkham** [comment]
Doesn't look like it happens on Python 2.

**Comment by charris** [comment]
@jakirkham This is current master. @juliantaylor I'm going to guess that it has something to do with the flags Python 3.5 x86 was compiled with on windows, Numpy inherits those flags.

**Comment by jakirkham** [comment]
I guess in the merge, but the parent commit (d05b94544a060e8197bb3f8c2955cd8aedfacfff) is 19 days old.

**Comment by charris** [comment]
Not sure what you are talking about. I think the problem is #6980. Let me try a revert here and see what happens...

**Comment by charris** [comment]
OK, I already had a testing branch, so what is here was an accident. I'll fix that.

**Comment by jakirkham** [comment]
Sorry. Maybe I misunderstood the purpose of this, but I thought you were trying to see if https://github.com/numpy/numpy/pull/6980 was **also** a problem on Python 2 with x86 architecture.

**Comment by charris** [comment]
I was, but I messed up ;) I have a new one up with that merge reverted.

**Comment by jakirkham** [comment]
Oh, ok. No worries. I am guessing you mean this one ( https://github.com/numpy/numpy/pull/6993 ).

**Pull request closed without merging**
