### PR TITLE
BUG: Fix inf and NaN-warnings in half float `nextafter`

### LINKED ISSUE #15977: nextafter(float16(inf), float16(0)) returns nan and issues `RuntimeWarning: invalid value`
### Reproducing code example:

Numpys `nextafter` for the `float16` representation of `inf` gives `nan` rather than `finfo(float16).max`:

```python
import numpy as np
np.nextafter(np.float16(np.inf), np.float16(0))
```

### Error message:

The result is:

```
<stdin>:1: RuntimeWarning: invalid value encountered in nextafter
nan
```

I would have expected:
- no RuntimeWarning, as infinity should be valid in `nextafter`
- a return value of `65500.0`, which is `finfo(float16).max`.

### Numpy/Python version information:

```
>>> print(np.__version__, sys.version)
1.18.1 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]
```

### PR DESCRIPTION
**Pull request by adam4130**
Fix  #15977

### CODE REVIEW

**Comment by eric-wieser** [comment]
This also needs a test that `nextafter` actually returns the right value, not just that it no longer errors!

**Comment by Qiyu8** [comment]
just as @gerritholl  noticed, `np.nextafter(np.float16(np.inf), np.float16(0))`  should return` 65500.0`, more np.inf tests should added.

**Comment by adam4130** [comment]
> just as @gerritholl noticed, `np.nextafter(np.float16(np.inf), np.float16(0))` should return` 65500.0`, more np.inf tests should added.

Thanks for the feedback. This case should be implicitly included by https://github.com/numpy/numpy/pull/15988/commits/2fe8a8c66885fd30f0aaf75667109b35a4596169#diff-17d79930c8c56b22e5bde831187c9e56R340 since `a_f16[0] = 0.0` and `a_f16[-1] = 65500.0`. Should I still add the case you mentioned?

**Comment by seberg** [comment]
@adam4130 yeah you can use `a_f16[-1]` and `-a_f16[-1]`, to check the result.

**Comment by Qiyu8** [comment]
> This case should be implicitly included by [2fe8a8c#diff-17d79930c8c56b22e5bde831187c9e56R340](https://github.com/numpy/numpy/commit/2fe8a8c66885fd30f0aaf75667109b35a4596169#diff-17d79930c8c56b22e5bde831187c9e56R340) since `a_f16[0] = 0.0` and `a_f16[-1] = 65500.0`. Should I still add the case you mentioned?

Both x and y can be hinf or -hinf, I think four more test cases is enough.

**Comment by seberg** [comment]
Hmmm, I had remembered an older version or simply incorrect, nvm.

**Comment by seberg** [comment]
Sorry, for only taking a courteous look before. I think the title of the issue report through us of. `np.nextafter(np.finfo(np.float64).max, np.inf)` *does* give an *overflow* warning. I think the change we have to make is that an overflow warning is given when `x` was finite no matter whether `y` was?

**Comment by adam4130** [comment]
@seberg I replaced that last commit, removing y. I think we should now have the desired overflow behavior which we already test for here: https://github.com/numpy/numpy/blob/master/numpy/core/tests/test_half.py#L482-L483.

**Comment by seberg** [comment]
Oh right, it was always correct, the second check was simply unnecessary.

**Comment by seberg** [comment]
It seems that `np.nextafter(np.nan, np.inf)` (or other variations with NaN) actually do not give a warning on my system at least. I guess that is actually slightly more correct? Since the invalid warning should normally be given when an invalid value is *generated*, not when an invalid value is *involved* in the operation. The fix looks great though, so maybe I will just merge this, or do you want to think about/follow up on that as well?

**Comment by adam4130** [comment]
I think it would be a little odd having `np.nextafter(np.nan, np.inf)` generate no warning while `np.nextafter(np.float16(np.nan), np.float16(np.inf))` does. It would be easy an change to remove it from the float16 case.

**Comment by seberg** [comment]
Thanks for fixing up all the small followup things as well, LGTM.

**Pull request merged**
