### PR TITLE
BUG: Backport #7254

### PR DESCRIPTION
**Pull request by ahaldane**
backport of #7254

Closes gh-7203.

I will leave it to someone else to merge if it looks like I did the backport correctly.

### CODE REVIEW

**Comment by gfyoung** [comment]
LGTM.  Thanks for doing this!

**Comment by gfyoung** [comment]
In light of #7284, please no one merge this until that issue is closed.

**Comment by charris** [comment]
LGTM, Thanks @ahaldane .

**Comment by gfyoung** [comment]
@charris : Read my message above.

**Pull request merged**
