### PR TITLE
DOC: Fix incorrect formula in gradient docstring.

### LINKED ISSUE #10545: Mistake in documentation of numpy.gradient
Under "Notes" the second line in the second equation should read 
                \\beta h_{d}-\\gamma h_{s}=1 \\\\

### PR DESCRIPTION
**Pull request by hobler**
DOC: Bug fix in explanatory note for the gradient function. Fixes #10545 

Original rendered docs [here](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.gradient.html)

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Looks correct to me. Maybe we should add another step in the working, doing the second-order tailor expansion, to make that obvious?

**Comment by ahaldane** [comment]
I think it's fine to leave out the math. The fix looks right to me too.

But while we're here, can we discuss more fixups nearby? We can add them as github edits once we're decided.

I think we should reword
```
    Assuming that :math:`f\\in C^{3}` (i.e., :math:`f` has at least 3 continuous
    derivatives) and let be :math:`h_{*}` a non homogeneous stepsize, the
    spacing the finite difference coefficients are computed by minimising
    the consistency error :math:`\\eta_{i}`:
```
to
```
    Assuming that :math:`f\\in C^{3}` (i.e., :math:`f` has at least 3 continuous
    derivatives) and let be :math:`h_{*}` a non homogeneous stepsize, we
    minimize the "consistency error" :math:`\\eta_{i}` between the true gradient 
    and an estimate of it as a linear combination of the neighboring grid-points:
```

Also, just a comment: I was not able to find this precise equation in the 3 references listed, so it took me a minute to understand the assumptions here. There are a ton of finite difference schemes so it would be nice to have clearer link to a reference, to learn more about this one. It looks like we already discussed this here: https://github.com/numpy/numpy/pull/8446#discussion_r95469793

**Comment by eric-wieser** [comment]
@ahaldane: your proposed change looks good to me.

**Comment by ahaldane** [comment]
Unless @hobler wants to make that change too, I think we can merge this PR and then make those changes in another PR.

So I'll merge in a few hours if there are no more comments.

**Comment by charris** [comment]
Thanks @hobler 

@ahaldane Please make a PR with your suggested wording.

**Pull request merged**
