### PR TITLE
MAINT: Remove check for SETUPTOOLS_USE_DISTUTILS in setup.py

### PR DESCRIPTION
**Pull request by mkoeppe**
This check was added in #20963 in an attempt to make numpy "more tolerant of setuptools >= 60". However, when `pip -install --no-build-isolation` is in use, (compared to numpy 1.21.x) this added check actually made numpy **less** tolerant of setuptools >= 60. 

In Sage, we use `SETUPTOOLS_USE_DISTUTILS=local` because we need to work around broken python 3.8 and 3.9 on Homebrew, which install a custom and problematic `distutils.cfg`. 

Ref: https://trac.sagemath.org/ticket/32423#comment:53, https://trac.sagemath.org/ticket/31335, https://trac.sagemath.org/ticket/31348#comment:38, https://github.com/Homebrew/homebrew-core/pull/91043#issuecomment-1032079055

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
@mkoeppe I appreciate your pain, but there are other issues with `setuptools.distutils` and I'm honestly not interested in working on that anymore. `setuptools.distutils` is unsupported, and I'd rather not re-enable it and then see new bug reports streaming in. 

Is it possible for you to keep this as a patch in Sage?

**Comment by rgommers** [comment]
> because we need to work around broken python 3.8 and 3.9 on Homebrew,

Re Homebrew, if it's for the `numpy` packaged inside Homebrew, then Homebrew can carry this patch. If it's for using a virtualenv on top of Homebrew: please don't do that, see https://justinmayer.com/posts/homebrew-python-is-not-for-you/

**Comment by mkoeppe** [comment]
> Is it possible for you to keep this as a patch in Sage?

Yes, we can keep it as a patch

**Comment by mkoeppe** [comment]
> If it's for using a virtualenv on top of Homebrew: please don't do that, see https://justinmayer.com/posts/homebrew-python-is-not-for-you/

One hears "distro python is broken" quite often, but in my experience the homebrew python maintainers are responsive to issues, and their packaging does provide added value compared to upstream CPython when new macOS versions are released.

Other ways to provision CPython are broken too, for example https://github.com/pyenv/pyenv/issues/2204

Haven't tried asdf yet, which was suggested in the linked article

**Comment by rgommers** [comment]
> One hears "distro python is broken" quite often, but in my experience the homebrew python maintainers are responsive to issues, and their packaging does provide added value compared to upstream CPython when new macOS versions are released.

That is true - for build/CI usage it should be okay. I think the article makes the point that it should not be used for longer-term usage, because Homebrew is not designed for that and it will happily move from under you and break all of your venvs.

**Comment by rgommers** [comment]
@mkoeppe if it helps you, I would be fine with merging an override in the form of an environment variable to disable this check, if that's easier than carrying a patch. I'd just much prefer to not remove the default of erroring out with a clear message.

**Comment by mkoeppe** [comment]
> @mkoeppe if it helps you, I would be fine with merging an override in the form of an environment variable to disable this check, if that's easier than carrying a patch.

Carrying a patch is fine for Sage, but it might be easier to other users if there's an override

**Comment by charris** [comment]
I'm going to close this. Thanks @mkoeppe for the PR, and if a better solution is decided on, feel free to post another.

**Pull request closed without merging**
