### PR TITLE
MAINT: Explicitly disallow object user dtypes

### PR DESCRIPTION
**Pull request by seberg**
These never worked to the best of my knowledge, so disable
it explicitly to hopefully simplify cleanup in other parts.

---

I don't think this is any limitation, but I would like to bake this in explicitly, so that it may be easier to clean up other parts.

### CODE REVIEW

**Comment by eric-wieser** [comment]
@EricCousineau-TRI, did you end up using custom object dtypes in your work?

**Comment by seberg** [comment]
I am having doubts that it works, because we do have quite a few `descr->type_num == NPY_OBJECT` checks around, e.g. in cleanup code.  Although, I agree that an exact subclass of Object (which is fine e.g. with None initialization) is probably close to workable.

**Comment by EricCousineau-TRI** [comment]
Just to confirm, I can think of 3 diff. things you may be asking:

(1) Use `dtype=object`:
`np.array([CustomClass()], dtype=object)`; 

(2) Explicit user dtype, but using `NPY_OBJECT`-ish codepaths via `NPY_ITEM_IS_POINTER | NPY_ITEM_REFCOUNT`:
`np.array([CustomClass()], dtype=CustomClass)`, where `issubclass(CustomClass, object) and not issubclass(CustomClass, np.generic)`

(3) Custom user dtype (using `np.void` I think):
`np.array([CustomClass()], dtype=CustomClass)`, where `issubclass(CustomClass, np.generic)`

I think you're asking about (2) - is that correct?
If so, then nah, we didn't use that. (I believe)

Thanks for checking!

---

In Drake, we currently use (1): [drake code](https://github.com/RobotLocomotion/drake/blob/04396b46dc5e5505f1aebe79264619f8061f6bb2/bindings/pydrake/autodiff_types_pybind.h#L29), [pybind11 code](https://github.com/RobotLocomotion/pybind11/blob/5dfa2b35b7e8fd2c2c01c8f7f6d87faf808e8cbd/include/pybind11/numpy.h#L1268-L1284)

I had played with / bothered y'all about (3), but it's been stalled: [drake PR](https://github.com/RobotLocomotion/drake/pull/8452/files), [drake / pybind code](https://github.com/EricCousineau-TRI/drake/blob/ab1735ef6451b1fdc3b4f62852c21e1731312d65/bindings/pybind11_ext/numpy_dtypes_user.h#L730-L746)

**Comment by seberg** [comment]
Yes, this is about (2), (1) is obviously OK. But, (3) I am curious about can you give details on what you are doing? Is that just a custom `np.void` (structured) dtype instance or are you actually creating your own subclass?  And if your own subclass, I assume that does _not_ use any fields, but is very basic?

**Comment by EricCousineau-TRI** [comment]
Sweet! Yeah, then nah, not using (2) at all.

> Is that just a custom np.void (structured) dtype instance or are you actually creating your own subclass? And if your own subclass, I assume that does not use any fields, but is very basic?

It's the latter - a subclass. And correct, no fields. I was basically following the `rational` class here:
https://github.com/numpy/numpy/blob/4a54bc458b93adbea75cb3ba05978ab327ff1552/numpy/core/src/umath/_rational_tests.c.src#L890-L910

If you want to look, this is our issue here: https://github.com/RobotLocomotion/drake/issues/8116

**Comment by seberg** [comment]
Hmmm, we don't support custom destruction at this time though?  Curious how important that is for you, or whether e.g. a specific Python object stored would also be a reasonable solution?  It is one of the things that I felt like putting off for a while.

**Comment by EricCousineau-TRI** [comment]
>  Curious how important that is for you [...]

If we want to achieve reference semantics (e.g. for manipulating large arrays of our custom dtypes with minimal overhead), and container redirection for whatevs reason didn't work, then destructors (and proper constructors) would be pretty important. I may not get to this for another year, so it's not a pressing timeline by any means.

**Comment by EricCousineau-TRI** [comment]
> [...] or whether e.g. a specific Python object stored would also be a reasonable solution?

Not sure if I understand this suggestion. Are you talking about something like (2), or something different from those?

If you are talking about (2), then nah, I don't think that'd fix our problems, b/c we want to be able to have the array memory for our custom dtypes be densely allocated; with Python objects (in any form), it'd have to be sparse, I think?

**Comment by seberg** [comment]
Well, I hope to revamp everything in the next year (so you would need to redo some things), I am mainly concerned about breaking existing working strange user-dtypes.  Although, depending on how actively you are developing this, I guess that may actually be fine, as long as a better alternative comes around?

**Comment by EricCousineau-TRI** [comment]
I don't think I'll do any intense stuff on my existing stuff for (3), and I wouldn't necessarily qualify it as "working" per se :P
I'd be totes fine if that setup changes, esp. if there's a better alternative!

Thanks!

**Comment by mattip** [comment]
Should we put this in to flush out other potential users?

**Comment by seberg** [comment]
I would say so, I would rather err on the noisy side with these fairly corner case things to be honest.

**Comment by mattip** [comment]
Thanks @seberg

**Pull request merged**
