### PR TITLE
MAINT: Give the `_<X>Like` and `_ArrayLike<X>` type aliases a more descriptive name

### LINKED ISSUE #18096: typing aliases for integer-like
When trying to use `numpy.typing`-provided aliases for integer-like scalars in https://github.com/scipy/scipy/pull/10844#pullrequestreview-559980027, I noticed that `numpy.typing` doesn't have the right alias. It does have:
```
_IntLike = Union[_BoolLike, int, np.integer]
```
but accepting bools as 0/1 where integers are expected isn't good practice.

Accepting integers for float-like is fine, and mypy does accept `int` if you annotate a variable as `float`. Complex I'm not sure about, but I'd think it's undesirable to accept ints/floats for complex-like.

### PR DESCRIPTION
**Pull request by BvB93**
Closes https://github.com/numpy/numpy/issues/18096.

This PR renames the `_<X>Like` and `_ArrayLike<X>` aliases to, respectively, `_<X>Like_co` and `_ArrayLike<X>_co`.

The goal of this change is to emphasize that aforementioned type aliases are _not_ invariant; 
they represent _all_ objects that can be cast into `<X>` (using `casting="same_kind"`).
The aliases are now thus marked (by convention) as covariant, despite the objects contained 
therein not necessarily being formal sub-types of `<X>`.

Examples
----------
``` python
from typing import Union
import numpy as np

# `_BoolLike_co` and `_BoolLike` would actually be equivalent here
_BoolLike_co = Union[bool, np.bool_]
_IntLike_co = Union[_BoolLike_co, int, np.integer]
```

### CODE REVIEW

**Comment by BvB93** [comment]
As a side note: this PR has some minor (name-related) merge conflicts with https://github.com/numpy/numpy/pull/18128.

**Comment by charris** [comment]
Looks good to me. Maybe `cov` instead of `co`? The latter has no obvious meaning.

**Comment by BvB93** [comment]
> Looks good to me. Maybe `cov` instead of `co`? The latter has no obvious meaning.

It is used consistently as suffix in both [typeshed](https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L71) and [typing](https://docs.python.org/3/library/typing.html#typing.Sequence) when referring to covariant typevariables, 
so I'd argue there is very much a precedent for using `co`.

**Comment by charris** [comment]
Thanks Bas.

**Comment by pfheatwole** [comment]
> > Looks good to me. Maybe `cov` instead of `co`? The latter has no obvious meaning.
> 
> It is used consistently as suffix in both [typeshed](https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L71) and [typing](https://docs.python.org/3/library/typing.html#typing.Sequence) when referring to covariant typevariables,
> so I'd argue there is very much a precedent for using `co`.

For anyone else trying to educate themselves on this issue, another reference is [PEP 484](https://www.python.org/dev/peps/pep-0484/), in the section [Covariance and Contravariance](https://www.python.org/dev/peps/pep-0484/#id26):

> By convention, it is recommended to use names ending in `_co` for type variables defined with `covariant=True` and names ending in `_contra` for that defined with `contravariant=True`.

**Pull request merged**
