### PR TITLE
BUG: fix MANIFEST.in for removal of a file in gh-8047.

### PR DESCRIPTION
**Pull request by rgommers**
oops

### CODE REVIEW

**Comment by njsmith** [comment]
I was going to make a joke about requiring a test for this, but... actually it would be good if our Travis builds generated an sdist and then built from it, at least sometimes?

**Comment by rgommers** [comment]
Sounds like a plan. Let's do that in a separate PR though - this needs to go in asap.

**Comment by njsmith** [comment]
Deal.

**Comment by njsmith** [comment]
Actually, it looks like Travis *did* notice the problem here: https://travis-ci.org/numpy/numpy/builds/88208291
...it's just that we didn't see it because of the `[ci skip]` in the original pull request (#6582). Doh. Maybe we should just stop using `[ci skip]`? Better safe than sorry and all that?

(Also, the reason the Travis build failed is a bit weird -- apparently `pip install .` issued a warning and the warning got caught by some code that greps the build logs for warnings: https://github.com/numpy/numpy/blob/master/tools/travis-test.sh#L34
so it might still make sense to exercise the sdist functionality.)

**Comment by rgommers** [comment]
> Actually, it looks like Travis did notice

yes, that's why I saw it so quickly.

> Maybe we should just stop using ``[ci skip]``? Better safe than sorry and all that?

For numpy TravisCI runs are pretty fast now, so maybe a good idea. I'm used to it for scipy though, where it makes less sense to me to burns ~5 hours of cumulative build/test time for trivial fixes. 

Or not, because I can't remember a case where ``[ci skip]`` has ever been a real problem. It's at most something like this, and then you'll fix it in 5 min within a day.

**Comment by njsmith** [comment]
Meh, depends how willing you are to keep track of things manually, and I am
lazy. If we charged market rates for our time, this bug has cost a few
hundred dollars / euros, which is about a year of cpu time...

**Comment by rgommers** [comment]
It really cost me 5 min (plus replying to you) to fix, so I wish that that was my market rate:)

**Comment by njsmith** [comment]
it's true, I'm also counting the time required to root-cause the issue and
discuss it :-)

On Fri, Oct 30, 2015 at 1:02 AM, Ralf Gommers <notifications@github.com>
wrote:

> It really cost me 5 min (plus replying to you) to fix, so I wish that that
> was my market rate:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/pull/6587#issuecomment-152454255>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Pull request merged**
