### PR TITLE
TYP,BUG: Reduce argument validation in C-based ``__class_getitem__``

### LINKED ISSUE #22185: BUG: ndarray subclasses always require both type arguments at runtime
### Describe the issue:

For ordinary generic classes, (e.g. `class Foo(Generic[A, B])`) subclasses can fix one or more of the generic parameters (e.g. `class FooSubclass(Foo[Any, A])`. After doing so, any reference to the type only has to supply the remaining free `TypeVar`s (e.g. `FooSubclass[float]` instead of `FooSubclass[Any, float]`. This doesn't seem to work with `ndarray`. No matter how many generic parameters are fixed at subclass definition time, future references to the subclass type throw an error at runtime when not given two types.

### Reproduce the code example:

```python
from typing import Any, Generic, TypeAlias, TypeVar

import numpy as np

A = TypeVar("A")
B = TypeVar("B")

class Foo(Generic[A, B]): ... # Define two parameter generic analogous to ndarray
class FooSubclass(Foo[Any, A]): ... # Define partially saturated subclass

class Subclass(np.ndarray[Any, A]): ... # Define partially saturated subclass

x: TypeAlias = Foo[Any, A] # Define partially saturated TypeAlias. No problem
y: TypeAlias = x[float] # Use partially saturated TypeAlias. No problem
z: TypeAlias = FooSubclass[float] # Use partially saturated subclass. No problem 

a: TypeAlias = np.ndarray[Any, A] # Define partially saturated TypeAlias. No problem
b: TypeAlias = a[float] # Use partially saturated TypeAlias. No problem
c: TypeAlias = Subclass[float] # Use partially saturated subclass. Problem
```

### Error message:

```shell
Traceback (most recent call last):
  File "temp.py", line 19, in <module>
    c: TypeAlias = Subclass[float]
TypeError: Too few arguments for Subclass
```

### NumPy/Python version information:

1.22.4 3.10.1 (main, Dec  6 2021, 18:38:26) [GCC 10.3.0]

### Context for the issue:

My initial motive was subclassing `ndarray` and using the subclass type to witness validations (e.g. that the matrix is a covariance matrix) (see the "smart constructor" pattern). But more broadly, this bug seems like it would affect almost anyone who is trying to subclass `ndarray` and also use Python's typing features.

### PR DESCRIPTION
**Pull request by BvB93**
Closes https://github.com/numpy/numpy/issues/22185

The `__class_getitem__` implementations would previously perform basic validation of the passed value, _i.e._ it would check whether a tuple of the appropriate length was passed (_e.g._ `np.dtype.__class_getitem__` would expect a single item or a length-1 tuple). As noted in aforementioned issue: this approach can cause issues when (a. 2 or more parameters are involved and (b. a subclasses is created one or more parameters are declared constant (_e.g._ a fixed dtype & variably shaped array).

This PR fixes aforementioned issue by removing any and all runtime argument validation, thus mimicking the behavior of the standard library. While we could alternatively fix this by adding more special casing (_e.g._ only disable validation when `cls is not np.ndarray`), I'm not convinced this would be worth the additional complexity, especially since the standard library also has zero runtime validation for all of its `Py_GenericAlias`-based implementations of `__class_getitem__`.

Examples
---------
The issue prior to this PR:
``` python
In [1]: import numpy as np
   ...: from typing import TypeVar, Any

In [2]: ShapeType = TypeVar("ShapeType")

# Variable shaped & fixed dtype
In [3]: class FooArray(np.ndarray[ShapeType , np.dtype[np.int64]]): ...

# Uhoh, __class_getitem__ still expects both a shape and dtype parameter
In [4]: FooArray[Any]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 FooArray[Any]

TypeError: Too few arguments for FooArray
```

### CODE REVIEW

**Comment by seberg** [comment]
Is there a new test missing for the code reported in the issue?  It does look correct to me for simplification of the code and I guess it is fine to relax the cases where the error was desired before?

Or do the current checks actually make sense, expect that we should be using `num_args <= 1` rather than `num_args == 1`?

Some tests are failing:
```
    @pytest.mark.parametrize("code", np.typecodes["All"])
    def test_concrete(self, code: str) -> None:
        cls = np.dtype(code).type
>       assert cls[Any]
E       TypeError: 'type' object is not subscriptable
```

**Comment by BvB93** [comment]
The latest rebase + https://github.com/numpy/numpy/pull/22212/commits/3947391d1a2225d8c4498f518c03097d2e02ee70 should address some missing test cases plus a fix for the previously too hastily altered `number.__generic_alias__` tests.

> Or do the current checks actually make sense, expect that we should be using num_args <= 1 rather than num_args == 1?

That would be pretty good option here actually, since there is no way an `ndarray` subclass can have *more* than 2 generic parameters without explicitly overriding `__class_getitem__` (at which point it's the users responsibility to implement it correctly).

**Comment by BvB93** [comment]
Updated using Sebastian's suggestion here: https://github.com/numpy/numpy/pull/22212#issuecomment-1238072061.
Should be good to go once CI is green.

**Comment by charris** [comment]
Should/can this be backported?

**Comment by BvB93** [comment]
> Should/can this be backported?

Yes; I don't expect that the relevant code paths have been touched ever since the introduction of `__class_getitem__`, so I don't anticipate any merge conflicts.

**Comment by seberg** [comment]
OK, lets give this a shot, changes look fine to me and I guess worst case we relax a bit more than necessary.  Thanks Bas!

The only thing I could think of, would be checking whether we are on the base class, which might make sense.  But I am not sure the added complexity is actually worth it.

**Pull request merged**
