### PR TITLE
BUG: Missed a case in the diff merge for #22110

### PR DESCRIPTION
**Pull request by Developer-Ecosystem-Engineering**
When merging #22110, one of the cases was missed.

### CODE REVIEW

**Comment by charris** [comment]
Thanks @Developer-Ecosystem-Engineering, off to test :)

**Comment by Developer-Ecosystem-Engineering** [comment]
🤞🤞

**Comment by charris** [comment]
Looks good.

**Comment by Developer-Ecosystem-Engineering** [comment]
🎉 thanks for your patience =)

**Pull request merged**
