### PR TITLE
BUG: Avoid intp conversion regression in Cython 3

### PR DESCRIPTION
**Pull request by seberg**
In the Cython 3 `__init__.pxd` `intp` was defined to `Py_ssize_t` which is *correct*.  However, Cython has special rules for `Py_ssize_t`. It uses the `PyNumber_AsIndex` (`operator.index`) function for conversion which rejects for example floats.

Of course I prefer that behavior, but:
1. There is no great reason why `np.intp_t` should be all that special.
2. Changing it silently changes downstream (and `np.random`) behavior.

It would be awesome if Cython would allow transitioning to using `operator.index()` style coercion since you can still explicitly convert via `int()`.

Now, why the new definition to `signed long`!?  `ssize_t` doesn't work because it is *also* special, using `PyLong_AsSize_t`. It seems to me that adding signed might give this type a bit of preference in promotion, so it is is just for good sport. (It is impossible to get Cython promotion fully right.)

### CODE REVIEW

**Comment by charris** [comment]
PRs that make you go um ... Is the long here an actual C long?

**Comment by seberg** [comment]
No, it tells Cython to make it behave *like* a C long, but it is whatever it is on the C level (which is an `npy_intp`).  The type is important only for how assignment works and also for how Cython does promotion.  (it was an `int` before!  if it was the actual type used by Cython it would go boom.)

**Comment by mattip** [comment]
LGTM. Is there a corresponding issue that this closes?

**Comment by seberg** [comment]
gh-25061 was it as it is really a more broad issue, but already closed in the narrow version.  I also ran into this in sklearn and the mtrand.pyx changes (which is undone here).

**Comment by charris** [comment]
In it goes, thanks Sebastian.

**Pull request merged**
