### PR TITLE
MAINT, DOC: Fixes minor formatting issue related to nested inline markup.

### LINKED ISSUE #20676: DOC: Wrong backtick escaping in Development workflow guide `ci_skip`
### Issue with current documentation:

The backticks of `ci_skip` are wrongly escaped see screenshot:
image

Here's the link to the relevant doc section: 
https://numpy.org/devdocs/dev/development_workflow.html#commands-to-skip-continuous-integration

And here's the offending code line:
https://github.com/numpy/numpy/blame/2f41a52d9b2fc70ea2bed6e04de470d854362ccd/doc/source/dev/development_workflow.rst#L208

### Idea or request for content:

_No response_

### PR DESCRIPTION
**Pull request by burkh4rt**
We adopt the solution suggested by @WarrenWeckesser in his discussion of the
issue [here](https://github.com/numpy/numpy/issues/20676#issuecomment-1003595547).

Closes #20676.

### CODE REVIEW

**Comment by charris** [comment]
Thanks @burkh4rt . The error looks unrelated.

**Comment by charris** [comment]
The error is probably pandas related, they released 1.4.0 today (Jan 22 2022).

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @burkh4rt! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Comment by burkh4rt** [comment]
Thank you @InessaPawson and @charris! I'm a long-time user of NumPy and it's been great taking a look at the underlying code.

**Pull request merged**
