### PR TITLE
ENH: Optimize performance of np.atleast_1d

### PR DESCRIPTION
**Pull request by eendebakpt**
In this PR we improve the performance of `np.atleast_1d` for the single argument case (and slightly improve for the other cases). 
The `np.atleast_1d` is used in many other methods as part of the input pre-processing ([Github search for np.atleast_1d](https://github.com/search?q=np.atleast_1d+language%3APython&type=code&l=Python)).

Benchmark
```
atleast_1d(1): Mean +- std dev: [main] 489 ns +- 16 ns -> [pr] 422 ns +- 9 ns: 1.16x faster
atleast_1d(x): Mean +- std dev: [main] 224 ns +- 9 ns -> [pr] 159 ns +- 7 ns: 1.41x faster
atleast_1d(1, x ): Mean +- std dev: [main] 592 ns +- 26 ns -> [pr] 605 ns +- 24 ns: 1.02x slower
polyadd: Mean +- std dev: [main] 2.50 us +- 0.11 us -> [pr] 2.26 us +- 0.08 us: 1.10x faster

Geometric mean: 1.15x faster
```

<details><summary>Benchmark script</summary>

```
import pyperf

runner = pyperf.Runner()

setup="""
import numpy as np
from numpy.polynomial import Polynomial

x = np.array([2, 3, 4])
y = np.array([2, 3])

p = Polynomial([1, 2, 3.])
"""   
runner.timeit(name=f"atleast_1d(1)", stmt=f"np.atleast_1d(1)", setup=setup)
runner.timeit(name=f"atleast_1d(x)", stmt=f"np.atleast_1d(x)", setup=setup)
runner.timeit(name=f"atleast_1d(1, x )", stmt=f"np.atleast_1d(1, x )", setup=setup)
runner.timeit(name=f"polyadd", stmt=f"np.polyadd(x, y)", setup=setup)
```
</details>

### CODE REVIEW

**Comment by ngoldbaum** [comment]
We looked at this at the triage meeting and think this needs asv benchmarks. It would be good to see that the slowdown for the list of arrays case is not significant. It would also be good to add a comment explaining that the single-element case is done first for performance reasons.

**Comment by eendebakpt** [comment]
> We looked at this at the triage meeting and think this needs asv benchmarks. It would be good to see that the slowdown for the list of arrays case is not significant. It would also be good to add a comment explaining that the single-element case is done first for performance reasons.

I added 3 benchmark functions. On my system there is no slowdown visible for the list of arrays case, but the asv runs are a bit noisy so the variation between main and this PR is typically smaller than the variations between different runs. @ngoldbaum Could you run the benchmarks independently?

**Comment by ngoldbaum** [comment]
Here's what I see running the new benchmarks on my laptop:

```
| Change   | Before [b2960879] <main>   | After [f6cb2a92] <atleast_1d>   |   Ratio | Benchmark (Parameter)                                      |
|----------|----------------------------|---------------------------------|---------|------------------------------------------------------------|
| -        | 206±10ns                   | 167±5ns                         |    0.81 | bench_shape_base.AtLeast1D.time_atleast_1d_single_argument |

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```

So on my machine, about 20% faster and any decrease in performance on the list-of-arrays case is less than 5%. Seems worth it to me!

**Comment by ngoldbaum** [comment]
Thanks @eendebakpt!

**Pull request merged**
