### PR TITLE
[WIP] configure Windows CI with AppVeyor

### PR DESCRIPTION
**Pull request by ogrisel**
At the moment I have registered this branch on my ogrisel account:

https://ci.appveyor.com/project/ogrisel/numpy

As you can see there are 9 errors in the tests caused by deprecation warnings. I have not investigated why it's happening. I don't have a windows host at hand at the moment.

If we want to merge this, we should create a shared appveyor account on the ci.appveyor.com service and share the password among core numpy developers.

If we want to have appveyor to monitor all incoming pull request in complement to travis, we would need to setup multi-status github reporting:

http://github-multi-status.herokuapp.com/

Otherwise it's possible to configure appveyor to run the test on commits merged to master only instead.

@cournape is experimenting with building numpy against libopenblas.dll to be able to skip the liblapack_lite build step that is very slow on appveyor.

### CODE REVIEW

**Comment by charris** [comment]
@ogrisel Is this ready? Would be good to clean up the history if so.

**Comment by ogrisel** [comment]
@charris actually it does not work as expected: I have trouble linking against openblas with MSVC (although it should be possible) and building lapack lite is too costly for appveyor. I won't have time to investigate what's wrong with my use of the `lib.exe` command in the coming days, maybe I should close this PR and reopen it later if I find the time to make it work.

**Comment by charris** [comment]
@ogrisel Closing sounds good to me. I'm trying to clear out the PR stack, so if you close this until you have more time that would help. If someone else wants to work on it, that would also be good.

**Comment by ogrisel** [comment]
Closing for now then.

**Pull request closed without merging**
