### PR TITLE
MAINT: Use templating to merge float loops

### PR DESCRIPTION
**Pull request by eric-wieser**
This deduplicates a bunch of code, making this file shorter and slightly more manageable.

Note that this requires us to adjust the api parser to process templated files.

### CODE REVIEW

**Comment by mattip** [comment]
while this adds 67 lines and removes 216 for a net win of ~150 lines, I am not sure the additional complexity justifies the change. The templated code is harder to read.

**Comment by eric-wieser** [comment]
Is it worth taking the half of this patch which is the tool update that allow API functions to be templated?

**Comment by mattip** [comment]
Let's put this in since it does simplify the templating

**Comment by eric-wieser** [comment]
Would have been happy to split it in half, but I'm not complaining :)

**Pull request merged**
