### PR TITLE
Fix typo in fill_diagonal docstring.

### PR DESCRIPTION
**Pull request by anntzer**
All's in the title.

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Looks obviously correct to me

**Comment by eric-wieser** [comment]
Ah, but the commit message should comply with [the development workflow](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html), and start with `DOC: `

**Comment by anntzer** [comment]
Done.

**Comment by eric-wieser** [comment]
Seems that appveyor got confused there and cancelled the CI build, but that looks all good to me

**Pull request merged**
