### PR TITLE
ENH: Add 'ulong' to sctypeDict

### LINKED ISSUE #21063: numpy.ulong is missing
It appears that NumPy doesn't define a scalar type `numpy.ulong`. This seems like a conspicuous omission -- given that the library exports many similar types such as `long` and `ulonglong`, I assumed that `ulong` would be a valid type.

Similarly, the following code snippet fails:

```python
>>> import numpy as np
>>> np.dtype("ulong")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type 'ulong' not understood
```

Is this a deliberate omission? I wasn't able to find any info about it. Is there any reason why we couldn't (or shouldn't) add `numpy.ulong` as an alias for `numpy.uint`?

### PR DESCRIPTION
**Pull request by gmgunter**
Add 'ulong' to `np.sctypeDict` so that `np.dtype("ulong")` is supported. Closes #21063

### CODE REVIEW

**Review by BvB93 — COMMENTED** [review]
Could you also add a test that checks `np.dtype("ulong") == np.dtype(np.uint)`? I'd suggest putting it somewhere in `core/tests/test_dtype.py`.

**Review by BvB93 — APPROVED** [review]
LGTM, @seberg do you have any comments?

**Comment by eric-wieser** [comment]
Just to check: does this definitely avoid adding `np.ulong`?

**Comment by seberg** [comment]
> Just to check: does this definitely avoid adding np.ulong?

Just checked, and it does indeed add it.  @gmgunter can you look into ensuring we don't do that – maybe even add it to the test `with pytest.raises(AttributeError): ...`, could have a comment saying that we currently don't add it because `np.long` also doesn't exist for historic reasons?  Since we don't have `np.long`, I agree with not doing it (at least not in this PR).

I am a bit surprised, I thought that we should have a test failing when expanding the public API surface, could be nice to look into that (unrelated to this PR though).

**Comment by gmgunter** [comment]
Oh, thanks for pointing this out. Didn't occur to me to test whether `np.ulong` had been inadvertently created as a result of this change.

It looks like the issue is that, in the PR branch, 'ulong' is also being added to `allTypes`, which defines a mapping of aliases to be exposes as attributes. Instead, it should only be added to `sctypeDict` in order to get the behavior that we wanted (i.e. support `np.dtype("ulong")` but not `np.ulong`).

Before I go ahead and push a fix for this, I wanted to point out something else I noticed -- `np.uint` *does* exist, despite `np.int` being [deprecated](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) (similar to `np.long`).

```python
>>> import numpy as np
>>> np.int
DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
<class 'int'>
>>> np.uint
<class 'numpy.uint64'>
```

Should this change how we feel about whether or not to add `np.ulong`?

**Comment by seberg** [comment]
> Should this change how we feel about whether or not to add np.ulong?

Sorry, when I first had a look, I was a bit unsure.  But I would say no for now, because `np.uint` already is `ulong` (confusing as it is).

**Comment by gmgunter** [comment]
@seberg sounds good to me. I've updated the implementation to ensure that `np.ulong` is not created, and added a test assertion based on your suggestion.

**Comment by seberg** [comment]
Yes, thanks @gmgunter.

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @gmgunter! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Pull request merged**
