### PR TITLE
BUG: add order to out array of `numpy.fft`

### LINKED ISSUE #26777: BUG: FFT operation returns C_CONTIGUOUS even if input is F_CONTUGIOUS
### Describe the issue:

In Numpy_2, FFT operation returns C_CONTIGUOUS even if input is F_CONTIGUOUS while In NumPy 1.26 output was F_CONTIGUOUS for F_CONTIGUOUS input.

### Reproduce the code example:

```python
>>> import numpy as np
>>> a = np.ones((10,10), dtype=numpy.complex64, order="F")
>>> numpy.fft.fft(a).flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
```

### Error message:

_No response_

### Python and NumPy Versions:

2.0.0
3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by ghost**
fixes #26777 

Output after making the changes
```py
>>> import numpy
>>> a = numpy.ones((10,10), dtype=numpy.complex64, order="F")
>>> numpy.fft.fft(a).flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

>>> a = numpy.ones((10,10), dtype=numpy.complex64, order="C")
>>> numpy.fft.fft(a).flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
```

### CODE REVIEW

**Review by seberg — COMMENTED** [review]
This looks good, but I think if we add this, we should add a test.  Ideally with a comment that we try to preserve order here even though NumPy doesn't strictly guarantee it.
(I.e. if this was not easy to change, I would have accepted the change in behavior probably; not that it is often hard, but there are cases.)

**Review by mhvk — COMMENTED** [review]
Should we explicitly expose an `order` keyword argument? In that case, the default can be `order="K"` (for keep).

Though I'm also fine with the idea here, since that fixes a regression from what happened previously (and is the same as what, e.g., `ufunc.accumulate` does, which also doesn't have an `order` argument).

Do agree that it would be good to have an extra test.  Feel free to use the one from the original issue!

**Review by mhvk — APPROVED** [review]
Just realized we can avoid the definition of `order` by using `empty_like`. Since I noticed that one could also remove some imports, I just pushed to your branch directly. With your added test, this looks all OK to me, but I'll let the tests run to be sure (locally, they passed).

**Comment by charris** [comment]
Thanks @vahidmech  and Marten.

**Pull request merged**
