### PR TITLE
API: Readd `np.bool_` typing stub

### LINKED ISSUE #26199: BUG: `np.bool_` alias not exported in `__init__.pyi` with `2.0.0rc1`
### Describe the issue:

Type checkers (tested with `pyright==1.1.356` in strict mode) don't recognize `np.bool_` as alias for `np.bool` on `numpy==2.0.0rc1`. 

Unless I'm missing something, this is because `bool_` is missing in `__init__.pyi`.

### Reproduce the code example:

```python
import numpy as np

type NpBool = np.bool_  # results in pyright errors
```

### Error message:

```shell
error: Type of "bool_" is unknown (reportUnknownMemberType)
error: "bool_" is not a known member of module "numpy" (reportAttributeAccessIssue)
```

### Python and NumPy Versions:

```
2.0.0rc1
3.12.2 (main, Feb 25 2024, 16:35:05) [GCC 11.4.0]
```

### Runtime Environment:

_No response_

### Context for the issue:

This makes it impossible to add support for both numpy 1 and 2 in typed python packages, e.g. in  https://github.com/jorenham/Lmo/blob/master/lmo/typing.py

### PR DESCRIPTION
**Pull request by mtsokol**
Fixes: #26199

Hi @seberg,

This PR adds `np.bool_` typing alias for `np.bool`. I also found some remaining `np.bool_` in tests.

### CODE REVIEW

**Comment by charris** [comment]
There are a few other uses. The documentation simply uses the `bool` documentation for `bool_`, if we are trying to discourage use we should add a note for that. `bool_` is also defined in `_type_aliases.py`, and used in `numpy/_core/src/multiarray/scalartypes.c.src`. My understanding is that we want to remove all internal usage, is that correct?

**Comment by rgommers** [comment]
> My understanding is that we want to remove all internal usage, is that correct?

I'd say yes. But that doesn't need to be backported to 2.0.x, and isn't urgent so I'd suggest doing that separately.

> EDIT: or are we reserving `bool_` for Python bool?

No, `np.bool_` is an alias to `np.bool` and should disappear in the far future. We should not have any aliases for Python builtin types.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @mtsokol

**Comment by mtsokol** [comment]
@charris I think all redundant usages of `bool_` are already removed. `bool_` is still present as an alias and can be used as `np.bool_` or `np.dtype("bool_")`. The former requires `"bool_"` to be defined in `_type_aliases.py`. Once we drop `bool_`, both can be removed.

In `scalartypes.c.src` I agree, `"|O:bool_"` can be changed to `"|O:bool"`. And in docs we can have another note about the `bool -> bool_` change. I will fix both.

**Pull request merged**
