### PR TITLE
DOC: Add CircleCI builder for devdocs

### PR DESCRIPTION
**Pull request by stefanv**
Also see https://github.com/numpy/numpy/pull/10213

### CODE REVIEW

**Comment by eric-wieser** [comment]
Will this build the api docs too? I notice from the logs:
```
Uploading /home/circleci/repo/doc/_build/html to devdocs
  No artifact files found at /home/circleci/repo/doc/_build/html
```

**Comment by stefanv** [comment]
Yes, you're right; the one set of docs go into `build/html`, the other into `_build/html`.  Should be fixed now.  It's pretty neat that you can browse the artifacts directly on CircleCI!

**Comment by pv** [comment]
Maybe upload to a publicly visible place for the master branch?
https://github.com/scipy/scipy/blob/master/circle.yml#L18-L41
The circleci artifacts cannot be browsed when you're not logged in as 
authorized user (i.e. the URLs of the artifacts is not listed anywhere 
and varies for different builds).

**Comment by stefanv** [comment]
Yes, certainly, that was our next step. Just trying to figure out ssh keys 
with circle 2.

**Comment by charris** [comment]
@stefanv Have you added the numpy repo to circleci somewhere? Having every new PR failing tests is annoying.

**Comment by stefanv** [comment]
Yes, it is for building the devdocs. Sorry about the noise, it's only very 
temporary until I resolve any issues with this PR.

**Comment by stefanv** [comment]
OK, we now have a working build.  Options:

1. Merge this CircleCI configuration
2. Add an empty CircleCI configuration
3. Disable CircleCI until later

The motivation for activating CircleCI is to build the dev-docs, and to upload them after each merge with master.

**Comment by stefanv** [comment]
Note: uploading to GitHub still has to be added, but can be done in another PR.

**Comment by charris** [comment]
Just to be clear, in its current state it just builds for PRs  and later on it will also upload on merge?

**Comment by charris** [comment]
Does the document get overwritten on upload? If not, how are the versions tracked. Note that we are talking maybe 15-20 merges/week on average.

**Comment by charris** [comment]
And what about branches?

**Comment by stefanv** [comment]
We can either disable the build for branches (via CircleCI config interface), or skip building on branches (via `.circleci/config`).

**Comment by charris** [comment]
With the occasional interleaved releases of different versions, it might be good to have both stable and development docs, with the stable docs uploading on release.

Anyway, lets get this in so we can get rid of the current errors. Thanks Stefan.

**Comment by charris** [comment]
Looks like close and reopen don't trigger new builds. Is there a setting for that?

**Comment by charris** [comment]
Might give numpy developers write access at circleci so they can hit the rebuild. It would also be good  to check if new pushes retrigger builds. Did that happen here or did you need to trigger them explicitly?

**Comment by charris** [comment]
@rgommers Wasn't there some discussion of moving the docs to github? I don't recall anything being resolved, but seem to recall a suggestion to that effect.

**Comment by rgommers** [comment]
Yes, that was about the dev docs only. Those are problematic because they have to be rebuilt regularly. They're ~40 MB (IIRC), and can easily be handled with gh-pages.

The complete set of docs on http://docs.scipy.org/ however is over 1 GB, and is probably also too much traffic for the gh-pages limits. Plus docs for releases only have to be updated once every couple of months or so, so not too much of an issue.

**Comment by eric-wieser** [comment]
@stefanv: It looks like there's a problem with Cython not being installed on CircleCI, which is making the test fail on all PRs

**Comment by charris** [comment]
Close and reopen do not work with circleci, it doesn't trigger a fresh merge with master. I was wondering if pushes failed in a similar way, which might be what is happening here.

**Comment by stefanv** [comment]
@jakirkham has looked into this issue before; any advice on how to get CircleCI to merge with master before building?

**Pull request merged**
