### PR TITLE
MAINT: Do not override ``sliding_window_view`` module to numpy

### PR DESCRIPTION
**Pull request by seberg**

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]

**Comment by eric-wieser** [comment]
We should maybe have a test for this type of thing somewhere - verifying that only objects actually in the `np.` namespace have `__module__` set this way.

**Comment by seberg** [comment]
Probably, the sanity checks in the `__array_function__` wrapper should likely also be moved into test rather than import time. Right now I don't think we have tests for all of these symbols I hopened an issue with the comment, tests are fine, i will just merge it and hope I didn't miss another place.

**Comment by deepthisreekvs** [comment]
This issue is resolved and it is in private function ._stride_tricks_impl
image

**Comment by seberg** [comment]
Ah, I didn't realize this there.  The issue gh-17724 is about adding tests for this (ideally for all functions), so that such errors don't happen in the future.

**Pull request merged**
