### PR TITLE
MAINT: Move the `fromnumeric` annotations to their own stub file

### PR DESCRIPTION
**Pull request by BvB93**
This pull request moves the `fromnumeric` annotations to their own dedicated stub file.

This should clean up the main `__init__.pyi` file a bit.

### CODE REVIEW

**Comment by BvB93** [comment]
CircleCI is failing but this is a known issue (https://github.com/numpy/numpy/issues/17301).

**Comment by person142** [comment]
NumPy redefines the module that functions are reported to come from; does this cause any inconsistencies with that?

**Comment by BvB93** [comment]
> NumPy redefines the module that functions are reported to come from; does this cause any inconsistencies with that?

For classes this would indeed be a bit of an issue, as it the likes of mypy use the classes' module for defining its name.
This behavior is unique to classes though, functions for example are only defined according to their signature, so this won't cause any issue here:

``` python
import numpy as np

array: np.ndarray

reveal_type(array)  # Revealed type is 'numpy.ndarray'
reveal_type(np.reshape)  # Revealed type is 'def (...)'

```

**Comment by charris** [comment]
Thanks @BvB93 .

**Pull request merged**
