### PR TITLE
DOC: #22266 Add examples for tril_indices_from(), triu_indices_from()

### PR DESCRIPTION
**Pull request by richierocks**
Add examples for tril_indices_from(), triu_indices_from() as requested by #22266. 

Written as part of PyData 2022 sprint.

### CODE REVIEW

**Comment by seberg** [comment]
Thanks.  The tests are failing here, so it seems one of the example output is wrong.  The lines should also be kept shorter (the linter is unhappy due to this), that probably means a slightly differently formatted output (if the output is always like this, then we can ignore that).

**Comment by charris** [comment]
close/reopen

**Comment by charris** [comment]
The examples seem to be incorrect, hence the test failures.

**Review by rossbar — APPROVED** [review]
I took the liberty of pushing up a fix to the failing docstring example. A couple minor subjective comments about potentially shortening things by the calling of other functions from the examples, but that's just an opinion. There's nothing to be done about the failing linter as the line length is dicated by the example output.

I'll put this in once CI passes. Thanks @richierocks !

**Pull request merged**
