### PR TITLE
BLD: Fix upload script

### PR DESCRIPTION
**Pull request by lithomas1**
I forgot to update a directory in the uploader script leftover from when I was trying to do a PEP 517 build.

### CODE REVIEW

**Comment by lithomas1** [comment]
Yup. Fingers crossed that it works this time around.

**Comment by mattip** [comment]
I [kicked off a build](https://github.com/numpy/numpy/actions/runs/2036967636).

**Comment by mattip** [comment]
It worked. The file is scipy-wheels-nightly/numpy/1.23.0.dev0+939.gc9689ca05/numpy-1.23.0.dev0+939.gc9689ca05.tar.gz

**Comment by charris** [comment]
Do we also have a zip file? The zip file is what I have been uploading to PyPI. We could change that, but is might break some downstream scripts.

**Pull request merged**
