### PR TITLE
REL: Prepare for NumPy 1.21.6 release.

### PR DESCRIPTION
**Pull request by charris**
- Create 1.21.6-changelog.rst.
- Update 1.21.6-notes.rst.
- Fix circleci doc builds.
- Change azure-pipelines Mac vmImage to macOS-1015.

### CODE REVIEW

**Comment by seberg** [comment]
Sorry, I hadn't realize this was coming now.  Can you hold off until tomorrow?

**Comment by charris** [comment]
> Can you hold off until tomorrow?

Sure. This came up at the end of https://github.com/scipy/oldest-supported-numpy/issues/45. Do you intend to add something?

**Comment by seberg** [comment]
Yeah, there is one small fix I have been meaning to do for a while and it should be quick.

**Comment by seberg** [comment]
Oh, just realized that this is 1.21.x not 1.22.x.  Still happy to backport, though, but maybe not as pressing. (and there is a tiny chance of backcompat issues, so only if a 1.21.7 wouldn't be too much hassle.)

**Comment by charris** [comment]
I'd rather avoid any potential problems. I wouldn't do this at all if the `oldest-supported-numpy` problem hadn't come up.

**Comment by charris** [comment]
A 1.22 fix would be welcome, though. Things there have quieted a lot since 1.22.3, so probably only one more release.

**Comment by Czaki** [comment]
if this release will be able to build from source on Windows? `CCompiler_spawn() got an unexpected keyword argument 'env'` observed when building `numpy==1.21.5` from source using latest setuptools:

```
          File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-v9k16mu4\overlay\site-packages\setuptools\_distutils\_msvccompiler.py", line 505, in spawn
                  return super().spawn(cmd, env=env)
          File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-u4z7ehkd\numpy_abda04e05c5e4cc9b598abfa5c2eb061\numpy\distutils\ccompiler.py", line 90, in <lambda>
                  m = lambda self, *args, **kw: func(self, *args, **kw)
        TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
```

https://github.com/4DNucleome/PartSegCore-compiled-backend/runs/5972857498?check_suite_focus=true#step:4:708

As I read test-related scripts the test process uses the system python which does not use latest setuptools.

**Comment by charris** [comment]
@Czaki  NumPy often does not build with latest setuptools, which are changing regularly these days. We are pinned to older versions and will change the build to use meson at some point on account of the instability. Windows builds are difficult in any case and are best avoided when possible.

**Comment by charris** [comment]
@BvB93 I'm trying to do a 1.21.6 release, but am now getting typing errors for no reason I can see. Could you take a look at the [error messages](https://tinyurl.com/y8g92ujq) and see if there is anything that can be easily fixed? Something has changed.

**Comment by Czaki** [comment]
@charris Thanks for your response. Now I check and `setuptools` is pinned in `pyproject.toml`. So I do not understand why it fails. 

I would love to avoid numpy builds but I also would love to deliver pypy wheels.

**Comment by BvB93** [comment]
> EDIT: The tests run without problems on my machine, the errors seem to be Mac specific, and possibly due to the azure-pipeline environment.

Same here on my Mac; locally the tests pass without issue. It's not clear to me what could be causing the issue here, though based on the reproducibility issue presumably something related to azure?

**Comment by charris** [comment]
> presumably something related to azure?

Sounds like it, they have broken things before, it is really annoying. Guess I'll put this in and see if the wheel builds pass. If not, is there an easy way to disable the tests?

**Comment by BvB93** [comment]
> Sounds like it, they have broken things before, it is really annoying. Guess I'll put this in and see if the wheel builds pass. If not, is there an easy way to disable the tests?

We could always add an xfail for Mac with these specific tests.

**Comment by charris** [comment]
> We could always add an xfail for Mac with these specific tests.

The wheel builds passed.  Not sure what the differences are, need to take a look at that someday.

**Comment by BvB93** [comment]
Sure, we can always add an xfail for Mac if worst comes to worst.

On 12 Apr 2022, at 01:24, Charles Harris ***@***.***> wrote:

﻿

presumably something related to azure?

Sounds like it, they have broken things before, it is really annoying. Guess I'll put this in and see if the wheel builds pass. If not, is there an easy way to disable the tests?

**Pull request merged**
