### PR TITLE
MAINT Fix typo for event name in wheels.yml

### PR DESCRIPTION
**Pull request by thomasjpfan**
Fixes typo in .github/workflows/wheels.yml

CC @mattip

### CODE REVIEW

**Comment by charris** [comment]
Can we trigger without a commit?

**Comment by thomasjpfan** [comment]
> Can we trigger without a commit?

Yes, we can trigger with button in the UI:

Screen Shot 2021-11-02 at 11 15 29 PM

**Comment by charris** [comment]
Great. One more question, where do the triggered uploads go for main and maintenance branches?

**Comment by charris** [comment]
Thanks @thomasjpfan .

**Comment by thomasjpfan** [comment]
> Great. One more question, where do the triggered uploads go for main and maintenance branches?

Currently, they are only saved into GitHub actions. I plan to configure the uploads in a follow up. To confirm, do we want to upload wheels from `main` into  https://anaconda.org/scipy-wheels-nightly/numpy and maintenance branches into https://anaconda.org/multibuild-wheels-staging/numpy ?

**Comment by charris** [comment]
Yes, that is what we want.

**Pull request merged**
