### PR TITLE
[FFT][BUG] do not set special compiler flags for pocketfft

### PR DESCRIPTION
**Pull request by mreineck**
I read in https://hackmd.io/30eMeRnDQCSW7yDOG05gxA?view# that the custom compiler flag set by pocketfft causes problems. This flag is a debugging relic and has no influence on code generation, so I have removed it.

### CODE REVIEW

**Comment by rgommers** [comment]
@mreineck did you mean to include anything else? This is just a cosmetic change, no compile flag is touched.

**Comment by mreineck** [comment]
Fascinating ... in my own branch I definitely deleted an "extra_compile_args=..." statement. Maybe someone already removed this on master and I missed that - in this case please ignore the PR!

**Comment by rgommers** [comment]
hmm, odd - you probably rebased before sending the PR so it changed your commit. GitHub cannot change individual commit contents on pushing or opening PRs.

**Comment by mreineck** [comment]
Looks like I tricked myself somehow ... there never was a specific flag in the version on master.

But then the statement "pocketfft tests somehow changing a flag?" in the above document is a mystery to me. Let me know if I can help locating the problem!

**Comment by rgommers** [comment]
It is a bit of a mystery. apparently the 32-bit Linux CI started sporadically failing, in a test unrelated to `numpy.fft`, due to the merge of Pocketfft. I don't know the finer details, maybe @charris or @tylerjereddy can explain or point to the issue description. Either way, it seemed like a minor issue that we didn't yet understand and were better off ignoring than burning more time on. So don't worry about it for now.

**Comment by charris** [comment]
We see the sporadic 32 bit test failures only on the daily wheels builds, not the normal CI testing. The error is a loss of accuracy in the pinv computation for complex64 matrices. Bisection indicated that the error appeared after the pocketfft merge. We haven't seen any problems in the normal CI runs. The current question is if the error is in the wheels code or the docker image in which they are being tested.

**Pull request closed without merging**
