### PR TITLE
MAINT,DOC: Remove sphinx-panels in favor of sphinx-design

### PR DESCRIPTION
**Pull request by melissawm**
Similar to https://github.com/scipy/scipy/pull/16659, replace `sphinx-panels` with [sphinx-design](https://sphinx-design.readthedocs.io/en/latest/), since `sphinx-panels` is set to be deprecated.

### CODE REVIEW

**Comment by melissawm** [comment]
It looks like CircleCI is complaining about a few intersphinx links, not sure why.

**Comment by mattip** [comment]
Does it build cleanly locally?

**Comment by melissawm** [comment]
It does - triggering a rebuild will probably show that but I can't seem to do it just for CircleCI.

**Comment by charris** [comment]
> but I can't seem to do it just for CircleCI.

You need to go to the CircleCI page (circleci/circleci: build ... details), log in, and hit the rerun button. I restarted it.

**Comment by charris** [comment]
Failing that, close/reopen the PR.

**Comment by rossbar** [comment]
> It looks like CircleCI is complaining about a few intersphinx links

I think the intersphinx part may be a red herring, as the docs build job in circleci is run with the `-q` flag, which suppresses all output except for those missing doc warnings. FWIW I can reproduce the circleci errors locally (I get the same 7 warnings, both with and without -j4), so they do appear to be real. I'm not sure that it's related to this PR though. My initial guess would be a change in doc dependency somewhere, perhaps due to the pins in `sphinx-design`. Will need to dig deeper before saying anything conclusive!

**Comment by rossbar** [comment]
Okay, a little more digging and here's what I think is going on:

`sphinx_panels` was keeping the sphinx version pinned to <5.0. When this was removed in favor of sphinx-design in this PR, that pin disappeared. Since numpy doesn't have an upper bound sphinx pin, we start getting sphinx>5 in CI. I suspect the 7 new doc warnings are related to this sphinx upgrade. Some possible solutions:
 1. Fix the 7 doc warnings in this PR, and continue to use the latest sphinx version
 2. Temporarily add `<5` to the sphinx pin in `doc_requriements` until we have a chance to fix these warnings in a follow-up PR.

**Comment by melissawm** [comment]
I found it - thanks again @rossbar ! Looks like this change in Sphinx 5 is responsible:

> [#2068](https://github.com/sphinx-doc/sphinx/issues/2068): [intersphinx_disabled_reftypes](https://www.sphinx- doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_disabled_reftypes) has changed default value from an empty list to ['std:doc'] as avoid too surprising silent intersphinx resolutions. To migrate: either add an explicit inventory name to the references intersphinx should resolve, or explicitly set the value of this configuration variable to an empty list.

Should be good now!

**Review by rossbar — APPROVED** [review]
Thanks @melissawm , this LGTM! I'll leave it open for a brief period in case @tupui wants to give it a once-over as the resident sphinx extension/theme expert. If not I'll merge within a few days!

**Review by tupui — APPROVED** [review]
LGTM as well. AFAICT the changes are the same as I did for SciPy (including the tweaks for the dark theme) so it should be all good.

**Pull request merged**
