### PR TITLE
BUG: skip the extra-dll directory when there are no DLLS

### PR DESCRIPTION
**Pull request by ghost**
When the gfortran functionality is not used, we don't want to enable the `__config__` functionality. This mistake was put in as an earlier optimization but led to failures with conda.

Sorry about making this mistake!

### CODE REVIEW

**Comment by charris** [comment]
Is 1.14 affected by any of this?

**Comment by xoviat** [comment]
Nope. We have a big hairy discussion going on in gh-10229, but all of this mess is only about 1.15. I was very conservative about the 1.14 changes, which I now appreciate.

**Comment by charris** [comment]
I'm enjoying the discussion at #10229. Sometimes you just need to commit to get the ball rolling.

**Comment by charris** [comment]
Thanks @xoviat .

**Pull request merged**
