### PR TITLE
BUG: Remove check in shuffle for non-ndarrays

### LINKED ISSUE #18142: random.Generator.shuffle() warns about ragged nested sequences
With a "ragged nested sequence", `Generator.shuffle()` triggers a warning in `asarray()`. This is unexpected, since I'm only trying to shuffle the sequence, not convert it to a NumPy array.

This only happens with `Generator` and not with `random.shuffle()`.

It is unclear how to call `shuffle()` without triggering this warning.

### Reproducing code example:

```python
import numpy as np
seq = [[], [], 1]
np.random.default_rng().shuffle(seq)
print(seq)
```

### Error message:

/ldaphome/ocifka/venv/spe/lib/python3.7/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)

### NumPy/Python version information:

1.19.4 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]

### PR DESCRIPTION
**Pull request by bashtage**
Remove ndim for non-ndarrays and check axis is 0

closes #18142

### CODE REVIEW

**Comment by mattip** [comment]
Thanks @bashtage

**Comment by eric-wieser** [comment]
I think this patch means that `np.random.default_rng().shuffle([1, 2, 3], axis=-1)` no longer works, but that's probably not worth worrying about.

**Comment by bashtage** [comment]
> I think this patch means that `np.random.default_rng().shuffle([1, 2, 3], axis=-1)` no longer works, but that's probably not worth worrying about.

As I read the docs this isn't supposed to work -- the NotImplementedError should be raised on any non-ndarray input when axis is not 0.  I think the accident that -1 was being changed to 0 and then the error was not being raised is also a mistake. IMO the `NotImplementedError` should have been right at the top before axis is normalized.

**Comment by bashtage** [comment]
It really comes down to the interpretation of `It is only supported on `ndarray` objects.`

**Pull request merged**
