### PR TITLE
MAINT: Fix cirrus MacOs wheel builds [wheel build]

### PR DESCRIPTION
**Pull request by charris**
@andyfaff Ping. This started failing last week. See https://cirrus-ci.com/build/5843049672081408.

@ngoldbaum You didn't see this failure in #27899 because the added commits did not have [wheel build] in the title line.

### CODE REVIEW

**Comment by charris** [comment]
Needs backport to 2.1.x.

**Comment by charris** [comment]
@rgommers We are building some macos wheels with openblas, I assume for older versions of macos. Do we want to keep supporting those?

**Comment by andyfaff** [comment]
macOS wheels are a bit complicated. Before macOS 14 use of openblas is necessary because Accelerate BLAS wasn't adequate. I assume we'll need to make these wheels until macos13 is no longer relevant.

**Comment by ngoldbaum** [comment]
I did see the failures on an earlier commit in that PR and figured it was unrelated. Thanks for looking into it.

**Comment by andyfaff** [comment]
This looks to be passing now.

**Comment by rgommers** [comment]
> I assume we'll need to make these wheels until macos13 is no longer relevant.

Yes, that is right. It'll be a while before we can drop those.

**Pull request merged**
