### PR TITLE
BLD: Add LoongArch support

### PR DESCRIPTION
**Pull request by loongson-zn**
Add LoongArch support,  please review,  thanks!

### CODE REVIEW

**Comment by mattip** [comment]
Could you explain what you are trying to do? So far this does not look useful.

**Comment by loongson-zn** [comment]
> Could you explain what you are trying to do? So far this does not look useful.

It's PR is to solve compilation failure on LoongArch architecture.  
LoongArch is a new instruction set. The official website is not ready yet.
Our development work is ongoing. At present, we have completed the initial version development based on Debian 10.
Binutils has identified EM_LOONGARCH is 258, I hope numpy can accept this patch. Thanks.

**Comment by mattip** [comment]
I see, that indeed is shown at https://wiki.debian.org/ArchitectureSpecificsMemo#Summary

**Comment by mattip** [comment]
.. but with a note saying "The architecture name has not yet been proposed for integration into dpkg". Is there a chance the name will change?

**Comment by loongson-zn** [comment]
@mattip  
The upstream submission  is our current the main work, so I don’t think the name will change.

**Comment by charris** [comment]
@loongson-zn Could you add a release note? See `doc/release/upcoming_changes` for examples, the heading should be `new_feature`.

**Pull request merged**
