### PR TITLE
STY: Fix weird indents to be multiples of 4 spaces

### PR DESCRIPTION
**Pull request by eric-wieser**
Extracted from #9705, plus a few greps to find other occurrences

### CODE REVIEW

**Comment by mattip** [comment]
Personally not a big fan of style-only fixes, they mess with history and make it hard to track where and why and in what context code was written. Are these really necessary?

**Comment by eric-wieser** [comment]
Better to have them in their own commit than to have an unrelated commit message touching these lines to fix them. Given that we mention the `STY` marker in our dev guide, I assume at least at some point we were ok with this type of commit.

**Comment by charris** [comment]
I think this is OK, it's not the big. My name is all over the history of some of these files because of the initial style fixes back around 1.3, not because I wrote the code.  There is probably a style checker out there somewhere that we could adapt to keep these fixes to a minimum in the future.

**Comment by mattip** [comment]
Thanks Eric

**Pull request merged**
