### PR TITLE
BUG: Fix complex+longdouble and broken subclass handling

### LINKED ISSUE #21481: BUG: Scalar changes did not capture `longdouble + complex` semantics fully
SciPy is noticing these changes with NumPy main:
```
=================================== FAILURES ===================================
_________________ TestCorrelateComplex.test_rank0[complex256] __________________
../testenv/lib/python3.10/site-packages/scipy/signal/tests/test_signaltools.py:2155: in test_rank0
    y_r += 1j * (-correlate(a.real, b.imag) + correlate(a.imag, b.real))
E   TypeError: unsupported operand type(s) for *: 'complex' and 'numpy.float128'
        a          = array(-0.7940189+1.39564349j, dtype=complex256)
        b          = array(-0.25786004-0.99202761j, dtype=complex256)
        dt         = <class 'numpy.complex256'>
        self       = <scipy.signal.tests.test_signaltools.TestCorrelateComplex object at 0x7f8925201450>
        y_r        = (-1.1797711271213198454+0j)
________ TestPareto.test_fit_MLE_comp_optimzer[True-True-False-1-0-0.1] ________
../testenv/lib/python3.10/site-packages/scipy/stats/tests/test_distributions.py:1556: in test_fit_MLE_comp_optimzer
    args = [data, (stats.pareto._fitstart(data), )]
        data       = array([2.12029996e+16, 1.19523801e+02, 1.40929869e+11, 2.07791008e+01,
       4.66818325e+01, 3.51368966e+00, 1.592095...1.41045904e+00, 4.88716443e+02, 9.77757362e+08,
       7.49791702e+01, 3.41238972e+07, 5.93724048e+12, 2.00158051e+00])
        fix_loc    = True
        fix_scale  = False
        fix_shape  = True
        rng        = Generator(PCG64) at 0x7F890CDA7CA0
        rvs_loc    = 0
        rvs_scale  = 1
        rvs_shape  = 0.1
        self       = <scipy.stats.tests.test_distributions.TestPareto object at 0x7f8921b78dc0>
../testenv/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py:2417: in _fitstart
    loc, scale = self._fit_loc_scale_support(data, *args)
        args       = (1.0,)
        data       = array([2.12029996e+16, 1.19523801e+02, 1.40929869e+11, 2.07791008e+01,
       4.66818325e+01, 3.51368966e+00, 1.592095...1.41045904e+00, 4.88716443e+02, 9.77757362e+08,
       7.49791702e+01, 3.41238972e+07, 5.93724048e+12, 2.00158051e+00])
        self       = <scipy.stats._continuous_distns.pareto_gen object at 0x7f892ad18e20>
../testenv/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py:2716: in _fit_loc_scale_support
    loc_hat, scale_hat = self.fit_loc_scale(data, *args)
        args       = (1.0,)
        data       = array([2.12029996e+16, 1.19523801e+02, 1.40929869e+11, 2.07791008e+01,
       4.66818325e+01, 3.51368966e+00, 1.592095...1.41045904e+00, 4.88716443e+02, 9.77757362e+08,
       7.49791702e+01, 3.41238972e+07, 5.93724048e+12, 2.00158051e+00])
        self       = <scipy.stats._continuous_distns.pareto_gen object at 0x7f892ad18e20>
../testenv/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py:2784: in fit_loc_scale
    Lhat = muhat - Shat*mu
E   RuntimeWarning: invalid value encountered in multiply
        Shat       = 0.0
        args       = (1.0,)
        data       = array([2.12029996e+16, 1.19523801e+02, 1.40929869e+11, 2.07791008e+01,
       4.66818325e+01, 3.51368966e+00, 1.592095...1.41045904e+00, 4.88716443e+02, 9.77757362e+08,
       7.49791702e+01, 3.41238972e+07, 5.93724048e+12, 2.00158051e+00])
        mu         = array(inf)
        mu2        = array(inf)
        mu2hat     = 1.659444495471661e+40
        muhat      = 1.3225472615245095e+19
        self       = <scipy.stats._continuous_distns.pareto_gen object at 0x7f892ad18e20>
        tmp        = array([2.12029996e+16, 1.19523801e+02, 1.40929869e+11, 2.07791008e+01,
       4.66818325e+01, 3.51368966e+00, 1.592095...1.41045904e+00, 4.88716443e+02, 9.77757362e+08,
       7.49791702e+01, 3.41238972e+07, 5.93724048e+12, 2.00158051e+00])
```

The first one is that for `1j * np.longdouble(3)` the longdouble gives up, but at least for this specific case it should not.  (I have to check the exact logic that we had, in theory, we do not need to give up for any object such that `np.array(obj)` is not a 0-D object array).

The second (which causes many more identical ones), actually seems correct to me.  The code does call `0.0 * inf` of sort, which *should* give a warning.  Unless there is a warning filter active here and being missed.
Although, there, I am still surprised that the behavior changed.  ThisIn this particular case, i tmay be that the the new code goes through the full `ufunc` path and the old code did not.  But even then, the old code should have given the warning also.

Thanks @jarrodmillman for pointing this out.

### PR DESCRIPTION
**Pull request by seberg**
When we see a complex number, we should go into the "promotion" path
even for longdouble.  That is because the complex number will behave
the same as a NumPy complex scalar and thus promotion works fine
(no issue with potential infinite recursion that would happen if we
go into the object loop).
Further, with a slight slowdown (but not slower than before), we now
check for subclasses of int, float, complex always and while we do
check whether we should defer, coercion is considered valid.

That is: We do not explicitly defer to a subclass of float unless e.g.
`__array_ufunc__ = None` or `__array_priority__` is set.

Some (arguably broken) subclasses may for exampleonly add an `__rop__`,
but not an `__op__`.  For these, the previous `is_forward` logic did not
work out correctly and could go into the wrong branch.
This is now fixed, by first checking for exact maches, and then also
checking for subclass, it should be safe to assume that one operand
is a subclass, but that is the only thing we can assume.

I now think that the only way to possibly get subclassing right, would
be by defining `__op__` and `__rop__` on a class to ensure that the
subclass cannot possibly inherit the base version.
(To be clear, I do not think that is worthwhile, and Python does not
do it either.)

Closes gh-21481.

---

Sorry that this is a rather large change again :(.  But making the "check for defering" more explicit seemed like a good idea.  The old code actually just checked always, if that seems nicer...

In principle we could also keep the exact checks as fast-paths and do the subclass checks at the end (which should micro-optimize things a bit), but I guess ths should be good at least for now.

### CODE REVIEW

**Comment by charris** [comment]
Bunch of `may be used uninitialized` warnings.

**Comment by seberg** [comment]
Hmmm, for some reason I don't seem to be seeing them locally right now.  Making using `default:` to "cover" everything seemed to have helped (plus some returns on impossible paths maybe).  But while that cut down things, there are still some left.

**Review by mattip — COMMENTED** [review]
LGTM, and the added tests seem to work as advertised. We have parity here with what CPython does for binary ops, so I think this is fine.

**Comment by mattip** [comment]
Thanks @seberg

**Pull request merged**
