### PR TITLE
Update FUNDING.yml

### PR DESCRIPTION
**Pull request by Dr-G**
add NumFOCUS github sponsors button (recurring donations only)

This feature is launching today at GitHub Universe!

cc @rgommers

### CODE REVIEW

**Comment by mattip** [comment]
Where does this change show up?

**Comment by mattip** [comment]
ahh, part of the ":heart: sponsor" button at the top of this page?

**Comment by charris** [comment]
Thanks @Dr-G . I don't think the `[...]` was needed for the single entry, but it probably doesn't hurt.

**Comment by mattip** [comment]
do we still need the `custom: https://www.numpy.org/#support-numpy` line?

**Comment by Dr-G** [comment]
@mattip I would suggest retaining it, yes.

**Comment by rgommers** [comment]
Looks great, thanks @Dr-G!

image

**Pull request merged**
