### PR TITLE
BUG: Make ``Generator._masked`` flag default to ``False``.

### LINKED ISSUE #13769: The _masked flag for random integers in an interval seems to be reversed.
The _masked=True flag at https://github.com/numpy/numpy/blob/6420e7f528a6c42422966544e453bdb2805ff620/numpy/random/generator.pyx#L442
seems from the comments to be meant to be selecting Lemire's method as the default. 

Should it not rather be `_masked=False` because setting the flag to False would in fact select Lemire's method. 

See the randomgen comment at https://github.com/numpy/numpy/blob/6420e7f528a6c42422966544e453bdb2805ff620/numpy/random/bounded_integers.pyx.in#L239
for more info.

Also the reference at https://github.com/numpy/numpy/blob/6420e7f528a6c42422966544e453bdb2805ff620/numpy/random/generator.pyx#L421
should perhaps rather be the formal journal reference:
Fast Random Integer Generation in an Interval, ACM Transactions on Modeling and Computer Simulation 29 (1), 2019

### Numpy/Python version information:

1.17.0.dev0+6420e7f 3.6.5 (default, Apr 25 2018, 14:23:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

### PR DESCRIPTION
**Pull request by bduvenhage**
Fixes #13769.

The Lemire method is the documented default for generating integers.

The change causes some of the random tests to fail because the stream of bounded integers are different for Lemire's methods than for masked rejection sampling. In randomgen we added reference results for Lemire's method.

### CODE REVIEW

**Comment by charris** [comment]
The tests need to be fixed and passing before this can go in. Might also note documentation about [commit messages](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html). In particular the short summary line.

**Comment by bduvenhage** [comment]
Thanks @charris 
I'll fix the tests and then we can review.

**Comment by charris** [comment]
Hmm, we have two versions of mt19937 we need to track, one for legacy (those tests should not change) and one for the new generators. I'm not clear on what we are testing here. @mattip @rkern Thoughts?

**Comment by bduvenhage** [comment]
Note that I'll remove the additional prints and comments when all the tests pass.

**Comment by charris** [comment]
OK, looks like the legacy generation is tested in `test_randomstate.py` and `test_random.py`.  I wonder if we shouldn't be testing the new generator with both options for the keyword?

**Comment by charris** [comment]
And choice of the Lemire's method is not a public option, so this looks OK.

**Comment by charris** [comment]
Thanks @bduvenhage .

**Comment by bduvenhage** [comment]
It was a pleasure @charris

**Pull request merged**
