### PR TITLE
CI: Create a link for the circleCI artifact

### PR DESCRIPTION
**Pull request by seberg**
Supersedes gh-15005, @larsoner is this the correct way to do it, or do I have to set up something else on the github actions to make it work?

### CODE REVIEW

**Comment by seberg** [comment]
Hmmm, I thought I should update the circleci config to 2.1, but seems ours is not yet compatible, have to look at that.

**Comment by larsoner** [comment]
Looks right to me. Unfortunately due to how GitHub actions work you'll have to merge this to `master` to see if it works. Alternatively, you could enable GitHub actions on your fork, and monitor the actions there to see if it works properly (e.g., by making a dummy PR to some branch in your fork where the action lives).

**Comment by seberg** [comment]
Thanks, I will try if I can manage it on my fork, also saw why the 2.1 failed (and it may need fixing), because of an unescaped `<<`

**Comment by seberg** [comment]
@larsoner but this approach is preferable to this one: https://github.com/apps/circleci-artifacts-redirector/ or am I confusing it and those are one and the same?!

**Comment by larsoner** [comment]
The -action used here is indeed the preferred one

**Comment by seberg** [comment]
I copy pasted a bad space and it was really confusing. I assume the CircleCI config file doesn't change, but thought it also doesn't really matter.

This is tested at: https://github.com/seberg/numpy/pull/33 and works! :)

**Comment by seberg** [comment]
Sorry for the noise, undid the circleci changes. There was some PR in matplotlib or so, that suggested you have to use 2.1 due to pipelines. But IIRC circleci forced that a while back, so I don't think it matters and I got the escaping wrong...

**Comment by mattip** [comment]
Where is the magic link?

**Comment by eric-wieser** [comment]
@mattip: It's in https://github.com/seberg/numpy/pull/34:

image

Notice the comment above,

> Looks right to me. Unfortunately due to how GitHub actions work you'll have to merge this to master to see if it works.

**Comment by mattip** [comment]
OK, let's put this in and see how it goes

**Comment by mattip** [comment]
Thanks @seberg and @larsoner for the github action

**Comment by seberg** [comment]
Thanks @larsoner this should make doc review much more convenient...

**Comment by larsoner** [comment]
I hope it does!

**Pull request merged**
