### PR TITLE
MAINT: doc: Remove doc/summarize.py

### LINKED ISSUE #15708: Tool doc/summarize.py does not work
The command-line tool `doc/summarize.py` does not currently work:
```
Traceback (most recent call last):
  File "doc/summarize.py", line 16, in <module>
    from sphinxext.phantom_import import import_phantom_module
ModuleNotFoundError: No module named 'sphinxext.phantom_import'
```
the tool depends on `sphinxext.phantom_import` which was part of `numpy/doc/sphinxext/` back in numpy 1.7.x, but has since moved on. Either this tool should be revised to work again, or considered to be removed.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
The code in doc/summarize.py is no longer used and it is
not being maintained, so remove it.

Closes gh-15708.

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
For completeness, https://github.com/numpy/numpy/issues/10106#issue-277270264 provides a script that provides similar functionality to `doc/summarize.py`, without a lot of the special-casing.

**Comment by eric-wieser** [comment]
@rossbar, note that that issue is concerned with objects having docstrings, but I think this summarize script is about checking that objects end up in the generated docs. My vague memory is that @rgommers or @mattip already sorted out some mechanism for detecting the latter, but I may be mistaken.

**Comment by rossbar** [comment]
Thanks for the additional info - it was discussed at today's Triage meeting and the script you posted in #10106 was brought up, so I linked it here to "document" the triage discussion in some sense. Either way, the consensus was that `summarize.py` is very rarely used and not worth the extra effort to maintain. Please weigh in if you disagree though!

**Comment by rgommers** [comment]
> script is about checking that objects end up in the generated docs. My vague memory is that @rgommers or @mattip already sorted out some mechanism for detecting the latter, but I may be mistaken.

That would be `tools/refguide_check.py`.



> Either way, the consensus was that `summarize.py` is very rarely used and not worth the extra effort to maintain.

agreed

**Comment by rgommers** [comment]
Merged, thanks @WarrenWeckesser, all

**Pull request merged**
