### PR TITLE
DOC: Extend release notes for #26611

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @seberg,

Addresses https://github.com/numpy/numpy/pull/26611#issuecomment-2174215818.

### CODE REVIEW

**Review by seberg — APPROVED** [review]
Thanks the change looks good and thanks a lot of the quick follow-up.  Sorry for not commenting earlier there.

I'll leave it open in case others want to dicuss (@mhvk might have a thought on printing).

I like the thought of adding a new mechanism for overriding that is part of `printoptions`, it just seems to make sense to me, although I don't know if anyone uses it :).

Thinking a bit about it now: I wonder if the old version of `stringfunc(array, repr=False/True)` wasn't better, though?  Passing `repr` avoids the possible wish to add another option for `str` later at very little cost.

(At which point the name might be a question "override" is not a bad term, maybe even `override_func`, although also fine to to go with str or repr and just have the kwarg anyway.)

**Comment by mhvk** [comment]
Thanks for the ping, I had indeed missed that the previous PR did not only remove `set_string_function` (good) but also introduced an alternative. I don't have a strong opinion, but it does seem to make sense to allow one to override both `repr` and `str`. @seberg - are you suggesting that the user-defined function should not just take the array, but also the `repr` argument? My sense is that it is easier to just provide two arguments, i.e., add add `override_str` as well (or perhaps in analogy with the old functions, call it `str_function` and `repr_function`).

**Comment by seberg** [comment]
Yeah, that was a thought, just to add fewer arguments.  But I don't mind the approach of having two kwargs, either (in which case, there is also no rush).
I thought they might often come together, but if not, then passing `repr=True/False` might just complicate things anyway (because making the one you don't want to override do the default thing is a bit annoying).

**Comment by ngoldbaum** [comment]
Ping @jni @GenevieveBuckley, I noticed the trouble you had in https://github.com/napari/napari/pull/6776, this should help you get back the shorter repr you had before.

**Comment by charris** [comment]
Thanks Mateusz.

I went ahead and merged this because the implementation is already in and the discussion seems to be mostly about alternatives.

**Pull request merged**
