### PR TITLE
BUG: make result of isfinite/isinf/signbit a boolean

### PR DESCRIPTION
**Pull request by juliantaylor**
may return something else than one or zero and npy_bool is
unfortunately an int8 not a c99 bool

### CODE REVIEW

**Comment by juliantaylor** [comment]
let me mess a bit with this
might take a while unless someone has a machine that reproduces the issue

**Comment by charris** [comment]
Yeah, it's painful. I have another test running to see if anything changed between merging your branch and current master.

**Comment by juliantaylor** [comment]
lets see if I can reproduces it in my windows vm, probably faster

**Comment by juliantaylor** [comment]
timeouts oO
can you restart appveyor jobs?

**Comment by charris** [comment]
Well, I was able to restart all of them...

**Comment by juliantaylor** [comment]
hm it works on win32 python34, so maybe a python3.5 problem? Unfortunately I can't test that as I only have windows xp available right now on which 3.5 won't install ._.

**Comment by charris** [comment]
Curiously, when I revert back to merge, only `FAIL: test_nans_infs (test_half.TestHalf)` fails. There is something loose rattling around. Could be a Python 3.5 bug, could be a compiler flag, might be a flags register running wild. Ugh, nasty problem.

**Comment by charris** [comment]
Looks like you didn't revert the whole merge, it's now failing on 64 bits also.. I did `git revert -m 1 3a92c5492`

**Comment by juliantaylor** [comment]
yes that was intentional, so its not the vector code that narrows it down
but its also worrying as this is dog standard code, unless I miss something obvious wrong

**Comment by charris** [comment]
Can't rule out compiler bugs either. I think it safe to say that this problem is Python 3.5 specific, which includes new compilers and possibly build flags.

**Comment by charris** [comment]
The half-float error vaguely smells of a possible optimization problem.

**Comment by juliantaylor** [comment]
ah I think I know the issue!

**Comment by juliantaylor** [comment]
lets see if that works, been using too much c99/c++ lately to notice this error ...

**Comment by charris** [comment]
If only we could make c99 standard... Although I expect that would turn up other problems.

**Comment by jakirkham** [comment]
So, this one checked out ( https://ci.appveyor.com/project/charris/numpy/build/1.0.446 ). Did it just resolve down to add `!= 0` everywhere?

**Comment by charris** [comment]
@jakirkham Looks like it.

**Comment by charris** [comment]
@juliantaylor Kudos for tracking that down.

**Comment by jakirkham** [comment]
Fixes https://github.com/numpy/numpy/issues/6991

**Pull request merged**
