### PR TITLE
DOC: add examples and extend existing dos for polynomial subclasses

### PR DESCRIPTION
**Pull request by jeffyancey**
Documentation changes from #11811

### CODE REVIEW

**Comment by jeffyancey** [comment]
@charris and @eric-wieser, should the `pow` fncs docstrings be modified to explicitly state that that array_like parameter must not be empty? Or should these functions be modified to support empty arrays?

Currently the `polyutils.as_series()` is used, which causes the follow error from line 176 if the array is empty:
```
ValueError: Coefficient array is empty
```

**Review by eric-wieser — APPROVED** [review]

**Comment by eric-wieser** [comment]
I don't think it needs to - if anything, I'd prefer to make `polyutils.as_series` work for empty arrays

**Comment by eric-wieser** [comment]
Small typo in commit message, but I can fix it when I merge

**Comment by charris** [comment]
Thanks @jeffyancey .

**Pull request merged**
