### PR TITLE
BUG: Add  `__ne__` method to dummy_ctype class.

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by charris** [comment]
Could you redo the commit message and provide a description? The class is `dummy_ctype`, not sure what dunder is. Also take a look at `doc/source/dev/gitwash/development_workflow.rst` to see the correct prefixes for the commit summary line. I think here `BUG: ` is probably correct, as the documentation suggests that both `__eq__` and `__ne__` should be explicitly defined.

**Comment by srinivasreddy** [comment]
Done. dunder  = double underscore  :smiley:

**Comment by charris** [comment]
Looks good, but the commit message still needs improvement. All lines should be <=72 characters in length, and the summary even shorter if possible. There are plugins for different editors that help with git commit messages. Anyway, something like
```
BUG: add `__ne__`  method to dummy_ctype class.

There is no Python defined relation between `__eq__` and `__ne__`,  so it is
recommended that both be defined.
```

**Comment by charris** [comment]
Appveyor error is http timeout, so merging this. Thanks @srinivasreddy .

**Pull request merged**
