### PR TITLE
TST: Remove code that is not supposed to warn out of warning assertion

### PR DESCRIPTION
**Pull request by eric-wieser**
Missed in #15804

### CODE REVIEW

**Comment by seberg** [comment]
Thanks, LGTM will merge when the tests are done (or merge yourself), would also be OK, with just including the removal of the boolean deprecation.

**Comment by eric-wieser** [comment]
Removing the boolean deprecation is turning out to be a can of worms. The semantics of `np.delete(x, mask)` seem fairly clear, but the semantics of `np.insert(x, mask, values)` seem hard to reason about.

I'm now of the opinion that we got the semantics of `np.insert(x, indices, values)` wrong when we generalized `indices` to arrays in 1.8.0, and indices should have been interpreted as the index in the destination array.

**Comment by seberg** [comment]
Hmmm, maybe we should just deprecate it instead of changing the behaviour? At least for insert, I can see that it may be weird, although I have to think about it a bit more.

**Comment by eric-wieser** [comment]
I assume by that you mean _"make it an error"_?

**Comment by eric-wieser** [comment]
The crux of the problem with insert is that it doesn't have a clear invariant. The one I would have liked to have picked is:
```
b = np.insert(a, indices, values)
assert b[indices] == values  # and a fills the gaps
```
but instead we end up with something weird

**Comment by seberg** [comment]
Yeah, I meant make it an error. I can see how that makes things more consistent. Not immediately sure it is actually easy to reason about, but inserting more than one element probably simply is not easy to reason about.
I have to admit that it would probably have more sense to do it that way :(. Not sure what to do about it, unless we want to discourage people from `np.insert` completely, make an `np.inserted` or so, and disallow array-indices in `np.insert`.

**Comment by seberg** [comment]
One thing, the current logic actually does make some sense in conjunction with `np.searchsorted`, since you would otherwise need to add `np.arange` to the indices.

**Comment by eric-wieser** [comment]
That's actually how I started down this rabbit hole, in #15798. If you did have to add `np.arange` though then the user wouldn't have reported that bug, as they wouldn't have been caught out by the implicit ordering choice :).

**Comment by seberg** [comment]
Oh, I missed that issue :). Mutiple (unsorted) entries in the values that are inserted in the same spot would indeed be problematic. Which I guess means this can be a well hidden trap :/ as opposed to something that is likely confusing on first sight for users (the case where you need to add `np.arange`). Tricky business, unless we want to deprecate everything again though, or replace it with an `insertsorted` function, if that is really the main use case to begin with...

**Comment by stochashtic** [comment]
I would say the main reason for maintaining a sorted list is obviously to insert into that list. Otherwise, you would just use `sort` for single instance usage. And in Python, where we design towards arrays rather than single entities and the optimised methods for them, then an `insertsorted` method seems a necessity. I believe allowing multiple inputs to `searchsorted` and `insert` via an array is dangerous without considering for the case of (unsorted) entries being inserted at the same spot. And this would naturally occur in any simulation/algorithm.

(My history when reporting  [#15798](https://github.com/numpy/numpy/issues/15798) was transforming some old C++ code using a binary search tree to Python. First using `sort` in order to QA. Then moving to `searchsorted` and `insert` to optimise.)

**Pull request merged**
