### PR TITLE
DOC: Fixed headings for tutorials so they appear at new theme sidebar.

### LINKED ISSUE #17203: DOC: Change rubrics to real headers
After the theme switch, there's now a separate sidebar for in-document headings.

The tutorial documents deliberately avoided this before, I think because the old theme made it look bad?
As a result, thatright sidebar is absent: https://numpy.org/devdocs/user/tutorial-ma.html

We should switch back to using real headings.

cc @melissawm, since I think you argued for `..rubric` originally.

### PR DESCRIPTION
**Pull request by melissawm**
Changes section titles in tutorials so they are proper sphinx headings and appear at the document TOC sidebar in the new PyData theme.

Fixes #17203

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Thanks! I wonder if there's any value to extra hierarchy in the headings, but there's no reason not to put this in as is first.

**Comment by eric-wieser** [comment]
Seems to work:

* https://15429-908607-gh.circle-artifacts.com/0/doc/build/html/user/tutorial-svd.html
* https://15429-908607-gh.circle-artifacts.com/0/doc/build/html/user/tutorial-ma.html

**Comment by eric-wieser** [comment]
@mattip: The way you made the navbar taller means the anchor links leave the headings covered by it. Something for a follow-up...

**Comment by mattip** [comment]
> the anchor links leave the headings covered by it.

Sorry, I don't understand. Could you define the terms a little better or somehow show what you mean?

**Comment by eric-wieser** [comment]
I'll open a new issue with a screenshot

**Pull request merged**
