### PR TITLE
DEP: remove PolyBase from np.polynomial.polyutils

### PR DESCRIPTION
**Pull request by hollycorbett**
DEP: Remove PolyBase from np.polynomial.polyutils

Addresses issue #15658 by removing PolyBase and associated error classes with only usages here.  Happy to submit alternative PR using getattr approach instead if desired.

### CODE REVIEW

**Comment by BvB93** [comment]
Can you also remove the exceptions from the stub file?
https://github.com/numpy/numpy/blob/d3b03c890e19e50e2815432d4ad1457dd8835028/numpy/polynomial/polyutils.pyi#L6-L10

**Comment by hollycorbett** [comment]
All done @BvB93 ... thanks for the heads up.  Do let me know if I missed anything.

**Comment by charris** [comment]
This could use a release note. See `doc/release/upcoming_changes` for examples. The name should be `18963.expired.rst`.

**Comment by BvB93** [comment]
> All done @BvB93 ... thanks for the heads up. Do let me know if I missed anything.

Nop, no further annotation-related comments from me.

**Comment by hollycorbett** [comment]
@charris PR updated.  Happy to squash before merge if preferred.

**Review by rossbar — APPROVED** [review]
I took the liberty of adding a few minor touchups to the release note (basically just formatting + mentioning that the Exceptions are also removed).

LGTM - I'm in favor of removing the objects outright. Thanks @hollycorbett !

**Comment by charris** [comment]
Thanks @hollycorbett .

**Pull request merged**
