### PR TITLE
DOC: Remove all references to bigndarray in documentation. 

### PR DESCRIPTION
**Pull request by k-kapp**
Fixes issue #9204.

### CODE REVIEW

**Review by eric-wieser — COMMENTED** [review]
Commit message should stand alone, and not _just_ reference the issue (so that it can be searched for). Patch LGTM though

**Comment by k-kapp** [comment]
Ok, sure. Just fixed it. 

Thanks, now I know.

**Comment by eric-wieser** [comment]
Commit message and PR title are not the same thing, I'm afraid - `git commit --amend` will let you change the former.

If you add `[ci skip]` in the last line of the message (or really anywhere), then it'll skip tests and I can just merge it

**Comment by eric-wieser** [comment]
Actually, I'll just squash and merge to fix it myself

**Comment by eric-wieser** [comment]
Thanks!

**Pull request merged**
