### PR TITLE
DOC: Fix unrendered links

### LINKED ISSUE #13740: "Contributing to NumPy" links not rendering?
[Contributing to NumPy](https://www.numpy.org/devdocs/dev/index.html) has some text that is probably intended to render as hyperlinks but doesn't. Instead, it just appears in italics:

Commit locally as you progress (`git add` and `git commit`) Use a _properly formatted_ commit message, write tests that fail before your change and pass afterward, run all the tests _locally_. Be sure to document any changed behavior in docstrings, keeping to the NumPy docstring _standard_.

From `numpy/doc/source/dev/index.rst`:
```
Commit locally as you progress (``git add`` and ``git commit``)
     Use a `properly formatted <writing-the-commit-message>` commit message,
     write tests that fail before your change and pass afterward, run all the
     `tests locally <development-environment>`. Be sure to document any
     changed behavior in docstrings, keeping to the NumPy docstring
     `standard <howto-document>`.
```
There are many other instances throughout the document (which is otherwise great, BTW).

### PR DESCRIPTION
**Pull request by kritisingh1**
Fixes #13740

### CODE REVIEW

**Comment by kritisingh1** [comment]
Reference to headings in files present in a different directory is not working for some reason, so I included web links for them, would like to inculcate a workaround if possible.

**Comment by mattip** [comment]
I am not sure why the references are not being generated automatically, but you can for ce a reference to be created like the [top line here](https://raw.githubusercontent.com/numpy/numpy/v1.16.4/doc/source/dev/development_environment.rst) and then refer to them as

```
:ref:`development-environment`
```

**Comment by kritisingh1** [comment]
@mattip everything is working as expected now.

**Comment by mattip** [comment]
Thanks @kritisingh1

**Pull request merged**
