### PR TITLE
TST: Disable shippable until we can fix it.

### PR DESCRIPTION
**Pull request by charris**
Not sure this works, using same approach that worked for travis.

### CODE REVIEW

**Comment by charris** [comment]
Well, that didn't work, let's try maintenance branches only.

**Comment by charris** [comment]
OK, this seems to work.

**Comment by seberg** [comment]
Just pinging @tylerjereddy in case you have any input about shippable? But I think disabling it should be fine.

**Review by tylerjereddy — APPROVED** [review]
Makes sense, shippable tends to clog up pretty fast with a big queue if there's an issue.

**Pull request merged**
