### PR TITLE
BUG: non-numeric type fill lack of error

### PR DESCRIPTION
**Pull request by max-kov**
From the docstring of `numpy.ma.maximum_fill_value`:

```
"""
Return the maximum value that can be represented by the dtype of an object.
...
---skip a bit---
...
Raises
------
TypeError
    If `obj` isn't a suitable numeric type.
```

However, when I used the function in my scripts it instead returned `None`:

```
>>> import numpy.ma as ma
>>> import numpy as np
>>> ma.minimum_fill_value(np.void(0))
>>>
```
I think the problem is coming from `numpy.core.numerictypes._minvals` and `numpy.core.numerictypes._maxvals`, the latter of which looks like this:
```
{<class 'numpy.bool_'>: 1,
 <class 'numpy.int8'>: 127,
 <class 'numpy.uint8'>: 255,
 <class 'numpy.int16'>: 32767,
 <class 'numpy.uint16'>: 65535, 
 <class 'numpy.int32'>: 2147483647,
 <class 'numpy.uint32'>: 4294967295, 
 <class 'numpy.int64'>: 9223372036854775807, 
 <class 'numpy.uint64'>: 18446744073709551615, 
 <class 'numpy.longlong'>: 9223372036854775807, 
 <class 'numpy.ulonglong'>: 18446744073709551615, 
 <class 'numpy.float16'>: None, 
 <class 'numpy.float32'>: inf, 
 <class 'numpy.float64'>: inf,
 <class 'numpy.float128'>: inf, 
 <class 'numpy.complex64'>: None,
 <class 'numpy.complex128'>: None, 
 <class 'numpy.complex256'>: None, 
 <class 'numpy.object_'>: None,
 <class 'numpy.bytes_'>: None, 
 <class 'numpy.str_'>: None, 
 <class 'numpy.void'>: None, 
 <class 'numpy.datetime64'>: 9223372036854775807,
 <class 'numpy.timedelta64'>: 9223372036854775807}
```
The array clearly adds the types without a maxvalue as a `None` value, but the `_scalar_fill_value` expects them to be missing. To fix we check if the value is indeed null before returning (alternatively we can remove all null values from the array but I could not decide which approach is better). Result:

```
>>> import numpy as np
>>> import numpy.ma as ma
>>> ma.minimum_fill_value(np.void(0))
Traceback (most recent call last):
  File "/home/max/code/numpy/numpy/ma/core.py", line 289, in _scalar_fill_value
    raise KeyError()
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/max/code/numpy/numpy/ma/core.py", line 347, in minimum_fill_value
    return _extremum_fill_value(obj, min_filler, "minimum")
  File "/home/max/code/numpy/numpy/ma/core.py", line 296, in _extremum_fill_value
    return _recursive_fill_value(dtype, _scalar_fill_value)
  File "/home/max/code/numpy/numpy/ma/core.py", line 215, in _recursive_fill_value
    return f(dtype)
  File "/home/max/code/numpy/numpy/ma/core.py", line 293, in _scalar_fill_value
    raise TypeError(f"Unsuitable type {dtype} for calculating {extremum_name}.")
TypeError: Unsuitable type |V0 for calculating minimum.
>>>
```

### CODE REVIEW

**Comment by max-kov** [comment]
Also, the fact that `numpy.float16` is `None` looks suspicious to me. [Here](https://github.com/numpy/numpy/blob/3106cbea04bcb910b852b4a511040d6897e3bea6/numpy/ma/core.py#L195) it maps `float32` and `float64` to `inf` I'm not sure if `float16` should be mapped too.

**Comment by seberg** [comment]
Related to gh-15991 which happens to close that thinig I believe.

**Comment by max-kov** [comment]
> Related to [gh-15991](https://github.com/numpy/numpy/pull/15991) which happens to close that thinig I believe.

I think that fixes the `float16` issue, but not the fact that the fill with `np.void` should fail.

**Comment by seberg** [comment]
Sorry yes, that was what I was referring too, that would not have been clear though.

**Comment by max-kov** [comment]
3 tests are now failing because somewhere down the line the test tries to fill a string type value which currently does not have a maximum or minimum value. I'm not really sure what the best way to fix that, any ideas?

**Comment by eric-wieser** [comment]
It looks like the behavior of `masked_arr.min()` on dtypes with a `None` fillvalue is to use `masked_arr.fill_value` to fill masked elements, whereas after your patch it's an error.

I think the right approach here is to use the new `where` argument to `min` and `max`, and eliminate the used of `minimum_fill_value` and `maximum_fill_value` entirely.

**Comment by max-kov** [comment]
> It looks like the behavior of `masked_arr.min()` on dtypes with a `None` fillvalue is to use `masked_arr.fill_value` to fill masked elements, whereas after your patch it's an error.
> 
> I think the right approach here is to use the new `where` argument to `min` and `max`, and eliminate the used of `minimum_fill_value` and `maximum_fill_value` entirely.

Sorry, I don't know which `where` argument you are talking about. Or did you mean to create a new `where` argument in `min`/`max`?

**Comment by eric-wieser** [comment]
The where argument in `masked_arr.data.min`

**Comment by max-kov** [comment]
> The where argument in `masked_arr.data.min`

Actually, I'm not entirely sure that helps. To use `min` with `where` mask you need to provide an `initial` and if initial isn't the biggest value in the array the result will be wrong. So, I think we're back to using `maximum_fill_value` as the initial? Or we could to through the whole array looking for the value

**Comment by max-kov** [comment]
I tried my best to remove the usage of `minimum_fill_value` but now instead I had to find the max value for the initial. And the problems with argsort trying to fill strings are still there.

**Comment by charris** [comment]
@max-kov Needs a rebase. Do you want to pursue this?

**Comment by charris** [comment]
@max-kov You may want to make this an issue instead.

**Pull request closed without merging**
