### PR TITLE
add PyMatrix for pure python nd matrix implementation and its subclas…

### PR DESCRIPTION
**Pull request by yiakwy**
…s supports vector based opertors

This implementation is highly recommended for numeric developers to inspect. Initially, I thought (2014) numpy doesn't support object based n-d container (including 1 d row or col vector). Then I found number has decided to support object. Congrats!

I want to contribute these codes for discussion How can I better integrate it into numeric with supporting of fast c implementation.

### CODE REVIEW

**Comment by rgommers** [comment]
@yiakwy I suggest you explain on the mailing list what https://github.com/yiakwy/PyMatrix does (your README is empty) and how that complements numpy. Then we can give you some feedback. Maybe there's a specific feature you're missing in numpy that can be added?

This PR isn't going to work for sure, so I'll close it now.

**Comment by juliantaylor** [comment]
Note numpy already has a matrix class that adds some operations commonly used with this structure.
But as a subclass of ndarray it also has many problems, like not all functions working on arrays are also able to work on matrices in a reasonable fashion.
So we recommend to use arrays and explicit `np.dot` and `np.linalg` usage instead.

**Comment by yiakwy** [comment]
@rgommers  I have added files. sorry I didn't notice subfolder before.
@juliantaylor yes I know. But my implementation is different and support n-d matrix Array. Much better than 'matrix'. My question is numpy c implementation nd array is really fast, I wan to integrate my codes into numpy. How can I do it?

2000 codes programming protocol:

class	member	description
Null	implement python protocol	interface function to mute numeric errors
Size	implement python protocol	matrix size descriptor
_data	
assert_equal(size)	
assert_tolerate(size)	
Formatter	implement python protocol	matrix format descriptor
_templates	used to print element
_width	element width
_size	matrix size
fire	formate element
	
matrixarray:list	implement python protocol	n demension matrix array
size	an instance of Size
formmat	an instance of Formmate
_init_hint(hint)	initialize user input with defaults
_init_formatter(_float, _width, formatter)	
_init_array_formatter(_float, _width, formatter)	
_init_matrix_formatter(_float, _width, formatter)	
matrixIterator	PEP8 , Iterator standards
setup_r_mode()	R mode
clear_r_mode()	
setIndice()	
clear_indice()	
setheader()	
clear_headers()	
isheader()	
isIndex()	
isIndexHeader()	
x_lable_enabled()	
y_label_enabled()	
clear()	clear elements inside memory
setUp(l, r,c ,0)	initialize matrixarrray from a array
fillUp(*iterators)	fillup a matrix with iterators
nil(r,c, value=None)	initial a matirx of size [r, c]
nil_multi(*args)	initial a matirx of size args
Zeros(r, c=None)	return zeros matrix of size [r, c]
tolist()	return a real array and eleminated matrix formate like [[]] or [[],[]]
inner_rep()	runtime inner list representation
_setitem(id, element, l, type)	"+": set l[id]=element, id is axes list;"-": pop out l[id] and return 
_getitem(_id, l)	get l[_id], were _id is a axes list, return multi elements as a list
_setitem_multi(ids, root, it, typ="+")	to be called by __setitem__ 
_getitem_multi(ids, root)	to be called by __getitem__
_str()	
_header(axis, formatter, l)	
_indice(axis, formatter, l)	
_modify_line(out, index, offset, size)	
_element2str(a, b, c, formatter)	
_element2str_sim(a, b, c, formmater)	
_shape_array()	compute array raw demensions by depth first searching
trp()	get transpose of n-d matrixaray
is_equal(other)	
is_tolerate(other)	
"matrixarraynum:
matrixarray"	implement python num protocol	
add_matrix()	
sub_matrix()	
neg_matrix()	
iad_matrix()	
dot_In()	
dot_out()	
div_matrix()	
mean_vt	
ubds_vt()	
sum()	
mean()	
ubds()	
map(Func, *iterables)	core function to implement other operators

**Comment by yiakwy** [comment]
Yes I think we should fix it as soon as possible.

I recommend for example __dot__ is a operator manager, which will inspect
parameters coming in and call proper operator like dot_in or dot_out. Where
dot_in or dot_out should obey "reduce, map, filter" implementation protocol.

2015-07-04 2:33 GMT+08:00 Julian Taylor <notifications@github.com>:

**Pull request closed without merging**
