### PR TITLE
BUG: Fix loss of precision for large values in long double divmod

### PR DESCRIPTION
**Pull request by eric-wieser**
No test I'm afraid, as my platform has no extended precision floats.

### CODE REVIEW

**Comment by charris** [comment]
Should still be possible to write a test, you just can't test the test on your os.

**Comment by eric-wieser** [comment]
I suppose `divmod(finfo(longdouble).max, 1)` should do the trick? I'm unlikely to get the test right first time though, and it takes like 20 minutes for the results to come through. I also have no way of knowing if the test fails on 1.13 at the moment.

**Comment by charris** [comment]
OK, open an issue and I'll take a crack at it later.

**Comment by charris** [comment]
Thanks Eric.

**Pull request merged**
