### PR TITLE
BUG: reorder operations for VS2015

### PR DESCRIPTION
**Pull request by mattip**
An attempt to influence #12520. Since the offending commit was 24c9faa, I tried reverting the logic in that commit.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Will try checking this out locally and seeing if it solves my problem tomorrow.

**Comment by Robe21** [comment]
7

**Comment by Robe21** [comment]
### 

- [](url)

**Comment by eric-wieser** [comment]
Yeah, this fixes the problems I was having. Running the full test suite now, but I'm expecting a pass

**Comment by eric-wieser** [comment]
Yeah, this fixes everything for me.

It might still be worth holding off on merging this until we can reproduce the failure in CI

**Comment by mattip** [comment]
What is even more confusing is that AFAICT Visual Studio 2015 uses Visual C++ 14.0 compiler, but so does Visual Studio 2017? The information on the [python windows compiler](https://wiki.python.org/moin/WindowsCompilers) page is confusing. What exact version of `cl` do you have?

**Comment by eric-wieser** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```

**Comment by mattip** [comment]
> It looks like I have the complete VS2015 Update 2 installation.

According to [wikipeida](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#2015), there was update 3 in June 2016. Is there a reason you cannot update?

**Comment by eric-wieser** [comment]
Nope, no reason I cannot update - but if the resolution is "update 3 or newer required", then we should blacklist my compiler version

**Comment by mattip** [comment]
I think we are done. We have a workaround for your (assumed broken) compiler, I would prefer not to add a CI run for a niche compiler. Do we have a mechanism to blacklist compilers, other than documenting the situation?

**Comment by tylerjereddy** [comment]
> I would prefer not to add a CI run for a niche compiler

Fair enough, saves me some work, but in that case I would prefer either:

1. Robustly detect and blacklist the compiler 
2. Come up with a (likely creative) unit test for reproducing / preventing regression

**Comment by eric-wieser** [comment]
> Come up with a (likely creative) unit test for reproducing / preventing regression

Such a unit test already exists, which is how we found this in the first place

> Robustly detect and blacklist the compiler

I feel like `config.h` holds the secret to detecting this kind of thing (by compiling and running a dummy program at build time).

**Comment by tylerjereddy** [comment]
Sorry, by *creative* I meant a test that will cause a failure with compilers currently used in CI. But yeah, I guess putting some kind of dummy code that will fail for the offending compiler is probably an order of magnitude less ugly & does the job of failing early / reproducibly instead of build successfully and then maybe only failing an isolated unit test.

I suppose the dummy code could even suggest the reason for a specific failure, although I don't know offhand if we annotate that stuff.

**Comment by charris** [comment]
Is this still WIP ?

**Comment by mattip** [comment]
The fix itself is good to go. The remaining question is how much energy we should invest in making sure the problem does not repeat by crafting a stand-alone test for faulty compilation at build time, to let a potential user know early that their build will give wrong results. I am of the opinion we do not need to do anything further, this should just be merged as-is, and users of these kinds of compilers should be running the test suite which would detect the problem.

**Comment by charris** [comment]
Let's put this in. The fact that such a new compiler can cause problems is disturbing, but it seems we have a workaround. I'll make a `compiler issue` tag and apply it to the relevant issues and PRs so we can make a bad compiler list at some point.

Does this mean that the invalid value bit is getting set by some platforms?

**Comment by eric-wieser** [comment]
Hmm, I think @charris has a point - don't we have to go back to explicitly clearing the invalid bit again?

**Comment by mattip** [comment]
I did not remove the existing call to `npy_clear_floatstatus_barrier` on lines [1879](https://github.com/numpy/numpy/pull/12526/files#diff-eb6ddd50e74f51bd4bceae1d17bfe4dcL1877), [1907](https://github.com/numpy/numpy/pull/12526/files#diff-eb6ddd50e74f51bd4bceae1d17bfe4dcR1907) and [1065](https://github.com/numpy/numpy/pull/12526/files#diff-96d92ba7a585978d3977b911b285cd4dR1065). Without those we would have seen warnings in the tests.

**Comment by eric-wieser** [comment]
Huh, I thought we did the initial reordering in order to eliminate those. Guess that's what happens when I respond from mobile. Thanks for fixing this for me, anyway!

**Pull request merged**
