### PR TITLE
BUG: Ensure `PyArray_AssignRawScalar` respects `NPY_NEEDS_INIT`

### LINKED ISSUE #11075: `PyArray_AssignRawScalar` does not respect `NPY_NEEDS_INIT`
Ran into an issue where I defined a custom dtype, `AutoDiffXd`, which flags itself as `NPY_NEEDS_INIT`.

I've defined an implicit conversion from `float` to `AutoDiffXd`, and the following conversions do not seem to pose an issue:
```
x = np.array([0., 1.], dtype=AutoDiffXd)

x = np.zeros(2, dtype=AutoDiffXd)
x[:] = [0., 1.]
```

However, the following *does* cause an issue:
```
x = np.zeros(2, dtype=AutoDiffXd)
x[:] = 0.
```

It seems that at present, `PyArray_AssignRawScalar` just allocates memory and directly uses it for casting:
https://github.com/numpy/numpy/blob/cc8cef9c24abfcae4ff7acd8e85bd1c3307b41e3/numpy/core/src/multiarray/array_assign_scalar.c#L236-L252

I believe it should check for `NPY_NEEDS_INIT`, and zero the memory out if need be.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #11075

---
This change is [Reviewable](https://reviewable.io/reviews/numpy/numpy/11076)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Confirmed on my downstream project that this resolves the issue.

**Comment by charris** [comment]
LGTM, thanks @EricCousineau-TRI . I've got to wonder if this is the only place where this might be a problem.

**Comment by mattip** [comment]
Reviewing the 91 places where `PyArray_malloc` is used in `numpy/core/src`, I found the following questionable uses, The others are all followed by a `memcpy`, `memset` or assignment:

- in [`_strided_datetime_cast_data_clone`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/dtype_transfer.c#L780)
- in [`npyiter_allocate_buffers`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/nditer_api.c#L1773)
- ['NpyIter_Copy`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/nditer_constr.c#L594), but it seems the data is assigned to at line 633
- [`_parse_signature`](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L400) seems line 446 assumes the allocated pointers are all initialized to NULL

Should I open a new issue / PR with this info?

**Comment by EricCousineau-TRI** [comment]
Thank y'all for the speedy response!

> Should I open a new issue / PR with this info?

Yes please! After looking at the code you mentioned, some small comments:
* `_strided_datetime_cast_data_clone` - Not sure on this one; if a custom dtype requires initialization, and specifies a cast to `datetime`, then perhaps this would make an issue.
* `npyiter_allocate_buffers`, `NpyIter_Copy` - Yup, these look like it could be a hotspot for these issues. I actually haven't tested iteration yet, so I'll check on that, and can post on your follow-up issue.
* `_parse_signature` - This one looks like it's just allocating a buffer for a string for the function signature, and some pointer / dimension arrays?

Thanks!

**Pull request merged**
