### PR TITLE
ENH: Add a float_power function with at least float64 precision.

### PR DESCRIPTION
**Pull request by charris**
The new float_power function converts integers and inexact types to inexact types of minimum precision float64 before computing the power. The intent is one should not need to worry about overflow or negative powers when computing a power when type preservation is not a factor. It also follows the suggestion in the mailing list discussion that the return type of the `**` operator be double precision.

### CODE REVIEW

**Comment by charris** [comment]
This is a work in progress, do not merge yet.

**Comment by NeilGirdhar** [comment]
Why not have the user convert their array to float32 first?

**Comment by charris** [comment]
@NeilGirdhar Avoiding explicit conversion is the whole point. The arises from the discussion on the mailing list of how the `**` operator should behave with integers to (negative) integer powers.

**Comment by NeilGirdhar** [comment]
so `fpower(x, y)` is basically:

```
def fpower(x, y):
     if np.issubdtype(x.dtype, np.integer):
         x = x.astype(np.float)
     return x ** y
```

?

**Comment by charris** [comment]
Updated and function renamed `float_power`.

@NeilGirdhar It is a ufunc, so the output type depends on the type of both inputs. In this case, the minimum precision is float64 as no lesser precision is available for the ufunc to convert to.

**Pull request merged**
