### PR TITLE
CI: switch the Cygwin job to Meson

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixing the Cygwin workflow as requested in #24410. @rgommers 

This gets the Cygwin build to this point.

```
Library m found: YES
Found CMake: /usr/bin/cmake (3.25.3)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency openblas found: NO (tried pkgconfig and cmake)
Run-time dependency openblas found: NO (tried pkgconfig and cmake)

../../numpy/meson.build:174:4: ERROR: Problem encountered: No BLAS library detected! Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).
```

Fixing that is beyond the scope of this PR.

### CODE REVIEW

**Comment by rgommers** [comment]
> Fixing that is beyond the scope of this PR.

Thanks @mkoeppe. I'll have a go at fixing that up today.

**Comment by rgommers** [comment]
I pushed a set of fixes. One thing to look at still is these warnings for every C and C++ file:
```
warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
```
It look like the configure check says it's supported but it's actually not:
```
Compiler for C supports function attribute visibility:hidden: YES
```

**Comment by rgommers** [comment]
This is good to go now.

**Comment by charris** [comment]
Thanks @mkoeppe @rgommers .

**Comment by lazka** [comment]
> It look like the configure check says it's supported but it's actually not:
> 
> ```
> Compiler for C supports function attribute visibility:hidden: YES
> ```

I've hit the same issue with mingw-w64 and proposed a fix for meson: https://github.com/mesonbuild/meson/pull/12473

**Comment by lazka** [comment]
> I've hit the same issue with mingw-w64 and proposed a fix for meson: [mesonbuild/meson#12473](https://github.com/mesonbuild/meson/pull/12473)

This has now been merged. I'd guess it will be part of 1.4

**Comment by rgommers** [comment]
Great, thank you @lazka. It'll be half a year or so before we can rely on Meson 1.4.0 as the minimum version, but it'll be nice to be able to clean up the special-casing added in this PR.

**Comment by lazka** [comment]
It was released as part of meson 1.3.0 now.

**Pull request merged**
