### PR TITLE
TST: Make test_partial_iteration_cleanup robust but require leak checker

### LINKED ISSUE #21169: BUG: ``test_partial_iteration_cleanup`` is failing for wheel builds
See [here](https://dev.azure.com/numpy/numpy/_build/results?buildId=23137&view=results).

Not sure what changed to cause this, seems about two weeks old.

### PR DESCRIPTION
**Pull request by seberg**
This makes sure the test is not flaky, but the test now requires a leak checker (both valgrind or reference count based should work in CPython at least).

Closes gh-21169

### CODE REVIEW

**Comment by seberg** [comment]
Hmmm, the test failure (not cygwin, that just failed randomly) seems due to pytest phasing out some nose backcompat stuff.  The main part seems to be `setup()` and `teardown()` methods, which need to be renamed.

**Comment by charris** [comment]
To be clear, the test runs but does not error, leak detection is left to valgrind etc. ?

**Comment by seberg** [comment]
Yes, I guess the test still may cover some code path.  But the main reason why its there is only checked when running with pytest-valgrind or pytest-leaks (or similar).

**Comment by charris** [comment]
Thanks Sebastian.

**Pull request merged**
