### PR TITLE
DOC: in PR template, set expectations for PR review timeline

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by mattip** [comment]
As discussed in today's community meeting. No need for CI, this is part of the github PR process documentation.

**Comment by mattip** [comment]
Thanks @rgommers

**Comment by bjnath** [comment]
> If you're submitting a new feature or substantial change in functionality,
> make sure you discuss your changes in the numpy-discussion mailing list first: 
> https://mail.python.org/mailman/listinfo/numpy-discussion

Put yourself in the shoes of someone reading this:
* If nobody responds, is that good or bad? 
* How long should I wait for a response? 
* What happens if I skip this step?

On the other hand, there's no room for answers -- the template is already lengthy. 

I'd suggest we rethink the template:

>\

**Comment by mattip** [comment]
Sounds like a good idea. Feel like making a PR? I would say "new feature or API change" instead of "big one" though. I doubt anyone is going to submit a large refactoring with no feature or API change as a first time contributor out of the blue.

**Comment by bjnath** [comment]
Thanks, @mattip. Good suggestion on "big one." 

So what *is* the guidance for someone who writes to the list and hears nothing back after a week?

**Comment by bjnath** [comment]
@mattip Submitted PR #17440 with the big, un-missable instructions proposed above.

**Pull request merged**
