### PR TITLE
BLD: Try building python3.11 wheels.

### PR DESCRIPTION
**Pull request by charris**
Try simplest approach to building Python3.11 wheels. This will probably fail on windows and macosx.

### CODE REVIEW

**Comment by mattip** [comment]
The cp311 wheel builds failed with
> `cibuildwheel: No build identifiers selected: BuildSelector(skip_config='cp36-* cp37-* pp37-* *-manylinux_i686 *_ppc64le *_s390x *-musllinux*', build_config='cp311-manylinux_x86_64', requires_python=None, prerelease_pythons=False)`

I think everyone will need a new cibuildwheel that support 311. See pypa/cibuildwheel#1221

**Comment by charris** [comment]
> I think everyone will need a new cibuildwheel that support 311

Looks like it. Might be a couple of weeks.

**Comment by charris** [comment]
close/reopen

**Comment by lithomas1** [comment]
@charris maybe try bumping cibuildwheel to 2.9.0? Looks like py 3.11 should be supported since that release.

**Comment by charris** [comment]
> maybe try bumping cibuildwheel to 2.9.0?

Thanks, let's give that a shot.

**Comment by charris** [comment]
Looks good. I'm going to put this in.

**Comment by charris** [comment]
@mattip @matthew-brett Multibuild for aarch64 is not supporting Python 3.11, do we need to update something?

**Comment by charris** [comment]
@lithomas1 How does cibuildwheel get run on travis? I don't see it anywhere and it isn't uploading the python 3.11 wheel for aarch64.

**Pull request merged**
