### PR TITLE
BUG: use proper input and output descriptor in array_assign_subscript cast setup

### LINKED ISSUE #27003: BUG: StringDType: integer indexed assignment does not work for arena strings.
### Describe the issue:

When the strings are "allocated" in the arena (len >= 16), assignment through integer indexing does not modify the array.
Curiously, it works with boolean indexing.
Thanks !

### Reproduce the code example:

```python
import numpy as np
from numpy.dtypes import StringDType
a = np.array(['a'*16, 'b'*16], dtype=StringDType())
b = np.array(['d'*16, 'e'*16], dtype=StringDType())
a[[0, 1]] = b
print(a) # expecting ['d'*16, 'e'*16], but getting ['a'*16, 'b'*16]
# curiously a[[True, True]] = b works...
```

### Error message:

_No response_

### Python and NumPy Versions:

2.0.1
3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #27003.

Probably going to be a long tail of these.

### CODE REVIEW

**Comment by mattip** [comment]
Thanks @ngoldbaum. Should we backport this?

**Comment by egesip** [comment]
Thanks @ngoldbaum, @mattip. I hope it's not gonna be a long tail of these, as you suspect, but there is still an issue if the r-value is a list:

```python
    a = np.array(['', ''], dtype='T')
    a[[0, 1]] = ['a'*16, 'b'*16]
    print(a)  # getting ['', '']
```

Note that both `a[[0, 1]] = ['a', 'b']` and `a[[0, 1]] = np.array(['a'*16, 'b'*16], dtype='T')` work (the latter one thanks to the current fix).

And worse, if `a` has some non-empty values, I get a crash (I am on Windows):

```python
    a = np.array(['a', 'b'], dtype='T')
    a[[0, 1]] = ['a'*16, 'b'*16] # crash
```

**Comment by ngoldbaum** [comment]
@mattip I added the backport label, thanks for the reminder.

@egesip I opened #27053 to track that. Thanks for the report, If you find any more of these please open issues, it's really helpful to get reports like this.

**Comment by egesip** [comment]
Will do. Thanks a lot for tackling these issues.

**Pull request merged**
