### PR TITLE
BUG: Add workaround for missing ufunc error propagation

### LINKED ISSUE #19634: ValueError becomes SystemError for in-place exponentiation (nightly build)
### Reproducing code example:

This issue is breaking tests where we expect to throw `ValueError`s and are now getting `SystemError`s.

```Python
import numpy as np

a = np.array([0, 1], dtype='int64')
try:
    a ** -3
except Exception as e:
    print(repr(e))
try:
    a **= -3
except Exception as e:
    print(repr(e))
```

### Error message:

With numpy 1.21.1:

```
ValueError('Integers to negative integer powers are not allowed.')
ValueError('Integers to negative integer powers are not allowed.')
```

With nightly build `'1.22.0.dev0+679.g261a769dd'`:

```
ValueError('Integers to negative integer powers are not allowed.')
SystemError("<ufunc 'power'> returned a result with an error set")
```

Full IPython traceback:

```
ValueError                                Traceback (most recent call last)
ValueError: Integers to negative integer powers are not allowed.

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-4-359753e44972> in <module>
----> 1 a **= -3

SystemError: <ufunc 'power'> returned a result with an error set
```

### NumPy/Python version information:

```
1.22.0.dev0+679.g261a769dd 3.9.6 (default, Jul 30 2021, 16:35:19) 
[GCC 7.5.0]
```

### PR DESCRIPTION
**Pull request by seberg**
Some ufuncs (currently `np.power` soon hopefully only some bad user
ufunc) may release the GIL but still set Python errors.
The best bet we have is attempting to blanket check for errors before
returning from the ufunc.

This adds a new ufunc (since we should move `np.power` to the new
style definition with error return), and tests all relevant ufunc
entrypoints.

Closes gh-19634

### CODE REVIEW

**Comment by seberg** [comment]
Technically the change for `ufunc.at` could be backported, I guess...  But it should have been wrong for all eternity, and `np.power.at` seems pretty unlikely to be used much.

**Comment by mattip** [comment]
> This adds a new ufunc

This adds a new ufunc only for testing, right? 

It looks OK to me. I am a bit worried about setting the error state when the GIL is released, theoretically this could be clobbered by another thread setting/resetting error state during the time the GIL is released. But I guess this will all be fixed when we move to ufuncs returning a value, so the return value of `innerloop()` would be a more reliable indication of an error.

**Comment by WarrenWeckesser** [comment]
@seberg, I have code in some gufuncs in [`ufunclab`](https://github.com/WarrenWeckesser/ufunclab) that use the same code as in  `power` for raising an exception in a loop function.  Two examples are `gmean` and `hmean` in [`means_gufunc.c.src`](https://github.com/WarrenWeckesser/ufunclab/blob/main/src/means/means_gufunc.c.src).  With the main branch of numpy (which includes this PR), an exception is not raised when those functions are given an empty input (and I have double checked that the code that sets the exception does get executed).  E.g.
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.22.0.dev0+1438.gdd2eaaabd'

In [3]: from ufunclab import gmean

In [4]: gmean([])
Out[4]: 0.0
```
Was the fix in this PR for plain element-wise ufuncs only?

**Comment by seberg** [comment]
Possibly, since the test only covers the ufunc and not gufunc path. I did not expect a problem in the gufunc version, because I think it always uses the iterator API, and `NpyIter_Deallocate` checks for `PyErr_Occurred()`.

But, after sqinting a bit, I see it reads `NpyIter_Deallocate(iter) < 0` which is incorrect, it should be `!NpyIter_Deallocate(iter)` because the iterator API unfortunately uses "1 is success convention" for no good reason...

**Comment by WarrenWeckesser** [comment]
By the way, I confirmed that the change of  `NpyIter_Deallocate(iter) < 0` to `!NpyIter_Deallocate(iter)` at https://github.com/numpy/numpy/blob/dd2eaaabdb0451631e95376ae2b4d319082b438e/numpy/core/src/umath/ufunc_object.c#L2530 fixes the issue for gufuncs.

**Comment by seberg** [comment]
Yeah, changing to bool would be nice, but it would have to have the same width/be binary compatible with `int` and I don't think it is.

**Comment by seberg** [comment]
Thanks, much appreciated! I was going to, but have not started on it.

**Pull request merged**
