### PR TITLE
MANT: Cleanup of _pyarray_revert

### PR DESCRIPTION
**Pull request by jaimefrio**
Removed several useless calls to copyswap, plus added a slightly
more efficient method for non-complex numeric types.

### CODE REVIEW

**Comment by jaimefrio** [comment]
The code in the second branch is a tad faster than the one in the first branch, e.g. with `a` an array of 1000 doubles and `b` and array of 100 doubles:

```
%timeit np.correlate(a, b)  # this does not require a return array reversal
10000 loops, best of 3: 33.3 µs per loop  # this PR
10000 loops, best of 3: 33.9 µs per loop  # 1.9.2

%timeit np.correlate(b, a)  # this requires a return array reversal
10000 loops, best of 3: 37.2 µs per loop  # this PR, +3.9 µs
10000 loops, best of 3: 39.3 µs per loop  # 1.9.2, +5.4 µs
```

When `b` is really small and `small_correlate` kicks in, the array reversal may take about 50% of the total time, so this apparently small difference becomes more significant.

But there is of course also the option of going for simplicity, getting rid of the second branch and unconditionally using the first one for all dtypes.

**Comment by ahaldane** [comment]
Do you also need to make sure that user-defined types go through the first path, using `PyArray_ISUSERDEF`? Also, if a new standard type is ever added we'd have to remember to check that it can go through the second path.

Otherwise looks good, as far as I can tell.

**Comment by jaimefrio** [comment]
You are probably right... Since the first branch can handle anything, it is probably better to have the special path for `PyArray_ISNUMERIC && !PyArray_ISCOMPLEX` and have everything else go through the other more reliable path...

**Comment by jaimefrio** [comment]
Ok, pushed a new commit.

**Comment by ahaldane** [comment]
Looks good to me now. 

I might also add a comment in the first block like "optimization for unstructured dtypes" but maybe that's overkill.

**Comment by jaimefrio** [comment]
If all it takes to make you happy is a little comment... ;-)

**Comment by charris** [comment]
Thanks Jaime.

**Pull request merged**
