### PR TITLE
Incremental improvement in random module docstrings

### PR DESCRIPTION
**Pull request by gmcastil**
I've worked through some more of the random module docstrings to make them more consistent and standardized.  The return values for some functions were missing or in a couple of cases, incorrect with respect to the actual behavior.  In keeping with the description of the `size` parameter that @gdementen proposed, I would like to suggest a similar type of return definition, where applicable::

```
    Returns
    -------
    samples : ndarray or scalar
        The drawn samples, of shape ``(m, n, k)``.
```

If this looks good, I'll continue working through the module and try to make it more consistent.  Thanks.

### CODE REVIEW

**Comment by jaimefrio** [comment]
I find it more confusing that helpful. In the context of the description of the `size` parameter it makes sense to stick with the example given there. But on a different argument in a different section of the docstring, I don't quite see it working.

Also, for `multivariate_normal` and `multinomial`, the extra dimension coming out of the blue without an explanation seems confusing to me. I like the longer explanation in `size` much better.

**Comment by gmcastil** [comment]
Thanks for the feedback Jaime, I'll revise the PR accordingly.

**Comment by charris** [comment]
@gmcastil Should I close this now that you have another PR up?

**Comment by gmcastil** [comment]
Yes.  PR #5685 is a replacement for this.  Seems to have had some trouble with Travis-CI, but I don't think that's an issue with the PR.  Thanks @charris.

**Comment by charris** [comment]
OK, closing.

**Pull request closed without merging**
