### PR TITLE
DOC: Fix Typo (Wrong argument name)

### LINKED ISSUE #10244: BUG: wrong or typo in signature for np.fromiter
gen = (0 for _ in range(3)
np.fromiter(iterable=gen,dtype='int') # fails
np.fromiter(iter=gen,dtype='int') # works

signature in docs and in core.multiarray declared as iterable

np.__version__
Out[8]: '1.13.3'

### PR DESCRIPTION
**Pull request by archsyscall**
Fixes #10244

### CODE REVIEW

**Comment by eric-wieser** [comment]
This conflicts with #10253, which corrects the implementation to match the docs instead.

**Comment by mattip** [comment]
@eric-wieser do you have a preference for this vs. gh-10253? This does seem like a simpler approach.

**Comment by charris** [comment]
@mattip @eric-wieser I prefer this to #10253.

**Comment by charris** [comment]
@eric-wieser @mattip I also prefer this as a minimal fix.

**Comment by eric-wieser** [comment]
I like the idea of changing the argument name for consistency with other python functions as in the other PR, but it may not be worth the reviewing effort vs this very simple fix. Perhaps instead of attempting to rename it, we should look at making these sorts of argument positional-only in future.

**Comment by charris** [comment]
> we should look at making these sorts of argument positional-only in future; 

That would certainly uncomplicate things. Would making that change be backward compatible? That is, if someone was so unfortunate as to have actually used the name, would it still work?

**Comment by charris** [comment]
I'm going to put this in. If it causes a conflict it should be easy to fix and there is no need to wait on a large resolution.

**Comment by charris** [comment]
Thanks @marload .

**Pull request merged**
