### PR TITLE
REL: Fix outdated docs link

### LINKED ISSUE #16018: Docs link is outdated on PyPI
https://github.com/numpy/numpy/blob/1d598997543637b9882d1663117b573210a20583/setup.py#L439

I assume we should be using a `numpy.org` link here, possibly derived from the version number?

### PR DESCRIPTION
**Pull request by eric-wieser**
Closes #16018

### CODE REVIEW

**Comment by eric-wieser** [comment]
@mattip proposed we just link to stable instead. We should make sure we do one of these things before 1.19.1. It probably doesn't matter for the `.0` release.

**Comment by mattip** [comment]
I think linking to the version is better than stable, thanks. Is it too late to backport this to 1.19?

**Comment by charris** [comment]
> Is it too late to backport this to 1.19

Too late for 1.19.0, I had to draw the line somewhere. Just mark it for 1.19.1, there will be more releases in the series.

**Comment by mattip** [comment]
Thanks @eric-wieser

**Pull request merged**
