### PR TITLE
Update README.md  (Append Installation - details/steps)

### PR DESCRIPTION
**Pull request by pujaji**
Prefix Installation steps before the testing steps as Installation is the very first step to dig in NumPy.
Various and detailed steps be appended once approved.

### CODE REVIEW

**Comment by mattip** [comment]
Information that is found elsewhere should not be duplicated. There are already links for more information. If there is anything to change here, perhaps the text could be replaced with links to the [testing documentation](http://www.numpy.org/devdocs/reference/testing.html), and the [what is numpy page](http://www.numpy.org/devdocs/user/whatisnumpy.html), but my inclination is to leave the README alone.

**Comment by pujaji** [comment]
Sure Matti.

This is Pujitha Jaji(Pronouns - Her/She) from India.
I am an Outreachy Internship Aspirant.I am delighted to be part of NumPy
Community.I am exploring all the things right now.I have used Numpyin
couple of my projects.I can't wait to kick start my work.Could you please
suggest how to dig-in

**Comment by mattip** [comment]
Please reach to me via the mail on my [github page](https://github.com/mattip) for some ideas

**Comment by mattip** [comment]
Closing. Hopefully @pujaji will find a way to contribute in another PR. If not we can reopen this.

**Pull request closed without merging**
