### PR TITLE
REL: Update master after 1.20.0 release.

### PR DESCRIPTION
**Pull request by charris**

### CODE REVIEW

**Comment by mattip** [comment]
@charris thanks. 
Is the doc update on the TODO list?:
- copy the 1.20 docs to the repo https://github.com/numpy/doc
- move the `stable` symlink to the 1.20 directory

**Comment by charris** [comment]
> Is the doc update on the TODO list?:

It is, but `make dist` fails in the 1.20.x branch with `cythonize` problems, so I've put it on hold until I can deal with it. Not sure why `runtests` works and `make dist` fails though. I'm hoping that a backport of #18144 will fix things.

**Comment by charris** [comment]
Problem seems to have been due to two installs of Python3.9 after I upgraded the system Jan 5, one in `/usr/lib` the other in `/usr/local/lib`.

**Comment by charris** [comment]
Lot of oddball fonts needed that will take a while to track down and install.

**Comment by charris** [comment]
Documentation up.

**Comment by mattip** [comment]
Thanks @charris

**Pull request merged**
