### PR TITLE
 DOC: Add datetime64 example for 'Now' to get the current time

### PR DESCRIPTION
**Pull request by Shreyjaradi**

### CODE REVIEW

**Comment by mattip** [comment]
This fails doctests. You should add a `+SKIP` directive, like here https://github.com/numpy/numpy/blob/fba4fc16a26e77ec4ce2b1900577f088b1d5a7a6/doc/source/reference/random/index.rst?plain=1#L26

```
File "/tmp/tmpeo8sv853/doc/source/reference/arrays.datetime.rst", line 93, in doc/source/reference/arrays.datetime.rst
Failed example:
    np.datetime64('now', 'ms')
Expected:
    numpy.datetime64('2024-05-18T18:02:42.000')
Got:
    np.datetime64('2024-05-18T18:58:30.000')
```

**Comment by Shreyjaradi** [comment]
@mattip I have made the changes, this is my first open source contribution at PyCon US 2024 Pittsburgh.

**Comment by Shreyjaradi** [comment]
@mattip , Can we close this ?

**Comment by rossbar** [comment]
Just FYI, it's always a good idea to submit features on a branch other than your `main` branch - one reason why is that maintainers often push minor suggestions to the PR to make things quicker; however this is not possible for PRs that originate from the `main` branch on your fork. Just a little nugget for next time!

I will go ahead and close as requested!

**Comment by Shreyjaradi** [comment]
Thank you so much. I will keep this in mind for the future. Thank you so
much.

**Comment by MattFisher** [comment]
@rossbar I think maybe @Shreyjaradi meant "Can we _merge_ this?" ?

Issue #10003 is still open and the "now" and "today" strings remain undocumented.
I came across the problem and [started implementing a fix](https://github.com/MattFisher/numpy/commit/8c89fbc761e296283cdbddbbd08abb86e20ac4dc) before I found this PR.

**Pull request closed without merging**
