### PR TITLE
DOC: Using ``f2py`` with ``fypp``

### PR DESCRIPTION
**Pull request by HaoZeke**
This is a documentation update. It also serves as a concrete guide to move away from the earlier `.src` based approaches to handling bindings.

### CODE REVIEW

**Comment by mattip** [comment]
About all I can say is that it seems to [build correctly](https://output.circle-artifacts.com/output/job/fc6a766e-256a-430a-a029-2f0f0af1bdd8/artifacts/0/doc/build/html/f2py/f2py-reference.html). Who do you think could review this?

**Comment by charris** [comment]
@HaoZeke Could you try rebasing on current main? I'm curious to see if the failing test is fixed.

**Comment by charris** [comment]
I am not too bothered about review, but would like to know why the macos_arm64 test is failing.

**Comment by HaoZeke** [comment]
> I am not too bothered about review, but would like to know why the macos_arm64 test is failing.

That's an odd one (reproducing here for posterity):

```bash
        I_mat = np.identity(q1.shape[-1])
        stack_I_mat = np.broadcast_to(I_mat,
                        q1.shape[:-2] + (q1.shape[-1],)*2)
>       assert_almost_equal(matmul(swapaxes(q1, -1, -2).conj(), q1),
                            stack_I_mat)
E       RuntimeWarning: invalid value encountered in matmul

I_mat      = array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
a          = array([[[[[ 0.47237268,  1.8584886 , -1.360483  ,  0.7482736 ],
          [ 0.11829849,  0.3338246 ,  0.8019968 , -0.2...65, -2.067151  , -0.05085188],
          [ 1.0249805 , -0.4747382 , -1.2114884 ,  0.24656454]]]]],
      dtype=float32)
a_dtype    = dtype('float32')
a_type     = <class 'numpy.ndarray'>
k          = 4
m          = 4
n          = 4
q          = array([[[[[-8.70491147e-01,  3.65809113e-01,  3.26250196e-01,
           -4.46061119e-02],
          [-2.18001142e-01,...940e-01],
          [-4.83443618e-01, -2.01184243e-01, -4.96693671e-01,
            6.92172348e-01]]]]], dtype=float32)
q1         = array([[[[[-8.70491147e-01,  3.65809113e-01,  3.26250196e-01,
           -4.46061119e-02],
          [-2.18001142e-01,...940e-01],
          [-4.83443618e-01, -2.01184243e-01, -4.96693671e-01,
            6.92172348e-01]]]]], dtype=float32)
r          = array([[[[[-0.54265076, -1.2356775 ,  1.289212  , -0.30365175],
          [ 0.        ,  2.1400294 ,  0.68829364,  0.4...  ,  2.3928301 ,  0.5438449 ],
          [ 0.        ,  0.        ,  0.        , -0.42238984]]]]],
      dtype=float32)
r1         = array([[[[[-0.54265076, -1.2356775 ,  1.289212  , -0.30365175],
          [ 0.        ,  2.1400294 ,  0.68829364,  0.4...  ,  2.3928301 ,  0.5438449 ],
          [ 0.        ,  0.        ,  0.        , -0.42238984]]]]],
      dtype=float32)
self       = <numpy.matrixlib.tests.test_matrix_linalg.TestQRMatrix object at 0x123f30c50>
stack_I_mat = array([[[[[1., 0., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 0., 1.]],

    ...],

         [[1., 0., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 0., 1.]]]]])

numpy/linalg/tests/test_linalg.py:1789: RuntimeWarning
=========================== short test summary info ============================
FAILED numpy/matrixlib/tests/test_matrix_linalg.py::TestQRMatrix::test_stacked_inputs[float32-outer_size2-size2] - RuntimeWarning: invalid value encountered in matmul
===== 1 failed, 40395 passed, 216 skipped, 50 xfailed, 3 xpassed in 56.34s =====
```

Doesn't seem to have anything to do with this PR though..

**Comment by charris** [comment]
> Doesn't seem to have anything to do with this PR though..

No, it doesn't. But it doesn't occur in main, which is why I asked for the rebase to make sure. I suspect you haven't kept main updated from upstream ...

**Pull request merged**
