### PR TITLE
ENH: Bump Highway to HEAD and remove platform filter

### PR DESCRIPTION
**Pull request by Mousius**
This results in a pretty nice boost on the effected platforms :smile_cat:

[wheel build]

### CODE REVIEW

**Review by seiko2plus — COMMENTED** [review]
LGTM, but I think it's better to test it against the `CI/wheel build` before it gets merged. I added the wheel build label, but it seems close/reopening the pr is required.

**Comment by seiko2plus** [comment]
close/reopen let's see!

**Comment by rgommers** [comment]
The failures seem unrelated. The macOS x86-64 wheel builds are failing on `delocate` not finding OpenBLAS. @mattip due to another change in `openblas-libs` perhaps?

**Comment by mattip** [comment]
The macos wheel failures are unrelated, for instance the [scheduled build](https://github.com/numpy/numpy/actions/runs/8678002071) from a few days ago is also failing. I will investigate.

**Comment by rgommers** [comment]
Thanks @mattip.

Let's hold off on merging for a bit here. While the failures are unrelated, they prevent running the macOS arm64 tests that we wanted to double check with this Highway change.

**Comment by Mousius** [comment]
> @Mousius to retest, the new commit should again have `[wheel build]` in the first line of the commit message.

I felt so happy that I got this running before I left this morning 😸 I've updated it..

**Review by rgommers — APPROVED** [review]
All green now, let's give it a go - thanks @Mousius!

**Pull request merged**
