### PR TITLE
DOC: Pull existing PR workflow

### PR DESCRIPTION
**Pull request by ganesh-k13**
### Changes
Doc on how to pull changes from old PR.

I'm not sure if this is a regular use case and hopefully it doesn't clutter the doc, please feel free to close it if it's too much info for NumPy docs.

Ref: https://stackoverflow.com/a/30584951/5671364

PS: I wasted some 15 mins trying to pull from `origin` instead of `upstream` and thought it might help someone if it's in the docs.

### CODE REVIEW

**Comment by melissawm** [comment]
I know we may not want to sanction specific tools but this is very easily done with the GitHub CLI interface:

Screenshot 2023-01-02 at 10 08 05 AM

May be worth mentioning it as an alternative?

**Comment by ganesh-k13** [comment]
Yeah, that's a good way to pull as well, I'll add it.

**Review by rossbar — COMMENTED** [review]
Here's my two cents: there are at least three ways to do this:
 1. Explicitly add a remote (e.g. `git add remote GH-NAME FORK-URL` and `git checkout --track GH-NAME BRANCH`)
 2. Pull the changes down from the branch the PR targets, as proposed here
 3. Use the gh cli as suggested above.

None of them is perfect. I personally always go with (1) as it then means I can easily grab future changes from the same user (even though it's more typing up front). (2) is nice because it gets rid of the need to create the remote, but I personally find the exact incantation hard to remember (hence the proposed documentation here!). (3) of course fixes both of these problems, but requires developers to install another tool, albeit one with growing popularity.

In the end I don't have a strong opinion on this. On the one hand I feel like the *most* correct thing to do is leave this for git/github specific docs (which is where most users would land anyways via a search engine). OTOH I'm not strongly against excluding the info as some might find it useful, though YMMV on how valuable all of the workflow instructions are in the developer docs.

**Comment by rossbar** [comment]
This was discussed at the docs meeting, and Sebastian raised another good point: both options 2) and 3) assume that the user's upstream remote is set up with ssh and *not* https, otherwise pushing to the PR is blocked by default.

The results of the wider discussion were that no one feels too strongly about this one, but it would be good to reference github docs here instead if possible.

**Comment by rossbar** [comment]
Unfortunately, it seems the GitHub documentation on this topic is not very good. I landed on [this article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork) from a quick search. The topic is correct, but this is not the best way to do this.

**Review by rossbar — APPROVED** [review]
No sense in letting this sit - it's useful info and there isn't an obvious alternative so let's get it in. If anyone finds a better resource in the GitHub docs it'd be great to link to it!

**Pull request merged**
