### PR TITLE
TST: Fix running tests under Tox, add Python 3.4 to Tox environments

### PR DESCRIPTION
**Pull request by moreati**
This PR
- Adds the sub-package `numpy.build_utils` to distributions created with distutils/setuptools. This matches the packages included in distributions created with Bento. Without this sub-package all tox builds fail with a traceback including `ImportError: No module named build_utils.apple_accelerate`
- Enables Python 3.4 test environments in Tox, to match `.travis.yml`

### CODE REVIEW

**Comment by charris** [comment]
LGTM, but I am not a tox user. If there is a tox user, please take a look.

**Comment by njsmith** [comment]
The tox part seems fine (and trivial) to me, but I'd like to hear from someone about this `numpy.build_utils` thing, since that part potentially has some (tiny) effect on our exposed api surface. Is it just a bug that we've been leaving it out of our sdists, and it's actually necessary to build numpy? Or what is it?

**Comment by moreati** [comment]
`numpy.build_utils` is not necessary to build numpy 1.9.2 (current version on PyPI). It is necessary to build current HEAD, and (so far unreleased) 1.11.0. Maybe also 1.10.x as well.

```
alex@martha:/tmp$ git clone git@github.com:numpy/numpy.git
...
alex@martha:/tmp$ cd numpy/
alex@martha:/tmp/numpy$ git submodule init
...
alex@martha:/tmp/numpy$ git submodule update
...
alex@martha:/tmp/numpy$ python setup.py sdist
Running from numpy source directory.
...
creating dist
Creating tar archive
removing 'numpy-1.11.0.dev0+9cd868a' (and everything under it)
alex@martha:/tmp/numpy$ ls dist/
numpy-1.11.0.dev0+9cd868a.tar.gz
alex@martha:/tmp/numpy$ cd ../
alex@martha:/tmp$ tar xf numpy/dist/numpy-1.11.0.dev0+9cd868a.tar.gz 
alex@martha:/tmp$ cd numpy-1.11.0.dev0+9cd868a/
alex@martha:/tmp/numpy-1.11.0.dev0+9cd868a$ ls numpy/build_utils
ls: cannot access numpy/build_utils: No such file or directory
alex@martha:/tmp/numpy-1.11.0.dev0+9cd868a$ python setup.py install
Running from numpy source directory.
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
non-existing path in 'numpy/distutils': 'site.cfg'
F2PY Version 2
Traceback (most recent call last):
  File "setup.py", line 252, in <module>
    setup_package()
  File "setup.py", line 244, in setup_package
    setup(**metadata)
  File "/tmp/numpy-1.11.0.dev0+9cd868a/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 148, in configuration
    config.add_subpackage('numpy')
  File "/tmp/numpy-1.11.0.dev0+9cd868a/numpy/distutils/misc_util.py", line 1001, in add_subpackage
    caller_level = 2)
  File "/tmp/numpy-1.11.0.dev0+9cd868a/numpy/distutils/misc_util.py", line 970, in get_subpackage
    caller_level = caller_level + 1)
  File "/tmp/numpy-1.11.0.dev0+9cd868a/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 11, in configuration
    config.add_subpackage('core')
  File "/tmp/numpy-1.11.0.dev0+9cd868a/numpy/distutils/misc_util.py", line 1001, in add_subpackage
    caller_level = 2)
  File "/tmp/numpy-1.11.0.dev0+9cd868a/numpy/distutils/misc_util.py", line 970, in get_subpackage
    caller_level = caller_level + 1)
  File "/tmp/numpy-1.11.0.dev0+9cd868a/numpy/distutils/misc_util.py", line 882, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "numpy/core/setup.py", line 13, in <module>
    from numpy.build_utils.apple_accelerate import uses_accelerate_framework, get_sgemv_fix
ImportError: No module named build_utils.apple_accelerate
```

**Comment by juliantaylor** [comment]
looks correct to me to add it, given the use of it in the build.
@charris this then also needs to go into 1.10 for its sdist tarball to work

**Comment by juliantaylor** [comment]
on second though, this also installs it.
It should be enough to add build_utils to MANIFEST

**Comment by njsmith** [comment]
If it's intended to be used by the build but not distributed, then it
should probably not be in the numpy/ namespace...

**Comment by moreati** [comment]
The same does apply to the 1.10.x branch.  Two options I see
1. Eliminate the requirement for `numpy.build_utils` in any build process, and *remove* it from Bento distributions.
or
2. Add `numpy.build_utils` to distutils distributions

```
alex@martha:/tmp$ cd numpy
alex@martha:/tmp/numpy$ python setup.py clean
running clean
alex@martha:/tmp/numpy$ git checkout maintenance/1.10.x 
Branch maintenance/1.10.x set up to track remote branch maintenance/1.10.x from origin.
Switched to a new branch 'maintenance/1.10.x'
alex@martha:/tmp/numpy$ python setup.py sdist
Running from numpy source directory.
Cythonizing sources
...
Creating tar archive
removing 'numpy-1.10.0.dev0+3a47516' (and everything under it)
alex@martha:/tmp/numpy$ cd ../
alex@martha:/tmp$ tar xf numpy/dist/numpy-1.10.0.dev0+3a47516.tar.gz 
alex@martha:/tmp$ cd numpy-1.10.0.dev0+3a47516/
alex@martha:/tmp/numpy-1.10.0.dev0+3a47516$ python setup.py install
Running from numpy source directory.
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
non-existing path in 'numpy/distutils': 'site.cfg'
F2PY Version 2
Traceback (most recent call last):
  File "setup.py", line 252, in <module>
    setup_package()
  File "setup.py", line 244, in setup_package
    setup(**metadata)
  File "/tmp/numpy-1.10.0.dev0+3a47516/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 148, in configuration
    config.add_subpackage('numpy')
  File "/tmp/numpy-1.10.0.dev0+3a47516/numpy/distutils/misc_util.py", line 1001, in add_subpackage
    caller_level = 2)
  File "/tmp/numpy-1.10.0.dev0+3a47516/numpy/distutils/misc_util.py", line 970, in get_subpackage
    caller_level = caller_level + 1)
  File "/tmp/numpy-1.10.0.dev0+3a47516/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 11, in configuration
    config.add_subpackage('core')
  File "/tmp/numpy-1.10.0.dev0+3a47516/numpy/distutils/misc_util.py", line 1001, in add_subpackage
    caller_level = 2)
  File "/tmp/numpy-1.10.0.dev0+3a47516/numpy/distutils/misc_util.py", line 970, in get_subpackage
    caller_level = caller_level + 1)
  File "/tmp/numpy-1.10.0.dev0+3a47516/numpy/distutils/misc_util.py", line 882, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "numpy/core/setup.py", line 13, in <module>
    from numpy.build_utils.apple_accelerate import uses_accelerate_framework, get_sgemv_fix
ImportError: No module named build_utils.apple_accelerate
```

**Comment by juliantaylor** [comment]
@njsmith has a point that it probably should not be in numpy/, maybe in tools or at the top level?
but regardless where it is placed using MANIFEST.in to have it in the tarball and not install it works for me

**Comment by rgommers** [comment]
Additionally to not installing, we should underscore it. Otherwise it's still visible for in-place builds.

**Comment by charris** [comment]
So is the consensus that `build_utils.py` should be prefixed with an underscore, moved into the `tools` directory, and be included in  `MANIFEST.in`?

**Comment by njsmith** [comment]
I think it's, either move to tools/, or else, prefix with an underscore?
(I'd prefer moving to tools/ but am fine with either.)

**Comment by rgommers** [comment]
Don't move it to ``tools/``, then you can't import it during build anymore. ``import numpy._build_utils`` is fine; there's no ``tools/__init__.py``.

**Comment by charris** [comment]
So, rename `build_utils` to `_build_utils`, and modify all the places it is referenced. no need to use add_subpackage in  numpy/setup.py, and add `recursive-include numpy/_build_utils *` to MANIFEST.in?

**Comment by moreati** [comment]
@charris I'm confused. I thought the consensus was
1. Rename `numpy.build_utils` -> `numpy._build_utils` and update any references
2. Remove `config.add_subpackage('build_utils')` from `numpy/setup.py`
3. Add `recursive-include numpy/_build_utils *` to `MANIFEST.in`

Are you saying step 3 is unnecessary and/or undesirable?

**Comment by charris** [comment]
No, we are in complete agreement ;)

**Comment by njsmith** [comment]
Can we also get a big prominent comment someplace
(numpy/_build_utils/README perhaps?) warning that the _build_utils package
is only available from in-place builds and disappears from real installs?
It's pretty unusual and confusing to have this kind of discrepancy between
source tree and installed package...

**Comment by charris** [comment]
@moreati Thanks. I assume you have tested that this works for building.

**Comment by moreati** [comment]
Correct

**Pull request merged**
