### PR TITLE
CI: fix CIRRUS_TAG check when tagging. Closes #22730

### LINKED ISSUE #22730: Cirrus fails to upload wheels on tag push.
Manually running a build for the 1.24.0 branch does upload the correct wheels, but to the nightly repo. Rerunning the tagged build only reruns the upload, which fails because there are no wheels to upload.

### PR DESCRIPTION
**Pull request by andyfaff**
@charris

Closes #22730.

### CODE REVIEW

**Comment by charris** [comment]
Ah... looks reasonable :) The other thing that might be worth checking is that it uploads to the staging repo. I think that  should be the case for all maintenance branches.

**Comment by andyfaff** [comment]
As it stands the code should upload *any* tag that begins with v.

**Comment by charris** [comment]
> Do you want tags from main to go to nightly, and tags from maintenance branches to go to staging?

That would be good. Or you can just ignore tags on main.

**Comment by andyfaff** [comment]
Ok, now tags beginning with v and are on a maintenance branch get uploaded to staging (`IS_PUSH=true`). cron/manual builds will still get uploaded to nightly (`IS_SCHEDULE_DISPATCH=true`).

**Comment by charris** [comment]
Thanks Andrew.

**Comment by charris** [comment]
@andyfaff This didn't fix the problem, there was still no upload with the v1.24.0 tag push.

**Pull request merged**
