### PR TITLE
DOC: reformat top-level release index

### PR DESCRIPTION
**Pull request by mattip**
Build a table of content as the top-level release page rather than a concatenation of all the notes.

This PR has two commits, the first could be backported if desired, in case we wish to keep the LTS 1.16 branch more clearly documented (it still may need a merge)

Also removes an old file `doc/release/time_based_proposal.rst` that is no longer relevant

### CODE REVIEW

**Comment by mattip** [comment]
You can see the new page [here](https://8001-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/release.html), where it is now one long table-of-contents instead of a wall of text. I needed to move the release directory inside of `doc/source` to use the sphinx `toc` directive.

Perhaps the level should be limited to 1 instead of 3, but then we loose the ability to search for a particular concept on the page itself to answer questions like "when was X deprecated"

**Comment by charris** [comment]
I don't want to touch 52 files in a maintenance branch.

**Comment by charris** [comment]
I like this in general. The main question is how deep to make the contents and it would be good to gather some feedback on that. Maybe post on the mailing list?

**Comment by justbennet** [comment]
When I go to look at the release notes page, I think I'm either interested in the most recent release or two or in finding a particular bug/enhancement.  I think the ToC is a fine approach, but would it be hard to list the PRs merged for each release on the ToC page?  I think that would make the ToC more useful without increasing its bulk unduly.

With or without that enhancement, I like this approach.  For traditionalists, could the current format be made available as an alternate link?

**Comment by charris** [comment]
>but would it be hard to list the PRs merged for each release on the ToC page?but would it be hard to list the PRs merged for each release on the ToC page?

We used to include that in the release notes, but with ~500 PRs merged in the initial releases it just cluttered things up. We do keep lists of merged commits in the `doc/changelog/`, but it was decided not to include those in the documentation. The lists for each release can also be found at the github release site as downloadable files.

**Comment by justbennet** [comment]
Thanks, Charles.  I was going by those listed in the few entries I scanned on the test page, where only a few were listed.  Yes, if it ends up being a huge list, it would be inappropriate for the abbreviated page.

For whatever one vote is worth, this seems a good idea to me, and the current depth seems fine.  

If a header paragraph that points to the various, more complete lists could be added for the benefit of people new to the project and unfamiliar with the conventions, that might be a nice addition, but the proposed format and contents are fine.

**Pull request merged**
