### PR TITLE
TST: Re-enable int8/uint8 einsum tests

### PR DESCRIPTION
**Pull request by JuliaPoo**
It seems #24732 fixed itself, see the following CI runs:
- [macOS intel](github.com/JuliaPoo/numpy/actions/runs/9344912430/job/25716839862)
- [windows clang-cl](github.com/JuliaPoo/numpy/actions/runs/9344767573/job/25716459859)

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
That's good news:) Thanks for the PR @JuliaPoo. 

Could you please also clean up the definition of `USING_CLANG_CL` near the top of the file, since it's no longer used?

Also, let's make doubly sure it's gone everywhere - when making that change, could you add `[wheel build]` to the first line of the commit message? That triggers a full set of wheel builds; those can have different compile flags, so it's useful to check.

I don't really mind not knowing what fixed it - could be changed to SIMD code, move to C17, type promotion changes, a change in the compilers, or just some random fix somewhere.

**Comment by mattip** [comment]
There is a similar code pattern in scalar math's [`test_shift_all_bits`](https://github.com/numpy/numpy/blob/29409dc098b1b6c1e5dbd343b2fd250af9195ead/numpy/_core/tests/test_scalarmath.py#L806). It might be nice to check if that passes now too, perhaps in a separate PR.

**Comment by mattip** [comment]
No need to wait for the PyPy wheel build. LGTM.

**Comment by mattip** [comment]
Thanks @JuliaPoo

**Pull request merged**
