### PR TITLE
DEP: Deprecate the event argument to datetime types, which is ignored since 1.7.0

### PR DESCRIPTION
**Pull request by eric-wieser**
This argument was ignored since cb45456 - it's long time we started telling people not to pass it.

### CODE REVIEW

**Comment by charris** [comment]
Two failing tests for pickling, otherwise lgtm.

**Comment by eric-wieser** [comment]
Seems like the right thing to do is simply squash the warnings in the tests? Loading pickles from 1.6 that have an `event` is just as bad a thing to do as creating a new one.

**Comment by charris** [comment]
I don't mind the 1.6 warning, but why are we getting it here? Isn't `event` set to `None` as the message suggests? That seems to imply that it is being passed incorrectly to the pickle, or the deprecation is missing a check.

**Comment by eric-wieser** [comment]
Ok, the problem here is that 1.6 is only able to read a pickle file that contains the deprecated 4-tuple, so 1.13 currently saves those extra two entries (`(unit, num, 1, 1)`) even though they're not needed. So when loading a pickle file, we hit the warning

So that leaves only two options:

* Don't warn when `1` is passed as the `event`, which catches the pickle case
* Break compatibility, and make 1.6 unable to load pickle files from 1.14. Does this work anyway? It's not something our unit tests would pick up.

**Comment by charris** [comment]
Hmm, what is the meaning of `1` as an event in this context? I have mixed feelings here, 1.6 is getting pretty old, even scipy doesn't support it any more, and I can't see anyone running 1.6 needing pickes created by 1.14. However, it does seem that 1.14 will generate warnings when loading pickles from earlier versions of Numpy, which is probably a bigger problem. So I am inclined to just ignore `1`, at least for the time being, and start using None instead. If there was a way to detect pickles, that would be lovely, but I can't think of any that wouldn't be excessively ugly.

**Comment by eric-wieser** [comment]
> and start using None instead.

You mean in the pickles? Note that this also breaks compatibility with 1.6, which expects an integer here

**Comment by eric-wieser** [comment]
From [the NEP](), event means (my wording) _"there are `event` integer values before moving to the next time unit"_. A descriptor of `("ms", 1, 1, 5)` would interpret the number 12 as _"the second event at 2ms"_.

So maybe we should require it to be 1 instead of `None`, but the latter is a better indication that the feature is no more.

**Comment by charris** [comment]
I'm not overly worried about 1.6, although we can ask for a second opinion. @rgommers Thoughts?

**Comment by charris** [comment]
> So maybe we should require it to be 1 instead of None

I would be fine with that also if it looks the best way to go.

**Comment by eric-wieser** [comment]
> . If there was a way to detect pickles, that would be lovely, but I can't think of any that wouldn't be excessively ugly.

Actually, it's super easy - there are two call sites for this function, and one of them is from pickle - so we can just add a boolean flag indicating which behaviour to use.

So now:

* When writing python, pass `None` explicitly
* When loading old pickle files:
  * If `event == 1`, succeed as before
  * Otherwise, raise a `UserWarning`, but keep discarding the data and assuming everything is fine, like we have been doing for a while

**Comment by charris** [comment]
Thanks Eric.

**Comment by eric-wieser** [comment]
Oops, this missed a release note. On the other hand, this behavior was supposedly deprecated a long time ago anyway...

**Comment by charris** [comment]
OK, added a `needs release note` tag.

**Comment by eric-wieser** [comment]
Am I doing the right thing in also using that tag on open PRs that need release notes before merging?

**Comment by charris** [comment]
Yes, my use here is a fresh innovation but should serve. I do remove the tag when the release note shows up.

**Pull request merged**
