### PR TITLE
TST: add pypy3.7

### PR DESCRIPTION
**Pull request by mattip**
Add a PyPy3.7 build job

@charris which github action labels could be improved?

### CODE REVIEW

**Comment by mattip** [comment]
hmm "use_wheel" with `NPY_RELAXED_STRIDES_DEBUG 1, DOWNLOAD_OPENBLAS 1` failed again. I wonder if something is off?

**Comment by mattip** [comment]
merging to progress on MacPython/numpy-wheels#103

**Comment by mattip** [comment]
We can back this out it if proves flaky

**Comment by charris** [comment]
> which github action labels could be improved?

I was thinking of the labels displayed here for the different tests, "full", etc.

**Comment by mattip** [comment]
I am notoriously bad at names. Suggestions welcome.

**Pull request merged**
