### PR TITLE
BUG: pull request related to the issue #7353

### PR DESCRIPTION
**Pull request by chiffa**
@njsmith 

Related discussions: #7357 #7354, #7353.

would also be need to pushed to maintenance branches for 1.10 and 1.11

### CODE REVIEW

**Comment by charris** [comment]
Please take a look at `doc/source/dev/gitwash/development_workflow.rst` for the preferred way to write commit messages and try to make them more informative and specific.

**Comment by chiffa** [comment]
I corrected a bug and added a test that would detect if it arrose, which would warrant TST and BUG headers. Should I make two separate commits or just one?

**Comment by charris** [comment]
One for each would be fine.

**Comment by charris** [comment]
And you will need to do a force push `git push --force origin <your branch>`.

**Comment by chiffa** [comment]
Should be good now. Should I send a mail to the numpy mailing list as specified in the `doc/source/dev/gitwash/development_workflow.rst` or should it be ok?

**Comment by charris** [comment]
No, but it is a good idea to make a comment here as github doesn't notify on changes.

**Comment by charris** [comment]
You should also keep the commit message lines under 72 characters. I note that your messages do not have line breaks, which are also needed. It is probably possible to set up your editor to recognize a commit is being made and do that for you. What editor do you use?

**Comment by chiffa** [comment]
pycharm right away (already does it), nano when I was rebasing

**Comment by chiffa** [comment]
Not sure to understand about line breaks: I separated comment from title with two line breaks is there is more to it I am not aware of?

**Comment by charris** [comment]
I don't think you can configure nano for git commits, but I may be wrong. Anyway, the first line of the summary is 110 characters long.

**Comment by charris** [comment]
You might be able to see it with `git log` if your terminal is wide.

**Comment by chiffa** [comment]
The second commit - yes, it is a bit too long. Should I go ahead and reword it?

**Comment by charris** [comment]
Yep ;)

**Comment by chiffa** [comment]
Correct now!

**Comment by charris** [comment]
Looks good. I'll leave it to @njsmith to put it in, thanks for your patience.

**Comment by chiffa** [comment]
Sure! Thanks for your guidance: I have a better understanding of git and GitHub now!

**Comment by njsmith** [comment]
Thanks @charris for working through that -- and thanks @chiffa for your patience :-). Everything looks good to me now, and tests are passing, so I think we're good to go!

**Comment by WeatherGod** [comment]
I don't think this PR fixed everything. I am still having this problem despite having a fairly recent numpy installed:
```
>>> np.__version__
'1.12.0.dev0+e62aa19'
>>> a = np.ones((10, 13))
>>> b = np.pad(a, ((4, 5), (2, 4)), 'constant', constant_values=((0.0, 0.0), (0.0, 0.0)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/numpy-1.12.0.dev0+e62aa19-py2.7-linux-x86_64.egg/numpy/lib/arraypad.py", line 1357, in pad
    cast_to_int=False)
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/numpy-1.12.0.dev0+e62aa19-py2.7-linux-x86_64.egg/numpy/lib/arraypad.py", line 1069, in _normalize_shape
    return tuple(tuple(axis) for axis in arr.tolist())
AttributeError: 'tuple' object has no attribute 'tolist'
```
I honestly can not figure out how this is even possible.

**Comment by WeatherGod** [comment]
The test fails for me as well, both on my development build, and for v1.11.0 installed via conda.

**Comment by WeatherGod** [comment]
clarification, if I run the commands that are in the provided tests, it fails with the same exception. I am currently trying out the test suite via `np.test()`.

**Comment by WeatherGod** [comment]
The test suite passes when run by `np.test()`. Something strange is going on here. Are we sure that this test is getting included in the test suite?

**Comment by WeatherGod** [comment]
Running `np.lib.test('full')` passes (except for one error that is unrelated to this issue).

**Comment by WeatherGod** [comment]
Just tried debugging this on my dev build, and everything works after the reinstall from source. Strange, but I'll chaulk that up to something strange with my environment.

Looking carefully at the v1.11.0 source, it does not appear that this fix was ever backported into that branch, despite having been merged to master in February. Should this get backported?

**Comment by chiffa** [comment]
@WeatherGod: Both the test and the the correction were merged to master. I am not sure if they were backported to 1.10 and 1.11 as I've suggested in my initial message, but I am completely unsure of the procedures that numpy core team has in place in order to backport bugfixes to other branches.

**Comment by charris** [comment]
I just backported it to 1.11. There will be no more 1.10 releases.

**Comment by WeatherGod** [comment]
Awesome, thanks!

**Pull request merged**
