### PR TITLE
BUG: fix link issue with lapack_lite module. See #12799

### LINKED ISSUE #12799: -shared flag missing from gfortran link line of lapack_lite numpy v1.16.0, fedora 28, python 2.7.15
I am having a build failure during linking of `lapack_lite` module. The `-shared` flag is not included in the link line, and the linker is looking for a `main` function. I am compiling against a Python in a non-system location, and am also setting various build flags through the environment. None the less, the `-shared` flag should be added in the numpy configuration.

### Reproducing code example:
```bash
$ 'env' 'CC=/usr/lib64/ccache/gcc' 'CXX=/usr/lib64/ccache/g++' 'CPPFLAGS= -I/work/apps/teca-deps/2.1.3/include' 'CFLAGS=-I/work/apps/teca-deps/2.1.3/include  -O3 -march=native -mtune=native -DNDEBUG' 'CXXFLAGS=-I/work/apps/teca-deps/2.1.3/include  -O3 -march=native -mtune=native -DNDEBUG' 'LDFLAGS=-L//work/apps/teca-deps/2.1.3/lib -L/work/apps/teca-deps/2.1.3/lib64' 'LD_LIBRARY_PATH=/work/apps/teca-deps/2.1.3/lib/:/work/apps/teca-deps/2.1.3/lib64/:' 'DYLD_LIBRARY_PATH=/work/apps/teca-deps/2.1.3/lib/:/work/apps/teca-deps/2.1.3/lib64/:' 'PKG_CONFIG_PATH=/work/apps/teca-deps/2.1.3/lib/pkgconfig:/work/apps/teca-deps/2.1.3/lib64/pkgconfig:' 'PATH=.:/work/apps/teca-deps/2.1.3/bin/:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/bloring/.local/bin:/home/bloring/bin' 'PYTHONHOME=/work/apps/teca-deps/2.1.3' 'MPLBACKEND=Agg' 'PYTHONPATH=/work/apps/teca-deps/2.1.3/lib:/work/apps/teca-deps/2.1.3/lib/python2.7/site-packages/' '/work/apps/teca-deps/2.1.3/bin/python' 'setup.py' 'build' 'install' '--prefix=/work/apps/teca-deps/2.1.3'
```

### Error message:
```
building 'numpy.linalg.lapack_lite' extension
compiling C sources
C compiler: /usr/lib64/ccache/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/work/apps/teca-deps/2.1.3/include -O3 -march=native -mtune=native -DNDEBUG -I/work/apps/teca-deps/2.1.3/include -fPIC

creating build/temp.linux-x86_64-2.7/numpy/linalg
creating build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite
compile options: '-DNO_ATLAS_INFO=-1 -I/usr/include -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/work/apps/teca-deps/2.1.3/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/common -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/common -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -c'
gcc: numpy/linalg/lapack_litemodule.c
gcc: numpy/linalg/lapack_lite/python_xerbla.c
/usr/bin/gfortran -Wall -g -L//work/apps/teca-deps/2.1.3/lib -L/work/apps/teca-deps/2.1.3/lib64 build/temp.linux-x86_64-2.7/numpy/linalg/lapack_litemodule.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o -L/usr/lib64/atlas -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/work/apps/teca-deps/2.1.3/lib -Lbuild/temp.linux-x86_64-2.7 -ltatlas -ltatlas -ltatlas -ltatlas -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/numpy/linalg/lapack_lite.so
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -g -L//work/apps/teca-deps/2.1.3/lib -L/work/apps/teca-deps/2.1.3/lib64 build/temp.linux-x86_64-2.7/numpy/linalg/lapack_litemodule.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o -L/usr/lib64/atlas -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/work/apps/teca-deps/2.1.3/lib -Lbuild/temp.linux-x86_64-2.7 -ltatlas -ltatlas -ltatlas -ltatlas -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/numpy/linalg/lapack_lite.so" failed with exit status 1
```

### Numpy/Python version information:
This is a builld issue on v1.16.0 tag

### Proposed fix
```diff
diff --git a/numpy/distutils/fcompiler/gnu.py b/numpy/distutils/fcompiler/gnu.py
index 81769e562..b93b42c12 100644
--- a/numpy/distutils/fcompiler/gnu.py
+++ b/numpy/distutils/fcompiler/gnu.py
@@ -306,7 +306,7 @@ class Gnu95FCompiler(GnuFCompiler):
                           "-fno-second-underscore"] + _EXTRAFLAGS,
         'compiler_fix' : [None, "-Wall",  "-g","-ffixed-form",
                           "-fno-second-underscore"] + _EXTRAFLAGS,
-        'linker_so'    : ["<F90>", "-Wall", "-g"],
+        'linker_so'    : ["<F90>", "-Wall", "-g", "-shared"],
         'archiver'     : ["ar", "-cr"],
         'ranlib'       : ["ranlib"],
         'linker_exe'   : [None, "-Wall"]
```

### PR DESCRIPTION
**Pull request by burlen**
adds -shared to gfortran linker_so options
resolves #12799

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Just to clarify -- was your original use case working ok in NumPy `1.15.x` series, and broke when `1.16.0` became available?

**Comment by burlen** [comment]
We have been using numpy-1.11.2, however we had other issues on Fedora 28 with that release, and thus decided to go to the latest release to see if they were resolved

**Comment by tylerjereddy** [comment]
And you can't do something like `NPY_DISTUTILS_APPEND_FLAGS = 1` `LDFLAGS = -shared`? I suppose that might affect other things.

**Comment by burlen** [comment]
`LDFLAGS=-shared` breaks other parts of our build- numpy being just one of a number of dependencies built. I haven't tried `NPY_DISTUTILS_APPEND_FLAGS`

**Comment by burlen** [comment]
`NPY_DISTUTILS_APPEND_FLAGS = 1` does also fix the issue. very cool! Still I think it's a bug that the linker doesn't get the right flags. What do you think?

**Comment by tylerjereddy** [comment]
If your use case can be fixed by using `NPY_DISTUTILS_APPEND_FLAGS = 1` I'm guessing other devs will prefer that to changing long-standing `distutils` code.

I don't know the full history behind our linker flag append behavior, but it is only recently that this new environment variable has been supported I think.

I don't have strong views on this, so mostly just asking for details to paint the picture for other reviewers.

**Comment by burlen** [comment]
You're probably right, this flag may be needed only on Linux, and perhaps only on newer gfortan compiler? The azure build reports the following error, 
```
gfortran: error: -bundle not allowed with -dynamiclib
```

**Comment by charris** [comment]
> but not when compiling against Python installed in an arbitrary location.

Ah, that makes sense. The flags added by `get_flags_linker_so` for G95 are obtained from Python. Do you compile Python yourself? If so, it may be a configuration problem.

**Comment by charris** [comment]
I note that there is also a `g95.py` Fortran compiler that should maybe be removed.

**Pull request closed without merging**
