### PR TITLE
ENH: Include co-authors in changelog.

### LINKED ISSUE #18969: Script to generate contributor list for release note should pick up co-authors
Example commit: https://github.com/numpy/numpy/pull/18956/commits/eb231979b90cfe7f434bd598aefe4196df74b32e

It looks like the script does not pick up co-authors. The PRs at today's sprint mostly came from pairs of contributors, so we should ensure we fix this before the next release.

### PR DESCRIPTION
**Pull request by charris**
Closes #18969

### CODE REVIEW

**Comment by charris** [comment]
@rgommers You asked for it . . .

**Comment by charris** [comment]
We could also add reviewed-by if desired. I hope none of these are gamed (too much).

**Comment by rgommers** [comment]
That was fast - thanks Chuck!

This at first did not work for me, I got `stderr: 'b"error: unknown option `--group=trailer:co-authored-by' ...`. 

Full traceback for searchability:

```
$ python tools/changelog.py $GITHUB_TOKEN HEAD^^^^^^^^^^^^^^^^^^^^^^^^..HEAD 
Traceback (most recent call last):
  File "tools/changelog.py", line 162, in <module>
    main(args.token, args.revision_range)
  File "tools/changelog.py", line 124, in main
    authors = get_authors(revision_range)
  File "tools/changelog.py", line 71, in get_authors
    cur = this_repo.git.shortlog('-s', grp, revision_range)
  File "/Users/rgommers/mambaforge/envs/scipy-dev/lib/python3.8/site-packages/git/cmd.py", line 546, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/rgommers/mambaforge/envs/scipy-dev/lib/python3.8/site-packages/git/cmd.py", line 1020, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Users/rgommers/mambaforge/envs/scipy-dev/lib/python3.8/site-packages/git/cmd.py", line 831, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git shortlog -s --group=trailer:co-authored-by HEAD^^^^^^^^^^^^^^^^^^^^^^^^..HEAD
  stderr: 'b"error: unknown option `--group=trailer:co-authored-by'\nusage: git shortlog [<options>] [<revision-range>] [[--] [<path>...]]\n\n    -c, --committer       Group by committer rather than author\n    -n, --numbered        sort output according to the number of commits per author\n    -s, --summary         Suppress commit descriptions, only provides commit count\n    -e, --email           Show the email address of each author\n    -w[<w[,i1[,i2]]>]     Linewrap output\n"'
```

The reason is that the `--group` argument to `git shortlog` is very new, it was introduced in git 2.29.0 (Oct 2020). After an upgrade it works nicely though, it pick up 3 extra authors.

> We could also add reviewed-by if desired. I hope none of these are gamed (too much).

Probably less interesting, since reviewers are much more unlikely to be new contributors. And yeah, the gaming thing - luckily it's still rare:)

**Review by rgommers — APPROVED** [review]
Thanks @charris. In it goes.

**Comment by charris** [comment]
Looks like author and co-authored-by can be combined in a single call to shortlog
```
git shortlog -s --group=author --group=trailer:co-authored-by HEAD~10..HEAD
```
So this can be simplified even more.

**Pull request merged**
