### PR TITLE
BLD: Avoid using os.spawnve in favor of os.spawnv in exec_command

### PR DESCRIPTION
**Pull request by ales-erjavec**
The env modifying spawn\* function are not thread safe on windows (python issue6476) so avoid using them unless so requested by the caller.

This is a minimally intrusive fix for the segfaults reported in #7607

### CODE REVIEW

**Comment by charris** [comment]
This isn't my area. @njsmith @juliantaylor Thoughts?

**Comment by njsmith** [comment]
My concern is that this only makes _exec_command safe in some cases (no env), while adding more spaghetti to the code. Switching to subprocess or even to the thread-safe spawnve posted in the linked issue would simplify the code while making it actually threadsafe in all cases.

**Comment by ales-erjavec** [comment]
>  Switching to subprocess or even to the thread-safe spawnve posted in the linked issue would simplify the code while making it actually threadsafe in all cases.

Note that subprocess is not completely thread safe either, it just has different failure modes

* http://bugs.python.org/issue2320
* http://bugs.python.org/issue1336

The situation is greatly improved in Python >= 3.2 and there does exist a backported [subprocess32](https://pypi.python.org/pypi/subprocess32/).

I did start to work on replacing the exec_command, with subprocess, but considering that that would (probably) cause different bugs, I opted to make this simpler change (that can also be backported) first.

**Comment by njsmith** [comment]
I just audited the numpy codebase and there appear to be no uses of the `env`-setting feature of `exec_command`. @charris: what do you think about just making someone attempting to pass envvars to `exec_command` into an error. (The motivation is that the PR here fixes the non-env case but leaves the env case buggy, at the cost of a bunch of extra switches to special case env-versus-non-env; all that goes away if we rip out the env support.)

**Comment by ales-erjavec** [comment]
> A backward compatible option would be to define a new function to used in its place and deprecate the current function.

I think [subprocess.run](https://docs.python.org/3.5/library/subprocess.html#subprocess.run) introduced in Python 3.5 would be a candidate (interface-wise) to replace exec_command. It is a simple use of Popen's interface and matches the existing exec_command use pattern. It can be 'backported' to support older Python versions ([like this](https://gist.github.com/ales-erjavec/d88bff7208be46b3278e94625e4dbbb2#file-subprocess_compat-py-L101))

**Comment by njsmith** [comment]
Meh, this is a mess, in code that's already a mess, and whose long term trajectory is probably to be removed rather than fixed, so I think I'm changing my vote to just merging and moving on :-). Anyone object?

**Comment by charris** [comment]
@njsmith No, be my guest.

**Comment by njsmith** [comment]
Let's do this

**Comment by njsmith** [comment]
Thanks @ales-erjavec

**Pull request merged**
