### PR TITLE
MAINT: Add "noexcept" markers to Cython functions that do not raise exceptions

### PR DESCRIPTION
**Pull request by scoder**
This is needed for Cython 3.0 due to the new default exception propagation from C functions (https://github.com/cython/cython/issues/4280).

See https://github.com/cython/cython/issues/5359
See https://github.com/cython/cython/pull/5386#issuecomment-1517025929

`noexcept` is available since Cython 0.29.31.

### CODE REVIEW

**Comment by mattip** [comment]
Thanks. I wonder if we should try cython3.0 in one of the CI runs. Not necessarily as part of this PR, but it might be useful to keep things from breaking

**Comment by mattip** [comment]
We have two "baseline" runs: one on [github actions](https://github.com/numpy/numpy/blob/main/.github/workflows/build_test.yml#L48) and one [on azure](https://github.com/numpy/numpy/blob/9163e933df91b516b6f0c7a9ba8ad1750e642f37/azure-pipelines.yml#L58). One of them could use the latest 3.0 beta by doing a `pip install cython=???` after the `pip install -r *.txt` calls. I think this would be easier to do on the azure CI run.

**Comment by scoder** [comment]
The `arm7_simd_test` job seems to use an older version of Cython (< 0.29.31) that doesn't support `noexcept` yet.

**Comment by scoder** [comment]
> Seems like that, `test_requirements.txt`, and `pyproject.toml` just need a bump.

I've updated them (and `build_test.yml`) to the latest release, 0.29.34, if that's ok. Required is only 0.29.31, but there were several bug fixes since then, so it's worth upgrading if everything builds with it.

You probably want to update to 0.29.35 once that's released, in order to support CPython 3.12 (once that is released), but then again, 3.12 still in flux so who knows what will happen before the final release…

**Comment by mattip** [comment]
Hmm. I think the build_test.yml should be using `build_requirements.txt` and `test_requirements.txt`, and the former should also be updated. Again, it may be out of scope for this PR, that is fine.

**Review by seberg — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @scoder

**Pull request merged**
