### PR TITLE
DOC: Fix reference warning for ABCPolyBase.

### PR DESCRIPTION
**Pull request by liang3zy22**
Fix following reference warning:
```

hermite.py:docstring of numpy.polynomial.hermite.Hermite:4: WARNING: py:obj reference target not found: ABCPolyBase
hermite_e.py:docstring of numpy.polynomial.hermite_e.HermiteE:4: WARNING: py:obj reference target not found: ABCPolyBase
laguerre.py:docstring of numpy.polynomial.laguerre.Laguerre:4: WARNING: py:obj reference target not found: ABCPolyBase
legendre.py:docstring of numpy.polynomial.legendre.Legendre:4: WARNING: py:obj reference target not found: ABCPolyBase
polynomial.py:docstring of numpy.polynomial.polynomial.Polynomial:4: WARNING: py:obj reference target not found: ABCPolyBase

```

I created a new module for polybase.ABCPolyBase.

### CODE REVIEW

**Comment by mattip** [comment]
It feels weird to add documentation for `_polybase.py` since it would seem that is meant to be private. On the other hand, how can a base class of a public hierarchy be private? @rossbar, @charris should we move `_polybase.py` -> `polybase.py`?

**Comment by rgommers** [comment]
This does not seem desirable to me at first sight.

> On the other hand, how can a base class of a public hierarchy be private?

Where are we promising that different classes are in a hierarchy? Something like the [Chebyshev class](https://numpy.org/devdocs/reference/generated/numpy.polynomial.chebyshev.Chebyshev.html#numpy.polynomial.chebyshev.Chebyshev) seems perfectly usable without that.

**Comment by charris** [comment]
> should we move _polybase.py -> polybase.py?

At first glance, I'd say no, it cannot do anything useful by itself. It does contain some documentation that tries to act like templates for the functions that use it and evidently there is some problem there. Is there no way else to fix things?

**Comment by mattip** [comment]
The [new page for the abstract base class](https://output.circle-artifacts.com/output/job/6c38234a-fee2-4151-b6e6-75936ba867b9/artifacts/0/doc/build/html/reference/generated/numpy.polynomial._polybase.ABCPolyBase.html#numpy.polynomial._polybase.ABCPolyBase) documents methods that are already documented in [the children classes](https://output.circle-artifacts.com/output/job/6c38234a-fee2-4151-b6e6-75936ba867b9/artifacts/0/doc/build/html/reference/generated/numpy.polynomial.hermite.Hermite.html). I think if we consider the fact that there exists an abstract base class an implementation detail (since it is private), a better course of action would be to remove the mention of the abstract base class from the 5 classes that use it.

**Comment by liang3zy22** [comment]
As discussion, I removed the abstract base class reference from the five [children classes](https://output.circle-artifacts.com/output/job/dbff0efa-3859-4df0-b893-36b3726005b5/artifacts/0/doc/build/html/reference/generated/numpy.polynomial.polynomial.Polynomial.html#numpy.polynomial.polynomial.Polynomial). And little modification for [Chebyshev class](https://output.circle-artifacts.com/output/job/dbff0efa-3859-4df0-b893-36b3726005b5/artifacts/0/doc/build/html/reference/generated/numpy.polynomial.chebyshev.Chebyshev.html#numpy.polynomial.chebyshev.Chebyshev).

**Comment by mattip** [comment]
Thanks @liang3zy22

**Pull request merged**
