### PR TITLE
ENH: improve performance for numpy.core.records.find_duplicate

### PR DESCRIPTION
**Pull request by danielhrisca**
The old implementation used a slower algorithm that only used lists and sublists to search for duplicates. By using an _OrderedDict_ the function executes much faster and the output is identical to the old implementation.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Can you share the benchmark results you care about?

Why is `OrderedDict` better than `dict`? 
What about in Python 3.7? I think they revamped the dict module.

**Comment by danielhrisca** [comment]
I use this to compare the two implementations

```python
from time import perf_counter
import numpy as np

for fields in (2000, 4000):

    arrays = [
        np.arange(5)
        for i in range(fields)
    ]

    names = [
        'field_{}'.format(i)
        for i in range(fields)
    ]


    start = perf_counter()
    for i in range(30):
        arr = np.core.records.fromarrays(arrays, names=names)
    stop = perf_counter()
    print(fields, stop-start)
```

The results are
* current implementation 2000 fields: 1.2 s
* proposed implementation 2000 fields: 0.4 s
* current implementation 4000 fields: 4.4 s
* proposed implementation 2000 fields: 0.8 s

I've encountered binary files with records that had 60000 fields.

Starting with Python 3.6 the dict is ordered so it could be used instead of an OrderedDict. However I see that numpy 1.17.0 will keep Python 3.5 support, and I also wanted to preserve the same output as the old implementation. This is why I've used OrderedDict instead.

**Comment by hmaarrfk** [comment]
cool. I don't know much about records, but seems like an interesting way to go! Definitely building on the strengths of python.

**Review by eric-wieser — COMMENTED** [review]
Can you use the `OrderedCounter` recipe from https://docs.python.org/3.3/library/collections.html#ordereddict-examples-and-recipes

**Comment by danielhrisca** [comment]
Hello Eric,

I've switched to that recipe as you have suggested.

**Comment by danielhrisca** [comment]
I'm working on some more optimizations in the _records.py_ file. Should I open a separate PR or use this PR instead?

**Comment by eric-wieser** [comment]
Please open a separate PR

**Review by eric-wieser — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @danielhrisca. It would be nice to add benchmarks to `./benchmarks/benchmarks`

**Pull request merged**
