### PR TITLE
DOC: Add release note about deprecation introduced in gh-27076.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
[skip actions] [skip azp] [skip cirrus]

### CODE REVIEW

**Comment by charris** [comment]
Thanks Warren.

**Comment by WarrenWeckesser** [comment]
In the note that I added, I included a couple extra spaces at the beginning of each line, because that is what I saw in `26452.deprecation.rst`.  But `26268.expired.rst` and `26611.expired.rst` don't have the extra indentation. You can see the difference in the rendered release notes: https://output.circle-artifacts.com/output/job/b4498da5-8a6c-4d33-a918-76400e056f83/artifacts/0/doc/build/html/release/2.1.0-notes.html#deprecations

I think extra indentation shouldn't be used.  If y'all agree, I'll submit a PR to fix `26452.deprecation.rst` and `27076.deprecation.rst`.

**Comment by WarrenWeckesser** [comment]
After looking at the rendering of all the notes, I think it is better to never indent the bullets.  Indenting creates a shaded area with a dark bar on the left, and I see no reason for that.  I'll submit a PR to fix the notes that have the extra indentation.

**Comment by seberg** [comment]
Yes, indeed.  None of the bullets shoul be indented.  They are just pasted verbatim into the final rst (with the link added below).
(The main special handling is, that bullets are sorted to come before subsections.)

**Pull request merged**
