### PR TITLE
BUG: Polynomials now copy properly (#22669)

### PR DESCRIPTION
**Pull request by MatteoRaso**
On line 502, self.symbol.copy() was called, which
causes an AttributeError, since self.symbol is a
string, so it doesn't have a copy() method. To fix it, 
I simply removed the copy() and directly assigned the string.

### CODE REVIEW

**Comment by mattip** [comment]
I wonder if at one point `symbol` was an ndarray, but then got changed into a string. Is there a pickle test for Polynomial?

**Comment by MatteoRaso** [comment]
> I wonder if at one point `symbol` was an ndarray, but then got changed into a string. Is there a pickle test for Polynomial?

No. I checked the commit history, and the `symbol` attribute was added in commit b84a53df9346a73fe8f6df0aaad8727f9bf56076, which is also when the bug was introduced.

**Comment by mattip** [comment]
Could you add another test that checks `y = pickle.loads(pickle.dumps(x)); assert_equal(x, y)` (it fails on `main`)?

Otherwise LGTM. xref @rossbar

**Comment by MatteoRaso** [comment]
> Could you add another test that checks `y = pickle.loads(pickle.dumps(x)); assert_equal(x, y)` (it fails on `main`)?
> 
> Otherwise LGTM. xref @rossbar
Done.

**Comment by mattip** [comment]
Thanks @MatteoRaso

**Comment by MatteoRaso** [comment]
No problem.

**Pull request merged**
