### PR TITLE
DOC: Remove duplicate information about governance

### LINKED ISSUE #17496: DOC: 'Governance' in Sphinx pages: delete/move/keep?
There are overlaps between the  [governance section](https://numpy.org/devdocs/dev/governance/index.html) in the Sphinx pages and [About us](https://numpy.org/about/) in the Hugo pages. But they're not identical.

What should be done about the Sphinx pages? Remove them, merge them into Hugo (as new pages?), leave them alone?

### PR DESCRIPTION
**Pull request by melissawm**
This is a second part of unifying the governance documentation (See also numpy/numpy.org#450)

Closes #17496

### CODE REVIEW

**Review by rkern — APPROVED** [review]
LGTM!

**Comment by melissawm** [comment]
Please wait for numpy/numpy.org#450 to be merged before merging this one as otherwise we'll have missing information. Thanks!

**Comment by melissawm** [comment]
This is good to go now :)

**Comment by mattip** [comment]
Thanks @melissawm. Do we have an icon for "this link is off-site" in the template? It would be nice to add it, or opens such links in a new window, since it can be disturbing to suddenly find yourself on a different site.

**Comment by melissawm** [comment]
Good idea, I'll check!

**Comment by melissawm** [comment]
I've asked @MarsBarLee to take a look at that.

**Pull request merged**
