### PR TITLE
MAINT: Adjust rest of string ufuncs to static_data approach

### PR DESCRIPTION
**Pull request by lysnikolaou**

### CODE REVIEW

**Comment by charris** [comment]
@mattip Any idea what is going on with the `BLAS tests (Linux) / Test Linux (nightly OpenBLAS)` failures?

**Comment by ngoldbaum** [comment]
@charris see https://github.com/numpy/numpy/issues/25849.

@mhvk any chance you have some time this week to look over this refactor?

**Review by ngoldbaum — APPROVED** [review]
This is a straightforward refactor and looks correct to me.

**Review by mhvk — COMMENTED** [review]
Sorry I missed this, but agreed this is a straightforward refactor - nice to see it used here too!

**Pull request merged**
