### PR TITLE
DOC: improve docstring of np.where

### PR DESCRIPTION
**Pull request by Brainor**

### CODE REVIEW

**Comment by eric-wieser** [comment]
This looks worse to me, I think the older wording was more accurate.

**Comment by eric-wieser** [comment]
"broadcastable against each other" might be an improvement, I'm not sure what our preferred terminology is at the moment.

**Comment by Brainor** [comment]
> "broadcastable against each other" might be an improvement, I'm not sure what our preferred terminology is at the moment.

Oh, thank you for your suggestion. Before the commit, I just found some lines like https://github.com/numpy/numpy/blob/0f759540e8f6ac212bf5644666ec0b5b349960c0/numpy/core/fromnumeric.py#L352-L353 and https://github.com/numpy/numpy/blob/0f759540e8f6ac212bf5644666ec0b5b349960c0/numpy/core/fromnumeric.py#L375-L376 so I thought it was a typo. Maybe `broadcastable to some shape` is also accurate?

**Comment by eric-wieser** [comment]
Ah, thanks for finding the other docstrings, that does indeed make your argument more compelling. Perhaps another maintainer will disagree with me, feel free to reopen.

**Pull request closed without merging**
