### PR TITLE
BLD: unvendor meson-python

### PR DESCRIPTION
**Pull request by rgommers**
The meson-python 0.15.0 release added the ability to configure a custom `meson` in `pyproject.toml`. So there's no longer a need for us to vendor it.

### CODE REVIEW

**Comment by rgommers** [comment]
Python 3.12 failures:
```
  meson.build:40:22: ERROR: <PythonExternalProgram 'python3' -> ['/opt/hostedtoolcache/Python/3.12.0/x64/bin/python']> is not a valid python or it is missing distutils
```

The vendored Meson needs an update so that we're getting the fixes in Meson 1.2.3 to avoid distutils/setuptools completely.

**Comment by rgommers** [comment]
Almost victory - a single test error left in the "without optimizations" job of `linux_simd.yml`:
```
  ----------------------------- Captured stderr call -----------------------------
  Traceback (most recent call last):
    File "/tmp/pytest-of-runner/pytest-0/test_limited_api0/limited_api/setup.py", line 6, in <module>
      from setuptools import setup, Extension
  ModuleNotFoundError: No module named 'setuptools'
  =========================== short test summary info ============================
  FAILED numpy/_core/tests/test_limited_api.py::test_limited_api - subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.12.0/x64/bin/python', 'setup.py', 'build', 'install', '--prefix', '/tmp/pytest-of-runner/pytest-0/test_limited_api0/installdir', '--single-version-externally-managed', '--record', '/tmp/pytest-of-runner/pytest-0/test_limited_api0/tmp_install_log.txt']' returned non-zero exit status 1.
```

That's because on 3.12 we no longer install `setuptools` as a build dependency, and it's needed as a test dependency there. Should be fixed by the last commit.

**Comment by rgommers** [comment]
Victory! This is ready to merge.

**Comment by charris** [comment]
Thanks Ralf.

**Pull request merged**
