### PR TITLE
MAINT: Haiku defines neither  ``__STDC_NO_THREADS__`` nor ``__GLIBC__``

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Ticket for this has been filed at: https://dev.haiku-os.org/ticket/16965

**Comment by mattip** [comment]
Haiku seems like [it is in beta](https://www.haiku-os.org/get-haiku/r1beta2/release-notes/). What are the chances they will fix this issue before an official release? I doubt the python scientific stack is the only place this issue will arise.

**Comment by Begasus** [comment]
A new beta is around the corner, summoning @korli to see if he could shed a light on this, not sure how high the priority is to fix this on Haiku's side

**Comment by Begasus** [comment]
I need to re-check this, the ticket has been updated and a solution handed, if things work out alright this can be closed.

**Comment by Begasus** [comment]
Closing this one, the fix should come from our side, sorry for the noise and thanks for taking the time to have a look at it :+1:

**Pull request closed without merging**
