### PR TITLE
DOC: Update some plotting code to current Matplotlib idioms

### PR DESCRIPTION
**Pull request by timhoffm**
- 3D Axes are created via `add_subplot(projection='3d')`
- There is now a `stairs()` function that's specifically designed for
  showing histogram curves
- Labels should be passed as keyword arguments to the plot functions
  instead of to `legend()`, which reduces the risk of mixing them up.

### CODE REVIEW

**Comment by rgommers** [comment]
This looks great, thanks @timhoffm. One issue, the build is failing with:
```
AttributeError: module 'matplotlib.pyplot' has no attribute 'stairs'
```
How recently was `stairs` introduced? We can consider upgrading the minimum matplotlib version needed to build the docs. For that, `stairs` has to be in a release that's >=1 year old I'd say. Otherwise it's better to revert that change.

**Comment by charris** [comment]
`stairs` was new in v3.4.0, might could be done with `steps` if v3.4.0 is too new.

**Comment by timhoffm** [comment]
I've reverted the use of `stairs`. Other ways to plot histograms from binned data are cumbersome/unituitive. That would be either using bars

~~~
>>> centers = (bins[1:] + bins[:-1]) / 2
>>> widths bins[1:] - bins[:-1]
>>> plt.bar(centers, n, width=widths)
~~~

or `step` (with the problem that steps expects equal-length inputs):

~~~
plt.step(bins, np.insert(n, 0, [0]))
~~~

That's exactly why we've introduced `stairs`. I don't want to advertise any of the workarounds. So, I'm going back to the original `plot`. I've added a note that `plt.stairs` can be used for Matplotlib 3.4+. This way people can still learn the new function and it's more likely that somebody will remove `plot` from the docs some time in the future.

**Review by rgommers — APPROVED** [review]
LGTM now, thanks @timhoffm

**Pull request merged**
