### PR TITLE
DEP,MAINT: Change deprecated indexing to errors.

### PR DESCRIPTION
**Pull request by charris**
The deprecated operations changed to errors are
- Conversion of floats and booleans to npy_intp indexes.
- Conversion of single element integer arrays of ndim > 1 to indexes.
- Multiple ellipsis in index.

The affected deprecation tests have been been changed to check for
raised errors instead, but remain in test_deprecations.py for the
moment. They will be moved when the conversion of the remaining indexing
deprecations is complete.

### CODE REVIEW

**Comment by charris** [comment]
Still needs the tests rearranged, but now is a good time to get it checked. @seberg This comes from your work on the indexing, could you check it over?

Also, I looked at the change that allows scalar boolean indexes treated as boolean arrays. I thought the results a bit odd, so have left that for another PR>

**Comment by seberg** [comment]
The scalar boolean stuff will probably need annoying changes in the test suit :( (I think it will fail the automated tests). Thanks for attacking this, wake me up if I forget to go over it. I will likely squeeze it in, but if I don't in the next 2 weeks, push me then!

**Comment by seberg** [comment]
OK, had a look over it, was not so much after all and looks good to me. Again about the scalar booleans, IIRC there are whole code branches there also which are not well tested, because they are never used. So we need new tests/change the automated ones, etc. which may well be quite a large (and confusing) job to do :(. But I suppose you probably already noticed that.

**Comment by seberg** [comment]
Chuck, did you want to change more on this? Otherwise I might merge it some time around (or you go ahead).

If I see it right, then the integer deprecations have been in place for about two years (by the time we will release). The others are not nearly as bad and would have been there for about a year (and two releases). So I think we are safe to attempt this.

**Comment by charris** [comment]
I want to move the affected deprecation tests into the appropriate modules and add something to the release notes. I'll do that today.

**Comment by jreback** [comment]
@charris I thought I read somewhere you were going to revert this for 1.11?

**Comment by charris** [comment]
@jreback See  #7162. Looks like we will allow float indexing for another release cycle.

**Pull request merged**
