### PR TITLE
BUG: Stub out ``get_build_msvc_version`` if ``distutils.msvccompiler`` cannot be imported 

### LINKED ISSUE #27405: BUG: ModuleNotFoundError: No module named 'distutils.msvccompiler' on Linux
### Describe the issue:

The module `numpy/distutils/command/config.py` unconditionally imports `numpy.distutils.mingw32ccompiler`, which unconditionally imports `distutilis.msvccompiler`. This module is not present on Linux, for obvious reasons.

The only function that `config.py` imports from `mingw32ccompiler` is `get_manifest`, which it only calls if `self.compiler.compiler_type == 'mingw32'`, which is plausible if cross compiling, I guess.

The only function that `mingw32ccompiler` imports from `distutils.msvccompiler` is `get_build_version` as `get_build_msvc_version`. `mingw32ccompiler.generate_manifest`,` calls this function, and is perfectly capable of handling if it returns `None`, indicating that MSVC is not installed.

The solution is as simple as catching `ImportError` when attempting to import `distutils.msvccompiler` and providing a stub for `get_build_msvc_version` which returns `None`:

```
try:
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
except ImportError:
    def get_build_msvc_version():
        return None
```

I'll have a PR for this in just a few minutes.

### Reproduce the code example:

```python
import numpy.distutils.core
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 24, in <module>
    from numpy.distutils.command import config, config_compiler, \
  File "/usr/lib/python3/dist-packages/numpy/distutils/command/config.py", line 19, in <module>
    from numpy.distutils.mingw32ccompiler import generate_manifest
  File "/usr/lib/python3/dist-packages/numpy/distutils/mingw32ccompiler.py", line 30, in <module>
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

### Python and NumPy Versions:

1.21.5
3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

### Runtime Environment:

_No response_

### Context for the issue:

I found this while creating a `setup.py` which uses `Cython.Build.cythonize` to auto-build a Cython module. The module itself doesn't even use numpy, but since it is installed, there is some hook which Cython picks up on which causes it to pull in `numpy.distutils.core`, which leads to the given error.

### PR DESCRIPTION
**Pull request by PinkPandaKatie**
Fixes #27405.

### CODE REVIEW

**Comment by mattip** [comment]
The `numpy.distutils` module is deprecated.

**Comment by charris** [comment]
Thanks @PinkPandaKatie .

@mattip Started to see failing tests on CI on account of this bug.

**Comment by mattip** [comment]
Which CI?

**Comment by charris** [comment]
> Which CI?

[macOS x86-64 conda (3.11)](https://github.com/numpy/numpy/actions/runs/10947337520/job/30395854748?pr=27426#logs)

Merging this got rid of one error, one remains. The Python 3.11.10 release may have broken things. I'm thinking of just removing `msvccompiler` from the api checks. I mean, the failure is on the Mac, and distutils itself will be going away soon enough.

**Comment by mattip** [comment]
We don't pin setuptools in the conda runs. See #27429

**Comment by rgommers** [comment]
I just saw this now. While `numpy.disutils` is deprecated, we should still accept PRs that fix bugs, especially if they're very easy to review like this one - if someone has a real-world problem and it's annoying enough that they come here to fix it (which seems to be the case here), then let's just apply the fixes.

For context: found this today because it tripped someone up in a conda-forge feedstock. Easier to backport this to the next bug fix release than trying to work around it in conda-forge.

**Comment by charris** [comment]
@rgommers Already done in 6b9ef481661. It wasn't in the changelog because it was part of getting the release preparation PR. Should be in the 2.1.2 release.

**Comment by rgommers** [comment]
Ah great, thanks!

**Pull request merged**
