### PR TITLE
DOC: add docstring for TooHardError

### PR DESCRIPTION
**Pull request by Radhika14soni**
xref gh-10106

Added DocString function in TooHardError. Please let me know if changes are required. Since it's my first contribution.

### CODE REVIEW

**Comment by mattip** [comment]
What we are looking for is a [docstring for the class](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring), like the one for [`AxisError`](https://github.com/numpy/numpy/pull/18013/files#diff-378d7fea035b0d27a45a942b31de5bf61ceda7b650b2ac98634ff88a88b19ef7R126).

**Comment by rgommers** [comment]
@Radhika14soni are you planning to update this PR with the change requested by @mattip?

**Comment by Radhika14soni** [comment]
Yes

**Comment by melissawm** [comment]
Gentle ping, @Radhika14soni . Do you need help with moving this forward?

**Comment by angellicacardozo** [comment]
Hello there, @melissawm and @Radhika14soni, nice to meet you! I would like to help with moving this PR forward.

**Comment by angellicacardozo** [comment]
Hello there, @Radhika14soni. I believe it is important to emphasize that I am also a complete new contributor to numpy community and hopefully will have the chance to grow together with you and all the amazing team.

Let's start, I followed a discussion on Dec 17, 2020, where there was a proposal to get the issue done by analyzing the docstrings as implemented for the other exceptions classes at the same file.

You have proposed the following change

```
class TooHardError(RuntimeError):
    def __str__(self):
        return ("max_work Exceeded")
```

For the original code

```
class TooHardError(RuntimeError):
    pass
```

Taking a look at others `__str__` I could notice a pattern including a string literal as the first statement and adding more information with `format` feature.  [Like what I see here [ * ]](https://github.com/numpy/numpy/blob/b0e95fca95a87f708f6cd59234c9125f0f57f586/numpy/core/_exceptions.py#L88)

```
def __str__(self):
        # only show the number if more than one input exists
        i_str = "{} ".format(self.in_i) if self.ufunc.nin != 1 else ""
```

Hope to hear from you soon,
Best regards

**Comment by mattip** [comment]
We are looking for the class `__docstring__`, more than the `__str__` repr of the class. Taking an example from [`AxisError`](https://github.com/numpy/numpy/blob/f4353323d0be0c3b3c7d0c752d6c135bc6d36465/numpy/core/_exceptions.py#L124), that docstring is rendered in [the documentation](https://numpy.org/devdocs/reference/generated/numpy.AxisError.html) to describe when this error appears and how to mitigate it. The `__docstring__` for TooHardError is much simpler. A good idea of why it is raised can be seen in the documentation for [shares_memory](https://numpy.org/devdocs/reference/generated/numpy.shares_memory.html).

**Comment by angellicacardozo** [comment]
@mattip and @InessaPawson First, my apologies for the slow reply.
Understanding the process involved in contribution has been a little massive.

Now, a few questions. 

1. Should I move the work to a fork that is a version of mine or I am expected to commit and continue doing the code on Radhika14soni`s fork?
2. Reading the docs I learned that we need to create branches names more related to the issue as possible, I believe that the current name is not as expected. So, again, am I expected to do something about it? 
3. @mattip I was ok following the instructions from [AxisError](https://github.com/numpy/numpy/blob/f4353323d0be0c3b3c7d0c752d6c135bc6d36465/numpy/core/_exceptions.py#L124) however, when trying to extract more information in order to add `Attributes`, `Parameters`, `Examples`  and so on into docs I tried checking out that source link that you gave me for the [rendered documentation](https://numpy.org/devdocs/reference/generated/numpy.AxisError.html) and then I was not able to find anything related with `AxisError`. Did I miss something ?

Finally, I am writing something more like this, still working on the information on how to mitigate it: 

```
    """max_work was exceeded.

    This is raised whenever the maximum number of candidate solutions to consider specified by the ``max_work`` parameter exceeds.
    Since checking whether two arrays share memory is NP-complete you have may considered 
    setting up max_work to a finite number avoiding the function to become exponentially slow for some inputs.

    """
```

Do you think it's all right to do it?

Best Regards,

**Comment by mattip** [comment]
(1) and (2): I think you can restart this on your own fork, with any branch name you choose.

(3) This exception does not really need all those sections. Let's start with just the docstring and see where we go from there. The string you have looks like a good start.

**Comment by InessaPawson** [comment]
The task has been completed in https://github.com/numpy/numpy/pull/21471. We can close this pull request.

**Pull request closed without merging**
