### PR TITLE
MAINT: Fix METH_NOARGS function signatures

### PR DESCRIPTION
**Pull request by hoodmane**
This is a continuation of @joemarshall's work #19058.

> I think there should be a bunch of more issues around `METH_NOARGS` usage that would be nice to fix up as well. 
_@seberg in https://github.com/numpy/numpy/pull/19058#issuecomment-871639053_

This fixes all of the incorrect `METH_NOARGS` signatures that I managed to track down.
We need this for https://github.com/pyodide/pyodide/pull/1677.

### CODE REVIEW

**Comment by seberg** [comment]
Thanks!  Would you be up to making it throughout `NPY_UNUSED(args)`?  Since I think it is a bit more clear what this is.  One (or two) of them are also a bit long lines, we try to stay under 80 characters.

But changes look good, just thought a bit more uniform naming will be easier to understand.

**Comment by hoodmane** [comment]
I don't understand the failing doctests.

**Comment by hoodmane** [comment]
Also, if you want me to clean the history I am happy to rebase and squash all the commits.

**Comment by seberg** [comment]
We can just squash-merge, curious what is "closure"? (I think I just come form a different angle, I thought "args", because most python functions get args or arg passed in, but here it is always NULL.)

No need to squash, if you don't we will probably just squash-merge.

**Comment by hoodmane** [comment]
I think `args` is sort of the right name for the extra argument of the `METH_NOARGS` functions. But the argument really doesn't mean anything: it just gets filled in with `NULL` here:
https://github.com/python/cpython/blob/fc4474e45eecbea8e88095f28c98c5d56438d841/Objects/methodobject.c#L489
I am not really sure why they put that in, it just seems to cause trouble.

The `void *` argument to getters and setters I think should best be called `void *closure`.

See here: https://docs.python.org/3/c-api/structures.html?highlight=getset#c.PyGetSetDef
> `void *closure` -- optional function pointer, providing additional data for getter and setter

In the CPython source, sometimes the extra noargs arguments are called `args` (13 times) but much more often they are called `ignored` (780 times).

The last argument to getters and setters is variously called `closure`, `context`, or `ignored` in CPython source.

This is more than you wanted to know I'm sure =)

**Comment by seberg** [comment]
> I am not really sure why they put that in, it just seems to cause trouble.

Well, could be to save some branching.  Or just historical, maybe `METH_NORARG` was added later for convenience...

> This is more than you wanted to know I'm sure =)

Hehehe, thanks :).  I was just confused why `closure` has any meaning in this context (but it is also a term I am simply not really used to).

Anyway, thanks!  Let me put this in, before I find something else to nitpick about ;).

**Comment by seberg** [comment]
Marking as backport candidate, since it is harmless and you mentioned you need it for `pyodine`, so presumably it would be nice to have a released version with it in.

**Comment by hoodmane** [comment]
Thanks!

**Comment by charris** [comment]
The circleci failures are legitimate.

**Comment by charris** [comment]
But I don't see exactly how the CircleCI failure is related to this.

**Comment by seberg** [comment]
Hmmm, and only on this PR!  Very strange...

**Comment by charris** [comment]
Also in the backport.

**Comment by hoodmane** [comment]
After the most recent commit, these tests are passing on main again. At a glance it is very unclear why the most recent commit would have any effect on these tests either.

**Pull request merged**
