### PR TITLE
ENH: Adds ufunc support to the scimath module

### PR DESCRIPTION
**Pull request by andyljones**
This adds ufunc support to the scimath module. The _makearray idiom is taken from the linalg module.

Since scipy imports `scimath.log` as `sp.log` , by proxy this fixes the annoying issue of calling `sp.log(pd.Series(1))` and getting an array back.

### CODE REVIEW

**Comment by charris** [comment]
Needs a test.

**Comment by eric-wieser** [comment]
I'd argue that `np.asanyarray` might be a better way to handle this.

**Comment by andyljones** [comment]
Can you link me to a modern example of supporting multiple kinds of array-like? I didn't know about the gufunc interface, so I'm wondering what else I missed.

**Comment by seberg** [comment]
I agree with Eric, asanyarray may be an option to change this (although I am not sure I want this module to be used.

Since this is almost two years old and requires quite a bit of change, I am going to close this PR. A PR that changes to asarray should be acceptable, however (but should include test), so please just open a new one if anyone finds this and wants to pick it up.
In case anyone stumbles upon it: I think the only reason why the make array pattern makes sense in linalg, is as a hack to support `matrix`...

**Pull request closed without merging**
