### PR TITLE
ENH: Update histograms.py to work with NaN.

### PR DESCRIPTION
**Pull request by roliveira**
In order to fix of #12955

### CODE REVIEW

**Comment by seberg** [comment]
For the automatic histograms, the number of bins probably might need to be adjusted as well. I see a little bit the problem, that we would go from "error on NaN" to (almost) silently accepting NaN in histograms. In similar functions we do not allow this, since we do have for example nanpercentile, etc.

Maybe something to think about the options and discuss on the mailing list?

**Comment by roliveira** [comment]
It was just a little problem on the automatic binning, and I thought that it would be an easy workaround it. Should it be an exception instead?

I just subscribed to the mailing list, I can follow-up from there if that becomes a thread.

On the EDIT side, I don't really know the workflow for the contributions. But I'm happy to dev. the tests and release notes.

**Comment by seberg** [comment]
Yes, if you can work on the tests and release notes that would be great, it also the best way to ensure it will happen timely. In the end we may fix it up a bit for you as well. @madphysicist do you have an opinion on this?

I was just suggesting a mail to the list, because I was not sure myself that I like silently constructing histograms, when users may not be aware that their data sometimes occurs NaN (i.e. I typically just filter out NaN values manually beforehand with `data[np.isfinite(data)]`, which is explicit. I agree that currently only the min/max estimation (and many of the automatic binners) will actually fail.
In a sense that it is a bit inconsistent, and I guess could go either way.

**Comment by madphysicist** [comment]
My knee-jerk reaction is that if we do include this, it needs to be documented and done more thoroughly. If we don't count NaNs, what happens to them? How do you handle normalization? Etc...

**Comment by fbertrand27** [comment]
Not sure if I should be posting this here, but as I just mentioned in #12955, the behavior does not seem to be consistent, depending if drawing from a single list of data or a list of lists.

**Comment by charris** [comment]
I'm going to close this. Anyone know if histograms can handle masked arrays? That would seem to be a good starting point.

**Comment by charris** [comment]
Thanks @roliveira for the attempt.

**Pull request closed without merging**
