### PR TITLE
ENH Make return values to fortran subroutines be int

### PR DESCRIPTION
**Pull request by hoodmane**
This is the last patch Pyodide needs to build Numpy for wasm-emscripten. I am not confident that this should be accepted, but I figure it is good to have a discussion.

The problem is that we don't have a real fortran compiler for llvm (see https://github.com/scipy/scipy/issues/15290), so we use f2c.

F2py defaults to making subroutines return void, whereas f2c makes them int. On most systems this wouldn't matter, but on wasm, strict return type checking is used which makes things fail when f2py code calls subroutines that were generated from fortran with f2c. To fix this we fix the f2py declarations to say the functions return int and not void.

(Thanks to @joemarshall for contributing the original version of this patch.)

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks for opening this PR @hoodmane. Making things work for Pyodide is a clear upside; it's less clear to me if this would have backwards compatibility impact or if there's other reasons not to merge this. @pearu, @HaoZeke any thoughts on this change?

**Comment by hoodmane** [comment]
If you are enthusiastic about this I think the way to go would be to use a conditional `#define` to choose between void or int as the return type. In that case I believe it would have no backwards compatibility impact.

Also it might be worth starting to think about adding ci support for an emscripten target to numpy. I have been researching how to do this and pyo3 already added ci support. Pyodide needs more work on properly exposing the files needed for out of tree builds but we are getting close.

**Comment by hoodmane** [comment]
I think this should be split into two parts: as I understand it `f2c.c` and `f2c.h` must be intended to be used with `f2c` always so the changes there are an increase in accuracy in all cases: even in native cases the return type is int not void but you just ignore it. On the other hand, the f2py changes are only an improvement if f2c is being used to compile Fortran. If you are using a real Fortran compiler, maybe it isn't necessary.

**Comment by charris** [comment]
> Pyodide is handling the f2py Fortran with f2c.

Isn't f2c limited to Fortran 77? It seems there is still some maintenance for it, but it is based on an old Fortran compiler written in C. That said, I think the f2py tests check for compiler availability, so that might take care of some problems.

**Comment by hoodmane** [comment]
Closed because it doesn't seem needed anymore??

**Pull request closed without merging**
