### PR TITLE
DOC: Change matrix size in absolute beginners doc.

### PR DESCRIPTION
**Pull request by chtrac**
Referring to issue #18678.

The documentation at https://numpy.org/doc/stable/user/absolute_beginners.html#creating-matrices had a slight inconsistency, where a matrix suddenly changed size and content without explicitly showing so.

This pull request updated the description and the corresponding image so that the documentation is more consistent.

I have tried matching the original style of the image as closely as possible.

### CODE REVIEW

**Comment by cdahlin** [comment]
After my first commit, I got some build errors for the documentation. It seems like there were some more discrepancies between the figures and the code in the text (which had the root cause in a different initial matrix). I fixed those as well, now it should be consistent.

**Comment by mattip** [comment]
I think this also needs a change in the first image to match the text

**Comment by cdahlin** [comment]
> I think this also needs a change in the first image to match the text

Are you referring to [this image](https://numpy.org/doc/stable/_images/np_create_matrix.png)?

I changed that to [this](https://github.com/numpy/numpy/blob/18db7880daf6cd20bd7539ab65a3f06663f10d90/doc/source/user/images/np_create_matrix.png) (also see attached). It's included in the first commit of this pull request.

np_create_matrix

**Comment by mattip** [comment]
Yes, now I see it. I only looked at the changed files, not at the [rendered page](https://18978-908607-gh.circle-artifacts.com/0/doc/build/html/user/absolute_beginners.html#creating-matrices).

LGTM.

**Comment by charris** [comment]
Thanks @cdahlin .

**Pull request merged**
