### PR TITLE
MAINT: Translate heapsort.c.src to C++ using templates

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
This is based on #20732

**Comment by charris** [comment]
close/reopen

**Comment by charris** [comment]
Just want to check the difference now that #20732 is in.

**Comment by charris** [comment]
It is better to rename the `*.c.src` files, as was done with the timsort code, than to make copies. Copying removes the credit for any of the surviving original code. There is no long term solution for that, refactoring and reformatting eventually erases history, but renaming slows it down a bit.

**Comment by charris** [comment]
Thanks @serge-sans-paille .

**Pull request merged**
