### PR TITLE
WIP, MAINT, TST: Switch NumPy testing to pytest

### PR DESCRIPTION
**Pull request by charris**
Copy of #10379.

Putting this up so that it can be worked on, will probably rebase, squash, and such.

### CODE REVIEW

**Comment by charris** [comment]
The `runtests.py` script needs work. The use of `unittest` needs fixing.

**Comment by pv** [comment]
unittest: s/unittest.TestCase/object/, s/setUp/setup_method/,
s/tearDown/teardown_method/

**Comment by pv** [comment]
There's unused stuff in `numpy/lib/_testutils.py` (which is direct
copypaste from scipy): the only part used here is PytestTester, the
other stuff looks scipy-specific and unnecessary to include here.

`USE_PYTEST` should also be removed from appveyor.yml.

python runtests.py -v -n -m %TEST_MODE% -- -n3 --junitxml=junit-results.xml

is probably teh correct test runner command there, and one probably
should not use "pip install -e ." to install.

**Comment by charris** [comment]
@pv I'm thinking this is not the way to go, rather I want to switch all the decorators to pytest and make the other needed changes, so I may open a different PR that does that and close this one.

**Comment by charris** [comment]
The state that I left this in before was so that I could work on changes while still testing with nose, but at some point a major change was needed.

**Comment by pv** [comment]
I feel that in the end state, we should do `git rm -rf numpy/testing/pytest_tools.py`, and numpy tests should use pytest directly instead of using a shim layer.

The stuff in `numpy.testing.*` that can run without nose, should be changed so that it can run without nose. The routines that only work with nose should be marked as such in the documentation.

**Comment by charris** [comment]
Closing this, will use bits in other PRs.

**Pull request closed without merging**
