### PR TITLE
DOC: Return of gradient() function

### PR DESCRIPTION
**Pull request by helderc**
This is an improve of documentation for gradient() funcion as commented in #5628

### CODE REVIEW

**Comment by charris** [comment]
Thanks @helderc .

**Comment by helderc** [comment]
The pleasure is all mine :)

**Comment by charris** [comment]
For future reference, it you included `Closes #5628` in the body of the commit message, the corresponding issue would have been automatically closed when this was merged.

**Comment by helderc** [comment]
Ok, thanks.

**Comment by jaimefrio** [comment]
Will have to be another PR, but the return of this function is a list of ndarrays, not an ndarray as the docstring says.

**Comment by helderc** [comment]
@jaimefrio so the text on return part would be: `List of ndarrays of the same shape as...`, right?

**Comment by jaimefrio** [comment]
I think the most relevant thing is to specify that the return type is `list`, or `list of ndarrays`, not `ndarray`: [here](http://stackoverflow.com/questions/29464892/why-is-numpy-gradient-returning-a-list-instead-of-ndarray) is someone the docs got confused. But yes, the edit you suggest also makes plenty of sense.

**Comment by helderc** [comment]
@jaimefrio done at PR #5757

**Pull request merged**
