### PR TITLE
DOC: added examples section for rfft2 and irfft2 docstring

### PR DESCRIPTION
**Pull request by rohitsanj**
This PR is part of the [NumPy sprint](https://hackmd.io/r4pcf4CQRMOUY2VXOWk5_Q) at SciPy 2020

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
It might be nice to draw from the corresponding Examples in the `fft2`/`fftn` docstrings, since they use real-valued inputs anyways. For example, the `fft2` docstring uses the following example:

```python
>>> a = np.mgrid[:5, :5][0]
>>> np.fft.fft2(a)
<array output here>
```

I think there would be value in consistency between the `fft*` and corresponding `rfft*` examples (though repeating the full plotting example from the `fftn` docstring would not be necessary).

**Comment by mattip** [comment]
@rohitsanj ping

**Comment by rossbar** [comment]
@rohitsanj I took the liberty of rebasing this on master and proposing some different examples along the lines of my comment in 64847ed. Please feel free to comment on the updated examples!

**Comment by charris** [comment]
@rossbar Thoughts? This seems to have stalled out.

**Comment by rossbar** [comment]
This is good to go IMO - it doesn't seem like there were any objections from @rohitsanj

**Comment by charris** [comment]
In it goes. Thanks @rohitsanj .

**Pull request merged**
