### PR TITLE
DOC: fixed docstring for descr_to_dtype

### LINKED ISSUE #16673: Improperly-formatted docstring for numpy.lib.format.descr_to_dtype
The docstring for `numpy.lib.format.descr_to_dtype` does not conform to the `numpydoc` standard. Currently the docstring is not included in the documentation generated by sphinx. 

### Numpy/Python version information:

1.20.0.dev0+e7adb14 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]

### PR DESCRIPTION
**Pull request by i-am-b-soto**
Hi Numpy, 
This PR is a direct response to issue #16673

fixes #16673

### CODE REVIEW

**Comment by mattip** [comment]
This is an improvement. The [rendered page](https://14228-908607-gh.circle-artifacts.com/0/doc/build/html/reference/generated/numpy.lib.format.html#module-numpy.lib.format) for `lib.format` still does not create links for these functions, so much of this is never presented. @rossbar is there a quick fix to turn those into links (I am confused whether removing the template was enough?) or should we leave that to a separate PR?

**Comment by rossbar** [comment]
>  is there a quick fix to turn those into links (I am confused whether removing the template was enough?) or should we leave that to a separate PR?

I couldn't find a quick fix - removing the template is not sufficient. My recommendation would be to leave it for a later PR, perhaps after #16681 is also hammered out.

**Comment by mattip** [comment]
Thanks @Iamsoto

**Comment by Iamsoto** [comment]
Glad to help!

**Pull request merged**
