### PR TITLE
Fix PyArray_FillFunc function definitions

### PR DESCRIPTION
**Pull request by timfel**
These should return an integer, as required by the function typedef.

### CODE REVIEW

**Comment by mattip** [comment]
Is there a test checking the return value?

**Comment by eric-wieser** [comment]
Note that internally, we never check the return value of `->fill` anyway

**Comment by timfel** [comment]
@mattip There's no test, but if you think there should be, I can add one

**Comment by timfel** [comment]
@eric-wieser Indeed, but since the typedef says there should be a return value the more strict checks in Sulong (github.com/graalvm/sulong) warned that nothing was actually being returned.

**Comment by charris** [comment]
Looks like  `*_fillwithscalar` functions have the same problem. I suppose that the function definitions should actually use the typedef and the type casts removed from the structure initialization so that errors are raised at compile time. See all the casts in the same file.
```
    (PyArray_CopySwapNFunc*)@from@_copyswapn,
    (PyArray_CopySwapFunc*)@from@_copyswap,
    (PyArray_CompareFunc*)@from@_compare,
    (PyArray_ArgFunc*)@from@_argmax,
    (PyArray_DotFunc*)@from@_dot,
    (PyArray_ScanFunc*)@from@_scan,
    @from@_fromstr,
    (PyArray_NonzeroFunc*)@from@_nonzero,
    (PyArray_FillFunc*)@from@_fill,
    (PyArray_FillWithScalarFunc*)@from@_fillwithscalar,
```

Seeing as the declared type is used in `_rational_tests.c.src`, suggesting that users use the declared type, we probably need to change the definitions, as here, rather than the include file.

**Comment by timfel** [comment]
@charris Indeed. I can go and change those, too.

**Comment by charris** [comment]
Removing the function casts in the structure initialization does issue warnings during compilation. Lots and lots of warnings :)

**Comment by charris** [comment]
All the cast functions need fixing.

**Comment by charris** [comment]
But not all can be fixed. It seems that having a `NPY_UNUSED` argument ruins the type comparison.

**Pull request merged**
