### PR TITLE
MAINT: Use `*.format` for some strings.

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by charris** [comment]
I'm not convinced that we should make many these sorts of changes right now. There are a lot of places where it could be done, but we are trying to stay mostly back compatible with 1.16 for the time being.

**Comment by Abdur-rahmaanJ** [comment]
ok

**Comment by Abdur-rahmaanJ** [comment]
what python version are you using?

**Comment by eric-wieser** [comment]
This change seems harmless to me - I doubt that anyone is going to change `dual` before the 1.17 release anyway.

I'm not sure its a good use of reviewer time though to pursue future changes like this.

**Pull request merged**
