### PR TITLE
MAINT: Replace manual expansion of PyArray_MinScalarType with an inner helper function

### PR DESCRIPTION
**Pull request by eric-wieser**
…

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Looks good, though I think I'd just use a all lower-case name for the internal function, e.g., `array_min_scalar_type` (since this function is not used in any other file).

**Comment by eric-wieser** [comment]
That function name already exists, so I think that would be more confusing

https://github.com/numpy/numpy/blob/cddee1d4b688bdc16d337721b2bdcd4db66949fd/numpy/core/src/multiarray/multiarraymodule.c#L3382-L3401

**Comment by mhvk** [comment]
So much for that! Cannot think of a better name...  Maybe will let it sit till the end of the day in case anybody else has comments.

**Comment by eric-wieser** [comment]
The names _are_ static, so the compiler won't stop us giving them the same name - but I think for the sake of grepping, it's a bad idea

I could add a leading underscore to make it more obvious it's private

**Comment by mhvk** [comment]
I think the `_internal` makes the private aspect quite obvious; just would have preferred an all lower-case name
...  actually, the other use of `min_scalar_type_num`, in `can_cast_scalar_to`, also creates a `value`, does swapping, and creates a dtype. Maybe there is more room still for combining?

**Comment by charris** [comment]
We have a strange mix of CamelCase and lower case with underscore names for historical reasons. I suspect the CamelCase was originally taken over from cPython, while the lower case names are newer.

**Comment by eric-wieser** [comment]
>  Maybe there is more room still for combining?

I'd prefer to leave that for a future PR

**Comment by mhvk** [comment]
OK, looking at it a bit more closely I see there isn't as much obvious overlap. So, let's get this one in!

**Pull request merged**
