### PR TITLE
Added linfit function for linear least squares fitting

### PR DESCRIPTION
**Pull request by djpine**

### CODE REVIEW

**Comment by michaelaye** [comment]
Is this not going to happen?

**Comment by djpine** [comment]
I would like to make something like that happen.  I think SciPy would make
more sense but I ran into resistance last year when I tried to get it
accepted.  I'm willing to try again and if you want to help, that would be
great.

Dave

____________________________________________________________________

David Pine
New York University
Chair, Department of Chemical & Biomolecular Engineering
    NYU Polytechnic School of Engineering
Silver Professor of Physics
    NYU College of Arts & Science
Office (Brooklyn): 728 Rogers Hall [6 MetroTech Center, Brooklyn, New York
11201]
Office (Manhattan): 601 Meyer Hall [4 Washington Place, New York, NY 10003]
Tel:  646-997-3004 (Brooklyn)
Tel:  212-998-7744 (Manhattan)
Web: http://www.physics.nyu.edu/pine/Home.html
E-mail:  pine@nyu.edu
____________________________________________________________________

**Comment by michaelaye** [comment]
Do you have a public link to the discussions that happened? I would need to read the different arguments to make up my mind myself. ;)

**Comment by argriffing** [comment]
> I think SciPy would make more sense but I ran into resistance last year when I tried to get it accepted.

I searched `djpine` on scipy's github and found only https://github.com/scipy/scipy/pull/3098.

**Comment by djpine** [comment]
I'll find it and send it to you when I'm connected with more than my phone.
But the main point was this:  there is a linear regression routine in the
scipy stats package called linregress that "does the same thing".  However,
in my opinion, the problems are that it uses the r^2 test as a measure of
goodness of fit rather that chisquared and it does not allow for individual
weighting of data points (error bars that differ from point to point) in
determining the best fit.  Basically it's tailored for use according to the
practices of the social sciences (including economics) rather than the
physical sciences (notably physics). The suggestion was to add
functionality to the stats package routine so that it was suitable for both
uses.  I tried this but it results in inefficient ugly code as well as a
confusing interface. In fact, the two communities and their use of linear
fitting routines is essentially non-overlapping.  It makes much more sense
to keep the two separate in my opinion. The linear fitting routine I wrote
uses the same goodness of fit ideas as does the routine curve_fit and
belongs in the same part of scipy.  At least that's how I see it.

David Pine

**Comment by djpine** [comment]
Most of the discussion on linfit is here:

https://mail.scipy.org/pipermail/scipy-user/2013-December/035250.html

____________________________________________________________________

David Pine
New York University
Chair, Department of Chemical & Biomolecular Engineering
    NYU Polytechnic School of Engineering
Silver Professor of Physics
    NYU College of Arts & Science
Office (Brooklyn): 728 Rogers Hall [6 MetroTech Center, Brooklyn, New York
11201]
Office (Manhattan): 601 Meyer Hall [4 Washington Place, New York, NY 10003]
Tel:  646-997-3004 (Brooklyn)
Tel:  212-998-7744 (Manhattan)
Web: http://www.physics.nyu.edu/pine/Home.html
E-mail:  pine@nyu.edu
____________________________________________________________________

**Comment by seberg** [comment]
Since this is very old, and it seemed that the consensus was that the way to move this anywhere would be inside scipy, I will close this here. If anyone wants to reopen, feel free to comment.

**Pull request closed without merging**
