### PR TITLE
DOC: Add docstring for fastCopyAndTranspose (in _add_newdocs.py)

### PR DESCRIPTION
**Pull request by dbrs01**
Regarding fastCopyAndTranspose, I am not sure if the first line should be _add_newdoc('numpy.core.linalg', 'fastCopyAndTranspose',_ instead of _add_newdoc('numpy.core', 'fastCopyAndTranspose',_ since the definition of _fastCopyAndTranspose_ is in _linalg.py_.  Also, in _linalg.py_ (line 160) it says that the function assumes that the input array is two-dimensional, but it still works for multidimensional arrays.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
I wonder if the omission of a docstring wasn't intentional here in order to discourage users from using this directly... @charris do you have insights here? The camel casing is also strange and makes me think this might have been intended to be private?

**Comment by charris** [comment]
> The camel casing is also strange

That function has been around since the beginning, maybe before the beginning :) The documentation stub has been there since 2006. The `fastCopyAndTranspose` function is exported from `numpy/core/numeric.py` as an alias of `_fastCopyAndTranspose` and is not part of the documented public API, but is tested. The underscored version is part of multiarray and the same name is used for a different function in `linalg.py`. If we document it, it might be best to do that in numeric.py for `fastCopyAndTranspose` and leave `_fastCopyAndTranspose` hidden. It doesn't seem to be used much, but who knows about downstream.

Might be worth getting another opinion about this.  @seberg, @mattip thoughts?

**Comment by rossbar** [comment]
> It doesn't seem to be used much, but who knows about downstream.

FWIW I was curious so I grepped through some of the usual suspects (scipy, matplotlib, astropy, scikit-learn and scikit-image) and didn't notice any instance of `fastCopyAndTranspose` being used.

**Comment by mattip** [comment]
Maybe we can deprecate exporting it to the main namespace instead of documenting it?

**Comment by seberg** [comment]
I am in favor of deprecation as well.  It could make sense to have such a functionality if it was any faster, but it is not.  And my guess is that if we have a faster transposed copy functionality, we would use it in `arr.copy()` already.

**Comment by dbrs01** [comment]
OK! 
So, should I close the pull request and open an issue to deprecate the export of fastCopyAndTranspose?

**Comment by charris** [comment]
IIRC, the only place it is actually used is in `linalg.py`, so another method will need to be used there.

**Comment by mattip** [comment]
I would suggest two steps. In the first:
- deprecating exporting `core.multiarray_umath._fastCopyAndTranspose` as `fastCopyAndTranspose` in `numeric.py`. This means wrapping the function in a way to raise a deprecation warning.
- in linalg.py use `core.multiarray_umath._fastCopyAndTranspose`. This will take some care as there is a local `_fastCopyAndTranspose` for non-2d ndarrays
- move tests into `test_deprecated.py` and making sure all the tests pass (other tests will need adjustment too).

Then a later step would be to refactor the use of `_fastCopyAndTranspose` in linalg.py to replace it with `copy` and reshaping.

**Comment by charris** [comment]
close/reopen.

**Comment by charris** [comment]
The failing tests look like the git problem. They should go away on merge if the close/reopen doesn't work.

**Comment by charris** [comment]
The Cygwin test is fixed. The refguide checks are failing, the docstring needs major fixes.

**Pull request closed without merging**
