### PR TITLE
API: Make descr->f only accessible through ``PyDataType_GetArrFuncs``

### PR DESCRIPTION
**Pull request by seberg**
This is the reversion of the reversion.  With a follow up commit to move the definitions which now require `GetArrFuncs`.  Together with the other PR to make sure `npy_2_compat.h` is vendorable, this should make @tylerjereddy PR on SciPy work fine (I wanted to try it but ran into issues, so just opening for now no tested with SciPy).

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Ping @lithomas1 for pandas too

**Review by tylerjereddy — COMMENTED** [review]
Pasting from my commit message in https://github.com/scipy/scipy/pull/20108:

```
    * vendor in the latest version of the compat header from:
    https://github.com/numpy/numpy/pull/25897
    
    * with this adjustment and that branch, the following
    scenarios all have full test suite passing:
      - build + test against his feature branch with new header vendored
    into my branch
      - (with new header vendored in) build against his branch, test against 1.26.4
      - (with new header vendored in) build + test against 1.26.4
```

I think that's pretty good?

**Comment by ngoldbaum** [comment]
I pinged Thomas and he said he'd have a chance to look at the impact of this on pandas this weekend. Let's try to give pandas a chance to add the header in a PR that can be quickly merged before we merge this so there's a minimum amount of time where the numpy tests are broken because pandas is broken. I can't find any other maintained projects on github code search that this change will break, so once Pandas is ready I think we can merge this.

Please let me know if there are issues with that plan.

**Comment by lithomas1** [comment]
pandas-dev/pandas#57668 should fix pandas.

**Comment by ngoldbaum** [comment]
@lithomas1 let us know when you're ready and I'll merge this

**Comment by lithomas1** [comment]
We're hopefully good on the pandas side.

**Comment by rgommers** [comment]
Nice, Pandas could stop using `->f` complete, so that's problem solved. For SciPy we can't, so we're going to have to sync merges and wheel builds a bit. Looks like this is good to go though, and we can work through this later today.

**Review by rgommers — APPROVED** [review]
I just retested this with SciPy (with Tyler's changes), that works cleanly with this branch and also building against this branch and then running the SciPy test suite against NumPy 1.22.4 looks good.

Changes in the fixup commit LGTM, and the rest was already reviewed. So let's give this another go. Thanks @seberg & reviewers!

**Pull request merged**
