### PR TITLE
MAINT: Remove the misleading `np.division` and `np.print_function` inherited from __future__

### PR DESCRIPTION
**Pull request by eric-wieser**
These clutter the autocomplete, and are names that look very plausible as numpy features.

Also do this to every single file in numpy, for consistency.

---

I haven't found any precedent for doing this elsewhere, but it removes this confusing behavior for beginners exploring via autocomplete in ipython
image

### CODE REVIEW

**Comment by eric-wieser** [comment]
I suppose another option would be to use `del division, print_function, absolute_import` on the following line.

I could also limit this to just `numpy/__init__.py`

**Comment by hameerabbasi** [comment]
Wouldn't it be better to just have an `__all__` in each file? Or is that infeasible due to the number of symbols?

**Comment by mattip** [comment]
> I could also limit this to just `numpy/__init__.py`

I am confused, `numpy/__init__.py` **has** an `__all__`, so how is autocomplete picking the offending imports?

**Comment by hameerabbasi** [comment]
I'm assuming the `__all__` for other modules include it, and we're adding those to `numpy.__all__`

**Comment by mattip** [comment]
`'print_function' in np.__all__` => False and yet there it is in autocomplete

seems like a known feature in autocomplete, [maybe configurable in IPython](https://github.com/ipython/ipykernel/issues/129)

**Comment by hameerabbasi** [comment]
In that case, I really don't think this PR is worth it (fixing an idiosyncrasy of one tool, going against convention and increasing maintenance costs). Instead, we should prod IPython devs to respect norms (at least by default).

**Comment by mattip** [comment]
I am not opposed to merging this, but it is just the tip of the autocompletion iceberg.
``np.lib.te<tab>`` completes to ``np.lib.test`` but ``'test' in np.lib.__all__`` => False

**Comment by mhvk** [comment]
I'm :-1: on this change; it goes too far to break convention of how to import from `__future__` just because  auto-completion does not do the right thing.  (Fortunately, this problem will resolve itself anyway in about 7.5 months from now.)

**Comment by charris** [comment]
I'm :-1: on this also, I don't think the gain is worth the unconventional churn, and as has been said, all to work around a IPython autocompletion. My feeling is that we should let Python 2.7 go gentle into that good night.

**Comment by eric-wieser** [comment]
Sounds like consensus to me

**Pull request closed without merging**
