### PR TITLE
cov and corrcoef: add support for weights

### PR DESCRIPTION
**Pull request by ndawe**
Given that `average` supports weights [1], and that when searching around there have been requests [2] for implementations of weighted covariance, I think it would be beneficial to also support weights in `cov` and `corrcoef` [3, 4].

[1] http://docs.scipy.org/doc/numpy/reference/generated/numpy.average.html
[2] http://stackoverflow.com/questions/11442962/python-package-that-supports-weighted-covariance-computation
[3] http://stats.stackexchange.com/a/61298/29084
[4] https://en.wikipedia.org/wiki/Weighted_arithmetic_mean#Weighted_sample_covariance

### CODE REVIEW

**Comment by charris** [comment]
Frankly, I'd just have one weight and let the user set up the correct value, but that may be a bit much...

**Comment by ndawe** [comment]
Yes, I quite frankly think that people are overthinking this. That's my feeling based on the discussion above.

**Comment by ndawe** [comment]
In the meantime I've moved on with my private implementation since it became clear that this would take more time than it's worth to get pushed into numpy. It's a weighted covariance... not that hard. Give users the ability to specify one type of weights (or just two, with frequencies) and let them set up the weight values according to what they need. Done.

**Comment by seberg** [comment]
Maybe.... I am fine with just one weight as long as the documentation is clear about what it is and what it is not. And possibly a link to somewhere explaining how you would get the other stuff.

**Comment by charris** [comment]
Still thinking about this and researching the topic.

**Comment by charris** [comment]
I'm thinking a combination of two weights, repeat and reliability, and ddof. The weights can be combined, but not by simple multiplication, at least for the correction factor in @ndawe formula above. The sum of squared weights needs to be replaced by `ddof * sum(n * r**2)`, where `n` are the repeat weights and `r` are the reliability weights. I'm not sure what ddof does in the reliability case, but ddof=1 will give the unbiased estimate in all cases..

**Comment by charris** [comment]
Closed by #4960.

**Pull request closed without merging**
