### PR TITLE
DEV: adding unbias option to the correlate function #6041

### PR DESCRIPTION
**Pull request by jankoslavic**
This is a pull request with regards to the issue:
https://github.com/numpy/numpy/issues/6041#issuecomment-118527975

### CODE REVIEW

**Comment by seberg** [comment]
General question, but should we have a `ddof` as well, or maybe even only the `ddof`?

**Comment by jankoslavic** [comment]
I think the ddof would make no sense here. The bias=False option is useful for periodic signals only (in this case the (time) correlation needs to be divided by the "number of observations". The number observations is N only when the signals fully overlap (and decreases to 1 at the edge).

I guess it would be fine to add the comment: the bias=False should be used for periodic signals, only.

**Comment by seberg** [comment]
Oh, sorry, yes. This is a very different thing then the bias in the statistical functions.

**Comment by mattip** [comment]
Closing as this has stalled. If someone wants to champion it they should ask on the mailing list (since it enhances the API). Or perhaps there already was a discussion?

**Pull request closed without merging**
