### PR TITLE
DEP: deprecate np.testing.dec

### LINKED ISSUE #17566: DOC: mark np.testing.dec functions as not recommended for future use
Given that

> ... the [`np.testing.dec`] decorators are only retained for folks using the old nose framework and will be removed as some point, nose doesn't work with recent Python without modification. Most distros no longer provide nose, but rather nose2.
> 
> _@charris in https://github.com/numpy/numpy/pull/16370#r494495147_

I think we should update the docs at https://numpy.org/devdocs/reference/routines.testing.html#decorators to make this clear.

We might also want to consider deprecating them fully with `DeprecationWarning`s

### PR DESCRIPTION
**Pull request by rpolley**
Per #17566 the decorators in `numpy.testing.dec` are intended for compatibility with the nose testing framework, and should discouraged in the documentation, if not outright deprecated. This pull request updates the documentation of these decorators with a deprecation warning telling people not to use the nose testing framework, adds a deprecation warning to them saying the same, and moves the tests to `numpy/core/tests/test_deprecated.py` and wraps them in an assert_deprecated check.

Closes: #17566

### CODE REVIEW

**Comment by rgommers** [comment]
This makes sense, it's about time. To be sure, can you please send an email to the numpy-discussion mailing list about this? All deprecations need to go through the mailing list for approval.

**Comment by rpolley** [comment]
I created [a discussion](http://numpy-discussion.10968.n7.nabble.com/Deprecate-np-testing-dec-td48809.html) on the mailing list for this pull request.

**Comment by mattip** [comment]
@rpolley I  am pretty sure we don't install nose for testing, so the moved tests were not actually run before this PR, and are not being run in it. Did you try it to make sure the deprecations work as advertised?

**Comment by charris** [comment]
> we don't install nose for testing

I removed it from the CI testing while back, it used to be there.

**Comment by mattip** [comment]
Checked locally, all looks good.

**Comment by mattip** [comment]
Thanks @rpolley

**Pull request merged**
