### PR TITLE
DOC: Add docstrings for consistency in aliases

### LINKED ISSUE #9183: np.conj vs np.conjugate
Both ``numpy.conj`` and ``numpy.conjugate`` exist, and in fact the docs for ``conj`` show examples that use ``conjugate``:

https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.conj.html

Furthermore, the page for numpy.conjugate doesn't exist. It would be nice to make this more consistent, e.g. change the examples in for the ``conj`` page to use ``conjugate``, or add a note to the ``conj`` docs that either can be used.

### PR DESCRIPTION
**Pull request by kritisingh1**
Closes #9183

### CODE REVIEW

**Comment by mattip** [comment]
Since the docstring for [`conj`](https://6740-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/reference/generated/numpy.conj.html) and [`conjugate`](https://6740-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/reference/generated/numpy.conjugate.html) is shared, the `See Also` will be wrong for one of them. I think it would be better (and less wordy) to leave it out, the Note is sufficient since it has links for both.

**Comment by eric-wieser** [comment]
I wonder if this is something that Sphinx or numpy-doc should handle?

**Comment by rgommers** [comment]
> I wonder if this is something that Sphinx or numpy-doc should handle?

I don't think so. That machinery is already hard to maintain and understand. It doesn't have much context in many places. Making it aware of things like aliased functions will be a major change that doesn't really fit.

**Comment by kritisingh1** [comment]
@mattip I removed the `See Also` section as you said and the travis builds are timing out now. I'm not sure what the reason might be. Could you help me with that? Thanks!

**Comment by mattip** [comment]
Restarted the travis build, it is green now. Merging. Thanks @kritisingh1

**Pull request merged**
