### PR TITLE
Fixed a typo in np.inner doc

### PR DESCRIPTION
**Pull request by samuelstjean**
Found this while reading the doc.

### CODE REVIEW

**Comment by seberg** [comment]
Thanks, for the next time, we normally prepend such a commit with `DOC: `, see also:
http://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message

(If you wish to train your git foo a bit, I will leave it open for a little bit)

**Comment by samuelstjean** [comment]
Oh, actually I just did a lazy web based edit and do not have a local copy of numpy to edit the commit message, but thanks anyway for the suggestion.

**Comment by seberg** [comment]
ok, something to remember for next time ;). Thanks!

**Comment by charris** [comment]
Perhaps we should put some commit notes in the `README.md` file.

**Pull request merged**
