### PR TITLE
ENH: add automated arange conversion to numpy.lib.index_tricks.ix_

### PR DESCRIPTION
**Pull request by bijlpieter**
Dear numpy team,

The following PR contains an implementation for a small enhancement to [`np.ix_`](https://numpy.org/doc/stable/reference/generated/numpy.ix_.html). This would make it possible to use integers directly to generate an open index mesh. This is much like how [`np.permutation`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html) used with an integer permutes `np.arange(x)`.

I've found myself needing to generate an index mesh based on (part of) the shape of an array. This usually results in something like
```
x, y, z = arr.shape[:3]
out = np.ix_(np.arange(x), np.arange(y), np.arange(z))
# or
out = tuple(np.ogrid[:x, :y, :z])
```
both of which feel unnecessarily complex. Why not allow `np.ix_(x, y, z)` or similarly `np.ix_(*arr.shape[:3])`? If `np.ix_` accepts integers `i` to be interpreted as `np.arange(i)`, this would be possible. I don't see any competing interpretations of `np.ix_` used with integers.

I have
- added an implementation for the proposed behavior to `np.ix_`,
- added a separate error message for inexact dtypes (all of which currently trigger the 1d sequence only exception) to indicate only integral scalars are valid for this purpose,
- adapted the docstrings where relevant, and
- added tests to verify the expected behavior.

Any thoughts or feedback is appreciated. Please let me know if anything needs to be added or changed.

With best regards,

Pieter

### CODE REVIEW

**Comment by bijlpieter** [comment]
Apologies for the linting error... missed it but fixed it

**Comment by seberg** [comment]
Thanks for opening a PR.  To be honest, I am not quite convinced of tagging this on to `np.ix_`, unfortunately.

My main reason is that `np.ix_` is advertised to be useful with indexing (also since it has boolean support).  The problem with that is that a scalar integer would have a very different meaning in that context.

**Comment by bijlpieter** [comment]
Hi @seberg ,

Thank you for your response. I had not yet considered that point of view, and agree with your sentiment. My experience with `np.ix_` has been primarily for ease-of-use in facilitating correct broadcasting of advanced indices (like you mention, integer/boolean arrays). Those are then combined afterwards into a tuple with basic indices (integers, slices) for the final indexing operation. In that sense, converting an integer `x` inside `np.ix_` to `np.arange(x)` seemed logical to me.

That being said, my intention is not to create a confusing API. Do you think there is any merit to adding this functionality in a new function or index trick? Or would its use case be too much of a niche to be considered for numpy?

**Comment by seberg** [comment]
I have not really made up my mind on this being useful or what an alternative should be.  I will note that starting on Python 3.11, it should be possible to write:
```
object[*index,]
```
(not sure if the trailing comma is needed).

About ogrid returning a list: this is something I expect we will change in the mid-term at least (few users should notice anyway), at least for a 2.0 release that would hopefully be the one after 1.25.  (Honestly, it is small enough a change I would be willing to do it for a normal release.)

Overall, I lean towards accepting integers fitting better to `np.ogrid` and `np.mgrid` then `np.ix_`.

**Comment by seberg** [comment]
Going to close this for now, happy to reopen if others are interested in it.  There was also an old PR somewhere, I think that suggested the addition of an `ndrange()` function.

Who knows, maybe an `ndrange` function could be a sane, integer-only, alternative to `arange`...

**Pull request closed without merging**
