### PR TITLE
sync release notes

### PR DESCRIPTION
**Pull request by juliantaylor**
add forgotten 1.9.2 notes and missing index add

the first commit should also go into the 1.10 branch, @charris do you want it rebased onto the merge base?

### CODE REVIEW

**Comment by charris** [comment]
> do you want it rebased onto the merge base?
I'd prefer not. I looked at the git log graph we ended up with in 1.9 and the lines heading into the past covered almost the full width of my (wide) screen. I'll just cherry-pick the one commit.

**Comment by charris** [comment]
Thanks Julian.

**Comment by juliantaylor** [comment]
That happens anyway with pull requests, scipy is "worse" and they don't even do the rebase thing. I think thats worth seeing exactly which commits are in which branch, but its your decision this time.

**Comment by charris** [comment]
I'm also hoping that the next release is sooner, so that there will be less to backport.

**Pull request merged**
