### PR TITLE
BUG: `take` casting logic with an `out=` argument

### LINKED ISSUE #16319: BUG: `take` casting logic with an `out=` argument
From the related PR: #4246

> When it receives an out argument, np.take converts the out array to

> the dtype of the array being taken from. This results in wrong TypeErrors
> being raised when out has a larger dtype than the array (and not being
> raised when it has a smaller dtype, even though they should):

> >> a = np.arange(3, dtype=np.int16) + 128
> >> b = np.empty((3,), dtype=np.int8)
> >> a.take([0, 1, 2], out=b) # wrong, should raise an error
array([-128, -127, -126], dtype=int8)
> >> b = np.empty((3,), dtype=np.int32)
> >> a.take([0, 1, 2], out=b) # perfectly OK, but raises an error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array data from dtype('int32') to dtype('int16') according to the rule 'safe'
This PR makes an explicit casting check, then either sets NPY_ARRAY_FORCECAST
or explicitly raises the error.

The tests added check the logic for conversion between all pairs of ints and
floats only.

Please see the related PR for the existing work on the issue.

### PR DESCRIPTION
**Pull request by royJackman**
Closes #16319

### CODE REVIEW

**Comment by eric-wieser** [comment]
This perhaps fixes `np.ma.take`, but we should really be fixing `np.ndarray.take` - if we fix that one, then we'll likely get the others fixed for free.

Unfortunately fixing that function will require diving into the C code.

**Comment by royJackman** [comment]
Would it make sense to write a new function to check that the array elements are within the bounds of the <code>PyArray_Descr</code> range or try and throw better errors using the existing <code>PyArray_CanCastTypeTo</code> function?

**Comment by seberg** [comment]
`CanCastTypeTo` is the right approach here, it might make sense to deprecate it, since right now its strange but effectively allows unsafe casts.

**Comment by royJackman** [comment]
The quickest way to port the same fix to the C code could be to add a sixth casting type along the lines of <code>NPY_RANGED_CASTING</code> and add another <code>else if</code> to the <code>PyArray_CanCastTypeTo</code> function.
If it isn't that important to be able to take from a larger size to a smaller one assuming all the values in the input table are within the range of the output dtype, it seems like it's a fix that can be added to the <code>else if (casting == NPY_SAFE_CASTING || casting == NPY_SAME_KIND_CASTING)</code> clause.
If the whole function needs to be rewritten, then good luck to the poor soul who takes that challenge on 🙏

**Comment by seberg** [comment]
@royJackman we do not inspect values for casts, so there is no wish to add such a casting mode or the necessary complexity.
(We currently do such casting for scalars, but consensus around that is that we should roll that back to some degree – i.e. it may be OK for Python integers/floats, but not for our own scalars which have a dtype.)

We can choose either safe or same kind casting here, I think we currently default to `safe` in ufuncs, so that is probably the best.

The tests seem good (would be good to have similar tests outside the `ma` module also).  I assume we will go the deprecation route here before the end (i.e. keep things as they are but give a warning for unsafe casts), but that will not be difficult to do once we have the first change.

**Comment by rossbar** [comment]
Adding the close label as it seems that fixing `np.ndarray.take` is the preferred, more general fix.

**Comment by mattip** [comment]
Closing. The test here is good but the fix should be done elsewhere.

**Pull request closed without merging**
