### PR TITLE
NVO: New vector operators: Divergence, Curl and Laplacian added to fu…

### PR DESCRIPTION
**Pull request by ghost**
Hello, in this contribution I have added the functions divergence, curl and laplacian, which I have missed when using numpy myself. They use the same method as the existing gradient function to calculate central differences and keep the input array shape. This is my first contribution to github, I would appreciate any comment if I did anything wrong. I added the source code only to function_base.py, the only place where I found the gradient function

Thanks,
Antonio

### CODE REVIEW

**Comment by charris** [comment]
For new functionality you should post a proposal on the mailing list for discussion. Of course, it doesn't hurt to have a PR to point to.

**Comment by jaimefrio** [comment]
I'm not sure of where things went wrong, but your PR shows up as you having added 4764 lines and removed 141, to `function_base.py`, so changes are not displayed, making it very hard to review your code.  For one, you should have developed your changes on a feature branch, not directly on master of your fork. Have you followed the [contributing guidelines](http://docs.scipy.org/doc/numpy-dev/dev/)?

**Comment by pv** [comment]
There's this: https://github.com/numpy/numpy/pull/6716.diff
It seems numpy/core/function_base.py was replaced by accident by numpy/lib/function_base.py

**Comment by antlarac** [comment]
Thank you for your comments! Yes it seems that I messed up at some point. I will start again and inform in the mailing list.
Thanks

**Pull request closed without merging**
