### PR TITLE
DOC: Update the docstring of asfortranarray and ascontiguousarray

### PR DESCRIPTION
**Pull request by teoliphant**
Fix for #5300 and a different approach to deprecation which is proposed here: #12244

### CODE REVIEW

**Comment by rgommers** [comment]
The first commit looks fine to me, modulo the unwanted indentation on the line under `Note:`.

The second commit reverts the first one - accidental?

**Comment by charris** [comment]
@teoliphant This does nothing at the moment, no changes at all.

**Comment by charris** [comment]
Somehow you seem to have run `git revert`

**Comment by charris** [comment]
@teoliphant You can get back to the first commit with `git reset --hard HEAD^`. You probably want the reset the master branch all the way to the beginning though, because all PRs should come from a branch, not your master. So maybe stating in master, do something like
```
git pull upstream --force master  # will clean up your master branch
git checkout -b  update-isfortranarray-docstring  # make a working branch and check it out
...
```

**Comment by teoliphant** [comment]
Closed and replaced by #12301

**Pull request closed without merging**
