### PR TITLE
ENH: Option to return covariance matrix of fitted coeffecients for polynomial fitters (#7780)

### PR DESCRIPTION
**Pull request by eliottrosenberg**
Implements the enhancements from @tom-bird in 2016 (https://github.com/numpy/numpy/pull/7880) so that the polynomial fitters in the polynomial module can return covariance matrices of the fitted parameters. (One slight difference from what @tom-bird did is that I removed a -2 in the denominator for consistency with polyfit.)

See issue #7780

### CODE REVIEW

**Comment by seberg** [comment]
If we are to move forward here, we need to base this on top of the old PR (using those commits) and then clean up the history at least a bit.
That will require rebasing/squashing the commit the command line (or similar) and not on github directly.

@eliottrosenberg if you wish to follow-up, please let us know, otherwise I think we will just close the PR soon unfortunately.  One very helpful alternative you could do is review the original PR noting any changes you did or would suggest.

**Comment by eliottrosenberg** [comment]
I'm happy to note what I changed from the old PR.

**Comment by eliottrosenberg** [comment]
@seberg Do you mean that I would be added as a reviewer to the original PR?

**Comment by seberg** [comment]
Yes, that would be cool.

**Comment by eliottrosenberg** [comment]
How do I get added as a reviewer?

**Comment by InessaPawson** [comment]
> How do I get added as a reviewer?

@eliottrosenberg Please submit your suggestions to the original PR: https://github.com/numpy/numpy/pull/7880. (Here is the official GitHub documentation on how to do it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request.) If accepted, you will automatically be added as a co-author.

**Pull request closed without merging**
