### PR TITLE
DEV: remove travis 32 bit job since it is running on azure

### PR DESCRIPTION
**Pull request by mattip**
We now have an [Azure job](https://dev.azure.com/numpy/numpy/_build/results?buildId=1222) to test linux 32 bit, let's remove the job it replaces from travis

### CODE REVIEW

**Comment by charris** [comment]
@tylerjereddy Should we recommend docker rather than chroot for these types of tests?

**Comment by tylerjereddy** [comment]
As far as I can tell both approaches (Docker and chroot) share the host kernel. It seems that Docker is [likely providing somewhat better "isolation"](https://stackoverflow.com/a/46450498/2942522) from the host, so maybe reducing the likelihood of accidental 64-bit things polluting the build is a good justification for using Docker.

One suggestion for making the clean-up in this PR more comprehensive -- `tools/travis-test.sh` contains a bunch of code & comments for 32-bit chroot build. There's an entire `setup_chroot()` function that I suppose can likely be deleted now, and probably the logic that handles dispatch to that function as well.

**Comment by mattip** [comment]
removed chroot from `travis-test.sh`

**Review by tylerjereddy — APPROVED** [review]
LGTM -- removes 60 lines of extraneous code / comments & I checked that Travis matrix is down to 11 entries from 12 on master.

**Comment by charris** [comment]
Docker looks more portable and easier to maintain, so lets go with that for now. Thanks Matti.

**Comment by charris** [comment]
Might be worth moving a few more things to azure. Travis gives us 5 parallel slots, so if we get down to <= 10 jobs we might save a couple or 5 minutes.

**Comment by charris** [comment]
There are also some tests that that look like they could be consolidated.

**Pull request merged**
