### PR TITLE
DOC: RST definition list fixes

### PR DESCRIPTION
**Pull request by endolith**
also add a more obvious example to the HOWTO

### CODE REVIEW

**Comment by charris** [comment]
What happens if the colon is left in? Note that we don't use rst, the docstring format is converted before rendering and I wonder if that should be fixed to work with the colon all the time. Also, note the commit message formatting documented in `doc/source/dev/gitwash/development_workflow.rst`

@pv Thoughts?

**Comment by endolith** [comment]
> What happens if the colon is left in?

It's not rendered as a definition list anymore, such as `message` and `explain` here: 

http://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.quad.html#scipy.integrate.quad

There should be only be a colon if there's a classifier after it:

http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#definition-lists

**Comment by charris** [comment]
@endolith My point was that the docstrings are not rst, so another place a fix could be made would be in `numpydoc`, which presumably could be modified to handle the empty string after the colon. That's why I pinged @pv.

**Comment by pv** [comment]
Perhaps (maybe file an issue to numpydoc tracker for this).
OTOH I don't see problems in merging this as a workaround.

**Comment by charris** [comment]
Thanks @endolith .

**Comment by charris** [comment]
I opened an issue for numpydoc.

**Pull request merged**
