### PR TITLE
Check lower base limit in base_repr.

### PR DESCRIPTION
**Pull request by nbeaver**
A minor fix to ensure the range is as expected. (This is my first pull request, so let me know if I missed something in the protocol.)

### CODE REVIEW

**Comment by jaimefrio** [comment]
It would be nice to add a test that the error is properly raised somewhere [here](https://github.com/numpy/numpy/blob/maintenance/1.10.x/numpy/core/tests/test_numeric.py#L877). Also, since you are working on this function, the docstring comment on it only handling positive `number`s seems to be wrong, would be nice if you could fix that too. Otherwise, LGTM.

**Comment by charris** [comment]
Should squash the commits. Use `git rebase -i HEAD^^' in the branch and follow directions, then force push to origin.

**Comment by charris** [comment]
Also needs a test for raising the error. Should go in `numpy/core/tests/test_numeric.py`.

**Comment by rgommers** [comment]
@nbeaver could you please address the comments? It would be good to get this PR merged.

**Comment by nbeaver** [comment]
@jaimefrio I have fixed the docstring and added the test as requested. However, the test seems to have added a merge conflict.

@charris I have squashed the commits.

@rgommers Thanks for the reminder.

**Comment by charris** [comment]
Thanks @nbeaver .

**Pull request merged**
