### PR TITLE
BUG：``np.sqrt`` return no_masked array 

### LINKED ISSUE #25635: BUG: `sqrt(ma.masked)` returns non-masked array
### Describe the issue:

In numpy 2.0 nightly, applying sqrt() to a fully masked scalar array undoes the mask.
numpy 1.26.3 behaves correctly.
Other ufuncs seem to behave correctly (but I haven't performed a thorough test for all of them).

### Reproduce the code example:

```python
>>> import numpy as np
>>> a = np.ma.masked_array(1, mask=True)
>>> type(a)
numpy.ma.core.MaskedArray

>>> np.sqrt(a)
# numpy 2.0
masked_array(data=1.,
             mask=False,
             fill_value=1e+20)
# numpy 1.26.3
masked_array(data=--,
             mask=True,
       fill_value=1e+20,
            dtype=float64)

>>> np.sqrt(np.ma.masked)
# numpy 2.0
masked_array(data=0.,
             mask=False,
             fill_value=1e+20)
# numpy 1.26.3
masked_array(data=--,
             mask=True,
       fill_value=1e+20,
            dtype=float64)
```

### Error message:

_No response_

### Python and NumPy Versions:

CPython 3.12.1 x86_64
numpy 2.0.0.dev0+git20240113.d2f60ff

from
python -m pip install --no-deps --pre -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy 
as of 2024-01-19

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by fengluoqiuwu**
Add mask copy to `__array_wrap__` if context is `None`.

I believe this is the correct approach, but I'm not entirely confident. The method `__array_wrap__` lacks both a proper explanation in the [documentation](https://numpy.org/devdocs/reference/generated/numpy.ma.MaskedArray.__array_wrap__.html#numpy.ma.MaskedArray.__array_wrap__) and in the code itself, which greatly impedes understanding and thorough testing.

```python
    def __array_wrap__(self, obj, context=None, return_scalar=False):
        """
        Special hook for ufuncs.

        Wraps the numpy array and sets the mask according to context.

        """
```

That said, the bug has been fixed with this PR, and all tests have passed on my computer. However, to be honest, I remain concerned about this method since many other methods call it. It could potentially lead to issues if not handled carefully.

Fixes #25635

### CODE REVIEW

**Comment by seberg** [comment]
Did you test this?  Please make sure to add tests to your PR, it is needed to merge, but also helps a lot with review.
While it may make sense to add it, I would expect `context` to *not* be `None` here and this change do nothing about `np.sqrt`.

There are some other things here.  I am not sure that this isn't already included in earlier code and it would probably be wrong, because the result array shape may not match the input one.  The mask may not make any sense at all, even if we want to guess at it making sense.

**Comment by fengluoqiuwu** [comment]
I believe this relates to [issue25635](https://github.com/numpy/numpy/issues/25635). When we run the following test code:

```python
Copy code
>>> import numpy as np
>>> a = np.ma.masked_array(1, mask=True)
>>> type(a)
>>> np.sqrt(a)
```
We get:

```python
Copy code
masked_array(data=1.,
             mask=False,
       fill_value=1e+20) # current code

masked_array(data=--,
             mask=True,
       fill_value=1e+20,
            dtype=float64) # PR code
```
So, I'm not sure if I'm misunderstanding the issue. Is this the expected result?

While it does raise a runtime warning:
```python
Copy code
<ipython-input-3-491a5a0a5603>:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  np.sqrt(np.ma.masked)
```

This warning is also present in the current implementation, and I think it may be a separate issue unrelated to the changes proposed in this PR.

**Comment by fengluoqiuwu** [comment]
As for:
```python
np.sqrt(np.ma.masked)
```

I didn't get any exception, but just the same warning:
```python
masked_array(data=0.,
             mask=False,
       fill_value=1e+20) # current code

masked_array(data=--,
             mask=True,
       fill_value=1e+20,
            dtype=float64) # PR code
```

**Comment by seberg** [comment]
I think you have to dig into that warning and using `import warnings; warnings.simplefilter("raise", DeprecationWarning)` and rerunning the code.

Something else is wrong.  Doing this will (hopefully, I don't recall the exact code), tell you more about what is going on.
The fact is we try to pass `context`, and incorrectly, give up on it.  It may be that the error matching in the C code is too fuzzy or something else is off.  But even in that case there is at least a `TypeError` being raised somewhere and that in itself seems off.

**Comment by fengluoqiuwu** [comment]
> Something else is wrong. Doing this will (hopefully, I don't recall the exact code), tell you more about what is going on. The fact is we try to pass `context`, and incorrectly, give up on it. It may be that the error matching in the C code is too fuzzy or something else is off. But even in that case there is at least a `TypeError` being raised somewhere and that in itself seems off.

It seems we're encountering another type issue. The method `domain` returns an array of np.float64, and when using the bitwise OR operator (`|`) with another array, it raises a runtime warning.

```python
Copy code
np.copyto(result, fill_value, where=d)

# Update the mask
if m is nomask:
    m = d
else:
    # Avoid modifying in place to prevent back-propagation
    m = (m | d)  <----- There
```
I'm also curious about how this results in an error indicating that the context is None... It's so strange.

**Comment by fengluoqiuwu** [comment]
Another strange thing is that with current code a `TypeError` was expected to occur, but in fact, it did not. I cannot reproduce this situation in the test file.

**Comment by fengluoqiuwu** [comment]
A better way to fix. 
Compare function in `numpy` has return type check but in `umath` hasn't, so if enter a masked_array with all elements masked to `umath.*`, it won't change the return type. This cause the bug.

**Comment by seberg** [comment]
@fengluoqiuwu there are so many PRs, I will just close this.  Let's continue discussion on the issue for now.  The `np` to `umath` change does nothing and moving the mask copy doesn't look thought through, so right now I think this is in a brainstorming and we don't need a PR for that.

**Comment by fengluoqiuwu** [comment]
> @fengluoqiuwu there are so many PRs, I will just close this. Let's continue discussion on the issue for now. The `np` to `umath` change does nothing and moving the mask copy doesn't look thought through, so right now I think this is in a brainstorming and we don't need a PR for that.

@seberg I sincerely apologize for pushing the wrong version of the branch to the PR without checking.

What I meant to convey is that adding `astype(np.bool)` can help avoid the `DeprecationWarning` and fix the bug. I'm unsure why `umath.less` and `np.less` return an `ndarray` with `dtype = np.float64` in the context of the ma domain class; it seems like there may be an issue with type conversion, and I couldn't reproduce it.

Regarding "moving the mask copy," it can be undone without affecting the bug fix.

I would appreciate your guidance on what to do next. Should I reopen a PR at an appropriate time? And should I add a test for the bug? Thank you for your understanding and patience.

**Comment by fengluoqiuwu** [comment]
This is the result of code with the PR, and I think that is what we need:
```python
>>> import numpy as np
>>> 
>>> a = np.ma.masked_array(1, mask=True)
>>> print(repr(np.sqrt(a)))
masked
>>> a = np.ma.masked_array([1., 2.], mask=[True, False])
>>> print(repr(np.sqrt(a)))
masked_array(data=[--, 1.4142135623730951],
             mask=[ True, False],
       fill_value=1e+20)
```

**Comment by fengluoqiuwu** [comment]
> @fengluoqiuwu there are so many PRs

Regarding the number of PRs, how many should I keep open? If I fix a bug but there are many PRs waiting for review and merge, what should I do?

**Pull request closed without merging**
