### PR TITLE
ENH: Validate dispatcher functions in array_function_dispatch

### PR DESCRIPTION
**Pull request by shoyer**
They should have the same signature as the decorated function.

Note: eventually these checks should be optional -- we really only need them to be run as part of NumPy's test suite, not every time numpy is imported.

### CODE REVIEW

**Comment by shoyer** [comment]
@mhvk lt would be great if you could take a look here

**Comment by charris** [comment]
Test failure is not relevant. Close/open to trigger new tests.

**Comment by mhvk** [comment]
@shoyer - this looks good. I'm only wondering whether we need the `check_signature` argument at all - if we're going to turn it off outside of testing, it might make more sense to start with having it always on, and then adding an `if` statement that uses some internal global variable that is set to `True` if tests are run. (More generally, not introducing the variable now allows us flexibility later on how we want to do this.)

If we do go with the keyword argument, how about `verify_signature` or plain `verify`?

Obviously, none of this is a big deal!

**Comment by shoyer** [comment]
@mhvk I originally omitted the keyword argument, but found it handy when writing decorators for functions that forward to other implementations, e.g., see
https://github.com/shoyer/numpy/blob/array-function-easy-impl/numpy/core/fromnumeric.py#L3383-L3392
https://github.com/shoyer/numpy/blob/array-function-easy-impl/numpy/lib/ufunclike.py#L45-L147

If we do turn this off outside of testing, we should document that `verify=True` does not guarantee that verification is done, unless the right global/environment variable is set. But I'll hold off on this until/when we notice an actual impact on import times.

I'll switch the keyword argument name to `verify`, I agree that's a little better.

**Review by mhvk — APPROVED** [review]
OK, actual examples of the keyword being useful definitely win the day! Agreed also that we should not worry about the bit of extra time unless we find it is actually significant. I think this is ready to go in, though perhaps a rebase to a single commit is a good idea.

**Review by hameerabbasi — APPROVED** [review]
This looks perfect to me -- There should probably be an evironment variable provided that turns verification on by default. I prefer this so implementations could be kept in line with NumPy when testing without having user code break.

**Comment by shoyer** [comment]
@hameerabbasi Yes, I agree that an environment variable would be the way to go here (especially if/when we make `array_function_dispatch` public API for the use of downstream libraries)

**Comment by shoyer** [comment]
Remind me, are we OK using the "Squash and merge" workflow on GitHub? I like it because it puts everything into one atomic commit per pull request, but preserve the history of commits when reviewing a pull request (which is lost when rebasing).

I know @charris probably has opinions here.

**Comment by charris** [comment]
Squash and merge is enabled, so we allow it.

**Comment by shoyer** [comment]
@hameerabbasi @mhvk thanks for reviewing this!

**Pull request merged**
