### PR TITLE
NEP: remove broadcast syntax from gufunc signature

### PR DESCRIPTION
**Pull request by mattip**
The consensus on the mailing list leaned against the broadcast part of the gufunc syntax extension. This PR moves it to the `Alternative` section of the NEP.

### CODE REVIEW

**Review by mhvk — COMMENTED** [review]
@mattip - thanks for the PR. It looks good except that at the start of the abstract there is also mention of three extensions.  Are we really not better off just with the note I put in?

**Comment by mattip** [comment]
I have no real preference either way, I just wanted to clarify what it is we are proposing when we ask the mailing list for approval.

**Comment by mhvk** [comment]
I thought we had asked the mailing list, and 1,2 but not 3 was the conclusion!

**Comment by mattip** [comment]
Right so the next step is to put the NEP up for approval via mail, like [this](https://mail.python.org/pipermail/numpy-discussion/2018-July/078380.html)

**Comment by mhvk** [comment]
But I did ask that already: https://mail.python.org/pipermail/numpy-discussion/2018-July/078404.html

**Comment by mattip** [comment]
whoops, slipped by me sorry. Closing in favor of PR #11429

**Pull request closed without merging**
