### PR TITLE
MRG: preparations for 1.9.3 release

### PR DESCRIPTION
**Pull request by matthew-brett**
Backport of 7d6aa8c - gzip fix for Python 3.5
Backport of b08f369 - numpy.distutils patch to help homebrew

### CODE REVIEW

**Comment by matthew-brett** [comment]
Linux travis build passing.

Successful OSX wheel builds : https://travis-ci.org/matthew-brett/numpy-wheels/jobs/81102106

@cgohlke - would you mind testing?

**Comment by njsmith** [comment]
LGTM, do you want to wait on word from @cgohlke before merging?

**Comment by matthew-brett** [comment]
@cgohlke - do you have time to do the patches?   Or should we cut the release like this?

Nathaniel - do you think it is reasonable to do a release from this content + / - Windows patches?  I believe I have the pypi and github permissions to do the release.

**Comment by njsmith** [comment]
I don't have any objection -- we could debate back and forth if anyone has a favorite bug fix they want to get in, but IMHO the bottom line is that we should get out some kind of 1.9.3 that passes tests on py35, and if you want to do the work then that's fine with me :-). And no-one's objected on the mailing list or #6319, so guess we're good to go.

(I'm not worried about getting @carlkl's patches into this -- they can go into 1.10.1 or whatever just as well.)

We do need the usual release engineering gunk: updated version in the source code, release notes, tag, etc. -- do you have the permissions for that?

**Comment by matthew-brett** [comment]
I do have github and pypi write permission, so I can tag the release and upload the source and OSX wheels to pypi.  I also have (some) upload permission to sourceforge, but I'm proposing not to do this release on sourceforge, on the basis that sourceforge is mainly for docs and windows builds, and we can't build a Python 3.5 binary using the mingw toolchain.

**Comment by matthew-brett** [comment]
@cgohlke - I'm planning to release later on today.  Do you have time to merge the Windows fixes?

**Comment by matthew-brett** [comment]
I am trying to work out how to upload packages with a PGP signature.

I failed with the following:

```
twine upload dist/numpy-1.9.3.* --sign --repository=pypitest
```

That generated unsigned packages : https://testpypi.python.org/pypi/numpy/1.9.3

@juliantaylor @pv - any hints how to do that?

**Comment by cgohlke** [comment]
Sorry, not time this weekend. Go ahead.

**Comment by matthew-brett** [comment]
Planning to merge - any objections?

**Comment by charris** [comment]
Go for it.

**Comment by carlkl** [comment]
I have further patches for mingwpy builds (windows) that could go to maintenance/1.9.x and/or to numpy/master. Any objections?

**Comment by matthew-brett** [comment]
Carl - both maintenance and master seem like good places for those.  Do you mind waiting for the next maintenance release?   Is it possible to build numpy for Python 3.5 with your tool-chain?

**Comment by carlkl** [comment]
2 questions:

python3.5 support is not finished yet. I made import libraries the vcruntime140.dll way (see steve dower's blog) to avoid http://bugs.python.org/issue25027. So extension binaries will be linked against vcruntime140.dll as well as against all the api-ms-win-crt-**-l1-1-0.dll's. 
BTW: linking static gcc runtimes (as done in mingwpy) don't lead to the bug mentioned above, as long as correct MS runtimes are linked.

Concerning numpy-1.9.3: The status for numpy-1.9.2 compiled with mingwpy and OpenBLAS and longdouble faked to double:
1. No error's or failures for 32 bit. 
2. There is one error for 64bit: 
```print no.longdouble(-np.inf)``` results in ```inf``` instead of ```-inf``` and that leads to 4 errors in numpy.test().
There are still failures for scipy-0.16.0 compiled with mingwpy.

I would like to make a PR for numpy:maintenance/1.9.x to get the changes into numpy-1.9.3

**Comment by matthew-brett** [comment]
Great progress - thanks a lot.

Julian - are you still interested to do a 1.9.4?  When would you plan to do that?

Carl - could you put in a PR to maintenance/1.9.x so we can get an idea of the extent of the changes?  

Presumably the 'inf' bug needs to be fixed on the mingw side?

**Comment by carlkl** [comment]
I plan to do the PR to maintenance/1.9.x tomorrow. If needed, I can add another one for numpy/master.

**Comment by matthew-brett** [comment]
OK - then if you don't mind I will release 1.9.3 today, because otherwise it's going to be another couple of days, to review the PR and accept it.

I'm happy to do a quick 1.9.4 release with just these fixes if there is no obvious time-frame for a more substantial 1.9.4 release.

**Comment by charris** [comment]
@carlkl Numpy 1.10 will be coming out soon, so a PR for master would be appreciated. That is where PR should normally start. Is there a reason (incomplete, etc) that you are looking at 1.9.3 first?

**Comment by matthew-brett** [comment]
To answer my own question about signing packages - this works:

```
python setup.py sdist --formats=gztar,zip upload --sign
```

Signing via `twine` appears not to work.

**Comment by charris** [comment]
@carlkl @juliantaylor Somewhat off topic, but when you get things figured out we should try to update numpy-vendor to produce 64 bit binaries.

**Comment by carlkl** [comment]
@charris, instead of creating a dedicated numpy-vendor I propose using mingwpy wheels, as described in https://github.com/numpy/numpy/pull/6350#issuecomment-143062748

**Comment by charris** [comment]
@carlkl numpy-vendor is a vagrant managed virtual machine that runs WINE on Ubuntu for the Windows compiles, so I assumed that at some point we would want to update the provisioning of the virtual machine and WINE to use your new tool chain. What am I missing?

**Comment by carlkl** [comment]
@charris adding OpenBLAS binaries and the mingwpy wheels should be enough?

**Comment by charris** [comment]
Probably. I'm not an expert on this and it isn't pressing, but once 1.10.0 is out we can work on it.

**Pull request merged**
