### PR TITLE
DEP: Deprecate `numpy.dual`.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Add a deprecation warning in the `numpy.dual` module, and
remove the use of `numpy.dual` from the few places where it
is used in the numpy code.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Mailing list discussion from January: https://mail.python.org/pipermail/numpy-discussion/2020-January/080308.html

**Review by rossbar — COMMENTED** [review]
Would it be appropriate to add a `.. deprecated:: 1.19` tag (assuming this makes it to 1.19) to the module docstring (in numpy/dual.py) or is that typically only used inside function docstrings? It does look like the `numpy/dual.py` module docstring gets picked up via an `.. automodule` and built into the [reference](https://numpy.org/devdocs/reference/routines.dual.html#module-numpy.dual) so maybe that would be useful? I'm not sure so I thought I'd ask!

**Comment by rgommers** [comment]
Please not yet for 1.19.0 - that will start emitting deprecation warnings for the latest releases of Scipy too soon.

**Comment by WarrenWeckesser** [comment]
@rgommers, agreed, this can wait until after 1.19.0 is released.

Can someone with the correct permissions add a 1.20.0 milestone to github?

**Comment by rgommers** [comment]
> Can someone with the correct permissions add a 1.20.0 milestone to github?

you now have triage permissions

**Comment by WarrenWeckesser** [comment]
Thanks @seberg and @rgommers.

@rossbar, good idea, I've added that in a new commit.

**Review by auvipy — APPROVED** [review]

**Comment by seberg** [comment]
Now that master is on 1.20, lets put this in, thanks Warren!

**Pull request merged**
