### PR TITLE
MAINT: support IBM i system

### PR DESCRIPTION
**Pull request by zheddie**
This fix to make numpy.distutils works well on IBM i system. Please kindly help to review and merge it. thanks.

### CODE REVIEW

**Comment by mattip** [comment]
`numpy.distutils` is deprecated, but we do not yet have a replacement. I am find with merging this as a "best effort", in the hopes that it does not break any other IBM build and that once we do settle on a replacement, there will be some effort to merge these flags into the new system. It would be nice if the new system lets us write some tests for this by mocking `sys.platform` and checking the resulting flags.

**Comment by zheddie** [comment]
Thanks @mattip , Yes, I am pretty sure that this fix would not block other systems, as all my code are covered under `sys.platform.startswith('os400')`. Any yes, it really depends on this function.

**Comment by mattip** [comment]
Thanks @zheddie

**Comment by zheddie** [comment]
@mattip , do you know how can I confirm the first release number which include this PR? thanks.

**Comment by mattip** [comment]
`git tag --contains 505cff914d`. This was committed in August, so it will be part of the upcoming 1.24.0 release.

**Pull request merged**
