### PR TITLE
ENH: Add tool to help speed up Travis CI

### PR DESCRIPTION
**Pull request by hugovk**
As suggested in by @mattip in https://github.com/numpy/numpy/pull/17242#issuecomment-686923820, add the script used in https://github.com/numpy/numpy/pull/17242 for optimising the build to `tools/` (original [here](https://github.com/hugovk/travis-ci-tools/blob/master/travis-sorter.py)), add some info to `doc/source/dev/ci.rst` and linking it to `doc/source/dev/index.rst`. I didn't pull the docstring from the script into the page as I wasn't sure how :)

### CODE REVIEW

**Comment by charris** [comment]
The repeated documention in `doc/source/dev-ci.rst` seems excessive, most of the `tools` are not included in the NumPy distribution and are not documented separately. I'm not sure how we should handle documenting them, it would be useful to have the documentation somewhere central, but where? @mattip any ideas.

**Comment by mattip** [comment]
This is a general problem with the tools directory. Maybe rather than add this `rst` document, we should add a toplevel docstring to an `__init__.py` file in the directory? Will that cause other problems? I agree we don't need to repeat the entire docstring there, it is enough to say "travis-sorter.py: a tool to help optimize travis running time", since the docstring of the file is quite complete.

**Comment by charris** [comment]
@mattip Sounds like an idea. @hugovk Why don't you remove the documentation from `ci.rst` and we will put this in while figuring out what to do about tools documentation.

**Comment by hugovk** [comment]
Sure, something like b81ae28937fad03c3954160102dca6cf72d3b654?

**Comment by charris** [comment]
@hugovk Might as well remove the new file and index entry as well.

**Comment by hugovk** [comment]
Done!

**Comment by mattip** [comment]
Thanks @hugovk

**Pull request merged**
