### PR TITLE
DOC: Add polyutils subpackage to reference documentation

### PR DESCRIPTION
**Pull request by MSeifert04**
In #9682 I realized that `polynomial.polyutils` isn't present in the reference documentation. 

But it seems like a public subpackage. Feel free to close the PR in case it wasn't meant to be public.

### CODE REVIEW

**Comment by MSeifert04** [comment]
I suspect it just got overlooked, so: *bump*.

**Comment by mhvk** [comment]
@charris - it does seem the omission of `polyutils` in the documentation is simply an oversight. Is this something to backport as well? (being a kind of bug)

**Comment by charris** [comment]
My original idea was that the functions in `polyutils` were implementation details common to all different polynomial types, but the separation wasn't very strict, in particular, the error classes and, perhaps, the mapdomain function. It is probably harmless to have them in the documentation and maybe even helpful.

The module was written long ago before we became stricter about what should be public or private.

**Comment by mhvk** [comment]
Looking more closely, it does seem some of the docstrings are actually not correct right now; e.g.,
```
    >>> from numpy import polynomial as P
    >>> P.trimcoef((0,0,3,0,5,0,0))
```

Still, overall, the documentation seems setup to by used!

**Comment by MSeifert04** [comment]
Good point, I'll check if the docstrings work and amend that. :)

**Comment by MSeifert04** [comment]
@mhvk Good point. I updated the docstrings so they actually work.

**Comment by MSeifert04** [comment]
Anything else I can do?

**Comment by charris** [comment]
The `as_series` examples don't show the common use, which is to convert a bunch of objects of different types to a bunch of objects of a compatible common type. Using range and arrays as inputs kind of defeats the purpose as all the elements are already of a common type. OK, range gets promoted to float, but still ...

**Comment by MSeifert04** [comment]
I've added your example and a example for `trim`. 

But I wasn't sure if these should *replace* the existing examples...

**Comment by charris** [comment]
Thanks @MSeifert04 .

**Pull request merged**
