### PR TITLE
DOC: work around GH isaacs/github#316 to show SVG image

### LINKED ISSUE #11000: SVG logo doesn't appear in README on GitHub
screen shot 2018-04-28 at 15 39 42

### PR DESCRIPTION
**Pull request by mattip**
There is an issue with the way github renders SVG images in README files, isaacs/github#316

Fixes #11000

### CODE REVIEW

**Comment by eric-wieser** [comment]
Didn't realize that `rawgithub.com` changed its name. This looks like a pretty reasonable solution to me.

That issue's awfully old though, and this problem is recent for us - I do wonder if this is just a temporary glitch on github's side.

**Comment by mattip** [comment]
We could wait a week before merging

**Comment by charris** [comment]
Man, that's weird. The page rendering changes every time I check out `numpy/numpy`, but looks mostly decent if I check out the `README.md` file. Anyway, let's give this a shot, it seems that other projects are still using this fix.

Thanks Matti.

**Comment by charris** [comment]
Maybe Github is just getting slow ...

**Pull request merged**
