### PR TITLE
NEP: Update NEP 19: RNG Policy

### PR DESCRIPTION
**Pull request by rkern**
Some productive discussions on the mailing list have forged a significantly altered proposal.

### CODE REVIEW

**Comment by rkern** [comment]
Substantive discussion here: https://mail.python.org/pipermail/numpy-discussion/2018-June/078252.html

**Comment by charris** [comment]
Test failure was unrelated.

**Comment by shoyer** [comment]
This looks pretty good to me now. Maybe the time is right to merge it and ask for consensus on the mailing list?

**Comment by mattip** [comment]
@rkern merged.

**Comment by mattip** [comment]
Thanks Robert

**Pull request merged**
