### PR TITLE
ENH: add locking to python lapacklite interface

### LINKED ISSUE #22509: BUG: Lapack lite is not thread-safe (need to guard)
`skimage` found an issue probably related to `eigvalsh` or generally threaded calls to `linalg_umath.cpp`.

Unfortunately, I have not yet narrowed it down further, and the test is slightly flaky (on my machine).  For example, it seems to easier reproduce running the full file, rather than just the test.

To reproduce, I have to explicitly use **`NPY_BLAS_ORDER=`** (disable blas use), then run current main of skimage tests:
```
python3 -m pytest skimage/feature/tests/test_basic_features.py::test_multiscale_basic_features_deprecated_multichannel
```

I have a gdb traceback of a crash (the actual crash fluctuates a bit, so it may well be elsewhere):
```
#5  0x00007fffb7ef3f7f in release_evd<double> (params=0x7fffda26e940) at numpy/linalg/umath_linalg.cpp:1482
#6  eigh_wrapper<double> (JOBZ=<optimized out>, UPLO=<optimized out>, args=<optimized out>, dimensions=<optimized out>, 
    steps=<optimized out>) at numpy/linalg/umath_linalg.cpp:1555
#7  0x00007ffff639eed5 in generic_wrapped_legacy_loop (__NPY_UNUSED_TAGGEDcontext=<optimized out>, data=<optimized out>, 
    dimensions=<optimized out>, strides=<optimized out>, auxdata=0x7fffd19e9b30)
    at numpy/core/src/umath/legacy_array_method.c:87
```

So it seems eigvalsh and threading related.  I need to dig further eventually, but maybe someone else has an idea what to look into (the umath code, the blas/lapack fallback code?).

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #22509.

lapack-lite is not thread safe, with tons of static global state.

This PR adds a global lock to every call into the thread-unsafe low-level lapack-lite code. I'm sure it adds some overhead but we can ameliorate that in the future leveraging PyMutex. lapack-lite is thread-unsafe even in the standard python build, it just doesn't get hit very often, and usually in CI under odd build configurations.

With this change applied the scikit-image tests referred to in #24512, which still fail under lapacklite, pass. Ping @stefanv in case scikit-image is going out of its way to avoid lapacklite in tests.

I don't have a simple numpy-only reproducer that crashes without this change. Does anyone have a simple way to crash a non-thread-safe lapack so I can add a test?

I might make it harder to install lapack-lite in the free-threaded build as a followup.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks Nathan!

> I might make it harder to install lapack-lite in the free-threaded build as a followup.

xref https://github.com/numpy/numpy/issues/26157#issuecomment-2150391809 where we discussed this. I'm fine with this deviation if it's still necessary after this PR. But if the locking fixes it, I'd prefer not to do this, since it will cause other problems when building numpy from source in downstream CI.

**Comment by seberg** [comment]
This doesn't look right, unfortunately.  I don't know why we even have this `lapack_lite` module, it belongs deprecated (probably because it was a "private" version used before the linalg-umath existed).
Adding locking here fixes an issue in the free-threaded build for the `lapack_lite` module and I am happy if you just want to merge it, but that is pretty unimportant and doesn't close the issue.

The locks need to be either:
* in the `lapack_lite` functions that get called here (and more), or
* in `umath_linalg.cpp` and only if the lapack backend isn't threadsafe which is probably just lapack-lite.

My guess is that the second one is simpler.

**Comment by rgommers** [comment]
IIRC I looked at completely removing `lapack_lite` recently, but it was complicated because of some direct usage in testing - so I left it alone. So I'd merge this as is. You're right though @seberg that adding locks in `umath_linalg` is also needed (and more important).

> My guess is that the second one is simpler.

I think so too.

**Comment by seberg** [comment]
I think we can just delete (or deprecate) it, the only test that looks important is for `xerbla` and that:
* Is skipped when it fails, so we don't know when it fails anyway.
* We should try to never pass invalid parameters to lapack.  See for example https://github.com/numpy/numpy/issues/25564 for an example where this happens and that `xerbla` does *not* kick in.

Now, it would be nice to use our `xerbla` and give a good error for example in that issue!  But it looks like it either doesn't work on all systems (e.g. due to mac dynamic linking resolution working differently) or probably never worked (or at least in a long time) for anything but lapack-lite, at least not in years...

**Comment by ngoldbaum** [comment]
Thanks for the pointer, this is my first time touching the linalg module so the structure wasn't clear initially. I think I'll close this and do this in two followups. First, right now there isn't a way to tell from inside the source code what BLAS is being used, so I need to add some meson logic to generate a macro that is set when lapacklite is being used.

Next, I can add a new global static lock in the umath_linalg module and then acquire and release it in that module. I might end up putting the locking in the functions exposed to Python rather than around every BLAS call for the sake of simplicity.

**Pull request closed without merging**
