### PR TITLE
For building scipy with less promiscuous flags

### PR DESCRIPTION
**Pull request by ghost**
[skip ci]

### CODE REVIEW

**Comment by rgommers** [comment]
@xoviat could you add a bit of context in the PR description? And why does the PR come from @matthew-brett's repo?

**Comment by matthew-brett** [comment]
Sorry @xoviat beat me to it.  We were discussing whether we really need the very dangerous-looking `-Wl,--allow-multiple-definition` to build Scipy DLLs.

https://github.com/conda-forge/openblas-feedstock/issues/2#issuecomment-349643128

It turned out that we don't need that flag to build - see links in 

https://github.com/conda-forge/openblas-feedstock/issues/2#issuecomment-349738654

**Comment by pv** [comment]
But doesn't scipy need that flag.

It's not uncommon to have multiple definitions of symbols in static
linking (and scipy indeed had those). So I'd just keep the flag unless
you can point out that it causes issues in practice.

**Comment by matthew-brett** [comment]
No, scipy doesn't need that flag - that was the test that I was pointing to above on appveyor.

Pauli - I see you put this in 3 months ago in 3cb0e8f.

Surely, given that scipy doesn't need it, it is safer to remove it and put it back if it is needed?

**Comment by xoviat** [comment]
@carlkl said he didn't like the way the scipy wheels were built and when asked for specific reasons, he mentioned this. Now this may be a valid concern, but I can't personally say.

**Comment by xoviat** [comment]
I'll leave this open for few days to let him explain, and then close it if there are still objections.

**Comment by pv** [comment]
Scipy doesn't need it any more, because the link conflicts were resolved manually.

**Comment by xoviat** [comment]
You're correct. @carlkl is wrong.

**Comment by pv** [comment]
gcc actually does check for multiple symbols if you link the `.o` files, but not when linking static `.a` archives with multiple symbols (which happened to be what was going on in scipy, where the fortran codes are mostly linked to static libs and those are linked in to the main program). It may be possible to emulate this behavior somehow.

**Comment by pv** [comment]
Relevant commit --- https://github.com/scipy/scipy/commit/97ccd7b4b8343ca3cbee9c972add301142f690a1  --- if some changes are made here, would be best to check scipy builds also with this commit reverted.

**Comment by carlkl** [comment]
gcc usually emits an error when it hits multiple definition of the same symbol. I was not aware, that this doesn't happen when linking static archives.
A fast search on this topic shows me this: http://www.appletonaudio.com/blog/2013/linking-c-static-libraries-with-duplicate-symbols and https://gcc.gnu.org/ml/gcc-help/2009-09/msg00107.html

**Pull request closed without merging**
