### PR TITLE
DOC: Add a reference into NEP 29,

### PR DESCRIPTION
**Pull request by Carreau**
use the same reference format as other NEP having reference, (uppercase
NEP, and on the first line of the document). This make it easier to link
to this NEP with intersphinx.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Sounds like a good idea. Not that it matters so much but NEPs 40 and 41 seem to be the only others that have document-level reference targets like this, and they use a different format that drops the leading zeros (e.g `.. NEP40`). Is it worth trying to standardize the link form? Might be nice from an intersphinx perspective but likely not worth worrying about.

**Comment by Carreau** [comment]
Oops, I saw that but forgot to update. zeroes dropped for consistency. It's better not to change existing links.

**Review by rossbar — APPROVED** [review]
LGTM, thanks @Carreau !

**Comment by Qiyu8** [comment]
maybe the best time to add reference is when they actually linked.

**Comment by rossbar** [comment]
@Qiyu8 in this case it the target is for links from other projects (via intersphinx), which makes a lot of sense for NEP 29.

**Comment by Carreau** [comment]
> @Qiyu8 in this case it the target is for links from other projects (via intersphinx), which makes a lot of sense for NEP 29.

Yes, and it's exactly how I found out the ref was missing, I published IPython 7.15 today and wanted to link to nep29 via `:ref:` and couldn't.

**Comment by charris** [comment]
Thanks @Carreau .

Looks like `nep-0026-missing-data-summary.rst` has a number of links to other NEPs, I wonder if we should do this for all the NEPs.

**Comment by Carreau** [comment]
> Looks like `nep-0026-missing-data-summary.rst` has a number of links to other NEPs, I wonder if we should do this for all the NEPs.

Likely but I'm trying to stay minimal to avoid controversy.

**Pull request merged**
