### PR TITLE
BUG: Scalars should have ndim=0 in memoryview.

### LINKED ISSUE #7513: BUG: Scalars should have ndim=0 in memoryview
```
>>> import numpy
>>> memoryview(numpy.int_(1)).ndim
1
>>> memoryview(numpy.float_(1)).ndim
1
```

### PR DESCRIPTION
**Pull request by abalkin**
Fixes #7513

### CODE REVIEW

**Comment by charris** [comment]
The appveyor failure was x86, python 2.7
```
======================================================================
ERROR: test_memoryview (test_scalarmath.TestMultiply)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\numpy\core\tests\test_scalarmath.py", line 509, in test_memoryview
    m = memoryview(x)
TypeError: cannot make memory view because object does not have the buffer interface
```
Not sure why that wouldn't show up on other platforms.

**Comment by charris** [comment]
Let's try the old close and reopen trick.

**Comment by charris** [comment]
Memoryview should be available in Python 2.7.

**Comment by abalkin** [comment]
> Memoryview should be available in Python 2.7.

While `memoryview` is available, `numpy` does not support it in Python 2.7 for some reason:

```
Python 2.7.10 (default, Jul 14 2015, 11:09:53)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.10.4'
>>> memoryview(numpy.int_())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot make memory view because object does not have the buffer interface
```

**Comment by abalkin** [comment]
I think I figured out the problem with Python 2.7. See 48af124.  It turned out that the new buffer protocol was not turned on for the numpy scalars.

**Comment by seberg** [comment]
Are you planning to fix the type thing here as well or prefer a followup? This change seems not very helpful without fixing also the type. Or maybe it is already fixed by enabling the new buffer protocol?

**Comment by abalkin** [comment]
> Are you planning to fix the type thing here as well or prefer a followup?

I've already opened #7516 as a follow-up.  I have no preference on how to split the fixes between PRs.  Please advise.

**Comment by abalkin** [comment]
> We don't support anything < 2.7 these days, so don't need the #if

This is great.  supporting < 2.7 and 3.x in the same source is PITA.  I'll update the patch.

**Comment by seberg** [comment]
I would be happy if you can include the fix here I think, the temporary result here without the correct itemsize seems in some sense worse then the previous, since not even all data gets exposed.

Or separate it, and best we will just merge this after the other one.

**Comment by abalkin** [comment]
Itemsize and format fix is a little bit harder because I don't want to duplicate the code that is already there for arrays.

**Comment by abalkin** [comment]
Looking at the comments in buffer.c, I find the following note:

```
 * - Don't use bf_releasebuffer, because it prevents PyArg_ParseTuple("s#", ...
 *   from working. Breaking this would cause several backward compatibility
 *   issues already on Python 2.6.
```

The requirement of not using `bf_releasebuffer` leads to a lot of complications that I would rather avoid in the scalar case.  Since numpy has dropped support for 2.6, do we still have the backward compatibility issues described above?

**Comment by pv** [comment]
The issue is with Python 2 in general, not only 2.6. Also potentially in 
3rd party code, not only in Numpy.

**Comment by abalkin** [comment]
@pv - can you explain what the issue is?  The comment just says that there is a problem with `PyArg_ParseTuple("s#", ...`, but does not explain what the problem is.  I thought `s#` format code triggers the old buffer protocol and is not affected by the `bf_releasebuffer` method.

**Comment by pv** [comment]
The problem as I recall is that PyArg_ParseTuple("s#", ...) stops working.

**Comment by pv** [comment]
Sorry for the brief answer --- this was several years ago, and I do not 
have time to check this again right now.

**Comment by charris** [comment]
What is the current status of this?

**Comment by seberg** [comment]
Not sure where this is, but just to note that I would prefer to put this in together with gh-7516, whether including it here does not matter to me but this without the followup seems not useful to me.

**Comment by charris** [comment]
@abalkin Ping.

**Comment by mattip** [comment]
Closing. This is now well tested and fixed

**Pull request closed without merging**
