### PR TITLE
DOC: fix NEP 50 reference

### LINKED ISSUE #26371: NEP50 Link is broken in devdocs
https://github.com/numpy/numpy/blame/b2960879bbf90af0cc3e533d2721d3a30470b056/doc/source/release/2.0.0-notes.rst#L79

In the docs resolves to https://numpy.org/devdocs/release/NEP50

### PR DESCRIPTION
**Pull request by luxedo**
Fixes https://github.com/numpy/numpy/issues/26371.
Closes https://github.com/numpy/numpy/pull/26468.

[skip actions][skip azp][skip cirrus]

I'm having trouble generating the documentation but according to my editor's linter this must be right

### CODE REVIEW

**Comment by luxedo** [comment]
1. Why would documentation changes makes tests fail? 
2. Is there any way to run again? Any chances of a different result?
3. Shouldn't these tags skip the pipelines? [skip actions][skip azp][skip cirrus]

**Comment by seberg** [comment]
I feel we had more PRs on this, but can you make it against the 2.0 maintanence branch?  On all other things: please just ignore this, it's completely unrelated issue.

**Comment by luxedo** [comment]
Just pushed from `maintenance/2.0.x`.

I found one PR  that is open:
https://github.com/numpy/numpy/pull/26468

And two other PRs that are already closed:
https://github.com/numpy/numpy/pull/26453
https://github.com/numpy/numpy/pull/26462

**Comment by charris** [comment]
Thanks @luxedo .

**Pull request merged**
