### PR TITLE
MAINT: Use the error_converting macro where possible

### PR DESCRIPTION
**Pull request by eric-wieser**
If we have the macro, we may as well use it.

Note that we can't use this macro on unsigned types.

### CODE REVIEW

**Comment by charris** [comment]
Hmm, I'd almost prefer removing the current uses of `error_converting` as the code is more self documenting without it and it isn't a complicated check. That said, this looks good to me otherwise, so I'll probably grump and put it in.

**Comment by eric-wieser** [comment]
>  I'd almost prefer removing the current uses of error_converting a

That is indeed the other option, but I'm not sure I agree it's more self-documenting without it

**Comment by charris** [comment]
The problem with too many macros is that you've got to find where they are defined and look at them before you know what is going on, and they are seldom documented. Of course, most of our functions are undocumented also ...

**Comment by charris** [comment]
Thanks Eric.

**Pull request merged**
