### PR TITLE
DOC: Add contributor tips.

### PR DESCRIPTION
**Pull request by RuchikaChugh**

### CODE REVIEW

**Comment by mattip** [comment]
Could you give some justification for these changes, and describe where you think they would fit in to the [current developer guide](http://www.numpy.org/devdocs/dev/index.html)

**Comment by RuchikaChugh** [comment]
The changes described by me can be made in the Readme file of the NumPy repository.
Talking about the Python versions section and the resources I have mentioned, It can be added in the [current developer guide](http://www.numpy.org/devdocs/dev/index.html) under Checking Python Version and the Resources can be mentioned separately in  working with NumPy source code.

**Comment by charris** [comment]
Why the new file? Just add to the Readme.md or wherever you think it needed.

**Comment by mattip** [comment]
@RuchikaChugh please either make the improvements you suggested in your comment in subsequent commits to this PR or close the PR.

**Comment by kritisingh1** [comment]
@mattip the [current developer guide](http://www.numpy.org/devdocs/dev/index.html) looks more than sufficient to me. The `New Contributor Tips` are more related to the ethics and code of conduct for people collaborating in open source projects.in general and not specific to NumPy. Do we really need to include them? However, we should consider, maybe, including the resources and tutorial part for beginner users of NumPy?

**Comment by rgommers** [comment]
I agree with @kritisingh1, this doesn't add anything to the current developer guide and also doesn't belong in the README.

> However, we should consider, maybe, including the resources and tutorial part for beginner users of NumPy?

We should not link random youtube videos I think. We do need to improve our tutorial content in general, but that's unrelated to the contributing guide.

No follow-up for 2 months, so I'll close this. Thanks everyone.

**Pull request closed without merging**
