### PR TITLE
BUG: Restore the environment variables when import multiarray fails.

### LINKED ISSUE #9861: Importing numpy alters the execution environment
In `core/__init__.py` two environment variables, `'OPENBLAS_MAIN_FREE'` and `'GOTOBLAS_MAIN_FREE'`, are temporary set for importing the multiarray numpy extension module. But if the importing is failed the environment is not restored.

This affects CPython tests (https://bugs.python.org/issue31792).

Moving the code that restores the environment into the `finally` block would fix this issue.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Fixes #9861.

### CODE REVIEW

**Comment by charris** [comment]
Could you fix up the commit message with a shorter summary line (see revised title) and more explanation in the body?

**Comment by serhiy-storchaka** [comment]
I have fixed up the commit message with a shorter summary line, but sorry, I don't know what should be added in the body.

You can edit the commit message when merge the change, isn't?

**Comment by charris** [comment]
I can edit the title, but have now idea how to get at the commit message. What would be good to add to the extended part of the commit message is your explanation of the problem that is in  the original issue.

**Comment by serhiy-storchaka** [comment]
Done.

**Pull request merged**
