### PR TITLE
ENH: Add annotations for `np.MachAr`

### PR DESCRIPTION
**Pull request by BvB93**
This PR adds annotations for the (somewhat unused) `np.MachAr` class.

### CODE REVIEW

**Comment by seberg** [comment]
Can we deprecate this instead? :)

**Comment by seberg** [comment]
Yeah, but even that code path (if it is even useful) doesn't need `MachAr` in the public API?

**Comment by BvB93** [comment]
> Yeah, but even that code path (if it is even useful) doesn't need `MachAr` in the public API?

True, though using a deprecation cycle to remove something from the public API (rather than getting rid if it in its entirety) feels a bit like half-assing it.

**Comment by seberg** [comment]
I guess my hope is that half-assing it now, makes it easier for future us to half-ass the second part later :grin:.

**Pull request closed without merging**
