### PR TITLE
DOC: GRAMMATICAL CORRECTIONS

### PR DESCRIPTION
**Pull request by Vaibhav-buzz**
some grammatical mistakes has been corrected

### CODE REVIEW

**Comment by Vaibhav-buzz** [comment]
@mattip why my 3 workflows awaiting approval ?? Please let me know.

**Comment by mattip** [comment]
I think we should reject these changes. The current text uses Oxford commas (closed punctuation), which is less ambiguous.

**Comment by seberg** [comment]
(The "awaiting approval" thing is just github policy, however.  Supposedly people opened stray PRs to mine crypto currency or so...)

**Comment by Vaibhav-buzz** [comment]
> I think we should reject these changes. The current text uses Oxford commas (closed punctuation), which is less ambiguous.

Why Oxford is always correct ? 
Mine edited gives the clear meaning to sentence then why Oxford dominate between us . Because it is " The Oxford " or what ?

**Comment by seberg** [comment]
We might have a slight preference (not even sure about that).  But the point is: if you would have written the original text without Oxford comma and someone proposed to add it, we would probably reject it on the same grounds if someone proposed to change it.

**Comment by rkern** [comment]
> Why Oxford is always correct ?

It is not, but it is not wrong either. So these are not corrections, just a stylistic choice that we don't care to change. AFAICT, only line 16 was arguably an actual error (but also not especially worth correcting), and line 31 introduces a new error.

We have [lots of ways to contribute, with a variety of skills](https://numpy.org/contribute/). Minor stylistic changes are generally not among those contributions that we seek out.

**Pull request closed without merging**
