### PR TITLE
Fix #5312: use an aligned allocator.

### LINKED ISSUE #5312: Use an aligned allocator for NumPy?
Regarding the f2py regression in NumPy 1.9 with failures on 32-bit Windows, the question is whether NumPy should start to use an allocator which gives guaranteed alignment.

https://github.com/scipy/scipy/issues/4168

### PR DESCRIPTION
**Pull request by pitrou**
Introduce two new functions, get_data_alignment() and set_data_alignment() which allow
setting the guaranteed alignment at runtime.

### CODE REVIEW

**Comment by juliantaylor** [comment]
an issue is that with this pointers can't be freed with free anymore, so technically an ABI break.
Its probably unlikely but there might be users out there who try that, or pass in malloc pointers to array constructors and then transfer ownership to the array.

**Comment by pitrou** [comment]
I noticed that PyDataMem_RENEW() is obviously wrong the base pointer changes alignment. Fixing, but this adds some overhead in cases where the base offset changes.
(also, there seem to be some problems in 32-bit mode)

**Comment by anirudh2290** [comment]
This PR and #5470 needs another look from reviewers, @seberg we probably need a "Awaits review" tag for such PRs ?

**Comment by seberg** [comment]
There is a "ready for review" tag, not sure if it helps here... I guess the problem is getting someone to review who knows this better.
Not sure I am too worried about transferred ownership of allocated pointers to consider it an ABI break). I suppose if we go there, that also opens us up to simply using the Python allocator for the `strides+shape` (dims), or even moving it into the object allocation to optimize it away entirely?

Anyway, you are right, this is one that could be reactivate, but may need prodding reviewers a bit :).

**Comment by anirudh2290** [comment]
okay thanks for the summary @seberg. I guess I will tag this and the other pr Ready for Review and revisit this later.

**Comment by seberg** [comment]
Thanks for this!  I will close it, since it is now superseded by gh-17582 and [NEP 49 — Data allocation strategies](https://numpy.org/neps/nep-0049.html).

**Pull request closed without merging**
