### PR TITLE
BLD, ENH: Display compiler configuration in `show_config`

### LINKED ISSUE #10983: numpy.show_config should show information about the compilation process itself
Today, numpy.show_config() shows information about libraries, but does not give information about the compiler used to build numpy nor the compilation flags. Sometimes knowing which compiler and flags were used, can help triage down where issues like #10370 happen.

I was thinking maybe output something like opencv's getBuildInformation function which shows:
```
General configuration for OpenCV 3.2.0 =====================================
  Version control:               unknown
 
  Extra modules:
    Location (extra):            /tmp/opencv3-20170521-37568-15s9x5w/opencv-3.2.0/opencv_contrib/modules
    Version control (extra):     unknown
 
  Platform:
    Timestamp:                   2017-05-21T18:48:31Z
    Host:                        Darwin 16.6.0 x86_64
    CMake:                       3.8.1
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/local/Homebrew/Library/Homebrew/shims/super/gmake
    Configuration:               Release
 
  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  (ver 8.1.0.8020042)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -mavx2 -fvisibility=hidden -fvisibility-inlines-hidden -mf16c -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -mavx2 -fvisibility=hidden -fvisibility-inlines-hidden -mf16c -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/local/Homebrew/Library/Homebrew/shims/super/clang
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -mavx2 -fvisibility=hidden -fvisibility-inlines-hidden -mf16c -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -mavx2 -fvisibility=hidden -fvisibility-inlines-hidden -mf16c -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):
    Linker flags (Debug):
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          -framework OpenCL /usr/local/opt/jpeg/lib/libjpeg.dylib /usr/local/lib/libpng.dylib /usr/local/lib/libtiff.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIlmImf.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libHalf.dylib /usr/local/lib/libIlmThread.dylib avcodec avformat avutil swscale avresample -framework VideoDecodeAcceleration bz2 -framework Cocoa -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore /usr/local/lib/libhdf5.dylib /usr/local/lib/libsz.dylib /usr/lib/libz.dylib /usr/lib/libdl.dylib /usr/lib/libm.dylib /usr/local/lib/libtesseract.dylib /usr/local/lib/liblept.dylib tbb -framework Accelerate
    3rdparty dependencies:       libwebp libprotobuf
 
  OpenCV modules:
    To be built:                 core flann hdf imgproc ml photo reg surface_matching video dnn fuzzy imgcodecs shape videoio highgui objdetect plot superres xobjdetect xphoto bgsegm bioinspired dpm face features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo tracking videostab xfeatures2d ximgproc aruco optflow phase_unwrapping stitching structured_light matlab python2
    Disabled:                    world contrib_world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python3 ts viz cnn_3dobj cvv freetype sfm
 
  GUI:
    QT:                          NO
    Cocoa:                       YES
    OpenGL support:              NO
    VTK support:                 NO
 
  Media I/O:
    ZLib:                        /usr/lib/libz.dylib (ver 1.2.8)
    JPEG:                        /usr/local/opt/jpeg/lib/libjpeg.dylib (ver 80)
    WEBP:                        build (ver 0.3.1)
    PNG:                         /usr/local/lib/libpng.dylib (ver 1.6.29)
    TIFF:                        /usr/local/lib/libtiff.dylib (ver 42 - 4.0.7)
    JPEG 2000:                   NO
    OpenEXR:                     /usr/local/lib/libImath.dylib /usr/local/lib/libIlmImf.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libHalf.dylib /usr/local/lib/libIlmThread.dylib (ver 2.2.0)
    GDAL:                        NO
    GDCM:                        NO
 
  Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 57.89.100)
      avformat:                  YES (ver 57.71.100)
      avutil:                    YES (ver 55.58.100)
      swscale:                   YES (ver 4.6.100)
      avresample:                YES (ver 3.5.0)
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    Aravis SDK:                  NO
    AVFoundation:                YES
    V4L/V4L2:                    NO/NO
    XIMEA:                       NO
    gPhoto2:                     NO
 
  Parallel framework:            TBB (ver 2017.0 interface 9106)
 
  Other third-party libraries:
    Use IPP:                     9.0.1 [9.0.1]
         at:                     /tmp/opencv3-20170521-37568-15s9x5w/opencv-3.2.0/macbuild/3rdparty/ippicv/ippicv_osx
    Use IPP Async:               NO
    Use VA:                      NO
    Use Intel VA-API/OpenCL:     NO
    Use Lapack:                  YES (-framework Accelerate)
    Use Eigen:                   YES (ver 3.3.3)
    Use Cuda:                    NO
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO
 
  OpenCL:                        <Link with OpenCL library>
    Include path:                /usr/local/include /usr/local/include
    Link libraries:              -framework OpenCL
    Use AMDFFT:                  YES
    Use AMDBLAS:                 YES
 
  Python 2:
    Interpreter:                 /usr/bin/python (ver 2.7.10)
    Libraries:                   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (ver 2.7.10)
    numpy:                       /usr/local/lib/python2.7/site-packages/numpy/core/include (ver 1.12.1)
    packages path:               lib/python2.7/site-packages
 
  Python 3:
    Interpreter:                 /usr/local/bin/python3 (ver 3.6.1)
 
  Python (for build):            /usr/bin/python
 
  Java:
    ant:                         NO
    JNI:                         /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/include /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/include/darwin /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/include
    Java wrappers:               NO
    Java tests:                  NO
 
  Matlab:
    mex:                         /Applications/MATLAB_R2016b.app/bin/mex
    Compiler/generator:          Working
 
  Documentation:
    Doxygen:                     /usr/local/bin/doxygen (ver 1.8.11)
 
  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO
 
  Install path:                  /usr/local/Cellar/opencv3/3.2.0
 
  cvconfig.h is in:              /tmp/opencv3-20170521-37568-15s9x5w/opencv-3.2.0/macbuild
-----------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by ganesh-k13**
### Display Compiler Configuration
Output of `np.show_config` truncated till needed portion::
```diff
# CFLAGS=$CFLAGS" -Wno-maybe-uninitialized" python3.10d setup.py build_ext -i --cpu-dispatch=avx -j 12 | tee log
>>> np.show_config()
...
C compiler flags used in this NumPy install:
    compiler type = unix
    compiler name = x86_64-linux-gnu-gcc
+++    build flags = ['-pthread', '-Wno-unused-result', '-Wsign-compare', '-g', '-Og', '-Wall', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wno-maybe-uninitialized', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC']
    linker flags = ['-pthread', '-shared', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wno-maybe-uninitialized', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
    compiler preprocessors = ['x86_64-linux-gnu-gcc', '-pthread', '-E', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
    include dirs = ['numpy/core/src/common', 'numpy/core/src', 'numpy/core', 'numpy/core/src/npymath', 'numpy/core/src/multiarray', 'numpy/core/src/umath', 'numpy/core/src/npysort', 'numpy/core/src/_simd', '/usr/include/python3.10d', 'numpy/core/src/common', 'numpy/core/src/npymath']
CPP compiler flags used in this NumPy install:
    compiler type = unix
    compiler name = x86_64-linux-gnu-g++
+++    build flags = ['-pthread', '-Wno-unused-result', '-Wsign-compare', '-g', '-Og', '-Wall', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wno-maybe-uninitialized', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC']
    linker flags = ['-pthread', '-shared', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wno-maybe-uninitialized', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
    compiler preprocessors = ['x86_64-linux-gnu-gcc', '-pthread', '-E', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
    include dirs = ['numpy/core/src/common', 'numpy/core/src', 'numpy/core', 'numpy/core/src/npymath', 'numpy/core/src/multiarray', 'numpy/core/src/umath', 'numpy/core/src/npysort', 'numpy/core/src/_simd', '/usr/include/python3.10d', 'numpy/core/src/common', 'numpy/core/src/npymath']

# python3.10d setup.py build_ext -i --cpu-dispatch=avx -j 12 | tee log
>>> np.show_config()
...
C compiler flags used in this NumPy install:
    compiler type = unix
    compiler name = x86_64-linux-gnu-gcc
---    build flags = ['-pthread', '-Wno-unused-result', '-Wsign-compare', '-g', '-Og', '-Wall', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC']
    linker flags = ['-pthread', '-shared', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
    compiler preprocessors = ['x86_64-linux-gnu-gcc', '-pthread', '-E', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
    include dirs = ['numpy/core/src/common', 'numpy/core/src', 'numpy/core', 'numpy/core/src/npymath', 'numpy/core/src/multiarray', 'numpy/core/src/umath', 'numpy/core/src/npysort', 'numpy/core/src/_simd', '/usr/include/python3.10d', 'numpy/core/src/common', 'numpy/core/src/npymath']
CPP compiler flags used in this NumPy install:
    compiler type = unix
    compiler name = x86_64-linux-gnu-g++
---    build flags = ['-pthread', '-Wno-unused-result', '-Wsign-compare', '-g', '-Og', '-Wall', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC']
    linker flags = ['-pthread', '-shared', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-g', '-Og', '-ffile-prefix-map=/build/python3.10-18rSsq/python3.10-3.10.0~b1=.', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
    compiler preprocessors = ['x86_64-linux-gnu-gcc', '-pthread', '-E', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
    include dirs = ['numpy/core/src/common', 'numpy/core/src', 'numpy/core', 'numpy/core/src/npymath', 'numpy/core/src/multiarray', 'numpy/core/src/umath', 'numpy/core/src/npysort', 'numpy/core/src/_simd', '/usr/include/python3.10d', 'numpy/core/src/common', 'numpy/core/src/npymath']
```

Notice the extra `'-Wno-maybe-uninitialized'` in case of the first output with extra `CFLAGS`. Not sure how and why the extra flags are coming for normal compilation :)

On a side note, I tried many things, like injecting the variables into globals of `__config__.py`, but given there are two files and we will depend on the fact that format does not change is risky. Moving the generation to a later time seems hard, quite frankly I don't think we can. If we do, however, we can add a subclass of `system_info` which would be pretty.

I wanted to add FORTRAN as well but thought let's see how this goes first.

resolves: #10983

### CODE REVIEW

**Comment by mattip** [comment]
This is getting a bit unwieldy. Could we add some kind of structure to the copious output? Maybe a flag `output=str` (default, like today) with a `output=dict` non-default variant, that would then allow users to somehow filter what they get back

**Comment by ganesh-k13** [comment]
Yeah completely agree. I can rework the output format for both proposed `str` and `dict`. We could add other modes like CSV as well?

**Comment by mattip** [comment]
Whatever makes sense. We can spread out the work over a few PRs if the choices get complicated.

**Comment by ganesh-k13** [comment]
Writing to a python file does not seem ideal. Let me try dumping to a YAML and reconstructing the data. Can add flexibility in display this way. I'll try it out, I'm ok to revert back anytime. Moving to draft for now.

**Comment by ganesh-k13** [comment]
Sample generated YAMLs: https://gist.github.com/ganesh-k13/a7968fc287557a7fc791c9462149d2da

The plan is to remove all `globals` calls in `__config__` and load these YAMLs. I'll pick up SIMD stuff from `numpy.core._multiarray_umath` and refine the display. Hoping to make it extensible and make it easy to add new display stuff.

**Comment by ganesh-k13** [comment]
With Meson coming in, I'm going to try something with that. Will close this for now.

**Comment by rgommers** [comment]
@ganesh-k13 here is what's probably the best way to go about using Meson for this kind of info: https://github.com/scipy/scipy/issues/16803#issuecomment-1283311313

**Comment by ganesh-k13** [comment]
Ah that's pretty neat! I'll start a new PR by following that issue, always wanted to refactor the `__config__`. Thanks @rgommers!

**Pull request closed without merging**
