### PR TITLE
BUG: Fix reference leak in niche user old user dtypes

### LINKED ISSUE #25949: BUG: Structured arrays do not clean up properly when freed, causing memory leaks
### Describe the issue:

Given a structured array with a field of type object, when the array is freed, NumPy 1.24 and earlier would decref the objects in the array allowing them to be freed. Since 1.25 this no longer happens, so the objects are leaked. This was introduced in https://github.com/numpy/numpy/pull/23620 and persists in the latest release (1.26.4).

Summary of behaviour in 1.24:
- `PyArray_ClearBuffer` is called when the array is freed
- `PyArray_GetClearFunction` returns `func=traverse_fields_function` with `auxdata` set to a `fields_clear_data` struct with `fields[0]` pointing to `clear_object_strided_loop`
- `clear_object_strided_loop decrefs every item in the array before clearing it

Summary of behaviour in 1.25.0:
- `PyArray_ClearBuffer` is called when the array is freed
- `PyArray_GetClearFunction` returns `func=zerofill_fields_function` with `auxdata` set to a `fields_clear_data` struct with `fields[0]` pointing to `fill_zero_object_strided_loop`
- `zerofill_fields_function` memsets the array item to zero, then calls `fill_zero_object_strided_loop`, which copies a `PyObject` representing zero into the array and increfs it

That last point should makes it clear that this is a bug: the new item is increfed, but the previous item is zeroed out without first decrefing.

Note that my dtype implements `fill` and `fillwithscalar`: it would be natural to call these when the array is being zeroed, but they are not called.

### Reproduce the code example:

```python
# custom.Custom is an object which prints a message when it is freed. With NumPy 1.24.2 the message is printed twice, with 1.25.0 the message is printed only once.
import custom
import numpy as np
x = np.array([custom.Custom()])
del x
y = np.array([custom.Custom()], dtype=custom.custom_dtype)
del y

# C code with the implementation of the Custom object and the structured dtype is below.

#include <Python.h>
#include <numpy/arrayobject.h>

typedef struct {
    PyObject_HEAD
} CustomObject;

void custom_dealloc (PyObject *self) {
    printf("Deallocating Custom object\n");
    Py_TYPE (self) -> tp_free ((PyObject *) self);
}

static PyTypeObject CustomType = {
    .ob_base = PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "custom.Custom",
    .tp_doc = PyDoc_STR("Custom objects"),
    .tp_basicsize = sizeof(CustomObject),
    .tp_itemsize = 0,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_new = PyType_GenericNew,
    .tp_dealloc = custom_dealloc,
};

static PyModuleDef custommodule = {
    .m_base = PyModuleDef_HEAD_INIT,
    .m_name = "custom",
    .m_doc = "Example module that creates an extension type.",
    .m_size = -1,
};

static PyObject *custom_getitem(void *data, void *arr);
static int custom_setitem(PyObject *item, void *data, void *arr);
static void custom_copyswapn(void *dest, npy_intp dstride, void *src, npy_intp sstride, npy_intp n, int swap, void *arr);
static void custom_copyswap (void *dest, void *src, int swap, void *arr);
static npy_bool custom_nonzero (void* data, void* arr);
static int custom_fill (void *data, npy_intp length, void *arr);
static int custom_fillwithscalar (void *buffer, npy_intp length, void *value, void *arr);

PyArray_ArrFuncs arrayFuncs;

PyMODINIT_FUNC
PyInit_custom(void)
{
    PyObject *retval = NULL;
    PyObject *module = NULL;
    PyArray_Descr *objDescr = NULL;
    PyArray_Descr *descrProto = NULL;
    PyArray_Descr *descr = NULL;
    PyObject *fields = NULL;
    int typeCode;

    import_array ();

    PyArray_InitArrFuncs(&arrayFuncs);
    arrayFuncs.getitem   = custom_getitem;
    arrayFuncs.setitem   = custom_setitem;
    arrayFuncs.copyswapn = custom_copyswapn;
    arrayFuncs.copyswap  = custom_copyswap;
    arrayFuncs.nonzero   = custom_nonzero;
    arrayFuncs.fill      = custom_fill;
    arrayFuncs.fillwithscalar = custom_fillwithscalar;

    objDescr = PyArray_DescrFromType (NPY_OBJECT);
    descrProto = PyArray_DescrNew(objDescr);
    fields = PyDict_New();
    if (PyDict_SetItemString (fields, "custom", Py_BuildValue ("(Oi)", (PyObject *) objDescr, 0))) {
        goto exit_cleanup;
    }

    descrProto->type    = 'C';
    descrProto->typeobj = &PyBaseObject_Type;
    descrProto->f       = &arrayFuncs;
    descrProto->fields  = fields;
    descrProto->names   = Py_BuildValue ("(s)", "custom");
    fields = NULL;

    typeCode = PyArray_RegisterDataType (descrProto);
    if (typeCode == -1) {
        goto exit_cleanup;
    }

    descr = PyArray_DescrFromType (typeCode);
    if (descr == NULL) {
        goto exit_cleanup;
    }

    module = PyModule_Create(&custommodule);
    if (module == NULL) {
        goto exit_cleanup;
    }

    if (PyModule_AddObjectRef(module, "custom_dtype", (PyObject *) descr) < 0) {
        goto exit_cleanup;
    }

    if (PyType_Ready(&CustomType) < 0) {
        goto exit_cleanup;
    }

    if (PyModule_AddObjectRef(module, "Custom", (PyObject *) &CustomType) < 0) {
        goto exit_cleanup;
    }

    if (PyType_Ready(&CustomType) < 0) {
        goto exit_cleanup;
    }

    retval = module;
    module = NULL;

exit_cleanup:
    Py_XDECREF(module);
    Py_XDECREF(objDescr);
    Py_XDECREF(descrProto);
    Py_XDECREF(descr);
    Py_XDECREF(fields);
    return retval;
}

static PyObject *custom_getitem(void *data, void *arr) {
    PyObject *ret = (PyObject *) (*(PyObject **) data);
    Py_XINCREF (ret);
    return ret;
}

static int custom_setitem(PyObject *item, void *data, void *arr) {
    PyObject *orig = *((PyObject**) data);
    *(PyObject **) data = item;
    Py_XINCREF(item);
    Py_XDECREF(orig);
    return 0;
}

static NPY_INLINE void bswap (PyObject **val) {
    char *bytes = (char *) val;

    size_t fwd = 0;
    size_t bwd = sizeof (*val) - 1;

    for (; fwd < bwd; ++fwd, --bwd) {
        const char tmp = bytes[fwd];
        bytes[fwd] = bytes[bwd];
        bytes[bwd] = tmp;
    }
}

static void custom_copyswapn(void *dest, npy_intp dstride, void *src, npy_intp sstride, npy_intp n, int swap, void *arr) {
    char *Dest = (char *) dest;
    char *Src  = (char *) src;

    npy_intp i;

    if (Src == NULL && !swap) {
        return;
    }

    for (i = 0; i < n; i++) {
        PyObject **d = (PyObject **) (Dest + dstride * i);

        if (Src != NULL) {
            PyObject **s = (PyObject **) (Src + sstride * i);
            PyObject *orig = *d;
            *d = *s;
            Py_XINCREF (*d);
            Py_XDECREF (orig);
        }

        if (swap) {
            bswap (d);
        }
    }
}

static void custom_copyswap (void *dest, void *src, int swap, void *arr) {
  PyObject **s = (PyObject **) src;
  PyObject **d = (PyObject **) dest;

  if (src != NULL) {
    PyObject *orig = *d;
    *d = *s;
    Py_XINCREF (*d);
    Py_XDECREF (orig);
  }

  if (swap) {
    bswap (d);
  }
}

static npy_bool custom_nonzero (void* data, void* arr) {
  return NPY_TRUE;
}

static int custom_fill (void *data, npy_intp length, void *arr) {
    printf("Called fill\n");
    return 0;
}

static int custom_fillwithscalar (void *buffer, npy_intp length, void *value, void *arr) {
    printf("Called fillwithscalar\n");
    return 0;
}
```

### Error message:

_No response_

### Python and NumPy Versions:

1.26.4
3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]

### Runtime Environment:

```
[{'numpy_version': '1.26.4',
  'python': '3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) '
            '[Clang 14.0.6 ]',
  'uname': uname_result(system='Darwin', node='HN49DX6RGC', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'armv8',
  'filepath': '/Users/cbrown/mambaforge/envs/xpress-test2/lib/python3.10/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
```

### Context for the issue:

We use structured dtypes in our commercial Python extension: https://pypi.org/project/xpress. The memory leaks are causing issues in customer environments.

### PR DESCRIPTION
**Pull request by seberg**
This was just a typo, add a test for the regression (checked that it triggered it).

Closes gh-25949

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Thanks sebastian! Sorry for missing the typo during review of the original PR...

**Comment by charris** [comment]
@seberg This doesn't backport to 1.26.x due to missing `PyArrayMethod_GetTraverseLoop`. Is it safe to ignore?

**Comment by seberg** [comment]
It would make sense to backport, the name of the loop changed, though.

**Comment by seberg** [comment]
Sorry, should be called `get_traverse_loop_function`.  If it doesn't work, I suspect that the one user already complained and has the work-around.

**Pull request merged**
