### PR TITLE
DOC: Merge together DISTUTILS.rst.txt#template-files" and distutils.rst#conversion-of-src-files #13129

### PR DESCRIPTION
**Pull request by ojaswi12**
I have included a description from the conversion-of-src fille, as well as added a link to read more about the conversion in Fortan files and non-Fortan files. What changes should I make if any?

### CODE REVIEW

**Comment by eric-wieser** [comment]
You should delete the original files too. As is, you've gone from 2 duplicate to three duplicates :)

**Comment by mattip** [comment]
I think you meant to modify [`doc/DISTUTILS.rst.txt`](http://www.numpy.org/devdocs/reference/distutils_guide.html), which is `include` ed in `/doc/source/reference/distutils_guide.rst`, note the extra `txt` at the end.

**Comment by mattip** [comment]
also you should be working on a branch, not on master. Please follow the [developer workflow](http://www.numpy.org/devdocs/dev/gitwash/development_workflow.html#basic-workflow).

**Comment by mattip** [comment]
changing the file name together with changing the content makes it harder to review the changes, The rename should be via `git mv oldfile newfile` not `git add newfile; git rm oldfile`

**Comment by ojaswi12** [comment]
sorry sir, I'll fix it
[DISTUTILS.rst.txt](https://github.com/numpy/numpy/files/3021336/DISTUTILS.rst.txt)

**Comment by eric-wieser** [comment]
> The rename should be via `git mv oldfile newfile` not `git add newfile; git rm oldfile`

Git doesn't know the difference between those two options without an intermediate commit (although SVN does). In general the solution to that kind of issue is just to make two commits, and try to isolate things to move-only commits, and everything else.

**Comment by ojaswi12** [comment]
I created a new PR with the correct changes in place.

**Comment by mattip** [comment]
xref #13211

**Pull request closed without merging**
