### PR TITLE
MAINT: add 'nightly' (= 3.5ish) to travis build matrix

### PR DESCRIPTION
**Pull request by njsmith**
Not sure if this works, but it's [documented](http://docs.travis-ci.com/user/languages/python/#Nightly-build-support) as being [recently added](https://twitter.com/travisci/status/573899818336129024) so let's see what Travis makes of this PR.

### CODE REVIEW

**Comment by juliantaylor** [comment]
fwif, we already have a 3.5 test build in gh-5772, its going to fail on a zipfile change

**Comment by njsmith** [comment]
Oh, interesting. My motivation is #6000, which is impossible to test at all without a real 3.5 build...

It does look like this PR is working, in that Travis does claim to be running a test against "Python 3.5.0a4+".

**Comment by juliantaylor** [comment]
Currently debian is ahead of travis so called nightly. In the other PR more stuff is failing than here.

I'm not so sure about adding python nightlys to our regular tests, useful during cpython's release phase, before that it will probably just add noise. But it could be worth a try at least.

**Comment by njsmith** [comment]
Yeah, I wouldn't want it in general, but between now and when 3.5-final gets released it seems pretty useful.

**Comment by njsmith** [comment]
Have we filed a bug about the `GzipFile` thing upstream?

**Comment by juliantaylor** [comment]
To my knowledge no one has yet.

**Comment by juliantaylor** [comment]
mh the new failure is not in numpy but nose itself ... that will not be fun to get sorted.

**Comment by njsmith** [comment]
wow, yeah, travis "nightly" says it's hg revision 1158f5d7a48e, which is from May 7. That's before they even branched 3.5 off from trunk.

**Comment by njsmith** [comment]
We could also some version of 3.5 to travis as a "failure allowed" matrix entry, so at least we'll be able to easily peek in and check by hand to make sure we haven't broken new stuff.

**Comment by njsmith** [comment]
Having taken a look at the GzipFile issue, I'm not going to bother filing a bug upstream: #6016

**Comment by njsmith** [comment]
Also the nose issue is no big deal... it's just a deprecation warning, so worst case we just filter it out in the tests.

**Comment by charris** [comment]
The imp module also raises a PendingDeprecation on import. I had a mostly complete PR for that...

**Comment by njsmith** [comment]
I filed the nose issue upstream as nose-devs/nose#929.

**Comment by charris** [comment]
Let's have this in for a while, we can always neglect the results ;) Thanks Nathaniel.

**Comment by njsmith** [comment]
I'll just note for the record that afaict the way this works is that you
get whatever was the latest version of 3.5 (or maybe 3.6) at the moment
when Travis last rolled out a new machine image (which happens ~monthly).

A more predictable approach would be to have our test scripts pull down the
latest 3.5 prerelease and build it manually, but I can leave that until
someone feels inspired...

**Pull request merged**
