### PR TITLE
[DOC]Small release doc fix

### PR DESCRIPTION
**Pull request by nouiz**
I did this PR for Theano and my first PR in numpy https://github.com/numpy/numpy/pull/306/files is from 2012.

### CODE REVIEW

**Comment by njsmith** [comment]
Whoops, thanks. The list of contributors is auto-generated, so the script probably got confused by a changed email address or something...

**Comment by njsmith** [comment]
@charris: I guess this needs a backport also...

**Comment by charris** [comment]
@njsmith Yep, needs a `.mailmap` entry, the name has changed from "Frederic" to "Frederic Bastien"

**Comment by charris** [comment]
Note for future reference, I'm doing the release notes updates in the 1.12.x branch for forward port after release.

**Comment by njsmith** [comment]
> I'm doing the release notes updates in the 1.12.x branch

Doh, sorry.

**Comment by charris** [comment]
No problem.

**Pull request merged**
