### PR TITLE
Revert "ENH: Enabled the use of numpy.vectorize as a decorator"

### PR DESCRIPTION
**Pull request by mattip**
Revert #23061. This was generated by pushing the "revert" button on the original PR.

There are problems with this:
- a broken test that I did not notice when merging
- it broke scipy, see [this comment](https://github.com/numpy/numpy/pull/23061#issuecomment-1484561901)

### CODE REVIEW

**Comment by mattip** [comment]
Closes #23461 by reverting the PR.

**Comment by charris** [comment]
Thanks Matti.

**Review by charris — APPROVED** [review]

**Comment by charris** [comment]
Hmm, seems I can't merge this. @mattip Feel free to merge.

**Comment by seberg** [comment]
Github has some hickups currently... lets hope it gets better soon.

**Comment by WarrenWeckesser** [comment]
Thanks @mattip.  Hopefully it will only take a few tweaks to get the improved `vectorize` ready to merge again.

**Pull request merged**
