### PR TITLE
MAINT: remove dSFMT

### PR DESCRIPTION
**Pull request by mattip**
In order to ground the discussion about which BitGenerator to include/remove, this PR suggests removing `dSFMT` - which is a faster/more advanced `MT19937`. Quoting [@rkern](https://github.com/numpy/numpy/pull/13675#issuecomment-502427589) (hopefully not taken too much out of context):

> it's just a fast member of the Mersenne Twister family; it shares all of MT19937's statistical failings while not actually being the same as MT19937. I just don't see the user base who wants to conservatively stay within the MT family despite having proven statistically-better options, but not so conservative that they won't stay with MT19937. That's a tough needle to thread.

Any other thoughts?

### CODE REVIEW

**Comment by jakirkham** [comment]
FWIW Julia uses dSFMT. I don't know whether that is a reason to keep or not. Just figured it was worth noting.

**Comment by rkern** [comment]
[My thoughts on that.](https://github.com/numpy/numpy/pull/13675#issuecomment-502427589)

Short form: having `DSFMT` in numpy per se doesn't help much with Julia compatibility. We're making our own choices for seeding, and there's no real hope of bitstream compatibility with our distributions and computations on top. Cross-language interoperation (where Julia and Python are communicating) is something to think about, but that's better implemented in a Julia-interop package.

**Comment by seberg** [comment]
The only reason would be if it is common to say: I want to reproduce as closely as possible, so want to use the same algorithm. But that seems like a weak argument, because 1. it should not matter for pretty much anything and 2. you do not get identical in any case.
Also, if that happens, that just is a point to make these available easily, not necessary to have them in numpy. If this is a pain point, I would be fine with having some of the extra generators live inside the numpy organization (I agree with Ralf, that moving to scipy seems not like a great way to handle this)

**Comment by jakirkham** [comment]
Certainly compatibility is one consideration.

Though it is also interesting that Julia chose dSFMT. Presumably they went through a similar process of looking at a few different PRNGs and debating their merits before settling on dSFMT. What persuaded them to use dSFMT over something else? What criteria did they use to decide? This is probably also more relevant to the larger discussion here of what PRNGs to keep in NumPy or drop (as we are effectively having that same conversation ;).

**Comment by rkern** [comment]
Like all of the Mersenne Twister family, `dSFMT` fails statistical quality tests like TestU01 and PractRand. Whatever Julia's reasons are, [we have chosen](https://github.com/numpy/numpy/issues/13635) (long rambling thread, sorry) to privilege statistical quality above other considerations, at least for the selection of a default. The question at hand now is whether or not we still expose `dSFMT` as a non-default option provided by numpy itself. That has less to do with the qualities of `dSFMT` per se, which is probably what Julia's reasoning is more about. Arguments like being able to port from Julia easily are more germane (though, IMO, weak, for the reasons I've given).

**Comment by mattip** [comment]
I have moved the code to numpy/bitgenerators. As of today it is not yet building, I hope to fix that over the next few days but that enables merging this PR as the code will not get lost.

**Comment by bashtage** [comment]
I've moved to -1 on dSFMT:

1. There is a MT variant that must be included.
2. [Julia is likely moving from dSFMT](https://github.com/JuliaLang/julia/issues/27614), although they appear to have the exact same issue that has been cropping up here.
3. If one wanted to have a faster MT, then SFMT is in practice a good bit faster accross the range of distributions since most rely on having 64 bits of randomness, which takes 2 calls to dSFMT.

**Comment by bashtage** [comment]
One final point: the biggest case for a *SFMT is x86. This is not likely enough to push it back to +1.

**Comment by charris** [comment]
Looks pretty much like consensus here, so merging this.

**Comment by jakirkham** [comment]
> 2. [Julia is likely moving from dSFMT](https://github.com/JuliaLang/julia/issues/27614), although they appear to have the exact same issue that has been cropping up here.

This is good to know. Thanks for sharing that. 🙂

**Pull request merged**
