### PR TITLE
#10779 Changed the way numpy.squeeze handles newer and older objects

### PR DESCRIPTION
**Pull request by durgeshra**
Changed the older code to the corrected one given in the issue #10779

### CODE REVIEW

**Comment by njsmith** [comment]
Hey, thanks!

I was a bit terse in the bug report -- this will need some tests added too, in particular to make sure that if we have an object with a `def squeeze(self)` method, then `np.squeeze(obj)` and `np.squeeze(obj, axis=None)` successfully call `obj.squeeze()`, and that `np.squeeze(obj, axis=0)` raises an error.

It'd also be good to add a mention to the release notes.

**Comment by durgeshra** [comment]
Hi! I have corrected the code as guided by you. It should work fine now. Can you elaborate what it means to mention the release notes?

**Comment by durgeshra** [comment]
Hi @njsmith ! I have corrected the code as guided by you. It should work fine now. Can you elaborate what it means to mention the release notes?

**Comment by durgeshra** [comment]
Hi @njsmith ! I have corrected the code as guided by you. Also rectified my syntax errors. It should work fine now. Can you elaborate what it means to mention the release notes?

**Comment by njsmith** [comment]
Hi again!

When I said "test", I meant a [unit test](https://en.wikipedia.org/wiki/Unit_testing), like the code in `numpy/core/tests/test_numeric.py` or `numpy/core/tests/test_regression.py`. Unfortunately, numpy is a pretty old and complicated project that can be hard to get started working on, and it tends to assume that you're already pretty familiar with things like testing, and python 2/python3 compatibility, and have some idea about the purpose of the things you're changing. And also unfortunately, I'm afraid we don't generally have enough spare time to help people catch up with those kinds of things :-(. So numpy's probably not the best place to start contributing to open source. But good luck though! Maybe we'll see you in a year or two once you're a little more experienced :-)

**Pull request closed without merging**
