### PR TITLE
ENH: Add riscv support

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by njsmith** [comment]
Does this ... do anything? It seems like it's just defining a new constant that nothing ever looks at...

**Comment by kraj** [comment]
right. this is first step in fixing the build though

**Comment by pv** [comment]
It removes the "Unknown CPU" error message, so probably not useful to merge as is, without confirming that the build actually works (including floating point etc. that the CPU flag controls).

**Comment by kraj** [comment]
Fair enough. I only have QEMU up here right now. I will try to run the unit tests on it and see how far I get.

**Comment by charris** [comment]
@kraj Any progress on this?

**Comment by seberg** [comment]
This was added in 718d9e866b (there was discussion about it also in gh-8213)

**Pull request closed without merging**
