### PR TITLE
DOC: Fix typos

### PR DESCRIPTION
**Pull request by jwilk**
Found using [mwic](http://jwilk.net/software/mwic) and [anorack](https://github.com/jwilk/anorack).

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Looks good to me

**Comment by eric-wieser** [comment]
@charris, is modifying past release notes OK?

**Comment by charris** [comment]
@eric-wieser I think fixing typos is OK.

**Comment by charris** [comment]
Thanks @jwilk ,

**Pull request merged**
