### PR TITLE
TEST: move test_ufunc and test_umath

### PR DESCRIPTION
**Pull request by El-Vim55**
This is my first pull request. The problem was simple but learning git took some time. The problem I solved was for #8300

### CODE REVIEW

**Comment by melissawm** [comment]
Hi @Gnoblin44 , thanks for your PR. In order to get the right people to review it, it's better to be more explicit in the title and description. Similarly, your commit message [should be descriptive](https://numpy.org/doc/stable/dev/development_workflow.html#writing-the-commit-message) in order to add context to this fix.

**Comment by Gnoblin44** [comment]
oopsie daisy, silly me

**Comment by mattip** [comment]
Is this the beginning of more extensive work? It seems so far you have renamed two files. The issue spoke about 

- There needs to be a clear distinction between testing the ufunc object (test_ufunc) and the ufuncs instances (test_umath). Currently the two types of tests are mixed between the files.
- The testing of the various ufuncs is far from complete.

**Comment by Gnoblin44** [comment]
@mattip Hmmm... Its a little vague, not sure what im supposed to do

**Pull request closed without merging**
