### PR TITLE
ENH: Fix alignment of repr for array subclasses

### PR DESCRIPTION
**Pull request by eric-wieser**
Test case:

```python
>>> class foo(np.ndarray): pass
>>> np.eye(2).view(foo)  #before
foo([[ 1.,  0.],
       [ 0.,  1.]])
>>> np.eye(2).view(foo)  #after
foo([[ 1.,  0.],
     [ 0.,  1.]])
```

<s>Where should this test go?</s> Added to `test_arrayprint.py`

### CODE REVIEW

**Comment by mhvk** [comment]
Very nice! I think this is worth mentioning in the release notes, since people with subclasses may well have written work-around `__repr__` for this (somewhat true for `Quantity`...).

**Comment by eric-wieser** [comment]
I think as soon as you want to print any extra kwargs, you still end up writing your `__repr__` anyway, so I wouldn't say it's that much of a feature. Either way, I missed a test case, so I added to the release notes while I was there

**Comment by mhvk** [comment]
I think this is all set, but probably good to leave it open for a day or two so others can comment as well.

**Comment by eric-wieser** [comment]
damn, looks like #8612 didn't work

**Comment by eric-wieser** [comment]
@mhvk, good to go?

**Comment by mhvk** [comment]
OK, going...

**Pull request merged**
