### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by krishnakatyal**
made readme file better by adding more details about numpy
and  Added installation guideline 
guide about installation makes it easy for first-time users to install  the package and  emphasis on the recommended installation process

### CODE REVIEW

**Comment by krishnakatyal** [comment]
@mattip kindly review my  PR

**Comment by eric-wieser** [comment]
When making this kind of change, it's important to say why you're making it, so that reviewers know what they should be looking for.

Could you edit your top comment to explain what you think makes this new readme format better?

**Comment by krishnakatyal** [comment]
@eric-wieser done!

**Comment by krishnakatyal** [comment]
> When making this kind of change, it's important to say why you're making it, so that reviewers know what they should be looking for.
> 
> Could you edit your top comment to explain what you think makes this new readme format better?

thanks will keep that in mind!

**Comment by rgommers** [comment]
I'm afraid this is not an improvement. The moved links are now in the wrong place under the "call for contributions" header. The first sentence is a little weird. And I'd prefer not to have the brief mention of `pip` here.

**Comment by krishnakatyal** [comment]
@rgommers 
kindly check my new PR 
I have made some improvements

**Comment by eric-wieser** [comment]
Moved to #14815. Please update existing prs rather than creating new ones.

**Pull request closed without merging**
