### PR TITLE
DOC: added tutorials.md

### PR DESCRIPTION
**Pull request by christophmckinzie**
Sorry, its for a OSS course assignment.

### CODE REVIEW

**Comment by rkern** [comment]
I'm sorry, but we cannot use our resources to help you with that. Please do not reopen or submit another classwork PR to this repository. We know that you do not have control over what you are assigned by your instructor, but we don't consent to having our repository be used as classwork practice.

**Comment by rkern** [comment]
If your assignment was to engage with an OSS project and make a meaningful contribution, [please see our guidelines for new developers](https://numpy.org/doc/stable/dev/index.html). NumPy is a mature project, so it can sometimes be hard to find a place to get started if one is not a longtime user, but we do have many open issues that can be worked on.

**Comment by christophmckinzie** [comment]
I completely understand. I do think it would be nice for the README.md to have some basic links to tutorials either way.

**Comment by rkern** [comment]
We're happy to [have that discussion with you](https://numpy.org/doc/stable/dev/howto-docs.html#contributing-new-pages).

**Pull request closed without merging**
