### PR TITLE
DOC,MAINT: Update wording surrounding `fname` parameter for loadtxt/genfromtxt

### PR DESCRIPTION
**Pull request by rossbar**
Both `loadtxt` and `genfromtxt` can read from lists and generators of strings. The `genfromtxt` docstring captures this, but the docstring for `loadtxt` was missing this info. Also updates the wording in the `np.loadtxt` exception message, along with minor formatting changes. Note also that I've changed the exception type from `ValueError` to `TypeError` in np.loadtxt as I believe it's more accurate.

Techinically, the first argument can be not only a list of str/bytes, but any non-string Iterable of strings - but I couldn't figure out how to explain this without reducing the clarity of the docstring, so I stuck with the wording in `genfromtxt` instead.

### CODE REVIEW

**Comment by melissawm** [comment]
I wonder if this could create problems for people checking for this `ValueError`. Other than that, looks good to me!

**Comment by charris** [comment]
Should add a compatibility release note about the error type change. I don't think it will cause trouble, but with a million plus users you never know.

**Comment by mattip** [comment]
Wouldn't it be simpler to keep the previous exception type?

**Comment by rossbar** [comment]
Since there's discussion around whether to change the exception type, I'll back that out into a separate issue so that we can focus on the wording updates only in this PR.

**Comment by mattip** [comment]
Thanks @rossbar

**Pull request merged**
