### PR TITLE
BUG: when checking for cblas in has_cblas(), it needs to be in _lib_names to be found

### PR DESCRIPTION
**Pull request by rbonthond**
I had to add 'cblas' to _lib_names for the has_cblas() function to find it.

### CODE REVIEW

**Comment by charris** [comment]
What system are you running on? Note that cblas is not always a separate library and the current setup works for most cases, so it is possible that this is not the correct fix.

**Comment by rbonthond** [comment]
This is on RHEL66

**Comment by charris** [comment]
Does using `site.cfg` work? Also, what version of numpy. I'm wary of this patch because I would have expected other reports of a problem starting with 1.8. Are you using ATLAS or some other version of BLAS?

**Comment by rbonthond** [comment]
yes i'm using a ~/.numpy-site.cfg:
```
[blas]
library_dirs = /usr/lib64:/usr/lib64/atlas
include_dirs = /usr/include:/usr/include/atlas
```

installed rpm's:

```
blas-devel-3.2.1-4.el6.x86_64
blas-3.2.1-4.el6.x86_64
```

Open to suggestions on how to do this differently.

**Comment by charris** [comment]
Hmm, blas and cblas should come in with atlas, I wonder if having explicit blas is causing a problem?

**Comment by charris** [comment]
I don't like this much because CBLAS is not BLAS. Note that `blas-devel-3.2.1-4.el6.x86_64` is not atlas, you probably want `atlas-devel` installed.

**Comment by charris** [comment]
We might want to add a `CBLAS` section to `numpy-site.config`. This also looks a bit strange, ` ~/.numpy-site.cfg`. Why the hidden file in your home directory? Normally that file would be in the same directory as the source and named `site.cfg`, but I might be missing something. Where did you get the source?

@rgommers Thoughts?

**Comment by rgommers** [comment]
> This also looks a bit strange, ``~/.numpy-site.cfg``. Why the hidden file in your home directory? Normally that file would be in the same directory as the source and named ``site.cfg``, but I might be missing something.

``~/numpy-site.cfg`` is OK. From the docstring in ``system_info.py``:

    The file 'site.cfg' is looked for in

    1) Directory of main setup.py file being run.
    2) Home directory of user running the setup.py file as ~/.numpy-site.cfg
    3) System wide directory (location of this file...)

Keeping ``site.cfg`` in your source tree has the disadvantage that it gets lost with ``git clean -xdf``, so using ``~/numpy-site.cfg`` can be useful.

**Comment by rgommers** [comment]
I agree that this doesn't look quite right. If there's a ``cblas`` lib in one of those paths, even if it's a separate lib, why isn't there a ``blas`` right next to it?

**Comment by charris** [comment]
The question is, where is cblas? I don't think it comes in with blas. On my fedora system it is provided by atlas and openblas.

**Comment by mattip** [comment]
Closing, for lack of reproducibility. @rbonthond if this is still an issue please reopen with more details.

**Pull request closed without merging**
