### PR TITLE
FIX: Added check for negative dimensions passed to np.resize()

### LINKED ISSUE #15030: BUG: `numpy.resize` returns wrong size when using `-1` syntax for axis length.
When resizing an array with `numpy.resize` and passing `-1` for the size of one of the dimensions you will not always get a shape that is compatible with the original shape.

### Reproducing code example:

```python
import numpy as np

test = np.arange(0, 444)
print(test.shape)
print(np.resize(test, (4, -1)).shape)
print(np.reshape(test, (4, -1)).shape)
```
prints
```
(444,)
(4, 110)
(4, 111)
```
Note that the call to `np.resize` returned an array of shape `(4, 110)` which is not compatible with the original shape, `(444,)`.

I posted about this on [SO](https://stackoverflow.com/questions/59147217/numpy-resize-gives-an-unexpected-array-size-when-using-1-syntax) and someone pointed out that the `resize` *method* of an array forbids using `-1` syntax and gives the following error message
``` python
ValueError: negative dimensions not allowed
```
 Should this restriction also be enforced on `numpy.resize`? Also, just out of curiousity, why is `-1` forbidden on a `resize` but not on a `reshape`?

### Numpy/Python version information:

1.17.4 3.7.1 (default, Jan  6 2019, 15:33:42) 
[Clang 9.1.0 (clang-902.0.39.2)]

### PR DESCRIPTION
**Pull request by anchit1729**
Added the negative value check and corresponding error for np.resize(). Fixes: #15030

### CODE REVIEW

**Comment by mattip** [comment]
The test failure is not related: it is an occasional "hiesenbug" that hits matmul on 32-bit widows.

Thanks for the first attempt at this PR. Please try to follow the [developer workflow(https://numpy.org/devdocs/dev/index.html), especially this part:
> Use a properly formatted commit message, write tests that fail before your change and pass afterward, run all the tests locally. Be sure to document any changed behavior in docstrings, keeping to the NumPy docstring standard.

This needs new tests, probably near the other reshape tests. Future commit messages should follow the standard.

**Comment by eric-wieser** [comment]
Duplicate of #15037, it would be worth reading the discussion there

**Comment by anchit1729** [comment]
I've added the tests as well, and tried to keep my commit messages more in line with the guidelines.

**Comment by eric-wieser** [comment]
In my opinion the patch at  #15037 is cleaner, the question is whether we should just switch to using the approach in https://github.com/numpy/numpy/pull/15037#issuecomment-573017457.

**Comment by mattip** [comment]
Closing in favor of gh-15037

**Pull request closed without merging**
