### PR TITLE
BUG: Fixes for building on Cygwin.

### PR DESCRIPTION
**Pull request by charris**
Rebase of #16246.

Changes needed to get numpy to compile on Cygwin, then a few changes to try to reduce the number of test failures due to extension module overlap, then marking differences I think are due to floating-point implementation or fork() failures.

Someone should probably check whether the list of ignored floating-point failures is reasonable.
Most of those have been around since 1.16 a while back.

Rebased to get all the commits gathered together and on top of master. Should probably all be squashed at some point,
this is for review.

@DWesl ping.

### CODE REVIEW

**Comment by charris** [comment]
A lot of the fixes look to be disabling tests, which seems not quite right. Ideally the tests would pass without fixing. Its might be that we should just wait for Cygwin to improve or stop supporting it.

**Comment by DWesl** [comment]
A lot of those `xfail` marks are for `fork()` failures on 32-bit Cygwin, which the Cygwin maintainers have been discouraging people from using for a year or so now because there are so many, so just dropping those would work for me.  If that becomes a problem on 64-bit again I can mark the failing tests then.

The edits to `npy_common.h` to mark which floating functions have trouble should probably stay in, and the note that the Windows dynamic loader doesn't really have a concept of `rpath` should probably also stay.  I'm fine with keeping the list of floating-point tests that give weird results as a local patch or note to self.

Should I start the PR over?  Proposed commit order:

1. Change some tests with loops to use `pytest.mark.parametrize`
2. The `test_system_into` patch to avoid weird behavior with certain tempfile names
3. Tell `fcompiler.gnu` that Windows doesn't do `rpath`
4. Tell `npy_common.h` which functions numpy should use its own versions for

The first two might work better as separate PRs.

**Comment by charris** [comment]
> Should I start the PR over? Proposed commit order:

You are in a better position to carry this forward than I am. How would you like to proceed?

**Comment by DWesl** [comment]
The added compiler flags to avoid a ufunc crash got merged in another PR, and my `fork` problems on 64-bit seem to have resolved themselves, so those portions of the PR are gone now, and there's not terribly much left.

**Comment by DWesl** [comment]
> > Should I start the PR over? Proposed commit order:
> 
> You are in a better position to carry this forward than I am. How would you like to proceed?

The first two changes in that list aren't really connected to the others, so I should probably separate those into different PRs focused on just those.  I'm not sure if the Cygwin-specific changes would be better handled on this PR or as a new PR or what.

**Comment by charris** [comment]
@DWesl I would prefer to close this and deal with new PRs. I want to know what would be most convenient for you.

**Review by dstiers11 — APPROVED** [review]

**Comment by DWesl** [comment]
The `Test_SIMD_ALL_256_FMA3__AVX2_[usf]{8,16,32,64}` tests are segfaulting, as are the `Test_SIMD_FP_256_FMA3__AVX2_f{32,64}` tests and the `Test_SIMD_INT_256_FMA3__AVX2_[us]{8,16,32,64}` tests and the `Test_SIMD_BOOL_256_FMA3__AVX2_b{8,16,32,64}` tests.  I'll try to figure out how to skip those so I can avoid using `pytest-forked`, which makes the tests really slow.  

I should probably also figure out why they're segfaulting at some point.  `/proc/cpuinfo` mentions AVX2 and FMA but not FMA3, and that roughly exhausts my knowledge of how to debug the crashes.

**Comment by rgommers** [comment]
> I should probably also figure out why they're segfaulting at some point. `/proc/cpuinfo` mentions AVX2 and FMA but not FMA3, and that roughly exhausts my knowledge of how to debug the crashes.

@seiko2plus or @mattip any advice here on how to debug?

**Comment by seiko2plus** [comment]
@DWesl, we use the term `FMA3` instead of `FMA` to avoid any confusion with `AMD/FMA4`.

@rgommers,
> any advice here on how to debug?

- Testing CPU detecting mechanism -> `python runtests.py -t numpy/core/tests/test_cpu_features.py`
  NOTE: You will have to patch `test_cpu_features.py` to enables `Cygwin`.
- Testing `_SIMD` module itself without any dispatched features:
   *  `python runtests.py --cpu-dispatch="none" -t numpy/core/tests/test_simd_module.py`
   *  `python runtests.py --cpu-dispatch="none" -t numpy/core/tests/test_simd.py`
- Testing `_SIMD` module with certain dispatched features, e.g. `sse41`
   `python runtests.py --simd-test="baseline sse41" -t numpy/core/tests/test_simd.py`
- Checking the build log, and finally GDB or LLDB

**Comment by DWesl** [comment]
Out of curiosity, should `abs(inf + nanj)` be `inf` or `nan`?  My first thought was `nan` because there's a `nan` in there, but the tests seem to be expecting `inf`.

**Comment by seberg** [comment]
> should `abs(inf + nanj)` be `inf` or `nan`?

I am sure NaN is correct. If an `inf` result is tested, that could well be a bug in the complex `abs` implementation.

**Comment by DWesl** [comment]
> > should `abs(inf + nanj)` be `inf` or `nan`?
> 
> I am sure NaN is correct. If an `inf` result is tested, that could well be a bug in the complex `abs` implementation.

Okay, I recently wrote a C program to check `cabsl(+-inf + nanj)` and `cabsl(nan +- infj)`, since those tests have been failing for months.  All four return `nan`.  The corresponding tests fail:
```bash
FAILED numpy/core/tests/test_multiarray.py::test_npymath_complex[complex256-inf-nan-npy_cabs-absolute] - AssertionError:
FAILED numpy/core/tests/test_multiarray.py::test_npymath_complex[complex256--inf-nan-npy_cabs-absolute] - AssertionError:
FAILED numpy/core/tests/test_multiarray.py::test_npymath_complex[complex256-nan-inf-npy_cabs-absolute] - AssertionError:
FAILED numpy/core/tests/test_multiarray.py::test_npymath_complex[complex256-nan--inf-npy_cabs-absolute] - AssertionError:
```
with the error:
```python
E       AssertionError:
E       Not equal to tolerance rtol=1e-07, atol=0
E
E       x and y nan location mismatch:
E        x: array(inf)
E        y: array(nan, dtype=float128)
```
I just noticed the dtype for `x` isn't right, so I'll look into fixing that.

**Comment by DWesl** [comment]
I tracked the `numpy.core._multiarray_tests.npy_cabs` call to `numpy/core/src/npymath/npy_math_complex.c.src` line 121, where it calls `npy_hypotl` and got stuck there.  I'm going to leave that be and post my other work.

**Comment by charris** [comment]
@DWesl Do you want me to keep this up?

**Comment by DWesl** [comment]
You can close it if you want.  I'm running a last round of tests before creating the pull request, to see if any of the failing tests are passing now.

**Comment by WarrenWeckesser** [comment]
>  Out of curiosity, should abs(inf + nanj) be inf or nan?

Actually, it looks like the result should be `inf`, based on behavior specified in IEEE 754-2008.  I haven't read the full specification; this comment is based on a [comment](https://bugs.python.org/issue38382#msg354262) that @mdickinson made in a Python bug report.  And `inf` is the value returned by Python's `abs` and by `np.abs` in 1.19.5:

```
In [1]: import math                                                                                                 

In [2]: z = complex(math.inf, math.nan)                                                                             

In [3]: abs(z)                                                                                                      
Out[3]: inf

In [4]: import numpy as np                                                                                          

In [5]: np.__version__                                                                                              
Out[5]: '1.19.5'

In [6]: np.abs(z)                                                                                                   
Out[6]: inf
```
And there is also
```
In [11]: np.hypot(np.inf, np.nan)                                                                                   
Out[11]: inf
```

**Comment by seberg** [comment]
Makes sense, the usual safe bet is to say is to replace NaN with "any possible value".  The oddball is just that for complex two values for which `np.isnan()` is True, will have different values for these cases.  But I suppose that isn't really an issue.

**Comment by mdickinson** [comment]
Annex G of the C standard is also a useful (and more easily available) source of information for these corner cases. For the C11 standard, §G.6p6 has:

> Each of the functions cabs and carg is specified by a formula in terms of a real function (whose special cases are covered in annex F): cabs(x + iy) = hypot(x, y) [...]

while §F.10.4.3p1 has:

> hypot(±∞, y) returns +∞, even if y is a NaN.

**Pull request closed without merging**
