### PR TITLE
BUG: Added proper handling of median and percentile when nan's are prese...

### PR DESCRIPTION
**Pull request by empeeu**
...nt in array to close issue #586.

Also added unit tests.

### CODE REVIEW

**Comment by charris** [comment]
@juliantaylor Want to have a look?

**Comment by charris** [comment]
@juliantaylor ping.

**Comment by empeeu** [comment]
@homu I rebased again. Should be able to merge now.

**Comment by charris** [comment]
@empeeu homu is a github bot ;)

**Comment by empeeu** [comment]
O rly? That's good to know. Is it new?

**Comment by njsmith** [comment]
Pretty new:
   http://homu.io/
   http://mail.scipy.org/pipermail/numpy-discussion/2015-June/073058.html

On Mon, Jun 22, 2015 at 6:03 PM, Ueckermann <notifications@github.com>
wrote:

> O rly? That's good to know. Is it new?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/pull/5753#issuecomment-114315423>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by empeeu** [comment]
That's pretty cool. Never break again!

**Comment by juliantaylor** [comment]
I'm still not very happy about this change, but its probably more my irrational longing for optimal performance on well behaved data. As most people were for it when it was discussed, in it goes.
Thanks for the contribution and the patience.

**Comment by madphysicist** [comment]
As part of creating an `iqr` function in `scipy.stats`, I am relying on this functionality being present in `numpy` versions after `1.11.0b3`. Is there any reason, (such as backports or something else) why my assumption is not correct?

**Comment by juliantaylor** [comment]
it is unlikely something like this would get backported as its quite invasive so its probably fine, but in general you should always test for behaviour instead of version numbers, it is normal for distributions to backport patches.

**Comment by njsmith** [comment]
Also it's generally nice to wait until an actual release (like 1.11.0) before counting on anything, because the whole point of a prerelease cycle is that we sometimes discover problems and have to revert things. Maintaining backcompat is hard enough to start with without also having to satisfy downstream assumptions about behavior from the future :-)

**Comment by madphysicist** [comment]
@juliantaylor and @njsmith. Thanks for the advice. My problem is that there have been quite a few changes to `percentile` and `nanpercentile` starting with version `1.9.0`, so I have a complex decision tree that mostly throws warnings about incomplete functionality. I will do my best to test for behavior where possible, but in the worst case I will just use actual release numbers. Hopefully the scipy maintainers are a little more forgiving of `try...except` :-)

**Pull request merged**
