### PR TITLE
DOC: remove explanations.rst

### PR DESCRIPTION
**Pull request by seattletechdiary**

### CODE REVIEW

**Comment by mattip** [comment]
You also need to remove the reference in `doc/source/user/index.rst:34`.

**Comment by sleeplessinseattledev** [comment]
Hi @mattip,

Do you remove all of these lines(37 - 45) or just line 37?

Thanks!

**Comment by mattip** [comment]
Just the line that points to explanations_index

**Comment by mattip** [comment]
Third and final task to close  #17845

**Comment by mattip** [comment]
Thanks @sleeplessinseattledev

**Pull request merged**
