### PR TITLE
BUG: fix the search dir of dispatch-able sources

### PR DESCRIPTION
**Pull request by seiko2plus**
Fix the search dir of dispatch-able sources to allow including the
generated config headers within the dispatch-able sources.

### CODE REVIEW

**Comment by mattip** [comment]
I think the CircleCI failures would be fixed if this picked up gh-16857, since the Azure builds succeed. Could you just confirm that this changeset  does not include gh-16857? No need to rebase, I am happy to merge without rebasing.

**Comment by seiko2plus** [comment]
@mattip, yes, gh-16857 wasn't included. I rebase it anyway.

**Comment by mattip** [comment]
ahh, I was trying to conserve CI resources. oh well.

**Comment by mattip** [comment]
Thanks @seiko2plus

**Pull request merged**
