### PR TITLE
DOC: update runtests.py help docs to follow scipy

### PR DESCRIPTION
**Pull request by argriffing**
See https://github.com/scipy/scipy/pull/5659.

### CODE REVIEW

**Comment by charris** [comment]
I assume the new documentation is correct for NumPy?

**Comment by argriffing** [comment]
> I assume the new documentation is correct for NumPy?

That's a good question! Honestly I'm not sure. @pv would know.

**Comment by pv** [comment]
Doesn't look like it behaves the same: https://github.com/numpy/numpy/pull/7056/files#diff-fdaa2edbb1e3772fb7c998d5324dee25R208

**Comment by charris** [comment]
Closing then. @argriffing Feel free to sync numpy with scipy and update the notes after.

**Pull request closed without merging**
