### PR TITLE
DOC: added linalg.multi_dot to doc

### PR DESCRIPTION
**Pull request by solarjoe**

### CODE REVIEW

**Comment by eric-wieser** [comment]
Duplicate of #8723 ?

**Comment by solarjoe** [comment]
Jup, sorry, I could not find where to change the name to add DOC:, but I found it now.
Now I am looking for the labels...

**Comment by eric-wieser** [comment]
You didn;t change the commit message though, only the PR name, which is irrelevant.

You can change the commit message with:

    git commit --amend -m "DOC: added linalg.multi_dot to function list" && git push -f

**Comment by eric-wieser** [comment]
Nevermind, I've fixed that for you. Force-pushing to someone else's master is a little weird

**Comment by eric-wieser** [comment]
@charris: Are documentation fixes like this backport candidates?

**Comment by ComFreek** [comment]
Unfortunately, this change is still not reflected in the online documentation: https://docs.scipy.org/doc/numpy-dev/reference/routines.linalg.html
Or am I looking at the wrong site?

**Comment by eric-wieser** [comment]
You're looking in the right place, but as the footer there says, it was last built in january.

**Pull request merged**
