### PR TITLE
MAINT: core: less function pointer casting in arraytypes.c.src

### PR DESCRIPTION
**Pull request by larsmans**
Followup to #5968.

### CODE REVIEW

**Comment by charris** [comment]
It would have been nicer if the type `PyArray_VectorUnaryFunc` had been defined differentlly, `void` was overused IMHO. Note that the C standard requires `void *` and `char *` to have the same storage. But since `PyArray_VectorUnaryFunc` is in the public API, it is probably best to leave it alone as you do.

**Comment by larsmans** [comment]
They might have the same storage, but compilers are going to complain nevertheless.

In defense of the current API, it does signal that the argument is not a string.

**Comment by charris** [comment]
The problem of overusing void is that it provides no useful information or check on what the arguments can be. For instance, if one argument is always `PyArrayObject *` it is counter productive to use `void *` in the prototype, something of a cop out. Thinking it over, here I think here it would be better to change the prototype.  If that raises warning for extensions, the warnings are probably deserved.

**Comment by larsmans** [comment]
There will be no warnings for extensions that pass a `PyArrayObject*` where a `void*` is expected, since the conversion is implicit, but there will be undeserved warnings/errors for extensions that use function pointers. I admit these will be rare, but changing the prototype is API breakage. If you think that's not a problem, I'll change the types.

**Comment by njsmith** [comment]
This would only be API breakage, not ABI breakage, right? (In general for
numpy ABI breakage is more serious.)

On Tue, Jun 16, 2015 at 1:24 AM, Lars <notifications@github.com> wrote:

> There will be no warnings for extensions that pass a PyArrayObject* where
> a void* is expected, since the conversion is implicit, but there will be
> undeserved warnings/errors for extensions that use function pointers. I
> admit these will be rare, but changing the prototype is API breakage. If
> you think that's not a problem, I'll change the types.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/pull/5971#issuecomment-112330985>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by larsmans** [comment]
On any platform where pointer sizes differ, the ABI is already broken.

**Comment by charris** [comment]
I was never that happy with the function prototypes, but casting non-conforming functions (which is legal) to fix the problem and not casting them back for the call is a hack. Which is to say, this PR is probably the right way to go in the short run. As you say, casting function pointers to `void *` is illegal in standard C. IIRC, some of the sort functions used to pass a comparison function in that way. But mixing data/function pointers is probably a bad idea in anycase.

**Comment by charris** [comment]
Thanks @larsmans .

**Comment by larsmans** [comment]
Oh... I had actually started work on a version that changes the prototypes to use `PyArrayObject*`, but I hadn't pushed it yet.

**Comment by charris** [comment]
@larsmans I'd be happy to have that one too, I'd just push it off to 1.11.

**Pull request merged**
