### PR TITLE
MAINT: Update to Cython 0.29.30.

### PR DESCRIPTION
**Pull request by felixxm**
See https://github.com/numpy/numpy/pull/21514#issuecomment-1128999118.

### CODE REVIEW

**Comment by mattip** [comment]
Please also pin `environment.yml` for conda builds
https://github.com/numpy/numpy/blob/ad1096884e82a8176e7b5125d168ceeca77c3bf7/environment.yml#L9-L14

**Comment by felixxm** [comment]
> Please also pin `environment.yml` for conda builds

Pinned :+1:

**Comment by mattip** [comment]
mamba and conda have 0.29.30, so let's put this in. Maybe the conda pinning will rattle the gitpod build's cache and make the build pass.

**Comment by charris** [comment]
> Do you have a rough timeline for the 1.22 backport?

Should be out in a day or two.

**Pull request merged**
