### PR TITLE
BUG: np.any() and np.all() should return boolean for object arrays

### PR DESCRIPTION
**Pull request by nlee737**
closes https://github.com/numpy/numpy/issues/4352

### CODE REVIEW

**Comment by fivemok** [comment]
I noticed something about this particular example in the documentation:

```
>>> o=np.array([False])
>>> z=np.any([-1, 4, 5], out=o)
>>> z, o
(array([ True]), array([ True]))
```

According to the docs about the ```out``` parameters:

```
out : ndarray, optional
Alternate output array in which to place the result. It must have the same shape as the expected output and its type is preserved (e.g., if it is of type float, then it will remain so, returning 1.0 for True and 0.0 for False, regardless of the type of a). See doc.ufuncs (Section “Output arguments”) for details.
```

the above example should not work since the ```np.any([-1,4,5], out=o)``` call will return a scalar boolean.

**Comment by eric-wieser** [comment]
There is already a PR for this at #11857 - I'd recommend you read through the comments there before going further.

**Comment by fivemok** [comment]
My apologies, I assumed #11857 is no longer active since its last activity date. I can close this if it's still active but if it's not, this PR should cover both ```np.any()``` and ```np.ndarray.any()```.

**Comment by seberg** [comment]
Closing, we should do this in a similar way, but probably not this way, plus there are conflicts.  See comments on the other PR.

**Pull request closed without merging**
