### PR TITLE
DOC: Fix Incorrect document in Beginner Docs

### LINKED ISSUE #15433: Typo in Beginner Docs
The last code block in [this section](https://numpy.org/devdocs/user/absolute_beginners.html#how-to-get-unique-items-and-counts) of the python docs is incorrect.

```
>>> unique_rows, occurence_count, indices = np.unique(a_2d, axis=0,
>>> return_counts=True, return_index=True)
>>> print('Unique Rows: ', '\n', unique_rows)
>>> print('Occurrence Count:', '\n', occurence_count)
>>> print('Indices: ', '\n', indices)
Unique Rows:
  [[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]
Occurrence Count:
  [0 1 2]
Indices:
  [2 1 1]
```
Indices and Occurence Count have flipped values

### PR DESCRIPTION
**Pull request by kishimoto-banana**
This PR fixes [Beginner Docs](https://numpy.org/devdocs/user/absolute_beginners.html#how-to-get-unique-items-and-counts).

Closes https://github.com/numpy/numpy/issues/15433

### CODE REVIEW

**Comment by mattip** [comment]
This can be tested with 
```
python tools/refguide_check.py --rst doc/source/user/absolute_beginners.rst
```
which shows many more errors. Care to fix them up?

**Comment by kishimoto-banana** [comment]
Sorry..., there are errors I don't know how to fix.

**Comment by WarrenWeckesser** [comment]
@kishimoto-banana, thanks for fixing this!  While there are other issues in this file, we don't have to get them all fixed in this pull request. It would be nice, however, to fix the issues that are directly related to this example of using `np.unique`.  You have fixed the worst problem, but there are two other minor issues that we might as well fix now.

First, when a line in the Python shell is continued on multiple lines, the prompt changes to `... `, so the transcript of the shell session where `np.unique` is called should look like

    >>> unique_rows, indices, occurence_count = np.unique(a_2d, axis=0,
    ... return_counts=True, return_index=True)

Second, the actual output of `print('Unique Rows: ', '\n', unique_rows)` is

```
Unique Rows:  
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```
Note the extra space in the output of the first row of the array.  That is the result of the `print` function printing a space between each of the items that it prints.  This behavior can be changed to give us the desired output by adding the argument `sep=''` to the print function:

```
>>> print('Unique Rows: ', '\n', unique_rows, sep='')
Unique Rows: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```
Could you add these two suggestions to this pull request?

**Comment by WarrenWeckesser** [comment]
Another minor bit of clean up: I don't know why the newlines characters were given as separate arguments here.  The `print` calls could be simplified to

```
  >>> print('Unique Rows:\n', unique_rows, sep='')
  >>> print('Indices:\n', indices)
  >>> print('Occurrence Count:\n', occurence_count)
```

**Comment by WarrenWeckesser** [comment]
One more: the spelling of `occurence_count` should be fixed to be `occurrence_count`.

**Comment by mattip** [comment]
Will fix the other comments in a follow-on PR to fix up all the doctest failures.

**Pull request merged**
