### PR TITLE
ENH:  Add new tensordotmat function to numeric.py.

### PR DESCRIPTION
**Pull request by ydup**
This function aims at the tensor dot product with the 2D matrix. And It is worth noting that the dimension order of tensor does not change after calculation. (This is different from tensordot)

### CODE REVIEW

**Comment by charris** [comment]
New functions should be discussed on the mailing list.

**Comment by eric-wieser** [comment]
I'm struggling to understand the motivation/purpose of this function. I assume this relates to #12111?

**Comment by ydup** [comment]
@eric-jones 
Not exactly, this function is based on tensordot, but can solve the axes change problem when users dot product a tensor(high dimension) with 2D matrix at any axes. I consider that this is different from ```matmul```.

**Comment by eric-wieser** [comment]
So using einsum``-like notation, you're looking for `xxxjxxx,jk->xxxkxxx`, where `x` is some non-contracted dimension?

**Comment by charris** [comment]
Needs a release note.

**Comment by mattip** [comment]
The sentiment on the issue was not to add tensordotmat. @ydup if you feel strongly NumPy should add this function, please start a discussion on the mailing list explaining why this is more than a documentation issue, and what added value the new function provides.

**Comment by ydup** [comment]
@mattip Thank you. I am doing more test of the tensordot, and compare it with the ```tensorflow.tensordot``` simultaneously. If it's necessary, I will start a discussion on ```tensordotmat``` : )

**Comment by seberg** [comment]
It appears that this PR was incorrectly closed by github while renaming the NumPy main (previously master) branch. I suspect because the original repository was also deleted.  That seems like a github issue, but I am not sure there is a solution to it aside from opening a new PR.

Sorry about that issue, I did not review the PR. However, even if the local branches were deleted, it seems the work is still available (e.g. using `https://github.com/numpy/numpy/pull/<pull-request-number>` with the command line interface), so we can assist creating a new PR!

**Pull request closed without merging**
