### PR TITLE
BUG: SWIG overloaded long functions on pyfragments.swg will seg fault

### LINKED ISSUE #16492: SWIG: pyfragments.swg dereferences a nullptr for overloaded functions
When SWIG (post SWIG-1.3.23) encounters overloaded functions, it generates a wrapper function for each one. Then, it creates a single entry point function for Python to call. This entry point function attempts to find the right overload. It does this by performing test casts of the arguments until it finds an overload that works, which it then calls. This bug happens during those test casts, because SWIG passes a nullptr for the value to convert.

### Reproducing code example:

This reproduces the issue for Windows (64 bit)
```cpp
void repro(unsigned long i = 0)
{
}
```

This reproduces the issue for Linux/gcc (64 bit)
```cpp
void repro(size_t i = 0)
{
}
```

We get a segmentation fault in both scenarios.
The issue comes from
https://github.com/numpy/numpy/blob/master/tools/swig/pyfragments.swg#L59
and
https://github.com/numpy/numpy/blob/master/tools/swig/pyfragments.swg#L109

It can be fixed by first checking for a nullptr (like SWIG's other pyfragments.swg do):

For example:
```cpp
if(!val) return SWIG_OK;
PyArray_CastScalarToCtype(obj, (void*)val, ulongDescr);
```

I'd submit a formal pull request, but for legal reasons I am only allowed to submit this bug report for now.

### PR DESCRIPTION
**Pull request by i-am-b-soto**
Hello numpy!,  
@gieseanw explained the problem and the solution in #16492. Hopefully I can provide another layer of insight. 

**Problem**
The following c function definitions will through a seg fault when attempting to pass a numpy.int32/numpy.int64 object to them:

```
void my_size_t(size_t i=0) ;
void my_long(long i = 0);
void my_llong(long long i = 0);
void my_ulong(unsigned long i = 0);
```
**Why?** 
When SWIG encounters a function overload (with the same number of parameters, it appears) it will attempt to convert the given Python parameters to the appropriate C types. Note SWIG treats functions with default values as overloaded functions. Pyfragments.swg partially defines the functions SWIG will use to convert numpy values to (in our case) long and ulong values

in pyfragments.swg lines 59  and 109 such functions make this call:
`PyArray_CastScalarToCtype(obj, (void*)val, longDescr);` 
Which is a numpy C library that will, in this scenario, through a segmentation fault when val = NULL

**The Solution**
As suggested by @gieseanw I've added 
`if (!val) return SWIG_OK` 
on lines 58 and 109 of **pyfragments.swg** to check if the value is null before calling `PyArray_CastScalarToCtype(obj, (void*)val, longDescr);`

This should work because the value will be populated with an address the next time SWIG calls these functions. And so, the correct values will be passed to their functions. 

I hope this makes sense and ends up contributing to the numpy cause.  

fixes #16492

EDIT: Added fixes

### CODE REVIEW

**Comment by gieseanw** [comment]
As the bug submitter, this looks correct to me.

**Comment by mattip** [comment]
This has a merge conflict. Any ideas how to write a test for the change?

**Comment by charris** [comment]
This seems reasonable AFAICT, if a bit of a hack. Needs a release note.

**Comment by seberg** [comment]
Thanks for the push, Chuck.  We discussed it briefly, and the changes look right.  Of course the use-case looks also weird and Swig is de-facto untested.

Thanks @Iamsoto lets give it a shot :).

**Comment by seberg** [comment]
@charris, sorry, I missed you wanted a release note for this?  I suppose it might effectively unbreak this code path, but not sure.

Please ping if you think that should happen, I can do that tomorrow.

**Comment by charris** [comment]
I think we can skip the release note, not sure how to word it in any case. If something breaks in the release, it should be enough to look at the changelog.

**Pull request merged**
