### PR TITLE
NEP:  add note on Python integer "exceptions" to NEP 50

### PR DESCRIPTION
**Pull request by seberg**
These are not really exceptions to the rules, but may look like exceptions when compared to the behavior of other operations.

Also briefly notes that we should probably aspire to allowing such "exceptions", but I don't think we should be beholden to make it possible in every case (some of these are non-trivial to make work!).

Also added one sentence that this applies to everything of course.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
While you're at it, would you mind adding a short section in the NumPy 2.0 migration guide that describes NEP 50 and links to the NEP?

**Review by rgommers — APPROVED** [review]
LGTM, thanks @seberg

**Comment by seberg** [comment]
I suspect that may need more massaging, so rather started a new PR here: gh-25683.  It's a tough choice of where to draw the line and what to just omit completely.

**Comment by mattip** [comment]
OK, so let's put this in and continue the discussion on #25683

**Pull request merged**
