### PR TITLE
BUG: raise error trying to coerce object arrays containing timedelta64('NaT') to StringDType

### PR DESCRIPTION
**Pull request by ngoldbaum**
Without the change to `stringdtype_is_known_scalar_type`, the second iteration of the for loop in the test would fail. Datetime already fails, so this just makes timedelta consistent with that.

I discovered this running the pandas test suite against my pandas string dtype built on StringDType.

@seberg is there maybe a better way to write `is_known_scalar_type` than using a bunch of if statements?

### CODE REVIEW

**Review by seberg — APPROVED** [review]

**Comment by mhvk** [comment]
> is there maybe a better way to write `is_known_scalar_type` than using a bunch of if statements?

no real suggestion, but the top of the function seems a bit duplicated with https://github.com/numpy/numpy/blob/dda030fa4d404cd6fabc95a5e6cad8fd3072ef7c/numpy/_core/src/common/get_attr_string.h#L7-L37

Given short-circuiting, at least writing it as a series of `||` may be more readable...

p.s. Really getting off-topic, but also somewhat duplicated with https://github.com/numpy/numpy/blob/dda030fa4d404cd6fabc95a5e6cad8fd3072ef7c/numpy/_core/src/multiarray/dtypemeta.c#L830-L860

**Comment by seberg** [comment]
Good point, `||` does seem a bit more concise and nicer.

**Comment by ngoldbaum** [comment]
Good call about all these similarities. The stringdtype code predates adding this to numpy. There was definitely some copy/pasting that can be reverted now that the code lives in numpy.

**Review by mhvk — APPROVED** [review]
Code changes itself look good! (And maybe best to do any refactoring elsewhere!)

**Comment by ngoldbaum** [comment]
> (And maybe best to do any refactoring elsewhere!)

Maybe.. but I went ahead and did it before I saw this comment 🙃. Was simple enough though...

**Review by mhvk — APPROVED** [review]
That `python_builtins_are_known_scalar_types` name is not brilliant (`is_python_version_of_scalar_type` might be better), but that's really out of scope here...  So, approving...

**Comment by mhvk** [comment]
No idea why the sanitizer job is filling its log with `AddressSanitizer:DEADLYSIGNAL` - seems unrelated...

**Comment by ngoldbaum** [comment]
> No idea why the sanitizer job is filling its log with AddressSanitizer:DEADLYSIGNAL - seems unrelated...

Yeah, that's #25875 which seems to have gotten particularly annoying today for some reason. I disabled that action and it shouldn't show up in future CI logs until we figure out what's wrong and re-enable it.

**Comment by mhvk** [comment]
Indeed, seems good to disable - though hopefully the alternatives work - it caught few bugs in my FFT gufunc implementations!

**Comment by seberg** [comment]
Thanks, lets put this in.  I just remembered we actually do have a faster version for finding the builtin scalar types I think (it sorts them and does a binary search for finding them when you do `np.dtype(np.float64)`, which we could use here).

But let's fix the bug for now.

**Pull request merged**
