### PR TITLE
MAINT: bytes() → b""

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by rkern** [comment]
These are minor stylistic choices. There are no significant upsides or downsides for either choice. In such cases, we prefer to leave things be and not make small PRs to change them. If we did want to make such changes, agreed by the larger development team, then we'd try to make one larger PR that made more of the changes at once.

**Comment by DimitriPapadopoulos** [comment]
You're right, this is an effort to avoid issues reported by linters such as pyupgrade. However, by the time I fix or review all errors, the larger PR request might need difficult merging, which I wanted to avoid, using small PRs.

**Comment by charris** [comment]
I actually like the idea of updating the code, but not everyone agrees :) Maybe we could develop a plan to do that.

**Comment by rkern** [comment]
I don't necessarily mind that project as a whole, but I never saw any discussion that we had agreed to do it or do it this way. I don't see any issue that mentions pyupgrade in such a context. Keeping the codebase pyupgrade-clean is an ongoing commitment supported by changes to our dev process and CI, not a one-shot effort, so we all actually need to agree to it. Coordinating review effort is also a way to obtain a short review turnaround on widespread PRs that touch a lot of the codebase.

If we do decide to do this, we need a tracking issue that describes the scope and motivation for the changes, and each PR should reference that issue. In isolation and without a PR description, this just looks like the tiny low-effort PRs (well, at least one that has lower effort to create than to review) that we sometimes get from those who just want a commit credit in a popular project.

**Comment by charris** [comment]
Maybe we could start with a simple list of upgrades suggested by pyupgrade so we could see what we are dealing with. @DimitriPapadopoulos could you put together such a list? We would also need a strategy for applying such upgrades.

**Comment by DimitriPapadopoulos** [comment]
See “[Implemented features](https://github.com/asottile/pyupgrade#implemented-features)” for a general overview of the changes suggested by [pyupgrade](https://github.com/asottile/pyupgrade).

A few notes:
1. Most importantly, [pyupgrade](https://github.com/asottile/pyupgrade) is not a really a linter, in the sense that it doesn't simply report issues, rather it fixes them.
2. Also, it is “uncompromising”, like [black](https://github.com/psf/black), in the sense that you cannot disable classes of issues. There are few options:
   ```
     -h, --help            show this help message and exit
     --exit-zero-even-if-changed
     --keep-percent-format
     --keep-mock
     --keep-runtime-typing
     --py3-plus, --py3-only
     --py36-plus
     --py37-plus
     --py38-plus
     --py39-plus
     --py310-plus
     --py311-plus
   ```
   Most of the suggestions make sense, but my experience with other modules is that maintainers may dislike some of the opinionated pyupgrade changes, particularly:
   * [Set literals](https://github.com/asottile/pyupgrade#set-literals)
   * [Dictionary comprehensions](https://github.com/asottile/pyupgrade#dictionary-comprehensions)
   * [redundant `open` modes](https://github.com/asottile/pyupgrade#redundant-open-modes)
   
   Yet, they make sense if you think about it. I am less surprised by the result of `{"string"}` (`{'string'}`) than the result of `set("string")` (`{'g', 'i', 'n', 'r', 's', 't'}`).
3. You may need to run pyupgrade twice. These changes are applied sequentially:
   * [printf-style string formatting](https://github.com/asottile/pyupgrade#printf-style-string-formatting) (from old prtinf-style formatting to `format()`)
   * [f-strings](https://github.com/asottile/pyupgrade#f-strings) (from `format()` to f-strings)
4. Some changes break formatting, so pyupgrade is best run together with [black](https://github.com/psf/black) or some other code formatter. For example:
   ```python
   "Some text: %s %s %s %s %s %s" % (parameter_a, parameter_b,
                                     parameter_c, parameter_d,
                                     parameter_e, parameter_f
   )
   ```
   yields:
   ```python
   "Some text: {} {} {} {} {} {}".format(parameter_a, parameter_b,
                                     parameter_c, parameter_d,
                                     parameter_e, parameter_f
   )
   ```
5. Changing all occurrences of `format()` to f-strings will not always be possible or reasonable, at least not without adding temporary variables for readability. Yet, pyupgrade will give up in some cases where f-strings do make sense.
6. I may have seen incorrect suggestions once in a while – but don't take my word for it as I may be confusing different tools.

For the above reasons, I thought it would be best to review classes of issues fixed by pyugrade in a project, one pull request for each class of changes. This, of course, is somehow tedious, since pyupgrade does not provide a way to apply only a single rule at a time for easier reviewing.

**Comment by DimitriPapadopoulos** [comment]
Changes so far:
* #23826 applies [`open` alias](https://github.com/asottile/pyupgrade#open-alias)
* #23827 attempts to apply [Set literals](https://github.com/asottile/pyupgrade#set-literals) on part of the code but this was wrong, and I seem to recall actually **not** suggested by pyupgrade
* **⚠ still in progress**: #23833 applies [printf-style string formatting](https://github.com/asottile/pyupgrade#printf-style-string-formatting) and [f-strings](https://github.com/asottile/pyupgrade#f-strings) sequentially
* #23834 applies [`OSError` aliases](https://github.com/asottile/pyupgrade#oserror-aliases)
* #23837, this PR, applies [forced `str("native")` literals](https://github.com/asottile/pyupgrade#forced-strnative-literals)

Most suggested changes (perhaps 75%) are of class [printf-style string formatting](https://github.com/asottile/pyupgrade#printf-style-string-formatting) and [f-strings](https://github.com/asottile/pyupgrade#f-strings). This is the most complex task, because:
* pyupgrade breaks formatting, and I need to fix it manually,
* I try to modify manually the few cases where pyupgrade does not suggest to change `format()` to f-strings.

**Comment by DimitriPapadopoulos** [comment]
I feel it is best to start cleaning up the code, with manual formatting where needed, before thinking of automating pyupgrade runs someday.

Nevertheless, if you are interested in automating pyupgrade runs, you will find suggestions https://github.com/Slicer/Slicer/issues/6599 and elsewhere.

**Comment by DimitriPapadopoulos** [comment]
Is a new PR the best way to list upgrades suggested by pyupgrade and discuss a strategy for applying such upgrades?

**Comment by rkern** [comment]
Policy decisions are discussed on the [mailing list](https://mail.python.org/mailman3/lists/numpy-discussion.python.org/).

**Comment by charris** [comment]
You could also open an issue with content. This isn't the best place for ongoing discussion.

**Pull request closed without merging**
