### PR TITLE
MANT: searchsorted should return base ndarrays always

### PR DESCRIPTION
**Pull request by jaimefrio**

### CODE REVIEW

**Comment by njsmith** [comment]
Could you add a test for `digitize` too, since that was the change that we know actually broke code?

**Comment by jaimefrio** [comment]
Added the `digitize` tests.

**Comment by njsmith** [comment]
Thanks Jaime!

@homu r+

@charris: This needs a 1.10 backport -- is there some tag that should be added or issue opened or something?

**Comment by charris** [comment]
@njsmith I've been using the `1.10.0 release` milestone as a tag.

**Pull request merged**
