### PR TITLE
BUG: Ensure inf/nan removal in assert_array_compare is matrix-safe.

### PR DESCRIPTION
**Pull request by mhvk**
Fix the regression introduced by #8452.

### CODE REVIEW

**Comment by pv** [comment]
How about testing all the code paths --- for both x and y, one case with 
nan & inf, one with only nan, one without either, and loop over the 
cartesian product of all combinations.

**Comment by mhvk** [comment]
@pv - OK, I added a few more tests.

**Comment by seberg** [comment]
OK, can't think of an obvious nicer solution, so works for me. Thanks, hopefully its fine now....

**Comment by seberg** [comment]
Ah, well the naming of the commit could have been better....

**Comment by mhvk** [comment]
Oops, sorry about that.

**Comment by seberg** [comment]
No worries, just pressed the button before noticing :).

**Pull request merged**
