### PR TITLE
merge _compiled_base module into multiarray

### PR DESCRIPTION
**Pull request by juliantaylor**
like with our other mini modules I don't know of a reason why it needs to be separate, so merge it into multiarray.

### CODE REVIEW

**Comment by jaimefrio** [comment]
Nice! This will allow some nice refactorings by giving this module access to non-public functionality.

I am specifically thinking of removing the custom implementation of binary search that `interp` uses, and have it call the corresponding function from `npy_sort/binsearch` directly. We may even speed up `digitize` a bit by not having to call `PyArray_SearchSorted`, but get the lower level function from `npy_sort/binsearch` as well.

**Comment by juliantaylor** [comment]
should be ready now, had to move a function to umathmodule as it was using functions from it, good thing we have our debug tests.

**Comment by jaimefrio** [comment]
LGTM. Should we give it a day or two to get more eyes on it?

**Comment by jaimefrio** [comment]
Thanks Julian, in it goes.

**Comment by jaimefrio** [comment]
Hmmm... After merging this commit my numpy is no longer running any tests for `np.lib`... I think the issue is with having removed entirely `numpy/lib/setup.py`. Adding it back fixes this, see #5493, not sure if there is a better way of going about this...

**Pull request merged**
