### PR TITLE
BUILD: pin pygments to 2.6.1, 2.7.0 breaks custom NumPyC lexer

### PR DESCRIPTION
**Pull request by mattip**
Try to figure out what is going on with circleCI and doc building. Maybe time to move to githbu actions?

### CODE REVIEW

**Comment by mattip** [comment]
I have no idea why this build is failing. It worked, then broke but only on CircleCI.

**Comment by mattip** [comment]
closes gh-17301

**Comment by mattip** [comment]
It turns out the problem was an unpinned dependency on `pygments`. They updated the `CLexer` in the recent 2.7.0 release, which broke [a hack](https://github.com/numpy/numpy/blob/v1.19.2/doc/source/conf.py#L393) to the lexer tokens. While strictly speaking only the changes to `doc_requirements.txt` are needed to fix gh-17301, I think the other changes are worthwhile. 

A follow-on PR will fix the lexer, this PR is needed to unbreak the doc builds.

**Comment by charris** [comment]
Thanks for chasing that down.  I'm not going to wait on travisCI.

**Pull request merged**
