### PR TITLE
WIP, ENH: Valgrind long double limitations could prevent numpy from being imported

### PR DESCRIPTION
**Pull request by petef4**
This addresses issue https://github.com/numpy/numpy/issues/12930: numpy cannot be imported while running with Valgrind, in some cases. The error message was "cannot convert longdouble NaN to integer".

This PR fixes the inability of numpy to be imported under valgrind to two more test cases. There is no impact on regular use without valgrind. There is a limitation that under valgrind numpy.longdouble metadata is incomplete but seeing as valgrind does not support float80 that is unimportant.

There are two improvements to https://github.com/numpy/numpy/pull/16834. That used 10 bytes to match the known type for float80. One of the commits here discards a further 2 bytes from the other end so that 8 are now reliably matched.

The underlying issue is that Valgrind has a documented limitation that it does not support 80 bit floating point arithmetic. Internally Valgrind represents all such long double numbers in 64 bits. One manifestation of that is that exp2() of a long double returns nan for all inputs except zero. The second commit drops some intermediate precision down to float64 where arithmetic would fail.

Predicates in the code mean that if Valgrind were to implement arithmetic on types longer than float64 in the future then the special treatment would no longer be applied.

These changes do not lend themselves to standard testing as valgrind is involved. I have run regression tests for the case without valgrind and presumably existing tests will do a more thorough job on more architectures. 

One of my test cases is shown here, these results are after applying the fix.  The other involved the software I am developing and I did not spend time extracting a simple test case.

```
$ python/bin/python3.9 -c 'import numpy as np; print(np.finfo(np.longdouble("-0.1")))'
Machine parameters for float128
---------------------------------------------------------------
precision =  18   resolution = 1e-18
machep =    -63   eps =        1.084202172485504434e-19
negep =     -64   epsneg =     5.42101086242752217e-20
minexp = -16382   tiny =       3.3621031431120935063e-4932
maxexp =  16384   max =        1.189731495357231765e+4932
nexp =       15   min =        -max
smallest_normal = 3.3621031431120935063e-4932   smallest_subnormal = 4e-4951
---------------------------------------------------------------

$ valgrind --tool=memcheck python/bin/python3.9 -c 'import numpy as np; print(np.finfo(np.longdouble("-0.1")))'
==4923== Memcheck, a memory error detector
==4923== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4923== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==4923== Command: python/bin/python3.9 -c import\ numpy\ as\ np;\ print(np.finfo(np.longdouble("-0.1")))
==4923== 
[...]/python/lib/python3.9/site-packages/numpy/core/getlimits.py:529: UserWarning: The value of the smallest subnormal for <class 'numpy.float128'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
[...]/python/lib/python3.9/site-packages/numpy/core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float128'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Machine parameters for float128
---------------------------------------------------------------
precision =  18   resolution = 1.0000000000000004567e-18
machep =    -63   eps =        1.084202172485504434e-19
negep =     -64   epsneg =     5.42101086242752217e-20
minexp = -16382   tiny =       0.0
maxexp =  16384   max =        inf
nexp =       15   min =        -max
smallest_normal = 0.0   smallest_subnormal = 0.0
---------------------------------------------------------------

```

### CODE REVIEW

**Comment by seberg** [comment]
Thanks, I suspected the recent changes might have  made things a bit worse with running on valgrind, but I guess I never tried much since then.

Two things that would be nice if you could look into for me:
* I suspect we can simplify/remove all of the calculation `isnan` checks, etc. by wrapping the whole function into `with np.errstate(all="ignore")`, with some chance that even fixes some lingering bugs (unnecessary noise) anyway?
* By prepending those bytes, you we are pretending that longdouble actually has 80-bits of precision, when it really just has 64bits.  If you prepend `\0` bytes you should get the result for double, which is technically actually more correct?

It would be nice to avoid this problem all-together, but I guess that would require some typedef magic and checking for `valgrind.h` availibility in the core.  And I am not sure that is worthwhile (a lot of longdouble related code gives warnings in valgrind unfortunately, due to these undefined padding bytes).

**Comment by petef4** [comment]
- I will look at wrapping the whole function into `with np.errstate(all="ignore")`
- I had made the arbitrary call that as valgrind does not support longdouble except to a very limited extent that I would mimic the standard case. That followed the approach of the previous fix https://github.com/numpy/numpy/pull/16834. I will now look at making the valgrind case report the finfo for float64. It should still call it long double, that is permitted by C/C++ standards to be the same as double.

Typedef magic cannot work as valgrind is a run-time procedure, not compile.

As I hinted at the outset lack of float80 support in valgrind will cause grief of one form or another. Its longdouble will be imperfect but being able to use numpy at all is of overriding importance.

**Comment by petef4** [comment]
@seberg I've not forgotten, but set this to WIP. I will probably replace it with a different PR that will report longdouble as float64 under valgrind instead of pretending it is float80. So similar behaviour to now but without the crash. I am just home from hospital after major surgery and need to recuperate before resuming this work.

**Comment by seberg** [comment]
Hope you got better, but will close the PR for now.  A new PR (or revival is great of course).  valgrind works well enough for me with NumPy, so I don't think this needs "urgent" take up by someone else.  (But of course anyone is invited to take it up.)

**Pull request closed without merging**
