### PR TITLE
DOC: use nightly dependencies [skip actions] [azp skip] [skip travis]

### LINKED ISSUE #24334: DOC: build on circleCI is using a bad scipy version
I see exceptions like this in the [circleCI build log](https://app.circleci.com/pipelines/github/numpy/numpy/20888/workflows/99d32350-2d1a-4f48-8e23-95216349ff75/jobs/33481) when building docs on main. Should we pin scipy in the [requirements file](https://github.com/numpy/numpy/blob/4359c877d810e39be0ddaae53a5a17b91ede603e/doc_requirements.txt#L7) to a [nightly](https://anaconda.org/scipy-wheels-nightly/scipy) to pick up scipy/scipy#18973? The build is [using scipy 1.11.1](https://app.circleci.com/pipelines/github/numpy/numpy/20888/workflows/99d32350-2d1a-4f48-8e23-95216349ff75/jobs/33481)

<details><summary>Traceback</summary>

```

docstring of numpy.random._generator.Generator.gamma:68: WARNING: Exception occurred in plotting numpy-random-Generator-gamma-1
 from /home/circleci/repo/doc/source/reference/random/generated/numpy.random.Generator.gamma.rst:
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.9/site-packages/matplotlib/sphinxext/plot_directive.py", line 481, in _run_code
    exec(code, ns)
  File "<string>", line 10, in <module>
  File "/home/circleci/repo/venv/lib/python3.9/site-packages/scipy/special/__init__.py", line 780, in <module>
    from . import _orthogonal
  File "/home/circleci/repo/venv/lib/python3.9/site-packages/scipy/special/_orthogonal.py", line 81, in <module>
    from scipy import linalg
  File "/home/circleci/repo/venv/lib/python3.9/site-packages/scipy/__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/circleci/.pyenv/versions/3.9.17/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/circleci/repo/venv/lib/python3.9/site-packages/scipy/linalg/__init__.py", line 208, in <module>
    from ._basic import *
  File "/home/circleci/repo/venv/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 13, in <module>
    from ._decomp import _asarray_validated
  File "/home/circleci/repo/venv/lib/python3.9/site-packages/scipy/linalg/_decomp.py", line 22, in <module>
    from numpy import (array, isfinite, inexact, nonzero, iscomplexobj, cast,
ImportError: cannot import name 'cast' from 'numpy' (/home/circleci/repo/venv/lib/python3.9/site-packages/numpy/__init__.py)
```
</details>

The end result is that the [devdocs plots](https://numpy.org/devdocs/reference/random/generated/numpy.random.Generator.gamma.html) are missing, where [stable has them](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.gamma.html). It is worth checking that the 1.26 docs plot correctly.

### PR DESCRIPTION
**Pull request by mattip**
Fixes #24334

Use the nightlies index to install documentation dependencies, since building docs requires a newer scipy, matplotlib, pandas. Also update the docker image used to build docs to python3.11, since it should be faster.

### CODE REVIEW

**Comment by mattip** [comment]
Whoops, I didn't skip cirrusCI

**Comment by mattip** [comment]
In Python3.10, the error message for converting a complex to an int changed from
```
TypeError: can't convert complex to int
```

```
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'
```

so running doctests with 3.11 fails

**Comment by mattip** [comment]
Ready for review, the matplotlib plots now appear in the [rendered documents](https://output.circle-artifacts.com/output/job/c1618648-f2b7-4c89-ab29-df175949be3f/artifacts/0/doc/build/html/reference/random/generated/numpy.random.gamma.html#numpy.random.gamma)

**Review by rgommers — APPROVED** [review]
LGTM, the CI log shows that the latest nightlies are indeed pulled in, and the html docs look fixed. In it goes.

**Pull request merged**
