### PR TITLE
BUG: mask nan to 1 in ordered compare

### LINKED ISSUE #6428: msvc9 32-bit builds are unusable
numpy-1.10.0 compiled with Visual Studio 2008 for 32-bit Python fails many tests (only part of the output is shown):
```
Running unit tests for numpy
NumPy version 1.10.0
NumPy relaxed strides checking option: True
NumPy is installed in X:\Python27\lib\site-packages\numpy
Python version 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
nose version 1.3.7
....F.FF.E........................................................................
<snip>
======================================================================
FAIL: test_api.test_array_array
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "X:\Python27\lib\site-packages\numpy\core\tests\test_api.py", line 75, in test_array_array
    assert_equal(dat, [49.0, 46.0, 48.0])
  File "X:\Python27\lib\site-packages\numpy\testing\utils.py", line 295, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "X:\Python27\lib\site-packages\numpy\testing\utils.py", line 782, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "X:\Python27\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 100.0%)
 x: array([ 49.,  46.,  48.])
 y: array([ 49.,  46.,  48.])

======================================================================
FAIL: test_api.test_array_astype
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "X:\Python27\lib\site-packages\numpy\core\tests\test_api.py", line 187, in test_array_astype
    assert_equal(a, b)
  File "X:\Python27\lib\site-packages\numpy\testing\utils.py", line 295, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "X:\Python27\lib\site-packages\numpy\testing\utils.py", line 782, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "X:\Python27\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 100.0%)
 x: array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]], dtype=float32)
 y: array([[0, 1, 2],
       [3, 4, 5]])
<snip>
======================================================================
FAIL: test_inplace_floor_division_array_type (test_core.TestMaskedArrayInPlaceArithmetics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27\lib\site-packages\numpy\ma\tests\test_core.py", line 2244, in test_inplace_floor_division_array_type
    assert_equal(len(w), 0, "Failed on type=%s." % t)
  File "X:\Python27\lib\site-packages\numpy\ma\testutils.py", line 130, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal: Failed on type=<type 'numpy.int64'>.
 ACTUAL: 1
 DESIRED: 0

----------------------------------------------------------------------
Ran 5440 tests in 34.344s

FAILED (KNOWNFAIL=7, SKIP=9, errors=498, failures=221)
```
Reverting https://github.com/numpy/numpy/pull/6252 fixes this problem.

Builds using msvc9 64-bit, msvc10, msvc14, and icl do not show this problem.

I did not notice this before because I was testing the RCs with the Intel, not msvc, compilers.

### PR DESCRIPTION
**Pull request by juliantaylor**
msvc2008 32 bit seems to miscompile it otherwise.
closes gh-6428

### CODE REVIEW

**Comment by njsmith** [comment]
@cgohlke: can you confirm that this works for you too?

**Comment by njsmith** [comment]
@juliantaylor: well, I don't understand much from the code, so I'm sure it's fine but I guess I'll suggest that adding a comment might be good :-)

**Comment by charris** [comment]
@juliantaylor I'm going with the SSE2 solution, so going to close this. Thanks for working this problem under time pressure.

**Comment by juliantaylor** [comment]
I still think this is a reasonable change having a comparison including nan might be dodgy concerning floating point signals

**Comment by charris** [comment]
OK, thanks Julian

**Pull request merged**
