### PR TITLE
CI: add llvm/clang sanitizer tests

### LINKED ISSUE #25875: CI: Compiler sanitizers tests are hanging intermittently
The actions label is `gcc_sanitizers`. All of the test runs show errors, some of which look valid, but none cause the test to fail. I have to wonder where the bogus values come from, are they byproducts of the sanitizer? See https://github.com/numpy/numpy/actions/runs/8008572322/job/21875289661 for examples.

I also note that the time was normally around 20 minutes, it is now well in excess of 2 hours.  Something has changed.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Closes #25875.

Should fix the test hang in #26307.

### CODE REVIEW

**Comment by charris** [comment]
Seems to be hung.

**Comment by ngoldbaum** [comment]
Darn it's hanging in the same place as the gcc_sanitizers test used to hang.

I added [`faulthander_timeout`](https://docs.pytest.org/en/7.1.x/how-to/failures.html#faulthandler) which should prevent hangs and hopefully let us get a traceback if this happens again. I'll add it to the main branch as well. I'll also increase the timeout if 120 seconds is too short.

**Comment by ngoldbaum** [comment]
I've manually run the tests several times but haven't been able to reproduce the hang. Let me know if you notice this job hanging after merging this PR. I'll try to keep an eye on the action run log.

**Comment by charris** [comment]
The documentation backport hung, #26312.  Let's see how this goes.

**Comment by charris** [comment]
Thanks Nathan.

**Comment by rgommers** [comment]
You probably want to close this backport PR I think. There's little need for having sanitizers in the maintenance branch, and if there's still potential reliability problems then it's best to continue improving things in `main`.

**Comment by ngoldbaum** [comment]
We turned on the workflow again, but the backport branch still had the old definition. This was supposed to ensure there wouldn't be test hangs on the backport branch.

**Comment by charris** [comment]
We will still need to disable the test in the  2.0.x branch.

**Pull request closed without merging**
