### PR TITLE
DOC: Add doc string for np.cov(m.T) == np.cov(m, rowvar=False)

### PR DESCRIPTION
**Pull request by 3rd3**
I think these are some useful bits of information.

### CODE REVIEW

**Comment by eric-wieser** [comment]
I'm not convinced that is correct

**Comment by eric-wieser** [comment]
Proof:

```
>>> a = np.ones((1, 5))
>>> np.cov(a)
array(0.0)
>>> np.cov(a, rowvar=False)
array(0.0)
>>> np.cov(a.T)
array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan]])

**Comment by 3rd3** [comment]
So, "… except the `rowvar` parameter checks for the case that only one variable is present in the transposed input and returns `0.0` in that case."? But then the text length vs information content ratio is perhaps a bit large.

**Comment by 3rd3** [comment]
But it might be useful as an example, perhaps?

**Comment by eric-wieser** [comment]
I think rather than spend time trying to work out how to describe the behaviour in the documentation, we should decide whether to just fix the bug.

I think this is the problem:
```
X = array(m, ndmin=2, dtype=dtype)
if not rowvar and X.shape[0] != 1:
    X = X.T
```
It seems to me that the check should be whether `m.ndim == 1`.

Or better yet, just replace that code with:
```
if not rowvar:
    m = m.T
X = array(m, ndmin=2, dtype=dtype)
````
Which would make your documentation correct.

This could however be argued as a breaking change

**Comment by melissawm** [comment]
Looks like this should be closed, @eric-wieser is there anything left to do here?

**Comment by charris** [comment]
I'm going to close this. Sounds like the problem should be addressed in the function rather than documentation.

**Comment by charris** [comment]
Thanks @3rd3, sorry this hung around for so long.

**Pull request closed without merging**
