### PR TITLE
BUG: Make floating remainder ufunc more exact.

### LINKED ISSUE #7224: Inexact result on floating-point remainder
This seems to be a regression in 11.0 or in master (note the values are exactly representable):
```
>>> np.remainder(3, 2.5)
0.49999999999999989
>>> np.__version__
'1.12.0.dev0+58263eb'
```
Compare to:
```
>>> np.remainder(3, 2.5)
0.5
>>> np.__version__
'1.10.4'
```

### PR DESCRIPTION
**Pull request by charris**
The intent here is to make sure the following is true for floating
numbers x (dividend) and y (divisor) and r = remainder(x, y).
- If both x and y are small integer floats, r is exact.
- The sign of r is the same as the sign of y, including signed zero.
- The magnitude of r is strictly less than the magnitude of y.
- y ~= r + y*floor(x/y), i.e., r is compatible with floor.

Remainder functions are also added to npy_math for all supported floats
'efdg'. This helps keep scalar and array results in sync. Explicit loops
are also made for remainder as the speedup over using generic loops is
about 20%.

Note that the NumPy version of remainder differs from that in Python, as
the latter is based around the fmod function rather than floor.

Closes #7224.

### CODE REVIEW

**Comment by njsmith** [comment]
You're getting failure on Travis due to c compiler warnings.

I'm nervous that this is a lot of lines of code and subtle semantics to be putting into a b4 release :-/ Would it make more sense to merge this to master and revert 34c2369 on 1.11?

**Comment by charris** [comment]
No ;) It's not very subtle, actually.

**Comment by charris** [comment]
Search and replace error.

**Comment by njsmith** [comment]
I guess I'm just nervous because 34c236939116c5 also seemed like a simple and obvious thing, but then it caused a bunch of downstream test failures and redesign during the beta period. So now we have a new simple and obvious change, and no beta period :-).

I know that the downstream test failures are partly just them being silly about floating point tolerances, but as a point of information, have you checked whether this patch fixes the failures in astropy?

**Comment by njsmith** [comment]
(Also FYI you missed the `#` in the `closes: ...` tag, in case you find yourself editing that commit message for other reasons.)

**Comment by charris** [comment]
What bothers me is that the scalar tests didn't catch it, they should have.

**Comment by charris** [comment]
There is certainly going to be another beta, @mhvk owes us a masked array fix and we need to undo the integer indexing.

**Comment by charris** [comment]
Certainly fixes the problem reported. Have you read the tests?

**Comment by charris** [comment]
I didn't figure on merging this right away, I wanted to see the tests and I need to revisit after some rest.

**Comment by njsmith** [comment]
I haven't (yet) read through the logic of these tests *or* the astropy tests, beyond checking that the astropy failures involved a comparison that only failed by a few ulps -- I figured you were doing that ;-)

**Comment by charris** [comment]
Ha, the scalar slots for `divmod` and `remainder` were set to `NULL` at some point in the past. The scalar functions were not being used.

**Comment by charris** [comment]
> figured you were doing that

I added tests for exact results for small integers. Only `-127..127`, but that failed badly with the previous implementation. That also covers the same ints scaled by powers of two, so (6,5) covers the (3, 2.5) test.

**Comment by charris** [comment]
I'm tending towards a simple `a - b*floor(a/b)` in the float case, which has the virtue that it is easy to understand and agrees with, for instance, Fortran modulo. Maybe just insure that zero has the correct sign, but explain in the documentation that roundoff can lead to some odd appearing results in some extreme corner case. That form also works well for small integers scaled by powers of two. Small, of course, depends on the precision. Another option, not far off this is to allow `abs(rem) <= abs(b)`.

**Comment by mhvk** [comment]
@charris - sounds good to me!

**Comment by charris** [comment]
I have been convinced that the best way to do this is to copy the Python implementation. Instead of trying to make the pair (`floor`, `remainder`) compatible, use (`floor_divide`,`remainder`) instead. That also has the advantage that both functions have two arguments, which allows us to do a better job of making them consistent.

**Comment by mhvk** [comment]
@charris - sounds good!

**Comment by charris** [comment]
OK, closing this, new PR in progress.

**Pull request closed without merging**
