### PR TITLE
DOC: Specify range for numpy.angle

### LINKED ISSUE #7426: numpy.angle shouldn't return negative values according to documentation?
I was surprised that numpy.angle returns negative values.

The documentation for [numpy.angle](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.angle.html) says:

> The **counterclockwise** angle from the positive real axis on the complex plane ..

This means the values should go from 0 to (2pi).

But that is not what happens. For example: 

> numpy.angle( 1 - 1j )
> **-0.78539816339744828**

I believe this should be that value plus (2pi) or **5.497787143782138**

If I am wrong, I believe the documentation should be clarified to give the intended output range as **(-pi, +pi]**

### PR DESCRIPTION
**Pull request by kritisingh1**
Fixes #7426

### CODE REVIEW

**Comment by eric-wieser** [comment]
I think you should keep the word "counterclockwise" here

**Comment by kritisingh1** [comment]
When the angle is from (-pi, 0) it is a clockwise angle from the positive real axis. Should I specify the direction for both (-pi,0] and [0,pi] then?

**Comment by eric-wieser** [comment]
The direction of the numeric value is always counterclockwise. If angle returns -90°, it means -90° counterclockwise. Yes, this can also be expressed as a 90° angle clockwise, but that's irrelevant because it returns -90 not +90.

**Review by eric-wieser — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @kritisingh1

**Pull request merged**
