### PR TITLE
use setuptools for bdist_egg distributions

### PR DESCRIPTION
**Pull request by heni**
Not only bdist_wheel needs setuptools

### CODE REVIEW

**Comment by charris** [comment]
Could you redo the commit message to begin with `BLD: ` and expand on the explanation that follows.

**Comment by heni** [comment]
Done! See https://github.com/numpy/numpy/pull/6848

**Comment by charris** [comment]
No need to close. You can use `git rebase -i HEAD^` to edit the commit message, then do a force push `git push -f origin HEAD`.

**Comment by heni** [comment]
It's too late :(
I'll remember this recipe for future usage!

**Pull request closed without merging**
