### PR TITLE
ENH: add helper for ifft padding to numpy.fft

### PR DESCRIPTION
**Pull request by awelkie**
See issue #1346

I'm not sure whether this should be a separate helper function or a flag to the `ifft` function, so I went with the easier way of making a helper function. I'm also not sure how to properly handle `ndarrays` with more than one dimension.

### CODE REVIEW

**Comment by awelkie** [comment]
Any feedback for this PR?

**Comment by seberg** [comment]
Out of curiousity, isn't the current padding that is done by ifft basically a bug if this is the right way to pad? In which case, I would like if we can include this padding into ifft, though we may need some warning on the current behaviour even if it should be a bug.

**Comment by seberg** [comment]
Ah, I guess it currently warns about it, though I still wonder how surprising "surprising" means.... @awelkie can you write a short mail about it to the mailing list? We usually pass all new functions there. Also there might be some nice opinion on which API is better.

**Comment by awelkie** [comment]
Sure. I'll send something out to the mailing list

**Comment by efiring** [comment]
Making it easy to do this type of padding is a great idea, but I would prefer to see it implemented via a kwarg in ifft.  Then the ifft docstring could explain exactly what the situation is, instead of referring vaguely to "surprising results".  And, the user would only have to read one docstring instead of two, and remember one function instead of two.

**Comment by Lodomir** [comment]
I would vote against this functionality (either as a separate function or kwarg).

The DFT is simply a special sum. Declaring the result as a "spectrum" or "time series" at certain frequencies or times is simply interpretation and depends on the use case.
Consequently, the padding you propose would be correct in some cases but misleading in others.

If one wants to approximate the Fourier integral on zero-centered grids for the temporal and spectral axes (`t=(arange(N)-floor(N/2))*dt, w=(arange(N)-floor(N/2))*dw`), one would do the following

    s1 = fft.ifft(fft.ifftshift(spectrum)) # fftshift(s1) gives time series on t

in which case

    s2 = 2*fft.ifft(fft.ifftshift(spectrum), 2*len(spectrum))

gives the expected interpolation in "time" domain - without using ifftpad.
If your temporal and spectral axes look different, you would need different shifts and padding to get the expected interpolation. Providing a function for a specific grid will give raise to much confusion.

Maybe instead change the docstrings to refer to a good document/book that explains the usage of the DFT (e.g. The DFT: An Owner's Manual for the Discrete Fourier Transform, Briggs & Van Henson).

Rant: `fftshift` and `ifftshift` are good examples. They are just circular shifts that order the inputs and outputs of the DFT for calculating Fourier transforms on very specific grids. But the functions are misunderstood to do something which is inherent to the DFT itself. Additionally, sometimes people think `fftshift` somehow belongs to the Fourier transform while `ifftshift` belongs to its inverse. Therefore, about 50% of the time they are misused - as a code search for `fftshift` on github reveals...

**Comment by endolith** [comment]
> but misleading in others.

Such as what?

> Providing a function for a specific grid will give raise to much confusion.

Are you also opposed to `fftfreqs` then?

> Therefore, about 50% of the time they are misused

Can you give a specific example?

**Comment by Lodomir** [comment]
>> but misleading in others.

> Such  as what?

Basically the example I mentioned. If the result you want is `s1`

    s1 = ifft(ifftshift(spectrum))

then

    s2 = ifft(ifftshift(ifftpad(spectrum, 2*len(spectrum)))

does not give the interpolation you want. But

    s3 = ifft(ifftpad(ifftshift(spectrum), 2*len(spectrum))
    s4 = ifft(ifftshift(spectrum), 2*len(spectrum))

both produce the correct result, but obviously a separate `ifftpad` function is not necessary. This is one example where `ifftpad` may be confusing.

>> Providing a function for a specific grid will give raise to much confusion.

> Are you also opposed to fftfreqs then?

Yes.

>> Therefore, about 50% of the time they are misused

> Can you give a specific example?

I apologize for the exaggeration, it is hopefully nowhere near 50%.
Off topic: If the DFT is used to approximate Fourier integrals of functions which are sampled on zero-centered grids, then the following expressions calculate the transform and its inverse (without scaling):

    F = fftshift(fft(ifftshift(f))) # Fourier transform
    f = fftshift(ifft(ifftshift(F))) # inverse Fourier transform

Note that in both cases `ifftshift` is the innermost function. But regularily I find code which implements any other combination of `(i)fftshift`. For example:

    F = ifftshift(fft(fftshift(f)))
    
That is correct for `N` even and wrong for `N` odd. But for `N` even `fftshift` and `ifftshift` do exactly the same and I would term this a "misuse". 

You will find it on github (744 search results alone for `ifftshift(fft(fftshift`) and in the literature (e.g. Computational Fourier Optics: A MATLAB Tutorial).

In my opinion the reason for this is the naming scheme of the `(i)fftshift` functions but also that they even exist (they are just aliases for specific circular shifts).

I fear that `ifftpad` may similarily be misused and suggest that providing a good reference in our documentation may be better than providing this function.

But before I go on ranting, I would point out that this is just my personal opinion. If others think this is a good addition to numpy then it should certainly be added.

**Comment by seberg** [comment]
@Lodomir if we ignore fftshift/ifftshift, would not a special "pad" argument fix this in some sense, because we would have control that the execution is always of `ifft(ifftpad(...)` style if we actually do `ifft(..., pad="something")`? I think that seemed like the preferred API anyway.

As for the shifting functions. Suggestions for new names or added documentation are always welcome.

Especially looking from the signal processing side my gut feeling is that `fftshift` is very handy and it should exist. The fact is that it is easy to get shifting with odd/even stuff wrong. Having no aliases would probably not change that; we can should think about how to make it more obvious to the user and easier to figure out whether what they are doing is correct.

**Comment by mattip** [comment]
Closing, this seems like the wrong approach. We have `fftshift` and `ifftshift`. As suggested, perhaps a `padding` kwarags which would properly call the shift function could be considered, but that is not this PR.

Please reopen if you feel this path to padding should be pursued.

**Pull request closed without merging**
