### PR TITLE
BLD, SIMD: Fix detect armhf and hardened the Neon/ASIMD compile-time tests

### PR DESCRIPTION
**Pull request by seiko2plus**
relates #21038 

This pull-request changes:

- Fix detecting armhf by strictly detects armhf via compiler definitions,
to avoid building neon objects on arch armel even when
the compiler supports armv7 features on it.

- Hardened the Neon/ASIMD compile-time tests to avoid
 compiler optimizing out the generated instructions,
so we make sure the required instructions have been tested against the linker/assembler.

### CODE REVIEW

**Comment by mattip** [comment]
Not necessarily part of this PR, but I am worried what will happen when we move off distutils to a different build system. I hope then we can untangle this and make it simpler: `numpy/distutils/checks` has over 40 files in it and `numpy/distutils/ccompiler_opt.py` is one of the two files in `numpy/distutils` that is larger than 95Kb (the others is `system_info.py`, which also needs simplification).

As for this PR, it seems to be needed, so lets put it in.

**Comment by mattip** [comment]
Thanks @seiko2plus

**Comment by seiko2plus** [comment]
> Not necessarily part of this PR, but I am worried what will happen when we move off distutils to a different build system.

depend on the build system, we gonna use. In general, we will need to modify the following class:
https://github.com/numpy/numpy/blob/6b43d9a3901d3713ae350776914c827a33753538/numpy/distutils/ccompiler_opt.py#L583-L589

And the modifications may include changing the behavior of the following function:
https://github.com/numpy/numpy/blob/6b43d9a3901d3713ae350776914c827a33753538/numpy/distutils/ccompiler_opt.py#L2256-L2266

> numpy/distutils/checks has over 40 files

I'm afraid not, simply each supported CPU feature requires a separated file. Gathering them into a single configuration file wouldn't be a practical solution at all.

> numpy/distutils/ccompiler_opt.py is one of the two files in numpy/distutils that is larger than 95Kb

we can split it into multiple files, some classes can be reduced in case of the new build system provide better functions, but it wouldn't cut that much code, most of the code related to feature configurations itself.

**Comment by dhomeier** [comment]
@seiko2plus it looks like this PR has also disabled all the NEON/ASIMD optimisations on Apple Silicon (M1); e.g. compiling with
```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix
```
up to 1.23rc2 the defaults were
```
INFO: Platform      : 
  Architecture: aarch64
  Compiler    : gcc

CPU baseline  : 
  Requested   : 'min'
  Enabled     : NEON NEON_FP16 NEON_VFPV4 ASIMD
  Flags       : none
  Extra checks: none

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : ASIMDHP ASIMDDP ASIMDFHM
  Generated   : 
              : 
  ASIMDHP     : NEON NEON_FP16 NEON_VFPV4 ASIMD
  Flags       : -march=armv8.2-a+fp16
  Extra checks: none
  Detect      : ASIMD ASIMDHP
              : numpy/core/src/umath/_umath_tests.dispatch.c
```
and optionally accepted for `--cpu-baseline` was
```
CPU baseline  : 
  Requested   : 'NEON NEON_FP16 NEON_VFPV4 ASIMD ASIMDHP ASIMDDP'
  Enabled     : NEON NEON_FP16 NEON_VFPV4 ASIMD ASIMDHP ASIMDDP
  Flags       : -march=armv8.2-a+fp16+dotprod
  Extra checks: none
```
whereas now, whether explicitly set or not, the build returns
```
CPU baseline  : 
  Requested   : 'NEON NEON_FP16 NEON_VFPV4 ASIMD ASIMDHP ASIMDDP'
  Enabled     : none
  Flags       : none
  Extra checks: none

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : none
  Generated   : none
```
I have not tried to benchmark anything to check the performance impact, but it seems for macOS the 1.22.4 compilation was working better.

**Comment by charris** [comment]
I opened an issue for the M1 regression.

**Comment by seiko2plus** [comment]
Oh, I'm so sorry that definitely leads to disable the the whole optimizations on aarch64

**Pull request merged**
