### PR TITLE
DOC: fix and doctest tutorial

### LINKED ISSUE #8067: Structured array - Introduction - Doc error
On page : http://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html
Structured array - Introduction
In the example : "Conveniently, one can access any field of the array by indexing using the string that names that field."

```
        y = x['foo'] should be >>> y = x['bar'] (the actual name of the "second" field which is addressed along the example).
        Additionally, this has to be updated at several places on the page.
```

### PR DESCRIPTION
**Pull request by mattip**
Fixes #8067 and tweaks the docstrings.

Is there a way to get refguide_check to run on this?

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Looks good to me, but will hold off on merging to see if we can refguide this.

**Review by tylerjereddy — COMMENTED** [review]
Enable refguide with the diff below, but remember it will fail if the tutorial deviates in a substantial way from the formatting of a typical Python docstring (I checked, and there are issues). The refguide module does have some notes about tutorial files, but anyway I think getting this to pass will at least mean looking for things that deviate substantially from a typical Python docstring.

```diff
diff --git a/tools/refguide_check.py b/tools/refguide_check.py
index fec715f..d5f2eb8 100644
--- a/tools/refguide_check.py
+++ b/tools/refguide_check.py
@@ -67,6 +67,7 @@ BASE_MODULE = "numpy"

 PUBLIC_SUBMODULES = [
     'core',
+    'doc.structured_arrays',
     'f2py',
     'linalg',
     'lib',
```

**Comment by mattip** [comment]
adapted refcheck to handle a module with only a `__doc__` attribute, activated refcheck on this file, and fixed the failures

**Comment by mattip** [comment]
Refguide ran in the [MacOS build](https://dev.azure.com/numpy/numpy/_build/results?buildId=1749) and succeeded

**Comment by mattip** [comment]
@tylerjereddy does this look OK?

**Review by tylerjereddy — APPROVED** [review]
I confirmed locally that refguide fails if one of the tutorial examples touched here is broken & Eric and I are happy with the changes beyond that, so in it goes.

Not sure why Shippable entry is missing in CI matrix, but not crucial here.

**Comment by tylerjereddy** [comment]
Thanks Matti

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/blob/master/tools/refguide_check.py#L909 scipy's refguide-check does check the tutorial, even in a hacky way which can be cleaned up/streamlined (https://github.com/scipy/scipy/blob/master/tools/refguide_check.py#L734)

**Comment by mattip** [comment]
@ev-br not sure that is applicable here. We want to check an importable python module that is pure documentation, not the `doc/source/tutorial/*.rst` files.

**Pull request merged**
