### PR TITLE
BUG: Masked array addition does not work when dtype=object

### LINKED ISSUE #4452: BUG: Masked array addition does not work when dtype=object
```
In [1]: import numpy as np
In [2]: x = np.ma.array(['x'], dtype='O')
In [3]: x + x
Out[3]:
masked_array(data = ['xx'],
             mask = False,
       fill_value = ?)

In [4]: x = np.ma.array(['x'], mask=[1], dtype='O')
In [5]: x + x
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-e2d9e13b7cb9> in <module>()
----> 1 x + x

numpy/ma/core.pyc in __add__(self, other)
   3689     def __add__(self, other):
   3690         "Add other to self, and return a new masked array."
-> 3691         return add(self, other)
   3692     #
   3693     def __radd__(self, other):

numpy/ma/core.pyc in __call__(self, a, b, *args, **kwargs)
    945             # This only makes sense if the operation preserved the dtype
    946             if result.dtype == da.dtype:
--> 947                 result += m * da
    948         # Transforms to a (subclass of) MaskedArray
    949         result = result.view(get_masked_subclass(a, b))

TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

### PR DESCRIPTION
**Pull request by abalkin**
Fixes #4452.

### CODE REVIEW

**Comment by charris** [comment]
@abalkin Needs a rebase.

**Comment by abalkin** [comment]
Apparently, the original issue has been fixed.  You can merge the test, though.

**Comment by charris** [comment]
@abalkin Great. Tests are always good. Can you edit the commit message to something like `TST: Test...`. Or was there already a test for this when it was fixed.

**Comment by abalkin** [comment]
> Or was there already a test for this when it was fixed.

I don't think so.  My case was fixed as a side-effect of ad902ff2 and I don't see any tests added in that commit.

**Comment by abalkin** [comment]
Maybe @juliantaylor knows more about that change.

**Comment by charris** [comment]
Looks like the test is needed, so in it goes. Thanks @abalkin.

**Pull request merged**
