### PR TITLE
DOC: add example to unique() and make connection to repeat()

### PR DESCRIPTION
**Pull request by AllenDowney**
I suggest adding `repeat` to the "See also" section of `unique` (and vice versa) since each is the inverse of the other.

### CODE REVIEW

**Comment by charris** [comment]
The reference looks out of place to me, repeat isn't really an inverse and serves a different purpose.

**Comment by AllenDowney** [comment]
I think `repeat` is the inverse of `value_counts`, at least with `return_counts=True`, as in this example:

```
seq = list('abbccc')
np.repeat(*np.unique(seq, return_counts=True))
```

And vice versa

```
t1 = list('abc')
t2 = [1, 2, 3]
np.unique(np.repeat(t1, t2), return_counts=True)
```

**Comment by rossbar** [comment]
I tend to agree with @charris. I think `np.repeat` makes the most sense in the context of array creation, whereas `np.unique` is more generally applicable. The inclusion of `repeat` in the See Also section of `unique` seems confusing at face value without the additional primer on typical use-cases. I'd be -0.5 on these changes.

Side note: I think it would be best if you closed #16742 and included those changes in this PR, so we don't have these related changes split over 2 PRs. This would make it easier to keep the discussion focused.

**Comment by AllenDowney** [comment]
Here are two reasons I think these two functions are related to each other:

1) They are the inverse of each other, as I showed in my previous comment.

2) When I was looking for `repeat`, it occurred to me that it is the inverse of `pd.value_counts`, so I Googled "inverse value_counts", and the first hit is a stackoverflow question that points to `np.repeat`

https://stackoverflow.com/questions/35492624/pandas-inverse-of-value-counts-function

So it looks like I am not the only one to make this connection. I thought I could help other people make the same connection faster by making these functions refer to each other.

But if the consensus is that adding these two lines to the documentation is bad, ok.

**Comment by rossbar** [comment]
Thanks for linking to the SO post, that is a nice motivating example. I still think there's just not enough context adding `repeat` to the See Also of `unique` (and vice versa) - I'm not sure many users would make the connection from the additional See Also entry to the SO answer (I certainly didn't, for instance).

Perhaps adding an example to the Examples section would be better.

**Comment by rossbar** [comment]
@rgommers with #16742 having been added do you want to just add this one as well? The two PRs are really two sides of the same coin.

**Comment by rgommers** [comment]
Ah, I assumed in the other PR that the `unique` docstring already had the See Also entry, missed a cross-link. It's fine as is now, but in the future it would indeed be better to do related changes in a single PR @AllenDowney.

I think adding the See Also entry here is fine, but it's much better with the example in the comment above. Can you please add that example to the `Examples` section @AllenDowney?

**Comment by AllenDowney** [comment]
Yes, sorry about creating multiple related PRs.

I have added a commit to this one that adds an example using `np.repeat`.

Please take a look.

**Comment by rgommers** [comment]
Thanks @AllenDowney, LGTM now - merged.

**Comment by AllenDowney** [comment]
Thanks!

**Pull request merged**
