### PR TITLE
Rename _operand_flag_tests.c.src into numpy/core/src/umath/_operand_f…

### PR DESCRIPTION
**Pull request by serge-sans-paille**
…lag_tests.c

There's no templating annotation in _operand_flag_tests.c.src

### CODE REVIEW

**Comment by mattip** [comment]
@seberg do we even need this test? Would a failure setting these flags cause many other things to fail?

**Comment by seberg** [comment]
I honestly am not sure, I was thinking numba might mess with the flags, but a quick check seems they don't.  `matmul` sets custom flags IIRC.  However, I am not even sure that the ones tested here cover anything at all.

This looks a bit like it was added with some specific use-case in, mind though (even though I would have to dig more to find out what that use-case is).  So for simplicity, would be happy to just put this in and defer digging in to later.

**Comment by mattip** [comment]
Thanks @serge-sans-paille

**Comment by mattip** [comment]
I wonder whether we should open a tracking issue to refactor the test suite to be a little more systematic. Perhaps we could use the data from the coverage test runs to build a database of which tests hit which code paths, and to remove tests that only hit redundant ones. We can build on [this idea](https://hynek.me/til/ditch-codecov-python/) to upload coverage artifacts and do our own analysis rather than depending on codecov.

**Pull request merged**
