### PR TITLE
MAINT: optimize _unique1d in arraysetops.py

### PR DESCRIPTION
**Pull request by k-kapp**
See discussion at pull request #9142

### CODE REVIEW

**Comment by eric-wieser** [comment]
Well that sure produces a weird set of errors...

**Comment by k-kapp** [comment]
Haha, yes, checking it along with the enclosing unique function now

**Comment by eric-wieser** [comment]
As a quick guess, it seems that `np.unique(axis=...)` only works on structured arrays of length <= 2, and this patch exposed the bug by taking the broken code path for length == 2

**Comment by eric-wieser** [comment]
Yep, here's the bug:

```
In [13]: arr
Out[13]:
array([[(0, 1, 0)],
       [(0, 1, 0)],
       [(0, 1, 0)],
       [(0, 1, 0)]],
      dtype=[('f0', '<i4'), ('f1', '<i4'), ('f2', '<i4')])

In [14]: arr[1:] == arr[:-1]
Out[14]:
array([[ True],
       [ True],
       [ True]], dtype=bool)

In [15]: np.equal(arr[1:], arr[:-1])
C:\Users\wiese\Repos\numpy\runtests.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  #!/usr/bin/env python
Out[15]: NotImplemented
```

**Comment by seberg** [comment]
This seems to have been done much the same in gh-10498, nothing to apply anymore. Thanks @k-kapp, looks like we almost could have had it a year earlier.

**Comment by eric-wieser** [comment]
Whoops - guess I never saw that second commit got pushed

**Pull request closed without merging**
