### PR TITLE
MAINT: Fix inconsistent PyPI casing

### PR DESCRIPTION
**Pull request by nihaals**

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Looks reasonable to me. I don't think it really matter that this touches old release notes, but I'll let someone else decide.

**Comment by nihaals** [comment]
> I don't think it really matter that this touches old release notes

I thought about this too, but since it's a minor change, I assumed it was fine. I don't really have a strong opinion either way, I get both preserving the history and correcting a "typo".

**Review by rgommers — APPROVED** [review]
Thanks @nihaals, LGTM.

>> I don't think it really matter that this touches old release notes

> I thought about this too, but since it's a minor change, I assumed it was fine. I don't really have a strong opinion either way, I get both preserving the history and correcting a "typo".

I agree in this case, this should be fine. And the changes are made now, so let's just put them in.

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @nihaals! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute/
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Pull request merged**
