### PR TITLE
DOC: Fix incorrect `.. deprecated::` syntax that led to this note being invisible

### PR DESCRIPTION
**Pull request by eric-wieser**
Introduced in cefd3523a63cfd5ede693d53d3821e37fa8ca158

### CODE REVIEW

**Comment by eric-wieser** [comment]
@seberg, I'm confused by this comment now, having found the commit that authored it. Was the intent for it to say something more like "TODO: consider deprecating?"

**Comment by seberg** [comment]
No its deprecated, the parent commit is the one that adds it, this just removed it again for unrecognized types to go to object. So `np.dtype(abstract_scalar)` is deprecated.

**Comment by eric-wieser** [comment]
So this message was supposed to be visible in the docs?

**Comment by seberg** [comment]
Yes, it was supposed to be visible, so this change seems good.

**Comment by eric-wieser** [comment]
I pushed to the wrong branch by accident and triggered a bogus CircleCI build, but the original build is at

https://app.circleci.com/pipelines/github/numpy/numpy/3676/workflows/c43c65f7-8e80-42e9-ba26-bf54ee837fbf/jobs/15765/artifacts

**Comment by eric-wieser** [comment]
Actually, I've generally just made a mess of my history here, the first commit is #17330. Let's deal with this one after that goes in.

**Comment by seberg** [comment]
Rebased, and warning looks fine in the artifact. Thanks.

**Pull request merged**
