### PR TITLE
BUG: Various fixes to _dtype_from_pep3118

### LINKED ISSUE #9053: _dtype_from_pep3118 is non-deterministic given zero-sized elements
In numpy 1.12.1, this code gives non-deterministic results, I'm guessing because the original field order is not preserved (the `fields` local variable is a dict rather than an OrderedDict):
```python
>>> print(np.core._internal._dtype_from_pep3118("(0)I:a:f:f:"))
```
In some cases the output is `[('a', '<u4', (0,)), ('f', '<f4')]`, in others it is `{'names':['f','a'], 'formats':['<f4',('<u4', (0,))], 'offsets':[0,0], 'itemsize':4}`.

These dtypes are at least equal to each other, but it gets worse: given `f:f:(0)Iempty:4x`, the padding is sometimes anonymous, and sometimes a field called `pad0`. These dtypes aren't the same and can't be cast between each other with the 'safe' or 'equiv' rules.

### PR DESCRIPTION
**Pull request by eric-wieser**
Fixes #9053, and groundwork for #9049.

Again, probably easier to review commit-by-commit

### CODE REVIEW

**Comment by mhvk** [comment]
I like the solution with the stream class (though I wonder to what extent you're reinventing `ply`...). But I cannot say I went through this in enough detail.

**Comment by mhvk** [comment]
p.s. would be nice to have #8774 so you don't have to redefine `gcd` and `lcm`...

**Comment by eric-wieser** [comment]
#8774 actually falls back on `_internals._gcd` for object arrays anyway

**Comment by eric-wieser** [comment]
> though I wonder to what extent you're reinventing ply

I've seen in the past that dependencies for numpy are a pain from a distribution perspective (#that-pr-about-deprecating-np.float), and it's better to do simple things ourselves.

**Comment by mhvk** [comment]
Yes, makes sense. And as said, I quite like your stream class; and the path that gets taken is at least a bit clearer than with a lex file (or a regex).

**Comment by ahaldane** [comment]
* The 'stream' cleanup commit looks nice. Perhaps consider making the class global level? I'm fine as is though.
 * The three bugfix commits look good: 
   * The itemsize commit is partly like in #7798 as you mentioned. I am fine merging it as you have it for now. Although, as noted there we are probably incorrectly interpreting the spec: According to spec `ix` should be 5 bytes, not 8. If the user wants 8 they need to do `ix0i`. We might leave that for #7798, since the problem is purely theoretical right now: I don't know of public python modules (including numpy) which can create buffers with 'ix' format.
   * The commit using the 'names' list to store the field order looks correct, and even seems to fix bugs we didn't come across (eg the extra test that the 1-item itemsize is unchanged).
   * The autogenerated names commit looks good and is much easier to read than the old code

I read over it well enough that it has my +1 for merging. If there are no other comments I would be happy to merge in a day or two.

**Comment by ahaldane** [comment]
All right, pulling the trigger here. Thanks @eric-wieser !

**Comment by eric-wieser** [comment]
> . Although, as noted there we are probably incorrectly interpreting the spec: According to spec ix should be 5 bytes, not 8

Can you give a reference for that?

**Comment by pv** [comment]
Is it that clear? As I understand, the aligned mode is supposed to 
follow the typical C compiler padding behavior.

**Comment by pv** [comment]
Is it that clear? As I understand, the padding is supposed to follow 
typical C compiler behavior.

**Comment by eric-wieser** [comment]
@pv: Here's the problem. The [c code](https://ideone.com/F0LFF6) gives 8, but `struct.Struct('ix').size` gives 5.

**Comment by pv** [comment]
Yes, but there is also a question on whether struct.Struct 
implementation is correct.

**Comment by pv** [comment]
Since also `struct.Struct('ib').size == 5`, I guess the question then is 
whether trailing padding must be explicit or not. The PEP does not spell 
this out. Python's struct module syntax is older than the PEP, so maybe 
that is the behavior that has priority.

**Comment by ahaldane** [comment]
Here's the reference, (copied from my comment in #7798):

The struct module [says this](https://docs.python.org/2/library/struct.html#byte-order-size-and-alignment) about how format strings treat trailing padding:

>    To align the end of a structure to the alignment requirement of a particular type, end the format with the code for that type with a repeat count of zero. 

My interpretation is that for a format like 'ix', even though the type is implicitly `@` (aligned) we should only add 1 trailing padding byte. If we wanted numpy-style padding bytes the format string should instead be something like 'ix0i'.

**Pull request merged**
