### PR TITLE
Revert "BUG: revise string_from_pyobj/try_pyarr_from_string with respect to malloc and copy."

### PR DESCRIPTION
**Pull request by rgommers**
Reverts numpy/numpy#18759

See https://github.com/numpy/numpy/pull/18759#issuecomment-860207450 for details.

### CODE REVIEW

**Comment by rgommers** [comment]
Only failures are the lint jobs, which is expected. Since this is blocking the SciPy 1.7.0rc2 release (need the `sdist` job to stop crashing in https://github.com/scipy/scipy/pull/14230), I'll merge it.

**Comment by charris** [comment]
Want me to trigger the nightly builds?

**Comment by rgommers** [comment]
Yes please!

**Comment by rgommers** [comment]
I forgot how that's done.

**Comment by charris** [comment]
> I forgot how that's done.
```
charris@fc [numpy-wheels.git (main)]$ git commit --allow-empty -m'Trigger build for NumPy SciPy fixes'
[main 51c6f4d] Trigger build for NumPy SciPy fixes
charris@fc [numpy-wheels.git (main)]$ git push upstream main
```

**Pull request merged**
