### PR TITLE
BUG: Fix typo in LEGACY_CONS_NON_NEGATVE_INBOUNDS_LONG

### PR DESCRIPTION
**Pull request by rouault**
(missing I in NEGAT[I]VE)

### CODE REVIEW

**Comment by rkern** [comment]
Notionally, this is an API change. I'd probably leave it alone.

**Comment by mattip** [comment]
If we want to go ahead with this, we would need to leave both declarations, make sure they are the same number in the enum, something like
```
LEGACY_CONS_NON_NEGATVE_INBOUNDS_LONG __attribute__((__deprecated__)) = 11
```

Does that work on MSVC? If not it would need some adjustment.

Maybe not worth the bother, but a comment that we know about the typo with a reference to this PR might prevent future contributors from re-submitting.

**Comment by rouault** [comment]
> Notionally, this is an API change

is it? There's no documentation for ConstraintType nor LEGACY_CONS_NON_NEGATVE_INBOUNDS_LONG
Furthermore this was introduced very recently in Oct 2023 through b6df6cd0f168d691ce6b6697a9c89a0670598567

**Review by seberg — APPROVED** [review]
Yeah, it's not released yet, so I we can just change it.

**Comment by rkern** [comment]
Okay, great!

**Comment by mattip** [comment]
Thanks @rouault

**Pull request merged**
