### PR TITLE
MAINT: Add azure-pipeline status badge to README.md

### PR DESCRIPTION
**Pull request by charris**

### CODE REVIEW

**Comment by charris** [comment]
The Mac failure is the usual f2py problem and unrelated to this change.

**Comment by tylerjereddy** [comment]
Ok, seems a safe enough PR for my first NumPy merge; I guess we may remove the appveyor badge at some point too.

**Comment by tylerjereddy** [comment]
thanks @charris

**Comment by charris** [comment]
> Ok, seems a safe enough PR for my first NumPy merge;

Congratulations.

**Pull request merged**
