### PR TITLE
DOC: Update sphinx, numpydoc, and pydata-sphinx-theme

### LINKED ISSUE #21390: DOC: Add dark mode switcher
### Issue with current documentation:

A dark mode has been requested before .

The PyData Sphinx theme recently created a dark mode switcher, and the documentation for implementing it are [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html?highlight=version#add-a-dropdown-to-switch-between-docs-versions). 

An example of the dark mode switcher can be found [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/). It is the sun/moon on the top right coner, next to the version switcher.

It is currently in the dev mode, as the dark mode switcher was included 2 weeks ago. If the dark mode switcher is included in the next PyData Sphinx Theme release with documentation, we can start implementing this for NumPy.

### Idea or request for content:

This is how dark mode looks in the example linked.
image

### PR DESCRIPTION
**Pull request by jarrodmillman**
Updates for sphinx, numpydoc, and pydata-sphinx-theme.

The new version of the pydata-sphinx-theme adds a theme switcher (light, dark, auto mode) among other improvements. I've set it to default to light mode for now. Once we have more feedback on the dark theme, we can set it to auto mode.

### CODE REVIEW

**Comment by mattip** [comment]
There are documentation build warnings (that make the build fail). Did something chagne in the autodoc summaries?

<details>

```
WARNING: unsupported theme option 'logo_link' given
/home/circleci/repo/doc/source/reference/arrays.interface.rst:249: WARNING: unknown document: c-api/buffer
/home/circleci/repo/venv/lib/python3.8/site-packages/numpy/__init__.py:docstring of numpy.arange:88: WARNING: unknown document: c-api/long
docstring of numpy.ma.arange:88: WARNING: unknown document: c-api/long
/home/circleci/repo/doc/source/user/basics.interoperability.rst:46: WARNING: unknown document: c-api/buffer
/home/circleci/repo/doc/source/user/how-to-how-to.rst:108: WARNING: unknown document: content/tutorial-style-guide
/home/circleci/repo/doc/source/user/quickstart.rst:1488: WARNING: unknown document: content/tutorial-svd
make: *** [Makefile:183: html-build] Error 1

Exited with code exit status 2


```

</details>

**Review by rgommers — COMMENTED** [review]
Thanks @jarrodmillman. The theme and numpydoc upgrades look good to me.

For the Sphinx upgrade: `5.0.1` is super recent, that's going to be annoying for contributors to deal with. We have always tried to maintain support for a reasonably old Sphinx version (e.g. as packaged in most common Linux distros; latest Ubuntu is at `4.3.2`). Is there a need to upgrade so aggressively?

**Comment by rgommers** [comment]
Sphinx 4.3 sounds fine to me, thanks Jarrod.

> So we will want to make a logo for the dark theme as well as the light theme

We don't have one I think, but that shouldn't be hard to do. Do you think just making the logo text white is better, or make an all-white version of the logo?

**Comment by charris** [comment]
Lets get this in and leave fixing the logo for the dark theme for another PR.

**Comment by charris** [comment]
Thanks Jarrod.

**Comment by melissawm** [comment]
We do have this one: https://github.com/numpy/numpy/blob/main/branding/logo/primary/numpylogolight.png

Could be a starting point?

**Pull request merged**
