### PR TITLE
DOC: clarify 'choice' documentation

### PR DESCRIPTION
**Pull request by gasparka**
Documentation clearly confusing:
https://stackoverflow.com/questions/40689152/what-does-replacement-mean-in-numpy-random-choice

Hopefully it is better now.

### CODE REVIEW

**Review by xinyufeifei — COMMENTED** [review]
It sounds more clearer to add "draw" in the explanation. i.e. "Whether the sample is draw with or without replacement". If an example is added at the bottom of the doc to demonstrate this feature, it would be great. Here is a suggested example: np.random.choice(5, 3, replace=True) -> array([3, 3, 2]).

**Comment by pujaji** [comment]
@mattip , Is this issue open?
Do you want me create a clarified version of documentation on random.choice?

**Comment by mattip** [comment]
@pujaji this is a pull request to solve the issue. Please look for issues with no pull request yet.

**Comment by pujaji** [comment]
> @pujaji this is a pull request to solve the issue. Please look for issues with no pull request yet.

@mattip I request you to see my mail

**Comment by gasparka** [comment]
This is still confusing, what about:
```
replace : boolean, optional
    Controls if a drawn element is returned to the sample pool i.e. can be drawn multiple times.
    Attempt to draw more elements then len(a) will result in ValueError if replace=False.
    Default is True.

```

**Comment by mattip** [comment]
If we choose not to close this, I think examples, rather than more text, would serve better to clarify the intention. The basic idea of sampling with/without replacement is one of the first things taught in statistics, I am not sure more words will help someone struggling with the idea.

**Comment by mattip** [comment]
Closing, I think the text is clear as is. Please reopen or submit a new PR if you disagree.

**Pull request closed without merging**
