### PR TITLE
MAINT: Syntax-highlight .src files on github

### PR DESCRIPTION
**Pull request by eric-wieser**
Before: https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/einsum_sumprod.c.src

After: https://github.com/eric-wieser/numpy/blob/_c.src-highlight/numpy/core/src/multiarray/einsum_sumprod.c.src

### CODE REVIEW

**Comment by charris** [comment]
Happy to give this a shot.

**Comment by eric-wieser** [comment]
Note I think this can also be handled by adding `/* -*-c-*- */` to the top of the file, but then we have to remember to do that to every file.

**Comment by seberg** [comment]
I had some issues with website caches when trying it out first, but this seems like an improvement and unless the language tag has some other big advantages, seems easier (and doesn't directly clash anyway).

**Comment by seberg** [comment]
Looking at these, would it make sense to also add something like this?:
```
# Ignore some vendored files (or automatically generated from vendored)
numpy/linalg/lapack_lite/f2c*.c linguist-vendored
numpy/linalg/lapack_lite/f2c*.h linguist-vendored
numpy/core/src/multiarray/dragon4.c linguist-vendored
numpy/core/src/multiarray/dragon4.h linguist-vendored

tools/npy_tempita/* linguist-vendored
```

I suppose the only effect it will have is shift the language statistics slightly, so probably doesn't matter much.

**Comment by eric-wieser** [comment]
My impression was that `numpy/core/src/multiarray/dragon4.c` diverges from the vendored version, and so we don't really want to mark that. As for `f2c`, I'd be inclined to just mark it generated.

**Pull request merged**
