### PR TITLE
MAINT: Fix Misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -I ../numpy-whitelist.txt`  
Whitelist consists of:  
```
amin
ans
behaviour
cancellation
dum
initialise
ith
nd
ot
splitted
writeable
```

### CODE REVIEW

**Comment by charris** [comment]
You should leave all the files in `numpy/linalg/lapack_lite` alone, they are generated from the Fortran code from Netlib using f2c and not something we should worry about.

**Comment by luzpaz** [comment]
@charris oh yea..i forgot about that.  Is there an upstream repo I can PR them to ? I'll get rid of them in this commit.

**Comment by charris** [comment]
There is an lapack repo https://github.com/Reference-LAPACK/lapack that seems to take PRs. The version we have here is old and I expect it would be pointless to fix the typos in this version when there are newer versions out there.

**Comment by charris** [comment]
Thanks @luzpaz .

**Pull request merged**
