### PR TITLE
Update .mailmap 2

### PR DESCRIPTION
**Pull request by pierreloicq**

### CODE REVIEW

**Comment by charris** [comment]
Which is the preferred address? Note that many have both.

**Comment by pierreloicq** [comment]
the noreply github please. I am fighting SPAM
Thanks

**Comment by charris** [comment]
Thanks @pierreloicq .

**Comment by charris** [comment]
Note that you are still in the git log as `Pierre <pierreloicq@gmail.com>`, who is now a different person.

**Comment by pierreloicq** [comment]
Yes but I don't think spams bots see there.
Please remove my email mention in your above comment.
Thanks

**Comment by pierreloicq** [comment]
@charris can you completely delete your above message ? since we can see the original message. Sorry for the trouble, I modified my git configuration so that it doesn't happen anymore . Thank you

**Pull request merged**
