### PR TITLE
TST: Extract a helper function to test for reference cycles

### PR DESCRIPTION
**Pull request by eric-wieser**
This also means we can now test that our test is actually able to detect the type of failure we expect

Trying to give myself some tools to debug the failure at https://github.com/numpy/numpy/pull/10882/files#r180813166

### CODE REVIEW

**Comment by eric-wieser** [comment]
An example of this in use:
```python
In [1]: from numpy.testing import assert_no_gc_cycles

In [2]: def make_array_ctype(shape):
   ...:     import ctypes
   ...:     ct = ctypes.c_uint8
   ...:     for i in shape:
   ...:         ct = i * ct
   ...:

In [3]: assert_no_gc_cycles(make_array_ctype, (1,))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-de469365c191> in <module>()
----> 1 assert_no_gc_cycles(make_array_ctype, (1,))

~\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\testing\_private\utils.py in assert_no_gc_cycles(*args, **kwargs)
   2352     args = args[1:]
   2353     with _assert_no_gc_cycles_context(name=func.__name__):
-> 2354         return func(*args, **kwargs)

C:\Program Files\Python 3.5\lib\contextlib.py in __exit__(self, type, value, traceback)
     64         if type is None:
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:
     68                 return False

~\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\testing\_private\utils.py in _assert_no_gc_cycles_context(name)
   2315                         id(o),
   2316                         pprint.pformat(o).replace('\n', '\n    ')
-> 2317                     ) for o in objects_in_cycles
   2318                 )
   2319             )

AssertionError: Reference cycles were found when calling make_array_ctype: 7 objects were collected, of which 6 are shown below:
  tuple object with id=2822255556536:
    (<class '_ctypes.Array'>,)
  PyCArrayType object with id=2822226500408:
    <class '__main__.c_ubyte_Array_1'>
  getset_descriptor object with id=2822252062256:
    <attribute '__dict__' of 'c_ubyte_Array_1' objects>
  getset_descriptor object with id=2822252062184:
    <attribute '__weakref__' of 'c_ubyte_Array_1' objects>
  tuple object with id=2822243712440:
    (<class '__main__.c_ubyte_Array_1'>,
     <class '_ctypes.Array'>,
     <class '_ctypes._CData'>,
     <class 'object'>)
  StgDict object with id=2822226211928:
    {'__dict__': <attribute '__dict__' of 'c_ubyte_Array_1' objects>,
     '__doc__': None,
     '__module__': '__main__',
     '__weakref__': <attribute '__weakref__' of 'c_ubyte_Array_1' objects>,
     '_length_': 1,
     '_type_': <class 'ctypes.c_ubyte'>}
```

**Comment by pv** [comment]
This assumes a single gc.collect() call is enough to make the next
gc.collect()==0, but is that really guaranteed? Should this call
gc.collect() multiple times first to flush things out?

**Comment by eric-wieser** [comment]
@pv: I don't know. My goal here was just to encapsulate the test we're already using, and add some extra diagnostics.

**Comment by eric-wieser** [comment]
After a rethink: spot-on diagnosis of the problem I had in #10882. This test should indeed be collecting multiple times. I'll add another commit.

**Comment by charris** [comment]
Python 2.7 is being difficult.

**Comment by eric-wieser** [comment]
Hmm. Can you think of a reliable test that prevents the garbage collector from ever finishing collecting? If not, should I just change the test to suppress RuntimeError rather than actually test for it?

**Comment by eric-wieser** [comment]
Seems that sometimes the GC doesn't even try to finalize the objects, which avoids the pathological case anyway. I've detected this with a `weakref`, and just skipped the test if that happens.

This now passes on 2.7 on my machine, and hopefully will do the same on the travis 3.6 failure.

**Comment by charris** [comment]
LGTM, @pv any comments? Doesn't exactly decrease the amount of code, but is worth having something debugged and expected to work.

**Comment by charris** [comment]
Thanks Eric.

**Comment by charris** [comment]
Hmm, needs a release note as it adds a new function to `numpy/testing`.

**Pull request merged**
