### PR TITLE
TST: Verify dot products with matrix transposes

### PR DESCRIPTION
**Pull request by jakirkham**
Related: https://github.com/numpy/numpy/issues/6794
Related: https://github.com/numpy/numpy/pull/6932

Tries different products with transposes to verify that correct result is gotten. Makes sure to try combinations that don't share memory, as well.

### CODE REVIEW

**Comment by charris** [comment]
You want these tests for future work, yes?

**Comment by jakirkham** [comment]
Correct, this is to make sure I don't mess something up. :) If you have pointers or thoughts on additional tests, I am open to suggestions.

**Comment by jakirkham** [comment]
I think I should add some inner product tests, as well.

**Comment by jakirkham** [comment]
I've decided to skip `inner` based tests as part of this PR group and just focus on `dot` for now.

**Comment by jakirkham** [comment]
Rebased.

**Comment by njsmith** [comment]
Can't see how more tests could do any harm :-) Thanks @jakirkham

**Pull request merged**
