### PR TITLE
BUG: fix regex of determineexprtype_re_3 in numpy/f2py/crackfortran.py

### PR DESCRIPTION
**Pull request by zixu-zhao**
Fix the regex of [determineexprtype_re_3](https://github.com/numpy/numpy/blob/master/numpy/f2py/crackfortran.py#L2935)

See #8791

### CODE REVIEW

**Comment by charris** [comment]
I suspect `(P<name>` should also be `(?P<name>` in the two places it occurs.

**Comment by ZZhaoTireless** [comment]
@charris Sure, I will fix that. Thanks!

**Comment by charris** [comment]
Thanks @ZZhaoTireless .

**Comment by charris** [comment]
If you put `Closes #8791` in the commit message body the issue will be automatically closed.

**Comment by ZZhaoTireless** [comment]
@charris Thanks, I will add it next time.

**Pull request merged**
