### PR TITLE
BUG: Fix inline assembly that detects cpu features on x86(32bit)

### LINKED ISSUE #15525: Wheel builds on i686 broken by detection of CPU features
Failing builds [here](https://travis-ci.org/MacPython/numpy-wheels/builds/646641130?utm_medium=notification&utm_source=email).

Seems to be a problem with the new cpu feature detection. May be a combination of an old compiler and i686.  We may want to test with multilinux2010 also.
```
numpy/core/src/common/npy_cpu_features.c.src:105:5: error: inconsistent operand constraints in an ‘asm’
     __asm__(NPY__CPUID_ASM : "=a" (reg[0]), "=b" (reg[1]), "=c" (reg[2]), "=d" (reg[3]) : "a" (func_id), "c" (0) : );
     ^
numpy/core/src/common/npy_cpu_features.c.src:105:5: error: inconsistent operand constraints in an ‘asm’
     __asm__(NPY__CPUID_ASM : "=a" (reg[0]), "=b" (reg[1]), "=c" (reg[2]), "=d" (reg[3]) : "a" (func_id), "c" (0) : );
     ^
numpy/core/src/common/npy_cpu_features.c.src:105:5: error: inconsistent operand constraints in an ‘asm’
     __asm__(NPY__CPUID_ASM : "=a" (reg[0]), "=b" (reg[1]), "=c" (reg[2]), "=d" (reg[3]) : "a" (func_id), "c" (0) : );
     ^
numpy/core/src/common/npy_cpu_features.c.src:105:5: error: inconsistent operand constraints in an ‘asm’
     __asm__(NPY__CPUID_ASM : "=a" (reg[0]), "=b" (reg[1]), "=c" (reg[2]), "=d" (reg[3]) : "a" (func_id), "c" (0) : );
     ^
```
@mattip @seiko2plus ping.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

### PR DESCRIPTION
**Pull request by seiko2plus**
resolves #15525
tested on [godbolt](https://godbolt.org/e#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlICsupVs1qgA%2BhOSkAzpnbICeOpUy10AYVSsArgFtaXAOylV6ADJ5amAHJ6ARpmIgAzAE5SAB1TTCS2pp19I09vXzoLK1tdByc3GTlMBT8GAmZiAgC9A05jWXlFOhS0ggibe0cXd2lU9MygnJkakssy6Iq3AEoZVG1iZA4AcgBSACZnPCoAaiwqFvQISYk8ZwAOADYJSY7JocN1XfVpzFmreeX17YODo5PMebEAWTEASQANC6GABgBBSb%2BdsYzFqTawABQAmmJ1KCAKpid5rL7fUbOUwTJFI6rMRTISYAN1QeHQSNoHgAnpIPNoxMgqUSIJYCJNiJhgEMAKwAIW4HIAIqRJozJlRtLRkGIiR0MYZORixhMbnMII8GOoxAA1bAAJSlP3%2BixpdKwAA8ICzgAKRWKJegBZ8pc5ZT8UXIFUDTsqXtYACrYMxQgDyD1BzzM2t1v3%2BlO09PNltF4slQ0dctRrDdxyVEgA4tYYWqxJc9td3XdPchhKIJBH9SiM7d5mDIdC4QjLiNER3FR6JCGCzX9f8APRDgHszB2Y2TXTMMmTByTAgITCTPvM1l4aqOJGDqNiZjSXQSCCjEbG5AINky1i7Xkc9QEXaykbs0avwy8ifGgVvzj32j3o%2BIwjDuu5gX8p60jGxLsuoAGwUBIF6uBYGnuel5PjeH6AU%2Bb54R%2BX4/i%2Bf6wfBD6nqBKGDiAAIgc4vLMKekxmqyHKcp8fJdLRya8sQTEsWyXIkbyXEUfRyD8eabEgeyImkJRVGDmJvLEsBzFSVyzicQpimTDRp6MWp1AJjaonARJRn2jp/wOk6kYQWMciyNZfwSAeR5iCe5lGv%2BOHAS5KH6f59GGSM6msVyHGyWZdG8nYkkRZywkxTxFlhQJ0mcfJyG6bWwUqQlgmclp0UBeBQUjKFzFWom6AxWlzFWTlg62QpLpqOizqOawznNSOkzegGvIBjRCAiOg7CTKgS6OJMxrrJMaC6B4eDsMQ0gKRp7F8js9GTBxKZdaiHVUNKd7Oj8QozpYEAEkmzoygpQpbTtPE7DKnx2l9%2B23smdn6qSFKGtSUGxqyAqcK1zUsgQvS0OuRXCX9Z1IgMXSsCAAzsgMpAGAMnw46gmOHNIPR9CuKKcDjBCYwTHRdAA1iAIyuAAdOyrifK43DrOynCfALKyGOyQiY9wON4wTpBEwMOPSCAn00/jaOkHAsBIEtK1reQlCa6tFTIMA3CcCMpCzKwBCOPLEB2LTON2JYaRkpjVOkEtuiqAQAa0KwzvK6QWAzqI7B2wHeAskkeKYPL/uYMaiTaJbLs44ycih%2BmdjEE7mhYMnpAEMQeC6MnXQ0PQTBsBwPD8IIlbiJIQh4HY8uQF0qAeAUtAxwAtAGziTN3VBrt3ujOCMcsJEkygQKYdTZCYailFEMSCF4Pid3Pq%2BhJ3S/lE4nDxPkyRNJvB95IkndFOku9tPvjTFKf9/Xy0y8VJD3S9P0XDo5j2O46HMt5prG7msbgkxgDIFxNwVmnBWbpVwIQEgAJnAH0mJoZa%2BtiDIMhmg6mdt6akCZs4QwrNPjC0MJwFYnxODsjWGsdkKxRYDHFv/f2Ms5YK3zvg1WMBEAoFQBg7WFAIB6zWigCsIhgDOE%2BubS261KC239g7WgTs87u09t7X2odA6SJDv7fAEdFBRxjlLOOCck4DFdqnDG/sM5Z2IGSHOgxXYFyLiXM2dBGAsBDtXAQps64gAkDSRuzd4Btw7n4HufcB5D2eIcEeY8J5H2nrPLQWRBCmBvivA%2Ba8wj%2BDSfUEI68/BZLfofC%2Bx8H4FPnufKetAr7NEiHvQQWJajVJaU0Up%2B8uik0/lXH%2BWMJYAMxkAkBYCJGiEmM4UhpDmIIKIFgymAp0Fa1miiEY2x1B4OVgQoh0znAHMOUco5TCWGS0JpjDhit8EDPHqwqW7CuE7K6FHdafgQDcCAA)

### CODE REVIEW

**Comment by mattip** [comment]
Why wasn't this code path hit on the 32 bit linux build on azure here, but only when building wheels? Can we mock what the wheel building does in a test?

**Comment by mattip** [comment]
maybe compiler version. I guess we could run the CI in a manybuild docker.

**Comment by seiko2plus** [comment]
@mattip, yes its compiler version, up to GCC 4.9

**Comment by mattip** [comment]
Thanks @seiko2plus. I guess this kind of thing is rare enough we can leave it for the wheel building to find

**Comment by seiko2plus** [comment]
@mattip, when I get done from the main tasks, I will work on adding the ability to configure CI from pull-requests in order to customize the build,  like building with certain arguments and enabling certain compilers, also I will try to find a way to speed up the building progress, may through `ccache` and `PCH`.

**Comment by mattip** [comment]
@seiko2plus that sounds nice but low priority.

**Comment by memetb** [comment]
I'm not sure if this is related but when I try to cross-compile/build numpy bdist wheels for arm on a linux box, I get a spurious m32 flag that upsets the `arm-linux-gnueabihf-gcc` call. Related? Would you like details or not?

**Comment by mattip** [comment]
We don't set `-m32` anywhere in the numpy code as far as I can tell. This may be coming from setuptools/distutils querying the host python for compiler flags, in particular maybe from one of these values: 

```
sysconfig.get_config_vars('CC', 'CXX', 'OPT', 'BASECFLAGS','CCSHARED', 'LDSHARED', 'SO')
```

**Comment by memetb** [comment]
Thanks for that prompt response. I was on this path already (had grepped up and down and not found anything related), but the title on this bug report made me pause and wonder if it came from deep down somewhere.

**Pull request merged**
