### PR TITLE
DOC: Add `np.ctypeslib` examples and further documentation

### LINKED ISSUE #22268: DOC: `np.ctypeslib` - list of functions that are missing examples – tracking issue
Find below the functions from `np.ctypeslib` that are missing examples in the docstrings. If you have a suggestion for an example, please submit a pull request.
To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)

- [x] as_array
- [ ] as_ctypes
- [ ] as_ctypes_type
- [x] load_library

**IMPORTANT:** Don't close this issue or remove the *"sprintable"* label until all the PRs with examples are merged.

### PR DESCRIPTION
**Pull request by linus-md**
This closes #22268 and borrows from the closed PR #22303.

### CODE REVIEW

**Comment by linus-md** [comment]
Any advice on how to format lines 125 and 126 would be appreciated.
```./numpy/ctypeslib.py:125:80: E501 line too long (94 > 79 characters)
./numpy/ctypeslib.py:126:80: E501 line too long (162 > 79 characters)```

**Review by rossbar — COMMENTED** [review]
I would've expected these to be failing the refguide checks, as there are e.g. hard-coded paths, memory locations, and Python versions in the outputs. Just something to keep an eye on!

**Comment by ngoldbaum** [comment]
I'm sorry, I didn't mean to merge this. I did merge https://github.com/numpy/numpy/pull/25322/commits and I think @linus-md might have accidentally done that work on top of this PR, backing out this PR first. I didn't look at the commit list before I merged the other PR and probably should have. I will try to make sure to do that from now on and ask to squash first.

Sorry about the trouble, still getting my feet under me as a maintainer!

@linus-md you're going to have to re-issue this PR if you want to get this change in.

**Comment by linus-md** [comment]
Hi @ngoldbaum what happened here? Was there an issue because I forgot to switch my branch in #25322 and reverted the changes and you merged this one at first and then the one reverting the changes? I can find the added examples from ``np.char``but not those here.

**Comment by ngoldbaum** [comment]
Take a look at the “commits” tab of #25322. You’ll see it includes the commits in this PR. I think you forgot to switch back to the `main` branch after working on this PR and instead *reverted it* and did the other PR “on top” of this one. When I merged #25322, that meant numpy’s git history also includes the commits from this PR so from github’s perspective this PR is merged. The *changes* from this PR aren’t in numpy yet, because you reverted those changes before working on the other PR.

Does that make sense?

**Comment by ngoldbaum** [comment]
Also this is a super common thing to get wrong and git and github’s interface makes it easy to miss.

In another project I worked on in grad school someone added and then removed a one gigabyte binary file, increasing the repository size by two gigabytes. No one noticed because the PR diff didn’t include the binary - it was added and removed after all! A few months later someone complained about the size of the repo it was a huge headache to fix. So it could have been worse!

**Comment by linus-md** [comment]
`Does that make sense?`

Yes thank you for explaining it. I am still getting used to using git for larger projects!

**Pull request merged**
