### PR TITLE
ENH:: Enable loadtxt to skip given number of first and last columns.

### PR DESCRIPTION
**Pull request by minahanr**
In response to issue #13878.

Added a parameter for the function loadtxt(), `skipcols`.
If skipcols is a positive integer, loadtxt() will not load the first `skipcols` columns.
If skipcols is a negative integer, loadtxt() will not load the last `skipcols` columns.
If skipcols is a tuple, loadtxt() will not load the first `skipcols[0]` columns or the last `skipcols[1]` columns.
Also added a number of tests to assure that skipcols worked properly under a variety of circumstances, including outliers such as when the txt file has either only one row or column.

Side notes:
Currently, if the user tells loadtxt() to skip more columns than are in the txt file, loadtxt() will return an empty array rather than giving an error.
Whether skipcols[1] is positive or negative, it will skip the last `|skipcols[1]|` columns. This would be easy to change, but both scenarios seem natural, so I allowed both of them.

### CODE REVIEW

**Comment by mattip** [comment]
@minahanr the API for this parameter is still not settled. Which approach did you take? Why did you feel the need for a PR?

I am tempted to close this:
- we did not settle on an API, that should be done before issuing a PR
- there is already gh-15080

**Comment by charris** [comment]
This will need a release note.

**Comment by WarrenWeckesser** [comment]
As @mattip pointed out, there is already [another PR](https://github.com/numpy/numpy/pull/15080) with a similar goal.  And there is some discussion of possible API changes in https://github.com/numpy/numpy/issues/13878, where I suggested allowing `usecols` to accept a `slice` object, and @eric-wieser suggested allowing `usecols` to accept a callable that takes the number of columns found in the file as an argument and must return the actual columns to be used.  I think something along those lines is preferable to adding another parameter to `loadtxt`.  If anyone has further suggestions for modifying the API, https://github.com/numpy/numpy/issues/13878 is probably the best place to discuss them.

**Comment by mattip** [comment]
Closing. @minahanr if you want to move this forward feel free to reopen with answers to the issues raised in the comments, or help move gh-15080 forward

**Pull request closed without merging**
