### PR TITLE
MAINT: Remove Python2 newbuffer getbuffer

### PR DESCRIPTION
**Pull request by sethtroisi**
More Py3K work

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Looks good, thanks.

Can you fix the commit message to conform to [guidelines](https://numpy.org/devdocs/dev/development_workflow.html#writing-the-commit-message)?

**Comment by WarrenWeckesser** [comment]
It might be better to *not* change the file `doc/Py3K.rst.txt`, as that looks like documentation of the 2->3 transition process.  I don't think it is intended to be the place to track the current status of what still needs to be done.

**Comment by charris** [comment]
> It might be better to not change the file `doc/Py3K.rst.txt`

Agree. It is a historical document.

**Comment by sethtroisi** [comment]
ACK on not changing Py3K.rst.txt

**Comment by mattip** [comment]
Thanks @sethtroisi

**Pull request merged**
