### PR TITLE
BUG: Make changelog recognize ``gh-`` as a PR number prefix.

### PR DESCRIPTION
**Pull request by charris**
The `changelog.py` script was only recognizing fast forward merges  where the PR number was of the form "(#xxxxx)", but some people were merging with the "(gh-xxxxx)"  or (typo) "gh-#xxxxx" form. Also ignore dependabot-preview as an author.

*  Update the 1.20.0 changelog.
*  Update the 1.19.0 changelog.
*  Update the 1.18.0 changelog.
*  Update the 1.17.0 changelog.

### CODE REVIEW

**Comment by seberg** [comment]
woops, sorry about that, I prefer the gh-, so I sometimes change it...

**Comment by charris** [comment]
close/reopen

**Comment by charris** [comment]
@r-devulap Thoughts?

**Comment by charris** [comment]
close/reopen

**Pull request merged**
