### PR TITLE
ENH: Add binding for random pyx files

### LINKED ISSUE #21908: BUG: Functions in `numpy.random` have no signature (in the sense of `inspect.signature`)
### Describe the issue:

While writing bindings for Numpy I discovered that functions in `numpy.random` are
missing signatures (in the sense of `inspect.signature`). 

My use case: I am using function signatures to  automatically generate Racket bindings for large parts of Numpy.

The following output were generated by the script `signature-random.py`.

Functions where inspect.signature fails
---
Functions where inspect.signature works
---
__RandomState_ctor

Builtins (where inspect.signature fails)
---
beta
binomial
bytes
chisquare
choice
default_rng
dirichlet
exponential
f
gamma
geometric
get_state
gumbel
hypergeometric
laplace
logistic
lognormal
logseries
multinomial
multivariate_normal
negative_binomial
noncentral_chisquare
noncentral_f
normal
pareto
permutation
poisson
power
rand
randint
randn
random
random_integers
random_sample
ranf
rayleigh
sample
seed
set_state
shuffle
standard_cauchy
standard_exponential
standard_gamma
standard_normal
standard_t
triangular
uniform
vonmises
wald
weibull
zipf

### Reproduce the code example:

```python
import inspect
import numpy

###
### This script finds the functions in `numpy.random` that have no signatures.
###


# Attempt to get the signature for `f`.
# Return `False` when no signature is available.
def sign(f):
   try:
     return inspect.signature(f)
   except:
     return False

mod = numpy.random
 
print("Functions where inspect.signature fails")
print("---")
for x in dir(mod):
    f = getattr(mod,x)
    if inspect.isfunction(f):
       if not sign(f):
          print(x)

print("Functions where inspect.signature works")
print("---")
for x in dir(mod):
    f = getattr(mod,x)
    if inspect.isfunction(f):
        if sign(f):
            print(x)

print("")
print("Builtins (where inspect.signature fails)")
print("---")
for x in dir(mod):
    f = getattr(mod,x)
    if (not inspect.isfunction(f)) and inspect.isbuiltin(f):
       if not sign(f):
          print(x)
```

### Error message:

_No response_

### NumPy/Python version information:

>>> import sys, numpy; print(numpy.__version__, sys.version)
1.22.4 3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]

### PR DESCRIPTION
**Pull request by bashtage**
Add binding so that inspect will work correctly

closes #21908

### CODE REVIEW

**Comment by bashtage** [comment]
No idea if this is side effect free, but should fix the issue.

**Comment by bashtage** [comment]
Does fix the `inspect` issue.

```
In [1]: import numpy as np

In [2]: import inspect

In [3]: inspect.signature(np.random.bytes)
Out[3]: <Signature (length)>

In [4]: sig = inspect.signature(np.random.bytes)

In [5]: sig.parameters
Out[5]: mappingproxy({'length': <Parameter "length">})

In [6]: gen = np.random.default_rng(0)

In [7]: inspect.signature(gen.integers)
Out[7]: <Signature (low, high, size, dtype, endpoint)>
```

**Comment by bashtage** [comment]
Not sure why Cython is introducing so many unused variables. Only happens in generator not mtrand.

```
    INFO: building 'numpy.random._generator' extension
    INFO: compiling C sources
    INFO: C compiler: gcc -pthread -B /home/kevin/anaconda/envs/throw-away/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/kevin/anaconda/envs/throw-away/include -I/home/kevin/anaconda/envs/throw-away/include -fPIC -O2 -isystem /home/kevin/anaconda/envs/throw-away/include -fPIC

    INFO: compile options: '-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNPY_NO_DEPRECATED_API=0 -Inumpy/random -Inumpy/random/src -Inumpy/core/include -Inumpy/core/include/numpy -Ibuild/src.linux-x86_64-3.9/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/home/kevin/anaconda/envs/throw-away/include/python3.9 -Inumpy/core/src/common -Inumpy/core/src/npymath -I/home/kevin/anaconda/envs/throw-away/include/python3.9 -c'
    extra options: '-U__GNUC_GNU_INLINE__ -msse -msse2 -msse3'
    INFO: gcc: numpy/random/_generator.c
    numpy/random/_generator.c:37271:20: warning: ‘__pyx_mdef___pyx_memoryviewslice_3__setstate_cython__’ defined but not used [-Wunused-variable]
    37271 | static PyMethodDef __pyx_mdef___pyx_memoryviewslice_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_memoryviewslice_3__setstate_cython__, METH_O, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:37213:20: warning: ‘__pyx_mdef___pyx_memoryviewslice_1__reduce_cython__’ defined but not used [-Wunused-variable]
    37213 | static PyMethodDef __pyx_mdef___pyx_memoryviewslice_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_memoryviewslice_1__reduce_cython__, METH_NOARGS, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:34368:20: warning: ‘__pyx_mdef___pyx_memoryview_3__setstate_cython__’ defined but not used [-Wunused-variable]
    34368 | static PyMethodDef __pyx_mdef___pyx_memoryview_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_memoryview_3__setstate_cython__, METH_O, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:34310:20: warning: ‘__pyx_mdef___pyx_memoryview_1__reduce_cython__’ defined but not used [-Wunused-variable]
    34310 | static PyMethodDef __pyx_mdef___pyx_memoryview_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_memoryview_1__reduce_cython__, METH_NOARGS, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:34216:20: warning: ‘__pyx_mdef_15View_dot_MemoryView_10memoryview_23copy_fortran’ defined but not used [-Wunused-variable]
    34216 | static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_23copy_fortran = {"copy_fortran", (PyCFunction)__pyx_memoryview_copy_fortran, METH_NOARGS, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:34121:20: warning: ‘__pyx_mdef_15View_dot_MemoryView_10memoryview_21copy’ defined but not used [-Wunused-variable]
    34121 | static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_21copy = {"copy", (PyCFunction)__pyx_memoryview_copy, METH_NOARGS, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:34044:20: warning: ‘__pyx_mdef_15View_dot_MemoryView_10memoryview_19is_f_contig’ defined but not used [-Wunused-variable]
    34044 | static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_19is_f_contig = {"is_f_contig", (PyCFunction)__pyx_memoryview_is_f_contig, METH_NOARGS, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:33967:20: warning: ‘__pyx_mdef_15View_dot_MemoryView_10memoryview_17is_c_contig’ defined but not used [-Wunused-variable]
    33967 | static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_17is_c_contig = {"is_c_contig", (PyCFunction)__pyx_memoryview_is_c_contig, METH_NOARGS, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:30094:20: warning: ‘__pyx_mdef___pyx_MemviewEnum_3__setstate_cython__’ defined but not used [-Wunused-variable]
    30094 | static PyMethodDef __pyx_mdef___pyx_MemviewEnum_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_MemviewEnum_3__setstate_cython__, METH_O, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:29858:20: warning: ‘__pyx_mdef___pyx_MemviewEnum_1__reduce_cython__’ defined but not used [-Wunused-variable]
    29858 | static PyMethodDef __pyx_mdef___pyx_MemviewEnum_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_MemviewEnum_1__reduce_cython__, METH_NOARGS, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:29480:20: warning: ‘__pyx_mdef___pyx_array_3__setstate_cython__’ defined but not used [-Wunused-variable]
    29480 | static PyMethodDef __pyx_mdef___pyx_array_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_array_3__setstate_cython__, METH_O, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/random/_generator.c:29422:20: warning: ‘__pyx_mdef___pyx_array_1__reduce_cython__’ defined but not used [-Wunused-variable]
    29422 | static PyMethodDef __pyx_mdef___pyx_array_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_array_1__reduce_cython__, METH_NOARGS, 0};
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    INFO: gcc -pthread -B /home/kevin/anaconda/envs/throw-away/compiler_compat -shared -Wl,-rpath,/home/kevin/anaconda/envs/throw-away/lib -Wl,-rpath-link,/home/kevin/anaconda/envs/throw-away/lib -L/home/kevin/anaconda/envs/throw-away/lib -L/home/kevin/anaconda/envs/throw-away/lib -Wl,-rpath,/home/kevin/anaconda/envs/throw-away/lib -Wl,-rpath-link,/home/kevin/anaconda/envs/throw-away/lib -L/home/kevin/anaconda/envs/throw-away/lib build/temp.linux-x86_64-3.9/numpy/random/_generator.o -Lbuild/temp.linux-x86_64-3.9 -lnpyrandom -lm -lnpymath -o numpy/random/_generator.cpython-39-x86_64-linux-gnu.so
```

**Comment by WarrenWeckesser** [comment]
Quick link for anyone looking for information about `binding`: [Source Files and Compilation / Compiler directives / `binding`](https://cython.readthedocs.io/en/stable/src/userguide/source_files_and_compilation.html?highlight=binding#compiler-directives).

**Comment by rgommers** [comment]
It may make sense to suppress the warnings by injecting `-Wno-unused-variable` in the build to get this merged. In parallel, getting the issue fixed in Cython would be nice. But that shouldn't be a blocker here.

**Comment by seberg** [comment]
Let's try close/reopen again, I somewhat doubt things changed, but it seems like the easiest thing to see whether cython 3 shipped a fix.

**Comment by bashtage** [comment]
I might need to rebase/merge to get the latest requirements and CI configs.

**Review by seberg — APPROVED** [review]
Thanks, looks like tests are passing, so I think we are fine, and I don't think we added a global warning ignore for this (or I hope so :)).

**Pull request merged**
