### PR TITLE
ENH:  Adding to API of isin, setxor1d  -  Adding of functions with 1D-units: intersect, setxor, union, setdiff -  Proposal for isin Performance.

### PR DESCRIPTION
**Pull request by free-coffee**
Improvements in lib.arraysetops:
1. Added axis argument in isin, as new function definition in: intersect, setxor, union, setdiff
2. Added retrun_index argument in setxor1d
3. Proposal: The in1d function should be more optimised in some cases - if all array elements are very likely but not gurenteed to be unique. Maybe we could have a function that reduces the checking-overhead after an element of the first vector has been confirmed to be in the secound, similar to numpy.core.multiarray._vec_string on c level. Alternatively make in1d assume_unique=True somehow work for non unique arrays?

!! this is in an 80% good state, because i was on a time limit.
! might need to address #11999.

### CODE REVIEW

**Comment by eric-wieser** [comment]
I think this might make sense as a bunch of smaller PRs. Adding `return_indices` to `set_xor` seems pretty sensible to me.

Also, you should probably use a branch that is not `master`.

**Comment by free-coffee** [comment]
Hi, thx for the feedback.
Was not aware and will make a maillist thread about this.
As far as im aware i cant create a branch and ENH type stuff would not fit in the maintenance branches.

**Comment by mattip** [comment]
> As far as im aware i cant create a branch

http://www.numpy.org/devdocs/dev/gitwash/development_workflow.html

You create a branch locally (`git checkout -b my-funky-branch`), make some commits, push to your personal fork of numpy on github, and finally make a pull request to the main repo.

**Comment by charris** [comment]
Need a release note.

**Pull request closed without merging**
