### PR TITLE
DOC: Move documentation from `help(ndarray.ctypes)` to `help(some_array.ctypes)`

### PR DESCRIPTION
**Pull request by eric-wieser**
Method docstrings make more sense in the type itself rather than in a function that produces the type.

These docstring are pretty sub-par for numpy, but I'd prefer to leave improving them to a later commit

--

I haven't attempted to build the docs locally, but I'm hoping I can preview them somehow via the CI?

### CODE REVIEW

**Comment by eric-wieser** [comment]
Testing this is a complete nightmare - you need to do a completely clean build of sphinx each time, which takes ages - and you have to remember to rebuild numpy first too

**Comment by mattip** [comment]
If you are "only" changing docstrings, you can edit the docstrings in your installed numpy and delete the appropriate files from `doc/build/doctrees`. Then `make html` will rebuild only what you have deleted, and pick up the new docstrings. If you are making wider changes then indeed, you must rebuild all the documentation.

**Comment by charris** [comment]
Documentation builds are pretty fast here since I started running two SSD's in RAID 0. Living dangerously...

**Comment by charris** [comment]
LGTM if it works :)

**Review by jeffyancey — APPROVED** [review]
lgtm

**Comment by eric-wieser** [comment]
I think part of the slowness for me comes from running the build in WSL.

Thanks for the tip @mattip. That worked once to clear the cache, but not again for some reason. Either way, it's clear that my machine is not set up in a way that I can spend time on doc nits.

Here's what the cached build on my machine looks like:

image

Which regardless of the actual formatting of the docstrings within, is an improvement

**Comment by mattip** [comment]
Thanks @eric-wieser

**Comment by eric-wieser** [comment]
[Seems to work](https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.ctypes.html?highlight=ctypes#numpy.matrix.ctypes). It seems the `numpy.ctypeslib` link isn't working though.

**Pull request merged**
