### PR TITLE
API: Update `lib.histograms` namespace

### PR DESCRIPTION
**Pull request by mtsokol**
Relevant issue https://github.com/numpy/numpy/issues/24507

Hi @rgommers @ngoldbaum,

This is the first PR within "`lib` namespace cleanup" milestone. This PR moves `lib.histograms` module to a private file and ensures that its public methods are only available through the main namespace (e.g. `np.histogram()`). There are no additional functions that only live in `np.lib.histograms`, so I don't expect any influence on other libraries (although I will check it).

### CODE REVIEW

**Review by ngoldbaum — APPROVED** [review]
This looks good to me. Github search finds a few existing usages of private things with leading-underscore names or things are already public in `numpy`, so I think this is good to do without any deprecations.

**Review by rgommers — APPROVED** [review]
LGTM too. Just one question: the `_impl` suffix to the filename was suggested by @ngoldbaum for names where we'd otherwise have both a public and a private file (e.g. `stride_tricks.py` and `_stride_tricks.py`). In this case though, there's only a single private name. Wouldn't a regular `_histograms.py` look better here? (I'm not sure, it really is a question - naming is hard)

**Comment by mtsokol** [comment]
> LGTM too. Just one question: the `_impl` suffix to the filename was suggested by @ngoldbaum for names where we'd otherwise have both a public and a private file (e.g. `stride_tricks.py` and `_stride_tricks.py`). In this case though, there's only a single private name. Wouldn't a regular `_histograms.py` look better here? (I'm not sure, it really is a question - naming is hard)

I would argue that keeping all implementations in `_<submodule>_impl.py` would be more consistent. I think mixing names depending on the fact of exporting to top or/and local namespace could be a bit confusing. 

```bash
# Let's assume "stuff" submodule exists

numpy/__init__.py  # imports top namespace items

# 1. variant - only top namespace items
numpy/lib/_stuff_impl.py  # hosts implementation, no doubt
or .../_stuff.py  #  alternative name in this case

# 2. variant - top namespace and local items
numpy/lib/_stuff_impl.py  # hosts implementation
numpy/lib/stuff.py  # defines local namespace, imports from impl

```

**Comment by rgommers** [comment]
Okay, fair enough, that's a good argument. I'm happy to go with this. Nathan also approved, so let's roll with this. It's the kind of thing we can easily revisit and make consistent later if we change our minds.

In it goes, thanks again!

**Pull request merged**
