### PR TITLE
MAINT: Extend unit tests for np.zeros, np.ones, np.empty

### PR DESCRIPTION
**Pull request by ChVeen**
After studying the unit tests in `test_matlib.py` I recognized that most unit tests only check the good cases, i.e., the cases with valid parameters.
Typically, in software testing one also checks for invalid parameters and special cases as well.
Thus, I extended the unit tests for `np.ones()` and `np.zeros()`.
Since both are used in a similar way I did both in one PR.

### CODE REVIEW

**Comment by MatteoRaso** [comment]
Thanks for the PR. Is this in response to an issue? If so, please link it. To be honest, I'm not sure why this would be needed. I don't think there's much chance of a function getting added without checks to make sure the user can't feed it bad inputs, and if it does happen, I don't see much of a chance for something disastrous to happen. Having to add tests to check all things that can go wrong would be a massive undertaking that creates more work in the future (tests can have errors themselves, and it's not like you can write tests for tests). In any case, these tests don't actually check `np.ones` and `np.zeros`, they check np.matlib.ones` and `np.matlib.zeros`, which are both depreciated.

**Comment by ChVeen** [comment]
Of course, the `ones()` and `zeros()` functions are somewhat simple. But what disastrous can happen _in general_ if complex functions are not tested properly.
Let me give some examples: 

1) You compute results for a paper and use numpy functions for it. One of the numpy functions was not properly tested and it produces wrong results in edge cases. You do not see this due to the amount of data. Because the numpy function does not react properly with an exception or something your paper will rely on wrong data.

2) A not properly tested numpy function is used in a tool chain and due to some unforeseen parameters it stops working. The tool chain interrupts and the whole system can not work properly. Or more worse the numpy function produces wrong data which will be used in the tool chain. Again we have wrong final results.
Hopefully someone recognizes this.

3) A numpy function works fine (of course :-)) and many software packages rely on the behavior of this function. Then someone changes this function and by accident a bit the needed behavior too. If the needed behavior is tested in the unit test, this problem would be catched immediately (regression test) before deploying.

The fact that I catched deprecated versions of both functions makes this PR a bit senseless, I agree to that. (Maybe the checks should be transferred to the not-deprecated versions then.)
But the need for proper testing should be evident.

BTW: This PR is just a proposal, I wanted to improve something. If it does not fit, simply close :-)

**Review by seberg — COMMENTED** [review]
Thanks, I agree that the tests are not very valuable here, since these are tested by `ndarray` probably and also in a deprecated module.

OTOH, more tests can't really hurt, so thanks.

**Comment by ChVeen** [comment]
Added the unit tests to module `test_numeric.py` to increase the merit a little bit (np.zeros, np.ones, np.empty).
Changed the PR title to reflect that.

**Comment by rossbar** [comment]
I'm -0.5 on churn in the test suite for deprecated modules - I think doing so has more potential downside than upside.

**Comment by mattip** [comment]
> BTW: This PR is just a proposal, I wanted to improve something. If it does not fit, simply close :-)

Thanks @ChVeen for the contribution. As others have mentioned, it does not seem like a good fit. Closing.

**Pull request closed without merging**
