### PR TITLE
CI/BLD: fix cirrus [wheel build]

### PR DESCRIPTION
**Pull request by andyfaff**
Try to fix wheel builds on 1.26.x

### CODE REVIEW

**Comment by andyfaff** [comment]
@rgommers, this gets a lot further, but there's some kind of issue with a symbol:

```
Original error was: dlopen(/private/var/folders/xc/tpssff9959345bnqq4c6tlww0000gn/T/cibw-run-f6i8w72x/cp312-macosx_arm64/venv-test-arm64/lib/python3.12/site-packages/numpy/core/_multiarray_umath.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_cblas_caxpy64_'
```
I'd hazard a guess that it's because the Xcode for Ventura/Sonoma is bumped, which probably puts it out of sync with the gfortran compiler.

**Comment by charris** [comment]
I'm beginning to wonder if backporting the build from 2.0.x might be easier :)

**Comment by rgommers** [comment]
> I'd hazard a guess that it's because the Xcode for Ventura/Sonoma is bumped, which probably puts it out of sync with the gfortran compiler.

That's a reasonable guess I think. The symbol name is correct, I verified that that's the name present in the macOS arm64-cp312 wheel for 1.26.4.

I am hours away from starting a two week long holiday, so I don't really have time to dig in. 

Other CI also needs tweaks. There are no critical fixes in this new release as far as I can tell, and only a handful of niche ones. Do we really want to spend time on getting this all sorted out for a `1.26.5` release?

**Comment by charris** [comment]
> Do we really want to spend time on getting this all sorted out for a 1.26.5 release?

No. I think there was only one PR in 1.26.5 that could be called somewhat important  and with 2.0.0 as close as it is I don't think it is worth the time. 1.26 always had a couple of CI problems, and has served its purpose of getting out a NumPy version that supported Python 12. If 1.26.5 were easy, I would release it, but it seems the problems are non-trivial.

**Pull request closed without merging**
