### PR TITLE
TST: fix forgotten change of not creating errors from test warnings i 1.10.x

### PR DESCRIPTION
**Pull request by rgommers**
See https://github.com/numpy/numpy/blob/master/doc/HOWTO_RELEASE.rst.txt#handle-test-warnings

Closes https://github.com/scipy/scipy/issues/5331#issuecomment-147504218

### CODE REVIEW

**Comment by charris** [comment]
Should also put a note in `numpy-vendor/README.rst`, as that is the script I followed in producing the release.

**Comment by charris** [comment]
Thanks Ralf. I wonder if there is a better way to do this, perhaps by interrogating the numpy version or looking in the setup.py file.

**Comment by rgommers** [comment]
Hmm, it could be something like ``'.dev0' not in ``np.__version__``. I'd rather have it turned off in all maintenance branches, but that's not possible to do in code.

**Comment by charris** [comment]
It might be better if all development branches continue to raise errors. Warnings are so easy to ignore...

**Comment by rgommers** [comment]
Done in https://github.com/numpy/numpy/pull/6474

**Pull request merged**
