### PR TITLE
MAINT: Define bit generator constants with DEF instead of cdef

### PR DESCRIPTION
**Pull request by alexhenrie**
This is the only way to tell the compiler that the value is a constant
which may be inlined instead of read from memory.

### CODE REVIEW

**Comment by seberg** [comment]
Hmm, to be sure, @alexhenrie would we notice if you forgot the cast to `<uint32>` somewhere? It seems a bit annoying that those casts are necessary with this change.

**Comment by alexhenrie** [comment]
Another option is to move the definition of the constants to bitgen.h where they can be defined as static constants or macros with the correct type.

**Comment by seberg** [comment]
Yeah, I am wondering if that is a nicer solution. @bashtage do you have an opinion? The other thing being: Does this actually improve performance in any place where it is relevant, SeedSequence at least is not a speed relevant code path IMO.

**Comment by bashtage** [comment]
These values aren't used in code that has any meaningful performance impact.  I don't think XSHIFT should be changed from calculated to static since (who knows??) there may be some platform somewhere where this size of this variable is not always and forever 16. These are only used by SeedSequence. 

I'm certain that no benchmark could find any performance difference between the existing version and this version.  

@rkern Any opinion?

**Comment by bashtage** [comment]
Does Cython understand UL, as in 0x1234UL?

**Comment by alexhenrie** [comment]
> I don't think XSHIFT should be changed from calculated to static since (who knows??) there may be some platform somewhere where this size of this variable is not always and forever 16.

`np.uint32` is guaranteed to be 32 bits on all platforms, so `np.dtype(np.uint32).itemsize * 8 // 2` will always be 16 on platforms where a byte is 8 bits. If you're worried about [exotic platforms](https://stackoverflow.com/questions/2098149/what-platforms-have-something-other-than-8-bit-char), the current code could actually be wrong on architectures that have 6 bits to a byte (meaning that uint32 could be 6 bytes and XSHIFT would be 24) or 12 bits to a byte (meaning that uint32 could be 3 bytes and XSHIFT would be 12). So hardcoding it to 16 is actually safer because you always want to shift the 32-bit integer by 16 bits here.

> I'm certain that no benchmark could find any performance difference between the existing version and this version.

I suspect [cachegrind](https://valgrind.org/docs/manual/cg-manual.html) would pick up on it, but I'll have to try it to be sure.

> Does Cython understand UL, as in 0x1234UL?

Yes. However, `long` is 64 bits on Linux and 32 bits on Windows. The way to specify that the value is 32 bits on all platforms would be to define it as `(uint32_t)0x1234`, but Cython doesn't support that.

**Comment by bashtage** [comment]
It seems fine although it practically pointless since this code is typically run once or at most a few 1000 times and each call is surrounded by the creation of a few python objects which are going to completely mask any micro optimization here.

**Comment by seberg** [comment]
Thanks for the comment Kevin, lets not dwell on it too much.

Thank you very much for the input @alexhenrie it is a good idea, but I think if there are no use-case test where we can detect a non-negligible speedup, I do not think it is worth the casting trouble to be honest.

**Comment by charris** [comment]
Seems that newer cython supports `const`. See https://github.com/cython/cython/wiki/FAQ#how-do-i-use-const. I'm not sure that would work for this, but it could be checked by looking at the generated code.

**Comment by seberg** [comment]
@charris it supports const in function signatures, but not for a module level constant expression.

**Comment by charris** [comment]
@seberg Thanks, good to know.

**Comment by alexhenrie** [comment]
> Thank you very much for the input @alexhenrie it is a good idea, but I think if there are no use-case test where we can detect a non-negligible speedup, I do not think it is worth the casting trouble to be honest.

I see the value in keeping the code simple. Hopefully Cython will add proper support for numeric constants in the future and then we can revisit this.

**Comment by rkern** [comment]
> I don't think XSHIFT should be changed from calculated to static since (who knows??) there may be some platform somewhere where this size of this variable is not always and forever 16.

FWIW, I only left it as calculated as a way of "showing my work" in case I decided to move to `uint64` words, pre-release, for some reason. That horizon has passed.

I agree that the performance gain for `SeedSequence` probably won't affect real programs. Thank you, @alexhenrie for the thoughtful contribution, though!

**Pull request closed without merging**
