### PR TITLE
MAINT: Fixed all exception cause in conv_template.py

### PR DESCRIPTION
**Pull request by abhayaman669**
This is for issue #15986.
In this, I fixed all the exception cause.
@eric-wieser please review this.
Thank you.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you show what the error traceback used to look like vs what it now looks like?

**Comment by abhayaman669** [comment]
@eric-wieser can you please guide me on how can I check this.
Thank you.

**Comment by abhayaman669** [comment]
@eric-wieser closing this PR as it's mentioned in the file that this is an autogenerated file and this does not need to be edited.
Thank you.

**Comment by eric-wieser** [comment]
I'm pretty sure this file is _not_ autogenerated - this is the file that generates the generated files!

**Comment by abhayaman669** [comment]
yes, you are right. I did it wrong. So is the code correct? should I reopen this PR?

**Pull request closed without merging**
