### PR TITLE
MAINT: remove the entropy c-extension module

### PR DESCRIPTION
**Pull request by mattip**
Replace `entropy` with `SeedSequence` and remove the module. 

xref gh-14359

release note needed, but cannot create until the PR is opened

### CODE REVIEW

**Comment by mattip** [comment]
I don't think this should be called a deprecation, since exposing the new module in 1.17.0 was an oversight in the first place. Hopefully gh-14360 will prevent these kind of issues in the future.

**Comment by rgommers** [comment]
> release note needed, but cannot create until the PR is opened

I noticed that too, always needs an extra commit after opening PR, pretty odd.

> I don't think this should be called a deprecation, since exposing the new module in 1.17.0 was an oversight in the first place. 

agreed. I'd be in favor of backporting this to 1.17.x

**Comment by rgommers** [comment]
the CircleCI failure is related

**Comment by rgommers** [comment]
LGTM, and since @bashtage approved of removing this in gh-14359 I'll push the green button. Thanks @mattip

**Comment by rgommers** [comment]
@charris okay to backport this to 1.17.x? I think that'd be helpful, to not have a documented public-looking function in the latest 1.17.x release.

**Comment by charris** [comment]
@rgommers I'm OK with that. I'd like to get all the fixes and changes to the new random module into 1.17. This is our shaking out period.

**Pull request merged**
