### PR TITLE
ENH: Use new argument parsing for array creation functions

### PR DESCRIPTION
**Pull request by seberg**
The array creation functions have the most to gain:

1. np.asarray is 4 times faster and commonly used.
2. Other functions are wrapped using __array_function__ in Python
   making it more difficult

This commit (unfortunatly) has to do a few things:

* Modify __array_function__ C-side dispatching to accomodate
  the fastcall argument convention.
* Move asarray, etc. to C after removing all "fast paths" from
  np.array (simplifying the code)
* Fixup imports, since asarray was imported directly in a few places
* Replace some places where `np.array` was probably used for speed
  instead of np.asarray or similar. (or by accident in 1 or 2 places)

---

Sorry, this should have been what was in gh-15270 :(.  I split out those PRs from the "full" branch, and apparently picked the wrong commit the last time around.

### CODE REVIEW

**Comment by mattip** [comment]
Looks good. Do the benchmarks confirm that this is more performant or are they about the same? I am a little concerned about possible unintentional behavior changes in the move from `array` to `asanyarray` in `numpy/testing/_private/utils.py`, are you sure this will not affect downstream users? Their classes may leak through to the actual equal/not-equal comparisons now, no?

**Comment by seberg** [comment]
I could undo those, I did go through fairly carefully, my thought was just that it is more idiomatic and previously was likely a micro-optimization.  Those calls had `copy=False, subok=True` which is the identical meaning to  `np.asanyarray`.

**Comment by BvB93** [comment]
As a request: could you add a `# TODO` note to [_asarray.pyi](https://github.com/numpy/numpy/blob/main/numpy/core/_asarray.pyi) to move the respective function-annotations to the (to-be created) mutliarray.pyi stub file?

**Comment by mattip** [comment]
Thanks @seberg

**Pull request merged**
