### PR TITLE
BLD: Add requirements.txt file for building docs

### PR DESCRIPTION
**Pull request by rossbar**
Adds a `doc_requirements.txt` file for cataloging additional dependencies required to build documentation.

Corresponding documentation on building docs and contributing to NumPy updated to reflect additional file.

I chose to include the file as `doc_requirements.txt` in the top-level directory as this is the way it was done for the existing `test_requirements.txt` file. However, it might be more appropriate to define the documentation requirements in the `doc/` folder, e.g. `doc/requirements.txt` or `doc/doc_requirements.txt`.

### CODE REVIEW

**Review by seberg — APPROVED** [review]
Thanks, looks good to me, will merge tomorrow unless someone else wants to comment on it.

**Comment by rossbar** [comment]
@seberg any preference on whether the requirements file is in the top-level dir or the `docs/` dir?

**Comment by seberg** [comment]
Hmm, no, not personally but it seems fine to me with keeping it together with the test requirements file.

**Comment by mattip** [comment]
Thanks @rossbar

**Comment by rgommers** [comment]
LGTM too, thanks @rossbar

**Pull request merged**
