### PR TITLE
ENH: Add SIMD implementation for deg2rad

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Comment by mattip** [comment]
When you reach the stage of asking for review, please include a benchmark that shows the impact of this PR. For an example, see the benchmarking done in #18766

**Comment by HowJMay** [comment]
Hi @mattip thank you for pointing out the benchmark issue. I am actually meeting problems on running the benchmark.
The only machine I have now is x86 machine with ubuntu. Is it ok to run only it?

**Comment by mattip** [comment]
> The only machine I have now is x86 machine with ubuntu

Sure, as long as it has the needed SIMD features to run the code. You may want to throttle the machine to 80% full speed to get more consistent results.

**Review by seiko2plus — CHANGES_REQUESTED** [review]
similar to #19780, there's no need to implement new universal intrinsics for `deg2rad`, just implemented directly inside the source file that defines ufunc inner loop.

Note implement a new universal intrinsic to the interface wouldn't affect on the performance, you have to put it in context.

In the case of `deg2rad`, there's no need to create a new dispatch-able source for it, you can put just your implementation inside https://github.com/numpy/numpy/blob/main/numpy/core/src/umath/loops_unary_fp.dispatch.c.src.

You will have to edit the following files too:

- [core/code_generators/generate_umath.py](https://github.com/numpy/numpy/blob/main/numpy/core/code_generators/generate_umath.py) to activate the simd dispatch and the new unfunc type functions.
- add forward declaration for it in here, https://github.com/numpy/numpy/blob/3544fae2859d8ecac378b9ddc8f909c69455a831/numpy/core/src/umath/loops.h.src#L189-L191

**Pull request closed without merging**
