### PR TITLE
ENH: Add `__array_function__` support to a few `random` functions

### PR DESCRIPTION
**Pull request by mikeiovine**
Linked issue: #15123

This pull request adds `__array_function__` support to the following methods in both `Generator` and `RandomState`:
* `permutation`
* `choice`
* `shuffle`
so that `ndarray` subclasses may provide their own implementation. 

If you have an `__array_function__` implementation like this: 
```python
 def __array_function__(self, func, types, args, kwargs):
    if func not in HANDLED_FUNCTIONS:
        return NotImplemented
    if not all(issubclass(t, MyCustomArray) for t in types):
        return NotImplemented
    return HANDLED_FUNCTIONS[func](*args, **kwargs)
```
And an `implements` decorator like this: 
```python
def implements(numpy_function):
    def decorator(func):
        HANDLED_FUNCTIONS[numpy_function] = func
        return func
    return decorator
```

Since `np.random.{suffle, choice, and permutation}` are really bound methods of an instantiated `RandomState` object, when you provide your own implementation, you have to do: 
```python
@implements(np.random.RandomState.choice) # NOT np.random.choice
def shuffle(random_state, array):
    # custom implementation 

# and similarly for np.random.Generator.choice
```
This is a little clunky, but I'm not sure if there's a better alternative. Please do let me know if you have suggestions :)

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @pentschev

**Comment by bashtage** [comment]
Does `permuted` need the same treatment? 

https://github.com/numpy/numpy/blob/588a517b68d9f273b607622dc854b1b3d014ac58/numpy/random/_generator.pyx#L4196

**Comment by bashtage** [comment]
Also, `mtrand` should not be changed.  This file is frozen and should only receive changes that are needed to continue compiling, but no new features or bug fixes.

**Comment by mattip** [comment]
@seberg is there a question whether this is needed or a question about the implementation?

**Comment by seberg** [comment]
Hmm, just tagged it because I wasn't sure we had a plan for `random`.  I am fine with this, it is pretty limited when it comes to random functionality (and only works for the old api), but I guess that is not really a real reason against it.  Just ping @shoyer in case.

**Comment by jakirkham** [comment]
Was this meant to be closed @mikeiovine?

**Comment by mikeiovine** [comment]
Well to be honest I forgot I had opened this and removed my Numpy fork recently while cleaning my account up. I figured that this change was pretty trivial anyways, so I closed it. But I can re-open if there's a good reason

**Pull request closed without merging**
