### PR TITLE
MAINT: clean up pocketfft modules inside numpy.fft namespace

### PR DESCRIPTION
**Pull request by rgommers**
Follow-up to https://github.com/numpy/numpy/pull/14436#issuecomment-528672347

- `pocketfft.py` --> `_pocketfft.py`
- `pocketfft.c` --> `_pocketfft.c`
- `pocketfft_internal.so` --> `_pocketfft_internal.so`

Also get rid of an old-style `info.py` file with just a module docstring in it.

### CODE REVIEW

**Comment by rgommers** [comment]
@mreineck does this change require any syncing back to your version, or is the NumPy pocketfft on its own now that Pypocketfft switched to C++?

**Comment by mreineck** [comment]
No need to synchronize with the upstream version ... I still have the branch somewhere, but it has been practically abandoned.

BTW I'll only have sporadic net access for the next two weeks, so responses may be delayed.

**Comment by mattip** [comment]
Thanks @rgommers

**Comment by charris** [comment]
@rgommers IIRC, you wanted this backported. Do you still want that?

**Comment by rgommers** [comment]
It's not super high prio, but seems healthy to backport.

**Pull request merged**
