### PR TITLE
BLD: Add Windows 32-bit wheels

### PR DESCRIPTION
**Pull request by lithomas1**

### CODE REVIEW

**Comment by mattip** [comment]
[So close](https://github.com/numpy/numpy/runs/4591018393?check_suite_focus=true#step:4:1279):
```
C:<path>/x86_64-w64-mingw32/bin/ld.exe: skipping incompatible \
   C:<path>/x86_64-w64-mingw32/lib\libmsvcrt.a when searching for -lmsvcrt
```
It seems the [azure build](https://dev.azure.com/numpy/numpy/_build/results?buildId=21843&view=logs&jobId=f4f599af-16a4-5739-21ab-e5c3fd4cfa58&j=c7c297f9-bef7-5b82-8018-be97071b59e8&t=4acccd37-9ebe-5147-da4a-63e0a17bf16e) is using [a different build of mingw](https://dev.azure.com/numpy/numpy/_build/results?buildId=21843&view=logs&j=c7c297f9-bef7-5b82-8018-be97071b59e8&t=4acccd37-9ebe-5147-da4a-63e0a17bf16e&l=110):
```
COLLECT_LTO_WRAPPER=C:<path>/libexec/gcc/i686-w64-mingw32/7.3.0/lto-wrapper.exe
```

**Comment by lithomas1** [comment]
Hmmm. I'm a bit stuck now. I got the correct 32-bit mingw to install by uninstalling the default 64-bit one, but now the build is failing and I can't seem to find an error message.

**Comment by mattip** [comment]
It seems something in the fancy log formatting is eating it up. When I look at the raw logs (click on the gear in the upper-right-hand corner) and search for "error:" I see only the hint at the error, not the error itself. Is there a way to replicate this locally?

```
2021-12-21T17:13:08.0218068Z   INFO: CCompilerOpt.cache_flush[842] : write cache to path -> D:\a\numpy\numpy\build\temp.win32-3.8\ccompiler_opt_cache_clib.py
2021-12-21T17:13:08.0301369Z   error: Command "C:\ProgramData\Chocolatey\bin\gfortran.exe -Wall -g -Wall \
    -g -shared -m32 -Wl,--whole-archive D:\a\numpy\numpy\openblas\openblas.a -Wl,--no-whole-archive \
    -LC:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw32\lib\gcc\i686-w64-mingw32\7.3.0 \
    -LC:\cibw\python\pythonx86.3.8.10\tools\libs -LC:\cibw\python\pythonx86.3.8.10\tools\PCbuild\win32 \
    -Lbuild\temp.win32-3.8 -o build\temp.win32-3.8\Release\.libs\libopenblas.67LVI5PIPIPYANQC3VAWDE6KZKQBFZON.gfortran-win32.dll \
    -Wl,--allow-multiple-definition \
    -Wl,--output-def,build\temp.win32-3.8\Release\libopenblas.67LVI5PIPIPYANQC3VAWDE6KZKQBFZON.gfortran-win32.def \
    -Wl,--export-all-symbols -Wl,--enable-auto-import -static -mlong-double-64" \
    failed with exit status 1
2021-12-21T17:13:08.0644930Z   Building wheel for numpy (pyproject.toml): finished with status 'error'
2021-12-21T17:13:08.0649935Z   ERROR: Failed building wheel for numpy
2021-12-21T17:13:08.0662073Z Failed to build numpy
2021-12-21T17:13:08.0663817Z ERROR: Failed to build one or more wheels
2021-12-21T17:13:08.0673482Z Exception information:
2021-12-21T17:13:08.0674069Z Traceback (most recent call last):
2021-12-21T17:13:08.0675174Z   File "C:\cibw\python\pythonx86.3.8.10\tools\lib\site-packages\pip\_internal\cli\base_command.py", line 164, in exc_logging_wrapper
2021-12-21T17:13:08.0676012Z     status = run_func(*args)
2021-12-21T17:13:08.0676825Z   File "C:\cibw\python\pythonx86.3.8.10\tools\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
2021-12-21T17:13:08.0677666Z     return func(self, options, args)
2021-12-21T17:13:08.0678676Z   File "C:\cibw\python\pythonx86.3.8.10\tools\lib\site-packages\pip\_internal\commands\wheel.py", line 175, in run
2021-12-21T17:13:08.0679687Z     raise CommandError("Failed to build one or more wheels")
2021-12-21T17:13:08.0680876Z pip._internal.exceptions.CommandError: Failed to build one or more wheels
```

**Comment by mattip** [comment]
The command from the [successful auzure build](https://dev.azure.com/numpy/numpy/_build/results?buildId=21846&view=logs&jobId=40b6d036-694f-5d1f-586c-a0e1fd689e6f&j=c7c297f9-bef7-5b82-8018-be97071b59e8&t=4acccd37-9ebe-5147-da4a-63e0a17bf16e) looks like
```
2021-12-21T17:13:07.7513588Z   INFO: C:\ProgramData\Chocolatey\bin\gfortran.exe -Wall -g -Wall -g -shared -m32 \
    -Wl,--whole-archive D:\a\numpy\numpy\openblas\openblas.a -Wl,--no-whole-archive \
    -LC:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw32\lib\gcc\i686-w64-mingw32\7.3.0 \
    -LC:\cibw\python\pythonx86.3.8.10\tools\libs -LC:\cibw\python\pythonx86.3.8.10\tools\PCbuild\win32 \
    -Lbuild\temp.win32-3.8 \
    -o build\temp.win32-3.8\Release\.libs\libopenblas.67LVI5PIPIPYANQC3VAWDE6KZKQBFZON.gfortran-win32.dll \
    -Wl,--allow-multiple-definition \
    -Wl,--output-def,build\temp.win32-3.8\Release\libopenblas.67LVI5PIPIPYANQC3VAWDE6KZKQBFZON.gfortran-win32.def \
    -Wl,--export-all-symbols -Wl,--enable-auto-import -static -mlong-double-64
```

**Comment by rgommers** [comment]
We're currently only building 32-bit Windows wheels for Python 3.8-3.9, and no longer for `>=3.10`. See files at https://pypi.org/project/numpy/1.21.5/#files to confirm. This build adds back a `cp310-win32` job. The reason was that Azure didn't have 32-bit Python 3.10. So adding it back now that we're no longer on Azure seems fine to me.

**Comment by lithomas1** [comment]
@mattip & @rgommers 
This is ready for review now. 
Apparently, I was not adding mingw to path correctly and that was failing silently. Fixing that somehow makes the weird gfortran compilation error go away. 

My best guess for what happened is that choco didn't delete the 64-bit gfortran correctly and somehow got found by the PATH and was run.

Anyways, does anyone want to test the win32 wheel to make sure that there is no 64-bit stuff and that openblas is linked correctly? I don't know how to do that on my 64-bit Windows machine.

**Comment by mattip** [comment]
Cool, great progress! I assume the 4 failing cygwin tests are unrelated. 
>Anyways, does anyone want to test the win32 wheel to make sure that there is no 64-bit stuff and that openblas is linked correctly

Something along the lines of finding a 32-bit windows python, downloading the 242MB of artifacts from the bottom of https://github.com/numpy/numpy/actions/runs/1613397881, opening the zip, and doing `python32-bit-windows -m pip install path-to-32-bit-windows-wheel. That should work even on a 64-bit machine. Then checking the openblas version would be something like these lines but using the DLL in site-packages/numpy/.libs instead: https://github.com/numpy/numpy/blob/4c15ba7f0143778e37b7841b8ccd17b21c796b71/tools/openblas_support.py#L302-L309

**Comment by mattip** [comment]
Looks good, I get `b'OpenBLAS 0.3.18 DYNAMIC_ARCH NO_AFFINITY Nehalem MAX_THREADS=24'

**Comment by mattip** [comment]
Thanks @lithomas1

**Comment by lithomas1** [comment]
Thanks for the help and tips. I'll keep that in mind in the future.

**Comment by liudonghua123** [comment]
I find that there is only `numpy-1.22.3-cp39-cp39-win32.whl`, `numpy-1.22.3-cp38-cp38-win32.whl` exists, `numpy-1.22.3-cp310-cp310-win32.whl` is missing on https://pypi.org/project/numpy/#files. 

I also search whl files provided in pypi from the last two MINOR version of numpy from [1.21.0](https://pypi.org/project/numpy/1.21.0/#files) to [1.22.3](https://pypi.org/project/numpy/1.22.3/#files), the `...-cp310-win32.whl` file is not exists.

**Pull request merged**
