### PR TITLE
MAINT: Use "with open(...)"

### PR DESCRIPTION
**Pull request by jakobjakobson13**

### CODE REVIEW

**Comment by mattip** [comment]
This is very hard to review with all the spurious codecov warnings

**Comment by seberg** [comment]
@charris the changes look good, but I susppect we don't want to modify this because it is just versioneer being vendored?

**Comment by charris** [comment]
> it is just versioneer being vendored?

Versioneer created it, but it won't hurt to fix it.

**Comment by charris** [comment]
Thanks @jakobjakobson13.

**Pull request merged**
