### PR TITLE
ENH: untangle circular import: core imports compat

### PR DESCRIPTION
**Pull request by mattip**
SciPy [reported](https://github.com/MacPython/scipy-wheels/pull/55#issuecomment-547767779) a problem importing 1.17.3 on CPython3.8. I think it is a circular import problem.

### CODE REVIEW

**Comment by mattip** [comment]
Marked for backporting

**Comment by tylerjereddy** [comment]
I'm having a hard time reproducing the original issue locally on a Mac in a virtualenv with Python 3.8/NumPy 1.17.3. It seems to just work (SciPy builds), but figuring out the exact wheels command sequence/scenario can be a pain I suppose.

**Comment by charris** [comment]
How should we test these fixes? I can build pre-release wheels, and maybe following @tylerjereddy do it for the PR.

**Comment by charris** [comment]
That said, the change is pretty minor and shouldn't cause problems. @mattip Could use a comment as to why the order is important.

**Comment by WarrenWeckesser** [comment]
FWIW: On Mac OS 10.12.6 (Sierra), with Python 3.8 from https://www.python.org/downloads/, and with all the dependencies installed with `pip3`, I was able to build scipy with `python3 setup.py bdist_wheel`.  I didn't get the error related to `numpy.compat` and `pickle`.

**Comment by mattip** [comment]
`numpy.core` imports `numpy.compat`, try to prevent a circular import.

**Comment by eric-wieser** [comment]
Does compat import core though? If not, I don't see how the circle can appear

**Comment by mattip** [comment]
`compat` does not import `core`. I am also mystified why the build failed. Happy to close this since the failure does not seem repeatable.

**Comment by charris** [comment]
Scipy still imports from `numpy.compat` in a few places, is that intended? The `numpy-distutils` submodule in `scipy-wheels` also points to a pretty old version, is that still needed.

**Comment by eric-wieser** [comment]
> The numpy-distutils submodule in scipy-wheels also points to a pretty old version

That's the real issue, combined with https://github.com/MacPython/scipy-wheels/pull/55#issuecomment-548409508.

We're mixing and matching `numpy.compat`, `numpy.distutils`, and the rest of `numpy`...

**Comment by eric-wieser** [comment]
Closing this, since it won't help anyway. The real issue is that `compat/__init__.py` is being replaced in the build process by an older version that does not define `pickle`.

**Pull request closed without merging**
