### PR TITLE
BUG: Remove trailing dec point in dragon4positional

### LINKED ISSUE #12441: format_float_positional with trim='-' leaves trailing decimal point
When using `format_float_positional` with `trim='-'`, the documentation says it will remove a trailing decimal point, but it does not always do so.

### Reproducing code example:

```python
import numpy as np
print(np.format_float_positional(1e-10, precision=5, trim='-'))
```

This outputs `0.` rather than `0`. Using `0` as input instead of `1e-10` produces the expected output.

### Numpy/Python version information:

1.15.4 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]

### PR DESCRIPTION
**Pull request by corneliusroemer**
fixes #12441

Unfortunately I couldn't test this locally since I cant get the build from source to work #20677

### CODE REVIEW

**Comment by mattip** [comment]
> Unfortunately I couldn't test this locally since I cant get the build from source to work #20677

You could use the [gitpod workflow](https://numpy.org/devdocs/dev/development_gitpod.html) which provides a cloud-based container ready for development

**Comment by mattip** [comment]
In any case, a test that fails before, passes after is needed.

**Comment by corneliusroemer** [comment]
@mattip Added a test, seems to work, who's best placed to review? The change is very simple but this may actually have been my first C code so better have a quick look at it.

**Comment by mattip** [comment]
Thanks @corneliusroemer

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @corneliusroemer! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute/. 
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Pull request merged**
