### PR TITLE
MAINT: Move typing tests

### PR DESCRIPTION
**Pull request by charris**
Move typing tests into a new `numpy/typing/tests directory` where they are easier to define and
closer to their data.

Note that this makes the `typing` module part of the runtime. Is that a problem?

### CODE REVIEW

**Comment by person142** [comment]
> Note that this makes the typing module part of the runtime. Is that a problem?

The conclusion last time this came up was that it was something like a 3% increase in import time, and the odds are (increasingly) good that something else will have imported `typing` already in which case it will be less.

**Comment by charris** [comment]
@person123 This PR is motivated by the desire to move the debug tests to python-3.8. Those tests are built and tested inplace and the typing tests error. Currently we use python-3.6 for the tests and the typing tests aren't run at all for that version.  Because we will be dropping 3.6 soon and the choice of python-dbg is driven by the distribution, Ubuntu focus in this case, we need to have it working or find another way to skip them. I think there is a path problem that this PR will fix, although another possibility is that mypy isn't properly upgraded for the debug run.

I suppose I should check that this PR actually fixes the problem before arguing further.

I don't see why the import times should go up much unless mypy is a slow import, the module isn't imported at the top level. Maybe lazy imports would fix it?

**Comment by charris** [comment]
Looks like this doesn't fix the debug testing problem. I'm suspecting the mypy version is not properly updated.

**Comment by charris** [comment]
Solved the debug test problem by adding `export MYPYPATH=$PWD` to `tools/travis-test.sh`.

**Comment by charris** [comment]
My numpy import time went from .068 sec. to .068 sec. But such things are hard to time when disk and SSD access may go through fast cache memories.

**Comment by eric-wieser** [comment]
> Note that this makes the typing module part of the runtime. Is that a problem?

How exactly is this the case?

**Comment by charris** [comment]
> How exactly is this the case?

Changed my mind, I don't think it does.

**Comment by person142** [comment]
> I don't see why the import times should go up much unless mypy is a slow import, the module isn't imported at the top level.

Oops yes, ignore me; I was misunderstanding.

> Solved the debug test problem by adding export MYPYPATH=$PWD to tools/travis-test.sh.

The intent was for that to be set here:

https://github.com/numpy/numpy/blob/8e4d796b679520a90ad61d370afc03e8e2ba559f/numpy/typing/tests/data/mypy.ini#L2

but it does look like the path is missing a necessary `..` to get all the way to the root. Does adding that help?

**Comment by charris** [comment]
> The intent was for that to be set here:

The debug build is special, there is also an `export PYTHONPATH=$PWD` and it doesn't work without that either.

**Comment by person142** [comment]
Oh, what you're seeing is that PEP 561 is Python 3.7+ only. So for Python 3.6 it does make sense that you would have to set the `MYPYPATH` explicitly.

**Comment by charris** [comment]
> Python 3.6 it does make sense that you would have to set the MYPYPATH explicitly.

Other way around :) Python-3.6 skipped the tests, Python-3.7-9 run the tests, but python-3.8-dbg, which is built inplace, needs the path set.

**Comment by person142** [comment]
Yargh I am really all scrambled up yesterday/today. I am going to just keep quiet now...

**Comment by mattip** [comment]
@charris this is still marked WIP and now has merge conflicts

**Comment by mattip** [comment]
@charris ping

**Comment by charris** [comment]
The question is if we want to do this.

**Comment by charris** [comment]
The merge conflict came from the addition of `numpy/tests/typing/fail/dtype.py` in master.

**Comment by mattip** [comment]
I think it makes sense, but there are ~10 open PRs for typing that will have a conflict if we merge this. Maybe we should merge those first (hint, hint) and take a break from new PRs so we can fix this one up.

**Comment by BvB93** [comment]
Considering we have a set of dedicated typing modules I feel it would also make sense to store the typing tests there.
+1

**Comment by charris** [comment]
Rebased here, just needed to add the new files. It would be good to get the rest of the testing stuff in and make the move.

**Comment by charris** [comment]
I have no idea why the test is failing. The error message is
```
E       AssertionError: numpy/typing/tests/data/pass/flatiter.py:3: error: Module has no attribute "rand"
E         Found 1 error in 1 file (checked 1 source file)
E         
E       assert 1 == 0
```
Yet if I put that failed line in a try... except clause, it is running just fine. The mypy testing is doing something funny and I suspect there is a bug in `api.run`, some sort of path thing. The test runs fine in master, it is only the moved test and the call to `np.random.rand` that fails. Anyone have a idea what `run.api` is actually checking? And why are we using a `np.random.rand(5).flat` which flattens a 1-D array, wouldn't `np.empty((2, 2)).flat` work as well.

**Comment by BvB93** [comment]
Supposedly adding `follow_imports = silent` ([docs](https://mypy.readthedocs.io/en/stable/running_mypy.html#following-imports)) to the ini file should do the trick, but after some trial and error I can't seem to get it to work.

> And why are we using a `np.random.rand(5).flat` which flattens a 1-D array, wouldn't `np.empty((2, 2)).flat` work as well.

Mostly a force of habit; let's just change it.

**Comment by charris** [comment]
@BvB93 There is also a report of the rand problem on s390x, see #16134. My guess is that `np.random` is being confused with Python random in some check.

**Comment by BvB93** [comment]
> My guess is that `np.random` is being confused with Python random in some check.

This would explain a lot actually.
I was wondering why `np.random` was already annotated as a `types.ModuleType` despite it lacking any sort of stub file.

**Comment by charris** [comment]
Not waiting on shippable.

**Comment by charris** [comment]
Tests are moved. @BvB93 Could you check that the path in `mypi.ini` is correct? I'm not sure where it needs to point.

**Comment by BvB93** [comment]
The `mypy_path` parameter should actually be redundant as of the addition of https://github.com/numpy/numpy/pull/17123.
The latter explicitly sets the `MYPYPATH` environment variable (which takes priority).

As a side note, I just noticed that we forgot to update `runtest.py` (fix: https://github.com/numpy/numpy/pull/17267).

**Pull request merged**
