### PR TITLE
MAINT: Take out code that will never be executed

### PR DESCRIPTION
**Pull request by k-kapp**
See issue #9154

### CODE REVIEW

**Comment by mhvk** [comment]
This looks right to me -- this code path cannot be reached -- but since @njsmith last touched this part of the file and changed just these 3 lines, maybe good to have his comments; it may have been the intent to solve for something else...

p.s.  As noted by @eric-wieser, it is fine to make a PR directly, without raising a separate issue. Indeed, it helps to keep the description of the problem together with its solution!

**Comment by charris** [comment]
LGTM, thanks @k-kapp 

@njsmith Comment?

**Comment by charris** [comment]
Looks like over zealous cut-n-paste was the culprit.

**Comment by njsmith** [comment]
Sorry I missed this. The patch looks good to me. My change back in 2012 was
just mechanically replacing a manual writeability check with a call to a
utility function doing the same thing. The odd 'if (!writeable) { if
(writeable) { ... } }' structure is older, and I have no explanation for it
:-).

**Pull request merged**
