### PR TITLE
TST: Start testing with "-std=c99" on travisCI.

### PR DESCRIPTION
**Pull request by charris**
C99 looks to work with gcc for all the Python versions we currently
support. Testing with c99 is a step forward in testing #11888 before
it gets merged after we drop Python 2.7 support.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Would this eventually end up as a change within distutils?

**Comment by charris** [comment]
> Would this eventually end up as a change within distutils?

Maybe. Given that some downstream projects use numpy distutils, we may want to add c99 compilers, such as linux does.
```
charris@fc [numpy.git (master)]$ c99 -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.1.1 20180712 (Red Hat 8.1.1-5) (GCC) 
```

**Comment by charris** [comment]
Maybe this is a better way of showing what linux does
```
charris@fc [numpy.git (master)]$ cat  `which c99`
#!/bin/sh
fl="-std=c99"
for opt; do
  case "$opt" in
    -std=c99|-std=iso9899:1999) fl="";;
    -std=*) echo "`basename $0` called with non ISO C99 option $opt" >&2
	    exit 1;;
  esac
done
exec gcc $fl ${1+"$@"}
```

**Comment by charris** [comment]
@pv @rgommers @juliantaylor Thoughts on C99?

**Comment by rgommers** [comment]
+1 for full C99 compat, but I don't think we can add it to `numpy.distutils` as a default flag - that will break too many other packages. New compilers doesn't sound attractive; I'd just add a flag to `setup.py` somewhere.

**Comment by pv** [comment]
I'm not sure any changes in numpy.distutils are required --- there's potential downstream breakage, and those who need this sort of flags or compiler executables can add them themselves.

For numpy itself, C99 should be fine. That MSVC doesn't support it fully is ridiculous, but IIUC the newer versions Python3 uses are better than the 2.7 situation.

**Comment by rgommers** [comment]
> That MSVC doesn't support it fully is ridiculous, but IIUC the newer versions Python3 uses are better than the 2.7 situation.

Yeah, Steve Dower said that anything in C99 not supported for MSVC 2015 (IIRC, could be 2017) is considered a bug. So should be fine by now for Python 3.x

**Comment by charris** [comment]
> anything in C99 not supported for MSVC 2015 (IIRC, could be 2017)

The bare `restrict` keyword does not seem supported, although there is a similar `__restrict`.

**Comment by charris** [comment]
Note that pocketfft is now building on both travis and appveyor, #11888.

**Comment by charris** [comment]
Going to merge this. The `-Wno-declaration-after-statement` flag is still there, as that also fails for Python 2.7 on Windows and gcc gives a much nicer error message. We can remove that when we drop Python 2.7 and add the flag somewhere else for building NumPy. Do we have any other compiler specific stuff in the build process that isn't part of distutils?

**Pull request merged**
