### PR TITLE
MAINT: doc: Remove doc/newdtype_example/

### LINKED ISSUE #9282: newdtype example doesn't work with python3
python 3 change some c api, so newdtype example in doc can't compile

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
This example of creating a custom dtype has had only cosmetic changes
(e.g. fix whitespace, add `from __future__ ...`) since 2008, and it hasn't
been touched at all since early 2016.  It was never updated for Python 3.
The example is not well docmented, and it is not referred to anywhere else
in the documentation, so it isn't really serving a useful purpose in the
doc directory.

If someone is looking for an example of creating a custom dtype, we can
direct them to numpy/numpy/core/src/umath/_rational_tests.c.src, which, as
part of the test suite, is actively maintained.

Closes gh-9282.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The test failure on **Azure Pipelines / azure-pipeline numpy.numpy (ComprehensiveTests macOS)** is not related to this pull request.

**Comment by mattip** [comment]
Do you see a place where you can add something about the proper example? Perhaps another section on this page https://numpy.org/devdocs/user/c-info.how-to-extend.html?

**Comment by WarrenWeckesser** [comment]
@mattip, it looks like the most appropriate section of the docs is ["User-defined data-types"](https://numpy.org/doc/1.17/user/c-info.beyond-basics.html#user-defined-data-types).  I could add a sentence after that first paragram that refers to `_rational_tests.c.src`.  Maybe something like

> [existing text...] available. As an example of what I consider a useful application of the ability to add data-types is the possibility of adding a data-type of arbitrary precision floats to NumPy.
>
> [new text added] The NumPy source code includes an example of a custom data-type as part of its test suite.  The file `numpy/numpy/core/src/umath/_rational_tests.c.src` implements a data-type that represents a rational number as the ratio of two 32 bit integers.

What do you think?

**Comment by mattip** [comment]
That whole paragraph needs a rewrite. It mentions NumPy1.0, uses first person, It does seem like the right place, so go for it.

**Comment by WarrenWeckesser** [comment]
@mattip, in the last commit, I modified the doc section on user-defined types. I removed the sentences that seemed to be expressing opinions, and added a note about the file `_rational_tests.c.src`.

**Pull request merged**
