### PR TITLE
MAINT: Fixed C++ guard in f2py test.

### PR DESCRIPTION
**Pull request by siavashserver**
Hello :)

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Does `foomodule.c` even need the C++ guard?  Why would it be compiled with C++?

**Comment by charris** [comment]
@WarrenWeckesser f2py was also used for interfacing C and C++ code. I don't know where things sit these days.

**Comment by WarrenWeckesser** [comment]
Sure, I was just wondering if this particular test file needs the guards.  They can't hurt, I guess, so it makes sense to fix the use of `__cplusplus` as in this pull request.

**Comment by charris** [comment]
Curiously, cpython 3.6 is also loaded with `__cplusplus` guards.

**Comment by siavashserver** [comment]
I guess the intent was to deal with unwanted C++ [name mangling](https://en.wikipedia.org/wiki/Name_mangling) for a couple of external Fortran function declarations there so it can safely call Fortran produced functions.

**Comment by WarrenWeckesser** [comment]
That only happens if the file is compiled with a C++ compiler.   I don't see why that would happen.  This is a C file, and I would expect the code that builds the test to use a C compiler.  And the fact that this file has had incorrect C++ guards for over ten years suggests that it is, in fact, only compiled with a C compiler.

**Comment by charris** [comment]
My guess is that the test was part of the `f2py2e` project back before is was brought into NumPy in what looks like 2005.  I'm not sure why the guard is there, it can probably be removed, but it is possible that it was intended to be compiled by a C++ compiler.

**Comment by charris** [comment]
I think at some point there was intent to support C++ compilers, but I expect that was done by forcing forcing the C++ compilers to compile code with `*.c` extensions. There are several `*.c` files with the guard. So I am going to put this in for now, but because there is little, if any, testing of C/C++ extension modules, we should decide whether we actually do still support those languages and add tests if we do.

**Comment by charris** [comment]
Thanks @siavashserver .

**Comment by siavashserver** [comment]
@charris My pleasure :)

**Pull request merged**
