### PR TITLE
DOC: Fix some document build errors about rst markups

### PR DESCRIPTION
**Pull request by ghost**
[skip cirrus] [skip azp] [skip actions]

### CODE REVIEW

**Comment by mattip** [comment]
Close/open to retrigger after scipy fix

**Comment by mattip** [comment]
It seems scipy nightly still does not work...

**Comment by rgommers** [comment]
Working on the `scipy` nightlies. Also, let's merge after gh-25911 or without the changes to the `array_api` docs, because those will conflict.

**Comment by rgommers** [comment]
Doc build is going to still be broken because of `pandas` though. Happy to verify it locally before merging.

**Review by rgommers — APPROVED** [review]
Fixed the merge conflict and fixed a couple more warnings. All looks good now, back to zero Sphinx warnings for me locally. In it goes. Thanks @F3eQnxN3RriK

**Pull request merged**
