### PR TITLE
MAINT: Bump pydata-sphinx-theme and set logo link to index

### LINKED ISSUE #17211: Numpy logo in new theme links to an undesirable page
It goes to https://numpy.org/devdocs/contents.html instead of the index.

### PR DESCRIPTION
**Pull request by leonarduschen**
Closes #17211

WIP: Will update as soon as ``pydata_sphinx_theme`` is updated

### CODE REVIEW

**Comment by mattip** [comment]
xref pandas-dev/pydata-sphinx-theme#246. Once that is merged we will need a new release of the theme.

**Comment by leonarduschen** [comment]
> xref pandas-dev/pydata-sphinx-theme#246. Once that is merged we will need a new release of the theme.

Yep, will need to bump to the new release version after the update

**Comment by mattip** [comment]
Did you mean to update the version of the theme in [the requirements file](https://github.com/numpy/numpy/blob/master/doc_requirements.txt#L7)? They have released 0.4.2

**Comment by mattip** [comment]
Are you sure this was merged? I see a `WARNING: unsupported theme option 'logo_link' given`

**Comment by leonarduschen** [comment]
Right, that was just a rebase just now. Will push once I confirm the docs in my local.

**Comment by leonarduschen** [comment]
Whoops you're right, the merge wasn't included in this release, gotta wait until they do I guess.

**Comment by charris** [comment]
Needs rebase. Is this still relevant?

**Comment by leonarduschen** [comment]
@charris yes, made this PR https://github.com/pandas-dev/pydata-sphinx-theme/pull/246 to close #17211, waiting to be released

**Comment by leonarduschen** [comment]
finally done (:

**Comment by mattip** [comment]
[Looks good](https://18779-908607-gh.circle-artifacts.com/0/doc/build/html/reference/generated/numpy.char.capitalize.html#numpy-char-capitalize) the offset is gone I think.

**Comment by mattip** [comment]
Thanks @leonarduschen

**Pull request merged**
