### PR TITLE
DEV: add .editorconfig for C/C++

### PR DESCRIPTION
**Pull request by e-kwsm**
Add [editorconfig](https://editorconfig.org/) file according to <https://numpy.org/neps/nep-0045-c_style_guide.html>.

### CODE REVIEW

**Comment by mattip** [comment]
Interesting. I had never heard about editconfig but apparently [many editors](https://editorconfig.org/#pre-installed) support this file without a plugin.

**Comment by ngoldbaum** [comment]
Nice, I want to see if I can get my emacs to pick this up. I have a hand-customized `.dir-locals.el` for numpy and it's very janky.

**Review by rgommers — APPROVED** [review]
LGTM. This seems like a good idea to add in principle. It's pretty basic, but consistent with NEP 45. It could be extended later for `.py` and other files if desired (trimming trailing whitespace in `.py` files in particular seems helpful, since that often creeps in with new PRs).

Seems fine to merge to me.

**Comment by mattip** [comment]
Thanks @e-kwsm.

**Pull request merged**
