### PR TITLE
MAINT: Fix a comment regarding the formula for arange length

### PR DESCRIPTION
**Pull request by MSeifert04**
The code computes `PyNumber_Subtract(stop, start)` so I changed the comment about the formula from `start - stop` to `stop - start`.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Is `MAINT` the right prefix for this kind of PR or should it rather be `DOC`?

**Comment by charris** [comment]
Usually "DOC", "MAINT" is more a code thing.

**Comment by charris** [comment]
Thanks @MSeifert04 .

**Comment by MSeifert04** [comment]
Thank you for the clarification @charris . I'll use `DOC` next time :)

**Pull request merged**
