### PR TITLE
DOC: Fix an obvious mistake in a message printed in doc/Makefile.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Review by charris — APPROVED** [review]

**Comment by charris** [comment]
LGTM.

**Comment by mattip** [comment]
Should we remove that target?

**Comment by rossbar** [comment]
There may be a couple things that are candidates for removal from the Makefile (at least they are out-of-sync with the current version of HOWTO_RELEASE). Maybe removals along these lines are more suitable for other PRs?

**Comment by WarrenWeckesser** [comment]
> Should we remove that target?

I've been using that target to build the docs, but it is likely that my workflow is not up to date.

**Comment by charris** [comment]
Thanks Warren.

**Pull request merged**
