### PR TITLE
DOC: npy format alignment increase to 64 bytes

### PR DESCRIPTION
**Pull request by jzwinck**
This is a follow-on to document #9025.  A separate PR because git is git.

### CODE REVIEW

**Comment by charris** [comment]
Umm, just do another commit and push to the original PR. You can also use `git rebase -i HEAD^^` to rewrite/squash commits.

**Comment by charris** [comment]
I'm going to close this. You can also check out the changed file in your original PR by `git checkout patch-2 doc/release/1.14.0-notes.rst`.

**Comment by charris** [comment]
Note that if you squash commits, changing history, you will need to do a force push `git push -f origin HEAD`.

**Comment by jzwinck** [comment]
That doesn't work. Rebase doesn't work. I get a conflict in basics.rst or
something like that where somebody made a trivial change to a comment. I
use git every day and I have no idea why it refuses to rebase my other PR.
Due to the long delays in reviewing the other PR a rebase is required or
else the release notes file for 1.14 does not exist. By closing this one
you are costing me hours of additional work which could be better spent
improving NumPy. I realize you think it is some trivial matter to rebase
and 95% of the time it does work but this is git so when it doesn't work
it's impenetrable.

**Comment by charris** [comment]
How does the rebase fail? Conflicts are usually fixable, if nothing else by checking out the difficult file from master and committing it. Note that `basics.rst` was last touched a year ago while `basics.py` has a lot of recent changes, but it is hard to see how that should affect you. Anyway, I'll reopen, but I suspect there is a way to do this on your end.

**Comment by xoviat** [comment]
@jzwinck To update the original PR, use the following:

```
git remote add upstream https://github.com/numpy/numpy.git
git reset --hard HEAD~500
git pull upstream master
git cherry-pick fbf585f
git push -f
```

**Comment by jzwinck** [comment]
@charris When I try to rebase I get:

```
CONFLICT (content): Merge conflict in numpy/doc/basics.py
error: Failed to merge in the changes.
Patch failed at 0296 DOC: Adding backslash between double-backtick and s.
The copy of the patch that failed is found in: .git/rebase-apply/patch
```

I tried resolving the conflict but it won't accept any permutation.

@xoviat Your command `git cherry-pick fbf585f` fails saying no such ref.

Sorry guys, I use Git every day but I need help here.  Please, if you know how to combine these things, combine them.  Or, just merge the two PRs.

**Comment by xoviat** [comment]
> Or, just merge the two PRs.

That's a good point you can run the following instead of the cherry-pick:

```
git merge patch-2
```

**Comment by jzwinck** [comment]
@xoviat Well `git merge patch-2` didn't work but `git merge origin/patch-2` did.  I force-pushed it to #9025 along with the merge commit it made.  I hope that's good enough.  Closing this now.

**Pull request closed without merging**
