### PR TITLE
BUG: financial.pmt modifies input #8055

### PR DESCRIPTION
**Pull request by hodgka**
financial.pmt masked rate array in place, changing original rate array.
Changed to mask to a new array, preserving the original array.

### CODE REVIEW

**Comment by charris** [comment]
Looks good. Could you squash your two commits into one? If you don't know how to do that, ask.

**Comment by hodgka** [comment]
What's the easiest way to do that?

**Comment by charris** [comment]
For your case `git rebase -i HEAD^^` which will bring up an editor with some documentation. Replace `pick` by `s` in the second commit, save and quit. The do a force push `git push -f origin HEAD`.

**Comment by charris** [comment]
Well, that's interesting, this PR has picked up fixes for the nose documentation also... Ah, I see the problem, you are merging from master, a big no-no, always work from a branch. Well, now your fork master has a divergent history from the master NumPy repository, so you may want to delete it after this and refork. But this is mergeable, so let's see what happens.

Looks OK. Thanks @hodgka .

**Pull request merged**
