### PR TITLE
BUG: datetime64 hash

### PR DESCRIPTION
**Pull request by shubham11941140**
Reviving #14622

### CODE REVIEW

**Comment by mattip** [comment]
Please link to previous work like PR #14622 and to the issue this is meant to solve #3836. I don't understand this resubmission: have you changed something and why? Is there a reason you didn't simply add your unique contribution to the comments there?

It seems this is the third such attempt at resubmitting previous PRs - #19718, #19720, and now this one. None of these PRs have descriptions or hints that that they are resubmissions of previous work. Please refrain from wasting precious reviewer time and CI resources.

**Comment by shubham11941140** [comment]
Please reopen the PR so I can delete the previous commit and update it with a new one.

**Comment by mattip** [comment]
I prefer to continue with the older PR. If there are things needed to fix there, you can submit a PR to https://github.com/walshb/numpy/tree/bw-datetime-hash-3836.

**Comment by shubham11941140** [comment]
I understand this, but I just wanted to clear up a few files in this PR.

**Comment by shubham11941140** [comment]
Please reopen: https://github.com/numpy/numpy/pull/19720 and https://github.com/numpy/numpy/pull/19718

**Comment by eric-wieser** [comment]
It appears that @shubham11941140 is trying to remove the evidence that they attempted to pass off other code as their own. Two things to note:

* You can always push commits to an already closed PR
* `git` doesn't forget; https://github.com/numpy/numpy/commit/bdf74574eddf0d1aa079233398aba98e219a4881 still exists even though its not in this PR.

**Comment by shubham11941140** [comment]
I am not able to commit to a closed PR.

**Comment by shubham11941140** [comment]
Please remove the comments that involve copying as I have mentioned the revival of an old PR.

**Pull request closed without merging**
