### PR TITLE
ENH: add hex version, move code to common

### PR DESCRIPTION
**Pull request by mattip**
Add a hex version to `version.py` as well as caching it in C when first called. This is a step toward using the current NumPy version in `PyUFuncObject`, as requested in PR #11175.

The hex version is based on the `PY_VERSION_HEX` macro from CPython.

I also aggregated the other functions that deal with versions into `common/npy_version.c`

### CODE REVIEW

**Comment by charris** [comment]
close/reopen for testing purposes.

**Comment by mattip** [comment]
I don't understand the azure testing
- I still see a [build in progress] for over 8 hours
- For some reason the [azure numpy.numpy-old](https://dev.azure.com/numpy/numpy/_build?definitionId=2) pipeline is triggered for this PR

**Comment by charris** [comment]
Yeah, somehow the test list has become cluttered in the process of experimentation. In this case, the tests seem to have completed in the stalled queue, which is the same as 'azure ci ...' and 'azure-pipeline...' but it didn't update. I suspect a timing glitch. Not sure why the old queue is still running, but suspect it is set up to respond. I'll delete it at some point now that I have figured out how to do that, but was a bit concerned that previous tests would be lost.

I think that azure doesn't archive old tests beyond 30 days or so, so that is something else we might want to look into.

**Comment by charris** [comment]
Looks like newer PRs are just running just one pipeline, so I think this is just a glitch.

**Comment by charris** [comment]
More experimentation.

**Comment by charris** [comment]
Can you try to rebase on master? The error on azure looks to be due to the old multithreaded testing.

**Comment by charris** [comment]
I reran the mac test manually and it passed. I'm thinking that the `numpy.numpy (1)` problem is due to changing the name while a test was in progress.

**Comment by mattip** [comment]
Lets see if a rebase clears the in-progress build

**Comment by mattip** [comment]
The mailing list had one response which was positive and proposed to encode even more info. I left room for the extra information in the lower bits for a future PR to extend this one.

**Comment by mattip** [comment]
Not clear why the macos pipeline failed

**Pull request closed without merging**
