### PR TITLE
MAINT: Update Pyodide to 0.25.1

### LINKED ISSUE #26164: CI: emscripten pyiodide build failing
See https://github.com/numpy/numpy/actions/runs/8473585481/job/23218246517?pr=26160. I was suspicious the setup-python upgrade may have been responsible, but reverting does not fix the failures.

### PR DESCRIPTION
**Pull request by charris**
Closes #26164.

### CODE REVIEW

**Comment by charris** [comment]
Patching pyodide.py is disabled here because it was failing. Not sure what has changed.

**Comment by agriyakhetarpal** [comment]
Hi, @charris! I was fixing this locally actually, now I see that you've done that already :) Thank you for the fix, maybe I should have commented there earlier, but didn't want to pester people on a weekend. It should now be okay to remove the patch step and the file because the commit that the patch was made out of has been included in the `v0.25.1` release. Here it is: https://github.com/pyodide/pyodide/pull/4654/commits/3b540c8c6724c073a056a288da67ac8d5e745ede

**Comment by charris** [comment]
@agriyakhetarpal Thanks for the information. I've removed the patch file and the commented out lines.

**Review by agriyakhetarpal — COMMENTED** [review]
The build and tests are passing here, so LGTM. Thank you for the quick fix!

**Pull request merged**
