### PR TITLE
MAINT: Add appveyor badge to README

### PR DESCRIPTION
**Pull request by jarrodmillman**
You can see a rendered version here:  https://github.com/jarrodmillman/numpy/tree/appveyor

### CODE REVIEW

**Comment by charris** [comment]
With the two badges, might be good to label them.

**Comment by eric-wieser** [comment]
I think this might work better:

```

[![Travis](https://img.shields.io/travis/numpy/numpy.svg?label=travis)](https://travis-ci.org/numpy/numpy)
[![AppVeyor](https://img.shields.io/appveyor/ci/charris/numpy.svg?label=appveyor)](https://ci.appveyor.com/project/charris/numpy)
```

**Comment by jarrodmillman** [comment]
Here are alternatives:
- https://github.com/jarrodmillman/numpy/blob/appveyor/README.md
- https://github.com/jarrodmillman/numpy/blob/appveyor2/README.md
- https://github.com/jarrodmillman/numpy/blob/appveyor3/README.md
- https://github.com/jarrodmillman/numpy/blob/appveyor4/README.md

The last one (suggested by @eric-wieser) looks good.  But i am not sure how to ensure it is using the master branch (presumably it does by default).  It also appeared slow to render sometimes (on my machine), but I don't know if that was a fluke or not as it appears to render fast now.

The middle two options take advantage of AppVeyor's support for customizing text.
- https://www.appveyor.com/blog/2014/11/26/customizing-text-of-build-status-badges/

Unfortunately, Travis does not include a logo and does not  support customizing the text yet (although there is interest):
- https://github.com/travis-ci/travis-ci/issues/5037

I slightly prefer the first option (over the last one) as I think most people that would know what Travis and Appveyor are would recognize their default badges.  It is fairly common:
- https://github.com/matplotlib/matplotlib/blob/master/README.rst
- https://github.com/scikit-learn/scikit-learn/blob/master/README.rst
- https://github.com/networkx/networkx/blob/master/README.rst

And I know how to ensure they are associated with the master branch.

However, that isn't a strong preference and am perfectly happy to do whatever you prefer.

**Comment by jarrodmillman** [comment]
I renamed ``appveyor.yml`` to ``.appveyor.yml``.  I assume that went uncommented as it seems the obvious thing to do (e.g., the travis config is a dot-file).  But I just wanted to make sure it was mentioned, since it would be easy to miss.

**Comment by charris** [comment]
@jarrodmillman AFAICT, appveyor.yml cannot be a hidden file. Google shows a number of requests for that functionality, but I haven't seen anything that shows that it is available.

**Comment by jarrodmillman** [comment]
@charris It is supported:  https://www.appveyor.com/docs/build-configuration/#yaml-file-alternative-naming

I believe it is the config file, which is used to run the tests on this PR.  Other projects also use it without any problems:
- https://github.com/scikit-image/scikit-image
- https://github.com/networkx/networkx

Any preference for which alternative to use for the badges?

**Comment by charris** [comment]
OK. However, I would prefer the rename to be in a separate PR rather than tagged onto a README maintenance PR.

**Comment by jarrodmillman** [comment]
I split the rename into a separate PR (see #9807) as requested.

**Comment by jarrodmillman** [comment]
It turns out we can point the ``img.shields.io`` to the master branch, which I've done.  Here is what the current PR looks like:  https://github.com/jarrodmillman/numpy/blob/appveyor/README.md

**Review by eric-wieser — APPROVED** [review]
LGTM. In future you can use `[ci skip]` in the commit message to not trigger builds, since those don't test docs anyway.

**Comment by jarrodmillman** [comment]
Thanks for the note about ``[ci skip]``.  That is very useful.

**Comment by charris** [comment]
@jarrodmillman Note that if you go to `Files changed` and hit the `view` button you will see the rendered version.

**Comment by charris** [comment]
Thanks @jarrodmillman . I note that this doesn't render that well on Linux with Firefox, but it looks good on Chrome and Brave.

**Pull request merged**
