### PR TITLE
MAINT: lib: Some code clean up in loadtxt

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
This is a maintenance-only PR, in preparation for some bug fixes and enhancements.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
I was tempted to move the nested functions `flatten_dtype_internal` and `pack_items` out of the `loadtxt` definition, and make them private functions at the top level of the module. Having them nested in `loadtxt` is unnecessary.  They are standalone functions, with no need to be exposed to the scope of `loadtxt`.  If anyone agrees such a change is worthwhile, I'll can add it to this PR.

**Review by eric-wieser — APPROVED** [review]
Looks good, thanks for splitting into separate commits too!

**Comment by WarrenWeckesser** [comment]
The one failure on TravisCI is the s390x platform, where the log has
just one line:

    An error occurred while generating the build script.

**Comment by mattip** [comment]
Thanks @WarrenWeckesser

**Pull request merged**
