### PR TITLE
TST: Enable doctests in IO Howto with testsetup and testcleanup

### LINKED ISSUE #17516: DOC: TST: ENH: Add doctests to I/O how-to
The [I/O how-to](https://numpy.org/devdocs/user/how-to-io.html) skips doctests because it reads fictitious files. These files should be created (dynamically or in advance) so doctests can be enabled.

### PR DESCRIPTION
**Pull request by bsipocz**
This is to close https://github.com/numpy/numpy/issues/17516

The PR adds the usage of `testsetup` and `testcleanup` directives to create the files the examples are using. 
This approach may cause issues if the tests are run in a system where no write permission is present, which presumably can be worked around with proper tempfiles, however these doctests live in the narrative docs, and I don't think anyone would test those without permission to the source directories.

The one example where I couldn't remove the `doctest: +SKIP` is the `skip.txt` case, as for that we would need a directive that lets us ignore warnings, and afaik that is not available in standard doctest (here is the one I know about: https://github.com/astropy/pytest-doctestplus/#ignoring-warnings)

Disclaimer: I'm not sure where the fixes to the headings are coming from, and haven't investigated as they are indeed fixes that work and more consistent with the standard formatting. If needed, I can manually revert them.

### CODE REVIEW

**Comment by charris** [comment]
LGTM. I'll let one of the doc folks put this in.

**Review by rossbar — COMMENTED** [review]
Alternatively we could use a file-like such as `io.StringIO` for this and define the "file" directly in the relevant example - this has the advantage of keeping the data close the example, at the expense of cluttering things up with `io`.

@bsipocz LMK what you think, otherwise I'm +1 for this as-is!

**Comment by bsipocz** [comment]
@rossbar - I don't have a strong preference, I feel both of these have their pro and cons. I think the current one is closer to the beginner user experience as it shows the whole process of what to do with an actual file, but it could clutter up if the setup and cleanup get out of sync with the code, or when tests start to fail. 
Using `io.StringIO` OTOH would provide nicer, self-contained, examples. 

So given that you better know the target audience for this doc page, please decide, and I'm happy to follow-up if needed.

**Comment by rossbar** [comment]
I vote for this approach then, thanks @bsipocz !

**Pull request merged**
