### PR TITLE
CI: pin scipy-doctest to 1.5.1

### LINKED ISSUE #28019: TST,DOC: Bump `scipy_doctest` (or remove pin) and fix new failures
@ev-br ping FYI,  since the new scipy-doctest release (less than an hour ago) the refcheck has universal failures.

I suspect, this is all just bad documentation that needs fixing, but not sure yet.  In either case, until fixed both CircleCI and the "benchmark" tests which also still run the refcheck are expected to fail.

(Currently, also the linter just started failing...)

### PR DESCRIPTION
**Pull request by mattip**
Fixes #28019

### CODE REVIEW

**Comment by mattip** [comment]
Should we remove the doctest run from benchmarking? There was a reason we added it there but I can't remember it...

**Comment by seberg** [comment]
> Should we remove the doctest run from benchmarking? There was a reason we added it there but I can't remember it...

It adds a second architecture to it, but I am not sure that was the reason.  So yeah, I am seems OK to remove it (or rename for clarity).

**Review by seberg — APPROVED** [review]
LGTM, once tests pass.  No opinion about hypothesis, but it does update very often and I think it has caused flaky tests before.

**Comment by charris** [comment]
I'd like a pin in the `maintenance/2.2.x` branch as I don't want to deal with lots of doc fixes during its lifetime.

**Comment by charris** [comment]
I'm not worried about the lint failures, they are an artifact of recent updates and I expect they will get fixed in the near future.

**Comment by seberg** [comment]
Good point, for maintenance I think the hypothesis pin also makes sense definitely.

Yes, we still should clean out these failures ASAP anyway, but let's put it in for now.  Thanks Matti!

**Pull request merged**
