### PR TITLE
MAINT: Replace integers in places where booleans are expected

### PR DESCRIPTION
**Pull request by MSeifert04**
Personally I don't like non-booleans where booleans are expected. However it's also creating more code, so I'm not sure if it's actually an improvement.

I paid attention to the places which might behave different depending on the actual type instead of just the boolean representation but I cannot guarantee that a mistake might have slipped through.

### CODE REVIEW

**Comment by seberg** [comment]
Not quite sure about the test changes being necessary, is there some reason (i.e. it trips up LGTM?). What do others think? They also do not hurt, though.

**Comment by MSeifert04** [comment]
@seberg I wouldn't mind undoing the test-changes again. I wasn't sure neither. Just let me know.

**Comment by MSeifert04** [comment]
> is there some reason (i.e. it trips up LGTM?).

No explicit reason, I just had a look at the MaskedArray code and encountered a place where `make_mask` was an integer - which seemed odd. After that I decided to run a linter against type-mismatches and encountered a few other places and changed all I thought were low-hanging-fruit.

I hope this isn't inappropriate.

**Comment by seberg** [comment]
I honestly do not care much either way, it is an improvement (this usage is mostly historically, maybe due to the fact that some ancient Python did not have bools). The change look all good.

**Review by eric-wieser — APPROVED** [review]

**Comment by charris** [comment]
Thanks @MSeifert04 . I see this as part of ongoing maintenance aimed a modernizing NumPy.

**Pull request merged**
