### PR TITLE
DOC: Add "performance" category to the release notes

### PR DESCRIPTION
**Pull request by seberg**
@charris looking at it, the "changes" section is pretty much unused, and the "improvements" is not super busy. But performance may still be good as its own category.

Opened for discussion, but should be fine to just merge.

### CODE REVIEW

**Comment by charris** [comment]
Hmm, another segmentation fault in fft. These problems seem to have come in with using github actions.

**Comment by mattip** [comment]
It seems you retriggered the build on azure? So that would rule out github actions

**Comment by seberg** [comment]
@mattip I pushed a typo fix after the failure had occurred.

**Comment by charris** [comment]
Thanks Sebastian.

**Pull request merged**
