### PR TITLE
BLD: Add clang `-ftrapping-math` also for `compiler_so`

### LINKED ISSUE #19427: (distutils) The `-ffp-exception-behavior=strict` setting does not actually work (reliably)
See also https://github.com/numpy/numpy/issues/19049#issuecomment-875843493 and the followup comments.

Clang (since 10 or 11, the documentation and release notes disagree), has the `-ffp-exception-behavior=strict` which we should be using (since we care about floating point error flags).

However, it seems that the monkeypatching maze in `numpy.distutils` ends up not using the option as modified in gh-19049.

### PR DESCRIPTION
**Pull request by seberg**
Apparently, there is a second `compiler_so` that is actually the
main compiler being used, and modifying only the first one is just
futile.

Closes gh-19427 in theory.  In practice, I somewhat expect that clang only decided that warning flags are worth any consideration so recently, that this will just break old clang versions

---

I have tested that this works: gh-19476 passes with this.  What is the minimum clang version we actually support? I expect this needs at least version 10 (which is fairly new), but I can't compile locally on version 9.  (I guess the CI run will tell me that this won't actually work :/)

### CODE REVIEW

**Comment by seberg** [comment]
I somewhat expected this would fail, but I don't understand it.  The mac CI build uses Clang 11.0.0, my local build uses `Debian clang version 11.0.1-2`, which doesn't really sound like `11.0.0` should reject a flag that my version is happy to accept.

**Comment by seberg** [comment]
I also confirmed that it does indeed fix gh-18005 for my clang version, so changing that comment.

I expect the `-ftrapping-math` will now work correctly (and the docs mention that flag at least for clang 5.0 – that is the furthest back I checked)

**Comment by seberg** [comment]
So for those checking this: https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffp-exception-behavior explains that `-ffp-excetion-behaviour=strict` should be good for us while: https://clang.llvm.org/docs/UsersManual.html#cmdoption-fdenormal-fp-math (go slightly lower, the anchor is missing), says:
> Control floating point exception behavior. -fno-trapping-math allows optimizations that assume that floating point operations cannot generate traps such as divide-by-zero, overflow and underflow.

and

> The option -ftrapping-math behaves identically to -ffp-exception-behavior=strict.

---

I think the main question is basically the old question:  Is modifying `self.compiler` and `self.compiler_so` reasonable?  The `self.compiler_so` does work and gets used.

**Comment by mattip** [comment]
I think we should put this PR in. @charris, thoughts?

> Is modifying self.compiler and self.compiler_so reasonable? The self.compiler_so does work and gets used.

Well, this PR does not add a new modification, it fixes the current one.

**Comment by charris** [comment]
I don't have a problem putting this in. What is the question about 1.21.x release notes?

**Comment by seberg** [comment]
@charris my question was whether we should do something about them being incorrect?

**Comment by charris** [comment]
> my question was whether we should do something about them being incorrect?

I tend to regard release notes as history, flaws and all, after the release. We could backport this change if you wish and mention that in a later release note.

**Comment by seberg** [comment]
OK, sounds good.  I am hesitant about backporting, since I have no idea if this may have side-effects for some.

**Comment by mattip** [comment]
Thanks @seberg

**Comment by davidghiurco** [comment]
I've been trying to triage `numpy>=1.22.0` backwards-breaking ABI changes when using libraries compiled(cythonized) against 1.22.x on a platform with `numpy==1.21.x`

When I do that, I get: `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

Is #19479 what caused this breaking ABI change?

**Comment by seberg** [comment]
> when using libraries compiled(cythonized) against 1.22.x on a platform with numpy==1.21.x

There is no break, NumPy API and ABI is fully *forward* compatible.  You have to compile against the oldest NumPy version you support.  There is https://pypi.org/project/oldest-supported-numpy/ to help with that.

**Pull request merged**
