### PR TITLE
TST: Fix endianness in unstuctured_to_structured test

### PR DESCRIPTION
**Pull request by ahaldane**
Fixes one of the three failing SPARC tests in #12638.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Weird that these `<` were inserted in the first place. In any case, the fix is logical and looks good.

**Comment by ahaldane** [comment]
I wrote that test not too long ago :)  Probably it was a cut-n-paste mistake.

**Comment by charris** [comment]
The azure failure was the same sporadic InvalidValue error we have seen before on Python 3.7. I think something has changed in error suppression and is comes from elsewhere than the test in which it appears.

**Comment by charris** [comment]
I may kick these fixes off to 1.16.1, but this one looks pretty safe.

**Comment by charris** [comment]
Thanks Allan.

**Comment by DerDakon** [comment]
I'm running a test with this on sparc, but it will take a while.

**Comment by ahaldane** [comment]
Incidentally, I ran the test suite for the `maintenance/1.16.x` branch on ppc64be, with and without `USE_DEBUG`.

Without USE_DEBUG, this is the only test that fails. 

With USE_DEBUG, I am getting uint alignment issues like in  #12626. I'm investigating.

**Comment by DerDakon** [comment]
Seems to help.

**Pull request merged**
