### PR TITLE
MAINT: fix typo in f2c_lapack.c

### PR DESCRIPTION
**Pull request by eltociear**
inifinity -> infinity

### CODE REVIEW

**Review by HaoZeke — APPROVED** [review]
LGTM. Thanks

**Comment by charris** [comment]
@HaoZeke The files in `lapack_lite` are generated, there is no point in correcting spelling errors in them. We have already skipped PRs that do so.

**Comment by eric-wieser** [comment]
In fact we should probably revert this change to avoid confusion if f2c_lapack is ever regenerated

**Comment by HaoZeke** [comment]
Sorry about that, should have read the header.

**Comment by WarrenWeckesser** [comment]
FYI: The misspelling is still in reference LAPACK:

[`*>          Specifies whether to test just for inifinity arithmetic`](https://github.com/Reference-LAPACK/lapack/blob/77a0ceb6c9a3c757e7039027f1f324e2811e6ee0/SRC/ieeeck.f#L44)

**Pull request merged**
