### PR TITLE
ENH: Avoid re-encapsulation of the default handler

### PR DESCRIPTION
**Pull request by eliaskoromilas**
The default handler is now capsuled once (singleton), which makes testing for object identity, using `==` in C, or `is` in Python sufficient.

https://github.com/numpy/numpy/issues/20193 and https://github.com/numpy/numpy/pull/20343 discussions imply that `PyDataMem_Handler.name` should not be used to encode information neither to suggest allocator uniqueness, so this will allow user libraries to tell if a 'default_allocator' **is** the 'default_allocator'.

The question is whether it would make more sense to also export that capsule in the NumPy API (e.g. like `Py_None` singleton).

### CODE REVIEW

**Comment by eliaskoromilas** [comment]
@mattip @seberg What do you think?

**Comment by seberg** [comment]
Seems reasonable to me.  Do we expect users to test identity?  Because if not, we could just not make this a public symbol, but I don't really care either way.

**Comment by eliaskoromilas** [comment]
> Do we expect users to test identity?

Define users :). My points in favor of exporting it publicly are:

* There is already a way to get (a borrowed reference to) it, but can be considered an overkill:
    ```c
    PyObject *handler = PyDataMem_SetHandler(NULL);
    PyObject *default_handler = PyDataMem_SetHandler(handler);
    Py_XDECREF(handler);
    Py_XDECREF(default_handler);
    ```
* Maybe in the future NumPy could offer more than one native allocator (e.g. pooled/unpooled versions). `PyDataMem_SetHandler(NULL)` will always set the default one but still all the available options should be accessible by the users. For example:
    ```c
    Py_XDECREF(PyDataMem_SetHandler(NULL)); // sets the default allocator
    Py_XDECREF(PyDataMem_SetHandler(PyDataMem_ArenaAllocator)); // sets the arena allocator
    Py_XDECREF(PyDataMem_SetHandler(PyDataMem_DefaultAllocator)); // sets the default allocator (for API consistency)
    ```
* It could enable a feature in the NumPy Allocator project, roughly equivalent to this:
    ```python
    import numpy
    import numpy_allocator
    
    class default_allocator(metaclass=numpy_allocator.type):
        _handler_ = numpy_allocator.default_handler()
    
    with another_allcoator:
        # do stuff
        with default_allocator:
            test = numpy.ndarray(())
    assert default_allocator.handles(test)
    ```

**Comment by seberg** [comment]
Good, any reason is enough of a reason for me in this case ;).

**Comment by seberg** [comment]
@mattip, if you like this, lets put it in for 1.22?

**Comment by mattip** [comment]
LGTM, thanks. It simplifies things a bit, at the cost of another exported API value

**Pull request merged**
