### PR TITLE
TST: Run test_large_zip in a child process

### PR DESCRIPTION
**Pull request by anirudh2290**
1. Moved the test to its child process as per discussion on https://github.com/numpy/numpy/issues/15775 . 
2. Removed the skip for pypy

@mattip

### CODE REVIEW

**Comment by mattip** [comment]
Could you temporarily remove the `@slow` mark from the test so it runs on all platforms, just to make sure it passes? Otherwise we could miss that it could be failing

**Comment by anirudh2290** [comment]
Looks like there is some download step on windows failing. Is there a way to retrigger the CI manually or do I need to push an empty commit ?

**Comment by mattip** [comment]
> Looks like there is some download step on windows failing.

The goal of 2da3d4f was to check that PyPy passes the new format of the test, which it does. So if you can revert that commit I think this is ready. It would be nice to add a comment to the effect of "run in a subprocess to ensure memory is released on PyPy"

Looking at [the log for PyPy]((https://dev.azure.com/numpy/numpy/_build/results?buildId=8959&view=logs&j=cb7817a0-aed9-5b1b-ffdb-285e933f569f&t=713c0b5c-565d-5b6b-cd58-66e4f64bd786&l=3709)), there are some tests that could be marked `slow_pypy` if we had such a mark. But that is too much for this PR.

**Comment by anirudh2290** [comment]
> Looking at the log for PyPy, there are some tests that could be marked slow_pypy if we had such a mark. But that is too much for this PR.

Good point! I can take a look at this and open another PR. I am wondering if we need to change the required memory to probably 8 or 9 GB for this particular test, maybe we can monitor this for a few CI runs and change if required.

**Comment by mattip** [comment]
Thanks @anirudh2290

**Pull request merged**
