### PR TITLE
CI: Test NumPy build against old versions of GCC(6, 7, 8)

### LINKED ISSUE #21920: BUG: Build of numpy 1.23.0 fails on debian-stretch
### Describe the issue:

On `debian-stretch` (gcc-6_6.3.0-18+deb9u1_amd64), building numpy 1.23.0 from source fails, see details in https://trac.sagemath.org/ticket/34110#comment:4
This is a regression from numpy 1.22.4.

### Reproduce the code example:

```python
pip install .
```

### Error message:

_No response_

### NumPy/Python version information:

1.23.0

### PR DESCRIPTION
**Pull request by seiko2plus**
closes #21920

### CODE REVIEW

**Comment by charris** [comment]
@rgommers What is the oldest gcc SciPy is going to support?

**Comment by rgommers** [comment]
> @rgommers What is the oldest gcc SciPy is going to support?

We bumped it from GCC 4.9 to GCC 8 for the next release: https://github.com/scipy/scipy/blob/0fc5126bf0cfd7d0f46c845003e0c52094d4019b/meson.build#L27-L37

The change in this PR is consistent with what we discussed in the developer meeting. From [the meeting notes](https://github.com/numpy/archive/blob/main/other_meetings/2022-07-12-SciPy2022_Team_Summit.md): _GCC versions: we need to test with a wider range of compilers, and drop older compilers. Sayed would like GCC 9, that’s stable for AVX512/SkylakeX features. Also influenced by C++ code. We need C99 and C++11. Proposal: minimum version gcc 6.3 and error out if the compiler is older._

I think GCC 8 would be fine, but doing 6.3 now and waiting if there's major complaints for SciPy before following suit is also fine.

**Comment by rgommers** [comment]
> but doing 6.3 now and waiting if there's major complaints for SciPy before following suit is also fine.

Given that what we get from Ubuntu is 6.5, let's make that the documented minimum version. I added a commit that updates the docs in two places to state this.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @seiko2plus! 

This should be backported to 1.23.3, and it would be good to add it to those release notes.

**Comment by charris** [comment]
Thanks @seiko2plus .

**Pull request merged**
