### PR TITLE
DOC: Add missing methods to numpy.strings docs

### PR DESCRIPTION
**Pull request by lithomas1**
Hopefully I'm not missing anything else.

I think I've got everything under ``dir(np.strings)`` that's public (not prefixed with _)

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Thank you for catching that we missed updating the docs!!

**Review by ngoldbaum — APPROVED** [review]
LGTM. @lysnikolaou it occurs to me reading over this list that it's a bit weird we expose `np.strings.mod` (for example) but not `np.strings.split`. Do we maybe want to reconsider exposing everything in `np.char` in `np.strings` for consistencies' sake? Or alternatively only exposing things we have fast ufunc implementations for. I'd slightly prefer the former, so people can more easily switch and benefit from fast implementations we add in the future.

Also note that this might be annoying to backport manually, since some of these functions are first available in numpy 2.1.

**Comment by lysnikolaou** [comment]
My thought process was that `np.strings` should only contain the functions whose behavior will remain the same for the forseeable future. This didn't include `join`, `split`, `rsplit` and `splitlines` at the time, since we hadn't figured out what we wanted to do with those.

I agree with the argument for consistency, so let's just add the slow versions of these to `np.strings` as well.

**Comment by ngoldbaum** [comment]
OK, let's pull this in to fix the docs and we can follow up with that. Thanks @lithomas1!

**Pull request merged**
