### PR TITLE
Fix ATLAS version detection

### PR DESCRIPTION
**Pull request by llasram**
ATLAS version detection still depends on the deprecated-and-removed `get_output` method.  Restoring this function seems to be the easiest short-term fix.

In more detail: within `numpy.distutils`, the [`system_info.get_atlas_version()`](https://github.com/numpy/numpy/blob/9dc9a00fdca195e06477d2c7dbd79850e9d4e107/numpy/distutils/system_info.py#L1420) function is still implemented in terms of the `config.config.get_output()` method removed in release 1.10.0.  The `get_atlas_version()` function is written in such a way that it swallows the unexpected `AttributeError` (or any other exception). When ATLAS is the selected BLAS implementation, this causes e.g. the `get_info('blas_opt')['define_macros']` list to include `('NO_ATLAS_INFO', -1)`.  It is unclear what this is intended to mean, and at least scikit-learn checks only for the presence of `NO_ATLAS_INFO` and not the associated value, as seen in scikit-learn/scikit-learn#5489.

Obviously longer-term `numpy.distutils` should switch to a more appropriate mechanism for identifying the ATLAS version, but restoring `get_output()` gets the existing detection function working until it can be re-implemented.

### CODE REVIEW

**Comment by charris** [comment]
Could you expand on what the problem is?

**Comment by llasram** [comment]
@charris Sure thing!  I updated the main PR description with more details.

**Comment by rgommers** [comment]
Makes sense to me to revert the removal of ``get_output``. May as well merge this, backport to 1.11.2, and then make a new issue for a better fix (which isn't super high prio imho).

**Comment by charris** [comment]
@rgommers Thanks for taking a look.

**Comment by charris** [comment]
@llasram Thanks.

**Comment by charris** [comment]
Backported in #7851.

**Pull request merged**
