### PR TITLE
ENH,BUG: Handle includes for meson backend

### LINKED ISSUE #25344: BUG: f2py (3.12) with meson does not support correct include file
### Describe the issue:

When running f2py with python3.12 (so using meson). I do face the following issue:
```
gfortran -Iuntitled.cpython-312-darwin.so.p -I. -I.. -I/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/src -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -Wall -O3 -Juntitled.cpython-312-darwin.so.p -o untitled.cpython-312-darwin.so.p/matrix.f.o -c ../matrix.f
../matrix.f:324:0:

  324 |       include 'coupl.inc'
      |
Fatal Error: Cannot open included file ‘coupl.inc’
compilation terminated.
```

The reason is not the trivial one (I do have such file in the local directory) but the fact that such file is not copy to the meson build directory. Additionally any attempt to provide a path to a directory where such file exists fails 
(either by specifying --include-paths or -I or even the outdated --include_paths). To be precise the failing compilation line is not updated correctly by any of those options.

### Reproduce the code example:

```python
C
      SUBROUTINE DFILTER2D(A,B,M,N)
C
       INCLUDE 'AB.inc' # put the following line inside that file
C      DOUBLE PRECISION A(M,N)
C      DOUBLE PRECISION B(M,N)
      INTEGER N, M
CF2PY INTENT(OUT) :: B
CF2PY INTENT(HIDE) :: N
CF2PY INTENT(HIDE) :: M
      DO 20 I = 2,M-1
         DO 40 J = 2,N-1
            B(I,J) = A(I,J) +
     &           (A(I-1,J)+A(I+1,J) +
     &           A(I,J-1)+A(I,J+1) )*0.5D0 +
     &           (A(I-1,J-1) + A(I-1,J+1) +
     &           A(I+1,J-1) + A(I+1,J+1))*0.25D0
 40      CONTINUE
 20   CONTINUE
      END
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/f2py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 732, in main
    run_compile()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 705, in run_compile
    builder.compile()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 131, in compile
    self.run_meson(self.build_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 124, in run_meson
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['meson', 'compile', '-C', 'bbdir']' returned non-zero exit status 1.
```

### Python and NumPy Versions:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.2
3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]

### Runtime Environment:

[{'numpy_version': '1.26.2',
  'python': '3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 '
            '(clang-1300.0.29.30)]',
  'uname': uname_result(system='Darwin', node='mac-1q0-072.local', release='22.1.0', version='Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'armv8',
  'filepath': '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None

### Context for the issue:

This is a blocker for supporting python3.12 for the moment so not directly critical.

### PR DESCRIPTION
**Pull request by charris**
Backport of #25364.

Closes #25344. Supersedes #25345. ~~Tests need to be reworked to use `option` correctly. Draft till then.~~

@oliviermattelaer could you check if this also works for you?

For reviewers:
- Implements `includes` in the `meson` backend in a manner consistent with the `-L -l` handling since https://github.com/numpy/numpy/pull/25297.
- Unifies the disparately handled `--include-paths` `--include_paths` and `-I` to do the "right thing" (which is also now thankfully the same thing)
  - Previously, the code would diverge since `-I` would be a "compiler" option and the others were not, now they all generate the same code

### CODE REVIEW

**Comment by charris** [comment]
@HaoZeke Any idea why that test fails when built with distutils? It passes with meson. The error message is
```
                                  vars2fortran: No typespec for argument "m".
E                                  			Block: add
E                                  In: 
```
Apparently the include doesn't work.

**Comment by HaoZeke** [comment]
> @HaoZeke Any idea why that test fails when built with distutils? It passes with meson. The error message is
> 
> ```
>                                   vars2fortran: No typespec for argument "m".
> E                                  			Block: add
> E                                  In: 
> ```
> 
> Apparently the include doesn't work.

Yup, so the `meson` backend in `-c` goes through the same code-path without `-c`, but `distutils` has two separate argument parsers and code-paths for the case with and without `-c`.

Basically in `distutils` there's `--include-paths` and `--include_paths` (which includes the file), `-I` (which includes the file if passed the same directory as the file). `-I` works only if `-c` is passed. With `meson` and this PR they are all the same now (but only for the `meson` backend).

I would prefer skipping the test if `distutils` is used than bending the `distutils` code-paths.

**Comment by HaoZeke** [comment]
Wait, sorry, didn't check the patchset. This should be fine with `distutils` too, will look into it.

**Comment by charris** [comment]
The current `f2py2e.py` here comes from main. I suspect the problem is in `get_includes`.

**Comment by HaoZeke** [comment]
> The current `f2py2e.py` here comes from main. I suspect the problem is in `get_includes`.

I think it has to do with the way the tests are constructed, running the example locally with `--backend distutils` works:

```f90
! incfile.f90
function add(n,m) result(b)
  implicit none
  include 'AB.inc'
  b = n + m
end function add
```

With `real(8) b, n, m` in `AB.inc` works fine:

```bash
❯ ls
AB.inc  blah.cpython-39-x86_64-linux-gnu.so  incfile.f90
❯ f2py -v
1.26.3
❯ f2py -c incfile.f90 --include-paths $(pwd) -m blah
...
❯ python -c "import blah; print(blah.add(3,4))"
7.0
```

Given that I'm restructuring the tests in #25252 it might be best to wait on that, but I will also see if there's a quick fix here.

**Comment by charris** [comment]
> but I will also see if there's a quick fix here.

Thanks. Going all meson is also an option at some point, but it might be easier to wait on 2.0.0.

**Comment by charris** [comment]
Leaving this fix for 2.0.0.

**Pull request closed without merging**
