### PR TITLE
MAINT: Fix sign-compare warnings in dragon4.c.

### PR DESCRIPTION
**Pull request by charris**

### CODE REVIEW

**Comment by charris** [comment]
@ahaldane ping.

By and large, I think `npy_int32` could simply be replaced everywhere with `int` with a gain in simplicity. Likewise `npy_bool` and `sign_bit`. The `buffersize` could also be passed as `int` as long as it is checked for size somewhere. Note that signed is freely converted to unsigned by C without warning, but generally that is OK. Another thing, which I don't thing matters here, is that `char` may be either signed or unsigned and that the encoding is assumed to be ascii.

**Comment by ahaldane** [comment]
Looks good and correct.

I checked the original C++ code, and it looks like it uses all these uints too, but I agree they should/can be ints instead. I agree we can make buffersize signed. There are two types of lines that do char arithmetic, which are `*curDigit = (char)('0' + outputDigit);` and `*curDigit += 1;`, but I don't think signedness matters in either since those only deal with the values '0' to '9'.

I have not considered the possibility that the encoding is not ascii. But since the only char values I ever use are `0-9 +.-\0`, and these are part of the C "basic character set", I think it we are fine.

The use of `npy_int32` instead of `int` also comes from the original c++ code, but I agree it can be changed. I think this was just a convenience since it had typedef'd lots of shorthand type names like `tU32`, `tS32` `tC8` and so on. But there are at least a few places it makes sense to me to keep `npy_int32`, since there is some bit-twiddling / union unpacking going on.

**Comment by ahaldane** [comment]
LGTM, ready to merge?

**Comment by charris** [comment]
@ahaldane I'll leave this to you in case it conflicts with your own work.

**Comment by ahaldane** [comment]
It's no problem, I'll merge. Thanks Chuck!

**Pull request merged**
