### PR TITLE
DOC: add sphinx-copybutton

### PR DESCRIPTION
**Pull request by mosc9575**
This PR adds the `sphinx-copybutton` to the docs.

numpy_copybutton

 - [x] fixes https://github.com/numpy/numpy/issues/26948

### CODE REVIEW

**Review by melissawm — APPROVED** [review]
This looks good to me - although the option for the prompt text is to select code after the `>>>` carets, this does not prevent other code blocks from being copied, for example the first code block here can be copied normally: https://output.circle-artifacts.com/output/job/eb36ceb6-c99c-4895-95bb-707b17b02123/artifacts/0/doc/build/html/user/quickstart.html#the-basics

**Comment by mosc9575** [comment]
This is wanted, see [strip and configure input prompts for code cells](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells).

> When the `copybutton_prompt_text` variable is set, `sphinx-copybutton` will remove the prompt from the beginning of any lines that start with the text you specify. In addition, only the lines that contain prompts will be copied if any are discovered. If no lines with prompts are found, then the full contents of the cell will be copied.

And this is useful, for example in the installation guide you can copy the conda and pip statements.

**Comment by melissawm** [comment]
Oh yes, sorry I wasn't clear, that's what I meant - I was worried this would prevent other cells from being copied. Looks good to me!

**Comment by mattip** [comment]
Thanks @mosc9575

**Pull request merged**
