### PR TITLE
Make windows installers quiet,  issue #572

### PR DESCRIPTION
**Pull request by mathijs-dumon**
The possibility for a silent numpy and/or scipy installer has been requested a number of times.
I have made a number of changes that should enable this, please review this. I'm not familiar with compiling numpy, so this is untested!

The basic idea is to create MSI installers instead of exe's. Then we can use msiexec and pass it a silent flag if the NSIS installer was passed a silent flag. This can be achieved using the NSIS 'IfSilent' directive.

### CODE REVIEW

**Comment by charris** [comment]
@mathijs-dumon @rgommers @juliantaylor I'm tempted to close this. Is the Wine failure important? Is there another way to get the same result?

**Comment by mathijs-dumon** [comment]
Well, I mostly wanted this for my own project, but have resorted to manually unpacking the three versions and using a python script to detect the capabilities of the user's PC and select the correct version. It works, but I would have rather had a way supported by the project.

So you may close this, I have no idea why this doesn't work under wine or how to solve it anyway, and I don't have enough time to figure it out anytime soon.

**Comment by matthew-brett** [comment]
If we get the new OpenBLAS / mingw-w64 binaries working then we won't have this problem any more because we won't need the separate installer step to choose different versions according to the CPU, because OpenBLAS detects the CPU at run-time.

**Comment by rgommers** [comment]
It feels like a shame to close this, because a silent installer is nice to have. However, I don't really have the time to dig into Wine issues......

**Comment by charris** [comment]
OK, closing this. It can be found with a search after if someone wants to open it again.

**Comment by rgommers** [comment]
@mathijs-dumon thanks for the effort! I hope this'll still make it in somehow in the future

**Pull request closed without merging**
