### PR TITLE
BUG: fix np.save issue with python 2.7.5

### LINKED ISSUE #10348: numpy.save broken in 1.14 with python 2.7.5
The following minimal example crashes with numpy 1.14 and python 2.7.5:

```
import numpy
a = numpy.zeros(64)
numpy.save("/tmp/a.npy", a)
```

```
lib/python2.7/site-packages/numpy/lib/format.pyc in _write_array_header(fp, d, version)
    306     header.append("}")
    307     header = "".join(header)
--> 308     header = asbytes(_filter_header(header))
    309 
    310     hlen = len(header) + 1 # 1 for newline

lib/python2.7/site-packages/numpy/lib/format.pyc in _filter_header(s)
    465             tokens.append(token)
    466         last_token_was_number = (token_type == tokenize.NUMBER)
--> 467     return tokenize.untokenize(tokens)
    468 
    469

/usr/lib64/python2.7/tokenize.pyc in untokenize(iterable)
    260     """
    261     ut = Untokenizer()
--> 262     return ut.untokenize(iterable)
    263 
    264 def generate_tokens(readline):

/usr/lib64/python2.7/tokenize.pyc in untokenize(self, iterable)
    196                 break
    197             tok_type, token, start, end, line = t
--> 198             self.add_whitespace(start)
    199             self.tokens.append(token)
    200             self.prev_row, self.prev_col = end

/usr/lib64/python2.7/tokenize.pyc in add_whitespace(self, start)
    185     def add_whitespace(self, start):
    186         row, col = start
--> 187         assert row <= self.prev_row
    188         col_offset = col - self.prev_col
    189         if col_offset:

AssertionError:
```

The tokenize is now performed before the padding and the newline is added to the header string. This does not seem to work in python 2.7. Adding the newline in _filter_header(s) fixes the problem for python 2.7, but does not work in python 3. This could be done in the version distinguishing part of _filter_header(s). I am not familiar with the numpy internals and the recent change for the 64 byte alignment (https://github.com/numpy/numpy/pull/9025), so I do not feel comfortable to change it myself.

### PR DESCRIPTION
**Pull request by pnbat**
Workaround for the tokenizer issue with python 2.7.5. Closes #10348.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you elaborate on the read &rarr; headline change?

**Comment by charris** [comment]
@eric-wieser 
>tokenize.generate_tokens(readline)
The generate_tokens() generator requires one argument, readline, which must be a callable object which provides the same interface as the readline() method of built-in file objects (see section File Objects). Each call to the function should return one line of input as a string. Alternately, readline may be a callable object that signals completion by raising StopIteration.

**Comment by charris** [comment]
I think this is OK. Thanks @pnbat .

**Comment by pnbat** [comment]
Maybe changing to readline would have been sufficient. I could elaborate on that during the refactorings...
I also hope that the unit tests are tight :)

**Comment by charris** [comment]
@pnbat The thought crossed my mind, but after looking at the Python fix I thought probably not. Be interesting to see if that is the case though.

**Pull request merged**
