### PR TITLE
DOC: Remove outdated versionadded directives for polynomial module

### PR DESCRIPTION
**Pull request by anishkargaonkar**
Remove outdated `versionadded` directives for the polynomial module https://github.com/numpy/numpy/issues/27239

### CODE REVIEW

**Comment by charris** [comment]
Needs rebase. I think most of the removals were done by #27454.

**Comment by anishkargaonkar** [comment]
@charris I agree, closing the PR 👍

**Comment by seberg** [comment]
Thanks @anishkargaonkar. That PR was a bit unfortunately broad (since I had hoped using this for a few PRs).  Hope you enjoyed the sprint anyway!

**Comment by anishkargaonkar** [comment]
No worries at all! @seberg Thanks a bunch for helping me get started. It was really fun. Cheers!

**Pull request closed without merging**
