### PR TITLE
CI: CircleCI: Install numpy after processing doc_requirements.txt

### LINKED ISSUE #20390: CircleCI test failures on main branch.
It fails because of a git version mismatch. CircleCI builds the correct Python3.8 wheel version, but that the installed version that Makefile sees is of the HEAD of the 1.21.x branch. Maybe the Makefile is using Python3.7? If so, I don't know why this is suddenly a problem.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Closes gh-20390.

### CODE REVIEW

**Comment by seberg** [comment]
Aha, CircleCI passed :tada:, no point in delaying: putting it in.  Thanks for the quick fix!

**Comment by WarrenWeckesser** [comment]
CircleCI completed successfully.  From the CircleCI log of the "build numpy" step:
```
[...]
Successfully built numpy
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.4
    Uninstalling numpy-1.21.4:
      Successfully uninstalled numpy-1.21.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.7.2 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.23.0.dev0+4.g4119d2823 which is incompatible.
Successfully installed numpy-1.23.0.dev0+4.g4119d2823

CircleCI received exit code 0
```
So pip does the installation, but let's us know that there is a conflict.  That answers my [question in the previous PR](https://github.com/numpy/numpy/pull/20392#issuecomment-971578225).

**Comment by seberg** [comment]
Ah, sorry.  I guess maybe `--no-warn-conflicts`?  Does it matter, so long as it doesn't error out?

**Comment by WarrenWeckesser** [comment]
> The pip command to install numpy should also have --progress-bar=off like the other pip commands, to avoid that string of |/-\... in the log.

Nevermind, `--progress-bar=off` doesn't turn off the spinning bar.  So I'll skip creating a follow-up PR.

**Pull request merged**
