### PR TITLE
BUG: Quick and dirty fix for interp.

### LINKED ISSUE #6468: numpy.interp uses 'left' value even when x[0]==xp[0]
The following code should demonstrate that numpy.interp uses the padding value specified by the kwarg 'left' even when the 0th element of the x-values being interpolated onto is identical to the 0th element of the input x-values.  This problem arose when I upgraded to numpy version 1.10.1 from version 1.9

```
import numpy as np

x1 = np.arange(1.0, 10.0, 1.0)
y1 = np.power(x1,  2)
x2 = np.arange(1.0, 9.1, 0.5)

np.testing.assert_equal(x1[0],  x2[0])
np.testing.assert_equal(x1[-1],  x2[-1])

y2 = np.interp(x2, x1, y1, left=np.NaN, right=np.NaN)

print y2[0]
```

### PR DESCRIPTION
**Pull request by charris**
The original had incorrect comparisons involving <=, <, and also failed
when the number of data points was 2. This fixes the use of the
comparisons and uses linear search for fewer than 5 data points.

The whole routine needs a simplified rewrite, but this takes care of the
bug.

Closes #6468.

### CODE REVIEW

**Comment by njsmith** [comment]
Looks plausible at least on a quick skim. I'm not at all confident of my ability to reason out the correctness of this code from first principles, so I'm going to focus on the tests :-)

* can you reassure me that the new test passes on 1.9?
* I found the `size` variable name confusing, because I expected it to be used to create arrays with different numbers of elements.
* is there any reason to delete the old tests? They seem to be slightly different than the new ones (e.g. the old tests use an array with three elements and the new tests use an array with four)
* it would be good to drop in some of the test cases quoted in #6468 verbatim, to convince ourselves they're really fixed.
* the commit message mentions a problem with 2 element arrays specifically, but there aren't any tests for this? (#6468 has examples with 2 elements, so handling the previous bullet point should cover this as well.)

**Comment by charris** [comment]
I'll check for 1.9. If the tests fail, that is a bug in 1.9

> I found the size variable name confusing, because I expected it to be used to create arrays with different numbers of elements.

Well, that is what it does ;) The number of data points defining the sequence to be tested is determined by size.

> is there any reason to delete the old tests? They seem to be slightly different than the new ones (e.g. the old tests use an array with three elements and the new tests use an array with four)

The new tests use data arrays of sizes 1..9 and the four points checked are the end points and out of bounds points. When size == 1 the check reduces to the old version as size - 1 == 0. The old tests are covered and now redundant.

>it would be good to drop in some of the test cases quoted in #6468 verbatim, to convince ourselves they're really fixed.

Pointless, the case is covered.

> the commit message mentions a problem with 2 element arrays specifically, but there aren't any tests for this? (#6468 has examples with 2 elements, so handling the previous bullet point should cover this as well.)

Yes, the tests cover that case also.

**Comment by njsmith** [comment]
Oh, doh, I see, I got confused and mixed up `x` and `incpts`.

**Comment by njsmith** [comment]
OK, yeah, I'm convinced the test does cover both the old cases and the ones given in #6468, so +1 from me.

Not a blocker, but just to check while we're here: is the size=0 case well defined, and should we be testing it too?

**Comment by charris** [comment]
size == 0 should raise a `ValueError` and is already tested. New tests pass on 1.9.x.

**Comment by njsmith** [comment]
Thanks Chuck!

**Comment by charris** [comment]
Thanks for the quick review.

**Comment by jaimefrio** [comment]
If you really want to test all of the code paths, then you need to check that each endpoint value works properly when the previous interpolation value results in an index 0, 1, 2, less than 8, or more than 8 indices away. This is what I had written for a test:

```
def test_endpoints(self):
    # gh-6468
    # The implementation tries first with values close to the last
    # value, hence the seemingly identical tests
    xp = np.linspace(0, 100, 101)
    yp = np.linspace(0, 100, 101)
    # left endpoint, all 0s should be interpolated as 0, not -1
    x = np.empty((33,))
    x[::2] = 0
    x[1::2] = np.arange(16)
    y = np.interp(x, xp, yp, left=-1)
    assert_equal(x, y)
    # right endpoint, all 100s should be interpolated as 100, not -1
    x[1::2] = 100 - np.arange(16)
    x[::2] = 100
    y = np.interp(x, xp, yp, right=-1)
    assert_equal(x, y)
```

Not sure if this can be combined within your test, or added as a different test...

**Comment by charris** [comment]
@jaimefrio I think that should be covered with size == 9, as a search that returns 0 is followed by a search that should return 9, which is more than 8 removed, smaller sizes cover the < 8 case. As the `x` points are also searched for in reverse order, that should cover the branches for next search point >  or < guess.

**Pull request merged**
