### PR TITLE
DOC: update scipy.integrate recommendation

### PR DESCRIPTION
**Pull request by ghost**
Closes scipy/scipy#7965.

### CODE REVIEW

**Comment by xoviat** [comment]
Well, for some reason I cannot edit the initial post, but this PR changes the "recommendation for MATLAB users" to point to the newer API which actually better mirrors MATLAB's API. Since this is a trivial change, it should be okay to merge immediately unless there are other points that someone wants to discuss.

**Comment by charris** [comment]
Perhaps you didn't allow editing when you submitted the PR? There is a checkbox or button somewhere you should be able to find when making the submission ...

**Comment by charris** [comment]
You can also squash commits using `git rebase -i` followed by a force push `git push -f origin HEAD`.

**Comment by charris** [comment]
Thanks @xoviat .

**Pull request merged**
