### PR TITLE
BLD, TST: move linux jobs to github actions

### PR DESCRIPTION
**Pull request by mattip**
[azpipelines skip]

Let's move what we can off travis before we are blocked. We already build windows and macOSx on azure pipelines.

- drop all linux x86 jobs from travis
- rebuild them on github actions
- remove python 3.6
Once this runs we should carefully check that each special job is actually doing what it is supposed to.

### CODE REVIEW

**Comment by mattip** [comment]
TODO in subsequent PRs: 
- why do we run arm64 on shippable and travis?
- move PyPy to python 3.7 by reverting gh-17695  and adding the download/setup-virtual-env part of tools/pypy-test.sh to the workflow here

**Comment by mattip** [comment]
We could consider putting all our eggs in one basket (since azure pipelines and github are both running CI on top of the same infrastructure) and move the windows/macOSx builds to github actions as well.

**Comment by charris** [comment]
> We could consider putting all our eggs in one basket

Would we get as many parallel jobs?

**Comment by mattip** [comment]
> Would we get as many parallel jobs?

Maybe not.

**Comment by charris** [comment]
I'm happy to put this in as it stands. To you want to keep working on it here?

**Comment by mattip** [comment]
Let's put this in and see how it goes for a while before doing more. I looked at the non-standard builds, I think they are doing what they are supposed to: at least the benchmark and the coverage/full ones look OK.

**Comment by charris** [comment]
In it goes, Thanks Matti.

**Pull request merged**
