### PR TITLE
DOC: update and copy-edit 2.0.0 release notes

### PR DESCRIPTION
**Pull request by rgommers**
The complete copy-edit was a lot of work, so I left it at that and didn't try to also reorder sections or add highlights or other narrative content in this PR.

### CODE REVIEW

**Comment by mattip** [comment]
LGTM, it seems like all of the info has been transfered. This can be improved in subsequent PRs.

**Comment by mattip** [comment]
Thanks @rgommers

**Comment by mattip** [comment]
I forgot to check that the release notes actually appear. They are not appearing in the [rendered documents](https://numpy.org/devdocs/release/2.0.0-notes.html). Is towncrier deleting them?

**Comment by mattip** [comment]
Ahh, we can add a `.. towncrier release notes start` which will cause a header duplication but will not remove the existing content. See the previous iteration of this problem [in these comments](https://github.com/numpy/numpy/pull/25827#issuecomment-1945905263)

**Comment by rgommers** [comment]
Ah yes, will take that along in the next PR.

**Comment by rgommers** [comment]
Except it doesn't work. And when working around that, it seems there is no way to tell it to not stage things for committing (except for adding `--draft` and manually piping that into a new file). Will try a bit more and hook it into `spin docs` somehow, but this isn't quite general-purpose tooling.

**Pull request merged**
