### PR TITLE
MAINT: change circleCI keys

### PR DESCRIPTION
**Pull request by mattip**
Related to https://circleci.com/blog/january-4-2023-security-alert/. People without permissions should not be able to visit the links below, but I want to document what I did.
- Create new keys, delete the old ones from [the ssh keys section](https://app.circleci.com/settings/project/github/numpy/numpy/ssh) of the circleCI numpy/numpy configuration. Also delete "deploy key" that led to this repo numpy/numpy 
- Delete the keys from [the neps settings ](https://github.com/numpy/neps/settings/keys) and [the devdocs settings](https://github.com/numpy/devdocs/settings/keys) and add new public keys from the private keys in the first step
- Delete the deploy permissions for the key that was registered to numpy/numpy, I did not replace it. I think it was part of an older documentation deployment scheme.
- Change the key fingerprints in this PR

cc @tupui

### CODE REVIEW

**Comment by tupui** [comment]
Thanks Matti 👍

**Comment by seberg** [comment]
Is it weird that the devdoc's key was already used after being updated?  Since I would have thought its only usable with this change, and the PR itself shouldn't trigger a push?

**Review by seberg — APPROVED** [review]
Anyway, thanks for looking into this quickly.  LGTM, the above just puzzles me, but if it seems right please just merge.

**Comment by tupui** [comment]
From the config, it should use the key but not publish. Only the run command is guarded with a filter on the branch.

In SciPy I updated the config with a guard before that (at the job level). This is with the new format for the config.
```
workflows:
  version: 2
  default:
    jobs:
      ...
      - deploy:
          requires:
            - build_docs
          filters:
            branches:
              only: main
```

**Comment by seberg** [comment]
Ah, so the old key being accepted is maybe just a fluke that it was accepted a short time after being deleted.  And the key "being used" is expected.

**Comment by mattip** [comment]
It seems like the scipy configuration separates the build from the deploy step. We have a single step. In a subsequent PR someone could use the scipy one as a template for improving this one, but let's put this in now so the documents can be deployed.

**Comment by mattip** [comment]
I doubt any first-time committers will be likely to tackle CI.

**Comment by seberg** [comment]
OK, thanks.  Since the explanation makes sense, lets put this in, don't want to block pushing new docs from other PRs.

**Comment by tupui** [comment]
Alright alright on it 😉

**Pull request merged**
