### PR TITLE
DOC: Fix links for NEP 40 in NEP 41

### PR DESCRIPTION
**Pull request by anirudh2290**
Fixed the broken links for NEP 40 in NEP 41.

### CODE REVIEW

**Comment by seberg** [comment]
Thanks, same would go for NEP 40. However, both of these files have an `.. _NEP40:` tag at the top, which I would think means that I can use the shorter link version?! I thought sphinx would have complained louder about this. @rossbar maybe you know if there is a nicer way to link these?

**Review by rossbar — COMMENTED** [review]
The original syntax will (should) work if you get rid of the trailing underscore and add an explicit `:ref:` role in front: `` :ref:`NEP 40 <NEP40>` ``. Alternatively, you could just do `` :ref:`NEP40` ``, though that results in a significantly less concise link name :) [it will use the full title of the NEP 40 document].

I think the trailing underscore might limit it to looking for intra-document anchors, though I'm not entirely sure that's the reason the original syntax wasn't working.

**Comment by anirudh2290** [comment]
Thanks @rossbar for the suggestion. I have changed it to use :ref: .

**Comment by seberg** [comment]
If you check the circleci "nep build process", I think this fixed the issue, but there are two more:
```
/home/circleci/repo/doc/neps/nep-0041-improved-dtype-support.rst:32: WARNING: undefined label: data-type-objects-dtype (if the link has no caption the label must precede a section header)
/home/circleci/repo/doc/neps/nep-0041-improved-dtype-support.rst:229: WARNING: undefined label: https://en.wikipedia.org/wiki/bfloat16_floating-point_format (if the link has no caption the label must precede a section header)
```
maybe we can mop them up here as well? It may also make sense to add the `-n` to the sphinxoptions, it seems a bit like it is actually missing... That flag should make CI error if there are mistakes...

**Comment by seberg** [comment]
Fixed two more errors and squashed. Will merge once the tests pass, since this is trivial.

**Comment by seberg** [comment]
Thanks Anirudh and Ross.

**Comment by anirudh2290** [comment]
Thanks for the fixes here @seberg !

**Pull request merged**
