### PR TITLE
CI: reduce CI load - two fewer Azure Windows jobs, and no GHA jobs on merge

### PR DESCRIPTION
**Pull request by rgommers**
As discussed in the community meeting just now, we have a large CI matrix and some of it doesn't really add much. In the future we'd like to see about getting rid of Azure as much as possible, since it's the most cumbersome system to work with. For now, cull jobs that are not adding value.

### CODE REVIEW

**Comment by mattip** [comment]
Thanks removing the azure jobs makes sense.

> CI: stop GitHub Actions jobs from running on merge to main

Thinking out loud: this is safe because the merge model for github is to merge main into the branch before running CI, so running the job again on merge to main will run exactly the same code.

I guess that is true as long as the merge button is pressed relatively soon after the last CI run, which is generally the case. I can't remember merging an old PR without at least a close/open to re-run CI first.

**Comment by charris** [comment]
Changing the Python39-32bit test to full has discovered a test failure. I suspect that test should be skipped on 32 bit tests.

**Comment by mhvk** [comment]
Very much from the sidelines, but in case it helps: in `astropy`, we have a much smaller CI set, but do run elaborate tests, including on less usual architectures, on weekly cron. Our experience is that these bring up very few additional failures (usually just the numpy-dev ones :smiley_cat:), so give a good compromise between finding bugs fast enough while having fairly fast CI results on PRs (and not making the climate crisis even worse).

**Comment by rgommers** [comment]
> I guess that is true as long as the merge button is pressed relatively soon after the last CI run,

@mattip agreed with your "thinking out loud". Extra comment: even if this quoted bit is not true and the maintainer's assessment was incorrect, then it means `main` now contains a test failure. Either way that's a problem, needs to be fixed, and it's going to show up within hours. It's not really interesting whether that failure then occurs on both other PRs _and_ a separate CI run on `main`, or only on other PRs.

> Changing the Python39-32bit test to full has discovered a test failure. I suspect that test should be skipped on 32 bit tests.

Yes indeed. It's `TestIO.test_big_binary`. No idea why it doesn't full on the other configs, but not really that relevant either - will add a skip.

> so give a good compromise between finding bugs fast enough while having fairly fast CI results on PRs (and not making the climate crisis even worse).

Thanks for the input @mhvk, and I agree with both of these goals - also the climate crisis one! For NumPy I think we're in an opposite boat to AstroPy. PRs are much more often C code that can fail on a non-standard compiler/OS/hardware/etc. When trimming down on CI jobs, I'd much rather remove doing the same job six times, only varying Python version and bitness. And I think that on the other hand we need more jobs with compilers, OSes, BLAS libraries, very old or new hardware for SIMD instruction sets, etc.

Things that tend to fail in cron jobs are a little annoying, because only repo owners get emails for those. So they are the ones getting stuck with cleanup duty (case in point: the Gitpod job has been failing for a while, and I need to go fix it). So I'd rather not have cron jobs for configs that can have nontrivial failures for compilers or SIMD instructions for example.

This PR is about trimming down only, which is prio 1 I think. Once we move from distutils to meson completely, we need to do a larger restructure, and rationalize what we run. Also, we can have other wish list items, like labels that run jobs (extensive BLAS tests for linalg PRs only, extensive SIMD tests for SIMD PRs, etc.).

**Comment by seberg** [comment]
> Things that tend to fail in cron jobs are a little annoying, because only repo owners get emails for those.

Rethinking it, I suspect astropy auto opens issues for these.  I would have a few wishes for such an issue (auto-close, simple retriggering maybe list of PRs merged since previous run), but that seems fine (or even better).  Pushing things to not run in main will also occasionally mean the maintainers have to figure out and tell people their PR broke things (while confusing others because theirs are suddenly red).

Overall, the changes look fine though.

**Comment by rgommers** [comment]
Looking into `TestIO.test_big_binary` more, what is happening there is not great. We've been running this test that takes >1 min to run for 10 years without any failures, on any invocation of `numpy.test('full')` on Windows. The only tweak to it is to disable it when Python was built with Mingw seems incorrect (we need to check if Mingw is used to build NumPy, not Python), and right now the test is only failing because the test itself is not robust (it's leaking a file descriptor).

I think we can do two things:
1. Remove the test completely, just store it on the issue and add a comment in the relevant code ([this code block in `convert.c](https://github.com/numpy/numpy/blob/340b3ff2ea6fdfebcb43a83aa8799dffd77ab325/numpy/core/src/multiarray/convert.c#L159-L179)) that if it is touched, run that test on 64-bit Windows once.
2. Introduce an `xslow` decorator to achieve the same (test is never run unless you manually enable it)

I have a preference for (1). Thoughts?


> Pushing things to not run in main will also occasionally mean the maintainers have to figure out and tell people their PR broke things (while confusing others because theirs are suddenly red).

This is already the case, removing separate CI runs on `main` changes very little there.

> Rethinking it, I suspect astropy auto opens issues for these. I would have a few wishes for such an issue (auto-close, simple retriggering maybe list of PRs merged since previous run), but that seems fine (or even better). 

That does seem useful indeed when running tests in either cron jobs or on `main`. Not better probably, because it's post PR merge, so hard to get the PR submitter to do the work to fix it quickly. It does requires automation / bot work. If we do invest time in that, I think having label-based CI triggers is higher on our wish list.

**Comment by mhvk** [comment]
> having label-based CI triggers is higher on our wish list.
We do have that too -- e.g., `Extra CI` and `Build all wheels`. Obviously, feel free to copy the implementation (as we've done often from numpy!).

**Comment by mhvk** [comment]
p.s. Yes, optimizing for compiler, BLAS, etc., dependencies seems to make a lot of sense. Perhaps it is possible to trigger those extra ones only if C code is touched? (Or, maybe easier, anything but `.py ` and `.rst`?)

**Comment by seberg** [comment]
Either solution with the test seems fine, I don't like deleting it, but it is a weird one maybe.  Marking would make most sense if we basically have it as a `release` mark or so, i.e. tests that should run before a release (hopefully?), or maybe automatically every few weeks or when a new tag is created.

But we have none of such machinery currently, probably not super hard to create (or steal from astropy), but someone needs to spend some more significant time on it.
That said... if that sounds like something we might do, I am happy with an xslow mark, because _maybe_ we do run it rarely but regularly at some point.

**Comment by mattip** [comment]
I adopted (1) and moved the 13-line test as a comment next to the 16-line code snippet it is meant to test.

**Comment by mattip** [comment]
> not sure what is up with that one

It is #23182 which was solved in #23183

**Comment by seberg** [comment]
Azure hasn't been moving for an hour, going to try close+reopen...

**Comment by seberg** [comment]
Annoying that there are more of them, but all failures are accounted for, so going to merge.  Thanks.

**Pull request merged**
