### PR TITLE
MAINT: Fix (some) yield warnings

### PR DESCRIPTION
**Pull request by ghost**
Edit: most effective approach is regular expression find + replace.

### CODE REVIEW

**Comment by xoviat** [comment]
It's unclear why these changes would lead to a new (deterministic) test faillure -- see the appveyor test results.

**Comment by charris** [comment]
Thanks @xoviat .

**Comment by charris** [comment]
I assume that each former yield test is no longer treated as separate, so it might be worth looking at adding informative error messages.

**Comment by charris** [comment]
Also, a single test failure deep in the loops will fail the whole test rather than just that particular combination of arguments that failed. There are several ways around that, but I'm not sure what the best way is. Is there a pytest recommended replacement for yield based tests?

**Comment by xoviat** [comment]
> Is there a pytest recommended replacement for yield based tests?

There's not really a clean replacement. One option is to parameterize the tests, but sometimes the tests are dynamically generated. The main answer that the pytest folks have given is that variable  introspection makes the exact failure clear -- and it does. However, the part about the test not making it to the other scenarios after the first one fails is a valid concern.

**Pull request merged**
