### PR TITLE
TYP: npyio: loadtxt: usecols: add None type

### PR DESCRIPTION
**Pull request by jlecordier**
According to the previous type hint, None was not allowed, but since None is the default value, then None IS allowed

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Good catch, thanks @jlecordier.

**Comment by jlecordier** [comment]
Oups, didn't see that `None | ` should be the first type in the union, and not the last..

**Comment by jlecordier** [comment]
It ultimately does not, it was just a matter of consistency with the rest of the codebase. These kinds of convention should be automatically applied by a linter anyway

**Comment by rgommers** [comment]
Okay, then I'd say fine to leave as is for now. If a linter wants to reshuffle it at some point, that's okay.

**Pull request merged**
