### PR TITLE
BUG: make a variable volatile to work around clang compiler bug

### LINKED ISSUE #18005: BLD: Do not use clang default to ignore floating point exceptions
Remarkably numpy.log() gives a runtime overflow warning on a float32 array containing values larger than 1e9.  Numpy 1.19.4, macOS 10.15.7, MacBookPro15,3.  Warning does not appear for float64 array even for much larger values (e.g. 1e35).

### Reproducing code example:

```python
import numpy as np
a = np.array([1e9], np.float32)
np.log(a)
```

### Error message:

RuntimeWarning: overflow encountered in log

### NumPy/Python version information:

1.19.4 3.8.6 (default, Nov 20 2020, 18:29:40) 
[Clang 12.0.0 (clang-1200.0.32.27)]

### PR DESCRIPTION
**Pull request by r-devulap**
Fixes https://github.com/numpy/numpy/issues/18005

### CODE REVIEW

**Comment by seberg** [comment]
Thanks @r-devulap this sounds like a simple and good change to me. Should be backported to both 1.19.x and 1.20.x I guess.

@tomgoddard I trust this fixes the issue, but if it is easy for you to check, that would be appreciated!

**Comment by tomgoddard** [comment]
I tried today's numpy daily build numpy-1.21.0.dev0+271.gf7bc51218-cp38-cp38-macosx_10_9_x86_64.whl in my software that led to this bug report and no longer get the log() overflow warning.  I did not verify that this daily build has the patch.

Thanks for the amazing quick work to locate and fix the problem.  I find it interesting that this bug could go unreported for long.   Surely log(float32) is used a fair bit.  Maybe it indicates that the RuntimeWarning messages are largely suppressed by software that uses numpy.

**Comment by charris** [comment]
@tomgoddard The fix was included in that build.

**Comment by seberg** [comment]
Relatively speaking, not too many people are affected by this or would notice it, I think.

1. You need to use float32 (which is not the default)
2. You need a reasonably recent/high end CPU
3. You need to use clang, which probably reduces it to mostly Mac OS
4. It is just a warning, many may miss it or just not care.

**Pull request merged**
