### PR TITLE
BUG: Replace f-string in setup.py

### PR DESCRIPTION
**Pull request by charris**
We want the warning to stay compatible with early versions of python.

### CODE REVIEW

**Comment by BvB93** [comment]
Since this issue apparently keeps cropping up, would it be worthwhile to add a test that checks for the presence of f-strings?

**Comment by charris** [comment]
@Bas I don't think adding a test would be worth it, Python versions without f-strings will soon be scarce in the wild in any case.

**Review by BvB93 — APPROVED** [review]
Fair enough, let's forgo the test in that case.

**Comment by seberg** [comment]
Thanks Chuck. I agree, we could add a trivial CI for a good message with whatever smallest Python version CI supports, but I am not sure it is worth it.

Just to make the note (I don't remember seeing it in a while) the "warning in matmul" on windows struck again here.

**Comment by charris** [comment]
Shippable seems to have trouble at the moment building the pickle5 wheel, don't know why.

**Pull request merged**
