### PR TITLE
Fix numpy lookfor for extension modules where path is None

### PR DESCRIPTION
**Pull request by stefanv**
I apologize in advance for the unsatisfactory nature of this PR, but I would appreciate some guidance.

For scikit-image, we've been co-opting `numpy.lookfor` for a long time to find functions inside of the library.  It stopped working this week.  The culprit was a binary module, for which `item.__path__` was not defined.

This patch ignores items for which `item.__path__` doesn't at least translate to a non-empty string.  But I am not sure how to test this approach.  Any thoughts?

### CODE REVIEW

**Comment by charris** [comment]
Do all binary modules lake `item.__path__` or is that something special about the troublesome module? That is, is it fixable? I don't have a problem with this going in without a test as long as it still functions for the usual cases.

**Comment by charris** [comment]
Is this a regression, or is the module new?

**Comment by eric-wieser** [comment]
> for which item.__path__ was not defined.

By which you presumably mean "was defined as `None`". It seems to me that setting `__path__ = None` is unsupported, and so the compiled module is at fault here. That's not to say we can't work around it, but it would good to be clear whether this would be a workaround or a bug fix.

**Comment by stefanv** [comment]
@eric-wieser Yes, this is due to a bug in Cython 0.29: https://github.com/cython/cython/issues/2662

**Comment by charris** [comment]
Sound like this can be closed, Cython is now up to 29.3.

**Pull request closed without merging**
