### PR TITLE
BUG: Alpha parameter must be 1D in `generator.dirichlet`

### LINKED ISSUE #15915: np.random.Generator.dirichlet misbehaves on multidimensional input
As noticed in gh-15876 dirichlet misbehaves (according to [its docs](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.Generator.dirichlet.html?highlight=dirichlet#numpy.random.Generator.dirichlet)) on multidimensional input. What's more docs seems ambigous: what does "k dimension for sample of dimension k" mean? I feel confused. Thus I suppose that both docs and code of dirichlet should be fixed. 

### Reproducing code example:

```python
>>> import numpy as np
>>> np.__version__
'1.18.0'
>>> rng = np.random.default_rng()
>>> rng.dirichlet([[1/6, 1], [1/6, 1]]).ndim # should be 2 according to docs
1
```

### PR DESCRIPTION
**Pull request by panpiort8**
Only one dimensional alpha parameter is currently supported, but higher
dimensions were silently allowed and gave an incorrect results. This
fixes the regression. In the future, the API could be extended to allow
higher dimensional arrays for alpha.
Fixes gh-15915.

### CODE REVIEW

**Comment by seberg** [comment]
Thanks, we also need a test for the new generator probably?

**Comment by panpiort8** [comment]
> Thanks, we also need a test for the new generator probably?

Could you please specify what 'for new generator' means?

**Comment by seberg** [comment]
Sorry, I think you implemented it for the new API i.e. `random.Generator(...).dirichlet`, the fix also applies to `np.random.dirichlet`, or was there no regression there so we just do not touch it? I suppose if the code is identical this is good as is.

**Comment by panpiort8** [comment]
> Sorry, I think you implemented it for the new API i.e. `random.Generator(...).dirichlet`, the fix also applies to `np.random.dirichlet`, or was there no regression there so we just do not touch it? I suppose if the code is identical this is good as is.

np.random.dirichlet misbehaves differently, but still misbehaves in both cases. I'm not sure if it's regression.

```python
>>> import numpy as np
>>> print(np.__version__)
1.16.0
>>> np.random.dirichlet([[1/6, 1], [1/6, 1]]).ndim # should be 2 according to docs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4749, in mtrand.RandomState.dirichlet
ValueError: object too deep for desired array
```

```python3
>>> import numpy as np
>>> print(np.__version__)
1.18.0
>>> np.random.dirichlet([[1/6, 1], [1/6, 1]]).ndim # should be 2 according to docs
1
```

**Comment by seberg** [comment]
Well, in 1.16 it gave an error in 1.18 it gives a wrong result, right, souds like a regression. I think you simply have to apply your identical fix also to the RandomState class here. That way it will be an error again in all cases and the regression is fixed.

**Comment by panpiort8** [comment]
> Well, in 1.16 it gave an error in 1.18 it gives a wrong result, right, souds like a regression. I think you simply have to apply your identical fix also to the RandomState class here. That way it will be an error again in all cases and the regression is fixed.

Ok, I've done it

**Comment by charris** [comment]
@seberg Gentle ping :)

**Comment by seberg** [comment]
OK, lets put this in. I suppose the docs may use a bit more polishing, but no need to backport that part and it looks fine. Thanks for following up on this one as well @panpiort8!

**Pull request merged**
