### PR TITLE
ENH: Add an "axis" kwarg to numpy.unique

### PR DESCRIPTION
**Pull request by joferkington**
## Description

Adds an `axis` kwarg to `numpy.unique` so that `unique` can easily be used to find unique rows/columns/sub-arrays/etc of a larger ndarray.
## Rationale

There is often a need to find unique rows/columns/etc of an array.  However, `numpy.unique` currently operates only on the flattened array, and returns unique elements.  It is possible to work around this in several ways (e.g. viewing each row/column/etc as a structured array or a void dtype the size of the row/column in question).  However, each of these work-arounds requires a fairly in-depth knowledge of numpy.  Having an `axis` kwarg to `unique` makes this operation much simpler.
## Examples

```
In [1]: import numpy as np

In [2]: a = np.array([[1, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0]])

In [3]: a
Out[3]: 
array([[1, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [4]: np.unique(a)
Out[4]: array([0, 1])

In [5]: np.unique(a, axis=0)
Out[5]: 
array([[0, 1, 0],
       [1, 0, 1]])

In [6]: np.unique(a, axis=1)
Out[6]: 
array([[0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [7]: b = np.dstack([a]*3).T

In [8]: b
Out[8]: 
array([[[1, 0, 0, 0],
        [0, 1, 1, 1],
        [1, 0, 0, 0]],

       [[1, 0, 0, 0],
        [0, 1, 1, 1],
        [1, 0, 0, 0]],

       [[1, 0, 0, 0],
        [0, 1, 1, 1],
        [1, 0, 0, 0]]])

In [9]: np.unique(b, axis=0)
Out[9]: 
array([[[1, 0, 0, 0],
        [0, 1, 1, 1],
        [1, 0, 0, 0]]])
```

### CODE REVIEW

**Comment by alimuldal** [comment]
I, for one, would really like to see this feature in numpy 1.10! Were there any show-stopping concerns about this implementation? I get the impression from the comments that the outstanding issues were mostly API and documentation-related.

**Comment by seberg** [comment]
@alimuldal, I do not remember the discussion on the list. Maybe you can have a look at this. We probably had most of the techincal issues already addressed it would seem, so yes. Maybe all this needs is another revival (i.e. from you), but maybe first have a look at the old discussion and see what the result was (if there was any), or just revive it on the mailing list.

**Comment by joferkington** [comment]
@alimuldal & @seberg Here's the list discussion: http://numpy-discussion.10968.n7.nabble.com/Adding-an-axis-argument-to-numpy-unique-td34841.html

If I recall correctly, it was mostly just ambiguity around naming vs. kwargs.  I didn't want to push something ahead too hard without a clear consensus.

Also related (along with other functionality):
http://numpy-discussion.10968.n7.nabble.com/New-function-count-unique-to-generate-contingency-tables-td38363.html
(and the pull request in question: https://github.com/numpy/numpy/pull/4958#issuecomment-71785570)

**Comment by alimuldal** [comment]
@joferkington Thanks, I'll take a look

**Comment by joferkington** [comment]
Related issue from a couple of years ago: https://github.com/numpy/numpy/issues/2871

**Comment by Stretch97** [comment]
I would also like to see this feature in numpy.

**Comment by micmitch** [comment]
This would be very useful.

I'm currently using the function unique_rows from @bfroehle which was posted here https://github.com/numpy/numpy/issues/2871

**Comment by martinosorb** [comment]
@joferkington As I was saying the other day in another thread, I think it would be a great functionality to have. I personally support the idea of just adding an "axis" parameter. I don't think it would be ambiguous: in all the functions that have one, the given axis is the one that ''disappears'' in after the operation, so it would be quite easy to remember. Are you still interested in taking this forward? Otherwise I may look into it.

**Pull request closed without merging**
