### PR TITLE
DOC: correct Logo SVG files rendered in dark by Figma

### PR DESCRIPTION
**Pull request by mebriki**
Corrected SVG colors following the NumPy Logo Guidelines and original logo/frame sizes are preserved. See #24933
The corrected colors in SVG files now render correctly in Figma

### CODE REVIEW

**Review by HaoZeke — CHANGES_REQUESTED** [review]
Thanks for the contribution! Generally LGTM, though I had a thought. Is there a reason for the change in sizes of the images? If not, it would be best to keep to the same size.

**Comment by iaminebriki** [comment]
> Thanks for the contribution! Generally LGTM, though I had a thought. Is there a reason for the change in sizes of the images? If not, it would be best to keep to the same size.

@HaoZeke I've noticed that figma has implicitly affected the sizes, but I've corrected them now, thank you

**Review by HaoZeke — APPROVED** [review]
Excellent, thanks.

**Comment by melissawm** [comment]
@InessaPawson want to take a look?

**Comment by seberg** [comment]
not sure it matters, but aren't the sizes still changed?

**Comment by iaminebriki** [comment]
> not sure it matters, but aren't the sizes still changed?

@seberg 
I think it matters for the public community who may use NumPy logo on Figma to design whatever materials they need Numpy logo on,
for the sizes you can check the previews in the [1st commit](https://github.com/numpy/numpy/pull/24975/commits/699e093d0e5afd8ebdacda9f83ebb957499adfaf) that the sizes are: **numpylogoicon.svg (150x150)**, **numpylogo.svg (300x135)** and **numpylogo2.svg (150x150)** which were restored in the [3rd commit](https://github.com/numpy/numpy/pull/24975/commits/46767aa89f236d55790ac744372b3fd62b606fe4)

**Comment by seberg** [comment]
@iaminebriki github clearly renders the sizes as still different.  And when I look at the code, it also still looks different.  The size change I see is `345px -> 575px -> 172px`.

**Comment by eric-wieser** [comment]
> I think it matters for the public community who may use NumPy logo on Figma to design whatever materials they need Numpy logo on,

I'm not sure it's numpy's responsibility to work around a bug in figma, or in general around non-compliant SVG renderers.

**Comment by iaminebriki** [comment]
> @iaminebriki github clearly renders the sizes as still different. And when I look at the code, it also still looks different. The size change I see is `345px -> 575px -> 172px`.

May be when I manually loaded the files on figma and then downloaded them the sizes were implicitly messed up even when I tried to resize them back manually..

**Comment by iaminebriki** [comment]
> > I think it matters for the public community who may use NumPy logo on Figma to design whatever materials they need Numpy logo on,
> 
> I'm not sure it's numpy's responsibility to work around a bug in figma, or in general around non-compliant SVG renderers.

yes sure, it appears that figma didn't render those files' colors correctly because they were filled in rgb..

**Comment by eric-wieser** [comment]
> yes sure, it appears that figma didn't render those files' colors correctly because they were filled in rgb..

Can you test that by replacing the rgb with hex and nothing else? My guess would be that the reason is that figma does not support `<style>`.

**Comment by iaminebriki** [comment]
> > yes sure, it appears that figma didn't render those files' colors correctly because they were filled in rgb..
> 
> Can you test that by replacing the rgb with hex and nothing else? My guess would be that the reason is that figma does not support `<style>`.

`<style>` works fine with Hex, e.g: `<style>.cls-1{fill:#4DABCF;}.cls-2{fill:#4D77CF;}</style>`

**Comment by seberg** [comment]
Thanks, since it is now just a less readable way of encoding the color, it seems OK to me now, so let's just put it in.

**Pull request merged**
