### PR TITLE
MAINT: distutils cleanup for Pyrex support and unused f2py/swig tests

### PR DESCRIPTION
**Pull request by rgommers**
related already closed issue: gh-1687

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I think this will break our (admittedly quite old) monkeypatching of numpy.distutils in yt's setup.py file:

https://bitbucket.org/yt_analysis/yt/src/1d85a1b623ed38907c4890609c63f6d875c33fc6/setup.py?at=yt&fileviewer=file-view-default#setup.py-64

see also this commit which added this function and monkeypatching:

https://bitbucket.org/yt_analysis/yt/commits/bce1c775bb844891a572ee2df95e57ce01138dee

So we've been using this since 2011. Is there some sort of native support in numpy.distutils for building cython extensions that yt should be using instead of this?

**Comment by charris** [comment]
I love the fresh smell of removed files ;)

**Comment by rgommers** [comment]
> I think this will break our (admittedly quite old) monkeypatching of numpy.distutils in yt's setup.py file:

Ah, the joys of monkeypatching. I think I'll put back the methods then but make ``generate_a_pyrex_source`` raise an error by default so it only works if monkeypatched.

> Is there some sort of native support in numpy.distutils for building cython extensions that yt should be using instead of this?

There's not. However Cython itself ships a distutils extension: http://docs.cython.org/src/quickstart/build.html#building-a-cython-module-using-distutils

I much prefer this method though: https://github.com/scipy/scipy/blob/master/tools/cythonize.py. That only rebuilds when necessary and avoids rebuilding source releases (those still contain the .c files plus a hash per file showing that they're not outdated).

**Comment by charris** [comment]
@ngoldbaum Numpy `setup.py` has
```
def generate_cython():
    cwd = os.path.abspath(os.path.dirname(__file__))
    print("Cythonizing sources")
    p = subprocess.call([sys.executable,
                          os.path.join(cwd, 'tools', 'cythonize.py'),
                          'numpy/random'],
                         cwd=cwd)
    if p != 0:
        raise RuntimeError("Running cythonize failed!")
```

The `tools/cythonize` script was copied from scipy and is present since Numpy 1.9.0. However, the scripts in `tools` are not part of installed Numpy.

**Comment by ngoldbaum** [comment]
> Ah, the joys of monkeypatching. I think I'll put back the methods then but make generate_a_pyrex_source raise an error by default so it only works if monkeypatched.

That would be great. In the long term I'll look at how we can avoid monkeypatching numpy.distutils to accomplish this.

**Comment by rgommers** [comment]
Updated.

**Comment by charris** [comment]
@rgommers Could use a mention in `1.11.0-notes.rst`.

**Comment by njsmith** [comment]
@ngoldbaum: Quick advertisement: if you want to get early warning of obscure issues like this that sneak into master without being noticed, then it's now very easy to add a travis build to your project that runs your tests against the latest numpy master. We're building wheels for py35 on travis and uploading them to a server at rackspace, so a command like this should work:
```
pip install --pre --upgrade --no-index --timeout=60 --trusted-host travis-dev-wheels.scipy.org -f http://travis-dev-wheels.scipy.org/ numpy
```
(scipy is also uploading dev versions to the same spot, so add `scipy` to the end of that command if you also want to test against the latest dev version of scipy. The wheels are only uploaded if the tests passed, so there's some minimal quality control, but of course there's no guarantee that these builds will actually work or that any changes in them will survive to a final release -- but it's hopefully a useful early warning system.)

**Comment by ngoldbaum** [comment]
Thanks for the tip. Unfortunately we don't use travis, since they don't support bitbucket or mercurial. I also doubt our full test suite would run on travis - it needs a lot of resources.

**Comment by rgommers** [comment]
> Could use a mention in 1.11.0-notes.rst.

Sure, done.

**Comment by charris** [comment]
Thanks Ralf.

**Pull request merged**
