### PR TITLE
MAINT: update function's `__module__` attribute in `deprecate`

### PR DESCRIPTION
**Pull request by person142**
Currently the location of the function definition is always reported
to be `numpy.lib.utils`; this changes it to be the location of the
actual definition when possible.

So for example this code:

```python
>>> from scipy.stats import frechet_r
>>> help(frechet_r.cdf)
```

gives:

```
Help on method frechet_r in module numpy.lib.utils:
...
```

on master but

```
Help on method frechet_r in module scipy.stats._continuous_distns:
...
```

on this branch. This won't help with things that don't have a `__module__` attribute,

```python
>>> import scipy.special as sc
>>> help(sc.hyp2f0)
```

still gives

```
Help on function hyp2f0 in module numpy.lib.utils:
...
```

but I don't know of a way around that?

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can we use `functools.update_wrapper` here instead?

**Comment by person142** [comment]
@eric-wieser done.

As it stands now the old behavior is changed somewhat since the wrapper function will automatically have  a `'__wrapped__'` key added to its `__dict__`. In particular, this means that the wrapper function will always have a `__dict__`, even if the wrapped function didn't (unlike before).

If desired I can change the behavior back by tossing in a

```python
if not hasattr(func, '__dict__'):
    del newfunc.__dict__
```

**Comment by charris** [comment]
Need to know if this might affect pickles. Not sure how, but...

**Comment by bsipocz** [comment]
@charris - what did you mean by affecting pickles? 

(I have this rebased and am happy to push it to a new PR given there is a clear path what else should be done with it. Also, in the meantime, I noticed that this functionality is not really used much, neither in numpy itself (but I noticed that there are a few super old deprecations, that I've cleaned up in separate PRs) nor in scipy anymore. Nevertheless, the fix maybe still relevant, and as it's in the public API others may still use it)

**Comment by seberg** [comment]
@bsipocz maybe you can just go ahead with your fixup and ping me?  This seems pretty save and good to me... Whether we want this function or not (I am not even a fan).  I am not sure about Eric's comment immediately, but it also doesn't seem like it would matter much either way...

**Comment by bsipocz** [comment]
Eric's comment was addressed, the one I wasn't sure what to do with was the pickles. 

As for the generic liking of ways of deprecations, I really like the decorator way astropy is using, it's rather feature rich and I think would be nice if it would be more widespread, but to achieve that it should be moved somewhere upstream. 

Anyway, I'll push a PR to wrap this one up here once I'm back on my laptop.

**Comment by seberg** [comment]
Ah, I suspect if anything this should fix pickling.

**Pull request closed without merging**
