### PR TITLE
REL: Prepare for the NumPy 1.24.2 release

### PR DESCRIPTION
**Pull request by charris**
- Create 1.24.2-changelog.rst
- Update 1.24.2-notes.rst

### CODE REVIEW

**Comment by charris** [comment]
Reverting 30535f40816306858841b14dced7ef092bccfad8 to see if that fixes things.

**Comment by charris** [comment]
The relevant differences to main seem to be in `numpy/core/src/npymath/ieee754.cpp` and `numpy/core/src/npymath/ieee754.c,src`,  which do not define npy_nextafter in main. This is probably due to the npymath cleanup.

**Comment by charris** [comment]
@mattip Thoughts?

**Comment by mattip** [comment]
hmm. Did we never try building wheels after #22972?

**Comment by charris** [comment]
> Did we never try building wheels after #22972?

Apparently not :) That's why I make sure to do that in these preparatory PRs. Note that the problem turned up when building wheels for m1.

**Comment by charris** [comment]
Undid the reversion to bring back the original so we can test solutions.

**Pull request merged**
