### PR TITLE
ENH Change return type of f2py_set_data_func, f2py_void_func, f2py_init_func from void to int

### PR DESCRIPTION
**Pull request by hoodmane**
For wasm32 support. This is split off from #21772.
@rgommers @HaoZeke @charris

### CODE REVIEW

**Review by HaoZeke — CHANGES_REQUESTED** [review]
This doesn't seem to be a complete change, the function pointers these are used for must now return integers.

**Comment by hoodmane** [comment]
Well note that the tests pass. Most platforms aren't picky about the return type, but wasm is. @certik says that the LFortran wasm backend is working but I haven't figured out how to build it yet. If LFortran is also producing `int` as the return type then I think we'll have a solid case here. `f2c` is pretty janky so it's hard to know if it's right or not.

**Comment by seberg** [comment]
I suspect returning `int` is never an ABI problem in practice (but I am not a specialist) – i.e. the platform ABI probably always uses a certain register for it, and all it does is making that register volatile (I suspect that register is always volatile, so it probably even going from `int` to `void` probably doesn't matter).

The other (but also awkward) thing would be to introduce a `FOTRAN_VOID` to allow you to more easily override the return value in situations where `int` is actually used.

**Comment by hoodmane** [comment]
My main worry is that we switch to a real Fortran compiler, it makes these functions return void, and we end up needing to patch this back to void.

**Comment by hoodmane** [comment]
I guess the problem with us patching the output it is that it means that we maintain special magic that allows numpy to work in `wasm32-emscripten`. In the long run, it would be good to be able to make emscripten builds of numpy without needing Pyodide-specific tools.

I'll try to get lfortran working asap and check what it does. 

Also, where does `f2py_set_data_func` come from? I find it in all sorts of object files but I don't see it in any source files.

**Comment by hoodmane** [comment]
Okay I tried building again without this patch and... all the tests pass? So maybe we don't need it after all. I swear the last time I tried to drop the patch a week ago it didn't work. Anyways, I guess I can close these.

**Comment by seberg** [comment]
This patch was for SciPy (not NumPy itself), I thought?  But hopefully everything is working, whatever the reason :).  Then we don't have to worry about doing weird contortions here.

**Comment by hoodmane** [comment]
Yeah I thought it was for Scipy, but if it is we don't seem to have coverage for it in the Pyodide test suite. In any case, I think patches for Scipy are less important because building Scipy is a lot further from working reasonably.

@joemarshall is there anything specific I should check to see if this patch is needed?

**Pull request closed without merging**
