### PR TITLE
BLD: Try adding aarch64 wheels [wheel build]

### PR DESCRIPTION
**Pull request by lithomas1**

### CODE REVIEW

**Comment by lithomas1** [comment]
@mattip @rgommers I think this is ready for an initial review now.

There's still somethings that I have to add(e.g. wheel uploading, and the triggering mechanism present on GHA), but it basically works now. It should be trivial to add, as it would probably just mean refactoring out the bash logic in GHA to a shared file under tools and calling it from both Travis CI and GHA.

For wheel uploading, someone needs to add the upload tokens to both staging and nightly under the names ``NUMPY_STAGING_UPLOAD_TOKEN`` and ``NUMPY_NIGHTLY_UPLOAD_TOKEN``.

**Comment by lithomas1** [comment]
No, I'm pretty sure I overrided the build/test components on the wheel builders.

(Because I didn't override the before_install step, it still executes on the wheel builders. Should be harmeless given that building happens in a docker container, but will try to fix in next commit.)

**Comment by mattip** [comment]
When I look at the [travis-ci run](https://github.com/numpy/numpy/pull/20987/checks?check_run_id=5047219437) for this PR I see 7 jobs. It is not clear from the ENV which architecture it is, but here is a table. Can you somehow disable runs 3 and 4?

run | python | architecture | style
[42773.1](https://app.travis-ci.com/github/numpy/numpy/jobs/558176511) | 3.8 | ppc64le | old
[42773.2](https://app.travis-ci.com/github/numpy/numpy/jobs/558176512) | 3.8 | s390x | old
[42773.3](https://app.travis-ci.com/github/numpy/numpy/jobs/558176513) | 3.8 | aarch64 | old
[42773.4](https://app.travis-ci.com/github/numpy/numpy/jobs/558176514) | 3.10-dev | aarch64 | old
[42773.5](https://app.travis-ci.com/github/numpy/numpy/jobs/558176515) | 3.8 | aarch64 | cibuildwheel
[42773.6](https://app.travis-ci.com/github/numpy/numpy/jobs/558176516) | 3.9 | aarch64 | cibuildwheel
[42773.7](https://app.travis-ci.com/github/numpy/numpy/jobs/558176517) | 3.10 | aarch64 | cibuildwheel

**Comment by lithomas1** [comment]
Oh, I think I see what you mean now. 
Is the idea to move the testing on aarch64 from the standalone job to inside the test phase of the cibuildwheel build?

**Comment by mattip** [comment]
> Is the idea to move the testing on aarch64 from the standalone job to inside the test phase of the cibuildwheel build?

Either that or put an `if not wheels` so that we either build wheels or run the old build scripts

**Comment by lithomas1** [comment]
Do you want to set up the upload tokens now or leave that for a follow up? I forgot to mention this, but someone also has to set up a cron job too, through the Travis UI to run the weekly builds.

**Comment by mattip** [comment]
Did you try /tools/wheels/upload_wheels.sh on your branch? 

I wonder why it is echoing the command [here](https://app.travis-ci.com/github/numpy/numpy/jobs/560045427#L23139)

**Comment by mattip** [comment]
Thanks @lithomas1.

**Comment by mattip** [comment]
A manual trigger has the line [`TRAVIS_EVENT_TYPE is api`](https://app.travis-ci.com/github/numpy/numpy/jobs/560238579#L22971) but there is no condition for that in the script, so it does not upload. I think we should add one. https://github.com/numpy/numpy/blob/8653f044866095c2176fed1d5b44d3fbcd6b93f7/tools/wheels/upload_wheels.sh#L1-L14

**Comment by mattip** [comment]
Now the manual trigger does something, but the upload [cannot find the wheel](https://app.travis-ci.com/github/numpy/numpy/jobs/560271760#L23067)
```
ls: cannot access './wheelhouse/*.whl': No such file or directory
```

**Comment by mattip** [comment]
Wheels for aarch64 are uploading! https://anaconda.org/scipy-wheels-nightly/numpy/files

**Pull request merged**
