### PR TITLE
BUG: nanquantile and empty input

### PR DESCRIPTION
**Pull request by kaili211**
BUG: fixed issue [14599](https://github.com/numpy/numpy/issues/14599) and added tests.

### CODE REVIEW

**Comment by mattip** [comment]
Haven;t looked at this in depth, but the issue mentions that `quantile` raises an exception on empty input. Shouldn't `nanquantile` do the same?

**Comment by kaili211** [comment]
> Haven;t looked at this in depth, but the issue mentions that `quantile` raises an exception on empty input. Shouldn't `nanquantile` do the same?

Hi, I'm quite new to Numpy resource codes, thank you for your comments.
I thought this issue wants the return from 1 NaN to an array of two NaNs for `np.nanquantile([], [0, 0.5])`, so I changed it.
Will return NaNs better than raise an error for nan-functions?

**Comment by seberg** [comment]
This is a reduce-like operation, and e.g. `nanmin` follows `min` in that it returns an error when the size is 0. Note that it does return NaN for an all-nan array. I am not even quite sure that is the best thing, but it might be the safe-default to fix this up quickly for now.

Can you add tests for both `nanquantile` and `nanpercentile`?

**Comment by InessaPawson** [comment]
@kaili211  It would be nice to fix https://github.com/numpy/numpy/issues/14599. Do you think you could finish this PR?

**Comment by charris** [comment]
@kaili211 Needs a rebase.

**Comment by charris** [comment]
The account is closed. If someone wants to copy the code and open an new PR, feel free to do so.

**Pull request closed without merging**
