### PR TITLE
Revert "DOC: add vstack, hstack, dstack reference to stack documentation."

### PR DESCRIPTION
**Pull request by shoyer**
Reverts numpy/numpy#7191

cc @charris

### CODE REVIEW

**Comment by charris** [comment]
Revert the merge. `git revert -m 1 <sha_of_merge>`. What you have is separate reversion of all related commits, hence all the tests.

**Comment by shoyer** [comment]
I just used the interface on GitHub -- my git foo is weak! If you have a preferred way to do this, it would be great if you could do that yourself :)

**Comment by njsmith** [comment]
@charris: not sure I follow, and want to make sure I understand so I don't mess it up myself at some point :-). This pull request seems to be just a single clean patch reverting the doc changes, which is what we want, right? What's the advantage of reverting the merge commit instead?

**Comment by charris** [comment]
@njsmith If you just revert the merge the unattached commits are eventually removed. What the revert button does is revert all the commits associated with the merge and each reverted commit gets tested. For instance, if there were ten commits in the PR you would see 11 Travis tests run. It isn't *wrong*, just ugly ;)

**Comment by charris** [comment]
OK, I'm going to close and reopen to see if that works on top of current master.

**Comment by charris** [comment]
I'm going to go ahead an merge this. The merge should get tested later.

**Comment by charris** [comment]
@shoyer Reverted, thanks.

**Comment by njsmith** [comment]
Okay, so to sum up, I think there are two things that the github "Revert" button does that are somewhat annoying:
1) If there are N commits in a pull request, then it creates N revert commits, instead of a single rolled-up revert commit.
2) It puts these commits on a new branch inside the numpy/numpy repository, instead of inside someone's personal fork. This clogs up the travis queue (because travis tests everything committed into the numpy/numpy repository, regardless of which branch it's on), and it clutters up our branch namespace with branches we don't care about. (I just deleted this particular branch, but that's an annoying extra step.)

**Comment by charris** [comment]
@njsmith Ha, I didn't notice the new branch, wondered why I got a commit notice from github. It may be that the reason the tests doubled was that both the branch and the PR were being tested rather than a lack of rolled up commits.

**Comment by njsmith** [comment]
@charris: it could easily be both working together to create a perfect storm of fail: if there were 10 commits being reverted, then travis sees 10 commits in quick sequence to a new branch, starts testing all 10 of them in parallel, and then sees a pull request posted and starts testing that as well.

**Pull request merged**
