### PR TITLE
TST, MAINT: Rename test files with duplicate names.

### PR DESCRIPTION
**Pull request by charris**
Pytest likes every test file to have a unique name. There are several
ways around this, but renaming the files seems the simplest and most
flexible and it doesn't get in the way of any future rearrangements we
may make. The deduplication approach here is to insert the package
name after the `test_` prefix. Note that the resulting test file names no
longer exactly match the files they are testing, for instance
`test_lib_utils.py` tests `numpy/lib/utils.py`, not `numpy/lib/lib_utils.py`. 
At some point it might make sense to rename all the test modules, but
that would probably break most current PRs. Renamed tests are:
```
numpy/core/tests/test_core_deprecations.py
numpy/core/tests/test_core_function_base.py
numpy/core/tests/test_core_regression.py
numpy/core/tests/test_core_shape_base.py
numpy/f2py/tests/test_f2py_regression.py
numpy/lib/tests/test_lib_function_base.py
numpy/lib/tests/test_lib_polynomial.py
numpy/lib/tests/test_lib_regression.py
numpy/lib/tests/test_lib_shape_base.py
numpy/lib/tests/test_lib_utils.py
numpy/linalg/tests/test_linalg_deprecations.py
numpy/linalg/tests/test_linalg_regression.py
numpy/ma/tests/test_ma_deprecations.py
numpy/ma/tests/test_ma_regression.py
numpy/random/tests/test_random_regression.py
numpy/testing/tests/test_testing_utils.py
```

### CODE REVIEW

**Comment by eric-wieser** [comment]
Ugh, this looks like a big design flaw in pytest to me. What happened to _"Namespaces are one honking great idea -- let's do more of those!"_?

**Comment by eric-wieser** [comment]
I assume [this](https://stackoverflow.com/questions/12582503/py-test-test-discovery-failure-when-tests-in-different-directories-are-called) is the problem you're referring to?

It sounds like adding `__init__.py` files is the way to go - this was originally advised against by pytest, but that recommendation has apparently been removed from their docs

**Comment by eric-wieser** [comment]
In fact, creating `__init__.py` files is [now recommended here](https://docs.pytest.org/en/latest/goodpractices.html#tests-as-part-of-application-code)

**Comment by charris** [comment]
Name spaces make sense for packages, which is why adding `__init__.py` works. Apparently Nose had some nasty work around for the problem.  Note that there are several different solutions at the link.

**Comment by eric-wieser** [comment]
I can't tell: are you arguing against adding __init__.py files there?

**Comment by charris** [comment]
The main problem with just adding `__init__` files is that you can no longer run `pytest numpy` because it imports numpy while in the numpy repository. Note that `runtest` installs in a different directory. That is why the suggested best layout would move `numpy` down into a `src` directory and put the tests in a `tests` directory.

**Comment by eric-wieser** [comment]
> can no longer run `pytest numpy` because it imports numpy while in the numpy repository.

Wouldn't this happen anyway if you run it from the repository root? Or does `cwd` change before the test files are run?

**Comment by charris** [comment]
It runs fine with the name change. I assume this is something taken care of in the collection phase, where importing the test modules does not require importing numpy because there is currently no `__init__` file. The other thing that goes missing with `__init__` is `run_test_suite`, so no `python <path_to_test-module>`, which is handy for writing tests. Note that scipy gave up that option and added the `__init__` files. This PR is for discussion as much as anything else, but there weren't that many duplicate file names.

**Comment by eric-wieser** [comment]
Unrelatedly: is MAIN a new prefix, or should that be MAINT?

**Comment by charris** [comment]
Should be MAINT ;)

**Comment by charris** [comment]
See #9524 for the alternative.

**Comment by charris** [comment]
Closing in preference to #9524.

**Pull request closed without merging**
