### PR TITLE
DOC: Remove CoC pages from Sphinx

### LINKED ISSUE #17415: DOC: Duplicate "Code of Conduct" pages
We have two Code of Conduct pages:

* [In the Sphinx pages](https://numpy.org/devdocs/dev/conduct/code_of_conduct.html#diversity-statement)
* [In the Hugo pages](https://numpy.org/code-of-conduct/)

Should the Sphinx version be removed?

### PR DESCRIPTION
**Pull request by bjnath**
Removes Code of Conduct pages `code_of_conduct.rst` and `report_handling_manual.rst` from Sphinx; these are 
now on Hugo.

Closes gh-17415

### CODE REVIEW

**Review by mattip — APPROVED** [review]
Looks good, assuming the doc build passes.

**Comment by bjnath** [comment]
@mattip 
> assuming the doc build passes.

We're clear:
image

**Comment by charris** [comment]
Thanks @bjnath .

**Comment by bjnath** [comment]
I see that when the original CoC was added and revised, entries were made in the changelog. Should this change go in the changelog too?

```
changelog/1.16.0-changelog.rst
330:* `#11865 <https://github.com/numpy/numpy/pull/11865>`__: DOC: add a Code of Conduct document.

changelog/1.19.0-changelog.rst
545:* `#16201 <https://github.com/numpy/numpy/pull/16201>`__: DOC: update Code of Conduct committee
```

**Comment by charris** [comment]
The changelogs are generated as part of a release, don't bother them.

**Pull request merged**
