### PR TITLE
TST: skip two tests in aarch64 linux wheel builds

### PR DESCRIPTION
**Pull request by rgommers**
xref gh-17554
xref gh-25460

### CODE REVIEW

**Comment by rgommers** [comment]
Okay, we should be good here now. Once this is merged I'll trigger a cron job run to upload new aarch64/arm64 wheels.

**Review by Mousius — CHANGES_REQUESTED** [review]
Unfortunate 😿 

Should the description be skip rather than fix? Also did you mean to delete the meson log?

**Comment by rgommers** [comment]
Well it fixes the failures (just not the root cause) :) But sure, changed the title.

> Also did you mean to delete the meson log?

Yes, that didn't actually work and caused the last aarch64 wheel build run to fail. I'm in a hurry to get the nightlies up before the holiday starts, so I'll revisit the logging at some point (probably next time we actually need info from it).

**Review by Mousius — APPROVED** [review]

**Comment by rgommers** [comment]
Thanks for the review @Mousius.

I'll go ahead and self-merge, then kick off new wheel builds.

**Pull request merged**
