### PR TITLE
DOC: Disclaimer for FFT library

### PR DESCRIPTION
**Pull request by bjnath**
Adds sentence to the top of `routines.fft.html` explaining that `scipy.fft`
is a more comprehensive collection, per mailing list discussion
(http://numpy-discussion.10968.n7.nabble.com/Add-Chebyshev-cosine-transforms-implemented-via-FFTs-td48373.html#a48382)

### CODE REVIEW

**Comment by grlee77** [comment]
Looks good. Aside from the extended set of functions provided, `scipy.fft` also supports single-precision and multithreading, but I don't know that we need to get into that level of comparison here.

**Comment by bjnath** [comment]
@grlee77 That's a good point; "superset" while technically true doesn't really convey scipy's bigger scope.

Reworded it to call scipy "more comprehensive". 

Hopefully the reader can take a hint.

**Review by rgommers — APPROVED** [review]
Make a tiny tweak, adding an intersphinx link and changing "library" to "module". In it goes. Thanks @bjnath

**Comment by bjnath** [comment]
+1 for both. Great idea to add a link.

**Pull request merged**
