### PR TITLE
REL: Update master after 1.18.x branch.

### PR DESCRIPTION
**Pull request by charris**
Apart from the usual modifications, this

- Removes a release note snippet added after towncrier was run
- Removes testing on Python 3.5 as it is dropped for 1.19.x.

### CODE REVIEW

**Comment by seberg** [comment]
If that fragment is deleted, shouldn't it also be added to the 1.18 release note file? This is a bit of an annoyance I guess. After the first release note creation, if we want it to be in 1.18, it needs to be manually inserted. If it should not be in 1.18, then it would not need to be deleted.

**Comment by charris** [comment]
> If that fragment is deleted, shouldn't it also be added to the 1.18 release note file?

It is preserved in the branch and I will manually add it to the release notes when I edit them. Next time I will probably branch, then delete all the fragments in master. Either way, there is a period of time in which things can get mixed up.

**Comment by charris** [comment]
CircleCI is complaining about missing `1.19.0-notes.rst`. As they are not yet generated I don't see why we should be checking that. Do we need dummy notes for some purpose?

**Comment by charris** [comment]
Looks like we need the reference to build the test docs. Will add that.

**Comment by seberg** [comment]
Yeah, I added them. OTOH, they are created during the run, so I can look into changing that. It should not really be necessary.

**Comment by eric-wieser** [comment]
> Next time I will probably branch, then delete all the fragments in master. Either way, there is a period of time in which things can get mixed up.

How about:
1. Create the 1.18 branch (with no commits), update master with new version numbers
2. Create a commit in the 1.18 branch with the collected release notes
3. Merge that commit back into master
4. Do all of the other 1.18-specific branch configuration afterwards

That should eliminate the possibility to end up with uncollected notes.

**Comment by charris** [comment]
@eric-wieser That should work to delete the fragments that are in the new branch.

**Comment by rgommers** [comment]
> Looks like we need the reference to build the test docs. Will add that.

This is still missing, and Sphinx is complaining. Is there any reason not to add an empty 1.19.0 release notes file?

**Comment by seberg** [comment]
Yeah, I think we should just do that, it is probably the simplest way of getting both the preview in CI and local tests were you do not want to have to create them. You could put some text in there (unfortunately towncrier does not overwrite that text right now).

**Pull request merged**
