### PR TITLE
BUG: Use larger fetch depth in gitpod.yml

### PR DESCRIPTION
**Pull request by charris**
Change the checkout@v2 fetch-depth parameter to zero, which means
everything. We could probably use a smaller number, but a full
checkout should only add a minute or two.

Related to #19119.

See https://github.com/actions/checkout for an explanation of the checkout@v2 parameters.

### CODE REVIEW

**Comment by charris** [comment]
@trallard Ping.

**Comment by charris** [comment]
If the full fetch is only needed to build NumPy, we could use a smaller clone after.

**Comment by trallard** [comment]
It looks good to me and makes sense since we are only doing a quick build

**Comment by charris** [comment]
Let's give this a try. Shame we have to merge to find out...

**Comment by charris** [comment]
That fixed the gitpod problem.

**Pull request merged**
