### PR TITLE
MAINT: make runtests.py --python and --ipython a little more ergonomic

### PR DESCRIPTION
**Pull request by njsmith**
I'm tired of having to manually enable warnings and import numpy,
so maybe others are too.

### CODE REVIEW

**Comment by rgommers** [comment]
The numpy import is a good idea, but I'm not sure about the warnings. Now when running the tests within the opened interpreter, you first get lots and lots of warnings like:

    /usr/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory
    '/home/rgommers/.local/lib/python2.7/site-packages/virtualenvwrapper': missing __init__.py

**Comment by rgommers** [comment]
Maybe you just want to enable ``DeprecationWarning``s, which are hidden by default?

**Comment by njsmith** [comment]
Sadly no -- I do want to enable display of DeprecationWarnings, but I also
want to disable the suppression of duplicate warnings, which can otherwise
make manual debugging extremely misleading. (You run the same line twice
and get different results, or you can't figure out why one line generates
two warnings in the test suite but only one at the REPL, or...) Basically
for a debugging shell I just want to totally disable all the cleverness
that warnings.py interposes between me and my code.
.
As a data point, can I ask why you're doing
  ./runtests.py --python
  import numpy; numpy.test()
Instead of
  ./runtests.py
? The latter seems simpler ;-)

**Comment by rgommers** [comment]
I'm not normally doing that; that was just for the purpose of checking what this PR does.

**Comment by rgommers** [comment]
I'm not a user of ``runtests.py --(i)python``, so no strong objections to the warnings - it just looked odd to me. I'll let people who do use this comment/merge.

**Comment by njsmith** [comment]
Sorry, mouse finger went wild and clicked close by accident...

Anyone have any objections to this? It's pretty trivial so I guess if no-one speaks up within a few days I'll go ahead and merge.

**Comment by rgommers** [comment]
Allright, no objections so in it goes. Thanks @njsmith

**Pull request merged**
