### PR TITLE
ENH: Add tool for downloading release wheels from Anaconda.

### PR DESCRIPTION
**Pull request by charris**
This is a simplified version of terryfy::wheel-uploader that has
two advantages over the original:

- It works with Anaconda where our wheels are now stored.
- It is simplified to match the NumPY workflow.

### CODE REVIEW

**Comment by mattip** [comment]
Does this need a reference in the [upload to pypi](https://numpy.org/devdocs/dev/releasing.html?highlight=how%20release#update-pypi) section and the [download wheels](https://numpy.org/devdocs/dev/releasing.html?highlight=how%20release#download-wheels) of the "Releasing a Version" documentation (that document is confusing: there are general directions and then a ["Step by step" section](https://numpy.org/devdocs/dev/releasing.html?highlight=how%20release#step-by-step-directions)).

**Comment by charris** [comment]
Yes, it needs more documentation, but I'm going to wait until the first rc is out to make that update so I can see exactly how the new procedures go. There should also add some error handling in case one of the file names is incorrect and it cannot be fetched, but so far there have been no problems downloading the 1.18.3 wheels from anaconda. It seems much faster than before.

**Comment by mattip** [comment]
Nice. Do you want this merged now or should it wait for the documentation update?

**Comment by charris** [comment]
I'd like it merged before branching, it will be simpler to use then, although it doesn't need to be run from the branch. My plan is to get the first rc out, then rewrite the walkthrough and release documentation. I view the walkthrough on github when doing a release, so don't need it in the branch.

**Comment by mattip** [comment]
Thanks @charris

**Pull request merged**
