### PR TITLE
NEP: Proposal for __duckarray__ protocol

### PR DESCRIPTION
**Pull request by pentschev**
This NEP proposes the introduction of the `__duckarray__` protocol, as described in high-level by NEP-22 and further discussed in #13831 .

We have another idea by @shoyer on how to handle duck array typing through `__array_function__`, as mentioned in https://github.com/numpy/numpy/issues/13831#issuecomment-512960168:

> we could consider adding a like argument to duckarray. That would require changing the protocol from the simplified proposal above -- maybe to use __array_function__ instead of a dedicated protocol like __duckarray__? I haven't really thought this through.

The idea above seems viable, and perhaps more complete as well. That said, I want to either extend this NEP to cover that, or maybe write a separate NEP so we can discuss and judge which one is a better solution. In the meantime, let's start discussing the text here.

cc @shoyer @rgommers @jakirkham @hameerabbasi @mrocklin

### CODE REVIEW

**Comment by seberg** [comment]
Maybe these are two different shoes? `__duck_array__` is a lightweight call to ensure the input is array-like. A hypothetical `convert_to_other_array_like(input, DaskArray)` seems to make more sense as an `__array_function__` since it allows either type to define the conversion?

**Comment by pentschev** [comment]
> Maybe these are two different shoes? __duck_array__ is a lightweight call to ensure the input is array-like. A hypothetical convert_to_other_array_like(input, DaskArray) seems to make more sense as an __array_function__ since it allows either type to define the conversion?

Thanks for the suggestion @seberg. They could be complementary, yes. I guess there would always be upsides and downsides, for example, with the `__array_function__` solution, we could have a single function to handle both cases depending on whether the user passes a `like=` argument, for example. Would be great to hear what people think about the potential solutions we have.

**Comment by shoyer** [comment]
> A hypothetical `convert_to_other_array_like(input, DaskArray)` seems to make more sense as an `__array_function__` since it allows either type to define the conversion?

One challenge here is that `__array_function__` is normal method, not a static/class method, so it isn't defined on array types like `DaskArray`.

If we want to dispatch based on the array type, we could devise an asymmetric protocol for this with a `classmethod`, e.g., for a sparse array that only comes with conversions to/from NumPy arrays:
```python
class SparseArray:
    @classmethod
    def __array_convert_from__(cls, source):
        if not isinstance(source, np.ndarray):
            return NotImplemented
        return cls(source)
    def __array_convert_to__(self, array_type):
        if not issubclass(array_type, np.ndarray):
            return NotImplemented
        return self.toarray()
```

Internally, `np.convert(array, target_type)` just do the normal Python protocol dance calling `__array_convert_to__` on the first argument (if available) and  `__array_convert_from__` on the second argument (if available), with checking for `NotImplemented`.

Then `np.convert(sparse_array, np.ndarray)` and `np.convert(numpy_array, SparseArray)` should work. Potentially `np.ndarray` could be the default value for the desired array type, for which we would also probably want to add a special case fall-back to calling `__array__`.

I guess the key question is whether there are use-cases for converting `like` another template array, or only converting `to` another array type. If we can come up with use cases for general purpose conversion (beyond just types), then `np.convert_like()` makes sense and we can reuse `__array_function__`. If not, we should probably make a new protocol (like what I wrote above).

**Comment by shoyer** [comment]
Generally I think this look great!

One minor suggestion: I think `__duckarray__` is too generic of a name and might conflict with other use-cases. All of NumPy's other protocols use the informal `__array*__` namespace, but `__array_duckarray__` sounds weird. How about `__numpy_duckarray__`? `__array_duck__` is another candidate, but that sounds backwards to me.

(Side note -- you are very generous to put me down as an author even though you did all writing!

**Comment by pentschev** [comment]
> I guess the key question is whether there are use-cases for converting like another template array, or only converting to another array type. If we can come up with use cases for general purpose conversion (beyond just types), then np.convert_like() makes sense and we can reuse __array_function__. If not, we should probably make a new protocol (like what I wrote above).

Yes, it makes sense. I guess this is something we have to think a bit more about (at least I do) and gather information from more people. Hopefully there will be others commenting here about that!

**Comment by pentschev** [comment]
> One minor suggestion: I think __duckarray__ is too generic of a name and might conflict with other use-cases. All of NumPy's other protocols use the informal __array*__ namespace, but __array_duckarray__ sounds weird. How about __numpy_duckarray__? __array_duck__ is another candidate, but that sounds backwards to me.

I agree with your primary motivation, indeed `__array*__` makes more sense. At first glance, I don't really like `__numpy_duckarray__` since it gives me the idea that it's something internal to NumPy only. I would go either with `__array_duckarray__` or `__array_duck__`, no strong opinions on either.

> (Side note -- you are very generous to put me down as an author even though you did all writing!

I did the text writing, but the general idea came from you on how to develop this, plus the code is a verbatim copy of your sample. :)

I took the liberty to add your name, but I should have asked first if you were ok with that. If you're not, let me know and I will take it out.

**Comment by hameerabbasi** [comment]
Please note that as per NEP 0, all design discussion should take place on the mailing list where it’ll reach the most relevant audience.

The PR should be merged as early as possible with just minor grammatical or style fixes.

**Comment by pentschev** [comment]
That's fine by me. If there's no comments we can go ahead and merge it.

What should be the NEP number? The latest merged in is 27, but I saw other open PRs using numbers 28 and 29 at least, even some duplicating numbers.

**Comment by seberg** [comment]
I think its OK to go for merge conflicts here. If Stephan is OK (and silence I assume means yes), I am good with merigng soon. I would just go for the first free number here, to be honest. I think the status right now is `Draft` (we want to make it `Provisional` I guess, but only after mailing list discussion).

**Comment by pentschev** [comment]
Alright, assigned number 28 for the NEP and changed its status to draft.

**Comment by pentschev** [comment]
Hmmm, mailing list archive shows a discussion on a NEP-28: https://mail.python.org/pipermail/numpy-discussion/2019-July/079872.html.

Would it be better to reassign that number to avoid confusion for people browsing archives?

**Comment by shoyer** [comment]
Yes, let's pick a new number. There's no harm in incrementing more than necessary :)

**Comment by pentschev** [comment]
Alright, assigned number 30, since I don't think I've seen that yet.

**Comment by seberg** [comment]
Ah right sorry, that one is far along and should be moved soon as well.

**Comment by pentschev** [comment]
No worries @seberg. If everyone's fine with it, NEP-30 is good for me. :)

**Comment by seberg** [comment]
OK, let me put this in. Then you have a nice link for discussion soon, and the number is settled.

**Comment by pentschev** [comment]
Thanks @seberg. I'm sending to the mailing list now.

**Comment by jakirkham** [comment]
@pentschev, do you have a link to the mailing list thread that we can add here?

**Comment by pentschev** [comment]
@jakirkham sure, here it is: http://numpy-discussion.10968.n7.nabble.com/NEP-30-Duck-Typing-for-NumPy-Arrays-Implementation-td47379.html

**Pull request merged**
