### PR TITLE
DOC: Update docs after NumPy 1.15.3 release.

### PR DESCRIPTION
**Pull request by charris**
- Forward port 1.15.3-changelog.rst
- Forward port 1.15.3-notes.rst
- Minor fixes to RELEASE_WALKTHROUGH.rst.txt

[ci skip]

### CODE REVIEW

**Comment by adamchainz** [comment]
This and the 1.15.2 release notes don't appear at https://docs.scipy.org/doc/numpy/release.html , is something broken ? :)

**Comment by rgommers** [comment]
nothing is been broken, the upload is simply delayed.

**Comment by adamchainz** [comment]
Ok cool! Thanks ✨

**Comment by rgommers** [comment]
1.15.4 docs are up now. won't be doing the 1.15.2/3 ones, they're identical

**Comment by adamchainz** [comment]
Well they have appeared anyway!

**Pull request merged**
