### PR TITLE
DOC: Fix link quick-start in old random API functions

### PR DESCRIPTION
**Pull request by seberg**
This should fix the link to the quickstart tutorial, I think we should backport it and upload the modified docs.

I am also considering that we should change "New code should use" to "New code should prefer", this message can be confusing for non-advanced users, and while they should use it pressing too hard on it may be more frustrating than helpful.

### CODE REVIEW

**Comment by charris** [comment]
LGTM. How do you know this fixes the problem?

**Review by melissawm — APPROVED** [review]
LGTM, thanks @seberg !

**Comment by seberg** [comment]
I tried locally (was a bit painful, because I forgot this was a `.pyx`, heh.

In any case, here is the result: https://669-5652112-gh.circle-artifacts.com/0/doc/build/html/reference/random/generated/numpy.random.multinomial.html
 
(its a bit strange the build artifact link points to somewhere incorrect)

**Comment by charris** [comment]
Thanks Sebastian. I merged without waiting for travis to finish.

**Pull request merged**
