### PR TITLE
BUG: Fix mean padding with np.pad so that prepended values cannot bias appended ones

### LINKED ISSUE #11216: BUG: mean padding with np.pad may lead to different prepended and appended values
The bug was posted [on the mailing list](https://mail.python.org/pipermail/numpy-discussion/2018-April/077961.html). It boils down to the fact that `np.mean` with mean padding recomputes the mean from the half-padded array for the append step. Mathematically this would be OK, but in case of finite precision and near-zero means the near-zero prepended values may bias the recomputed mean in a way that prepended and appended values are different. Stripped-down example:

```
>>> import numpy as np
>>> a = np.array([-1, 2, -1]) + np.array([0, 1e-12, 0], dtype=np.float64)
>>> a = np.pad(a, (1, 1), 'mean')
>>> print(a)
[ 3.33362967e-13 -1.00000000e+00  2.00000000e+00 -1.00000000e+00
  3.33399974e-13]
```

As you can see, the first and the last values (both of which should be the mean) differ on the order of the machine epsilon. The prepended value is the true mean of the original array, the appended value is the mean where the prepended value is also taken into account. It was decided on the mailing list that [this is a bug](https://mail.python.org/pipermail/numpy-discussion/2018-April/077964.html).

### PR DESCRIPTION
**Pull request by adeak**
Fixes https://github.com/numpy/numpy/issues/11216.

In the appending step of `np.pad` we explicitly set the sampling size to be (at most) the original size of the array along the corresponding dimension. In case of `min` and `max` padding this problem doesn't arise, and I believe `median` padding should be safe too. I guess the code could be refactored such that statistics are only computed once when no `stat_length` is given, but I wanted to fix the original bug with minimal changes.

I also added `numpy/lib/tests/test_arraypad.py:test_check_mean_ignore_prepend` to test the problem, which fails in master and passes with this patch.

### CODE REVIEW

**Comment by adeak** [comment]
Ah, you're right, thanks. I only had symmetric chunks in mind.

My naive impression is that most use cases would use `None`, so perhaps it would be enough to default the chunk size to the size in the corresponding dimension in case of `None` input? That is, to do a similar override as in the patch, to be done for both mean/median and both left/ride. Or is that what you meant by "have the chunk sizes explicitly set up"? 

I still fear edge cases that might elude me, but since the problem seems to only arise when we "oversample" in either step, capping all the statistics to the actual corresponding dimension should hopefully solve this.

**Comment by charris** [comment]
I was thinking more along the lines of setting up the `stat_length` kwarg in the beginning. The problem here seems to be the use of `_validate_lengths` for both `pad_width` and `stat_length`.

**Comment by lagru** [comment]
> I think this might overlap with @lagru's (planned?) work in #11126

Yeah it certainly does. I'm currently adapting most of the stuff in arraypad.py which I'll upload it as WIP in the near future. Because the basic approach is changed from concatenation to insertion much of the stuff needs to be rewriten / adapted. To which extend this is necessary can be discussed in the coming PR.

But I don't want to block or hinder this PR on the promise of a not yet raised PR. I'll try to do this as fast as possible so that everything can be taken into consideration.

**Comment by adeak** [comment]
Thanks, @eric-wieser and @lagru. I'm pretty sure this bug is not particularly pressing, and it would be much simpler to have lagru's substantial refactor in first and tackle this bug after (assuming it still exists). Not to mention that my own fix would have to be changed anyway based on the above feedback. So I'll just close this for now and we can revisit it if necessary. Take your time, no need to rush :)

**Pull request closed without merging**
