### PR TITLE
MAINT: Update pavement.py

### PR DESCRIPTION
**Pull request by charris**
- Add README signing from scipy.
- Change NOTES.txt to README.

[ci skip]

### CODE REVIEW

**Comment by charris** [comment]
Minor changes to `pavement.py` script. Larger changes we should consider are removing the build scripts for Windows and OS X. They are harmless, but no longer used and they clutter up the file.

**Comment by charris** [comment]
@rgommers Is it worthwhile adding `*.tar.xz` files?

**Comment by rgommers** [comment]
No. distutils-sig wants to go to a single source archive format, and ``.tar.xz`` doesn't really provide much of interest.

**Comment by rgommers** [comment]
LGTM, merged. Thanks Chuck.

**Pull request merged**
