### PR TITLE
BUG: `take` casting logic with an `out=` argument

### PR DESCRIPTION
**Pull request by jaimefrio**
When it receives an `out` argument, `np.take` converts the `out` array to
the dtype of the array being taken from. This results in wrong `TypeError`s
being raised when `out` has a larger dtype than the array (and not being
raised when it has a smaller dtype, even though they should):

```
>>> a = np.arange(3, dtype=np.int16) + 128
>>> b = np.empty((3,), dtype=np.int8)
>>> a.take([0, 1, 2], out=b) # wrong, should raise an error
array([-128, -127, -126], dtype=int8)
>>> b = np.empty((3,), dtype=np.int32)
>>> a.take([0, 1, 2], out=b) # perfectly OK, but raises an error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array data from dtype('int32') to dtype('int16') according to the rule 'safe'
```

This PR makes an explicit casting check, then either sets `NPY_ARRAY_FORCECAST`
or explicitly raises the error.

The tests added check the logic for conversion between all pairs of ints and
floats only.

### CODE REVIEW

**Comment by charris** [comment]
Maybe time to take another look at this.

**Comment by seberg** [comment]
@jaimefrio this seems to still requires some work. Unless you comment/wish to continue, I would probably:

  * close the PR
  * create a new issues to note that there is a start for fixing this in this PR. (Or modify the existing one)

In a few weeks. Of course the PR can be reactivated at any time. (tag:PR-possibly-close)

In general this seems like a fairly straight forward task, although likely requiring some form of Deprecation.

**Comment by anirudh2290** [comment]
This has been stale from the point when @seberg last responded. Closing for now. Feel free to reopen @jaimefrio if you still wish to pursue this task.

**Comment by eric-wieser** [comment]
I think we should create an issue to continue tracking this behavior

**Comment by anirudh2290** [comment]
sure @eric-wieser, will do.

**Pull request closed without merging**
