### PR TITLE
ENH: Add `_get_madvise_hugepage` function

### LINKED ISSUE #21328: ENH: API to check whether Hugepages are enabled
### Proposed new feature or change:

It would be helpful to have a user facing API to be able to check whether Hugepages are enabled or not. This would help when trying to diagnose performance issues users may be seeing.

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/numpy/numpy/issues/21328

Provides a simple private function to query whether NumPy will try to use hugepages or not.

### CODE REVIEW

**Comment by jakirkham** [comment]
Yeah am all for improving on how we do the check to make it more accurate. Tried searching around for checks to see if hugepages were in use, but mostly just turned up system configs that may not be indicative either. Probably just missing something though

**Comment by seberg** [comment]
Hmmmpf, after searching a bit more, I also can't see anything that will really say whether hugepages are _actually_ used or not.
It seems to me that basically (on new kernels) NumPy will pretty much always signal madvise hugepages (for large allocations).  But, most (not ancient) kernels won't care anyway (they will have set it to `always` anyway.  Some embedded system may use `madvise` though.

But, I cannot find a way to figure out whether the kernel is actually giving us "transparent hugepages" or not.  It seems if you allocate some arrays and then query certain things, you can guess at it (or figure it out exactly if you are root).
But that all seems complicated to check programatically from within NumPy?

It seems to me that for `mmap` with `MAP_HUGETLB` you would actually be sure to get hugepages.  But that is a very different allocation mechanism, so I am not even sure it has to align...

**Comment by seberg** [comment]
Depending on the use-case, an interesting thought might be to write a small memory-handler that uses `mmap`, so that you can write (on new NumPy versions):
```
with mmapped_hugepages(desired_size=1024**3):
   arr = np.arange(100000000)
```
But, I suspect that isn't really what you are hoping for...

**Comment by jakirkham** [comment]
Thanks for digging into this more Sebastian 🙏 

Yeah it's tricky. Old kernels are not that uncommon (like HPCs) and unusual hardware comes up surprisingly frequently (at least for me 😄) so it can be useful to check. Ideally the system has it configured correctly, but how it needs to be configured may vary based on the system. So having a way to check within NumPy whether this is working is helpful.

Agree doing an allocation and then inspecting it would probably work (need to check syntax) and that this sort of strategy doesn't seem like the sort of thing NumPy should be doing at runtime. Maybe a trivial/small allocation could work in NumPy (though imagine hugepages wouldn't be used in this case for any number of reasons)? Though maybe that doesn't even make sense.

Having different allocators like this is interesting in its own right. Though as you guessed, for this use case am mostly looking for a way to sanity check a deployment/debug issues that come up.

**Comment by seberg** [comment]
So [this](https://github.com/numpy/numpy/blob/c4efd1f2f23bffb5de34a6348bcdbb33d7d0365a/numpy/__init__.py#L379-L405) is the logic currently used.  Basically, we don't use `madvise` on kernels older than 4.6.

An "overview" the situation seems to be:

* NumPy **1.16.0+** madvise hugepages [was added](gh-11957).  Interestingly, Julian there already notes to not set `/sys/kernel/mm/transparent_hugepage/defrag` to `always` but on 3.x kernels.
* NumPy **1.17.1**  Peter ensured madvise hugepages is given even if compiled on systems lacking it.  This was [backported](14309)
* NumPy **>= 1.19.0**  madvise hugepages used *unless* the kernel is *correctly* detected as <4.6 (the version parsing is pretty basic and can fail e.g. for `4.5-something`).  For NumPy 1.19+ `NUMPY_MADVISE_HUGEPAGE=0` and `NUMPY_MADVISE_HUGEPAGE=1` will enforce one or the other. [PR](gh-15769)

The last one was because people complained about [big slowdowns](gh-15545) and it seemed that kernels before 4.6 were the problem (again to do with defragmentation settings).

But, of course I can imagine that the heuristic is not reasonable on HPC systems or so.  If just because they got their kernel set up right with the defrag.

---

Considering that the logic isn't quite trivial (i.e. parsing may fail) should we just put this in and hope it will be useful?

**Comment by jakirkham** [comment]
It wouldn't hurt to have it.

We've marked it private. So if we need to change it in some big way or remove it, that shouldn't be an issue.

If we think of better heuristics, we can also update this.

If there's a docstring or function name, that would be clearer we could try that as well.

**Comment by seberg** [comment]
OK, I tweaked it to return `False` if the OS is not linux (and the `#ifdef`'s will cause `madvise` to definitely never be called).  Planning to just put it in later.

**Comment by seberg** [comment]
Thanks @jakirkham, lets see if it helps in those debugging situations.

**Comment by jakirkham** [comment]
Thanks Sebastian! 😀

**Pull request merged**
