### PR TITLE
BLD: update vendored Meson to 1.5.2

### LINKED ISSUE #27531: numpy 2.0.1 build issue on ibm AIX OS
### Describe the issue:

I am trying to build numpy 2.0.1 on AIX OS with ibm-clang_r compiler. numpy is using meson build in this version and I am hitting issue -

$ python -m build --wheel --no-isolation .
* Getting build dependencies for wheel...
* Building wheel...
+ /tmp/3392379693/python/bin/python /home/user/numpy/2.0.1/numpy-2.0.1/vendored-meson/meson/meson.py setup /home/user/numpy/2.0.1/numpy-2.0.1 /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i/meson-python-native-file.ini
The Meson build system
Version: 1.4.99
Source dir: /home/user/numpy/2.0.1/numpy-2.0.1
Build dir: /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i
Build type: native build
Project name: NumPy
Project version: 2.0.1

../meson.build:1:0: ERROR: Unable to detect linker for compiler `ibm-clang_r -Wl,--version -L/tmp/3392379693/python/lib -I/tmp/3392379693/python/include -I/tmp/3392379693/python/include/openssl`
stdout:
stderr: ld: 0706-012 The -- flag is not recognized.
.ibm-clang: error: linker command failed with exit code 255 (use -v to see invocation)

seems linker ld on AIX does not support --version flag.  tried few suggestion found on internet but could not get past this issue. 

does meson build supported on AIX ? could some one please suggest way out from here?

PS - I was able to build numpy 1.26.4  which had setup.py . ( did not use meson build for this ) simply built whl file using python setup.py bdist_wheel, but with 2.0.1 this is not the case as setup.py is removed from this version and have to build using meson build.

### Reproduce the code example:

```python
$ python -m build --wheel --no-isolation .
* Getting build dependencies for wheel...
* Building wheel...
+ /tmp/3392379693/python/bin/python /home/user/numpy/2.0.1/numpy-2.0.1/vendored-meson/meson/meson.py setup /home/user/numpy/2.0.1/numpy-2.0.1 /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i/meson-python-native-file.ini
The Meson build system
Version: 1.4.99
Source dir: /home/user/numpy/2.0.1/numpy-2.0.1
Build dir: /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i
Build type: native build
Project name: NumPy
Project version: 2.0.1

../meson.build:1:0: ERROR: Unable to detect linker for compiler `ibm-clang_r -Wl,--version -L/tmp/3392379693/python/lib -I/tmp/3392379693/python/include -I/tmp/3392379693/python/include/openssl`
stdout:
stderr: ld: 0706-012 The -- flag is not recognized.
.ibm-clang: error: linker command failed with exit code 255 (use -v to see invocation)
```

### Error message:

_No response_

### Python and NumPy Versions:

python version 3.12.6
numpy version 2.0.1

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by rgommers**
- Incorporate https://github.com/numpy/meson/pull/15 (many fixes, including support for free-threading on Windows)
- Incorporate https://github.com/numpy/meson/pull/17
- Closes gh-27531

### CODE REVIEW

**Comment by rgommers** [comment]
The only CI failures are unrelated (due to gh-27548). The BLAS detection in those two failing jobs worked fine, so this looks about ready.

Will add another fix and retest.

**Comment by charris** [comment]
Is this based off current main? The macos failure might go away with a rebase.

**Comment by rgommers** [comment]
Yeah it's up-to-date, only a few commits behind. The macOS conda-forge failure is coming in with the AIX linker change in the vendored Meson it looked like, the job is passing on the first commit in this PR. Still puzzled by it though, not sure what's going on there.

I'll drop the change for now - the primary goal here is to update to Meson 1.5.x and get free-threading on Windows going.

**Comment by rgommers** [comment]
Ugh, the macOS failure is a flake that just happened to also touch on `icc`. It shows up on gh-27544 from 3 days ago as well, and also on several other issues from years ago (e.g., gh-17635). None of the other issues have an explanation.

**Comment by mattip** [comment]
I see the test run is using xdist with two workers. Is there something in the test that is not thread safe? Maybe some other test is importing and changing `sys.modules` in parallel with this one?

**Comment by mattip** [comment]
The failures are in numpy.distutils which is deprecated. Can we avoid testing whether any of its API has changed?

**Comment by rgommers** [comment]
> The reason I ask is that it was common until a cache update.

Hmm, not impossible, although I think my initial PR included that fix already (it was anchored on a commit only 2 days old). That said, your "wrong `setuptools` version" is quite plausible.

> The failures are in numpy.distutils which is deprecated. Can we avoid testing whether any of its API has changed?

An easy way to do that would be to bump this CI job to use Python 3.12 (assuming nothing else is broken there). I'll check that.

**Comment by mattip** [comment]
Did you mean to change this? https://github.com/numpy/numpy/blob/855bed7eb4b1fa59215cc52dcf5ff4b6d2a5b13d/.github/workflows/macos.yml#L28

**Comment by charris** [comment]
Note that the problems seemed to start with a new release of 3.11.

**Comment by rgommers** [comment]
> Did you mean to change this?

Yes indeed. Done in gh-27555.

**Comment by rgommers** [comment]
Okay, this is finally ready now. I updated the PR description with what it adds/fixes. Should be back-portable for 2.1.3.

**Comment by charris** [comment]
Thanks Ralf.

**Pull request merged**
