### PR TITLE
Fix array_equal and array_equiv issue

### PR DESCRIPTION
**Pull request by jayvius**
array_equal() and array_equiv() don't work for string arrays and record arrays. This is because those methods use numpy.equals ufunc for comparison, and there are no equal ufuncs registered for strings and record arrays. Replace numpy.equals with '==' array operation, which handles strings and record arrays. Fixes #3015. Closes #146.

### CODE REVIEW

**Comment by mohtamohit** [comment]
Hey @charris @jayvius, is there a way I can see that this support for strings for np.equal was rolled out in which version of numpy?

**Comment by mattip** [comment]
`git tag --contains 6dc709a5aa0b17b5a74b7456d7cbd2580d9063f6` says this PR is in v1.8.0. The comment above mentions backporting to 1.7.x, maybe it was done there too.

Is there a problem?

**Comment by mohtamohit** [comment]
Ok great. I'm not sure if I totally understand if the issue being discussed here is related to the following. But, with numpy version 1.16, I try to run the following and it fails. Do we have an open issue to support it or is it already fixed in later versions?

```
In [23]: y = np.array(['abc', 'pqr'])
In [24]: y.dtype.type
Out[24]: numpy.str_
In [25]: np.equal(y, y)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-da698f6c7142> in <module>
----> 1 np.equal(y, y)
TypeError: ufunc 'equal' did not contain a loop with signature matching types dtype('<U3') dtype('<U3') dtype('bool')

```
Thanks in advance.

**Comment by mohtamohit** [comment]
It seems we have one [here](https://github.com/numpy/numpy/issues/6122), thanks in advance.

**Pull request merged**
