### PR TITLE
ENH: Add new ``numpy.ma.*`` aliases

### PR DESCRIPTION
**Pull request by takanori-pskq**
Related to #13114, separated from #16300. Now parameter name `fill_value` collides in `np.ma.full` (see #16300 ).

### CODE REVIEW

**Comment by BvB93** [comment]
Can you also add the new aliases to [`numpy/ma/__init__.pyi`](https://github.com/numpy/numpy/blob/master/numpy/ma/__init__.pyi)?
Annotating them as `Any` (just like the rest) should be fine.

**Comment by takanori-pskq** [comment]
Added type annotations.

**Review by rossbar — COMMENTED** [review]
`full` and `full_like` were the only problematic ones that jumped out to me from my previous review of #16300 (see [this comment](https://github.com/numpy/numpy/pull/16300#pullrequestreview-466282097) specifically). `ones_like`, `zeros_like`, and the `*split` functions avoid this problem and have nice tests.

I know you just split this one off from another PR, but I think everything aside from the `full*` functions is mergeable. If you were willing, the changes related to `full*` could be reverted/split off elsewhere to prevent that from blocking the rest.

**Comment by takanori-pskq** [comment]
Added release note.

**Comment by bsipocz** [comment]
Closing this PR now as its content is conflicting with `main` here. The rebased version can be found in #21998.

**Pull request closed without merging**
