### PR TITLE
BUG: Overflow in tan and tanh for large complex values

### PR DESCRIPTION
**Pull request by ewmoore**
This is a fix for gh-2321.  I've imported the implementation for ctanh from FreeBSD's math library which handles large arguments correctly.  Which fixes this bug and the equivalent bug in np.tan.  

The problem here is that importing the function into npy_math_complex.c and adding a config check causes us to use the implementation from glibc on Linux, which also has this bug.  Although it seems to have been fixed in glibc last April (http://sourceware.org/bugzilla/show_bug.cgi?id=11521). 

I see several things that could be done here, the easiest is probably to use our version of ctanh unconditionally.  Although there are a multitude of ways to go about that, for instance should I remove the implementation from npy_math_complex.c and just place it directly in umath/funcs.inc, where the buggy version was?  Or should I just remove the config check and add a note about it somewhere? Or some other choice all together.

Some kind of test will also need to be added, but I thought I'd get some input on how to handle this before doing anything else.

### CODE REVIEW

**Comment by charris** [comment]
Current state on Fedora 21.
```
In [2]: np.tanh(372+1j)
Out[2]: (nan+nan*j)
```
Looks like library function is not used. gcc 4.9.2 gives `1.000000000000000000+0.000000000000000000i`, where denormals look to be flushed to zero, probably a side affect of how the function compiles. The code for that is
```
#include <stdio.h>
#include <math.h>
#include <complex.h>

int main(int argc, char **args)
{
    double complex z = 372.0 + 1.0 * I;
    double complex res = ctanh(z);

    printf("%20.18f%+20.18fi\n", creal(res), cimag(res));
}
```

Do we have a policy on denormals? Do we need one?

I haven't followed this PR, but we should bring it to conclusion.

**Comment by charris** [comment]
@ewmoore IIRC, the changes to the code generators is already merged and the documentation for `frexp` and `ldexp` moved.

I managed to get these patches applied without too much work, there was one test failure
```
FAIL: test_ldexp_overflow (test_umath.TestLdexp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/Workspace/numpy.git/build/testenv/lib64/python2.7/site-packages/numpy/core/tests/test_umath.py", line 548, in test_ldexp_overflow
    assert_equal(ncu.ldexp(2., imax), np.inf)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib64/python2.7/site-packages/numpy/testing/utils.py", line 322, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 1.0
 DESIRED: inf
```

**Comment by charris** [comment]
Rebased and squashed in #5510.

**Comment by charris** [comment]
I'd be happy to just use it when there are no system supplied functions. GCC seems OK now. I think the thing to do is run the improved tests now and then and submit bug reports to the relevant projects. If they can't fix things, then we might consider using these functions instead.

**Comment by charris** [comment]
One thing that does bother me is that the system complex functions do not seem to be detected, at least on Fedora 21.

**Comment by ewmoore** [comment]
I guess this discussion should move else where, but do you mean that the system functions are not detected here or with master?  Do the system functions pass the tests?

**Comment by charris** [comment]
With master, I've got that figured out now, which I assume you already did ;) I'm working through things and will probably take your work and modify it a bit.

**Pull request closed without merging**
