### PR TITLE
DOC: clarify the effect of None parameters passed to ndarray.view

### PR DESCRIPTION
**Pull request by adeak**
Issue https://github.com/numpy/numpy/issues/14875 suggests that passing explicit `None`s to `ndarray.view` will lead to surprising (non-default) behaviour. Although the behaviour is due to an implementation detail (i.e. that `view` is written in C), it might be helpful to make this quirk explicit in the documentation.

Related things that might need tackling:

1. There's a reference to core/defmatrix.py at the top of core/_add_newdocs.py, but I can't seem to find this file. Perhaps this reference should be removed or fixed while we're at it.
2. Masked arrays have a similar API for `.view`, yet there passing `None` works as expected, since it's all written in Python. Perhaps this should be mentioned in those docs? I'm leaning towards "no".
3. The description of the `dtype` parameter references a hypothetical `a` array, which makes sense in the interactive help but seems undefined in [the online docs](https://numpy.org/devdocs/reference/generated/numpy.ndarray.view.html#numpy.ndarray.view) where the header says `ndarray.view` rather than `a.view`. This is probably a more ubiquitous feature in the docs, but I figured I'd note it in case this needs fixing too.
4. I rephrased the parameter descriptions to emphasize the _omission_ of these parameters, but I also added a paragraph to the notes explaining the behaviour when explicit `None`s are passed. If this  latter addition ends up staying, would it make sense to have a test for `dtype(None) is dtype('float_')` (assuming there isn't one already, I haven't looked yet)? In case this ever gets changed, [though not very likely](https://github.com/numpy/numpy/issues/14875#issuecomment-552280923), we'd want to update these notes as well.

### CODE REVIEW

**Comment by eric-wieser** [comment]
I think the signature should change too, to:
```diff
-a.view(dtype=None, type=None)
+a.view([dtype][, type])
```
which reflects the style used in the [redacted part of PEP1040](https://github.com/python/peps/pull/1040/files).

**Comment by adeak** [comment]
@eric-wieser thanks for the tip! I pushed a commit with your first version (because I didn't update the page in time). I don't remember seeing this notation in numpy yet, but then I found it in [the `arange` docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html). I also like your latter suggestion.

Either way my paragraph about `None`s in the notes is now superfluous (since nobody said that `None`s are special), so I've removed that part.

**Comment by eric-wieser** [comment]
> I don't remember seeing this notation in numpy yet

I added the notation for the ufunc docstrings such as `np.add`, but after I did that it looks like they backed the notation out of PEP 457!

**Comment by adeak** [comment]
Thank you for the feedback! Fair enough about the `type=None` case.

I'm wondering if adding the `.. note` would make more sense under the `dtype` parameter's description, but I couldn't find any examples for this placement and I don't know if sphinx would play nicely with that, so I put it above the parameter descriptions where all the other notes seem to be.

I didn't notice the square brackets in the ufuncs, my brain seems to stop reading the signature at `x1, x2, /`...

**Comment by eric-wieser** [comment]
> my brain seems to stop reading the signature at ...

Sounds like a feature to me, the extra arguments are irrelevant to 90% of users anyway.

**Review by eric-wieser — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @adeak

**Comment by seberg** [comment]
Seems good to me, note that I would not mind if someone goes around and deprecates the `None` use in this function.

**Comment by adeak** [comment]
Thank you, all. Does this also mean that the 4 points I raised at the end of the PR description should be left alone?

@seberg would it make sense to deprecate explicit `None` here if there's no longer a suggestion of that being the default value? As long as `dtype(None)` works, it makes sense (for a given value of "sense") to allow that here too.

**Comment by seberg** [comment]
Well, `np.dtype(None)` being float, is a bit strange to be honest (and maybe could be deprecated). Note that `dtype=None` should always be identical to the default behaviour. But for `view` the default behaviour is to _keep_ the current dtype.

It is just that for functions that do not "keep" a dtype, `None` is the default, which is `float64`.

**Comment by seberg** [comment]
Anyway, I do not mind either way, lets just leave it unless you/someone feels strong about it.

**Pull request merged**
