### PR TITLE
MAINT: Add missing placeholder annotations

### PR DESCRIPTION
**Pull request by BvB93**
This PR adds (placeholder) annotations for a few objects that were missed in https://github.com/numpy/numpy/pull/17104.

In the wake of https://github.com/numpy/numpy/issues/18270 I did a double check of all placeholder annotations and identified a few 
that were previously missing, mostly module-level `__all__` attributes. 

In addition there were two groups of public functions that were missing from their module's `__all__`.
This has now been rectified:
* `np.ctypeslib.as_ctypes_type`
* Five functions in `np.rec`.

### CODE REVIEW

**Comment by BvB93** [comment]
https://github.com/numpy/numpy/pull/18302/commits/12d99670040c265a615694fd3b8ae1492807c93f and https://github.com/numpy/numpy/pull/18302/commits/c21509a595eea2cf9d64893a58adb5abcce68bb1 would qualify for a backport in my opinion.
The remaining two commits aren't nearly as important; I'd say that can remain exclusive to >= 1.21 unless someone has a strong opinion about.

**Comment by charris** [comment]
It would be best if you made the backport PRs.

**Comment by BvB93** [comment]
> It would be best if you made the backport PRs.

Will do; I'll create the backport after this PR has been merged.

**Comment by charris** [comment]
Thanks Bas.

**Pull request merged**
