### PR TITLE
DOC: Fix doctest formatting in `rot90()` examples

### PR DESCRIPTION
**Pull request by Peque**
Current [generated documentation looks like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.rot90.html):

screenshot from 2018-05-31 13-11-23

After applying this patch:

screenshot from 2018-05-31 13-08-07

### CODE REVIEW

**Comment by charris** [comment]
Hmm, how are you running doctests?

**Comment by Peque** [comment]
@charris I am not. :smile:

Just made the change based on the `make html` generated HTML output, which is currently broken as-is (as you can see in the first screenshot and [in the current official documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.rot90.html) as well).

Should I be running doctests? I guessed if that was the case it would be included in the project's CI processes so I would not need to care about that. :thinking:

**Comment by charris** [comment]
We don't currently run doctests, but will probably do so again in the future. The problem we have is that testing should ignore print formatting changes and other such minor things, so we need our own doctester. There are very few, and ancient, uses of `<BLANKLINE>` in NumPy. The rendering is a problem, though. @stefanv @jnothman Thoughts?

**Comment by Peque** [comment]
@charris Yeah, I kept the blank line because I thought that could matter if doctests were to be run. If they are currently not being run, and if you plan on tweaking the doctester to ignore those differences in the output, then it might be better to simply remove the blank line. This way the documentation is rendered correctly too.

Anyway `<BLANKLINE>` is apparently correct doctest syntax.

**Comment by pv** [comment]
For Scipy we chose to do it so that we just omit all blank lines (so
that it renders OK) and run the doctests with
doctest.NORMALIZE_WHITESPACE enabled.

**Comment by charris** [comment]
@pv That sounds reasonable. @Peque It sounds like the fix would be dropping the blank line. There are six other current uses of BLANKLINE, might fix those up also, but in another PR. We should probably document that somewhere.

**Comment by Peque** [comment]
@charris Okay, force-pushed a new commit with the change.

**Comment by Peque** [comment]
PS: there is already a "not necessary" mention about `<BLANKLINE>` in `doc/sphinxext/doc/format.rst:441`. Maybe you want to change that to "not recommended".

**Comment by mattip** [comment]
Note that the source for `doc/sphinxext` is the repo https://github.com/numpy/numpydoc

**Comment by charris** [comment]
Hmm, that change in the documentation went in with numpydoc v0.7, the NumPy 1.14 releases are using v0.6. However, looking at the 1.15 dev docs, which are supposed to use v0.8, there is that same problem. So either the documentation is in error, or the documentation build wasn't using the new numpydoc.

I believe @stefanv  added the developer doc builds, and @jnothman maybe there is a problem with the html creation.

**Comment by charris** [comment]
Thanks @Peque .

**Pull request merged**
