### PR TITLE
MAINT: Change file extension of ma README to rst.

### PR DESCRIPTION
**Pull request by rossbar**
GitHub not currently rendering the rST correctly because of the `.txt` extension.

Changing the extension fixes the rendering on GitHub

### CODE REVIEW

**Comment by mattip** [comment]
Maybe this file should join the doc/Py3K.rst.txt in an archive file since it has value as a historical design document. Currently neither document is reverenced in the documentation,

**Comment by rossbar** [comment]
Is there an archive within numpy/numpy for historical docs or should a directory be created in numpy/archive for historical documentation? Or perhaps there is a different location that is more appropriate?

**Comment by seberg** [comment]
We could make a folder to host both somewhere in https://github.com/numpy/archive not super discoverable, but neither is it right now. And, while maybe a shame to remove, it does not seem important enough to convert to a NEP.

**Comment by charris** [comment]
There isn't a lot of material, so perhaps just create an archive directory in doc. We also have a changelog directory whose content is not published, but which I think is useful, I search it occasionally. Perhaps it could also be moved.

**Comment by charris** [comment]
Thanks @rossbar . Other considerations aside, the rst extension makes sense.

**Pull request merged**
