### PR TITLE
Remove single file option

### PR DESCRIPTION
**Pull request by charris**
This is a first cut for comment. There is a bit of additional style cleanup that can be done.

### CODE REVIEW

**Comment by njsmith** [comment]
What's here looks good to me. Is there more you want to do before merging?

For extra cleanup points, we could switch on `-fvisibility=hidden` in gcc and delete NPY_NO_EXPORT entirely. But that's probably best done as a separate PR.

**Comment by charris** [comment]
There is a now empty header file to remove, and several defines that can be moved upward. I'll finish those up.

**Comment by charris** [comment]
I take that back, no empty header files and I think the rest of the cleanup can take place when umath is merged with multiarray. The `npy_pycompat.h` file is effectively empty as it just includes another header file, but we might as well leave it alone for the moment, as it is included in almost everything.

So go ahead and merge if you are so inclined ;)

**Comment by njsmith** [comment]
Let's do this :-)

**Pull request merged**
