### PR TITLE
 BUG: Protect divide by 0 in multinomial distribution.

### LINKED ISSUE #20483: BUG: random.multinomial causes floating point exception if `pvals` has size 0
### Describe the issue:

Calling `random.multinomial` with `pvals` of size zero (empty list, empty tuple, etc.) produces a floating point exception rather than raising a `ValueError`.

### Reproduce the code example:

```python
import numpy as np

# produces floating point exception
_ = np.random.multinomial(0, [])
```

### Error message:

```shell
Floating point exception (core dumped)
```

### NumPy/Python version information:

1.20.3 3.9.0 (default, Oct 12 2021, 08:34:59) 
[GCC 8.3.0]

### PR DESCRIPTION
**Pull request by bashtage**
Guard against empty pvals
closes #20483

### CODE REVIEW

**Comment by bashtage** [comment]
Does not affect `Generator` which requires `pvals` to be non-empty, and raises if it is.

**Comment by seberg** [comment]
LGTM, thanks.  I guess this is obscure enough that we don't have to add a `.. versionchanged::` tag.

One question:  Does this change what happens if `pvals` is a scalar value?  Because `len()` would previously fail, but I am not sure that conversion to array doesn't just do `np.array(1., ndmin=1)` here, which means that a single `pval` that is not a sequence is promoted to a sequence.

Fix might be to just use `0, 1` and raise a custom error if the array is 0-D?  Or it is to do nothing and declare this a case where `pvals` is always a 1-D sequence and we allow promoting scalars to 1-D (although I am a bit unsure in this case compared to things like `axis=`).

**Comment by bashtage** [comment]
In 1.16 a float p-val raises:

```
In [2]: np.random.multinomial(10,.4)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-b4117eaf8ee3> in <module>
----> 1 np.random.multinomial(10,.4)

mtrand.pyx in mtrand.RandomState.multinomial()

TypeError: object of type 'float' has no len()
```

In this version it raises as well,

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-b4117eaf8ee3> in <module>
----> 1 np.random.multinomial(10,.4)

mtrand.pyx in numpy.random.mtrand.RandomState.multinomial()

ValueError: object of too small depth for desired array
```

**Comment by bashtage** [comment]
I have now caught scalar pvals and raise TypeError so that the exception matches.  The error message is more useful now.

**Pull request merged**
