### PR TITLE
Maintenance/1.12.x

### PR DESCRIPTION
**Pull request by nravic**

### CODE REVIEW

**Comment by charris** [comment]
Don't know what you were trying to do, but there is something very wrong here.

**Comment by bashtage** [comment]
@charris Did you mean to close the maintenance/1.12.x _branch_?

**Comment by pv** [comment]
This is not the maintenance/1.12.x branch, and "closing branches" is an operation that does not exist in git.

**Comment by bashtage** [comment]
Is this a github special?  

https://github.com/numpy/numpy/branches

Never seed the tag 'closed' on a branch.

**Comment by eric-wieser** [comment]
Yeah, that's pretty weird

**Comment by njsmith** [comment]
Pretty sure that's GitHub's way of saying "there is a pull request proposing to merge this branch into something else, and that pull request is closed". Helpful for feature branches, but extremely confusing in this case where someone created a nonsensical pull request on a standalone branch.

I guess it might be possible to delete this PR, but other than that I think we just ignore the weird message and move on.

**Comment by bashtage** [comment]
The next commit on that branch might restore its status to normal.

**Comment by charris** [comment]
I wonder what would happen if I hit the delete branch button? Does it refer to the user's branch? Did the user actually ask us to commit a `numpy/numpy` branch? If so, how?

This looks like a github bug with porentially nasty side effects.

**Comment by charris** [comment]
I did an empty commit and push and that cleared up the flag. Still annoying.

**Comment by njsmith** [comment]
> I wonder what would happen if I hit the delete branch button? Does it refer to the user's branch?

There is no user branch here – this pull request's "source" was set to the "maintenance/1.12.x" branch in the numpy/numpy repository, and the "target" was set to the "master" branch in the numpy/numpy repository. (You can tell because if you scroll up to the top, where it says "wants to merge XX commits into XX from XX", there's no mention of the repositories; compare to an ordinary pull request. This is useful for development patterns where a team shares a single repo and develops feature branches collaboratively within it, but confusing for us.) So if you had hit delete branch, it would have deleted the actual-real-live maintenance/1.12.x branch.

**Comment by bashtage** [comment]
If you had an up to date copy you could have immediately pushed it back I
think.

**Comment by eric-wieser** [comment]
> I did an empty commit and push and that cleared up the flag. Still annoying.

Presumably you could now force-push back to the previous commit to clean up?

**Comment by juliantaylor** [comment]
it is no big deal as you can just repush it, but there seem to be some trolls around trying to annoy people.
This happened here already once, I mentioned it on the mailing list back then.

**Comment by eric-wieser** [comment]
Based on @nravic/numpy, this looks like an honest mistake to me - the submitted was indeed working on a patch.

**Comment by charris** [comment]
> Presumably you could now force-push back to the previous commit to clean up?

I was going to leave it in, it's harmless.

> Based on @nravic/numpy, this looks like an honest mistake to me

What bothers me is that he should not have had the permissions to make such a PR.

**Comment by eric-wieser** [comment]
Seems like that's by design. I can go to https://github.com/scipy/scipy/branches, click compare, and then click the pull request button.

**Pull request closed without merging**
