### PR TITLE
ENH: Use AVX-512F for complex number arithmetic, absolute, square and conjugate

### PR DESCRIPTION
**Pull request by r-devulap**
This patch implements complex add, subtract, multiply, square, absolute and conjugate using AVX-512F for both CFLOAT and CDOUBLE. This patch not only improves microbenchmarks but also high level workloads. Specifically, it speeds up the program for computing the Mandelbrot set by nearly 3.5x (added to the benchmarks). Detailed benchmark numbers run in Intel i9-7900X CPU are provided below: 

      before           after         ratio
    [11654979]       [14756955]
    <master>         <cmplx-simd>
      16.8±0.2ms       14.2±0.4ms     0.84  bench_avx.AVX_cmplx_arithmetic.time_ufunc('multiply', 4, 'F')
     8.42±0.03ms       6.97±0.2ms     0.83  bench_avx.AVX_cmplx_funcs.time_ufunc('conjugate', 2, 'D')
     15.5±0.04ms      12.6±0.02ms     0.81  bench_avx.AVX_cmplx_arithmetic.time_ufunc('multiply', 2, 'F')
      6.93±0.2ms       5.34±0.3ms     0.77  bench_avx.AVX_cmplx_arithmetic.time_ufunc('subtract', 1, 'D')
      10.0±0.2ms      7.23±0.05ms     0.72  bench_avx.AVX_cmplx_funcs.time_ufunc('square', 2, 'D')
      8.53±0.2ms       5.87±0.1ms     0.69  bench_avx.AVX_cmplx_funcs.time_ufunc('conjugate', 4, 'F')
     8.28±0.02ms      5.47±0.03ms     0.66  bench_avx.AVX_cmplx_funcs.time_ufunc('conjugate', 2, 'F')
      5.25±0.3ms       3.10±0.1ms     0.59  bench_avx.AVX_cmplx_arithmetic.time_ufunc('add', 1, 'F')
      10.0±0.2ms       5.85±0.3ms     0.58  bench_avx.AVX_cmplx_funcs.time_ufunc('square', 1, 'D')
      5.26±0.1ms       3.04±0.1ms     0.58  bench_avx.AVX_cmplx_arithmetic.time_ufunc('subtract', 1, 'F')
      11.8±0.5ms       6.74±0.1ms     0.57  bench_avx.AVX_cmplx_arithmetic.time_ufunc('multiply', 1, 'D')
      10.3±0.2ms      5.52±0.09ms     0.53  bench_avx.AVX_cmplx_funcs.time_ufunc('square', 2, 'F')
        7.75±1ms       4.12±0.1ms     0.53  bench_avx.AVX_cmplx_funcs.time_ufunc('conjugate', 1, 'D')
      10.4±0.2ms       5.36±0.3ms     0.52  bench_avx.AVX_cmplx_arithmetic.time_ufunc('add', 1, 'D')
      45.6±0.3ms      21.2±0.07ms     0.46  bench_avx.AVX_cmplx_funcs.time_ufunc('absolute', 1, 'D')
      48.2±0.2ms       22.1±0.3ms     0.46  bench_avx.AVX_cmplx_funcs.time_ufunc('absolute', 4, 'D')
      46.2±0.8ms       20.7±0.5ms     0.45  bench_avx.AVX_cmplx_funcs.time_ufunc('absolute', 2, 'D')
     10.0±0.07ms       3.32±0.1ms     0.33  bench_avx.AVX_cmplx_funcs.time_ufunc('square', 1, 'F')
      8.30±0.2ms      2.62±0.04ms     0.32  bench_avx.AVX_cmplx_funcs.time_ufunc('conjugate', 1, 'F')
      9.52±0.02ms      2.64±0.02s     0.28  bench_avx.Mandelbrot.time_mandel
      37.8±0.7ms       9.53±0.2ms     0.25  bench_avx.AVX_cmplx_funcs.time_ufunc('absolute', 4, 'F')
      38.4±0.2ms      9.49±0.02ms     0.25  bench_avx.AVX_cmplx_funcs.time_ufunc('absolute', 2, 'F')
      15.7±0.3ms      3.83±0.08ms     0.24  bench_avx.AVX_cmplx_arithmetic.time_ufunc('multiply', 1, 'F')
      39.2±0.4ms       8.21±0.4ms     0.21  bench_avx.AVX_cmplx_funcs.time_ufunc('absolute', 1, 'F')

### CODE REVIEW

**Comment by mattip** [comment]
There is a new test failure.

If we do go down the path of universal intrinsics, could other platforms could reuse this code or is it somehow specific to X86_64?

**Comment by r-devulap** [comment]
> There is a new test failure.

I am unable to reproduce this test failure on my end on machines with and without AVX-512F. Still looking into ..

**Comment by r-devulap** [comment]
> If we do go down the path of universal intrinsics, could other platforms could reuse this code or is it somehow specific to X86_64?

This patch (just my previous patches) heavily use k-masks and masked instructions (mask_load, mask_store, maskz_compress, maskz_div, etc.) which I am not sure are supported on other architectures. I don't this we can reuse this as is. (Some of them are even specific to AVX-512F and are not available on AVX2 and SSE as well)

**Comment by r-devulap** [comment]
> > There is a new test failure.
> 
> I am unable to reproduce this test failure on my end on machines with and without AVX-512F. Still looking into ..

Never mind, able to reproduce it now.

**Comment by r-devulap** [comment]
Fixed the test failure

**Comment by r-devulap** [comment]
Didn't like the fact that I was using only half the register width, so I re-wrote absolute ufunc to improve performance further. Mandelbrot set runs nearly 5x faster with this change.

**Comment by r-devulap** [comment]
Rebased with master to fix conflicts. Also, adding information @rgommers wanted on performance patches: 

1) Details of Microbenchmarks are provided above. 
2) High level benchmark (added to the benchmarks in this patch): Computing Mandelbrot set is sped by 5x
3) All the AVX code is enabled through runtime dispatch
4) Code bloat: Using gcc-7.4 on ubuntu 18.04, it increases from 22728816 Bytes to 22802976 Bytes which is about 72Kb

**Comment by mattip** [comment]
LGTM. I will wait for a little while for other reviewers before merging. This will provide a benchmark for comparison when and if we rewrite these loops for universal intrinsics.

**Comment by mattip** [comment]
Thanks @r-devulap

**Comment by mkoeppe** [comment]
This seems to have broken compilation of numpy on debian-jessie (gcc 4.9.2) -- see https://trac.sagemath.org/ticket/29766#comment:71

**Comment by mattip** [comment]
It seems we should not even try to use AVX512 intrinsics if the compiler is <4.9.2.

**Comment by r-devulap** [comment]
@mkoeppe  I am taking a look.

**Comment by r-devulap** [comment]
@mkoeppe Let me know if this patch fixes your problem: https://github.com/numpy/numpy/pull/16871

**Comment by mkoeppe** [comment]
> @mkoeppe Let me know if this patch fixes your problem: #16871

Tricky to test for me at the moment, as numpy master's `setup.py sdist` seems broken

**Pull request merged**
