### PR TITLE
DOC: Include `np.long` in `arrays.scalars.rst`

### PR DESCRIPTION
**Pull request by mtsokol**
Addresses #25015.

Hi @ngoldbaum, in this PR I updated `arrays.scalars.rst` so it includes `np.long` and updated diagrams. (the other one-line changes are fixes for some warnings that I found when building locally)

### CODE REVIEW

**Review by ngoldbaum — COMMENTED** [review]
I think there's a desire to keep the `.dia` file and only modify that file and regenerate the png and PDF, from inside [Dia](https://wiki.gnome.org/Apps/Dia/) see https://github.com/numpy/numpy/pull/23252#issuecomment-1437641781. I'm able to open the file locally if I do `sudo apt install dia` then `dia path/to/file.dia`.

If that ends up being too cumbersome we could come back to how to handle the diagram files the numpy docs have in a few places but please give it a try first.

**Comment by mtsokol** [comment]
@ngoldbaum Sure! I restored&updated the `.dia` file and regenerated the new png/pdf diagram. 

Nevertheless, I would argue that all diagrams could be migrated to e.g. Google Drawings or draw.io (both free), as the Dia is ancient and rather cumbersome to use. (I hope there isn't another reason to stick to it)

**Comment by ngoldbaum** [comment]
> Nevertheless, I would argue that all diagrams could be migrated to e.g. Google Drawings or draw.io (both free), as the Dia is ancient and rather cumbersome to use. 

Sure, I think work happened along these lines in #18501, but the diagrams never got updated . Ideally (I think) the source for the diagram would live in the docs. I'd argue it makes the most sense to use the built-in support in sphinx for the dot format, see e.g. see e.g. https://github.com/numpy/numpy/issues/18501#issuecomment-790799206.

> (I hope there isn't another reason to stick to it)

I'm pretty sure the only reason is inertia.

**Review by ngoldbaum — APPROVED** [review]
LGTM! @rossbar can you confirm what I'm saying to Mateusz about the diagrams is correct before I merge this?

**Comment by ngoldbaum** [comment]
Let's just go ahead and merge this, we can fix doc issues in a followup.

**Pull request merged**
