### PR TITLE
minor docstring correction in numpy.percentile()

### PR DESCRIPTION
**Pull request by megies**

### CODE REVIEW

**Comment by charris** [comment]
Could you rewrite the commit message? See the guidelines in `doc/source/dev/gitwash/development_workflow.rst`. Note that "minor docstring correction" isn't very informative.

Otherwise, LGTM.

**Comment by megies** [comment]
I rewrote the commit message and force-pushed the new commit. Sorry about being pretty concise with the message earlier, I just made the change right away online at github very quickly in between working on other stuff when I noticed this docstring glitch.

**Comment by charris** [comment]
No problem. But now that you are here I'm going to be difficult ;) The summary line is too long, how about something like `DOC: correct wrong variable reference in percentile docstring`. If you put `[skip ci]` in the message body, the tests will be skipped. They don't check docstrings.

**Comment by megies** [comment]
No problem. ;)
Couldn't do without numpy, so spending some seconds is the least I can do.

Was considering going for `DOC:` but then I saw `MAINT:` mentioning "typos" (http://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message). Anyway, I'll change the message to `DOC:`, no problem. Your proposed first line is still too long according to my vim git plugin, so I'll make it even shorter.. :P

Nice to have a commit message routine that skips tests, but from a repo maintainer point of view I'd probably still prefer tests executed for external PRs instead of a "carte blache" green light. Well, this one's overly trivial, so yeah, there you go.. ;)

**Comment by charris** [comment]
Thank @megies. Agree that the prefixes are a bit ambiguous. What vim git plugin do you use?

**Comment by megies** [comment]
Well, documentation is in awesome shape, for such a big project especially. :)

@charris, here's what's currently in my `.vim/bundle`, nothing special really:
```
DirDiff.vim
file-line
gundo.vim
nerdtree
rainbow_parentheses.vim
supertab
syntastic
tagbar
vim-fugitive
vim-gitgutter
```

The syntax highlighting for overly-long git commit first lines is actually a vim builtin for my Debian system vim on jessie.. :)  (file /usr/share/vim/vim74/syntax/gitcommit.vim in https://packages.debian.org/jessie/all/vim-runtime/filelist)

**Comment by charris** [comment]
Thanks. I'll give some of those a try.

**Comment by juliantaylor** [comment]
this only went into the maintenance branch, it also needs to go into master or it will get lost

**Comment by megies** [comment]
Oh, OK. I assumed that the current maintenance branch would routinely get merged into `master`.. will somebody cherry-pick or should I open another PR?

**Comment by charris** [comment]
Forward ported in #6421. @juliantaylor Thanks for the catch.

**Pull request merged**
