### PR TITLE
MAINT: Add python 3.6 support to suppress_warnings

### LINKED ISSUE #8176: Test failures on Python 3.6.0b2
They seem to result from nesting `warnings.catch_warnings` and `suppress_warnings`. The problem is new in 3.6 and may be either be a Python bug, or something we are doing in `suppress_warnings` that we shouldn't.
```
FAIL: test_deprecations.TestComparisonDeprecations.test_array_richcompare_legacy_weirdness
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 371, in test_array_richcompare_legacy_weirdness
    assert_warns(FutureWarning, lambda: np.arange(2) == "a")
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling <lambda>

======================================================================
FAIL: test_deprecations.TestComparisonDeprecations.test_none_comparison
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 315, in test_none_comparison
    assert_warns(FutureWarning, operator.eq, np.arange(3), None)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling eq

======================================================================
FAIL: test_deprecations.TestComparisonDeprecations.test_void_dtype_equality_failures
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 359, in test_void_dtype_equality_failures
    assert_warns(FutureWarning, lambda: struct1 == 1)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling <lambda>

======================================================================
FAIL: test_deprecations.TestIdentityComparisonDeprecations.test_identity_equality_mismatch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 415, in test_identity_equality_mismatch
    assert_warns(FutureWarning, np.equal, a, a)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling equal

======================================================================
FAIL: test_deprecations.TestRankDeprecation.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 272, in test
    assert_warns(np.VisibleDeprecationWarning, np.rank, a)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling rank

======================================================================
FAIL: test_utils.test_suppress_warnings_decorate_no_record
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/tests/test_utils.py", line 945, in test_suppress_warnings_decorate_no_record
    assert_(len(w) == 1)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 90, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by seberg**
Python 3.6 has two methods for showing warnings, so we have to support
both ways (strictly speaking, on python 3.6 itself only the new would
probably be needed).

Also adds the _filters_mutated() call to replace manual registry
clearing. This is basically the fix that newer python versions have
to avoid the issue making the manual clearing unnecessary.

Closes gh-8176

### CODE REVIEW

**Comment by seberg** [comment]
For the curious, I commented on the python issue about the introduction that a release note would have been nice. I am also not 100% sure if they already decided whether to leave the function with a leading underscore or not.

**Comment by seberg** [comment]
Btw. just saw that it seems that by default, if you create a merge request, you make the branch accessible for the upstream devs. Not sure if its worth much, but could avoid a full creation of a new PR in some cases.

**Comment by seberg** [comment]
Also, especially for cleaning up (with forced push), it could be annoying also.

**Comment by charris** [comment]
Thanks Sebastian, that was quick. Yes, it would have helped if the change had been mentioned in the 3.6 release notes.

**Pull request merged**
