### PR TITLE
DOC: AI generated examples for ma.reshape

### PR DESCRIPTION
**Pull request by otieno-juma**
I used AI Llama 3 to help create these.
@bmwoodruff and I reviewed them.
[skip actions] [skip azp] [skip cirrus]

reshape fuction pic

### CODE REVIEW

**Comment by eagunn** [comment]
@otieno-juma Compared to your example code for #26827, I had a much harder time parsing this example code. I think it is because you do not assign the results of the reshape to a variable and then explicitly have that variable print out. That is, your examples looks like:
```
    >>> a = np.ma.array([1, 2, 3, 4])
    >>> np.ma.reshape(a, (2, 2))
    masked_array(
      data=[[1, 2],
            [3, 4]],
      mask=False,
      fill_value=999999)
```
and I think they would be easier to understand if they looked like:
```
    >>> a = np.ma.array([1, 2, 3, 4])
    >>> x = np.ma.reshape(a, (2, 2))
    >>> x
    masked_array(
      data=[[1, 2],
            [3, 4]],
      mask=False,
      fill_value=999999)
```

**Comment by otieno-juma** [comment]
Thank you very much, @eagunn, for the feedback. We will improve our prompts to enhance those edges.

**Comment by rgommers** [comment]
Converting to draft pending review of the first such PR: gh-26827.

**Comment by charris** [comment]
@otieno-juma Could you rebase this and the other pending PRs?

**Comment by otieno-juma** [comment]
@bmwoodruff, All the checks have passed. could you please review it?

**Comment by bmwoodruff** [comment]
I ran the tests locally on my machine. Looks good. @charris, this should be ready for you to review. @otieno-juma , you can remove the draft status.

**Comment by charris** [comment]
Thanks @otieno-juma . Was there a response to @eagunn ? I didn't have a problem parsing the result, just wondering.

**Pull request merged**
