### PR TITLE
BUG recarray slices should preserve subclass.

### PR DESCRIPTION
**Pull request by mhvk**
Aims to solve #6949 -- quite likely important for FITS records in astropy as well, so cc @embray.

### CODE REVIEW

**Comment by charris** [comment]
LGTM.

**Comment by westphae** [comment]
LGTM too--fixes my use cases and makes sense for other uses I tried.  Thanks for the very quick, elegant fix!

**Comment by ahaldane** [comment]
Looks good from over here too.

**Comment by embray** [comment]
Not immediately obvious to me why this regressed in 1.10.2 but sounds good.

**Comment by charris** [comment]
Appveyor seems dead in the water at the moment. Nothing here should depend on windows, so merging.

**Comment by charris** [comment]
Thanks Marten.

**Pull request merged**
