### PR TITLE
MAINT: Rename INSTALL.rst.txt to INSTALL.rst

### PR DESCRIPTION
**Pull request by ShobanChiddarth**

### CODE REVIEW

**Comment by mattip** [comment]
A while ago there were other projects linking directly to some of our pages. I can't remember which projects (SciPy)? or where, so I am not really excited about changing the file names unless we are sure it will not break something else. Why does the filename bother anyone?

**Comment by ShobanChiddarth** [comment]
It will bother VS Code (And Probably other editors) to preview in rst Syntax

Before Renaming: 
Before Renaming

After Renaming (Locally):
1. Syntax highlights (with extension)
   Syntax highlights
2. Preview
   Preview-1
   Preview-2

**Comment by mattip** [comment]
I found it: there used to be a link to this from [scipy](https://github.com/scipy/scipy/blob/59e6539cf80dc04b16b0f0ab52343381f0a7a2fa/scipy/linalg/tests/test_build.py#L54), but on latest HEAD that file is removed. They also have a copy of this file with the same name. Note this file is linked internally from [HOWTO_RELEASE.rst.txt](https://github.com/numpy/numpy/blame/main/doc/HOWTO_RELEASE.rst.txt#L14).

**Comment by ShobanChiddarth** [comment]
OK. So you mean you are not going to rename it?

**Comment by mattip** [comment]
I would be in favor of renaming the file (@charris might also have an opinion) now that SciPy no longer depends on it. In order to be complete, this PR should also change the reference in HOWTO_RELEASE.rst.txt. 

There are more files with this naming convention, what do you think we should do with them? `find . -name '*rst.txt'` yeilds
```
./doc/HOWTO_RELEASE.rst.txt
./doc/records.rst.txt
./doc/ufuncs.rst.txt
./doc/Py3K.rst.txt
./doc/C_STYLE_GUIDE.rst.txt
./doc/EXAMPLE_DOCSTRING.rst.txt
./doc/DISTUTILS.rst.txt
./doc/RELEASE_WALKTHROUGH.rst.txt
./doc/HOWTO_DOCUMENT.rst.txt
./doc/TESTS.rst.txt
./INSTALL.rst.txt       <--- this PR

```

Some of them are linked to from SciPy (using `git grep '*rst.txt'` and looking for numpy):
- scipy/doc/API.rst.txt links to https://github.com/numpy/numpy/blob/main/doc/DISTUTILS.rst.txt
- scipy/doc/source/dev/contributor/runtests.rst links to https://github.com/numpy/numpy/blob/main/doc/TESTS.rst.txt

so when renaming we should leave the older name as a symlink (for a couple of years) and the links in SciPy should change to point to actual documentation rather than source files.

**Comment by charris** [comment]
I don't mind renaming as long as it doesn't break anything. I'm guessing that the original choice was to avoid editor problems before there was rst support. I want to rename the two walkthroughs in any case.

**Comment by ShobanChiddarth** [comment]
Ok. Then can I make another commit renaming all the files?
(Now also Notepad supports .rst files)

**Comment by charris** [comment]
> Then can I make another commit renaming all the files?

Yes. You can also squash into one commit and do a force push if you are familiar with that.

**Comment by ShobanChiddarth** [comment]
> You can also squash into one commit and do a force push if you are familiar with that.

Sorry, I'm not. I committed the rest. Thanks.

**Comment by mattip** [comment]
In addition to renaming, the following references need changing (I excluded the ones in release notes and changelogs):
```
$ git grep "rst.txt"
doc/HOWTO_RELEASE.rst.txt:- INSTALL.rst.txt
doc/HOWTO_RELEASE.rst.txt:- https://github.com/numpy/numpy/blob/main/doc/HOWTO_RELEASE.rst.txt
doc/Makefile:   @# the instructions in doc/HOWTO_RELEASE.rst.txt
doc/neps/nep-0045-c_style_guide.rst:recommended that this proposal, which originated as ``doc/C_STYLE_GUIDE.rst.txt``,
doc/source/dev/howto_build_docs.rst:.. _HOWTO RELEASE: https://github.com/numpy/numpy/blob/main/doc/HOWTO_RELEASE.rst.txt
doc/source/dev/releasing.rst:.. include:: ../../HOWTO_RELEASE.rst.txt
doc/source/dev/releasing.rst:.. include:: ../../RELEASE_WALKTHROUGH.rst.txt
doc/source/reference/distutils_guide.rst:.. include:: ../../DISTUTILS.rst.txt
doc/source/reference/testing.rst:.. include:: ../../TESTS.rst.txt
```

**Comment by ShobanChiddarth** [comment]
Sorry for the delay.

What do changing references mean and how do I do that?

**Comment by HaoZeke** [comment]
In keeping with @mattip, I'm actually -0 on this. Editors can be configured to change the font-locking (or syntax highlighting) and if these are RST files, won't they cause an error by not being in a `toctree` (a warning actually, but CircleCI changes warnings to errors)?

**Comment by mattip** [comment]
> What do changing references mean and how do I do that?

Everywhere there is a reference to `*.rst.txt` you should change that to the new `*.rst`

**Comment by ShobanChiddarth** [comment]
I changed it. Sorry for the delay every time. I study in a boarding school and I rarely get holidays. That is the reason for the 1 month (nearly) delay. I just twisted my foot and came home to take a rest. That's how I am able to work on this pr now. I hope every issue is solved right now (as I made another commit changing all the references. Please let me know if there are more conflicts.

**Comment by ShobanChiddarth** [comment]
df1fd69 was a commit made after changing references said by @mattip https://github.com/numpy/numpy/pull/20949#issuecomment-1028952067
> In addition to renaming, the following references need changing (I excluded the ones in release notes and changelogs):
> 
> ```
> $ git grep "rst.txt"
> doc/HOWTO_RELEASE.rst.txt:- INSTALL.rst.txt
> doc/HOWTO_RELEASE.rst.txt:- https://github.com/numpy/numpy/blob/main/doc/HOWTO_RELEASE.rst.txt
> doc/Makefile:   @# the instructions in doc/HOWTO_RELEASE.rst.txt
> doc/neps/nep-0045-c_style_guide.rst:recommended that this proposal, which originated as ``doc/C_STYLE_GUIDE.rst.txt``,
> doc/source/dev/howto_build_docs.rst:.. _HOWTO RELEASE: https://github.com/numpy/numpy/blob/main/doc/HOWTO_RELEASE.rst.txt
> doc/source/dev/releasing.rst:.. include:: ../../HOWTO_RELEASE.rst.txt
> doc/source/dev/releasing.rst:.. include:: ../../RELEASE_WALKTHROUGH.rst.txt
> doc/source/reference/distutils_guide.rst:.. include:: ../../DISTUTILS.rst.txt
> doc/source/reference/testing.rst:.. include:: ../../TESTS.rst.txt
> ```

But there were more references than those
```git
$ git grep ".rst.txt"
doc/changelog/1.15.0-changelog.rst:* `#10583 <https://github.com/numpy/numpy/pull/10583>`__: MAINT: Fix typos in DISTUTILS.rst.txt.
doc/changelog/1.15.0-changelog.rst:* `#11578 <https://github.com/numpy/numpy/pull/11578>`__: DOC: link to TESTS.rst.txt testing guidelines, tweak 
testing...
doc/changelog/1.16.0-changelog.rst:* `#11084 <https://github.com/numpy/numpy/pull/11084>`__: DOC: link to TESTS.rst.txt testing guidelines, tweak 
testing...
doc/changelog/1.17.0-changelog.rst:* `#12602 <https://github.com/numpy/numpy/pull/12602>`__: DOC: Update RELEASE_WALKTHROUGH.rst.txt.
doc/changelog/1.17.0-changelog.rst:* `#13729 <https://github.com/numpy/numpy/pull/13729>`__: DOC: Merge together DISTUTILS.rst.txt#template-files" and distutils.r…
doc/changelog/1.17.0-changelog.rst:* `#13781 <https://github.com/numpy/numpy/pull/13781>`__: DOC: Update TESTS.rst.txt for pytest
doc/changelog/1.19.0-changelog.rst:* `#15043 <https://github.com/numpy/numpy/pull/15043>`__: DOC: Update HOWTO_RELEASE.rst.txt
doc/changelog/1.21.0-changelog.rst:* `#18048 <https://github.com/numpy/numpy/pull/18048>`__: DOC: Update TESTS.rst.txt
doc/source/release/1.7.0-notes.rst:NumPy C Style Guide added (``doc/C_STYLE_GUIDE.rst.txt``).
doc/source/release/1.8.0-notes.rst:doc/HOWTO_BUILD_DOCS.rst.txt for how to access the content.
```
So I done `$ git reset HEAD~`, changed those references, made the commit 1d51bed and force pushed it to this pr.

**Comment by ShobanChiddarth** [comment]
Yes, I pushed all the changes to ShobanChiddarth:patch-1. But about the conflicting files, I get this message in github

> This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
> #### Conflicting files
> ```
> INSTALL.rst.txt
> doc/C_STYLE_GUIDE.rst.txt
> doc/EXAMPLE_DOCSTRING.rst.txt
> doc/RELEASE_WALKTHROUGH.rst.txt
> doc/source/reference/distutils_guide.rst
> ```

I don't have write access so I am not able to solve those conflicts. Only you can do that. Thanks.

**Comment by ShobanChiddarth** [comment]
I did it. Anything else?

**Review by mattip — APPROVED** [review]
I rebased and force-pushed again to clear merge conflicts. If this passes CI I think it is good to merge. If there are further nits we missed we can fix them in future PRs.

**Comment by ShobanChiddarth** [comment]
Tests were passed.
image
Anything else?

**Comment by mattip** [comment]
> I want to rename the two walkthroughs in any case.

@charris do you still want to do this?

**Comment by charris** [comment]
@mattip It isn't pressing, but I thought starting both with `WALKTHROUGH` would make them sort better when listing. So at some point I'll make a PR to rename them:

- `WALKTHROUGH_BRANCHING.rst`
- `WALKTHROUGH_RELEASING.rxt`

**Comment by ShobanChiddarth** [comment]
> Thanks @ShobanChiddarth

Welcome @mattip, regards

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @ShobanChiddarth! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Comment by ShobanChiddarth** [comment]
@mattip I missed one file [doc/records.rst.txt](https://github.com/numpy/numpy/blob/main/doc/records.rst.txt) and I am creating another pr to rename that one too. Are there any special rules to follow to link one pr to another or it is just simple as I started my first pr (#20949, this one)?

**Pull request merged**
