### PR TITLE
DOC: user guide update

### PR DESCRIPTION
**Pull request by pv**
Updates to the user guide:
- Remove all placeholders and warnings about incompleteness. They do no good.
- Add the "tentative numpy tutorial" from the wiki. There should be a simple tutorial in the documentation. Fixed the `from numpy import *` imports, fixed up the code (cf. sphinx-build doctest builder checks), and removed all discussion about `np.matrix`.
- Add the "Numpy for matlab users" page from the wiki. Removed some opinion-based discussion. More cleanup could be done.

I'm not sure how much further effort I'm willing to spend cleaning up the old material, so help is appreciated.

### CODE REVIEW

**Comment by rgommers** [comment]
This looks great!

**Comment by charris** [comment]
Thanks Pauli.

**Comment by ev-br** [comment]
> I'm not sure how much further effort I'm willing to spend cleaning up the old material, so help is appreciated.

I for one might be ready to spend some effort. Some idea of what is to be done would be helpful.

**Comment by njsmith** [comment]
One thing to consider for out of date material is whether it should just be
deleted in favor of a link to something like scipy-lectures.org's numpy
tutorial, or software carpentry's.

**Comment by pv** [comment]
The main thing would be just to read the added texts through, and remove or rewrite parts that are bad or contain placeholder notices. My comment was mainly on the numpy-to-matlab page.

The basics tutorial appears reasonably up to date, as basics in numpy haven't changed for a long time. I think it makes sense to have a brief tutorial also in Numpy documentation.

**Comment by rgommers** [comment]
http://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html looks pretty good. Although this needs a few tweaks.... :

    # Make all numpy available via shorter 'num' prefix
    import numpy as num
    # Make all matlib functions accessible at the top level via M.func()
    import numpy.matlib as M

**Pull request merged**
