### PR TITLE
DOC: Updates following NumPy 1.16.4 release.

### PR DESCRIPTION
**Pull request by charris**
[ci skip]

### CODE REVIEW

**Comment by mattip** [comment]
Thanks @charris

**Comment by seberg** [comment]
It seems this causes CI failures because of the removal of `::` moving them to `:`. Which in turn causes an `*` in the file glob pattern inside the indented block below to be seen as a bold face emphasis character.

Is the correct thing to revert the double `::` or escaping the `*`?

**Comment by tylerjereddy** [comment]
Oh, it snuck through because of the ci skip I guess

**Comment by charris** [comment]
That oddity has always been there, it isn't new. The `*` can be escaped, but then is reads funny as text. But if it is now causing problems we might as well escape it, I find I read the rendered text online when making a release instead of in an editor.

**Comment by charris** [comment]
Maybe we should use explicit markup for that code block, `.. code-block::`

**Comment by charris** [comment]
Viewing the file, apparently the `::` is needed to mark a code block, which is why the old rendering problem now causes an error.  It is funny as the code shows up as a quote.

**Comment by seberg** [comment]
Chuck, do you have a preferred fix here? The :: seems a bit  better to me then quoting right now to be honest (although ugly), but maybe the best is the `.. code-block::`

**Pull request merged**
