### PR TITLE
TST: add a static typing test for memoryviews as ArrayLikes

### LINKED ISSUE #16612: Add an `ArrayLike` test case for memoryview
See the discussion in https://github.com/numpy/numpy/pull/16558/files#r440321349.

We should add a test case that memoryviews can be typed as `ArrayLike`. It works in practice because they are `Sequence`s, but we should test that explicitly.

### Reproducing code example:
Add a test case like:

```python
from numpy.typing import ArrayLike

x = b'foo'
v: ArrayLike = memoryview(x)
```

### PR DESCRIPTION
**Pull request by levistovall**
See #16612

### CODE REVIEW

**Comment by person142** [comment]
Looks good @levistovall; CI failures should be unrelated. I've restarted them to see if they pass on the second attempt.

**Comment by person142** [comment]
Ah actually they will continue to fail because of some new 3.9 deprecations. Definitely unrelated though.

**Comment by person142** [comment]
Thanks @levistovall!

**Comment by levistovall** [comment]
Happy to be able to contribute a couple of lines. :)

**Pull request merged**
