### PR TITLE
Update pavement.py

### PR DESCRIPTION
**Pull request by muhammadanas0716**

### CODE REVIEW

**Comment by Mukulikaa** [comment]
Hi @muhammadanas365, can you include a description of what this PR aims to achieve and a more descriptive title, please?

**Comment by muhammadanas365** [comment]
Sure. Go ahead.

**Comment by muhammadanas365** [comment]
It was kinda a testing. I like just made some strings more productive. Which I don't think is a necessity.

**Comment by Mukulikaa** [comment]
> It was kinda a testing. I like just made some strings more productive. Which I don't think is a necessity.

It is preferred that you try out these things in your own fork so that the CI is not burdened here. IMO, renaming the object is not an improvement on the existing script so I think this PR can be closed.

**Comment by muhammadanas365** [comment]
Sure. Won't do again 🙂

**Pull request closed without merging**
