### PR TITLE
BUG: fix regression in 1.13.x in distutils.mingw32ccompiler.

### LINKED ISSUE #9553: AttributeError when compiling f2py using mingw in Python 3 and miniconda (suggested patch)
Overview:
-----------
Attempting to compile fortran90 code using mingw using f2py in Python 3 on Windows 7 via miniconda. Got an error, made a patch that works for me, but I figured I should post the issue so it can be resolved officially.

Package info:
* python 3.6.1
* conda 4.3.24
* numpy 1.13.1

Steps:
-------
a. Followed steps 1 through 4 given at [this link](https://www.scivision.co/f2py-running-fortran-code-in-python-on-windows/).
b. In Anaconda prompt: `>f2py -c myCodes.f -m myCodes`

myCodes.f:
```c     NAME OF THIS FILE - myCodes.f
c     -----------------------------

c     This subroutine prints hello World
c     on the screen

      subroutine hwd()

          print*, 'Hello World !'

      end subroutine hwd
```

Results:
--------
image

Self-patch:
------------
The issue arises due to Lines 265 through 268 in numpy/distutils/mingw32compiler.py, which has
```
    lib_dirs = []
    for stem in stems:
        for folder in sub_dirs:
            lib_dirs = os.path.join(stem, folder)
```
This sets to lib_dirs as a string, which then throws an error in line 272, when we try to append to it.

I modified the code as follows and was able to compile fortran using f2py:
```
    lib_dirs = []
    for stem in stems:
        for folder in sub_dirs:
            lib_dirs.append(os.path.join(stem, folder))
```

Hopefully this patch won't affect any other functionality.

### PR DESCRIPTION
**Pull request by rgommers**
Issue was introduced in gh-8454.

Thanks to @jennirinker for pointing out the issue and fix.  Closes gh-9553.

### CODE REVIEW

**Comment by rgommers** [comment]
@rolk this fixes an issue that was introduced in one of your PRs. Somehow it did work for you before, maybe due to ``stems`` being an empty list. Want to double check this PR?

**Comment by charris** [comment]
Heh. I'll put this in after a wait for @rolk.

**Comment by rolk** [comment]
> that looks like a clear bug

I think that sums it up. I'll go fetch my brown paper bag now.

> Somehow it did work for you before, maybe due to stems being an empty list

Nope, faulty test methodology: `_build_import_library` eventually dies for me anyway, so at one point I must have stopped checking the branch where `_check_for_import_lib` returns False, missing out on bugs in `find_python_dll` after refactoring. Mea culpa.

I think that the reason that this bug surfaces is that Miniconda (in contrast to the full Anaconda distribution) does not contain the import library for the Python runtime DLL, and then the branch is triggered.

And on that note: @jennirinker: I found the objdump+dlltool process very brittle; if you ever experience strange crashes in system calls, you could try to build it as a wheel in Anaconda and then install it in the Miniconda environment afterward.

**Comment by charris** [comment]
Thanks Ralf.

**Pull request merged**
