### PR TITLE
BUG: Make extensions compilable with MinGW on Py2.7

### PR DESCRIPTION
**Pull request by rolk**
The original changeset 1c8ecc7 to make extensions compilable with MinGW
used the base_prefix attribute unconditionally. However, this is not
available in versions before Python 3.3.

This changeset introduces a check for whether the attribute is available
so that the code will work without errors also on Python 2.7. However,
this may lead to surprising results when compiling in a virtualenv.

Hat tip to Diorcet Yann (@diorcety) for pointing out this problem.

### CODE REVIEW

**Comment by charris** [comment]
@rolk Are you happy with this now?

**Comment by rolk** [comment]
@charris Yes I am happy, but I would wait for @kmuehlbauer to report back some testing results;  I don't have a 2.7 stack on Windows myself. (I changed the title of the patch to the right format BTW - don't know what got into me the first time; I think I edited it from a format-patch writeout).

**Comment by kmuehlbauer** [comment]
@rolk @charris I'm sorry. I'm mistakingly thought, conda-forge can test this patch at https://github.com/conda-forge/numpy-feedstock. But this doesn't work ATM, because conda-forge uses OpenBlas for which there is no windows build. 

@ocefpaf mentioned, that he could make use of this fix. So maybe he can report back something.

**Comment by ocefpaf** [comment]
> @ocefpaf mentioned, that he could make use of this fix. So maybe he can report back something.

I haven't got to it yet. (My time with a Windows laptop is limited.)
I'll report ASAP.

**Comment by charris** [comment]
I'm going to make a 1.13.1 release in couple of days, so this PR won't make it unless it is finished up soon.

**Comment by rolk** [comment]
@charris I would advice to put it in regardless; I presume that @diorcety got it to work when he wrote the first draft, and most importantly we know that MinGW on Py2.7 is broken without it. (And even if it stays broken, the fallout wouldn't be that bad: I don't think any of the big distributions use MinGW at the moment)

**Comment by diorcety** [comment]
Yes, i'm currently using it, it works well. In my case I'm currently using with MSVC with another minor fix https://github.com/diorcety/numpy/commit/4862fee943912374c2316ef6c609110c31036663

**Comment by charris** [comment]
OK. Thanks @rolk .

**Pull request merged**
