### PR TITLE
DOC: add hypothesis test dependency in README and PyPI long-description

### PR DESCRIPTION
**Pull request by rgommers**
This update was requested on the mailing list a few months ago: https://mail.python.org/archives/list/numpy-discussion@python.org/message/JCRWCUAORV7KO6RVI7YLOOPZEZF2PZ4J/

[ci skip]

### CODE REVIEW

**Comment by charris** [comment]
Might mention `test_requirements.txt` for testing locally with `runtests.py`.  `mypy` is required for testing annotations and `pytz` for testing datetime.

**Comment by rgommers** [comment]
Hmm, I'd rather not go further than this minor edit in the PyPI description, that's enough to make `numpy.test()` work. `test_requirements.txt` is also not accessible from PyPI/sdist/wheel. Better to have that kind of thing in the docs. 

And also, we should get rid of requirements files over time - this belongs in `pyproject.toml`, where we already have:
```
[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "asv",
    "mpmath",
    "gmpy2==2.1.0rc1",
    "threadpoolctl",
    "scikit-umfpack",
]
doc = [
    "sphinx!=3.1.0, !=4.1.0",
    "pydata-sphinx-theme>=0.6.1",
    "sphinx-panels>=0.5.2",
    "matplotlib>2",
    "numpydoc==1.1.0",
]
dev = [
    "mypy",
    "typing_extensions",
    "pycodestyle",
    "flake8",
]
```

**Comment by charris** [comment]
Thanks Ralf.  The `*_requirements.txt` files are in the source distributions. Can pip be used to install the contents of  `pyproject.toml` without building from source? I don't normally use pip for local installation, it doesn't handle multiple versions well.

**Comment by rgommers** [comment]
> The `*_requirements.txt` files are in the source distributions. Can pip be used to install the contents of `pyproject.toml` without building from source? I don't normally use pip for local installation, it doesn't handle multiple versions well.

You can do `pip install .[test]` or `pip install .[dev]` to install the optional dependencies from a local checkout. To do that from PyPI, because the metadata lives inside the sdist/wheels, you'd have to download that first. Just doing `pip install pytest hypothesis` is better I'd say then `pip install numpy[test]`.

**Comment by charris** [comment]
We are looking at slightly different use cases. I made the `release_requirements.txt` file so that the next release manager could set up their environment, I use it myself when upgrading fedora and the default Python changes. Same for the other files. If all those dependencies could be managed through `pyproject.toml` I'd be happy to move their contents there. It would be easier to keep everything in sync that way.

**Comment by rgommers** [comment]
Ugh, looked at some bad discussions in the Pip issue tracker - this does not seem supported, and there's no intent to support it. Separate `requirements.txt` files for each use case it is. Bad design, but what can we do 🤷🏼

**Pull request merged**
