### PR TITLE
ENH: Improve clang-cl compliance

### PR DESCRIPTION
**Pull request by bashtage**
Avoid unnecessary MSVC path when using clang-cl

This patch lets NumPy 2.0.0-dev compile using clang-cl on Windows.

### CODE REVIEW

**Comment by bashtage** [comment]
There are 4 test failures

```
FAILED ..\build-install\Lib\site-packages\numpy\core\tests\test_einsum.py::TestEinsum::test_einsum_sums_int8
FAILED ..\build-install\Lib\site-packages\numpy\core\tests\test_einsum.py::TestEinsum::test_einsum_sums_uint8
FAILED ..\build-install\Lib\site-packages\numpy\core\tests\test_scalarmath.py::TestBitShifts::test_shift_all_bits[<<-l]
FAILED ..\build-install\Lib\site-packages\numpy\core\tests\test_scalarmath.py::TestBitShifts::test_shift_all_bits[<<-L]
```

**Comment by mattip** [comment]
Thanks for reviving clang-cl compliance.

The einsum tests seem sensitive to SIMD semantics, and were [xfailed on macos](https://github.com/numpy/numpy/blob/5047644af5fc65830fdadcf930695d4a941448c8/numpy/core/tests/test_einsum.py#L614) with the move to meson. I don't remember seeing the `shift_all_bits` tests fail before.

**Comment by bashtage** [comment]
Any idea why `np.show_config` is platform dependent?  When I ran it on Cygwin it said the keyword `mode` was not available.  I don't see anything in `__config__.py.in` that would make this happen.

**Comment by rgommers** [comment]
The `mode` keyword is new, so perhaps there was a version mixup somehow?

**Review by rgommers — APPROVED** [review]
This all LGTM now, thanks @bashtage.

For the new CI job, onfigure output is clean:
```
 C compiler for the host machine: clang-cl (clang-cl 16.0.6)
C linker for the host machine: lld-link lld-link 16.0.6
C++ compiler for the host machine: clang-cl (clang-cl 16.0.6)
C++ linker for the host machine: lld-link lld-link 16.0.6
```

The build log is pretty messy, but that's mostly a lot of repeats of:
```
 In file included from C:\hostedtoolcache\windows\Python\3.11.4\x64\Include\Python.h:86:
C:\hostedtoolcache\windows\Python\3.11.4\x64\Include/cpython/pytime.h(184,12): warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
    struct timeval *tv,
           ^
C:\hostedtoolcache\windows\Python\3.11.4\x64\Include/cpython/pytime.h(190,12): warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
```
plus some `lapack_lite` operator precedence warnings. Nothing that requires addressing now or is specific to `clang-cl`.

**Pull request merged**
