### PR TITLE
ENH: Raise C++ standard to C++17

### PR DESCRIPTION
**Pull request by seiko2plus**
relates #22710

### CODE REVIEW

**Comment by charris** [comment]
Hmm, the 390 failures look legit, although I can't tell exactly what is going on. The compiler is gcc 9.4.0.

**Comment by seiko2plus** [comment]
> Hmm, the 390 failures look legit, although I can't tell exactly what is going on. The compiler is gcc 9.4.0.
```Bash
+grep -v _configtest log

+tee warnings

+grep -E 'warning\>'

/tmp/tmpo5cfeoce/test.cpp:7:8: warning: ‘if constexpr’ only available with ‘-std=c++17’ or ‘-std=gnu++17’

+grep -vE 'manifest_maker: standard file '\''-c'\'''

+grep -vE 'no previously-included files matching'

+grep -vE 'ld returned 1|no files found matching'
```


This negative warning triggered by: 
https://github.com/numpy/numpy/blob/920564c7955ddd074bb6e555618cd37d3d78f1a1/setup.py#L264-L278

The issue here is that we have to test whether the compiler supports C++17 by default before specifying any flags to avoid forcing C++17 on compilers that allow C++20 and beyond by default.

**Comment by seiko2plus** [comment]
pass `-Werror` during the test should pass the build, I will give it a try.

**Comment by charris** [comment]
Thanks Sayed.

**Pull request merged**
