### PR TITLE
Correct my email address

### PR DESCRIPTION
**Pull request by cowlicks**

### CODE REVIEW

**Comment by jaimefrio** [comment]
Merged, thanks.

**Comment by cowlicks** [comment]
@jaimefrio I got an email about getting 1 free "prime coin" for this commit. Weird, did NumPy agree to start doing this?

**Comment by rgommers** [comment]
no this is basically spam. I'll ask them to remove Numpy from the list. I think that there are two of these now; from the other one Numpy and Scipy were removed already

**Comment by charris** [comment]
On Mon, Feb 2, 2015 at 12:23 PM, Ralf Gommers <notifications@github.com>
wrote:

> no this is basically spam. I'll ask them to remove Numpy from the list. I
> think that there are two of these now; from the other one Numpy and Scipy
> were removed already
>

Seems to be more of an advertisement aimed at getting people to enroll.
Reminds me of banks that used to offer a "free" set of steak knives for
opening a savings account...

Chuck

**Comment by rgommers** [comment]
Asked to block numpy here: https://github.com/sigmike/peer4commit/issues/121

**Pull request merged**
