### PR TITLE
DOC: add a "make show" command to doc/Makefile

### PR DESCRIPTION
**Pull request by rgommers**
Opens the front page of the docs built with `make html` in the default web browser.

Idea copied from SciPy

`[ci skip]`

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Seems like a nice addition that could help simplify the docs workflow. One question: should the `show` target depend on `html-build` so that users will not get a file not found error in the browser? I find myself almost always chaining the building and viewing together (`make html && firefox build/html/index.html`), but maybe there's a case for having a stand-alone viewing command.

**Comment by rgommers** [comment]
That sounds like it would be a little annoying, I often build without looking in the browser each time, or vice versa. If you'd want that, you probably should add a `build-and-show` command.

**Comment by rossbar** [comment]
I guess it really boils down to personal preference, so the current proposal SGTM.

It doesn't matter much, but might as well add `show` to the `.PHONY` list. Other than that, LGTM!

**Comment by rgommers** [comment]
> might as well add `show` to the `.PHONY` list.

thanks, done

**Comment by charris** [comment]
Thanks Ralf.

**Pull request merged**
