### PR TITLE
test python3.5 32 bit debug with gcc 5

### PR DESCRIPTION
**Pull request by juliantaylor**
not merge material, but lets see what breaks with new stuff

### CODE REVIEW

**Comment by rgommers** [comment]
good idea. doesn't seem too bad. The errors on

    import mmap
    import resource
    import cmath

look like an issue with this particular Python 3.5 build, those modules aren't removed.

**Comment by juliantaylor** [comment]
yes those are most likely packaging errors, I'll take care of it.
the gzip offset errors look a little worrying but probably an issue of py3.5 itself.

**Comment by juliantaylor** [comment]
@rgommers when you fixed #5644 are you sure the error went to stdout?
from what I can tell the version check actually merges stdin and stdout which also caused issues for this test.

**Comment by rgommers** [comment]
Think so, but I'll double check tonight (not in front of that laptop) now. 

What issue does it cause, and where is that merge happening (and guess that was always the case then)?

**Comment by juliantaylor** [comment]
LD_PRELOAD=/invalidfile python setup.py build

would fail as it has an stderr error message in the version string.
I only looked briefly, but I fear that might already be done in distutils itself, this PR uses a ugly hack to redirect to null in `version_cmd`

**Comment by rgommers** [comment]
It's indeed mixing stderr and stdout; warning does go to stderr:

    $ gfortran -dumpversion
    gfortran: warning: couldn't understand kern.osversion '14.1.0
    4.9.1
    $ gfortran -dumpversion > tmp.txt
    gfortran: warning: couldn't understand kern.osversion '14.1.0
    $ cat tmp.txt
    4.9.1
    $ gfortran -dumpversion 2>tmp2.txt
    4.9.1
    $ cat tmp2.txt 
    gfortran: warning: couldn't understand kern.osversion '14.1.0

**Comment by rgommers** [comment]
Looks to me like it's not distutils, but this: https://github.com/numpy/numpy/blob/master/numpy/distutils/exec_command.py#L436

Comment right above:

    # Not sure how to handle the case where errmess
    # contains only warning messages and that should
    # not be treated as errors.

And docstring of ``exec_command`` says ``The output contains both stdout and stderr messages.``

**Comment by rgommers** [comment]
``exec_command`` gets called in a bunch of places, and is pretty horrible. Maybe we can add a keyword ``ignore_stderr=False`` to it. Needs implementing 3 times though:(

**Comment by charris** [comment]
@juliantaylor Mind if I close this?

**Comment by juliantaylor** [comment]
no, though we need an issue for the remaining gzip issue

**Comment by charris** [comment]
Could you open an issue then and close this. I'm in a housecleaning mode...

**Comment by njsmith** [comment]
current master + #6018 is 3.5 clean AFAICT -- should we clean this up and merge it after all, or...?

**Comment by juliantaylor** [comment]
probably not, your nightly variant with allowed failure is probably better for merging
gcc-5 and the debug mode do provide some value but probably not enough to merge something that builds in the rolling debian experimental/unstable

**Comment by charris** [comment]
@juliantaylor Still want to keep this open?

**Comment by charris** [comment]
Closing this. @juliantaylor Feel free to reopen if you still want it.

**Pull request closed without merging**
