### PR TITLE
ENH sync ndarray methods doc/args with numpy function doc/args

### LINKED ISSUE #2340: Documentation of ndarray.clip is misleading (Trac #1745)
_Original ticket http://projects.scipy.org/numpy/ticket/1745 on 2011-02-17 by @fengy-research, assigned to unknown._

clip doesn't accept a_min and a_max as keyword arguments.

### PR DESCRIPTION
**Pull request by ahaldane**
Modified the docstrings to all, any, sum, prod, mean, var, std, min, max
to add keepdims argument. ~~Removed out argument from argmax/argmin.~~

Made numpy clip's args mirror ndarray.clip's args. That is, a_min and
a_max are now keword args 'min' and 'max'. Fixes #2340

### CODE REVIEW

**Comment by ahaldane** [comment]
* *added* numpy.argmin/argmax 'out' keyword to match ndarray.argmin/argmax.
 * modified names of numpy.put positional args to match ndarray.put.

**Comment by mhvk** [comment]
Great!  But doesn't the renaming of arguments need a deprecation? Any code that used, e.g., `a.clip(a_min=...)` will break with this change...

**Comment by ahaldane** [comment]
Huh, despite writing python for years I did not know you could specify positional arguments like kwd args.

You're right, and a github search shows plenty of people using `np.clip(a_min=x)`: [1](https://github.com/sirpercival/ir-reduce/blob/0e1348a5e3c15886c6e5c25c73901aff484cf5aa/findtrace.py#L117) [2](https://github.com/smdabdoub/find/blob/295e41a84e854172b059a92e704aea49662dd012/transforms/log.py#L48) [3](https://github.com/boutproject/BOUT-dev/blob/cbe528207ba3230321b9482e7516f4d492cd460e/tools/tokamak_grids/pyGridGen/crosslines.py#L155). There are also plenty of people using `ndarray.clip(min=x)`: [1](https://github.com/alexhock/ML/blob/72ce3981a1aafb5b5dfa5ecec86e7fb2f1e1da98/algos/mlhelper/image_scale.py#L137) [2](https://github.com/abramhindle/marsyas-fork/blob/b026c9f5c7497c5e3302d7e8510dfb43acab32aa/scripts/large-evaluators/tempo-reference-implementation/onset_strength.py#L49) [3](https://github.com/gtaylor/python-colormath/blob/22c6303fde5e1a1917cb463ace18d3042634cfa5/colormath/color_diff_matrix.py#L47)

Maybe the way to do it is to have both `a_min` and `min` keyword args for `np.clip`. `a_min` can give a deprecation warning. I'd like to hear a numpy maintainer's opinion on what to do though!

**Comment by mhvk** [comment]
I think you'd add `..., **kwargs)` and then check for `a_min` in there.  But this would need to be combined with some formal deprecation notice.  I don't know how that procedure works for `numpy`...

**Comment by ahaldane** [comment]
Also, this means there is a similar problem with my changes to `put`. Currently the signatures are `ndarray.put(indices, values, mode='raise')` and `np.put(a, ind, v, mode='raise')`. I can do the same `**kwargs` trick there too.

**Comment by charris** [comment]
Let's separate the argument renames into a separate PR and restrict this to the documentation of `keepdims`. Renaming arguments is a nasty business and should be discussed on the list first.

**Comment by ahaldane** [comment]
Ok, removed those problematic changes. New summary for this PR:

 * added keepdims argument in docstrings to all, any, sum, prod, mean, var, std, min, max
 * added 'out' keyword arg to numpy.argmin/argmax to match ndarray.argmin/argmax.
 * Corrected ndarray.clip docstring to reflect the actual ndarray.clip args (rather than np.clip's args)

**Comment by charris** [comment]
Looks good. Needs tests for the new functionality, and the addition of the `out` parameter can be mentioned in `1.10.0-notes.rst`.

**Comment by ahaldane** [comment]
Added tests for the 'out' parameter. Everything else was docstring changes.

**Comment by charris** [comment]
Thanks @ahaldane.

**Pull request merged**
