### PR TITLE
WIP, ENH: Add pytest support to numpy.testing

### PR DESCRIPTION
**Pull request by charris**
This PR adds pytest compatible versions of the numpy.testing decorators and utils. It does not provide test runners or doctests, but it will not error when nose is not present. Typical use would be something like
```
$ NPY_PYTEST=1 pytest numpy/testing/tests
```

I don't expect this to be the final form, we may want to separate the pytest and nose tools in some other way and choose something less clunky to choose between them.

### CODE REVIEW

**Comment by bashtage** [comment]
There is a function in the previous commit that will detect the test runner used.  Should this be used here to avoid NPYTEST definition?

**Comment by bashtage** [comment]
https://github.com/charris/numpy/blob/974ce6f144e79d5edf7076e14cf35c01c97536dc/numpy/testing/nose_tools/parameterized.py#L271

Here

**Comment by charris** [comment]
@bashtage That function is a bit too clever and doesn't detect which numpy test runner is running.

**Comment by charris** [comment]
OK, all the decorators and exceptions are now working properly with pytest. The `KnownFailureException` and `SkipTest` are now the pytest `XFailed` and `Skipped` exceptions, but it took a while to figure out how to avoid the hard pytest dependence. A pytest plugin would have been simpler in some ways, but it was hard to avoid importing numpy in the numpy directory when simply running `pytest`. It would probably not be difficult with a custom test runner, which is the next bit to finish this up.

**Comment by charris** [comment]
The last two commits are just to get the code up so I can pull it down to workon at the scipy sprints. They should be regarded as scratch commits, nothing final.

**Comment by aragilar** [comment]
It appears that pytest has moved where XFailed is, the following patch fixes this.

```
diff --git a/numpy/testing/pytest_tools/utils.py b/numpy/testing/pytest_tools/utils.py
index a873199b1..f9874fcb0 100644
--- a/numpy/testing/pytest_tools/utils.py
+++ b/numpy/testing/pytest_tools/utils.py
@@ -45,7 +45,7 @@ class KnownFailureException(Exception):
     def __new__(cls, *args, **kwargs):
         # import _pytest here to avoid hard dependency
         import _pytest
-        return _pytest.skipping.XFailed(*args, **kwargs)
+        return _pytest.outcomes.XFailed(*args, **kwargs)
 
 
 class SkipTest(Exception):
```

**Comment by xoviat** [comment]
@charris The way that SciPy transitioned to pytest is to introduce a temporary state where both nose and pytest were required, and then to eventually remove the nose dependency. Is that acceptable?

**Comment by charris** [comment]
The main problem we have is to maintain the nose tests for downstream while switching to pytest for our own use, which is why the current strange file organization is in place along with the environment variable. It isn't difficult the separate the two dependencies and I'd like to keep it that way for testing. I note that, IIRC, this patch is pretty much complete except for the actual test runners and some work on runtime exceptions, which I am not currently happy with. It has been a while since I worked on this, so my memory is a bit vague as to the state I left it in.

**Comment by xoviat** [comment]
Now, when you say that "we need to maintain the nose tests for downstream," are you talking about maintaining `numpy.testing` for existing users, or are you talking about actually making sure that numpy can still be tested with nose?

**Comment by charris** [comment]
Existing users.

**Comment by bashtage** [comment]
It would be nice to be able to drop nose as a testing requirement when using NumPy if your test runner is pytest.

**Comment by pv** [comment]
@xoviat: the way scipy transitioned was pretty much an 
everything-at-once thing, but I organized it so that commits that would 
also work on Nose came first. There was not really a "transitional 
state" in my local repository.

**Comment by xoviat** [comment]
Yes, I'm aware of that. gh-10240 would seem to accomplish that if it includes all of the tests. Whether that's true is another question.

**Comment by charris** [comment]
Note that this branch can be merged without affecting the current nose testing, so might be a good basis going forward.

**Comment by charris** [comment]
Note that `run_module_suite` here doesn't work since `__init__` added to test directories. But I can comment and push the last to commits, then if this goes in the remaining fixups should not be to much work.

**Comment by xoviat** [comment]
If it doesn't break the existing nose tests, then go ahead and put this in. I can work on fixing the remaining issues.

**Pull request closed without merging**
