### PR TITLE
MAINT: Fix some API versions.

### PR DESCRIPTION
**Pull request by charris**
These were missed in the 1.24.0 preparations.

### CODE REVIEW

**Comment by mattip** [comment]
Shouldn't the need to udate the `C_API_VERSION` have been caught by a test?

**Comment by charris** [comment]
The mismatch was caught in the wheel builds after cversions.txt was updated, I should add a comment that the two versions need to be kept in sync, it wasn't clear that that was needed, so it was a bit of an experiment leaving them out of sync. I'll add a note here.  I don't know why it didn't show up in other tests. I first noticed that the cversion needed updating by reading the build logs.

**Comment by mattip** [comment]
digging around, [`check_api_version()`](https://github.com/numpy/numpy/blob/8d205fdac2daa0c6d90ad4b8911413071e9a3f09/numpy/core/setup_common.py#L76) checks that the files are correct, and this is called in configure().  https://github.com/numpy/numpy/blob/8d205fdac2daa0c6d90ad4b8911413071e9a3f09/numpy/core/setup.py#L479-L485

Maybe we should change it to unconditionally raise instead of only when `is_released is True.

**Comment by mattip** [comment]
That would have caught the error earlier. The condition was part of the [original PR to add this feature](https://github.com/numpy/numpy/commit/c3cef2607b05081b3a0f4de6a2ee254e5d31f448#diff-6fde01624b4d27874d419c0f8aeae3743c4f5e7e1c9f2b039eb453a714d0cbb1R302) 13 years ago.

**Comment by mattip** [comment]
I can do that in a separate PR. This one fixes the error.

**Comment by mattip** [comment]
Thanks @charris

**Pull request merged**
