### PR TITLE
ENH: Suppress over-/underflow RuntimeWarning in assert_array_equal

### LINKED ISSUE #18992: Overflow warnings from np.testing.assert_array_equal for subnormal inputs
### Reproducing code example:

```
In [1]: import numpy as np

In [2]: np.testing.assert_array_equal(np.array([1,2,3], np.float32), np.array([1,1e-40,3], np.float32))
/Users/phawkins/.pyenv/versions/3.9.0/envs/py3.9.0/lib/python3.9/site-packages/numpy/testing/_private/utils.py:830: RuntimeWarning: overflow encountered in true_divide
  max_rel_error = max(error[nonzero] / abs(y[nonzero]))
```

It's surprising for `assert_array_equal` to issue any kind of warning.

I suspect the `errstate` guard here: https://github.com/numpy/numpy/blob/74a65e1cef00e3e9805dbc88252a023975b70079/numpy/testing/_private/utils.py#L813
should be suppressing `over` and possibly `under` as well.

### NumPy/Python version information:

```
1.20.3 3.9.0 (default, Nov  9 2020, 14:53:43)
[Clang 11.0.0 (clang-1100.0.33.17)]
```

### PR DESCRIPTION
**Pull request by Syrlander**
Closes #18992

### CODE REVIEW

**Comment by Syrlander** [comment]
Build error related to missing SciPy docs. See: https://github.com/scipy/scipy/issues/14267

**Review by seberg — COMMENTED** [review]
Thanks LGTM, just a few nitpicks to try and make the code a bit shorter.

**Comment by Syrlander** [comment]
@seberg, thanks for the suggestions, I've incorporated them into the latest commit. I'm fairly new to contributing to numpy, so any suggestions about common practice is appreciated.

**Review by seberg — APPROVED** [review]
Thanks, LGTM. just waiting for CI and giving others a chance to comment if they want to.

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @Syrlander! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Pull request merged**
