### PR TITLE
Dot product overwrite bugfix

### PR DESCRIPTION
**Pull request by jonathanrocher**
This is a proposal for fixing issue https://github.com/numpy/numpy/issues/3357. It goes beyond simply warning the user about this, which was the least we want do based on the ML discussion:
http://thread.gmane.org/gmane.comp.python.numeric.general/54277

This makes a copy of the entire array that is overlapping to do the "right" thing, assuming that no-one would willingly want to do the dot product between matrices that are changing during the dot product.

Feedback requested.

### CODE REVIEW

**Comment by charris** [comment]
Needs to be adapted to current master and history cleaned up. I'll do that if there is agreement on this. @njsmith @seberg this seems reasonable to me. Thoughts?

**Comment by mhvk** [comment]
@charris - I happened to be looking at `cblasfunc` today (to see what is involved in having a gufunc for matrix products...), and noticed that that one does do overlap checking: https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/cblasfuncs.c#L418

If things get inserted further up the chain, those checks can be removed.

p.s. I'm surprised that with the amount of code preceding these blas calls there is still a speed advantage; I guess it speaks to how well optimized some of those routines are... [unlike LAPACK implementations, which seems to be just do the bog-standard thing)

**Comment by charris** [comment]
The speed advantage of BLAS depends a lot on the matrix sizes. For even a straight call the overhead for very small arrays can make it slower than naive C code. For big arrays and multi-processor cpus it has a big advantage.

Note the the cblasfunc handles all the different mat-vec combinations and types, which is where some of the size comes from.

**Comment by mattip** [comment]
Fixed in the NEP 20 refactoring

**Pull request closed without merging**
