### PR TITLE
ENH: Use SVML for f64 exp and log 

### LINKED ISSUE #20891: BUG: exp(NINF) returns underflow error after version 1.20
### Describe the issue:

We have an interesting situation where a test suite that checks the value of e^-inf is behaving differently depending on Numpy version. With numpy version 1.19.5 and 1.20.3 we consistently get "0.0" as the result.  Later versions- 1.21 and 1.22- raise an underflow error.  We are running Python 3.8.6 built by GCC 10.2.0 and using virtual environments to install these Numpy versions.

A further confounding factor is that on our slightly older processors we don't get this underflow, instead returning 0.  The Python and GCC toolchains is the same thanks to environment modules and the OS and patches are the same on both generations, but the older processors (Intel Xeon E5-2667) return 0 and the newer (Intel Xeon Gold 6254) return underflow with the newer numpy versions.

I'd posted the issue to the mailing list where [it was suggested](https://mail.python.org/archives/list/numpy-discussion@python.org/message/ORCESTII2FXESJK5OC2S4Z3WUCKHDLJ6/) that we should expect a result of 0 and that this may be an issue in the SIMD version.

Thanks for looking- please let me know if there's any additional information I can provide.

### Reproduce the code example:

```python
#!/usr/bin/env python3
import numpy as np
np.seterr(under='raise')
print(np.exp(np.NINF))
```

### Error message:

```shell
Traceback (most recent call last):
  File "./under.py", line 4, in <module>
    print(np.exp(np.NINF))
FloatingPointError: underflow encountered in exp
```

### NumPy/Python version information:

Numpy: 1.21.4 
Python: 3.8.6 (default, Dec 16 2020, 13:45:25) [GCC 10.2.0]

### PR DESCRIPTION
**Pull request by r-devulap**
SVML implementations are much faster than the ones currently implemented here. It also fixes the spurious underflow FP exception problem. (fixes https://github.com/numpy/numpy/issues/20891). 

```
       before           after         ratio
     [8840d950]       [802e6b05]
     <main>           <exp-log-svml>
-      32.8±0.1μs      20.7±0.01μs     0.63  bench_ufunc_strides.AVX_UFunc_log.time_log(2, 'd')
-      33.8±0.4μs      20.7±0.03μs     0.61  bench_ufunc_strides.AVX_UFunc_log.time_log(4, 'd')
-         392±2μs          207±1μs     0.53  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 4, 1, 'd')
-         385±2μs        200±0.1μs     0.52  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 2, 1, 'd')
-       183±0.4μs         86.5±2μs     0.47  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'exp'>, 1, 1, 'd')
-         616±2μs          256±1μs     0.42  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'exp'>, 4, 4, 'd')
-         676±3μs          259±2μs     0.38  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 4, 4, 'd')
-      30.7±0.1μs      11.1±0.03μs     0.36  bench_ufunc_strides.AVX_UFunc_log.time_log(1, 'd')
-         615±2μs          205±2μs     0.33  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'exp'>, 4, 2, 'd')
-         674±2μs          223±1μs     0.33  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 4, 2, 'd')
-        611±30μs          198±9μs     0.32  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'exp'>, 2, 4, 'd')
-        671±30μs         217±10μs     0.32  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 2, 4, 'd')
-       668±0.4μs        202±0.8μs     0.30  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 2, 2, 'd')
-         373±1μs       107±0.05μs     0.29  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 1, 1, 'd')
-       610±0.4μs          168±1μs     0.28  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'exp'>, 2, 2, 'd')
-        670±30μs          184±7μs     0.27  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'exp'>, 1, 4, 'd')
-        735±30μs          187±7μs     0.25  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 1, 4, 'd')
-        669±20μs         150±10μs     0.22  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'log'>, 1, 2, 'd')
-        611±20μs          129±4μs     0.21  bench_ufunc_strides.Unary.time_ufunc(<ufunc 'exp'>, 1, 2, 'd')
```

This speeds up training logistic regression benchmark by nearly 2x: 
```
       before           after         ratio
     [8840d950]       [802e6b05]
     <main>           <exp-log-svml>
-      3.65±0.02s       1.89±0.03s     0.52  bench_ufunc_strides.LogisticRegression.time_train(<class 'numpy.float64'>)
```

### CODE REVIEW

**Comment by seberg** [comment]
I guess we can't backport this, but that seems OK.  The hardware requirements for both versions are identical here?

**Comment by r-devulap** [comment]
> The hardware requirements for both versions are identical here?

Technically no (SVML needs AVX512_SKX whereas existing implementation needs just AVX512F). But practically its the same. Currently all CPU's with AVX512F automatically means AVX512_SKX.

**Comment by seiko2plus** [comment]
@r-devulap, Regardless of Xeon Phi users. What about other operating systems?

**Comment by r-devulap** [comment]
@seiko2plus ah yeah, I didn't realize that this will regress on other OS. Will need to re-do this.

**Comment by r-devulap** [comment]
yay, finally passed :)

**Comment by mattip** [comment]
@seiko2plus thought?

**Comment by r-devulap** [comment]
ping

**Review by seiko2plus — APPROVED** [review]
Thank you @r-devulap, LGTM.

**Comment by mattip** [comment]
Thanks @r-devulap

**Comment by xkszltl** [comment]
> Technically no (SVML needs AVX512_SKX whereas existing implementation needs just AVX512F). But practically its the same. Currently all CPU's with AVX512F automatically means AVX512_SKX.

FYI AMD is adding AVX512 as well.

**Pull request merged**
