### PR TITLE
MAINT: fix first power in polynomials display.

### LINKED ISSUE #21695: ENH: Replace x**1 with x in polynomials str representation
### Proposed new feature or change:

Currently the first degree of the indeterminate variable in polynomials is displayed as x**1:

``` python
>>> import numpy.polynomial as poly
>>> str(poly.Polynomial([1,2,3]))
'1.0 + 2.0·x¹ + 3.0·x²'
```

 Usually the first degree is not written. It is suggested to omit the degree for the term with the power of one:

``` python
>>> import numpy.polynomial as poly
>>> str(poly.Polynomial([1,2,3]))
'1.0 + 2.0·x + 3.0·x²'
```

In Latex representation it is displayed correctly, so there is nothing to be done:

image

Numpy version: master branch

### PR DESCRIPTION
**Pull request by axil**
Fixes #21695.

### CODE REVIEW

**Review by HaoZeke — COMMENTED** [review]
I'm faintly -0 on this. It seems like a verbose special casing (in code) for what is unambiguous to begin with.

**Comment by axil** [comment]
@HaoZeke Not sure what you mean. Here's the existing code special casing the very same thing in latex representation:

https://github.com/numpy/numpy/blob/e05e65718b34aea0c3be393459e2d5933ab075e0/numpy/polynomial/polynomial.py#L1525-L1530

I just did the same for string representation. 

Can you elaborate?

**Review by HaoZeke — APPROVED** [review]
Following precedent as noted by @axil, this looks alright. Pending fixes to the tests of course.

**Comment by charris** [comment]
Lot of failing tests that expect the old style.

**Comment by axil** [comment]
> Lot of failing tests that expect the old style.

@charris Yes, there's some work to do. I wanted to get principal approval at the meeting to understand that I won't do meaningless work fixing the tests. I'll fix them today.

**Comment by axil** [comment]
The tests proved to be deeply interconnected with the PR for #21653, so even if I make the tests pass in this PR it will result in a nontrivial merge conflict with that PR. So either
– #21653 should be merged first, then this PR  should be rebased and tests fixed accordingly or
– these two issues should be united into one.

**Comment by mattip** [comment]
PR #21654 to fix issue #12653 is failing tests. If it would be easier for you, I think it would be fine to merge the two changes into one PR. If it is easier to first concentrate on #21654 that is fine too.

**Comment by axil** [comment]
Yes, this PR may be closed now. I'll merge fixes for both issues into the PR https://github.com/numpy/numpy/pull/21654.

**Pull request closed without merging**
