### PR TITLE
ENH:  make __file__ existence optional

### PR DESCRIPTION
**Pull request by franzhaas**
`__file__` is not always present, for example when copy pasting to a repl, or running numpy code that was stored in a database, or a single file executable.

I found 2 spots where IMHO it is easily possible to become independent of `__file__`. And chose those to start working on becoming `__file__` independent. 

The big step would be to get loading of the shared library `__file__` independent, but these 2 changes are well isolated, and probably provide reasonable grounds to discuss the goal.

### CODE REVIEW

**Comment by mattip** [comment]
Could you provide a concrete use case where `__file__` is not available and `from numpy.core import _multiarray_umath` succeeds?

**Comment by franzhaas** [comment]
> Could you provide a concrete use case where `__file__` is not available and `from numpy.core import _multiarray_umath` succeeds?

There are, as far as i know no usefull / sensible use cases feasible where __file__ is not available, but a unmodified numpy is installed and functioning at the moment. I think this is becasue __config__.py loads shared libraries based on __file__, but there are likely other road blocks as well.

However if you copy the functions modified by this PR into a repl, and call it from there, this situation can be produced. (which is a mockup for the situation that the source code is not stored in a file, but loaded from elsewhere.)

I intend to propose modifications to misc_util.py in order to add a __init__.py to the .libs folder, and to access the shared libraries from there using importlib.resources. And go trough the remaining __file__ references after that.

However these changes are way more intrusive. I am considering at the moment to modify a released wheel  instead.

Guidance and input is highly welcome.

Thanks,
Franz

**Comment by mattip** [comment]
> There are, as far as i know no usefull / sensible use cases feasible where `__file__` is not available

Well, if that is a true assessment of the situation, I would prefer you develop this experiment in a fork of numpy, until there is some use for the change. Every commit to the repo triggers CI and sends emails to a dozen developers, so it is a not insignificant amount of churn.

**Comment by mattip** [comment]
Still waiting for an clear explanation/use case that would justify continuing to work on this PR ...

**Comment by rgommers** [comment]
> However if you copy the functions modified by this PR into a repl, and call it from there, this situation can be produced.

That's not something that makes sense to do for any reasonable use case, so this is either misguided or a proxy for something else.

> Hopefully ending up with a single file executable with numpy in it.

Can you please explain the how/why of this single file executable building? Are you building a new tool to compile such executables, or using an existing tool?

**Comment by franzhaas** [comment]
Sorry, i tried  to follow mattips advice, to develop on on my fork, with the intend to build an argument for these changes (bundled with additional ones). but forgot that it is still attached to this pull request, creating notifications. I didnt mean to bother at this stage.

I do not think that this PR is viable at the moment.

### Trajectory of this PR
I am using pyoxidizer, and am actually making some process. on windows, with the exeception of numpy.random I can already load numpy and use it for toy examples, however I can not run the tests (yet), also blas is missing. 

I am working on getting numpy.random to load at the moment, as it crashes during import. I am not yet understanding the issue, it does not crash but fails with an key error when single stepping throught the import process. This is reported here.: https://github.com/indygreg/PyOxidizer/issues/489 but there has not yet been progress. The crash apears to be related to the multiprocessing/locking logic.

### Request for help
If someone can point me to a difference in the pyd files in numpy.random as oposed to for example those in numpy.polynomal with respect of loading / dependencies, that would be greatly apreciated.

### As for why i like to build single file executables:

I have a lot of small single purpose python solutions, which interact with experimental hardware, and i want to REPRODUCE the same software on different machines/in the future. I do worry about not beeing able to reproduce functionality, I do not worry about security, missing features, or disk space. I do not have the resources to CI my python solutions (constraints from the experimental HW).

Thanks

**Comment by rgommers** [comment]
Thanks, that makes sense. If we can support PyOxidizer in a reasonable way, I'd be +1 on that. The changes in this PR at the moment are, as you say, not viable. How about closing this PR, and reopening when you are ready?

> If someone can point me to a difference in the pyd files in numpy.random as oposed to for example those in numpy.polynomal with respect of loading / dependencies, that would be greatly apreciated.

`numpy.random` is the only component built with Cython. Cython walks the project tree at build time to determine the import name (`PyMODINIT_FUNC` I think) - that is one thing I can see going wrong there. It may be useful to check if you can build a small standalone module with some Cython code in a subdir.

**Comment by franzhaas** [comment]
@rgommers 
thanks, this is helpfull.

closing for now

**Comment by franzhaas** [comment]
There is progress on this issue, the reason why cython extensions can not be loaded into pyoxidizer has narrowed down (The multiphase initialisation is not working on pyoxidizer), which can be disabled in the cython generated c code by modifying a #define.

**Comment by mattip** [comment]
> The multiphase initialisation is not working on pyoxidizer

That might make it hard to support NumPy going forward, as I think we are moving dtypes toward multiphase initialization

**Comment by franzhaas** [comment]
Thanks for the headsup, then i will not disable mutliphase initialisation.

For know, using the pyoxidizer feature to load pyd files from disk it is already possible to load numpy.random. This is not really a single file executable, but a much viewer file executable.

The next items I intend to focus on are.:

1.) letting the tests run (pytest currently refuses to start on this "viewer file executable")
2.) Getting the cython extension to load from memory (instead of the disk)

**Comment by franzhaas** [comment]
Finally, there is progress again. The reason why loading multiphase modules could not be loaded has been found, and a solution is proposed.

https://github.com/indygreg/PyOxidizer/pull/494

**Pull request closed without merging**
