### PR TITLE
ENH, BLD: Define RISCV-32 support

### PR DESCRIPTION
**Pull request by kraj**
Helps compile on riscv32

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by seberg** [comment]
@kraj I think this should also be added to `numpy/core/include/numpy/npy_endian.h`.  Does the full test suit pass with this patch?  @aurel32 this may be a long shot, but since you added RISCV64, does this make sense to you?

**Comment by kraj** [comment]
@seberg so far I have only fixed build, I am in process of setting up a test run in qemu/riscv32

**Comment by kraj** [comment]
> @seberg so far I have only fixed build, I am in process of setting up a test run in qemu/riscv32

I ran the tests
```
lib/tests/test_polynomial.py .................                                                                                                       [ 60%]
lib/tests/test_recfunctions.py .........................................x........                                                                    [ 60%]
lib/tests/test_regression.py ...........................                                                                                             [ 60%]
lib/tests/test_shape_base.py ..............................s...................................                                                      [ 61%]
lib/tests/test_stride_tricks.py ................                                                                                                     [ 61%]
lib/tests/test_twodim_base.py ..................................                                                                                     [ 61%]
lib/tests/test_type_check.py ....................................................                                                                    [ 62%]
lib/tests/test_ufunclike.py ......                                                                                                                   [ 62%]
lib/tests/test_utils.py ..............                                                                                                               [ 62%]
linalg/tests/test_build.py .                                                                                                                         [ 62%]
linalg/tests/test_deprecations.py Fatal Python error: Segmentation fault

Current thread 0x946f9010 (most recent call first):
  File "/usr/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 969 in qr
  File "<__array_function__ internals>", line 5 in qr
  File "/usr/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1789 in assert_warns
  File "/usr/lib/python3.9/site-packages/numpy/linalg/tests/test_deprecations.py", line 17 in test_qr_mode_full_future_warning
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 184 in pytest_pyfunc_call
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1627 in runtest
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 163 in pytest_runtest_call
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 256 in <lambda>
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 310 in from_call
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 255 in call_runtest_hook
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 216 in call_and_report
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 127 in runtestprotocol
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 110 in pytest_runtest_protocol
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 338 in pytest_runtestloop
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 313 in _main
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 257 in wrap_session
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 306 in pytest_cmdline_main
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/usr/lib/python3.9/site-packages/numpy/_pytesttester.py", line 206 in __call__
  File "/usr/lib/python3-numpy/ptest/./run-ptest", line 4 in <module>
Segmentation fault
```
this is riscv32 emulation on qemu. So I might have to see whats going on.

**Comment by charris** [comment]
@kraj  Any progress?

**Comment by kraj** [comment]
@charris I think the test results above hold, for my purposes its working ok.

**Comment by kanavin** [comment]
@kraj  this needs rebase on latest target commit

**Comment by charris** [comment]
close/reopen to see if Mac problem goes away.

**Comment by charris** [comment]
close/reopen

**Comment by rossburton** [comment]
Successful CI run, is anything blocking this from merging?

**Comment by threexc** [comment]
Hi, with release version 2.0.0 the relevant file paths have changed to `numpy/_core/include/numpy/npy_cpu.h` and `numpy/_core/include/numpy/npy_endian.h`. Is anyone still looking at this?

**Comment by kraj** [comment]
I think we need to refresh it and rerun the tests.

**Review by mattip — APPROVED** [review]
Rebased to clear conflicts (moved core -> _core). LGTM, thanks.

**Comment by mattip** [comment]
Thanks @kraj. Let us know if there are problems

**Pull request merged**
