### PR TITLE
DOC: Bump pydata-sphinx-theme version

### LINKED ISSUE #26058: DOC: Inaccessible contrast for a:visited links in admonitions
### Issue with current documentation:

1. Visit https://numpy.org/neps/nep-0029-deprecation_policy.html
2. If you've not visited the link "SPEC 0 — Minimum Supported Versions" before, it looks like:

image

3. Click the link "SPEC 0 — Minimum Supported Versions"
4. Return to https://numpy.org/neps/nep-0029-deprecation_policy.html
5. It looks like:

image

The contrast of purple on the dark background is low: it's ratio is 1.51, below the WCAG AA level of 4.5:

image

This comes from [`basic.css`](https://numpy.org/neps/_static/basic.css), which I think is from Sphinx:

```css
a:visited {
    color: #551A8B;
}
```

If I disable the rule, it looks like this, with a good ratio of 5.37:

image

The docs use PyData Sphinx Theme 0.13.3, but I can't reproduce the problem with these links (and inspecting the elements to edit in a link):

* https://pydata-sphinx-theme.readthedocs.io/en/v0.13.3/examples/kitchen-sink/admonitions.html
* https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/kitchen-sink/admonitions.html (0.15.2)

### PR DESCRIPTION
**Pull request by charris**
Backport of #26125.

Fixes #26058.

Fixes inaccessible contrast for `a:visited` links in admonitions. 

Note: I didn't manage to build everything locally to test this out, does the CI generate a preview build?

### CODE REVIEW

**Comment by melissawm** [comment]
Preview is here, @charris https://output.circle-artifacts.com/output/job/b4f4d991-cc18-4431-98c3-8af892b0a6b9/artifacts/0/doc/build/html/index.html?pr=26305 👍🏻

**Comment by melissawm** [comment]
I see that there are still some issues with the spacing of the navbar (depending on the active section, there is a weird truncation of the section titles)

Can I try and fix that before we backport? Is it ok if I just push a commit to this PR?

**Comment by charris** [comment]
> Can I try and fix that before we backport? 

Sure, but it is already in. Just push a new PR to main and I will backport it.

**Comment by melissawm** [comment]
Thanks, @charris !

**Comment by melissawm** [comment]
Here you go: https://github.com/numpy/numpy/pull/26311

**Pull request merged**
