### PR TITLE
MAINT: Deal with FIXMEs in number.c

### PR DESCRIPTION
**Pull request by k-kapp**
The solution to the FIXMEs in number.c were relatively
simple, so I might be missing something here since no
one has fixed it yet. The solution I present here might
make the macros slightly uglier and harder to read, though,
so perhaps the return and goto statements in the macros
were not so bad after all.

### CODE REVIEW

**Comment by k-kapp** [comment]
Come to think of it, if this is to be merged, we could also drop the goto statement entirely by using if/else instead. But I will leave that to the reviewers.

**Comment by eric-wieser** [comment]
IMO this isn't an improvement. (Also, you should be using spaces for consistency with the rest of the file, not tabs).

**Comment by k-kapp** [comment]
No problem, I can close it if that is the case. Did think it was too simple a solution.

**Comment by eric-wieser** [comment]
I'm not the only person with opinions here though, so closing it might have been a bit far...

**Comment by k-kapp** [comment]
I'm happy to keep it closed - I think it's pretty trivial in any case, and I guess that if it really was an issue, then someone would have dealt with this already. I did not think that my solution was much of an improvement either - just added it as a suggestion in case the `goto` and `return` statements were _really_ an issue (again, if they were, someone probably would have already done something similar/better than I did).

**Comment by charris** [comment]
The fixmes are due to me and were motivated by a desire to improve code clarity, so any changes should be directed at making the control flow more readable and obvious, hence the comment about `return`. The current macros aren't wrong, they just offended my sense of taste ;) Others may have different reactions...

**Pull request closed without merging**
