### PR TITLE
DOC: Update documentation to reference SSH

### PR DESCRIPTION
**Pull request by ogidig5**
ENH: Update documentation to reference SSH

I've updated the documentation in numpy/doc/source/dev/index.rst.
This change reflects the current authentication methods using SSH keys. 
This pull request replaces outdated references to GitHub Usernames and Passwords.
This change improves the clarity and accuracy of the documentation

I'd appreciate it if @bmwoodruff and @InessaPawson could review these changes.
See #26343

### CODE REVIEW

**Comment by mattip** [comment]
I think we should remove all the "typical" github interactions from this page and leave only the "special" things that are specific to NumPy. This will also future-proof the page for any changes in github policy.

**Comment by bmwoodruff** [comment]
This appears to be a small part missed in the removal of too verbose Git details at the end of last year. See https://github.com/numpy/numpy/pull/25340

Would the best course of action be to just remove the bullet point entirely?

I think there is one more lingering reference located in [RELEASE_WALKTHROUGH.rst](https://github.com/numpy/numpy/blob/main/doc/RELEASE_WALKTHROUGH.rst).  Would a simple " You will also need to authenticate with GitHub to push the documentation (search online for details)." work to replace "You will also need a GitHub personal access token (PAT) to push the documentation" and the bullet point that follows?  This removes any reference to using a PAT or SSH.

**Comment by mattip** [comment]
I think most all of points (1), (2) and (3) can be removed, except the part where 
> If your commit introduces a new feature ...

There may be more that can be deleted. This should all be rephrased to flow better.

**Comment by bmwoodruff** [comment]
As a first time contributor to an open source project. I think parts (1), (2), and (3) are great helps. Here are some thoughts.

- The information about tags and submodules is needed in (1).
- Keep the links to properly formatted commit messages, testing, and standards in (2).  
- In (3), entirely remove the second bullet referring to a username and password and SSH.

The above removes the GitHub items related to authentication and leaves enough for a newcomer to hopefully jump in. 

The comment I made above about RELEASE_WALKTHROUGH.rst should be ignored. 
The file it's located in is a historical reference on [releasing.html](https://numpy.org/devdocs/dev/releasing.html#release-process).

@ogidig5 , those are my thoughts. 

As a different PR, or in addition to this one, here is one more thing I wish I knew when I made my first contribution.
- The third bullet of (3) could include "and include any appropriate [CI commands](https://numpy.org/devdocs/dev/development_workflow.html#commands-to-skip-continuous-integration)."
  -  We could add a bullet to the bottom of the [CI commands](https://numpy.org/devdocs/dev/development_workflow.html#commands-to-skip-continuous-integration) for those that only want to update the docs. Use `[skip azp] [skip actions] [skip cirrus]`. This comment gets added often to doc PRs. When [docs only] becomes available (see https://github.com/numpy/numpy/pull/26316), this could be updated.

**Comment by charris** [comment]
This should be done in a separate branch rather than `main`, something like `ogidig5:update-reference`. That is, assuming linux and starting in the main branch of your fork:
```
git checkout -b update-reference
<edit>
<commit>
git push origin HEAD
```
You can then make the PR from your fork on github.

**Comment by charris** [comment]
You can see the relevant branches right under the title on this page.

**Comment by charris** [comment]
Note that I also edited the title to add the `DOC:` tag.

**Comment by bmwoodruff** [comment]
I'll work with @ogidig5 on Monday clean up his fork and submit a new clean PR on a branch. Thanks for the comments all. We can close this PR.

**Pull request closed without merging**
