### PR TITLE
BUG: Make n a long int for np.random.multinomial

### LINKED ISSUE #25061: BUG: np.random.multinomial(<float>, ...) raises a TypeError in numpy 1.26
### Describe the issue:

Up through numpy 1.25.2, `random.multinomial()` accepted a float as the first argument _n_, whereas numpy 1.26 does not. (In our code, that value comes from a computation involving `scipy.constants.Avogadro`.)

In numpy 1.25.2 (tweaking an example from the docs):

```python
>>> import numpy as np
>>> np.random.multinomial(20.0, [1/6.]*6, size=1)
array([[4, 5, 2, 6, 3, 0]])
```

In numpy 1.26.0 and 1.26.1:

```python
>>> import numpy as np
>>> np.random.multinomial(20.0, [1/6.]*6, size=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpy/random/mtrand.pyx", line 4256, in numpy.random.mtrand.RandomState.multinomial
TypeError: 'float' object cannot be interpreted as an integer
```

**Q. Is this an intentional API change?**

I don't see it in the release notes.

* The [doc for multinomial's](https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.multinomial.html) first argument says `n: int`.
* [mtrand.pyx](https://github.com/numpy/numpy/blob/22ab9aa73cd80d13c74b8a227d7e3f10b84ab7fc/numpy/random/mtrand.pyx#L4278C27-L4278C38) declares _n_ as `np.npy_intp`.
* [mtrand.pyi](https://github.com/numpy/numpy/blob/22ab9aa73cd80d13c74b8a227d7e3f10b84ab7fc/numpy/random/mtrand.pyi#L502) mtrand.pyi declares _n_ as `_ArrayLikeInt_co`.
* [\_\_init\_\_.cython-30.pxd](https://github.com/numpy/numpy/blame/22ab9aa73cd80d13c74b8a227d7e3f10b84ab7fc/numpy/__init__.cython-30.pxd#L27) declares `npy_intp` as `Py_ssize_t`.
* Cython's [UFuncs.pyx](https://github.com/cython/cython/blob/bc32b7ec3f15f532c0ae59b930544c23172e8c50/Cython/Utility/UFuncs.pyx#L4) declares `npy_intp` as `int`.

So I guess what changed was shifting API definitions from Cython's UFuncs.pyx to NumPy's \_\_init\_\_.cython-30.pxd 

Environment: macOS 13.6, Intel CPU, Python 3.11.6.
Also: Ubuntu Linux, Intel CPU, Python 3.11.6.

### Reproduce the code example:

```python
import numpy as np
np.random.multinomial(20.0, [1/6.]*6, size=1)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpy/random/mtrand.pyx", line 4256, in numpy.random.mtrand.RandomState.multinomial
TypeError: 'float' object cannot be interpreted as an integer
```

### Runtime information:

`import sys, numpy; print(numpy.__version__); print(sys.version)`
```
1.26.1
3.11.6 (main, Oct 31 2023, 22:06:12) [Clang 15.0.0 (clang-1500.0.40.1)]
```

`print(numpy.show_runtime())`
```
[{'numpy_version': '1.26.1',
  'python': '3.11.6 (main, Oct 31 2023, 22:06:12) [Clang 15.0.0 '
            '(clang-1500.0.40.1)]',
  'uname': uname_result(system='Darwin', node='jerrys-mbp.lan', release='22.6.0', version='Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:52 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_X86_64', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/usr/local/var/pyenv/versions/3.11.6/envs/test1/lib/python3.11/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 1,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None
```

### Context for the issue:

I'll adjust our calling code to convert these values to `int`, so fixing this is not a priority.

I'd like to:

1. let you know in case it is a bug to fix
2. hear if this API change applies to other functions so we can fix them all while updating to numpy 1.26.1

### PR DESCRIPTION
**Pull request by thalassemia**
Fixes #25061.

### CODE REVIEW

**Comment by 1fish2** [comment]
Should the Python Interface file [mtrand.pyi](https://github.com/numpy/numpy/blob/22ab9aa73cd80d13c74b8a227d7e3f10b84ab7fc/numpy/random/mtrand.pyi#L502) also declare `multinomial`'s _n_ argument `long`?

It's currently typed `_ArrayLikeInt_co` which seems way off.

**Comment by seberg** [comment]
It is of course *not* safe to change this to `long`, this was a correct bug fix for windows and huge arrays.

**Comment by thalassemia** [comment]
The other changes to `npy_intp` I agree with and understand. Changing the type of `n` to `npy_intp` is, as far as I can tell,  unnecessary and moot because it is subsequently [assigned to a `long`](https://github.com/numpy/numpy/blob/69b9afac50094573a8ac587f1b07d8aa4ee8d681/numpy/random/mtrand.pyx#L4410) later on in the function and not directly used again.

**Comment by seberg** [comment]
ops, sorry, you are right, somehow I thought it was used for a size.  So we can do that, still wondering a bit about the other changes away from long (and presumably more in `_generator.pyx`) which changed if the cython version is important.

**Comment by seberg** [comment]
Thanks, this doesn't fix the underlying issue, but it seems fine and rejects very large values that don't fit `long` but do fit `intp`, which is potentially a bit safer on windows.  Small enough fix even for the legacy random, I would say.

**Pull request merged**
