### PR TITLE
DOC: modified examples in numpy.fft.irfft(n) to indicate that it is N…

### PR DESCRIPTION
**Pull request by ghost**
…OT necessary to pass domain size in compositions of the reduced transforms (it may be necessary in other configurations, such as mixed-type compositions, resampling, etc)

### CODE REVIEW

**Comment by eric-wieser** [comment]
I don't fully understand the intent behind this patch. Very roughly, the docs today are:
```
See Notes for why X is necessary

Notes
------
X is necessary because ...
```
You've changed it to roughly
```
See Notes for why X is not necessary

Notes
------
X is necessary because ...
```

For this to make sense, I think you need to adjust the wording of the notes section.

Could you give a concrete example for what you mean when you say it's not necessary?

**Comment by williamhilton-works** [comment]
To be concise, the original example concerning necessary conditions is wrong. It is not necessary to specify the second argument of the irfft function in the relation irfft(rfft(a), len(a)) == a. To construct a counterexample, we need only to show that irfft(rfft(a)) == a. Indeed,

a=np.random.rand(8)
hypothesis1=np.fft.irfft(np.fft.rfft(a),len(a))==a
hypothesis2=np.fft.irfft(np.fft.rfft(a))==a
hypothesis1==hypothesis2

produces a boolean vector of trues, demonstrating that the hypotheses are the same. Consequently, it is not necessary to include len(a) as an argument in this example. If it was necessary, it would suggest that the rfft and irfft functions were somehow not designed to be functional inverses of one another in the default options -- such a state of affairs would be rather poor design. In this sense, the original example is not just wrong but, in fact, it is a bad example!

I'm not exactly sure the direction that the original author was headed in (there are many possibilities), but I suppose I can cook up one such instructive example in the direction of functional inverses. In particular, the relation irfft(fft(a), len(a)) == a holds. The second argument is most definitely necessary, since irfft(fft(a)) != a isn't even the right length! Simply put, the fft function produces the entire Fourier spectral data associated with a. But the irfft function is reading this full spectrum as if it were only the independent Fourier modes, hence the erroneous result.

I'm brand new to these documenting practices, so I am unable to judge the appropriateness of including this alternative example (which, for instance, refers to the more general fft function in the context of the reduced Hermitian-symmetric forms). On a related note, I think my consternation also explains why I turned a wrong bad example into just a bad example. Perhaps we should exclude the example, or instead add it and a few more, carefully reviewing the padding and Hermitian-symmetric invertability situations? Your call.

**Comment by rossbar** [comment]
> To be concise, the original example concerning necessary conditions is wrong.

Note that this is not true in general - a closer look at the Notes section of irfft:

> The correct interpretation of the hermitian input depends on the length of
the original data, as given by `n`. This is because each input shape could
correspond to either an odd or even length signal. By default, `irfft`
assumes an even output length which puts the last entry at the Nyquist
frequency; aliasing with its symmetric counterpart. By Hermitian symmetry,
the value is thus treated as purely real. To avoid losing information, the
correct length of the real input **must** be given.

For this reason, the example provided above will fail if you change a to `a = np.random.rand(9)` instead of `8`, illustrating why the docs are correct in their current form.

**Comment by rossbar** [comment]
@williamhilton-works - just a quick ping to see if you're still pursuing these proposed changes. IMO the docs are correct in their current form (see above comment) but if there is some angle I'm missing please feel free to follow up!

**Comment by williamhilton-works** [comment]
You claim that the example I provided will fail when you change the argument to 9 instead of 8. This is not the case. Instead, you have elucidated that the statement itself in the documentation is false in general.

To recap, the documentation claims that irfft(rfft(a), len(a)) == a to within numerical accuracy. When you ran the example I provided, you found that _not _only__ does hypothesis1!=hypothesis2, but you also found that _both_ hypothesis1 and hypothesis2 were also not true in their entirety! (And most certainly not to within numerical accuracy, mind you.) I acknowledge that you do have a handle on what is really going on here, considering the info you pointed out on those finer details regarding the treatment of the Nyquist frequency, but the simple fact that the documentation is false remains.

Moreover, concerning the 'necessary condition' bit that I was going on about, notice that nothing is necessary for a falsity. E.g. Assume that your computer is currently turned on. Suppose someone then immediately claims that your computer is currently turned off. What condition is necessary, then, for your computer to be currently turned off? You will search and search, but you will find that there are literally no conditions whatsoever for your computer to be currently turned off, as it is false -- as it is assumed to currently be turned on.

Your point has provided evidence for further modification to documented statements. Unfortunately, for me, I find it unacceptable that my proposed modification fails to address that glaring inconsistency. For this reason, I shall no longer pursue these changes.

**Comment by seberg** [comment]
I don't follow, it is not a "necessary condition" for the statement to be true for a specific `a`, but it is necessary for the statement to be always true given arbitrary `a`.

In any case, in my opinion the proposed change is simply confusing to anyone not trying to disect this from the perspective of a mathematical proof (I am not convinced even sure then it helps or is even more correct). So maybe you can find a way to avoid the math jargon, but overall I think its much better as it is.

**Comment by williamhilton-works** [comment]
Good point. If it resonates with the community as it is, then I think the cost in pursing this  outweighs any potential benefit -- pedantic or otherwise.

**Pull request closed without merging**
