### PR TITLE
MAINT: Added comment pointing FIXME to relevant PR.

### LINKED ISSUE #15668: FIXME in `numpy/__init__.py` related to `numpy.lib` imports
There is a FIXME comment in `numpy/__init__.py` that doesn't seem to have a corresponding issue on GitHub, at least not one that I noticed with a cursory search of the issues.

https://github.com/numpy/numpy/blob/eb167a3fe540780f397a14817f54a95333fbcc6c/numpy/__init__.py#L140-L145

There is additional code in `numpy/__init__.py` related to this FIXME:

https://github.com/numpy/numpy/blob/eb167a3fe540780f397a14817f54a95333fbcc6c/numpy/__init__.py#L178-L184

My intent is getting this into the issue tracker so that it can be discussed/documented and synced up with the code comments. If there is an existing issue that I missed, I'd recommend updating the comment in `numpy/__init__.py` to point there.

### PR DESCRIPTION
**Pull request by rossbar**
Clarifies a FIXME comment in `numpy/__init__.py` by referencing
relevant discussion in issue tracker.

Closes #15668.

### CODE REVIEW

**Comment by mattip** [comment]
I think a comment along the lines of "ugly but changing this would break too many things and listing over 200 functions and classes is worse" would be more constructive

**Comment by rossbar** [comment]
It still might be worth keeping a comment that calls this particular import out for attention in the future - maybe @rgommers can weigh in?

**Comment by rgommers** [comment]
>  changing this would break too many things

why? shouldn't break anything I'd think?

**Comment by rgommers** [comment]
Perhaps also change `FIXME` to `NOTE` to prevent the next person to want to tackle this?

I think we'll want to change it at some point, together with a larger cleanup of namespaces (e.g. in the new NEP 37 `numpy.api` or similar)

**Comment by rossbar** [comment]
Made some changes pursuant the discussion:
 * FIXME -> NOTE
 * Reword of the actual comment to note that the import can be revisited in the future concurrent with namespace cleanup
 * Added reference to this discussion to provide further context

**Comment by charris** [comment]
Thanks Ross. I think this will naturally come under review if we decide to limit the API, there is only so much we can add to a note at this time.

**Comment by rossbar** [comment]
Agreed, thanks @charris

**Pull request merged**
