### PR TITLE
ENH Added `copy` keyword to `np.asarray` for closer compatability w/ ArrayAPI spec

### PR DESCRIPTION
**Pull request by Micky774**
Added `copy` keyword to `np.asarray` for closer compatability w/ ArrayAPI spec.

### CODE REVIEW

**Comment by BvB93** [comment]
So what exactly is the use case of this proposed change? ‘np.asarray(…)’ is already equivalent to ‘np.array(…,  copy=False)’, so what’s the point in duplicating this functionality? It kinda defeats the point of ‘np.asarray’.

**Comment by seberg** [comment]
@Micky774 adding this doesn't help, because the mismatch is much larger (and incompatible!).  In fact, this should be marked as **Breaking**, because the standard uses different semantics.  `False` has a different meaning.

**Comment by Micky774** [comment]
> @Micky774 adding this doesn't help, because the mismatch is much larger (and incompatible!). In fact, this should be marked as **Breaking**, because the standard uses different semantics. `False` has a different meaning.

I see. On a related note, what is the current sentiment towards convergence/adoption of Array API? In the slack group @rgommers had mentioned it may be worth adding the `copy` keyword for `asarray` and `reshape`. If the nuance here is that Array API has a different set of semantics, that's fine and I can close this PR, but what of other "compatible" changes such as the `device` kwarg, which would simply [be ignored](https://numpy.org/devdocs/reference/array_api.html#creation-functions-differences) by NumPy, but would us closer to Array API?

Follow-up: is there any plan on changing NumPy `copy` semantics to match Array API? For example through a long (and potentially painful) deprecation cycle?

**Comment by seberg** [comment]
Changing the `copy` semantics is a breaking change.  We can consider it, it simply was not pushed seriously yet.  For `np.array` it would be a large change, but then that is what `np.asarray` exists for (so maybe nudging people to that is not bad anyway).

So I think it is doable, but could be on the noisy side (affects a fair amount of users, but likely not a huge amount since `asarray` is more obvious).  It also is not particularly dangerous, I guess since the "failure" path would be an Exception telling you that no-copy was not possible.

I don't clearly remember the discussion at the time.  On the NumPy side a string `copy="never"` or enum `copy=copy.NEVER` seemed to be the crowd favorite, since it has a smooth transition and some disliked the "three way boolean" (with None having a distinct meaning).

**Comment by Micky774** [comment]
> Changing the `copy` semantics is a breaking change. We can consider it, it simply was not pushed seriously yet. For `np.array` it would be a large change, but then that is what `np.asarray` exists for (so maybe nudging people to that is not bad anyway).
> 
> So I think it is doable, but could be on the noisy side (affects a fair amount of users, but likely not a huge amount since `asarray` is more obvious). It also is not particularly dangerous, I guess since the "failure" path would be an Exception telling you that no-copy was not possible.
> 
> I don't clearly remember the discussion at the time. On the NumPy side a string `copy="never"` or enum `copy=copy.NEVER` seemed to be the crowd favorite, since it has a smooth transition and some disliked the "three way boolean" (with None having a distinct meaning).

Would this be something worth bringing up during a triage/community meeting? If so which one would be preferred? Or would this be better served as an async discussion?

**Comment by mattip** [comment]
> Would this be something worth bringing up during a triage/community meeting? 

Yes. I will add a label so if we miss it in the community meeting we can discuss it in the triage meeting.

**Comment by seberg** [comment]
Lets mention it today, but probably will just remove the label.  Resitance to the 3-way bool was dropped, so trying to transition to `copy=False` having the new meaning seems plausible now (removing the enum).

**Comment by seberg** [comment]
We didn't get to it today, but I will close the PR for now.  Not that it is bad, but I think the more important part is to do the other work first, juts adding `copy` here doesn't help much unfortunately.

**Pull request closed without merging**
