### PR TITLE
ENH: Provide functions to convert the axes of object arrays to and from lists

### LINKED ISSUE #14478: Provide functions to convert the last axis of object arrays to and from lists
Extracted from #14014.

Given a 2d array like:
```python
array([[list(['0.1', '0.2', '0.3'])],
       [list(['0.3', '0.4', '0.5'])],
       [list(['0.5', '0.6', '0.7'])]], dtype=object)
```

it would be nice to have some way to convert the array intothe 3d
```python
array([[['0.1', '0.2', '0.3'])],
       [['0.3', '0.4', '0.5']],
       [['0.5', '0.6', '0.7']]], dtype=object)
```

Presumably, if we built this it would be natural to provide a function to go in the other direction.

Filing this primarily so that I can close the original issue.

### PR DESCRIPTION
**Pull request by psimaj**
Closes #14478.
This pull request implements functionalities asked for in #14478.
I decided to implement the function converting arrays to arrays of lists in a way that allows choosing the axis to convert, as if we always converted the last (or next-to-last, depending how we look at it) axis, then those functions wouldn't be inverses of eachother; for example, converting
`array([list([[1, 2], 
                  [3, 4]])])`
with array_of_lists_to_array results in
`array([[[1, 2], 
             [3, 4]]])`
but converting the last axis of the above array into lists would yield
`array([[list([1, 2]), 
            list([3, 4])]])`
which is different to what we started with.
I would greatly appreciate opinions on the above change and regarding the names of the functions and their placement in the project structure (currently placed in lib/shape_base.py).

### CODE REVIEW

**Comment by psimaj** [comment]
@eric-wieser Could you please take a look at and review this PR? I see that some tests aren't passing, but I am not sure what exactly is wrong (locally everything passed) and it's my first PR, so I'd appreciate a little guidance.

**Comment by charris** [comment]
Should probably run this past the numpy mailing list.

**Comment by InessaPawson** [comment]
@psimaj Thank you for sharing your ideas! If you'd like to move this PR forward, I recommend asking for feedback on the NumPy mailing list: https://mail.python.org/archives/list/numpy-discussion@python.org/.

**Comment by mattip** [comment]
I think we should close this, as neither the issue nor the PR gained much traction.

**Comment by rossbar** [comment]
I'll go ahead and close this - if there's strong desire to push this idea forward, following up with the mailing list seems like a good place to start.

**Pull request closed without merging**
