### PR TITLE
DEP: Remove deprecated numpy.who

### PR DESCRIPTION
**Pull request by eendebakpt**
Remove deprecated `numpy.who`. 

Note: the removal is faster than the usual deprecation policy. See #23999 on the numpy 2.0 release.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks for helping with this effort @eendebakpt! 

This LGTM. I checked back, and `who` was proposed for removal several times, in NEP 52, in the linked tracking issue, and the older gh-12385. I also checked that it's not used at all in SciPy, scikit-learn, Pandas, or any other projects I have a clone of locally. So this should be good to go. I'll leave it open for a bit though, best to give these deprecation/removal PRs at least a couple of days to give folks a chance to comment.

**Comment by seberg** [comment]
I guess we might have a stray release note mentioning deprecation rather than removal that might be nice to edit.

I don't think this can break production code at worst course instructions might use it.  The one thing we could note is that e.g. Spyder has a variable explorer and I think there are extensions for IPython to get it too (i.e. there are nicer replacements available these days if you use rich IDEs).

**Comment by eendebakpt** [comment]
The only mentioning of deprecation of `who` I could find was in NEP 52 in the section `Cleaning up the main namespace`. There it was listed as one of the examples that could be deprecated (and later removed) from the main namespace. I do not want to modify the NEP though, I think it should remain static.

**Comment by seberg** [comment]
Took the liberty to remove the "deprecated" part, it never was, it's an either or.  I guess the deprecation was missing a release note fragment though, thanks for checking and updating.

**Comment by rgommers** [comment]
This PR picked up stray changes to two git submodules, can you revert that @eendebakpt? Also there's a merge conflict now. Other than that, this looks good to merge.

**Comment by rgommers** [comment]
CI is failing with `ERROR .. - ImportError: cannot import name 'who' from 'numpy.lib' `.

**Review by rgommers — APPROVED** [review]
Looks good and all CI is happy now - in it goes. Thanks again @eendebakpt!

**Pull request merged**
