### PR TITLE
TST: restore output of failing refguide-check tests

### PR DESCRIPTION
**Pull request by mattip**
gh-15430 added a context manager to restore the doctest environment after tests, but broke output reporting. This PR restores error reporting so 
```
python tools/refguide_check.py --rst doc/source/user/c-info.python-as-glue.rst
```

will now show the errors as it did before gh-15430

### CODE REVIEW

**Comment by mattip** [comment]
ping @sethtroisi

**Comment by mattip** [comment]
Single test run failure on travis unrelated.

**Comment by sethtroisi** [comment]
I proposed a fix in https://github.com/numpy/numpy/pull/15516,
it's simple and intuitive why it should work.
it's also after midnight and I'm totally understand if you'd prefer the safe rolled back first.

**Comment by mattip** [comment]
Closing in favor of gh-15516

**Pull request closed without merging**
