### PR TITLE
MAINT: Specify color in RGB in the docs about the new NumPy logo

### LINKED ISSUE #398: Specify the color space (sRGB) in design docs
Specify the color space (RGB) and change colors to RGB in all design documentation pertaining to numpy.org and the NumPy branding assets.

### PR DESCRIPTION
**Pull request by aerikpawson**
Specifying color in RGB in the guidelines for the new NumPy logo. Fixes numpy/numpy.org#398

### CODE REVIEW

**Comment by eric-wieser** [comment]
This doesn't look like it's related to #398, which is about specifying the colorspace itself.

**Comment by InessaPawson** [comment]
@aerikpawson The PR looks good to me. Thank you for bringing our attention to the change in the unofficial name of one of the colors (from Warm Black to Gunmetal). This makes me think that we should abandon these names altogether to avoid any confusion in the future. So, please remove them in this document.
Also, please review and make changes to this file: https://github.com/numpy/numpy.org/blob/master/README.md

**Comment by InessaPawson** [comment]
> This doesn't look like it's related to [numpy/numpy.org#398](https://github.com/numpy/numpy.org/issues/398), which is about specifying the colorspace itself.
> 
> cc @InessaPawson

@eric-wieser The proposed changes in the PR are correct. However, it’s not ready to be merged. (See the comment above.)
This issue is a part of the NumPy web team’s effort to take care of the color management of numpy.org and branding assets, at least on our end. 
My apologies for not including more details. Let me update the issue now.

**Comment by charris** [comment]
@InessaPawson Good to go?

**Review by InessaPawson — APPROVED** [review]
LGTM. Thank you, @aerikpawson!

**Comment by InessaPawson** [comment]
> @InessaPawson Good to go?

Now it is. Thank you, @charris!

**Comment by charris** [comment]
Thanks @aerikpawson .

**Pull request merged**
