### PR TITLE
MAINT: refactor to use assignment expressions (walrus operator :=)

### PR DESCRIPTION
**Pull request by mwtoews**
This PR refactors the codebase to use assignment expressions (aka “the walrus operator”) described by [PEP 572](https://peps.python.org/pep-0572/) supported by Python 3.8+. A common use-case for the operator is to evaluate [`re.match`](https://docs.python.org/3/library/re.html#re.match) results in a `if` statement, limiting the scope of the resulting variable.

### CODE REVIEW

**Comment by mattip** [comment]
Did you use a tool to find these or was it all manual?

**Comment by seberg** [comment]
TBH, I am a bit lukewarm towards blanket replace.  Some of these places do look better, but most just put more things onto a single line of code.

**Comment by mwtoews** [comment]
I'm not aware of any tools to help with this effort. Mostly just finding candidates with

    git grep -E -B1 -A1 "if [a-zA-Z0-9]+:"

then manually refactoring.

Any instances that are less readable (i.e. too much code on a single line) can be restored, just specify which ones.

**Comment by HaoZeke** [comment]
I think it would be a good idea to not touch the `f2py` code with this refactor. There is a lot of global state carried around there and its hard for me to tell at a glance which ones are used elsewhere.

**Comment by rossbar** [comment]
> I'm not aware of any tools to help with this effort.

I think `pyupgrade` is one of the standard tools for this type of auto-updating. I'm not sure whether it supports auto-upgrading code to use the walrus operator.

**Comment by rkern** [comment]
> Any instances that are less readable (i.e. too much code on a single line) can be restored, just specify which ones.

I mean, _personally_, I find _all_ of them less readable. The name gets lost in the expression, to my code-reading eyes. But that's just my aged-Pythonista brain and shouldn't be a controlling factor here.

In general, though, I don't like to see these refactors done mechanically en masse. I think a lot of the code here is not well-covered by tests. Personal preferences aside, I would be happy enough to see any one of these done individually when someone is touching that part of the code for other reasons (and happy enough to see the pattern used in new code). But if no one is looking at that code to modify it for other reasons, then the readability or scope leakage of the variable name is not particularly important.

**Comment by seberg** [comment]
Sounds like nobody is excited about it so I will just close it, thanks.  It's not like it's saving indention levels (maybe in one case it did).
`:=` can be nice, and maybe it would be more of a point if it was common in NumPy.  But I doubt it will be common in our code.

**Review by HaoZeke — CHANGES_REQUESTED** [review]
I think it would be a good idea to not touch the `f2py` code with this refactor. There is a lot of global state carried around there and its hard for me to tell at a glance which ones are used elsewhere.

**Pull request closed without merging**
