### PR TITLE
DOC: Merge doc strings of divide and true_divide.

### LINKED ISSUE #20085: DOC: `divide` vs. `true_divide`
### Issue with current documentation:

Currently, the docstrings of `numpy.divide`:and  `numpy.true_divide` are different:
https://github.com/numpy/numpy/blob/1eff1c543a8f1e9d7ea29182b8c76db5a2efc3c2/numpy/core/code_generators/ufunc_docstrings.py#L1064
https://github.com/numpy/numpy/blob/1eff1c543a8f1e9d7ea29182b8c76db5a2efc3c2/numpy/core/code_generators/ufunc_docstrings.py#L4014

Yet in the generated documentation, both [`numpy.divide`](https://numpy.org/doc/stable/reference/generated/numpy.divide.html) and [`numpy.true_divide` ](https://numpy.org/doc/stable/reference/generated/numpy.true_divide.html) use the dosctring of `numpy.true_divide`.

In a way, this does make sense, because in Python 3 `numpy.divide` is equivalent to `numpy.true_divide`. However:
1. I cannot find the mechanism which defines `numpy.divide` as an alias of `numpy.true_divide` in the documentation. Can someone help me with that?
2. Like the documentation of [`numpy.unicode_`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.unicode_):
   alias of [`numpy.str_`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.str_)
   I suggest the documentation of `numpy.divide` states it's an alias:
   alias of [`numpy.true_divide`](https://numpy.org/doc/stable/reference/generated/numpy.true_divide.html)

Finally, I'm not certain whether `divide` is an alias of `true_divide`, or `true_divide` an alias of `divide`. For example in `numpy/array_api/_elementwise_functions.py` I can find only `divide`, not `true_divide`:
https://github.com/numpy/numpy/blob/1eff1c543a8f1e9d7ea29182b8c76db5a2efc3c2/numpy/array_api/_elementwise_functions.py#L263-L274

### Idea or request for content:

_No response_

### PR DESCRIPTION
**Pull request by drosin**
Closes #20085

### CODE REVIEW

**Comment by Mukulikaa** [comment]
Hi @drosin, I finally had time to look deeper into this. Turns out it's slightly more complicated than we initially thought! The `divide` docstring doesn't show up because it has been aliased internally:
https://github.com/numpy/numpy/blob/2513620bfbb30fa55bbbba1902f29284adab650c/numpy/core/src/umath/umathmodule.c#L290-L293

It has been mentioned in this comment in `generate_umath.py` as well:
https://github.com/numpy/numpy/blob/2513620bfbb30fa55bbbba1902f29284adab650c/numpy/core/code_generators/generate_umath.py#L325

You'll see in `generate_umath.py` the docstring of `divide` is not fetched from `ufunc_docstrings.py` at all because of the above aliasing. Only the docstrings of `true_divide` are fetched:
https://github.com/numpy/numpy/blob/2513620bfbb30fa55bbbba1902f29284adab650c/numpy/core/code_generators/generate_umath.py#L339-L349

I am not sure if there is a way to correct the documentation without refactoring the entire code and weeding out `true_divide` from everywhere... Maybe @melissawm or @rgommers can think of something?

**Comment by drosin** [comment]
Hi @Mukulikaa, now I kept the true_divide doc string and removed the divide doc string. Before it was the other way around. Now, it seems that almost all tests are passing. 

Do you know why this one test is still failing?

**Comment by Mukulikaa** [comment]
The doctest is not passing for examples involving `argmax` and `argmin` in `how-to-index.rst`. It doesn't seem related to your changes, though it is definitely weird. 

Also, thanks for trying out a different approach to solve this issue but I think it'll be in our interest to keep `divide` instead of `true_divide` following the discussion in gh-20085. 

This will be discussed in the next triage meeting (next Wednesday I think?) and you are welcome to join the discussion!

**Comment by seberg** [comment]
@charris and me discussed it briefly, and we both thought that making `divide` the main one seems more reasonable.

**Comment by melissawm** [comment]
@drosin do you think you have all the info you need to move this forward? Feel free to ask for help otherwise. Thanks!

**Comment by drosin** [comment]
@Mukulikaa I made divide the main function as suggested. This results in error messages changing as shown in the diff (numpy/core/tests/test_datetime.py).

There are still tests failing. Where should I start to fix them?

**Comment by melissawm** [comment]
HI @drosin - even though there are no conflicts showing I believe you just need to rebase to get rid of the failures. You can do

```
$ git pull upstream main
$ git checkout merge_true_divide_doc
$ git rebase -i upstream/main
```

(resolve any conflicts if they arise) and push back your changes.

**Comment by drosin** [comment]
Hi @melissawm, I rebased. Now there are still some failures. How could I fix the failing checks?

**Comment by charris** [comment]
@drosin The example in `numpy/core/code_generators/ufunc_docstrings.py` line 1103 needs fixing. See https://tinyurl.com/y4wow8k2 for the error.

**Comment by drosin** [comment]
@charris The checks are now successful apart from travis. What's next?

Note that the error strings have changed for 1/0 division error saying 'divide' instead of 'true_divide'.

**Comment by Mukulikaa** [comment]
The rendered pages are [here](https://23790-908607-gh.circle-artifacts.com/0/doc/build/html/reference/generated/numpy.divide.html) and [here](https://23790-908607-gh.circle-artifacts.com/0/doc/build/html/reference/generated/numpy.true_divide.html).

**Comment by melissawm** [comment]
This is looking good! I was going to suggest including the mention to `true_divide` in the See Also section, but I realized this would also appear in the `true_divide` docstring itself, which would be weird. So I think this is ready - thanks for the hard work here @drosin !

**Pull request merged**
