### PR TITLE
SIMD: ARM Neon intrinsics implemention of MultiplyIntList

### PR DESCRIPTION
**Pull request by Qiyu8**
The performance of `MultiplyIntList ` has improved by 50% after using neon intrinsics in ARM machine. But I can't find any test case triggered this function because It's just a internal function. so I didn't write a benchmark.

### CODE REVIEW

**Comment by mattip** [comment]
This **does** seem like something that should be trivially optimized by the compiler. There is no need for scatter-gather or advanced conversions. Are we missing flags to enable vectorization?

**Comment by seberg** [comment]
These type of functions are probably only really used for dimensions, which typically hover at `<=3` items, I wonder if this is worth it for very short lists...  It also explains why its never used, we only really use this thing for shapes, which should always be `intp`...

**Comment by eric-wieser** [comment]
I'm with @matti here. In my mind, this falls squarely into "premature optimization" territory.

**Comment by matti** [comment]
@eric-wieser Glad to hear that, but I think you meant @mattip

**Comment by Qiyu8** [comment]
Thanks for the response, it's an premature optimization and don't have practical value(Only used in dimensions),  Will be closed. 😺

**Pull request closed without merging**
