### PR TITLE
BENCH: Added missing ufunc benchmarks

### PR DESCRIPTION
**Pull request by kenogo**
See #9621. I wasn't sure which acronym to use. If BUG is wrong please tell me and I'll change it to the correct one.

### CODE REVIEW

**Comment by kenogo** [comment]
Okay, how should I handle this? ```isnat``` is raising a ```ValueError```. I could add an exception that continues when it encounters a ```ValueError``` in ```bench_ufunc.py```. But I'm not sure whether ```isnat``` shouldn't be raising a ```TypeError``` instead. I could edit ```ufunc_type_resolution.c``` for that.

**Comment by kenogo** [comment]
```isnat``` was raising a ValueError if you passed it an argument that wasn't of the ```datetime``` or ```timedelta``` type. I corrected it to TypeError (I hope I actually did the right thing here and raising a ValueError was incorrect).

**Comment by seberg** [comment]
About isnat, I am not sure we put it in pretty recently, might have been an oversight, and maybe we should change the error type, but would need at least a release note mention.

**Comment by kenogo** [comment]
@seberg Should I put this under "Compatibility notes"?

**Comment by seberg** [comment]
Sounds right, it gets rearranged anyway, so probably not a big deal.

**Comment by eric-wieser** [comment]
Looks good to me. I'd probably squash those last three commits into one though, since tests don't pass on the intermediate commits.

**Comment by kenogo** [comment]
@eric-wieser Done! :)

**Review by eric-wieser — APPROVED** [review]
LGTM. @seberg, happy for the exception type to be changed without a deprecation? I don't think there's any way to do a deprecation anyway, and the alternative is to introduce a `class ValueOrTypeError` that derives from both.

**Comment by seberg** [comment]
Well, at least the ufunc is new in 1.13. I am not too happy about it, but my guess is we (and downstream) can manage.

**Comment by charris** [comment]
Thanks @kenogo .

**Pull request merged**
