### PR TITLE
ENH: Chain exception in memmap.py

### PR DESCRIPTION
**Pull request by ChrisAHolland**
This edit is relation to issue #15986. 
Only contains 1 exception edit for ease of maintainer review.
@eric-wieser

### CODE REVIEW

**Comment by eric-wieser** [comment]
Did you mean to close this?

**Comment by ChrisAHolland** [comment]
@eric-wieser I saw that it didn't pass some of the CI tests so I made the impulsive decision to close it and take a further look. I will open another PR to fix this!

**Comment by eric-wieser** [comment]
There's now a "make draft button" to the right that is a good way to mark PRs as not ready for review just yet, if you change your mind after submitting them.

**Comment by ChrisAHolland** [comment]
> There's now a "make draft button" to the right that is a good way to mark PRs as not ready for review just yet, if you change your mind after submitting them.

Thanks for the info! I reopened this PR and added another chained exception in #16067

**Pull request closed without merging**
