### PR TITLE
OpenVMS port

### PR DESCRIPTION
**Pull request by vorfol**
OpenVMS port

### CODE REVIEW

**Comment by seberg** [comment]
Thanks for working on this!  It doesn't bother me too much, but you can just keep editing the same PR by force pushing to a branch.  Half of the changes (the C-code ones) look like mostly actual bug fixes to me (even if it is impossible to trigger on other platforms), so this is very nice.

I am a bit curious whether we can avoid ship that header file, though?  It should be available to be found on the system?

For fastest review it might make things slightly easier if you split out the C changes that are basically bug fixes from build related/distutil changes (simply because different people tend to review them).  But overall, this seems very manageable, so just a thought.

**Comment by vorfol** [comment]
Thanks for review. I just wanted to merge and build the project on other systems to test whether I broke the code.
About header file: do you mean 'stdint_vms.h'? I found that header file in OpenVMS CRTL version 8.5 (and change it a little), but in CRTL 8.4 it is missing and some types and constants are already defined in other header files. I think no one took care about compatibility in OpenVMS.

**Comment by seberg** [comment]
Yeah, it seems strange to include `stdint_*` in NumPy, unless I am missing that we do this for other platforms as well?

**Comment by seberg** [comment]
@vorfol about testing, if you think you are far enough along, you can use our CI for it. It might be nicer to mark the PR as draft and keep updating though.

**Pull request closed without merging**
