### PR TITLE
STY: Use PEP 585 and 604 syntaxes throughout the .pyi stub files

### LINKED ISSUE #20631: ENH: Use PEP 585 and 604 syntaxes throughout the .pyi stub files
### Proposed new feature or change:

As of the mypy 0.920 release it is now possible to use the union operator and `builtins` type-subscription for both variables as well as annotations, while previously only the latter was possible. At some point these syntaxes should be adopted in the numpy .pyi stub files, as they generally improve readability and the likes of `typing.List` will (eventually) be deprecated in favor of `builtins.list`.

Examples
----------
``` python
# All expressions below are now legal in .pyi stub files, even in python <3.9
a: list[int]
b = list[int]

c: int | str
d = int | str
```

Further reading
----------------
* [PEP 585](https://www.python.org/dev/peps/pep-0585/): Type Hinting Generics In Standard Collections
* [PEP 604](https://www.python.org/dev/peps/pep-0604/): Allow writing union types as X | Y

### PR DESCRIPTION
**Pull request by BvB93**
Closes https://github.com/numpy/numpy/issues/20631

This PR implements the typing-based style improvements, made possible by PEP [585](https://www.python.org/dev/peps/pep-0585/) and [604](https://www.python.org/dev/peps/pep-0604/), in the .pyi stub files. Namely, using `builtins`/`collections.abc` subscriptable types over the generic aliases from `typing` and use of the `|` operator over `typing.Union` (and `Optional`).

There are a handful of places that have been excluded from this PR, namely `np.array_api` and a number of .py files in `numpy.typing`, the latter requiring python >= 3.9 and/or 3.10 for the use in runtime-valid type aliases.

### CODE REVIEW

**Comment by charris** [comment]
Passed with Python 3.10 on travis, failed with Python 3.8 with import `ABCmetaE   TypeError: 'ABCMeta' object is not subscriptable`.

**Comment by BvB93** [comment]
> Passed with Python 3.10 on travis, failed with Python 3.8 with import `ABCmetaE TypeError: 'ABCMeta' object is not subscriptable`.

Yeah, I just noticed I changed two runtime imports that I shouldn't have changed.
Should be fixed as of the latest rebase.

**Comment by BvB93** [comment]
The `np.linalg` failures on Cygwin seem to be unrelated, though the sheer number of them is somewhat concerning.
Any idea what could be going on here?
```
=========================== short test summary info ============================
FAILED ../../linalg/tests/test_linalg.py::TestSolve::test_sq_cases - Assertio...
FAILED ../../linalg/tests/test_linalg.py::TestInv::test_sq_cases - AssertionE...
FAILED ../../linalg/tests/test_linalg.py::TestCholesky::test_basic_property
FAILED ../../linalg/tests/test_linalg.py::TestTensorsolve::test_tensorsolve_result[shape1]
```

**Comment by charris** [comment]
> Any idea what could be going on here?

No. I've just started looking at that, something seems to have changed.

**Comment by charris** [comment]
Thanks Bas.

**Pull request merged**
