### PR TITLE
BUG: Fix error from np.array_equal with equal_nan=True

### PR DESCRIPTION
**Pull request by ivirshup**
Fix for #16377. Previously, this would error:

```python
np.array_equal(list("abc"), list("abc"), equal_nan=True)
```

This fixes that bug, and tests for it. 

This is a little messy, but I'm not sure if there is a nicer way to check if a ufunc could be applied to a given type.

### CODE REVIEW

**Comment by ivirshup** [comment]
I noticed `isnan` can actually be quite slow, so I've changed the method to minimize the number of times it's called. Basically, I've added more fast paths. To show that it actually makes the function faster, I've run a small benchmark using `1.19.0rc1`

<details>
<summary> Benchmarking code </summary>

```python
from itertools import product
import numpy as np
import pandas as pd

print(np.__version__)

def array_equal_1(a1, a2, equal_nan=False):
    """
    True if two arrays have the same shape and elements, False otherwise.

    Parameters
    ----------
    a1, a2 : array_like
        Input arrays.
    equal_nan : bool
        Whether to compare NaN's as equal. If the dtype of a1 and a2 is
        complex, values will be considered equal if either the real or the
        imaginary component of a given value is ``nan``.

        .. versionadded:: 1.19.0

    Returns
    -------
    b : bool
        Returns True if the arrays are equal.

    See Also
    --------
    allclose: Returns True if two arrays are element-wise equal within a
              tolerance.
    array_equiv: Returns True if input arrays are shape consistent and all
                 elements equal.

    Examples
    --------
    >>> np.array_equal([1, 2], [1, 2])
    True
    >>> np.array_equal(np.array([1, 2]), np.array([1, 2]))
    True
    >>> np.array_equal([1, 2], [1, 2, 3])
    False
    >>> np.array_equal([1, 2], [1, 4])
    False
    >>> a = np.array([1, np.nan])
    >>> np.array_equal(a, a)
    False
    >>> np.array_equal(a, a, equal_nan=True)
    True

    When ``equal_nan`` is True, complex values with nan components are
    considered equal if either the real *or* the imaginary components are nan.

    >>> a = np.array([1 + 1j])
    >>> b = a.copy()
    >>> a.real = np.nan
    >>> b.imag = np.nan
    >>> np.array_equal(a, b, equal_nan=True)
    True
    """
    import builtins
    from operator import is_

    try:
        a1, a2 = np.asarray(a1), np.asarray(a2)
    except Exception:
        return False
    if a1.shape != a2.shape:
        return False

    common_type_char = np.sctype2char(np.promote_types(a1.dtype, a2.dtype))
    # When we don't need to check for nan
    if not equal_nan:
        return bool(np.asarray(a1 == a2).all())
    # When isnan won't work, but there could be nan values
    elif common_type_char == "O":
        vecis = np.vectorize(is_)
        a1nan, a2nan = vecis(a1, np.nan), vecis(a2, np.nan)
    # When there can't be nan values
    elif not builtins.any(t.startswith(common_type_char) for t in np.isnan.types):
        return bool(np.asarray(a1 == a2).all())
    # When we can use
    else:
        a1nan, a2nan = np.isnan(a1), np.isnan(a2)
    # NaN's occur at different locations
    if not (a1nan == a2nan).all():
        return False
    # Shapes of a1, a2 and masks are guaranteed to be consistent by this point
    return bool(np.asarray(a1[~a1nan] == a2[~a1nan]).all())


def array_equal_2(a1, a2, equal_nan=False):
    """
    True if two arrays have the same shape and elements, False otherwise.

    Parameters
    ----------
    a1, a2 : array_like
        Input arrays.
    equal_nan : bool
        Whether to compare NaN's as equal. If the dtype of a1 and a2 is
        complex, values will be considered equal if either the real or the
        imaginary component of a given value is ``nan``.

        .. versionadded:: 1.19.0

    Returns
    -------
    b : bool
        Returns True if the arrays are equal.

    See Also
    --------
    allclose: Returns True if two arrays are element-wise equal within a
              tolerance.
    array_equiv: Returns True if input arrays are shape consistent and all
                 elements equal.

    Examples
    --------
    >>> np.array_equal([1, 2], [1, 2])
    True
    >>> np.array_equal(np.array([1, 2]), np.array([1, 2]))
    True
    >>> np.array_equal([1, 2], [1, 2, 3])
    False
    >>> np.array_equal([1, 2], [1, 4])
    False
    >>> a = np.array([1, np.nan])
    >>> np.array_equal(a, a)
    False
    >>> np.array_equal(a, a, equal_nan=True)
    True

    When ``equal_nan`` is True, complex values with nan components are
    considered equal if either the real *or* the imaginary components are nan.

    >>> a = np.array([1 + 1j])
    >>> b = a.copy()
    >>> a.real = np.nan
    >>> b.imag = np.nan
    >>> np.array_equal(a, b, equal_nan=True)
    True
    """
    import builtins
    from operator import is_
    from functools import partial

    try:
        a1, a2 = np.asarray(a1), np.asarray(a2)
    except Exception:
        return False
    if a1.shape != a2.shape:
        return False

    common_type_char = np.sctype2char(np.promote_types(a1.dtype, a2.dtype))
    comp = np.asarray(a1 == a2)

    if bool(comp.all()):
        return True
    elif not equal_nan:
        return False
    elif common_type_char == "O":
        # When isnan won't work, but there could be nan values
        _isnan = np.vectorize(partial(is_, np.nan), otypes="?")
    elif not builtins.any(t.startswith(common_type_char) for t in np.isnan.types):
        # When there can't be nan values
        return False
    else:
        # When we can use isnan
        _isnan = np.isnan
    # Check if all failed comparisons were due to nans
    if not _isnan(a1[~comp]).all() or not _isnan(a2[~comp]).all():
        return False
    else:
        return True


def generate_timings(array_shapes, nan_proportions):
    records = []

    for shape, prop in product(array_shapes, nan_proportions):
        record = {}
        record["array_shape"] = shape
        record["proportion_nan"] = prop
        a = np.ones(shape)
        n_nans = int(np.multiply.reduce(shape) * prop)
        a[tuple(np.random.choice(s, n_nans) for s in shape)] = np.nan
        record["1.19.0rc1"] = %timeit -o np.array_equal(a, a, equal_nan=True)
        record["initial"] = %timeit -o array_equal_1(a, a, equal_nan=True)
        record["current"] = %timeit -o array_equal_2(a, a, equal_nan=True)
        records.append(record)
    
    return records

df = pd.DataFrame.from_records(generate_timings([(100, 100), (1000, 1000)], [0., .01, .1, .9]))
df
```


</details> 

Here's a table of timing for running `array_equals(a, a, equal_nan=True)` at the current release candidate, and the two commits I've made here. I've varied `a` by shape and proportion of values that are `np.nan`. In this case, it is a `float` array.

|    | array_shape   |   proportion_nan | 1.19.0rc1                                                                 | initial     (11169c6)                                                              | current (3956241)                                                                   |
|---:|:--------------|-----------------:|:--------------------------------------------------------------------------|:--------------------------------------------------------------------------|:--------------------------------------------------------------------------|
|  0 | (100, 100)    |             0    | 40.1 µs ± 1.11 µs per loop | 47.2 µs ± 2.54 µs per loop | 10.3 µs ± 480 ns per loop |
|  1 | (100, 100)    |             0.01 | 41.1 µs ± 336 ns per loop  | 48.3 µs ± 751 ns per loop  | 26.8 µs ± 285 ns per loop  |
|  2 | (100, 100)    |             0.1  | 59.7 µs ± 2.41 µs per loop | 67.4 µs ± 1.49 µs per loop | 47.5 µs ± 512 ns per loop  |
|  3 | (100, 100)    |             0.9  | 106 µs ± 2.95 µs per loop  | 115 µs ± 3.37 µs per loop  | 112 µs ± 3.89 µs per loop  |
|  4 | (1000, 1000)  |             0    | 8.18 ms ± 372 µs per loop    | 8.46 ms ± 486 µs per loop    | 481 µs ± 56.5 µs per loop   |
|  5 | (1000, 1000)  |             0.01 | 7.62 ms ± 560 µs per loop    | 6.85 ms ± 682 µs per loop    | 1.07 ms ± 19.2 µs per loop  |
|  6 | (1000, 1000)  |             0.1  | 9.4 ms ± 391 µs per loop     | 9.71 ms ± 401 µs per loop    | 5.72 ms ± 396 µs per loop    |
|  7 | (1000, 1000)  |             0.9  | 12.6 ms ± 876 µs per loop    | 11.7 ms ± 646 µs per loop    | 13.5 ms ± 701 µs per loop    |

**Comment by ivirshup** [comment]
And upon further inspection, the last commit could also have poor performance. So I looked at how `pandas` does it, and it's quite simple: `np.all((a1 == a2) | (isnan(a1) & isnan(a2)))`. It turns out this does pretty well. I'm going to think about this a bit more. I've included some benchmarks for floating point values below which show performance for a few cases.

<details>
<summary> Benchmark code </summary>

```python
from itertools import product
import numpy as np
import pandas as pd
import builtins
from operator import is_
from functools import partial

print(np.__version__)

def array_equal_1(a1, a2, equal_nan=False):
    import builtins
    from operator import is_

    try:
        a1, a2 = np.asarray(a1), np.asarray(a2)
    except Exception:
        return False
    if a1.shape != a2.shape:
        return False

    common_type_char = np.sctype2char(np.promote_types(a1.dtype, a2.dtype))
    # When we don't need to check for nan
    if not equal_nan:
        return bool(np.asarray(a1 == a2).all())
    # When isnan won't work, but there could be nan values
    elif common_type_char == "O":
        vecis = np.vectorize(is_)
        a1nan, a2nan = vecis(a1, np.nan), vecis(a2, np.nan)
    # When there can't be nan values
    elif not builtins.any(t.startswith(common_type_char) for t in np.isnan.types):
        return bool(np.asarray(a1 == a2).all())
    # When we can use
    else:
        a1nan, a2nan = np.isnan(a1), np.isnan(a2)
    # NaN's occur at different locations
    if not (a1nan == a2nan).all():
        return False
    # Shapes of a1, a2 and masks are guaranteed to be consistent by this point
    return bool(np.asarray(a1[~a1nan] == a2[~a1nan]).all())


def array_equal_2(a1, a2, equal_nan=False):
    import builtins
    from operator import is_
    from functools import partial

    try:
        a1, a2 = np.asarray(a1), np.asarray(a2)
    except Exception:
        return False
    if a1.shape != a2.shape:
        return False

    common_type_char = np.sctype2char(np.promote_types(a1.dtype, a2.dtype))
    comp = np.asarray(a1 == a2)

    if bool(comp.all()):
        return True
    elif not equal_nan:
        return False
    elif common_type_char == "O":
        # When isnan won't work, but there could be nan values
        _isnan = np.vectorize(partial(is_, np.nan), otypes="?")
    elif not builtins.any(t.startswith(common_type_char) for t in np.isnan.types):
        # When there can't be nan values
        return False
    else:
        # When we can use isnan
        _isnan = np.isnan
    # Check if all failed comparisons were due to nans
    if not _isnan(a1[~comp]).all() or not _isnan(a2[~comp]).all():
        return False
    else:
        return True

def array_equal_3(a1, a2, equal_nan=False):
    try:
        a1, a2 = np.asarray(a1), np.asarray(a2)
    except Exception:
        return False
    if a1.shape != a2.shape:
        return False

    common_type_char = np.sctype2char(np.promote_types(a1.dtype, a2.dtype))
    comp = np.asarray(a1 == a2)

    if bool(comp.all()):
        return True
    elif not equal_nan:
        return False
    elif common_type_char == "O":
        # When isnan won't work, but there could be nan values
        _isnan = np.vectorize(partial(is_, np.nan), otypes="?")
    elif not builtins.any(t.startswith(common_type_char) for t in np.isnan.types):
        # When there can't be nan values
        return False
    else:
        # When we can use isnan
        _isnan = np.isnan
    # Check if all failed comparisons were due to nans
    return np.all(comp | (_isnan(a1) & _isnan(a2)))


def generate_timings_equiv(funcs: "Mapping[str, Callable]", array_shapes, nan_proportions):
    records = []

    for shape, prop in product(array_shapes, nan_proportions):
        record = {}
        record["array_shape"] = shape
        record["proportion_nan"] = prop
        a = np.ones(shape)
        n_nans = int(np.multiply.reduce(shape) * prop)
        a[tuple(np.random.choice(s, n_nans) for s in shape)] = np.nan
        print(record)
        for k, f in funcs.items():
            record[k] = %timeit -o f(a, a, equal_nan=True)
        records.append(record)

    return pd.DataFrame.from_records(records)

def generate_timings_diff_patterns(funcs: "Mapping[str, Callable]", array_shapes, nan_proportions):
    records = []

    for shape, prop in product(array_shapes, nan_proportions):
        record = {}
        record["array_shape"] = shape
        record["proportion_nan"] = prop
        a = np.ones(shape)
        b = np.ones(shape)
        n_nans = int(np.multiply.reduce(shape) * prop)
        a[tuple(np.random.choice(s, n_nans) for s in shape)] = np.nan
        b[tuple(np.random.choice(s, n_nans) for s in shape)] = np.nan
        print(record)
        for k, f in funcs.items():
            record[k] = %timeit -o f(a, b, equal_nan=True)
        records.append(record)

    return pd.DataFrame.from_records(records)

def generate_timings_diff_vals(funcs: "Mapping[str, Callable]", array_shapes, nan_proportions):
    records = []

    for shape, prop in product(array_shapes, nan_proportions):
        record = {}
        record["array_shape"] = shape
        record["proportion_nan"] = prop
        a = np.ones(shape)
        b = np.ones(shape)
        n_nans = int(np.multiply.reduce(shape) * prop)
        indices = tuple(tuple(np.random.choice(s, n_nans) for s in shape))
        a[indices] = np.nan
        b[tuple(i[:-(n_nans // 10)] for i in indices)] = np.nan
        print(record)
        for k, f in funcs.items():
            record[k] = %timeit -o f(a, b, equal_nan=True)
        records.append(record)

    return pd.DataFrame.from_records(records)

funcs = {"1.19.0rc1": np.array_equal, "take1": array_equal_1, "take2": array_equal_2, "take3": array_equal_3}
shapes = [(1000,), (1000000,)]
props = [0, .1, .5, .9]

df_equiv = generate_timings_equiv(funcs, shapes, props)
df_patt = generate_timings_diff_patterns(funcs, shapes, props)
df_vals = generate_timings_diff_vals(funcs, shapes, props)

for df in [df_equiv, df_patt, df_vals]:
    print(df.to_markdown())
```

</details>

<details>
<summary> Benchmark results for floating point </summary>


When the arrays are equal

|    | array_shape   |   proportion_nan | 1.19.0rc1                                                                  | take1                                                                     | take2                                                                      | take3                                                                     |
|---:|:--------------|-----------------:|:---------------------------------------------------------------------------|:--------------------------------------------------------------------------|:---------------------------------------------------------------------------|:--------------------------------------------------------------------------|
|  0 | (1000,)       |              0   | 11.8 µs ± 52.6 ns| 18.8 µs ± 377 ns| 6.44 µs ± 726 ns | 4.57 µs ± 163 ns|
|  1 | (1000,)       |              0.1 | 13.4 µs ± 586 ns | 20.3 µs ± 558 ns | 18.6 µs ± 1.14 µs| 14.3 µs ± 264 ns|
|  2 | (1000,)       |              0.5 | 14.6 µs ± 221 ns | 20.8 µs ± 256 ns | 20.9 µs ± 409 ns  | 14.4 µs ± 131 ns|
|  3 | (1000,)       |              0.9 | 14 µs ± 92.8 ns  | 20.1 µs ± 219 ns | 21.2 µs ± 131 ns  | 14.2 µs ± 145 ns|
|  4 | (1000000,)    |              0   | 7.83 ms ± 93.7 µs   | 7.83 ms ± 45.5 µs  | 328 µs ± 5.86 µs   | 323 µs ± 4.48 µs  |
|  5 | (1000000,)    |              0.1 | 9.45 ms ± 87.2 µs   | 9.44 ms ± 44.3 µs  | 4.93 ms ± 274 µs    | 957 µs ± 13.1 µs  |
|  6 | (1000000,)    |              0.5 | 13 ms ± 166 µs      | 13 ms ± 227 µs     | 11.1 ms ± 108 µs    | 964 µs ± 15.7 µs  |
|  7 | (1000000,)    |              0.9 | 12 ms ± 224 µs      | 12 ms ± 137 µs     | 12.1 ms ± 287 µs    | 956 µs ± 11.7 µs  |

When the pattern of `nans` doesn't have significant overlap

|    | array_shape   |   proportion_nan | 1.19.0rc1                                                                  | take1                                                                      | take2                                                                     | take3                                                                      |
|---:|:--------------|-----------------:|:---------------------------------------------------------------------------|:---------------------------------------------------------------------------|:--------------------------------------------------------------------------|:---------------------------------------------------------------------------|
|  0 | (1000,)       |              0   | 11.8 µs ± 48.2 ns| 18.1 µs ± 136 ns | 5.86 µs ± 67 ns | 4.16 µs ± 91.4 ns|
|  1 | (1000,)       |              0.1 | 5.61 µs ± 14.1 ns| 11.3 µs ± 111 ns | 14.6 µs ± 175 ns| 14.1 µs ± 113 ns |
|  2 | (1000,)       |              0.5 | 5.55 µs ± 31.9 ns| 11.4 µs ± 93.6 ns| 15.6 µs ± 115 ns| 14 µs ± 88.7 ns  |
|  3 | (1000,)       |              0.9 | 5.55 µs ± 17.1 ns| 11.3 µs ± 68.2 ns| 15.3 µs ± 213 ns| 14.1 µs ± 143 ns |
|  4 | (1000000,)    |              0   | 6.94 ms ± 85.5 µs   | 7.06 ms ± 54.9 µs   | 611 µs ± 11.8 µs  | 612 µs ± 9.21 µs   |
|  5 | (1000000,)    |              0.1 | 1.54 ms ± 54.7 µs  | 1.55 ms ± 53.4 µs  | 4.37 ms ± 160 µs   | 1.61 ms ± 16.3 µs  |
|  6 | (1000000,)    |              0.5 | 1.56 ms ± 76.5 µs  | 1.57 ms ± 37.3 µs  | 6 ms ± 70.7 µs     | 1.58 ms ± 29.4 µs  |
|  7 | (1000000,)    |              0.9 | 1.54 ms ± 43.8 µs  | 1.55 ms ± 57.8 µs  | 4.86 ms ± 95.1 µs  | 1.59 ms ± 15.5 µs  |

When the pattern of `nan`s overlaps a lot

|    | array_shape   |   proportion_nan | 1.19.0rc1                                                                  | take1                                                                      | take2                                                                      | take3                                                                     |
|---:|:--------------|-----------------:|:---------------------------------------------------------------------------|:---------------------------------------------------------------------------|:---------------------------------------------------------------------------|:--------------------------------------------------------------------------|
|  0 | (1000,)       |              0   | 12 µs ± 43.1 ns  | 18.4 µs ± 411 ns | 5.98 µs ± 77.7 ns| 4.18 µs ± 115 ns|
|  1 | (1000,)       |              0.1 | 5.68 µs ± 34.8 ns| 11.6 µs ± 87.1 ns| 18 µs ± 159 ns   | 14.5 µs ± 367 ns|
|  2 | (1000,)       |              0.5 | 5.75 µs ± 43.9 ns| 11.6 µs ± 342 ns | 21.8 µs ± 1.36 µs | 14.9 µs ± 239 ns|
|  3 | (1000,)       |              0.9 | 5.98 µs ± 116 ns | 11.4 µs ± 100 ns | 20.9 µs ± 176 ns  | 14.9 µs ± 403 ns|
|  4 | (1000000,)    |              0   | 8.67 ms ± 397 µs    | 8.56 ms ± 175 µs    | 713 µs ± 5.26 µs   | 697 µs ± 5.99 µs  |
|  5 | (1000000,)    |              0.1 | 1.61 ms ± 9.35 µs   | 1.63 ms ± 18.1 µs  | 6.47 ms ± 192 µs    | 2.22 ms ± 430 µs   |
|  6 | (1000000,)    |              0.5 | 1.84 ms ± 146 µs    | 1.8 ms ± 294 µs    | 13.3 ms ± 281 µs    | 1.93 ms ± 35.2 µs  |
|  7 | (1000000,)    |              0.9 | 1.69 ms ± 71 µs    | 1.66 ms ± 65.9 µs   | 14.7 ms ± 1.15 ms   | 1.9 ms ± 72.5 µs   |

</details>

**Comment by charris** [comment]
@ivirshup Looks like a good problem to fix. Do you wish to pursue this?

**Comment by seberg** [comment]
I am going to close this.  At this point, I think the solution may be to add a unicode and string loop to `np.isnan` (potentially an object one, if we can agree on using `bool(obj != obj)` to define `NaN`).
The additional complexities currently in the PR do not seem the right angle to me.

However, it *would* be great to look into fixing `isnan`, and very interesting to look into adding a generic solution to enable checking wether a type dtype supports `NaN`s (unordered) values or not.

**Pull request closed without merging**
