### PR TITLE
ENH: adds type hints to numpy.version

### LINKED ISSUE #17702: ENH: Add annotations to `numpy.version`
[`numpy.version`](https://github.com/numpy/numpy/blob/d62b0ee88b20e5946fe49f0ba533b3e547e4d4f1/numpy/version.pyi) is a small sub-module whose objects are rather straightforward to annotate.
I'd say this is a suitable candidate for a "good first issue".

### PR DESCRIPTION
**Pull request by dpfens**
To address #17702,  adds type annotations to the generated `numpy.version` submodule

### CODE REVIEW

**Review by BvB93 — COMMENTED** [review]
Looks good overall; I suppose we can actually safelly use inline annotations here.

Can you delete the (now redundant) `numpy/version.pyi` file?
Afterwards the PR is good to go IMO.

**Comment by dpfens** [comment]
@BvB93 Done.  Is there a better practice for adding these annotations?  If so, I can change the annotations to match it

**Comment by BvB93** [comment]
> @BvB93 Done. Is there a better practice for adding these annotations? If so, I can change the annotations to match it

Naah, everything is looking good now.

For most of NumPy we're using stub files (`.pyi`) to store the annotations because of two reasons:
* In order to avoid importing the `typing` module during runtime (as this takes time).
* Parts of NumPy are written in C, so there is no normal `.py` file where we can place the annotations.

`numpy.version` is one of the rare few modules where neither of these concerns are relevant,
 so we can use inline annotations exactly as you've done.

**Comment by BvB93** [comment]
Ah, can you delete the line below? This should fix the failing tests.

https://github.com/numpy/numpy/blob/93d3e7c247b66ec54d1095df30e99a95b4af9c72/numpy/typing/tests/test_isfile.py#L15

**Comment by dpfens** [comment]
Sounds good.  Just deleted that line.

**Review by BvB93 — APPROVED** [review]
LGTM now, thank you for your contribution!

**Comment by seberg** [comment]
Thanks @dpfens and Bas.

**Pull request merged**
