### PR TITLE
DOC, BLD: reword release note, upgrade sphinx version

### PR DESCRIPTION
**Pull request by mattip**
* Reword release note so that it does not end with a bullet list to work around problem with towncrier
* Upgrade sphinx version to remove deprecation warning

### CODE REVIEW

**Comment by mattip** [comment]
Not sure I understand what is going on. The fragment [renders well in the PR](https://10910-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/release/1.18.0-notes.html#passing-shape-0-to-factory-functions-in-numpy-rec-is-deprecated) but then after merge [broke](https://circleci.com/gh/numpy/numpy/11346?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) gh-15195 (the error, all the way at the end, is 
```
1.19.0-notes.rst:30: WARNING: \
Bullet list ends without a blank line; unexpected unindent.
```

**Comment by mattip** [comment]
The release note is [now rendered], but with an extra "NumPy 1.19.0 Release Notes" link between the 1.19 and 1.18.1 release notes. I cannot reporduce following the CI steps offline

**Review by eric-wieser — APPROVED** [review]
Thanks for looking into this.

I think we should put this in since it unblocks CI, even if the rendering is a bit weird.

**Comment by seberg** [comment]
I somewhat hope that new blank line that went in with the other PR was the reason for the back and forth, but not sure. In any case I will just put this in as wel,l the change looks good.

**Pull request merged**
