### PR TITLE
TYP: Fix type of ``copy`` argument in ``ndarray.reshape``

### PR DESCRIPTION
**Pull request by Azureblade3808**
The counterpart of `None` should be `builtins.bool` instead of `bool`(`numpy.bool`).

### CODE REVIEW

**Review by jorenham — COMMENTED** [review]
Thanks for this! 
I noticed that `copy=np.bool(True)` is also legal at runtime, so how about allowing both, i.e. `builtins.bool | np.bool | None = None`?

**Comment by jorenham** [comment]
I guess that if you want to get technical about it, `copy` should allow anything that implements `__bool__`, which according to typeshed, is `object`. 
But that'd be more confusing than it would be helpful IMO.

**Comment by Azureblade3808** [comment]
Sorry for being late.

I believe that types of `copy`s in `ndarray.reshape` and `numpy.reshape` need to be identical. And type for the latter one is `None | bool` which translates into `None | builtins.bool` because `numpy.bool` is not imported in the related file.

So I think the proposed change in this PR is reasonable in its current form.

**Comment by jorenham** [comment]
> I believe that types of `copy`s in `ndarray.reshape` and `numpy.reshape` need to be identical. And type for the latter one is `None | bool` which translates into `None | builtins.bool` because `numpy.bool` is not imported in the related file.

I agree. But if you feel like it, you could add the `numpy.bool` type to both `reshape` functions. Either way would be fine by me, so it's up to you.

**Comment by Azureblade3808** [comment]
After reading some other code in this repository, I decide not to add `numpy.bool` so that boolean types can be accordant.

**Comment by jorenham** [comment]
thanks @Azureblade3808

**Pull request merged**
