### PR TITLE
BLD: update vendored Meson for cross-compilation patches

### PR DESCRIPTION
**Pull request by rgommers**
Pulls in https://github.com/numpy/meson/pull/16 from our Meson fork for 2.1.0 (xref gh-27044). A full update to Meson 1.5.1 won't make it in in time for 2.1.0, so this is helpful.

~Draft PR to test in CI before merging https://github.com/numpy/meson/pull/16~

### CODE REVIEW

**Comment by rgommers** [comment]
This is integrating a change conda-forge would like before the 2.1.x branch creation. CI is happy, so I'll go ahead and merge straight away.

**Comment by charris** [comment]
Does this need a backport?

**Comment by rgommers** [comment]
To 2.0.x? I didn't consider that yet. Not sure - @h-vetinari?

**Comment by h-vetinari** [comment]
If there's a chance for a 2.0.2, I think it should be backported. If someone creates a branch at the commit in numpy/meson that's currently in 2.0.x, I can do the same backport there.

**Comment by h-vetinari** [comment]
> @h-vetinari `vendored-meson/meson` is a submodule, nothing special needed.

I get the submodule part, but I had falsely assumed that the vendored meson had already diverged between 2.0.x and main.

**Pull request merged**
