### PR TITLE
TST: get more info in shippable failures

### PR DESCRIPTION
**Pull request by charris**
~Also change pytest-xdist for pytest.~

### CODE REVIEW

**Comment by mattip** [comment]
Maybe one more?
```
diff --git a/numpy/tests/test_public_api.py b/numpy/tests/test_public_api.py
index a9d6da01c..631eb836a 100644
--- a/numpy/tests/test_public_api.py
+++ b/numpy/tests/test_public_api.py
@@ -14,6 +14,9 @@ try:
 except ImportError:
     ctypes = None
 
+# from setuptools v49.2.0, setuptools warns if distutils is imported first,
+# so pre-emptively import setuptools
+import setuptools
 
 def check_dir(module, module_name=None):
     """Returns a mapping of all objects with the wrong __module__ attribute."""

```

**Comment by charris** [comment]
> Maybe one more?

Getting late for me. I'm thinking the real problem is in xdist since this doesn't happen without it.

**Comment by mattip** [comment]
Close/reopen after gh-16857

**Comment by mattip** [comment]
I took the liberty of pushing another fix

**Comment by mattip** [comment]
The point of this warning is that setuptools now vendors its own distutils package, so by importing setuptools it injects setuptools.distutils in sys.modules as if it is the stdlib distutils. So on the one hand we could pin our CI to use setuptools<49.2.0, but then one of the downstream projects might update setuptools and start getting warnings that actually come from numpy.

Another choice would be to require setuptools>=49.2.0, and refactor our code to import setuptools.distutils everywhere we import distutils.

**Comment by charris** [comment]
> setuptools now vendors its own distutils package

That seems... dangerous. There is probably a good reason for it, but replacing the standard library is darn fragile because of all the issues we are seeing.

**Comment by mattip** [comment]
So the best course of action for now might be to pin `setuptools<49.2.0`. I guess we can merge what we have here as a best-effort, or maybe revert some of the more invasive ones?

**Comment by charris** [comment]
> I guess we can merge what we have here as a best-effort, or maybe revert some of the more invasive ones?

I rather avoid making a mess working around this, especially if it get fixed in the long run. I'd be more in favor of pinning the version and removing the workarounds we have already added. Things work now, so we can wait until upstream shakes out.

**Comment by charris** [comment]
The best procedure is probably to pin first, then maybe revert the workarounds.

**Comment by charris** [comment]
The setuptools version has been pinned.

**Pull request closed without merging**
