### PR TITLE
DOC: Better document 'order' argument of 'sort' and friends

### LINKED ISSUE #5927: Incomplete documentation for sort() and friends: order argument
In the documentation of `numpy.sort()` and friends (`numpy.recarray.sort()`, `numpy.ndarray.sort()`, at least), the `order` parameter is lacking two pieces of information:

- The current documentation mentions that it is a *list*, but the example is with a *string* (record name): the documentation should state that a string is also accepted.

- The current documentation does not describe what is the default behavior of `order` when it is not specified. I guess that the lexicographic order on the records is used? or maybe only the first record field is sorted? It would be useful to document this so that user know what they are getting, in this important (default) case.

### PR DESCRIPTION
**Pull request by jaimefrio**
Closes #5927 and #5901

### CODE REVIEW

**Comment by charris** [comment]
Just to be sure, the last of the unspecified fields it the dominant one?

**Comment by jaimefrio** [comment]
I think it's the other way around... it's not like `lexsort`, where you call `argsort` once per field, in reverse relevance order, i.e. the last one determines the ordering except for ties.

What `order` does is temporarily put those items at the front of the `'names'` tuple of the dtype. Comparison for dtypes with fields compares the fields in order, and stops as soon as it does not find a tie. So in this case there is a single sort call, and it is the first, not the last, that dominates the ordering, except for ties.

**Comment by charris** [comment]
So they are sorted in lexicographical order by fields, left to right. Might be worth mentioning that in the documentation. (lexsort is lexicographical order, right to left ;)

**Comment by charris** [comment]
Thanks Jaime.

**Pull request merged**
