### PR TITLE
Fixed Issue #2477 (Trac #1884)

### PR DESCRIPTION
**Pull request by mshubhankar**
I've changed the nx.asarray() to nx.asanyarray() for the function polyval.
As suggested by charris , i've also checked the other functions for the same problem and changed the 
function call in polyint and polyder also. 
Hope it works!

(#2477)

### CODE REVIEW

**Comment by charris** [comment]
This is not correct for `polyint` and `polyder`, as the input is the coefficients or an instance of `poly1d`. I'd say that passing in a masked array should be an error if anything is masked, but it may not be worth the effort to check that.

For the `polyval` case, you should make a test that the type is preserved correctly. a good place for the test is `numpy/lib/tests/test_polynomial.py`. Hmm, that test module is rather messy and incomplete, but you can probably just add a
```
def test_polyval(self):
```
method to the misnamed `TestDocs` class.

**Comment by mshubhankar** [comment]
I am not able to run the test_polynomial.py file. It says that i don't have nose installed even after installing nose using sudo pip install nose. 
Traceback (most recent call last):
  File "test_polynomial.py", line 188, in <module>
    run_module_suite()
  File "/home/shubhankar/.local/lib/python2.7/site-packages/numpy/testing/nosetester.py", line 124, in run_module_suite
    nose = import_nose()
  File "/home/shubhankar/.local/lib/python2.7/site-packages/numpy/testing/nosetester.py", line 74, in import_nose
    raise ImportError(msg)
ImportError: Need nose >= 0.10.0 for tests - see http://somethingaboutorange.com/mrl/projects/nose

**Comment by pv** [comment]
Use `pip install --user FOO` instead of `sudo pip install FOO`, unless
you are absolutely sure you need the latter.

**Comment by charris** [comment]
@mshubhankar Any progress?

**Comment by eric-wieser** [comment]
This is duplicated by #6891, which is also incorrect, but at least a little more recent

**Comment by charris** [comment]
Closing as inactive.

**Pull request closed without merging**
