### PR TITLE
CI: BLD: build wheels and fix test suite for Python 3.12

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
Hmm, I tested on GitHub Actions on my own fork and that is happy with

```
python: ["cp312"]
env:
    CIBW_PRERELEASE_PYTHONS: True
```

The Cirrus CI yaml is a little different; I expected this to work but it doesn't:
```
env:
        CIBW_PRERELEASE_PYTHONS: True
        CIBW_BUILD: cp312-*
```
it ends with:
```
cibuildwheel: No build identifiers selected: BuildSelector(build_config='cp312-*', skip_config='cp36-* cp37-* cp-38* pp37-* *-manylinux_i686 *_ppc64le *_s390x *-musllinux_aarch64 *-win32', requires_python=<SpecifierSet('>=3.9')>, prerelease_pythons=True)
```
not sure if it's not yet supported yet or the `cp312-*` selector needs a tweak. If anyone happens to know, that would be helpful here.

**Comment by rgommers** [comment]
`test_requirements.txt` is annoying, we now need it with an unpinned `setuptools` for Python 3.12, and `==59.2.0`  on other Python versions. Guess no choice but to duplicate it for now.

**Comment by mattip** [comment]
Is the cibuildwheel version current on that job? I see [2.12.1](https://github.com/numpy/numpy/blob/cbaf0de567768339926f7cb8d1a3ef3803c170d4/tools/ci/cirrus_wheels.yml#L3) where 2.13.1 is the latest.

**Comment by mattip** [comment]
> Guess no choice but to duplicate it

you mean to put a selector on the line in `test_requirements.txt` for the python version, or do you want to duplicate the file?

**Comment by rgommers** [comment]
Thanks @mattip, good catches. My brain is kinda fried it seems after the mini-sprint in the last 36 hours:)

This is ready now. For merging it, please include `[wheel build]` in the merge commit message, that'll kick off new wheel builds for upload to the nightlies bucket.

**Comment by rgommers** [comment]
The one CI failure is a connection issue; the actual job had completed and is green in Azure.

**Comment by rgommers** [comment]
@seberg or @charris would one of you mind reviewing this? Matti is traveling for a little while so I don't expect he'll get to this soon, and I suspect some folks in downstream projects are keenly awaiting the 3.12 nightlies.

**Comment by mattip** [comment]
Thanks @rgommers. Lets keep things moving.

**Comment by mattip** [comment]
I merged with the github button and will manually kick off a wheel build

**Comment by rgommers** [comment]
Ah, guess I was wrong - thanks Matti!

**Comment by seberg** [comment]
:tada: I think manual button doesn't trigger the cirrus builds, but it probably doesn't matter much in practice, the next build is tomorrow anyway.

**Pull request merged**
