### PR TITLE
MAINT: Various fixups from main.

### PR DESCRIPTION
**Pull request by charris**
Meson related bits from main that have not yet been backported.

### CODE REVIEW

**Comment by charris** [comment]
There are still significant changes in `numpy/linalg`, expecially `numpy/linalg/umath_linalg.cpp`, but I don't know if we need them.

**Comment by charris** [comment]
@mattip Do we need the `numpy/testing/_private/extbuild.py` update?

**Comment by mattip** [comment]
No, it is fine to continue using setuptools in those tests

**Comment by charris** [comment]
> No, it is fine to continue using setuptools in those tests

That doesn't leave much then, I don't even think the upload needs changing unless we do nightlies.

**Pull request closed without merging**
