### PR TITLE
BUG: made view of new array to fix ix_ bug

### LINKED ISSUE #6062: BUG: ix_ modifies input arrays
Regression that was introduced in gh-5805. Discovered when running Scipy tests against numpy master:

    ======================================================================
    ERROR: test_qhull.TestUtilities.test_more_barycentric_transforms
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/Users/rgommers/Code/bldscipy/scipy/spatial/tests/test_qhull.py", line 310, in test_more_barycentric_transforms
        grid = np.c_[list(map(np.ravel, np.broadcast_arrays(*np.ix_(*([x]*ndim)))))].T
      File "/Users/rgommers/Code/numpy/numpy/lib/index_tricks.py", line 77, in ix_
        raise ValueError("Cross index must be 1 dimensional")
    ValueError: Cross index must be 1 dimensional

A simple way to reproduce the issue:

    >>> x = np.linspace(0, 1, num=5)
    >>> np.ix_(*([x] * 4))
    Traceback (most recent call last):
      File "<ipython-input-6-b0c751ea5a84>", line 1, in <module>
    np.ix_(*([x] * 4))
      File "/Users/rgommers/Code/numpy/numpy/lib/index_tricks.py", line 77, in ix_
        raise ValueError("Cross index must be 1 dimensional")
    ValueError: Cross index must be 1 dimensional

    >>> x.shape
    (5, 1, 1, 1)

Solution is simply to make a copy when constructing output arrays.

### PR DESCRIPTION
**Pull request by githubmlai**
closes gh-6062

done with help of Sebastian Berg! =)

### CODE REVIEW

**Comment by rgommers** [comment]
In order to make it a stronger regression test, you may also want to check the shape of the input is unchanged:

    assert_equal(x.shape, (length_of_vector,))

Other than that, looks good to me. Thanks @githubmlai

**Comment by githubmlai** [comment]
Ok just added the suggested test

**Comment by jaimefrio** [comment]
It doesn't seem to be showing on github, have you pushed your changes?

**Comment by githubmlai** [comment]
Ok sorry didn't commit correctly! Thanks for catching!!!

**Comment by jaimefrio** [comment]
In it goes, thanks for fixing my mess up!

**Pull request merged**
