### PR TITLE
BUG: Broadcast Arguments in Random Integer Generation

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.

### CODE REVIEW

**Comment by gfyoung** [comment]
Anyone have idea how I might add functionality for the following call?  
```
>>> import numpy as np
>>> np.random.randint(5, [10, None])
```
Currently, it doesn't work because ```numpy``` will throw a type error when trying to convert the ```None``` element.  However, I can't think of anything "fast" / segfault-safe that isn't iterating through both the ```low``` and ```high``` arrays.  However, it would make sense to allow given that we allow ```high``` to be ```None```.

**Comment by njsmith** [comment]
> `np.random.randint(5, [10, None])`

I wouldn't bother... just tell people to write `randint([5, 0], [10, 5])` if that's what they want. (It'll be infinitely less confusing.)

**Comment by gfyoung** [comment]
Okay, that will make things a lot easier.  Will add that to documentation.

**Comment by gfyoung** [comment]
Documentation added, and Travis is happy.  I have no idea how this will gel with #6824 or #6869, but as it stands, unless there are some style/functional issues I'm missing, I think it should be good to go.

**Comment by gfyoung** [comment]
In light of the email discussion, would it be safe to close this PR along with the related issue (#6745)?

**Comment by gfyoung** [comment]
In light of the email discussion, would it be safe to close this PR along with the related issue (#6745)?

**Comment by charris** [comment]
@gfyoung I'll close this as it would need a complete rewrite at this point. I'll leave the issue open just in case someone wants to pursue it. Thanks for your work here.

**Pull request closed without merging**
