### PR TITLE
ENH: Use AVX-512 for np.isnan, np.infinite, np.isinf and np.signbit

### PR DESCRIPTION
**Pull request by r-devulap**
- Vectorization is enabled through run-time detection. 
- Code bloat: On Bionic with gcc-9, it goes up from 24790744  bytes to 24701032 bytes which is about 87Kb increase.
- Benchmarks: 

```
before           after         ratio
[66c756ce]       [bda64382]
 <master>         <test-ufunc-avx>
 2.43±0.01ms         2.30±0ms     0.95  bench_avx.AVX_UFunc.time_ufunc('isnan', 1, 'f')
 4.64±0.06ms      3.83±0.02ms     0.83  bench_avx.AVX_UFunc.time_ufunc('isfinite', 1, 'd')
 3.01±0.02ms      2.32±0.01ms     0.77  bench_avx.AVX_UFunc.time_ufunc('isfinite', 1, 'f')
 3.20±0.02ms      2.35±0.05ms     0.74  bench_avx.AVX_UFunc.time_ufunc('isinf', 1, 'f')
 5.06±0.01ms      3.45±0.01ms     0.68  bench_avx.AVX_UFunc.time_ufunc('isinf', 1, 'd')
 5.14±0.01ms      3.14±0.03ms     0.61  bench_avx.AVX_UFunc.time_ufunc('signbit', 1, 'd')
 8.96±0.02ms      5.39±0.03ms     0.60  bench_avx.AVX_UFunc.time_ufunc('isfinite', 2, 'd')
 8.50±0.04ms      5.02±0.01ms     0.59  bench_avx.AVX_UFunc.time_ufunc('isnan', 2, 'd')
 9.59±0.02ms      5.40±0.02ms     0.56  bench_avx.AVX_UFunc.time_ufunc('isfinite', 4, 'd')
 8.36±0.01ms      4.69±0.03ms     0.56  bench_avx.AVX_UFunc.time_ufunc('signbit', 2, 'd')
 8.53±0.02ms      4.70±0.08ms     0.55  bench_avx.AVX_UFunc.time_ufunc('signbit', 4, 'd')
 7.77±0.01ms      4.18±0.02ms     0.54  bench_avx.AVX_UFunc.time_ufunc('isnan', 2, 'f')
 8.52±0.02ms      4.52±0.04ms     0.53  bench_avx.AVX_UFunc.time_ufunc('isnan', 4, 'f')
 7.43±0.02ms      3.83±0.03ms     0.52  bench_avx.AVX_UFunc.time_ufunc('signbit', 2, 'f')
 9.93±0.04ms      5.05±0.02ms     0.51  bench_avx.AVX_UFunc.time_ufunc('isnan', 4, 'd')
 8.19±0.02ms      4.15±0.02ms     0.51  bench_avx.AVX_UFunc.time_ufunc('signbit', 4, 'f')
 8.92±0.02ms      4.47±0.02ms     0.50  bench_avx.AVX_UFunc.time_ufunc('isfinite', 4, 'f')
 8.48±0.03ms      4.20±0.03ms     0.50  bench_avx.AVX_UFunc.time_ufunc('isfinite', 2, 'f')
    10.2±0ms         5.01±0ms     0.49  bench_avx.AVX_UFunc.time_ufunc('isinf', 2, 'd')
 10.5±0.09ms      5.06±0.03ms     0.48  bench_avx.AVX_UFunc.time_ufunc('isinf', 4, 'd')
 10.0±0.01ms      4.52±0.03ms     0.45  bench_avx.AVX_UFunc.time_ufunc('isinf', 4, 'f')
 5.02±0.01ms      2.14±0.02ms     0.43  bench_avx.AVX_UFunc.time_ufunc('signbit', 1, 'f')
10.00±0.03ms      4.20±0.05ms     0.42  bench_avx.AVX_UFunc.time_ufunc('isinf', 2, 'f')
```

### CODE REVIEW

**Comment by mattip** [comment]
CI is failing on macOS:
```
_multiarray_umath.cpython-36m-darwin.so: Symbol not found: __knot_mask16
```

**Comment by mattip** [comment]
Seems worthwhile to move forward with this.

The cpu-feature detection should go through the newer `NPY_CPU_HAVE(FEATURE_NAME)` detection rather than adding more code to `setup_common.py` and the public headers.

**Comment by r-devulap** [comment]
> The cpu-feature detection should go through the newer `NPY_CPU_HAVE(FEATURE_NAME)` detection rather than adding more code to `setup_common.py` and the public headers.

@mattip This patch does use the new `NPY_CPU_HAVE_AVX512_SKX `feature which only makes available the runtime check. My understanding was that the compile time checks hasn't been merged yet (the universal intrinsic patch has the commit required for the macro setup).

**Comment by r-devulap** [comment]
Fixed the build failure on macOS.

**Comment by seiko2plus** [comment]
the C definition name makes the reviewer get confused, it should be `NPY_HAVE_AVX512_SKX` or `NPY_COMPILER_HAVE_AVX512_SKX`

**Comment by mattip** [comment]
> My understanding was that the compile time checks hasn't been merged yet

Ahh, correct, sorry.

**Comment by mattip** [comment]
Is there any advantage to using avx2 intrinsics for these ufuncs? I think that is still more common than avx512.

**Comment by mattip** [comment]
Squash/merged so future reimplementation of this in universal intrnisics will be a little easier (I hope). Thanks @r-devulap

**Pull request merged**
