### PR TITLE
DOC: Removed some c-api duplication

### PR DESCRIPTION
**Pull request by bmakos**
DOC: Attempting to remove duplicate documentation. #13013

### CODE REVIEW

**Comment by bmakos** [comment]
The weird formatting is not in the reStructuredText, but most probably in the sphinx html theme. I built the PDF's and those look right. I will look into the html themes soon to see if I could fix that.

**Review by eric-wieser — APPROVED** [review]

**Comment by eric-wieser** [comment]
@mattip, where can I find the link to the build docs?

**Comment by mattip** [comment]
"Show all checks" -> circleci -> "Artifacts" tab (visible only to numpy commiters) -> Container0 -> home -> circleci -> repo -> doc -> build -> html. For this commit it is [how-to-extend](https://6364-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/user/c-info.how-to-extend.html) and [c-api.array](https://6364-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/reference/c-api.array.html)

**Comment by eric-wieser** [comment]
That's it, I hadn't logged in

**Comment by mattip** [comment]
Thanks @bmakos

**Pull request merged**
