### PR TITLE
DEP: Finalize ragged array creation deprecation

### PR DESCRIPTION
**Pull request by seberg**
This finalizes all DeprcationWarnings related to the creation of object
arrays from nested lists enforcing that users use `dtype=object` if this
is intentional.

### CODE REVIEW

**Comment by mattip** [comment]
Could you also change the status of NEP 34 to `Final`, or should that be in a different PR?

**Comment by mattip** [comment]
https://numpy.org/neps/nep-0034-infer-dtype-is-object.html

**Comment by mattip** [comment]
Travis CI is still running after 8 hours, but everything else looks good.

Thanks @seberg

**Comment by dkz-phys** [comment]
What if creating either ragged or regular ndarray is the desired behavior? Is there an efficient numpy function that can check whether the input is ragged or not?

**Comment by dkz-phys** [comment]
Also maybe spares asanyarray, as the name suggests "any" array should work? The current doc says "Input data, in any form that can be converted to an array"

**Pull request merged**
