### PR TITLE
DOC: add CITATION.cff file for GitHub support

### PR DESCRIPTION
**Pull request by mwtoews**
This PR is very similar to #19733 (ping @tupui) but goes much further to implement a [CITATION.cff](https://citation-file-format.github.io/) file. This machine-readable (YAML) document contains both a software citation and a "preferred-citation" based on the _Nature_ publication. By default, GitHub's "Cite this repository" tool will offer APA and BibTeX versions of the preferred citation, which is why CITATION.bib is removed.

The author listing for the software can (and should) change with time. I've populated it based on the [contributors listing](https://github.com/numpy/numpy/graphs/contributors), more-or-less ordered by commits. I've only included folks with a "significant number" of commits, e.g. 50ish or more. I've done my best to gather the correct information, apologies for any errors or omissions. The last author is simply "others" as a catch-all for the other 1400 contributors.
 
This file should also be updated for each release, updating "version" and "date-released" fields. I'm not 100% sure how this could be done, but it's possible to automate this with one of the existing tools/scripts (which one?) with the help of [PyYAML](https://pypi.org/project/PyYAML/). I can add this functionality to this PR with some guidance.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Note that the generated bibtex is
```latex
@article{Harris_Array_programming_with_2020,
author = {Harris, Charles R. and Millman, K. Jarrod and van der Walt, Stéfan J. and Gommers, Ralf and Virtanen, Pauli and Cournapeau, David and Wieser, Eric and Taylor, Julian and Berg, Sebastian and Smith, Nathaniel J. and Kern, Robert and Picus, Matti and Hoyer, Stephan and van Kerkwijk, Marten H. and Brett, Matthew and Haldane, Allan and del Río, Jaime Fernández and Wiebe, Mark and Peterson, Pearu and Gérard-Marchant, Pierre and Sheppard, Kevin and Reddy, Tyler and Weckesser, Warren and Abbasi, Hameer and Gohlke, Christoph and Oliphant, Travis E.},
doi = {10.1038/s41586-020-2649-2},
journal = {Nature},
month = {9},
pages = {357--362},
title = {{Array programming with NumPy}},
volume = {585},
year = {2020}
}
```
which is IMO worse than the hand-crafted
```latex
@ARTICLE{2020NumPy-Array,
  author  = {Harris, Charles R. and Millman, K. Jarrod and
            van der Walt, Stéfan J and Gommers, Ralf and
            Virtanen, Pauli and Cournapeau, David and
            Wieser, Eric and Taylor, Julian and Berg, Sebastian and
            Smith, Nathaniel J. and Kern, Robert and Picus, Matti and
            Hoyer, Stephan and van Kerkwijk, Marten H. and
            Brett, Matthew and Haldane, Allan and
            Fernández del Río, Jaime and Wiebe, Mark and
            Peterson, Pearu and Gérard-Marchant, Pierre and
            Sheppard, Kevin and Reddy, Tyler and Weckesser, Warren and
            Abbasi, Hameer and Gohlke, Christoph and
            Oliphant, Travis E.},
  title   = {Array programming with {NumPy}},
  journal = {Nature},
  year    = {2020},
  volume  = {585},
  pages   = {357–362},
  doi     = {10.1038/s41586-020-2649-2}
}
```

**Comment by mwtoews** [comment]
These are minor differences, and I'm guessing most BibTeX users might reformat either inputs to their needs anyways (e.g. [accents](https://tex.stackexchange.com/q/134116/), [dashes](https://tex.stackexchange.com/q/58668/) or [double parentheses](https://tex.stackexchange.com/q/327386/)). It's not a problem to keep both, so the `.bib` file could stay.

**Comment by tupui** [comment]
Not my call here. IMHO this will bring very little benefit vs the extra maintenance.

When you have a commit, your name is in the source and GitHub keeps a list of that already with a UI (by time even). You can cite a commit hash too, even more precise.

But the main issue to me is that this still does not acknowledge non code contributions. Project management, outreach activities, discussions, etc. Hence having a more "precise" list for code contributions could reinforce the illusion of completeness and shadow even more all the people doing other type of work.

**Comment by melissawm** [comment]
I think it is reasonable to add an easier way to cite the NumPy paper. I do however agree that this is not representative of the entire contributor base for the project today. In any case, the paper is the official way of citing NumPy. I am not sure what the right approach is here. Thanks for the PR though, @mwtoews !

**Comment by eric-wieser** [comment]
@mwtoews, do you have a motivation in mind for the cff file beyond different behavior on github? Are there other tools that are starting to become popular that benefit from this format over the `.bib` file?

**Comment by mwtoews** [comment]
Thanks all for the feedback. I'm now questioning if this would be helpful or introduce a hot mess for someone to maintain.

- CITATION.cff is a relatively new format (since 2017), and it's primary aim is to harmonize various CITATION.[bib|md|rst] formats into one machine readable form, which is a superset that can be used to derive different formats. There are [many tools](https://github.com/citation-file-format/citation-file-format#tools-to-work-with-citationcff-files-wrench) to work with the format, and the schema has had a few updates. Several third-parties, such as GitHub, directly use the format in some way.
- For the preferred citation in _Nature_, I think either existing .bib or proposed .cff format are fine. Not everyone uses BibTeX, but there is also less familiarity with .cff from those needing this file.

It is the _software_ citation aspect that is more interesting and difficult.

- CITATION.cff does a better job of representing the software authors by providing their name, alias (based on GitHub username), and [ORCiD](https://orcid.org/). Other non-software contributors (i.e. work not tracked by commits) can be included manually as "authors", although presently the schema does not allow the contribution roles to be captured (this is under active discussion in their issues).
- Software authors for each release would be difficult to manage going forward. How should the authors be ordered? What criteria would an author need to meet to be included? Would some previous authors that don't have visible code be removed as an author in future releases?

There is potentially some data science answers to the last point. Projects with less than 100 contributors may have easier answers to these questions, but NumPy presently has 1,440 contributors according to GitHub (or 1,589 according to `git shortlog -nes | wc`).

**Comment by tupui** [comment]
I think if there is something to be done, it's better to manually curate such list. Even for large projects, 1000 or even 2000 entries is not non manageable by hand as only the first round would take time. You will have a harder time trying to over engineer a solution based on some kind of arbitrary metrics.

Instead I would just take a few maintainers' brain for a bit and go through names. In one (virtual) pizza party, this is done and you possibly have fun discussions about the history of the project as you go 😉 And this way, no complains about a metric/algo, the decision was collegial.

And then you decide on how you keep the list up to date. Some projects like scikit-learn have extra things like filling out release notes in a PR. You could add a step to think about authorship.

**Comment by seberg** [comment]
Its a complicated problem unfortunately :/...  but it sounds a bit like the resolution on this PR itself is to close it?

**Comment by mwtoews** [comment]
Thanks again for the feedback. I'll close this PR, since maintaining a software CITATION.cff would require much more buy-in from one or more members of the NumPy core team.

**Pull request closed without merging**
