### PR TITLE
TST. API: test using distributions.h via cffi

### PR DESCRIPTION
**Pull request by mattip**
xref #14951 

Add an example of calling functions from `distributions.h` from cffi

### CODE REVIEW

**Comment by mattip** [comment]
I also made sure the numba test passes locally on windows. Numba is a bit heavy and moving too fast to be a permanent test dependency. I don't think they have released a Python3.8 version yet.

**Comment by mattip** [comment]
The test failure seems unrelated - matmul is seeing an invalid value on win32. I think this is a different manifestation of the occasional heisenbug.

**Comment by bashtage** [comment]
A very heavy handed approach to make these available for Cython through _generator.<extension> binary would be to use wrap the functions and use the `api` flag for Cython.  Probably a non-starter, but I foudn this when looking for a solution.

**Comment by mattip** [comment]
The solutions I see in the [cython documentation](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#using-cython-declarations-from-c) do seem rather heavy-handed. We expose the functions from python, but as you say that requires the Python->C-API->call the function->C-API->Python route. Maybe we should delay extending the API for now?

**Comment by bashtage** [comment]
It looks like the only "easy" and universal method is to compile the functions into distributions.lib or libdistributions.so like npymath.lib.  This would allow downstream Cython to link to these functions, and if they want to use Numba, a downstream could create a dll from the subset of the lib they need. 

Of course, not really easy.

**Comment by bashtage** [comment]
Or ship numpy/random/scr/distributions/distributions.c

**Comment by mattip** [comment]
Let's continue the discussion about extending for cython on gh-14778

**Comment by mattip** [comment]
Tests pass, documentation added [here]9https://10268-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/reference/random/extending.html#cffi) and [here](https://10268-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/reference/random/examples/cffi.html). Is there anything more needed to demonstrate this example?

**Comment by bashtage** [comment]
I think this proves teh case for cffi.

**Comment by charris** [comment]
Thanks Matti.

**Pull request merged**
