### PR TITLE
BUG: Fix build on ppc64 when the baseline set to Power9 or higher

### LINKED ISSUE #24789: BLD: PPC issues with new CPU dispatcher
### Describe the issue:

Collecting here multiple issues I observed that prevent building on PPC with the new CPU dispatcher.

Issue 1:

Building on a POWER9 host which supports VSX3, VSX4 is incorrectly detected as supported.

```
Host machine cpu family: ppc64
Host machine cpu: ppc64le
Program python found: YES (/usr/bin/python3.11)
Found pkg-config: /usr/bin/pkg-config (2.0.3)
Run-time dependency python found: YES 3.11
Has header "Python.h" with dependency python-3.11: YES
Compiler for C supports arguments -fno-strict-aliasing: YES
Message: Appending option "detect" to "cpu-baseline" due to detecting global architecture c_arg "-mcpu=native"
Test features "VSX VSX2 VSX3 VSX4" : Supported
Message: During parsing cpu-dispatch: The following CPU features were ignored due to platform incompatibility or lack of support:
"XOP FMA4"
Test features "VSX VSX2 VSX3 VSX4" : Supported
Configuring npy_cpu_dispatch_config.h using configuration
Message:
CPU Optimization Options
  baseline:
    Requested : min+detect
    Enabled   : VSX VSX2 VSX3 VSX4
  dispatch:
    Requested : max -xop -fma4
    Enabled   :
```

Issue 2:

Even in VSX3-conditional code, build fails with an incorrect variable name in ASM code.

```
[9/297] powerpc64le-unknown-linux-gnu-g++ -Inumpy/core/libnpymath.a.p -Inumpy/core -I../numpy-1.26.0/numpy/core -Inumpy/core/include -I../numpy-1.26.0/numpy/core/include -I../numpy-1.26.0/nump
y/core/src/npymath -I../numpy-1.26.0/numpy/core/src/common -I/usr/include/python3.11 -I/var/tmp/portage/dev-python/numpy-1.26.0/work/numpy-1.26.0-python3_11/meson_cpu -fdiagnostics-color=alway
s -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O3 -mcpu=power10 -DNPY_HAVE_VSX2 -DNPY_HAVE_VSX -DNPY_HAVE_VSX_ASM -DNPY_HAVE_VSX3 -DNPY_HAVE_VSX4 -DNPY_HAVE_VSX4_MMA -O3 -mcpu=native
 -mtune=native -pipe -fno-strict-aliasing -DNDEBUG -fPIC -MD -MQ numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o -MF numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o.d -o numpy/core
/libnpymath.a.p/src_npymath_halffloat.cpp.o -c ../numpy-1.26.0/numpy/core/src/npymath/halffloat.cpp
FAILED: numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o 
powerpc64le-unknown-linux-gnu-g++ -Inumpy/core/libnpymath.a.p -Inumpy/core -I../numpy-1.26.0/numpy/core -Inumpy/core/include -I../numpy-1.26.0/numpy/core/include -I../numpy-1.26.0/numpy/core/s
rc/npymath -I../numpy-1.26.0/numpy/core/src/common -I/usr/include/python3.11 -I/var/tmp/portage/dev-python/numpy-1.26.0/work/numpy-1.26.0-python3_11/meson_cpu -fdiagnostics-color=always -D_FIL
E_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O3 -mcpu=power10 -DNPY_HAVE_VSX2 -DNPY_HAVE_VSX -DNPY_HAVE_VSX_ASM -DNPY_HAVE_VSX3 -DNPY_HAVE_VSX4 -DNPY_HAVE_VSX4_MMA -O3 -mcpu=native -mtune=
native -pipe -fno-strict-aliasing -DNDEBUG -fPIC -MD -MQ numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o -MF numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o.d -o numpy/core/libnpym
ath.a.p/src_npymath_halffloat.cpp.o -c ../numpy-1.26.0/numpy/core/src/npymath/halffloat.cpp
In file included from ../numpy-1.26.0/numpy/core/src/common/common.hpp:10,
                 from ../numpy-1.26.0/numpy/core/src/npymath/halffloat.cpp:12:
../numpy-1.26.0/numpy/core/src/common/half.hpp: In member function ‘np::Half::operator double() const’:
../numpy-1.26.0/numpy/core/src/common/half.hpp:116:38: error: ‘vf32’ was not declared in this scope
  116 |                              : "=wa"(vf32)
      |                                      ^~~~
ninja: build stopped: subcommand failed.
```

Issue 3:

After applying the following patch to fix:

```
diff --git a/numpy/core/src/common/half.hpp b/numpy/core/src/common/half.hpp
index 054c99859..b85b592bb 100644
--- a/numpy/core/src/common/half.hpp
+++ b/numpy/core/src/common/half.hpp
@@ -113,7 +113,7 @@ class Half final {
     #elif defined(NPY_HAVE_VSX3) && defined(NPY_HAVE_VSX_ASM)
         __vector float vf64;
         __asm__ __volatile__("xvcvhpdp %x0,%x1"
-                             : "=wa"(vf32)
+                             : "=wa"(vf64)
                              : "wa"(vec_splats(bits_)));
         return vec_extract(vf64, 0);
     #else
```

it would seem that the assembly uses invalid instructions.

```
[9/297] powerpc64le-unknown-linux-gnu-g++ -Inumpy/core/libnpymath.a.p -Inumpy/core -I../numpy-1.26.0/numpy/core -Inumpy/core/include -I../numpy-1.26.0/numpy/core/include -I../numpy-1.26.0/nump
y/core/src/npymath -I../numpy-1.26.0/numpy/core/src/common -I/usr/include/python3.11 -I/var/tmp/portage/dev-python/numpy-1.26.0/work/numpy-1.26.0-python3_11/meson_cpu -fdiagnostics-color=alway
s -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O3 -mcpu=power10 -DNPY_HAVE_VSX2 -DNPY_HAVE_VSX -DNPY_HAVE_VSX_ASM -DNPY_HAVE_VSX3 -DNPY_HAVE_VSX4 -DNPY_HAVE_VSX4_MMA -O3 -mcpu=native
 -mtune=native -pipe -fno-strict-aliasing -DNDEBUG -fPIC -MD -MQ numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o -MF numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o.d -o numpy/core
/libnpymath.a.p/src_npymath_halffloat.cpp.o -c ../numpy-1.26.0/numpy/core/src/npymath/halffloat.cpp
FAILED: numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o 
powerpc64le-unknown-linux-gnu-g++ -Inumpy/core/libnpymath.a.p -Inumpy/core -I../numpy-1.26.0/numpy/core -Inumpy/core/include -I../numpy-1.26.0/numpy/core/include -I../numpy-1.26.0/numpy/core/s
rc/npymath -I../numpy-1.26.0/numpy/core/src/common -I/usr/include/python3.11 -I/var/tmp/portage/dev-python/numpy-1.26.0/work/numpy-1.26.0-python3_11/meson_cpu -fdiagnostics-color=always -D_FIL
E_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O3 -mcpu=power10 -DNPY_HAVE_VSX2 -DNPY_HAVE_VSX -DNPY_HAVE_VSX_ASM -DNPY_HAVE_VSX3 -DNPY_HAVE_VSX4 -DNPY_HAVE_VSX4_MMA -O3 -mcpu=native -mtune=
native -pipe -fno-strict-aliasing -DNDEBUG -fPIC -MD -MQ numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o -MF numpy/core/libnpymath.a.p/src_npymath_halffloat.cpp.o.d -o numpy/core/libnpym
ath.a.p/src_npymath_halffloat.cpp.o -c ../numpy-1.26.0/numpy/core/src/npymath/halffloat.cpp
{standard input}: Assembler messages:
{standard input}:38: Error: unrecognized opcode: `xvcvhpdp'
{standard input}:83: Error: unrecognized opcode: `xvcvdphp'
{standard input}:846: Error: unrecognized opcode: `xvcvdphp'
{standard input}:892: Error: unrecognized opcode: `xvcvhpdp'
ninja: build stopped: subcommand failed.
```

This is using the following binutils:

```
$ ld --version
GNU ld (Gentoo 2.41 p2) 2.41.0
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

All three of these issues apply on both big and little endian, as well as regardless of using `-mcpu=native` or `-mcpu=power9`.  As always, I provide [free shell access to the hardware I encountered these issues on](https://static.matoro.tk/isa-sandbox-faq.html) if desired.

@seiko2plus @rgommers 

### Reproduce the code example:

```python
N/A
```

### Error message:

_No response_

### Runtime information:

N/A

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by seiko2plus**
closes #24789

### CODE REVIEW

**Comment by rgommers** [comment]
@seiko2plus is this still marked as Draft on purpose?

**Comment by seiko2plus** [comment]
> is this still marked as Draft on purpose?

I had to test it locally against an assembler that doesn't support VSX3 scalar double-precision conversion. It's ready for review now.

**Comment by charris** [comment]
Thanks Sayed.

**Comment by Flamefire** [comment]
FWIW: https://github.com/numpy/numpy/commit/7a84442b1caa4904a9b8e58bd6b93045b4ad350f fixes a test failure in `test_half_conversions` caused by a difference of 512 in indices 31745-32255 & 64513-65023 (all NaNs) of the test for float64

**Pull request merged**
