### PR TITLE
TST: Check use of out parameter in clip() 

### PR DESCRIPTION
**Pull request by aishwarya34**

### CODE REVIEW

**Comment by mattip** [comment]
@aishwarya34 is this part of some other PR or issue? Do you doubt the `out` parameter works as advertised?

**Comment by aishwarya34** [comment]
This is not part or any other PR or issue. The out parameter is working as expected. Without the out parameter, the 'refer' variable is not being updated and so are arr1 and arr2 variables not being updated with the clipped value. But with out parameter, the 'refer' variable is getting updated as it is passed as value of out parameter and so are arr1 and arr2 variables being updated with the clipped value.

**Comment by mattip** [comment]
@aishwarya34 if everything is working well, why do we need this extra test code? I would prefer not to add it.

**Comment by aishwarya34** [comment]
ohh so you are saying a check is not needed to future proof the code. okay then i will close the PR

**Comment by eric-wieser** [comment]
Yeah, I think I lean away from adding tests for something simple like this, especially since this doesn't improve coverage. If the clip ufunc thing ever wraps up, then this will be testing a very well-tested code-path anyway. If you're looking for places to add tests to numpy @aishwarya34, you could work backwards from the code coverage at https://codecov.io/gh/numpy/numpy/tree/master/numpy

**Pull request closed without merging**
