### PR TITLE
adding an INPLACE_ARRAY typemap without dimensions

### PR DESCRIPTION
**Pull request by kasbah**
See [this discussion](http://mail.scipy.org/pipermail/numpy-discussion/2013-November/068330.html) (and what I am doing with it [here](http://dev.drobilla.net/attachment/ticket/940/test_numpy.py)) as to why I found this useful. Let me know what you think. I could do a similar typemap for the other ARRAY1 types and update the docs if you think others could find this useful too. Maybe they should be called *_ARRAY rather than *_ARRAY1 as it's just a pointer essentially and could work for any dimension arrays.

### CODE REVIEW

**Comment by seberg** [comment]
I am not quite sure what to make of this without looking at this more closely. Is there anyone who actually uses numpy swig to have a comment on this or can easily review? If nobody has, I will have a look at, but considering the age may also close it (we can always reopen/create a new one).

**Comment by kasbah** [comment]
Well, I am still around to answer any questions but I can't really remember what I was doing. Links are broken now but I found an [archive of the first message for context](https://web.archive.org/web/*/http://dev.drobilla.net/attachment/ticket/940/test_numpy.py)

> Hey,
> 
> I am trying to improve the Lilv <http://drobilla.net/software/lilv/> Python
> bindings to include numpy.i to allow for creation and verification of audio
> test buffers using NumPy.
> 
> I am just trying to get *something* working at the moment so I am tring to
> wrap a test function.
> 
> static inline void
> lilv_test(float* data_location){}
> 
> and I have in lilv.i:
> 
> %apply (float* INPLACE_ARRAY1) {(float* data_location)};
> 
> This doesn’t produce any warnings or anything but when I try and use it
> from Python I get:
> 
> TypeError: in method 'lilv_test', argument 1 of type 'float *'
> 
> What does work is if I have:
> 
> lilv_test(float* data_location, int n){}
> 
> and
> 
> %apply (float* INPLACE_ARRAY1, int DIM1) {(float* data_location, int n)};
> 
> but this doesn’t fit very well with the functions I eventually want to
> wrap, as they don’t have a dimension argument.
> 
> Is it not possible to use INPLACE_ARRAY1 without a dimension?
> 
> Thanks for any help,
> 
> Kaspar

**Comment by mikofski** [comment]
@mattip and @anirudh2290 it sounds like this is a good candidate for a STALE tag, or maybe it can be CLOSED? 

#### Quick Facts
| Original Post Date | Original Poster | Last Post Date | Merge Conflicts? | Reviewer | Docs? | Tests? |
|---------------------|------------------|-----------------|--------------------|-----------|--------|--------|
| 2013-12-01 | Kaspar Emanuel (@kasbah) | 2019-04-26 | yes | Sebastian Berg (@seberg ) | no | no |

#### Summary
* add one new type map to [Numpy SWIG interface](https://numpy.org/doc/stable/reference/swig.html) [`numpy.i`](../blob/ba5205c1b8a7bebdf37535c701ffcd8bd79362bb/tools/swig/numpy.i) for [`INPLACE_ARRAY1`](../blob/ba5205c1b8a7bebdf37535c701ffcd8bd79362bb/tools/swig/numpy.i#L1426) but without dimension argument so that it can be used to test [lilv](http://drobilla.net/software/lilv), a C library with Python bindings for making [LV2 audio plugins](https://lv2plug.in/). See [drobilla.net ticket #940](http://dev.drobilla.net/ticket/940) form 6 years ago which was marked "fixed" and closed, it mentions `numpy.i` and this PR, but it's not clear if it was vendorized
```patch
 *   21. (DATA_TYPE INPLACE_ARRAY1[ANY])
 *   22. (DATA_TYPE* INPLACE_ARRAY1, DIM_TYPE DIM1)
 *   23. (DIM_TYPE DIM1, DATA_TYPE* INPLACE_ARRAY1)
+*   24. (DIM_TYPE DIM1, DATA_TYPE* INPLACE_ARRAY1)
```
* Note: `numpy.i` new location is here: [`tools/swig/numpy.i`](../blob/ba5205c1b8a7bebdf37535c701ffcd8bd79362bb/tools/swig/numpy.i)
* here's an updated link to [the original numpy-discussion from November-2013](https://mail.python.org/pipermail/numpy-discussion/2013-November/068330.html), original link is broken
* the related project drobilla seems current, last commits were in 2019, [it's git repo is here](http://git.drobilla.net/cgit.cgi/drobillad.git/commit/) and [on gitlab](https://gitlab.com/drobilla/drobillad/-/commits/master/)
* needs update to [Numpy SWIG `README`](../blob/464f79eb1d05bf938d16b49da1c39a4e02506fa3/tools/swig/README) and the [swig-interface docs](../blob/464f79eb1d05bf938d16b49da1c39a4e02506fa3/doc/source/reference/swig.interface-file.rst) for the new type.
* needs a tests in [`Array1.i`, `Array1.cxx`, & `Array1.h`](../tree/464f79eb1d05bf938d16b49da1c39a4e02506fa3/tools/swig/test)

#### recommendation:
* IMO this can be marked STALE, there's been no activity on it since it was posted, [there's only one commit](../pull/4087/commits) in December-2013.
* Maybe as @seberg  seems to suggest, it could be CLOSED? I don't know what the criteria for closing an issue would be. I think if there was renewed issue, it could always be reopened or a new issue created. It also seems that if it was a pressing issue for the downstream software, then there would have been pressure, but in 6 years, no comments there or here?

**Comment by Qiyu8** [comment]
I will close this PR for management purpose, Feel free to reopen or create a new one.

**Pull request closed without merging**
