### PR TITLE
[WIP] Remove skip in .rst doctests

### LINKED ISSUE #15846: DOC: remove SKIP in the rst doctests
There are plenty of `+SKIP` doctests directives in the documentation. Ideally, we should not need them, see  #14970 for background information.

Procedure: edit the rst files to make the tests more robust or correct. Then, run

```
python tools/refguide_check.py --rst
```

to check the result.

This issue should be considered after #15845

### PR DESCRIPTION
**Pull request by leeyspaul**
This is a draft PR in progress. 

Closes #15846

### CODE REVIEW

**Comment by leeyspaul** [comment]
Hi @pdebuyl could you provide an example of a `+SKIP` directive to be removed? 

I cannot find any except in `development_environment.rst` which skips the `.test()` block. 

Thank you! :)

**Comment by pdebuyl** [comment]
Some files are completely excluded from the tests. Look for "RST_SKIPLIST" in refguide_check.py.

"arrays.nditer.cython.rst" for instance necessitates to build cython code.

**Comment by mattip** [comment]
Should we close this? @leeyspaul will you be continuing the work soon?

**Comment by leeyspaul** [comment]
Hey @mattip ! I just hopped back on this yesterday hoping to complete within the week although I do think I'm missing a lot of prior knowledge to understand what the ask is. 

Is there any documentation or anything I can look at? Looking at the PR here: https://github.com/numpy/numpy/issues/14970 is still a bit confusing for me.

**Comment by mattip** [comment]
Doctests in general? Here https://docs.python.org/3/library/doctest.html
The idea is that over the years, our documentation has grown many `+SKIP` directives on doctests that are run as part of the test suite. Someone should go over them and see if they are still needed, or if we can remove them to make sure the examples are correct.

**Comment by leeyspaul** [comment]
Ok, thank you for that. In terms of the `+SKIP` directives and finding them would I just do a find all of `+SKIP` and also take a look at the `SKIPLIST` in `refguide_check.py`?

Thank you for the information!

**Comment by pdebuyl** [comment]
#15846 which you mentions concerns the doctests in the rst files of the documentation. I removed most skips but as I wrote above, some files are skipped by being in RST_SKIPLIST. This is the first type of skipping to address. Some skips are unavoidable, such as for np.empty for which the result is random.

**Comment by charris** [comment]
This seems to have stalled, so closing. The one fix here still needs to be made, I'll make a PR. Thanks @leeyspaul .

**Pull request closed without merging**
