### PR TITLE
TST: ensure sum of weights is positive in np.average and ma.average

### LINKED ISSUE #9825: Strange behaviour of np.average with negative weights
The current implementation of `np.average` accepts weights and the only check performed is that the sum of weights is not zero.
This is due to the fact the the result is normalised by the sum of weights.

This however leads to the following strange behaviour when dealing with negative weights:

```python
In [1]: import numpy as np

In [2]: np.average([3,5], weights=[1, -0.99])
Out[2]: -194.99999999999986

In [3]: np.average([3,5], weights=[1, -1.01])
Out[3]: 204.9999999999998

In [4]: np.average([3,5], weights=[0, -1])
Out[4]: 5.0

In [5]: np.average([3,5], weights=[0, +1])
Out[5]: 5.0
```

wouldn't be better to normalise by the **absolute sum** or the **sum of absolute values**? In this way we would get:

```python
# Case absolute sum
In [4]: average([3,5], weights=[0, -1])
Out[4]: -5.0

In [5]: average([3,5], weights=[0, +1])
Out[5]: 5.0

In [6]: average([3,5], weights=[1, -0.99])
Out[6]: -194.99999999999986

In [7]: average([3,5], weights=[1, -1.01])
Out[7]: -204.9999999999998
```
or 
```python
# Case sum of absolute values
In [4]: average([3,5], weights=[0, -1])
Out[4]: -5.0

In [5]: average([3,5], weights=[0, +1])
Out[5]: 5.0

In [6]: average([3,5], weights=[1, -0.99])
Out[6]: -0.97989949748743732

In [7]: average([3,5], weights=[1, -1.01])
Out[7]: -1.0199004975124377
```
Finally, is there a realistic use case where negative weights are needed?

### PR DESCRIPTION
**Pull request by apbard**
Fixes #9825 by raising an error if weights are negative.

### CODE REVIEW

**Comment by mhvk** [comment]
This looks good code-wise, but I'm slightly wary that we're making the code quite a bit slower for what seems an unlikely case to happen in practice. It seems quite possible that `np.average` is used in applications that deal with very large arrays for which an ~20% overhead for a needless check is painful (estimated, not tested). [I don't use `np.average` myself like that, but as another example that involved weights - though not one where negative ones are an issue immediately - `np.bincount` is in the critical path of code I use.] I also don't want to presume nobody ever *uses* negative weights (or, perhaps weirder, but surely possible, complex weights), making proper use of the current definition.

**Comment by eric-wieser** [comment]
I actually think that negative weights are a useful thing to allow, so am -1 on this patch.

**Comment by mhvk** [comment]
Might it be better to just document the current behavour better? In the end, the user can then check themselves whether weights are negative, if this is important.

**Comment by charris** [comment]
I tend to the "document it" side, although I confess not having a good idea where negative weights would be useful.

**Comment by charris** [comment]
Unless there is disagreement, I'm going to close this and ask @apbard to improve the documentation.

**Comment by apbard** [comment]
I can change the title and the commit content...no need to close this and reopen another one i think.
Should I add just doc or also implement the other proposal (`absolute sum of weights` )? It has no impact on performance and should solve some of the inconsistencies of negative weights.

**Comment by eric-wieser** [comment]
I'd prefer not to silently change behaviour simply due to a difficult-to-justify sense of inconsistency from people who aren't using the feature anyway.

An argument for allowing some negative weights is numerical error causing weights close to zero to be negative, which should still produce the right answer if we don't force it to error.

I can't think of an argument for allowing all-negative weights / weights that sum to a negative result.

**Comment by impredicative** [comment]
I estimate there is a fair amount of buggy code out there with weights that can silently be negative, causing silent bugs that are never caught.

What will the updated documentation even say? A negative weight does what exactly?

**Comment by mhvk** [comment]
The documentation can simply state mathematically what is done, and note that weights can be negative. Generally, one has to weigh the possible finding of bugs against people rolling their own versions because the ones that come with numpy are too slow because of the tests (and in this case the test is not all that cheap).

**Comment by apbard** [comment]
Sorry for the huge delay.
I have added the formula in the documentation and changed the check to raise an error only if the sum of weights is non-positive. Also there was a missing check in ma.average.

**Comment by impredicative** [comment]
@apbard Why the sum of weights and not any individual weight?

**Comment by apbard** [comment]
@impredicative, just for the performance, rounding errors and strange usage concerns raised by @mhvk and @eric-wieser.

**Comment by impredicative** [comment]
@apbard In other words, the weight vector [1, 2, 3, -5] (sum=1) is fine, but [1, 2, 3, -6] (sum=0) and [1, 2, 3, -7] (sum=-1)are not. I can foresee this causing exceptions that can be difficult to come to terms with.

**Comment by gwerbin** [comment]
This is a case for having 2 API layers; one for fast, unchecked operations and another for safe, checked, but potentially slower operations.

**Comment by apbard** [comment]
@impredicative sum=0 was not allowed even before.
an alternative I have proposed was to normalise by the absolute sum...but there was not agreement on that.

**Comment by apbard** [comment]
@gwerbin you mean by adding e.g., a keyword `check_weights=False`?

**Comment by impredicative** [comment]
@apbard One can perhaps make a case for these options for a flag: `check_weights = 'sum_nonzero' | 'sum_positive' | 'all_nonnegative' | 'all_positive'`. To avoid breaking preexisting code, the current default would be `'sum_nonzero'`.

**Comment by mhvk** [comment]
@impredicative - most of python is not written with the idea that you have to hand-hold users, since you cannot really foresee what wrong input they might give anyway, or what use a function may have. Plus, code becomes much less easy to understand if there are loads of checks everywhere. Much more important is to be very clear about what a function actually does, and have tests that ensure this is what happens (where the tests should include "strange" inputs).

**Comment by impredicative** [comment]
@mhvk I pretty much agree, and so I wouldn't want users to be blocked from having weights that sum to negative. I prefer that the documentation clearly note the function's assumptions that weights can be negative and even sum to negative. It's strange to document such checks that aren't done, but it will bring attention to the users that need to do it externally.

**Comment by WarrenWeckesser** [comment]
I think the simplest resolution here is to not add additional checks or keywords.  Instead, we can more clearly document the current behavior (as suggested above).  Specifically, in the 1-d case, the calculation is simply `(a @ weights)/sum(weights)`, with no checks for negative weights, and with an exception raised if `sum(weights)` is 0.

If other NumPy devs agree on this, we can close this pull request, and address improving the docstring in a separate PR.

**Comment by mattip** [comment]
I would agree, but the order should be reversed - first open a PR/issue about documentation, then close these.

**Comment by mattip** [comment]
#14365 is merged. Closing. Please reopen if I misunderstood the intention, and specify the next action item for this PR.

**Pull request closed without merging**
