### PR TITLE
DOC: clarify wording in tutorial

### PR DESCRIPTION
**Pull request by njsmith**
In gh-9664, a user got confused by this wording, because they thought
it was talking about the length of a vector as a distance in cartesian
space versus the length of a vector as the number of elements it
contains.

### CODE REVIEW

**Comment by charris** [comment]
I thought we stopped using "rank" for dimensionality?

**Comment by charris** [comment]
Maybe "size" instead of "length"?

**Comment by peter-mason-dpm** [comment]
I am sure you are aware you are speaking to a world audience with differing levels of knowledge, background and educational proximity (age). For my part an electronics engineer with experience dating from the time when TTL logic first arrived from a small startup company, Texas. I am encouraged if this issue has stimulated discussion and would also welcome a wider awareness although I am generally philosophically hostile to semantics of language but that is probably because I am finding that learning French is difficult.
Size rather than length seems better to me but may find a conflict in the fashion lobby (perhaps but not necessarily relevant). An acquaintance suggested that bandwidth be reserved for the frequency spectrum and not data, I found a flux of one photon in Wikipedia although it defines flux as rate per area and "gay" cannot now be use in the traditional sense.
As stated I do not like language semantics.
Peter

**Comment by seberg** [comment]
Well, size is nice, but we also use it for the total number of elements so that is a small minus point. As to rank, I would agree that it would be better to do it the other way around, dimension outside the bracket, and mention rank inside the bracket, since dimension is the nomenclature numpy normally uses.

**Comment by njsmith** [comment]
The getting started guide doesn't need to comprehensively mention every piece of common and rare terminology... I just added a commit dropping the word "rank" entirely and it's much smoother.

**Comment by charris** [comment]
Thanks Nathaniel.

**Pull request merged**
