### PR TITLE
BUG: weighted nanpercentile, nanquantile and  multi-dim q

### LINKED ISSUE #26455: Unexpected behavior of `nanpercentile` with weighted missing values
### Issue with current documentation:

#24254 by @lorentzenchr introduced the possibility to pass non-negative weights to `np.nanpercentile`.

However, the influence of the weights of nan values is not necessarily intuitive to grasp. In particular, changing the weights of the nan values impacts the results:

```python
>>> import numpy as np
>>> np.nanpercentile([1, np.nan, 2, 3], 50, method="inverted_cdf")
np.float64(2.0)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 1.0, 1.0, 1.0], method="inverted_cdf")
array(2.)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 0., 1.0, 1.0], method="inverted_cdf")
array(1.)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 2., 1.0, 1.0], method="inverted_cdf")
array(2.)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 3., 1.0, 1.0], method="inverted_cdf")
array(3.)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 1e200, 1.0, 1.0], method="inverted_cdf")
array(3.)
```

This seems to contradict the first line of the docstring of that function:

> Compute the qth percentile of the data along the specified axis, while ignoring nan values.

However I am not sure if it's a bug or a feature. I assume that giving non-zero weights to missing values might have some mathematical meaning? If this is intended, I think the docstring should be updated to explain the expected behavior in this case.

However I do not really see why weighing more the `np.nan` values would shift the median to the right. In the above snippet, `np.nan` behaves like the largest non-missing values in the sample which seems quite arbitrary to me, hence the feeling that this might be a bug instead of an intended behavior. Maybe the weights should then be renormalized after trimming the weights of missing values to fix the problem.

### Idea or request for content:

Also note that the return type of this function is influenced by whether we pass the `weights` kwarg (the return value is 0d `ndarray`) or not (the return value is an instance of `np.float64`).

I think this is a minor bug on its own. I can open a dedicated issue if needed.

### PR DESCRIPTION
**Pull request by lorentzenchr**
Fixes #26455.

Hint: The solution is no beauty, but it does seem to do it's job. The whole `nanpercentile` seems convoluted given that it could rely more on `percentile`.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Linter failures are real. I unfortunately don't have time to understand the code to give you a proper code review right now.

**Comment by lorentzenchr** [comment]
@seberg might be interested in this one. I try to fix the bugs I created.
@ogrisel detected this bug. Tests are taken from your issue.

**Review by ogrisel — COMMENTED** [review]
I don't understand all the black magic tricks of the slicing/ndindexing expressions but the test looks good.

**Comment by seberg** [comment]
I pushed some changes, to simplify the logic with moveaxes and add tests for multi-dimensional inputs.

The problem if you add tests... is that you find the *other* bugs in the *old* code paths and need to fix them too.  Multi-dimensional `q` wasn't properly implemented...

**Review by seberg — APPROVED** [review]
But someone else should have a quick look over...

**Comment by charris** [comment]
Thanks @lorentzenchr and reviewers.

**Pull request merged**
