### PR TITLE
BUG: einsums bool_sum_of_products_contig incorrect for small arrays

### PR DESCRIPTION
**Pull request by seberg**
The small array (and end of loop) special case incorrectly stepped
through array and left pointers bogus.
## 

Tests still needed, anyone want to jump on this....

Honestly, I am a bit dumbstruck that this was never found. The tests probably just do not test this special case (until now matmul shapes tests), and nobody probably ever really used boolean einsum....
I found this running the tests with valgrind.

### CODE REVIEW

**Comment by seberg** [comment]
Oh, btw. one example is:
```
np.einsum('...ij,...jk->...ik', *[np.ones((2, 1, 1), dtype=np.bool_)]*2)
```

**Comment by jaimefrio** [comment]
When you gaze long enough into the einsum code, the einsum code also gazes into you. ;-)

**Comment by seberg** [comment]
Next time I have to look at it, I will wear protective glasses :P

**Comment by charris** [comment]
Looks correct to me. The code is almost too clever, what with falling through the cases from large to small. @seberg If you could add some tests I'd be much obliged.

**Comment by charris** [comment]
I'll add a test in a separate PR. Thanks Sebastian.

**Pull request merged**
