### PR TITLE
MAINT: remove maint from triggering wheel build, add env to sdist

### PR DESCRIPTION
**Pull request by mattip**
Fixes #21095 to add the missing environment variables so upload should work. Also remove wheel building for the "Maint" label since it is too common and wheel building is expensive (it does a "full" test)

### CODE REVIEW

**Comment by mattip** [comment]
@rgommers

**Comment by lithomas1** [comment]
Thanks for catching my mistake :)

**Comment by mattip** [comment]
The [sdist wheel build](https://github.com/numpy/numpy/runs/5579392359?check_suite_focus=true#step:7:19) is now properly reporting the required environment variables (as `false` since the PR should not cause an upload). Before this PR the values were empty. After merging this we can hit the manual trigger to make sure the `IS_SCHEDULE_DISPATCH`, which is true when either the cron job (SCEHDULE) or manual dispatch (DISPATCH) triggered the build, tests `true`

Would another maintainer like to review this?

**Comment by mattip** [comment]
> I'll try modifying the release scripts(tools/download-wheels.py) to also grab the sdist

Ahh, nice. I didn't notice that script before. I don't know if there is a way for one github action to trigger another so we can test the uploads. If not, perhaps we could add another cron job workflow to test that the wheels we expect to be there exist. In any case, perhaps @charris would like to use it to download the wheels for a release, in which case it should be documented as part of the release process.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @mattip! And apologies for the delay.

**Pull request merged**
