### PR TITLE
BUG: Update coordinates on PyArray_ITER_GOTO1D

### PR DESCRIPTION
**Pull request by ReallyNiceGuy**
Correctly fix bug #18987

### CODE REVIEW

**Comment by ReallyNiceGuy** [comment]
Sorry for the mixup.

The call to PyArray_ITER_GOTO1D inside PyArray_NeighborhoodIterNew introduced a bug.
I can't know if the base iterator is a normal iterator or another Neighborhood iterator. It is best to put on the C API documentation a note telling that a new Neighborhood iterator on top of a contiguous iterator that is not at the start will be pointing to the start of the data, and not at the current iterator position.

**Comment by seberg** [comment]
@ReallyNiceGuy sorry, forgot about this a bit. To be sure I understand the limitations:  If we can't do the GOTO1D to fill the indices, does that mean the function was broken if the input is a contiguous buffer?

Would it work if we introduced the GOTO1d conditionally only *if* the input was contiguous?

**Comment by ReallyNiceGuy** [comment]
Not how I see it. The way I understand it, GOTO1D is to be used only with normal iterators, not with Neighbor iterators. The same applies GOTO.
There is no such function for a neighbor iterator, from what I could find.
So, my (flawed) idea was to call GOTO1D on the creation of the neighbor iterator, to put the coordinates on the right place before resetting the created iterator. This breaks in horrible ways if the base iterator is itself a neighbor iterator.
The correct fix would be either make GOTO and GOTO1D neighbor iterator aware (too expensive for my taste, it seems), or to have a way to differentiate between a normal iterator and a neighbor iterator, implement a function that does the GOTO1D specifically for a neighbor iterators and select the correct call on the neighbor iterator creation function.
The 3rd option is to fix it in the documentation...

**Comment by seberg** [comment]
> have a way to differentiate between a normal iterator and a neighbor iterator

Oh, good point!  I think this should actually be very easy with a `PyObject_TypeCheck(...)` or if you don't want to go into subclass checking paths just `Py_TYPE(iter) == &PyArray_` (if we assume there is no subclassing, which I think we can here).  I am not sure whats best to check for (if base-class, or if a neighbourhood iterator..

**Comment by ReallyNiceGuy** [comment]
Sorry for my delay.
I ran some tests and figured out that a neighborhood iterator (`niter2`) based on another neighborhood iterator (`niter1`) behaves correctly, because the base iterator from `niter1` is already set as "non contiguous". This means that, even if  `niter1` is not at the beginning when `niter2` is created, `niter2` it will be correctly positioned. There is no need to reset the position of the neighborhood iterator inside `PyArray_NeighborhoodIterNew`.

So, just checking for a `PyArrayIterObject` and calling `GOTO1D` only on that case will be the correct thing to do. Of course, all odds are off if another subclass of `PyArrayIterObject` is created and it doesn't set `contiguous` to `0` on it's base array at creation time.

**Comment by seberg** [comment]
No rush at all, it typical for issues to not move for weeks or even months (more often because of reviewers anyway).  Although, if you would like to see this fixed in the NumPy 1.21.x release, it would be good to do soon. 

Does that mean that the `contiguous` flag is already set there? Then calling `GOTO1D` if its not-contiguous might be good enough?  Otherwise, my tendency would be to do a a check that it isn't a neighbourhood iterator.  I hope we can assume nobody subclasses these...

**Comment by ReallyNiceGuy** [comment]
> No rush at all, it typical for issues to not move for weeks or even months (more often because of reviewers anyway). Although, if you would like to see this fixed in the NumPy 1.21.x release, it would be good to do soon.

I am running the tests, and I will run scipy tests also.

 
> Does that mean that the `contiguous` flag is already set there? Then calling `GOTO1D` if its not-contiguous might be good enough? Otherwise, my tendency would be to do a a check that it isn't a neighbourhood iterator. I hope we can assume nobody subclasses these...

The neighborhood iterator always updates its own coordinates, so this change to not contiguous is unnecessary for it.

```patch
diff --git a/numpy/core/src/multiarray/iterators.c b/numpy/core/src/multiarray/iterators.c
index 3ebd4c858..6db2efaeb 100644
--- a/numpy/core/src/multiarray/iterators.c
+++ b/numpy/core/src/multiarray/iterators.c
@@ -1770,7 +1770,19 @@ PyArray_NeighborhoodIterNew(PyArrayIterObject *x, const npy_intp *bounds,
      * XXX: we force x iterator to be non contiguous because we need
      * coordinates... Modifying the iterator here is not great
      */
-    x->contiguous = 0;
+    if (x->contiguous) {
+        x->contiguous = 0;
+
+        if (Py_TYPE(x) == &PyArrayIter_Type) {
+            /*
+             * Force the coordinates to be updated, so they point
+             * to the correct index position.
+             * Only needed for a normal PyArrayIterObject that was
+             * contiguous before.
+             */
+            PyArray_ITER_GOTO1D(x, x->index);
+        }
+    }
 
     PyArrayNeighborhoodIter_Reset(ret);
```

The patch above is what I am intending to commit later.
If the iterator is already non-contiguous, then there is no need to force anything, the coordinates are being updated anyways.

**Comment by ReallyNiceGuy** [comment]
Scipy tests passed at commit https://github.com/scipy/scipy/commit/31351394351f944b9cf87c1fbc54213192cfe180

**Comment by seberg** [comment]
Thanks, sorry, but to double check:  The Type check is necessary?  I also have a slight tendency to prefer a negative type check `!= Neighbourhooditerator`, but I can't quite put my finger on why.

**Comment by ReallyNiceGuy** [comment]
> Thanks, sorry, but to double check: The Type check is necessary? I also have a slight tendency to prefer a negative type check `!= Neighbourhooditerator`, but I can't quite put my finger on why.

You know what? Good that you asked. I was writing a response to you on why it must be a positive check and then I decided to check somethings.

Even a plain `PyArrayIterObject` might not be safe to use in this automatic manner.
`PyArray_RemoveSmallest` and `PyArray_IterAllButAxis` return ```PyArrayIterObject```s that are not safe to use with  `PyArray_ITER_GOTO1D`.

I will remove this last change, and this weird behavior of `Neighbourhooditerator` must be documented.

**Comment by ReallyNiceGuy** [comment]
One test failed, but I think was azure itself. It could not install mingw.
This PR is in its final form. The issue with GOTO1D is fixed. I will open another bug with the neighborhood iterator issue. It was already an issue before this PR and it is not related.

**Comment by seberg** [comment]
Lets give this another shot.  @ReallyNiceGuy, would you be up to adding a brief note about this caveat to the NeighborhoodIterator documentation or so?

**Comment by ReallyNiceGuy** [comment]
> Lets give this another shot. @ReallyNiceGuy, would you be up to adding a brief note about this caveat to the NeighborhoodIterator documentation or so?

Sure, I can do it. Probably tomorrow, though.

**Pull request merged**
