### PR TITLE
BLD: use cython3 for one CI run

### PR DESCRIPTION
**Pull request by mattip**
Test one CI run with cython3.0.0 pre-release.

xref [this comment](https://github.com/numpy/numpy/pull/23797#issuecomment-1559334894) from a PR that noticed a tweak needed for cython3.

### CODE REVIEW

**Comment by mattip** [comment]
Hmm. The test from #17289 is failing. I don't directly see the connection with cython. As far as I know we use cython only in the random module, so why is this ufunc test failing? Maybe cython used to mess with the pickling macinery and no longer does?

**Comment by seberg** [comment]
@mattip it is a Cython bug, I have opened an issue for it there a [while ago](https://github.com/cython/cython/issues/5411).

We could try to fix it in NumPy by attaching a correct `__module__` to our ufuncs (usually `numpy`), although we cannot fix it for 3rd party ufuncs unfortunately unless we guess the module at creation time (which I don't think we can).

**Comment by mattip** [comment]
Ahh, this is a duplicate of #20167, and involves Cython 3.0.0a7 up to the current 3.0.0b3. I skipped the test for these specific versions.

**Comment by charris** [comment]
Thanks Matti, let's give this a shot.

**Pull request merged**
