### PR TITLE
DOC: improve ndarray.reshape signature documentation

### PR DESCRIPTION
**Pull request by lesteve**
It seems more accurate to use `*args`, since `a.reshape(10, 11)` is the same as `a.reshape((10, 11))`, as the note below mentions

Unless there is some subtlety I am missing?

### CODE REVIEW

**Comment by seberg** [comment]
Both forms are accepted, `arr.reshape((2, 5))` is also OK.  OTOH, I suppose this is the typical form, so maybe we should just change it (I am not actually quite certain).  `arr.transpose` is the same and uses `*axes`.

**Comment by lesteve** [comment]
I indeed know (or rather learned recently) that both forms are valid. I may be biased because I have always used `arr.reshape(2, 3, 4)` so I read the signature as "this is not supposed to work". Although the note below says both forms are fine, I find the signature is contradicting the note and somehow my mind trusts more the signature that a comment in a docstring.

Overall, my feeling is that I got confused but I am fine if nothing changes, and I will carry on with my life :wink: 

I try to motivate changing the signature below.

I would have a preference for indicating clearly in the signature that both `arr.reshape(2, 3, 4)` and `arr.reshape((2, 3, 4))` are possible. Thinking about the exact value of `shape` when a tuple is passed in (technically `shape=((2, 3, 4), )` i.e a tuple of length 1 containing a tuple of length 3 which is not a valid numpy shape), is not something I would be bothered about too much.

I tried to search in the github issues for other people having questions on this kind of things:
- https://github.com/numpy/numpy/issues/9801 also wanted to change the signature but the issue was closed when the note was added to the docstring saying that both forms are valid.
- in https://github.com/numpy/numpy/issues/10221#issuecomment-351949520, one maintainer mentions that the signature is more like `reshape(*args, *, order)`
- in https://github.com/numpy/numpy/issues/15290#issuecomment-572157614 PyCharm is complaining when `arr.reshape(2, 3, 4)` is used because the signature says only 2 arguments are accepted. Your former self (@seberg) seems to say that if we switch the signature PyCharm may be confused too, which I am not too sure about. At least the signature will be compatible, but maybe PyCharm is clever enough and will figure out that `shape` is not a valid numpy shape.

**Comment by mattip** [comment]
I am -1 on this change. We should not be encouraging the `reshape(1, 2, 3)` form rather encouraging `reshape((1, 2, 3)). The documentation already mentions that the first form (`*args`) is possible. If anything I would be in favor of deprecating the `*args` form or stating that using a tuple is preferred.

**Comment by seberg** [comment]
Thanks for the PR!  Unfortunately, I will close it with Matti's opinion.  Since no-one else noted an opinion and I am also slightly leaning that way.

Now if anyone sees this and disagrees, I am happy to reopen/revisit.  Maybe the `*args` is vastly more common in practice anyway.

It seems one of the linked issues is about improving the error message which can be quite confusing, that seems very worthwhile to me.

**Comment by lesteve** [comment]
No worries, thanks a lot for your time and comments!

**Pull request closed without merging**
