### PR TITLE
BUG remove memory leak in array ufunc override.

### PR DESCRIPTION
**Pull request by mhvk**
Backport of #9092.

#@charris - is this what you meant by backporting?

### CODE REVIEW

**Comment by charris** [comment]
Yep. The easy way to do these once the backport branch has diverged and after deleting the origin branch is
```
git rebase --onto maintenance/1.13.x HEAD^
git push origin HEAD
```
Might not need to delete that origin branch, a force push might suffice. The only drawback is that you might need to switch to the branch in order to make the new PR, github will not always show it up top like it usually does.

**Comment by juliantaylor** [comment]
even better, for the original PR to:

    git rebase --onto $(git merge-base master maintenance/1.13.x) HEAD^

that way you don't even create a new commit for the backport, just create a new PR from the same branch.

**Comment by charris** [comment]
Thanks Marten.

**Comment by mhvk** [comment]
OK, I'll try the git-fu next time!

**Comment by eric-wieser** [comment]
@juliantaylor, @charris: In the interest of making the shared-commit-style backports easier, can we tag the branch-point?

**Comment by charris** [comment]
I've considered tagging the branch point, but I don't agree that rebasing onto the branch is a hassle. Unless it fails, of course. I actually prefer it to Julian's suggestion and the link graph of the repo is much simpler.

**Comment by charris** [comment]
BTW, there is some git fu to find the branch point, although I wouldn't call it straight forward. Apparently merge-base cannot be relied upon for that purpose.

**Pull request merged**
