### PR TITLE
DOC: Post 1.14.0 release updates.

### PR DESCRIPTION
**Pull request by charris**
* Update .mailmap
* Update 1.14.0-notes.rst
* Add 1.14.0-changelog.rst

[skip ci]

### CODE REVIEW

**Comment by eric-wieser** [comment]
Isn't it `[ci-skip]`?

**Comment by charris** [comment]
It's either of `[ci skip]` or `[skip ci]`. The reason it no longer works with appveyor is that they recently decided that it needs to be on the first line after the summary, which violates standard git practice. AFAICT, lgtm has always ignored it. There are also version specific to the various testing services.

**Comment by charris** [comment]
Ah here we are
>AppVeyor searches for [skip ci] / [ci skip] / [skip appveyor] in the commit message title only. This avoids confusion when squashing commits, in particular with the GitHub squash-and-merge feature.

**Review by eric-wieser — APPROVED** [review]
Will let you merge this, in case you find anything else you missed.

**Pull request merged**
