### PR TITLE
ENH: Allow ravel to reshape in place when possible

### PR DESCRIPTION
**Pull request by seberg**
Closes gh-5033

Will add tests later...

### CODE REVIEW

**Comment by seberg** [comment]
Hmm, never added release notes I guess. @aarchiba maybe you have an opinion about this? This broke `vdot` (which used to use flatten though), but I thought since you changed the reshape code at some point you might have an opinion here. We can either undo this (partly), or change vdot and hope others C-code does not run into the issue.

The change is, that the old code would (except for keeporder) always return a contiguous chunk of memory.

**Comment by njsmith** [comment]
- can you file a 1.10 blocker bug to ensure this doesn't get lost?
- can you explain what the issue with `vdot` actually is? is it that `ravel` is returning a logically different array (e.g. it's unwrapping the array in a different order), or is it really that the array is the same (same elements in the same order) but just with different storage layout?

**Comment by seberg** [comment]
Of course the array is the same, but it is not contiguous in memory. `vdot` used to use `flatten` as well though.
Or one could say, the current version is as if you do:
```
np.array(np.ravel(arr, order='C'), copy=False, order='C')
```

**Comment by seberg** [comment]
Sorry, that got mangled up. The example is what would give the old result with the current version.
Note that the first `order` is iteration order, while the second is memory layout.

**Pull request merged**
