### PR TITLE
TST: switch to ubuntu wily for testing with gcc5

### PR DESCRIPTION
**Pull request by juliantaylor**

### CODE REVIEW

**Comment by juliantaylor** [comment]
oh right we haven't fixed the version check reading stderr yet

**Comment by charris** [comment]
Seems to have compiled and installed, not sure why the error.

**Comment by charris** [comment]
Closing and reopening to restart build from scratch.

**Comment by charris** [comment]
@juliantaylor Needs a rebase. Do you want to keep this open?

**Comment by charris** [comment]
Closing this. The test script has changed significantly and the changes here are pretty minimal, so it is probably easiest to just start over.

**Pull request closed without merging**
