### PR TITLE
DOC: isclose accepts boolean input

### LINKED ISSUE #19309: isclose accepts bool inputs although the docs state it shouldn't
## Documentation

The docstring of `numpy.isclose` currently states

https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/numeric.py#L2314

but it happily accepts boolean tensors:

```python
>>> a = np.array([True], dtype=np.bool_)
>>> np.isclose(a, a)
array([ True])
```

### PR DESCRIPTION
**Pull request by yashasvimisra2798**
Added that `isclose` accepts boolean tensors.
Fixes #19309

### CODE REVIEW

**Comment by rkern** [comment]
We don't use the word "tensor" in numpy documentation unless if we mean actual [multilinear maps](https://en.wikipedia.org/wiki/Tensor). We use "array" for cases such as these.

A corresponding change also needs to be made to the same note for `allclose()`.

**Comment by rkern** [comment]
I had to go to the [origin discussion](https://github.com/numpy/numpy/pull/16835#pullrequestreview-448436234) to understand exactly why `bool` requires a specific callout here. I know I always think of them as a "numeric" data type (insofar as they get treated as 0s and 1s as needed pretty much whenever "numeric-ness" is requested), the inheritance hierarchy not-withstanding. I might phrase this as "`bool` is considered a numeric data-type for this purpose".

**Comment by yashasvimisra2798** [comment]
@rkern thanks, I'll fix this. Also for `allclose()` where exactly shall I add this line?

**Comment by rkern** [comment]
It has the same `non-numeric data types` comment to be fixed.

**Comment by yashasvimisra2798** [comment]
@rkern I have made the changes, please check.

**Review by rkern — APPROVED** [review]
LGTM!

**Comment by rossbar** [comment]
Thanks @yashasvimisra2798 !

**Pull request merged**
