### PR TITLE
BLD: declare support for python 3.8

### PR DESCRIPTION
**Pull request by mattip**
The descriptors on [PyPI](https://pypi.org/project/numpy/) are missing Python 3.8

### CODE REVIEW

**Comment by mattip** [comment]
the macos build is failing, this seems to be the relevant part of the log:
```
Installed /Users/runner/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/numpy-1.17.4.dev0+2ec2d35-py3.6-macosx-10.14-x86_64.egg
Processing dependencies for numpy==1.17.4.dev0+2ec2d35
Searching for numpy==1.17.4.dev0+2ec2d35
Reading https://pypi.org/simple/numpy/
No local packages or working download links found for numpy==1.17.4.dev0+2ec2d35
```

**Review by rgommers — APPROVED** [review]

**Comment by ihnorton** [comment]
FWIW, I'm seeing the same kind of build failure on azure/macOS ([link](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=1409&view=logs&jobId=291b3e6c-60a9-5f30-6b17-b27c7388dcd0&taskId=811bd65a-d252-5f67-f059-7dfe899d7bf6&lineStart=525&lineEnd=526&colStart=1&colEnd=1)) for a different package. The problem seems to be a mismatch between `platform.mac_ver` and `distutils.util.get_platform()`. With some debugging printouts I get:

```
platform.mac_ver: ('10.13.6', ('', '', ''), 'x86_64')
distutils.util.get_platform:  macosx-10.14-x86_64
```

It is unclear where that difference is coming from, because `MACOSX_DEPLOYMENT_TARGET` is not set by the environment ([test](https://github.com/TileDB-Inc/TileDB-Py/pull/214/commits/fcd4a1ce28531a371b6da8a5ee143260b17642cf), [output `MACOSX_DEPLOYMENT_TARGET:  <none>`](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=1415&view=logs&jobId=291b3e6c-60a9-5f30-6b17-b27c7388dcd0&taskId=78986c0d-983a-5e7e-7bcc-d42b42569216&lineStart=160&lineEnd=161&colStart=1&colEnd=1))

But when I print out `distutils.sysconfig.get_config_vars`, it shows `MACOSX_DEPLOYMENT_TARGET=10.14`...

Manually setting `MACOSX_DEPLOYMENT_TARGET=10.13` in pipeline environment via yml breaks the `setuptools` build 🤷‍♂

**Comment by rgommers** [comment]
Thanks @ihnorton. That doesn't look fun to debug. Sounds like a bug in Python itself, please ping us if you file an issue on the Python bug tracker.

**Comment by ihnorton** [comment]
I believe what is happening is that the Python interpreter from the azure `UsePythonVersion` task was built with `MACOSX_DEPLOYMENT_TARGET=10.14`. That's where the __cached__ `distutils.sysconfig.get_config_vars` value is coming from. This value sets the result of `distutils.util.get_platform`.

- `distutils.util.get_platform` calls `_osx_support.get_platform_osx`: https://github.com/python/cpython/blob/17d0c0595e101c4ce76b58e55de37e6b5083e6cd/Lib/distutils/util.py#L87
- `get_platform_osx` uses the cached value of `MACOSX_DEPLOYMENT_TARGET`: https://github.com/python/cpython/blob/cf10a750f4b50b6775719cfb17bee00bc3a9c60b/Lib/_osx_support.py#L429-L502

Now, note that eggs and local build tmpdir are named based on the output of `distutils.util.get_platform`: https://github.com/pypa/setuptools/blob/3b8307541e6d24c5eeb4e4998cf9ee46b6e6506f/setuptools/wheel.py#L82-L86

Working from the error location
- the `tmpdir` name is used to check compatibility of the local package (for `setup.py install`): https://github.com/pypa/setuptools/blob/b9a9aae8b3b624443722a40ca935348d2a100b7d/setuptools/command/easy_install.py#L665-L670
- package index availability check calls `wheel.is_compatible`: https://github.com/pypa/setuptools/blob/1cc88214f605e8458cc45495e6a8f476ad6d1cbb/setuptools/package_index.py#L119
- which in turn calls `pep425tags.get_supported`: https://github.com/pypa/setuptools/blob/3b8307541e6d24c5eeb4e4998cf9ee46b6e6506f/setuptools/wheel.py#L79
- which uses its own implementation of `get_platform`: 
https://github.com/pypa/setuptools/blob/772db178f1bcea1ea892c61b026d658a32998476/setuptools/pep425tags.py#L266-L280
- which is based on the output of `platform.mac_ver`: https://github.com/pypa/setuptools/blob/772db178f1bcea1ea892c61b026d658a32998476/setuptools/pep425tags.py#L119-L142

Minimal test repo: https://github.com/ihnorton/azure-mac-py-version
Build log: https://dev.azure.com/isaiahnorton/isaiahnorton/_build/results?buildId=228

---

So, I guess distutils doesn't support targeting an older platform than the interpreter was compiled against. It seems like this is arguably an azure bug, in that they installed a python version that is partially incompatible with the image used. I'll open a bug about it (and for my own CI, I will probably switch to miniconda for now).

**Comment by ihnorton** [comment]
Azure pipelines issue: https://github.com/microsoft/azure-pipelines-image-generation/issues/1342

**Comment by charris** [comment]
Might as well get this in now, I forgot to do it for 1.17.x before the release. Thanks Matti.

**Comment by charris** [comment]
@ihnorton Thanks for tracking that down.

**Pull request merged**
