### PR TITLE
DOC: Added warning about using append for masked arrays (#22338)

### PR DESCRIPTION
**Pull request by MatteoRaso**

### CODE REVIEW

**Comment by seberg** [comment]
Thanks for looking into this.  But I think I mentioned in the issue that adding docs is seems better in the masked array docs not in the `append` docs (as a general note).  There are many functions that do not work properly with MA, marking some of them IMO gives the wrong impression that only those are problematic.  And I don't think we will mark _all_.

**Comment by MatteoRaso** [comment]
> Thanks for looking into this. But I think I mentioned in the issue that adding docs is seems better in the masked array docs not in the `append` docs (as a general note).

That seems confusing, though. If somebody is looking at the documentation for ma.append, then they already know to use that function instead of append, so the message would be useless.

>There are many functions that do not work properly with MA, marking some of them IMO gives the wrong impression that only those are problematic.

Would it? I don't think that's the impression that I would get if I saw a warning in the documentation about using the function with masked arrays. Besides, append doesn't outright fail here, it appends the arrays but gives the wrong result, so people could end up thinking that it's the right function to use. At the worst, all that needs to be done is add "consider using a function from numpy.ma when working with masked arrays".

**Comment by mattip** [comment]
I think the energy expended here would be better put to solving the problem systematically. [This comment](https://github.com/numpy/numpy/issues/22338#issuecomment-1259054223) provides a better path for moving forward than adding documentation warnings. There are prototype classes out there. For instance, the astropy one has [`__array_function__`](https://github.com/astropy/astropy/blob/482a641c1d2d261bdc733aff9720cba4f2005a2e/astropy/utils/masked/core.py#L787) and [`__array_ufunc__`](https://github.com/astropy/astropy/blob/482a641c1d2d261bdc733aff9720cba4f2005a2e/astropy/utils/masked/core.py#L648) which probably solve 90% of these problems.

**Comment by mattip** [comment]
... although after a cursory glance there I did not see an `append` for that class :(

**Comment by seberg** [comment]
The implementation is there: https://github.com/astropy/astropy/blob/482a641c1d2d261bdc733aff9720cba4f2005a2e/astropy/utils/masked/function_helpers.py#L454

I am not saying to put it on `ma.append` that is clearly useless.  I am saying that the Masked arrays overview/intro page *should* warn that many functions may misbehave for masked array inputs.
Note, that this is not limited to NumPy itself, even though it may be more surprising there.  *Many* things will silently drop the mask.

We can discuss adding it everywhere, but even then my feeling would be that is the wrong approach.  Masked arrays are, maybe unfortunately so, not really a core feature.  Fixing masked arrays seems not super realistic, so replacing them with something outside of NumPy is the realistic path as Matti pointed out.

**Comment by MatteoRaso** [comment]
>We can discuss adding it everywhere, but even then my feeling would be that is the wrong approach.

I feel the exact opposite. I think the best solution would be to include a check to see if the input is a masked array in every function that has a corresponding masked function, and if it is, then pipe the input to the masked function. That being said, it's clear that this is part of a much larger problem than this small fix can solve, and this isn't the right place to find a solution, so I'm closing the PR.

**Pull request closed without merging**
