### PR TITLE
BUG: fixes for StringDType/unicode promoters

### LINKED ISSUE #27493: BUG: index string ufunc promoter issues
At runtime, when the first argument is of `dtype[str_]` and `StringDType` dtype, the second argument can (also) be a native `str`, a (nested) sequence of `str`, or any other `np.str_` array-like (including `NDArray[str_]`).

```pycon
>>> np.char.index(np.array(["where's Wally?"], dtype=np.str_), "Wally")
array([8])
>>> np.char.index(np.array(["where's Wally?"], dtype=np.dtypes.StringDType()), "Wally")
array([8])
>>> np.char.index(np.array(["where's Wally?"], dtype=np.dtypes.StringDType()), np.str_("Wally"))
array([8])
```

But this doesn't appear to be the case when the dtypes "flipped", i.e.

```pycon
>>> np.char.index(np.array(["where's Wally?"], dtype=np.str_), np.array("Wally", dtype=np.dtypes.StringDType()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.pyenv/versions/3.12.6/lib/python3.12/site-packages/numpy/_core/strings.py", line 327, in index
    return _index_ufunc(a, sub, start, end)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy._core._exceptions._UFuncNoLoopError: ufunc 'index' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StringDType'>, <class 'numpy.dtypes._PyLongDType'>, <class 'numpy.dtypes._PyLongDType'>) -> None
```

_Originally posted by @jorenham in https://github.com/numpy/numpy/pull/27470#discussion_r1782989412_

### LINKED ISSUE #27637: BUG: Operation spuriously returns a legacy string
After applying the changes from #27636:

```
>>> print(repr(np.strings.replace(
            np.array(["hello planet"], dtype="U"),
            np.array("planet", dtype="T"),
            np.array("world", dtype="T"))))
array(['hello world'], dtype='<U11')
```

We get a unicode array back, despite the fact that StringDType explicitly installs a promoter for this case.

I thought this had something to do with the fact that the legacy string unicode promoters work by constructing a promoter DType tuple that's filled with `None` entries. But that's fine, since `None` has less priority than a specific DType.

Instead something else is going on. I got as far as tracing through the call to `resolve_descriptors`, which does correctly set the output DType to StringDType, so something else fishy is going on later when the actual output array is created.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes https://github.com/numpy/numpy/issues/27493. Fixes #27637.

There are a number of missing cases for mixed unicode/string operations that this adds promoters for. Also adds tests for these cases.

Additionally replaces uses of `Py_None` as an abstract promoter target with `PyArray_IntAbstractDType`, which makes the promoters fire less offten in unintended cases and is closer to the intention in the code.

Also fixes issues with the python wrappers for the string ufuncs incorrectly selecting the fixed-width string branches for some signatures by relying on `np.result_type` to check for `StringDType` inputs.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
The latest version of this PR touches a lot of code that @lysnikolaou wrote in the python-level string ufunc wrappers so I'm giving him a ping in case he wants to take a look.

**Comment by ngoldbaum** [comment]
@jorenham if you're at all curious how NumPy handles ufunc type dispatching on the C side, this fixes an issue you spotted while playing with the type stubs.

**Review by mhvk — APPROVED** [review]
This looks good to me. While looking at the tests and also #27637, I did wonder whether you really want the output to be `StringDType` in something like `replace` when what you started with was a `U` array. But I think it probably is just good to moving towards `StringDType` by default.

**Comment by ngoldbaum** [comment]
@seberg would you mind taking a look at this? I value your sense of taste for the "right" way to make changes to numpy internals.

**Review by seberg — APPROVED** [review]
Looks fine to me.  I think there might be a whole in the logic for `out=`, but I am not sure it is worth digging deeper (as opposed to a follow-up, maybe when a bug is reported).

I would love to find a better story for this type of thing... The one story that I could potentially see is to make something like an abstract (doesn't need to be an actual thing could just be a tuple as in `isinstance`, but conceptually):
```
class StringOrUnicodeDType:
```
so that we could just add _one_ promoter, but the promoter would be need to programmatically decide whether the result should be unicode or string.
(Similar to the "this dtype must occur", style of logic.  But these ufuncs that include ints show that just a list of dtypes is not super helpful a such)

(Sorry, the changes look good to me, but I am not sure I am in the right state of mind for any inspiration, although I do suspect the tuple idea is about as good as it gets.  Together with allowing a promoter to say "do not apply" it would go very far -- if we allow that, a promoter could even register everything, it would just not be friendly)

**EDIT: I forgot to say thanks :), this is tricky stuff and looks good, just unfortunately verbose.  And verbose isn't fully unintentionally, but it would be good to improve it.**

**Comment by ngoldbaum** [comment]
Thanks! I agree there's definitely room for improvement here to make it less verbose. I also noticed while working on this that the use of `None` in the Unicode promoters makes them fire way too often (e.g. for `add` and `multiply` for purely numeric operands). We should fix that too.

I opened a followup issue about this: https://github.com/numpy/numpy/issues/27671

I'll go ahead and merge this.

**Comment by danish-circuit** [comment]
I've been running into an issue and I suspect this merge where:

`embedding = np.array(response["embedding"]).astype(np.float32).tolist()`

and 

```
class ChunkEmbedding(BaseModel):
    chunk_id: str
    embedding: list[float]
    embedding_model: str
    input_tokens: int
```

returns a mypy error:

`Argument "embedding" to "ChunkEmbedding" has incompatible type "str | list[str] | list[list[str]] | list[list[list[Any]]]"; expected "list[float]"  [arg-type]`

Only an issue on 2.2.0 and not 2.1.0. 

Should I be doing something else after these updates?

**Comment by seberg** [comment]
@danish-circuit this PR doesn't have anything to do with typing.  Please make a new issue with a full reproducer ideally.

**Pull request merged**
