### PR TITLE
BLD: cp313 cp313t linux_aarch64 [wheel build]

### PR DESCRIPTION
**Pull request by andyfaff**
cp313+cp313t builds for linux_aarch64.

### CODE REVIEW

**Comment by charris** [comment]
Hmm, there is some problem with 313t on aarch64. There is also a nightly build of musllinux for aarch64 for earlier Python, but I don't see where that is located. @mattip I believe you were experimenting with that using a newer musl version?

**Comment by andyfaff** [comment]
It might just need an environment variable to be set.

**Comment by ngoldbaum** [comment]
If you don't want to work on the free-threaded wheel, just disable it for now and I'll work on adding it in a followup.

**Comment by ngoldbaum** [comment]
The thing you're missing from the github actions config for free-threaded wheels is this bit:

```
      - name: Set up free-threaded build
        if: matrix.python == 'cp313t'
        run: |
          echo "CIBW_BUILD_FRONTEND=pip; args: --no-build-isolation" >> "$GITHUB_ENV"
```

I'm not familiar with cirrus, but somehow you'll need to set that environment variable in the runner's shell environment, similar to the `$GITHUB_ENV` mechanism.

**Comment by charris** [comment]
> If you don't want to work on the free-threaded wheel, just disable it for now

I'll probably just put this in as is if it isn't fixed soon, it looks fixable.  @andyfaff I'm curious about the missing musllinux build for 3.13 on aarch64, do we need the new version of musl?

**Comment by charris** [comment]
Cirrus offers the following example:
```
custom_path_task:
  env:
    SDK_ROOT: ${HOME}/sdk
    PATH: ${SDK_ROOT}/bin:${PATH}
  custom_script: sdktool install
```

**Comment by andyfaff** [comment]
> I'm curious about the missing musllinux build for 3.13 on aarch64, do we need the new version of musl?

The `linux_aarch64_task` will build both the manylinux and musllinux wheels.

**Comment by charris** [comment]
The 3.13t aarch64 build timed out, we might want to make the manylinux and musl builds separate tasks.

**Comment by andyfaff** [comment]
I tried to tune the builds so they use a minimal set of resources, for cost. So we could either add another entry or bump CPUs/memory.

**Comment by charris** [comment]
Thanks Andy, Nathan. The second run of the 3.13t build took 51 minutes, which might be shaving things a bit close, but the failure is fixable with a rerun.

**Comment by ngoldbaum** [comment]
Should the nightlies have shown up on the staging site? I don't see how to trigger builds for nightly wheels on cirrus.

**Comment by seberg** [comment]
Not sure how to trigger cirrus wheel builds (except by adding a one-off chron).  I triggered the others manually today.  Cirrus seems currently scheduled weekly on sunday only.
(I don't recall changing it back from bi-weekly, but I guess things slowed down.)

**Comment by charris** [comment]
> I don't see how to trigger builds

I don't know how to trigger a new build on cirrus either, but looked into it a bit once. IIRC, there needs to be in entry in the YML file to allow that.

**Comment by rgommers** [comment]
It's a little fiddly on Cirrus - I go to the repo settings and change the cron config to trigger a build 2 minutes into the future, then change it back to the original schedule after the build succeeds. I think I've got the routine down now though. Don't we get RC builds anyway in hours to a day, now that the branch happened?

If you want me to do it let me know

**Comment by ngoldbaum** [comment]
No worries, I just was curious why they hadn't shown up yet on the nightly wheel site.

I don't think it'll help much to have nightlies a day or two before the RC so I wouldn't go out of your way to set it up.

**Pull request merged**
