### PR TITLE
MAINT: pass -v in cibw test command [wheel build]

### PR DESCRIPTION
**Pull request by ngoldbaum**
This makes the output more verbose but also makes it easier to track down rare hangs and crashes. c.f. https://github.com/numpy/numpy/issues/27872#issuecomment-2507483739

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM, thanks Nathan

**Review by rgommers — CHANGES_REQUESTED** [review]
Eh, except that after reading the logs I see that it didn't actually work. Also, it'd be better to do this only for the free-threaded wheels I think, since the log is a lot harder to read and we don't have the verbose need for the other builds.

**Comment by ngoldbaum** [comment]
> Eh, except that after reading the logs I see that it didn't actually work

Argh, I guess pytest-xdist doesn't actually support writing the output. So maybe a better fix would be to run the tests under `pytest-xdist`, but maybe with [`pytest-timeout`](https://pypi.org/project/pytest-timeout/) set to something reasonable like 10 minutes so any hanging test gets killed by the runner (hopefully!)

**Comment by ngoldbaum** [comment]
Closing since this doesn't work, as Ralf pointed out.

**Pull request closed without merging**
