### PR TITLE
BUG: Vecdot subclasses and axis

### PR DESCRIPTION
**Pull request by mhvk**
In #25155, a new `vecdot` function was introduced. This fixes two aspects
1. Ensure subclasses are passed through.
2. Ensure axis is interpreted as it would be for `gufunc`.

I'm not sure the latter is consistent with the array API, though if it isn't, there likely are problems elsewhere too.

### CODE REVIEW

**Review by mtsokol — APPROVED** [review]

**Comment by mhvk** [comment]
See #25416 for what should be the better alternative, of creating a gufunc for vecdot.

**Comment by charris** [comment]
@mhvk How do you want to do this with #25416 also up for review?

**Review by charris — APPROVED** [review]

**Comment by mhvk** [comment]
I think #25416 is the proper solution, but want to be sure that at least one gets merged. If it is easier, we can merge this and I will just rebase. But also fine to make this a draft or close it for now.

**Comment by charris** [comment]
OK, I made it a draft and we will see how  #25416 goes.

**Comment by charris** [comment]
Closing this, the ufunc versions seems close to going in.

**Pull request closed without merging**
