### PR TITLE
MAINT: back out conversion of npymath component to c++

### LINKED ISSUE #21629: BLD: numpy-1.23.0rc1 wheels cannot be used to build scipy
Continuation of #21360, related to #20880

The cibuildwheel-built wheels have a subtle problem with npymath.lib. The compilation adds a msvc-specific `.drectve` section to the library which mingw64 does not understand. This causes the build on scipy to fail. See scipy/scipy#16305. It seems they have a directive to link to py3.x.lib, which comes from `pragma comment(lib,"python3XX.lib")` in `pyconfig.h`. Now what changed in npymath that is including python headers?

### PR DESCRIPTION
**Pull request by mattip**
May fix #21629 by reverting the conversion to a c++ file. I got the last version of the C file via `git show -r 91a3e3a~1 -- numpy/core/src/npymath/ieee754.c.src > numpy/core/src/npymath/ieee754.c.src`, where `91a3e3a` is the commit that deleted it so `91a3e3a~1` is the commit-one-before.

Once this is merged, we can kick off wheels, and then retry the scipy build with those wheels.

### CODE REVIEW

**Comment by charris** [comment]
Welp, let's give it a shot :)

Thanks Matti.

**Comment by charris** [comment]
I'll fire up the cibuild.

**Comment by mattip** [comment]
I am optimistic. The dumpbin /directives is cleaner

<details>

```
>dumpbin /directives numpy\core\lib\npymath.lib
Microsoft (R) COFF/PE Dumper Version 14.29.30141.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file numpy\core\lib\npymath.lib

File Type: LIBRARY

   Linker Directives
   -----------------
   /DEFAULTLIB:python38.lib
   /DEFAULTLIB:MSVCRT
   /DEFAULTLIB:OLDNAMES

   Linker Directives
   -----------------
   /DEFAULTLIB:python38.lib
   /DEFAULTLIB:MSVCRT
   /DEFAULTLIB:OLDNAMES

   Linker Directives
   -----------------
   /DEFAULTLIB:python38.lib
   /DEFAULTLIB:MSVCRT
   /DEFAULTLIB:OLDNAMES

   Linker Directives
   -----------------
   /DEFAULTLIB:python38.lib
   /DEFAULTLIB:MSVCRT
   /DEFAULTLIB:OLDNAMES

  Summary

          18 .bss
        1588 .chks64
          10 .data
         2B8 .debug$S
         128 .drectve
         624 .pdata
         304 .rdata
        796C .text$mn
         8B0 .xdata

```

</details>

**Comment by mattip** [comment]
This [passes the meson build on windows](https://github.com/mattip/scipy/runs/6645288163?check_suite_focus=true).

**Comment by charris** [comment]
Great. I assume the pypy problem is something different.

**Comment by mattip** [comment]
> I assume the pypy problem is something different.

Yes

**Pull request merged**
