### PR TITLE
Maintenance/1.10.x

### PR DESCRIPTION
**Pull request by chiffa**
Added this example for `pad` function in `arraypad.py`:

```
    >>> a = [[1, 2], [3, 4]]
    >>> a = np.lib.pad(a, ((3, 2), (2, 3)), 'constant',
                 constant_values=np.array(((-1, -2), (-3, -4))))
    array([[-3 -3 -1 -1 -4 -4 -4]
           [-3 -3 -1 -1 -4 -4 -4]
           [-3 -3 -1 -1 -4 -4 -4]
           [-3 -3  1  2 -4 -4 -4]
           [-3 -3  3  4 -4 -4 -4]
           [-3 -3 -2 -2 -4 -4 -4]
           [-3 -3 -2 -2 -4 -4 -4]])
```

with respect to undocumented change in behavior from issue #7353

### CODE REVIEW

**Comment by njsmith** [comment]
* Something's gone wrong with your git branches
* All fixes should go to master first, not directly to maintenance branches
* The proper fix here is probably to fix `arraypad` to accept the old syntax so that the old docs become right again :-)

**Comment by chiffa** [comment]
Ok, took note about master and branch, will try when I have a bit more time to dig in depth.

The behavior of the constant padding in multiple dimensions was never documented, which I guess led the the failure of detecting the change in the behavior. Should I still add it into the docstrings? I assume they are run as unit-tests during the continuous integration, right?

Should I also investigate the weird behavior of the `np.nan` that gets converted to a signed 32 bit integer?

**Comment by njsmith** [comment]
> The behavior of the constant padding in multiple dimensions was never documented, which I guess led the the failure of detecting the change in the behavior. Should I still add it into the docstrings? I assume they are run as unit-tests during the continuous integration, right?

No, we don't test docstrings. If this is behavior that you were depending on and we broke it, though, then the usual default assumption would be that that's a bug and we should fix it (regardless of whether it was actually documented or tested). If it turns out there was some good reason why it was broken or similar than that might change, but if it's just a matter of coercing array-like inputs into real arrays then it's probably just a bug. And if you want to submit a fix then you should certainly also add a test at the same time, and documentation if that makes sense.

> Should I also investigate the weird behavior of the np.nan that gets converted to a signed 32 bit integer?

This is sorta-intentional, in that if you insist on casting from float to integer then we map `nan` to the smallest possible integer (which doesn't make much sense, but no other options make any more sense). However, it is probably a bug that we are allowing floats here to be silently cast to integer at all -- trying to pad an integer array with floats should raise an error in general.

**Comment by njsmith** [comment]
Closing this pull request due to git being difficult -- feel free to re-open a new one :-)

**Pull request closed without merging**
