### PR TITLE
MAINT: update x86-simd-sort to latest

### PR DESCRIPTION
**Pull request by r-devulap**
latest version simplifies the use of static avx512 and avx2 sort, argsort, partition and argpartition functions. No difference in performance or algorithms.

### CODE REVIEW

**Comment by mattip** [comment]
MSVC is failing to build

**Comment by r-devulap** [comment]
> MSVC is failing to build

yeah, MSVC has no icelake specific flags and doesn't define __AVX512VBMI2__ leading to missing header files :/

**Comment by mattip** [comment]
Ci is passing. @seiko2plus want to take a look?

**Review by Mousius — APPROVED** [review]
Seems ok to me 😸

**Pull request merged**
