### PR TITLE
MAINT: Remove redundant Python2 float/int conversions

### LINKED ISSUE #17283: Why does int64's is not inherited from "int", but "float64" is inherited from "float"?
### Reproducing code example:

```python
import numpy

numpy.float64.mro() -> [numpy.float64,
                        numpy.floating,
                        numpy.inexact,
                        numpy.number,
                        numpy.generic,
                        # Here the standard float type:
                        float,
                        object]

numpy.int64.mro() -> [numpy.int64,
                      numpy.signedinteger,
                      numpy.integer,
                      numpy.number,
                      numpy.generic,
                      object]


isinstance(numpy.float64(1.2345), float) -> True

isinstance(numpy.int64(1), int) -> False
```

### Numpy/Python version information:

```
import sys, numpy; print(numpy.__version__, sys.version)
1.19.1 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
```

### PR DESCRIPTION
**Pull request by shubham11941140**
Reviving #18218
Resolves #17283

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
These all look reasonable to me (assuming CI is happy), thanks for the contribution.

**Comment by shubham11941140** [comment]
There are no conflicts and all checks have passed, please merge it with main, so I can close the Pull Request.

**Comment by eric-wieser** [comment]
This code was plagiarized from #18218 it seems.

**Comment by shubham11941140** [comment]
I want to remove my code. Please give me a PR and remove the merge from the main branch.

**Comment by eric-wieser** [comment]
In this case I think just editing the PR text at the top to indicate that you are reviving a stale PR is enough; there's no need to actually revert the change.

But it's really important for reviewers that we know when you are reviving an old PR, otherwise we waste time repeating old discussions.

**Pull request merged**
