### PR TITLE
API: Change default axis argument for argsort.

### LINKED ISSUE #8701: BUG: np.ma.argsort has different default for axis than ndarray
Right now, the default arguments for sorting-related methods are:

Defaults to `axis=-1`:
 * `np.sort`
 * `np.ndarray.sort`
 * `np.argsort`
 * `np.ndarray.argsort`
 * `np.ma.sort`
 * `np.masked_array.sort`
 * The _documentation_ of `np.ma.argsort`
 * The _documentation_ of `np.masked_array.argsort`

Defaults to `axis=None`:
 * The _implementation_ of `np.ma.argsort`
 * The _implementation_ of `np.masked_array.argsort`

For 1D arrays, there is no difference, as `None` just means flatten and use the only axis.

For 2D arrays, however, code written for `ndarrays` can fail in unexpected ways when passed a `masked_array`, because `sort` breaks liskov subsitution:

```
def foo(x):
    i = x.argsort()
    assert(i.shape == x.shape)

>>> foo(som_arr)  # ok
>>> foo(som_arr.view(MaskedArray)) # AssertionError
```

### PR DESCRIPTION
**Pull request by eric-wieser**
Now matches:
 * its own documentation
 * everything else

Fixes #8701 

---

Should this be considered a breaking change? Do we want to go through a deprecation cycle that requires this argument to be specified explicitly when needed? Something like \<snip\> #8918 

Continuing from a forgotten discussion with @juliantaylor at https://github.com/numpy/numpy/pull/8678#discussion_r102762155

### CODE REVIEW

**Comment by rgommers** [comment]
Yeah, this is a breaking change. There's something to be said for Julian's position of "this ship has sailed", and also for making the user specify ``axis`` explicitly and keeping the ``FutureWarning`` in place for several releases. We can't just change the default.

**Comment by eric-wieser** [comment]
Fair, I'll update this PR with the deprecation approach instead

**Comment by eric-wieser** [comment]
Ok, I'll leave this as is for when that "several releases" time comes.

In the mean time, I've got a deprecating version at #8918

**Comment by eric-wieser** [comment]
Closing this, since it'll be easier just to make a new PR to remove this deprecation

**Pull request closed without merging**
