### PR TITLE
BLD, BUG: Fix cblas detection on windows

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by mattip** [comment]
The installed package is called "cblas"? Where does that package come from?

**Comment by isuruf** [comment]
It's from netlib.org. We use it to build numpy and then switch between netlib/MKL/OpenBLAS at install time.

See also section "NumPy packages & accelerated linear algebra libraries" in https://numpy.org/install

**Comment by mattip** [comment]
LGTM, let's put this in. Documentation: it would be nice to take a look at [site.cfg.example](https://github.com/numpy/numpy/blob/f1206ddb24d35781328266b2b02fa27e6fbb9846/site.cfg.example) or the install documentation and mention all the different BLAS implementations we support.

**Comment by mattip** [comment]
Thanks @isuruf

**Pull request merged**
