### PR TITLE
BUG: Fixes #7395, operator.index now fails on numpy.bool_

### LINKED ISSUE #7395: np.bool_.__index__ should error
`operator.index` correctly raises an error on boolean arrays:

```
In [6]: operator.index(np.array(True))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a4163d1794ac> in <module>()
----> 1 operator.index(np.array(True))

TypeError: only integer arrays with one element can be converted to an index
```

But on a boolean scalar, it incorrectly succeeds:

```
In [7]: operator.index(np.bool_(True))
Out[7]: 1
```

The latter should be an error (possibly with some deprecation period).

### PR DESCRIPTION
**Pull request by emilienkofman**
Attempt to fix the bug described in #7395. If this needs a depreciation warning I can change the Err to Warning and maybe add a test (?)

### CODE REVIEW

**Comment by charris** [comment]
Needs a test in anycase, also a mention in `doc/release/1.12.0-notes.rst`.

**Comment by seberg** [comment]
Should we deprecate this first if we do it? Once this is removed PyArray_IntpFromPyInt (or whatever it was exactly called) in conversion_utils.c can be simplified a little, since checking for a numpy bool is not necessary anymore.

**Comment by charris** [comment]
@emilienkofman Needs to be finished.

**Comment by eric-wieser** [comment]
Closing in favor of #9685

**Pull request closed without merging**
