### PR TITLE
DOC: Fix some documentation formatting.

### PR DESCRIPTION
**Pull request by abhinavsagar**

### CODE REVIEW

**Comment by charris** [comment]
I think the lines should be merged, not separated.

**Comment by charris** [comment]
Please look at the documentation on commit messages, your original was uninformative.

**Comment by abhinavsagar** [comment]
@charris Done. Sorry for the inconvenience.

**Comment by eric-wieser** [comment]
What is the purpose of this change? It makes no difference to the rendered docs, and in my mind,
```
This is a long sentence that
wraps.
This is the next sentence
```
is better than
```
This is a long sentence that
wraps. This is the next
sentence
```
because it means you can change the first sentence without having to rewrap all the others.

**Comment by mattip** [comment]
Closing. Pretty sure we don't want to start a cycle of small formatting changes, unless it is a concentrated effort with clear goals in mind. Please feel free to reopen if you disagree.

**Pull request closed without merging**
