### PR TITLE
DOC: Style version switcher button

### PR DESCRIPTION
**Pull request by tupui**
Follow up of #21426

It styles the button following what is done in SciPy:

- In PR, button name is using the PR reference (~default blue colour is used~)
- Stable is green
- Dev is orange
- Old is red

Colours where picked from:

```
Wong, B. Points of view: Color blindness.
Nat Methods 8, 441 (2011). https://doi.org/10.1038/nmeth.1618
```

cc @seberg

### CODE REVIEW

**Comment by tupui** [comment]
Wait for some reason the PR name is not showing up in the button. I am looking into it.

**Comment by tupui** [comment]
I updated the PR, locally it works, let's see here.

For the colour this is a theme issue actually. When no version is found like here, it does not add anything to the CSS dataset. Not sure we can look for the absence of a property in the dataset (still looking and if I don't find, maybe something to add in the theme). But if red is fine, there is no need for a solution.

**Comment by tupui** [comment]
Ok I have a solution. I will send a PR for the theme. We need to define an empty value for `data-active-version-name` (and from what I see in examples, we should have done this in the first place). So with the last commit, I adapted the logic so that it will work when the theme updates.

**Comment by tupui** [comment]
@MarsBarLee did you get a chance to look at this?

**Comment by seberg** [comment]
I don't really have an opinion on the colors or if they are an improvement here, but should we just roll with this and get it in quickly?

**Comment by tupui** [comment]
IMHO this is ready as it is since the colours are coming from a Nature article and are supposed to be inclusive.

**Comment by seberg** [comment]
Thanks Pamphile, sounds like its time to just go with it.

**Comment by tupui** [comment]
Thank you Sebastian 😃

**Pull request merged**
