### PR TITLE
CI: rearrange Azure build jobs

### PR DESCRIPTION
**Pull request by mattip**
related to #18312. Don't lead with a flaky build job.

### CODE REVIEW

**Comment by seberg** [comment]
Thanks, seems good. This makes the initial check a "full" test run (instead of fast), but maybe it doesn't matter.

**Comment by mattip** [comment]
It is still the [fastest Azure job](https://dev.azure.com/numpy/numpy/_build/results?buildId=15243&view=logs&jobId=40b6d036-694f-5d1f-586c-a0e1fd689e6f&j=40b6d036-694f-5d1f-586c-a0e1fd689e6f). Maybe we should be looking at caching the 32-bit build tools, which take ~5 minutes to install per job.

**Comment by seberg** [comment]
Oh wow, lets just put it in. Thanks Matti!

**Comment by mattip** [comment]
I haven't seen [this compiler failure](https://github.com/mattip/numpy/runs/1823488257?check_suite_focus=true#step:4:3108) before:
```
during IPA pass: profile
numpy/core/src/multiarray/einsum_sumprod.c.src: In function ‘longdouble_sum_of_products_contig_three’:
numpy/core/src/multiarray/einsum_sumprod.c.src:1264:1: internal compiler error: in coverage_begin_function, at coverage.c:656
 1264 | }
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
```

But I don't see it here, it all passed. Does github actions rerun automatically?

**Comment by seberg** [comment]
Uhoh, I don't remember ever seeing it either. Thats a strange error, just pointing at the end of the file. Why didn't this cause CI to fail?!

**Pull request merged**
