### PR TITLE
BUG: Fixed default BitGenerator name

### LINKED ISSUE #14206: Wrong capitalization on bitgenerator MT19937
Wrong capitalization of MT19937 in default argument values of functions in numpy.random._pickle.py

### Reproducing code example:

```python
import numpy as np
np.random._pickle.__randomstate_ctor() # => error
np.random._pickle.__randomstate_ctor('mt19937') # => error
np.random._pickle.__randomstate_ctor('MT19937') # => works
```

### Error message:

*** ValueError: mt19937 is not a known BitGenerator module.

### Numpy/Python version information:

1.17.0 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

### PR DESCRIPTION
**Pull request by giuse**
Fixes #14206

### CODE REVIEW

**Review by charris — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @giuse

**Comment by giuse** [comment]
Thanks to you guys! <3

**Comment by charris** [comment]
A test would be welcome. There are already several pickle tests, but they look incomplete.

**Comment by giuse** [comment]
Uhm a test for the default value of three functions? I am relatively new to python, is this a thing?

```python
def run_test(self):
    try:
        np.random._pickle.__generator_ctor()
        np.random._pickle.__bit_generator_ctor()
        np.random._pickle.__randomstate_ctor()
    except ValueError:
        self.fail("Wrong default parameters")
```

I tried to keep my contribution to a minimum and this looks suspiciously boilerplate-y. I will put that in a file in a commit in a pull request in a branch if you think it useful :) if it were up to me I would also have put the default BitGenerator in a constant and have the functions refer to that, but thought "hey it will be asked in the code review if that is the style". Dunno, let me know how you feel I could best contribute.

**Comment by rkern** [comment]
That would be a valid and nominally useful test; it would be called a "smoke test". Obviously, this bit someone once (we wrote code that didn't make sense), so someone coming along later might change things that won't make sense either.

I would say that it would make a better test (a proper unit test) to test the value that comes out, but honestly, we should probably just remove the default values. By construction, all of the pickles should be specifying these constructor functions with complete arguments, so the defaults will never be used. That's why we missed it; everything works even with the wrong default because we never call these functions without arguments.

**Comment by giuse** [comment]
I see. I am used to TDD on smaller project, and committing code that has never run is a big no-no. I can see with the scale of numpy this is hardly applicable, and the value of smoke tests for this application. Thanks for taking your time explaining that to me!

So what would you folks rather have, the test above or removing the default values?

**Comment by mattip** [comment]
The test should go into `numpy/random/tests/test_smoke.py`. I am +0.5 for removing the default argument and testing that calling the function with no argument raises an error with a nice error message (see `TestDefaultRNG.test_seed` for an example of such a test in that file).

I am confused by the related issue: how is openai/gym calling this function with no argument? Is raising an error desired behaviour there?

**Comment by giuse** [comment]
Thanks, then I will go on and paste the test in anyway, since if agreed to change to no-default the file will need to be in place anyway (and it is nice to see a test fail in refactoring :smile: ).

On the related issue: confusion warranted, there is technically no connection :) what happened is that I opened `_pickle.py` while hunting for my problem, saw [this `dict`](https://github.com/numpy/numpy/blob/master/numpy/random/_pickle.py#L9) and thought "uh oh", and yeah few lines below the obvious case mismatch. Submitting such a small patch was a no-brainer.

I played it in my mind about refactoring to use class objects directly, or at least restrict it to a list of class names plus fetching the objects with `globals()` (or better yet `inspect.getmembers(sys.modules[__name__], inspect.isclass)`), but between being super busy ATM and having limited experience on how Python handles these concepts (and yet a few scars already) I picked the safe way :)

**Comment by charris** [comment]
> but honestly, we should probably just remove the default values.

Agree. That seems fragile. Are you suggesting that the pickling code make the value explicit before pickling? We should make the default value public somewhere rather than leave it hiding away in the default_rng function.

**Comment by rkern** [comment]
The pickling code _does_ always make the value explicit. That's why we never encountered these bad default values despite testing pickling. The defaults are never used.

https://github.com/numpy/numpy/blob/master/numpy/random/bit_generator.pyx#L530
https://github.com/numpy/numpy/blob/master/numpy/random/generator.pyx#L127
https://github.com/numpy/numpy/blob/master/numpy/random/mtrand.pyx#L135

**Pull request merged**
