### PR TITLE
BUG: Add 'sparc' to platforms implementing 16 byte reals.

### PR DESCRIPTION
**Pull request by charris**
This is for the _selected_real_kind_func function in
f2py/crackfortran.py. See #12638.

### CODE REVIEW

**Comment by DerDakon** [comment]
Added this to my test build, will take ~1 hour or so.

**Comment by charris** [comment]
@DerDakon I just used 'sparc', I don't think there has been a 32 SPARC in the last 25 years and even before then don't know what precisions were supported.

**Comment by DerDakon** [comment]
I don't think real sparc32 are of any interest anymore…

**Comment by DerDakon** [comment]
Seems to work.

**Comment by charris** [comment]
Thanks for testing. In it goes.

**Pull request merged**
