### PR TITLE
DOC: deduplicate dtype basic types (1)

### LINKED ISSUE #17486: Deduplicate dtype documentation
## Documentation

We still have a fair bit of overlap between these two pages:

* `user/basics.types.rst`: https://numpy.org/devdocs/user/basics.types.html - table of scalar type and type aliases
* `reference/arrays.scalars.rst`: https://numpy.org/devdocs/reference/arrays.scalars.html - autodoc listings of scalar types and type aliases

It's tempting to remove the table on the first page, and tell users to look at the docs on the second.

If nothing else, it would be good to describe to the reader how the pages relate to each other - right now the former links to the latter only via the (currently broken) class names. A "see also" link somewhere would make the connection a little easier to understand.

### PR DESCRIPTION
**Pull request by tech-gian**
Closes gh-17486

https://numpy.org/devdocs/user/basics.types.html

### CODE REVIEW

**Comment by mattip** [comment]
Welcome. It is not easy to be a first-time contributor, there are a lot of moving pieces. You seem to have missed the information presented when you opened the PR. To repeat the important things here: 
- You will find it helpful to read https://numpy.org/doc/stable/dev/index.html. 
- You have submitted a PR off your master branch rather than creating a specific branch as mentioned in step 2. This will make it more difficult to adapt this PR to needed fixes. You can't change this now, but for next time ...
- This is a documentation change, so you may find it quicker to build the docs locally than to wait for CI to complete. That is explained [later in the doc](https://numpy.org/doc/stable/dev/index.html#building-docs). 

I see the build has already failed. I think you need to sign in to CircleCI in order to see the failure, it is this:
```
/home/circleci/repo/doc/source/user/basics.types.rst:98: WARNING: undefined label: \
https://numpy.org/devdocs/reference/arrays.scalars.html#sized-aliases \
(if the link has no caption the label must precede a section header)
```

You might want to read up a bit about [cross-referencing in sphinx](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html?highlight=labels#cross-referencing-documents)

**Comment by tech-gian** [comment]
I'm really sorry for my mistakes. Should I delete this PR and create a new one, while fixing all the things your mentioned?

**Comment by mattip** [comment]
No, the general direction here looks good! Thanks for contributing, it can be daunting at the beginning and there is a lot to learn.

**Comment by tech-gian** [comment]
So now I should wait for accepting or declining this PR now?

**Comment by mattip** [comment]
First thing is to figure out why the sphinx build is not happy and fix it, then try to build locally. Once you are happy with your work, you push a new changeset: 
```
git commit -am"DOC: fix bad link"
git push tech-gian
```

which will trigger a new build

**Comment by melissawm** [comment]
Hello, @tech-gian , do you need help to continue with this?

**Comment by tech-gian** [comment]
Hello @melissawm . The truth is that I need some kind of help. I can't figure out is the problem with my commits.

I also think the basic idea about the fix to the issue is correct. Please tell me your opinion.

**Comment by melissawm** [comment]
I could be wrong but I'm pretty sure the build worked fine but something went wrong because you did the changes in the `master` branch. Not sure if now that we've renamed it to `main` it would work.

**Comment by tech-gian** [comment]
So, what should I do? Should I make the pull request to some other branch from tech-gian/numpy:master? Should I change something on my code? Or something else?

**Comment by charris** [comment]
You might try updating your local branch, see bottom of https://docs.github.com/en/github/administering-a-repository/renaming-a-branch .

**Comment by tech-gian** [comment]
So, I have to rename my local branch (and get my commits into the new one) and then create a new PR to the `master` branch
 from my local branch?
PS: Sorry to ask so many details, but it's one of my first PR in open-source projects and I'm still trying to understand the whole process.

**Comment by charris** [comment]
You probably want to rename your repo branch to main on github also. Pull requests should not be made from the main branch, you can make a new branch for that starting in the main branch by
```
git reset HEAD~3  # because three commits
git checkout -b <new branch>
git commit <your changed files>
git push origin HEAD
```
and make a new PR. You will also want to `git push -f origin main` to clean up your repo.

**Pull request closed without merging**
