### PR TITLE
DOC: Update Copyright to 2022 [License]

### PR DESCRIPTION
**Pull request by rajaeinet**
Update NumPy Copyright to 2022
Changed files:
- `LICENSE.txt`
- `doc/source/conf.py`

Happy new year :)

### CODE REVIEW

**Comment by charris** [comment]
LGTM, but I notice we have two copyright holders, "The NumPy community" and "NumPy Developers". Do we have a good idea what those terms mean? From a legal standpoint some clarification might be useful. @rgommers Thoughts?

**Comment by rgommers** [comment]
Good point, let's use "developers" in both places. Community is broader; you need to actually have written the code/docs for copyright.

**Comment by rajaeinet** [comment]
> Good point, let's use "developers" in both places. Community is broader;

I changed it in my second commit.

**Review by charris — APPROVED** [review]

**Comment by charris** [comment]
Thanks @rajaeinet .

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @rajaeinet! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute/. 
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion.

**Pull request merged**
