### PR TITLE
API: Update `lib.stride_tricks` namespace

### PR DESCRIPTION
**Pull request by mtsokol**
Relevant issue https://github.com/numpy/numpy/issues/24507

Hi @rgommers @ngoldbaum,

This PR moves `lib.stride_tricks` module to a private file and ensures that it's public methods are only available through the main or local namespaces. For local namespace there are `as_strided` and `sliding_window_view` functions.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I see `DummyArray` is included in the public `stride_tricks` namespace as well. Searching, it does seem to have some downstream usage. However, its implementation is literally:

```
class DummyArray:
    """Dummy object that just exists to hang __array_interface__ dictionaries                                                                                         
    and possibly keep alive a reference to a base array.                                                                                                              
    """

    def __init__(self, interface, base=None):
        self.__array_interface__ = interface
        self.base = base
```

So IMO, we should make it private and add a note to the migration guide that downstream projects who need it should just copy/paste it into their source tree. There's no need to expand the docstrings or make public something so trivial to implement.

**Comment by mtsokol** [comment]
> So IMO, we should make it private and add a note to the migration guide that downstream projects who need it should just copy/paste it into their source tree. There's no need to expand the docstrings or make public something so trivial to implement.

That makes sense to me. In the github search engine it shows only 13 hits, so I removed it from the public `np.lib.stride_tricks` namespace.

**Review by ngoldbaum — APPROVED** [review]
LGTM, are there any downstream usages that need to get resolved before this can be merged?

**Comment by rgommers** [comment]
> Ah yeah, it does look like there are quite a few [downstream usages](https://github.com/search?q=np.lib.stride_tricks).

That link doesn't show me anything. The `numpy.lib.stride_tricks` namespace is still present after this PR gets merged. Can you elaborate?

**Comment by ngoldbaum** [comment]
> That link doesn't show me anything. The numpy.lib.stride_tricks namespace is still present after this PR gets merged. Can you elaborate?

Oops, sorry, you're right, they're all usages of `as_strided` and `sliding_window_view`, never mind.

**Comment by ngoldbaum** [comment]
OK, in that case, in it goes.

**Pull request merged**
