### PR TITLE
MAINT: Rebuild lapack lite

### PR DESCRIPTION
**Pull request by eric-wieser**
<s>This (the first four commits) is based on top of #8377, which makes it possible to run this script at all.</s> (rebased now that those are merged)

This will give a baseline to compare #8376 against. This does not produce the same output as what is committed, sadly. There are a number of possible reasons for this:

* The script is non-deterministic, and depends on something like dictionary ordering
* The original used a patched version of `f2c`, but that patch was not recorded, and patching `f2c` as part of the build process is a lot of effort just to squelch some warnings
* The version of lapack originally transpiled is not the one it says it is

### CODE REVIEW

**Comment by eric-wieser** [comment]
Hmm, those tests were cancelled for some reason

**Comment by eric-wieser** [comment]
@pv @ovillellas: Don't suppose you remember how you built these files in c679f7b91c6bb49603aec432b7a92879e8818437?

Seems that somehow `blas_lite.c` originally did not contain a definition for `xerbla_`, but now it does (which causes the CI failure). Was this function manually removed from `blas_lite`?

**Comment by eric-wieser** [comment]
This latest build strips out `cgelsd`, `clals0`, `clalsa`, `clalsd`, `sgelsd`, `slals0`, `slalsa`, and `slalsd` - none of which are used.

**Comment by eric-wieser** [comment]
> Seems that somehow blas_lite.c originally did not contain a definition for xerbla_, but now it does 

Nope, someone had manually added an `#if 0`. Fixed in 0a4c136.

**Comment by eric-wieser** [comment]
Awesome, that actually worked! Ready for review, I think.

**Comment by rgommers** [comment]
The last paragraphy of README says:

    A slightly-patched ``f2c`` was used to add parentheses around ``||`` expressions
    and the arguments to ``<<`` to silence gcc warnings. Edit
    the ``src/output.c`` in the ``f2c`` source to do this.

The diff in this PR doesn't have these additional parentheses.

**Comment by rgommers** [comment]
It would also be useful to add some instructions to README on how to test ``lapack_lite``. In our CI setup it's not tested at all I believe.

**Comment by eric-wieser** [comment]
> The diff in this PR doesn't have these additional parentheses.

Correct. Manually obtaining the f2c source, patching without instruction, and rebuilding seems like a lot of busywork to fix unimportant warnings.

**Comment by eric-wieser** [comment]
Are you content for me to just remove these lines from the README?

**Comment by eric-wieser** [comment]
> It would also be useful to add some instructions to README on how to test [it]

There's nothing really to say here. You test the generated files by building the generated files, then running the numpy test suite.

**Comment by charris** [comment]
What is the motivation for this, what does it fix/add?

**Comment by eric-wieser** [comment]
The motivation is that provides a bisection point when upgrading to a newer version of lapack, which is required to fix a problem mentioned in an issue I think I linked above.

Otherwise, it becomes hard to distinguish "this version doesn't work" from "these build tools do bot work.

**Comment by eric-wieser** [comment]
Will refund the link when bot on mobile

**Comment by eric-wieser** [comment]
@charris: The underlying issue requiring an upgrade of lapack-lite is [discussed here](https://github.com/numpy/numpy/pull/8369#discussion_r93036961)

**Comment by charris** [comment]
@eric-wieser  The way to test this is to force a build that uses lapack_lite. For instance
```
BLAS=None LAPACK=None ATLAS=None python setup.py build
```
will not use any system libraries.

**Comment by eric-wieser** [comment]
@charris: This is already tested by appveyor, I believe. (Since it failed until I got it right)

**Comment by charris** [comment]
You should be able to define those variables in the `env` in a (new) travis test.

**Comment by eric-wieser** [comment]
But adding it explicitly to travis seems like a good idea anyway, so I'll do that too

**Comment by charris** [comment]
Yep, better done on purpose than by accident.

**Comment by eric-wieser** [comment]
@charris: Alright, done and passing

**Comment by charris** [comment]
Let's get this underway. Thanks Eric.

**Comment by charris** [comment]
About stripping out `cgelsd, clals0, clalsa, clalsd, sgelsd, slals0, slalsa`, and `slalsd`, I note that `dgelsd` is present and presumably used, although `zgelsd` is missing. Since in most cases both single and double are now supported -- originally just double -- it may be that the single versions are missing through oversight and in the new version you may want to keep all of those.

**Comment by eric-wieser** [comment]
`zgelsd` is used in `np.linalg`, so I'd sure hope it's not missing!

**Comment by charris** [comment]
Right, I looked in the wrong place. However,  `*geqrf` appears in both single and double precision, so I think the intent was that all included lapack routines should be available in both single and double versions. I'm really suspecting the fact that the single version of `*gelsd` did not use the single version was an oversight. Note that those functions were included previously.

**Comment by charris** [comment]
Note that rebuilding and (possibly) stripping out functions should really have been two separate PR.

**Comment by eric-wieser** [comment]
Right - the reason the PR is the way it is is that I built it as it was, then added functions until I stopped getting errors. Perhaps I should have grepped the source code for function prototypes, but I think then I'd end up listing subroutines I didn't care about

**Comment by charris** [comment]
Well, least squares works for single, but I'll bet it is now computing in double. Note that the addition of single functionality is fairly new, so something may have been easily overlooked.

**Comment by eric-wieser** [comment]
Assuming we're talking about the python code, the only decision it uses to pick between the functions is `isComplex`. Unless there's some type-specific dispatch somewhere that I haven't seen

**Comment by charris** [comment]
The generalized ufuncs are defined in `umath_linalg.c.src`, and indeed the single versions of least squares are not included, but most everything else has both single and double versions. That may have been intentional for accuracy reasons, but maybe not. @pv Do you recall if this was an error or a deliberate decision.

**Comment by eric-wieser** [comment]
Right, that jogs my memory - I only kept the functions that had prototypes declared in `umath_linalg`, since the others didn't seem to be exposed anyway

**Comment by charris** [comment]
Hmm, OK, `lstsq` is not defined as a generalize ufunc in any case (see end of file) so the logic is probably in the python code and may well not allow for single.

**Comment by charris** [comment]
So we aren't missing anything ... yet. As to how easy it is, I'll take your word for it :)

**Pull request merged**
