### PR TITLE
MAINT: fix exception chaining in format.py

### PR DESCRIPTION
**Pull request by devhpes**
Changes related to #15986 

Added chaining for UnicodeError in format.py

### CODE REVIEW

**Comment by mattip** [comment]
Can you show the output of the new code? Does adding the original error position help the user or does it clutter stdout?

**Review by eric-wieser — APPROVED** [review]
This looks better than it was, even if the error is a bit weird.

@mattip, remember that these changes don't affect the amount of stdout, they just change "while handling..." to "caused by ..."

**Comment by mattip** [comment]
Thanks @devhpes

**Comment by devhpes** [comment]
thanks @eric-wieser  and @mattip

**Pull request merged**
