### PR TITLE
formatting: comply with pep8

### PR DESCRIPTION
**Pull request by ghost**
This PR only includes whitespace changes.

### CODE REVIEW

**Comment by charris** [comment]
Nope, we don't do all of that. We put spaces around some binary operators, but not all, and that is valid PEP8. Nor are we very strict in tests, many of which are easier to understand when not strictly PEP8. There are some easy fixes that we will accept, line spacing between functions and classes for instance, but you can't just run a fixer over the files, it takes more work than that. You might have expected as much given the number of files changed.

I use use the following configuration for pep8
```
charris@fc [~]$ cat .config/pep8
[pep8]
max_line_length=79
statistics = True
ignore = E121,E122,E123,E125,E126,E127,E128,E226,E231,E265,E501,E712,W291,W293,W391,E241,E201
```
If you want to submit something less ambitious, go ahead.

**Comment by xoviat** [comment]
This was an attempt to remove whitespace changes from #9431. Would it be okay if the changes were restricted to distutils only?

**Comment by charris** [comment]
Depends on what the fixes are. Just running pep8 will do lots of things we don't care about.

**Comment by charris** [comment]
If you are looking for some janitorial sort of things, to do we are going to eliminate yield based test. Some of those fixes should be pretty easy, just replacing the yield with a straightforward function call.

**Comment by xoviat** [comment]
I am not looking for janitorial things to do. Everything that I work on is run through autopep8 so that I don't have to think about formatting, which saves test failures that occurs when flake8 is run on CI on other projects. However, this creates larger diffs that people complain about when submitting PRs to projects that do not comply with PEP8. It's quite a pain compared to go's formatter and makes me wish that the Python style guides would be even stricter than they currently are.

**Comment by njsmith** [comment]
@xoviat: You might find using `pep8radius` to reign in your `autopep8` produces less friction.

**Pull request closed without merging**
