### PR TITLE
BUG: Fixes to numpy.distutils.Configuration.get_version

### PR DESCRIPTION
**Pull request by eric-wieser**
This [emitted a ResourceWarning](https://travis-ci.org/numpy/numpy/jobs/499665501#L2687) as previously written, as the streams never got closed.

This change also detects errors in `svnversion` and `hg`, rather than ignoring the error code and hoping stdout contains a revision anyway.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Wow, this exposes a nasty bug in `numpy.disutils` on all versions of python 3 - the regexes here fail with:
```
TypeError: cannot use a string pattern on a bytes-like object
```

It looks like we might need a broader sweep to remove `except Exception` from our code.

**Comment by eric-wieser** [comment]
Hey look, it also has always failed on windows:
```python
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```

**Comment by eric-wieser** [comment]
Squashed to ease backporting, I assume?

**Comment by charris** [comment]
That, and having a single commit that passes tests is nice. Git cherry-pick can take a range of commits as input, but single commits are still a bit nicer.

**Comment by charris** [comment]
@eric-wieser  Hmm, your recent commits have unbroken lines in the commit summaries, they need hard line breaks. Maybe an editor setting for commit messages?

**Pull request merged**
