### PR TITLE
ENH: add an axis argument to np.bincount

### PR DESCRIPTION
**Pull request by jaimefrio**
This adds an `axis` argument to `np.bincount`, which can now take multidimensional
arrays and do the counting over an arbitrary number of axes. `axis` defaults
to `None`, which does the counting over all the axes, i.e. over the flattened
array.

The shape of the output is computed by removing from `list` (the input array)
all dimensions in `axis`, and appending a dimension of length
`max(max(list) + 1, minlength)` to the end. `out[..., n]` will hold the number
of occurrences of `n` at the given position over the selected axes.

If a `weights` argument is provided, its shape is broadcasted with `list`
before removing the axes. In this case, `axis` refers to the axes of `list`
_before_ broadcasting, and `out[..., n]` will hold the sum of `weights` over
the selected axes, at all positions where `list` takes the value `n`.

The general case is handled with nested iterators, but shortcuts without
having to set up an iterator are provided for 1D cases, with no performance
loss against the previous version.

As a plus, this PR also solves #823, by providing specialized functions for
all integer types to find the max. There are also specialized functions for
all integer types for counting and doing weighted counting.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Just as cheerleader for this since another issue reminded me of it:

statsmodels would have quite a lot of use for a vectorized version of bincount. I always missed that.
I never hit the "send" button for my reply almost a year ago. The main questions were about broadcasting which I don't know whether they are still relevant.
In any case, I and we can adjust to whatever the pattern numpy has now for partial reduction, and we will use any vectorized version if it's more efficient than the plain loops.

**Comment by jaimefrio** [comment]
I am closing this for now. There are several functions out there that could use an axis argument, and `bincount` is one of them. But rather than bloating them all with code, the proper approach seems to me to build some intermediate layer over `nditer` that abstracts the complexity away. It would probably make for a nice GSoC project...

**Comment by rgommers** [comment]
@jaimefrio you could still consider the suggestion of @charris to do this in a for-loop in Python. That would keep the code simple, and non-optimal speed for something that doesn't work at all now is OK:) Reason to do that: the intermediate layer might take a long time to materialize, and this does look useful.....

**Comment by mhvk** [comment]
The mailing list conversation reminded me: the multidimensional weight, single-dimension index case of this was something I was very much looking forward to. I can see why this was closed, but it would still be really great to have...

**Comment by eric-wieser** [comment]
Relevant to #5197

**Comment by mhvk** [comment]
Would still be great to have this -- @eric-wieser - `np.bincount` is very fast; we'd have to be very careful about performance before thinking of moving this to a `gufunc` (I analyze GBs of baseband data with it, so I care...).

**Comment by eric-wieser** [comment]
I would hope that the cost of a `gufunc` would only be a small constant, whereas it sounds like you're using it on large inputs anyway?

**Comment by mhvk** [comment]
True, I just worry about the iterator not being optimized as much, but with a good inner loop I guess it should be fine.

**Comment by eric-wieser** [comment]
> I just worry about the iterator not being optimized as much,

As much as what? Obviously iterating over something takes more time than assuming it has length 1...

**Pull request closed without merging**
