### PR TITLE
API: Add `NumpyUnpickler` for backporting

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @charris @ngoldbaum,

This PR contains `NumpyUnpickler` for 1.26 that should be backported. 
(The original PR should be merged later as that one will go into 2.0)

### CODE REVIEW

**Comment by charris** [comment]
@mtsokol Did you intend to make this against the main branch?

**Comment by mtsokol** [comment]
I'm not familiar with backporting yet 😅 - I should just make it against `maintenance/1.26.x` right?

**Comment by mtsokol** [comment]
@charris I think now I should be set up correctly.

**Comment by charris** [comment]
Thanks @mtsokol .

**Pull request merged**
