### PR TITLE
MAINT: setuptools 49.2.0 emits a warning, avoid it

### PR DESCRIPTION
**Pull request by mattip**
[setuptools 49.2.0, released today](https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v4920), will now emit a warning if distutils is imported before setuptools. This affects the test_api tests, so pre-emtively import setuptools.

### CODE REVIEW

**Comment by charris** [comment]
Hmm, didn't fix the problem. maybe import in the test?

**Comment by mattip** [comment]
This time I tested before pushing (a unique idea, I should do it more often). I hope it has a better chance of passing. I also noticed some small C warnings about "warning: function declaration isn't a prototype" so added a `void` argument to fix those too.

**Comment by charris** [comment]
Travis is hopelessly lagged, so just going to put this in since azure passes. Thanks Matti.

**Comment by charris** [comment]
I still see this that happens during pytest collection
```
charris@fc [numpy.git (master)]$ python runtests.py -t numpy/tests -- --collect-only
Building, see build.log...
Build OK
/home/charris/.local/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
```
Could be in pytest, or maybe pytest is importing some files during collection.

**Comment by charris** [comment]
Fixed in #16828.

**Pull request merged**
