### PR TITLE
BUG: Clear errors correctly in F2PY conversions

### LINKED ISSUE #20400: BUG: numpy/1.21.4, python3.10-dbg Aborted when running f2py/tests/test_return_integer.py::TestF77ReturnInteger::test_all[t0]
### Describe the issue:

Hello, while preparing numpy 1.21.4 for the newly uploaded to Debian python 3.10.0 interpreted, one of the tests caused the dbg flavor interpreter to crash

### Reproduce the code example:

```python
root@zion:/build/numpy-1.21.4/debian# PYTHONPATH=/build/numpy-1.21.4/debian/tmp/usr/lib/python3/dist-packages/ python3.10-dbg -m pytest tmp/usr/lib/python3/dist-packages/numpy/f2py/tests/test_return_integer.py -vvv
/usr/lib/python3/dist-packages/hypothesis/entry_points.py:32: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  yield from importlib_metadata.entry_points().get("hypothesis", [])
============================================================================================================================= test session starts ==============================================================================================================================
platform linux -- Python 3.10.0+, pytest-6.2.5, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3.10-dbg
cachedir: .pytest_cache
hypothesis profile 'np.test() profile' -> database=None, deadline=None, print_blob=True, derandomize=True, suppress_health_check=[HealthCheck.data_too_large, HealthCheck.filter_too_much, HealthCheck.too_slow, HealthCheck.return_value, HealthCheck.large_base_example, HealthCheck.not_a_test_method]
rootdir: /build/numpy-1.21.4, configfile: pytest.ini
plugins: hypothesis-5.43.3
collected 20 items                                                                                                                                                                                                                                                             

tmp/usr/lib/python3/dist-packages/numpy/f2py/tests/test_return_integer.py::TestF77ReturnInteger::test_all[t0] Aborted
```


### Error message:

```shell
i have a gdb session traceback which i'll post after submit (as it's quite long)
```


### NumPy/Python version information:

1.21.4

### PR DESCRIPTION
**Pull request by HaoZeke**
Closes #20400.

Thanks @seberg!

### CODE REVIEW

**Comment by charris** [comment]
Note to self, also needs backport to 1.21.5.

**Comment by charris** [comment]
Thanks @HaoZeke .

**Comment by charris** [comment]
Can you think of a way to test this?

**Comment by seberg** [comment]
Not sure that complex path is covered, otherwise, I think we are basically testing it in debug mode, just it seems only with 3.10

**Pull request merged**
