### PR TITLE
BUG: Make system_info output reproducible

### PR DESCRIPTION
**Pull request by lamby**
Whilst working on the Reproducible Builds effort [0], we noticed
that python-numpy generates output that is not reproducible. This
affects "downstream" packages such as numexpr.

This occurs as it encodes the absolute pathname into the generated file.

 [0] https://reproducible-builds.org/

Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

### CODE REVIEW

**Comment by njsmith** [comment]
Seems reasonable to me. 

Maybe we should add the string "numpy" to the file somewhere, so if people see "generated by misc_util.py" then they have some clue which project to look for this in?

**Comment by lamby** [comment]
@njsmith wrote:

> Maybe we should add the string "numpy" to the file somewhere

Good idea. Pushed an updated commit.

**Comment by charris** [comment]
Note changed PR title. We like to have certain prefixes on the commit message, see the list at `doc/source/dev/gitwash/development_workflow.rst`.

**Comment by lamby** [comment]
Thanks!

**Pull request merged**
