### PR TITLE
 DOC: Update a page title with proper case

### LINKED ISSUE #16261: DOC: Mixed capitalization styles in page titles
Page titles in the docs use both 
- `sentence case` [("How to contribute to the NumPy documentation")](https://numpy.org/devdocs/dev/howto-docs.html), where only the first word is capitalized, and 
- `title case` [("Releasing a Version")](https://numpy.org/devdocs/dev/releasing.html), which capitalizes principal words (omitting "a", "of", "the", etc.)

Mixing styles makes the docs seem disorganized; a uniform style would give a better impression.

I vote that we converge on sentence case, which is contemporary usage almost everywhere, and I volunteer to go through our pages and PR the needed changes.

### PR DESCRIPTION
**Pull request by misalraj**
fixes #16261

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Looks good to me, thanks @misalraj

**Comment by rgommers** [comment]
I'll merge this, since it fixes one issue. Thanks @misalraj. I will reopen the issue, since there is more to do there.

**Comment by misalraj** [comment]
Sure, I will check for a more similar type of issues.

**Comment by codeguru42** [comment]
I am looking into this. I assume that proper names should remain capitalized when they appear in the middle of a title. However, what qualifies as a "proper name"? Some examples:

* distutils
* python
* scipy
* numpy

And in the case of "scipy" and "numpy" what is the captialization? Is it "scipy", "Scipy", or "SciPy"? And similarly for "numpy".

**Comment by rkern** [comment]
It depends on the project's choices, but often the project itself will be capitalized while the package/module name (or other artifact) will be lower-case. When referring to the project in general, use its preferred capitalization (which might match the package name!). When referring to the package/module itself, use the exact identifier as it would be in an `import` statement, and use code formatting.

When referring to the `distutils` package itself, use `distutils` (with the code formatting, too); it doesn't really have a separate project anymore, so `distutils` is the thing you should call it.

The Python language is "Python", but the `python` executable is `python`.

The preferred forms for the NumPy and SciPy projects are just those, but when you are referring to the packages themselves, they are `numpy` and `scipy`.

**Pull request merged**
