### PR TITLE
DOC: fix typo in savetxt docstring (closes #7620)

### LINKED ISSUE #7620: Typo in documentation of savetxt
This is just a minor typo in the [documentation](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.savetxt.html) explaining how to specify the output format for savetxt in the case of complex numbers

> a full string specifying every real and imaginary part, e.g.
‘ %.4e %+.4j %.4e %+.4j %.4e %+.4j’ for 3 columns

should be

> a full string specifying every real and imaginary part, e.g.
‘ %.4e %+.4ej %.4e %+.4ej %.4e %+.4ej’ for 3 columns

The other format strings on this particular help page are fine, but I haven't checked whether the typo has propagated to other help pages.

### PR DESCRIPTION
**Pull request by bertrand-l**
Just a tiny typo, haven't found it anywhere else in `lib`

### CODE REVIEW

**Comment by charris** [comment]
If you put `[ci skip]` in the commit message for documentation fixes the tests won't be run.

**Comment by charris** [comment]
LGTM.

**Comment by charris** [comment]
Thanks @bertrand-l .

**Comment by bertrand-l** [comment]
Thanks for the merge and the `[ci skip]` tip @charris

**Pull request merged**
