### PR TITLE
BLD: unvendor meson-python on 1.26.x and upgrade to meson-python 0.15

### PR DESCRIPTION
**Pull request by rgommers**
This is a backport of gh-25008. It closes gh-25681.

### CODE REVIEW

**Comment by rgommers** [comment]
The Windows wheel build failures showing ` Invalid --only='""'` are due to an issue with `cibuildwheel` https://github.com/pypa/cibuildwheel/issues/1740. Upgrading to fix that.

**Comment by rgommers** [comment]
The other issue is in the regular `musllinux` job:
```
$ /__w/numpy/numpy/test_env/bin/python -m pytest --rootdir=/__w/numpy/numpy/build-install/usr/lib/python3.10/site-packages -n auto -m 'not slow' numpy
/__w/numpy/numpy/test_env/lib/python3.10/site-packages/_pytest/config/__init__.py:328: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there. (from /__w/numpy/numpy/build-install/usr/lib/python3.10/site-packages/numpy/conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest '/__w/numpy/numpy/build-install/usr/lib/python3.10/site-packages/numpy/conftest.py'.
numpy/__init__.py:135: in <module>
    raise ImportError(msg) from e
E   ImportError: Error importing numpy: you should not try to import numpy from
E           its source directory; please exit the numpy source tree, and relaunch
E           your python interpreter from there.
```

Looks like that is due to a new `pluggy` version (1.4.0, released last week) - yay for transitive dependencies: https://github.com/matplotlib/pytest-mpl/issues/221. It's almost holiday time for me, so I'm inclined to just ignore that for now on `1.26.x`, since it's harmless.

**Comment by charris** [comment]
> since it's harmless.

The wheels look to be built and pass, which is my main concern, but I suspect that is a bit of an accident, perhaps because pytest is pinned to 7.4.0 in test_requirements and those requirements are installed before running the wheel tests. Alternatively, the wheel tests are `-mfast`, while the musl tests are `-m 'not slow'`. 

In any case we may want to look at `numpy/conftest.py`, which has
```
#FIXME when yield tests are gone.
@pytest.hookimpl()
def pytest_itemcollected(item):
```
We still have yield tests. Scipy doesn't have the hook, so that is good.

**Comment by charris** [comment]
Thanks Ralf.

**Pull request merged**
