### PR TITLE
BLD: Upload wheel artifacts separately [wheel build]

### PR DESCRIPTION
**Pull request by lithomas1**

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Thanks @lithomas1!

This seems to work. On macOS:
```
Artifact name is valid!
Container for artifact "cp39-macosx" successfully created. Starting upload of file(s)
Uploaded /Users/runner/work/numpy/numpy/wheelhouse/numpy-1.23.0.dev0+350.g404bd8802-cp39-cp39-macosx_11_0_arm64.whl (66.6%) bytes 0:8388607
Uploaded /Users/runner/work/numpy/numpy/wheelhouse/numpy-1.23.0.dev0+350.g404bd8802-cp39-cp39-macosx_10_9_x86_64.whl (48.1%) bytes 0:8388607
Uploaded /Users/runner/work/numpy/numpy/wheelhouse/numpy-1.23.0.dev0+350.g404bd8802-cp39-cp39-macosx_10_9_x86_64.whl (96.3%) bytes 8388608:16777215
Uploaded /Users/runner/work/numpy/numpy/wheelhouse/numpy-1.23.0.dev0+350.g404bd8802-cp39-cp39-macosx_10_9_x86_64.whl (100.0%) bytes 16777216:17404266
Uploaded /Users/runner/work/numpy/numpy/wheelhouse/numpy-1.23.0.dev0+350.g404bd8802-cp39-cp39-macosx_11_0_arm64.whl (100.0%) bytes 8388608:12591682
Total size of all the files uploaded is 29995950 bytes
File upload process has finished. Finalizing the artifact upload
```

On Windows:
```
Artifact name is valid!
Container for artifact "cp310-win_amd64" successfully created. Starting upload of file(s)
Uploaded D:\a\numpy\numpy\wheelhouse\numpy-1.23.0.dev0+350.g404bd8802-cp310-cp310-win_amd64.whl (57.5%) bytes 0:8388607
Uploaded D:\a\numpy\numpy\wheelhouse\numpy-1.23.0.dev0+350.g404bd8802-cp310-cp310-win_amd64.whl (100.0%) bytes 8388608:14584226
Total size of all the files uploaded is 14584227 bytes
File upload process has finished. Finalizing the artifact upload
Artifact has been finalized. All files have been successfully uploaded!
```

PyPy on Linux:
```
Artifact name is valid!
Container for artifact "pp38-manylinux_x86_64" successfully created. Starting upload of file(s)
Uploaded /home/runner/work/numpy/numpy/wheelhouse/numpy-1.23.0.dev0+350.g404bd8802-pp38-pypy38_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (51.9%) bytes 0:8388607
Uploaded /home/runner/work/numpy/numpy/wheelhouse/numpy-1.23.0.dev0+350.g404bd8802-pp38-pypy38_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (100.0%) bytes 8388608:16148486
Total size of all the files uploaded is 16148487 bytes
File upload process has finished. Finalizing the artifact upload
```

It isn't entirely clear to me what this one line change does exactly though. Can you elaborate? Why is macOS special-cased here?

**Comment by lithomas1** [comment]
Basically, if the artifacts have the same name, they get combined into one zip. By default, the name for uploads is "artifact", so that's why they appear as a huge ~300 MB zip file. 

Since it is a pain(and uses a lot of bandwidth) to download the whole thing, and most of the time you only need a subset of wheels for testing/debugging, I use the job name as the artifact name, which splits everything up.

macos is special cased since it has a "*" symbol in the job name e.g. ``cp38-macosx_*``, which the uploading action doesn't like. 
(It's also slightly different in that the x86_64 and arm64 wheels are in the same zip, since they are produced by the same job.)

**Comment by mattip** [comment]
Ahh, I see. Now there are 14 separate artifacts at the bottom of [the wheel build summary page](https://github.com/numpy/numpy/actions/runs/1661590103), and in the macOS one there are actually two wheels: x86_64 and arm64. The sizes seem to match the wheel sizes [on PyPI](https://pypi.org/project/numpy/#files)

**Comment by mattip** [comment]
Thanks @lithomas1

**Pull request merged**
