### PR TITLE
BUG: Segfault for classes with deceptive __len__

### LINKED ISSUE #7264: Segfault when constructing an array from a "bad" class
```
In [1]: class C:
    def __getitem__(self, i): raise IndexError
    def __len__(self): return 42
   ...: 

In [2]: np.array(C())
Fatal Python error: Segmentation fault
```
A bit contrieved; on the other hand you can imagine hitting an IndexError in some nested function called by `__getitem__` accidentally bubbling up.

EDITED: gdb backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6132bae in PyArray_DTypeFromObjectHelper (obj=obj@entry=<C at remote 0x7ffff66cf898>, maxdims=maxdims@entry=32, out_dtype=out_dtype@entry=0x7fffffffd478, 
    string_type=string_type@entry=0) at numpy/core/src/multiarray/common.c:538
538             if (Py_TYPE(objects[i]) != common_type) {
(gdb) bt
#0  0x00007ffff6132bae in PyArray_DTypeFromObjectHelper (obj=obj@entry=<C at remote 0x7ffff66cf898>, maxdims=maxdims@entry=32, out_dtype=out_dtype@entry=0x7fffffffd478, 
    string_type=string_type@entry=0) at numpy/core/src/multiarray/common.c:538
#1  0x00007ffff6132e63 in PyArray_DTypeFromObject (obj=obj@entry=<C at remote 0x7ffff66cf898>, maxdims=maxdims@entry=32, out_dtype=out_dtype@entry=0x7fffffffd478)
    at numpy/core/src/multiarray/common.c:184
#2  0x00007ffff613c7a5 in PyArray_GetArrayParamsFromObject (op=<C at remote 0x7ffff66cf898>, requested_dtype=<optimized out>, writeable=<optimized out>, 
    out_dtype=0x7fffffffd478, out_ndim=0x7fffffffd46c, out_dims=0x7fffffffd480, out_arr=0x7fffffffd470, context=0x0) at numpy/core/src/multiarray/ctors.c:1560
#3  0x00007ffff613cb7d in PyArray_FromAny (op=op@entry=<C at remote 0x7ffff66cf898>, newtype=0x0, min_depth=0, max_depth=0, flags=flags@entry=112, context=<optimized out>)
    at numpy/core/src/multiarray/ctors.c:1692
#4  0x00007ffff613ceff in PyArray_CheckFromAny (op=<C at remote 0x7ffff66cf898>, descr=<optimized out>, min_depth=min_depth@entry=0, max_depth=max_depth@entry=0, 
    requires=112, context=context@entry=0x0) at numpy/core/src/multiarray/ctors.c:1870
#5  0x00007ffff61c2d25 in _array_fromobject (__NPY_UNUSED_TAGGEDignored=<optimized out>, args=<optimized out>, kws=0x0) at numpy/core/src/multiarray/multiarraymodule.c:1714
#6  0x00007ffff79bcaa9 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#7  0x00007ffff7a34a01 in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#8  0x00007ffff7a35df2 in ?? () from /usr/lib/libpython3.5m.so.1.0
#9  0x00007ffff7a35ed3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
#10 0x00007ffff7a35efb in PyEval_EvalCode () from /usr/lib/libpython3.5m.so.1.0
#11 0x00007ffff7a55074 in ?? () from /usr/lib/libpython3.5m.so.1.0
#12 0x00007ffff7a57585 in PyRun_FileExFlags () from /usr/lib/libpython3.5m.so.1.0
#13 0x00007ffff7a576f6 in PyRun_SimpleFileExFlags () from /usr/lib/libpython3.5m.so.1.0
#14 0x00007ffff7a6e504 in Py_Main () from /usr/lib/libpython3.5m.so.1.0
#15 0x0000000000400af7 in main ()
```

### PR DESCRIPTION
**Pull request by ahaldane**
Fixes #7264

### CODE REVIEW

**Comment by ahaldane** [comment]
Hmm, failues in python2 are fixed by removing the code block a few lines above, which has the comment `/* Not exactly sure what this is about... */` :)  Looking into it...

**Comment by ahaldane** [comment]
OK, I have to leave this for a little bit. 

Here are notes so I remember what I was thinking. The issue is that python2 and python3 give different results. 

The first reason is [this block](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/common.c#L493-L504) marked `/* Not exactly sure what this is about... */`,  which in python2 causes the `C()` from the example in #7264 to count simply as an object type by testing `PyInstance_Check`. In other words, in python2 the sequence checks are completely skipped, and we drop directly to the object array case. I'm not sure there is an equivalent instancecheck in python3, as "old style" classes/instances were removed.

However, if we remove that block at least we now get a `ValueError` in both python3 and python2... but they are different ValueErrors. At first python2 and python3 are similar in that they create an array of `NPY_DOUBLE` (a bit strange itself) in `PyArray_GetArrayParamsFromObject` but they differ when calculating the number of dimensions of this array.

This is caused by yet another call to `PyInstance_Check` in python2, [here](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/ctors.c#L698-L702), which also has a warning `/* FIXME: XXX -- what is the correct thing to do here? */`. In python2 this case is True, so `ndim` gets set to 0. In python3 this is False, so `ndim` gets set to 1 further down during sequence checks. That means that, when trying to assign to the array of doubles, they go down different branches [here](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/ctors.c#L1770-L1783), each giving a different ValueError.

I am tempted to just remove the first block above, and live with the fact that we get different ValueErrors in python2 and python3. However that probably means there is a bug that will turn up when more people convert from python2 to python3.

**Comment by ahaldane** [comment]
Fixed up, should be ready. Is a release note needed?

I decided to remove the code blocks involving `PyInstance_Check` (which only exists in python2). It turns out those were the only two uses in all of numpy! Now python2 and python3 have the same behavior.

This does mean a small change in behavior for python2:
```python
class C:
    def __init__(self):
        pass
    def __getitem__(self, ind):
        if ind in [0,1]:
            return ind
        else:
            raise IndexError()
    def __len__(self):
        return 2

np.array([C()])
```

Old result: 

     array([<__main__.C instance at 0x7fe4ce8eb9e0>], dtype=object)

New result:

     array([[0, 1]])

In words, if a class defines both `__len__` and `__getitem__`, it is now considered a sequence, but it wasn't before.

However, as before, if `__len__` is not defined but `__getitem__` is, you get an object. Apparently some libraries expect that.

**Comment by charris** [comment]
@anntzer How did you discover the error?

I think a note would be appropriate, put it in `1.11-notes`, as we might as well get it fixed and tested. Note that on Python 2.7 the following class also segfaults
``
In [3]: class C(object):
    def __getitem__(self, i): raise IndexError
    def __len__(self): return 42
   ...:     
```

**Comment by anntzer** [comment]
I was trying to figure out what rules numpy uses to decide between creating an object array and trying to iterate over the array and get floats out of that (basically my starting point was #7233), so at some point I basically wrote the same class as you did and saw the segfault.

**Comment by charris** [comment]
Thanks @ahaldane .

**Comment by ahaldane** [comment]
Thanks, and as Post Script note: I updated the final version to remove dead code in `_use_default_type`, and then made sure that we did not lose the detection of 'user-defined' types which the dead code checked for.

**Pull request merged**
