### PR TITLE
BUG: fix for windows

### PR DESCRIPTION
**Pull request by kpsychas**
Related Issue http://stackoverflow.com/questions/33886558/numpy-installation-error-mingw32ccompiler-instance-has-no-attribute-compile-o

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks for tacking this issue @kpsychas. The issue you're running into seems to be caused by you using Mingw32, but ``numpy.distutils.misc_util.mingw32()`` returning False. Correct? 

If so I'd like to fix that as well here. ``mingw32()`` tries to detect whether that compiler is present - the envvars it uses depend on installation method it looks like. Could you tell us how you installed mingw32 and if you can see an easy way to detect it given what's in your ``os.environ``?

**Comment by kpsychas** [comment]
It looks like what you describe is correct. 
What I notice now by inspecting os.environ is that is has the System Variables but I use Anaconda which is in the PATH in User Variables. MinGW is installed under Anaconda environment.

If you need more details let me know. I don't know how helpful that information is.

**Comment by rgommers** [comment]
Thanks. I can see the same issue for the numpy-vendor setup now (``mingw()`` returns False there). It hasn't been an issue only because ``/GL`` doesn't exist for any compiler prior to Python 3.5 - which Mingw32 doesn't support. 

Only the ``msvc`` and ``bcpp`` compilers in distutils have a ``compile_options`` attribute - horrible design as usual. Hence this PR may also be helpful for other compilers than Mingw32. So I'll merge it, and leave the ``mingw`` issue for a bigger cleanup.

**Comment by rgommers** [comment]
opened a new issue for the ``mingw()`` thing, see gh-6981

**Pull request merged**
