### PR TITLE
WIP, API: Add pad_to for simpler padding if a target size is already known

### PR DESCRIPTION
**Pull request by MathijsdeBoer**
In order to pad an array to a specific target shape, some manual math has to be done to determine where the new values need to end up.
While this may not be as large an issue if the user just wants to append or prepend these values to the array, difficulties may arise when the user wants to grow the array to all sides.
I've written a function that performs the required math and operations to pad arrays to a target size and that should work for many dimensions.

`pad_to` takes an array, and a shape to which to pad to.
It also accepts an append mode which dictates where in the array the new values are added.
In the case of `append_mode=surround` an additional variable, `padding_ratio` determines how many of the values end up before, and how many end up after the original array.
`padding_mode` is passed onto `pad(..., mode=padding_mode, ...)`, as is `**kwargs`, so the user has complete control over the remaining functionality built into `pad`.

I came across the need for a function like this when I was doing some work on preprocessing some data for a machine learning project, when I had to pad some dimensions of my input to match the model's expected input shape.
I ended up not needing this functionality, but I figured it would be worth it for others.

I hope I covered and included everything on the contributing page. 
If I missed anything, let me know.

### CODE REVIEW

**Comment by Czorio** [comment]
I've added the WIP tag to the title.
Turns out that I'm not familiar enough to get the functions to be callable in the unit tests I am writing.
I'll hack away at it, but outside help is always welcome.

**Comment by bashtage** [comment]
This feels too specific to be part of the top-level API. Is there a better location?

**Comment by Czorio** [comment]
I'm not too sure where else it would go?

I am of the opinion that padding to match a target size (my pull request) is about as specific as padding to add a certain number of entries on each side (the currently implemented `np.pad`).

I'll agree that `pad_to_match` might be more specific than nessecary, but I was inspired by the likes of `np.zeros_like` and `np.ones_like`, which are both in the top-level API.

**Comment by bashtage** [comment]
There are probably a lot of things in the top-level namespace that shouldn't really be there, but are effectively unmovable due to backward compat concerns.  

It would probably be best to go to the mailing list to discuss where these should go.  I could imagine something like `numpy.reshaping` which could collect things like this and the `unpad` function that was recently on the mailing list.

**Comment by InessaPawson** [comment]
@MathijsdeBoer Thank you for working on this PR! To move it forward, we recommend getting feedback from the NumPy mailing list.

**Comment by MathijsdeBoer** [comment]
Right, I have discussed this on the mailing lists in the past.
As @bashtage mentioned in an earlier comment, this function would probably fit better in a sub package, which was also a point of discussion in the mailing list at the time, if memory serves.
This other package did not exist yet though, and I am unsure if it does now?

Unfortunately, other obligations got in my way shortly after my last change and, quite honestly, I kind of forgot about this after those obligations cleared up 😿 

I'll have to get reacquainted with your process, but when I'm back at work, I'll see if I can find some time to give this PR another try.

**Comment by charris** [comment]
I'm going to close this for now. The idea seems useful, @MathijsdeBoer feel free to pursue this if you wish.

**Pull request closed without merging**
