### PR TITLE
NEP: move nep 34 to accepted

### PR DESCRIPTION
**Pull request by mattip**
There were no objections on the mailing list, actually no-one responded at all. I will optimistically assume it is because no-one objected.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]

**Comment by WarrenWeckesser** [comment]
Maybe I'm being too much of a stickler, but I'm worried that the email on October 29 (https://mail.python.org/pipermail/numpy-discussion/2019-October/080200.html) doesn't match the style for proposing that a NEP be *accepted* (https://numpy.org/neps/nep-0000.html#how-a-nep-becomes-accepted).  The subject of that email was "NEP 34 - deprecate automatic dtype=object on ragged arrays", and in it you said "I would like to submit NEP 34 ...".  There was no indication in the email that it was the proposal to *accept* the NEP.  For the sake of clarity (and to follow the letter of NEP 0), a better subject would have been something like "Proposal to accept NEP 34: Disallow inferring dtype=object from sequence".  And the body of the email should have had a sentence of the form “If there are no substantive objections within 7 days from this email, then the NEP will be accepted; see NEP 0 for more details.”

If someone didn't follow the links that you provided and wasn't up-to-date on the current status of the NEPS, they could have easily mistaken that email as a request to merge a pull request to *create* the NEP.

**Comment by rgommers** [comment]
Good catch @WarrenWeckesser. Can one of you send a new email with the proposal to accept?

**Comment by WarrenWeckesser** [comment]
@mattip sent a new email on Nov. 16: https://mail.python.org/pipermail/numpy-discussion/2019-November/080242.html

Thanks Matti.

**Comment by mattip** [comment]
The mail was sent a week ago, and there were no objections to accepting the NEP

**Comment by rgommers** [comment]
In it goes, thanks Matti!

**Pull request merged**
