### PR TITLE
BUG: Fix misuse of .names and .fields in various places (backport 14290 to 1.16)

### PR DESCRIPTION
**Pull request by eric-wieser**
Backport of gh-14290. All but the merge commit are exactly the same commit.

Merge commit is needed to pull in the backport of gh-13964, since those did not use a single-commit approach.

### CODE REVIEW

**Comment by charris** [comment]
Looks like 1.16 is missing a later change, or maybe a bad rebase. I don't know that these fixes matter enough to pursue the matter.

**Comment by eric-wieser** [comment]
Looks like the test relied on a later change to produce the malicious dtype. Easy to produce a different way, so trying that out. Won't spend too much time on this.

**Comment by charris** [comment]
The shippable failure can be ignored, it timed out.

**Comment by eric-wieser** [comment]
I think otherwise this is fixed

**Comment by charris** [comment]
Let's give it a shot. Thanks Eric.

**Pull request merged**
