### PR TITLE
WIP: Test latest cibuildwheel

### PR DESCRIPTION
**Pull request by charris**
The latest cibuildwheel failed on the 1.16.x branch for macos pp39 builds, check if it also fails here, and if so we should open an issue upstream.

[wheel build]

### CODE REVIEW

**Comment by charris** [comment]
Apparently, empty commits cannot be used to trigger wheel builds.

**Comment by charris** [comment]
@andyfaff Should empty commits work for wheelbuilds of PRs?

**Comment by charris** [comment]
A manually triggered wheel build looks to work.

**Comment by rgommers** [comment]
Empty commits work, but `[wheel build]` should be on the first line of the commit message.

**Comment by rgommers** [comment]
I think you can declare victory and close this? If there's another hiccup with `tools/openblas_support.py`, let's go ahead and delete that script. We don't need it anymore now that we have OpenBLAS wheels, and I'll be glad to never see that fragile script again.

**Comment by charris** [comment]
The pp39 builds need to be tested. I do that with a PR to enable those builds.

**Comment by mattip** [comment]
> I think you can declare victory and close this? If there's another hiccup with tools/openblas_support.py, let's go ahead and delete that script. We don't need it anymore now that we have OpenBLAS wheels, and I'll be glad to never see that fragile script again.

The `tools/openblas_support.py` script is still used for wheel builds [here](https://github.com/numpy/numpy/blob/b3f09c6787e98e57eff303cbb75c3001dd8b0514/tools/wheels/cibw_before_build.sh#L18) and [here](https://github.com/numpy/numpy/blob/b3f09c6787e98e57eff303cbb75c3001dd8b0514/tools/wheels/cibw_before_build.sh#L42).

**Comment by rgommers** [comment]
> > 
> 
> The `tools/openblas_support.py` script is still used for wheel builds [here](https://github.com/numpy/numpy/blob/b3f09c6787e98e57eff303cbb75c3001dd8b0514/tools/wheels/cibw_before_build.sh#L18) and [here](https://github.com/numpy/numpy/blob/b3f09c6787e98e57eff303cbb75c3001dd8b0514/tools/wheels/cibw_before_build.sh#L42).

Yes I know, otherwise we could delete it today. I meant "do the work so we can delete it" - xref https://github.com/scipy/scipy/issues/19381#issuecomment-1761515617 (I'll comment there now, I have one question).

**Pull request closed without merging**
