### PR TITLE
ENH: Add broadcasting to randint

### PR DESCRIPTION
**Pull request by bashtage**
Continuation of @gfyoung 's initial patch but using a different approach.  This essentially produces a complete random integer generator including arg checks for each type.  The int64/uint64 cases uses a separate path since special handling is required to ensure cast values are in bounds. 

Related PR's and Issues: #6938  #6902 #6745

### CODE REVIEW

**Comment by charris** [comment]
Note that #8717 allows zero size arrays. I haven't checked if this does that, but might be worth consiering.

**Comment by bashtage** [comment]
I saw that - it will be a small fix to this but wanted to make sure it was getting in before incorporating it.

**Comment by bashtage** [comment]
I think this is finished, modulo reviews.  It closes #8717 although I didn't put in the tests for empty choice.

**Comment by bashtage** [comment]
This is currently in randomgen and may make it through there. Not essential here.

**Pull request closed without merging**
