### PR TITLE
BUG, MAINT: Remove overzealous automatic RST link

### PR DESCRIPTION
**Pull request by Carreau**
When adding links to all the NEPs, one non-rst file was taken in the
crossfire.

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
Nice catch, thanks @Carreau !

**Comment by charris** [comment]
There are two `nep-0016-*` files and benchmark one doesn't conform to the template. There is something deeper wrong here. Both came in with #12174, I wonder if it was a mistake?

**Comment by charris** [comment]
OK, the `nep-0016-benchmark.py` was an attachment to `nep-0016-abstract-array.rst`
```
.. literalinclude:: nep-0016-benchmark.py
```
See it rendered at https://numpy.org/neps/nep-0016-abstract-array.html . I suggest that we simply move the script into the main NEP

**Comment by Carreau** [comment]
I don't think that has much impact. For it was just the fact that the py file was invalid syntax that make a docstring-formatting tool I'm working on choke on that.

**Comment by charris** [comment]
> I don't think that has much impact.

Just that it is confusing to have two `nep-0016*` files, one of which is `*.py`. It is easy enough to copy the benchmark code from the docs if needed.

**Comment by charris** [comment]
Thanks @Carreau .

**Pull request merged**
