### PR TITLE
 DOC: Change license date 2020 -> 2021

### PR DESCRIPTION
**Pull request by dmontesl**
A very small contribution to update the license date from 2020 to 2021 :)

### CODE REVIEW

**Comment by mattip** [comment]
There is one more in the copyright notice in `doc/source/conf.py`

**Review by mattip — APPROVED** [review]
LGTM

**Comment by seberg** [comment]
Interesting, the travis CI here also failed with the 16 byte alignment error I saw on my PR https://travis-ci.com/github/numpy/numpy/jobs/480993160#L4095

```
  numpy/core/src/multiarray/_multiarray_tests.c.src: In function ‘call_npy_cargl’:
4095  numpy/core/src/multiarray/_multiarray_tests.c.src:2000:9: note: the ABI of passing aggregates with 16-byte alignment has changed in GCC 5
4096           npy_@name@@suffix@(*(@itype@*)PyArray_DATA((PyArrayObject *)z_arr));
4097           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4098
```
obviously unrelated, but does anyone know what this is?

**Comment by charris** [comment]
That question was answered before, apparently it means that compiled code is not binary compatible between gcc 5 and gcc 4.

**Comment by seberg** [comment]
Oh, had not seen that. Makes sense, so we just don't worry about it and ignore these warnings when they crop up?

**Comment by charris** [comment]
Found the explanation at https://github.com/numpy/numpy/issues/18220#issuecomment-767015694

**Comment by seberg** [comment]
Thanks @Aerysv. And thanks Chuck, sorry for missing that.

gh-18349 should fix the circleci failure, no need to wait for this here though I think.

**Pull request merged**
