### PR TITLE
ENH: searchsorted API like pandas

### PR DESCRIPTION
**Pull request by FranzForstmayr**
This PR addresses #16965 and renames the arguments of `searchsorted`. 
The usage is not affected, as the replaced arguments `a` and `v` are included as kwargs, which was suggested in the issue.

The parameter names `array` and `value` are taken from pandas and are more clear than `a` and `v`.

### CODE REVIEW

**Comment by charris** [comment]
Changing argument names breaks backwards compatibility, so we don't do it. This also changes positional arguments into keyword arguments.

**Comment by bashtage** [comment]
Basically, you are suggesting deprecating `a` and `v` in favor of their more verbose names.  While I personally think this is reasonable, the long-standing practice is to leave these types of things alone except in extreme circumstances, such as when keywords are incorrectly spelled.

**Comment by bashtage** [comment]
Basically, you are suggesting deprecating `a` and `v` in favor of their more verbose names.  While I personally think this is reasonable, the long-standing practice is to leave these types of things alone except in extreme circumstances, such as when keywords are incorrectly spelled.


In pandas-speak, you want

```python
@deprecate_kwarg(old_arg_name='a', new_arg_name='array')
@deprecate_kwarg(old_arg_name='v', new_arg_name='value')
def searchsorted(array, value, ...)
    ...
```

**Comment by FranzForstmayr** [comment]
Yes exactly, this was already discussed in #16965. 
I was not aware of this pandas utils, in this case `deprecate_nonkeyword_argument` would be appropriate.

**Comment by bashtage** [comment]
> I was not aware of this pandas utils, in this case `deprecate_nonkeyword_argument` would be appropriate.

I think NumPy has their own decorator for similar changes.  The point of the pandas or similar decorators is that they do not complain about positional use, and only let users know if they are accessing these arguments using keywords that are changing.

**Comment by FranzForstmayr** [comment]
Sorry for the delay, but I was not sure, if the numpy team wants those changes. The PR creates keyword arguments from positional arguments, however this would maintain backward compatibility. 
If there's any need for updating this PR let me know.

**Comment by mattip** [comment]
I will close this based on the principle that we don't want to merge backward-incompatible changes without a deprecation cycle and approval from the mailing list. Thanks @FranzForstmayr for the PR, but I don't think this change warrants that effort. Hopefully the Array API will get this right the first time around, and someday we can do a NumPy 2.0 based on the Array API.

**Pull request closed without merging**
