### PR TITLE
DOC: Add example for np.ma.compressed.

### PR DESCRIPTION
**Pull request by stefmolin**
Add example for np.ma.compressed as part of https://github.com/numpy/numpy/issues/22269

### CODE REVIEW

**Comment by mattip** [comment]
I am curious if you tried using integer values in the example. It would seem to me that would convey the point just as well, and the output format would be more consistent and compact.

**Comment by seberg** [comment]
I agree with Matti that this would be a good change.  Make the values "boring" and faster to grasp that they match the previously unmasked values exactly (i.e. they could be 1, 2, 3, 4, 5, ... while the later masked ones could be -1).

**Comment by rgommers** [comment]
@stefmolin friendly ping - are you planning to update this PR or reply to the review comments?

**Comment by stefmolin** [comment]
I've been working toward some deadlines that were for this weekend. I'm nearly finished, so I will be able to push changes today or tomorrow.

**Pull request merged**
