### PR TITLE
STY: Style fixes for .travis.yml and travis-upload-wheel.sh

### PR DESCRIPTION
**Pull request by charris**
- shell script style fixes inspired by google shell style guide
  https://google.github.io/styleguide/shell.xml
- .travis.yml longline breaking tested with
  http://yaml-online-parser.appspot.com/

### CODE REVIEW

**Comment by charris** [comment]
@ogrisel Just a heads up in case the upload breaks.

**Comment by ogrisel** [comment]
@charris I parsed it with the `yaml` module of Python and the escaped line breaks in the `secure` environment variable seem to behave correctly. Although there is no way to test it without merging to master as the upload code is only executed on the master branch.

**Comment by charris** [comment]
@ogrisel Thanks for taking a look. Guess we will have to check the wheels after merge.

**Comment by ogrisel** [comment]
+1

**Comment by charris** [comment]
Let's try the merge then.

**Comment by charris** [comment]
@ogrisel Looks like it still works.

**Comment by ogrisel** [comment]
Great.

**Pull request merged**
