### PR TITLE
DOC: BLD: fix lots of Sphinx warnings/errors.

### PR DESCRIPTION
**Pull request by rgommers**
This is a backport of gh-9238.

### CODE REVIEW

**Comment by charris** [comment]
Thanks Ralf.

**Comment by rgommers** [comment]
@charris how do you push the detached commit that's tagged with ``v1.13.0`` to the repo without making a new branch?

I'd like to also push the actual commit from which I built the docs (which is this PR on top of v.1.13.0)

**Comment by charris** [comment]
@rgommers Not sure what the question is. If you want to reposition the tag after new commits, I think you can delete it (and upstream also) and retag after the new commits.

**Comment by rgommers** [comment]
No I don't want to reposition the tag. What I'm noticing is that the commit that is tagged is not part of any branch, it's a detached head. Normally if you push anything to Github, it has to go to a branch. So I want to understand how you got that commit there. Then I can add a new commit to it with the same method.

**Comment by pv** [comment]
You can push tags and the associated commits without them having to be
attached to a branch, via "git push".

**Comment by charris** [comment]
Note that you will want to reposition the tag so that it points to your new commit before you push it upstream. Hmm, makes me wonder if a force push will rewrite the upstream tag...

**Comment by charris** [comment]
The main difference between tags and branches is that the latter advances as you make commits to the branch, whereas a tag points to a fixed commit.

**Comment by pv** [comment]
Force push will replace the tag afaik.
Github allows turning on a setting that prevents force push to branches, but I don't see something that would make tags protected.

**Comment by njsmith** [comment]
...why isn't `v1.13.0` part of the `maintenance/1.13.x` branch?

**Comment by charris** [comment]
@njsmith What is your question?

**Comment by njsmith** [comment]
@charris: sorry, not sure what's unclear. Ralf is saying that the commit tagged `v1.13.0` isn't on the `maintenance/1.13.x` branch, but my understanding was that generally release commits should be part of their corresponding maintenance branch, so I'm curious what's going on.

**Comment by charris** [comment]
@njsmith A release has release specific stuff that doesn't belong in the maintenance branch. See `doc/RELEASE_WALKTHROUGH.rst.txt` to see how it is done.

**Comment by rgommers** [comment]
> You can push tags and the associated commits without them having to be attached to a branch, via "git push".

Ah that makes sense, thanks.

> Note that you will want to reposition the tag so that it points to your new commit before you push it upstream.

No, now that I understand it, I won't push it (I'll put it on my own fork and link to it from the relevant issue/PRs). The ``v.1.13.0`` tag really should match the published sdist and wheels.

**Pull request merged**
