### PR TITLE
DOC: Improve np.finfo docs

### LINKED ISSUE #6940: DOC: docstring for numpy.finfo.eps is incorrect
The [docstring](https://github.com/numpy/numpy/blob/97c35365beda55c6dead8c50df785eb857f843f0/numpy/core/getlimits.py#L33-L36) for `numpy.finfo` currently defines the `eps` attribute as:

> The smallest representable positive number such that 1.0 + eps != 1.0. [...]

That definition is not correct, at least in the common case of the IEEE 754 binary formats. For example, with the IEEE 754 binary64 format under the usual round-ties-to-even rounding mode, the stated definition gives a value of `2**-53 + 2**-105` (approx. `1.1102230246251568e-16`), which is a little over half of the correct value of `2**-52` (approx `2.220446049250313e-16`).

```
In [36]: eps = 2**-53 + 2**-105

In [37]: eps
Out[37]: 1.1102230246251568e-16

In [38]: 1.0 + eps != 1.0
Out[38]: True

In [39]: 1.0 + np.nextafter(eps, -np.inf) != 1.0
Out[39]: False

In [40]: np.finfo(float).eps
Out[40]: 2.2204460492503131e-16
```

Some possible rewordings:

> The smallest positive number such that 1.0 + eps is representable.

Or:

> The difference between 1.0 and the smallest representable float larger than 1.0.

Or it could be defined in terms of `nextafter` as:

> The value of `np.nextafter(1.0, np.inf) - 1.0`.

For comparison, section 5.2.4.2.2, paragraph 11 of the C99 standard defines the various `*_EPSILON` macros (`DBL_EPSILON`, `FLT_EPSILON`, ...) as:

> the difference between 1 and the least value greater than 1 that is representable in the given floating point type, b<sup>1− p</sup>

The docstring for `epsneg` is similarly incorrect.

### PR DESCRIPTION
**Pull request by rossbar**
Replace inaccurate statements about `eps` and `epsneg` attrs of `np.finfo` with
correct statements and examples.

Added np.spacing and np.nextafter to See Also section.

N.B. - used `:math:` role to enable LaTeX rendering in HTML docs. In my opinion it does not interfere with the readability of the doc string, but happy to remove LaTeX math formatting if it is deemed distracting and/or is against numpy's policy for docstrings.

Closes #6940 by incorporating feedback from @gwhammett, @joferkington, and @mdickinson

### CODE REVIEW

**Comment by charris** [comment]
There is a sphinx plugin that enables the latex `$...$` form for inline math. that might be useful at some point.

**Comment by charris** [comment]
I don't think there is good reason for the math markup here, you can probably just use the double backtick form ``` ``eps = 2**-52`` ```, approximately 2.22e-16. 
`

**Comment by rossbar** [comment]
Thanks for the feedback @charris, I've replaced the LaTeX-formatted math with literal blocks as suggested.

**Comment by charris** [comment]
Thanks Ross. I add some missing periods :)

**Pull request merged**
