### PR TITLE
ENH: Quantile

### PR DESCRIPTION
**Pull request by chunweiyuan**
This is forked off `eric-wieser:quantile` for #9213.  Addresses some of the reviewer comments therein.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Merge made a mess of the release notes

**Comment by charris** [comment]
Should remove the `1.14.0-notes.rst` changes, that is already branched.

**Comment by chunweiyuan** [comment]
Well, I just gave it another shot (10199).  Hopefully better this time.

**Comment by eric-wieser** [comment]
So you know for next time: You didn't need to close this PR - you could have just force-pushed your retry over it

**Pull request closed without merging**
