### PR TITLE
ENH: Allow longdouble probabilities

### LINKED ISSUE #6132: random.choice doesn't allow float128 probs
I think this is due to the `same_kind` casting in numpy 1.10, and I don't know whether this is considered a bug.
```python
>>> import numpy as np
>>> probs = np.array([0.4, 0.4, 0.2], dtype=np.float128)
>>> np.random.choice([1, 2, 3], p=probs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1087, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:11331)
TypeError: Cannot cast array data from dtype('float128') to dtype('float64') according to the rule 'safe'
```

### PR DESCRIPTION
**Pull request by bashtage**
Force cast floating to 64-bit floats to allow 128bit floats

closes #6132

### CODE REVIEW

**Comment by bashtage** [comment]
This was a thought.  A deeper question is should all floating be allowed to be converted to float64. Here I have only applied the change to probability-like values.

**Comment by charris** [comment]
I don't favor this, it is misleading to accept float128 and then not use it. And someday we will want to support quad precision, aarch64 already has it.

**Comment by bashtage** [comment]
I have rewritten this to only forecast longdouble to double, but not float128 generically.

**Comment by eric-wieser** [comment]
I also think this is probably not a good idea. The normal API is rejecting the longdouble input because it would lose precision to downcast it to `double`. Forcing the user to downcast themselves ensures that they are aware their precision is being discarded. I struggle to see an advantage to discarding this information silently; the best I can think of is "the extra precision of long double would give statistically indistinguishable results", but I don't know whether that's actually true.

**Comment by bashtage** [comment]
I am also OK with explicit being better than implicit. Should #6132 be closed as won't fit/by design?

**Comment by eric-wieser** [comment]
My interpretation of #6132 is a feature request to actually perform double-precision calculations when passed a double-precision array.

**Comment by bashtage** [comment]
I can see that.  That would be a large change since we (usually) only get 64 bits per call from the PRNG, and so it would require a substantial rewrite to take advantage of 113 bits of precision in [0,1). It would be less hard with an 80-bit long double since it has 64 bits of precision.

**Comment by bashtage** [comment]
Not quite as bad as I initially thought. Looks like it would mostly require `Generator.random` to support extended precision floats, assuming the rest of the code (which are just NumPy functions) does the right right thing with `longdouble` or `float128` arrays.

**Pull request closed without merging**
