### PR TITLE
CI: fix last docbuild warnings

### PR DESCRIPTION
**Pull request by mattip**
Related to #13114. I am not seeing the warnings locally that I see in the CI run, so maybe updating the image will help?

### CODE REVIEW

**Review by seberg — APPROVED** [review]
No idea if it works (my guess is no), but even if not, we could just update it anyway.

**Comment by mattip** [comment]
Gahh. It turns out the docstrings for Mapping look like
```
D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.
```

The `->` apparently tells sphinx that this is a type hints, and so it tries to look up a type for `D[k] if k in D, else d.  d defaults to None.` which fails, that is obviously not a type.

For this PR I will add new docstrings to `NpzFile.get` and friends, but it would be nice to solve this more systematically. I think the fix should come from CPython, that docstring looks wrong.

**Comment by mattip** [comment]
Marking as ready for review (assuming CI passes) and rebased to run tests since I changed the implementation of `NpyzFile`

**Comment by mattip** [comment]
Closes #13114, whohoo!

**Comment by charris** [comment]
Thanks Matti.

**Pull request merged**
