### PR TITLE
BLD: Make CI pass again with pytest 4.5

### PR DESCRIPTION
**Pull request by eric-wieser**
We need to register `valgrind_error` and `slow` as pytest markers to avoid warnings from pytest >= 4.5.0 that are turned into errors.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
@nicoddemus Is this an expected change requirement for pytest 4.5, which just showed up in our CI?

**Comment by tylerjereddy** [comment]
@charris Notes that this change doesn't get propagated to wheels though.

**Comment by tylerjereddy** [comment]
@charris suggests maybe handling in `_pytesttester.py` might also be helpful if possible?

**Comment by eric-wieser** [comment]
@tylerjereddy: Seems like a good idea, but agreed with people in person that it makes sense as a follow up. Merging this to unblock other CI.

**Pull request merged**
