### PR TITLE
Remove version.py.in, no longer used

### PR DESCRIPTION
**Pull request by sumith1896**
Can somebody have a look at this?
And let me know if there are some guidelines, first time to NumPy

### CODE REVIEW

**Comment by Sumith1896** [comment]
Can somebody have a look at this?
And let me know if there are some guidelines, first time to NumPy

**Comment by argriffing** [comment]
This could be left over from bento.
https://github.com/numpy/numpy/commit/04d225afa2b7b780a735fd95eb557ac3eb66e686

**Comment by Sumith1896** [comment]
Sorry I don't get it.
Do we need this file?

**Comment by argriffing** [comment]
> Sorry I don't get it.
> Do we need this file?

I have no idea what that file is, I was just giving a related link in case someone else knew. @cournape?

**Comment by charris** [comment]
@argriffing good find. I looks to be a bento leftover, and `numpy/__config__.py.in` looks to be another.

@Sumith1896 Bit of patience please. Also, could you amend your commit message to something like
```
MAINT: Remove version.py.in.
```
And then say in the summary portion that the file was used by Bento. For commit messages in general, see `doc/source/dev/gitwash/development_workflow.rst`.

**Comment by Sumith1896** [comment]
@charris I'm really sorry if I came out as impatient,  I didn't mean to be.

Thanks for the doc. I have amended my commit message now/

**Comment by charris** [comment]
OK, thanks @Sumith1896 .

**Comment by Sumith1896** [comment]
Thank you @argriffing @charris for the review.

It was my pleasure.

**Pull request merged**
