### PR TITLE
BUG: Fix small leaks in error path and ``empty_like`` with shape

### PR DESCRIPTION
**Pull request by seberg**
The error path leak I noticed randomly, since we did not have a test for it, otherwise
a leak checker would have noticed it.
The other leak is tricky, because tracemalloc should have notified us about it, but
unfortunately it is public API that you are supposed to `free` that object, so that is
not possible. Thus it was only found with a full valgrind leak-check run, and without
manually narrowing things down and controlling it, that takes 24 hours so I never
bothered it (since I assumed pytest-leaks finds all things).

In any case, these are trivial fixes, the only question would be if someone thinks the test is dangerous...

### CODE REVIEW

**Comment by seberg** [comment]
Aside from some false positives due to Python Unicode decoding (my guess is just a `strcmp` not being suppressed). There are a couple of false positives in the random machinery along the lines of:

```
_______________________________________________________________________________________________________ TestDefaultRNG.test_integers_broadcast[bool_] ________________________________________________________________________________________________________
[VALGRIND LEAK]

Valgrind has detected a memory leak:

**488386** 
**488386** **********************************************************************
**488386** build/testenv/lib/python3.8/site-packages/numpy/random/tests/test_smoke.py::TestDefaultRNG::test_integers_broadcast[bool_]
**488386** **********************************************************************
==488386== 130 (+65) (64 (+32) direct, 66 (+33) indirect) bytes in 2 (+1) blocks are definitely lost in loss record 19,992 of 35,486
==488386==    at 0x483677F: malloc (vg_replace_malloc.c:309)
==488386==    by 0x6A74B10: _buffer_info_new (buffer.c:458)
==488386==    by 0x6A74B10: _buffer_get_info (buffer.c:595)
==488386==    by 0x6A74FEA: array_getbuffer (buffer.c:723)
==488386==    by 0x16FD8A2E: __Pyx__GetBufferAndValidate.constprop.0 (bit_generator.c:14521)
==488386==    by 0x16FDAE6B: __pyx_f_5numpy_6random_13bit_generator_12SeedSequence_mix_entropy (bit_generator.c:5317)
==488386==    by 0x16FED229: __pyx_pf_5numpy_6random_13bit_generator_12SeedSequence___init__ (bit_generator.c:4783)
==488386==    by 0x16FED229: __pyx_pw_5numpy_6random_13bit_generator_12SeedSequence_1__init__ (bit_generator.c:4426)
==488386==    by 0x5A2A42: type_call.lto_priv.0 (typeobject.c:991)
==488386==    by 0x16FE1901: __Pyx_PyObject_Call (bit_generator.c:13065)
==488386==    by 0x16FE1901: __Pyx_PyObject_FastCall_fallback (bit_generator.c:13511)
==488386==    by 0x16FE1901: __Pyx_PyObject_FastCall (bit_generator.c:13566)
==488386==    by 0x16FE1901: __Pyx_PyObject_CallOneArg (bit_generator.c:13571)
==488386==    by 0x16FE1901: __pyx_pf_5numpy_6random_13bit_generator_12BitGenerator___init__ (bit_generator.c:7299)
==488386==    by 0x16FE1901: __pyx_pw_5numpy_6random_13bit_generator_12BitGenerator_1__init__ (bit_generator.c:7131)
==488386==    by 0x69715A: wrap_init.lto_priv.0 (typeobject.c:5995)
==488386==    by 0x4FFEF2: UnknownInlinedFun (descrobject.c:474)
==488386==    by 0x4FFEF2: wrapperdescr_call.lto_priv.0 (descrobject.c:520)
==488386==    by 0x173C44D9: __Pyx_PyObject_Call (_pcg64.c:6336)
==488386==    by 0x173C44D9: __Pyx_PyObject_FastCall_fallback (_pcg64.c:6378)
==488386==    by 0x173C44D9: __Pyx_PyObject_FastCall (_pcg64.c:6433)
==488386==    by 0x173C4C97: __pyx_pf_5numpy_6random_6_pcg64_5PCG64___init__ (_pcg64.c:2321)
==488386==    by 0x173C4C97: __pyx_pw_5numpy_6random_6_pcg64_5PCG64_1__init__ (_pcg64.c:2279)
==488386== 
==488386== LEAK SUMMARY:
==488386==    definitely lost: 32,363 (+32) bytes in 1,396 (+1) blocks
==488386==    indirectly lost: 962 (+33) bytes in 33 (+2) blocks
==488386==      possibly lost: 120,500,206 (+999) bytes in 523,537 (+3) blocks
==488386==    still reachable: 182,942,766 (+88,002) bytes in 1,369,227 (+74) blocks
==488386==                       of which reachable via heuristic:
==488386==                         length64           : 2,912 (+0) bytes in 181 (+0) blocks
==488386==                         newarray           : 86,800 (+16) bytes in 5,070 (+1) blocks
==488386==         suppressed: 0 (+0) bytes in 0 (+0) blocks
==488386== Reachable blocks (those to which a pointer was found) are not shown.
==488386== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==488386== 
**488386** 
**488386** **********************************************************************
```
which is due to our (arguably not very good) buffer handling, but harmless (We store pointers as python integers, which valgrind is sure must be lost pointers).

---

I suppose I would need to rerun valgrind again to be sure, but I expect this is all there is to find at this time (the `empty_like` kicks in in various places).

**Review by anirudh2290 — COMMENTED** [review]
Thank you Sebastian for these fix ups! Is this also addressing some of the leaks in https://github.com/numpy/numpy/issues/16339 ?

**Comment by seberg** [comment]
I think gh-16348 covers the relevant ones there. There is this one weird scalarbuffer one, that I am a bit unsure about...

**Comment by anirudh2290** [comment]
is running valgrind with this test : test_smoke.py::TestDefaultRNG::test_integers_broadcast[bool_] good to reproduce the leak here ?

**Comment by seberg** [comment]
Running that tests doesn't show any leaks. Sorry for even mentioning the other thing. The reason that the other one leaks I think is that its `def setup` (which runs for every single test) creates a new rng and then the test itself reseeds it (or something like that). So the test creates a new buffer, and that is lost by valgrind until `setup` is run again...

**Comment by anirudh2290** [comment]
> Running that tests doesn't show any leaks. Sorry for even mentioning the other thing. The reason that the other one leaks I think is that its `def setup` (which runs for every single test) creates a new rng and then the test itself reseeds it (or something like that). So the test creates a new buffer, and that is lost by valgrind until `setup` is run again...

So running any test with a class (test_umath::TestRemainder) would reproduce the leak? sorry just trying to reproduce this on my end with valgrind.

**Comment by seberg** [comment]
Sorry, I guess I never mentioned which tests actually flushes out the issue I solved here! (The test remainder actually doesn't run for me, due to collection errors, probably to do with missing longdouble support, did not look into it).

The one that flushes out the main issue here (not the error path, there is no test flushing that out, which is why I added it), is:
```
PYTHONMALLOC=malloc valgrind --show-leak-kinds=definite --log-file=/tmp/valgrind-output2 python3.8 runtests.py -g -t numpy/core/tests/test_numeric.py::TestLikeFuncs::test_filled_like -- -k "not f2py" -vv --valgrind --valgrind-log=/tmp/valgrind-output2 --continue-on-collection-errors
```

so: `/test_numeric.py::TestLikeFuncs::test_filled_like`

**Comment by seberg** [comment]
(and yeah, I skipped the f2py tests, they are slow, maybe I should run that at some point, but all the subprocess/compile calls create false positives)

**Comment by anirudh2290** [comment]
thanks @seberg , thats exactly what i am looking for. will try that out.

**Comment by charris** [comment]
close/reopen

**Comment by charris** [comment]
LGTM passed, github didn't get the message.

**Comment by mattip** [comment]
Thanks @seberg

**Pull request merged**
