### PR TITLE
DEV: add distutils deprecation warning filter to pytest conf

### PR DESCRIPTION
**Pull request by rossbar**
Followup to #20875: add a new filter to ignore the new distutils deprecation warning.

### CODE REVIEW

**Comment by charris** [comment]
Does this warning also need to be ignored in releases? If so, it also needs to be added to `numpy/pytesttester.py`.

**Comment by rossbar** [comment]
> Does this warning also need to be ignored in releases?

I'm not quite sure what this means. AFAICT everything works with the warnings filter specified in the `pytest.ini` file: both of the following will now work:

```bash
$ pytest --pyargs numpy
```

```python
>>> import numpy as np
>>> np.test()
```

whereas before this addition, the former invocation will fail.

**Comment by charris** [comment]
The difference is that `pytest.ini` is not included in the released wheels, so `import numpy; numpy.test()` doesn't use it. That is what distinguishes releases.

**Comment by rossbar** [comment]
> The difference is that pytest.ini is not included in the released wheels, so import numpy; numpy.test() doesn't use it. That is what distinguishes releases.

Thanks for the clarification - in that case I don't think it's necessary because the switch that turns all warnings into errors is itself in the `pytest.ini` file, so this change should only be relevant for those building from source.

**Comment by charris** [comment]
Thanks Ross.

**Pull request merged**
