### PR TITLE
DOC: fix links in 1.17 release note

### PR DESCRIPTION
**Pull request by mattip**
Fix links in 1.17 release note, ~which also exposed missing export of `structured_to_unstructured`~

I tested this by
1. build the documentation
2. `touch` the release note
3. build again with `SPHINXOPTS='-n' make html` to make sure there were no dangling links.

### CODE REVIEW

**Comment by charris** [comment]
Couple of test failures on CircleCI and Mac.

**Comment by mattip** [comment]
If #13889 gets fixed, we can add a link to `structured_to_unstructured`

**Comment by charris** [comment]
Could you split this into two parts? The 1.17 bits should be against the 1.17.x branch as I will forward port the release notes later.

**Comment by mattip** [comment]
Replaced by #13893 against the 1.17.x branch

**Pull request closed without merging**
