### PR TITLE
BUG: Fix inconsistent np.quantile behavior across platforms 

### PR DESCRIPTION
**Pull request by cl334**
see #13272 np.quantile: inconsistent behaviour across platforms for certain edge cases

### CODE REVIEW

**Review by eric-wieser — COMMENTED** [review]
Needs a test. I'm worried this will misbehave when q is float32 or float16 (or Decimal, assuming we support that) but will have to think about it.

**Comment by seberg** [comment]
Hmmm, good points. I had not worried too much about it, since quantile is pretty new and percentile always would have similar issues. Would probably seem ok to do such a fix, but yeah, it is not ideal.

**Comment by eric-wieser** [comment]
Actually, the reason that changing `1.` to `1` is a bad idea is because it breaks the use of `fractions.Fraction`. With #13371, `quantile` needs a one line patch to make it work on `Fractions` and give exact results.

**Comment by eric-wieser** [comment]
Here's the one-line patch needed to make `quantile` work on `Fraction` (#13390) (+ another one line to make `percentile` work).

**Comment by seberg** [comment]
@eric-wieser so I agree, we should fix this by making the path explicit (instead of relying on the `.dtype` check). The question is whether we want to keep the linux behaviour for good. I can't say I am really in favor. It is correct from a typing perspective (user input is an exact integer, so no need to cast to float), but seems a bit too special to be useful and more likely to cause surprises then being actually useful?

Plus you can get the exact behaviour if you use a different method (even if those are a mess right now, and may change).

**Comment by seberg** [comment]
@cl334 can you maybe try to make it explicit about whether or not it goes into the interpolation branch?

**Comment by seberg** [comment]
I will close this PR for now, since it is a single line that is currently not doing the right thing. The corresponding issue is still open, a new PR is welcome.

**Pull request closed without merging**
