### PR TITLE
MAINT: IntpFromSequence cannot return a wrong length here.

### LINKED ISSUE #10813: No exception set while conversion failure in PyArray_IntpConverter
In https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/conversion_utils.c#L131, under the condition `nd != len`, there is no exception set. Python requires the converter to set an exception when failure.

### PR DESCRIPTION
**Pull request by seberg**
As per Matti's comment, removing the path and adding an assert instead,
since it is clearer to read.

Closes gh-10813

### CODE REVIEW

**Review by eric-wieser — CHANGES_REQUESTED** [review]
Doesn't look right

**Comment by eric-wieser** [comment]
Are you sure this can't return a different value? How does the following behave?
```
class Evil:
    _len = 10
    def __getitem__(self, x):
        return 1
    def __len__(self, x):
        self._len -= 1
        return self._len
```

**Comment by eric-wieser** [comment]
I went down a rabbit hole here and ended up at gh-13407

**Comment by seberg** [comment]
Hehe, there you think something is easy. But yeah, I had somehow forgotten to think length might change :). I will check your changes today, seems like it doubles as nice maintenance at least. Closing this, as we will probably end up with that.

**Pull request closed without merging**
