### PR TITLE
MAINT: Uses chain exceptions in numpy/ma/core.py

### PR DESCRIPTION
**Pull request by nandgator**
Uses chained expression in nested `try-except` statement. Fixes part of https://github.com/numpy/numpy/issues/15986#issuecomment-660762674

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Looks good, thanks!

**Comment by mattip** [comment]
I don't understand what happened here. There was a commit, now some pullbot force pushed **over** that commit with a commit that already was merged? What is this pullbot and how did it get onto the repo?

**Comment by seberg** [comment]
Yeah, weird, but seems OK. There are two things here:

1. This PR is based on joe733:master
2. joe733 probably set up this pull bot on *his* repo, which auto pulls from upstream (numpy:master)

So strange, but the strange commit did not happen due to anything from our side.

**Comment by seberg** [comment]
But... I guess that forced pull over master, did delete the actual changes here :(.

**Comment by rgommers** [comment]
> joe733 probably set up this pull bot on his repo, which auto pulls from upstream (numpy:master)

That doesn't explain the label the bot added though. This bot nor user have triage or commit rights. I've also seen that on at least one other PR. Would be good to figure out what's going on exactly.

**Comment by seberg** [comment]
@rgommers that is an action, I thought we can try. If it annoys you, please go ahead and delete it again.

**Comment by eric-wieser** [comment]
It sounds like we should close this issue and get @joe733 to try again on a non-master branch.

**Comment by rgommers** [comment]
> @rgommers that is an action, I thought we can try. If it annoys you, please go ahead and delete it again.

It doesn't, and better labeling seems useful - it's just confusing. So we have two new bots here, one added by you and one mystery one, that have nothing to do with each other?

**Comment by seberg** [comment]
Yes, one is an action running on NumPy org (the labeler). The other is an action installed by @joe733 probably for all repositories even. Which would be fine, but unfortunately the PR is based of `master` :(.

I agree with @eric-wieser, @joe733 sorry about that, but can you open a new PR with a new fork?  We will be happy to help you out if you are unsure how to go about that!

**Comment by joe733** [comment]
Sorry folks for the mess. My bad I should have double check that bot. :facepalm: Here's the new pull #17422 from [`joe733/hotfix-for-nested-try`](https://github.com/joe733/numpy/tree/hotfix-for-nested-try) branch.

**Pull request closed without merging**
