### PR TITLE
STY: change CRLF line terminators to Unix

### PR DESCRIPTION
**Pull request by nschloe**
With
```sh
grep -IUrl --color "^M"
```
one can grep for CRLF line terminators. (The `^M` is generated by pressing Ctrl+v, Ctrl+m.) The current numpy tree gives
```
doc/release/upcoming_changes/17727.performance.rst
doc/source/_static/numpylogo.svg
doc/source/user/how-to-io.rst
doc/source/user/how-to-how-to.rst
doc/source/user/who_covid_19_sit_rep_time_series.csv
doc/source/user/install.rst
numpy/core/src/common/npy_cpuinfo_parser.h
.github/PULL_REQUEST_TEMPLATE.md
```
so I went ahead and changed those to Unix line terminators like the rest.

_Edit:_

Another way of find CRLF-terminated files is via
```
find . -not -type d -exec file "{}" ";" | grep CRLF
```

### CODE REVIEW

**Comment by charris** [comment]
I don't see these, no carriage returns. Git should be set up to covert text to unix in commits and local convention on checkout, and maybe that is why I am getting unix checkouts, my global `.gitconfig` file has `    autocrlf = false` in it. In any case, it is recommended that `.gitattributes` be used to define the behavior in a way that follows the repo, see [here](https://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git). The recommendation is that we update `.gitattributes` before fixing the line endings in the repo because the latter can cause some conflicts with users.

**Comment by nschloe** [comment]
> I don't see these, no carriage returns.

What does
```
file ./.github/PULL_REQUEST_TEMPLATE.md
```
```
./.github/PULL_REQUEST_TEMPLATE.md: exported SGML document, ASCII text, with CRLF line terminators
```
give for you?

**Comment by bashtage** [comment]
> I don't see these, no carriage returns.

This is probably due to your local configuration.  If these were all LF then I think the github diff would be empty.

**Comment by nschloe** [comment]
> This is probably due to your local configuration. If these were all LF then I think the github diff would be empty.

But that's the diff, right? They were CRLF before, I converted them to LF, so we get non-empty diff. What am I missing here?

**Comment by bashtage** [comment]
> But that's the diff, right? They were CRLF before, I converted them to LF, so we get non-empty diff. What am I missing here?

I am agreeing with you that these are here.  The comment above was in response to @charris 's observation.

**Comment by charris** [comment]
> This is probably due to your local configuration.

Exactly, My argument is that we should first fix up the `.gitattributes` file to define the desired eol for our text files because it is part of the repository rather than a local configuration setting. That will prevent such things in the future.  _Then_ we can put in this cleanup.

**Comment by charris** [comment]
Thanks @nschloe . I'm working on a PR to improve our `.gitattributes` file

**Comment by nschloe** [comment]
Cool, thanks!

**Pull request merged**
