### PR TITLE
DOC: some doc build maintenance and f2py doc updates

### PR DESCRIPTION
**Pull request by rgommers**
- update doc Makefile for some changes on hosting server.
- update f2py front page and some doc build metadata.
- remove outdated doc/f2py content.

### CODE REVIEW

**Comment by charris** [comment]
Have some warnings like
```
warning: no files found matching '*' under directory 'doc/f2py'
```
Seems to come from
```
reading manifest template 'MANIFEST.in'
```
Maybe this bit `recursive-include doc/f2py *`.

**Comment by charris** [comment]
Do you want this backported? I'll being doing 1.13.1 next week.

**Comment by rgommers** [comment]
Commit 79402fd would be useful to backport, the rest not.

**Comment by rgommers** [comment]
restarted the stalled test on TravisCI once already, no luck. Just ignore it I guess.

**Comment by charris** [comment]
Thanks Ralf. I'll backport the relevant commit.

**Pull request merged**
