### PR TITLE
Don't pass un-encodable env to spawn

### PR DESCRIPTION
**Pull request by novocaine**
On python 3 and windows, passing os.environ directly to spawn's environ can cause problems if entries in your env are not encodable using sys.getfilesystemencoding() (on windows, this is 'mbcs' i.e. the system codepage).

For example, maybe you have a fancy ascii prompt in PS1 that looks great in your terminal.

This patch pre-emptively tries to encodes the environ ignoring entries that don't encode before passing it into spawn.

I have also changed the except: clause here to catch Exception rather than OSError. If spawn fails to encode the env, it doesn't throw an OSError, it throws a decoding error. This leads to the process mysteriously aborting without actually printing anything I think due to the redirection of stderr/stdout above. 

As an aside - all this code looks like it could mostly be replaced by subprocess..?

### CODE REVIEW

**Comment by njsmith** [comment]
This doesn't look quite right to me -- shouldn't you at least be using the surrogateescape handler on recent py3 versions?

(And yes, this certainly should be ripped out and replaced with calls to subprocess eventually, but I guess no-one has been brave enough yet to try. If you feel like taking out your machete and having a go, then feel free!)

**Comment by novocaine** [comment]
Thanks for the quick feedback.

I looked into this a bit deeper and it ultimately boils down to checking whether PyUnicode_EncodeFSDefault is going to fail or not. On Python 3.5b3:

```C
PyObject *
PyUnicode_EncodeFSDefault(PyObject *unicode)
{
#ifdef HAVE_MBCS
    return PyUnicode_EncodeCodePage(CP_ACP, unicode, NULL);
#elif defined(__APPLE__)
    return _PyUnicode_AsUTF8String(unicode, "surrogateescape");
#else
    PyInterpreterState *interp = PyThreadState_GET()->interp;
    /* Bootstrap check: if the filesystem codec is implemented in Python, we
       cannot use it to encode and decode filenames before it is loaded. Load
       the Python codec requires to encode at least its own filename. Use the C
       version of the locale codec until the codec registry is initialized and
       the Python codec is loaded.

       Py_FileSystemDefaultEncoding is shared between all interpreters, we
       cannot only rely on it: check also interp->fscodec_initialized for
       subinterpreters. */
    if (Py_FileSystemDefaultEncoding && interp->fscodec_initialized) {
        return PyUnicode_AsEncodedString(unicode,
                                         Py_FileSystemDefaultEncoding,
                                         "surrogateescape");
    }
    else {
        return PyUnicode_EncodeLocale(unicode, "surrogateescape");
    }
#endif
}
```

So, on unix, it should not actually fail because os.environ is surrogateescaped on that platform. 

The problem seems to be unique to windows which has populated os.environ using the platform's wide-char interface, which I guess has not checked whether the underlying data is encoded in the correct code page. 

So we can restrict the fix to windows-only and we should not encode with "surrogateescape" - we are really trying to simulate PyUnicode_EncodeCodePage(CP_ACP, unicode, NULL).

**Comment by rgommers** [comment]
+1 for a minimal fix here, so LGTM. That code is basically untestable and extremely hard to understand, so I'd be very hesitant to merge anything that is ripped out and replaced....

**Comment by charris** [comment]
Let's give it a shot and wait for feedback. Thanks @novocaine.

**Pull request merged**
