### PR TITLE
DOC: Canonical_urls

### LINKED ISSUE #17069: Html docs need canonical URLs
See https://github.com/numpy/numpy/issues/17037#issuecomment-672356421. Basically, we now have stable links, some metadata is needed to tell Google et al. to prefer those pages rather than the release version specific page with the same content.

### PR DESCRIPTION
**Pull request by susan-shu-c**
Resolves #17069 adding canonical urls to the header of docs.

I have tested it locally which adds the canonical url in the generated .html files.
The indentation I used in `layout.html` is so that the generated ones line up (see last line of screenshot).
numpy_pr

A similar way that the folks at Sphinx did it: [link to merged PR](https://github.com/sphinx-doc/sphinx/pull/4764)
I opted not to use the `{% block linktags %}` they used due to unexpected behavior (the `href` is generated correctly, but duplicated) when building in `numpy`.

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Looks good to me, this appears to match what sphinx themselves did https://github.com/sphinx-doc/sphinx/pull/4764/files.

Let's check the doc build when CI finishes to see that the links are valid, but otherwise should be good to merge.

**Comment by eric-wieser** [comment]
Seems to work:

https://15437-908607-gh.circle-artifacts.com/0/doc/build/html/user/absolute_beginners.html

**Comment by mattip** [comment]
Thanks @susan-shu-c

**Comment by susan-shu-c** [comment]
Awesome, thanks @eric-wieser and @mattip for looking over this. 

The docs to get started and build the docs are very clear!

**Pull request merged**
