### PR TITLE
BUG: make data attribute of ndarray read-only

### LINKED ISSUE #1873: memory corruption by ndarray_instance.data assignment (data should be made readonly) (Trac #1275)
_Original ticket http://projects.scipy.org/numpy/ticket/1275 on 2009-10-25 by trac user mcieslik, assigned to unknown._

It's probably not a bug, but I'd like to ask for clarification. I try to make two arrays share memory. I create big array from small arrays (this involves a copy e.g. by vstack). Create slice/views of the big array corresponding to the small arrays and do a array.data assignment i.e.:

    small_array.data = big_array[some_slice].data

This works, both arrays can now modify the same memory, but is not safe as it can lead to memory corruption (see below). My first question: is this considered very very bad practice and if so how to point an ndarray instance to a new memory safely. 

    
    In [1]: import numpy as np
    In [2]: zeros = np.zeros((2,2))
    In [3]: double_zeros = np.vstack((zeros, zeros))
    In [4]: double_zeros
    Out[4]:             
    array([[ 0.,  0.],  
           [ 0.,  0.],  
           [ 0.,  0.],  
           [ 0.,  0.]]) 
    In [5]: zeros.data = double_zeros[0:3].data
    In [6]: double_double_zeros = np.vstack((double_zeros,double_zeros))
    In [7]: double_double_zeros
    Out[7]:                    
    array([[ 0.,  0.],         
           [ 0.,  0.],         
           [ 0.,  0.],         
           [ 0.,  0.],         
           [ 0.,  0.],         
           [ 0.,  0.],
           [ 0.,  0.],
           [ 0.,  0.]])
    In [8]: double_zeros.data = double_double_zeros[0:5].data
    In [9]: zeros
    Out[9]:
    array([[  1.25794259e-312,   9.42758674e-317],
           [  1.58101007e-322,   2.37151510e-322]])
    
    In [10]: zeros[0][0] = 1.1
    In [11]: zeros
    Out[11]:
    array([[  9.88131292e-324,   3.95252517e-323],
           [  4.94065646e-324,   2.42092166e-322]])
    In [12]: zeros[0][0] = 2
    In [13]: *** glibc detected *** /usr/bin/python: corrupted double-linked list: 0x000000000117dab0 ***
    (this kills the interpreter)

### PR DESCRIPTION
**Pull request by jaimefrio**
Fixes #1873

### CODE REVIEW

**Comment by jaimefrio** [comment]
Haven't found any specific ndarray attribute tests, any suggestions on where could they go?

Also, if we agree to merge this it probably deserves a mention in the release notes.

**Comment by seberg** [comment]
+100, but do we want to take the chance of having to revert it again if there is enough complains, or should we just go for a VisibleDeprecationWarning with a scary text first?

**Comment by nouiz** [comment]
Old version of Theano was doing the same at the C level in the past. But not now. We currently use PyArray_NewFromDescr. Is there an equivalent in python? We did this as we create our view ourself in some cases. Other people could do this in python.

But I agree, doing it by changing the data ptr is dangerous, so I would consider just raising an error to tell that this isn't supported anymore and tell if they are in the rare case of wanting to build there own view, they should use the equivalent in python of PyArray_NewFromDescr.

I would be surprised there is many complain, but we never know!

**Comment by seberg** [comment]
You can use the `np.ndarray` constructor, I guess? Though IIRC there was something about some types of `buffer`s not being supported, but not sure.

**Comment by charris** [comment]
If this goes in for 1.10, it needs a description in the release. But I admit being ambivalent, we already have so much that will likely break code somewhere...

**Comment by charris** [comment]
May be a problem with f2py. IIRC, there is a place where the data pointer (and other stuff) is swapped. Swapping pointers is also something used in some C++ std classes; swap with pointer in local class and the pointer gets deallocated when the function exits. Anyway, we might want a special function for swapping ndarray structure contents when needed.

**Comment by charris** [comment]
I think f2py changes the data pointer. C++ vectors have a swap method, ndarray could probably use  the same. The functionality would be to swap the data contents of two ndarray structures. In C++ one of the two would be cleaned up when is when it went out of scope and we wouldn't have all that functionality in C, but could still be useful.

**Comment by seberg** [comment]
A swap method in the C-Api might make sense. I seem to remember people saying that they need it. I personally hope it should not be needed (almost?) ever, and it is dangerous buisness if the array is referenced elsewhere.... (I doubt C++ vectors widely use views?)
Anyway, I guess having a function for it still beats writing the data pointer in the ndarray structure directly plus you can put a big warning flag on it ;).

**Comment by njsmith** [comment]
We should perhaps also be trying not to add more code that requires refcnt
== 1, also, since perhaps there is somewhat more hope these days of numpy
being run on non-cpython implementations... (I know pypy, jython, and
pyston are all actively working on supporting real honest numpy through
their c api compatibility layers right now)

On Tue, Dec 22, 2015 at 11:00 AM, seberg <notifications@github.com> wrote:

> A swap method in the C-Api might make sense. I seem to remember people
> saying that they need it. I personally hope it should not be needed
> (almost?) ever, and it is dangerous buisness if the array is referenced
> elsewhere.... (I doubt C++ vectors widely use views?)
> Anyway, I guess having a function for it still beats writing the data
> pointer in the ndarray structure directly plus you can put a big warning
> flag on it ;).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/pull/5958#issuecomment-166703810>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Pull request closed without merging**
