### PR TITLE
MAINT: Update meson build infrastructure.

### PR DESCRIPTION
**Pull request by charris**
Backport #24969,  #24979, #24968, #25068.

### CODE REVIEW

**Comment by charris** [comment]
I'm doing multiple backports one PR at a time. Still a work in progress.

**Review by rgommers — APPROVED** [review]
This LGTM, thanks Chuck!

**Comment by rgommers** [comment]
> I'm doing multiple backports one PR at a time. Still a work in progress.

Not sure if that means that you want to add more commits here, so I'll hold off on merging this.

**Comment by charris** [comment]
> want to add more commits here

Yes, I want to isolate any problems the turn up.

**Pull request merged**
