### PR TITLE
REL: Prepare for 1.11.x branch.

### PR DESCRIPTION
**Pull request by charris**
- Add comment to cversions.txt (no change)
- Add comment to setup_common.py (no change)
- Nothing done for numpy/core/include/numpy/numpyconfig.h
- Update log start to 1.10.0 in pavement.py.

### CODE REVIEW

**Comment by charris** [comment]
Python 3.2 pip seems to have a bug.

**Comment by charris** [comment]
@rgommers Could this be due to the move to setup_tools? This is for Python 3.2 which seems to be using an invalid pip.
```
   from pip._vendor.progress.bar import Bar, IncrementalBar

  File "/home/travis/build/numpy/numpy/builds/venv/lib/python3.2/site-packages/pip/_vendor/progress/bar.py", line 48

    empty_fill = u'∙'

                      ^

SyntaxError: invalid syntax
```

**Comment by njsmith** [comment]
All the messages here say 1.10... Did you mean 1.11?

**Comment by charris** [comment]
Yep, changed Title.

**Comment by rgommers** [comment]
gh-7068 fixed this. ``pip`` dropped support for Python 3.2 4 months ago: https://github.com/pypa/pip/commit/b11cb019a47ff0cf3d8a37a0c89d8ae4cf25282f

No idea why earlier TravisCI runs didn't fail.

**Pull request merged**
