### PR TITLE
DOC: remove reverted release blurb [skip actions][skip azp][skip cirrus]

### PR DESCRIPTION
**Pull request by mattip**
Left over in a merge, see [this comment](https://github.com/numpy/numpy/pull/25955#issuecomment-1987920815)

### CODE REVIEW

**Comment by charris** [comment]
Should make this against `maintenance/2.0.x`, the notes in main will be overwritten after the release.

**Comment by seberg** [comment]
Sorry, thought changing the base might work (can do that with the edit button), but adds other commits here of course.

**Comment by mattip** [comment]
I will make another PR against that branch

**Comment by charris** [comment]
Closing as not needed. The notes are already different in the 2.0.x branch and all further modifications should made there.

**Pull request closed without merging**
