### PR TITLE
MAINT: Drop Python 3.10 support.

### LINKED ISSUE #27861: Dropping Python 3.10 support.
We are scheduled to drop Python 3.10 support in NumPy 2.3. I will make a PR to get started on that, but
have noticed a few issues I have questions about:

@ngoldbaum `numpy/_core/src/multiarray/stringdtype/static_string.c` has a 3.10 workaround.
@seberg `numpy/_core/include/numpy/numpyconfig.h`  NPY_FEATURE_VERSION needs update.
@r-devulap `linux_simd.yml` could probably use an update/rework.
@mattip can PyPy support 3.11 yet?

### PR DESCRIPTION
**Pull request by charris**
Dropping support is in line with SPEC 0, NumPy 2.3 is due sometime in June 2025.

Closes #27861.

### CODE REVIEW

**Comment by charris** [comment]
I don't expect this to work on first try, might need some windows/ubuntu updates. I've left some questions on the corresponding task #27861.

**Comment by charris** [comment]
Note that this is passing because testing PyPy was disabled. It is still enabled for wheel building. A short term solution would be putting python 3.10 back into pyproject.toml once we know the rest works.

**Comment by mattip** [comment]
Hopefully by the time 2.23 is ready there will be a PyPy 3.11. In any case i think NumPy should drop OyPy 3.10 if it is dropping CPython 3.10

**Comment by charris** [comment]
Self merging so this doesn't get forgotten.

**Pull request merged**
