### PR TITLE
DOC: Update beginners docu for sum function with axis

### LINKED ISSUE #16697: DOC: Update Sum function with axis
In this Documention  https://numpy.org/devdocs/user/absolute_beginners.html 
Sum of rows of an numpy array is denoted by b.sum(axis=0), but the axis should be equal to 1 for sum of rows and 0 for sum of columns.

pleas refer to the screenshot below from the documentation web page.

image

### PR DESCRIPTION
**Pull request by EvaJau**
Hopefully clarifies how summing over an axis is done. Fixes #16697

### CODE REVIEW

**Comment by melissawm** [comment]
Hi @EvaJau - you can edit your description to say either "Closes #16697", "Fixes #16697" or any of the other magic words listed here: https://docs.github.com/pt/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by EvaJau** [comment]
> Hi @EvaJau - you can edit your description to say either "Closes #16697", "Fixes #16697" or any of the other magic words listed here: https://docs.github.com/pt/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Yes, sure. Thanks for the hint!

**Comment by melissawm** [comment]
Hi @EvaJau just in case you were pairing up with someone to work on this, do you want to add them as co-author to your commit message?

**Comment by EvaJau** [comment]
> Hi @EvaJau just in case you were pairing up with someone to work on this, do you want to add them as co-author to your commit message?

Hey, I didn't pair for this issue but thanks for asking!

**Comment by melissawm** [comment]
This looks good to me, although I'm not a native English speaker it does look clearer. Thanks!

**Pull request merged**
