### PR TITLE
BUG: Fix in-place permutation

### LINKED ISSUE #11975: numpy.random.permutation modified pandas.RangeIndex
### Reproducing code example:

```python
import numpy as np
import pandas as pd

ri = pd.RangeIndex(2)
print('before permutation:', ri.values)

while True:
    idx = np.random.permutation(ri)
    if idx[0] == 1:
        break
    
print('after permutation:', ri.values)
```

### Error message:
Running the code outputs the following:

before permutation: [0 1]
after permutation: [1 0]

np.random.permutation should not change input based on manual.

The code behavior correctly if change the code to

    idx = np.random.permutation(ri.values)

### Numpy/Python version information:

1.15.1 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
``

### PR DESCRIPTION
**Pull request by bashtage**
Alter test to check if arrays are the same to avoid in-place modification of some array-like objects

closes #11975

### CODE REVIEW

**Comment by bashtage** [comment]
It is hard to write the ideal test that would fail on master but pass in this PR since it requires a non-trivial array-like object that is `False` when tested with `is` equality after the `np.asarray` but shares memory.  `RangeIndex` from pandas has these attributed.  I wrote a test with a recarray but it passes on master as well. 

Are there any classes like this in NumPy?  Or are there other tests that define any that I could borrow?

**Comment by mattip** [comment]
```
class N(np.ndarray):
    pass
a = np.arange(10).view(N)
b = np.asarray(a)
b is a  # False
np.may_share_memory(a, b)  # True
```

**Comment by bashtage** [comment]
Thanks. works perfectly.

**Comment by charris** [comment]
Might try
```
In [1]: class Foo(object):
   ...:     a = np.arange(5)
   ...:     def __array__(self):
   ...:         return self.a
   ...:     

In [2]: a = Foo()

In [3]: a.__array__()
Out[3]: array([0, 1, 2, 3, 4])

In [4]: np.random.permutation(a)
Out[4]: array([0, 1, 3, 4, 2])

In [5]: a.__array__()
Out[5]: array([2, 4, 3, 0, 1])
```
As a test that currently fails. I suspect that is closer to the original.

**Comment by charris** [comment]
I'm not convinced that we can solve this problem in all generality without just making a copy, but we can make a start :)

**Pull request merged**
