### PR TITLE
MAINT: Translate numpy/linalg/umath_linalg.c.src to C++ using templates.

### PR DESCRIPTION
**Pull request by serge-sans-paille**
As it's a large file, I've first handled the C++ conversion part while keeping
Numpy templating system. The switch to C++ template is to be done in another
commit.

### CODE REVIEW

**Comment by BvB93** [comment]
I imagine this will autogenerate a new `umath_linalg.cpp` file? If so, can you add it to `.gitignore`?

**Comment by serge-sans-paille** [comment]
> I imagine this will autogenerate a new `umath_linalg.cpp` file? If so, can you add it to `.gitignore`?

Yeah, but this commit is only transient. It's part of an effort to replace @templates@ with equivalent C++ constructs.
That's why I put a [wip] flag on the title: in the end, there's only going to be a .cpp file as source.

**Comment by BvB93** [comment]
> in the end, there's only going to be a .cpp file as source.

Sure, but these files will be autogenerated when building numpy, correct? _i.e._ `git` will want to them checked out when building locally unless they're added to .gitignore.

**Comment by serge-sans-paille** [comment]
Not once I finish the patchset: there will be no .cpp.src, only a source .cpp, just like #19713

**Comment by charris** [comment]
> Not once I finish the patchset

But it would keep `git status` a bit cleaner in the meantime.

**Comment by serge-sans-paille** [comment]
As green as a field of clover, cc @charris

**Comment by serge-sans-paille** [comment]
up ?

**Comment by charris** [comment]
I have a couple of general questions:

- Do we still need NPY_INLINE? Doesn't standard C++ have inline?
- What is the advantage of the template specializations?
- Does clang-format improve the appearance?

**Comment by seberg** [comment]
I scrolled through only, but if others/Chuck agree, we should probably just merge: It seems good.  Some of the constant `struct`s seemed to lacking indentation, is that on purpose (yeah, silly style nit :))?  The old `init` function had a comment that some constant were runtime, that was just wrong/outdated, I guess?

**Comment by charris** [comment]
> we should probably just merge

Agree, but I'm trying to get some education on modern C++ along the way :) I've dabbled with C++ since it was classes for C, but these days it is almost a different language.

**Comment by serge-sans-paille** [comment]
> I have a couple of general questions:
> 
>     * Do we still need NPY_INLINE? Doesn't standard C++ have inline?

Yeah `inline` is a standard C++ keyword. Do you want me to change it?

> 
>     * What is the advantage of the template specializations?
> 
>     * Does clang-format improve the appearance?

I already did a pass of clang-format on the cpp file. We could improve the clang-format styling for C++ stuff though (?)
> 
> 
> EDIT: OK, I can see the specializations as a convenient way to name the classes with different initializations.

Correct! That was needed to make the glue between generic functions and lapack ones that have different names for different types

**Comment by serge-sans-paille** [comment]
> I scrolled through only, but if others/Chuck agree, we should probably just merge: It seems good. Some of the constant `struct`s seemed to lacking indentation, is that on purpose (yeah, silly style nit :))?

Well, I clang-formated it, I don't know if we want to deviate from the automatic rendering (?)

> The old `init` function had a comment that some constant were runtime, that was just wrong/outdated, I guess?

This part is technically interesting :-)

When one writes

```
int bar();
struct foo {
    static const int a;
    static const int b;
};

const int foo::a = 1;         // pattern used to init `one` in the numpy code
const int foo::b = bar();   // pattern used to init `nan` in the numpy code
```

the initialization of `a` is done at compile time, it's put in constant memory and that's fine.
The initialization of `b` is done at runtime, upon loading of the library (through elf constructors on Linux). Here's the godbolt output: https://godbolt.org/z/zhYv135Ge

This could be all done at compile time if `foo` is flagged as `constexpr`. I'd love to see that happen (esp. in this case where C++ already provides standard `constexpr` way to generate `NaN` and `inf` : https://en.cppreference.com/w/cpp/types/numeric_limits/quiet_NaN

Maybe that's something I should do in another PR ?

**Comment by charris** [comment]
> Yeah inline is a standard C++ keyword. Do you want me to change it?

I'm thinking we should. The reason for `NPY_INLINE` was that it wasn't standard in C and the method of implementing it varied between compilers. That was about 12 years ago. Now that we require C99 we could probably dispense with it, especially for static functions in C++ code. We could make a another PR to do that wholesale.

> We could improve the clang-format styling for C++ stuff though

Feel free to offer suggestions/PRs. Clang-format does vary a bit between versions, it is now at version 15 and the style file was written for version 12 as first attempt to standardize automatic formatting.

**Comment by charris** [comment]
Thanks @serge-sans-paille .

**Pull request merged**
