### PR TITLE
ENH: Virtually implement __buffer__ for Python < 3.12 

### PR DESCRIPTION
**Pull request by Andrej730**
See #26783 for the details

Note that there is also `__release_buffer__` part of the buffer protocol -
https://github.com/numpy/numpy/blob/768724556fd9a60556fea5203b1489bb51c507a5/numpy/__init__.pyi#L2843-L2844

I've kept it Python 3.12+ only as it's [optional part of the protocol](https://peps.python.org/pep-0688/#python-level-buffer-protocol) and it's `Buffer` is using just `__buffer__` to detect whether class supports the protocol. So, there is no need to virtually implement it for <3.12.
image

### CODE REVIEW

**Comment by Andrej730** [comment]
@BvB93 can you please take a look?

**Comment by Andrej730** [comment]
@rgommers @jorenham Hi! Could you please let me know who I can ask for a PR review?

**Review by jorenham — COMMENTED** [review]
Thanks for the PR!

I totally agree that it's annoying that opn Python <3.12 static type-checkers mark e.g. `memoryview(my_ndarray)` as an error.
And [PEP 688](https://peps.python.org/pep-0688/) was (in part) proposed to solve this issue, which it did, but that requires at least Python 3.12.

In typeshed they have "backported" this by adding a `__buffer__` to the builtin typing stubs, ignoring the fact that this isn't the case at runtime. But static stub-checkers (e.g. mypy's `stubtest` or `pyright --verifytypes`) report this as a "hard" error, making this fall into the category of *bugs*.

An although I fully understand why this is practical, and that it could make static typing easier in several situations, I don't think it's a good idea to (knowingly) have the typing stubs deviate from the (true) runtime.
And that's not *only* because it's wrong, or because "bugs are bad". It's mostly because I know from experience that things like these can (and will) lead to very tricky and significant problems , and many confused users (myself included).
I could list several major problems such deviations have caused if you want, but that'll probably become a huge rant 😅 (and is unrelated to this PR).

In this case, I think that especially for `ndarray` subclasses this could cause many typing issues, e.g. in 3rd party libraries, most of which are unforeseeable "unknown unknowns".

So to make a long story short: As far as I'm concerned, I don't think this is worth the risk. 

ELet me conclude by quoting Tim Peters wise words from [PEP 20](https://peps.python.org/pep-0020/) (even though this probably makes me sound like a total wise-ass):

> Special cases aren't special enough to break the rules.
> Although practicality beats purity.

**Comment by Andrej730** [comment]
Sad but makes sense, though it is inconsistent with the decision made in typeshed.

I guess will be stuck with those warnings for a couple years more since VFX Platform CY2025 is also currently planning to use Python 3.11 :\

**Comment by jorenham** [comment]
For what it's worth; perhaps you could work around it with a custom `memoryview` wrapper, e.g.

```python
from typing import cast
from typing_extensions import Buffer

import numpy as np
import numpy.typing as npt

def better_memoryview(x: Buffer | npt.NDArray[np.generic], /) -> memoryview:
    # alternatively, you could also use `# type: ignore[arg-type]` (with mypy)
    return memoryview(cast(Buffer, x))
```

You could (but probably shouldn't) even go as far as replace `builtins.memoryview`:

```
import builtins
builtins.memoryview = better_memoryview
```

... but that'll probably get you fired 😅

**Pull request closed without merging**
