### PR TITLE
BUG: fix `_selected_real_kind_func` return values for macOS on arm64

### PR DESCRIPTION
**Pull request by dhomeier**
`np.f2py.crackfortran._selected_real_kind_func` was only considering `aarch64` as a `machine` value for determining Fortran's `selected_real_kind` values on these CPUs, but on macOS M1 `platform.machine()` returns `arm64` (in system `/usr/bin/python3` (3.8.9) and any Python 3.9-3.11 build I have tested).
This PR adds the latter to the list of processors, fixing #21765. I have also extended the return range to 33, which matches the Fortran values on arm64 and x86_64 (and thus possibly works for all higher numbers, for which –1 is returned); giving this a try here by extending the test to `range(40)`.
Tested on macOS 12.4 with the new ports for gcc 11.3 and 12.1 documented in iains/gcc-darwin-arm64#91 and iains/gcc-darwin-arm64#92.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @dhomeier. The `ppc64le` job on TravisCI doesn't seem to like this:
```
______________________________ TestKind.test_all _______________________________

self = <numpy.f2py.tests.test_kind.TestKind object at 0x7f25100ea4c0>

    def test_all(self):

        selectedrealkind = self.module.selectedrealkind

        selectedintkind = self.module.selectedintkind

    

        for i in range(40):

            assert selectedintkind(i) == selected_int_kind(

                i

            ), f"selectedintkind({i}): expected {selected_int_kind(i)!r} but got {selectedintkind(i)!r}"

    

        for i in range(40):

>           assert selectedrealkind(i) == selected_real_kind(

                i

            ), f"selectedrealkind({i}): expected {selected_real_kind(i)!r} but got {selectedrealkind(i)!r}"

E           AssertionError: selectedrealkind(32): expected 16 but got -1

E           assert -1 == 16

E            +  where -1 = <fortran function selectedrealkind>(32)

E            +  and   16 = selected_real_kind(32)

i          = 32

selectedintkind = <fortran function selectedintkind>

selectedrealkind = <fortran function selectedrealkind>

self       = <numpy.f2py.tests.test_kind.TestKind object at 0x7f25100ea4c0>

../../builds/venv/lib/python3.8/site-packages/numpy-1.24.0.dev0+275.g4fead45a2-py3.8-linux-ppc64le.egg/numpy/f2py/tests/test_kind.py:24: AssertionError
```

**Comment by dhomeier** [comment]
> E           AssertionError: selectedrealkind(32): expected 16 but got -1

Yes, apparently for `ppc64le` the limit should be 31, not 33.
So I could either limit the tests to `range(32)`, or add another case for 'ppc'; question is of course, does this apply for `ppc64le` only (unlikely IMO), `ppc64` or `ppc` in general? And what about `power`...?

I still tend to the second option, as it would at least correct some more cases that have just not been covered by tests before. Or might try and investigate what the kinds are on other CPUs.

**Comment by rgommers** [comment]
Adding `ppc64le` as a special case and updating something else if a new test failure is reported would be fine with me. If you can select any 64-bit PowerPC platform that works too. I don't think `ppc64` is a valid platform identifier though?

**Comment by dhomeier** [comment]
As it only checks for `startswith` that would cover all PowerPC[64] platforms – probably having the same precision, see e.g. https://github.com/OpenFAST/openfast/issues/502#issuecomment-662750466
The `else` case btw. already implies that everything else is an Intel CPU with 80bit support, which likely is not very robust either.

**Comment by rgommers** [comment]
I tested this on `arm64` macOS, and it shows two failures:
```
__________________________________________________ TestKind.test_real ___________________________________________________

self = <numpy.f2py.tests.test_kind.TestKind object at 0x17e464af0>

    def test_real(self):
        """
        Test (processor-dependent) `real` kind_func for real numbers
        of up to 31 digits precision (extended/quadruple).
        """
        selectedrealkind = self.module.selectedrealkind

        for i in range(32):
>           assert selectedrealkind(i) == selected_real_kind(
                i
            ), f"selectedrealkind({i}): expected {selected_real_kind(i)!r} but got {selectedrealkind(i)!r}"
E           AssertionError: selectedrealkind(16): expected 16 but got -1
E           assert -1 == 16
E            +  where -1 = <fortran function selectedrealkind>(16)
E            +  and   16 = selected_real_kind(16)

i          = 16
selectedrealkind = <fortran function selectedrealkind>
self       = <numpy.f2py.tests.test_kind.TestKind object at 0x17e464af0>

numpy/f2py/tests/test_kind.py:32: AssertionError
_____________________________________________ TestKind.test_quad_precision ______________________________________________

self = <numpy.f2py.tests.test_kind.TestKind object at 0x17e219280>

    @pytest.mark.xfail(platform.machine().lower().startswith("ppc"),
                       reason="Some PowerPC may not support full IEEE 754 precision")
    def test_quad_precision(self):
        """
        Test kind_func for quadruple precision [`real(16)`] of 32+ digits .
        """
        selectedrealkind = self.module.selectedrealkind

        for i in range(32, 40):
>           assert selectedrealkind(i) == selected_real_kind(
                i
            ), f"selectedrealkind({i}): expected {selected_real_kind(i)!r} but got {selectedrealkind(i)!r}"
E           AssertionError: selectedrealkind(32): expected 16 but got -1
E           assert -1 == 16
E            +  where -1 = <fortran function selectedrealkind>(32)
E            +  and   16 = selected_real_kind(32)

i          = 32
selectedrealkind = <fortran function selectedrealkind>
self       = <numpy.f2py.tests.test_kind.TestKind object at 0x17e219280>

```

**Comment by rgommers** [comment]
```
% echo $FC
/Users/rgommers/mambaforge/envs/numpy-dev/bin/arm64-apple-darwin20.0.0-gfortran

$ gfortran --version
GNU Fortran (GCC) 11.0.1 20210403 (experimental)
```

There's one failure on `main`, and I think it's been introduced fairly recently:
```
___________________________________________________ TestKind.test_all ___________________________________________________

self = <numpy.f2py.tests.test_kind.TestKind object at 0x11792d580>

    def test_all(self):
        selectedrealkind = self.module.selectedrealkind
        selectedintkind = self.module.selectedintkind

        for i in range(40):
            assert selectedintkind(i) == selected_int_kind(
                i
            ), f"selectedintkind({i}): expected {selected_int_kind(i)!r} but got {selectedintkind(i)!r}"

        for i in range(20):
>           assert selectedrealkind(i) == selected_real_kind(
                i
            ), f"selectedrealkind({i}): expected {selected_real_kind(i)!r} but got {selectedrealkind(i)!r}"
E           AssertionError: selectedrealkind(16): expected 10 but got -1
E           assert -1 == 10
E            +  where -1 = <fortran function selectedrealkind>(16)
E            +  and   10 = selected_real_kind(16)

i          = 16
selectedintkind = <fortran function selectedintkind>
selectedrealkind = <fortran function selectedrealkind>
self       = <numpy.f2py.tests.test_kind.TestKind object at 0x11792d580>

numpy/f2py/tests/test_kind.py:24: AssertionError
```

**Comment by dhomeier** [comment]
I guess darwin-arm64 has not been tested for that long anyway.
That gcc is still a bit older than the one from https://github.com/fxcoudert/gcc/releases/tag/gcc-11.2.0-arm-20211201 I tested first, so probably rather far from a stable release. But in a way that drives home a thought from my previous comment, that there is no guarantee the compiler supports any extended or quad-precision real at all, so perhaps the default kind for `p >= 16` should rather be `-1`. And that it does depend on the compiler as well as on the CPU – I just found out that current ifort, of all things, provides no `real(kind=10)` at all!

**Comment by seberg** [comment]
@HaoZeke any chance you have time to check this out?  Since a couple of platforms have these issues including M1 setups and [debian arm](https://github.com/numpy/numpy/issues/5550#issuecomment-1396522813) builds.

Will close reopen, to see retrigger CI, since this has been a while (it was all green).

**Comment by HaoZeke** [comment]
The `arm64` addition has already made its way into `main` but the rest of the PR would be good to have too.

**Comment by seberg** [comment]
Thanks @HaoZeke in that case, it sounds like we should give this a try.  I guess if something is off, it should be noisy and easy to fix.

**Pull request merged**
