### PR TITLE
MAINT: remove unused nd_grid `__len__`.

### PR DESCRIPTION
**Pull request by tylerjereddy**
~~Add a test to trigger [uncovered path](https://codecov.io/gh/numpy/numpy/src/master/numpy/lib/index_tricks.py#L203...204) in `nd_grid` corresponding to `len` probe of empty `mgrid` instance.~~

Now, just removing the unused method

### CODE REVIEW

**Comment by mattip** [comment]
close/open to trigger windows builds

**Comment by eric-wieser** [comment]
This method doesn't make any sense - we should just remove `nd_grid.__len__`.

**Comment by tylerjereddy** [comment]
Revised based on feedback to remove `__len__` from `nd_grid`

**Review by eric-wieser — APPROVED** [review]
Maybe worthy of a compatibility note, that the expression `len(np.mgrid)` is now considered nonsensical and throws a TypeError.

**Comment by tylerjereddy** [comment]
Added a compatibility note as requested -- `ogrid` is equally affected too.

**Comment by eric-wieser** [comment]
@rgommers: Does this need a deprecation warning, or is it such a weird thing to do that we'd expect it to break no one?

**Comment by charris** [comment]
I suppose `len` was there to compliment the use of indexing, which seems like an abuse of notation. If only there was a easier way to generate the slices, and the use of complex was always weird.

**Comment by charris** [comment]
Thanks Tyler.

**Pull request merged**
