### PR TITLE
WIP: implement __rop__ logic for scalar operators

### PR DESCRIPTION
**Pull request by ewmoore**
Re. #7449.  

This is a work in progress, both because I'd like to get some feedback on the approach and there are currently two test failures that I don't yet understand.

### CODE REVIEW

**Comment by ewmoore** [comment]
Also, negative integer powers still return an int type if one of the inputs is unsigned.

**Comment by charris** [comment]
I added a release notes tag as this will probably change behavior.

**Comment by ewmoore** [comment]
This is fun:
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.9.3'

In [3]: np.longdouble(3) * None
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-0319ac841cc8> in <module>()
----> 1 np.longdouble(3) * None

TypeError: unsupported operand type(s) for *: 'numpy.float128' and 'NoneType'

In [4]: None * np.longdouble(3)
/home/ewm/.pyenv/numpy-1.9.3-scipy-0.17.0-py27/bin/ipython:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  #!/home/ewm/.pyenv/numpy-1.9.3-scipy-0.17.0-py27/bin/python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-9199aac90ce7> in <module>()
----> 1 None * np.longdouble(3)

RuntimeError: maximum recursion depth exceeded while calling a Python object
```
The fix for #1296 doesn't treat both arguments the same so this still fails.  Working on a fix for this as well.

**Comment by ewmoore** [comment]
Alright. I think this is about ready to go.

**Comment by ewmoore** [comment]
This also results in a change to the outputs for true division of integer scalars.  Now the usual integer to float promotion occurs so `int8 / int16 -> float32`.  It used to go to `float64` because, for reasons I don't understand integer array true_divide always goes to double.

**Comment by charris** [comment]
Needs rebase, probably the release notes.

**Comment by ewmoore** [comment]
Yep. Rebased.

**Comment by charris** [comment]
@ewmoore It looks like the decision will be to raise a `DeprecationWarning` when raising scalar integers to negative integer powers except that zero division should raise an error. I think this PR should probably be split into two, one specifically for the negative exponent case, and the other for speeding things up. The first will be required for the 1.12.0 release.

**Comment by ewmoore** [comment]
@charris, I'm not going to be able to do much anytime soon.  I've just started a new job and don't at present have a development machine.

**Comment by charris** [comment]
Rebased in #8126. Thanks @ewmoore . How is the new job?

**Pull request closed without merging**
