### PR TITLE
MAINT: Use mask_store instead of store for compiler bug workaround

### LINKED ISSUE #27745: BUG: SIGILL Illegal Instruction with numpy 1.26.4 on KNL
### Describe the issue:

Hiya, I'm seeing an illegal instruction in function `DOUBLE_log_AVX512F` from `_multiarray_umath.cpython-39-x86_64-linux-gnu.so` when running numpy 1.26.4 on a Knight's Landing CPU (aka Intel Xeon Phi). The problematic instruction is `vextractf64x2` -- according to [an internet reference](https://www.felixcloutier.com/x86/vextractf128:vextractf32x4:vextractf64x2:vextractf32x8:vextractf64x4) this falls under the `AVX512DQ` CPU feature flag which the KNL does _not_ advertise, so this could be an error in dynamic dispatch?

An older version of this workflow using numpy 1.24.2 succeeds. That implementation of `DOUBLE_log_AVX512F` only uses `vextractf64x4` and `vextractf128` from the VEXTRACT family.

It's worth noting that the workflow is running in a singularity container, however this doesn't affect the flags visible in `/proc/cpuinfo`¹, and the output of `numpy.show_runtime()` below seems to indicate that the machine is correctly detected as a KNL.

I don't see any explicit references to `vextract*` in the numpy codebase, so this could ultimately be a compiler issue. The numpy packages in use are from these images:

https://quay.io/repository/biocontainers/rnaquast/manifest/sha256:b1064d92b9c2cbf506902718e13325f08f6439a361a07fa46086175ced940a2a
https://quay.io/repository/biocontainers/rnaquast/manifest/sha256:917929562006aa015b8b529935ec345110155326df2950980e075089ec415edc

However I haven't found the build recipe for these numpy packages to compare the build environments.

¹ 
```
Singularity> head -n30 /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 87
model name	: Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz
stepping	: 1
microcode	: 0x1ac
cpu MHz		: 1512.194
cache size	: 1024 KB
physical id	: 0
siblings	: 272
core id		: 0
cpu cores	: 68
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ring3mwait epb rsb_ctxsw fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms avx512f rdseed adx avx512pf avx512er avx512cd xsaveopt dtherm ida arat pln pts
bogomips	: 2793.77
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
Singularity> head -n30 /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 87
model name	: Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz
stepping	: 1
microcode	: 0x1ac
cpu MHz		: 1480.834
cache size	: 1024 KB
physical id	: 0
siblings	: 272
core id		: 0
cpu cores	: 68
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ring3mwait epb rsb_ctxsw fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms avx512f rdseed adx avx512pf avx512er avx512cd xsaveopt dtherm ida arat pln pts
bogomips	: 2793.77
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

...
```

### Reproduce the code example:

```python
I don't have a self-contained example sorry
```

### Error message:

```shell
Program received signal SIGILL, Illegal instruction.
0x00002aaaac2c4f03 in DOUBLE_log_AVX512F ()
   from /usr/local/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so


$ objdump -D /usr/local/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so
...
00000000003b0430 <DOUBLE_log_AVX512F>:
...
  3b0ee5:       ff 15 c5 21 1e 00       callq  *0x1e21c5(%rip)        # 5930b0 <log@GLIBC_2.2.5>
  3b0eeb:       0f b6 8d 90 fe ff ff    movzbl -0x170(%rbp),%ecx
  3b0ef2:       62 f1 fd 48 28 9d d0    vmovapd -0x130(%rbp),%zmm3
  3b0ef9:       fe ff ff 
  3b0efc:       c5 fb 11 43 18          vmovsd %xmm0,0x18(%rbx)
  3b0f01:       eb 8f                   jmp    3b0e92 <DOUBLE_log_AVX512F+0xa62>
* 3b0f03:       62 f3 fd 48 19 d8 03    vextractf64x2 $0x3,%zmm3,%xmm0
  3b0f0a:       88 8d 90 fe ff ff       mov    %cl,-0x170(%rbp)
  3b0f10:       62 f1 fd 48 29 9d d0    vmovapd %zmm3,-0x130(%rbp)
  3b0f17:       fe ff ff 
  3b0f1a:       c5 f8 77                vzeroupper 
...

(note that the version of gdb I used to isolate the failure was too old to even decode the vextractf64x2 function, hence the use of objdump from a newer distro to get a dissassembly)
```

### Python and NumPy Versions:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.4
3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]

And from the older working image:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.2
3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]

### Runtime Environment:

>>> numpy.show_runtime()
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.26.4',
  'python': '3.9.15 | packaged by conda-forge | (main, Nov 22 2022, '
            '08:45:29) \n'
            '[GCC 10.4.0]',
  'uname': uname_result(system='Linux', node='pnod1-12-9', release='3.10.0-1160.80.1.1.el7.dug.x86_64', version='#1 SMP Mon Nov 28 07:23:08 GMT 2022', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_KNL'],
                      'not_found': ['AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}}]

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by r-devulap**
Fixes https://github.com/numpy/numpy/issues/27745. 

GCC 12 and later versions incorrectly generate vextractf64x2 instruction (requires AVX512-DQ) when using -O3 with -mavx512f. The workaround in this commit prevents the optimization from taking place.

Bug demonstration: https://gcc.godbolt.org/z/xT6osP173

### CODE REVIEW

**Comment by r-devulap** [comment]
The CI failure looks unrelated, I think.

**Comment by charris** [comment]
I think a rebase on main will fix the circleci failures.

**Comment by r-devulap** [comment]
Rebased.

**Review by seiko2plus — CHANGES_REQUESTED** [review]
Nice catch! The fix just needs to be more global across all the sources. I suggest applying this workaround to both `npyv_store_f64` and `npyv_storea_f64` for GCC when `NPY_HAVE_AVX512BW` and `NPY_HAVE_AVX512DQ` are not enabled.

**Comment by r-devulap** [comment]
>  I suggest applying this workaround to both npyv_store_f64 and npyv_storea_f64 for GCC when NPY_HAVE_AVX512BW and NPY_HAVE_AVX512DQ are not enabled.

The illegal AVX512-DQ instruction is only generated when -O3 optimizes an element-wise load following store_pd by reusing the register instead of loading from memory. Using mask_store adds an overhead and doing that everywhere seems unnecessary.

**Comment by seiko2plus** [comment]
> The illegal AVX512-DQ instruction is only generated when -O3 optimizes an element-wise load following store_pd by reusing the register instead of loading from memory.

I'm aware of this, but we use this fallback style with other kernels. I believe it's better to make it global as long as there is no performance regression.

> Using mask_store adds an overhead and doing that everywhere seems unnecessary

What kind of overhead? This workaround seems quite good to me. As a matter of fact, passing `-1` as the mask value does not require allocating any mask register. In other words, `_mm512_mask_store_pd(a, -1, b)` is equivalent to `_mm512_store_pd(a, b)`; both should emit `vmovapd` with the same encoded value.

Additionally, this workaround should only be applied for GCC versions >=12 and when `AXV512DQ` and `AXV512DW` are not defined.

**Comment by r-devulap** [comment]
> I'm aware of this, but we use this fallback style with other kernels. I believe it's better to make it global as long as there is no performance regression.

AFAIK, there is only one other place where we use this kind of fallback here: https://github.com/numpy/numpy/blob/4e8f724fbc136b1bac1c43e24d189ebc45e056eb/numpy/_core/src/umath/loops_trigonometric.dispatch.cpp#L191-L207

This is build using AVX512_SKX rather than just AVX512F and so this problem doesn't really happen anywhere else.  Going forward we are using HWY which builds for AVX512_SKX and so I don't think we really need more fixing than this.

**Review by seiko2plus — APPROVED** [review]

**Comment by seiko2plus** [comment]
>  Going forward we are using HWY which builds for AVX512_SKX and so I don't think we really need more fixing than this.

Agreed! Thank you @r-devulap

**Pull request merged**
