### PR TITLE
ENH: Make NpzFile conform to the Mapping protocol

### LINKED ISSUE #1723: implement the rest of the dictionary interface for NpzFile (Trac #1125)
_Original ticket http://projects.scipy.org/numpy/ticket/1125 on 2009-06-03 by @dwf, assigned to unknown._

The patch attached implements a more complete dictionary interface for NpzFile. That is to say, it provides (in addition to the already present **getitem**()):
- `__contains__` - tests for containment of a key in self.files
- `__iter__` - returns an iterator over self.files
- keys() - returns a copy of self.files
- values() - returns a list of all arrays in the NpzFile
- iterkeys() - returns an iterator [really a generator] over all items in self.files
- itervalues() - returns an iterator over all arrays in the NpzFile
- items() - returns a list of (key, value) pair tuples
- iteritems()  - returns an iterator over (key, value) pair tuples

This allows the convenient "for fname in mynpzfile"  syntax, as well as letting you write code that doesn't care whether its input is an in-memory dictionary or a lazily-loaded NpzFile.

### PR DESCRIPTION
**Pull request by eric-wieser**
This is a breaking change for python 3, because the Mapping protocol changed between python 2 and python 3. In practice, any user running `2to3` should have found this fixed itself automatically.

Fixes gh-1723

### CODE REVIEW

**Comment by ahaldane** [comment]
Hmm, we potentially want a cycle of deprecation warnings. 

Or maybe, make the change, but keep the 'iteritems' methods but make them warn.

**Comment by eric-wieser** [comment]
Not sure keeping `iteritems` is enough to be worthwhile, since this can still break any code that expects `items()` in python 3 to return a `list`.

**Comment by ahaldane** [comment]
OK, so that leaves us with 2 options: 1. Just go ahead with the change, or 2. make no change now but add deprecation warnings, then change in 1.16.

It depends on whether we really expect anyone's code to break. A github search suggests people really are using iteritems: https://github.com/search?utf8=%E2%9C%93&q=np.load+iteritems&type=Code
which makes me lean towards deprecation warnings only for now.

**Comment by eric-wieser** [comment]
Can np.load return a raw dict? If so, that code might already be broken on python 3.

**Comment by eric-wieser** [comment]
Alright, updated with deprecation warnings.

This will break code that assumes this works on python 3:

```
the_items = np.load(....).items() + [('test', 1)]
```
but the error message should be clear, and I doubt anyone is doing that.

**Comment by ahaldane** [comment]
OK, this seems backward-compatible enough. Will merge in a little while.

**Comment by eric-wieser** [comment]
@ahaldane: Conflicts solved. Ready to go?

**Comment by ahaldane** [comment]
Yep, looks good. merging.

Thanks Eric!

**Pull request merged**
