### PR TITLE
MAINT: Fix all special-casing of dtypes in `count_nonzero`

### PR DESCRIPTION
**Pull request by eric-wieser**
This is a redo of #7177

Rationale:
* `int.astype(bool)` is marginally faster than `int == 0` (profiled as ~5%)
* `bool.astype(bool, copy=False)` should be comparable to a python `if`
* `apply_along_axis` is slow, and probably loses whatever we gain by avoiding `sum`

I haven't rerun @gfyoung's benchmark suite that came with #7177

This also won't pass until <s>#9848</s>  #9856 is merged

### CODE REVIEW

**Comment by mhvk** [comment]
Looks good to me, if only for the increase in clarity.

**Comment by shoyer** [comment]
Looks like this fails for some dtypes. From Travis:
```
======================================================================
ERROR: numpy.core.tests.test_numeric.TestNonzero.test_count_nonzero_axis_all_dtypes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python3.6/site-packages/numpy/core/tests/test_numeric.py", line 1070, in test_count_nonzero_axis_all_dtypes
    assert_equal_w_dt(np.count_nonzero(m, axis=0),
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python3.6/site-packages/numpy/core/numeric.py", line 413, in count_nonzero
    return a.astype(np.bool_, copy=False).sum(axis=axis, dtype=np.intp)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by eric-wieser** [comment]
@shoyer: That's because there's a bugfix this needed from #9848, as I mention in the description.

However, @ahaldane argued the bugfix needed a deprecation cycle, so I've redone this with a workaround

**Comment by eric-wieser** [comment]
That should hopefully trigger a retest now that #9856 is in

**Comment by eric-wieser** [comment]
@shoyer Tests now pass

**Review by shoyer — APPROVED** [review]

**Comment by eric-wieser** [comment]
I'm struggling to get `asv` to provide useful comparison benchmarks on my machine, frustratingly

**Comment by charris** [comment]
Thanks Eric.

**Comment by eric-wieser** [comment]
Massive improvement for `object` arrays: https://pv.github.io/numpy-bench/#bench_core.CountNonzero.time_count_nonzero_multi_axis.

Maybe the special casing of `bool` was worth having, but the user would do better to call `sum` directly in those cases anyway.

**Comment by eric-wieser** [comment]
Although actually, a performance hit for very large object arrays: https://pv.github.io/numpy-bench/#bench_core.CountNonzero.time_count_nonzero_multi_axis?commits=c2372aff&commits=65828136&commits=36e716ad&idx=11

**Pull request merged**
