### PR TITLE
CI: add pypy

### PR DESCRIPTION
**Pull request by ghost**
This PR adds pypy to the test matrix. It is marked as a failure for now, but will allow measurement of the pypy progress.

### CODE REVIEW

**Comment by eric-wieser** [comment]
@mattip seemed to suggest that #10042 fixes the pypy tests, but maybe I misunderstood that.

**Comment by xoviat** [comment]
IMO this should just be merged since it doesn't actually change any code and allows reviewers to see the results of the pypy tests. #10042 isn't merged yet, so the pypy tests would tend to fail (I can't personally vouch for that PR though).

**Comment by eric-wieser** [comment]
Is there any way to make that test give more useful output? There's not much I can do to track down the problem in:

```
nose version 1.3.7
.......................E....E................S.............................................................................................................................................S.................................E.................S..................................................................................................................................E..............................................................................KKK.EE.EEE.EEEE.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................KK.........................E........S.......................................................F..................................................................................................................................................................................................................................................................................RPython traceback:
  File "pypy_module_pypyjit.c", line 183, in portal_12
  File "pypy_interpreter_2.c", line 35363, in handle_bytecode__AccessDirect_None
  File "pypy_interpreter_2.c", line 46582, in dispatch_bytecode__AccessDirect_None
*** Invalid usage of a dying CPython object ***
cpyext, the emulation layer, detected that while it is calling
an object's tp_dealloc, the C code calls back a function that
tries to recreate the PyPy version of the object.  Usually it
means that tp_dealloc calls some general PyXxx() API.  It is
a dangerous and potentially buggy thing to do: even in CPython
the PyXxx() function could, in theory, cause a reference to the
object to be taken and stored somewhere, for an amount of time
exceeding tp_dealloc itself.  Afterwards, the object will be
freed, making that reference point to garbage.
>>> PyPy could contain some workaround to still work if
you are lucky, but it is not done so far; better fix the bug in
the CPython extension.
./tools/travis-test.sh: line 105:  6158 Aborted                 (core dumped) $PYTHON ../tools/test-installed-numpy.py --mode=full
```

Perhaps run the tests in verbose mode or something so that the actual test names print out?

**Comment by xoviat** [comment]
That test failure appears to be non-deterministic because I couldn't see it in the last test run. Running the tests in verbose mode is an option but not sure that should be done on the CI. Do you want verbose mode for pypy only?

**Comment by eric-wieser** [comment]
Ooh, another approach would be to just [enable `faulthandler`](https://docs.python.org/3/library/faulthandler.html) in the tests, assuming that PyPy has that. That would be generally useful on all test setups.

**Comment by eric-wieser** [comment]
Beat me to it, was about to link to [`nose-faulthandler`](https://pypi.python.org/pypi/nose-faulthandler/0.1)!

**Comment by njsmith** [comment]
I'm generally a fan of "verbose mode" (ie listing test names as they're
run) in non-interactive situations like CI runs. When running locally it's
not a big deal, but given how annoying it is to debug things on Travis, the
more info you get in that initial log, the better.

Enabling faulthandler seems like a useful idea as well – unlikely to hurt
and could be useful sometimes. Some searching suggests that PyPy has at
least some kind of faulthandler support, though it isn't clear to me how
finished it is.

**Comment by eric-wieser** [comment]
Note that the `faulthandler` module is only available on python 3, so I think `nose-faulthandler` needs to be installed conditionally

**Comment by xoviat** [comment]
That's not the problem. `nose-faulthandler` should always be installed, but it's triggering a dependency.

**Comment by xoviat** [comment]
@larsoner Please update `nose-faulthandler` on pypi. In the mean time, I will work around the problem.

**Comment by eric-wieser** [comment]
Hmm, now it seems to hang

**Comment by xoviat** [comment]
Do you want to disable faulthandler then?

**Comment by xoviat** [comment]
Don't look now, but it might be unhung.

**Comment by eric-wieser** [comment]
`faulthandler` seems pretty handy for all the other modes, so I'd be inclined to keep that.

Maybe we should not run the full tests for pypy yet, if that's what's causing it to be slow? Having tests take longer to complete is a pain, and it seems travis won't mark the job as complete even if all the required tests pass.

**Comment by xoviat** [comment]
No, the fact is that pypy is slow for running tests. We could skip it for PRs. Would you prefer that?

**Comment by mattip** [comment]
I should be the last one to criticize, but:
- Travis is running an old version of PyPy, [5.8.0](https://travis-ci.org/numpy/numpy/jobs/304073904#L557) which is considered "old". Version 5.9.0  [released in October](http://pypy.readthedocs.io/en/latest/release-v5.9.0.html) fixes many issues related to running pandas and numpy. Is there a way to make travis use the latest released PyPy like the portable one (runs on most versions of linux) available [here](https://github.com/squeaky-pl/portable-pypy)?
- PyPy3 is still beta-quality, for instance virtualenv does not install on it yet
- doctests will still fail, even after pr #9998 and #10042. Fixing that will require assiging the C-level pointers before calling ``PyType_Ready``, but that is a whole `nother story.

**Comment by xoviat** [comment]
> Travis is running an old version of PyPy, 5.8.0 which is considered "old". Version 5.9.0 released in October fixes many issues related to running pandas and numpy. Is there a way to make travis use the latest released PyPy like the portable one (runs on most versions of linux) available here?

File an issue with Travis CI.

> PyPy3 is still beta-quality, for instance virtualenv does not install on it yet

It passes most of the tests, and I think it should pass nearly all of them when nditer is merged. The goal is to discover bugs in the tests. If it's more likely to fail, that's good.

**Comment by xoviat** [comment]
I don't see this being merged though due to the timing issue.

**Comment by njsmith** [comment]
FTR, there's an example here of fetching and setting up the latest pypy3 release in a travis build script: https://github.com/python-trio/trio/blob/3edfafeedef4071646a9015e28be01f83dc02f94/ci/travis.sh#L52-L62

@mattip not sure what you mean about virtualenv not working on pypy3, you can see in the snippet above that I've been using it for months...

**Comment by xoviat** [comment]
@njsmith Just to be clear, I closed this because people are not going to tolerate pypy taking 30 minutes to finish the tests. That's not unique to numpy; every project that I've seen takes at least two times as long to test.

**Comment by mattip** [comment]
@njsmith virtualenv fails on our 32 bit linux chdir [buildbot](http://buildbot.pypy.org/summary?branch=py3.5) which uses Ubuntu 12.04, and this [travis build](https://travis-ci.org/numpy/numpy/jobs/304176290) also fails.

**Comment by njsmith** [comment]
@xoviat ah, true, that's a discussion we'll probably need to have at some point. 30 minutes seems excessive when most of our tests runs are ~5 minutes -- though I guess you have it running all the slow tests too? The next pypy release should have speedups for cpyext calls that might make a significant difference... or not. Another trick that can be useful is to convince Travis to kick off the pypy run first, since the travis run limit means we're doing 2-3 separate passes to get all the other tests finished.

@mattip ah weird -- it's been fine for me on travis's 64-bit 14.04. Not sure what's going on with that travis build -- the error messages are about cython?

**Comment by mattip** [comment]
You need to open the install step. [This](https://travis-ci.org/numpy/numpy/jobs/304176290#L614) is the correct link to failing virtualenv

**Comment by njsmith** [comment]
@mattip Huh, lots of weird stuff going on there. That's using a pinned old version of virtualenv -- could that be the problem? I wonder if we even still need to do that. And then why doesn't our script notice when the virtualenv call fails. And why do we then `pip install -U virtualenv` *after* we've already set up a virtualenv using an old version...

**Comment by larsoner** [comment]
> Please update nose-faulthandler on pypi.

In principle this is possible. `nose` itself is unmaintained, though, so I am disinclined to maintain the plugin for it. Installing from GitHub should be doable with `pip`, though, and it sounds like you got to that solution anyway.

**Pull request closed without merging**
