### PR TITLE
CI: use version 0.3.26.0.2 of scipy-openblas wheels

### PR DESCRIPTION
**Pull request by mattip**
Now that the wheel versions are pinned, try the latest version (with a single shared object).

Needed for #25505

### CODE REVIEW

**Comment by mattip** [comment]
Something on musllinux is [off](https://github.com/numpy/numpy/actions/runs/7723072436/job/21052421270?pr=25732#step:4:840), the string replacement function `get_library()` is not being called when generating the pkg-config file. Is this from the wheel itself or from the build step...
```
ld: cannot find -l{get_library()}
```

**Comment by mattip** [comment]
Hmm. The older wheels had an empty `Libs:` line when calling `scipy-openblas.get_pkg_config()` (on posix). Then the shared object is not built-in to NumPy, and the `_distributor_init` preloads the shared object into the For the case where we want to replace the tarball with the wheel #25505, we need that line to specify the shared object `Libs: -L${libdir} -lscipy_openblas`. So in this case I think I need an option to `get_pkg_config()` which would only be used in the #25505 case. Then the `scipy-openblas.pc` file would differ depending on the use case.

**Comment by mattip** [comment]
The chosen solution in the scipy-openblas wheels means that the call to `get_pkg_config()` [in spin](https://github.com/numpy/numpy/blob/97773523a4b95ba97469bdc71d1634006f2ed76c/.spin/cmds.py#L568) will need to become `get_pkg_config(use_preloading=True)`, the ones in #25505 can stay with the default argument

**Comment by mattip** [comment]
CI is passing, and meson is using the scipy-openblas wheel-provided pkg-config script, for instance [in muslinux](https://github.com/numpy/numpy/actions/runs/7747912735/job/21129427327?pr=25732#step:4:166) and [windows](https://github.com/numpy/numpy/actions/runs/7747912764/job/21129427114?pr=25732#step:7:82)

**Review by rgommers — APPROVED** [review]
Great, thanks @mattip

**Pull request merged**
