### PR TITLE
MAINT:  Remove duplicates in the exposed API

### LINKED ISSUE #10198: Duplicate entries in np.__all__
These might be symptomatic of having two implementations, where the one that is actually used is determined by the import order (not good).

```python
>>> import collections
>>> {k: v for k, v in collections.Counter(np.__all__).items() if v > 1}
{'alen': 2,
 'all': 2,
 'alltrue': 2,
 'amax': 2,
 'amin': 2,
 'any': 2,
 'argmax': 2,
 'argmin': 2,
 'argpartition': 2,
 'argsort': 2,
 'around': 2,
 'choose': 2,
 'clip': 2,
 'compress': 2,
 'cumprod': 2,
 'cumproduct': 2,
 'cumsum': 2,
 'diagonal': 2,
 'mean': 2,
 'ndim': 2,
 'nonzero': 2,
 'partition': 2,
 'prod': 2,
 'product': 2,
 'ptp': 2,
 'put': 2,
 'ravel': 2,
 'repeat': 2,
 'reshape': 2,
 'resize': 2,
 'round_': 2,
 'searchsorted': 2,
 'shape': 2,
 'size': 2,
 'sometrue': 2,
 'sort': 2,
 'squeeze': 2,
 'std': 2,
 'sum': 2,
 'swapaxes': 2,
 'take': 2,
 'trace': 2,
 'transpose': 2,
 'var': 2,
 'issubdtype': 2}
```

### PR DESCRIPTION
**Pull request by srinivasreddy**
Fixes  #10198

### CODE REVIEW

**Comment by eric-wieser** [comment]
This fixes the symptom, but not the problem - the real issues is that we have files doing

```python
from module_a import *
from module_b import *  # silently overwrites imports from `module_a`
```

**Comment by srinivasreddy** [comment]
May i ask, have you decided which functions to import from which module?

**Comment by eric-wieser** [comment]
I don't understand the question. The first task is just to find out where the duplicates are coming from, and whether they're actually different

**Comment by charris** [comment]
@srinivasreddy What you need to do is identify the duplicates and then determine where they come from.

**Comment by eric-wieser** [comment]
There's an interesting hack you can do using the `__prepare__` method which would look like:
```python
class _imported(metaclass=NoDuplicates):
    from x import *
    from y import *

_imported.extract_to(locals())
__all__ = _imported.__all__
```

Where `NoDuplicates.__prepare__` would return an attribute dict that forbids repeated keys, just like `enum.EnumMeta`

**Comment by eric-wieser** [comment]
Closing in favor of having further discussion back on #10198.

**Pull request closed without merging**
