### PR TITLE
BUG: Prevent crash in poly1d.__eq__

### LINKED ISSUE #8760: numpy.poly1d.__eq__ method fails with AttributeError
I called the `inspect.signature` function on a `numpy.poly1d` object:
```python
import numpy as np
import inspect
poly = np.poly1d([1, 2, 3])
print(inspect.signature(poly))
```
and got an unexpected exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.5/inspect.py", line 2987, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/python3.5/inspect.py", line 2737, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/python3.5/inspect.py", line 2228, in _signature_from_callable
    if _signature_is_builtin(obj):
  File "/python3.5/inspect.py", line 1785, in _signature_is_builtin
    obj in (type, object))
  File "/python3.5/site-packages/numpy/lib/polynomial.py", line 1203, in __eq__
    if self.coeffs.shape != other.coeffs.shape:
AttributeError: type object 'type' has no attribute 'coeffs'
```

So `numpy.poly1d` objects can be compared only to objects with special attributes structure.

The current`__eq__` implementation from [v.1.12.x](https://github.com/numpy/numpy/blob/maintenance/1.12.x/numpy/lib/polynomial.py#L1201-L1204):
```python
def __eq__(self, other):
    if self.coeffs.shape != other.coeffs.shape:
        return False
    return (self.coeffs == other.coeffs).all()
```

numpy version 1.12.0

### PR DESCRIPTION
**Pull request by eric-wieser**
Fixes #8760, and does some cleanup while we're here

### CODE REVIEW

**Comment by eric-wieser** [comment]
The second commit here removes the need for awkward code like https://github.com/scipy/scipy/blob/7a09c8c9658aaaef4be6aade66218a7023465e12/scipy/special/orthogonal.py#L123-L145

**Comment by mhvk** [comment]
Looks good to me! (no comments)

**Comment by charris** [comment]
Thanks Eric.

**Comment by WarrenWeckesser** [comment]
That awkward code is still in scipy, and it crashes after this change. 😞 
Here's the output of one of the scipy tests that uses the master branch of numpy:
```
======================================================================

ERROR: test_assoc_laguerre (test_basic.TestAssocLaguerre)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/special/tests/test_basic.py", line 1068, in test_assoc_laguerre

    a1 = special.genlaguerre(11,1)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/special/orthogonal.py", line 548, in genlaguerre

    lambda x: eval_genlaguerre(n, alpha, x))

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/special/orthogonal.py", line 142, in __init__

    self.__dict__['coeffs'] *= float(kn)

KeyError: 'coeffs'
```

**Comment by eric-wieser** [comment]
I mean, if `scipy` is going to try and modify deliberately read-only properties, then it deserves to crash...

Although I can see that that's not a viable option.

If scipy has decided that these properties are actually read/write, then perhaps so should we?

**Comment by WarrenWeckesser** [comment]
> I mean, if scipy is going to try and modify deliberately read-only properties, then it deserves to crash...

I agree!  I haven't looked too closely at the issue, nor at the shenanigans going on in that awkward code.  But I guess the `ValueError` the results from attempting to change the coefficients by modifying `coeffs` in place should have been a warning to whoever wrote the code that bypassing the read-only-ness was fraught with peril:

```
In [6]: np.__version__
Out[6]: '1.12.0'

In [7]: p = np.poly1d([1, 2, 3])

In [8]: p.coeffs *= 3
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-4fc1bf5fa199> in <module>()
----> 1 p.coeffs *= 3

/Users/warren/anaconda/lib/python2.7/site-packages/numpy/lib/polynomial.pyc in __setattr__(self, key, val)
   1208 
   1209     def __setattr__(self, key, val):
-> 1210         raise ValueError("Attributes cannot be changed this way.")
   1211 
   1212     def __getattr__(self, key):

ValueError: Attributes cannot be changed this way.
```
And yet, they change...

```
In [9]: p.coeffs
Out[9]: array([3, 6, 9])
```

**Comment by eric-wieser** [comment]
Ooh, that's an exciting bug with both the new and old implementation

What's happening is that `p.coeffs *= 3` translates to

    temp = p.coeffs
    temp *= 3   # actually modify the data
    p.coeffs = temp  # errors

Perhaps another argument to make it read/write?

**Comment by charris** [comment]
That's why the numpy polynomial classes are immutable and don't implement inplace operators.

**Comment by eric-wieser** [comment]
@charris: Doesn't matter if `poly1d` doesn't implement inplace operators, if its fields do

**Comment by charris** [comment]
Oh, that's right. In fact, the polynomial classes do allow modification of the coefficients, but it was a deliberate decision. I was tempted to make them private, but took the python route: we are all grown ups here, do what you please, but don't do that ;)

**Comment by eric-wieser** [comment]
>  In fact, the polynomial classes do allow modification of the coefficients

**Comment by charris** [comment]
Yep, those are the classes I was referring to. I recall having that discussion with someone who wanted to modify the coefficients and telling him it was not recommended, but I left the possibility open because someone who knew what they were doing might want that option.

**Comment by eric-wieser** [comment]
> someone who knew what they were doing might want that option.

The issue is not whether that someone knows what they are doing, but whether they know what the developers of the library expect them to be doing.

Either way, on the topic at hand - is making `coeffs` a plain attribute a reasonable solution?

**Comment by charris** [comment]
Looks like the only way to keep scipy working is to leave the attributes in the dictionary. The code in `class orthopoly1d` is really ugly and needs fixing, but I don't see how we can block that access in the current code with something harmless, like a deprecation warning. One suspects that it was intended to bypass the (inconvenient) safeguards. In any case, the scipy fix could be as simple as calling `poly1d` to get the coefficients *before* initializing the base class, adjusting them as needed, and then do the initialization. 

After that, eventually we should be able to use the really nice cleanup in this PR.

**Comment by eric-wieser** [comment]
@charris: Am I correct in thinking that old scipy needs to work with new numpy, and new scipy needs to work with old numpy?

**Comment by eric-wieser** [comment]
@charris: Ok, changes made:

* to numpy to work before and after a fix to scipy (#8788) 
* to scipy to work before and after a fix to numpy(#7184)

**Comment by eric-wieser** [comment]
> the scipy fix could be as simple as calling poly1d to get the coefficients before initializing the base class

Not as easy as that, sadly. Unfortunately, there is a `orthopoly1d._scale` method, that mutates the object deliberately. So either way, we're stuck with an immutable-but-not-really property

**Pull request merged**
