### PR TITLE
ENH: Change f2c declarations with void return type to int

### PR DESCRIPTION
**Pull request by hoodmane**
When using f2c, the generated C functions for all of these actually
return int. WebAssembly is strict on return types and will crash due
to the discrepancy.

This is split off from #21772, I think this is a straightforward improvement
to the accuracy of the header files.

### CODE REVIEW

**Comment by charris** [comment]
@eric-wieser Thoughts?

**Comment by charris** [comment]
I suppose the real question is: what do the actual functions return?

**Comment by hoodmane** [comment]
I think these symbols are f2c-specific since I find them in many C files generated by f2c, in headers related to f2c, and in object files generated with f2c. When I compile the same Fortran files with gfortran and pass `-fdump-tree-all`, neither the resulting object files nor any of the intermediate IR contain any reference to any of these symbols.

The issue is related to alternate returns:
https://gcc.gnu.org/onlinedocs/gcc-3.4.6/g77/Alternate-Returns.html
Depending on the way the ABI works, I think functions are expected to return `int` in order to indicate which alternate return they use. f2c just makes every `void` function into an `int` function in case it has an alternate return without bothering to check which it does.

Each f2c function will have at the beginning a section like:
```C
    /* Builtin functions */
    integer s_cmp(char *, char *, ftnlen, ftnlen), s_wsfe(cilist *), e_wsfe(
	    void), do_fio(integer *, char *, ftnlen);
```
where you can clearly see that these functions return ints.

**Comment by charris** [comment]
> neither the resulting object files nor any of the intermediate IR contain any reference to any of these symbols.

In that case it is probably safe to put this in. I wonder if `void` was too late an addition to C to make it into f2c?

**Comment by charris** [comment]
Let's give it a shot. Thanks @hoodmane .

**Pull request merged**
