### PR TITLE
MNT: Remove `set_string_function`

### LINKED ISSUE #26576: MNT: ``np.set_string_function`` implementation should be removed
@mtsokol removed `set_string_function` from the public API in #24376, but the code and underlying C implementation are still in the codebase. The python version is marked as deprecated but the equivalent C API isn't.

We should replace the usages in docstrings with `printoptions` and remove it from the codebase. This also includes the public C API function `PyArray_SetStringFunction` which we may need to just stub out but leave behind for API stability, unfortunately this was missed for 2.0. A [github search](https://github.com/search?q=PyArray_SetStringFunction) finds no usages outside of numpy itself or re-exports of the numpy C API.

The main reason I'd like to do this is this API is implemented using global variables and is not thread-safe. There's no reason to update code to be thread safe if it's private and only needed for a deprecated function that is no longer public.

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @ngoldbaum,

This PR removes `set_string_function` and makes `PyArray_SetStringFunction` throw a "was removed" exception when called. 

`__str__` in `numpy.ndarray` class can be still altered with `set_printoptions`. `__repr__` can't be modified by a user with the Python or C API.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Needs a release note. You also missed spots the C function still shows up:

```
numpy/__init__.pxd
526:    void PyArray_SetStringFunction (object, int)

doc/source/reference/c-api/types-and-structures.rst
223:    methods can also be altered using :c:func:`PyArray_SetStringFunction`.

doc/source/reference/c-api/array.rst
4083:.. c:function:: void PyArray_SetStringFunction(PyObject* op, int repr)

numpy/__init__.cython-30.pxd
611:    void PyArray_SetStringFunction (object, int)
```

Maybe also add a note or comment to `numpy/_core/code_generators/numpy_api.py` above the entry for the function that it is stubbed out and should be removed in the future.

> __repr__ can't be modified by a user with the Python or C API.

That's not true is it? You can use `printoptions` to override how the repr appears too:

In [1]: with np.printoptions(formatter={"all": lambda x: "hello"}):
   ...:     print(repr(np.array([1, 2, 3])))
   ...:
array([hello, hello, hello])

**Comment by mtsokol** [comment]
> That's not true is it? You can use `printoptions` to override how the repr appears too:
> 
> ```
> In [1]: with np.printoptions(formatter={"all": lambda x: "hello"}):
>    ...:     print(repr(np.array([1, 2, 3])))
>    ...:
> array([hello, hello, hello])
> ```

I think there's no need to dig into it so let's say that we can override `repr`/`str` sufficiently with `printoptions`.

With `set_string_function`, that we're removing, we can override whole `repr`, not only elements `repr` (but I guess it's a redundant feature):

```python
In [104]: a = np.array([[1,2,3]])

In [105]: a
Out[105]: array([[1, 2, 3]])

In [106]: np.set_string_function(lambda x: "hello")

In [107]: a
Out[107]: hello
```

**Comment by ngoldbaum** [comment]
Yeah, I think `printoptions` replaces all the actually useful use cases. If anyone really wants to override how we lay out printing arrays they can do that themselves.

**Comment by mtsokol** [comment]
Done!

**Review by ngoldbaum — APPROVED** [review]
LGTM. @seberg @mattip are you ok with having a stubbed-out C API function like this?

In [a GitHub search](https://github.com/search?q=PyArray_SetStringFunction%28&type=code) I see no uses outside of copies of numpy and re-exports and listings of the numpy C API.

**Comment by ngoldbaum** [comment]
I do see one downstream project trying to work around us removing the ability to completely override the print formatting for the entire array:

https://github.com/napari/napari/pull/6776

They ended up deciding to set `edgeitems` so the array size is limited in the printed output, but it's not quite the same as what they had before.

That said, maybe printoptions could grow an option to override printing the entire array?

**Comment by mattip** [comment]
Since we began deprecating this in 2.0, I think we need to wait for 2.2 to remove it, no?

**Comment by ngoldbaum** [comment]
The C-level function was never deprecated but the python-level function was removed from the public API in NumPy 2.0, skipping the deprecation.

It seems odd to me to have the Python function gone from the public API but to insist on a long deprecation period for the C-level function that is used much less often.

**Comment by seberg** [comment]
> It seems odd to me to have the Python function gone from the public API but to insist on a long deprecation period for the C-level function that is used much less often.

FWIW, the deprecation warning should have been implemented to include the C-side, but the normal deprecation policy is 2 (or maybe even 3 in this case) releases (1 year).
I don't care too much about bending that here, it isn't a typical end-user function.  But what is the reason?

**Comment by ngoldbaum** [comment]
It looks like it was deprecated first, then quickly removed before the deprecation was in a release (the comment says it was deprecated in numpy 2.0). I think it was included in the general API cleanup, @mtsokol might remember the details about why it was included for removal so quickly after being deprecated. I don't remember thinking too carefully about this one during review.

**Comment by seberg** [comment]
> It looks like it was deprecated first, then quickly removed before the deprecation was in a release

I am confused:  This PR would be the one to remove it, no?  Giving us a very brief deprecation period on the Python function.

I am happy to ignore the C version, and had we done it in 2.0, I would have been happy to just do it probably.
But now it does seem a bit like there is no reason to not just wait for 2.2 at least, so I am -0.0 for finalizing the deprecation so quickly?

**Comment by mtsokol** [comment]
> It looks like it was deprecated first, then quickly removed before the deprecation was in a release (the comment says it was deprecated in numpy 2.0). I think it was included in the general API cleanup, @mtsokol might remember the details about why it was included for removal so quickly after being deprecated. I don't remember thinking too carefully about this one during review.

I think we just made a decision during one of the meetings to put this function in the "remove" group for 2.0 and removed it: https://github.com/numpy/numpy/issues/24306 (See `Details`).

So `set_string_function` was removed from the main namespace without a deprecation period (the error message says what should be used instead), and we didn't touch C's `PyArray_SetStringFunction` at all. This PR removes `set_string_function` implementation and stubs out `PyArray_SetStringFunction`.

> That said, maybe printoptions could grow an option to override printing the entire array?

Sure, then there would be a new option `override_repr` or something in `np.set_printoptions` that accepts a callable and completely replaces how arrays are printed, replicating `set_string_function` functionality.

**Comment by seberg** [comment]
Aha, so the point is that it was effectively already removed in 2.0 because it only exists as a private function.

**Comment by mtsokol** [comment]
> That said, maybe printoptions could grow an option to override printing the entire array?

@ngoldbaum I added `override_repr` option that allows defining custom `repr(...)`, which replicates:
```python
np.set_string_function(lambda x: "FOO", repr=True)
```

**Comment by seberg** [comment]
One thing we forgot yesterday:  This needs a release note for the C-API change at least.

**Comment by ngoldbaum** [comment]
Sorry for taking a little while to merge this one. Let's bring this in and thanks for finishing up the work on this deprecation/removal @mtsokol!

**Comment by seberg** [comment]
I can see the use of adding it, but hadn't realized it was added in this PR. If we add `override_repr` we should have a relase note for that, and that is also a place to give anyone a chance to bike-shed names.

**Comment by mtsokol** [comment]
Sure! Let me tweak the release note separately.

**Comment by alexanderswerdlow** [comment]
Thanks for adding this functionality back with `override_repr`!

Just wanted to note that at least one other project that relies on this feature: [lovely-numpy](https://github.com/xl0/lovely-numpy), and I personally also have a [hackier version](https://github.com/alexanderswerdlow/image_utils/blob/511d72c841dc732dd529c3627b0fab0466e622c6/src/image_utils/custom_library_ops.py#L54), so it's great that it's being left in .

Very useful to be able to quickly see array information in one glance :)

**Pull request merged**
