### PR TITLE
BUG: try to keep array ordering in expand_dims

### PR DESCRIPTION
**Pull request by MicK7**

### CODE REVIEW

**Comment by MicK7** [comment]
Currently calling the reshape without specifying the order assumes that you want C ordering as expand_dims output.
It is not clearly stated in  the function documentation. Thus I deduce that it is legit for the user to expect that the returned array ordering is not changed compared to the original one.
I just use the flags to check the input array ordering.
As I am not a numpy expert there may be a better way to achieve that.

**Comment by seberg** [comment]
Sorry, but the memory order is already unchanged.  The only thing your code change influences is the `result.strides` but _not_ the contuity as reported by `result.flags`.
See also https://numpy.org/doc/stable/reference/arrays.ndarray.html?highlight=relaxed#internal-memory-layout-of-an-ndarray which explains these added size 1 dimensions don't matter to contiguity (just below the formulas).

So as far as I can tell, you still only change the `result.strides` and NumPy makes no general guarantees about them here.  So I am tempted to not worry about it, but willing to hear why it matters.  (Or what I am missing.)

**Comment by MicK7** [comment]
Oh thank you so much for taking the time to answer.
Indeed, I will close this PR because the issue was on my side as I was relying on result.strides.
So sorry for the bad PR, I should have check twice before commiting.

**Comment by seberg** [comment]
No worries.  strides and contiguity are confusing, it took years to untangle it fully again!

**Pull request closed without merging**
