### PR TITLE
ENH: Make `ndarray` generic w.r.t. its shape and dtype

### LINKED ISSUE #16545: Typing support for dtypes
Per https://github.com/numpy/numpy/issues/7370#issuecomment-346126667, we could specify dtype as part of ndarray types (including type inference) by using NumPy's [scalar types](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.scalars.html), e.g., `np.ndarray[Any, np.float64]` or `np.ndarray[np.float64, Any]` (where `Any` indicates the shape).

Is this a good way to indicate dtypes? How would we handle dtypes that don't have a well specified scalar type? For example:
- `datetime64` and `timedelta64` do not have precision as part of the type
- [`np.void`](https://stackoverflow.com/questions/25247190/numpy-void-type-how-to-use-it) is used for all arbitrary structured dtypes, but doesn't indicate the field names or subtypes (side note: `np.struct` would be a much better name)
- string dtypes have their size as part of the type

One simple answer is to not worry about more detailed type information for now, and worry about more precise specification for scalar types later, when support in the typing module becomes available (e.g., for integer types or custom struct-like data structures like `TypedDict`).

### LINKED ISSUE #16547: Order of generic types for ndarray
Per https://github.com/python/typing/issues/516, it seems likely that we will have a choice between two ways to write type hints:
1. `ndarray[Dtype, Shape]`
2. `ndarray[Shape, Dtype]`

We'll probably have two generic arguments, but will have the freedom to choose in which order they appear. Do we have any reason to prefer one order over the other?

One weak argument in favor of `[Shape, Dtype]` is that it matches `ndarray.__new__` (but that's so rarely used that it probably doesn't matter).

### PR DESCRIPTION
**Pull request by BvB93**
Closes https://github.com/numpy/numpy/issues/16545; closes https://github.com/numpy/numpy/issues/16547.

Well folks, it's finally here: this pull requests makes the `np.ndarray` class generic w.r.t. its 
shape and dtype: `np.ndarray[~Shape, ~DType]`. The shape's bound is currently set
to `Any` (see "Non-Goals") while the dtype's bound is set to `np.dtype`.

~The "generification" of `np.ndarray` is accompanied by the addition of three types to the public 
API of `numpy.typing`, all of which are subscriptable during runtime (similar to the likes of 
`typing.Sequence[~T]`):~
* ~`NDArray`: A generic version of `np.ndarray[~Shape, ~DType]`.~
* ~`DType`: A generic version of `np.dtype[~Scalar]`.~
* ~`ArrayND`: A shortcut for `np.ndarray[Any, np.dtype[~Scalar]]`. I imagine that, at some point in 
  the future, we can expand this with the likes of `Array0D`, `Array1D`, `Array2D`, _etc._.~

Non-Goals
-----------
* EDIT: Providing runtime-subscriptable aliases for `ndarray`, similar to the likes of 
  `collections.abc.Sequence` versus `typing.Sequence`. This will be reserved for a future 
  PR as the exact details might warrant some further discussion.
* We currently lack the tools to properly type the ndarray's shape (_i.e._ we lack variadics).
  As the `~Shape` bound is likelly to change in the future it is recommended to type it as `Any` (for now).
  See https://github.com/numpy/numpy/issues/16544 for the discussion on shape typing.
* The various functions and methods in numpy currently lack the necessary overloads to the utilize 
  the arrays dtype (for now!). This is considered work for future PRs due to the jobs sheer size.

### CODE REVIEW

**Comment by shoyer** [comment]
This is great to see!

A few questions/concerns:

1. Why `NDArray[~Shape, ~DType]` instead of `NDArray[~Shape, ~Scalar]`?
2. In principle, `Array0D`, `Array1D`, etc, could be fine, but the similarity of the names `NDArray` and `ArrayND` feels a little confusing to me. I wonder if we could think of another name?

**Comment by BvB93** [comment]
@shoyer 
1. This was based on earlier discussion in https://github.com/numpy/numpy-stubs/pull/48. The main concern was that the scalar types (hierarchy) might not always be quite enough on its own, especially with the big dtype update of NEP 41 & 42 in mind. Making `ndarray` generic w.r.t. `np.dtype` instead of `np.generic` thus provides us a bit more flexibility.
2. I see your point, Yes. Perhaps something along the lines of `SimpleNDArray` or `SimpleArray`? 
  If anyone has a suggestion here, feel free to chime in.

**Comment by a-reich** [comment]
Hi, since you were soliciting thoughts on the naming, how about `ArrayAnyShape` or `ArrayUnshaped`?

**Comment by BvB93** [comment]
So for now I've removed the generic aliases (`NDArray`, `ArrayND`, _etc._) from this PR.
As they might warrant some additional discussion, they'll be reserved for a follow-up (and I'd like to get this PR merged ASAP in 1.21).

**Comment by charris** [comment]
Thanks Bas.

**Comment by stefanv** [comment]
Do we have some user-facing documentation to guide in usage of these annotations?

**Comment by BvB93** [comment]
@stefanv There is the [`numpy.typing`](https://numpy.org/devdocs/reference/typing.html) docs page, though nothing specifically for `ndarray[~Shape, ~DType]` yet, as this PR was just aimed at making `ndarray` a parametrized generic. I'm planning on exposing a runtime-subscriptable version of `np.ndarray` soon, something which I'd like to accompany with a documentation update.

**Comment by janosh** [comment]
@BvB93 This is great work! Thanks for pushing `numpy.typing`!

I don't have a good overview though. What's the status quo? Is it possible to type hint the dimensionality of an array? Or even the specific shape?

**Comment by forrestbao** [comment]
PEP 646 has been added to Python 3.11 now. So any update from Numpy side?

**Comment by muxator** [comment]
This interests me too. The most recent python version is 3.12 now. Is there a place to follow the discussion on making `ndarray` parametric wrt its shape?

**Comment by Jacob-Stevens-Haas** [comment]
@muxator, see #26081

**Pull request merged**
