### PR TITLE
BUG: dot/matmul 'out' arg should accept any ndarray subclass

### LINKED ISSUE #9641: Why does np.dot does not work with memmaped output array?
Executing:

```
a = np.ones((10,1))
b = np.ones((10,1))
c = np.memmap('zeros.mat', dtype=np.float64, mode='w+', shape=a.dot(b.T).shape, order='C')

a.dot(b.T, out=c)
```
Gives error:
ValueError: output array is not acceptable (must have the right type, nr dimensions, and be a C-Array)

But:

```
print(a.dtype == b.dtype == c.dtype)
print(np.dot(a, b.T).shape == c.shape)
print(c.flags['C_CONTIGUOUS'])
```

Returns:
True
True
True

### PR DESCRIPTION
**Pull request by ahaldane**
Fixes #9641

### CODE REVIEW

**Comment by eric-wieser** [comment]
Error messages need fixing too

**Comment by ahaldane** [comment]
Error messages updated

**Comment by eric-wieser** [comment]
The `/* Choose which subtype to return */` stuff can move within the `out == NULL` branch now too

**Comment by eric-wieser** [comment]
Do you want to wait on #9209 before finishing this off?

**Comment by ahaldane** [comment]
yeah let's wait

**Comment by ahaldane** [comment]
Rebased, and updated to use the recently defined `PyArray_GetSubType`.

I moved `PyArray_GetSubType` to `ctors.c` and added a declaration in `ctors.h` so it is visible across numpy C files.

(One slight difference in the new code is that I no longer use one of the input arrays as the "template" argument used in `__array_finalize__` (last arg of PyArray_New/FromDescr). I think it is more correct now).

**Comment by eric-wieser** [comment]
A little worried that not using one of the arrays as a template argument is a compatibility break, even if it wasn't necessarily good design before. Otherwise looks good

**Comment by eric-wieser** [comment]
Yeah, I suspect this stops working:

```
>>> a = np.ma.array(np.eye(3))
>>> a._optinfo['x'] = 1
>>> np.dot(a, a)._optinfo
{'x': 1}
```

Which it seems people care about (#9279)

**Comment by ahaldane** [comment]
Yeah, you're right. I removed the last commit.  (We also lose all the other info like the fillvalue).

The PR summary is now:
 * Removed check for subtype of out argument
 * moved (cut-n-paste) the subtype calculation into an else statement

**Comment by eric-wieser** [comment]
Thanks!

**Pull request merged**
