### PR TITLE
TYP, MAINT: Relax the `obj` type in `__array_finalize__`

### PR DESCRIPTION
**Pull request by BvB93**
The `ndarray.__array_finalize__` method as implemented in numpy can accept accept any arbitrary object. 
This is now reflected in the annotations of all `ndarray` subclasses. 

Note that this excludes the `ndarray` baseclass itself, as `__array_finalize__` behaves here as a sort of pseudo-
abstract method and widening the type to `object` would force all third-party subclasses to do the same.

### CODE REVIEW

**Comment by seberg** [comment]
@BvB93 I am a bit confused about what we actually pass as "object" here.  Isn't it guaranteed to be a NumPy array (or subclass)? – I am honestly not sure, I know `.view()` gets here eventually, and `__new__`, but both of those always pass an `ndarray` or subclass?

**Comment by BvB93** [comment]
> @BvB93 I am a bit confused about what we actually pass as "object" here. Isn't it guaranteed to be a NumPy array (or subclass)? – I am honestly not sure, I know `.view()` gets here eventually, and `__new__`, but both of those always pass an `ndarray` or subclass?

In practice, I doubt that anything other than an `ndarray` (or maybe `None`) is passed along for the exact reasons that you stated above. With the way that `__array_finalize__` is implemented for the various `ndarray` subclasses (_i.e._ via carefull checking of attributes), it does mean that it _could_ in principle accept any object and still produce a sensible result. 

This is most clearly demonstrated by `chararray.__array_finalize__`, which doesn't even utilize the passed `obj`:
https://github.com/numpy/numpy/blob/73e48ae177c4b29cdbdbcfd39e22cf5de6c7f125/numpy/core/defchararray.py#L1980-L1983

**Comment by seberg** [comment]
If this was on an ABC, it would say `None | array-subclass` (to document the protocol), I think?  Should the protocol/ABC implementation relax the ABCs annotation in such a case?

I still surprised that this advertises "supported usage" rather than inheriting the tighter "correct protocol usage".  But I am not concerned, so happy to put this in.  (Please feel free to just self-merge.)

**Comment by BvB93** [comment]
> If this was on an ABC, it would say `None | array-subclass` (to document the protocol), I think?

I agree, and the `ndarray` _baseclass_ is treated exactly as such here. For the subclasses on the other hand I'd argue that they can be treated much more akin to concrete classes, and hence I don't forsee any problems with widening the parameter type to `object` (matching runtime behavior).

**Pull request merged**
