### PR TITLE
BUG: Fix common block handling in f2py

### LINKED ISSUE #22648: BUG: crackfortran.py fails with 'common' blocks with Numpy version > 1.20
### Describe the issue:

It seems Fortran 77 'COMMON' blocks are not matched correctly. I got the following error message:

crackline: groupcounter=1 groupname={0: '', 1: 'python module', 2: 'interface', 3: 'block data', 4: 'subroutine'}
crackline: Mismatch of blocks encountered. Trying to fix it by assuming "end" statement.

Following code causes the error:

python module iri16py ! in 
    interface  ! in :iri16py
        block data  ! in :iri16py:iridreg_modified.for
           COMMON /fircom/ eden,tabhe,tabla,tabmo,tabza,tabfl
       end block data 
    end interface 
end python module iri16py

Unfortunately all interface signature code after the common block will be ignored. With Numpy <= 1.20 it runs smooth. All versions above causes this error. If I document out the 'common' line all behaves fine. Please fix that soon. I tried to find out the reason in crackfortran.py, but it seems a bit too complex for me.
f2py seems also to be fine if one removes the space between end block data -> end blockdata.

### Reproduce the code example:

```python
f2py following code:
python module iri16py ! in 
    interface  ! in :iri16py
        block data  ! in :iri16py:iridreg_modified.for
           COMMON /fircom/ eden,tabhe,tabla,tabmo,tabza,tabfl
       end block data 
    end interface 
end python module iri16py
```

### Error message:

```shell
crackline: groupcounter=1 groupname={0: '', 1: 'python module', 2: 'interface', 3: 'block data', 4: 'subroutine'}
crackline: Mismatch of blocks encountered. Trying to fix it by assuming "end" statement.
```

### NumPy/Python version information:

1.21 and above

### Context for the issue:

I use a Python module which make use of old Fortran 77 code. Since f2py ignore all signature code after the COMMON block, the Python module routine gets not compiled in and the load of module fails. Without a fix to this issue I am forced to stay at Numpy 1.20 but I would like to update.

### PR DESCRIPTION
**Pull request by HaoZeke**
Closes #22648.

The issue is that some part of the parser updates the `groupcounter` when it shouldn't.

EDIT: The actual issue can be traced to https://github.com/numpy/numpy/commit/e6dab4ff15f25793c81b808d49d5359b8901809f where the parser was updated to include the Fortran 2008 block construct, which is used in several other places in the file and caused the issue.

### CODE REVIEW

**Comment by seberg** [comment]
This looks like it really is all there is to it?   Can you just copy the failing example from the issue as a test?

**Comment by HaoZeke** [comment]
> This looks like it really is all there is to it? Can you just copy the failing example from the issue as a test?

It did, but then I noticed some of the other parts of the code depend on hard-coded values of this, so I'm not sure incrementing the counter doesn't introduce additional bugs. Will take a closer look soon.

**Comment by HaoZeke** [comment]
The actual issue can be traced to https://github.com/numpy/numpy/commit/e6dab4ff15f25793c81b808d49d5359b8901809f where the parser was updated to include the Fortran 2008 `block` construct, which is used in several other places in the file and caused the issue.

Adding a test to get this through.

**Comment by HaoZeke** [comment]
A better fix would be to change the variable names so the `block` Fortran 2008 construct can be recognized within `crackfortran`, however since there's no support for it anyway, and it would be a rather large change, this seems like the best approach for now.

**Comment by HaoZeke** [comment]
@charris this bug is present from `1.21.0` onwards, including the release candidates, and the fix might need a backport?

**Comment by mattip** [comment]
ping @pearu or anyone else from the f2py team for a review

**Comment by HDembinski** [comment]
I did a crude check of this PR on my setup. Crude means: I did not install this version of numpy, but I used my existing numpy installation 1.23.5 and replaced the folder f2py with the one from this PR. I used this workaround successfully before, using the f2py folder from numpy 1.19.5, which allows me to compile our project.

Unfortunately, this patch here does not seem fix everything. It definitely fails less, but I still get an error on one of our fortran codes:
```
Line #61 in CMakeFiles/_phojet191.dir/PHO_PRIMKT.f:"      PARAMETER (IRMAX=200)"
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
	Reading file 'CMakeFiles/_phojet191.dir/PHO_PRSTRG.f' (format:fix,strict)
	Reading file '/Users/hdembinski/Extern/chromo/src/fortran/dpmjetIII-19.1/include/phojet/inc/poinou' (format:fix)
	Reading file '/Users/hdembinski/Extern/chromo/src/fortran/dpmjetIII-19.1/include/phojet/inc/podebg' (format:fix)
	Reading file '/Users/hdembinski/Extern/chromo/src/fortran/dpmjetIII-19.1/include/phojet/inc/poevt1' (format:fix)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/hdembinski/Extern/chromo/venv/lib/python3.10/site-packages/numpy/f2py/__main__.py", line 5, in <module>
    main()
  File "/Users/hdembinski/Extern/chromo/venv/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 704, in main
    run_main(sys.argv[1:])
  File "/Users/hdembinski/Extern/chromo/venv/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 441, in run_main
    postlist = callcrackfortran(files, options)
  File "/Users/hdembinski/Extern/chromo/venv/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 342, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/Users/hdembinski/Extern/chromo/venv/lib/python3.10/site-packages/numpy/f2py/crackfortran.py", line 3300, in crackfortran
    readfortrancode(files, crackline)
  File "/Users/hdembinski/Extern/chromo/venv/lib/python3.10/site-packages/numpy/f2py/crackfortran.py", line 552, in readfortrancode
    dowithline(finalline)
  File "/Users/hdembinski/Extern/chromo/venv/lib/python3.10/site-packages/numpy/f2py/crackfortran.py", line 819, in crackline
    raise Exception('crackline: groupcounter(=%s) is nonpositive. '
Exception: crackline: groupcounter(=0) is nonpositive. Check the blocks.
```
Sorry, I cannot give a minimal reproducer, the fortran codes which we wrap are very complex and I am not an expert. If you want to try it out yourself, you can get the code from git@github.com:impy-project/chromo.git. Compile with `python setup.py develop`. You need cmake, setuptools, wheel, numpy and gcc/gfortran.

**Comment by HDembinski** [comment]
I would like to test this PR locally on chromo, but when I try to check this branch out locally, I get this error
```
From https://github.com/numpy/numpy
 ! [rejected]            refs/pull/22657/head -> fix22648  (non-fast-forward)
failed to run git: exit status 1
```
I am not sure how this fix.

**Comment by HDembinski** [comment]
Firstly, I am extremely grateful to @HaoZeke for trying to figure this out.

We are testing this PR over here in our project https://github.com/impy-project/chromo/pull/127

Unfortunately the latest version still does not work on the module `_phojet191` that we build among other things. I provided instructions over at https://github.com/impy-project/chromo/pull/127 on how to build just this offending module (we normally build many more), to simplify testing/debugging this issue.

**Comment by charris** [comment]
Needs a rebase. @HaoZeke @pearu Thoughts on getting the problem fixed?

**Comment by charris** [comment]
Needs rebase.

**Comment by charris** [comment]
Needs rebase.

**Comment by afedynitch** [comment]
Hi,
our project [project](https://github.com/impy-project/chromo/pull/127) heavily relies on f2py to wrap around legacy fortran code. Things went smooth until numpy 1.19, then the interface file generation got broken and we distributed [the interface file generated with 1.19](https://github.com/impy-project/chromo/tree/main/src/f2py) to fix builds with np <1.24. It's bad design but we had no choice. Due to changes in numpy 1.24, we can't reuse the interface files. Unfortunately, f2py in current 1.24 remains broken since the generated interface files produce only partially wrapped libraries . They have more content than 1.20 ... 1.23 but still are incomplete. @HDembinski figured out that just replacing crackfortran.py with that from 1.19 fixes the problem, and we can potentially develop a hackish fix, if this doesn't get resolved timely.

What is the status on this PR? Has it been decided to fix it and backport to <1.24?

**Comment by charris** [comment]
@afedynitch @HDembinski I'm happy to put this in and backport if it solves the problem.

@HaoZeke Could to spend some time on this?

**Comment by HaoZeke** [comment]
> @afedynitch @HDembinski I'm happy to put this in and backport if it solves the problem.
> 
> @HaoZeke Could to spend some time on this?

Sorry, forgot to finish this up. I'll look into it this week.

**Comment by jncots** [comment]
Hi, I'm one of the core devs of the chromo package mentioned above. In the attached zip file you can find an example, how the xx_module.c and f2pywrappers.f file generation fails on one of our legacy codes when going from 1.19 to 1.24. It may help @HaoZeke to track down the origin of the problem.
[f2py_chromo_problem.zip](https://github.com/numpy/numpy/files/11623285/f2py_chromo_problem.zip)

**Comment by charris** [comment]
@HDembinski @afedynitch  could you test this?

@HaoZeke I think a rebase will fix the test failure on azure.

**Comment by HDembinski** [comment]
We are currently testing it, much thanks to @HaoZeke 

Side-comment: considering how complex the crackfortran code is, it may be a good target for a rewrite using a formal parser. I personally had only good experiences with the lark library in Python, which allows you to specify the rules in EBNF notation. Lark can generate a standalone parser in Python from this spec, so client code does not even need the lark library as a dependency. I just leave this here as a note.

**Comment by charris** [comment]
@HDembinski Any success? I'd like to get this in before the 1.25 release if it works.

**Comment by afedynitch** [comment]
@charris In most cases, this seems to work. We identified a problem that [happens only on Windows](https://github.com/impy-project/chromo/pull/127#issuecomment-1579874551), whereas the same code parses well on mac and linux, and was parsing fine on pre-1.20 on Windows. Also, we have seem some changes to the interface that were easy to fix but we were wondering if they are intentional, such as a difference the interpretation of [character* arrays](https://github.com/impy-project/chromo/pull/127#issuecomment-1581879904).

Except that Windows problem, which I believe is a bug, the other issues are not a problem for us but may break some  backward compatibility.

**Comment by HDembinski** [comment]
@afedynitch is currently handling this so I don't have the full overview. As far as I understand, we may be able to deal with it on our end by making code changes, but it is still a regression: the code we had is parsed in a different way and that requires adaptations in both the legacy Fortran and in the Python code.

**Comment by afedynitch** [comment]
> @HDembinski Would it be helpful to put this in as is?

Yes, the present version solves most of our problems. But the windows issue might be a bug that you wouldn't want to put in, I guess. Maybe this is some sort of encoding issue, but it wasn't there with previous versions. Better if @HaoZeke can look at it shortly once more.

**Comment by charris** [comment]
Sounds like there are still some problems. @HaoZeke Could you revisit this?

**Comment by charris** [comment]
@pearu Thoughts?

**Comment by afedynitch** [comment]
@HaoZeke @charris @pearu Any new thoughts or progress on this?

**Comment by HaoZeke** [comment]
> @HaoZeke @charris @pearu Any new thoughts or progress on this?

I think the windows issue should be reported separately, and we should go ahead with this. There are some other open PRs with fixes for `f2py` which might also help windows, but none specifically (no reproducible bug reports yet).

**Comment by mattip** [comment]
@HaoZeke Could you relate to the comment that 
> [W]e have seem some changes to the interface that were easy to fix but we were were wondering if they are intentional, such as a difference the interpretation of [char* arrays](https://github.com/impy-project/chromo/pull/127#issuecomment-1581879904.

**Comment by HaoZeke** [comment]
> @HaoZeke Could you relate to the comment that
> 
> > [W]e have seem some changes to the interface that were easy to fix but we were were wondering if they are intentional, such as a difference the interpretation of [char* arrays]([impy-project/chromo#127 (comment)](https://github.com/impy-project/chromo/pull/127#issuecomment-1581879904).

The change in interpretation was part of https://github.com/numpy/numpy/pull/19388 and is also related to https://github.com/numpy/numpy/issues/24008 which should be fixed by https://github.com/numpy/numpy/pull/24299. These are however separate from the common block handling and shouldn't be covered here.

**Comment by afedynitch** [comment]
> I think the windows issue should be reported separately, and we should go ahead with this. There are some other open PRs with fixes for `f2py` which might also help windows, but none specifically (no reproducible bug reports yet).

Thanks @HaoZeke for fixing the issue!

Indeed, you were right about the Windows bug being unrelated. It is cause by f2py --include-paths not picking up the colon separators for the multiple include paths required by our code. I filed it separately #24533 .

**Comment by afedynitch** [comment]
On a different note... is this fix going to be backported?

**Comment by HaoZeke** [comment]
> On a different note... is this fix going to be backported?

I think that would be a good idea, @charris ?

**Comment by charris** [comment]
It was backported yesterday.

**Pull request merged**
