### PR TITLE
DOC,MAINT: Move towncrier files and fixup categories

### PR DESCRIPTION
**Pull request by seberg**
Name all categories as singular (or adjectives). Also move the fragments
into an ``upcoming_changes`` folder to be more discoverable.

Notes that we format some things as bullet points traditionally (right now
towncrier only truly supports bullet point format, but I have a PR to fix
that).

---

Currently towncrier still somewhat malforms things, and the title is not really correctly handled. Also I would prefer to directly create a correct file (removing the need to rename).

This change also adds a `highlight` category already. We do not have to use it, but if someone believes their change will be a highlight, it would be possible to add a fragment to make sure it shows up in the draft version. I changed the ``--version`` here, because I want to change it so that the `NumPy` part is is hardcoded, but it will be easier to do that once towncrier moves to have better support there.

### CODE REVIEW

**Comment by seberg** [comment]
(If nobody speaks up, I may go ahead pretty soon to merge, to makes sure new fragments have to be moved around less, the most important thing is to be OK with `upcoming_changes` folder inside `doc/release/` as the place to put the fragments).

**Comment by charris** [comment]
Do we remove everything in `upcoming-changes` after a release?

**Comment by seberg** [comment]
Yes, towncrier will automatically do that (or ask you about it) if you do not run it with the `--draft` mode. In principle, when you backport things, the fragment will also get backported (it will link the original PR of course, but maybe that is for the better even).

**Comment by seberg** [comment]
One small thing is that now it is not easy to read what the upcoming changes are. I could keep the `1.18` release file around and just write that all changes are in the `upcoming_changes` (or `upcoming_release`?) folder and to run `towncrier --draft --version 1.18` for an overview.

**Comment by charris** [comment]
Might be useful to generate the release notes along the way, not sure of the best way to do that.

**Comment by eric-wieser** [comment]
It would be great if we could generate the release notes as part of the dev-docs build, so that we can just link to them online that way

**Comment by seberg** [comment]
Hmmm, I think that should be possible (at least once either towncrier moves fast enough). Although, if I add it to the devdoc process, I guess there is no harm in downloading/installing a random towncrier version/fork until things work correctly.

I will look at that now, as long as we do not mind things to be a little bit in flux, I can just add the docs and everythin here. But that may mean linking to my own towncrier fork for now for the "Howto release" document :/.

**Comment by seberg** [comment]
Sorry for all the spam/pushes. I may update the link later (this version still has at least one small issue), but now works:
https://8627-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/release.html

However, it clones a branch from my towncrier fork... Also which notes are formatted as bullet points and which not seems to differ a bit more from release to release then I remembered. So I am not quite sure what to do about that. I could "detect" bullt points and sort them, or just change the documentation to say that `Deprecations` are bullet points as well normally.

**Comment by seberg** [comment]
I suppose, I could just vendor towncrier in updated state, and when towncrier catches up, we can pull it out again and change the documentation (and modify our toolchain with whatever is necessary).

I will ask Chuck on the community call, the whole towncrier (code only) is less than 800 lines, so I think it really is fine...

**Comment by mattip** [comment]
There may be more files to move, I just merged #14181 which added a note to the old location

**Comment by charris** [comment]
We need to get this in. Note that more files have been added to `changelog`.

**Comment by seberg** [comment]
Yes, sorry about that. Towncrier is moving, so I think I can fix it up better very soon. If no one complains by tonight, I think I will just do the first part (that does not fix up the rendering, just moving files, etc.) and simply merge myself.

I expect the necessary changes will go into towncrier very soon, I am almost finished with them (assuming towncrier will merge them quickly).

**Comment by charris** [comment]
> I think I will just do the first part (that does not fix up the rendering, just moving files, etc.)

Excellent. There are still folks adding to the old 1.18.0-notes and I'd like a place for them to put things.

**Pull request merged**
