### PR TITLE
DOC: Add example to msort docstring

### PR DESCRIPTION
**Pull request by shreya-singh-tech**
added examples to msort in lib/function_base.py based on issue #22266

### CODE REVIEW

**Review by melissawm — COMMENTED** [review]
Looks good to me, thanks @shreya-singh-tech !

**Review by rossbar — APPROVED** [review]
Thanks @shreya-singh-tech - I took the liberty of pushing up a few very minor formatting tweaks, but this LGTM!

**Comment by charris** [comment]
Thanks @shreya-singh-tech .

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @shreya-singh-tech! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Pull request merged**
