### PR TITLE
DEP: remove deprecated (and private) numpy.testing submodules.

### LINKED ISSUE #14566: #14454 broke the wheel builds.
`MAINT: add test to prevent new public-looking modules being added`

See #14454 for comments.

I suspect this is because the optional `nose` package was not available. Note that `nose` needs fixes to run with recent Python3 because it imports the deprecated `imp` module.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

### PR DESCRIPTION
**Pull request by rgommers**
Removes these files that were deprecated since 1.15.0:

- numpy/testing/decorators.py
- numpy/testing/noseclasses.py
- numpy/testing/nosetester.py

This also resolves a failure in the recently introduced tests in `test_public_api.py` (see gh-14454).  Closes gh-14566

### CODE REVIEW

**Comment by charris** [comment]
There are still folks using the NumPy nose framework so it may be a bit early to delete the files. Most of the linux distributions have patched versions of nose, so that still works. If we do remove the files there needs to be a release note.

**Comment by rgommers** [comment]
Nothing is gone, the correct imports are and have always been
```
from numpy.testing import Tester, run_module_suite, dec
```

These files were always private, they just missed an underscore.

**Comment by mattip** [comment]
> There are still folks using the NumPy nose framework

@charris can we ping those projects to encourage them to deprecate the old imports?

**Comment by charris** [comment]
OK, looks like there are workarounds for any that need it. I'll do a wheels build after this is merged to check.

Thanks Ralf.

**Comment by charris** [comment]
OK, the travis builds are working, but the [appveyor](https://ci.appveyor.com/project/matthew-brett/numpy-wheels/builds/27571654/job/xq3rm82x24c583ar) builds are failing. I don't know if that is related.

**Comment by rgommers** [comment]
That Appveyor failure does not look related. It does look very odd though. 
```
  File "C:\Python37-x64\lib\site-packages\setuptools\msvc.py", line 199, in msvc14_gen_lib_options
    if LegacyVersion(np.__version__) < LegacyVersion('1.11.2'):
```

Indeed, that can't be right, looks like a regression introduced in `setuptools`.

**Comment by rgommers** [comment]
Or it got triggered by @mattip's `build_src` changes

**Comment by charris** [comment]
I'm suspecting the latter, the code in setuptools is three years old.

**Pull request merged**
