### PR TITLE
API: Update `lib.type_check` namespace

### PR DESCRIPTION
**Pull request by mtsokol**
Relevant issue https://github.com/numpy/numpy/issues/24507

Hi @rgommers @ngoldbaum,

This PR moves `lib.type_check` module to a private file and ensures that its public methods are only available through the main namespace. There are no additional functions available from a local namespace.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM, thanks @mtsokol. Can you rebase to fix the conflicts?

**Comment by mtsokol** [comment]
> LGTM, thanks @mtsokol. Can you rebase to fix the conflicts?

Sure! Rebased.

**Comment by rgommers** [comment]
This one will need another rebase.

**Comment by mtsokol** [comment]
> This one will need another rebase.

Done!

**Review by rgommers — APPROVED** [review]
Thanks Mateusz, this LGTM now.

After the slight hiccup with `function_base`, I verified manually which function names are removed from the `numpy.lib` namespace with this PR. Those are:
```
['isrealobj',
 'imag',
 'iscomplexobj',
 'isreal',
 'real_if_close',
 'common_type',
 'iscomplex',
 'real',
 'typename',
 'mintypecode',
 'nan_to_num']
```
All of these are available in the main namespace and nothing looks like it should stay in `numpy.lib`, so this all looks fine.

**Pull request merged**
