### PR TITLE
MAINT: Make keyword arrays static

### PR DESCRIPTION
**Pull request by alexhenrie**
These arrays never change, and making them static will avoid having to reinitialize them on every function call.

### CODE REVIEW

**Comment by eric-wieser** [comment]
I'm not convinced by this change - isn't it sufficient to mark them const?

**Comment by alexhenrie** [comment]
Sadly, marking them `const` produces compiler warnings because `PyArg_ParseTupleAndKeywords` takes a non-const array even though it doesn't actually modify the array. `git grep -F 'char *kwlist[]'` shows that most of these arrays were already marked `static` in NumPy, and none are marked `const`. I'm just proposing that we be consistent and add `static` to the ones that didn't have it already.

**Comment by eric-wieser** [comment]
I just concluded the same thing. The approach seems odd, but it's even how CPython itself does it. I'll maybe play around with godbolt to see if `const` is ultimately better, but at the end of the day consistency matters more than microoptimization here.

**Comment by eric-wieser** [comment]
> takes a non-const array even though it doesn't actually modify the array

As far as I remember this is due to a shortcoming in C (fixed in C++), where a `T const* const` argument cannot legally be passed a `T*`.

**Comment by seberg** [comment]
Sorry, forgot about these. Adding `static` uniformly seems great to me (some of this might cause me a merge conflict, but that is trivial). Thanks @alexhenrie.

**Comment by alexhenrie** [comment]
Thank you!

**Pull request merged**
