### PR TITLE
MAINT: Add git rules to ignore all SIMD generated files

### PR DESCRIPTION
**Pull request by seiko2plus**
related to #17827

### CODE REVIEW

**Comment by mattip** [comment]
Can't we move all of the generated files to the `build` directory even when we run with `--in-place`?

**Comment by seiko2plus** [comment]
Yes, that can be easily done for generated files that are related to `CCompilerOpt` but I'm not sure about template sources `*.src`.

**Comment by seiko2plus** [comment]
@mattip but wait if we moved all the generated files to the build/src dir then what about from `--in-place`?

**Comment by mattip** [comment]
As I understand it, the point of `--in-place` is to allow `import numpy` to work, it is an argument to `build_ext` to tell it to copy the c-extension modules into the place the package expects in the source tree. I am pretty sure all the intermediate compilation artifacts, like generated c and h files, should be in `./build`. The cythonized c files are an exception: we are meant to ship those in the `sdist` tarball so they are exempt from the rule.

**Comment by seiko2plus** [comment]
@mattip, thank you for the explanation, I thought the point of `--in-place` is to simplify tracing generated files :) . so to make it clear the root dir of the generated files of `(f2py, swig, template src, dispatch)` should remain `build/src.*` even with the option `--in-place`, Did I get right? if yes, can we make this change with dispatchable sources and leave the rest for now?

**Comment by mattip** [comment]
Yes exactly what I meant. If it is not too complicated to change the root dir that would be great.

**Comment by rgommers** [comment]
> The cythonized c files are an exception: we are meant to ship those in the `sdist` tarball so they are exempt from the rule.

That used to be the case, but not anymore.



> As I understand it, the point of `--in-place` is to allow `import numpy` to work, it is an argument to `build_ext` to tell it to copy the c-extension modules into the place the package expects in the source tree. I am pretty sure all the intermediate compilation artifacts, like generated c and h files, should be in `./build`.

This is not the case. Try an in-place build and see what's under `.build` and what's in the source tree (delete `.gitignore` to see). You will find that all expanded versions of `.c.src` and `.h.src` also stay in the same dirs, and only intermediate build artifacts like `.o`, `.o.d` and `.a` files end up in `build/`. This can differ a bit per platform, but overall the reasoning here is wrong and generated files that are themselves _source_ files for building compiled extensions can stay in tree.

**Review by rgommers — APPROVED** [review]
This all looks good to me.

**Comment by mattip** [comment]
Thanks @rgommers for the explanation.

**Comment by mattip** [comment]
Thanks @seiko2plus

**Pull request merged**
