### PR TITLE
Speed up _string_helpers init.

### PR DESCRIPTION
**Pull request by ttsugriy**
Using `map(chr...)` is [faster](https://colab.research.google.com/gist/ttsugriy/802cc1f338b5825b3cf2739152903e2a/list-comprehensions-vs-map.ipynb) than using a list comprehension. Also, it's better to use `tuple` instead of `list` because it prevents accidental mutations and uses less memory. [Collab](https://colab.research.google.com/gist/ttsugriy/802cc1f338b5825b3cf2739152903e2a/list-comprehensions-vs-map.ipynb) notebook can be used to verify the speedup.
```
%%timeit
_all_chars = [chr(_m) for _m in range(256)]
_ascii_upper = _all_chars[65:65+26]
_ascii_lower = _all_chars[97:97+26]
LOWER_TABLE = "".join(_all_chars[:65] + _ascii_lower + _all_chars[65+26:])
UPPER_TABLE = "".join(_all_chars[:97] + _ascii_upper + _all_chars[97+26:])

20.3 µs ± 2.1 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
vs
```
%%timeit 
_all_chars = tuple(map(chr, range(256)))
_ascii_upper = _all_chars[65:65+26]
_ascii_lower = _all_chars[97:97+26]
LOWER_TABLE = "".join(_all_chars[:65] + _ascii_lower + _all_chars[65+26:])
UPPER_TABLE = "".join(_all_chars[:97] + _ascii_upper + _all_chars[97+26:])

15.5 µs ± 3.44 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Sure, the absolute numbers are not super impressive, but combined with maintenance improvements mentioned above, it seems worthwhile.

### CODE REVIEW

**Comment by rossbar** [comment]
Are we sure that importing string is still slow? I see the comment above this section but it's at least 5 years old. It'd be good to check!

**Comment by ttsugriy** [comment]
I'm not sure how to check this since it likely heavily depends on the used interpreter.

**Comment by ngoldbaum** [comment]
It's still a lot slower to do the import on Python 3.11:

```
$ pyperf timeit "import string"
.....................
Mean +- std dev: 95.7 ns +- 1.4 ns
```

```
$ pyperf timeit "_all_chars = tuple(map(chr, range(256)))
_ascii_upper = _all_chars[65:65+26]
_ascii_lower = _all_chars[97:97+26]
LOWER_TABLE = \"\".join(_all_chars[:65] + _ascii_lower + _all_chars[65+26:])
UPPER_TABLE = \"\".join(_all_chars[:97] + _ascii_upper + _all_chars[97+26:])"
.....................

Mean +- std dev: 13.1 us +- 3.7 us
```

**Comment by ttsugriy** [comment]
so it looks like there are plenty of reasons to proceed with this change, right? :)

**Comment by rossbar** [comment]
> It's still a lot slower to do the import on Python 3.11:

Technically the `pyperf` things above show the opposite: 95 ns vs. 13 us. But anyways that's a bit misleading because `pyperf` is probably reporting results from imports after caching.

**Review by rossbar — COMMENTED** [review]
IMO this has no practical impact but it's no less readable and not worth bikeshedding - in it goes! Thanks @ttsugriy

**Comment by ngoldbaum** [comment]
> Technically the pyperf things above show the opposite: 95 ns vs. 13 us.

Argh, sorry for the lack of care, I wasn't reading very carefully. You're right about the caching too, pyperf has a warmup run.

Profiling with `-x importtime` says that `import string` takes about 800 us on my laptop.

**Pull request merged**
