### PR TITLE
BLD: Openblas 0.3.10

### PR DESCRIPTION
**Pull request by mattip**
OpenBLAS 0.3.10 was released. Upgrade and add the hashes via parsing the output of
```
python tools/openblas_support.py --test
```
after changing the version. The test reports missing hashes.

Also tweaked the handling of IS_32BIT to allow `--test` to print all the downloads.

Also removed some duplicate hashes.

### CODE REVIEW

**Comment by mattip** [comment]
It seems a little late in the release cycle to backport this to 1.19, correct?

**Comment by charris** [comment]
> It seems a little late in the release cycle to backport this to 1.19

Yes. Should be good for 1.20 though.

**Comment by charris** [comment]
Another PyPy segfault, Shippable is acting up.

**Comment by charris** [comment]
Thanks Matti.

**Comment by mattip** [comment]
That PyPy segfault is annoying. I cannot replicate it locally.

**Pull request merged**
