### PR TITLE
MAINT: Translate timsort.c.src to C++ using templates.

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Another step in the road of c.src -> c++ conversion
As usual, to keep changes as independent as possible, I've kept a c <> C++ boilerplate layer that's going to be removed once all sorting method get converted

### CODE REVIEW

**Comment by madphysicist** [comment]
What is the benefit of switching to C++? Is this really something that's happening to numpy?

**Comment by rkern** [comment]
Yes, this is a thing that is happening: slowly and cautiously using C++ language features when they are an improvement over our custom `.c.src` code generation tool. We're definitely not making all of numpy C++. [Here is the previous discussion](https://mail.python.org/archives/list/numpy-discussion@python.org/message/BLCIC2WMJQ5VT6HJSUW4V5TNGQ36JQXI/).

**Comment by madphysicist** [comment]
@rkern Very neat. I'm dusting off my C++ skills, so this might be a useful place to practice. Thanks for the interesting read. I'm glad we're not using the STL.

**Comment by serge-sans-paille** [comment]
I'm a bit puzzled by the error...

**Comment by charris** [comment]
> I'm a bit puzzled by the error...

I think it is due to a recent merge. I think @seberg is dealing with it.

**Comment by charris** [comment]
close/reopen

**Comment by charris** [comment]
Could you try running `clang-format` on this, we have a `.clang-format` file. I'm also curious if `typename` is C++ version safe.

**Comment by serge-sans-paille** [comment]
rebase on `main` and clang-formated

**Comment by serge-sans-paille** [comment]
>  I'm also curious if typename is C++ version safe.

It is. It's been there since C++98 and it's here to stay.

**Comment by charris** [comment]
Thanks @serge-sans-paille .

**Comment by mattip** [comment]
It is interesting that the older templating engine's syntax is very similar to C++ templating.

Could you run a benchmark to see if there is any performance difference?

**Pull request merged**
