### PR TITLE
DOC: Fix a minor issue of MaskedArray

### PR DESCRIPTION
**Pull request by tienhsiangkao**
This issue explained the inconsistency between the shape of `data` and `mask` when use ``mask=numpy.bool_(False)`` for ``numpy.ma.MaskedArray``, as gh-13758 pointed out.

### CODE REVIEW

**Comment by eric-wieser** [comment]
`numpy.bool_(False)` is better spelt `np.False_`, similar for `np.True_`.

What's worth mentioning here is the behavior differs because `np.False_ is np.ma.nomask`, which is for whatever reasons treated specially.

**Comment by tienhsiangkao** [comment]
Thanks, so I need to make those changes and redo a pull request? Forgive my
ignorance since this is my first time to do this kind of stuff.

On Sat, Jul 13, 2019 at 5:43 PM Eric Wieser <notifications@github.com>
wrote:

> numpy.bool_(False) is better spelt np.False_, similar for np.True_.
>
> What's worth mentioning here is the behavior differs because np.False_ is
> np.ma.nomask, which is for whatever reasons treated specially.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_numpy_numpy_pull_13978-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DADRETYVMFMTLZZETKKMXIWTP7JLBXA5CNFSM4IDDPL72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ32U6A-23issuecomment-2D511158904&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=_xlsTki5G1Yufiika_Kf00WER1fRzLq_RXb-n9kkcz0&m=Zf4BCu_ISYT20s5SEPZDpkIJr3RQZLtpg3Omj9ZxNMM&s=UjnF3kR4OlLYKa_dhZTrhfwXalCLUZES97Lokoa49wQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADRETYUSIP3K6GXPOGH3KWDP7JLBXANCNFSM4IDDPL7Q&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=_xlsTki5G1Yufiika_Kf00WER1fRzLq_RXb-n9kkcz0&m=Zf4BCu_ISYT20s5SEPZDpkIJr3RQZLtpg3Omj9ZxNMM&s=P0DedQb7S308dDlRWg4ZxFB2aOljElJhYxcJuhyUO7w&e=>
> .
>


-- 
Yours sincerely,
Tian-Xiang, "Ronnie", Gao
Ph.D. Student in Oceanography



Texas A&M University O&M Building
Room 618 MS 3146
College Station, Texas 77843

Email: tienhsiangkao@tamu.edu
           tienhsiangkao@gmail.com

**Comment by eric-wieser** [comment]
I'd perhaps wait for more feedback first. You will not have to create a new PR, you can just push ne w commits to the same branch as this PR, and this page will update.

Having said that, you probably shouldn't be making this PR from `master` (since you only have one master, so that approach doesn't scale to having multiple PRs open at one), so it might be worth making a new `MaskedArray-docs` branch locally and creating a new PR from that.

**Comment by tienhsiangkao** [comment]
Thanks, I will do that!

On Sat, Jul 13, 2019 at 5:51 PM Eric Wieser <notifications@github.com>
wrote:

> I'd perhaps wait for more feedback first. You will not have to create a
> new PR, you can just push ne w commits to the same branch as this PR, and
> this page will update.
>
> Having said that, you probably shouldn't be making this PR from master
> (since you only have one master, so that approach doesn't scale to having
> multiple PRs open at one), so it might be worth making a new
> MaskedArray-docs branch locally and creating a new PR from that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_numpy_numpy_pull_13978-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DADRETYV7Q5PL4EEY4RWUOVDP7JL5LA5CNFSM4IDDPL72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ32XFA-23issuecomment-2D511159188&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=_xlsTki5G1Yufiika_Kf00WER1fRzLq_RXb-n9kkcz0&m=8P1bFV7lEP71NbMc6ZkICOEZZfYIcuM1BASNGrwSMPY&s=pVqEww_25K_2Q_q0e7gyguyEJWWXZuM7DepvWwxLYXg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADRETYRRHFITRWXDGCHDTYTP7JL5LANCNFSM4IDDPL7Q&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=_xlsTki5G1Yufiika_Kf00WER1fRzLq_RXb-n9kkcz0&m=8P1bFV7lEP71NbMc6ZkICOEZZfYIcuM1BASNGrwSMPY&s=WoCR6vt1h9s9ENYV9o416flvTVZIAKCOfgWp5SZ5gJc&e=>
> .
>


-- 
Yours sincerely,
Tian-Xiang, "Ronnie", Gao
Ph.D. Student in Oceanography



Texas A&M University O&M Building
Room 618 MS 3146
College Station, Texas 77843

Email: tienhsiangkao@tamu.edu
           tienhsiangkao@gmail.com

**Comment by tienhsiangkao** [comment]
I just redid PR with corresponding changes. Please let me know if anything
needs to be improved.

On Sat, Jul 13, 2019 at 5:52 PM T'ien-hsiang Kao <tienhsiangkao@gmail.com>
wrote:

> Thanks, I will do that!
>
> On Sat, Jul 13, 2019 at 5:51 PM Eric Wieser <notifications@github.com>
> wrote:
>
>> I'd perhaps wait for more feedback first. You will not have to create a
>> new PR, you can just push ne w commits to the same branch as this PR, and
>> this page will update.
>>
>> Having said that, you probably shouldn't be making this PR from master
>> (since you only have one master, so that approach doesn't scale to having
>> multiple PRs open at one), so it might be worth making a new
>> MaskedArray-docs branch locally and creating a new PR from that.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_numpy_numpy_pull_13978-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DADRETYV7Q5PL4EEY4RWUOVDP7JL5LA5CNFSM4IDDPL72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ32XFA-23issuecomment-2D511159188&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=_xlsTki5G1Yufiika_Kf00WER1fRzLq_RXb-n9kkcz0&m=8P1bFV7lEP71NbMc6ZkICOEZZfYIcuM1BASNGrwSMPY&s=pVqEww_25K_2Q_q0e7gyguyEJWWXZuM7DepvWwxLYXg&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADRETYRRHFITRWXDGCHDTYTP7JL5LANCNFSM4IDDPL7Q&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=_xlsTki5G1Yufiika_Kf00WER1fRzLq_RXb-n9kkcz0&m=8P1bFV7lEP71NbMc6ZkICOEZZfYIcuM1BASNGrwSMPY&s=WoCR6vt1h9s9ENYV9o416flvTVZIAKCOfgWp5SZ5gJc&e=>
>> .
>>
>
>
> --
> Yours sincerely,
> Tian-Xiang, "Ronnie", Gao
> Ph.D. Student in Oceanography
>
>
>
> Texas A&M University O&M Building
> Room 618 MS 3146
> College Station, Texas 77843
>
> Email: tienhsiangkao@tamu.edu
>            tienhsiangkao@gmail.com
>
>


-- 
Yours sincerely,
Tian-Xiang, "Ronnie", Gao
Ph.D. Student in Oceanography



Texas A&M University O&M Building
Room 618 MS 3146
College Station, Texas 77843

Email: tienhsiangkao@tamu.edu
           tienhsiangkao@gmail.com

**Comment by eric-wieser** [comment]
Closing in favor of gh-13980, thanks!

**Pull request closed without merging**
