### PR TITLE
BUG/MAINT: Remove special cases for 0d arrays in interp

### PR DESCRIPTION
**Pull request by eric-wieser**
These can be handled generically a level deeper.

This makes `interp(arr_0d, ...)` return numpy scalars rather than python scalars, which is consistent with other functions within numpy

This fixes `np.interp(arr_0d, ..., period=...)` too, which would previously crash.

Rework of b66a200a4a1e98f1955c8a774e4ebfb4588dab5b

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
This looks all OK to me. I slightly wonder about mentioning (and even testing) that the output is a numpy scalar, since at some level it should be an implementation detail. But fine to go with your choice.

**Comment by mhvk** [comment]
Your new test does check the output type. Anyway, I think that is fine -- it just means that if it ever changed, we'd be warned to add another note. So, I'll merge.

**Comment by mhvk** [comment]
Was wondering about backporting: overall, perhaps not?

**Comment by charris** [comment]
> Was wondering about backporting: overall, perhaps not?

@mhvk I'd like to just get 1.14 fixed up and then do a 1.15 release soonish.

**Comment by mhvk** [comment]
OK, sounds good. Let's not backport this one then, as it fixes a corner case that has been broken a long time.

**Pull request merged**
