### PR TITLE
API: Bump NPY_MAXDIMS to 64 and NPY_MAXARGS to 128

### PR DESCRIPTION
**Pull request by seberg**
Both come up often enough, there was once a PR to bump `NPY_MAXARGS` to 256, but right now I thought, maybe try this and someone else can bump it more ;).  (of course bumping requires a major release, though).

This increases stack usage and the size of some objects (mainly iterators) of course, otherwise I don't really expect much of an impact, there are a couple of places where this type of arrays are fully zeroed out, but even the worst case should be a very small (few percent) slowdown.

**Effect:**
* Downstream should be using this the same as we are: as stack space.  So this increases their stack space, but otherwise does nothing (it is also increased if you run against NumPy 1.x).
* In theory, downstream might be doing other things, these should lead to reasonable errors though (i.e. NumPy rejecting a 64 dimensional array when running with NumPy 1.x).
* **Worst case:** A third party could use ``NPY_MAXDIMS`` in a struct in _their_ headers.  This would be problematic if their downstream compiles with NumPy 1.x still.

I think it is realistic that this does nothing except bumping the stack use a bit, although I guess it is not unlikely that some downstream libs may not support 64 dims right away.

(I wouldn't mind adjusting some of the places where these are used to use `alloca`, e.g. in ufuncs we almost always have 2, but always have huge working stack area).

---

The discussion then suggested 256, and this was the old PR: https://github.com/numpy/numpy/pull/4840

I am not sure, for MAXDIMs, removing the limit entirely is hard, for MAXARGS, it seems like much more to do than back in the day, but at least for the iterator probably not so bad.  I.e. it would be nice to not have MAXARGS at all (or maybe have it, but only to switch between stack allocation and malloc.

Until then, does just bumping seem good, should we go with 256.  I honestly have no opinion, I did this first remembering it was higher, then saw they suggested 256...

### CODE REVIEW

**Comment by seberg** [comment]
Ah, I forgot the worst case initially.  Added to the release notes also, but if a downstream library uses `NPY_MAXDIMS` in _its_ public headers, the library and its users could end up compiling with a different NumPy version.  Such a library would have to hardcode the *old* value, or find a transition way/force downstream to recompile. 

However, I could only see a few usages of `NPY_MAXDIMS` in headers and they didn't look like public headers.

**Comment by mattip** [comment]
If we are already touching this, I would be in favor of removing the use of a fixed size altogether. The only places we really need this constant are when allocating a temporary buffer for some calculations on the strides. Currently this is a static allocation on the stack, it could be done dynamically instead. In `__new__` we know the size we need to allocate so we could just allocate what we need.

**Comment by mattip** [comment]
Maybe there should be some artificial upper limit so people do not do crazy things, say 1024.

**Comment by seberg** [comment]
I don't disagree, but don't really want to dive into it right now.  I would just remove the `NPY_MAXARGS` bump, and limit to maxdims then.

Something the old PR fails to mention, though: This breaks iteration ABI, the legacy iterate has to stay limited to 32 dims (which will affect some functions).

**Comment by rgommers** [comment]
Cross-linking to https://github.com/numpy/numpy/issues/5744; this topic was moved forward for NumPy 2.0.

**Pull request closed without merging**
