### PR TITLE
MAINT: Apply ruff/flake8-comprehensions rules (C4)

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Merging #27300 first will help with residual linter errors.

### CODE REVIEW

**Comment by charris** [comment]
The easy fix here is to not worry about distutils. We don't maintain that anymore and we will remove it in a year when Python 3.11 gets dropped.

**Comment by charris** [comment]
That is simply done by `git co main distutils` followed by a commit.

**Comment by charris** [comment]
Needs rebase.

**Comment by charris** [comment]
I get mixed feelings about some these changes, some are definitely improvements, some not much difference, and some maybe a git more difficult. I think the problem is getting used to modern python, which can be more complicated than the old. The addition of literal sets, etc., takes a bit of getting used to for an old hand. I think of this as more modernization than just formatting...

**Comment by charris** [comment]
Oops, accidentally closed it. Reopened.

**Comment by DimitriPapadopoulos** [comment]
I don't disagree. However, set literals must have been introduced for a reason — I presume to avoid the function call and improve performance. These changes might be seen as micro-optimisations. While micro-optimisation is usually frowned upon, here it is automatically and systematically applied by a tool.

**Comment by DimitriPapadopoulos** [comment]
With that said, I am happy to silence rules that don't seem to improve the code base — and revert the associated changes.

**Comment by charris** [comment]
> I am happy to silence rules that don't seem to improve the code base

I'm not sure which those were :)  Also note #27884.

**Comment by charris** [comment]
I'm inclined to just put this in while ~we~  I am in this mode.

**Comment by charris** [comment]
Thanks @DimitriPapadopoulos .

It looks like most of the lint failures can be automatically fixed.

**Pull request merged**
