### PR TITLE
NEP: Rename nep 29

### PR DESCRIPTION
**Pull request by eric-wieser**
There is an NEP entitled "deprecation policy", but that is [NEP-23](https://numpy.org/neps/nep-0023-backwards-compatibility.html).
Using those words in the filename of another NEP is misleading.

cc @rgommers and @tacaswell, the primary authors of these two NEPs.

I'm not sure if "final" means "the filename is fixed forever".

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Good idea @eric-wieser. While we're at it: perhaps `python-version-support` would be an even clearer name?

**Comment by eric-wieser** [comment]
I chose not to do that because it also concern numpy versions, from my very brief read of it. Feel free to rename again through the github ui,

**Comment by rgommers** [comment]
@tacaswell any preference?

**Comment by tacaswell** [comment]
If we are going to change the name, prefer "version-support", however this is going to break a whole bunch of links (as the rst name is in the url (https://numpy.org/neps/nep-0029-deprecation_policy.html)).

**Comment by rgommers** [comment]
Ah yes, good point @tacaswell. A Google search shows that there's quite some use of the link already.

The actual NEP title is:
```
NEP 29 — Recommend Python and Numpy version support as a community policy standard
```
so a filename isn't that confusing. 

We can't do this it looks like @eric-wieser

**Comment by eric-wieser** [comment]
I could create a "moved" rst page to remain at the old url.

**Comment by rgommers** [comment]
> I could create a "moved" rst page to remain at the old url.

that seems to defeat the purpose, since the filename will still be present. it's anyway a minor thing, since the NEP title and the listing on https://numpy.org/neps/ are clear.

I suggest to just close this PR.

**Comment by mattip** [comment]
Closing. Please reopen if I misunderstood.

**Pull request closed without merging**
