### PR TITLE
BUG: fixing regex to avoid potential ReDoS

### PR DESCRIPTION
**Pull request by yetingli**

### CODE REVIEW

**Comment by rgommers** [comment]
As I wrote elsewhere: you should never send a patch for a potential security issue in public! Please read up on how to contact projects and disclose security issues privately. Most large projects will have that (see our README for example), and if not you should send a private email to find out how to continue.

In this case I don't think there's a real issue, but I'm not 100% sure. So I will contact you by email directly at the email address listed in your GitHub profile, and we'll figure out what is going on here. 

In the meantime, I will close this PR.

**Comment by bjnath** [comment]
@rgommers 
> never send a patch for a potential security issue in public!

Let's add it to the contributor guidelines. I'll find a spot for it and file a PR.

**Comment by eric-wieser** [comment]
Better, let's put it in @melissawm 
's issue templates

**Comment by bjnath** [comment]
OK, I'll let @eric-wieser  take care of it.

**Pull request closed without merging**
