### PR TITLE
MAINT:  NEP process updates

### PR DESCRIPTION
**Pull request by njsmith**
- Write down a formal procedure for declaring a NEP "accepted"

- Assign numbers to all existing NEPs

### CODE REVIEW

**Comment by njsmith** [comment]
CC @jarrodmillman @stefanv

**Comment by eric-wieser** [comment]
Do we want to reserve some early numbers to become things like HOW_TO_DOCUMENT and other instructional documents?

So maybe start numbering at 100?

**Comment by njsmith** [comment]
I just figured we'd allocate those numbers as they come up? I'm not sure which ones are "special enough" to get "special numbers", and I'm not sure that NEP 5 or whatever is that much more memorable than NEP 25 anyway...

**Comment by charris** [comment]
I don't have a problem with the numbering, it is kind of arbitrary anyway.

**Review by charris — APPROVED** [review]

**Comment by charris** [comment]
Let's get this in so @njsmith  can add entries in his NEP PRs. Thanks Nathaniel.

**Comment by stefanv** [comment]
Looks good, thanks!

**Pull request merged**
