### PR TITLE
DOC: Link issue label

### PR DESCRIPTION
**Pull request by UltiRequiem**

### CODE REVIEW

**Comment by melissawm** [comment]
Thanks @UltiRequiem - can you please check that the lines don't exceed 80 characters in the source file? Thanks!

**Comment by UltiRequiem** [comment]
Sorry, I was cleaning the forks I had and deleted this one by mistake, so I can no longer make changes to this Pull request. I will open a new pull request with the requested change.

**Comment by UltiRequiem** [comment]
The new pull request is #19195.

**Comment by mattip** [comment]
Next time, rather than open a new PR you can add another commit to this one.

**Pull request closed without merging**
