### PR TITLE
TYP: Update type annotations for the numpy 1.25 release 

### LINKED ISSUE #22632: TYP: Review type & signatures changes for the numpy 1.25 release
Ensure that the stub files are updated to reflect any runtime changes to types and/or functions signatures.

### PR DESCRIPTION
**Pull request by BvB93**
Tentatively closes https://github.com/numpy/numpy/issues/22632

This PR either adds or polishes annotations related to new numpy 1.25 features (as per the release notes).

### CODE REVIEW

**Comment by charris** [comment]
Grrr, the rtools package is causing problems again. Unrelated to this PR.

**Comment by BvB93** [comment]
> Grrr, the rtools package is causing problems again. Unrelated to this PR.

Yeah, figured as much... The rtools error seems to persist even after restarting the job.

**Comment by charris** [comment]
> Yeah, figured as much

We got it fixed, now something has broken again. Be nice if it were stable for more than a few days.

**Comment by mattip** [comment]
Can we somehow cache the environment so we don't have to download each time?

**Comment by seberg** [comment]
I bet the test will just fail again.  The changes look good though, thanks for being the guardian of typing changes :).

**Pull request merged**
