### PR TITLE
 MAINT: Move add_newdocs into core, since it only adds docs to those pieces

### PR DESCRIPTION
**Pull request by eric-wieser**
Builds upon gh-11473. Once that one is merged, toggle the base branch of this PR to see the updated diff

This results in a more reasonable import sequence.

### CODE REVIEW

**Comment by eric-wieser** [comment]
I've not got python 3.7 installed, but would be curious to see what the import time graph looks like with this PR.

**Comment by charris** [comment]
Agree, I've been tempted to do the same, I've looked for it in core more than once ...

**Comment by rgommers** [comment]
Seems like a good idea too.

**Comment by charris** [comment]
Looks like all the `pytesttester` stuff still shows up in the diff.

**Comment by eric-wieser** [comment]
> toggle the base branch of this PR to see the updated diff

**Comment by charris** [comment]
Thanks Eric.

**Pull request merged**
