### PR TITLE
API: Do not import sliding_window_view to main namespace

### PR DESCRIPTION
**Pull request by seberg**
At least for now, lets not import it to the main namespace, since there is
no agreement that this is a good idea.

---

Not quite sure if the ref-docs are OK with omitting the module name in the function calls, lets see.

### CODE REVIEW

**Comment by mattip** [comment]
Thanks @seberg

**Comment by zklaus** [comment]
Does this really do the trick? There is still the `module='numpy'` argument to the array dispatcher.

**Comment by eric-wieser** [comment]
It will do the trick, but we should definitely remove that argument to avoid confusion - good catch!

**Comment by seberg** [comment]
Indeed, it will mostly print incorrectly I think.

**Pull request merged**
