### PR TITLE
BUG: Remove our patched version of `distutils.split_quoted`

### PR DESCRIPTION
**Pull request by eric-wieser**
The patch was a workaround for our broken `exec_command`. It was removed
in gh-1217, but then added back in gh-1321.  Now that we've fixed
exec_command, I believe we can finally take it out for good.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Worryingly the test failed [the firsttime](https://dev.azure.com/numpy/numpy/_build/results?buildId=2331), but passed the second. Hopefully unrelated to this change.

**Comment by charris** [comment]
Let's give it a shot. If someone runs into a problem it may indicate another/different fix is needed.

**Comment by charris** [comment]
This needs a backport, correct? I think all the other fixes have been backported.

**Comment by eric-wieser** [comment]
Yes, without this backport the behavior of `FLAGS` = `"-O2" -O2` would be broken (although that's pretty contrived)

**Comment by charris** [comment]
Note that the commit message for this was not correctly formatted.

**Pull request merged**
