### PR TITLE
ENH:  Use SVML for fp32 and fp64 power and arctan2

### PR DESCRIPTION
**Pull request by sterrettm2**
This adds support for SVML's power and arctan2 for 32 and 64 bit floating point. On a simple benchmark of these functions included in this merge request, this gives a very significant performance improvement. It also adds some tests for power's behavior on infinities and NANs.
```
       before           after         ratio
     [397b6e51]       [c85e17e3]
     <main>           <SVML>
-     14.5±0.05ms      2.29±0.07ms     0.16  bench_ufunc.BinaryBench.time_pow_64
-     6.12±0.02ms         954±10μs     0.16  bench_ufunc.BinaryBench.time_pow_32
-      16.2±0.2ms      1.93±0.04ms     0.12  bench_ufunc.BinaryBench.time_atan2_64
-     18.3±0.06ms          822±8μs     0.04  bench_ufunc.BinaryBench.time_atan2_32

```

### CODE REVIEW

**Comment by mattip** [comment]
Those are some pretty impressive gains. Were there any benchmark slowdowns? @r-devulap any reason not to put this in?

**Review by r-devulap — APPROVED** [review]
LGTM. Verified the benchmark results too on my SKX. Been meaning to add this patch myself for a while. Thanks @sterrettm2!

**Comment by mattip** [comment]
Thanks @sterrettm2

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @sterrettm2! We hope you stick around! Your choices aren’t limited to writing patches – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Pull request merged**
