### PR TITLE
Add test to gh 5732

### PR DESCRIPTION
**Pull request by charris**
This is gh-5732 with an added test for nan_to_num called with an integer list.

### CODE REVIEW

**Comment by charris** [comment]
Function is totally busted for Python > 3.2 as lists will have a copy method.

**Comment by jaimefrio** [comment]
Wouldn't it be simpler to start with a `y = np.asanyarray(x)` and avoid all that clever making the objects quack?

```
y = np.asanyarray(x)
t = y.dtype.type
if issubclass(t, _nx.complexfloating):
    return nan_to_num(x.real) + 1j*nan_to_num(x.imag)
# If 'y' is not a copy of 'x', make it be one
if y is x:
    y = y.copy()
...
```

Half the code, and it only relies in functionality we have control over.

**Comment by jaimefrio** [comment]
The other option is to add the `t = y.dtype.type` to both branches of the `try` / `except` clause.

**Comment by charris** [comment]
Yeah, that is what I am doing now. The original function was an awfull mess dating back to Numeric. I just need to make sure it replicates what the original behavior was supposed to be, the documentation isn't much help...

**Comment by charris** [comment]
Note that in the current version integer types are not upcast (since 1.5 at least), and all array types are accepted with copies being returned. The lack of upcast may be an ancient bug, but at this point it might be a feature.

**Comment by jaimefrio** [comment]
Thanks, in it goes.

**Pull request merged**
