### PR TITLE
TST: tests for sort_complex()

### PR DESCRIPTION
**Pull request by tylerjereddy**
`np.sort_complex()` is [completely uncovered](https://codecov.io/gh/numpy/numpy/src/master/numpy/lib/function_base.py#L1547) by unit tests

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Looks like Windows doesn't like the `float128`, which is probably bad to use in the test anyway

**Comment by charris** [comment]
Best to use the 'char' notation for testing the types as they correspond to the C types. In this case `'F', 'D', 'G'`.

**Comment by mattip** [comment]
Thanks Tyler

**Comment by eric-wieser** [comment]
> Best to use the 'char' notation for testing the types

I tend to prefer the long names, but they're equivalent:

* `np.half`
* `np.single`
* `np.double`
* `np.longdouble`

**Pull request merged**
