### PR TITLE
more small-array performance improvements

### PR DESCRIPTION
**Pull request by juliantaylor**
some more small array performance improvements, please see the commits for details.
The changes are somewhat hackish and could probably also be resolved by a more extensive overhaul of the ufunc object, though these changes are also very simple and should we decide to do an overhaul its good to have a better performance in our benchmarks for comparison.

small reductions (O(100) elements) improve on my machine by ~20% and binary ufuncs by about ~10%.
- `add.reduce(ones(100))` from 1.80us to 1.5us
- `add(ones(100), ones(100))` from 0.77us to 0.7us

### CODE REVIEW

**Comment by juliantaylor** [comment]
as we are going to be less strict on preserving the ufunc structure this can be probably be considered for merging

**Comment by njsmith** [comment]
Maybe it would be best to finish off that NEP first and then figure out what to do here? Is this urgent?

**Comment by charris** [comment]
Ping folks who are in the conversation. We should either close this or take it forward.

**Comment by charris** [comment]
Ping.

**Comment by mattip** [comment]
Can we close this?

**Comment by mattip** [comment]
Closing. Please reopen if you wish to move it forward.

**Pull request closed without merging**
