### PR TITLE
MAINT: move numpy/random/examples -> numpy/random/_examples

### PR DESCRIPTION
**Pull request by mattip**
Move numpy/random/examples to numpy/random/_examples

See [this comment](https://github.com/numpy/numpy/pull/14604#issuecomment-555783945), the files are not meant to be part of the public API.

### CODE REVIEW

**Comment by charris** [comment]
Test failure looks legitimate.

**Comment by eric-wieser** [comment]
Why does `numpy/random/_examples/__init__.py` exist at all, if these modules aren't support to be imported?

**Comment by mattip** [comment]
> Why does numpy/random/_examples/__init__.py exist at all, if these modules aren't support to be imported?

Updated the docs and removed `__init__.py`

**Comment by charris** [comment]
Thanks Matti.

**Pull request merged**
