### PR TITLE
BLD: Add PyPy wheels [wheel build]

### PR DESCRIPTION
**Pull request by lithomas1**
~~Note: I don't think MacPython/numpy-wheels has Windows/MacOs PyPy wheels, just the Linux ones, so I did that too here. Is there a reason they were being left out?~~
I was wrong, see comments below.

### CODE REVIEW

**Comment by mattip** [comment]
Please add PyPy wheels for windows (already in numpy-wheels) and macOS x86_64 (new, but no reason to omit it, PyPy does not yet have an arm64-macOS offering). That means 3 more wheels, bringing the total number from 12 to 15:
OS  | pythons  | arches | wheels
--|--|--|--
windows | cp38, cp39, cp310, pp38 | amd64 | 4
linux | cp38, cp39, cp310, pp38 | manylinux2014 | 4
macOS | cp38, cp39, cp310 | arm64 | 3
macOS | cp38, cp39, cp310, pp38 | x86_64 | 4

Comparing to the [1.22 release on PyPI](https://pypi.org/project/numpy/#files): we currently provide i686 linux and win32 wheels for CPython. I don't think we need to provide those for PyPy (PyPy does not release a win32 version, and the use case for 32-bit linux is quite borderline).

**Comment by mattip** [comment]
It might be nice as a followup PR to refactor the long list of includes into a matrix.

**Comment by mattip** [comment]
At some point we also need an sdist. Does cibuildwheel do that?

**Comment by lithomas1** [comment]
> At some point we also need an sdist. Does cibuildwheel do that?

No, see discussion in https://github.com/pypa/cibuildwheel/issues/173.

> It might be nice as a followup PR to refactor the long list of includes into a matrix.

Will do.

Also, the PyPy macOS builds are failing to compile for some reason, but the Windows and Linux ones seem to pass. 
Is there a MacOS PyPy test job here on the main repo that I can look at to debug this?
Thanks for the help.

**Comment by mattip** [comment]
OK, I was optimistic that PyPy macOS x86_64 would work. Apparently there is a redefinition that gcc and MSVC do not warn about but that clang does not like. Let's leave the macOS PyPy wheel out for now.

<details><summary>Build failure</summary>

```
In file included from /tmp/pypy3.8-v7.3.7-osx64/include/pypy3.8/Python.h:73:
/tmp/pypy3.8-v7.3.7-osx64/include/pypy3.8/pyport.h:68:20: \
    error: redefinition of typedef 'Py_hash_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
typedef Py_ssize_t Py_hash_t;
                       ^
/tmp/pypy3.8-v7.3.7-osx64/include/pypy3.8/cpyext_object.h:9:14: \
    note: previous definition is here
    typedef long Py_hash_t;
                 ^
1 error generated.
```

**Comment by mattip** [comment]
Thanks @lithomas1

**Pull request merged**
