### PR TITLE
DEP: Deprecate `np.ma.MaskedArray.mini`

### LINKED ISSUE #8764: DEP: Deprecate `np.masked_array.mini`
It's not at all clear why this exists, or how `MaskedArray.mini` is different from `MaskedArray.min`

This was introduced in 80f6f5062022104f3a57de05cb119df23c2b5de4 by @stefanv, in a patch claimed to be authored by Pierre ( @pierregm? )

### PR DESCRIPTION
**Pull request by eric-wieser**
This was untested, and the documentation did not mention how it differed from `min` anyway.

Fixes #8764

Also (movable to another PR on request):
 
* Deprecates `np.ma.minimum(x)` as an alias for `np.ma.minimum.reduce`, because this alias does not exist for `np.minimum(x)` in core, and this makes the distinction between `minimum` and `min` confusing
* Corrects the default axis of `np.ma.minimum.reduce`, which was different from that in core. (but not documented anywhere)

### CODE REVIEW

**Comment by eric-wieser** [comment]
(appveyor was broken)

**Comment by stefanv** [comment]
This looks good to me.  The only other place in which we may want to mention the reduce is the docstring of minimum, as an example.

**Comment by eric-wieser** [comment]
> the docstring of minimum

You mean the one at `np.ma.minimum.__doc__` that is currently just `'Object to calculate minima'`?

**Comment by stefanv** [comment]
Right :)

**Comment by charris** [comment]
Needs rebase. Maybe deal with comment.

**Comment by eric-wieser** [comment]
Is that last commit an API break, requiring deprecation like #8918 ?

**Comment by eric-wieser** [comment]
Rebased, comment addressed

**Comment by charris** [comment]
> requiring deprecation like #8918 ?

Hmm. Looks like it does as the default behavior is changed.

**Comment by charris** [comment]
Mostly, I'm trying to get the deprecations in before branching 1.13.

**Comment by eric-wieser** [comment]
Ok, respun as a deprecation, rather than an API-breaking bugfix

**Comment by charris** [comment]
Thanks Eric.

**Pull request merged**
