### PR TITLE
ENH: add keyword `nrows` to `genfromtxt`, closes #5084 #5090 #5093

### LINKED ISSUE #5084: Hope genfromtxt function add nrows keyword
numpy function `genfromtxt` can skip header and footer lines. However sometimes we might want to control the number of rows to read directly. For example, a txt file might contain  several blocks with different number of columns, we can't read them all in once. Specify `nrow` to read would be convenient.

Is it possible add something like 
`genfromtxt(file,skip_header=1,nrows=2)` ?

### PR DESCRIPTION
**Pull request by syrte**
Change the brach from master to feature branch. 
No code changed.

### CODE REVIEW

**Comment by charris** [comment]
@WarrenWeckesser Do you consider this ready? If so, I'll cleanup the commits and push it.

**Comment by charris** [comment]
It looks like `max_rows` is preferred to `nrows`.

**Comment by WarrenWeckesser** [comment]
https://github.com/numpy/numpy/pull/5253 is my continuation of this PR, where I changed the argument to `max_rows`.

**Comment by charris** [comment]
@WarrenWeckesser So how to proceed? Should this be closed in favor of #5253?

**Comment by WarrenWeckesser** [comment]
> Should this be closed in favor of #5253?

That would be my preference, if @styra agrees.  Then you and the other numpy devs can decide if #5253 should be merged.  Some alternatives were suggested on the mailing list in November, but I don't think any core developers chimed in.

**Comment by charris** [comment]
As long as @styra commit(s) stay, I don't see a problem with closing this. `max_rows` does seem more descriptive than `nrows`, although in the examples in the discussion `nrows` would do. Things to do

1) styra's commits should be squashed and the commit message amended. Something like
```
    ENH:Add keyword nrows to genfromtxt.
    
    This allows one to specify the maximum number of rows processed in
    in a call. The new functionality allows for reading more complex
    data formats. For instance, multiple calls can be used to read in
    multiple arrays stored in a single file.
    
    Closes #5084.
    Closes #5093.
```
2) Your commit should probably be `MAINT`.

3) A note should be added to the 1.10 release notes.

@styra If you want to do this, speak up. Otherwise I will be closing this.

**Comment by charris** [comment]
@styra @WarrenWeckesser NVM, I'll fix this up and push.

**Comment by charris** [comment]
Closing, see #5496. Thanks @styra.

**Pull request closed without merging**
