### PR TITLE
MAINT: remove counter-based Philox and Threefry BitGenerators

### PR DESCRIPTION
**Pull request by mattip**
In order to ground the discussion about which BitGenerator to include/remove, this PR suggests removing the counter-based Philox and ThreeFry generators. [Quoting](https://github.com/numpy/numpy/pull/13675#issuecomment-502427589) @rkern in PR numpy/numpy#13675 (hopefully not taken too much out of context):

> I think only one of these needs to be here. I think I would also dispute the "very popular in machine learning". I'm pretty sure neither (or both collectively) are more popular than MT19937 in that field or any other, just because defaults matter. What they do have is relevance to massively-parallel applications in GPUs (because you can trivially get independent streams with dumb seed allocation), which I think is the source of the claim. But that leads me to question whether numpy is the right place, if that's the justification. It seems to me that you would want to get the implementation from the package that's providing the GPU implementation as well to ensure that they are the same; I certainly would. Each of these has a couple of variants within the family, and if we're playing around with the seeding like SeedSequence, that's just another place where implementation differences can creep in. At the same time, if we can promote the use of @imneme's strong seeding algorithm through SeedSequence, then it's entirely possible that that would obviate the desirability of these algorithms on the GPU; one could pick faster GPUable algorithms that just need strong, but not perfect, seed allocation.

> That said, having a counter-based medium-strength-crypto PRNG might be justification enough all by itself; I'm just wobbly on the stated "popular in machine learning" justification.

which would seem to suggest maybe this PR is too much and one of them should remain, but which?

### CODE REVIEW

**Comment by charris** [comment]
Circle CI says you need a blank line.

**Comment by mattip** [comment]
I have moved the code to numpy/bitgenerators. As of today it is not yet building, I hope to fix that over the next few days but that enables merging this PR as the code will not get lost.

**Comment by bashtage** [comment]
I think at least one of these should be retained.   Cipher-based CB RNGs are quite different from the others included and have some desirable statistical properties.  It is likely that CBRNGs are the most statistically sound RNGs that have been considered.  For example, they never have cycles that you get stuck in, which isn't guaranteed by many other families. They are also simpler to seed in parallel. The only real limitation of most CBRNGs is their performance, and they are notable slower than PCG/Xoshiro/JSF and others.  If they had the performance of PCG, I would think they would be the best choice for the default PRNG. 

I also like the idea of having at least 2 first class generators, especially when they are from different families.  The differences between these help to ensure that additional RNG-specific features are not overly coupled to the default RNG.  I recognize that this is a second-order concern, but as someone who is likely to maintain some bit generators outside of NumPy, it is very helpful to have the separation enforced. This point is somewhat generic and could be satisfied by a range of generators. 

I have an improved version of Philox the provides all 4 variants here: https://github.com/bashtage/randomgen/blob/master/randomgen/philox.pyx

This would probably be my preference for a second generator after PCG.

**Comment by charris** [comment]
I agree that is would be nice to have one of these, as it looks like things might go that way in the future, especially if hardware support comes online. Not that we want to get into the hardware nitty-gritty, but having one might provide for useful experimentation. @bashtage Could you pick one?

**Comment by rkern** [comment]
Replaced by #13833

**Pull request closed without merging**
