### PR TITLE
MAINT: Ufunc parsing super fast (work in progress)

### PR DESCRIPTION
**Pull request by mhvk**
It is probably useful to see where I hope all my PRs lead to. Combining #11338, #11351, #11282 plus follow-up commits, the reduction is becoming quite impressive (speeds are: current master -> #11351 -> this PR.
```
import numpy as np
a = np.array(1)
b = np.empty_like(a)
%timeit np.positive(a)                                 # 352->348->294 ns
%timeit np.positive(a, subok=True)                     # 606->501->377 ns
%timeit np.positive(a, where=True)                     # 586->503->366 ns
%timeit np.positive(a, where=True, subok=True)         # 695->531->394 ns
%timeit np.positive(a, b)                              # 354->352->263 ns
%timeit np.positive(a, out=b)                          # 557->480->316 ns
%timeit np.positive(a, out=b, subok=True)              # 668->506->420 ns
%timeit np.positive(a, out=b, where=True, subok=True)  # 752->536->451 ns
```

The main plan I followed was to use interned strings instead of `char`, and to ensure things get done only once, in particular with output arguments: `out` is now resolved right at the start and treated as a positional argument thereafter. In the process, `ufunc_full_args` disappeared again, since the code can now count on all arguments being in one place.

Note: no need to try to comment on all of this at once - this is mostly here to show that the work is worth it, and that I have something to refer to when discussing particular bits.

p.s. To my dismay, just adding `subok=True` still costs about 85 ns: 40ns in python for creating kwargs, 20ns for looking for out when it isn't there, and about 25 ns in parsing it.

### CODE REVIEW

**Comment by eric-wieser** [comment]
For comparison on your machine, can you show the timing for `+a` and `a_builtin = 1; +a_builtin`?

**Comment by mhvk** [comment]
I think `+a` does not (yet?) go through `np.positive`, since it is much faster. But negative does (and `np.negative` gives the same timings as above). Built-in is of course far faster still (but, hey, I've not done anything yet to actual code, just the parsing of arguments!).
```
%%timeit
np.negative(a)  # 290 ns
%%timeit
-a  # 267 ns
negative = np.negative
%%timeit
negative(a)  # 260 ns
a_builtin = 1
%%timeit
-a_builtin  # 17.6 ns
```

**Comment by mhvk** [comment]
One generic question is the extent to which we're willing to adapt the signature of `PyUFunc_GenericFunction`. In particular, it might make sense to adopt the `METH_FASTCALL` signature, i.e., `PyObject **stack, Py_ssize_t nargs, PyObject *kwnames`, where `stack` contains the `nargs` arguments as well as the values of the keywords with the names given in the `kwnames` tuple.
In principle, this could even be used for the reductions (but sadly not for `__call__`).

**Comment by mattip** [comment]
> In particular, it might make sense to adopt the METH_FASTCALL

Since this function is part of the public API I would prefer to keep it simple.

**Comment by mhvk** [comment]
> Since this function is part of the public API I would prefer to keep it simple.

Yes. In fact, that also means that some of what I'm doing here is not quite right; I cannot assume that `out` is not present in `kwargs`. I might need to let this call an internal, private function and use that as well for `ufunc_general_call`. Anyway, clearly a benefit of showing it now! And another reason for proceeding in slow steps.

**Comment by shoyer** [comment]
It looks like all these other PRs are merged -- can we close this?

**Comment by mhvk** [comment]
This has quite a bit of follow-up commits, but I would definitely have to re-do those now that `multiarray` and `umath` are merged. So let me indeed close it here.

**Pull request closed without merging**
