### PR TITLE
REL: add "make upload" command for built docs, update "make dist".

### PR DESCRIPTION
**Pull request by rgommers**
Changes to "make dist" for building docs:
- remove .chm related line, we don't distribute those on docs.scipy.org
- only include needed pdf files in dist.tar.gz

Note that I chose not to trigger `dist` from `upload` because one should be able to run `dist` without specifying username/release and without getting errors.

[ci skip]

### CODE REVIEW

**Comment by rgommers** [comment]
@pv ping. I've tested this and this works for me (numpy-1.9.2/ is now present on the server).

**Comment by pv** [comment]
Add a call to the fixperm script, to fix group permissions.

**Comment by rgommers** [comment]
Thanks, done.

**Comment by charris** [comment]
I'm inclined to backport this to 1.10.x for the next release.

**Comment by rgommers** [comment]
@charris go for it if you want to, but not essential. I can use it anyway to build and upload the 1.10.2 docs, you can just ping me.

**Comment by charris** [comment]
Maybe add some notes to `HOWTO_BUILD_DOCS.rst.txt` or `HOWTO_RELEASE.rst.txt`, or maybe both. Probably does not need to be mentioned in the release notes, but can't hurr.

**Comment by rgommers** [comment]
@charris good point, done.

**Comment by charris** [comment]
Thanks Ralf.

**Pull request merged**
