### PR TITLE
API: Readd `sctypeDict` to the main namespace

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @ngoldbaum,

In this PR I restored `np.sctypeDict`.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Looks like the ubuntu apt mirrors are having network instability and are causing some CI failures. Going to merge now to fix the Jax CI.

**Comment by jakevdp** [comment]
I think this also needs to be removed from `__expired_attributes__` in order to be importable: https://github.com/numpy/numpy/blob/399c0c5139bae794f1c3b44f97cac9c6565ef651/numpy/_expired_attrs_2_0.py#L47

**Comment by ngoldbaum** [comment]
I'm not able to reproduce that locally.

I don't think execution goes into `__getattr__` if attribute access succeeds:

```
# mod.py
def __getattr__(attr):
    raise AttributeError(attr)

foo = 3
```

```
def __getattr__(attr):
    raise AttributeError(attr)

foo = 3
```

Are you doing something different where execution ends up in the module `__getattr__`?

Regardless, you're right that was left behind, @mtsokol when you have a chance would you mind cleaning this up?

**Comment by mtsokol** [comment]
@ngoldbaum Ah yes, I forgot to remove it from the dict, but it's just unused - I will remove it in another PR.

**Pull request merged**
