### PR TITLE
 ENH: Enabled the use of numpy.vectorize as a decorator

### LINKED ISSUE #9477: vectorize-style decorator
Would be really handy to have a `vectorize`-like implementation that acts like a Python decorator. To be clear, `vectorize` almost satisfies that need, but one cannot use it as a decorator and pass keyword arguments. There are certainly easy ways around this, but it would be nice to have an accepted way to do this in NumPy for simple reuse.

### PR DESCRIPTION
**Pull request by MatteoRaso**
An improved version of #23061. Resolves #9477 and #23021.

### CODE REVIEW

**Comment by MatteoRaso** [comment]
Ok, I've fixed the benchmark and `Partial` problem. There's a bunch of other tests failing, but looking over them, it doesn't seem to have to do with the changes I made. That being said, please look over them in case I'm wrong.
@mattip 
@mhvk 
@seberg 
@WarrenWeckesser

**Comment by charris** [comment]
Can you rebase on current main? 455 files changed is a bit much and I think accounts for some of the problems.

**Comment by MatteoRaso** [comment]
>Can you rebase on current main? 454 files changed is a bit much and I think accounts for some of the problems.

So sorry, didn't even notice. Yes, I'll try to rebase.

**Comment by MatteoRaso** [comment]
Ok, rebase was successful.

**Comment by charris** [comment]
Let's give this a shot and see if downstream complains. Thanks @MatteoRaso .

**Comment by MatteoRaso** [comment]
No problem.

------- Original Message -------

**Pull request merged**
