### PR TITLE
MAINT: C code no longer calls Python _newnames()

### PR DESCRIPTION
**Pull request by tylerjereddy**
### Background

While looking through the source for some of the `dtype` internals (`numpy/core/src/multiarray/descriptor.c`) I noticed that C code calling Python code in `_convert_from_commastring()` is described in the comments as:

> path critical C code calling Python code

that should be cleaned up and re-written in C. While that particular effort looks very challenging (either re-implement the regex in C or use platform-specific regex options in C), there are other locations in the source code where `PyImport_ImportModule` is used to call Python code from C code, perhaps to some detriment (as the above comment implies).

### The target here

One of the awkward C-calling-Python scenarios surrounds the `_newnames()` function, which seems to be used a lot with i.e., `recarray` for handling fields. There are several C functions in `numpy/core/src/multiarray/methods.c` that call the Python version of this function, presumably to perform similar tasks.

### The changes here

I've reimplemented `_newnames()` using C / Python C-API; it was pretty painful to get working despite the apparent simplicity of the Python version. The Python equivalent has been removed and the C code now calls a C function proper that appears to now do the same thing as the previous Python version.

Not sure if this kind of transformation / maintenance is really called for, but it does seem less ugly to avoid the Python-C-Python thing. What do people think?

### CODE REVIEW

**Comment by jeffyancey** [comment]
I can't see any downsides to migrating `_newnames()` to C. You say "appears to do the same thing", and as far as I can tell, they are equivalent as well.

**Comment by tylerjereddy** [comment]
Looks like everything passes except Python 3.4; I isolated the segfault to `test_partition_cdtype` and in particular there may be PEP 442 related reference counting issues (which were later adjusted in Python 3.6?).

In Python 3.4 this segfaults:
```Python
d = np.array([('Galahad', 1.7, 38), ('Arthur', 1.8, 41),
              ('Lancelot', 1.9, 38)], 
              dtype=[('name', '|S10'), ('height', '<f8'), ('age', '<i4')])
tgt = np.sort(d, order=['age', 'height'])
# second call causes segfault on Python 3.4 only
tgt = np.sort(d, order=['age', 'height'])
```

The segfault can be prevented by duplicating the definition of `d`, but not by using `d.copy()` -- so this works on Python 3.4:

```Python
d = np.array([('Galahad', 1.7, 38), ('Arthur', 1.8, 41),
              ('Lancelot', 1.9, 38)], 
              dtype=[('name', '|S10'), ('height', '<f8'), ('age', '<i4')])
d = np.array([('Galahad', 1.7, 38), ('Arthur', 1.8, 41),
              ('Lancelot', 1.9, 38)], 
              dtype=[('name', '|S10'), ('height', '<f8'), ('age', '<i4')])
tgt = np.sort(d, order=['age', 'height'])
tgt = np.sort(d, order=['age', 'height'])
```

Wild! But perhaps not entirely surprising since I'm not particularly experienced with the manual reference counting in Python C API.

**Comment by eric-wieser** [comment]
> path critical C code calling Python code

I don't believe this. If string-parsing is path critical, then don't do it, and declare the dtypes structurally instead.

**Comment by charris** [comment]
Python 3.4 segfaults. We will be dropping 3.4, but I'd rather not break it out of the starting gate :) I assume that this is intended to speed up some operations, does it do so and are we tracking those in the benchmarks?

**Comment by tylerjereddy** [comment]
I can look into benchmarks;  I was mostly just assuming that calling Python functions from our C code was something that is useful to avoid where possible from a design / overhead standpoint, but assuming is never sufficient with performance.

Perhaps `PyImport_ImportModule` in C code that calls Python isn't so bad, but seems ugly--I guess I need the benchmarks to show.

Was hoping there would be an obvious reference count issue / leak in my source re: the Python 3.4 issue;  I'll try to take another shot at that.

**Comment by tylerjereddy** [comment]
So, probably -1 here then; for completeness, here are some early benchmarks (I've pushed the rough draft benchmark code etc. to the PR as well for transparency--a ref counting issue seems to persist somehow):

`asv continuous 591880b 44082abb -e -b "time_sort_array_fields" >& bench_log_specific.txt`

```
 38        before           after         ratio                                     
 39      [591880b0]       [44082abb]                                                
 40 -      23.0±0.6μs       15.0±0.5μs     0.65  bench_methods.FieldHandling.time_sort_array_fields(20)
 41 -      17.0±0.5μs       10.0±0.5μs     0.59  bench_methods.FieldHandling.time_sort_array_fields(10)
 42 -        12.0±2μs       7.00±0.5μs     0.58  bench_methods.FieldHandling.time_sort_array_fields(1)
 43 -      14.0±0.5μs       8.00±0.5μs     0.57  bench_methods.FieldHandling.time_sort_array_fields(3)
 44 -        16.0±2μs       9.00±0.5μs     0.56  bench_methods.FieldHandling.time_sort_array_fields(5)
 45                                                                                 
 46 SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.   
```

The gains probably occur mostly when the sorting operation itself is fast and the string parsing gets used more in a relative sense; anyway, < 2 x improvement is perhaps not remarkable enough to overcome the resistance here & increased maintenance burden longer-term.

There may be some other scenarios that better showcase an improvement, but not clear on which off-hand.

**Pull request closed without merging**
