### PR TITLE
DOC: Correct documentation of `numpy.delete` obj parameter.

### PR DESCRIPTION
**Pull request by abdur-n-tr**
DOC: Correct the doc of `obj` parameter of  in `numpy.delete`.

### CODE REVIEW

**Comment by mattip** [comment]
I guess this is an improvement, although what else could `obj` be other than indices?

**Review by eric-wieser — APPROVED** [review]

**Comment by ahaldane** [comment]
Thanks @abdurrehman11

**Comment by ahaldane** [comment]
You mean on scipy.org? Those generally only get updated after a release, which is most likely 1.17 for this PR.

**Comment by abdurrehman11** [comment]
Thanks @ahaldane for cooperation.

**Pull request merged**
