### PR TITLE
DOC: add note and examples to `isrealobj` docstring

### LINKED ISSUE #12652: numpy.isrealobj('a string') is True !
numpy.isrealobj('a string') is True ! and various other inconsistencies between isrealobj, isreal and iscomplexobj

### Reproducing code example:

```
$ python3
Python 3.4.9 (default, Aug 14 2018, 21:28:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.version.version
'1.10.4'
>>> numpy.isrealobj('a string')
True
>>> numpy.iscomplexobj('1+1j')
False
>>> numpy.isrealobj(False)
True
>>> numpy.iscomplexobj(False)
False
>>> numpy.isreal('1.0')
False
>>> numpy.isreal(True)
True
>>> numpy.isreal({'a':'1','b':1})
True
```

### Numpy/Python version information:

1.10.4 3.4.9 (default, Aug 14 2018, 21:28:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

### PR DESCRIPTION
**Pull request by yashasvimisra2798**
Fixes #12652

Co-authored-by:  Mukulika 60316606+Mukulikaa@users.noreply.github.com
@Mukulikaa

### CODE REVIEW

**Comment by rossbar** [comment]
For reference, similar changes were just made to the `isreal` docstring in #18843

**Review by rgommers — APPROVED** [review]
LGTM, thanks @yashasvimisra2798 and @Mukulikaa!

**Comment by rgommers** [comment]
A couple of small things for next time:
- Note that it is usually not necessary (/desired) to merge main into the branch you made the PR from. That will only make the commit history more 
- I added some details to your commit message, and edited the title. Being descriptive is always useful, that way people don't have to go look at the issue description.

**Comment by Mukulikaa** [comment]
Thank you, @rgommers! I've taken a note of this for next time :)

**Comment by yashasvimisra2798** [comment]
Thanks, @rgommers will keep these things in mind from next time.

**Pull request merged**
