### PR TITLE
NEP: Edit nep-0042 for more clarity

### PR DESCRIPTION
**Pull request by seberg**
This is a pretty large reorganizing of NEP 42 with a huge amount of work from Ben. It may not be the final word, but I think we should put it in and hope that further cleanups will be more localized.

The actual proposal did not shift much, I did delete occasional details that seemed not necessary in hindsight.  There is a new paragraph (and image) for NEP 41, to explain "parametric" a bit more.  I am happy to split it out.

---

**NOTE: Please squash merge, the history is not clean, but I did not want to rewrite it just yet!**

### CODE REVIEW

**Comment by seberg** [comment]
The test failure is just because this isn't rebased on a recent enough master.  For anyone tempted to read it, I would highly suggest to clone the branch and `make html` in the `doc/neps` folder.

**Comment by stefanv** [comment]
"Types are written as a single Python class in which each datatype is a special instance" — "of which" ?

**Comment by stefanv** [comment]
"which is a subclass of np.dtype. np.dtype[float64] will also denote this class" — missing some spaces there

**Comment by stefanv** [comment]
Author list: should add @bjnath if he is interested.

**Comment by stefanv** [comment]
I've read the first bit now, and I think the motivation is looking fantastic!

**Comment by seberg** [comment]
@stefanv, sorry, but can you double check that your branch is up to date? I am having trouble finding the sentences you are referring to. @bjnath is already listed now as author, although he can have another chance to prefer not to ;).

**Comment by stefanv** [comment]
@seberg Sorry, I had a slightly older build, you're right.

**Comment by charris** [comment]
Putting this in, it already has too many commits :) Thanks Sebastian.

**Pull request merged**
