### PR TITLE
MAINT: Add appropriate exception message for divide by zero

### PR DESCRIPTION
**Pull request by Rushali-Sarkar**
Chained Exception in _polybase.py
Added Exception error for division by zero

### CODE REVIEW

**Comment by mattip** [comment]
Could you show an example of what traceback is printed before this change, and what traceback is printed afterwards?

**Comment by rkern** [comment]
Not sure why we're changing the `ZeroDivisionError` into a `ValueError`. Can you link to the issue in which this was discussed?

**Comment by rkern** [comment]
IMO the current code in `main` is the correct one. The issue that was noted in #15986, the "chain exceptions" mega-issue, was fixed in #17453.

**Comment by charris** [comment]
Going to close this. Thanks @Rushali-Sarkar for giving it a try.

**Pull request closed without merging**
