### PR TITLE
DOC: link to the npy-format NEP in numpy.npyio docs.  Closes gh-4523.

### PR DESCRIPTION
**Pull request by rgommers**
[ci skip]

### CODE REVIEW

**Comment by jaimefrio** [comment]
I believe we now also have a version 2.0 of the NPY format after #4765. Shouldn't stop this PR, but the new format should be similarly documented. Can the NEP be updated?

**Comment by charris** [comment]
@jaimefrio Yep, docs need an update. I put this in as is for now.

**Comment by charris** [comment]
Thanks Ralf.

**Comment by rgommers** [comment]
I'll update the docs.

**Comment by rgommers** [comment]
done in gh-5423

**Pull request merged**
