### PR TITLE
Fix 1.9 alignment

### PR DESCRIPTION
**Pull request by charris**
Backport of #5316 with potential modification suggested by Julian. After review, extra commit willl be squashed.

### CODE REVIEW

**Comment by charris** [comment]
@juliantaylor Could you check this?

**Comment by charris** [comment]
OK remove 'fixup'.

**Comment by juliantaylor** [comment]
looks ok, I'll probably backport some more minor stuff this weekend and then we can do a 1.9.2

**Comment by juliantaylor** [comment]
note I don't know when I'll finish the other fix, I tend to look at the duplication in raw_assign* get anoyed and stop, and I'm also to lazy to actually try to homogenize it ;)

**Pull request merged**
