### PR TITLE
BUG: Fix casting between npy_half and float in einsum

### LINKED ISSUE #10899: BUG: result of numpy.einsum is sometimes wrong with float16
To reproduce:
```
>>> np.einsum('i,ji->', np.ones(2, dtype=np.float16), np.eye(2, dtype=np.float16))
32770.0
```

Why:
`*(@type@ *)dataptr[2] += @to@(accum);` in https://github.com/numpy/numpy/blob/3ec8875/numpy/core/src/multiarray/einsum.c.src#L594 is preprocessed to `*(npy_half *)dataptr[2] += npy_float_to_half(accum);`.  The example above works fine if the line is replaced with
```
*(@type@ *)dataptr[2] = @to@(@from@(*(@type@ *)dataptr[2]) + accum);
```

### PR DESCRIPTION
**Pull request by toslunar**
Fix #10899

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you add a test too?

**Comment by toslunar** [comment]
Thanks.  I added three test cases that correspond to the fixed lines.  Each test case hits exactly one of the three lines.

I also confirmed that these test fail in the master branch.
```
% python
Python 3.6.2 (default, Jul 17 2017, 16:44:45)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.test()
NumPy version 1.15.0.dev0+8323be1
NumPy relaxed strides checking option: True
.................x...................................................... [  1%]
...............................s........................................ [  3%]
............................................................s........... [  4%]
............................................s.........................FF [  6%]
F....................................................................... [  7%]
....^C
=================================== FAILURES ===================================
_______________________________ TestEinSum.test1 _______________________________

self = <numpy.core.tests.test_einsum.TestEinSum object at 0x10dc93cf8>

    def test1(self):
        optimize = False
        x = np.eye(2, dtype='f2')
        y = np.ones(2, dtype='f2')
        assert_array_equal(np.einsum("ji,i->", x, y, optimize=optimize),
>                          [2.])  # contig_contig_outstride0_two
E       AssertionError:
E       Arrays are not equal
E
E       (mismatch 100.0%)
E        x: array(32770., dtype=float16)
E        y: array([2.])

optimize   = False
self       = <numpy.core.tests.test_einsum.TestEinSum object at 0x10dc93cf8>
x          = array([[1., 0.],
       [0., 1.]], dtype=float16)
y          = array([1., 1.], dtype=float16)

py3npy/lib/python3.6/site-packages/numpy-1.15.0.dev0+8323be1-py3.6-macosx-10.12-x86_64.egg/numpy/core/tests/test_einsum.py:539: AssertionError
_______________________________ TestEinSum.test2 _______________________________

self = <numpy.core.tests.test_einsum.TestEinSum object at 0x10dc9f208>

    def test2(self):
        optimize = False
        x = np.eye(2, dtype='f2')
        y = np.ones(2, dtype='f2')
        assert_array_equal(np.einsum("i,ij->", y, x, optimize=optimize),
>                          [2.])  # stride0_contig_outstride0_two
E       AssertionError:
E       Arrays are not equal
E
E       (mismatch 100.0%)
E        x: array(32770., dtype=float16)
E        y: array([2.])

optimize   = False
self       = <numpy.core.tests.test_einsum.TestEinSum object at 0x10dc9f208>
x          = array([[1., 0.],
       [0., 1.]], dtype=float16)
y          = array([1., 1.], dtype=float16)

py3npy/lib/python3.6/site-packages/numpy-1.15.0.dev0+8323be1-py3.6-macosx-10.12-x86_64.egg/numpy/core/tests/test_einsum.py:546: AssertionError
_______________________________ TestEinSum.test3 _______________________________

self = <numpy.core.tests.test_einsum.TestEinSum object at 0x11160f080>

    def test3(self):
        optimize = False
        x = np.eye(2, dtype='f2')
        y = np.ones(2, dtype='f2')
        assert_array_equal(np.einsum("ij,i->", x, y, optimize=optimize),
>                          [2.])  # contig_stride0_outstride0_two
E       AssertionError:
E       Arrays are not equal
E
E       (mismatch 100.0%)
E        x: array(32770., dtype=float16)
E        y: array([2.])

optimize   = False
self       = <numpy.core.tests.test_einsum.TestEinSum object at 0x11160f080>
x          = array([[1., 0.],
       [0., 1.]], dtype=float16)
y          = array([1., 1.], dtype=float16)

py3npy/lib/python3.6/site-packages/numpy-1.15.0.dev0+8323be1-py3.6-macosx-10.12-x86_64.egg/numpy/core/tests/test_einsum.py:553: AssertionError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
to show a full traceback on KeyboardInterrupt use --fulltrace
/Users/tos/py3npy/lib/python3.6/site-packages/numpy-1.15.0.dev0+8323be1-py3.6-macosx-10.12-x86_64.egg/numpy/core/fromnumeric.py:65: KeyboardInterrupt
3 failed, 357 passed, 3 skipped, 70 deselected, 1 xfailed in 11.19 seconds
False
>>>
```

**Comment by mattip** [comment]
LGTM

**Comment by charris** [comment]
Hmm, some lines > 80 characters in length, but I think is helps clarity in these cases.

**Pull request merged**
