### PR TITLE
BUG: Cannot convert boolean arrays to ctypes with ctypeslib 

### PR DESCRIPTION
**Pull request by Czapkaman**
Bugfix to #6176 bool class from ctypes. 
It works for me but you should check it.

### CODE REVIEW

**Comment by mattip** [comment]
Tests needed, at a minimum the test from the issue

**Comment by mattip** [comment]
Also please squash the numerous commits

**Comment by eric-wieser** [comment]
This is also fixed in #12456

**Comment by mattip** [comment]
Fixed in #12456 which was merged. Thanks @Czapkaman, please continue to contribute

**Pull request closed without merging**
