### PR TITLE
API: Remove several niche objects for numpy 2.0 python API cleanup

### PR DESCRIPTION
**Pull request by ev-br**
As discussed in https://github.com/numpy/numpy/issues/23999#issuecomment-1626916281, specifically https://github.com/numpy/numpy/issues/23999#issuecomment-1600974562, remove
- [x] np.cast
- [ ] <s>np.info</s>
- [x] np.source
- [x] np.lookfor

An alternative is of course to formally deprecate them first :-).

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I think `np.info` was supposed to stick around.

**Comment by WarrenWeckesser** [comment]
There has been recent activity related to `info`, e.g. https://github.com/numpy/numpy/issues/23245, https://github.com/numpy/numpy/pull/23355.

I'm ambivalent about the ultimate fate of `info`, but if it is to be removed, the removal must be consistent with the usual deprecation policy.  Let's not get *too* trigger happy with removing stuff without the correct deprecation cycle; we should not fall into the [normalization of deviance](https://en.wikipedia.org/wiki/Normalization_of_deviance) where we get casual about removing seemingly insignifcant things without deprecation.   There should be a really compelling reason for not sticking to the standard deprecation process.

**Comment by ev-br** [comment]
OK, updated with `np.info` staying intact.

**Comment by rgommers** [comment]
> . Let's not get _too_ trigger happy with removing stuff without the correct deprecation cycle; we should not fall into the [normalization of deviance](https://en.wikipedia.org/wiki/Normalization_of_deviance) where we get casual about removing seemingly insignifcant things without deprecation. There should be a really compelling reason for not sticking to the standard deprecation process.

There is a compelling reason, namely NumPy 2.0 which already requires new releases and wheel builds from every significant downstream package. I think this is the wrong PR to make this comment; this PR seems fine to me given
https://numpy.org/neps/nep-0052-python-api-cleanup.html#backward-compatibility. Having it deprecated in 2.0 and then removed in 2.2 is kind of pointless work for these APIs, and has a negative impact on one of the key goals for 2.0.

**Comment by rgommers** [comment]
I had a look at `np.info` and the linked issues - it seems like it is useful to some users, but the docstring for it is completely wrong - it is not at all equivalent to `help/?`.

**Comment by seberg** [comment]
I would like to always think of the two things:
* who is affected:  in this case at least probably very few, and most of the functions are docs, so no-one in production
* how are they affected:  I think in this case the replacement is rather obvious.

I will grant that `np.info` has probably uses and users at least for teaching, so happy to keep it.

**Comment by seberg** [comment]
@ev-br can you add brief release notes?  Maybe with a sentence saying to replace `np.cast` with the call to `.astype()` or `np.asarray(..., dtype=)`?  (I guess for `source`, `??` or inspect may also be something we could point to)

**Comment by seberg** [comment]
But, if anyone disagrees, I don't mind making it a deprecation, I just think the step adds little beyond allowing downstream to work without updates, and large chunks of downstream won't have that (and this won't be the reason why).

**Comment by seberg** [comment]
Test failures are unfortunately real, there seem to be remains of these in the typing tests.

**Comment by ev-br** [comment]
CI is 🟢

**Comment by seberg** [comment]
Grrrrrrr, I did a github code search found a decent amount of `np.cast[` usage.  Considering that it's ugly but trivial code, probably it's better to only deprecate it :(.

I can follow up with that and finish that, though.

**Comment by rgommers** [comment]
> Grrrrrrr, I did a github code search found a decent amount of `np.cast[` usage. Considering that it's ugly but trivial code, probably it's better to only deprecate it :(.

If it's trivial to update, I think we should remove it. And otherwise we have to ensure it's not in the reference guide anymore - in this particular case that's already true though, so no extra work (but also an extra reason to remove, it was never even meant as public API).

**Comment by seberg** [comment]
Ok, let's roll with it.  I will note that if anyone complains about `np.cast` with some conviction, I will vote to revert it.  I don't really think its worth.

The replacement suggesting might not create a copy when there previously was, but I don't think that should be a problem, but rather an improvement in most cases.

**Comment by jakevdp** [comment]
One note: removing `cast` breaks scipy, which references it here: https://github.com/scipy/scipy/blob/42224e89fe4b0eecef866d7e57dd9312b42e289c/scipy/linalg/_decomp.py#L22

Discovered because JAX's upstream nightly CI failed: https://github.com/google/jax/issues/16864

Should there be some kind of deprecation cycle here? As is, the next numpy release will lead to an import error for all previous releases of scipy.

**Comment by seberg** [comment]
I am not worried about SciPy since it must adapt to 2.0 anyway as a C-API user.  But it is a data-point towards it being used enough to go through a deprecation to help smooth transition for small less maintained Python libs that may also use it.

**Comment by ev-br** [comment]
scipy PR: https://github.com/scipy/scipy/pull/18973

**Pull request merged**
