### PR TITLE
MAINT: Fix a few more typos

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Additional typos not fixed in #27376.

I am not sure how to fix this comment:
```
$ grep -n wither numpy/numpy/_core/tests/test_half.py 
52:        # avoid testing NaNs due to differ bits wither Q/SNaNs
$ 
```
Perhaps:
```
        # avoid testing NaNs due to differing bits in Q/S NaNs
```

### CODE REVIEW

**Comment by charris** [comment]
> differing bits in Q/S NaNs

I'd write them out, "quiet and signaling NaNs".

**Comment by musvaage** [comment]
`https://www.ibm.com/docs/en/openxl-fortran-aix/17.1.2?topic=overview-infinities-nans`

this page refers to bit patterns

**Comment by musvaage** [comment]
> quiet and signaling NaNs

deferring to a repo Member on this one

but if I read the content of the previous comment's cited webpages correctly then perhaps

``` 
        # avoid testing, due to different bit patterns in quiet and signaling NaNs
```

**Comment by musvaage** [comment]
@seiko2plus

_cf_: comment on NaNs

Have you any opinion on herein proposed rewording?

**Comment by musvaage** [comment]
numpy/_core/tests/test_half.py

the dumped comment lines from the file otherwise look good excepting the following

`is been`
`calculations tries`
`mid points`

```
$ ed -s numpy/numpy/_core/tests/test_half.py <<<'25p'
        # NaN value can cause an invalid FP exception if HW is been used
$ ed -s numpy/numpy/_core/tests/test_half.py <<<'122,126p'
        # The above calculations tries the original values, or the exact
        # mid points between the float16 values. It then further offsets them
        # by as little as possible. If no offset occurs, "round to even"
        # logic will be necessary, an arbitrarily small offset should cause
        # normal up/down rounding always.
$ 
```

**Comment by seiko2plus** [comment]
@DimitriPapadopoulos, @musvaage  Thank you a lot for covering my typos.

> Have you any opinion on herein proposed rewording?

Not really, but the current rewording is ideal to me:
``` 
# avoid testing NaNs due to differing bit patterns in Q/S NaNs
```

**Comment by musvaage** [comment]
@mattip and @rkern

Thanks for the review on one of the predecessor PRs.

<hr>

_this is only for my records_

 BUG: Fix build on ppc64 when the baseline set to Power9 or higher `#24806`
charris merged 4 commits on Nov 7, 2023

_cf_:  ENH, TST: Modify half-precision tests to deal with FP HW exceptions

MAINT: fix typos `#27344`
charris merged 1 commit on Sep 11, 2024

 MAINT: Fix a few typos - and sometimes improve wording `#27376`
charris merged 1 commit on Sep 11, 2024

**Comment by mattip** [comment]
Thanks @DimitriPapadopoulos

**Pull request merged**
