### PR TITLE
DOC: np.fromfunction documentation not clear

### PR DESCRIPTION
**Pull request by soumyasomasundaran**

### CODE REVIEW

**Comment by mattip** [comment]
Is this PR in response to some issue or problem? Please expand on the need for it.

**Comment by soumyas567** [comment]
No, It is not.  I am a first-time contributor. 
In the fromfunction() documentation, it is said as below 
"The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis. For example, if shape were (2, 2), then the parameters would be array([[0, 0], [1, 1]]) and array([[0, 1], [0, 1]])"
The parameters for the array along the axis is given as [0,0] [1,1] and [0,1][0,1] which actually should be [0,0][0,1] and [1,0] [1,1]. So I tried to edit that part.

**Comment by mattip** [comment]
I think the current docstring is correct. Try it out. The lambda function is called once with `i` and `j`. First return `i`, which is the first argument to the function, then `j` which is the second. Note how they correspond to the values in the docstring.
```
>>> np.fromfunction(lambda i, j: i, (2, 2), dtype=float)
array([[0., 0.],
       [1., 1.]])
>>> np.fromfunction(lambda i, j: j, (2, 2), dtype=float)
array([[0., 1.],
       [0., 1.]])

```

**Comment by soumyas567** [comment]
Yes, I am Sorry. 
"The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis. For example, if shape were (2, 2), then the parameters would be array([[0, 0], [1, 1]]) and array([[0, 1], [0, 1]])" 
This was a little confusing. Thanks for the time and sorry for the inconvenience.

**Comment by mattip** [comment]
Agreed, it is confusing. Would it help to replace the examples with the ones I showed, maybe even to vary the shape to `(2,3)`? If so would you like to change this PR to do that?

**Comment by soumyas567** [comment]
Yes, shall I add  

`np.fromfunction(lambda i, j: i, (2, 3), dtype=float)`
`np.fromfunction(lambda i, j: j, (2, 3), dtype=float)`

as the first example instead of replacing the other two? The examples already given are perfect.

**Comment by mattip** [comment]
Whatever would help you the most in understanding the function. Fresh eyes have the best perspective for what would help new users most.

**Comment by soumyas567** [comment]
I have added the same example with shape (2,2). I think that will help the reader to have a better understanding of what  is meant in the first paragraph.

**Comment by mattip** [comment]
Here is the rendered page https://23511-908607-gh.circle-artifacts.com/0/doc/build/html/reference/generated/numpy.fromfunction.html?highlight=fromfunction#numpy.fromfunction

**Comment by mattip** [comment]
Thanks @soumyas567

**Comment by bobOnGitHub** [comment]
Still not seeing this.

First, what do you mean by axis/axes ? From the [documentation](https://numpy.org/doc/stable/user/quickstart.html) ;

> ....In NumPy dimensions are called axes.
> 
> For example, the array for the coordinates of a point in 3D space, [1, 2, 1], has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.
>  
> [[1., 0., 0.],
>  [0., 1., 2.]]

**Ok, so an axis is a dimension is an axis.** 

Now, from the [fromfunction documentation](https://numpy.org/doc/stable/reference/generated/numpy.fromfunction.html) ;

> The function is called with N parameters, where N is the rank of [shape](https://numpy.org/doc/stable/reference/generated/numpy.shape.html#numpy.shape). Each parameter represents the coordinates of the array varying along a specific axis. For example, if [shape](https://numpy.org/doc/stable/reference/generated/numpy.shape.html#numpy.shape) were (2, 2), then the parameters would be array([[0, 0], [1, 1]]) and array([[0, 1], [0, 1]])

So here's how I see an array of [A,B,C,D] shaped (2,2) ;

A B
C D

and here's how I would normally assign coords to those array elements ;

(0,0) (0,1)
(1,0) (1,1)

In the documentation example C = (1,0) is never passed as part of any parameter whereas B = (0,1) is passed as both elements in the 2nd parameter.

Yes, this is what happens when you run the code so the doc matches the functionality but WHY ? It looks to me like the functionality is wrong/there is a bug and the doc just docs the behaviour of a buggy function.

What am I not seeing / getting ? How am I looking at this differently to the rest of you ?

**Pull request merged**
