### PR TITLE
MAINT: Don't internally use the one-argument where

### PR DESCRIPTION
**Pull request by eric-wieser**
nonzero is a clearer spelling

### CODE REVIEW

**Comment by juliantaylor** [comment]
I don't agree that nonzero is clearer on boolean inputs. where is also used in e.g. IDL.
where_nonzero would be better but I don't think another alias is a good idea either.

**Comment by eric-wieser** [comment]
My argument would be that `where` is ambiguous, as you have to count the number of arguments to know what it does.

On the whole, it seems pretty unpythonic to have two basically unrelated functions share the same name - the only thing in common between `where(c, x, y)` and `nonzero(c)` is that the cast their first argument to bool.

Obviously it's far too late to change our public API there, but I think we should at least discourage the use of `np.where(c)` and avoid it internally

**Comment by charris** [comment]
Yeah, `nonzero` isn't the best name and `where_nonzero` would probably be better, but it is entrenched. The dual use of `where` always seemed weird to me.

**Comment by charris** [comment]
Thanks Eric.

**Comment by eric-wieser** [comment]
Alternatively, perhaps `where(c, x, y)` has the wrong name. If we want to implement #8994 without dropping support for `where(c)`, then we need a new name for that anyway, so it can be used by `__array_ufunc__` (although I guess `np.where.ufunc` could be that name)

**Pull request merged**
