### PR TITLE
CI: Add editable install tests

### LINKED ISSUE #26337: Change one CI job to use an editable install
This is a follow-up to gh-26325, which fixed the test suite so it passes (at least on a regular Linux `numpy-dev` env) with an editable install:
```
$ pip install -e . --no-build-isolation
$ pytest numpy
```

This is not tested at all in CI at the moment, so it's fairly easily broken again. We should pick a suitable existing job and change it to use an editable install rather than `spin` or a regular install via a wheel. In case there's no suitable job, we can add a new one - but that's probably not necessary. Just need a generic Linux one for which compile tests (which don't work with editable installs) aren't important.

### PR DESCRIPTION
**Pull request by luxedo**
Closes #26337 (Or at least try... Pipelines are a pain to test.) by adding a new job `test-editable`.

I did not identify any other job that could be made with an editable install. If there's one please let me know so I can tweak that one instead of adding a new one.

### CODE REVIEW

**Comment by luxedo** [comment]
Surprisingly it passed first time

```
...
numpy/typing/tests/test_isfile.py .                                      [ 99%]
numpy/typing/tests/test_runtime.py .....................x...             [ 99%]
numpy/typing/tests/test_typing.py ssssssssssssssssssssssssssssssssssssss [ 99%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 99%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssss                  [100%]

==== 49013 passed, 1920 skipped, 33 xfailed, 5 xpassed in 296.79s (0:04:56) ====
```

**Comment by mattip** [comment]
I think the approach in #26655 is preferable, it does not add another CI job.

**Comment by luxedo** [comment]
I updated the PR by replacing the old `linux.full` to `linux.test-editable`. The main differences are:

* `test-editable` does not install `gfortran`
* `test-editable` does not build python wheel
* `test-editable` does not generate coverage data

If those features are desired I close this one PR and give a hand to https://github.com/numpy/numpy/pull/26655

**Comment by mattip** [comment]
Closing since #26655 was merged. Thanks @luxedo

**Pull request closed without merging**
