### PR TITLE
Change mkl_info.dir_env_var from MKL to MKLROOT

### PR DESCRIPTION
**Pull request by mingwandroid**
Reference: https://software.intel.com/en-us/node/528500

### CODE REVIEW

**Comment by charris** [comment]
Is this new and `MKL` was once valid, or has it always been `MKLROOT`?

**Comment by mingwandroid** [comment]
I don't know how to determine that as I can only find the latest documentation on the website.

**Comment by mingwandroid** [comment]
Actually, I found a reference for `MKLROOT` dating back to 2012:

https://software.intel.com/en-us/articles/intel-mkl-103-getting-started

**Comment by charris** [comment]
Looks like MKL 10.0 came out in 2008 and your reference is 10.3, so we are probably good. Thanks @mingwandroid .

**Comment by rgommers** [comment]
Does this actually make a difference? The ``mkl_info`` class already has a method ``get_mkl_rootdir`` that should look for ``MKLROOT`` and add it to the library and include paths.

**Comment by mingwandroid** [comment]
It does make a difference. The values from `get_mkl_root` get written into site.cfg (AFAIR, I am not at my computer to check this filename) only.

The case that failed for me was building `scipy` using a `numpy` built on a different system so site.cfg contained paths that don't exist.

**Comment by rgommers** [comment]
``site.cfg`` doesn't get written, but ``__config__.py`` does get written and installed. 

Scipy should not be using the paths in that file though. I can see how something would go wrong if ``get_info`` was imported from ``numpy.distutils`` instead of ``numpy.distutils.system_info``  - then you'd get the numpy build-time paths.

I have no problem with this PR, but it sounds like there's something else that needs fixing. The paths in ``__config__.py`` should never be reused for building another package.

**Pull request merged**
