### PR TITLE
DOC: Merge together DISTUTILS.rst.txt#template-files" and distutils.r…

### LINKED ISSUE #13129: DOC: Merge together DISTUTILS.rst.txt#template-files" and distutils.rst#conversion-of-src-files
A follow-up to #11689.

These two sections describe the same distutils feature, but in different ways. It would be good to unify them.

### PR DESCRIPTION
**Pull request by mattip**
Closes #13129, replaces #13211, #13175

Starting from @aashuli 's work on #13175, I removed the extraneous commits from a bad rebase, rebased off master and squashed the changes to one commit

It is a bit hard to see the changes in source, let's see how it renders after a CI build

### CODE REVIEW

**Comment by mattip** [comment]
The merged documentation can be seen [here](https://7618-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/reference/distutils_guide.html?highlight=templating#other-files), the [higher level description of distutils](https://7618-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/reference/distutils.html#conversion-of-src-files) now reference the merged docs.

**Comment by mattip** [comment]
> I think you need deepcopy above

Good catch. Fixed.

**Review by seberg — APPROVED** [review]
Seems good to me, should those imports be there or at the top of the file?

**Comment by mattip** [comment]
The file is kind of large, maybe it should be broken into functional units. So this is kind of a compromise, but I am happy to move them to the top if it disturbs someone.

**Comment by seberg** [comment]
OK, let me put it in, the file is indeed very large. If someone wants it to be cleaned up, just note it. Thanks Matti.

**Pull request merged**
