### PR TITLE
Revert "BUG: Update coordinates in PyArray_ITER_GOTO1D"

### PR DESCRIPTION
**Pull request by rgommers**
Reverts numpy/numpy#18987

### CODE REVIEW

**Comment by seberg** [comment]
OK, lets just put this in. @charris do we have to do something to get the dev wheels uploaded before tomorrow after this?

**Comment by seberg** [comment]
Thanks Ralf!

**Comment by charris** [comment]
@seberg Just need to push an empty commit upstream to the numpy-wheels main branch. I'll do that.

**Comment by rgommers** [comment]
> @charris do we have to do something to get the dev wheels uploaded before tomorrow after this?

No need. Now I understand the question. The failing CI job was for Python 3.10-dev, there's no NumPy wheels - it was a source build in CI.

**Pull request merged**
