### PR TITLE
DOC: Add description to linear algebra section

### LINKED ISSUE #15204: DOC: linear algebra section of quickstart tutorial is incomplete
The [Quickstart Tutorial](https://numpy.org/devdocs/user/quickstart.html) through version 1.19.dev0 contains an incomplete section on linear algebra near the end of the page.

The section starts off with the statement: "Work in progress. Basic linear algebra to be included here." which seems like it is a reminder for developers rather than user-facing documentation. 

I searched through the issues and didn't see this raised anywhere; I wanted to make sure it was raised so that it doesn't fall through the cracks.

### PR DESCRIPTION
**Pull request by devangmukherjee**
added description to linear algebra section and gave a description of all the functions used in the code below it.
fixes #15204

### CODE REVIEW

**Comment by rgommers** [comment]
Not sure if the right approach here is to add a few lines, or to remove it and just reference the new tutorial in gh-15295. @melissawm what would you prefer?

**Comment by rgommers** [comment]
Thanks for tackling this one @devangmukherjee

**Comment by devangmukherjee** [comment]
I gave a description of all linear functions used just below this paragraph. Should I add something else as well?

**Comment by rossbar** [comment]
To me, the inclusion of the **Linear Algebra** section as-is in the Quickstart Tutorial is an awkward fit, especially since none of the other packages (`np.random`, `np.fft`, `np.polynomial`) are given the same consideration.

I tend to agree with @rgommers  here. +1 for linking to the more detailed `linalg` tutorial in #15295 

I originally opened #15204 so that the incomplete section wouldn't fall through the cracks, but it seems like the Quickstart tutorial might be due for a larger restructuring, so perhaps it should be closed to mitigate premature attention

All that being said, thanks @devangmukherjee for taking a crack at this! Your changes do a good job of reflecting the `linalg` components highlighted in the subsequent example.

**Comment by melissawm** [comment]
My (probably biased) opinion is that linear algebra specifically could be a separate tutorial (#15295 is just about SVD - we might do a more comprehensive tutorial if necessary). Otherwise we might risk overwhelming the absolute beginner (they should not be required to know linear algebra to use NumPy)

**Comment by charris** [comment]
What is the decision here?

I think a basic tutorial should use a lot of illustrations showing what happens to a matrix and also indicate how the indices (slices) relate to rows and columns. There are probably materials for that already available in various places. Some of the diagrams in the submitted Nature paper could also be repurposed.

**Comment by rossbar** [comment]
Thanks for your interest in the topic @devangmukherjee. There is a consensus that the `linalg` section of the tutorial needs a significant overhaul, so the PR will need to be closed for now. Thanks again for taking a stab at it!

**Pull request closed without merging**
