### PR TITLE
BLD: update to OpenBLAS 0.3.27

### LINKED ISSUE #26240: BUG: consider shipping numpy 2 final (or rc2) with OpenBLAS 0.3.27
NumPy 2.0.0rc1 currently ships OpenBLAS 0.3.26 that has a thread-safety bug on Windows:

- https://github.com/OpenMathLib/OpenBLAS/issues/4582

This was fixed in OpenBLAS 0.3.27 but is not yet packaged on pypi.org:

- https://pypi.org/project/scipy-openblas64/

This bug is causing the scikit-learn release CI to freeze when testing against numpy 2.0.0rc1.

### PR DESCRIPTION
**Pull request by mattip**
Fixes #26240 by building with scipy_openblas wheels containing OpenBLAS 0.3.27

### CODE REVIEW

**Comment by mattip** [comment]
sdist test broke:
```
ImportError: libscipy_openblas64_64_.so: cannot open shared object file: \
   No such file or directory
```

**Comment by mattip** [comment]
The newer `libscipy_openblas64_.so` has
```
SONAME               libscipy_openblas64_64_.so
```

I will fix that in the upstream repo and revisit this PR

**Comment by mattip** [comment]
Ci is passing.

**Comment by charris** [comment]
Thanks Matti

**Pull request merged**
