### PR TITLE
DOC: Add Examples for np.ma.right_shift

### LINKED ISSUE #22269: DOC: `np.ma` - list of functions that are missing examples – tracking issue
Find below the functions from `np.ma` that are missing examples in the docstrings. If you have a suggestion for an example, please submit a pull request.
To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)

- [x]     compress_cols
- [ ]     compress_nd
- [x]     compress_rows
- [ ]     compressed
- [ ]     convolve
- [ ]     correlate
- [ ]     cov
- [ ]     diag
- [ ]     ediff1d
- [ ]     in1d
- [ ]     isin
- [ ]     left_shift
- [x]     max
- [x]     min
- [x]     power
- [ ]     put
- [ ]     putmask
- [ ]     reshape
- [ ]     right_shift
- [x]     round
- [x]     round_
- [ ]     setxor1d
- [ ]     sort
- [ ]     take
- [x]     union1d
- [x]     unique

**IMPORTANT:** Don't close this issue or remove the *"sprintable"* label until all the PRs with examples are merged.

### PR DESCRIPTION
**Pull request by soma2000-lang**
Partially resolves https://github.com/numpy/numpy/issues/22269
@Mukulikaa @rossbar

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @soma2000-lang! One small request: if you plan to work on more docstrings, could you please bunch the updates in one PR (at least for a set of related docstrings)? There's a lot of unnecessary CI overhead if you open one PR per example.

**Comment by soma2000-lang** [comment]
@rgommers  sure if I add kore doctrines I will be adding it in this pr only

**Comment by charris** [comment]
You need to be more precise.
```
File "build/testenv/lib/python3.9/site-packages/numpy/ma/core.py", line 7188, in right_shift
Failed example:
    masked_x
Expected:
    ma.right_shifmasked_array(data=[11, 3, 8, --],
             mask=[False, False, False,  True],
       fill_value=999999)
Got:
    masked_array(data=[11, 3, 8, --],
                 mask=[False, False, False,  True],
           fill_value=999999)


File "build/testenv/lib/python3.9/site-packages/numpy/ma/core.py", line 7192, in right_shift
Failed example:
    ma.right_shift(masked_x,1)
Expected:
    masked_array(data=[5, 1, 4, --],
                mask=[False, False, False,  True],
        fill_value=999999)t(masked_x)
Got:
    masked_array(data=[5, 1, 4, --],
                 mask=[False, False, False,  True],
           fill_value=999999)
```

**Review by rossbar — COMMENTED** [review]
I took the liberty of pushing up the final touchups to get this over the line. Thanks @soma2000-lang

**Pull request merged**
