### PR TITLE
NEP: array API standard adoption (NEP 47)

### PR DESCRIPTION
**Pull request by rgommers**
This NEP proposes adoption the array API standard (https://data-apis.github.io/array-api/latest/) in NumPy.
This will add a new `numpy.array_api` submodule containing that standardized API.

The main purpose of this API is to be able to write code that is portable to other array/tensor libraries like CuPy, PyTorch, JAX, TensorFlow, Dask, and MXNet.

We expect this NEP to remain in draft state for quite a while, while we're gaining experience with using it in downstream libraries, discuss adding it to other array libraries, and finishing some of the loose ends (e.g., specifications for linear algebra functions that aren't merged yet, see https://github.com/data-apis/array-api/pulls) in the API standard itself.

See https://mail.python.org/pipermail/numpy-discussion/2020-November/081181.html for an initial discussion about this topic.

_To see a rendered version of this NEP, use "build - Details" in the CI status of this PR:_
image
_then browse to the "Artifacts" tab and search for "nep-0047" and click on the file link_

### CODE REVIEW

**Comment by shoyer** [comment]
I'm struggling to find a link to the rendered doc. The link "NumPy Enhancement Proposals" in the generated doc page from circleci points straight to https://numpy.org/neps/, which doesn't show NEP 47 yet.

**Comment by rgommers** [comment]
Ah, forgot about the neps folder having a separate Makefile and build step, which messes up the linking. I'll update the instructions, here is a direct link: https://18468-908607-gh.circle-artifacts.com/0/doc/neps/_build/html/nep-0047-array-api-standard.html

**Comment by charris** [comment]
Should we go ahead in put this in? That will make it easy to find for future discussion.

**Comment by shoyer** [comment]
+1, I think we should go ahead and merge this so it's easier to find/view
rendered docs. We haven't had any inline comments yet (and those can be
made after merging anyways).

**Comment by rgommers** [comment]
Sounds good to me, thanks Chuck

**Comment by charris** [comment]
Thanks Ralf.

**Comment by leofang** [comment]
Wow this is quick! Thanks all!

**Comment by shoyer** [comment]
To be clear, merging does not mean acceptance -- this is just a "draft" NEP
:)

**Comment by jakirkham** [comment]
Where should we look for the rendered version? Looking here ( https://numpy.org/neps/ ), but am not sure if the docs are still building or if I'm looking in the wrong place 😅

**Comment by seberg** [comment]
Its already there: https://numpy.org/neps/nep-0047-array-api-standard.html

**Comment by jakirkham** [comment]
Thanks Sebastian! 😄 Must have overlooked it

**Pull request merged**
