### PR TITLE
ENH: Allow object and subarray dtypes in fromiter

### LINKED ISSUE #4791: Let `fromiter` handle object arrays
In 2006, Tim Hochberg questioned the reason [why fromiter does not handle object arrays](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/ctors.c#L3580-3588):

```
            /* We would need to alter the memory RENEW code to decrement any
               reference counts before just throwing away the memory.
             */

This doesn't seem right. The array that we would be RENEWing is a bunch 
of PyObject*s. The reference counts don't reside there, but in the 
objects themselves. When we do the RENEW, we don't want the reference 
counts to change at all. The one tricky case is if we run out of memory, 
I'm not certain that the current setup correctly deals with reference 
counts in this case, although it appears likely that it should work 
since ret->data should still point to a valid chunk of memory and 
decreffing ret should result in the subsequent deallocation of all the 
stored objects.
```

http://mail.scipy.org/pipermail/numpy-discussion/2006-November/024747.html

@teoliphant responded

```
I'm not sure if you are still thinking about this.  I suspect I added 
the comment because I was concerned about two things:

1) a resize that deletes memory without first decrefing object counts 
--- I suspose this can't happen here, though, because RENEW is always 
"growing" memory, right?

2) a resize that grows memory without inserting NULLS.  For Object array 
manipulation to work, you need initialized (to NULL) "empty" memory. 

>The one tricky case is if we run out of memory, 
>I'm not certain that the current setup correctly deals with reference 
>counts in this case, although it appears likely that it should work 
>since ret->data should still point to a valid chunk of memory and 
>decreffing ret should result in the subsequent deallocation of all the 
>  
>
>stored objects.
>  
>
As long as you don't store the pointer to new memory until after the 
RENEW was successful then this should work.

I think my comment came from the possibility of #1 in general use of 
RENEW, but I don't think that is going to happen.  Therefore, the only 
tweak that seams necessary is to initialize any new memory to NULL for 
OBJECT arrays.
```

http://mail.scipy.org/pipermail/numpy-discussion/2006-November/024841.html

I couldn't find any further discussion of this issue since 2006. Is this analysis of what needs to be done to `PyArray_FromIter` still sound?

### LINKED ISSUE #15789: np.fromiter crashes if NPY_RELAXED_STRIDES_DEBUG is set
If numpy is built with `NPY_RELAXED_STRIDES_DEBUG == 1`, then fromiter uses the invalid strides.

```python
import numpy as np

NPY_RELAXED_STRIDES_DEBUG = np.ones(1, np.uint8).strides[0] != 1
assert NPY_RELAXED_STRIDES_DEBUG 

class MyIter:
    def __length_hint__(self):
        # only required to be an estimate, this is legal
        return 1  
    def __iter__(self):
        return iter([1, 2, 3])

x = np.fromiter(MyIter(), int)
# segfault
```

Tested on an approximation of master.

### PR DESCRIPTION
**Pull request by seberg**
Allows dtypes with objects (and subarray) in fromiter.  There was
never really a good reason for rejecting them.

Otherwise does some maintanence (e.g. the array is contiguous, so
no need to do complicated index calculations), improve the error
message, and add tests for those things.

Closes gh-4791, gh-15789

### CODE REVIEW

**Comment by BvB93** [comment]
Oooh neat, does the mean it's now also possible to create >1D arrays with the likes of, _e.g._, `dtype=("f8", (10,))`?

Also, this feels worthy of a release note in my opinion.

**Comment by seberg** [comment]
> Oooh neat, does the mean it's now also possible to create >1D arrays with the likes of, e.g., dtype=("f8", (10,))?

If you must, yes... but it does that via the subarray dtype, so it might be subtly different from what you expect.

**Comment by seberg** [comment]
Added something, unfortunately, also triggered an unrelated bug on the way. (the example works, the bug is in some error path)

**Comment by seberg** [comment]
No, I think review just stalled and should be good.  We probably have to apply your stride fix here as well (probably just meaning to remove/modify `RELAXED_STRIDES_DEBUG` ifdef part).

**Comment by mattip** [comment]
Let's merge this then I will rebase #21477 on top

**Comment by seberg** [comment]
Thanks!

**Pull request merged**
