### PR TITLE
STY: Refactoring npymath

### PR DESCRIPTION
**Pull request by Djacon**
Npymath contains code that doesn't have a common style. 

The main changes are:
> Added or moved curly braces in if-else statement
> Removed extra spaces
> Added spaces in math expressions

### CODE REVIEW

**Comment by Djacon** [comment]
Hi everyone. This is my first PR to this repository. 

Honestly, I can't find a problem in my code that causes an error in the first cygwin_build_test:
`` ValueError: In "numpy/core/src/npymath/npy_math_internal.h.src" loop at line 1: no definition of key "kind" ``

**Comment by mattip** [comment]
We are not big on reformatting PRs. They tend to clog up CI, produce spurious failures, and confuse history when looking through `git blame`. In particular, condensing the `else` formatting here goes against our [c style guide](https://numpy.org/neps/nep-0045-c_style_guide.html#code-layout).

**Comment by Djacon** [comment]
Okay, thanks for the reply

**Comment by mattip** [comment]
Please don't give up, there are lots of other places that could use some help. What in particular interests you? [The tracking issue](https://github.com/numpy/numpy/issues/13114) about bad reference links in the documentation is one such place, there are more.

**Pull request closed without merging**
