### PR TITLE
API: Update `lib.function_base` namespace

### PR DESCRIPTION
**Pull request by mtsokol**
Relevant issue https://github.com/numpy/numpy/issues/24507

Hi @rgommers @ngoldbaum,

This PR moves `lib.function_base` module to a private file and ensures that its public methods are only available through the main namespace. There are no additional functions available from a local namespace.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM, and I verified that this doesn't change anything in `np.__all__` (`'disp'` was already not in it). So in it goes, thanks @mtsokol.

**Comment by WarrenWeckesser** [comment]
It looks like this removed `add_newdoc` from `numpy.lib`.  This appears to be the change that is breaking the SciPy builds with the numpy main dev branch (see the CI results for any recent pull request).  Back in https://github.com/numpy/numpy/issues/12385#issuecomment-509709380, it was stated that `add_newdoc` would remain public.  Has that decision changed?  Should we fix the SciPy build by replacing `numpy.lib.add_newdoc` with our own copy?

**Comment by mtsokol** [comment]
> It looks like this removed `add_newdoc` from `numpy.lib`. This appears to be the change that is breaking the SciPy builds with the numpy main dev branch (see the CI results for any recent pull request). Back in [#12385 (comment)](https://github.com/numpy/numpy/issues/12385#issuecomment-509709380), it was stated that `add_newdoc` would remain public. Has that decision changed? Should we fix the SciPy build by replacing `numpy.lib.add_newdoc` with our own copy?

@WarrenWeckesser, that's correct `add_newdoc` and `add_docstring` needs to stay in `numpy.lib` - let me revert that one-line change quickly.

**Comment by rgommers** [comment]
Ah, this was not an intentional change in this PR. Let's put it back right now and build new nightlies to unbreak SciPy. @mtsokol can you open a new PR for this?

Let's add `add_newdoc` to the list of functions in the `numpy.lib` namespace in gh-24507 and make an explicit decision there. In case it gets removed, SciPy and other main downstream libraries should be fixed up first.

**Comment by rgommers** [comment]
Synchronous comments, glad they match:)

**Comment by mtsokol** [comment]
I created a PR https://github.com/numpy/numpy/pull/24564 that fixes it and readds `add_newdoc` and `add_docstring` to `np.lib` only to align with main namespace and `lib` namespace design.

**Comment by rgommers** [comment]
Fix merged and new nightly wheel builds triggered - they should be available in ~30 minutes or so.

**Pull request merged**
