### PR TITLE
BLD: Make ConfigParser evaluate environment variables in site.cfg

### PR DESCRIPTION
**Pull request by juru1234**
In order to allow easy compilation with multiple different compilers installed, allow site.cfg to evaluate environment variables. This should work with Unix and Windows, but has been tested on Linux, only.

### CODE REVIEW

**Comment by stefanv** [comment]
@julianruess How does this handle conflicts in variable names between sections?

**Comment by rgommers** [comment]
@julianruess can you please also give a description of how to test this? Ideally it would have a unit test, but at a minimum I'd like to be able to test this manually.

**Comment by julianruess** [comment]
Sorry for the late response: 

Rename site.cfg.example to site.cfg and add the following content to the file:

[mkl]
library_dirs = ${INTEL_HOME}/mkl/lib/intel64
include_dirs = ${INTEL_HOME}/mkl/include
mkl_libs = mkl_rt
lapack_libs =

Now build numpy with gcc (python setup.py install). The compiler will complain that it isn't able to evaluate the environment variable $INTEL_HOME.

"Bad value substitution: option 'library_dirs' in section 'mkl' contains an interpolation key 'INTEL_HOME' which is not a valid option name. Raw value: '${INTEL_HOME}/mkl/lib/intel64'"

When manually adding a path to $INTEL_HOME (e.g. export INTEL_HOME=~/test), the compiler will perceed. This is a proof that environment variables in site.cfg get parsed with this patch.

**Comment by charris** [comment]
Ping to the reviewers, who I expect are all traveling :)

**Comment by mattip** [comment]
@julianruess while in the general case it is hard to test distutils, I think this would be easy enough to add basic tests to `numpy/distutils/tests/test_system_info.py` so we can make sure this works on all platforms and will not break in the future.

**Comment by mattip** [comment]
You can then run them with `python3 runtests.py -t numpy/distutils/tests/test_system_info.py`

**Comment by charris** [comment]
I would kinda like to see this in 1.8, but haven't seen a signoff from @rgommers and other reviewers, so pushing off to 1.19.

**Comment by charris** [comment]
@mattip @rgommers let's bring this to a close.

**Comment by mattip** [comment]
This is still lacking a test.

**Comment by mattip** [comment]
Should we close this? I am not sure the added level of indirection is worth the trouble: it is as easy to generate a new site.cfg as to set environment variables.

**Comment by mattip** [comment]
I am going to close this. Please reopen or open a new PR if there still is a desire to add this.

**Pull request closed without merging**
