### PR TITLE
DOC: Make reference doc nditer examples python3 friendly

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by charris** [comment]
I think we will put off  worrying about moving the examples to Python3 until after we drop 2.7 support, as there are a *lot* of examples and we should try to get many of them at once. Also, these fixes are not quite correct, `print x,` omits the linefeed so that everything prints on one line, `print(x)` doesn't do that.

**Comment by charris** [comment]
I raised the topic of updating the examples to Python 3 on the numpy mailing list.

**Comment by hmaarrfk** [comment]
@charris thanks. Yeah, I noticed many of the examples were just python3 safe. I guess waiting until 2019 isn't too long to go, but it would be nice to have the "compatible" versions sooner if they don't add unnecessary noise.

Thanks for considering!

**Comment by charris** [comment]
@hmaarrfk The consensus on the list is that we should start converting to Python 3 examples soonest, so you should reopen this and fix up the fixes.

**Comment by eric-wieser** [comment]
More intrusive, but now you're using `end`, I'd be inclined to use something that produces more readable output like `end="; "`

**Comment by hmaarrfk** [comment]
Numpy doesn't add the commas when it prints statements though:

```python
In [1]: import numpy as np
In [2]: a = np.arange(5)
In [3]: print(a)
[0 1 2 3 4]
In [4]: np.__version__
Out[4]: '1.14.3'
```

is there a particular statement you would like to add the `;` to?

**Comment by charris** [comment]
Thanks @hmaarrfk .

**Pull request merged**
