### PR TITLE
ENH: Use f90 compiler specified in f2py command line args for pgi compiler

### LINKED ISSUE #16481: f2py undefined symbol with PGI fortran compiler and MPI calls
I am trying to wrap fortran code with f2py. The fortran code includes some MPI calls and is compiled with the PGI compiler.
When importing the wrapped module in python I get this error: `undefined symbol: mpi_comm_rank_`

### Reproducing code example:

```
1 ! file: helloworld.f90
2 subroutine sayhello(comm)
3   use mpi
4   implicit none
5   integer :: comm, rank, size, ierr
6   call MPI_Comm_size(comm, size, ierr)
7   call MPI_Comm_rank(comm, rank, ierr)
8   print *, 'Hello, World! I am process ',rank,' of ',size,'.'
9 end subroutine sayhello
```
### Compilation
`CC=gcc f2py --verbose --f90exec=mpif90 --fcompiler=pg -c helloworld.f90 -m helloworld`

### Partial output
```
[...]
<class 'numpy.distutils.fcompiler.pg.PGroupFCompiler'>
version_cmd     = ['***/pgi/linuxpower/19.9/bin/pgfortran', '-V']
compiler_f77    = ['***/pgi/linuxpower/19.9/bin/pgfortran', '-fpic', '-Minform=inform', '-Mnosecond_underscore', '-fast']
compiler_fix    = ['***/spectrum_mpi/10.03.00.01rtm3-rh7_20190611/bin/mpif90', '-Mfixed', '-fpic', '-Minform=inform', '-Mnosecond_underscore', '-fast']
compiler_f90    = ['***/spectrum_mpi/10.03.00.01rtm3-rh7_20190611/bin/mpif90', '-fpic', '-Minform=inform', '-Mnosecond_underscore', '-fast']
linker_so       = ['***/pgi/linuxpower/19.9/bin/pgfortran', '-shared', '-fpic']
archiver        = None
ranlib          = None
linker_exe      = None
version         = LooseVersion ('19.9-0')
libraries       = []
library_dirs    = []
object_switch   = '-o '
compile_switch  = '-c'
include_dirs    = ['***/python_venv/python_numpy_pgi_reproducer/include', '***/anaconda3/2019.03/include/python3.7m']
[...]
***/pgi/linuxpower/19.9/bin/pgfortran -shared -fpic /tmp/tmpfy731xy8/tmp/tmpfy731xy8/src.linux-ppc64le-3.7/helloworldmodule.o /tmp/tmpfy731xy8/tmp/tmpfy731xy8/src.linux-ppc64le-3.7/fortranobject.o /tmp/tmpfy731xy8/helloworld.o -o ./helloworld.cpython-37m-powerpc64le-linux-gnu.so
Removing build directory /tmp/tmpfy731xy8
```
The "linker_so" executable is chosen to be the pgfortran executable, whereas I would like to use the mpif90 executable instead.
This leads to the following error when importing the wrapped module from python:

```
$ python -c "import helloworld"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: ***/helloworld.cpython-37m-powerpc64le-linux-gnu.so: undefined symbol: mpi_comm_rank_
```

### System informations

```
$ mpif90 --version
pgf90 19.9-0 linuxpower target on Linuxpower
```

```
$ python --version
Python 3.7.3
```
```
$ python -c "import sys, numpy; print(numpy.__version__, sys.version)"
1.18.4 3.7.3 (default, Mar 27 2019, 22:31:02)
[GCC 7.3.0]
```
### Workarround
This solves the problem in my case:
In file numpy/distutils/fcompiler/pg.py - line 36 (numpy installed version)
```
-'linker_so': ["pgfortran"],
+'linker_so': ["<F90>"],
```
The executable supplied with the `--f90exec` option is then the one picked to be the linker executable and the ImportError does not occur.

### PR DESCRIPTION
**Pull request by danbeibei**
Closes #16481

### CODE REVIEW

**Comment by eric-wieser** [comment]
Won't this do the wrong thing when an f77 compiler is requested?

**Comment by danbeibei** [comment]
It calls the pgf90 executable rather than the pgfortran executable.
Those are actually the same compiler according to the PGI Fortran Reference Guide (https://www.pgroup.com/resources/docs/20.4/openpower/fortran-ref-guide/index.htm): 
> pgf90, pgf95, and pgfortran are the same compiler that has evolved from Fortran 90 to Fortran 2003 standards. The older names are supported so that makefiles that were written using pgf90/pgf95, will still work. All three names refer to the same one compiler that supports the Fortran 2003 language standard.

**Comment by eric-wieser** [comment]
What about old compiler versions which do not have an f90 compiler at all? Maybe we already do not support those.

**Comment by danbeibei** [comment]
It won't neither have the pgfortran executable as this one is newer than the pgf90 executable.
IMO the question should be raised the other way around: what about newer code, fortran 95 code or fortran 2003 code for instance ? It would be compiled with the pgf90 executable instead of the pgfortran executable. It would work because those are the same, but it's confusing.

Nevertheless, the command line utility lets the user dial in his compiler command of choice, I feel like the system should use the specified command for linking as well. This is were I might be mistaking.

**Comment by charris** [comment]
@eric-wieser Are you OK with this?

**Comment by charris** [comment]
@eric-wieser Ping.

**Comment by charris** [comment]
I'd like to put this. If there are problems we can address them when they arise. @danbeibei Could you make a release note in `doc/release/upcoming_changes`, look at the other entries and the README to see how it is done. Also, what happens if the `--f90exec` is not part of the command?

**Comment by danbeibei** [comment]
OK, I added a release note.

If the `--f90exec` option is not provided the pgf90 executable is used instead of the pgfortran one.

**Comment by eric-wieser** [comment]
@charris: I don't know nearly enough about building fortran to have an opinion here, my question above was to prompt opinions from people who might.

**Comment by charris** [comment]
@eric-wieser Neither do I :) In these cases we need to depend on people  who actually use the relevant compiler for fixes that make thing work for them.

**Pull request merged**
