### PR TITLE
DOC: run towncrier to consolidate the 2.0.0 release notes to data

### PR DESCRIPTION
**Pull request by rgommers**
The first commit is purely running `towncrier`, no manual changes. The second commit fixes all doc build warnings I see locally.

Actually editing the 2.0.0 release notes will be a follow-up PR.

### CODE REVIEW

**Comment by charris** [comment]
Thanks Ralf.

**Comment by seberg** [comment]
I think this lost the ones that were inlcuded by the previous generation in https://github.com/numpy/numpy/pull/24510?  There some smaller fixups on that, but not sure they are relevant, maybe it is easier to just pull in all those fragments again.

**Comment by rgommers** [comment]
Oh great, a tool that silently deletes content. And doesn't even have an option for merging as far as I can tell from https://towncrier.readthedocs.io/en/stable/cli.html#towncrier-build. I only checked one of the first deleted lines in the diff and saw it was moved, so I thought it was a diff display thing and didn't check the whole thing.

I'll fix this up manually, but it looks to me like it makes the tool pretty much useless then.

**Comment by mattip** [comment]
I think you can get a bit of a work-around by adding a line to the generated file to tell towncrier [not to remove the current content](https://towncrier.readthedocs.io/en/stable/customization/newsfile.html#adding-content-above-towncrier). There will still be two heading lines, but they can be deleted in the inevitable cleanup.

**Comment by seberg** [comment]
Just doing a merge or copying things manually is probably just as well.  The point is, towncrier is meant to be run exactly once.
It is running in our `devdocs` build so we always have a nice rendered version online.  The only small wrinkle is that the local docs build shouldn't mutate the repo, so it doesn't run towncrier:  Could be done I am sure.  Nobody ever asked for it.

**Comment by rgommers** [comment]
gh-25832 should restore the missing content.

> I think you can get a bit of a work-around by adding a line to the generated file

Ah good find, that seems needed. I'll see about adding that in the next PR.

> The point is, towncrier is meant to be run exactly once. [...] The only small wrinkle is that the local docs build shouldn't mutate the repo, so it doesn't run towncrier

Let's fix that; this isn't a reasonable restriction and not having a local build seems bad (we'd never accept that for code, so I don't think we should for docs either). I'll see if it's easy to do.

**Pull request merged**
