### PR TITLE
Continuation of PR #16245, Model tutorial format based on tutorial-svd

### PR DESCRIPTION
**Pull request by bjnath**
Resolves most of gh-16245

    Also addresses https://github.com/numpy/numpy/pull/16245#discussion_r430454958
    about the sentence in question, but leaves  "Do" in the title.

    Still awaiting resolution:

        https://github.com/numpy/numpy/pull/16245#discussion_r429025078
        https://github.com/numpy/numpy/pull/16245#discussion_r429029258

### CODE REVIEW

**Comment by bjnath** [comment]
@stefanv in https://github.com/numpy/numpy/pull/16245#discussion_r430454958:

> I'd find it equally odd if you wrote "I'm about to perform calculus" and then proceeded to call np.diff. Just like you wouldn't typically say "I'm about to perform electrical engineering", or "I'm about to do some food science".
> 
> Linear algebra is a whole branch of mathematics: "one does not simply" apply it wholesale.
>

**Comment by bjnath** [comment]
I've changed the sentence but left a bare 'Do' in the title. Putting "operations" in the title so it becomes "Do linear algebra operations" sounds forced.

There's no obvious way to decide cases where most people don't hear a problem but a few do. 
Here everyone compromises: The hoi polloi yield on the sentence and the flamekeepers yield on the title.

**Comment by charris** [comment]
Needs rebase.

**Comment by melissawm** [comment]
@bjnath, are you willing to finish working on this? Would you mind if we rebased and merged as-is? Any leftover ideas can be done in a follow-up if needed. Thanks!

**Comment by melissawm** [comment]
I am closing this as most of the changes suggested have been superseded by #18758, #16385 and in the [numpy-tutorials](https://numpy.org/numpy-tutorials). Thanks @bjnath !

**Pull request closed without merging**
