### PR TITLE
add modifications to handle gfortran on msvc

### PR DESCRIPTION
**Pull request by ghost**
This is currently wip (it fully works but needs to handle non msvc+gfortran). Feedback would be greatly appreciated to understand whether this is the correct approach.

### CODE REVIEW

**Comment by rgommers** [comment]
Not sure if you still want feedback given that you closed the PR, but: if it takes listing scipy submodules explicitly then that's a lot better than nothing, but it's then not a generic solution for "Fortran + Python on Windows". I haven't been following in enough detail, but how sure are you that this is necessary?

**Comment by pv** [comment]
As for the library order: the easiest solution could be to specify it 
manually in setup.py. Does numpy.distutils preserve the library order 
given by the setup.py scripts? If not, it could be made to do that, and 
we could fix the library order on Scipy side.

**Comment by rgommers** [comment]
> Does numpy.distutils preserve the library order given by the setup.py scripts? 

It doesn't, and making it do so will be useful in other contexts as well. E.g. I just tried to move ``ndimage`` forward for a debugging exercise to not have to wait on ``sparsetools`` compiling, but couldn't get that to work via setup.py listings.

**Comment by xoviat** [comment]
> Not sure if you still want feedback given that you closed the PR

I inadvertently deleted the branch and github closed the PR. 

@rgommers The other issue that I am unsure how to address is how to gracefully handle DLL dependencies . Do you have any ideas on this?

**Comment by xoviat** [comment]
new pr: #9431 (gh wouldn't let me reopen this)

**Pull request closed without merging**
