### PR TITLE
Update mtrand.pyx

### PR DESCRIPTION
**Pull request by fplandes**
Docstring of "pareto" lightly changed, according to the discussion :
https://github.com/numpy/numpy/issues/4181#issuecomment-68915452

### CODE REVIEW

**Comment by rgommers** [comment]
@fplandes thanks for making this PR. Fix looks OK, I'll push it with a few minor PEP8 fixes included.

**Comment by rgommers** [comment]
Actually it doesn't address all comments on gh-4181. I'll comment there.

**Comment by charris** [comment]
@rgommers Be nice to get this finished up.

**Comment by rgommers** [comment]
Submitted my proposed more complete fix as gh-5459. @fplandes would be useful if you could comment there or on gh-4181.

**Pull request closed without merging**
