### PR TITLE
API: Add missing deprecation and release note files

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @ngoldbaum @charris,

Here's a PR with a small batch of changes:
- Proper error message for `np.dtype("a")` (for bytesized alias a warning is raised additionally)
- Restoring of `np.dtype(unicode)`
- Missing release note files from previous PRs
- Delete `np.sctypeDict` removal from the changelog

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I think there's enough downstream usage showing up in issues that we should probably merely deprecate `"a"` and `"aN"`. There isn't much burden for keeping it besides user confusion, but deprecating it fixes that without introducing exceptions in previously working code. I suggested removing it initially because I thought there was basically zero usage.

Is that ok?

**Comment by mtsokol** [comment]
Ah, sure! I will restore them (with deprecation).

**Comment by mtsokol** [comment]
Now it should be available again, with a deprecation on access (for `np.dtype("a")` and `np.dtype("aN")`).

**Comment by ngoldbaum** [comment]
Needs a test in `numpy/core/tests/test_deprecations.py` too.

**Comment by mtsokol** [comment]
> Needs a test in `numpy/core/tests/test_deprecations.py` too.

Right, I added a test that checks the type and contents of a raised warning.

**Comment by ngoldbaum** [comment]
LGTM now, thanks @mtsokol!

**Pull request merged**
