### PR TITLE
ENH: Add 404 page

### PR DESCRIPTION
**Pull request by mjvbz**
I had added a custom 404 page for the repo i am not sure it shows when it fallbacks to 404 but i added a 404 page in __pages folder which may help you. If the team needs ti change 404 error page styles your team can change it. 

I think it may help you team. THANK YOU!

### CODE REVIEW

**Comment by melissawm** [comment]
Hello, @shonsanthosh - can you clarify where do you expect this page to show up? Currently, development around the NumPy website happens at https://github.com/numpy/numpy.org and we do have a 404 page there - see for example https://numpy.org/test

**Comment by shonsanthosh** [comment]
> Hello, @shonsanthosh - can you clarify where do you expect this page to show up? Currently, development around the NumPy website happens at https://github.com/numpy/numpy.org and we do have a 404 page there - see for example https://numpy.org/test

I have checked the page but it doesnt show any custom 404 page so i guess you can merge my commit and make it as a  404 page of the website. Below screenshot is the current 404 page. Its from github pages.

Screenshot_20211124-195827

Now days i see websites habe custom 404 page. So that i think this also need one like that.

**Comment by scratchmex** [comment]
Discussion should be moved to the proper repo as suggested.

**Comment by seberg** [comment]
Indeed, thanks everyone but will close this one since it is on the numpy repo.

**Comment by mjvbz** [comment]
Ok!

**Pull request closed without merging**
