### PR TITLE
MAINT: Update to Cython 0.29.29. 

### PR DESCRIPTION
**Pull request by felixxm**
Issue #21316.

### CODE REVIEW

**Comment by EwoutH** [comment]
You're fast, +1!

**Comment by felixxm** [comment]
> `setup.py` also needs updating.

Updated :+1:

**Comment by EwoutH** [comment]
> It looks like we have to wait for GA, https://github.com/cython/cython/runs/6451267445?check_suite_focus=true.

That queue is insane, over 100 jobs waiting

**Comment by felixxm** [comment]
Released https://pypi.org/project/Cython/0.29.29/ :rocket:

**Comment by charris** [comment]
Looks like conda hasn't got it yet. I'll wait a day or two for that, but put this in before branching in any case.

**Comment by mattip** [comment]
conda-forge has the release. Reopening to try again

**Comment by mattip** [comment]
Thanks @felixxm

**Comment by EwoutH** [comment]
Could we backport this PR to the 1.22 maintenance branch? It might fix #21008.

**Comment by charris** [comment]
@EwoutH Already marked for backport.

**Comment by charris** [comment]
Note that the gitpod build failed on merge, 0.29.29 is not yet available in mamba.

**Comment by charris** [comment]
And now 0.29.30 is out :)

**Comment by felixxm** [comment]
I prepare #21530 for the `main` branch.

**Pull request merged**
