### PR TITLE
SIMD, BUG: fix reuses the previous values during the fallback to libc

### LINKED ISSUE #17761: BUG: Invalid value in inplace log
### Reproducing code example:

I cannot reproduce on my system (yet).

### Error message:

[Travis Linux](https://travis-ci.org/github/mne-tools/mne-python/jobs/743151838) hits a RuntimeWarning it did not previously (with no relevant code changes at our end):
```
mne/filter.py:387: in _construct_fir_filter
    h = minimum_phase(h)
../../../virtualenv/python3.8.1/lib/python3.8/site-packages/scipy/signal/fir_filter_design.py:1246: in minimum_phase
    np.log(h_temp, out=h_temp)
E   RuntimeWarning: invalid value encountered in log
```
Above the error is in a SciPy call. But it appears to happen anywhere we do a `np.log(x, out=x)`, here is another:
```
mne/preprocessing/nirs/_optical_density.py:43: in optical_density
    np.log(raw._data[ii], out=raw._data[ii])
E   RuntimeWarning: invalid value encountered in log
```
If it's not clear from looking at the past few days of NumPy merges what the culprit might be, I can try to get more information out of Travis about what's actually in the offending arrays.

### NumPy/Python version information:

This is on `numpy-1.20.0.dev0+0ffaaf8` / 0ffaaf8 from Thursday (today) on `pypi.anaconda.org/scipy-wheels-nightly`. Previous builds on `numpy-1.20.0.dev0+5f071c6` / 5f071c6 from Monday didn't have this problem.

### PR DESCRIPTION
**Pull request by seiko2plus**
closes #17761

### CODE REVIEW

**Review by seberg — APPROVED** [review]
Thanks, not fluid with SIMD, but this looks good to me! Also good you noticed the sincos issue.  I guess the last test could do an exact check, but probably no good reason either.

**Comment by mattip** [comment]
ping @r-devulap

**Comment by r-devulap** [comment]
Wouldn't preventing the store from writing to these elements be a simpler and efficient fix? That is, change 
 `_mm512_mask_storeu_pd(op, load_mask, res);` to  `_mm512_mask_storeu_pd(op, or(glibc_mask, load_mask) , res);` I think that might fix it or am I missing something?

**Comment by seiko2plus** [comment]
@r-devulap,

> I think that might fix it or am I missing something?

yes, sure it will fix it but I just tried to take advantage and slightly improve performance.

I removed `unlikely` hint to avoid flush the pipe and I added a constant hint
which leads to increase the performance in between 10 to 20% for mixed and out-ranged values.

**Comment by seiko2plus** [comment]
actually using `unlikely` leads to a roughly 10% increase in performance for in-ranged values but it has bad impact on
out-ranged values.

**Comment by charris** [comment]
Thanks Sayed. I expect we will be tweaking the SIMD code going forward once it is all working.

**Comment by r-devulap** [comment]
> actually using `unlikely` leads to a roughly 10% increase in performance for in-ranged values but it has a bad impact on
> out-ranged values. 

Very surprising to see any measurable difference with just the use of `__builtin_expect `.

**Pull request merged**
