### PR TITLE
Added new Dummy function

### PR DESCRIPTION
**Pull request by satyaram413**

### CODE REVIEW

**Comment by melissawm** [comment]
Again: #20231

**Comment by eric-wieser** [comment]
@satyaram413, could you tell us what the name (and associated institution, if it has such a thing) of the course on upgrad is?

**Comment by eric-wieser** [comment]
Again: #20241

**Comment by satyaram413** [comment]
> @satyaram413, could you tell us what the name (and associated institution, if it has such a thing) of the course on upgrad is?

Hey @eric-wieser, the instructor is Sajan Kedia, and yeah Upgrad is having ties with IIITB and Liverpool John Moore's University.

**Comment by mattip** [comment]
Upgrad has a [github org](https://github.com/upgrad), pinging the members to try to stop this: @irfanahmadin, @mohitk05, @planetabhi, @pradipta.

**Comment by rkern** [comment]
They probably have no real connection to the instructor who is responsible. They maintain the software that Upgrad's website runs on.

**Comment by mohitk05** [comment]
Hello @rkern, this is unfortunate. I was an engineer at Upgrad and you are true, the ones tagged would not be able to help here. @satyaram413 you may inform your contact at Upgrad, they may have a solution for this, or @irfanahmadin may pass this on to the relevant team if it is possible for him.

**Comment by sajankedia** [comment]
@eric-wieser @rkern @irfanahmadin, @mohitk05, @planetabhi, @pradipta: 
Respected Numpy community,
I'm extremely sorry for this Numpy PR Disaster.
It was my mistake. In Upgrad, we're teaching how to contribute to Open Source.
We've reshoot the entire course, so it should not happen in the future.
I'm Extremely sorry to the entire Open Source Community.

**Pull request closed without merging**
