### PR TITLE
Update .gitignore file

### PR DESCRIPTION
**Pull request by singhaditya28**
Update file till-date to ensure improved stability and security
Hope I'm able to help. 😃 👍

### CODE REVIEW

**Comment by eric-wieser** [comment]
Was this modified by hand, or copied from a standard template somewhere?

**Comment by singhaditya28** [comment]
@eric-wieser  edited fully by-hand.

**Comment by pv** [comment]
Seems to be this template: https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by singhaditya28** [comment]
Template only includes the general cases, while I have added OS-based and some general ignores  too.
Obviously it was inspired from template but not copied. @pv @eric-wieser 
Hope you understand! 👍 😃

**Comment by rossbar** [comment]
I think it would be best to limit edits to the `.gitignore` file to those that are necessary, rather than a big overhaul of the entire file like this. I'm going to go ahead and close this. If you find that the current `.gitignore` misses some files on your system, please feel free to raise an issue/open a new PR that addresses the particulars.

**Pull request closed without merging**
