### PR TITLE
PERF: Reduce overhead of np.linalg.norm for small arrays

### PR DESCRIPTION
**Pull request by eendebakpt**
The `numpy.linalg.norm` method has some overhead for small and medium sized arrays. This PR reduces the overhead by making two small adjustments to the implementation. Details are discussed below.

Benchmark:
```
import numpy as np
x=np.random.rand(100,)
%timeit np.linalg.norm(x) 
%timeit np.sqrt(x.dot(x)) # for comparison

x=x+1j*np.random.rand(100,)
%timeit np.linalg.norm(x)
```
Results for main
```
3.63 µs ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.91 µs ± 7.91 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
5.33 µs ± 13.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
This PR
```
2.27 µs ± 10.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.92 µs ± 4.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.35 µs ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)```
```

* The call `dot(x,x)` is replaced with `x.dot(x)`. Since `x` has been cast with `asarray` and `ravel`, we know that `x` is a 1D numpy array. An alternative would be `np.inner(x,x)`. The call with `inner` is faster than `dot(x,x)` but slower than `x.dot(x)`
 
* The call to `np.sqrt` is replaced with a specialized call for float numbers (the common case). Ideally, the call would be replaced with a call to a numpy version of `sqrt` that only handles the scalar case. I could not find such a method exposed in the numpy codebase. Would it be possible to use a create such a method?

### CODE REVIEW

**Comment by seberg** [comment]
Thanks!  The first change, I think we might as well just do.  Since the input is an exact array (and not even a subclass).
The second, I am not a huge fan of, but if it is noticably faster for small array it seems OK.  A comment may be nice to note that it is just a micro-optimization.

**Comment by rossbar** [comment]
> The second, I am not a huge fan of, but if it is noticably faster for small array it seems OK. A comment may be nice to note that it is just a micro-optimization.

Agreed - are we sure that the second change actually has an appreciable impact on the benchmarks? It'd be good to know what the contribution to performance improvement is from each change.

Also re: benchmarking, we could likely get more comprehensive results with the NumPy benchmarking suite, e.g. `python runtests.py --bench-compare main bench_linalg`

**Comment by mattip** [comment]
> I tried running the benchmarks, but they do not work on my systems

Please open an issue with the tracebacks. This is the standard way for reporting performance enhancements in a reproducible way and allows us to track regressions. Maybe this PR improves one measure of performance but hurts others (unlikely, but stranger things have happened).

**Comment by eendebakpt** [comment]
I removed the specialization for float. With the ideas in https://github.com/numpy/numpy/pull/21423 (and some other ideas) the overhead from `np.sqrt` can be reduced enough that the performance advantange does not seem worth the special case.

Running benchmarks still does not work, it is due to https://github.com/numpy/numpy/issues/21288 (but it does not yet give me a solution).

**Comment by seberg** [comment]
Yeah, I just ran into the benchmark problem as well and opened gh-21428 for it.  I am not sure it would be super useful here anyway, because we are a bit short on tests for small arrays/scalars.

So it would be nice to add tests for the norm of very small arrays, but considering how simple it is now and that the benchmarks don't run easily, I am happy to glance over it now.

Can you clean up the `import math` and `float64`, though?

**Comment by eendebakpt** [comment]
Benchmark:
```
       before           after         ratio
     [fd646bd6]       [f28a2946]
     <main>           <optimize_linalg_norm>
-     16.1±0.03μs      15.3±0.08μs     0.95  bench_linalg.Linalg.time_op('norm', 'float32')
```

**Comment by seberg** [comment]
OK, the benchmark seems to at least notice a small difference and I don't think this adds any maintanence burden anyway in the current state.  So lets just get it in.

Thanks @eendebakpt.

**Pull request merged**
