### PR TITLE
DOC: Document that info() handles array instances.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
See https://github.com/numpy/numpy/issues/23245.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The updated docstring rendered on CircleCI: [numpy.info](https://output.circle-artifacts.com/output/job/688306d9-2b13-4bda-bc1b-e1d0317e10b5/artifacts/0/doc/build/html/reference/generated/numpy.info.html)

**Review by mhvk — COMMENTED** [review]
Nice! I would suggest to also add `array` to the top line of the docstring (l. 531), perhaps even as the first item:
```
Get help information for an array, function, class, or module.
```

**Comment by WarrenWeckesser** [comment]
@mhvk, good idea, done.

**Review by mhvk — APPROVED** [review]
Thanks, looks good!

**Comment by seberg** [comment]
Looks good to me also, thanks!  Can't say I have ever used `info` either for this or for the doc searching (I do wonder a bit if the latter is really still relevant, but doesn't really matter).

**Comment by seberg** [comment]
The CI skips prevented the refguide check from running.  That is failing now unfortuntely, since the pointers will vary.

**Comment by WarrenWeckesser** [comment]
Ah, right.  https://github.com/numpy/numpy/pull/23359 should fix it.

**Comment by charris** [comment]
> The CI skips prevented the refguide check from running.

Seems that whenever I do that the documents will fail :)

**Pull request merged**
