### PR TITLE
MAINT: delay initialization of getlimits (circular imports)

### LINKED ISSUE #12063: Circular import issue involving getlimits and NPY_DT_DBG_TRACING
PR #10602 seems to have triggered a circular import problem when using the dtype-transer debug mode. (set `NPY_DT_DBG_TRACING` to 1 at the top of `dtype_transfer.c`).

The problem seems to be that debug tracing tries to print a dtype before the dtype object has been created, I'm still trying to see what happened. 

It involves `getlimits.py` which has been the source of circular import issues in the past.

```python
>>> import numpy as np
Calculating dtype transfer from  to 
Traceback (most recent call last):
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/_dtype.py", line 23, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/_dtype.py", line 77, in _construction_repr
    return _scalar_str(dtype, short=short)
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/_dtype.py", line 81, in _scalar_str
    byteorder = _byte_order_str(dtype)
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/_dtype.py", line 151, in _byte_order_str
    swapped = np.dtype(int).newbyteorder('s')
AttributeError: module 'numpy' has no attribute 'dtype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 200, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 163, in _get_module_lock
SystemError: <built-in function acquire_lock> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/__init__.py", line 72, in <module>
    from . import getlimits
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/getlimits.py", line 125, in <module>
    tiny=_f16(2 ** -14))
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/getlimits.py", line 75, in __init__
    self.epsilon = self.eps = float_to_float(kwargs.pop('eps'))
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/getlimits.py", line 70, in <lambda>
    float_to_float = lambda v : _fr1(float_conv(v))
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/getlimits.py", line 29, in _fr1
    a = a.copy()
SystemError: <method 'copy' of 'numpy.ndarray' objects> returned a result with an error set
```

### PR DESCRIPTION
**Pull request by ahaldane**
During module initialization, getlimits.py previously called numpy code before all of numpy was loaded,
which often causes circular import issues. This PR delays getlimits init.

This partly reverts and also continues PR #9113. Here, I made the whole of getlimits delay initialization. It's not good for any numpy code at all to be run before numpy is fully loaded.

Fixes #12063

### CODE REVIEW

**Comment by charris** [comment]
This works. I wonder if there is another way that keeps things together that hasn't occurred to us. @eric-wieser  Thoughts? This sort of thing isn't unique, ISTR that there are other places where import order is important.

**Comment by charris** [comment]
Go to close/open this to experiment with azure.

**Comment by charris** [comment]
I'm not particularly happy with this, it seems messy :( But I'll put it in if noone can suggest a better approach. I assume that the problem cannot be fixed by changing import order? Could the package be moved?

**Comment by ahaldane** [comment]
Can modules in core be moved? Currently people can import it as `import numpy.core.getlimits`, and the fact that there are no underscores suggests it is public and can't be moved.

I agree it's ugly. I just added a commit trying to make it more palatable by removing all the global variable declarations and underscores, other ideas welcome. I can drop the commit if you like the old commit better.

**Comment by eric-wieser** [comment]
@ahaldane: See my proposal at #11924 regarding moving modules in core.

**Pull request merged**
