### PR TITLE
DOC: Fixed minor typos in temp_elide.c

### PR DESCRIPTION
**Pull request by mortada**
Fixes typos introduced in #7997

### CODE REVIEW

**Comment by eric-wieser** [comment]
Put [ci-skip] on third line of the commit message when you fix that up, to save testing a comment fix

**Comment by eric-wieser** [comment]
Huh, guess that didn't work

**Comment by eric-wieser** [comment]
darn, should have been `[ci skip]`

**Comment by juliantaylor** [comment]
it's `[ci skip]`

**Comment by mortada** [comment]
thanks, just updated

**Comment by eric-wieser** [comment]
Thanks @mortada

**Pull request merged**
