### PR TITLE
BLD: distutils: more robust gfortran version checking.  Closes gh-5768.

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by juliantaylor** [comment]
couldn't we just drop gcc 3 support? or is the version needed for anything else?

**Comment by rgommers** [comment]
gcc 3.4.5 still needed on Windows for the time being

**Comment by juliantaylor** [comment]
right, looks good, lets see how long till it breaks the next time

**Comment by juliantaylor** [comment]
thanks

**Comment by juliantaylor** [comment]
I wonder what happens a gcc without -dumpversion and that other property that caused the change in the first place.

**Comment by juliantaylor** [comment]
```patch
--- a/numpy/distutils/tests/test_fcompiler_gnu.py
+++ b/numpy/distutils/tests/test_fcompiler_gnu.py
@@ -20,6 +20,8 @@ gfortran_version_strings = [
     ('GNU Fortran 95 (GCC) 4.2.0 20060218 (experimental)', '4.2.0'),
     ('GNU Fortran (GCC) 4.3.0 20070316 (experimental)', '4.3.0'),
     ('GNU Fortran (rubenvb-4.8.0) 4.8.0', '4.8.0'),
+    ('GNU Fortran (AB2) 4.8.3', '4.8.3'),
+    ('GNU Fortran 95 (Just in case 4.1.7) 4.3.2', '4.3.2'),
     ('4.8.0', '4.8.0'),
     ('4.0.3-7', '4.0.3'),
     ("gfortran: warning: couldn't understand kern.osversion '14.1.0\n4.9.1",
```

still fails ...

**Comment by juliantaylor** [comment]
might be easier to search for some other method instead of trying to parse the endless combination of strings. maybe just check for a option that was added in 4.0 to check if we have a version 3 compiler. Or some smarter way using preprocessor macros

**Comment by rgommers** [comment]
@juliantaylor I agree that this is a poor method, but it's hard to change. Worse, there are basically no tests and there's no way to test all the weird compiler versions out there. So I'd rather touch it as little as possible.

Also, we don't need to check only for >=4.0. ``GnuFCompiler.get_flags`` adds flags for ``v >= '4.6.0'`` for example.

The way that ``gfortran -dumpversion`` gets called now is in ``CCompiler_get_version``, which executes the ``version_cmd`` determined by ``FCompiler.find_executables`` and then calls ``GnuFCompiler.version_match(version_string)``.

**Pull request merged**
