### PR TITLE
BUG: Fix problems with linalg.norm with ord=numpy.inf 

### PR DESCRIPTION
**Pull request by the-master-guy**
Placed the fix in a location so that other edge cases are not incorrect, and added a test to check for the specific edge case.

Closes #10655

### CODE REVIEW

**Review by eric-wieser — CHANGES_REQUESTED** [review]
The test currently fails.

Additionally, this does the wrong thing for inputs larger than 1d, or for the keepdims argument.

I think this would be better implemented via #10635.

**Comment by eric-wieser** [comment]
@hameerabbasi: want to take this on using `initial`?

**Comment by hameerabbasi** [comment]
@eric-wieser On it. 😀

**Comment by eric-wieser** [comment]
Closing in favor of #10992

**Pull request closed without merging**
