### PR TITLE
BLD: use newer openblas wheels [wheel build]

### PR DESCRIPTION
**Pull request by mattip**
Fix wheel build failure on macos-x86_64 with newer wheels, see MacPython/openblas-libs#153. Blocking #26273.

### CODE REVIEW

**Comment by mattip** [comment]
The macos wheels build, but now the linux ones don't. Investigating.

**Comment by mattip** [comment]
CI is passing

**Review by Mousius — APPROVED** [review]

**Comment by Mousius** [comment]
I wheely needed this, thanks @mattip!

**Comment by seberg** [comment]
This should be backported, right?

**Comment by mattip** [comment]
This only needs backporting if the backports are using OpenBLAS 0.3.27 (in which case wheel building would fail without it)

**Comment by seberg** [comment]
Yeah, we backported the 0.3.27 switch, but I guess @charris will know if we have wheel building failures because of it.

**Comment by charris** [comment]
> but I guess @charris will know if we have wheel building failures

I don't recall any problems,  but lets backport this.

**Pull request merged**
