### PR TITLE
BUG: PPC64el machines are POWER for Fortran

### PR DESCRIPTION
**Pull request by matthew-brett**
Fix Fortran kind detection for PPC64el.

See: gh-3424.

### CODE REVIEW

**Comment by charris** [comment]
Have you tested on SPARC?  Otherwise, LGTM.

**Comment by charris** [comment]
BTW, you should be able to attach labels. If not we need to increase your permissions.

**Comment by matthew-brett** [comment]
Yes, I can apply labels - sorry - just didn't think to do it.

The SPARC machine I sometimes have access to is down at the moment, but I'm confident that the `machine.platform()` string does not start with 'ppc64'.  In fact, on Debian, I happen to know it's 'sparc64' (https://github.com/nipy/nibabel/blob/master/nibabel/casting.py#L668) .

**Comment by charris** [comment]
Oops, I meant on a PPC machine.

**Comment by matthew-brett** [comment]
:) - not sure how I feel about being Mr SPARC - but - I don't actually have access to a 'power' machine - I guess these were Mac G4s running OSX?    This test does pass on a big-endian 'ppc64' machine running Debian.

**Pull request merged**
