### PR TITLE
MAINT: It's faster to use an astype than to multiply by 1.0

### PR DESCRIPTION
**Pull request by archsyscall**
The existing code multiplied by 1.0 to cast `x` as double. However, it is about twice as fast to use an `astype` than that.

```python
In [2]: def case1(x):
   ...:     return x * 1.0
   ...:

In [3]: def case2(x):
   ...:     return x.astype('float64')
   ...:

In [4]: arr = np.random.randint(0, 1000, 10000)

In [5]: %timeit case1(arr)
9.35 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [6]: %timeit case2(arr)
4.75 µs ± 39.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Thank You!

### CODE REVIEW

**Review by eric-wieser — CHANGES_REQUESTED** [review]
These cases are not equivalent when `x.dtype in (np.half, np.single, np.longdouble)`, or when `x` is complex

**Comment by marload** [comment]
> These cases are not equivalent when `x.dtype in (np.half, np.single, np.longdouble)`, or when `x` is complex

Thank You!

There is a way to deal with the exception, but I think it will reduce the readability of the code. So I think it's better to just leave it as it is. 

Is there a simple way to deal with the exceptions you are thinking of?

**Comment by seberg** [comment]
You would have to first use `np.result_type` and then also add `astype(dtype, copy=False)` with the copy kwarg to make it worthfile. Not sure it will be worthwhile in the end.

**Comment by mattip** [comment]
Closing. Thanks for the initiative, but this fix does not cover all the cases. Please reopen if you find a way to cleanly address the problems. I think if we were starting over we would not have [`scimath`](https://numpy.org/devdocs/reference/routines.emath.html?highlight=scimath#module-numpy.lib.scimath) in the first place, so maybe a better change would be to deprecate this module.

**Pull request closed without merging**
