### PR TITLE
TST: Add dependabot config file.

### PR DESCRIPTION
**Pull request by charris**
Create dependabot config and schedule weekly checks of dependency versions.

### CODE REVIEW

**Comment by mattip** [comment]
How do we know Dependabot can use this? Is there a dashboard that can see this is read and not causing failures?

**Comment by charris** [comment]
> How do we know Dependabot can use this?

I'm not sure, thought about that for this PR. When I added Dependabot it said that it was an alternative to doing it as part of the add process, but it wouldn't let me finish adding without doing it during the add process. There is nothing about it in the settings interface. I'm not even sure triggering a check would let us know.

**Comment by mattip** [comment]
They have a repo for [feedback](https://github.com/dependabot/feedback) maybe we should open an issue? The current file passes the [validator](https://dependabot.com/docs/config-file/validator/)

**Comment by charris** [comment]
Yeah, I checked with the validator before making the PR, it was useful because the documentation for the config file was incorrect :) Dependabot could definitely use more documentation.

**Comment by mattip** [comment]
Merging, let's hope for the best. Thanks @charris

**Pull request merged**
