### PR TITLE
DOC, TST: Clean up matplotlib imports

### LINKED ISSUE #12492: DOC, TST: matplotlib backends in doctests
As [noted](https://github.com/numpy/numpy/pull/12253#discussion_r239262077) we probably shouldn't have things like `matplotlib.use('agg')` in our docs. I added several such cases in #12253 -- I think my main reason was related to issues of:

1) having matplotlib plots showing (popping) up on my screen locally during doctests because of backend settings / whatever defaults get used with our original docstrings
2) Actual doctest errors, at least locally, without using a fixed backend

I'm not sure if the issues are less severe after the doctest->refguide transition now.

### PR DESCRIPTION
**Pull request by charris**
Backport of #12634.

Highly modified. The only fixes preserved from the original are some matplotlib imports, as most of the original problems originated with fixing up the doctests so that they passed the testing used in 1.17.0-dev.

### CODE REVIEW

**Comment by charris** [comment]
@tylerjereddy I backported  #12634 even though doctests are not current enabled in 1.16.x. Is removing 'agg' it still the right thing to?

**Comment by tylerjereddy** [comment]
I suppose this is likely harmless, yeah. I assume this is just a form of light "clean-up?"

If I'm correct in assuming that the bulk of the doc changes associated with refguide stuff are in master but not the `1.16.x maintenance` branch, then I don't think we're aiming to support i.e., local / user refguide runs until `1.17.x` series, right?

**Comment by charris** [comment]
> then I don't think we're aiming to support i.e., local / user refguide runs until 1.17.x series, right?

I'm thinking that is the easy way to go. It would be nice to have, and I was thinking of backporting the example fixes, but it isn't essential; I wouldn't do it for a normal release. What are your thoughts as to how much work it would be?

**Comment by tylerjereddy** [comment]
The diffs were pretty big so it may get a little ugly if we try to backport, but we have the testing machinery so we'd know when we got it right.

I think your idea sounds good though -- plenty of stuff to stay busy with on 1.16.x without the refguide stuff.

**Pull request merged**
