### PR TITLE
DOC: fix math formatting of np.linalg.lstsq docs

### PR DESCRIPTION
**Pull request by adamjstewart**
Previously, norm was symbolized with a double pipe. Now, it uses the actual norm symbol.

Also removes unnecessary whitespace after hanging hyphen.

P.S. Was it supposed to be the 2-norm squared / did I mess up when replacing `^2` with `_2`?

### CODE REVIEW

**Comment by adamjstewart** [comment]
How do I build the docs? I tried `cd doc; make clean; make html` but I don't see any change to the `np.linalg.lstsq` docs. Also, is there a way to only make docs for `np.linalg.lstsq`?

**Comment by adamjorr** [comment]
> How do I build the docs? I tried `cd doc; make clean; make html` but I don't see any change to the `np.linalg.lstsq` docs. Also, is there a way to only make docs for `np.linalg.lstsq`?

I think you need to do `cd doc; make dist`; I'm not sure which targets are actually required to update everything but that should do it.

**Comment by mattip** [comment]
We use autosummary to generate the documentation from docstrings, which are taken from whatever happens when you do `import numpy`. Since you are modifying `numpy/linalg/linalg.py` these changes are not picked up. So before you build the docs you need to do one of these 
- use `pip install -e .` in the numpy base directory (which will build in-place then use the version-controlled documents directly)
- use some form of `pip install .` each time you modify the source to update numpy

Whichever one you choose, sphinx will not know the docstrings are changed so you need to remove the relevant files from `doc/source/reference/generated` to get `make html` to notice and rebuild them.

If you can rephrase what I have written to make it more clear and add it to the developer documentation that would be great.

**Comment by mattip** [comment]
Checking the circleci artifact, this now renders as 

linsq

The previous version can be seen [here](http://www.numpy.org/devdocs/reference/generated/numpy.linalg.lstsq.html), so the change is an improvement but I don't understand the two `2`s next to the norm bars, is that correct (not a mathematician)?

**Comment by adamjstewart** [comment]
> So before you build the docs you need to do one of these...

Thanks @mattip, it worked perfectly!

> If you can rephrase what I have written to make it more clear and add it to the developer documentation that would be great.

I'm currently studying for my qualifying exams, but if you open an issue and assign it to me I can get to it within the month.

> I don't understand the two 2s next to the norm bars, is that correct (not a mathematician)?

The top 2 is for squared, the bottom 2 represents a 2-norm. The bottom 2 is often left out, but then it becomes ambiguous as to which type of norm it is. I can remove it if you don't want it though.

**Comment by charris** [comment]
close/reopen

**Comment by adamjstewart** [comment]
Pinging for merge.

**Comment by mattip** [comment]
So the Euclidean 2 norm norm can be written in numpy as `np.sum(np.square(b-ax))`? Could you add that for the non-mathemeticians among us?

**Comment by seberg** [comment]
@mattip would you prefer to just remove the lower 2? It is correct, but I would personally assume it is the 2-norm if there is nothing (plus the sentence spells it out). So I would be happy with removing it, in a linear algebra context it is pretty clear IMO.

Only thing would be consistency and there seems no other occurances in the linalg docs though, except the norm documentation which actually defines the `_2` (and also renders incorrectly probably).

**Comment by adamjstewart** [comment]
> It is correct, but I would personally assume it is the 2-norm if there is nothing

Agreed. Just say the word @mattip

**Comment by mattip** [comment]
The math formatting is perfect. But for the non-mathematicians among us, it would be nice to have a pseudocode alternative (if my pseudocode is accurate). No big deal, I will put this in as is and we can always extend it.

**Comment by mattip** [comment]
Thanks @adamjstewart

**Pull request merged**
