### PR TITLE
DOC: Add arraysetops to an autosummary

### PR DESCRIPTION
**Pull request by rossbar**
Generates a stub for the `numpy.lib.arraysetops` module which fixes 6 broken links (see #13114).

Also minor modifications to the `arraysetops` module docstring:
 * Remove listing of functions from module docstring.
 * Modify/improve rst formatting.

### CODE REVIEW

**Comment by mattip** [comment]
Thanks @rossbar

**Comment by bjnath** [comment]
@rossbar How did the change fix the problem? Could it be a recipe for fixing further docstrings?

**Comment by rossbar** [comment]
> How did the change fix the problem? 

There are a lot of links (see #13114) that are broken because the document they point to doesn't exist. Adding missing docs to `auto*` directives can auto-generate .rst stubs from their docstrings that then serve as anchors for the links.

> Could it be a recipe for others to fix additional docstrings?

Generally, yes - though it's not entirely formulaic. Finding the appropriate place to include the `.. autosummary` is part of the challenge (it was pretty straightforward in this case since there was already a set routines article). There are also decisions related to which auto directive to use and configuring the directive appropriately.

**Comment by bjnath** [comment]
@rossbar Thanks for explaining it!

**Pull request merged**
