### PR TITLE
DEP, MAINT: Pylint fixes, replacement of deprecated assert_ calls and more

### PR DESCRIPTION
**Pull request by marksmayo**
- replaced deprecated assert_ with assertTrue
- used isort to clean up import orders
- rewrote format of imports eg from x import y
- other minor pylint fixes like missing newlines, trailing whitespace

### CODE REVIEW

**Comment by marksmayo** [comment]
I just can't.

**Comment by charris** [comment]
You took on too much. I would have put it in when it was still small, just the benchmarks and masked arrays. In any case, if we can get Black to make some changes needed for NumPy, we will lint the whole Python part of the code base.

Thanks for the attempt.

**Comment by marksmayo** [comment]
Thanks @charris - I don't quite get why the commit check with flake8 happens on files I didn't touch, or on lines I didn't touch? Makes it tricky to get stuff in.  Unless isort does more than I expected.

**Comment by charris** [comment]
If you change something in a file, the lint check often finds unrelated things in the file, it isn't quite as limited as one might hope. We tend to ignore it in those cases.

There are two problems with massive changes. The first that they will cause conflicts with existing PRs, which will then need rebasing. The second is that they change a lot of the history. I'm not so worried about the second, but opinions vary. In any case, we only want to deal with the fallout once.

**Pull request closed without merging**
