### PR TITLE
BUG: Prefix library names with `lib` on windows.

### PR DESCRIPTION
**Pull request by ghost**
In linux and particulary MinGW on windows, library names may
be prefixed with "lib." However, if the library name is prefixed
with "lib" on MSVC or ABI-equivalent (clang/intel), the prefix should
not be excluded from the library name. This caused system_info
to find "libopenblas" or "libsuitesparse" but then add "openblas"
to the library names, which is of course problematic because
MSVC would not look for "libopenblas" but rather "openblas."

In particular:
- https://github.com/scikit-umfpack/scikit-umfpack/blob/f9cde48990e6ba2882261865f208d3d7c45c2e58/scikits/umfpack/setup.py#L32-L37
- https://github.com/SHTOOLS/build-shtools/blob/2733d27e872fee51023a3bc06b5baf197a39b027/appveyor.yml#L72-L73

### CODE REVIEW

**Comment by charris** [comment]
Does this affect the NumPy Openblas builds on windows?

**Comment by xoviat** [comment]
The answer to that is no, because the openblas file is named "openblas.a" rather than "libopenblas.a". However, that brings up a good point: this code would fail in the case where the compiler is MSVC or equivalent, but the fortran compiler is mingw or equivalent.

**Comment by xoviat** [comment]
See here: 

> MinGW supports libraries named according to the "<name>.lib" and "<name>.dll" conventions, in addition to the normal "lib<name>.a"

**Comment by xoviat** [comment]
BTW; not worth cleaning up the commits IMO; it's one commit that can be squashed on merge.

**Comment by xoviat** [comment]
@charris @rgommers 1.14 is out; I see no reason not to merge this now (I can't see any reason why it wouldn't work, and the longer it's in master, the more testing it will have).

**Comment by xoviat** [comment]
@charris Ping. Just got hit with this again.

**Comment by charris** [comment]
Well, let's see what develops.

**Comment by xoviat** [comment]
Thanks!

**Pull request merged**
