### PR TITLE
BLD: improve detection of Netlib libblas/libcblas/liblapack

### LINKED ISSUE #25028: BUG: BLAS detection assumes Debian/Ubuntu specific changes with unknown symbol from cblas
### Describe the issue:

Building NumPy 1.26.1 on openSUSE results in a module that builds fine, but when importing it results in an unknown symbol:

```
[  234s] ImportError: 
[  234s] 
[  234s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[  234s] 
[  234s] Importing the numpy C-extensions failed. This error can happen for
[  234s] many reasons, often due to issues with your setup or how NumPy was
[  234s] installed.
[  234s] 
[  234s] We have compiled some common reasons and troubleshooting tips at:
[  234s] 
[  234s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[  234s] 
[  234s] Please note and check the following:
[  234s] 
[  234s]   * The Python version is: Python3.9 from "/usr/bin/python3.9"
[  234s]   * The NumPy version is: "1.26.1"
[  234s] 
[  234s] and make sure that they are the versions you expect.
[  234s] Please carefully study the documentation linked above for further help.
[  234s] 
[  234s] Original error was: /home/abuild/rpmbuild/BUILDROOT/python-numpy-1.26.1-0.x86_64/usr/lib64/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so: undefined symbol: cblas_sgemm
```

I think this is because of a Debian-specific change, in `/usr/share/doc/libblas-dev/README.if-you-look-for-libcblas.so.3`:

    Debian science team maintainers have merged the CBLAS ABI into
    the libblas.so shared object. Everything you need from libcblas.so
    can be found in libblas.so . Please link your program against it
    instead.

Due to that change, linking against -lblas is absolutely fine, and works -- it's currently passing in your CI. However, other distributions are likely not doing the same. I can probably work around this by using blas-order=cblas, but I also thought I'd make you aware of that distribution-specific change as well.

### Reproduce the code example:

```python
<None required>
```

### Error message:

_No response_

### Runtime information:

NumPy 1.26.1
openSUSE Tumbleweed 20231026

### Context for the issue:

_No response_

### LINKED ISSUE #25041: BUG: OpenBSD/amd64 7.4 doesn't build from source due to missing `-lcblas`
### Describe the issue:

Can't install numpy through pip, because the meson can't detect the blas and lapack correctly.
And I find there aren't any blas.pc and lapack.pc under the /usr/local/lib/pkgconfig.

### Reproduce the code example:

```python
pip install numpy==1.26.1
```

### Error message:

_No response_

### Runtime information:

OpenBSD/amd 7.4
 Python 3.10

### Context for the issue:

The meson can't detect the blas and lapack in OpenBSD.

### PR DESCRIPTION
**Pull request by rgommers**
Changes:
- Add proper dependencies for Netlib BLAS and LAPACK, using both pkg-config and system (custom) detection
- Also improve the MKL and OpenBLAS detection, so there is less logged in `meson-log.txt`
- Add a CI job for split `libblas`, `libcblas` and `liblapack` in an OpenSUSE container
- Add `blas`, `cblas` and `lapack` to the FreeBSD CI job

Closes gh-25028
Closes gh-25041
Also address the issue for conda-forge with split `libblas`/`libcblas` encountered in https://github.com/conda-forge/numpy-feedstock/pull/302.

### CODE REVIEW

**Comment by rgommers** [comment]
This is good to go now.

**Comment by mattip** [comment]
LGTM, all checks are passing. It is interesting that the `mesonbuild/dependencies/blas_lapack.py` file has similarities to the numpy.distutils.sysconfig mechanism, but written in modern python.

**Comment by mattip** [comment]
Thanks @rgommers.

**Comment by rgommers** [comment]
> It is interesting that the `mesonbuild/dependencies/blas_lapack.py` file has similarities to the numpy.distutils.sysconfig mechanism, but written in modern python.

Not too surprising I guess. It is only the fallback mechanism that has the similarities though (aside from the symbol checks, which I just ported from `distutils/system_info.py`); the first choice of using pkg-config is way nicer.

**Pull request merged**
