### PR TITLE
BUG: `nanquantile`/`percentile` result shape on empty input

### PR DESCRIPTION
**Pull request by disha4u**
I have modified the nanquantile_unchecked function in /numpy/lib/nanfunctions.py so that it returns nan value for all quantiles asked for an empty array. "see Issue #14599"

This is my first commit, apologies is something went wrong and would love any feedback- mail: disha.97.agarwal@gmail.com.

### CODE REVIEW

**Comment by seberg** [comment]
Needs at least a test and follow PEP 8 style guidelines. Out of curiosity, what happens if you simply delete the whole `.size == 0` branch?

**Comment by disha4u** [comment]
> Needs at least a test and follow PEP 8 style guidelines. Out of curiosity, what happens if you simply delete the whole `.size == 0` branch?

Hi, I am new to this can you help me what all test I need to run, I will also read PEP 8 style guidelines.

**Comment by batterseapower** [comment]
> Needs at least a test and follow PEP 8 style guidelines. Out of curiosity, what happens if you simply delete the whole `.size == 0` branch?

Deleting the branch does not work because `apply_along_axis` seems to barf in this case.

**Comment by mattip** [comment]
Tests should be added to `numpy/lib/tests/test_nanfunctions.py`. You can run them with `python3 runtests.py -t numpy/lib/tests/test_nanfunctions.py`.

**Comment by mattip** [comment]
@disha4u do you wish to continue with this? Do you have questions around adding tests?

**Comment by charris** [comment]
@disha4u I'm going to close this. Feel free to open a new PR is the issue still needs fixing.

**Pull request closed without merging**
