### PR TITLE
DOC: Remove the links for ``True`` and ``False``

### PR DESCRIPTION
**Pull request by takanori-pskq**
Related to #13114 .

### CODE REVIEW

**Comment by eric-wieser** [comment]
I think changing `const` to `data` would fix this too.

**Comment by eric-wieser** [comment]
Actually, ``:const:`True` `` should work just fine, the python docs do it: https://github.com/python/cpython/blob/323188360d61875bd68688ef41711bade298af50/Doc/library/decimal.rst#L610

I think it would be better to work out why these links do not work.

**Comment by takanori-pskq** [comment]
``const:`True` `` in the python docs works because there's the document of `True` in the python docs (https://github.com/python/cpython/blob/323188360d61875bd68688ef41711bade298af50/Doc/library/constants.rst, https://docs.python.org/3/library/constants.html#True). In the numpy docs, I think external link can be used to point the document of `True` in the python docs.

**Comment by eric-wieser** [comment]
I was under the impression that intersphinx would automatically follow the link. Does ``:const:`python:True` `` work instead?

**Comment by takanori-pskq** [comment]
``:py:data:`True` `` seems to work correctly.

**Comment by eric-wieser** [comment]
Does `:py:const:` work too?

**Comment by takanori-pskq** [comment]
No, `:py:const:` doesn't work.

**Comment by eric-wieser** [comment]
It may be worth opening an issue against sphinx.

**Comment by eric-wieser** [comment]
Tried to fix the doc CI, but realized that won't work as CircleCI is silly - you'll need to rebase.

**Comment by mattip** [comment]
Thanks @takanori-pskq

**Comment by bskinn** [comment]
Yeah, intersphinx only knows how to wire cross-references together using the domain and role *exactly* as specified in the `objects.inv`.

Since `True` is present in the Python docs `objects.inv` as belonging to `:py:data:`, this is how you have to construct the reference:

```
> sphobjinv su -u https://docs.python.org/3/ `true` -s

No inventory at provided URL.
Attempting "https://docs.python.org/3/objects.inv" ...
Remote inventory found.


  Name                            Score
-------------------------------  -------
:c:function:`PyObject_IsTrue`      90
:c:macro:`Py_RETURN_TRUE`          90
:c:var:`Py_True`                   90
:py:data:`True`                    90
```

As best I understand it, the `:const:` role is likely only ever going to work for cross-references made to targets within the same documentation set.

**Pull request merged**
