### PR TITLE
TYP: use `types.CapsuleType` on python>=3.13

### PR DESCRIPTION
**Pull request by jorenham**

### CODE REVIEW

**Comment by seberg** [comment]
Has a conflict now.  `typing_extensions` includes this as a backport, but I guess we don't use that unless strictly necessary?  (which capsules are not)

**Comment by jorenham** [comment]
As far as I'm aware `typing_extensions` isn't a required dependency, so I believe that the only way do that is if with something like:

```python
try:
    from typing_extensions import CapsuleType
except ImportError:
    CapsuleType: TypeAlias = Any
```

The issue with this is the lack of guarantees regarding the `typing_extensions` version. 
So if we want to do this, I believe that the formally correct way would be to add `typing-extensions` as an optional numpy dependency, i.e. installable as extra with e.g. `pip install  numpy[typing]`, ensuring `typing_extension` version compatibility. 

I believe that there are many things in `typing_extensions` that could help with numpy typing (e.g. typevar defaults, so that we can `np.complexfloating[T]` as sugar for `np.complexfloating[T, T]`) ... but this is probably not the place to be discussing that 😋 .

**Comment by seberg** [comment]
I guess the only thing it's used for is `from typing_extensions import assert_type` (based on the comment, this is needed for Python 3.9).

Anyway, let's put this in as soon as the tests MyPy tests succeeded.

**Comment by jorenham** [comment]
> I guess the only thing it's used for is `from typing_extensions import assert_type` (based on the comment, this is needed for Python 3.9).

Exctly,and that's only within the type tests, which is no problem since the test dependencies *do* include `typing_extensions`.

I believe that it would also be valid to do 

```python
from typing import TYPE_CHECKING:

if TYPE_CHECKING:
    from typing extensions import ...
else:
    ...
```

because type-checkers are (or should be) aware of `typing_extensions`, or so I was told.

**Pull request merged**
