### PR TITLE
ENH: speed up cov by ~10% for large arrays

### PR DESCRIPTION
**Pull request by larsmans**
Replaces n² divisions by one division and n² multiplications.

Follow-up to #6403.

### CODE REVIEW

**Comment by rudimeier** [comment]
Note 10% speedup is only true if times series are really short in comparison to the number of time series. But in this case X is much smaller than ```dot(X,X.T)``` and you could better do ``` X /= sqrt(fact) ``` _before_ doing `` dot(X,X.T)```.

I guess for reasonable time series length the speedup of this patch is almost not significant because dot() has the most impact.

If you really want to optimize cov() then you could use lapack's dsyrk. to replace
```(dot(X, X.T.conj()) / fact)```  by ```dsyrk(1.0/fact, X)```. It is at least factor 2 faster, regardless of input sizes.

I have done this locally but it's not ready for upstream yet.

BTW is there a good reason why we are always using float64 even if the input would be float32?

**Comment by larsmans** [comment]
Yes, the assumption is that the dot product is cheap. If it's not, we're not losing anything.

> If you really want to optimize cov() then you could use lapack's dsyrk.

Sounds good. Should I give up on this PR so you can finish that work?

> is there a good reason why we are always using float64 even if the input would be float32?

It doesn't really matter, since the multiplication is done in-place so the type of `c` doesn't change. I just needed some floating point type that is not Python's built-in `float`, because that gives a `ZeroDivisionException` when `fact == 0` regardless of `np.errstate`.

**Comment by argriffing** [comment]
> use lapack's dsyrk.

I guess this is BLAS not LAPACK and is included in numpy's blas_lite, so I think it could be used.
https://github.com/numpy/numpy/blob/master/numpy/linalg/lapack_lite/blas_lite.c#L8665

**Comment by charris** [comment]
@argriffing The interface probably needs exposure in python. There are actually a couple of other functions in blas_lite that we might consider exposing. Scipy has it.

**Comment by larsmans** [comment]
@charris What would the proper place for that exposure, `numpy/linalg/umath_linalg.c.src`?

**Comment by larsmans** [comment]
Regarding the suggestion to do `X /= sqrt(fact)`, that's possible, but it does add new code paths that need testing (because `X_T` should then be scaled along iff it is not a view of `X`), so don't wait for me to implement that. I suggest that this PR be merged as an intermediate optimization until there is a `syrk` Python wrapper, or not at all.

**Comment by charris** [comment]
@larsmans Not sure. Probably additional exposures should be coordinated with scipy, as we could end up with different signatures, as, for instance, in qr. LU factorization, and maybe multiplication with Householder reflectors would be other functions we could expose. Agree that adding `syrk` is out of scope for this PR.

**Comment by larsmans** [comment]
It could be a private function, initially.

**Comment by charris** [comment]
LGTM. Thanks @larsmans .

**Comment by ewmoore** [comment]
If syrk is added, it should just be a private function.  It is exposed as a
public function in scipy.linalg.blas and scipy.linalg.cython_blas.  Which
are, AFAIK, the place where blas functions are provided.

**Pull request merged**
