### PR TITLE
DOC: Add warning to NPV function

### LINKED ISSUE #10877: NPV function return wrong value
numpy.npv returns wrong value.

### PR DESCRIPTION
**Pull request by Kai-Striega**
closes https://github.com/numpy/numpy/issues/10877

This PR:

* Clarifies that ``np.npv`` calculates the net present value (NPV) of a series of cashflows (at the start of each period) , rather than of a series of *future* cashflows (at the end of each period).

* Adds an example splitting the cashflows into an initial investment and future cashflows.

* Refactors the NPV-IRR congruence check as a formal example.

@joelowj do you think these changes would have helped you / would be clearer for someone like you to understand.

@seberg I don't think I have access to the built documentation, would you confirm that it was formatted correctly?

### CODE REVIEW

**Comment by seberg** [comment]
@Kai-Striega its here: https://9284-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/index.html looks good though.

**Comment by joelowj** [comment]
@Kai-Striega, thanks for your time and effort! Yup, that would make the behaviour pretty clear! 👍

**Comment by seberg** [comment]
OK, it reads fine to me as well. I will trust @Kai-Striega and @joelowj that the finance makes sense :). Thanks both of you! Honestly did not know there was a warnings section and not just a tag, but may as well use it since it renders right.

**Comment by Kai-Striega** [comment]
@seberg 

My understanding is that the ``warnings`` cautions the user whereas ``warns`` list the warnings (as in the Python object) which could be raised.

**Pull request merged**
