### PR TITLE
Improve numpy.zeros() performance.

### PR DESCRIPTION
**Pull request by miguelusque**
Hi,

I have noticed that the performance of zeros() method could be improved when initialising the array with empty() and then multiply its values by zero.

image

Hope it helps!

Regards,
Miguel

### CODE REVIEW

**Comment by miguelusque** [comment]
Actually, the smaller the array is, the higher speedup we get:

image

**Comment by eric-wieser** [comment]
The function you're editing in this PR is `np.matlib.zeros`, which is not the usual `np.zeros` (and frankly, no one should be using except in legacy code).

What operating system are your tests on?

**Comment by miguelusque** [comment]
I am running it on Google Colab, so I assume it is Linux based.

**Comment by miguelusque** [comment]
Btw, sorry to amend the unexpected files. My first PR to this repo. Would you like me to also amend the correct files?

**Comment by eric-wieser** [comment]
I find it very hard to believe that `zeros` is really this slow, given all it does is ask the operating system to provide it with a zeroed page; vs your replacement which actually does a multiplication and memory access for every element.

**Comment by WarrenWeckesser** [comment]
Multiplying by zero is not a reliable way to set the array to zero.  The uninitialized memory might contain a `nan` or `inf`, and multiplying such a value by zero gives `nan`, not zero.

**Comment by miguelusque** [comment]
Hi Eric,

Actually, you might be right. I have just tested it on a DGX server, running on a container, and the results are different:

image

I think we can safely close this PR, but, being honest, not sure why Colab has different behaviour.

Thank you for your time!

Regards,
Miguel

**Comment by mattip** [comment]
Basically you are measuring the speed of malloc/calloc. Benchmarking memory allocation is difficult. I think you might be hitting [virtual memory optimizations](https://vorpus.org/blog/why-does-calloc-exist/) (about half way down).

**Comment by miguelusque** [comment]
Hi Matti,

You’ve added a comment which interests me.

Does NumPy uses a memory pool like CuPy, cuDF and JAX, to pre-allocate memory and reduce malloc/calloc calls?
________________________________

**Comment by mattip** [comment]
Kind of. NumPy ahs a [simple pool](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/alloc.c#L34), with 1024 buckets and 7 positions in each bucket. There is a proposal to allow overriding allocation strategies via a C-API, see gh-17582.

**Pull request closed without merging**
