### PR TITLE
BUG: avoid side-effect of 'include complex.h'

### LINKED ISSUE #26787: BUG: Cython Extension Fails to Compile if C variable `I` is used.
### Describe the issue:

I have a Cython extension that uses the variable `double I` in a wrapped C function. This fails to compile with the introduction of NumPy 2.0. This specifically results when users in SymPy have chosen that a symbolic variable be named `Symbol('I')` and then we print C code using that variable and compile on the fly with Cython in our various code generation tools. I believe that this variable must clash with something defined in the included NumPy headers.

### Reproduce the code example:

```python
`ufuncify_matrix_1_h.h`:


void eval_matrix(double matrix[],
                 double thetai,
                 double omegai,
                 double thetap,
                 double omegap,
                 double Ti,
                 double I,
                 double m,
                 double g,
                 double d,
                 double h);

`ufuncify_matrix_1_c.c`:
```c
#include <math.h>
#include "ufuncify_matrix_1_h.h"

void eval_matrix(double matrix[],
                 double thetai,
                 double omegai,
                 double thetap,
                 double omegap,
                 double Ti,
                 double I,
                 double m,
                 double g,
                 double d,
                 double h)
{
    double _z0 = 1.0/h;
    matrix[0] = _z0;
    matrix[1] = -1;
    matrix[2] = -_z0;
    matrix[3] = 0;
    matrix[4] = 0;
    matrix[5] = d*g*m*cos(thetai);
    matrix[6] = I*_z0;
    matrix[7] = 0;
    matrix[8] = -I*_z0;
    matrix[9] = -1;
}
```
`ufuncify_matrix_1.pyx`:
```cython
import numpy as np
from cython.parallel import prange
cimport numpy as np
cimport cython

cdef extern from "ufuncify_matrix_1_h.h":
    void eval_matrix(double matrix[],
                     double thetai,
                     double omegai,
                     double thetap,
                     double omegap,
                     double Ti,
                     double I,
                     double m,
                     double g,
                     double d,
                     double h)

@cython.boundscheck(False)
@cython.wraparound(False)
def eval_matrix_loop(matrix,
                     thetai,
                     omegai,
                     thetap,
                     omegap,
                     Ti,
                     double I,
                     double m,
                     double g,
                     double d,
                     double h):

    cdef int n = matrix.shape[0]

    cdef double[:, ::1] matrix_memview = matrix
    cdef double[::1] thetai_memview = thetai
    cdef double[::1] omegai_memview = omegai
    cdef double[::1] thetap_memview = thetap
    cdef double[::1] omegap_memview = omegap
    cdef double[::1] Ti_memview = Ti

    cdef int i

    for i in range(n):
        eval_matrix(
            &matrix_memview[i, 0],
            thetai_memview[i],
            omegai_memview[i],
            thetap_memview[i],
            omegap_memview[i],
            Ti_memview[i],
            I,
            m,
            g,
            d,
            h)

    return matrix.reshape(n, 2, 5)
```
`ufuncify_matrix_1_setup.py`:
```python
import numpy
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

extension = Extension(name="ufuncify_matrix_1",
                      sources=["ufuncify_matrix_1.pyx",
                               "ufuncify_matrix_1_c.c"],
                      extra_compile_args=[],
                      extra_link_args=[],
                      include_dirs=[numpy.get_include()])

setup(name="eval_matrix",
      ext_modules=cythonize([extension]))
```
```


### Error message:

```shell
$ python ufuncify_matrix_1_setup.py build_ext --inplace
Compiling ufuncify_matrix_1.pyx because it changed.
[1/1] Cythonizing ufuncify_matrix_1.pyx
/home/moorepants/miniconda/envs/numpy-I/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/moorepants/src/cython-wrapper-example/ufuncify_matrix_1.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
In file included from /home/moorepants/miniconda/envs/numpy-I/lib/python3.12/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1909,
                 from /home/moorepants/miniconda/envs/numpy-I/lib/python3.12/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12,
                 from /home/moorepants/miniconda/envs/numpy-I/lib/python3.12/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from ufuncify_matrix_1.c:1251:
/home/moorepants/miniconda/envs/numpy-I/lib/python3.12/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
In file included from /home/moorepants/miniconda/envs/numpy-I/lib/python3.12/site-packages/numpy/_core/include/numpy/npy_common.h:376,
                 from /home/moorepants/miniconda/envs/numpy-I/lib/python3.12/site-packages/numpy/_core/include/numpy/ndarraytypes.h:4:
ufuncify_matrix_1_h.h:7:25: error: expected ‘)’ before ‘__extension__’
    7 |                  double I,
      |                         ^
In file included from ufuncify_matrix_1.c:1256:
ufuncify_matrix_1_h.h:8:18: error: expected ‘;’, ‘,’ or ‘)’ before ‘double’
    8 |                  double m,
      |                  ^~~~~~
ufuncify_matrix_1.c: In function ‘__pyx_pf_17ufuncify_matrix_1_eval_matrix_loop’:
ufuncify_matrix_1.c:20204:5: warning: implicit declaration of function ‘eval_matrix’ [-Wimplicit-function-declaration]
20204 |     eval_matrix((&(*((double *) ( /* dim=1 */ ((char *) (((double *) ( /* dim=0 */ (__pyx_v_matrix_memview.data + __pyx_t_8 * __pyx_v_matrix_memview.strides[0]) )) + __pyx_t_9)) )))), (*((double *) ( /* dim=0 */ ((char *) (((double *) __pyx_v_thetai_memview.data) + __pyx_t_11)) ))), (*((double *) ( /* dim=0 */ ((char *) (((double *) __pyx_v_omegai_memview.data) + __pyx_t_12)) ))), (*((double *) ( /* dim=0 */ ((char *) (((double *) __pyx_v_thetap_memview.data) + __pyx_t_13)) ))), (*((double *) ( /* dim=0 */ ((char *) (((double *) __pyx_v_omegap_memview.data) + __pyx_t_14)) ))), (*((double *) ( /* dim=0 */ ((char *) (((double *) __pyx_v_Ti_memview.data) + __pyx_t_15)) ))), __pyx_v_I, __pyx_v_m, __pyx_v_g, __pyx_v_d, __pyx_v_h);
      |     ^~~~~~~~~~~
error: command '/usr/bin/gcc' failed with exit code 1
```
```


### Python and NumPy Versions:

```
$ python
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
2.0.0
3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]
```

### Runtime Environment:

```
>>> import numpy; numpy.show_runtime()
[{'numpy_version': '2.0.0',
  'python': '3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) '
            '[GCC 12.3.0]',
  'uname': uname_result(system='Linux', node='nandi', release='6.8.0-35-generic', version='#35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'architecture': 'Haswell',
  'filepath': '/home/moorepants/miniconda/envs/numpy-I/lib/libopenblasp-r0.3.27.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]
```

### Context for the issue:

This breaks any use of `ufuncify()`, `autowrap()`, and custom C code generation in SymPy if the user happens to use a conflicting variable name. We can write some kind of intermediate solution to search for possible name clashes in the code generation processes and swap the name, if that is the issue.

### PR DESCRIPTION
**Pull request by mattip**
Fixes #26787 

I confirmed the example in the issue fails before, passes after this fix.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM. In this case it fixes a regression for SymPy, but even without that it seems like a reasonable thing to do since `I` isn't a great name to propagate to users of numpy headers.

**Comment by mattip** [comment]
I wonder if we could add a test for this in the `_core/tests/examples` directory, which currently only builds c code tests for the limited API and cython.

**Comment by rgommers** [comment]
Seems reasonable to add a test, probably requires only including a numpy header and then defining a variable `I` in a C extension. We could merge and backport this though, and leave the issue open until a test is added, in case it takes a while to write the test.

**Comment by mattip** [comment]
> We could merge and backport this though, and leave the issue open until a test is added

Makes sense

**Comment by seberg** [comment]
Wouldn't this break existing uses of `I` in C/C++ code which may even have an explicit `complex.h` include?

How about adding this to our `__init__.pyd` instead?  That way we don't get it in Cython, where it would be strange to use `I`, but don't break it in C/C++ where it isn't as strange and there is a decent change it is already in use.

That is especially for a backport.

**Comment by seberg** [comment]
Ah, sorry, I had read Cython in the title but I guess it is just as much about C code there.

Still seems a bit like we might break code that already uses `complex.h`, but not sure how often people actually use `I` from it.  If that isn't super rare, it may also make sense to just document this pattern?

But, I don't have a big opinion either way, because I don't really know how likely it is we will regress others, since there seems to be no choice that regresses nobody.

**Comment by mattip** [comment]
I think the error this way is preferred to the (current) opposite. If we undefine `I` (like in this PR) and someone wants to use the macro afterward, I think the compiler error message should make it clear that `I` is undefined.

**Comment by mattip** [comment]
Any more review needed here?

**Comment by seberg** [comment]
No, if people notice, we may want to add docs on how to re-add `I`, I guess.  But I guess we hope that nobody really notices anyway.

Thanks @mattip.

**Comment by duncanmmacleod** [comment]
> No, if people notice, we may want to add docs on how to re-add `I`, I guess. But I guess we hope that nobody really notices anyway.
> 
> Thanks @mattip.

not sure if this belongs in a new ticket, but I noticed:

```
/home/duncan/opt/conda/conda-bld/gstlal-inspiral_1722349839412/work/python/_spawaveform.c: In function 'SPAWaveformReduceSpin':
/home/duncan/opt/conda/conda-bld/gstlal-inspiral_1722349839412/work/python/_spawaveform.c:585:55: error: 'I' undeclared (first use in this function)
  585 |         hOfF[k] = amp * (cos(Psi+shft*f+phi0+piBy4) - I*sin(Psi+shft*f+phi0+piBy4));
      |                                                       ^
```

This is from a C extension module that has `#include <complex.h>` _before_ `#include <numpy/arrayobject.h>`.

**Comment by duncanmmacleod** [comment]
@rgommers, thanks for following up. The header block for the [relevant module](https://git.ligo.org/lscsoft/gstlal/-/blob/gstlal-inspiral-1.10.0-v1/gstlal-inspiral/python/_spawaveform.c?ref_type=tags#L1-L25) looks like this:

```c
#include <Python.h>

/* standard includes */
#include <stdio.h>
#include <math.h>
#include <complex.h>
#include <string.h>

/* LAL Includes */

#include <lal/LALDatatypes.h>
#include <lal/LALStdlib.h>
#include <lal/Units.h>
#include <lal/LALInspiral.h>

/* GSL includes */
#include <gsl/gsl_complex.h>
#include <gsl/gsl_complex_math.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_linalg.h>
#include <gsl/gsl_blas.h>

#include <numpy/arrayobject.h>
```

As far as I can tell that follows your requirements, but ends up with `error: 'I' undeclared`.

**Comment by mattip** [comment]
This is due to issue #26787 and PR #26789. I am not sure what the correct path forward is, unfortunately C does not have namespaces (even though they are a honking great idea).

**Comment by rgommers** [comment]
Ah yes, that does meet the requirement, so no bug then indeed. 

> No, if people notice, we may want to add docs on how to re-add `I`, I guess. But I guess we hope that nobody really notices anyway.

Somebody noticed .... no way to win here really.

**Comment by mattip** [comment]
@duncanmmacleod please open a new issue, and link to the code in question.

**Comment by tkoeppe** [comment]
See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82417. libstc++ with a standards conforming mode `-std=c++NN` should not be defining `I`, but the `-std=gnu++NN` modes do cause it to be defined.

**Comment by jwakely** [comment]
Hi, GCC dev here. This PR is just completely wrong.

It's one thing to insist that users must include `Python.h` before any other headers (I don't like it, and it doesn't compose or scale, but that problem isn't caused by numpy) but it's entirely different to include a standard header then undefine its contents so that nobody can ever use `I` again.

Just saying users can include `<complex.h>` after the numpy headers obviously doesn't work because `<complex.h>` has include guards so that including it a second time has no effect.

Public library headers should not be doing this.

**Comment by seberg** [comment]
@jwakely FWIW, we already reverted the undef.

**Comment by jwakely** [comment]
Yeah, I'm aware it was already reverted by #27182 I just wanted to very clearly make the point that this was never OK in the first place. You can mess with the contents of standard library headers inside a `.c` file, but not in a public header that your downstream users consume.

**Comment by mattip** [comment]
As long as we have the ear of a GCC dev, `#define`ing the bare letter `I` to a value in a public header, while maybe stated in standards and whatever, is bad form, which is what got us in this quandry in the first place.

**Comment by jwakely** [comment]
> while maybe stated in standards and whatever, is bad form

GCC doesn't get to just not define something that's in the C standard and whatever.

By all means take that up with the C standard, but GCC has no choice. And you're 25+ years too late to take it up with the C standard now anyway, since it was added for C99.

**Comment by jwakely** [comment]
Defining it for C++ (rather than only for C) _is_ a GCC choice, not something required by the C++ standard. But is only done for `-std=gnu++NN` modes, not strict modes. But there should never have been a quandry, the macro is in the C standard, it's not something numpy needs to fix, and not something you can fix.

**Pull request merged**
