### PR TITLE
ENH: Improve performance of np.full

### LINKED ISSUE #16180: full works on lists but with very bad performance
When you pass a python list to full, it actually works as expected but with bad performance. The documentation says that only a scalar is accepted, but because it does the right thing, it's very easy for people to end up with code like this that's correct but inefficient.

```
import numpy
x = numpy.full(100, range(100))
```

The reason it's inefficient is because the source looks like this:
```
    if dtype is None:
        dtype = array(fill_value).dtype
    a = empty(shape, dtype, order)
    multiarray.copyto(a, fill_value, casting='unsafe')
    return a

```
If the dtype is not specified, the branch actually creates a copy of the whole array, throws it away, and then does it again.

I would suggest either explicitly supporting this use case, and improving performance and docs to match. Or, try to do some kind of basic check to reject this input as unacceptable.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #16180

### CODE REVIEW

**Comment by eric-wieser** [comment]
It might be good to add a test for the case you're speeding up here. A benchmark isn't necessary, but a test is enough to catch if we break `full(list)`.

**Comment by Qiyu8** [comment]
`asarray `is actually the conditionly  uncopy version of `array`, If `dtype` is set and does not match, array is still copied, then the performance remains the same. Maybe we should go through all the places where we use the `array `function, and see if we can change it to `asarray `.

**Comment by eric-wieser** [comment]
@Qiyu8, the important change here is not the switch to adarray, but the fact that we convert the variable in place to avoid converting to array a second time.

**Comment by Qiyu8** [comment]
> @Qiyu8, the important change here is not the switch to adarray, but the fact that we convert the variable in place to avoid converting to array a second time.

Should we write a benchmark to avoid unnecessary in-place copy?

**Comment by eric-wieser** [comment]
I don't think it's worth it.

**Comment by seberg** [comment]
We have a guideline for SIMD, because since they add a maintenance (and possibly code-size) burden and so should make sure they are worth the it.   I do not think we have super clear rules about it, but this is a particularly simple case.

@dojafrat this is a nice fix, would you have time to see that there is at least one test with a sequence or other array as input?  The current tests appear to be in `numpy/core/tests/test_api.py`.

**Comment by dojafrat** [comment]
Yes I can add that test!

Thanks guys

**Comment by seberg** [comment]
@dojafrat there is something wrong with the history here, a bad merge/rebase maybe. If you can manage to fix it up so that it only has the one commit in there, that would be great.  Otherwise, I think I can squash it, or try to fix it and force push to your branch...

**Comment by eric-wieser** [comment]
Closed in favor of #16644

**Pull request closed without merging**
