### PR TITLE
DOC: add PyPy support to release notes

### PR DESCRIPTION
**Pull request by mattip**
I hope the tone is correct, feel free to suggest a different phrasing more in line with the project guidelines

### CODE REVIEW

**Comment by seberg** [comment]
Would it make sense to add that "updateifcopy" logic mostly effects some functions if `out=...` is used (especially with casting)? That would be my guess at least.

We normally merge into master first, then backport to the release branch. I will edit it to that though.

**Comment by seberg** [comment]
Hmmm, changing base added some weird commits, so undid it again for now.

**Comment by charris** [comment]
Yep, should go into master. If you want, I can cut and paste it into an update I've got in the works.

**Comment by mattip** [comment]
sorry, for the mess. Yes, cut-and-paste is fine

**Comment by charris** [comment]
Done, closing this.

**Pull request closed without merging**
