### PR TITLE
ENH: Add ``ma.full`` and ``ma.full_like``

### PR DESCRIPTION
**Pull request by takanori-pskq**
Separated from #17480. See #17480 and #16300

### CODE REVIEW

**Comment by mattip** [comment]
Close/reopen to get fixes from latest master and redo the build

**Comment by charris** [comment]
This needs a release note, see the entries in doc/release/upcoming_changes` for examples of how to do that. The added functions seem reasonable to me.

**Comment by takanori-pskq** [comment]
#17480 also need a release note?

**Comment by charris** [comment]
Yes, because ENH indicates that the PR contains options/functions previously unavailable.

**Comment by takanori-pskq** [comment]
Added release note.

**Comment by mattip** [comment]
I am inclined to close this until we have a clear use case that needs the functionality.

**Comment by mattip** [comment]
Closing, see #21998 for more discussion.

**Pull request closed without merging**
