### PR TITLE
MAINT,ENH: Rename all dispatchers as well as possible

### PR DESCRIPTION
**Pull request by seberg**
This is a bit of a call and various decisions could be made.
In some cases, I simply duplicated dispatchers to get the rigth name
(there is no other way to rename the function).

In other cases, I attempted to find a somewhat decent name (without
underscore) that at least gives a better idea than having
`_dispatcher` in there.
I tried to standardize the two most common ones to `unary_operation`
and `binary_operation`.

It may be possible to auto-copy the function and replace the name
in the decorator.  In general (if there is a custom decorator), I think
using the same name is probably best.

I do not have a strong opinion about the cases where dispatchers are
used multiple times though.  E.g. when to duplicate and when not.

---

As a reminder, this fixes (mostly) the problem that:
```
np.histogram(asdf=3)
```
gives:
```
TypeError: _histogram_dispatcher() got an unexpected keyword argument 'asdf'
```
which I think is potentially confusing to users.  It thus mostly addreses gh-21647.

@shoyer since this was originally your work, could you have a look/review this?

(I am happy about other ideas, or at least reducing it to only fix places where the dispatcher is defined directly before the function.)

The following symbols have dispatcher names that do not match and are not either `unary_operation` or `binary_operation`:
```
numpy.core.fromnumeric round_ around
numpy.core.fromnumeric product prod
numpy.core.fromnumeric cumproduct cumprod
numpy.core.fromnumeric sometrue any
numpy.core.fromnumeric alltrue all
numpy.core.defchararray count find_or_count
numpy.core.defchararray find find_or_count
numpy.core.defchararray index find_or_count
numpy.core.defchararray rfind find_or_count
numpy.core.defchararray rindex find_or_count
numpy.core.defchararray rpartition partition
numpy.lib.type_check iscomplex is_type
numpy.lib.type_check isreal is_type
numpy.lib.type_check iscomplexobj is_type
numpy.lib.type_check isrealobj is_type
numpy.lib.shape_base hsplit hvdsplit
numpy.lib.shape_base vsplit hvdsplit
numpy.lib.shape_base dsplit hvdsplit
numpy.fft._pocketfft ifft fft
numpy.fft._pocketfft rfft fft
numpy.fft._pocketfft irfft fft
numpy.fft._pocketfft hfft fft
numpy.fft._pocketfft ihfft fft
numpy.fft._pocketfft ifftn fftn
numpy.fft._pocketfft fft2 fftn
numpy.fft._pocketfft ifft2 fftn
numpy.fft._pocketfft rfftn fftn
numpy.fft._pocketfft rfft2 fftn
numpy.fft._pocketfft irfftn fftn
numpy.fft._pocketfft irfft2 fftn
```

### CODE REVIEW

**Comment by charris** [comment]
@seberg Needs a rebase (already :)

**Comment by mhvk** [comment]
Bit from the sidelines, but would it not be simpler to try/except the call to the dispatcher and on error change the name of the function in the exception message? (or even just append a message noting the function that called the dispatcher). As is, I'm not sure that the reduction in code readability is worth the better error message.

**Comment by seberg** [comment]
Hmmm, I had half discarded that thought, because the inspection seemed a bit annoying.  *However*, we only have to inspect errors originating in the "dispatcher" itself, and those are much less likely to get a bunch of complicated errors their way, so the inspection is a bit less bad.

(There could be rare cases where there is a TypeError not originating from the signature mismatch, but probably really rare.)

Let me try that, I think you are likely right and that is just good.

**Comment by seberg** [comment]
OK, lets consider the alternative in gh-21731 and close this.  Thanks for the input!

**Pull request closed without merging**
