### PR TITLE
files have been added by removing sub repository

### PR DESCRIPTION
**Pull request by yiakwy**
Hi I have added files PyMatrix filder. Please check it. I wrote a blog half a year ago www.yiak.co (a long time ago) for your reference. Now my question is , numpy is really fast! So how can I integrate my coding interface into numpy?

### CODE REVIEW

**Comment by rgommers** [comment]
@yiakwy you've added 1209 files here. Please remove everything except the one or two ``.py`` files that contain you actual source code.

**Comment by yiakwy** [comment]
@rgommers  Oh that is because I use eclipse for debugging. I have deleted all eclipse cookies.

**Comment by rgommers** [comment]
Thanks, now the PR is at least readable. My comment https://github.com/numpy/numpy/pull/6039#issuecomment-118386429 still applies. This is not a reviewable PR and it's not clear what you actually intend to accomplish. A readable summary on the mailing list is key. Start with a use case, then how numpy currently supports that use case, and finally how your code improves compared to current numpy.

**Comment by rgommers** [comment]
That said, this much code is not going to fly in any case - if it's neccesary to still have 22 files with Python code, you're going to want to release it as a standalone package.

**Comment by yiakwy** [comment]
@rgommers Yes Numpy is good at its C implementation for numeric computation but does not support object container design philosophy initially (2013 I think, maybe I was wrong, and that is why pandas exists and numpy has ndtype module). Then I started implementation for universal matrix container with following principles: 
1. support n-demension matrix object container, **an uniform interface** for row vector(transpose of [...,0,0,0,0,1]) and col vector([1,0,0,0,...])
2. matrix container supports storing object from scratch, and because it is a container or matrix tree
3. matrix container can become **larger and smaller** in runtime by setting elements
4. matrix container will return None if "b[a,c,d,]" is none not raising an error (I think raising an error is not a good practice for numeric application, try to believe me)
5. matrix container is of dynamic dimension length, and "b[a,c,d]  = e "will set an element at position e even if it does not exist and filling gaps between. I also thinks that it is a good practice to do such a thing.
6. If matrix support object from scratch, it will support R Dataframe immediately.
7. Pandas interface is very ugly. That is main reason I don't want to use it.
8. It could be a numeric container which support fast matrix iteration

I know the philosophy and techniques used by numpy ndarray. All these good techniques I didn't touch will be really good for fast computation

9. it uses "gap" for fast interacting
10. it actually a one dimension array and compute index values to locate an element, while I used depth searching because the shape of matrix is runtime variable and **unpredictable**.
11. Just In Time compiler group support

So my computation speed is very slow after testing, but have a good manipulation interface just like a matrix in matlab (and better, can set headers, indice, detect n-d row vector, n-d col vector, support sub matrix like d[[1,3], [1,3]] will retur 2-d matrix).

I want numpy expert to give some ideas how these benefits can absorbed by numpy or how I can improve my codes to help numpy.

I don't want create a wheel again. It is my fault to realize numpy support "object" now so want to join community to make contribution as far as I could. 

Thanks for any ideas from numpy experts. I am able to do C Plugins

**Comment by yiakwy** [comment]
@rgommers  Maybe you can play with the codes first (it will be slow for matrix larger than 10000 * 1000, due to the reason I mentioned before but It cannot be avoid as far as I can see--since it is a mutable container, which can become larger or smaller in runtime never throw error when user access a none or set a element at position does not exist)

**Comment by yiakwy** [comment]
pandas also support index and headers but it uses **"offset"** for implementation. While I don't have "offset" it is because, "index" and "headers" have two functions:

1. human visualizaiton -
2. hash mapping

Hence I use hash mapping to do this and print it by adding "headers" and "indice" only when user indicate (by data, logically) they want see it.

All of the interface like __setitem__ or __getitem__ obeys the philosophy:
**deduce user's behaviour by using data**

e.g a nd - matrix like 

c = [0,[[[[1]]]]]

the package always print it in 2-d version:
[ 0 
  [[[1]]] ] (by default a col matrix)

and user can access it by "c[1]" the system will output "1" by deducing equation:
if all index less than or equal to 1:  ---> user want a single element
   if user omit some index in some dimension and that is valid, we get that value with new index other return row represented by c[0] 

Hi you can try the codes, it works in my version. I have updated my submission

**Comment by yiakwy** [comment]
@rgommers  you can play with the right version using my example. It should work just in my computer for different manipulation attempts made by normal numeric users

**Comment by njsmith** [comment]
Hi @yiak,

(FYI if @rgommers doesn't reply then its probably because he's just left on vacation.)

Thanks for the list of features; that's exactly the kind of thing that we need to evaluate a proposal like this. The best place for this kind of discussion is the mailing list, though, because we try to keep the issue tracker more for day to day maintenance.

In this case your proposal is pretty radical; I think enough so that you're basically trying to do something different from what numpy is trying to do. Which is fine, but like Ralf says, you'll probably have more luck releasing your work as a separate library (possibly using numpy internally for speed), so users can pick which interface they prefer. So I'm going to close this pull request; if discussion on the list leads to a consensus that done particular changes would be good, then feel free to open more targeted pull requests.

**Comment by yiakwy** [comment]
@njsmith  I will throw the questions in mail list soon. That is my faust do it separately. Then I quickly realise that I am doing things in wrong directly. I still use numpy because it is very fast. But this is exactly demo I show how these ideas come true. And I thinks it is not my problem, but **"numeric developers" problem** I am currently inspecting numpy C implementation. I do have little time on this project now (that is my school work). I wish Numpy developers might be interested on that or point out my potential problems, really.

**Pull request closed without merging**
