### PR TITLE
ENH: cross compilation: use sysconfig to determine if x86_64 linux

### PR DESCRIPTION
**Pull request by hoodmane**
Using `platform` is enquiring about the build system we want to know
about the target system. We can use `sysconfig` for that.

### CODE REVIEW

**Comment by hoodmane** [comment]
Perhaps it would be better to use `sysconfig.platform()`.

**Review by mattip — APPROVED** [review]
+1 for using `sysconfig` where possible as the One Source Of Truth

This LGTM assuming CI passes

**Comment by mattip** [comment]
Aside: I see you are using `main` instead of a named branch. I think it is better practice to have named branches:
```
git checkout -b sysconfig-not-platform
```

See [this stackoverflow](https://stackoverflow.com/questions/17445774/branch-name-when-doing-a-pull-request) about the topic.

**Comment by hoodmane** [comment]
Yeah that was a mistake but it's annoying to rename the branch if I don't notice before making the PR.

**Comment by seberg** [comment]
The s390x didn't go through (not sure, it claims it was restarted too often).  All else is green though, so putting it in, thanks!

**Comment by hoodmane** [comment]
The Travis CI jobs seem to have failed on several of my PRs. Maybe they had a minor outage yesterday or something?

**Comment by hoodmane** [comment]
Thanks for the reviews @mattip and @seberg!

**Comment by seberg** [comment]
Feels like Travis CI has been sluggish for a while.  It seems also a bit weird to me that on the details it looks like they are all still in process, but going to TravisCI all but one is long done (and that one never started)...

**Pull request merged**
