### PR TITLE
[MRG] Enable py27 travis wheels upload for downstream projects

### PR DESCRIPTION
**Pull request by ogrisel**
This is a fix for #7024.

### CODE REVIEW

**Comment by ogrisel** [comment]
Hum weird, there is a commit that should not be there. Let me amend my PR.

**Comment by ogrisel** [comment]
Ok it should be fixed.

**Comment by charris** [comment]
So this generates wheels for 2.7 and 3.5?

**Comment by njsmith** [comment]
That's the idea, yes

**Pull request merged**
