### PR TITLE
DOC: remove "last updated" date from generated HTML pages

### PR DESCRIPTION
**Pull request by mgeier**
Alternative to #18268, which just removes the "last updated" date instead of trying to make it more accurate.

### CODE REVIEW

**Comment by mgeier** [comment]
It looks like this also removes the "last updated" info from the landing page (which should stay).

Any ideas how to fix this?

**Comment by rossbar** [comment]
`html_last_updated` is a sphinx-level config value that may also be used in other places (like the landing page, as you noticed). I think we want to find a solution that only removes the info from the footer - I would start by looking at the [sphinx theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/) specifically to see if there is a way to configure the footer, either via theme-specific config values (e.g. in `html_theme_options`) or via the template.

**Comment by mgeier** [comment]
I don't have the energy for putting any more work into this.

Feel free to either merge this and live with the removal of the date from the index page or close this and remove the footer date in a separate PR.

**Comment by charris** [comment]
@rossbar Do you want to keep this open?

**Comment by rossbar** [comment]
It's fine to close IMO. If anyone wants to take up the thread, the way I'd try to do this is by overriding the [footer template](https://github.com/pydata/pydata-sphinx-theme/blob/270bf6c60de2c9f16aa32c3eeb6de39f0ee0e734/pydata_sphinx_theme/footer.html#L11-L13).

**Pull request closed without merging**
