### PR TITLE
ENH/BUG: Allow multinomial to check pvals with other float types

### LINKED ISSUE #8317: multinomial casts input to np.float64
`np.random.multinomial` seems to cast its second argument `pvals` to an array of dtype float64. Whilst this isn't an issue in and of itself, I've come across an interesting scenario where I have an array of dtype float32 whose sum is `0.99999994`, and when it gets cast to float64, its sum is now `1.0000000222053895`, which causes `np.random.multinomial` to raise `ValueError: sum(pvals[:-1]) > 1.0`. 

For a little context, I have an array of dtype float32 because it's come off the GPU, where single precision calculations are a great deal faster.

### PR DESCRIPTION
**Pull request by bashtage**
Add additional check when original input is an array that does not have dtype double

closes #8317

### CODE REVIEW

**Comment by bashtage** [comment]
The condition is kind of a mouthful, so may not be the best approach. The alternative would be to use a fused type for kahan_sum which would then be checked also using a fused type for the comparison value.

**Comment by bashtage** [comment]
The two commits use different approaches.  

1. The first uses a complex test that is only run on `np.floating` that aren't doubles.
2. The second adds a new `kahan_check` function that takes a `cython.floating` fused type to handle the float separate from the double.

**Comment by seberg** [comment]
My first impression is that the last version looks slightly nicer than the previous.  Does the `1+1e-12` threshold really make sense for float32 though?
Maybe your last version is actually the most practical one, although it is somewhat annoying that there is probably no easy recipe of how to fix a float32 or similar input which almost works...

**Comment by bashtage** [comment]
> Does the `1+1e-12` threshold really make sense for float32 though?

No. It is just 1.0.  Could use the value of np.nextafter(np.float32(1.0), np.float32(2.0)).

> Maybe your last version is actually the most practical one, although it is somewhat annoying that there is probably no easy recipe of how to fix a float32 or similar input which almost works...

Is last here 3 or 2?

**Comment by seberg** [comment]
Oh, yeah, I was thinking about option 3, which I wouldn't mind if there was some simple solution to give to the user running into the problem...

**Comment by bashtage** [comment]
I've not included the 3rd version in the 3rd commit. It is easily the simplest.

**Pull request closed without merging**
