### PR TITLE
TYP: allow ``None`` in operand sequence of nditer

### LINKED ISSUE #28038: TYP: `nditer` does not allow `None`-valued elements in operand sequence
### Describe the issue:

Passing `None`-valued elements next to array_like-valued elements in a sequence as operands to `nditer` is part of the documented idiom of [iterator-allocated output arrays](https://numpy.org/doc/stable/reference/arrays.nditer.html#iterator-allocated-output-arrays). Mentions of this can also be found in the [documentation of `nditer`](https://numpy.org/doc/stable/reference/generated/numpy.nditer.html) directly. The type-hints do not reflect this, however, and lead to an error instead when using this intended way of calling `nditer`.

### Reproduce the code example:

```python
import numpy as np
import numpy.typing as npt

def square(a: npt.NDArray):
    with np.nditer([a, None]) as it:
        for x, y in it:
            y[...] = x*x
        return it.operands[1]
```

### Error message:

```shell
Argument of type "list[NDArray[Unknown] | None]" cannot be assigned to parameter "op" of type "ArrayLike | Sequence[ArrayLike]" in function "__new__"
  Type "None" is not assignable to type "ArrayLike"
    "None" is incompatible with protocol "Buffer"
      "__buffer__" is not present
    "None" is incompatible with protocol "_SupportsArray[dtype[Any]]"
      "__array__" is not present
    "None" is incompatible with protocol "_NestedSequence[_SupportsArray[dtype[Any]]]"
      "__len__" is not present
      "__getitem__" is not present Pylance (reportArgumentType)
```

### Python and NumPy Versions:

2.2.0
3.13.1 | packaged by conda-forge | (main, Dec  5 2024, 21:23:54) [GCC 13.3.0]

### Type-checker version and settings:

Pylance 2024.12.1 used in Visual Studio Code 1.96.0

### Additional typing packages.

_No response_

### PR DESCRIPTION
**Pull request by simonaltrogge**
Prevent type-hint errors when using `nditer` in an intended way (see https://numpy.org/doc/stable/reference/arrays.nditer.html#iterator-allocated-output-arrays).

Fix #28038

### CODE REVIEW

**Comment by jorenham** [comment]
> Sequences only consisting of `None` elements are now valid according to the type hint

I'm afraid that's inevitable, as there's no way to express "a `Sequence[ArrayLike | None]` that has at least 1 element that isn't of type `None`".

**Review by jorenham — COMMENTED** [review]
In order to prevent the new `None` from accidentally being deleted in the future, it could help to add a quick type-test for this (in `numpy/typing/tests/data`, in either `reveal` or `pass`)

**Comment by simonaltrogge** [comment]
I added such a type test in cf3dc6b073890cbc982251871657afd932bec716 based on the information I found in the [testing readme](https://github.com/numpy/numpy-stubs/blob/master/tests/README.md) of the archived numpy-stubs repository as I could not find any information in the numpy repository itself. If this information is still up to date, maybe it should be migrated to this repository as well?

**Review by jorenham — APPROVED** [review]

**Comment by jorenham** [comment]
> I added such a type test in [cf3dc6b](https://github.com/numpy/numpy/commit/cf3dc6b073890cbc982251871657afd932bec716) based on the information I found in the [testing readme](https://github.com/numpy/numpy-stubs/blob/master/tests/README.md) of the archived numpy-stubs repository as I could not find any information in the numpy repository itself. If this information is still up to date, maybe it should be migrated to this repository as well?

Yea that's a good point. There's a good chance we'll be overhauling the type-tests soon, so I suppose we'll take that into consideration once we do that :)

**Comment by jorenham** [comment]
Thanks, Simon!

**Pull request merged**
