### PR TITLE
Change meshgrid 'xy' indexing logic for more than 2 arrays

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This changes the behavior of `meshgrid` with 'xy' indexing when there are more than 2 input vectors.

Before this PR, the code

``` Python
import numpy as np

x1, x2, x3, x4 = [1], [10, 20], [100, 200, 300], [1000, 2000, 3000, 4000]

ij = np.meshgrid(x1, x2, x3, x4, indexing='ij')
xy = np.meshgrid(x1, x2, x3, x4, indexing='xy')

print 'ij:', [m.shape for m in ij]
print 'xy:', [m.shape for m in xy]
```

would print

```
ij: [(1, 2, 3, 4), (1, 2, 3, 4), (1, 2, 3, 4), (1, 2, 3, 4)]
xy: [(2, 1, 3, 4), (2, 1, 3, 4), (2, 1, 3, 4), (2, 1, 3, 4)]
```

meaning that 'xy' indexing simply reverses the two first dimensions of the result of 'ij' indexing.

I don't think that it makes sense to only reverse the first two dimensions.

After this change, the same code would return 

```
ij: [(1, 2, 3, 4), (1, 2, 3, 4), (1, 2, 3, 4), (1, 2, 3, 4)]
xy: [(4, 3, 2, 1), (4, 3, 2, 1), (4, 3, 2, 1), (4, 3, 2, 1)]
```

This change does not impact the behavior in the case where only two vectors are given.

### CODE REVIEW

**Comment by pv** [comment]
The current behavior is intentional. Such change probably would not be
OK due to backward compatibility issues even if the behavior was accidental.

**Comment by SylvainCorlay** [comment]
In the sample code that I provided, I don't think that it makes sense to return `[2, 1, 3, 4]`, even though it is what the documentation is saying.

Regarding backward compatibility, all the examples that I could find were only using 2 arguments (for surface plotting in Matplotlib for example).

**Comment by pv** [comment]
The behavior emulates the Matlab function with the same name.
.
Backward incompatible changes for cosmetic reasons are usually not a
good idea. Numpy is soon 10 years old --- you cannot easily grep through
code using it, and not all of that can be found on the internet.

**Comment by SylvainCorlay** [comment]
- Matlab' s meshgrid only takes two arguments, case where the behavior is not changed:
http://www.mathworks.com/help/matlab/ref/meshgrid.html
- It is actually not a cosmetic reason, I actually ran into this behavior which I found inconsistent.
What is the policy regarding changes in numpy? Do you dismiss any change that may break any client code?

**Comment by rgommers** [comment]
@SylvainCorlay there is a strong backwards compatibility guarantee, but it depends. If a current behavior is clearly buggy, it can be changes straight away. If it's confusing or sub-optimal in some way, it is possible to change it but then it needs a deprecation cycle of 1 or 2 releases (and discussion on the mailing list). The gain has to then be substantial, because of the cost of any change for a library as heavily used as numpy.

**Comment by rgommers** [comment]
In this case I agree that it cannot be changed. Return values would keep the same shape but have different values. Even with a deprecation warning, that's very dangerous and unwanted.

**Comment by pv** [comment]
(i) Matlab's meshgrid can also take three arguments. (ii) Breaking backward compatibility would require good reasons for the change. Here, this is not obvious; the current behavior appears intentional, even if inconsistent at first sight, and a more sensible alternative is provided by `indexing='ij'`.

**Comment by SylvainCorlay** [comment]
@pv indeed, my bad, 3 arguments are allowed in Matlab. Fair enough. Closing!

**Pull request closed without merging**
