### PR TITLE
DEV: Fixed Un-responsive live-preview in gitpod.

### PR DESCRIPTION
**Pull request by bhavukkalra**
I wanted to keep the gitpod working environment Up To date as it is a Gem for Documentation workers and who wants a quick on the go setup.

Replaced existing Obselete dependencies. Added Install "esbonio".

This PR is in response of closing issue #21246

What this PR Introduces.
1) Use New Properties for restructuredtext VSCode Extension defined in newest Release [178.0.0](https://github.com/vscode-restructuredtext/vscode-restructuredtext/releases/tag/178.0.0)
2) Add a Dependency installation step in gitpod container build namely `esbonio` as they have completely moved from `docutils` based preview. Now the extension also gives a prompt to install `esbonio` for the Live-Preview to work.

Image of Working Live-Preview

working-live-preview

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
This LGTM, the configuration updates seem to be correct though I'll hold off on merging in case someone with more experience with gitpod wants to weigh in (@melissawm )

Thanks @bhavukkalra !

**Comment by bhavukkalra** [comment]
I agree with you @rossbar as I would also like to hold this PR merge. There is a reason for this.
1) I just observed that the gitpod instance is currently not able to build the docs. Its a problem with the command `make html`. I checked on my Local instance as well and getting the same error. My changes don't address the build, but I guess we should get this resolved

**Comment by bhavukkalra** [comment]
This PR now also fixes changes needed to resolve issue #21250 as well. If this PR gets successfully merged, the gitpod Instance should be up-to-date and working(build).

**Review by rossbar — APPROVED** [review]
LGTM thanks @bhavukkalra 

Let's get this so we can try the new gitpod instance and verify everything is working.

**Comment by bhavukkalra** [comment]
Sure @rossbar. I'll try the instance on my end as well to make sure that everything works as it is supposed to.

**Pull request merged**
