### PR TITLE
ENH: make f2py an executable module

### PR DESCRIPTION
**Pull request by juliantaylor**
allows pep 338 execution via python -mnumpy.f2py

### CODE REVIEW

**Comment by juliantaylor** [comment]
one could remove some duplication by using that file in f2py/setup.py where the shebang is added, thoguh I don't know whats the best way to get the f2py module path. is setup.py ever executed out of source?

**Comment by juliantaylor** [comment]
updated with less duplication, but I don't know if that works on windows
@jaimefrio can you test if the f2py still works?

**Comment by jaimefrio** [comment]
It will have to wait until Tuesday: I have retired my old Windows laptop, and now have a shiny Mac, but still have access to plenty of Windows boxes at work. What exactly do you want me to test?

**Comment by rgommers** [comment]
The main numpy ``setup.py`` is ``exec``'d by ``setupegg.py``, but I don't think you have to worry about ``f2py/setup.py`` usage other than via distutils/setuptools.

**Comment by rgommers** [comment]
I guess test that ``python -mnumpy.f2py <any_fortran_file>`` works + that scipy builds?

**Comment by juliantaylor** [comment]
no, I need tested that the f2py "binaries" still execute, they changed from text files with `#!/usr/bin/python` to `#!/usr/bin/sh`

**Comment by juliantaylor** [comment]
mh just booted my windows vm, does not work :(

**Comment by juliantaylor** [comment]
updated to a different method

**Comment by rgommers** [comment]
If you tested this and it does work on Windows (+ TravisCI is happy), then I'd say go ahead and merge it.

**Pull request merged**
