### PR TITLE
MAINT: Rearrange `numpy/testing` files

### PR DESCRIPTION
**Pull request by charris**
Prepare for follow on PR switching to pytest

* Create `numpy/testing/_private/ directory`.
  * Add `_testutils.py` from scipy to it.
  * Add `nose_tools/noseclasses.py` to it
  * Add `nose_tools/nosetester.py` to it
  * Add `nose_tools/parameterize.py` to it
  * Add `nose_toos/decorators.py` to it
* Copy `nose_tools/utils.py` to `numpy/testing`
* Redirect imports as needed.
* Delete the `nose_tools` directory and all in it.
* Rename `_testutils.py` to `_pytester.py`.
    
The `_testutils.py` file comes from scipy with scipy specific bits removed for numpy.

### CODE REVIEW

**Comment by charris** [comment]
@eric-wieser The `utils.py` diff is slightly messy because it overwrites the previous `numpy/testing/utils.py` file, basically deleting it. The source file is completely deleted. There is not much to be done here, as it is replacing a preexisting file.

**Comment by charris** [comment]
@pv Why are the scipy files in `_lib` also marked private? Is that a documentation thing?

**Comment by charris** [comment]
This completely loses the file histories. Will make another attempt.

**Comment by eric-wieser** [comment]
> This completely loses the file histories. 

Looks pretty good except for the utils.py.

To make this work, you want two commits:

* Commit 1
    * `rm destination_files`
* Commit 2
   * `mv src_files destination_files`

What git can't piece together is

* Commit 1
   * `rm destination_files`
   * `mv src_files destination_files`

**Comment by charris** [comment]
Done in #10812, but the history was already lost when the files were moved last July.

**Pull request closed without merging**
