### PR TITLE
MAINT: Rearrange `numpy/testing` directory to prepare for pytest.

### PR DESCRIPTION
**Pull request by charris**
This PR does the following in preparation for the pytest switch:

* Moves the contents of `numpy/testing/nose_tools` to `numpy/testing`
* Moves `numpy/testing/pytest_tools/decorators.py` to `numpy/testing/pytestdecorators`
* Deletes the `numpy/testing/nose_tools` and `numpy/testing/pytest_tools`

At this point it is possible to run both nose and pytest tests. The next PR in this series will switch to pytest and delete the `numpy/testing/pytestdecorators` file. At that point NumPy can no longer be tested with nose.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Is `pytestdecorators` missing a file extension?

**Comment by eric-wieser** [comment]
Git is showing a really useless diff here. Can you split this into smaller commits somehow to give it a hand?

**Comment by charris** [comment]
It is just file deletions and renames, plus a couple of lines in `setup.py` to account for that. so it is always going to look bad as a diff. In summary
```
numpy/testing/nose_tools/nosetester.py => numpy/testing/nosetester.py
numpy/testing/nose_tools/noseclasses.py => numpy/testing/noseclasses.py
numpy/testing/nose_tools/decorators.py => numpy/testing/decorators.py
numpy/testing/nose_tools/utils.py => numpy/testing/utils.py
numpy/testing/nose_tools/parameterized.py => numpy/testing/parameterized.py
numpy/testing/nose_tools => DELETED

numpy/testing/pytest_tools/decorators.py => numpy/testing/pytestdecorators.py
numpy/testing/pytest_tools/nosetester.py => DELETED
numpy/testing/pytest_tools/noseclasses.py => DELETED
numpy/testing/pytest_tools/utils.py => DELETED
numpy/testing/pytest_tools => DELETED
```
> Is pytestdecorators missing a file extension?

Indeed. curiously, it didn't matter. Fixed.

**Comment by charris** [comment]
The important thing here is probably that the tests still run :-)

**Comment by eric-wieser** [comment]
> so it is always going to look bad as a diff

I think the issue is that the diff is essentially:

```
rm a
mv b a
```
which git isn't able to handle very well, it seems.

Putting the deletions and moves in separate commits would make the diff readable, at the expense of introducing a non-testable commit. But those are introduced whenever a PR has more than one commit anyway.

**Comment by charris** [comment]
Hmm, maybe the best way is to copy the files out and commit over top of the existing files of the same name, and then delete both directories. That should give straight forward diffs. I'll close this and give that a shot. It is way too late to do it tonight.

**Comment by pv** [comment]
Could we have something like `numpy.testing._internal`, so that not everything numpy needs internally becomes public. This is probably the same thing as `pytestdecorators`  above, but marked as an internal module.

**Comment by ijazbesant** [comment]
This is a py.test plugin to facilitate the generation and comparison of data arrays produced during tests (this is a spin-off from pytest-arraydiff). ... To use, you simply need to mark the function where you want to compare arrays using @pytest.mark.array_compare , and make sure that the function returns a plain Numpy array:

**Pull request closed without merging**
