### PR TITLE
DOC: quantile parameter q is a probability

### PR DESCRIPTION
**Pull request by lorentzenchr**
The `q` argument of `numpy.quantile` is a probability level, not a quantile, see also the documentation of R's [`quantile`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html) function.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Seems reasonable, though I defer to someone with more knowledge of statistics terminology. If this change were to be made, should the descriptions in `percentile` also be updated?

**Comment by lorentzenchr** [comment]
> If this change were to be made, should the descriptions in percentile also be updated?

I thought about that, but was not so sure. Maybe we could call this arg "percentage" of the percentile.

**Comment by seberg** [comment]
Percentage seems fine, it's also used by wikipedia early on.  I wonder if it would make things a bit easier to grok if we add the "level" almost everywhere (like "probability level").  (Maybe also more precise even?)

**Comment by seberg** [comment]
Let's put it in, definitely much more correct this way and we can improve more later.  Thanks.

**Pull request merged**
