### PR TITLE
DOC: replace np.ma functions' return types with `MaskedArray`

### PR DESCRIPTION
**Pull request by paxcodes**
A quick solution to issue #16751.

Co-authored-by: IrinaMaria <28827042+IrinaMaria@users.noreply.github.com>

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @paxcodes and @IrinaMaria!. This looks good at first glance. The sprint has swamped CircleCI (where we check doc builds) a little, so we'll have to wait for a little bit - or I'll try to verify this locally after dinner.

**Comment by rgommers** [comment]
It renders like this:

image

I think adding a note at the end of the docstring is not an unreasonable solution; parsing the whole docstring with a regex as suggested in gh-16751 will be fragile. However, the trouble is that it's tricky to make numpydoc happy, since the added note is at the end. Ideally we'd add this note under the `Notes` section, and not right at the end.

So it's probably best to have a custom replacement step per function; it can't be done easily with a generic regex. I think this should work:

```python
zeros = _convert2ma('zeros', params=dict(fill_value=None, hardmask=False))
if zeros.__doc__ is not None:
    if retval not in np.ma.zeros.__doc__:
        raise RuntimeError("Don't mess with me!")

    np.ma.zeros.__doc__.replace('out : ndarray', 'out : ndarray or MaskedArray')
```
This cannot easily break silently, in the unlikely case that someone changes the original docstring without updating the replacement string, they'll get a `RuntimeError`.

Now of course we want to do this for ~10 functions, which means the above should be a simple utility function that takes:
- the function itself
- string to replace
- new string

**Comment by rgommers** [comment]
For clarification: the `if zeros.__doc__ is not None:` guard is necessary because it's possible to run `python -O ...` which will strip off docstrings and hence you should never access `__doc__` unprotected.

**Comment by paxcodes** [comment]
Thank you for the swift and helpful feedback @rgommers! I think I follow what you're saying. I will work on this if not tomorrow, some time this week!

May 9, 2021, 12:14 by ***@***.***:

**Comment by paxcodes** [comment]
IIUC, these lines here,

```py
if retval not in np.ma.zeros.__doc__:
    raise RuntimeError("Don't mess with me!")
```

is so that...

> This cannot easily break silently, in the unlikely case that someone changes the original docstring without updating the replacement string, [they'll get a RuntimeError.]

Is it correct that `retval` is a variable that contains the string we are replacing? In np.ma.zeros' case: `out : ndarray`?

And the RuntimeError will be triggered (for np.ma.zeros in this case) when the expected return value string, `out : ndarray`, is not found in the docstring for np.ma.zeros. And the person receiving the RuntimeError should either fix the docstring or update the `retval` variable. Am I understanding it correctly?

**Comment by rgommers** [comment]
Exactly! You may want to choose a more descriptive name for `retval`, as well as a more descriptive message than `"Don't mess with me!"` :)

**Comment by paxcodes** [comment]
@rgommers An example error message if the expected return type string is not found in the docstring,

> Failed to replace `out : ndarray` with `out : ndarray or MaskedArray`. The documentation string for return type, out : ndarray, " is not found in the docstring for `np.zeros`. Fix the docstring for `np.zeros` or update the expected string for return type.

Unfortunately, I still can't get my environments (locally or in gitpod) to building the docs even with a tiny change of adding a "test string". I will work on that. I thought I send an update anyway to keep this PR from being stale.

**Comment by paxcodes** [comment]
Although I can't see my changes in `/build/html`, I see it when I run `np.ma.zeros?` in iPython. Hopefully CI is happy. 🤞🏼

Screen Shot 2021-05-18 at 8 30 58 PM

**Comment by paxcodes** [comment]
@rgommers We noticed that https://numpy.org/devdocs/reference/generated/numpy.frombuffer.html does not have a "Returns" section.

We can insert a "Returns" section by replacing `\n    Notes\n    -----\n` with `\n    Returns\n    -------\n    out: MaskedArray\n\n    Notes\n    -----\n` but I wonder whether Numpy team would prefer to add the `Returns` section in the original np.frombuffer's docstring? (IIUC it would be in [_add_newdocs.py#1519](https://github.com/numpy/numpy/blob/376077268622c12d425bc1b70b8c66c53af14eea/numpy/core/_add_newdocs.py#L1519)) I can make a separate PR for that if that is the case?

**Comment by mattip** [comment]
> I can make a separate PR for that if that is the case?

Yes please, it should not be in this PR. Did you mean to link to [`ma.frombuffer`](https://numpy.org/devdocs/reference/generated/numpy.ma.frombuffer.html?highlight=frombuffer#numpy.ma.frombuffer)? Both `frombuffer` docstrings could use an explicit "Returns" section. I don't think the "Note" is appropriate and there are implications when using the `like` kwargs on the return type.

**Comment by paxcodes** [comment]
@mattip I linked to docs of [np.frombuffer](https://numpy.org/devdocs/reference/generated/numpy.frombuffer.html) because that's the docs for `np.ma.frombuffer` is based from.

Adding a "Returns" section in `np.frombuffer` will also add it to `np.ma.frombuffer`. I have made the [PR](https://github.com/numpy/numpy/pull/19093) for this. I will wait for that to be merged before proceeding to work on this.

**Comment by paxcodes** [comment]
@rgommers Ready for review.

**Review by rgommers — APPROVED** [review]
This looks good to me now, merging. Thanks @paxcodes and @IrinaMaria!

**Pull request merged**
