### PR TITLE
ENH: Add todense function to numpy.matrix

### LINKED ISSUE #6060: Proposal: Add a todense method to matrixes.
The method would be an identity map for numpy matrixes.

It is needed to match the interface offered by scipy. The particular situation which tripped me up was the following:

``` python
>>> # Preamble
>>> import scipy.sparse as S
>>> diagonals = [[1, 2, 3, 4], [1, 2, 3], [1, 2]]
>>> tmp = S.diags(diagonals, [0, -1, 2])

>>> tmp_lil = tmp.tolil()
>>> tmp_lil_0 = tmp_lil[0,:]
>>> tmp_lil_0[ tmp_lil_0.nonzero() ] # calling .todense() is necessary

    <1x2 sparse matrix of type '<type 'numpy.float64'>'
            with 2 stored elements in LInked List format>


>>> tmp_csc = tmp.tocsc()
>>> tmp_csc_0 = tmp_csc[0,:]
>>> tmp_csc_0[ tmp_csc_0.nonzero() ] # calling .todense() raises an exception

 matrix([[ 1.,  1.]])

```

I find the case to add the method compelling and do not see any obvious downsides. If it is acceptable to add it, **then should it return the same object or should it return a copy**?

With this information, I should be able to work on a pull request (#6066)

### PR DESCRIPTION
**Pull request by musically-ut**
The implementation and tests have been adapted from scipy.
Closes #6060.

### CODE REVIEW

**Comment by musically-ut** [comment]
@argriffing Has proposed how to fix my particular use-case in https://github.com/scipy/scipy/issues/5038 and has expressed his opinion that it is best not to encourage duck-typing between `scipy.sparse` and `numpy.matrix`.

Hence, I am closing this pull request.

**Comment by musically-ut** [comment]
Reopening the PR since the fix to scipy breaks backwards compatibility.

**Comment by musically-ut** [comment]
Thanks for your interest!

I'm rebasing it against `master` and am running the unit tests. Will force push my branch when they all succeed. That should lead to a clean merge/commit history.

**Comment by eric-wieser** [comment]
@musically-ut: @homu is a bot, sorry to break it to you. Yes, I fixed your type of `ENH` (yours was `EHN`)

**Comment by eric-wieser** [comment]
I think I'd prefer not to add this, since:
* Adding new features to `np.matrix` will just encourage people to use it
* This would be better implemented as `scipy.sparse.todense(a)`, which just calls `np.array(a)` on its input.

**Comment by musically-ut** [comment]
> This would be better implemented as `scipy.sparse.todense(a)`, which just calls `np.array(a)` on its input.

This was proposed a while back in https://github.com/scipy/scipy/issues/7467 but was not favorably looked upon.

**Pull request closed without merging**
