### PR TITLE
MAINT: Fixing typos in f2py comments and code.

### PR DESCRIPTION
**Pull request by melissawm**
Small PR to fix typos.

I suspect the intrinsic typo could be the source of bugs, but I coudn't find any issues directly related to this.

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]

**Comment by eric-wieser** [comment]
It would be great if we could add a tiny test that uses the now-fixed `intrinsic` keyword, which currently is not present in any of our f90 files

**Comment by seberg** [comment]
@melissawm, just a small ping, no rush. Is adding a small list something we can do easily/quickly? Seems like it would be nice to finish it off, especially if it helps with moving gh-15457.

**Comment by charris** [comment]
Thanks Melissa.

**Comment by melissawm** [comment]
Hi all, thanks for merging, yes I'll add the test!

**Pull request merged**
