### PR TITLE
MANT: refactor PyArrayMultiIterObject constructors

### PR DESCRIPTION
**Pull request by jaimefrio**
Creates a single private implementation of the PyArrayMultiIterObject
constructor, and calls it from the three existing public constructors.

### CODE REVIEW

**Comment by mhvk** [comment]
Only saw this as it came up due to the "now unmergeable" message. It makes a lot of sense to me, but I'm not sure I'm the most competent reviewer...

**Comment by eric-wieser** [comment]
Yeah, looks pretty reasonable to me too - would be willing to look in more detail after a rebase

**Comment by jaimefrio** [comment]
Homu also reminded me that this existed, will try to find tine to rebase it in the next couple of weeks.

**Comment by ron819** [comment]
@jaimefrio are you still working on this?

**Comment by mattip** [comment]
I rebased this off master and opened #13445 to hopefully get this cleanup merged soon. I will tentatively close this one, but if @jaimefrio wishes to continue, feel free to close the other and reopen this

**Pull request closed without merging**
