### PR TITLE
CI: only build cirrus wheels when requested

### PR DESCRIPTION
**Pull request by andyfaff**

### CODE REVIEW

**Comment by andyfaff** [comment]
I've checked that `[wheel build]` triggers a wheel build in f4190e4, but doesn't in 2e4b2ac.

@charris, can you try adding a `36 - Build` label to this PR, I can't do that myself?

When you add the label can you look at the cirrus-ci runner to check that adding the label triggered a wheel build? Note the last commit doesn't have `[wheel build]` in the commit message, so there's no dependency of the label and the commit message.

Lastly, the wheel build should activate on a tag beginning with v, but not if the tag contains dev0. We won't be able to test that until the next tag event.

**Comment by charris** [comment]
Looks like the Cirrus builds didn't go through.

**Comment by andyfaff** [comment]
It doesn't look like adding a label, or closing/opening a PR triggers any external CI. I'll make another commit to check if the label checking works.

**Comment by andyfaff** [comment]
@charris 5ca2bca is building wheels. There is no `[wheel build]` message, it's only building them because the label is present.
As mentioned in my last post just adding a label won't be sufficient to trigger a build, you then have to make a commit.

I hope this logic is sufficient to close #24280.

**Comment by andyfaff** [comment]
@rgommers, is the logic in here sufficient? I can remove the label tests if required.

**Comment by rgommers** [comment]
Ah this looks good, thanks @andyfaff. And yes, it'd be great to remove all label-based logic.

**Comment by rgommers** [comment]
> @charris, can you try adding a 36 - Build label to this PR, I can't do that myself?

Let me add you to the triage team now so you have permissions.

**Comment by andyfaff** [comment]
Commented out the label related things (just in case it's required later).

- wheel build once a week in a cron job
- if a tag is made that doesn't have dev0 in the tag name
- if [wheel build] is included in the commit message.

**Comment by rgommers** [comment]
That sounds like the right logic to me, thanks!

**Review by rgommers — APPROVED** [review]
LGTM, let's give this a go. Thanks @andyfaff!

**Pull request merged**
