### PR TITLE
DOC: add security vulnerability reporting and doc links to README

### LINKED ISSUE #13475: document a security vulnerability reporting mechanism
tl;dr we need a way to report security vulnerabilities to us, and to document that.

For context, see https://tidelift.com/docs/lifting/security. Since we have never had an actually urgent CVE ever (as far as I know), I'd prefer to just link to https://tidelift.com/docs/lifting/security-process. Any objections?

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-13475

### CODE REVIEW

**Comment by seberg** [comment]
Sounds OK, but how does Tidelift contact us, and who do they contact? I am actually a bit puzzled, since in the end we still need to provide a safe public key and a contact person? Or do they send an email to a few people and they got access to some secured website?

**Comment by seberg** [comment]
OK, sorry read through the process on Tidelift. So we have to make sure the "lifters" are well defined (but I guess that already has happened far enough probably). Other then that, they do promise to do some organization around the security progress, so that cannot hurt I suppose.

**Comment by rgommers** [comment]
> So we have to make sure the "lifters" are well defined (but I guess that already has happened far enough probably)

yep. it will go to me, and it should also go to a numfocus contact (I think). if anyone else wants to sign up, that would be very welcome

**Review by TychoDickerson — APPROVED** [review]
👍 Looks grate !!!

**Comment by rgommers** [comment]
Okay, this change was approved of by @charris on gh-13475 and @seberg seems fine with it too. So merging this, since it's a simple doc change and a bit time-critical.

**Comment by rgommers** [comment]
Thanks all. Again, if someone else wants their email added to Tidelift they get these alerts, that would be very welcome.

**Pull request merged**
