### PR TITLE
TST: Allow periodic 3.9-dev testing

### PR DESCRIPTION
**Pull request by charris**
This PR should not be merged, it is here so that 3.9 can be
periodically tested by rerunning the failed test.

### CODE REVIEW

**Comment by charris** [comment]
Tests pass on my machine with the just released 3.9.0b4.
```
11654 passed, 104 skipped, 61 xfailed, 2 xpassed in 423.16s (0:07:03)
```

**Comment by charris** [comment]
Note that  PyUnicode_AS_UNICODE is _not_ fixed in Cython 3.0b5.

**Comment by mattip** [comment]
Cython 0.29.21 was released [with fixes](http://docs.cython.org/en/latest/src/changes.html#id15), maybe worth giving it a shot?

**Comment by charris** [comment]
@mattip Tests pass.

**Comment by charris** [comment]
No longer needed.

**Pull request closed without merging**
