### PR TITLE
TYP: Fixed & improved ``TypeVar`` use for ``numpy.char.chararray``

### PR DESCRIPTION
**Pull request by jorenham**
Three subtle changes related to the ``TypeVar('_CharDType', ...)`` type parameter of ``numpy.char.chararrray``:

- Previously, the dtype ``TypeVar`` of ``numpy.char.chararray`` was defined in ``__init__.pyi``, from which it had to be imported, even though it was used only once.
- The ``TypeVar`` constraints were replaced with an upper type bound (``bound=``), so that subtypes of ``dtype[str_  | bytes_]`` (e.g. ``numpy.dtypes.StrDType``), and type-unions, can also be used as type-argument.
- The invariant type parameter is now covariant, because the dtype is only used as output, and never accepted as input (i.e. it's immutable).

### CODE REVIEW

**Comment by charris** [comment]
Did you intend to update the submodules?

Needs rebase.

**Comment by jorenham** [comment]
> Did you intend to update the submodules?

Hmm no not at all 🤔. No idea what happened there 🤷🏻‍♂️

**Comment by charris** [comment]
Need another rebase :)

**Comment by charris** [comment]
Thanks @jorenham .

**Pull request merged**
