### PR TITLE
STY: Drop some trailing spaces in `numpy.ma.core`.

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by charris** [comment]
Looks like another venv upgrade has broken a test. That's 5 venv releases in about two weeks... When it all settles out we may have to pin the version or fix the test. I suspect the underlying problem is the constant upgrading of setuptools.

**Comment by jakirkham** [comment]
Weird. Yeah, I still use `virtualenv` when it is appropriate, but `conda` more often than not is better for me to work with if I want multiple environments.

**Comment by jakirkham** [comment]
Do you know what the version of `venv` was before the problem appeared? Maybe it can just be pinned to that so the spurious test failures can be quelled.

**Comment by charris** [comment]
Well, the latest is 14.0.5, not sure where the test environment is at this point. Could try a commit using 14.0.4. OTOH, that script test has been an endless source of pain...

**Comment by jakirkham** [comment]
So, are you thinking of removing it instead? Was there some particular reason it was added?

**Comment by charris** [comment]
@matthew-brett Added the test to check that f2py was installed in the path. Yes, I'm tempted to disable the test.

**Pull request merged**
