### PR TITLE
DEP: Deprecate as_strided returning a writable array as default

### PR DESCRIPTION
**Pull request by seberg**

### CODE REVIEW

**Comment by seberg** [comment]
@jakirkham if you are interested in it, this would be the blue print for making the masked array warning relatively specific.

**Comment by njsmith** [comment]
+1 to the concept, but should get a mailing list post I think -- or has it had one and I missed it?

**Comment by njsmith** [comment]
BTW, I think we can remove diagonal from the warning message since it's been returning read-only views for a while now?

**Comment by seberg** [comment]
No idea, but that is your thing, so I trust you. Send an email and just removed the diagonal mention here....

**Comment by seberg** [comment]
Since there seemed to be some resistance on the mailing list, I opted with just doing adding a lengthy and scary documentation ;). If anyone finds this and is interested in the other solution (also because it gives blueprints for new "warn-on-write" stuff), the old version can be found here: https://github.com/seberg/numpy/tree/writeable-as-strided-warn-on-write

This now a simple doc change.

**Comment by njsmith** [comment]
LGTM. Do you want to also add a `writeable=True` kwarg, so that we at least have the option eventually to nudge people to explicitly say `writeable=False`?

(Or possibly `writable`, but I guess that like `referer` the ship has sailed on that one...)

**Comment by seberg** [comment]
Are you planning a spelling reform with writeable? ;) Anyway, added that since why not, if you already try to nudge people, make it at least easy.

**Comment by njsmith** [comment]
"Writable" is the [more standard spelling](https://books.google.com/ngrams/graph?content=writeable%2Cwritable&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Cwriteable%3B%2Cc0%3B%2Cs0%3B%3Bwriteable%3B%2Cc0%3B%3BWriteable%3B%2Cc0%3B.t4%3B%2Cwritable%3B%2Cc0%3B%2Cs0%3B%3Bwritable%3B%2Cc0%3B%3BWritable%3B%2Cc0%3B%3BWRITABLE%3B%2Cc0) but `flags` uses `writeable` so oh well, consistency wins :-)

**Comment by njsmith** [comment]
Thanks @seberg!

**Comment by seberg** [comment]
Seems my browser is set to UK english spell checking or something ;).

**Comment by charris** [comment]
Should get a mention in the 1.12 release notes.

**Pull request merged**
