### PR TITLE
ENH: Add density argument to histogramdd.

### PR DESCRIPTION
**Pull request by eric-wieser**
A new `density` argument is added to `histogramdd`. It is an alias for the existing `normed` argument and provides commonality with the `histogram` function in which the incorrectly implemented `normed` argument has been replaced by `density`.

Fixes gh-4371.

Less contentious version of #11397

### CODE REVIEW

**Review by rgommers — APPROVED** [review]

**Comment by charris** [comment]
Thanks Eric.

**Comment by charris** [comment]
I've marked this for a `forward-port`.

**Comment by eric-wieser** [comment]
This is another trivial-port branch that needs no rebase

**Comment by charris** [comment]
So we just need to change the base branch?

**Comment by charris** [comment]
I think it would be good if you just resubmitted it as a new PR against master.

**Comment by eric-wieser** [comment]
Yes, just resubmit the PR with the same source branch, but targeting a different base branch. I've gone ahead and done that at #11531

**Comment by eric-wieser** [comment]
Marking as a backport to indicate it made it to `master` too

**Pull request merged**
