### PR TITLE
TST: Remove Python 3.6 CI testing.

### PR DESCRIPTION
**Pull request by charris**

### CODE REVIEW

**Comment by mattip** [comment]
This will need adjusting now, might as well remove the pypy build altogether. I will redo it in the github actions workflow

**Comment by charris** [comment]
Done.

**Comment by mattip** [comment]
Thanks @charris

**Comment by mattip** [comment]
Do you want to announce on the mailing list that we have dropped python 3.6?

**Comment by charris** [comment]
Can't hurt.

**Comment by charris** [comment]
@mattip Better labels for github actions would be nice.

**Pull request merged**
