### PR TITLE
MAINT: Fix non-void function does not return a value warning

### PR DESCRIPTION
**Pull request by hoodmane**
This is the only error that comes up when compiling with `-Werror=return-type`.

### CODE REVIEW

**Comment by hoodmane** [comment]
Okay I moved the function declarations. I am concerned about changing the return type because it is an ABI break.

**Comment by hoodmane** [comment]
I think moving the `int` is an improvement. The other way was pretty hard to read.

**Comment by WarrenWeckesser** [comment]
Eventually (obviously not in this PR) it would be nice to purge the use of the `KR_headers` macro.  NumPy requires at least C99, so I don't see why these files shouldn't also have the same requirement.

**Review by WarrenWeckesser — APPROVED** [review]
LGTM.

**Comment by hoodmane** [comment]
Thanks for the review @WarrenWeckesser.

**Comment by seberg** [comment]
LGTM as well, lets get it in.  I am not sure if the file is not generated, so not sure its ideal to edit it directly.  It would also be nice to have tests...
But for not I guess we have the "external" tests by wasm and this looks fine :).

**Pull request merged**
