### PR TITLE
BUG: do not override exception on import failure

### LINKED ISSUE #7419: import_array hides true cause of import errors
When compiling for Python 3, it would be useful to utilize exception chaining to explain why "numpy.core.multiarray failed to import". I think you can use [PyException_SetCause](https://docs.python.org/3/c-api/exceptions.html#c.PyException_SetCause) to do this?

### PR DESCRIPTION
**Pull request by mattip**
Fixes #7419. Whatever failed must set an exception.

Maybe should have a test but how can we construct one?

### CODE REVIEW

**Comment by eric-wieser** [comment]
An alternative approach would be to chain exceptions here

**Comment by virtuald** [comment]
With regards to making a test... in reference to my original bug report, apparently the way I ran into this error message (or lack thereof) is documented at https://www.chiefdelphi.com/forums/showthread.php?t=145631 ...

```
ImportError: /usr/local/lib/python3.4/dist-packages/numpy/core/multiarray.cpython-34m.so: undefined symbol: PyType_GenericNew
ImportError: numpy.core.multiarray failed to import
```
The first error was the one that was hidden. So... maybe add some define that causes a symbol to be used that doesn't exist? Alternatively, you just have to cause something during that initialization process to fail somehow... surely there's something weird you could force with an environment variable or something?

**Comment by charris** [comment]
I think I'll just skip having a test. @virtuald Might be helpful if you could test this after 1.16.0 comes out.

**Comment by charris** [comment]
Thanks Matti.

**Comment by charris** [comment]
@eric-wieser The chain exception option was mentioned in the original issue. Could add it after we drop 2.7, but probably not be worth the trouble.

**Pull request merged**
