### PR TITLE
DOC: Suggest C-contiguity condition when mutating `ndarray.shape`

### PR DESCRIPTION
**Pull request by hanjohn**
Changing array shape by directly assigning dimensions to ndarray.shape generally works
if the array is C-contiguous. For an F-contiguous array, however, the error message would
inaccurately imply that the array was not contiguous at all (#10146).

The error message and references to it in documentation have been
updated to clarify that simply being contiguous in memory is not sufficient.

### CODE REVIEW

**Comment by eric-wieser** [comment]
On second thoughts, this new error message is wrong:
```
>>> a = np.zeros((2, 2), np.uint8)
>>> b = a[:,0]
>>> b.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>> b.shape
(2,)
>>> b.shape = (2, 1)  # no error
```

`C_CONTIGUOUS` might be sufficient, but it certainly isn't necessary

**Comment by hanjohn** [comment]
If C-contiguity is sufficient (but not necessary), then it sounds like my original commit message was inaccurate, but the new error message _is_ technically correct because it is asserting that 1) the array in question must not be C-contiguous and 2) the new shape simply can't be assigned without allocating a new block of memory.

This is in contrast to the original error message which is sometimes just wrong, assuming that the array was entirely non-contiguous.

Did you mean that the error message should simply be rewritten to be more helpful in general, rather than referencing C-contiguity at all? Right now it's not obvious to me that the error message can clearly/tersely communicate more details about the constraints used in `_attempt_nocopy_reshape`.

Let me know if I'm off the mark here, thanks!

**Comment by eric-wieser** [comment]
You're right, the new error message is technically correct, and a little better than what it was - but it could still be more useful.

**Comment by mhvk** [comment]
I'm not sure the contiguous part is all that useful. It only matters for those axes that are affected. Perhaps it is better to just stick with the addition as the new error message? I.e., something like "Incompatible shape: the order of the elements would change in memory. Use reshape() to make a copy with the desired shape"

**Comment by eric-wieser** [comment]
> the order of the elements would change in memory

This isn't always true either- sometimes all that's required is that padding between elements can be removed.

**Comment by shivam2012** [comment]
Is anybody still working on this. If any documentation changes are required do let me know.

**Comment by hanjohn** [comment]
I'll take another pass at it, sorry about the delay

**Comment by eric-wieser** [comment]
It looks like you just rebased everything since december somehow.

**Comment by hanjohn** [comment]
Made a mess on my branch, decided to start over with #10600

**Pull request closed without merging**
