### PR TITLE
Backport 7131

### PR DESCRIPTION
**Pull request by charris**
Backport #7131, Fix setuptools sdist

### CODE REVIEW

**Comment by charris** [comment]
The cause of the failing tests is likely this
```
pip install --upgrade "pip<8.0.0" "setuptools<19.0"
```
Looks like we need later pip or setuptools, but they don't support 2.6,3.2, and 3.3. I'm inclined to remove the test from this backport.

**Comment by njsmith** [comment]
Maybe we just need an earlier virtualenv?

**Comment by njsmith** [comment]
(If these kinds of things continue to be a pain then it wouldn't be the end of the world to just drop 2.6/3.2/3.3 for 1.11. definitely it's nice to give people advance warning but getting stuck on 1.10 is not really any different than getting stuck on 1.11 for most people, I think.)

**Comment by charris** [comment]
Checking if things work apart from known fails with current setuptools and pip.

@njsmith Has virtualenv changed recently?

**Comment by njsmith** [comment]
I'm just guessing based on the fact that it's the virtualenv call that's
failing, and the traceback seems to reference an embedded copy of pip
8.something inside a directory called virtualenv_support.

On Wed, Jan 27, 2016 at 3:31 PM, Charles Harris <notifications@github.com>
wrote:

> Checking if things work apart from known fails with current setuptools and
> pip.
>
> @njsmith <https://github.com/njsmith> Has virtualenv changed recently?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/pull/7132#issuecomment-175910438>.
>



-- 
Nathaniel J. Smith -- https://vorpus.org <http://vorpus.org>

**Comment by charris** [comment]
Looks like virtualenv was upgraded about a week ago (1.14.0 & 1.14.1).

**Comment by rgommers** [comment]
Just remove the commit with the test I'd say. There's not much value in backporting that.

**Comment by charris** [comment]
@rgommers I was going to remove the versioning and Python 3.2 test, but removing the sdist test is just as easy.

**Pull request merged**
