### PR TITLE
DOC: AI-Gen examples for ma.put

### PR DESCRIPTION
**Pull request by otieno-juma**
I used AI Llama 3 to help create these.
@bmwoodruff and I reviewed them.
[skip actions] [skip azp] [skip cirrus]

put fuction pic

### CODE REVIEW

**Comment by rgommers** [comment]
Converting to draft pending review of the first such PR: gh-26827.

**Comment by otieno-juma** [comment]
@bmwoodruff, All the checks have passed. Could you please have a look at it?

**Comment by bmwoodruff** [comment]
I ran the tests locally on my machine. Looks good. @charris, this should be ready for you to review. @otieno-juma , you can remove the draft status. We removed `[skip actions]` from our commit messages so that the benchmark test would run.

**Comment by charris** [comment]
Thanks @otieno-juma .

**Pull request merged**
