### PR TITLE
DOC: Tighten up newcomer suggestion in README See gh-19778

### PR DESCRIPTION
**Pull request by JHarrisJoshua**
Updated README; addressed comments in #19778 using the suggested edits.
Note that I did not see the same wording in dev.index.rst. Perhaps it has been updated since the original issue.
It does look like this wording shows up [here](https://numpy.org/contribute/).

### CODE REVIEW

**Comment by mattip** [comment]
Rather than expand the README.md, I would prefer to shrink it. We don't want to create two sources of documentation to manage. The README.md should only refer to the actual documentation for more information.

**Comment by JHarrisJoshua** [comment]
> Rather than expand the README.md, I would prefer to shrink it. We don't want to create two sources of documentation to manage. The README.md should only refer to the actual documentation for more information.

That makes sense to me. Just to confirm, do you want to keep any of the updates related to the #19778, and remove the rest?

**Comment by mattip** [comment]
My goal in creating that issue was to find a way to reduce the "Can I work on this? Where should I start?" comments in issues. I don't think the changes in this PR would reduce people asking "Can I work on this?". The details covered in the [developer documentation](https://numpy.org/devdocs/dev/index.html) do not relate to the social aspect of contributing: (how to choose a topic, how to declare your intention to work on it, how to find the source code that might be related) and this PR summarizes those technical directions into the README. I was looking for something else.

To be clear: if I knew what I was looking for I would have formulated it myself, part of the problem is I don't know exactly what is needed.

**Review by rossbar — COMMENTED** [review]
I'm -1 on these changes and would vote to close this. I think it's better to keep the README minimal to avoid duplication of information from more authoritative sources (e.g. the developer documentation).

**Comment by mattip** [comment]
Closing. @JHarrisJoshua thanks for the attempt, and I hope you can find another way to solve this issue.

**Pull request closed without merging**
