### PR TITLE
DOC: Fix typo in random.geometric docstring

### PR DESCRIPTION
**Pull request by dawar-s**
Replaced '.' with ',' in sample size

### CODE REVIEW

**Comment by dawar-s** [comment]
This is my first open-source contribution, fix for a small typo in random.geometric docstring. I have read all the guidelines for contributions and raised the PR. I would welcome any feedback.

**Comment by dawar-s** [comment]
I should have probably used [skip actions] [skip azp] [skip cirrus] since this is a typo fix. Also I see that macos_arm64_test has failed. Should I close this PR and create a new one with [skip actions] [skip azp] [skip cirrus] ?

**Comment by mdhaber** [comment]
> I should have probably used [skip actions] [skip azp] [skip cirrus]

Yes, good work finding that.

> Should I close this PR and create a new one 

The failure is unrelated to the PR. In any case, there would be no need to open a new PR. 

I'll respond to the content of the PR shortly.

**Comment by mdhaber** [comment]
I'll go ahead and merge this. Thanks for the fix! Looking forward to future contributions of increasing (but still focused) scope : )

**Comment by dawar-s** [comment]
Thank you so much for your kind words! I'm a bit late in my career contributing to open source, but I'll do my best to do meaningful contribution as much as possible :)

**Comment by linus-md** [comment]
Now it is obvious that I am European for introducing this in #25357 ;)

**Pull request merged**
