### PR TITLE
CI: Find cygwin test failures

### PR DESCRIPTION
**Pull request by DWesl**
Cygwin CI runs started failing linear algebra tests about two days ago.  This prints package versions so I can try to find the problem, and attempts to roll back openblas to see if that fixes the issue.

### CODE REVIEW

**Comment by charris** [comment]
That's curious, it looks like the cygwin test isn't running.

**Comment by DWesl** [comment]
I suspect someone turned it off due to the four failing tests.  Marking those tests as expected failures on Cygwin would be the other way to deal with that.

**Comment by DWesl** [comment]
> I suspect someone turned it off due to the four failing tests.

Alternately, the Cygwin CI may not have been running because I borked the syntax of the workflow file.  

I haven't found a way to make the failing tests pass again, but I can make the CI runs stop complaining.

The failing tests seem to be:
```
../../linalg/tests/test_linalg.py::TestSolve::test_sq_cases XFAIL (C...) [ 74%]  (LinalgCase: 8x8)
../../linalg/tests/test_linalg.py::TestInv::test_sq_cases XFAIL (Con...) [ 74%]  (LinalgCase: 8x8)
../../linalg/tests/test_linalg.py::TestCholesky::test_basic_property[float32-shape3] XFAIL [ 75%]
../../linalg/tests/test_linalg.py::TestCholesky::test_basic_property[float32-shape4] XFAIL [ 75%]
../../linalg/tests/test_linalg.py::TestCholesky::test_basic_property[float64-shape3] XFAIL [ 76%]
../../linalg/tests/test_linalg.py::TestCholesky::test_basic_property[float64-shape4] XFAIL [ 76%]
../../linalg/tests/test_linalg.py::TestTensorsolve::test_tensorsolve_result[shape1] XFAIL [ 76%]
```

**Comment by mattip** [comment]
I will put this in to make CI happy, but we should try to figure out why cygwin has these failures. Theoretically gcc-based cygwin should have an easier time interfacing to gcc-based OpenBLAS than MSVC, I wonder what is going on.

**Comment by mattip** [comment]
Thanks @DWesl

**Pull request merged**
