### PR TITLE
ENH: unstructured_to_structured converts dtype argument 

### PR DESCRIPTION
**Pull request by LeonaTaric**
Before:

> field = unstructured_to_structured(np.zeros((20, 2)), dtype=[('x', float), ('y', float)])  # failed

> field = unstructured_to_structured(np.zeros((20, 2)), dtype=np.dtype([('x', float), ('y', float)]))  # success

After:

> field = unstructured_to_structured(np.zeros((20, 2)), dtype=[('x', float), ('y', float)])  # success

> field = unstructured_to_structured(np.zeros((20, 2)), dtype=np.dtype([('x', float), ('y', float)]))  # success

### CODE REVIEW

**Comment by mattip** [comment]
Fixes #22428. Please provide tests.

**Comment by LeonaTaric** [comment]
> Fixes #22428. Please provide tests.

Yeah, wait a moment

**Comment by LeonaTaric** [comment]
> Fixes #22428. Please provide tests.

All Right, the tests were provided.

**Comment by seberg** [comment]
Seems like a straight forward generalization to me that is in line with what NumPy does every where else.  (recfunctions is a bit of an oddball, but I don't see why it should be here).  So merging.

Thanks @LeonaTaric.

**Comment by seberg** [comment]
Hmmm, I was going to squash it down to a single commit.  @LeonaTaric all commits are by you, right?  Also, if you wish your real name to appear on the change-log and don't mind it to be on your github profile then that might make things a bit simpler.  (the changelog is auto-compiled from committers)

**Comment by seberg** [comment]
Oh well, will just squash and assume you are the same person, thanks @LeonaTaric.

**Comment by LeonaTaric** [comment]
> Hmmm, I was going to squash it down to a single commit. @LeonaTaric all commits are by you, right? Also, if you wish your real name to appear on the change-log and don't mind it to be on your github profile then that might make things a bit simpler. (the changelog is auto-compiled from committers)

Yeah, all commits are by me. Thanks.

**Comment by LeonaTaric** [comment]
> Hmmm, I was going to squash it down to a single commit. @LeonaTaric all commits are by you, right? Also, if you wish your real name to appear on the change-log and don't mind it to be on your github profile then that might make things a bit simpler. (the changelog is auto-compiled from committers)

Don't mind, just use my profile name "LeonaTaric" ok.

**Comment by charris** [comment]
> Don't mind, just use my profile name "LeonaTaric" ok.

Makes problems for me when documenting releases, I'll need to make an entry in `.mailmap` for your name. We try to look professional :)

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @LeonaTaric! We hope you stick around! Your choices aren’t limited to submitting code patches – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Comment by LeonaTaric** [comment]
> Hi-five on merging your first pull request to NumPy, @LeonaTaric! We hope you stick around! Your choices aren’t limited to submitting code patches – you can review pull requests, help us stay on top of new and old issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

Yeah, I wish to join the mailing list and make more contributions ^_^

**Pull request merged**
