### PR TITLE
DOC: Fix a number sequence in docs

### PR DESCRIPTION
**Pull request by TwistedHardware**
I have found that there are two missing numbers in a sequence in the documentation.
http://docs.scipy.org/doc/numpy/user/misc.html#interfacing-to-c

It goes 1,2,3,5,7,8 with missing 4 and 6.

### CODE REVIEW

**Comment by TwistedHardware** [comment]
Do I have to open an issues for this?

**Comment by maniteja123** [comment]
Hi, I am not a dev. But AFAIK, it is expected to open a PR to solve an issue but the other way around is not common. So, it is fine until the PR is doing the right changes. Hope it answers the question.

**Comment by jaimefrio** [comment]
Thanks, Abdullah!

**Comment by TwistedHardware** [comment]
You are welcome Jaime, glad to help.

**Pull request merged**
