### PR TITLE
BUG: Fix memmap regression when shape=None

### PR DESCRIPTION
**Pull request by pgunn**
See issue #11223 and #11305.

Later this week I'll have more time and will look into adding coverage for this into the test suite (if nobody else gets to it first).

### CODE REVIEW

**Review by mhvk — COMMENTED** [review]
Looks good. Do indeed add a test case - as is, it clearly is too easy to get things like this to slip by!

**Comment by pgunn** [comment]
@mhvk Would you be ok with my adding the test case as a separate diff? I don't want to hold up anyone else with this fix (and can't commit to having time until later this week to learning your test infra and adding the test).

**Comment by mhvk** [comment]
I very much prefer not too -- if this needs to be merged beforehand, someone else can write the test - just a matter of using the failure in #11305.

**Comment by mattip** [comment]
test fails on master, passes on branch

**Comment by charris** [comment]
Thanks @pgunn @mattip .

**Comment by lesteve** [comment]
Great, thanks everyone for the quick fix!

**Comment by mattip** [comment]
Adding this to 1.14.5 since it is a regression from 1.14.3

**Comment by charris** [comment]
@mattip 1.14.x doesn't have this problem, #11223 went into master.

**Comment by mattip** [comment]
Ahh, that's why the cherry-pick was complaining. Thanks.

**Pull request merged**
