### PR TITLE
MAINT: replace uses of cython numpy.math.pxd with native routines

### LINKED ISSUE #25177: ENH: vendor numpy.math.pxd from cython into numpy
Cython uses `numpy.math` via a `math.pxd` file. We never vendored it into NumPy when we vendored the `__init__.pxd` file. Even though we would like to get rid of numpy.math, we have not done so yet. We should vendor that file into NumPy so that Cython can remove it in a few years.

xref cython/cython#5842

### PR DESCRIPTION
**Pull request by mattip**
[skip azp]
[skip cirrus]

Fixes #25177 in the hope that eventually CPython can drop their copy

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
The goal of removing this from Cython seems good. I am wondering however if the list of included functions isn't too random. A lot is missing, e.g.:

```python
# tmp.pyx
from numpy.math cimport asinf
from numpy.math cimport asinl
from numpy.math cimport asin
```

```
$ cython tmp.pyx -3

Error compiling Cython file:
------------------------------------------------------------
...
from numpy.math cimport asinf
from numpy.math cimport asinl
from numpy.math cimport asin
^
------------------------------------------------------------

tmp.pyx:3:0: 'numpy/math/asin.pxd' not found
```

So this doesn't seem to meet the goal Cython had of being a drop-in replacement of `libc.math`; rather this is a random grab bag of functions.

The use of `numpy.math` inside `numpy.random` is limited to two functions it looks like: `isnan` and `signbit`. That appears to be a micro-optimization that I'm not sure is worthwhile (didn't check) - it may access `__builtin_isnan` that way (`signbit` is no better). It'd be cleaner to not depend on this `math.pxd` at all and just use the regular C99 versions.

**Comment by mattip** [comment]
> It'd be cleaner to not depend on this `math.pxd` at all

That solves the need for `math.pxd` in NumPy but does not allow Cython to delete it. So maybe we should keep this PR to provide `math.pxd` in NumPy (so that Cython can at some point remove it) but 
- not use it internally
- remove anything broken from it (with a parallel PR to cython to keep the files synced)
- at some future point delete it

I think all three of those could be done in future follow-up PRs, or would you like any of them done here?

**Comment by rgommers** [comment]
I am not sure of the answer, since what bothers me the most here is that the selection of functions included makes little sense. How would a user know what's in this namespace without trial and error?

It may be better for Cython to simply deprecate the `numpy.math` namespace and tell users to prefer `libc.math` and that if they have a specific issue to work around `libc` issues, simply do this in their own code:
```cython
cdef extern from "numpy/npy_math.h" nogil:
    # replace copysign with the function of interest here
    double copysign "npy_copysign"(double, double)
```

**Comment by mattip** [comment]
I did the first step, which is to remove the use of math.pxd from NumPy. I will continue the discussion with Cython about what to do with their `numpy.math.pxd`.

**Review by rgommers — APPROVED** [review]
Thanks Matti!

**Pull request merged**
