### PR TITLE
TST: Bump the python 3.10 test version from beta4 to rc1

### PR DESCRIPTION
**Pull request by BvB93**
Use the new python 3.10rc1 release for testing.

### CODE REVIEW

**Comment by charris** [comment]
Well, that's unfortunate. I wouldn't have expected much change between b4 and rc1.

**Comment by seberg** [comment]
Honestly, the complex thing looks like a python bug when fixing something that was mostly fine probably: https://bugs.python.org/issue44698 I will comment, there.

**Comment by seberg** [comment]
Hmmm, first thought the "overflow" error came directly from the Python change.  But it may be that the error is just the right thing to do, and the subtle change causes it to show up now.

**Comment by seberg** [comment]
I guess we should just hard-code the expected values there. @BvB93  do you think typing `__name__` change is expected?

**Comment by BvB93** [comment]
> I guess we should just hard-code the expected values there. @BvB93 do you think typing `__name__` change is expected?

It isn't; `typing.Union` doesn't even have a `__name__` attribute, so how exactly did we end up with `__name__ = None` ?

**Comment by seberg** [comment]
@BvB93 can you make sure the `None` return is intentional in Python?  So long it isn't backported to 3.9 or so, we could just adapt to it...

**Comment by BvB93** [comment]
After some discussion in https://bugs.python.org/issue44524 there seems to be an agreement that the whole `__name__ is None` thing is a bug, so I'd suggest we just skip the the problematic test for 3.10rc1.

@seberg what's the best course of action here for the `complex`-related failures? 
Do you know if we can ignore the error for now, or will this require changes from our side?

**Comment by seberg** [comment]
@BvB93 it sounds like Python will revert this for 3.10 (and actually apparently also 3.9).  If we want to make CI pass, I think we can just hardcode the expected values and trust Python to add a regression test when they fix it.

**Comment by charris** [comment]
Thanks Bas. I'm a bit concerned that we make sure to enable the lookfor test when (probably) rc2 comes out.

**Comment by BvB93** [comment]
> Thanks Bas. I'm a bit concerned that we make sure to enable the lookfor test when (probably) rc2 comes out.

The `lookfor` test is currently disabled exclusively for rc1, so it should run as usual once we switch to rc2.

**Pull request merged**
