### PR TITLE
MAINT: Replace sphinx extension sphinx.ext.pngmath by sphinx.ext.imgmath.

### PR DESCRIPTION
**Pull request by kianasun**
The deprecated `pngmath` extension was removed in sphinx 1.6. The replacement is `imgmath`.

### CODE REVIEW

**Comment by charris** [comment]
Could you add a description about the change?

**Comment by charris** [comment]
This looks incomplete, there are a number of other references to `png_math` in `doc/source/conf.py` and `doc/scipy-sphinx-theme/conf.py`.

**Comment by charris** [comment]
```
./doc/source/conf.py:pngmath_use_preview = True
./doc/source/conf.py:pngmath_dvipng_args = ['-gamma', '1.5', '-D', '96', '-bg', 'Transparent']
./doc/scipy-sphinx-theme/conf.py:extensions = ['sphinx.ext.autodoc', 'sphinx.ext.pngmath', 'numpydoc',
./doc/scipy-sphinx-theme/conf.py:pngmath_latex_preamble = r"""
./doc/scipy-sphinx-theme/conf.py:pngmath_use_preview = True
./doc/scipy-sphinx-theme/conf.py:pngmath_dvipng_args = ['-gamma 1.5', '-D 96', '-bg Transparent']
```
Looks like all these go over to `imgmath` easily enough.

**Comment by charris** [comment]
Looks like `scipy-sphinx-theme` is a submodule. @pv, @jnothman does this need updating in `numpydoc`?

**Comment by skx19952** [comment]
Hi, I replaced ``pngmath`` by ``imgmath`` and used ``svg`` format instead of ``png``.  I can also replace the other references to ``pngmath`` if needed.

**Comment by charris** [comment]
I think that
```
./doc/source/conf.py:pngmath_use_preview = True
./doc/source/conf.py:pngmath_dvipng_args = ['-gamma', '1.5', '-D', '96', '-bg', 'Transparent']
```
Need replacement also. They both have `img` counterparts with `png` replaced with `img`.

**Comment by skx19952** [comment]
Hi, I think ``svg`` format is better,  but both ``imgmath_use_preview`` and  ``imgmath_dvipng_args`` are used only when format is ``png``. So I only set these options when ``sphinx.ext.pngmath`` is used.

**Comment by charris** [comment]
OK, let's give these changes a shot. Thanks @skx19952 .

**Pull request merged**
