### PR TITLE
DOC: Adding backslash between double-backtick and s.

### PR DESCRIPTION
**Pull request by dhermes**
For some reason unknown to me, this is not allowed in Sphinx.

In the currently [rendered docs][1], it makes the `<code>` (rather `<tt>`) element continue for the whole line:

screenshot from 2017-08-11 12-06-08

If a space or hyphen is used, it can look as desired (see [simple gist][2]):

screenshot from 2017-08-11 12-06-46

[1]: https://docs.scipy.org/doc/numpy-dev/user/basics.types.html
[2]: https://gist.github.com/dhermes/95158b647c30f368bcb0592752e585f9

### CODE REVIEW

**Comment by eric-wieser** [comment]
Duplicate of #9422?

**Comment by dhermes** [comment]
DERP. My bad. Totally a dupe.

**Comment by eric-wieser** [comment]
If you can fix this one up to use a backslash before that one, then I'll merge this

**Comment by dhermes** [comment]
Done.

**Comment by eric-wieser** [comment]
Two things:
* Did you check that worked locally?
* Can you squash your commits into one, and start the commit message with `DOC:`?

**Comment by dhermes** [comment]
@eric-wieser I did not check that it worked locally, being unsure how to actually build the docs. That's why I made the [teeny gist][2].

Will squash / add `DOC:` to the commit.

Can you point me to a document / command that shows how to build the docs?

PS In [`google-cloud-python`][1] we gave up asking "drive-by committers" to squash their commits. Now that the GitHub UI allows squash when merging the commit, it wasn't worth it.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python
[2]: https://gist.github.com/dhermes/95158b647c30f368bcb0592752e585f9

**Comment by dhermes** [comment]
Commits have been squashed and commit message has been amended.

**Comment by eric-wieser** [comment]
Didn't see the gist - that's convincing enough for me - next time, put `[ci skip]` in doc-only PRs, so we don't need to wait for tests

**Comment by dhermes** [comment]
> next time, put `[ci skip]` in doc-only PRs, so we don't need to wait for tests

Will do

**Comment by charris** [comment]
Conflict fixed and merged. Thanks @dhermes .

**Comment by dhermes** [comment]
Thanks!

**Pull request merged**
