### PR TITLE
BLD: Update openblas download to new location, use manylinux2010-base

### PR DESCRIPTION
**Pull request by mattip**
Backport of gh-15639 to 1.18

### CODE REVIEW

**Comment by charris** [comment]
Lots of test failures.

**Comment by charris** [comment]
Note the f strings are not available in Python 3.5.

**Comment by mattip** [comment]
1.18.1 was released with the openblas-lib tagged `v0.3.5-274-g6a8b4269`, which internally has the tag `0.3.7.dev`. We have artifacts at https://anaconda.org/multibuild-wheels-staging/openblas-libs/files with the openblas-lib tag `v0.3.5-605-gc815b8fb`. This has the internal tag `0.3.8`. If we want to move the 1.18 build to use the new location, we would have to either rebuild OpenBLAS with the `v0.3.5-274-g6a8b4269` or `v0.3.7` tag, or update to `0.3.8`.

**Comment by charris** [comment]
Why can't we just copy the libraries over? What am I missing?

**Comment by mattip** [comment]
@tylerjereddy can we copy files into anaconda.org?

**Comment by charris** [comment]
I'm going to release 1.18.2 soon using rackspace. The 1.18.x series has looked pretty good, so there may not be a 1.18.3, which would probably be the only one needing the updated location.

**Comment by mattip** [comment]
I don't think we need this. Closing. Please reopen if the rackspace storage goes away.

**Pull request closed without merging**
