### PR TITLE
ENH: Fast paths for richcompare

### LINKED ISSUE #14415: Comparisons between numpy scalars and python scalars are very slow
Comparisons between numpy scalars and python scalars are very slow. It's an order of magnitude faster to do `int(npint) == pyint` than `npint == pyint`.

It seems to me that at worst be no slower as numpy could just do `int()` for me?

The slowdown was apparent with all the types I tried including uint8, int32, float32 and uint64, **but not** int64 and float64, which are fast.

### Reproducing code example

```python
import numpy as np
import time

N = 1024 * 32
T = np.int32

def testPvP():
  y = 0
  x = T(y)
  t0 = time.perf_counter()
  for i in range(N):
    int(x) == y
  t = time.perf_counter() - t0
  print('int(np) == py:', t * 1000, 'ms')

def testNvP():
  y = 0
  x = T(y)
  t0 = time.perf_counter()
  for i in range(N):
    x == y
  t = time.perf_counter() - t0
  print('     np == py:', t * 1000, 'ms')

for i in range(5):
  testPvP()
  testNvP()
  print()
```

```
int(np) == py: 7.214172000000005 ms
     np == py: 50.713307000000015 ms

int(np) == py: 6.769899999999995 ms
     np == py: 51.27685699999998 ms

int(np) == py: 6.717130000000015 ms
     np == py: 55.45432100000003 ms

int(np) == py: 7.091216000000012 ms
     np == py: 51.84300200000003 ms

int(np) == py: 6.472694000000001 ms
     np == py: 55.38991200000004 ms
```

### Numpy/Python version information:

```
1.17.0 3.7.4 (default, Jul 13 2019, 14:20:24)
[GCC 6.3.0 20170516]
```

### PR DESCRIPTION
**Pull request by shubham11941140**
"Fixes #14415"

### CODE REVIEW

**Comment by shubham11941140** [comment]
"Fixes #14415"

**Comment by shubham11941140** [comment]
There are no conflicts and all checks have passed, please merge it with the main, so I can close the Pull Request.

**Comment by shubham11941140** [comment]
Please merge the PR.

**Comment by shubham11941140** [comment]
Please merge the PR.

**Comment by shubham11941140** [comment]
Seberg please merge this PR

**Comment by shubham11941140** [comment]
Please do the merging, so I can close this issue.

**Comment by mattip** [comment]
@shubham11941140 as I commented before, a PR is not merged until it is reviewed. If there are no corrections or modifications needed (which is rare), and if it does not require further consideration, it may be merged. If it is not commented on **for a week**, then you can ping with a reminder.

Can you explain how this PR differs from #17970 ?

**Comment by mattip** [comment]
Since it seems the submitter is just reposting older PRs, I am going to close this. @shubham11941140 please justify this resubmission if you choose to reopen.

**Comment by shubham11941140** [comment]
I have made a few changes which I want to commit. Please open it.

**Comment by shubham11941140** [comment]
Please reopen the PR, I have a few changes to make.

**Comment by ganesh-k13** [comment]
I'm just curious and asking as I opened the initial PR, is this part of some course work @shubham11941140 ? Please feel free to work on this and I can help you if needed, but any reason for taking the diff from an existing PR and pasting it almost as is without pinging the original owner?

**Comment by eric-wieser** [comment]
@ganesh-k13, this user has made 3 or 4 PRs that just copy old work without attribution. At this point, my assumption is they are acting in bad faith.

**Comment by ganesh-k13** [comment]
Yeah, found his three other PRs :). I'm trying to find a pattern here. My observation so far is that these low-quality PRs are not coming from a single college. It could be some online course given we are all WFH now.

Or it could be that college students are following some trend and read somewhere that OS contribs improves their resume.

**Pull request closed without merging**
