### PR TITLE
BUG: Fix an issue wherein assigment to `np.ma.masked_array` ignores mask in index

### LINKED ISSUE #18951: Assigment to np.ma.masked_array ignores mask in index
Assignments like a[a>=3] = 5 dont handle masked elements in condition/index properly:

### Reproducing code example:

```python
>>> import numpy as np
>>> import numpy.ma as ma

>>> a = ma.array([1, 2, 3, 4], mask=[1, 0, 1, 0])
>>> a
masked_array(data=[--, 2, --, 4],
             mask=[ True, False,  True, False],
       fill_value=999999)

>>> c = a>=3
>>> c
masked_array(data=[--, False, --, True],
             mask=[ True, False,  True, False],
       fill_value=999999)

>>> c.data
array([False, False,  True,  True])

>>> a[c] = 5
>>> a
masked_array(data=[--, 2, 5, 5],
             mask=[ True, False, False, False],
       fill_value=999999)


EXPECTED:
masked_array(data=[--, 2, --, 5],
             mask=[ True, False,  True, False],
       fill_value=999999)
```

3 is masked, so it shouldn't be overwritten.

This works as a workaround:

```python
>>> a = ma.array([1, 2, 3, 4], mask=[1, 0, 1, 0])
>>> c = a>=3
>>> a[~c.mask & c.data] = 5
>>> a
masked_array(data=[--, 2, --, 5],
             mask=[ True, False,  True, False],
       fill_value=999999)
```

### Error message:

None.

### NumPy/Python version information:

1.20.2 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
numpy-1.20.2-cp38-cp38-win_amd64.whl

### PR DESCRIPTION
**Pull request by iameskild**
Resolves #18951. 

Add a check for the case when the index is a masked_array itself. 

There are other cases which might require a check to see if the index is a masked_array within the `__setitem__` method. Should those be included in this PR? (see line 3376, 3389, 3392 in `numpy.ma.core`). 

This was a collaborative effort by @ImenRajhi and myself :)

Thank you for your review!

### CODE REVIEW

**Comment by mattip** [comment]
Is there a test where the boolean index array shape/mask fails to match the  indexed array?

**Comment by iameskild** [comment]
@mattip I apologize for the delayed response. I'm not sure I entirely understand your question, is that a scenario which we should be testing for? Do you have an example?

The test that we wrote is taken from the issue where this bug was first discussed, #18951.

**Comment by mattip** [comment]
What happens when you try:
```
a = array([1, 2, 3, 4], mask=[1, 0, 1, 0])
b = array([1, 2, 3, 4], mask=[1, 1, 1, 0])
c = b > 2
a[c] = 5
```

On the one hand the masks do not match, but on the other hand `c` does match `a` so I guess this should not raise an error. Does it?

**Comment by iameskild** [comment]
Hi @mattip, thanks for question. This does not raise an error:
```python
>>> import numpy.ma as ma
>>> a = ma.array([1, 2, 3, 4], mask=[1, 0, 1, 0])
>>> b = ma.array([1, 2, 3, 4], mask=[1, 1, 1, 0])
>>> c = b > 2
>>> c
masked_array(data=[--, --, --, True],
             mask=[ True,  True,  True, False],
       fill_value=True)
>>> a[c] = 5
>>> a
masked_array(data=[--, 2, --, 5],
             mask=[ True, False,  True, False],
       fill_value=999999)
``` 
Given our changes, I believe these are expected results. If you have any other questions, I'm happy to try and answer them. Thanks again!

**Comment by mattip** [comment]
Thanks @iameskild. Let's give this a chance, maybe downstream testing will expose an edge case I haven't thought of.

**Comment by neutrinoceros** [comment]
Hello from downstream 👋🏻 
I'm sorry to report this broke a test in yt, see issue therein https://github.com/yt-project/yt/issues/3472
Should I open a fresh issue here too ?

**Comment by mattip** [comment]
@neutrinoceros sorry about that. It would be great if you could open a new issue and describe exactly what is going on. In the terms used above, what are `a` and `c`? Does it have to do with NANs?

**Comment by neutrinoceros** [comment]
It's a bit hard to keep track of the data flow since there are two levels of abstraction between numpy and the user (namely matplotlib and yt), but I'm going to try my best to describe this in a dedicated report.

**Comment by mattip** [comment]
I think you should be able to set a `breakpoint()` just before line 3378 https://github.com/numpy/numpy/blob/6cd4b015dfd512fb4bc9d2e06a0f0cef4503582b/numpy/ma/core.py#L3376-L3380

**Comment by neutrinoceros** [comment]
thanks @mattip . After a bit of digging I was able to boil it down to a much simpler matplotlib script. Apparently the new failure only happens with the matplotlib's master branch + numpy's main branch atm.
I'm currently thinking this can be considered a mpl bug, so I reported this to matplotlib folks. Feel free to join the discussion there https://github.com/matplotlib/matplotlib/issues/20843

**Comment by mattip** [comment]
@iameskild Please take a look at the failing test in #19721 where assigning to a masked value should modify the mask to unmask that value. The current situation after this PR is that the mask is never modified, which is a change in behaviour and breaks downstream.

**Pull request merged**
