### PR TITLE
Added unique_2D function

### PR DESCRIPTION
**Pull request by Mark799**
Added a unique_2D() function to determine the unique values of the array as a whole and count these in each list of an n-dimensional array.

### CODE REVIEW

**Comment by rgommers** [comment]
Hi @Mark799, could you please explain in more detail what this adds? Why isn't using `unique` with the `axis` keyword enough?

**Comment by eendebakpt** [comment]
The `unique_2d` functionality can perhaps be implemented using `np.unique`. For example:
```
import numpy as np
x = np.array([[0,1,2,3], [0,0,0,1], [0,2,0,0], [0,0,0,99]])
print('Array:')
print(x)

unique_values = np.unique(x)
unique_values, indices = np.unique(x, return_index=True)
indices_2d = np.unravel_index(indices, x.shape)

for idx, (i, j) in enumerate(list(zip(*indices_2d))):
    value = unique_values[idx]
    print(f'unique value {value} first occurence at {i}, {j}')


unique_values, counts = np.unique(x, return_counts=True)
for idx, value in enumerate(unique_values):
    print(f'unique value {value} has count {counts[idx]}')
```
Output:
```
Array:
[[ 0  1  2  3]
 [ 0  0  0  1]
 [ 0  2  0  0]
 [ 0  0  0 99]]
unique value 0 first occurence at 0, 0
unique value 1 first occurence at 0, 1
unique value 2 first occurence at 0, 2
unique value 3 first occurence at 0, 3
unique value 99 first occurence at 3, 3
unique value 0 has count 10
unique value 1 has count 2
unique value 2 has count 2
unique value 3 has count 1
unique value 99 has count 1
```

**Comment by Mark799** [comment]
> Hi @Mark799, could you please explain in more detail what this adds? Why isn't using `unique` with the `axis` keyword enough?

@eendebakpt, thank you for the question! When using `unique` with the `axis` keyword, the function treats entire subarrays along the specified axis as unique elements. This means that, rather than evaluating the uniqueness of individual values, it considers the structure and content of the entire subarray. I propose introducing functionality that counts each individual element in an n-dimensional array along a specified axis, while preserving the structure of the remaining dimensions.

Let me know if anything remains unclear!

**Comment by Mark799** [comment]
> The `unique_2d` functionality can perhaps be implemented using `np.unique`. 
> (...)

Thank you for your suggestion, @eendebakpt. My intention is indeed to enhance the functionality of the original `unique` function rather than develop an entirely new one. That said, there are a few limitations to your proposal that I’d like to address:

- It does not preserve the original shape of the input array.
- It lacks the ability to count over a specific axis.

My goal is to vectorize the original `unique` function while addressing these considerations.

**Comment by Mark799** [comment]
Hi @rgommers, as a maintainer, I’d greatly appreciate your feedback on the code. Could you share your thoughts on the following?

1. How do you feel about the added functionality? (see also my other comments for clarification)
2. What’s your opinion on the way it is currently implemented?

**Comment by jakevdp** [comment]
Hi @Mark799 – reading this, I'm still confused about the exact functionality you propose to add. In particular, how do you return an array of unique values along an axis when each sub-array has a different number of unique values? Do you propose having some kind of fill value? Would that fill value be user-configurable?

Perhaps it would be useful to give a few example inputs, example function calls, and example outputs for the API you have in mind.

**Comment by Mark799** [comment]
> Hi @Mark799 – reading this, I'm still confused about the exact functionality you propose to add. In particular, how do you return a single array of unique values along an axis when each sub-array may have a different number of unique values? Do you propose having some kind of fill value? Would that fill value be user-configurable?
> 
> Perhaps it would be useful to give a few example inputs, example function calls, and example outputs for the API you have in mind.

Hi @jakevdp, thank you for the inquiry. To answer your questions: the function determines the unique values of the array as a whole, before counting the appearances in each row. The total number of a specific unique value appearing in a specific row could also be 0, as it may not appear in it. I am not sure what you mean with 'fill value', but ideally the unique elements could also be user-defined, where the function only needs to count the appearance of those. 

The goal is to determine the unique values of the array as a whole and count these in each list of an n-dimensional array. (I've changed this in my first comment.)

The docstring already contains two examples. But I will add some more here.

Example 1: 2D numpy array.
`array` contains 4 unique elements: `1, 2, 3, 4`. The first row contains the first three unique elements exactly once, but not the last one, so the first array of the output becomes `[1, 1, ,1, 0]`. The second row contains the first unique elements 3 times, so the second array of the output becomes: `[3, 0, 0, 0]`. The last array contains twice the element 3, and once the element 4, so the output becomes `[0, 0, 2, 1]`.

```
>>> array = np.array([[1, 2, 3],
>>>                   [1, 1, 1],
>>>                   [4, 3, 3]])
>>> unique_2D(array)

(array([1, 2, 3, 4]),
 array([[1, 1, 1, 0],
        [3, 0, 0, 0],
        [0, 0, 2, 1]]))
```

Example 2: n-dimensional numpy array
`array` consists of random numbers between 0 and 10, with shape `(500, 400, 60)`. The unique elements are `0, 1, 2, 3, 4, 5, 6, 7, 8, 9`. All but the last dimensions are preserved, in this case: `(500, 400, ...)`, the last dimension becomes the length of the unique elements, in this case: 10. The shape that is returned is `(500, 400, 10)`. The sum of the last axes always equals 60, as there are 60 elements in each of the input array. 
```
>>> array = np.random.randint(0, 10, (500, 400, 60))
>>> values, count = unique_2D(array)
>>> values
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>>> count[0, 0]
array([ 7,  7,  2,  7,  3,  7,  5, 10,  8,  4])

>>> count.shape
(500, 400, 10)

>>> count.sum(axis = -1)
array([[60, 60, 60, ..., 60, 60, 60],
       [60, 60, 60, ..., 60, 60, 60],
       [60, 60, 60, ..., 60, 60, 60],
       ...,
       [60, 60, 60, ..., 60, 60, 60],
       [60, 60, 60, ..., 60, 60, 60],
       [60, 60, 60, ..., 60, 60, 60]])
```

**Comment by rgommers** [comment]
Okay, so what you want is almost the same as `unique`, except the `return_counts` return value is per row rather than in total. To compare your first example:
```python
>>> x = np.array([[1, 2, 3],
...               [1, 1, 1],
...               [4, 3, 3]])
>>> np.unique(x)  # this yields the same as your unique_2d
array([1, 2, 3, 4])
>>> np.unique(x, return_counts=True)  # second return value is global rather than per row 
(array([1, 2, 3, 4]), array([4, 1, 3, 1]))
```

This seems a little too niche and doesn't generalize nicely from 2-D to n-D. I'm not sure if there's a vectorized way to construct the per-row counts in pure Python/NumPy, but this should be easy to do with a for-loop or a bit of Cython code.

**Comment by Mark799** [comment]
> Okay, so what you want is almost the same as `unique`, except the `return_counts` return value is per row rather than in total. To compare your first example:
> 
> ```python
> >>> x = np.array([[1, 2, 3],
> ...               [1, 1, 1],
> ...               [4, 3, 3]])
> >>> np.unique(x)  # this yields the same as your unique_2d
> array([1, 2, 3, 4])
> >>> np.unique(x, return_counts=True)  # second return value is global rather than per row 
> (array([1, 2, 3, 4]), array([4, 1, 3, 1]))
> ```
> 
> This seems a little too niche and doesn't generalize nicely from 2-D to n-D. I'm not sure if there's a vectorized way to construct the per-row counts in pure Python/NumPy, but this should be easy to do with a for-loop or a bit of Cython code.

@rgommers thank you for the reply. Indeed, the proposed function's return value is per row rather than in total. What do you mean with it "doesn't generalize nicely from 2-D to n-D"?

You say it "seems a little too niche" and "the per-row counts (...) should be easy to do with a for-loop or a bit of Cython code". Do I understand from this that you think this functionality should not be added?

**Comment by rgommers** [comment]
> What do you mean with it "doesn't generalize nicely from 2-D to n-D"?

You hardcode the implementation to be 2-D and per row. What if someone needs the count per column, or a count per 2-D block over a 3-D array? The implementation is too specific to allow for that.

> Do I understand from this that you think this functionality should not be added?

Yes, that is correct. Per-row counts is not useful enough to warrant a new function in NumPy. If anyone needs this (should be rare), it's 4 lines of code to implement in their own code base.

**Comment by eendebakpt** [comment]
@Mark799 I agree with rgommers reasoning for not adding this to numpy. But since you asked for feedback on the implementation:

* The code and docstring looks good. For other features we would welcome such contributions!
* One thing your implementation does not address (and which the `np.unique` does handle) is nan. For example:
```
x = np.array([[1, 2, 3], [1, 2, np.nan], [3, 3, 3]])
r = unique_2D(x)
print(r) # does not count nan
r = np.unique(x, return_counts=True)
print(r) # does count nan
```
Depending on the use case that might be ok or not.

**Comment by Mark799** [comment]
Thank you @rgommers and @eendebakpt for the feedback. 

If I understand it correctly, the code quality is good, but the added feature is not desired in Numpy. That leaves me with a few questions:

**1. How do I know if a feature is useful?** 
I understand the niche part, where not many people may be using it, but (simple versions of) many numpy functions can be recreated using a few lines of code. Even (a simple implementation) of the `np.unique()` function can be recreated using `np.sort()` and `np.diff()`. So, how can this be assessed?

**2. Is there a list of desired functionality?** 
I have checked the issues, but found no 'new feature requested' label. Does this exist?

**Comment by seberg** [comment]
Going to close this, since I also agree that this function seems a bit too niche.

FWIW, the better way to implement this function is to use the `return_inverse` and then use `np.add.at()` (bincount doesn't support axis):
```
..., inverse = unique(a, axis=None, return_inverse=True)

assert a.ndim == 2  # can generalize, but more complex
counts = np.zeros_like((a.shape[0], n_unique), dtype=np.intp)
np.add.at(counts, (np.arange(a.shape[0], inverse)))
```
`np.add.at` may be very slow in this usage so making a loop will be much better unless `n_unique` is pretty small.

**Comment by rgommers** [comment]
@Mark799 to answer your questions: there's no formulaic answer, so asking by opening a new issue is usually a good way to go about it if it seems like a good idea to you and is [in scope](https://numpy.org/neps/scope.html) for NumPy in principle.

There is a roadmap for big picture topics (https://numpy.org/neps/roadmap.html), and for individual functions there are only feature requests in issues in this repo.

**Pull request closed without merging**
