### PR TITLE
ENH,BUG: Expand the experimental DType API and fix small exposed issue

### PR DESCRIPTION
**Pull request by seberg**
Aside from one little bug fix (which is almost impossible to trigger from within NumPy apparently, but we could backport it if we want), this exposes some new API to the experimental DType API.  Testing is not provided, even superficial use of https://github.com/seberg/unitdtype will test it reasonably well, I think.

There are a few things here:
* A simple bug fix
* Maintanence: Marking the `strides` (fixed strides) as `const` in `get_loop` 
* Experimental DType API enhancements:
  * Small fixups
  * Enable multi-file support when `UNIQUE_SYMBOL` is used (a bit clunky, but works...)
  * Expose the builtin DTypes for ease of use.
  * Allow using `_get_loop`, yes, I don't like the signature.  But at the end of the day, this is a useful API even if we should eventually replace it.
  * Adds a "wrapping-array method" to allow wrapping an existing UFunc for operands of a _different_ dtype.  This is specifically useful for physical Units, but allowing to do it externally requires settling more API than I like.  Eventually, we should maybe do that very slowly (i.e. deprecate this after it can be moved out).  But for now this is OK, and experimental anyway.

The big chunk here is really that "wrapping array method", which adds a whole new file (and some stuff into `ArrayMethod` itself, as I did not feel like making a proper subclass for it).  The user-facing API is fully opaque, so the implementation could be changed completely.

I would like to "just move ahead" here.  There are really only serious changes for the experimental DType API here.

### CODE REVIEW

**Comment by seberg** [comment]
That "wrapping" stuff is actually described in NEP 43, although very mildly differently (e.g. different names).

**Comment by seberg** [comment]
@mattip, unless anyone would like to bikeshed the experimental API choice of `PyUFunc_AddWrappingLoop`, I think this is ready to just go in.

**Comment by mattip** [comment]
Maybe break out the bug fix and the const additions into a separate PR?

**Comment by seberg** [comment]
Split out, will have to rebase once those are in.

> Expands a "wrapping-array method" to allow wrapping an existing UFunc for operands of a different dtype

Should be `Adds a` or "Expands the experimental API by ...".  The idea is mentioned in NEP 43, although the specifics are slightly different.  But then the NEP never specifies a C-API, just a python mockup, so they are bound to be different anyway.

> Also: is DType->singleton critical for now or can we leave it for later?

Our DTypes all have it, it seemed reasonable to allow direct access, also because it is typical to have a default (i.e. very few DTypes will not have one).  So it is not strictly necessary, but it was a small convenience in the Unit DType prototype to provide it.

**Comment by mattip** [comment]
Thanks @seberg.

**Comment by mattip** [comment]
Never mind, this is fine like it is.

**Pull request merged**
