### PR TITLE
API: Update `lib.polynomial` and `lib.npyio` namespaces

### PR DESCRIPTION
**Pull request by mtsokol**
Relevant issue https://github.com/numpy/numpy/issues/24507

Hi @rgommers @ngoldbaum,

This PR moves `lib.polynomial` and `lib.npyio` modules to private files and ensures that their public methods are only available through the main namespace. For `lib.npyio` there are two objects available from local namespace (they were used this way in docs and codebase) so for `npyio` there are `_npyio_impl.py` and `npyio.py` (and this is also the reason why so many lines changed - contents of `npyio.py` were moved to `_npyio_impl.py`).

### CODE REVIEW

**Comment by ngoldbaum** [comment]
For future reference, it's a little easier to review renames if you make the rename a single commit and then subsequent edits to the file their own commit.

It looks like the two symbols this keeps in `lib.npyio` are `BagObj` and `NpzFile`. Both probably need to be public somewhere and `np.lib.npyio` is as good a place as any and has the benefit being where they publicly live now. 

Given that this PR proposes keeping `np.lib.npyio`, It might make sense to deprecate (or just out-and-out move, since it's not used much) `DataSource`'s location in the main namespace and move it to `np.lib.npyio` along with these two classes.

Can you add `BagObj` to the listing in `doc/source/reference/routines.io.rst`, along with `NpzFile`?

This removes 22 symbols from `np.lib.__all__`, all of them are in the main namespace:

```
In [5]: print(set(oldall) - set(np.lib.__all__))
{'save', 'polyint', 'poly1d', 'genfromtxt', 'polyadd', 'DataSource', 'savez_compressed', 'polyfit', 'savez', 'polymul', 'polysub', 'packbits', 'poly', 'roots', 'fromregex', 'loadtxt', 'load', 'polyval', 'unpackbits', 'polydiv', 'polyder', 'savetxt'}

In [6]: diff = set(oldall) - set(np.lib.__all__)

In [7]: diff.issubset(np.__all__)
Out[7]: True

```

**Comment by mtsokol** [comment]
> Given that this PR proposes keeping `np.lib.npyio`, It might make sense to deprecate (or just out-and-out move, since it's not used much) `DataSource`'s location in the main namespace and move it to `np.lib.npyio` along with these two classes.

Sure! `DataSource` is originally available in `np.lib.npyio` so I only removed it from the main namespace and added expiration message, where to find it now.

> Can you add `BagObj` to the listing in `doc/source/reference/routines.io.rst`, along with `NpzFile`?

`NpzFile` is already there, in the "NumPy binary files" section. I added `BagObj` to a new "Object wrappers" section.

**Review by ngoldbaum — APPROVED** [review]

**Review by rgommers — COMMENTED** [review]
This looks good to me overall. My one question is why we'd want to make `BagObj` public? It doesn't seem like a thing that anyone should be using, nor can I find any interesting usage in the wild with code search right now.

**Comment by ngoldbaum** [comment]
> nor can I find any interesting usage in the wild with code search right now

Hmm, for some reason I thought I saw some when I searched the other day but can't find any now. Sorry for the mistaken suggestion!

The only public usage I can find outside of numpy is [here](https://github.com/orzuk/OEIS/blob/fdd264ebb4d95f1556dc6285fb6af290de789fed/src/parse_seqs_names.py#L5) and it's not even used in that file.

Given this level of usage I agree with Ralf there's no reason to add it to the docs, it's probably safe to just delete it since it has no internal consumers. Maybe add a custom `AttributeError` message if someone tries to directly access it that encourages people to copy/paste the old implementation if they do need it, it's less than 20 lines of non-comment code.

**Review by rgommers — APPROVED** [review]
All looks good to me now, let's get this in. The one CI failure is a network error - the Anaconda scientific-python bucket is struggling today.

**Pull request merged**
