### PR TITLE
DOC: Update the f2py section of the "Using Python as Glue" page.

### PR DESCRIPTION
**Pull request by sibasmarak**
Updated the f2py section of the "Using Python as Glue" page.

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
Thanks for the contribution! It would be great if you could edit the description and title of this PR to summarize the change - it means maintainers don't need to think of a commit message themselves.

**Comment by sibasmarak** [comment]
Sure @eric-wieser . Thanks for pointing out!

**Comment by WarrenWeckesser** [comment]
Thanks @sibasmarak!  But you should know that I already submitted a PR that includes these changes and a few more in https://github.com/numpy/numpy/pull/16257

**Comment by sibasmarak** [comment]
Thanks, @WarrenWeckesser ! Actually I just saw your contribution after I made my PR. I am actually new to open source. I have no idea how to proceed, I stumbled upon this and just made a PR. I am slowly realizing a systematic way to do a PR, and what to check before a PR. Thanks!

**Comment by WarrenWeckesser** [comment]
We don't have a policy of always assigning an issue to someone, nor do we regularly self-assign when we start preparing a pull request for an issue.  Indeed, we often tell people who ask permission to work on an issue that there is no need to ask, just go ahead an work on it.  This is rarely a problem, especially with an issue that is only a few hours old!

Occasionally when I start working on an issue, I'll make a comment in the issue that I'm preparing a fix, but I don't do that consistently, and I didn't do it in this case.  I'll start making such comments all the time now.

Having said all that: once I've figured out what is going on with the CI tests, I'll merge this PR, and make my additional changes in a follow-up PR.

**Comment by WarrenWeckesser** [comment]
@sibasmarak, thanks again for your first contribution!  I added a few more details to the commit message when I merged the PR.

**Pull request merged**
