### PR TITLE
MAINT: Update setup.py for Python 3.11.

### PR DESCRIPTION
**Pull request by charris**

### CODE REVIEW

**Comment by charris** [comment]
I'm not sure if we should do this for the first rc release, or wait until Python 3.11.0 is released.

**Comment by mattip** [comment]
I guess it depends how close to [the scheduled Oct 3 release](https://peps.python.org/pep-0664/#release-schedule) you publish 1.23.3.

**Comment by charris** [comment]
Let's get @rgommers take on this.

**Review by rgommers — APPROVED** [review]
Thanks @charris. This is in `main` and we will definitely have 3.11 wheels well before 1.24.0 is released, so this looks correct to me. People will start developing with 3.11 now, so we shouldn't raise warnings for it.

**Comment by rgommers** [comment]
Whether it needs to be backported to 1.23.3: I'd say yes, since we have wheels up already.

**Pull request merged**
