### PR TITLE
[WIP] Continue testing with new version of sphinx theme

### PR DESCRIPTION
**Pull request by Shekharrajak**
Continuation of https://github.com/numpy/numpy/pull/14494

- Latest sphinx version is used
- Search box is working fine with new version. Custom template of searchbox is removed in this PR.
- imgmath_image_format is not needed, since new theme is directly using the script of mathjs .
- edit on github button added

Related PRs: https://github.com/Shekharrajak/scipy-sphinx-theme-v2/pull/42

Working copy: 
* http://generated-numpy-docs-14648-3-sphinx2.surge.sh/
* http://generated-numpy-docs-14648-2-sphinx2.surge.sh/
* http://generated-numpy-docs-14648-sphinx2.surge.sh
* http://generated-numpy-docs-28-sphinx2.surge.sh/

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Generated the docs using `grunt --project=docs`

and deployed using  surge --project doc/source/build/ --domain generated-numpy-docs-28-sphinx2.surge.sh

 deployed at http://generated-numpy-docs-28-sphinx2.surge.sh

**Comment by Shekharrajak** [comment]
I keep testing the new theme using this branch. So it must be open for now.

**Comment by Shekharrajak** [comment]
It will be helpful if someone helps me resolving CI/CD failure.

**Comment by rgommers** [comment]
I think the warnings need resolving.

For this one I think it's just doing what the warning says:
```
/home/circleci/repo/doc/scipy-sphinx-theme-v2/custom_sphinx_theme/scripts.html:29: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {% endif %}
/home/circleci/repo/doc/scipy-sphinx-theme-v2/custom_sphinx_theme/scripts.html:29: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {% endif %}
```


Here we want to be using MathJax instead of `pngmath` I believe:
```
WARNING: dvipng command 'dvipng' cannot be run (needed for math display), check the imgmath_dvipng setting
```
This is configured in `doc/source/conf.py`.

**Comment by Shekharrajak** [comment]
Thanks @rgommers ! Working on it.

**Comment by Shekharrajak** [comment]
Finally all green 🎉

**Comment by Shekharrajak** [comment]
NEPs doc generated using `SPHINXOPTS=-q make -e html` in doc/neps folder and demo link is : http://generated-numpy-neps-sphinx2.surge.sh/

**Comment by Shekharrajak** [comment]
latest devdoc after these changes : generated-numpy-docs-14648-sphinx2.surge.sh

**Comment by rgommers** [comment]
Looking at most pages on a 13" screen, the sidebar is shifting to below all content rather than on thee right side:

image

For the reference guide pages on individual functions, the right sidebar is anyway empty:

image


Should we get rid of the right sidebar?

Other than that it looks quite good! I think we can upload this onto the doc server, which is nicer to test on than Surge. Then point more people at it:)

**Comment by Shekharrajak** [comment]
> Looking at most pages on a 13" screen, the sidebar is shifting to below all content rather than on thee right side:
> 
> image
> 

Thanks for the review. I am looking into it. It will be helpful if you can paste the link as well so that I can see the page in different device size and work on it. 


> For the reference guide pages on individual functions, the right sidebar is anyway empty:
> 
> image
> 
> Should we get rid of the right sidebar?

Yeah! If there are no headers/subheaders on that page then it will empty.


> Other than that it looks quite good! I think we can upload this onto the doc server, which is nicer to test on than Surge. Then point more people at it:)

Yeah sure. We can put the build inside folder (may be folder name is `beta` for the URL numpy.org/doc/beta . Should I create a PR for that in numpy/doc repo ?

**Comment by Shekharrajak** [comment]
I fixed this issue in new commit and build : generated-numpy-docs-14648-2-sphinx2.surge.sh

**Comment by Shekharrajak** [comment]
New demo link after few fixes: http://generated-numpy-docs-14648-3-sphinx2.surge.sh/

**Comment by mattip** [comment]
Definitely an improvement. A few quick thoughts: 

When I click on [a link](http://generated-numpy-docs-14648-3-sphinx2.surge.sh/dev/index.html), the page is aligned to the left-navbar's highlighted item rather than to the top of the page. 

Has the (left navbar site TOC) + (right navbar page TOC) concept been discussed? Traditionally I am used to the page TOC expanding out of the site TOC rather than appearing on a separate navbar.

The top menu has a gap of white space between the logo and the "Quick Start" 

Maybe it is an artifact of using surge.sh, but the footer links are not correct.

**Comment by Shekharrajak** [comment]
New generated numpy docs using the new commit from the [scipy-sphiinx-theme](https://github.com/scipy/scipy-sphinx-theme-v2) : http://generated-numpy-docs-14648-5-sphinx2.surge.sh/

**Comment by Shekharrajak** [comment]
> Has the (left navbar site TOC) + (right navbar page TOC) concept been discussed? Traditionally I am used to the page TOC expanding out of the site TOC rather than appearing on a separate navbar.

Yeah we have discussed it. I find that most of us don't really need the right sidebar. I think we shoud try to make the same in left sidebar itself.

Thanks for the input and review.

**Comment by charris** [comment]
Ping all. Where does this stand these days?

**Comment by eric-wieser** [comment]
My guess is that we've decided to let pydata handle our theme, since their theme is nice enough and has enough interested maintainers to keep it afloat - meaning this can be closed.

What theme is scipy using?

**Comment by charris** [comment]
> My guess is that we've decided to let pydata handle our theme

That is also my recollection, I'll close this. Thanks @Shekharrajak.

**Pull request closed without merging**
