### PR TITLE
ENH,BUG: Handle includes for meson backend

### LINKED ISSUE #25344: BUG: f2py (3.12) with meson does not support correct include file
### Describe the issue:

When running f2py with python3.12 (so using meson). I do face the following issue:
```
gfortran -Iuntitled.cpython-312-darwin.so.p -I. -I.. -I/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/src -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -Wall -O3 -Juntitled.cpython-312-darwin.so.p -o untitled.cpython-312-darwin.so.p/matrix.f.o -c ../matrix.f
../matrix.f:324:0:

  324 |       include 'coupl.inc'
      |
Fatal Error: Cannot open included file ‘coupl.inc’
compilation terminated.
```

The reason is not the trivial one (I do have such file in the local directory) but the fact that such file is not copy to the meson build directory. Additionally any attempt to provide a path to a directory where such file exists fails 
(either by specifying --include-paths or -I or even the outdated --include_paths). To be precise the failing compilation line is not updated correctly by any of those options.

### Reproduce the code example:

```python
C
      SUBROUTINE DFILTER2D(A,B,M,N)
C
       INCLUDE 'AB.inc' # put the following line inside that file
C      DOUBLE PRECISION A(M,N)
C      DOUBLE PRECISION B(M,N)
      INTEGER N, M
CF2PY INTENT(OUT) :: B
CF2PY INTENT(HIDE) :: N
CF2PY INTENT(HIDE) :: M
      DO 20 I = 2,M-1
         DO 40 J = 2,N-1
            B(I,J) = A(I,J) +
     &           (A(I-1,J)+A(I+1,J) +
     &           A(I,J-1)+A(I,J+1) )*0.5D0 +
     &           (A(I-1,J-1) + A(I-1,J+1) +
     &           A(I+1,J-1) + A(I+1,J+1))*0.25D0
 40      CONTINUE
 20   CONTINUE
      END
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/f2py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 732, in main
    run_compile()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 705, in run_compile
    builder.compile()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 131, in compile
    self.run_meson(self.build_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 124, in run_meson
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['meson', 'compile', '-C', 'bbdir']' returned non-zero exit status 1.
```

### Python and NumPy Versions:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.2
3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]

### Runtime Environment:

[{'numpy_version': '1.26.2',
  'python': '3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 '
            '(clang-1300.0.29.30)]',
  'uname': uname_result(system='Darwin', node='mac-1q0-072.local', release='22.1.0', version='Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'armv8',
  'filepath': '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None

### Context for the issue:

This is a blocker for supporting python3.12 for the moment so not directly critical.

### PR DESCRIPTION
**Pull request by HaoZeke**
Closes #25344. Supersedes #25345. ~~Tests need to be reworked to use `option` correctly. Draft till then.~~

@oliviermattelaer could you check if this also works for you?

For reviewers:
- Implements `includes` in the `meson` backend in a manner consistent with the `-L -l` handling since https://github.com/numpy/numpy/pull/25297.
- Unifies the disparately handled `--include-paths` `--include_paths` and `-I` to do the "right thing" (which is also now thankfully the same thing)
  - Previously, the code would diverge since `-I` would be a "compiler" option and the others were not, now they all generate the same code

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
sure will do (but later today).

Thanks,

olivier

On 11 Dec 2023, at 13:41, Rohit Goswami ***@***.***> wrote:


Closes #25344<https://github.com/numpy/numpy/issues/25344>. Supersedes #25345<https://github.com/numpy/numpy/pull/25345>. Tests need to be reworked to use option correctly. Draft till then.

@oliviermattelaer<https://github.com/oliviermattelaer> could you check if this also works for you?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/numpy/numpy/pull/25364

Commit Summary

  *   f83e066<https://github.com/numpy/numpy/pull/25364/commits/f83e0661682b0f858d29ec3e1b706ad26fc608a1> TST: Add a test for inclusion of files
  *   679eabe<https://github.com/numpy/numpy/pull/25364/commits/679eabefb5ae721da00d22a895c77a9d0242ab00> ENH: Handle includes in meson [f2py]
  *   4977bd2<https://github.com/numpy/numpy/pull/25364/commits/4977bd28a43a8e5fc1809018ddcd2bd6ebd90405> ENH: Handle includes consistently across f2py

File Changes

(6 files<https://github.com/numpy/numpy/pull/25364/files>)

  *   M numpy/f2py/_backends/_meson.py<https://github.com/numpy/numpy/pull/25364/files#diff-c01087e39278f6d9fa6075370ad8729923ebce00c5679c5e4ac287157196d9b6> (21)
  *   M numpy/f2py/_backends/meson.build.template<https://github.com/numpy/numpy/pull/25364/files#diff-c022b6feb70dbbdfa41e222d73c4fb8e56e7ff9acd8b875001f5da559d593d8b> (5)
  *   M numpy/f2py/f2py2e.py<https://github.com/numpy/numpy/pull/25364/files#diff-3f84592a30e3a8ae9502c8905fea187a0056e221976dae55852d01471771fab3> (57)
  *   A numpy/f2py/tests/src/regression/AB.inc<https://github.com/numpy/numpy/pull/25364/files#diff-1746d50713ce235461280263ce77de3022848e06ed0391928a7d36f0b316f98e> (1)
  *   A numpy/f2py/tests/src/regression/incfile.f90<https://github.com/numpy/numpy/pull/25364/files#diff-28f38f20625beba52f9ec77f1556710e0ad3230c8c59e30afd1a946950019980> (5)
  *   M numpy/f2py/tests/test_regression.py<https://github.com/numpy/numpy/pull/25364/files#diff-b50b12179caec30bd22a1ee49e3ad18f22e39ddab88e2291ed43bbcda4dd3e00> (12)

Patch Links:

  *   https://github.com/numpy/numpy/pull/25364.patch
  *   https://github.com/numpy/numpy/pull/25364.diff

**Comment by oliviermattelaer** [comment]
@HaoZeke, yes it does fix the issue if I specify include-paths options.

However, if I do not it does crash with 
```
    [f"{indent}'{inc}'" for inc in self.include_dirs]
TypeError: 'NoneType' object is not iterable
make: *** [matrix2py.so] Error 1
```
which is likely not what you expect (and likely one reason for the CI to fail)

**Comment by HaoZeke** [comment]
@oliviermattelaer thanks, I think the latest patchset should be good to go if it works for you.. Tests are now passing

**Comment by oliviermattelaer** [comment]
Yes does work for me. Thanks a lot,

Olivier

**Comment by mattip** [comment]
Thanks @HaoZeke

**Comment by charris** [comment]
Going to forgo this backport for 1.26.4.

**Pull request merged**
