### PR TITLE
BUG: Fixed Bug #25744 - np.put on empty array does not raise error

### PR DESCRIPTION
**Pull request by Chris2Rich**
BUG: Fixed Bug #25744 - np.put on empty array does not exit

Fixed by adding if statement to check if size of array is 0. If size is 0 then error is raised, else control flow resumes.

### CODE REVIEW

**Comment by Chris2Rich** [comment]
have no clue why BLAS tests failed need help with that tbh

**Comment by seberg** [comment]
> have no clue why BLAS tests failed need help with that tbh

Thanks, Just ignor it.   However, it would be good (and necessary actually) to test this on the C side (goes through `methods.c` but the actual implementation may be elsewhere).  We also do need a test.

**Comment by Chris2Rich** [comment]
added C implementation

**Comment by Chris2Rich** [comment]
fixed all bugs with simple changes - only made 10 commits because compilation errors on my machine

**Comment by ngoldbaum** [comment]
For whatever reason, the new error is being triggered by a test that does `a = np.zeros((5, 5, 0)); a.put(100, 0)`. The test checks if you get an `IndexError`, and it's failing because now it's seeing `ValueError`. I don't understand why the test is triggering your new error, it probably shouldn't be.

**Comment by Chris2Rich** [comment]
> > have no clue why BLAS tests failed need help with that tbh
> 
> Thanks, Just ignor it. However, it would be good (and necessary actually) to test this on the C side (goes through `methods.c` but the actual implementation may be elsewhere). We also do need a test.

will this be reviewed?

**Comment by ngoldbaum** [comment]
> will this be reviewed?

The tests are failing, generally people don't look closely at PRs with failing tests.

In any case, closing in favor of #25975.

**Pull request closed without merging**
