### PR TITLE
BUG: Fix misuse of .names and .fields in various places

### PR DESCRIPTION
**Pull request by eric-wieser**
Easiest to review commit-by-commit.

Done with the 1.16.x branch point as its base, so it can be easily backported to either 1.16 or 1.17 if desired

### CODE REVIEW

**Comment by eric-wieser** [comment]
Debug segfault was not something I expected from a python only change...

**Comment by pv** [comment]
pytest 5.1.0 segfaults on python3.5-dbg

**Comment by eric-wieser** [comment]
Is there a tracking issue for that?

**Comment by charris** [comment]
close/reopen

**Comment by eric-wieser** [comment]
Had to remove a change because it's test ran into gh-13438. I'll push the follow-up commit once this goes in, and leave it with a CI failure until we fix gh-13438.

**Comment by ahaldane** [comment]
LGTM. There are probably still things broken with zero-field dtypes, eg perhaps the view issue from #14310, but its good to fix all these.

**Comment by charris** [comment]
@ahaldane Do you think this should go in before your fixes?

**Comment by eric-wieser** [comment]
I don't think it matters, this doesn't overlap in its current form.

**Comment by charris** [comment]
@eric-wieser If you are happy with this I'll go ahead and merge. Looks like it might close some issues, are they included in the commit messages?

**Comment by eric-wieser** [comment]
I haven't found any issues this will close yet - they're deep enough corner cases they were probably never reported.

If you put this in, I'll kick off backport PRs for 1.16 and 1.17 tonight (assuming you want both)

**Comment by charris** [comment]
@seberg has marked this for his review, so I'll wait on that.

**Review by seberg — APPROVED** [review]
LGTM, pretty deep corner case, I guess. Not too surprising that there are no issues about it...

EDIT: I think this is good for backport (not that it is likely that many users will actually stumble over it).

**Comment by charris** [comment]
@eric-wieser Merged.

**Pull request merged**
