### PR TITLE
TST: Re-enable test display on appveyor

### PR DESCRIPTION
**Pull request by eric-wieser**
The .appveyor.yml expects this file to exist, but pytest does not output it by default.

Let's see if this works...

### CODE REVIEW

**Comment by pv** [comment]
Please add this to appveyor.yml rather than numpy.test()
cf https://github.com/scipy/scipy/blob/master/appveyor.yml#L170
I guess the same works with numpy's runtests

**Comment by eric-wieser** [comment]
This works as intended: 

image

**Comment by charris** [comment]
Hmm, I never saw a problem here. I assume that is because I own the appveyor tests ...

**Comment by charris** [comment]
Thanks Eric.

**Comment by eric-wieser** [comment]
What do you mean you never saw a problem? After the pytest switch, the test numbers (4671 etc) stopped showing up.

**Pull request merged**
