### PR TITLE
MAINT: CI: Add an explicit 'pr' section to azure-pipelines.yml

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Azure-pipelines is currently experiencing an "incident":

    https://status.dev.azure.com/_event/179641421)

From that web page:

> Currently CI and PR triggers in YAML for GitHub and Bitbucket
> repositories are not working when they are not explicitly listed
> in the YAML file. Our expected behavior is that when there are
> no explicit triggers in the YAML, the pipelines will trigger on
> all commits on all branches and all pull requests. This is
> currently not happening. To workaround, please explicitly list
> the triggers you want in the YAML file for your pipeline.

This PR adds the suggested explicit 'pr' triggers to the YAML file.

### CODE REVIEW

**Comment by mattip** [comment]
As long as you are into CI, could you restore the [apt update](https://github.com/numpy/numpy/blob/v1.18.1/tools/pypy-test.sh#L9) line above the `apt install` which might fix that build.

**Comment by mattip** [comment]
xref gh-15328, which seemed to have removed that line. Apparently it was not needed until lately when the builds started failing

**Comment by WarrenWeckesser** [comment]
@mattip, good idea, looks like that worked.

**Comment by WarrenWeckesser** [comment]
Azure pipelines ran, and all tests pass, including Linux PyPy3.

**Comment by rgommers** [comment]
Let's get it in then! Thanks @WarrenWeckesser and @mattip

**Pull request merged**
