### PR TITLE
Draft: [BUG] Fix Polynomial representation tests

### PR DESCRIPTION
**Pull request by eendebakpt**
Fix tests for Polynomial representation methods.

Fixes regression from #21760

### CODE REVIEW

**Comment by eendebakpt** [comment]
@mattip Tests are passing now. Currently the formatting of the domain-window mapping is not entirely consistent with how the polynomial is displayed. For example in unicode mode:
```
0.0 + 1.0·(-3.0 + 2.0x)
```
Note that usage of `·` in the multiplication, but the term `2.0x` (and not `2.0·x`). 

I can address that as well, but it will take a little bit more time. If this regression is blocking other PRs we can also merge this and address the consistent formatting later.

**Comment by rgommers** [comment]
> I can address that as well, but it will take a little bit more time. If this regression is blocking other PRs we can also merge this and address the consistent formatting later.

I haven't followed along here, but +1 for merging now and dealing with the rest later if this indeed fixes a problem. Any test failure is going to block uploading nightlies, which is needed before we can fix pandas & co.

**Comment by mattip** [comment]
Merging to unbreak the test. @rossbar do you have an opinion about the remaining doubts?

**Comment by mattip** [comment]
I opened #25957 about the address sanitizer failure, it is certainly not due to this PR.

**Comment by rossbar** [comment]
> do you have an opinion about the remaining doubts?

No, I think the intent is clear either way - whatever @eendebakpt prefers seems good to me!

**Pull request merged**
