### PR TITLE
TST: add unit test for issctype

### PR DESCRIPTION
**Pull request by tylerjereddy**
Add a unit test for [uncovered](https://codecov.io/gh/numpy/numpy/src/master/numpy/core/numerictypes.py#L191) `issctype`.

### CODE REVIEW

**Comment by charris** [comment]
Can this be made part of another test? Having lots of small tests that cover corner cases coult get out of hand...

**Comment by tylerjereddy** [comment]
Yeah, I thought 1:1 mapping between a NumPy function and a unit test was reasonable, if not desirable. Stefan wants me boosting % coverage more so will probably be opening similar PRs more frequently. I guess if that exposes things that need to be deprecated that's useful too.

**Comment by charris** [comment]
If this is the only test for issctype I don't have a problem, I was hoping there was a larger test  to which it could be added...

**Comment by charris** [comment]
Thanks Tyler.

**Pull request merged**
