### PR TITLE
ENH: turn quicksort into introsort

### PR DESCRIPTION
**Pull request by juliantaylor**
Introsort is regular quicksort but changing to a heapsort when not
enough progress is made. This retains the good quicksort performance
while changing the worst case runtime from O(N^2) to O(N*log(N))

### CODE REVIEW

**Comment by juliantaylor** [comment]
another improvement one could do is use a good 3way partitioning scheme for integer sorts, the current simple partition does N swaps on equal elements.

**Comment by charris** [comment]
Need to fix the worst case at line 753 in `fromnumeric`.

**Comment by charris** [comment]
> good 3way partitioning scheme

Java adopted dual-pivot quicksort, which looks to do better. The simplicity of the basic quicksort has a certain attraction.

**Comment by juliantaylor** [comment]
my though in not changing it was older numpy versions still have the worst case, and the worst case maybe includes an older numpy than the user expected ;)
but that is probably a bit overly conservative

**Comment by charris** [comment]
Maybe put a footnote on it and explanation about versions? I'm not sure on what the markup should be.

**Comment by charris** [comment]
Thanks Julian.

**Comment by pv** [comment]
fwiw https://pv.github.io/numpy-bench/#regressions?sort=1&dir=desc (best case seems worse --- also, the sort benchmarks in bench_function_base.py seem a bit silly as they only test this)

**Comment by juliantaylor** [comment]
hm I'm a moron, didn't translate the recursion to iterative properly ...

**Comment by juliantaylor** [comment]
https://github.com/numpy/numpy/pull/7871 should fix it, thanks for checking the benchmarks

**Pull request merged**
