### PR TITLE
DEV: Update ``spin`` usage in NumPy (prototype)

### PR DESCRIPTION
**Pull request by czgdp1807**
https://github.com/scipy/scipy/pull/21674
https://github.com/scientific-python/spin/pull/238

### CODE REVIEW

**Comment by mattip** [comment]
Without further comments specific to NumPy, I understand we should wait for resolution of the related scipy/scipy and scientific-python/spin PRs to be resolved before looking at this one. Should we mark it as "draft" until then?

**Comment by ngoldbaum** [comment]
https://github.com/scientific-python/spin/issues/242 and https://github.com/scientific-python/spin/pull/241 are also related. What I'd really like is if we could simply delegate to upstream, adding the one argument we want to add, without needing to update our `spin build` command every time something changes in `spin`.

**Comment by charris** [comment]
Note that spin should not be used to generate the changelog and update the notes, those are both part of the release preparation, not the document generation.

**Comment by rgommers** [comment]
This seems reasonable once the linked `spin` PR lands, but it doesn't do anything extra yet, it just adds the support code to be able to pass arguments to `meson compile` and `meson install`. So I'd put this on hold until it's actionable, and then add some new feature that uses that added flexibility.

> Note that spin should not be used to generate the changelog and update the notes, those are both part of the release preparation, not the document generation.

@charris `spin` is a UX for development tasks (and that can/does include recurring release tasks), and it already has `spin changelog` and `spin notes` tasks, so I'm not sure what your comment is referring to. There's nothing in this PR that changes anything here.

**Comment by czgdp1807** [comment]
Closing this PR. This change should be inside `spin` and not here. I will give some context shortly.

**Comment by czgdp1807** [comment]
Regarding context please see my explanation in https://github.com/scientific-python/spin/pull/238#issue-2571022366

**Pull request closed without merging**
