### PR TITLE
Update 7525, DOC: Fix order='A' docs of np.array.

### PR DESCRIPTION
**Pull request by charris**
Update #7525, Fix order='A' docs of np.array

### CODE REVIEW

**Comment by charris** [comment]
Thanks @MechCoder .

**Comment by charris** [comment]
@seberg Comments?

**Comment by seberg** [comment]
Thanks, looks fine to me. It is all a bit long and complex, but that is just how things are ;).

**Comment by MechCoder** [comment]
Thanks, sorry I did not have time to follow up

**Pull request merged**
