### PR TITLE
BUG: Align PCG64 random states to a 16-byte boundary.

### PR DESCRIPTION
**Pull request by hawkinsp**
If int128_t variant of the PCG state is used, then the int128_t values must be aligned to 16-byte boundaries. Currently nothing enforces this and sometimes values end up 8-byte aligned, which may crash if SSE/AVX vector instructions are used by the compiler.

Fixes a segmentation fault caused by unaligned accesses with certain versions of clang and certain optimization settings on x86-64 in the existing PRNG tests. There is no new test because there is no externally-visible behavior change.

### CODE REVIEW

**Comment by charris** [comment]
Could you take a look at `PCG64DXSM` as well? It is in the same file.

**Comment by seberg** [comment]
I am curious what Python version this was run on that the sanitizer found a potential issue?  Based on the [commit/bpo](https://github.com/python/cpython/commit/1b85f4ec45a5d63188ee3866bd55eb29fdec7fbf) and [this](https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-4-release-candidate-1) I would expect it is fixed since `python 3.7.4`.  Unless there are 32bit systems with 128bit integers available?  (That is for 3.7+)

If `malloc` itself doesn't provide the 16byte alignment, it doesn't matter.  It is not overly complicated, just a bit surprising its needed.  (Maybe it makes sense to mention malloc or the Python allocator in the comment?)

**Comment by bashtage** [comment]
You could instead use `PyArray_malloc_aligned` which is always aligned on a 16 byte boundary.  If you so this would you need to use the `PyArray_free_aligned`

**Comment by bashtage** [comment]
Do compilers that know this is a `__uint128_t` really not align this?  This is very surprising if true.

https://github.com/numpy/numpy/blob/8b1a65b5294f5c8f69020d73361f92e82c811432/numpy/random/src/pcg64/pcg64.h#L69

**Comment by bashtage** [comment]
Another alternative fix would be to add `__attribute__((aligned(16)))` to the struct here 

https://github.com/numpy/numpy/blob/8b1a65b5294f5c8f69020d73361f92e82c811432/numpy/random/src/pcg64/pcg64.h#L89

**Comment by bashtage** [comment]
Looks like this is relevant

https://reviews.llvm.org/D86310

**Comment by hawkinsp** [comment]
@seberg You've hit the nail on the head. This was Python 3.6, and I saw the bug with NumPy 1.18.5. The issue is that `PyGC_Head` is 24 bytes in Python 3.6, so even if the platform allocator gives a 16-byte aligned block, then a block returned by `Py_GC_Malloc` will be 8-byte aligned only. I verified that the problem does not occur with Python 3.7.

Yes, the compiler knows to align `int128_t` to a 16-byte boundary. But it can only control the offset of the `int128_t` value inside the object, not the base address of the object. That part is up to Python and the allocator.

Since this is only a problem for Python 3.6, we can either backport this fix to NumPy versions < 1.20 or just drop the patch completely. I'm happy either way (since for my personal use case we're expecting to be off Python 3.6 very soon.)

**Comment by seberg** [comment]
We could backport only but it is very unlikely there will be another release unless some serious issue cropped up at least (I don't think we have ever done that in the past decade).

**Comment by hawkinsp** [comment]
Sounds good to me. I'll close this PR; we can reopen and backport if it the need arises.

**Pull request closed without merging**
