### PR TITLE
BUG: Bump Highway to latest master

### LINKED ISSUE #27037: BUG: random segmentation fault in `np.unique` on MacOS (arm64) + numpy 2.0.1
### Describe the issue:

We noticed a regression with numpy 2.0.1 in yt's test suite https://github.com/yt-project/yt/issues/4953, which bisects to gh-26821

This crash (segmentation fault) pops up in a test that use numpy's RNG (seeded), but it is still non-deterministic: it doesn't *always* happen, though it is frequent enough that I can reliably hit it locally if I run the test a dozen times.
As a shortcut get a MWE, I saved the random-generated data to a `.npy` file (uploaded to filetransfer.io, see link in the reprod script)

I suspect the important change in gh-26821 is that Highway is now used by default on macOS+arm64

may be linked to gh-27023

### Reproduce the code example:

```python
import numpy as np

# https://filetransfer.io/data-package/VZDHbBLq#link
arr = np.load("array.npy")
np.unique(arr)
```

### Error message:

```shell
I don't know how to get gdb on macOS arm64
```

### Python and NumPy Versions:

```
2.1.0.dev0+git20240725.0819378
3.10.14 (main, Apr  8 2024, 15:51:39) [Clang 15.0.0 (clang-1500.3.9.4)]
```
Also seen in CI with Python 3.9, FWIW

### Runtime Environment:

```
[{'numpy_version': '2.1.0.dev0+git20240725.0819378',
  'python': '3.10.14 (main, Apr  8 2024, 15:51:39) [Clang 15.0.0 '
            '(clang-1500.3.9.4)]',
  'uname': uname_result(system='Darwin', node='kwanzaabot.home', release='23.5.0', version='Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]
```

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by Mousius**
Fixes #27037

### CODE REVIEW

**Review by r-devulap — APPROVED** [review]
@neutrinoceros verified that this patch fixes the bug. https://github.com/numpy/numpy/issues/27037#issuecomment-2252763746

**Comment by r-devulap** [comment]
> I checked why our tests did not find this, and it's because they generate random 32-bit values which are very unlikely to have many duplicates. We can also run them with 8-bit values.

 @Mousius could you add a test in NumPy to add coverage for such sorting array with duplicate values? 
Ref https://github.com/numpy/numpy/issues/27037#issuecomment-2255439097

**Comment by Mousius** [comment]
@r-devulap lets not talk about how the test was the first thing I wrote and still forgot to include it in the PR 🙀

**Comment by charris** [comment]
Thanks @Mousius .

**Pull request merged**
