### PR TITLE
DOC: add a Code of Conduct document.

### PR DESCRIPTION
**Pull request by rgommers**
Discussed and accepted in this thread:
https://mail.python.org/pipermail/numpy-discussion/2018-July/078476.html

Will be linked from https://scipy.org/codes-of-conduct.html and from the
GitHub community profile (https://github.com/numpy/numpy/community)

### CODE REVIEW

**Review by charris — APPROVED** [review]

**Comment by rgommers** [comment]
> I was going to merge, but on the list you asked for comment, so will wait. Feel free to merge when enough time has passed.

comment only on the people to be on the CoC committee. no reason not to merge this already, we can always change names later.

**Comment by charris** [comment]
OK, done. Thanks Ralf.

**Comment by rgommers** [comment]
Thanks for merging. I've created and tested numpy-conduct@googlegroups.com, will add @njsmith and @stefanv to that. And create some links to the CoC on scipy.org and from the NumFOCUS summary of NumPy.

**Comment by rgommers** [comment]
Updated:
- https://scipy.org/codes-of-conduct.html
- https://github.com/numfocus/numfocus/blob/master/projects/NumPy.md
- (to be merged) https://github.com/numpy/numpy.org/pull/13

**Comment by mattip** [comment]
Should there be a link on the [governance](http://www.numpy.org/devdocs/dev/governance/index.html) page as well?

**Comment by rgommers** [comment]
> Should there be a link on the governance page as well?

Hmm not sure. Between the links on numpy.org, scipy.org, the developer guide, and via GitHub `CODE_OF_CONDUCT.md` and Insights > Community, I think discoverability is pretty good. And I think a CoC (~ community building & legal fineprint) is a bit orthogonal to governance (~ how decisions get made). 

So I'd say no. If others feel strongly that belongs under governance, I won't argue though.

**Pull request merged**
