### PR TITLE
ENH: improve the error raised by ``numpy.isdtype``

### PR DESCRIPTION
**Pull request by keewis**
When passing an invalid string kind to `numpy.isdtype`, it raises this error:

``` python
np.isdtype(np.uint64, "integer")
# TypeError: kind argument must be comprised of NumPy dtypes or strings only, but it is a <class 'str'>.
```

That's not really helpful: we did pass in a string (as the first part of the message requires), we just passed the _wrong_ string.

Improving this is somewhat tricky: `_preprocess_dtype` is used to check both dtypes and kinds, and the only difference is the error message that is passed in. To work around that, I've added a boolean parameter to know when to change the error message.

However, this function now feels a bit weird to me, so instead we could also generate `err_msg` within `_preprocess_dtype` and just pass something like `kind="kind"` or `kind="dtype"` (I'm not attached to that name, though).

Edit: with the last two commits I changed the function to generate the error message based on the `is_kind` flag, and to raise a `ValueError` if the wrong string was passed.

### CODE REVIEW

**Comment by keewis** [comment]
I'm not particularly attached to the specific wording, as long as we can very clearly state that it was the string value (not the type) that was wrong. Also, I wonder if it wouldn't it be more appropriate to raise a `ValueError` instead in this case?

In general, though, I agree, my implementation I'm currently proposing is somewhat unsatisfactory.

For another idea, how about we raise an error (or return a sentinel), and the calling code is responsible for raising the error? For example:
```python
_error = object()

def _preprocess_dtype(dtype):
    """
    Preprocess dtype argument by:
      1. fetching type from a data type
      2. verifying that types are built-in NumPy dtypes
    """
    if isinstance(dtype, ma.dtype):
        dtype = dtype.type
    if isinstance(dtype, ndarray) or dtype not in allTypes.values():
        return _error
    return dtype

def isdtype(...):
    ...
    dtype = _preprocess_dtype(dtype)
    if dtype is _error:
        raise TypeError(
            "dtype argument must be a NumPy dtype, "
            "but it is a {type(dtype)}."
        )

    ...
    kind = _preprocess_dtype(kind)
    if kind is _error and isinstance(kind, str):
        raise ValueError(
                "kind argument is a string, but"
                f" {repr(dtype)} is not a known kind name."
        )
    elif kind is _error:
        raise TypeError(
            "kind argument must be comprised of "
            "NumPy dtypes or strings only"
        )
```

**Comment by keewis** [comment]
note that by using `elif isinstance(kind, str)` in `isdtype` we basically resolved the issue I had, and we could keep the original implementation of `_preprocess_dtype`. I'm happy to remove the `err_msg` in the way you suggested, though.

**Review by mtsokol — CHANGES_REQUESTED** [review]

**Review by mtsokol — APPROVED** [review]

**Comment by mtsokol** [comment]
@keewis  thank you!

**Comment by keewis** [comment]
did you plan on backporting this change? Since we changed the exception type, it might be easier to use if all versions of `isdtype` return the same type. Otherwise, how do you usually deal with these kinds of changes?

**Comment by mtsokol** [comment]
@charris Could we still backport this change to 2.0?

**Comment by charris** [comment]
@mtsokol We can do that.

**Pull request merged**
