### PR TITLE
FutureWarning for np.full(..., non-float).

### PR DESCRIPTION
**Pull request by anntzer**
cf. discussion in #6366.

@seberg @njsmith @charris 
Please consider whether this can make it to 1.10.rc2 to get at least some testing before the actual release.

### CODE REVIEW

**Comment by njsmith** [comment]
Lgtm. @charris, what do you think?

**Comment by charris** [comment]
LGTM also. Thanks @anntzer .

**Comment by njsmith** [comment]
Doh, only looking at the backport go by so I realize that this is missing a test. Don't really want to delay 1.10rc2 over it, but @anntzer if you have a few minutes it'd be good to have (in master if nothing else).

**Comment by anntzer** [comment]
in test_numeric or in test_deprecations?

**Comment by njsmith** [comment]
test_deprecations

Unless you'd rather do it the other way. It really doesn't matter much :-)

**Comment by rkern** [comment]
This behavior is confusing. http://stackoverflow.com/questions/33070449/why-does-np-full-raise-a-futurewarning

In the case where the user explicitly specifies the dtype, the behavior will not be different in the future, so there should be no warning. It's only when the user does not explicitly specify the dtype as something other than `None` that the behavior will change in the future.

**Comment by anntzer** [comment]
Apologies, see #6449.

**Pull request merged**
