### PR TITLE
DOC: Add images illustrating how-to-io.rst

### LINKED ISSUE #17517: DOC: ENH: I/O how-to needs a visual aid
Improve navigation of the [I/O how-to](https://numpy.org/devdocs/user/how-to-io.html) by prepending  a decision tree/flowchart using an image or graphviz, as suggested by @mattip.

### PR DESCRIPTION
**Pull request by TAnhMinh**
Add .. image:: how-to-io-image.png and .. image:: how-to-io-image.pdf and their .tex source file. Resolves #17517.

### CODE REVIEW

**Comment by TAnhMinh** [comment]
Hi! I don't want to bother you but would it be possible to label this as hacktoberfest-accepted, please?

**Comment by melissawm** [comment]
Hello, @TAnhMinh ! Thanks for picking this up. I have a couple of comments on the looks and some of the content, but first of all I believe we need to check if this is an appropriate format and if TikZ is the right tool for the job. I'd like to hear some more experienced maintainers on this. Maybe @mattip ?

**Comment by eric-wieser** [comment]
> Add `.. image:: how-to-io-image.png` and `.. image:: how-to-io-image.pdf`

It looks like you forgot to commit this part of your work - which means the image doesn't actually appear anywhere

**Comment by rgommers** [comment]
> but first of all I believe we need to check if this is an appropriate format and if TikZ is the right tool for the job.

I'd say it's the best tool for the job. The annoyance is of course that we're stuck with either committing generated images or adding a tricky to install dependency to the doc build. I don't quite like either option, so here's a proposal:
- Do not commit `.png` or `.pdf` files (it doesn't scale)
- Make this an _optional_ doc build dependency
- Ensure tikz is installed in CI

**Comment by eric-wieser** [comment]
Perhaps worth noting that diagrams like the above are inaccessible to screenreaders, in a way that svg diagrams might not be.

**Comment by rgommers** [comment]
Good point @eric-wieser. For Matplotlib figures this doesn't matter, but for diagrams that are only text + boxes, using SVG output makes a lot of sense.

**Comment by charris** [comment]
What is the status of this?

**Comment by melissawm** [comment]
@TAnhMinh are you planning on working on this? If not, I think @marsbarlee may be able to help with the image.

**Comment by charris** [comment]
@melissawm I think the question at this point is do we want the diagram. Using svg should be OK as we are planning to drop the Latex builds.

**Comment by InessaPawson** [comment]
@melissawm and I discussed this PR at today’s meeting. The diagram would be a valuable addition to the NumPy documentation. However, we are wondering if, instead of .svg, we could reproduce it in .md using Mermaid (https://mermaid-js.github.io/mermaid/#/). It would be more beneficial from the maintenance and reproducibility point of view. 
@eric-wieser @rgommers @charris What do you all think?

**Comment by charris** [comment]
@InessaPawson I am unfamiliar with Mermaid and have no opinion about it. It looks like it uses JavaScript, and I suppose that will work with html, so the question is probably if sphinx can deal with it and what the documentation team wants to do.

**Comment by InessaPawson** [comment]
> the question is probably if sphinx can deal with it and what the documentation team wants to do.

@charris This extension https://github.com/mgaitan/sphinxcontrib-mermaid should make it work with sphinx.

**Comment by InessaPawson** [comment]
@TAnhMinh Would you be interested to finish this PR using Mermaid? Please let us know by August 1, 2022.

**Comment by mattip** [comment]
While the idea to have a diagram is nice, and the information is helpful, the original submitter has not been responsive. I will close this. If someone wants to finish it, please reopen or open a new issue, and reconstruct the image in either SVG or mermaid (which would require adding some new dependencies I think).

**Pull request closed without merging**
