### PR TITLE
BUG: Restore support for i386 and PowerPC (OS X)

### PR DESCRIPTION
**Pull request by evanmiller**
Downstream report: https://trac.macports.org/ticket/64019

### CODE REVIEW

**Comment by charris** [comment]
That's i686, correct?

**Comment by charris** [comment]
Also, long double on i686 (32 bit system) is usually 12 bytes for alignment of 80 bit extended precision.

**Comment by evanmiller** [comment]
I believe it's i686; OS X refers to all 32-bit Intel as "i386" so I am going off that.

I will update the logic to reflect 12-byte alignment.

**Comment by mattip** [comment]
This is in response to #20270 which redefined `NPY_SIZEOF_LONGDOUBLE` and `NPY_SIZEOF_COMPLEX_LONGDOUBLE` for `__x86_64` and `__arm64__`. Would it make sense only do the redefines if we are on one of those platforms, which would the leave in place the defines that worked before #20270 ?

**Comment by evanmiller** [comment]
@mattip If I understand you correctly, you propose:

* Moving the `#undef` statements to be inside the `#if` blocks
* Removing the "unknown architecture" `#error`

Is that correct?

**Comment by mattip** [comment]
I think so. I am a bit undecided since it would be nice if all the definitions of `NPY_SIZEOF_LONGDOUBLE` and `NPY_SIZEOF_COMPLEX_LONGDOUBLE` were generated the way they are for the other platforms (via `generate_numpyconfig_h()`), but that might be out of scope for this PR. Maybe a comment "move to generate_numpyconfig_h in setup.py` might provide a hint for someone to redo this at some point. I am not sure why they are here in the first place, maybe because of cross-compilation?

**Comment by evanmiller** [comment]
Maybe best to ask @isuruf

**Comment by isuruf** [comment]
For universal2 wheels, we need the headers to be common to both architecture before preprocessing. That's why this was added.
There are 2 options here.
1. Remove undef for arch other than x86_64, arm64. (This would support only universal2 wheels and thin wheels)
2. Merge this PR. (This would support universal wheels in addition to universal2 and thin wheels)

I'm fine with either option. @evanmiller, thanks for fixing this.

**Comment by mattip** [comment]
Thanks, that is helpful. I am not very familiar with the nuances here, are universal wheels still supported across the ecosystem? @evanmiller whichever choice you make, could you add a comment summarizing the point @isuruf makes?

**Comment by evanmiller** [comment]
@mattip Is the existing comment sufficient?

https://github.com/numpy/numpy/blob/e94bbb87ba10ec2585f87af8e9a80afee2f89e04/numpy/core/include/numpy/numpyconfig.h#L6-L10

**Comment by isuruf** [comment]
Sounds good @evanmiller

**Comment by isuruf** [comment]
```
 /* 
  * On Mac OS X, because there is only one generated header for all the archs 
  * in universal builds, any macro in the generated header which depends on
  * the arch needs to be hardcoded.
  */ 
  ```

**Comment by mattip** [comment]
Thanks @evanmiller

**Pull request merged**
