### PR TITLE
DOC: fix typos in trapz() docstring

### PR DESCRIPTION
**Pull request by sciunto**
Fix typos in docstring :)

### CODE REVIEW

**Comment by charris** [comment]
I think the original is correct, if confusing. The explanation for `x` needs to be improved as well. Something like
```
    x : array_like, optional
        The sample points corresponding to the `y` values. If `x` is None, the sample points
        are assumed to be evenly spaced  `dx` apart. The default is None.
    dx : scalar, optional
        The spacing between sample points when `x` is None. The default is 1.
```

**Comment by sciunto** [comment]
oh, ok, now I understand correctly that sentence. But, still confusing I think.

**Comment by charris** [comment]
I updated this in #6982, so closing. Thanks @sciunto .

**Comment by sciunto** [comment]
Thanks to you!

**Pull request closed without merging**
