### PR TITLE
BUG: Fix gh-25867 for used functions and subroutines

### PR DESCRIPTION
**Pull request by HaoZeke**
There's a small refactor here (first commit, can be removed). The fix here was to wrap modules which have functions and subroutines. This was what was supposed to be implemented in https://github.com/numpy/numpy/pull/25361. Also has a new test for the fix.

### CODE REVIEW

**Comment by HaoZeke** [comment]
@mancellin this should fix capytaine, could you check? (neat project by the way!)

**Comment by HaoZeke** [comment]
CI failure seems unrelated.

```bash
After this operation, 139 MB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libjsoncpp25 amd64 1.9.5-3 [80.0 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 librhash0 amd64 1.4.2-1ubuntu1 [125 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 dh-elpa-helper all 2.0.9ubuntu1 [7610 B]
Ign:5 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 cmake-data all 3.22.1-1ubuntu1.22.04.1
Ign:6 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 cmake amd64 3.22.1-1ubuntu1.22.04.1
Get:7 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 libopenblas0-pthread amd64 0.3.20+ds-1 [6803 kB]
Ign:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 cmake-data all 3.22.1-1ubuntu1.22.04.1
Ign:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 cmake amd64 3.22.1-1ubuntu1.22.04.1
Get:8 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 libopenblas0 amd64 0.3.20+ds-1 [6098 B]
Err:5 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 cmake-data all 3.22.1-1ubuntu1.22.04.1
  404  Not Found [IP: 20.106.104.242 80]
Get:9 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 libopenblas-pthread-dev amd64 0.3.20+ds-1 [4634 kB]
Err:6 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 cmake amd64 3.22.1-1ubuntu1.22.04.1
  404  Not Found [IP: 20.106.104.242 80]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 libopenblas-dev amd64 0.3.20+ds-1 [18.6 kB]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/cmake/cmake-data_3.22.1-1ubuntu1.22.04.1_all.deb  404  Not Found [IP: 20.106.104.242 80]
Fetched 11.7 MB in 1s (12.5 MB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/cmake/cmake_3.22.1-1ubuntu1.22.04.1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

**Comment by charris** [comment]
The BLAS test failures may be due to not basing on current main.

**Comment by charris** [comment]
Thanks @HaoZeke .

**Comment by mancellin** [comment]
> @mancellin this should fix capytaine, could you check? (neat project by the way!)

Thank you @HaoZeke. I will test this as soon as possible.

**Comment by mancellin** [comment]
Everything seems to work fine on the latest nightly builds :tada:

**Pull request merged**
