### PR TITLE
ENH: Modified metadata for build_err_msg method

### LINKED ISSUE #19171: np.testing error messages lose "Actual" and "Desired" metadata when comparing arrays
Most  np.testing functions print error messages with ACTUAL and DESIRED to help aid in debugging. From the docstring example:

```shell
>>> np.testing.assert_equal([4,5], [4,6])
Traceback (most recent call last):
   ...
AssertionError:
Items are not equal:
item=1
 ACTUAL: 5
 DESIRED: 6
```

However, this only holds when processing scalars, lists, and tuples. When processing actual numpy arrays, most functions make a call to `assert_array_compare()` which replaces the default `names=('ACTUAL', 'DESIRED')` in  `build_err_msg()` with `x` and `y`. As a result, error messages from `assert_allclose()` or similar functions will strip this metadata.

https://github.com/numpy/numpy/blob/main/numpy/testing/_private/utils.py#L851

### Reproducing code example:

```python
import numpy as np
actual = np.array([4, 5])
desired = np.array([4, 6])
np.testing.assert_allclose(actual, desired)
```

**Observed**
```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 2 (50%)
Max absolute difference: 1
Max relative difference: 0.16666667
 x: array([4, 5])
 y: array([4, 6])
```

**Expected**
```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 2 (50%)
Max absolute difference: 1
Max relative difference: 0.16666667
 ACTUAL: array([4, 5])
 DESIRED: array([4, 6])
```

When debugging test outputs or looking at test logs, people not familiar with the numpy convention may not be aware that x is ACTUAL and y is DESIRED.

### PR DESCRIPTION
**Pull request by sayantikabanik**
**Info regarding the PR**
- PR opened for the issue [19171](https://github.com/numpy/numpy/issues/19171)
- Replaced the `x` & `y` params with `ACTUAL` & `DESIRED` for clear understanding during debugging 
- modified tests  under `tests_utils.py` to incorporate the message string change

### CODE REVIEW

**Review by czgdp1807 — APPROVED** [review]
This looks good to me. @BvB93 @almostsquare Any thoughts on this?

**Comment by sayantikabanik** [comment]
@czgdp1807 @BvB93 are there any more changes required for this PR to be complete?

**Comment by almostsquare** [comment]
> This looks good to me. @BvB93 @almostsquare Any thoughts on this?

Thanks for the changes, @sayantikabanik! Looks good!

**Comment by czgdp1807** [comment]
LGTM.

**Comment by mattip** [comment]
Since this is user-facing, do we want to add a one-line release note about the changed behaviour?

**Comment by sayantikabanik** [comment]
> Since this is user-facing, do we want to add a one-line release note about the changed behaviour?

I second that.

**Comment by charris** [comment]
@sayantikabanik You can make the release note in `doc/release/upcoming_changes`. Look at the other notes to see how it is done.

**Comment by czgdp1807** [comment]
This needs a clean up of git history. We will meet later today and help you clean up the stuff here.

**Comment by sayantikabanik** [comment]
> This needs a clean up of git history. We will meet later today and help you clean up the stuff here.

Thanks :D

**Comment by sayantikabanik** [comment]
Could the CI be restarted from the backend? It's stuck I think.

**Comment by czgdp1807** [comment]
It's Travis again. @rgommers It's get stuck very often. Can be ignored I think.

**Comment by mdhaber** [comment]
It looks like this was close and valuable for consistency. 
@sayantikabanik would you like to merge main here? That should get CI going again.
I could also open a new PR to do this - preserving your commits - if you'd prefer.

**Comment by mdhaber** [comment]
@ngoldbaum looks like this can be closed now

**Comment by ngoldbaum** [comment]
Finished in #24931

**Pull request closed without merging**
