### PR TITLE
DOC: Update dtype hierarchy png file

### PR DESCRIPTION
**Pull request by Unessam**
Modifying dtype hierarchy png file referring to these issues: #23078 #23249 and @eric-wieser comment 
Below are two screenshots of the changes:
Screenshot 2023-02-20 220507
Screenshot 2023-02-20 214244

### CODE REVIEW

**Comment by eric-wieser** [comment]
This image is a generated output from this file: https://github.com/numpy/numpy/blob/main/doc/source/reference/figures/dtype-hierarchy.dia

Can you edit the original? Also, please don't create a new PR next time, you can just update the old one.

**Comment by Unessam** [comment]
@eric-wieser thanks for your comment, could you please point to the original one, all I can see are the files in this directory: doc/source/reference/figures/

**Comment by eric-wieser** [comment]
I already pointed you to the original one in my comment above, it's the one with the `.dia` extension.

I'm afraid I'm not familiar with how to edit these files; but we seem to have a few of them, so hopefully someone more involved with documentation is.

**Comment by Unessam** [comment]
@eric-wieser thanks for your advice and being patient with me, I updated all three files (dia, pdf, png) now

**Comment by seberg** [comment]
Would it be quick for you to keep the "original" order of first `bytes_` and then `str_`?

**Comment by eric-wieser** [comment]
It would be great if you could explain in the PR description how you edited the .dia file, so that whoever does this next time has instructions they can follow.

**Comment by seberg** [comment]
@eric-wieser "Dia" is an old diagram editor.  Probably not the right website, but: https://wiki.gnome.org/Apps/Dia/

**Review by rossbar — APPROVED** [review]
LGTM - @Unessam since you've figured out how to edit the image source file, fixing the box sizes so they don't intersect/cut off the text would be another nice improvement (see e.g. `ulonglong`, `unsignedinteger`, `complex_`, etc.)

That can be left to a separate PR though, +1 for these changes as-is.

**Comment by Unessam** [comment]
@rossbar thanks for your comment, will fix the box sizes in a separate PR soon.
@seberg thanks for cm, will apply the change in the order of bytes_ and str_ along with the rest of the changes requested by Ross soon

**Pull request closed without merging**
