### PR TITLE
BUG: Fix datetime_to_timedelta_resolve_descriptors signature

### PR DESCRIPTION
**Pull request by hoodmane**
This function is supposed to take a fifth argument.

### CODE REVIEW

**Review by WarrenWeckesser — APPROVED** [review]
Yup.

**Comment by seberg** [comment]
Thanks!

**Comment by hoodmane** [comment]
Could this be backported to v1.23? We're running into trouble with it (of course we can apply a cherry-picked patch)
https://github.com/pyodide/pyodide/pull/3284

**Comment by lesteve** [comment]
This fix is in v1.24.0rc1 (tagged 4 hours ago) so it will be in numpy 1.24.

Maybe pyodide can live with the patch in the meantime? I updated the pyodide PR to do this.

Unless there is a 1.23 bugfix released scheduled soon, which may not be that likely since 1.23.5 has been released 4 days ago.

**Comment by hoodmane** [comment]
Yeah it is totally fine for us to patch it.

**Pull request merged**
