### PR TITLE
TYP: Concrete ``float64`` and ``complex128`` scalar types with builtin bases

### LINKED ISSUE #21906: `np.float64` is not accepted as `float` under static type checks
Some of the built-in scalar types [inherit from the corresponding Python types](https://numpy.org/devdocs/reference/arrays.scalars.html#arrays-scalars-built-in). However, this fact does not seem to be exposed by the numpy type stubs.

```
# Python version 3.8.10, numpy version 1.23.0
import numpy as np

x = np.float64(1.0)
print(f"x={x} of type={type(x)} is float: {isinstance(x, float)}")
# x=1.0 of type=<class 'numpy.float64'> is float: True


def f(a: float) -> float:
    return a


f(x)
"""
pyright 1.1.256:
error: Argument of type "float64" cannot be assigned to parameter "a" of type "float" in function "f"
  "float64" is incompatible with "float" (reportGeneralTypeIssues)

mypy 0.961:
error: Argument 1 to "f" has incompatible type "floating[_64Bit]"; expected "float"
"""
```

Replacing `np.float64` with `np.float_` or `np.double` does not help.

### LINKED ISSUE #23081: BUG: type checking np.isfinite() arguments fails for sequences of (np.number | float)
### Describe the issue:

I'm trying to add type hints to an existing code base. I currently have a function (simplified):

```Python
def array_to_file(
    data,
    fileobj,
    out_dtype,
    intercept = 0.0,
    divslope = 1.0,
):
    if not np.all(np.isfinite((intercept, 1.0 if divslope is None else divslope))):
        raise ValueError('divslope and intercept must be finite')
    ...
```

We have written it to accept numpy or Python types. The general use case is Python types, but if someone wants to avoid doubling their memory by making sure all passed values are float32, they can. I want to make this:

```Python
Scalar = np.number | float

def array_to_file(
    data: npt.ArrayLike,
    fileobj: io.IOBase, 
    out_dtype: np.dtype | None = None,
    intercept: Scalar = 0.0,
    divslope: Scalar | None = 1.0,
):
    if not np.all(np.isfinite((intercept, 1.0 if divslope is None else divslope))):
        raise ValueError('divslope and intercept must be finite')
    ...
```

But I get the error below.

### Reproduce the code example:

```python
import numpy as np

Scalar = np.number | float

def check1(x: Scalar) -> np.bool_:
    return np.isfinite(x)

def check2(x: Scalar, y: Scalar) -> np.ndarray:
    return np.isfinite((x, y))
```

### Error message:

```shell
$ mypy example.py
example.py:9: error: Argument 1 to "__call__" of "_UFunc_Nin1_Nout1" has incompatible type "Tuple[Union[number[Any], float]]"; expected "Union[_SupportsArray[dtype[Any]], _NestedSequence[_SupportsArray[dtype[Any]]], bool, int, float, complex, str, bytes, _NestedSequence[Union[bool, int, float, complex, str, bytes]]]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

### Runtime information:

```
1.23.5
3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
```

### Context for the issue:

This is not terribly high priority. I can rewrite this in a way that will type check, but it seems like a bug.

If `numpy.typing` has better ways of writing `Scalar` that I haven't seen, happy to switch to that.

### LINKED ISSUE #23663: BUG: Shouldn't numpy's floating types (e.g. `np.float_`) and python's native `float` type be compatible?
### Describe the issue:

When trying to type hint functions accepting scalars, I get unexpected error messages from my type checker (Pylance). As `np.float_` is a subtype of python's native `float` type, I would expect to be able to pass a variable with type `np.float_` when a native `float` is expected.

### Reproduce the code example:

```python
import numpy as np

def idx(x: float) -> float:
    return x

arr = np.arange(5.0, dtype=np.float_)
sum = np.sum(arr)
idx(sum)
```

### Error message:

```shell
Argument of type "float_" cannot be assigned to parameter "x" of type "float" in function "idx"
  "float_" is incompatible with "float" Pylance (reportGeneralTypeIssues)
```

### Runtime information:

1.24.1
3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

### Context for the issue:

This issue makes it either impossible or much harder to correctly type hint functions such that they are compatible with numpy.

### PR DESCRIPTION
**Pull request by jorenham**
At runtime, `numpy.float64` subclasses `builtins.float`, and `numpy.complex128` subclasses `builtins.complex`. But the typing stubs currently do not reflect this. The consequence is that e.g. `spam: float = np.float64(22 / 7)` will be marked as an error by static type-checkers.

This PR introduces concrete types for `float64` and `complex128` that, like at runtime, (also) inherit from the `float` and `complex` builtin types, respectively.

Note that that the amount of type-tests had to be adjusted to accommodate this change, doesn't reflect the impact of this change on existing codebases is this case. This is becaue the `typing.assert` that is used in these type-tests, requires the *exact* type to match, so `assert_type` considers `floating[_64Bit]` and `float64` as totally different types, even though `float64 <: floating[_64Bit]`. So for existing typing annotations this won't require a change.

Fixes #23081
Fixes #21906
Fixes #23663

### CODE REVIEW

**Comment by charris** [comment]
Thanks @jorenham . I'll go with your judgement here.

**Comment by charris** [comment]
> Fixes #23081 #21906 #23663

You need "fixes" for each of the issues.

**Comment by jorenham** [comment]
> > Fixes #23081 #21906 #23663
> 
> You need "fixes" for each of the issues.

Ah that explains

**Comment by jorenham** [comment]
> @jorenham Thanks for implementing these changes to resolve static type checking issues involving Python and numpy float types. At the time you implement them, did you also consider covering the case below (assigning a `float` to a `np.float64`)?
> 
> image
> 
> I installed latest numpy with your changes using:
> `pip install git+https://github.com/numpy/numpy.git@main`
> 
> 

You're assigning a supertype to a subtype here; that's not valid. You also can't assign an int to a bool, but you can assign a bool to an int.

**Pull request merged**
