### PR TITLE
MAINT: removed duplicate 'int' type in ScalarType

### PR DESCRIPTION
**Pull request by gdementen**
This is a redo of #20526 (I had not given a proper branch name), including the test changes.

### CODE REVIEW

**Review by BvB93 — COMMENTED** [review]
The second `int` will have to be removed here as well:
https://github.com/numpy/numpy/blob/f4a3e07877eb258f69a7d65d8a3b7e8d96e1aacd/numpy/core/numerictypes.pyi#L136-L140

**Comment by gdementen** [comment]
@BvB93 yes, I figured that now 😉. I only understood your other comment when I saw the test failure (I did not realize there were two distinct numerictypes.pyi files and I read your comment too quickly the first time), I am very sorry about this!

**Comment by gdementen** [comment]
@BvB93 do I need to do anything else?

**Review by BvB93 — APPROVED** [review]
LGTM

For those unaware: the consensus in https://github.com/numpy/numpy/pull/20526 seems to have been that `np.ScalarType` is not guaranteed ordered to be (deterministically) ordered as far as public API is concerned, so this shouldn't be a concern.

**Comment by seberg** [comment]
Thanks for following up @gdementen and thanks Bas for the review, lets get this in :).

**Pull request merged**
