### PR TITLE
ENH: Minor code optimization in numpy/npy_math

### PR DESCRIPTION
**Pull request by Djacon**
The main changes are:
> Replacing `(x-1)*(x+1)` by `x*x-1`
> Replacing `a/(b*c)` by `a/b/c`
> Removing unnecessary brackets in (x*x)

### CODE REVIEW

**Comment by Djacon** [comment]
Sorry, I don't quite understand you. Did you mean that `(x-1)*(x+1)` is more accurate than `x*x-1` or that `a/(b*c)` is more accurate than `a/b/c`?

**Comment by Djacon** [comment]
Hmm, I just checked this on python and C. Speaking of python, `a/b/c` is more accurate (try just checking `0.1/0.1/0.1` and `0.1/(0.1*0.1)`). If we talk about C, the same accuracy (maybe the compiler does really optimize it)

**Comment by Djacon** [comment]
About x*x-1 the same situation

**Comment by rkern** [comment]
The complex code is also carefully crafted to preserve branch cuts around negative 0s (real and complex). We followed core Python's `cmath` implementation that spent a lot of effort on this (e.g. [here](https://github.com/python/cpython/blob/main/Modules/cmathmodule.c#L664) for an example of the `(x-1)*(x+1)` construction). I would probably leave all of this alone without a rigorous and compelling analysis about the improvements that we can expect.

**Comment by Djacon** [comment]
Hmm, interesting. Well, in that case, yes, it's better to leave it as it is

**Pull request closed without merging**
