### PR TITLE
MAINT: Update doc requirements

### PR DESCRIPTION
**Pull request by jarrodmillman**

### CODE REVIEW

**Comment by seberg** [comment]
Thanks Jarrod, there is another copy of these in `environment.yaml`, IIRC that should change too.

**Comment by mattip** [comment]
I am a little worried about upgrading the theme from 0.7.2 to 0.8.1. Reading through [the changelog](https://github.com/pydata/pydata-sphinx-theme/releases) it seems there are some slight style changes. Did you look at these when upgrading the version?

**Comment by seberg** [comment]
Looking through the style changes, none of them strike me as changes we should worry about.  I would be +1 with just going ahead and upstreaming any issues if they crop up.

(I am wondering if we should backport this for the sake of also backporting the version picker eventually?)

**Comment by mattip** [comment]
Thanks @jarrodmillman. As for backporting, we usually do not rebuild older versions of the documentation, right?

**Comment by charris** [comment]
> we usually do not rebuild older versions of the documentation, right?

There was a request that we rebuild the 1.22 documentation to fix linking problems.

**Comment by mattip** [comment]
> There was a request that we rebuild the 1.22 documentation to fix linking problems.

So this should be backported to 1.22 and then we should rebuild the docs. I guess that would be an opportunity to also get the version pulldown.

**Comment by charris** [comment]
@mattip Is the version picker ready? I'm planning to release 1.22.4 this week.

**Comment by mattip** [comment]
The version picker is available in [the devdocs](https://numpy.org/devdocs/) and so far seems to work as advertised.

**Pull request merged**
