### PR TITLE
BUG: Check that `pvals` is 1D in `_generator.multinomial`.

### LINKED ISSUE #15492: multinomial accepts multi-dimensional arrays but returns unexpected counts or raises ValueError
https://github.com/scipy/scipy/issues/11422 noticed that `scipy.stats.multinomial(n,pvals).rvs()` is not vectorized. 
`scipy.stats.multinomial(n,pvals).rvs` calls `rng.multinomial(n, pvals)` for some Generator rng, (such as `rng == np.random.default_rng`)

`rng.multinomial(n, pvals)` accepts multidimensional arrays for `pvals` but then partially treats `pvals` as a collection of one-dimensional arrays, and partially as a 1-d array.
When passed an array of shape `(m,p)`, `multinomial` decides that there are  `m` (not `p`) possible outcomes in the experiment.  It then takes the first `(m-1)` elements of the multi-dimensional array and uses those as the first `(m-1)` probabilities. The final probability is implied, and is `1-sum(first m-1 probabilities)`.  This selection of probabilities may cross rows.
[`rng.multinomial` also has an optional `size` keyword.  That doesn't impact this issue.]

I.e. It appears that it is effectively doing the following for an array  of shape `(m, p)`:
```
probabilities = pvals.flatten()[:m]  # May cross rows, or stop before end of first row
if np.sum(probabilities[:-1]) > 1: raise ValueError(...)
probabilities[-1] = 1 - np.sum(probabilities[:-1])
# Generate a single length m array of counts using probabilities
#  (but user expects m arrays of length p)
...
```

I.e. When passed a multi-dimensional array, `rng.multinomial` will either: a) raise an Exception;  or b) will return a 1-d array of ints to the user, rather than a multi-dimensional array.

Is `multinomial` expected to respect multi-dimensional arrays?
If not, should it immediately raise a ValueError if `pvals` is not 1-d?

### Reproducing code example:

```python
import numpy as np
rng = np.random.default_rng()
rng.multinomial(20, np.array([[0,1], [1,0], [0,1]]))  
# produces single 3-element array([ 0, 20,  0]), but user expecting 3 2-element arrays

rng.multinomial(20, np.array([[0,1], [1,0], [0,1], [0,1]]))    
# User expecting 4 2-element arrays, gets an Exception.
```
The error occurs because it treated the (4,2) array as an array of length 4, and used 2 values from row 0, and 1 values from row 1. It summed the first 3 elements of [0, 1, 1, 0, 0, 1, 0, 1] to get 2.0 which is bigger than 1, so raised an Exception.

### Error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-103-63e116799aea> in <module>
----> 1 rng.multinomial(20, np.array([[0,1], [1,0], [0,1], [0,1]]))

generator.pyx in numpy.random.generator.Generator.multinomial()

ValueError: sum(pvals[:-1]) > 1.0
```

### Numpy/Python version information:
```
1.17.3 3.8.0 (default, Nov  6 2019, 15:49:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

### PR DESCRIPTION
**Pull request by panpiort8**
Fixes gh-15492.

Unfortunately I found no flags to ensure pvals is 1d within np.PyArray_FROM_OTF.
Alternatively I can check number of dimensions with PyArray_NDIM after calling above method .

### CODE REVIEW

**Comment by charris** [comment]
We are no longer making changes to `mtrand.pyx`. @rkern Comment?

**Comment by rkern** [comment]
Agreed.

**Comment by seberg** [comment]
Hmmm, this was a regression in 1.17 though, in 1.16 a ValueError was given (although not this one).

**Comment by charris** [comment]
@seberg A regression in the legacy code?

**Comment by seberg** [comment]
Yes, so I think this is fine as such, since it is buggy behaviour and the error was correctly given previously.

**Comment by rkern** [comment]
I retract, then.

**Comment by charris** [comment]
I assume the difference comes from using `PyArray_FROM_OTF` instead of `PyArray_ContiguousFromObject(pvals, NPY_DOUBLE, 1, 1)`. Note that if the input is not already an array, `np.ndim` will create one, so there is some duplication. I wonder if it would be better to use the original creation function?

Might be worth checking other uses of PyArray_FROM_OTF to see if the behavior was changed in other places. I'm not sure what that change bought us

**Comment by charris** [comment]
Checking, `PyArray_ContiguousFromObject` was dropped in six places in the transition to 1.17. We should probably fix that and also use it in the corresponding generator functions. In 1.16
```
numpy/random/mtrand/numpy.pxd:111:    object PyArray_ContiguousFromObject(object obj, NPY_TYPES type,
numpy/random/mtrand/mtrand.pyx:796:            obj = <ndarray>PyArray_ContiguousFromObject(key, NPY_ULONG, 1, 1)
numpy/random/mtrand/mtrand.pyx:799:            obj = <ndarray>PyArray_ContiguousFromObject(key, NPY_LONG, 1, 1)
numpy/random/mtrand/mtrand.pyx:1135:            p = <ndarray>PyArray_ContiguousFromObject(p, NPY_DOUBLE, 1, 1)
numpy/random/mtrand/mtrand.pyx:4639:        parr = <ndarray>PyArray_ContiguousFromObject(pvals, NPY_DOUBLE, 1, 1)
numpy/random/mtrand/mtrand.pyx:4765:        alpha_arr   = <ndarray>PyArray_ContiguousFromObject(alpha, NPY_DOUBLE, 1, 1)
```

**Comment by charris** [comment]
We should also test that the error is raised in the functions that are running that check.

**Comment by seberg** [comment]
@panpiort8 would you be willing and dig a bit into checking that the other cases Chuck listed are doing the right thing? (The ideal thing would be to add new tests, and fix them if they break)

**Comment by charris** [comment]
I was thinking of just using `PyArray_ContiguousFromObject` as before. @mattip Do you recall what the reason for the change was?

**Comment by panpiort8** [comment]
> @panpiort8 would you be willing and dig a bit into checking that the other cases Chuck listed are doing the right thing? (The ideal thing would be to add new tests, and fix them if they break)

I'll do that

**Comment by panpiort8** [comment]
> I was thinking of just using `PyArray_ContiguousFromObject` as before. @mattip Do you recall what the reason for the change was?

Maybe it's not so vital as I used [PyArray_FROMANY](https://docs.scipy.org/doc/numpy-1.13.0/reference/c-api.array.html#c.PyArray_FROMANY) which is wrapper of same function as PyArray_FROM_OTF and PyArray_ContiguousFromObject. If was to quess PyArray_ContiguousFromObject was replaced by PyArray_FROM_OTF, because one can set requirements (NPY_ALIGNED in the case of multinomial) in the latter.

**Comment by mattip** [comment]
I think the original change to `PyArray_FROM_OTF` came from the _randomgen rewrite, git blame says commit 1235545860 which is somewhere in the _randomgen repo

**Comment by panpiort8** [comment]
> Checking, `PyArray_ContiguousFromObject` was dropped in six places in the transition to 1.17. We should probably fix that and also use it in the corresponding generator functions. In 1.16
> 
> ```
> numpy/random/mtrand/numpy.pxd:111:    object PyArray_ContiguousFromObject(object obj, NPY_TYPES type,
> numpy/random/mtrand/mtrand.pyx:796:            obj = <ndarray>PyArray_ContiguousFromObject(key, NPY_ULONG, 1, 1)
> numpy/random/mtrand/mtrand.pyx:799:            obj = <ndarray>PyArray_ContiguousFromObject(key, NPY_LONG, 1, 1)
> numpy/random/mtrand/mtrand.pyx:1135:            p = <ndarray>PyArray_ContiguousFromObject(p, NPY_DOUBLE, 1, 1)
> numpy/random/mtrand/mtrand.pyx:4639:        parr = <ndarray>PyArray_ContiguousFromObject(pvals, NPY_DOUBLE, 1, 1)
> numpy/random/mtrand/mtrand.pyx:4765:        alpha_arr   = <ndarray>PyArray_ContiguousFromObject(alpha, NPY_DOUBLE, 1, 1)
> ```
> 
> And maybe add an inline note so those calls don't get improved again.

I've checked and it's almost ok. What happened with above calls till v.1.19?

- numpy/random/mtrand/numpy.pxd:111: function declaration removed from 'header'
- numpy/random/mtrand/mtrand.pyx:796: set_state function; 'conversion' was removed
- numpy/random/mtrand/mtrand.pyx:799: same as above
- numpy/random/mtrand/mtrand.pyx:1135: choice method; it checks dimensions anyway
- numpy/random/mtrand/mtrand.pyx:4639: multinomial method; under repair
- numpy/random/mtrand/mtrand.pyx:4765: dirichlet method; This case is problematic. Actually passing multidimensional `alpha` should be prohibited, but according to [docs](https://numpy.org/doc/1.16/reference/generated/numpy.random.dirichlet.html?highlight=dirichlet#numpy.random.dirichlet)... well and here's the problem. `alpha` doc mentions 'dimension', which to my mind is ambigous and later `samples` doc mentions `alpha.ndim`. So maybe `alpha` can be multidimensional? But not really:

```
>>> import numpy as np
>>> print(np.__version__)
1.16.0
>>> np.random.dirichlet([[1/6, 1], [1/6, 1]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4749, in mtrand.RandomState.dirichlet
ValueError: object too deep for desired array
```

The `dirichlet` method is broken even in v1.16, so I would leave it as it is.

**Comment by panpiort8** [comment]
But there is another (maybe not so another) problem few methods in `numpy/random/_generator.pyx` are similarly broken. I'm going to fix them.

**Comment by panpiort8** [comment]
And `dirichlet` is broken according to [its docs](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.Generator.dirichlet.html?highlight=dirichlet#numpy.random.Generator.dirichlet):

```
>>> import numpy as np
>>> np.__version__
'1.18.0'
>>> rng = np.random.default_rng()
>>> rng.dirichlet([[1/6, 1], [1/6, 1]]).ndim # should be 2 according to docs
1
```

Or rather both `dirichlet` and its docs are broken as `dirichlet` should raise exception on multidimensional input (accoring to common sense).

Should it have its own issue? Or am I supposed to do it at once?

**Comment by mattip** [comment]
I think it should go in a different PR. Please be sure to add a tests so it stays fixed.

**Comment by seberg** [comment]
Yeah, lets move dirichlet to another thread, unless it misbehaves if `alpha` has 2 or more dimensions? I find the appending of the dimension also a bit strange. It is fine as such, but I think that for other multi-dimensional distributions we do not append it, but rather include it in `size` as you think. But there is no regression here, so it  may better to update the docs...

**Comment by charris** [comment]
What is the status of this?

**Comment by panpiort8** [comment]
> What is the status of this?

Work in progress

**Comment by panpiort8** [comment]
> But anyway few methods in `numpy/random/_generator.pyx` are similarly broken. I'm going to fix them.

I was wrong - everything except multinomial and dirichlet is ok.

**Review by seberg — APPROVED** [review]
Thanks, looks good to me, will merge soon.

**Comment by seberg** [comment]
I think this change somehow causes a ref-counting error. I don't see it yet though. Will probably look into it soon though.

**Comment by seberg** [comment]
OK, I have found the leak, had missed a small thing before. It has nothing directly to do with this change, there was simply already a leak in the error path this now takes and this flushed it out.

**Pull request merged**
