### PR TITLE
MAINT: remove star imports

### PR DESCRIPTION
**Pull request by ghost**
This looks ugly, and that's because it is! Rather it simply exposes the ugliness that was hidden behind the star imports.

Goals for this PR:
  - Remove all star imports
  - Zero functional changes

Note: this PR will not attempt to remove duplicate imports, but it allows static analyzers to potentially solve  gh-10198 with another PR.

### CODE REVIEW

**Comment by eric-wieser** [comment]
This was done by looking at `__all__`?

**Comment by xoviat** [comment]
```
gh-clone numpy
cd numpy
pip install -e .
pip install python-dewildcard
dewildcard
pip install pep8radius yapf
pep8radius master --yapf --in-place
```

**Comment by xoviat** [comment]
Code is here: https://github.com/xoviat/dewildcard/blob/b3e70e450ced2b591130d20a62522fa4633fe2cb/dewildcard.py

**Comment by xoviat** [comment]
Okay, I'm +1 on merging as-is assuming I haven't made any mistakes. The idea is to allow static analyzers to work their magic in a future PR to remove duplicates.

**Comment by charris** [comment]
In this case I'm not convinced that changing the `__init__` files improves them, they are far less readable; ugly, actually. I think our position here is that every module should have `__all__` defined, and that should limit what comes in with the `*`.

**Comment by xoviat** [comment]
@charris 

This is a temporary step to remove the star imports, which are not recommended. It's always possible to remove the extra globals in a future PR (which I may do), but the star imports need to be removed first.

**Comment by eric-wieser** [comment]
> The idea is to allow static analyzers to work their magic in a future PR to remove duplicates.

I'd argue we should be trying to remove duplicates from `__all__`, not from the list of things we import.

**Comment by eric-wieser** [comment]
Your tool is wrong here:
https://github.com/xoviat/dewildcard/blob/b3e70e450ced2b591130d20a62522fa4633fe2cb/dewildcard.py#L35

That isn't looking at `__all__` to decide what `*` imports, which it should

**Comment by xoviat** [comment]
@eric-wieser Thanks for the suggestions. However, I won't be working on this further until I can replace all of the star imports.

**Pull request closed without merging**
