### PR TITLE
REL: Prepare for the NumPy 1.25.0rc1 release

### PR DESCRIPTION
**Pull request by charris**
- Update .mailmap.
- Update npysort/x86-simd-sort submodule, it was accidentally changed.
- Update 1.25.0-notes.rst.
- Create 1.25.0-changelog.rst.
- Remove unwanted doc/release/numpy2_changes.
- Remove stray release note fragment in repo root.

### CODE REVIEW

**Comment by charris** [comment]
@seberg Do we have documentation on the plans for 2.0? If so, I'd like to include a reference to it in the release notes.

If anyone wants to add/subtract anything from the highlights, please comment.

**Comment by r-devulap** [comment]
I forgot to add release note for `np.argsort ` perf improvements.

**Comment by charris** [comment]
> I forgot to add release note for np.argsort  perf improvements.

Post it in the comments here and I'll add it, or just go ahead and push it here.

**Comment by r-devulap** [comment]
See https://github.com/numpy/numpy/pull/23846

I think it might late to add it in doc. Posting it here as well: 

```
Faster ``np.argsort`` on AVX-512 enabled processors
---------------------------------------------------
32-bit and 64-bit quicksort algorithm for np.argsort gain up to 6x speed up on
processors that support AVX-512 instruction set.

Thanks to `Intel corporation <https://open.intel.com/>`_ for sponsoring this
work.
```

**Comment by charris** [comment]
> I think it might late to add it in doc

Don't worry, I'll just add it to the notes before the final release. After the release the notes are forward ported, so don't add it anywhere else.

**Pull request merged**
