### PR TITLE
DOC: Bump pydata-sphinx-theme version

### LINKED ISSUE #26058: DOC: Inaccessible contrast for a:visited links in admonitions
### Issue with current documentation:

1. Visit https://numpy.org/neps/nep-0029-deprecation_policy.html
2. If you've not visited the link "SPEC 0 — Minimum Supported Versions" before, it looks like:

image

3. Click the link "SPEC 0 — Minimum Supported Versions"
4. Return to https://numpy.org/neps/nep-0029-deprecation_policy.html
5. It looks like:

image

The contrast of purple on the dark background is low: it's ratio is 1.51, below the WCAG AA level of 4.5:

image

This comes from [`basic.css`](https://numpy.org/neps/_static/basic.css), which I think is from Sphinx:

```css
a:visited {
    color: #551A8B;
}
```

If I disable the rule, it looks like this, with a good ratio of 5.37:

image

The docs use PyData Sphinx Theme 0.13.3, but I can't reproduce the problem with these links (and inspecting the elements to edit in a link):

* https://pydata-sphinx-theme.readthedocs.io/en/v0.13.3/examples/kitchen-sink/admonitions.html
* https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/kitchen-sink/admonitions.html (0.15.2)

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #26058.

Fixes inaccessible contrast for `a:visited` links in admonitions. 

Note: I didn't manage to build everything locally to test this out, does the CI generate a preview build?

### CODE REVIEW

**Comment by mattip** [comment]
I think [these warnings](https://app.circleci.com/pipelines/github/numpy/numpy/25783/workflows/5569aa1c-099f-46c4-aaee-27534cf4a60d/jobs/39104?invite=true#step-108-15605_27) are failing the build
```
WARNING: the pydata_sphinx_theme extension is not safe for parallel writing
WARNING: doing serial write
```

Perhaps the `-j` will have to be removed to get a docs build https://github.com/numpy/numpy/blob/5edf018a070f0677ac8818c40d55c58b26a61ee4/.circleci/config.yml#L77

**Comment by hugovk** [comment]
Thanks, updated!

**Comment by mattip** [comment]
[here](https://output.circle-artifacts.com/output/job/432ecc92-3169-4877-bffe-46230dddd690/artifacts/0/doc/build/html/reference/generated/numpy.empty.html#numpy.empty) is an example API page. Generally it seems quite nice. I find the orange of the "See also" header a bit jarring. Do we need to remove some of our [CSS styling](https://github.com/numpy/numpy/blob/main/doc/source/_static/numpy.css)?

**Comment by hugovk** [comment]
Yes, that contrast needs fixing:

image

image


If we disable the `:before` CSS from that file:

```css
.admonition-legacy.admonition>.admonition-title::before,
div.admonition>.admonition-title::before {
  color: var(--pst-color-warning);
  content: var(--pst-icon-admonition-attention);
  background-color: var(--pst-color-warning);
}
```

We get:

image


image

This CSS was added by @melissawm in https://github.com/numpy/numpy/pull/24939. 

Melissa: is right thing to do, is delete `div.admonition>.admonition-title::before` and `div.admonition>.admonition-title::after` from that CSS and keep the `.admonition-legacy` bits?

**Comment by melissawm** [comment]
@hugovk it looks like there's a bit of extra customization that is still causing some misalignment of items and truncation (see for example the top navbar and cards at the landing page: https://output.circle-artifacts.com/output/job/e09e4603-3ea6-4dc9-be1a-42c27782dbcd/artifacts/0/doc/build/html/index.html?pr=26125)

I'm not sure if that's from existing NumPy customization or from new PyData theme settings.

**Comment by hugovk** [comment]
Hmm, not sure where to look for that. I did notice the some of the header elements have `col-lg-3` and `col-lg-9` classes, which are not used for https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html, removing those helps a bit, but I don't think that's the root issue.

https://numpy.org/doc/stable/ has a search box in the left column, not in the header like the [PR preview](https://output.circle-artifacts.com/output/job/e09e4603-3ea6-4dc9-be1a-42c27782dbcd/artifacts/0/doc/build/html/index.html?pr=26125), and the version selector is wider ("Choose version" vs. "1.26"). Deleting the `col-lg-` classes and search box makes the header "fit" like before...

Looks like this is a bigger job than just bumping a version and deleting some old CSS :) It might be better for someone else to continue this PR.

**Comment by melissawm** [comment]
I can do that - thanks for getting it started! We can keep this one open and I'll push to it so you are still a co-author. Does that work for you? Thanks ❤️

**Comment by hugovk** [comment]
Certainly! I'm not worried about co-author, feel free to push to this, close and create a new one, use or ditch my commits, or whatever is best for you. Thank you!

**Comment by melissawm** [comment]
Hi folks - just updated this, and included some cleanup for the CSS files. There are If this is too much I'll understand and break it into another PR, but I figure since I needed to touch the CSS file anyway...

Here's a summary of the major changes:
- Landing page https://numpy.org/devdocs/index.html
- Some colors and style for the API documentation. Example: https://numpy.org/devdocs/reference/generated/numpy.bitwise_invert.html#numpy-bitwise-invert
- Admonition colors now inherit directly from the PyData Sphinx Theme. Example: https://numpy.org/devdocs/building/index.html
- See also the Absolute Beginners guide which show some of the style changes https://numpy.org/devdocs/user/absolute_beginners.html
- Similar to https://github.com/scipy/scipy/pull/20460, I'm using as much of the PyData Sphinx Theme predefined colors as possible. This means some of the NumPy colors are absent from this version. Again, if that's too aggressive I'm happy to walk those back.

Related: #25927

I will add links to the preview of the pages mentioned above as soon as CI finishes building.

**Comment by mattip** [comment]
Commit eb4c33d7cee1a removed an unrelated file, was that on purpose?

**Comment by mattip** [comment]
Looks much better. The version switcher is bright red on my browser. Is that the desired color?

**Comment by melissawm** [comment]
@mattip the version switcher is red when it displays "choose version". It should be orange on devdocs and red on older versions. On stable it has the regular background color. This is the same approach I took for scipy, but maybe the red is too much?

**Comment by mattip** [comment]
> This is the same approach I took for scipy

Then it should be fine. Let's get this in, we can always do more later.

**Comment by mattip** [comment]
Thanks @hugovk, @melissawm

**Comment by hugovk** [comment]
Thank you @melissawm!

**Comment by bmwoodruff** [comment]
Figured I'd add what I found to the conversation.  I've been building numpy on codespaces multiple times today.  Twice I've been able to build the docs without any errors. Every other time I've build the docs I've encountered the exact same warning messages with an error at the last stage of the doc build. 

```
WARNING: the pydata_sphinx_theme extension is not safe for parallel writing
WARNING: doing serial write
```

I've set up 7 different codespace environments today. My best guess is that I when I build the docs from the main branch, I have no issues.  When I build the docs from another branch, I get the warning messages.  

To build the docs with codespaces, I'm using the following 5 commands. 

```
conda activate numpy-dev
pip install -r requirements/build_requirements.txt
spin build
pip install --pre --force-reinstall --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple -r requirements/doc_requirements.txt
spin docs
```

**Comment by melissawm** [comment]
Hi @bmwoodruff - the parallel safety warning is a known issue with the PyData Sphinx theme and something that will be fixed upstream. It should not impact the documentation build. Are you able to build despite the warning?

**Comment by bmwoodruff** [comment]
Hi @melissawm , the docs build and are viewable, but the ending message suggests otherwise. 
```
build finished with problems, 2 warnings.
make: *** [Makefile:144: html-build] Error 1
make: Leaving directory '/workspaces/numpy/doc'
```
I tried running the docs with `SPHINXOPTS="" spin docs`, following
https://github.com/numpy/numpy/blob/35c4f376f22561cbc3d6187614aedbd9bdccae6a/.spin/cmds.py#L145
I still encounter the `make` error. Since the docs still build and things are viewable, I've ignored the error message for now. Mostly it's a bit confusing for a newbie. This was the only reference to this warning on the numpy site, so I figured I'd add a comment. I did find your conversations on scipy, and the linked discussion on pydata, all related to the same issue.

**Pull request merged**
