### PR TITLE
API: C-API removals

### PR DESCRIPTION
**Pull request by seberg**
These removes some functions from the C-API that seemed rather uncontroversial to me.  Many are undocumented, some just felt a bit odd without any real use-case.

From the release note as an overview:
* `PyArrayFlags_Type` and `PyArray_NewFlagsObject` as well as
  `PyArrayFlagsObject` are private now.
  There is no known use-case, use the Python API if needed.
* `PyArray_MoveInto`, `PyArray_CastTo`, `PyArray_CastAnyTo` are removed
  use `PyArray_CopyInto` and if absolutely needed `PyArray_CopyAnyInto`
  (the latter does a flat copy).
* `PyArray_FillObjectArray` is removed, its only true use is for
  implementing ``np.empty``.  Create a new empty array or use
  `PyArray_FillWithScalar()` (decrefs existing objects).
* `PyArray_CompareUCS4` and `PyArray_CompareString` are removed.
  Use the standard C string comparison functions.
* `PyArray_ISPYTHON` is removed as it is misleading, has no known
  use-cases and easy to replace.
* `PyArray_FieldNames` is removed as it is unclear what it would
  be useful for.  It also has incorrect semantics in some possible
  use-cases.
* `PyArray_TypestrConvert` since it seems a misnomer and unlikely
  to be used by anyone.  If you know the size or are limited to
  few types, just use it explicitly, otherwise go via Python
  strings.

I skipped removing `PyArray_CopyAnyInto`, it is a raveling copy and that seems dubious to me, but OK.  Having 3 aliases around felt unnecessary, though.

The trickiest part is that I used the `Cast*` slots for the new Copy as the functions are fully equivalent and it seemed nice in that corner of the table.

`PyArray_FillObjectArray` is also renamed and reduced to only filling with `None`.  It should be replaced, as the concept is quite problematic.  I don't see it being used, otherwise the solution would be to tag on a big warning...

`FieldNames` is odd, because while we use the same logic in construction, I don't see users doing that.  But if you use it to get the names, it reorders them, but name order is important, so that seems misleading.

---

Should be rather straight forward, if someone feels strongly about being able to compile partial commits, squash them, as I only updated the C version at the end.

### CODE REVIEW

**Comment by mattip** [comment]
Doc building is failing. There is a warning about missing files, but I don't think that is the cause:
```
WARNING: Path to light image logo does not exist: numpylogo.svgumpy.asarray_chkfinite
WARNING: Path to dark image logo does not exist: numpylogo_dark.svg
```

I couldn't rerun only the circleci CI.

**Comment by seberg** [comment]
Yeah, no idea... just closing/reopening to see if that helps.

**Comment by seberg** [comment]
Still beats, me... @tupui maybe a long shot, but do you happen to know if this is known from pydata-sphinx-theme or so?!  I don't see why this PR should include anything causing the build to trip building.  The error is:
```
updating environment: [new config] 2587 added, 0 changed, 0 removed
WARNING: Path to light image logo does not exist: numpylogo.svgumpy.asarray_chkfinite
```
(Which is clearly a malformed path, but one that seems unrelated to anything here.)

`array_chkfinite` is just the first function docs/html we build, I believe.  I don't understand why none of the other PRs seem to fail.  Could there be some caching that means they simply don't rebuild or are getting other dependencies, or is there some odd cause here?

**Comment by ngoldbaum** [comment]
Docs seem to build fine with this PR checked out on an M3 Mac running Mac OS Sonoma.

**Comment by rgommers** [comment]
That all seems very reasonable. The only one of these that is used in SciPy is `PyArrayFlags_Type` (once):

https://github.com/scipy/scipy/blob/fa9f13e6906e7d00510d593f7f982db30e4e4f14/scipy/sparse/linalg/_dsolve/_superlumodule.c#L352-L355

I can't say that it's immediately obvious to me what is going on there.

**Comment by seberg** [comment]
Well, let's see if rebasing magically fixes the doc build issue...  I have not really tried to dig deeper into it after Melissa had a look.

**Comment by seberg** [comment]
Are we just being stupid?  We have `scipy.linalg` imports in NumPy.  And those do that nonsense `INCREF` that Ralf found.  That is bound to segfault.

We change API to break ABI, and in the rare case where it actually matters, our doc builds are bound to be broken until downstream is recompiled.

**Comment by mattip** [comment]
> Are we just being stupid?

Probably :)

**Comment by seberg** [comment]
Let's see if https://github.com/scipy/scipy/pull/19656 is merged quickly.  But I think I am willing to gamble and live with a briefly broken doc build until new downstream nightlies are uploaded.

**Comment by seberg** [comment]
OK, scipy update is through and sufficient to make the docs build pass here.

**Comment by seberg** [comment]
Btw. I think this one is ready to go in now.

**Comment by mattip** [comment]
Thanks @seberg

**Comment by jakevdp** [comment]
Hi - the `ml_dtypes` package uses `PyArray_TypeNumFromName` here: https://github.com/jax-ml/ml_dtypes/blob/6f7b695c95004c9b9b1d070918a5091920624e0c/ml_dtypes/_src/custom_float.h#L873-L882 Hopefully the long comment gives enough context – can you suggest an alternative API to use for this case?

**Comment by jakevdp** [comment]
It might be that our best option is to simply remove the highlighted code block, as the TODO there has been satisfied by the creation of the `ml_dtypes` package.

**Comment by seberg** [comment]
I thought you can just grab it from Python via `PyArray_DescrConverter(unicode_string("name"))` or similar.  If we support names for this, it seems like they need to work for Python also, and not be its own mechanism?

**Comment by jakevdp** [comment]
Thanks @seberg - I'll give that a try.

**Pull request merged**
