### PR TITLE
Change mode of open in func write_file()

### PR DESCRIPTION
**Pull request by jakobjakobson13**
See  #17012 item 1

### CODE REVIEW

**Comment by eric-wieser** [comment]
This looks wrong to me - `data` is unicode.

**Comment by jakobjakobson13** [comment]
> This looks wrong to me - `data` is unicode.

Okay, I'll close it then.

**Comment by eric-wieser** [comment]
Ci seems to agree with me.

In principle, we could use `open(..., "w", encoding="utf8")`, but I think:
* We'd need to do that everywhere
* This is likely to cause trouble on systems which do not use utf8 encoding by default

**Comment by jakobjakobson13** [comment]
Okay.

**Pull request closed without merging**
