### PR TITLE
TST: refine Azure fail reports

### LINKED ISSUE #13452: Azure config silently passes build issues and crashes
Follow-up to gh-13448. Summary of the issue by @tylerjereddy there:

"""
We only hard fail Azure CI entries when there are test failures, which means that test results have to be produced to record the failure in the next step of test publication.

But build failures are ignored when build + test are smushed into one Azure stage.

This is the tradeoff we implicitly accepted by allowing test results to be published even when the build / test stage fails.

I see PyPy3 was failing in that PR before merge too, for a different reason as well. I believe the longer-term solution is to separate the build and test stages to separate steps, and enforce a hard fail on build errors, but catch test failures only in the publication stage.

For the 32-bit job this is a little tricky because a docker container is used to do both build & test, but there should be a neat way around that with some thought / mounting of the build results.

Matti can perhaps comment on the PyPy3 job, but it should almost certainly be expanded in this way & same for all other azure jobs with fused build + test stages (also kind of makes runtests.py a little less useful).
"""

The Azure config issue isn't solved. I agree with Matti's comments on that issue, we should make Azure behave like all other CI. Build failures, segfaults, etc. should all result in a little red cross so the reviewer actually goes and has a look.

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #13452

~I've set this as a draft PR since there's an intentional bug to demonstrate the CI mechanics discussed.~

Reviewers should feel free to test other failure scenarios, or even better on their own forks.

Pertinent docs:
- [specifying conditions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
- [task control options](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-control-options)
- [publish test results task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Looks like the behavior we were looking for based on the current results.

**Review by eric-wieser — APPROVED** [review]
This looks good to me, nice job (other than the obvious deliberate failure

**Comment by tylerjereddy** [comment]
Ok, purged the intentional bug & lifted draft status.

**Comment by tylerjereddy** [comment]
matmul heisenbug showing up again

**Comment by charris** [comment]
Thanks Tyler.

**Pull request merged**
