### PR TITLE
BUG: Fix passing a MaskedArray instance to ``MaskedArray.__setitem__``

### LINKED ISSUE #19721: REG: inconsistency in masked arrays with boolean array addressing
Initial discovery: https://github.com/yt-project/yt/issues/3472
Later reported and discussed as https://github.com/matplotlib/matplotlib/issues/20843
Many thanks to @jklymak for contributing a pure-numpy test in comments. This report was edited to feature a slightly modified version of his test instead of the original example which included matplotlib code and was much harder to decipher.

### Reproducing code example:

```python
import numpy as np

a = np.ma.masked_array([0, 1], mask=[False, False])
b = np.ma.masked_array([0, 1], mask=[True, True])
mask = a < 1
b[mask] = a[mask]
expected_mask = [False, True]
np.testing.assert_array_equal(b.mask, expected_mask)
```

### Error message:
<details>
<summary>Traceback</summary>

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/robcleme/dev/yt-project/yt-py310/numpy/t.py:8 in <module>                                 │
│                                                                                                  │
│   5 mask = a < 1                                                                                 │
│   6 b[mask] = a[mask]                                                                            │
│   7 expected_mask = [False, True]                                                                │
│ ❱ 8 np.testing.assert_array_equal(b.mask, expected_mask)                                         │
│   9                                                                                              │
│                                                                                                  │
│ /Users/robcleme/dev/yt-project/yt-py310/numpy/numpy/testing/_private/utils.py:934 in             │
│ assert_array_equal                                                                               │
│                                                                                                  │
│    931 │                                                                                         │
│    932 │   """                                                                                   │
│    933 │   __tracebackhide__ = True  # Hide traceback for py.test                                │
│ ❱  934 │   assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,                          │
│    935 │   │   │   │   │   │    verbose=verbose, header='Arrays are not equal')                  │
│    936                                                                                           │
│    937                                                                                           │
│                                                                                                  │
│ /Users/robcleme/dev/yt-project/yt-py310/numpy/numpy/testing/_private/utils.py:844 in             │
│ assert_array_compare                                                                             │
│                                                                                                  │
│    841 │   │   │   msg = build_err_msg([ox, oy], err_msg,                                        │
│    842 │   │   │   │   │   │   │   │   verbose=verbose, header=header,                           │
│    843 │   │   │   │   │   │   │   │   names=('x', 'y'), precision=precision)                    │
│ ❱  844 │   │   │   raise AssertionError(msg)                                                     │
│    845 │   except ValueError:                                                                    │
│    846 │   │   import traceback                                                                  │
│    847 │   │   efmt = traceback.format_exc()                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError:
Arrays are not equal

Mismatched elements: 1 / 2 (50%)
 x: array([ True,  True])
 y: array([False,  True])
```
</details>

### NumPy/Python version information:

The error is raised with the current dev versions of numpy and bisects down to 2504230 (#19244)
I used Python 3.10b2

### PR DESCRIPTION
**Pull request by neutrinoceros**
Fixes #19721
I'm not really satisfied with the approach (nested `isinstance`) *but* it turns out that this seems to work without breaking other related tests.
I'll take any advice on how to improve over this if required.

### CODE REVIEW

**Comment by mattip** [comment]
PR #19740 is similar but takes a slightly different approach

**Comment by neutrinoceros** [comment]
Yup, #19740 actually slightly more elegant. If @imaeskild agrees, I can update this accordingly. Aas I said on the ticket I was hoping to finally contribute to numpy given how long it took me to track this down.

**Comment by iameskild** [comment]
@neutrinoceros @mattip I apologize for all the confusion. I didn't see this PR before I created #19740. I'm happy to close that one if this PR get merged 👍

**Comment by neutrinoceros** [comment]
Excellent, thank you. If you want to make a suggestion here I'll happily share authorship with you for the fix :)

**Comment by mattip** [comment]
@neutrinoceros I think a path forward might be to cherry-pick @iameskild 's commits on top of this, so something like
```
$ git fetch origin pull/19740/head:fix_19721
$ git cherry-pick 835880a16e
$ git cherry-pick 0fc08dbf4eb
$ git cherry-pick 1eefb679e9c
```

and then you can remove your check since it is redundant. So what would remain would be 
- your test
- @iameskild 's code fix

**Comment by neutrinoceros** [comment]
Thanks @mattip, just did.I took the liberty to collapse @iameskild's three commit into a single one while I was rebasing, hope that's ok. Now my commit message is a bit misleading since my own commit only includes a tests (not the fix).

**Comment by mattip** [comment]
Thanks @neutrinoceros and @iameskild

**Comment by neutrinoceros** [comment]
Thank you guys !

**Pull request merged**
