### PR TITLE
BUG: pull request 9087 modifies a tuple after use

### PR DESCRIPTION
**Pull request by mattip**
backported pull request #9195

### CODE REVIEW

**Comment by mattip** [comment]
my first backport, hope it is OK

**Comment by mhvk** [comment]
@charris - could you check? I think it is OK, but I'm still a bit unsure about labels, including the commit title etc.

**Comment by charris** [comment]
Looks good, keeping the same title helps when generating the 1.13.0 changelog and the tags look good. I like the remove the candidate tag after the backport is done and add the milestone to allow searching for missing backports. As a general rule, it is OK to merge backports without review.

**Comment by charris** [comment]
Note that I am considering leaving the Backport-candidate tag alone if the milestone is set on both PRs. The procedure isn't quite settled yet.

**Pull request merged**
