### PR TITLE
BUG: delay calls of array repr in getlimits

### PR DESCRIPTION
**Pull request by matthew-brett**
Delay use of array repr until needed for string representations of the
float info parameters.  This is to allow getlimits to be imported early
without pulling in too much of the repr machinery.

See: https://github.com/numpy/numpy/pull/8983#discussion_r115838683

### CODE REVIEW

**Comment by ahaldane** [comment]
Yep, this fixes the circular import problem from #8983.

I was just reading this code myself to see how to fix it. My thought was to delay creation of `_KNOWN_TYPES` by defining
```python
_KNOWN_TYPES = None
def _get_known_types():
    global _KNOWN_TYPES

    if _KNOWN_TYPES is not None:
        return _KNOWN_TYPES

    ... (indented definition of _KNOWN_TYPES goes here ...
```
but I haven't properly thought through all the performance implications that you probably know about.

This PR looks good to me, let's just wait for tests to pass.

**Comment by ahaldane** [comment]
The `__main__` clause doesn't seem to work:

```
python2 ./getlimits.py 
Traceback (most recent call last):
  File "./getlimits.py", line 10, in <module>
    from .machar import MachAr
ValueError: Attempted relative import in non-package
```

(the other files in this directory which have such a clause work properly).

**Comment by charris** [comment]
> The __main__ clause doesn't seem to work:

Should be removed. Scripts cannot use `absolute_imports` as they do not run in the right context. That clause dates back to 2006 and was probably used for debugging.

**Comment by charris** [comment]
Thanks Matthew. I expect we can do more in this regard, but this is a good start and fixes the immediate problem.

**Comment by ahaldane** [comment]
Thanks for moving this one forward @charris, and thanks for the fix @matthew-brett

**Pull request merged**
