### PR TITLE
ENH: add quantile support for datetime64

### LINKED ISSUE #11620: percentile don't support datetime64
```python
dates = np.array([[np.datetime64('2018'), np.datetime64('2019')]], dtype='M8[ns]')
np.percentile(dates, 50)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/usr/local/miniconda3/envs/pandas/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4291, in percentile
#     interpolation=interpolation)
#   File "/usr/local/miniconda3/envs/pandas/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4033, in _ureduce
#     r = func(a, **kwargs)
#   File "/usr/local/miniconda3/envs/pandas/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4405, in _percentile
#     x1 = take(ap, indices_below, axis=axis) * weights_below
# TypeError: ufunc multiply cannot use operands with types dtype('<M8[ns]') and dtype('float64')

# a workaround
np.percentile(dates.view('i8'), 50).astype('M8[ns]')
# numpy.datetime64('2018-07-02T12:00:00.000000000')

np.version.version
# '1.14.5'
```

### PR DESCRIPTION
**Pull request by holymonson**
@eric-wieser, Is this OK? No explicit rounding.

close #11620

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
It might be helpful to add some tests to this potential contribution as well--I see that you've started discussing input and expected output with Eric in the linked issue so that might be a starting point.

**Comment by holymonson** [comment]
@tylerjereddy, testcase added. Travis CI reports false fail, please rebuild.

**Comment by tylerjereddy** [comment]
Ok, I restarted the failing Python 3.7 job in Travis

**Comment by shoyer** [comment]
A couple of thoughts:
- Consider casting to `timedelta64` directly (e.g., `dates.view('timedelta64')`) instead of adding/subtracting an offset. This should be equivalent but more efficient.
- Please add tests to make sure that NaT is handled properly (like NaN).

**Comment by seberg** [comment]
This is currently supported.  However, I do not think we have any tests, so it would be great to recover (and maybe add to those).  It may be tested downstream but I am not certain.

There is also the question of rounding that was brought up here, I am not immediately sure if this is a problem with our linear interpolation formula and datetime/timedelta inputs;  it might be nice to vet it.

The handling of NaT is still broken, I suspect the fix should be closer to what we do for `NaN`s   gh-20376 open about this.

**Pull request closed without merging**
