### PR TITLE
allow axis to be a list in np.mean

### PR DESCRIPTION
**Pull request by boeddeker**
```python
np.median([[1]], axis=[1])  # Work
np.mean([[1]], axis=[1])  # This PR
np.sum([[1]], axis=[1])  # Brocken
```

### CODE REVIEW

**Comment by boeddeker** [comment]
Sorry, this PR only changes the Exception.
The function `numpy.core.umath.add.reduce` raises a `TypeError: 'list' object cannot be interpreted as an integer`, but I can not find the cause of the Exception, why it accepts tuple but not list. 

Does anyone know if it is possible to change `numpy.core.umath.add.reduce` to accept lists?

**Comment by jaimefrio** [comment]
I think raising on non-tuples is a conscious design decision, which means we really don't want this change in behavior. Maybe @seberg can confirm it?

**Comment by charris** [comment]
@jaimefrio That was my recollection also. That means we probably want to fix  median :)

**Comment by seberg** [comment]
Yeah, `PyArray_ConvertMultiAxis` only allows tuples, I was not completely sure about the ufunc machinery (it divergers sometimes), but since `np.sum` also prefers tuples, I agree. Median is the oddball here and there is no big reason why not to force tuple IMO. @boeddeker since maybe you are wondering, one advantage of only allowing tuple is that it less annoying to test for.
I have to admit though, in quite a few places we probably also first try to convert to integer and then just try to convert to tuple/iterate.

**Comment by seberg** [comment]
The `normalize_axis_tuple` in python goes this way (try `operator.index` and then convert to tuple. Frankly, I do not care too much either way, but overall it seems fine to force tuples for this, feels more natural anyway.

**Comment by boeddeker** [comment]
Ah, ok. 
I changed the reduction in my code from median to mean and was irritated that is breaks.
When this is the intended behavior, this issue can be closed.

Isn't it better to have a consistent behavior (i.e. test many reduction operations to behave the same way for lists)? 
Or is this decision related to execution time?
I personally prefare to allow tuple and list, as long there is no reason to exclude mutable types.

A simple example where it is common to use list is when a list comprehention is involved (e.g. drop some axis):
```python
np.sum(A, axis=[a for a in range(A.ndim) if a != 0])
```

**Comment by seberg** [comment]
The C-code which, was there first and is used more, explicitly wants tuples. It is a bit far fetched to say there is a very big reason maybe.
In many cases it is important (for example in indexing `[1]` and `1` have a different meaning. And if such things happen, it is too easy to get into seriously trouble if you coerce freely.

Here, it is not such a big deal, because a single integer and a length one sequence have the same meaning always. However, I still lean towards being strickt:
 1. There is simply no real downside, except the tiny downside that there are some exceptions that allow more. (i.e. you changed the code, if you wrote it the first time you would not care)
 2. I wouldn't want to rule out that things like a pandas DataFrame with a single integer in it could not mean something very different to some downstream project then a single integer.

We try to be strict for most things nowadays (no floats instead of integers, no lists for tuples in indexing, etc.), because it makes possible issues immediately obvious instead of setting up traps for the future.
Right now I do not think the potential for failure is huge here, but being a bit more strict also does not seem to hurt.

**Comment by seberg** [comment]
Is: `np.sum(A, axis=tuple(a for a in range(A.ndim) if a != 0))` really so much worse? :)

**Pull request closed without merging**
