### PR TITLE
pyproject.toml: Upgrade setuptools for Python 3.12 beta 1

### PR DESCRIPTION
**Pull request by cclauss**
Related to #23808

https://www.python.org/download/pre-releases
https://docs.python.org/3.12/whatsnew/3.12.html

### CODE REVIEW

**Comment by mattip** [comment]
We deliberately pin setuptools to work around other problems with `numpy.distutils`. The plan for python 3.12 is to move to the meson build system, and to deprecate use of setuptools. You can try out the meson build using `python3.12 -m pip install -r build_requirements.txt; python3.12 -m spin build`.

**Comment by cclauss** [comment]
Remarkably, with this one change, I am able to successfully:
`python3.12 -m pip install Cython git+https://github.com/cclauss/numpy.git@patch-1`

**Comment by mattip** [comment]
Can you run tests?

**Comment by cclauss** [comment]
> 55 successful, 2 skipped, 3 failing checks

### Build_Test / intel_spr_sde_test (pull_request) Failing after 37s
`RuntimeError: Unrecognized setuptools command: ['editable_wheel', '--dist-dir', '/tmp/pip-wheel-11ogh7zp/.tmp-yehi2l_w']`
Perhaps this is caused by `editable_wheel` being considered _private_ in current versions of `setuptools`.
* https://setuptools.pypa.io/en/stable/history.html

### azure-pipeline numpy.numpy
### azure-pipeline numpy.numpy (ComprehensiveTests Windows Python39-32bit-full)

**Comment by cclauss** [comment]
@EwoutH Perhaps you have a clearer vision about how to do this.

**Comment by rgommers** [comment]
Until gh-23838 is merged, you can either use the branch from which I made that PR, or follow the instructions at https://github.com/numpy/numpy/blob/main/building_with_meson.md#pip-install.

**Comment by rgommers** [comment]
Also note that 3.12.0b1 has a bug that may cause a crash in numpy, and is fixed in CPython's main branch (see gh-23766).

**Pull request closed without merging**
