### PR TITLE
MAINT: Change the order of checking for locale file and import urllib modules

### PR DESCRIPTION
**Pull request by EelcoPeacs**
ENH: Changed the sequence of checking for locale existence of a file and importing urllib modules in numpy._datasource.py to prevent the import in case the local file was found

See #12536

### CODE REVIEW

**Comment by charris** [comment]
LGTM. Did this actually fix your problem? Why was the _socket object/module missing?

**Comment by charris** [comment]
Thanks @EelcoPeacs .

**Comment by charris** [comment]
I notice that your commit message is badly formed. All lines in the message should be < 72 characters in length and separated by line breaks, with a blank line after the summary line at the top. There should be a plugin for your editor that does that for you.

**Comment by EelcoPeacs** [comment]
Thanks for the merge. Yes, this fix solved my problem and is also a minor improvement on the sequence of the code for checking file existence. I encountered the problem in a program that incorporates a dedicated build of Python, Seg3D. This special build does not incorporate all libraries.
Sorry for the badly formed commit. I'll improve this next time.

**Pull request merged**
